### ISSUE TITLE
Introduce Type `ConfigurationScope`

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10004]
### Feature Description:
Add the `ConfigurationScope` type and use it in `vscode.workspace.getConfiguration(...)` and `ConfigurationChangedEvent#affectsConfiguration()`.

**Comment by colin-grant-work** [comment]
I'll take this one, and improve our `affectsConfiguration` implementation, as well.

**Comment by JonasHelming** [comment]
@colin-grant-work Is this still on your radar?

**Comment by colin-grant-work** [comment]
@JonasHelming, it is fixed by #11393, which is just waiting on reviews.
