### ISSUE TITLE
core: fix typo for `ApplicationShell` method

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10007]
#### Bug Description:

There is a typo in the method present under `ApplicationShell`:

https://github.com/eclipse-theia/theia/blob/7442150b335a9280a314dbf30f6a9227305b6b04/packages/core/src/browser/shell/application-shell.ts#L296-L299

`setTopPanelVisibily` should be renamed to `setTopPanelVisibility`

As part of the changes we should also add an entry in the [changelog](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md) for breaking changes.

**Comment by 5hraddha** [comment]
Hi @vince-fugnitto , I would like to take this issue up. Could you please assign it to me?
