### ISSUE TITLE
Add `DebugConfigurationProviderTriggerKind` 

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10008]
### Feature Description:
Add the enum `DebugConfigurationProviderTriggerKind` and dynamically fetch debug configs when appropriate.

https://code.visualstudio.com/api/references/vscode-api#DebugConfigurationProviderTriggerKind

**Comment by alvsan09** [comment]
I think this is already covered under PR: #10134

**Comment by tsmaeder** [comment]
@alvsan09 cool, thanks for catching that.
