### ISSUE TITLE
ThemeIcons used by vscode extensions do not load correctly

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#10010]
### Bug Description:

See title. I assume this regression was introduced by #9436 as the `instanceof` check fails here:

https://github.com/eclipse-theia/theia/blob/7442150b335a9280a314dbf30f6a9227305b6b04/packages/plugin-ext/src/plugin/tree/tree-views.ts#L372

### Steps to Reproduce:

1. Install the npm extension (built-in)
2. Open the npm view
3. Notice the missing icon

### Additional Information

- Operating System: Ubuntu (Gitpod)
- Theia Version: `a7d63a0`

**Comment by tsmaeder** [comment]
Just for my understanding: why is the instanceof failing?

**Comment by msujew** [comment]
@tsmaeder As far as I understand the different ES versions, ES5 classes work quite differently from classes in newer ES versions. That's why the `@es5Compatibility` annotation is needed, so that extensions compiled with es5 can still use them without issues. That however introduces a problem related to the TypeScript compiler which tries to emit newer ES2017 `instanceof` calls for classes compiled to ES5, which just don't work. The prototype chain seems to be completely different, as `Object.getProtoTypeOf(iconPath) === ThemeIcon.prototype` returns false as well, even when the debugger shows the prototype of `iconPath` to be `ThemeIcon`.
