### ISSUE TITLE
Add `DebugProtocolSource` and `DebugProtocolBreakpoint`

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10011]
### Feature Description:
Provide access to the debug protocol objects of the same name. A plugin would have to downcast to the debug protocol types in order to use:

https://code.visualstudio.com/api/references/vscode-api#DebugProtocolBreakpoint
https://code.visualstudio.com/api/references/vscode-api#DebugProtocolSource

**Comment by JonasHelming** [comment]
We are working on this
