### ISSUE TITLE
Introduce `DebugSession#workspaceFolder`

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10023]
### Feature Description:
Introduce `DebugSession#workspaceFolder` 
See https://code.visualstudio.com/api/references/vscode-api#DebugSession

The workspace folder should be taken into account when running pre-launch/debug tasks, for example, but also in labels where it makes sense. Digging through the source code VS Code might be necessary to identify usages.

**Comment by jfaltermeier** [comment]
I will start having a look at this issue
