### ISSUE TITLE
Support `InlineValue` feature

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10028]
### Feature Description:
Support plugins contributing `InlineValue` objects to the debugger editor, see https://code.visualstudio.com/api/references/vscode-api#InlineValuesProvider

`debug-editor-model.ts` already has support for inline value decorations, but we would have to call the plugin API to add to or replace the one's we're currently showing.

Depends partially on #10027

**Comment by ndoschek** [comment]
Awaits uplift of monaco to add the necessary types in the `monaco.languages` namespace.
Please see PR: https://github.com/theia-ide/vscode/pull/1

**Comment by vince-fugnitto** [comment]
@ndoschek do you have any updates on the issue?

**Comment by ndoschek** [comment]
Hi @vince-fugnitto, yes I started with that already but ran out of time unfortunately, but I plan to finish it this month.
