### ISSUE TITLE
WebView Extensions fails to load their links 

### ISSUE THREAD

**Issue by ChayaLau** [eclipse-theia/theia#10036]
### Steps to Reproduce:

1. add WebView extension to theia plugins, i used webview-sample of vscode extensions samples.
2.  press the F1 key and click cat coding : start coding session.
3. the cat coding web view should appear and show its content
4. expected results : the webview should react and increase the number displayed
actual results : nothing changes the content

### Additional Information
the extension script fails to load and there is error in the console for each link in the extension that was supposed to be linked :
`Failed to load resource: the server responded with a status of 404 ()`

- Operating System: windows
- Theia Version: 16

**Comment by msujew** [comment]
Hi @ChayaLau, have you tried reproducing this with Theia 1.17? I can't reproduce it using the current `master`.

**Comment by ChayaLau** [comment]
@msujew  - thanks for testing,  i tried again, now with master but i still get the same errors and behavior, how did you add the plugin? copied the folder after npm run compile to plugin folder?
![image](https://user-images.githubusercontent.com/87074645/131729585-9e45bb5d-7cb5-4a26-9343-aaab2004db8d.png)

**Comment by ChayaLau** [comment]
@msujew - in which OS did you test it?

**Comment by msujew** [comment]
I used Gitpod (Ubuntu) to provide the backend.

I installed the extension using the `Install from VSIX` command.

**Comment by colin-grant-work** [comment]
It's possible that this is related to the problems observed here:
https://github.com/eclipse-theia/theia/pull/9464

In that case, your colleague reported a similar bug that wasn't easily reproducible by others. Is there some chance that there's a peculiarity of your environment at SAP or custom code related to plugins that could be causing these problems?

**Comment by msujew** [comment]
Given the lack of reproducibility, I'll close this issue. If anyone experiences similar issues, please create a new issue and provide repro steps.
