### ISSUE TITLE
Add deprecated fields to `LanguageConfiguration`

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10031]
### Feature Description:
There are two deprecate fields `__electricCharacterSupport` and  `__characterPairSupport` in `LanguageConfiguration`. We should add the declarations for compatibility, but not an implementation.

https://code.visualstudio.com/api/references/vscode-api#LanguageConfiguration

**Comment by dineshUmasankar** [comment]
I would like to submit my attempt on this issue. I believe I would be adding these two fields into the interface defined as [LanguageConfiguration](https://github.com/eclipse-theia/theia/blob/068e78d34f88f274c9c7f9ddd64299fd7796589d/packages/plugin/src/theia.d.ts#L6267). In addition, I am not entirely sure how to test fields within an interface, and would appreciate some guidance regarding this.

**Comment by vince-fugnitto** [comment]
Closing thanks to #10050 👍
@dineshUmasankar in the future you can use the following [syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to automatically close issues when pull-requests are merged.
