### ISSUE TITLE
Missing plugin tree node context menu

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#10046]
### Bug Description:

Tree views contributed by plugins seem to be missing their context menu: See [original community thread here](https://community.theia-ide.org/t/vscode-plugin-sidebar-context-menu-not-display/1933) and this example image using the [`SSH Client`](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-ssh) extension:

![image](https://user-images.githubusercontent.com/4377073/131988833-05e6b39b-1d5c-4ce5-982e-1a6d6c2dd529.png)

### Steps to Reproduce:

1. Download the `SSH Client` extension
2. Connect to any ssh host
3. Observe the missing context menu on the tree node

### Additional Information

- Operating System: Ubuntu (Gitpod)
- Theia Version: 1.17.2

**Comment by emilhammarstedtst** [comment]
I think this is solved by https://github.com/emilhammarstedtst/theia/commit/04e2816dfe2e2e78077f84ba89b1abd7c37f8c0b and should be closed.

**Comment by msujew** [comment]
@emilhammarstedtst You're right, I'll close this.
