### ISSUE TITLE
`Enable Preview` not works  in `search in workspace result`

### ISSUE THREAD

**Issue by shuyaqian** [eclipse-theia/theia#10045]
### Steps to Reproduce:

1.  set 'Enable Preview' true in preferences
2. search in workspace
3. click tree item in search results
4. file will be opened but not preview

### Additional Information

- Operating System: linux
- Theia Version: 1.17.0

**Comment by shuyaqian** [comment]
I see that click in search results, file is opened directly in IntelliJ IDEA, but in vscode, file is previewed after setting `Enable Preview`.

**Comment by msujew** [comment]
@shuyaqian Thank you for reporting this issue. I can confirm that the issue is present using the latest `master`. Are you interested in contributing a fix?

**Comment by vince-fugnitto** [comment]
@shuyaqian it is a duplicate of https://github.com/eclipse-theia/theia/issues/7589.
