### ISSUE TITLE
[WiP] PR: implement a cors proxy into the vsx-registry module to support extension installation

### ISSUE THREAD

**Issue by frank-dspeed** [eclipse-theia/theia#10056]
### Feature Description:
implement a cors proxy into the vsx-registry module to support extension installation

#### Current behavior
Cors Blocking access to the open-vsx registry 

#### Solution
A Integrated Cors Proxy running on server side that supports cors access to the marketplace url

# Related issues
- https://github.com/open-pwa/theia/issues/1 => tacks the pr progrgess

**Comment by vince-fugnitto** [comment]
@frank-dspeed I believe the changes are no longer necessary, the **cors** issues were fixed upstream (open-vsx) and should now work properly in the browser.

**Comment by frank-dspeed** [comment]
@vince-fugnitto while your correct it turns out that there is a frontend call to a refresh method that trys to find the lastCompatibleExtension version via a post request this can get refactored to use a search request that serves much less data and is sufficent.

there is already a redundant method that can get the latest compatible version for a search entry so i want to reuse that and simply drop the need for the post request anyway.

**Comment by vince-fugnitto** [comment]
@frank-dspeed I'm not sure `search` is suitable to return us data on an extension we already have the `id` for, it is used to query the list of all extensions based on query params:

- https://open-vsx.org/swagger-ui/#/registry-api/searchUsingGET

I believe it might not even be supported at the moment: https://github.com/eclipse-theia/theia/issues/9480.

**Comment by frank-dspeed** [comment]
@vince-fugnitto i get valid results the code that i posted works in general at present and contains a check to verify the search result

```
        const [ namespace, name ] = id.split('.');
        
        if (entry && entry.namespace === namespace && entry.name === name) {
```

**Comment by vince-fugnitto** [comment]
@frank-dspeed unfortunately I believe it is ultimately a workaround to use `search` over the `query` api, and since cors is now properly handled upstream it is also no longer necessary? We also need to postprocess the result to confirm the `id` is correct which is also not ideal.

**Comment by frank-dspeed** [comment]
@vince-fugnitto your correct i should implement a extra namespace/name/allVersions endpoint that returns all versions via a get request it makes no sense to have a post request i try to do a PR on upstream
