### ISSUE TITLE
Menu is not shown when Electron on Linux is switched to full-screen mode

### ISSUE THREAD

**Issue by westbury** [eclipse-theia/theia#10077]
### Steps to Reproduce:

1. Run the desktop example on Linux
2. Press F11 to switch to full-screen
3. Note that the menu is missing

### Additional Information

- Operating System: Linux
- Theia Version: 1.17

For reference the PR that introduced the full-screen feature is https://github.com/eclipse-theia/theia/pull/9399

**Comment by vince-fugnitto** [comment]
@westbury I believe it is the same behavior as in vscode.
I believe the issue is that the menus are still hidden when `window.menuBarVisibility = visible` and we toggle full screen.

**Comment by vince-fugnitto** [comment]
The more appropriate pull-request would be https://github.com/eclipse-theia/theia/pull/9830.

**Comment by westbury** [comment]
> I believe it is the same behavior as in vscode

When using vscode, tapping the alt key shows the menu (I'm using Ubuntu 20.04).  In Theia this does not appear to work.

> The more appropriate pull-request would be #9830

Thanks for pointing out that PR, that was useful though it does not appear to affect this issue.
