### ISSUE TITLE
`QuickInputService.input()` does not respect `options`

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#10094]
### Bug Description:
Hi,
I the quickInputService.input() method with the options prompt, placeHolder and value, all is working fine in Theia 1.16, once I updated to the latest 1.17.2, the input does not work as expected (does not show the prompt, placeHolder, and value).
Note: I did the upgrade as mentioned in the migration guide.

### Steps to Reproduce:

1. try this code: 
2. let val = await this.quickInputService.input({
            prompt: "prompt msg",
            placeHolder: "a place holder",
            value: 'initial value'
        });
3. the input will show up, but will not show the properties in the options above

### Additional Information

- Operating System: Window 10
- Theia Version: 1.17.2

**Comment by vince-fugnitto** [comment]
It looks like the `options` are not being properly passed:

https://github.com/eclipse-theia/theia/blob/8df74a70d59136d15802ac6c55bdad0d9dc1b5f5/packages/monaco/src/browser/monaco-quick-input-service.ts#L184-L186
