### ISSUE TITLE
Cannot read 1 resources

### ISSUE THREAD

**Issue by DevTester425** [eclipse-theia/theia#10103]
### Bug Description:
When opening a folder, a notification appears: "Cannot read 1 resources:"

### Steps to Reproduce:
1. click menu item File->Open Folder...
2. select a folder
3. a notification appears
4. a new instance of the editor successfully opens at the specified path 

See the video

https://user-images.githubusercontent.com/88549983/133386585-9ad50f34-3104-4ced-9d1e-6537da3b5aa3.mp4

### Additional Information

- Operating System: Microsoft Windows 10, 64 bit
- @theia/example-electron: 1.17.0

**Comment by bayang** [comment]
Same issue here on linux with version 1.2.0, 
I choose open file with ctrl + o, pick the file in explorer, the file is displayed in editor but a notification appears

![Screenshot_20210917_105813](https://user-images.githubusercontent.com/11558944/133759801-71cc0437-a440-45b3-b841-a52c9f80d379.png)

I tried with a test folder containing only one text file that is rw, the notification still appears

```
ls -larth
total 12K
drwxr-xr-x 10 me me 4,0K 17 sept. 11:08 ..
drwxr-xr-x  2 me me 4,0K 17 sept. 11:08 .
-rw-r--r--  1 me me   24 17 sept. 11:08 test.txt
```
Also the path of the problematic files should be displayed in the notification as per the code sample posted above (the `${inaccessibleFilePaths.join(', ')` part).

It is never present in my case.

Nothing in the logs (I can see info, warn and errors in the logs so I guess the problematic part is not logged or is at debug level).
