### ISSUE TITLE
Dev Meeting Agenda 2021-09-14 - Updates

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia#10100]
As I don't currently have write access to the wiki, I am requesting that the following two items that we discussed are added to the record.

- TheiaCon: The Call For Papers is now open for this event happening in mid-November. Please submit your proposals at https://forms.gle/9jtMmv8ruHKdREYs7. Please also retweet and share this tweet to raise awareness, https://twitter.com/theia_ide/status/1437729831819616258. More information will be coming online about the event soon.
- Call Agenda and Notes: We discussed posting reminders of this Dev Call weekly at https://community.theia-ide.org/, linking to the wiki and soliciting more topics. We can also briefly summarize what happened at the last call.
- Forum Categories: Also for https://community.theia-ide.org/, we discussed creating categories to make posts more discoverable. Brian will make a proposal to discuss and decide upon later.

fyi @marcdumais-work

**Comment by marcdumais-work** [comment]
Thanks @brianking - I have added these items to the `dev-meeting` wiki page.
