### ISSUE TITLE
[theia] WebSocket limitation to Drag&Drop a large project

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#1010]
**Problem**

When using drag & drop, it is easy to overload the websocket (ex: drag the `theia` folder from your filesystem into the browser). Only a subset of `theia` will actually be copied over: ~220M / 750M.

The reason for only updating a fraction of the content is a limitation in websocket.
We have to be able to handle the flag [`bufferedAmount`](http://marcelojabali.blogspot.ca/2012/07/websocket-bufferedamount-attribute.html) like: 

```ts
// Buffering threshold at 10k
var THRESHOLD = 10240;
if (mySocket.bufferedAmount < THRESHOLD)
    mySocket.send(getUpdateData());
       }, 1000);
};


```
Another solution might be to adjust the [nodejs connection](https://blog.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/).

**Comment by hexa00** [comment]
>Another solution might be to adjust the nodejs connectio

I don't think that has anything to do with the problem?

Note also that this should be fixed in the vscode jsonrpc lib

**Comment by akosyakov** [comment]
Sending happens here: https://github.com/TypeFox/vscode-ws-jsonrpc/blob/fffa3810484d51f6a565126c53f9e19ec272cc38/src/connection.ts#L25

**Comment by hexa00** [comment]
Thanks for the link we should add rate limiting to that code so that the we don't go over the socket buffer.

**Comment by msujew** [comment]
Resolved with https://github.com/eclipse-theia/theia/pull/9820
