### ISSUE TITLE
When the parameter is Array, the function in BackendService cannot get the correct parameter.

### ISSUE THREAD

**Issue by kidswong999** [eclipse-theia/theia#10129]
### Bug Description:
When the parameter is Array, the function in BackendService cannot get the correct parameter.

### Steps to Reproduce:

1. yo theia-extension, select Backend Communication, and create extension.
2. Change to `sayHelloTo(names:string[]): Promise<string>` in protocol.ts
3. Change to 
```
sayHelloTo(names:string[]): Promise<string> {
        console.log('backend:', typeof(names), names.length, names)
        return new Promise<string>(resolve => resolve('Hello ' + names));
    }
```
in hello-backend-service.ts
4. Change to `execute: () => this.helloBackendService.sayHelloTo(['World', 'a', 'b']).then(r => console.log(r))` in test_backend-contribution.ts

### Result:
root INFO backend: string 5 World

### Expected
root INFO backend: object 3 ['World', 'a', 'b']

- Operating System: Windows 10
- Theia Version: 1.17.2

**Comment by kittaakos** [comment]
Same as https://github.com/eclipse-theia/theia/issues/4343. Also related: https://github.com/eclipse-theia/theia/issues/4310.

**Comment by vince-fugnitto** [comment]
> Same as #4343. 

Thank you for the issue, closing since it is a duplicate of #4343.
