### ISSUE TITLE
Test Explorer API

### ISSUE THREAD

**Issue by firelizzard18** [eclipse-theia/theia#10140]
This is a question about a VSCode 1.59 feature and when it might be added to Theia. I am a contributor to the [Go extension](https://github.com/golang/vscode-go/), and recently I implemented a test explorer/controller for the [Testing API](https://code.visualstudio.com/updates/v1_59#_testing-apis) introduced in VSCode 1.59.

My question is, does Theia plan to add this in the near future? As of v0.28.0, the Go extension has two parallel test systems: the old system and the new one built around the Testing API. It is my intent to merge these two together. If Theia intends to add the Testing API in the near future, I will wait for that. Otherwise, I will look at ways to work around this.

**Comment by msujew** [comment]
We are currently in the process of closing the API gap to vscode 1.55.2, see https://github.com/eclipse-theia/theia/issues/9863.

As the testing API seems quite extensive, I can't imagine it being supported in the near future of Theia. Especially considering that we still have to do a lot of catching-up until we reach 1.59.

@tsmaeder Your opinion on that?

**Comment by tsmaeder** [comment]
IMO, we should focus on getting to a defined level of support, first. Contributions are welcome, though ;-).

**Comment by vince-fugnitto** [comment]
Closing in favor of the epic https://github.com/eclipse-theia/theia/issues/10669 which tracks the APIs.
