### ISSUE TITLE
Fix typedoc generation/publishing

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#10155]
Our typedoc used to rely on the previous hack made to build our repository. The build script rework broke it.

**Comment by marcdumais-work** [comment]
It looks like this prevents the workflow from reaching the npm publish part: 
https://github.com/eclipse-theia/theia/runs/3703430963?check_suite_focus=true

**Comment by marcdumais-work** [comment]
Work-around, to permit npm publish even if building the docs fails:
https://github.com/eclipse-theia/theia/pull/10168

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/10182.
