### ISSUE TITLE
debug: clean up debug session management

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10164]
### Bug Description:
Whe only remove debug sessions when the debuggee sends an "exited" event. However, when we press the "stop" button in the UI, we're sending a 'terminate' request to the debuggee...this just asks the debuggee to terminate the debug session not to exit the process. So we end up with a stale debug session we cannot get rid of.

### Steps to Reproduce:

1. Install the mock debug extension (probably attaching to a long-running java process works, as well) (see https://github.com/eclipse-theia/theia/pull/10163 for instructions)
2. Launch a moch debug sessions
3. Press the "stop" button on the debug session
4. Observe. the session remains.

I believe we should get rid of the debug session upon 'terminated', not 'exited'.

### Additional Information

- Operating System:
- Theia Version: 1.18.0 master

**Comment by svor** [comment]
Can see this problem when running Theia with **redhat.java-0.82.0.vsix** and **vscode-java-debug-0.35.0.vsix**

https://user-images.githubusercontent.com/1271546/135986824-09694a0b-1eb6-40e2-9dad-47aa71433f69.mp4

**Comment by alvsan09** [comment]
> @alvsan09 are you going to work on this, because I was going to.

I started looking into it but I have been a bit distracted from it, 
It's a good time to take it over if you like :+1: 
Thanks for reaching out !

**Comment by tsmaeder** [comment]
I'm currently working on a fix, but t.b.h it's not obvious how to track the lifecycle of nested debug sessions, debug adapters and debuggees. Still seeing lots of surprises.
