### ISSUE TITLE
view command does not list the available views as in vscode

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#10228]
### Bug Description:
Hi,
When trying to open a view using the view command, it does not list the available views.

### Steps to Reproduce:

1. cpen the Open view menu command under the View menu.
2. in the input there is no list of the available views - also trying to type the view name manually does not work.

### Additional Information

- Operating System: windows 10
- Theia Version: 1.18.0

**Comment by msujew** [comment]
Hi @safisa,

I am not able to reproduce the issue using the current `master`:

https://user-images.githubusercontent.com/4377073/135999725-316299cf-9721-4a21-8284-8d7c9105b46f.mp4

Do you mind retesting it under the current `master` branch?

**Comment by safisa** [comment]
Hi,
I figured out what causes this issue, first of all there was an error in the console log (dev tools) when runnig the view command:

listWidget.ts:222 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at listWidget.ts:222
    at Array.map (<anonymous>)
    at TraitSpliceable.splice (listWidget.ts:222)
    at splice.ts:17
    at Array.forEach (<anonymous>)
    at CombinedSpliceable.splice (splice.ts:17)
    at listWidget.ts:1331
    at EventBufferer.bufferEvents (event.ts:792)
    at List.splice (listWidget.ts:1331)
    at QuickInputList.setElements (quickInputList.ts:460)

The cause of the above error is a plugin I have in vscode (vsix), that contains a view without a name). In the example bellow there is no "name": "Title 2" in the "view-UID". Once adding it, the view command will show all available views.

"viewsContainers": {
	"activitybar": [
		{
			"id": "view-UID",
			"title": "Title 1",
			"icon": "icon.svg"
		}
	]
},
"views": {
    "view-UID": [
        {
            "id": "id2",
            "icon": "icon.svg",
            "name": "Title 2"
        }
    ]
}

I still have a small issue in the view command, that in the views list is shows both the titles "Title 1" and "Title 2", although both open the same view!

Thanks.
