### ISSUE TITLE
Committers: rotate your tokens

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10235]
### Bug Description:
I've recently sent this to the theia developers mailing list:

> Folks, if you're a Theia committer (aka one of these people: https://projects.eclipse.org/projects/ecd.theia/who) we're asking you to fill out this form:
 
https://docs.google.com/forms/d/e/1FAIpQLSd9Uzed0cZkHVn8IqcazukQ2C9jpLhEEa1EFW_4L91Nk-Ny7A/viewform?usp=sf_link
 
/Thomas

Since we haven't heard back from a number of committers, we're trying again in this way. The next step would be to start revoking write access to Theia related projects for folks who don't fill out the form.

**Comment by jankeromnes** [comment]
Thanks for the ping! I don’t believe I have anything, but I will audit what secrets I have in Travis. Could you please clarify what type of tokens we’re looking for? (E.g. is it Personal Access Tokens from https://github.com/settings/tokens ?)

**Comment by tsmaeder** [comment]
@jankeromnes anything that allows write access to theia-related repositories, so yes, I believe personal tokens qualify if you are a Theia committer.
