### ISSUE TITLE
Property editor.codeActionsOnSave is not allowed

### ISSUE THREAD

**Issue by mtsmfm** [eclipse-theia/theia#10243]
### Bug Description:

![image](https://user-images.githubusercontent.com/1796864/136370316-78e6e730-08e3-4951-8abb-f86b9cb3ffb4.png)

### Steps to Reproduce:

1. ctrl-shift-p
2. Run Open Preferences (JSON)
3. Type `"editor.codeActionsOnSave": {}`

### Additional Information

- Operating System: Linux
- Theia Version: Che-Theia@21bd47b using Theia@a73a746bf

**Comment by vince-fugnitto** [comment]
The preference seems to now be supported.
