### ISSUE TITLE
Update documentation: Architecture - Extensions

### ISSUE THREAD

**Issue by spoenemann** [eclipse-theia/theia#1026]
https://github.com/theia-ide/theia/blob/master/doc/Architecture.md#extensions

> At the moment an extension is consumed by adding a dependency to the npm-package and then reference the exposed DI modules in the startup script (see main.ts). In the future, we will automate the creation of the application, based on metadata in the package.json of an extension. Extensions can be installed/uninstalled at runtime, which will trigger a recompilation and restart.

This paragraph seems outdated. The link to `main.ts` is broken.

**Comment by tsmaeder** [comment]
I think an updated version can be found here: https://github.com/eclipse-theia/theia-website/blob/master/src/docs/extensions.md
