### ISSUE TITLE
yarn download:plugins disregard proxy settings

### ISSUE THREAD

**Issue by Niklas-Dahlquist** [eclipse-theia/theia#10267]
#### Bug Description:
Latest changes to download-plugins.ts doesn't follow proxy settings

#### Steps to Reproduce:

Do a yarn download:plugins behind a proxy that requires login in [Theia Blueprint](https://github.com/eclipse-theia/theia-blueprint), is it caused by Blueprint now since a vscode-builtin bundle was introduced, where the resolving kicks-in?

Fails during this step: [download-plugins.ts:125 console.warn('--- resolving extension-packs ---');](https://github.com/eclipse-theia/theia/blame/master/dev-packages/cli/src/download-plugins.ts#L125l)

```
--- resolving extension-packs ---
Error: connect ETIMEDOUT 198.41.30.195:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '198.41.30.195',
  port: 443
}
```

- Theia Version: 1.18.0

**Comment by gbodeen** [comment]
We're now running into almost the same problem in our CI. The trouble appears to start with the `bent` library used in `dev-packages/ovsx-client/src/ovsx-client.ts` that isn't configurable to use proxy settings, from where it is used in the `getLatestCompatibleExtensionVersion` method, which is in turned called from within `dev-packages/cli/src/download-plugins.ts` when the `yarn download:plugins` script is run.

**Comment by vince-fugnitto** [comment]
@gbodeen that's right, we would need to refactor `bent` to similarly use what we have in the `download:plugins` script which supports the proxy settings: https://github.com/eclipse-theia/theia/pull/7747.

**Comment by ballcoach12** [comment]
FWIW, I am seeing the same problem.

**Comment by msujew** [comment]
Just to give some context how this is fixed: The `download:plugins` command will automatically pick up the `http_proxy` and `https_proxy` env variables. Also, you can manually set the `--proxy-url <some http address>` argument, which will then take precedence over any existing env variables.
