### ISSUE TITLE
Automatic websocket reconnection after transient offline events is broken

### ISSUE THREAD

**Issue by xavth** [eclipse-theia/theia#10261]
#### Context

Before Theia 1.13.0, when the browser is temporarily offline (e.g. toggling Wifi on and off), Theia reconnects automatically *except* for some Chromium versions under Linux (see https://github.com/eclipse-theia/theia/issues/9298).

After Theia 1.13.0, this issue with some Chromium versions under Linux was fixed in https://github.com/eclipse-theia/theia/pull/9299 so that when the browser is temporarily offline, Theia reconnects automatically all the time.

#### Description

In Theia 1.17.0, when the browser is temporarily offline Theia doesn't reconnect properly afterwards.

This takes a slightly different form in some Chromium versions for Linux:
- in the general case, on disconnection the bottom bar becomes yellow as expected, but even though it goes back to normal as expected when internet reconnects, Theia seems to not actually have reconnected and local changes cannot be saved.
- in the case of specific Chromium versions under Linux (presumably exactly the same as those that were affected by https://github.com/eclipse-theia/theia/issues/9298), the bottom bar doesn't go back to normal and instead stays yellow forever.

In both cases, any unsaved changes at the time of the disconnection can never be saved afterwards; the only way to get back to a working state is to reload the page, which loses all unsaved changes.

This might be related to the new HTTP fallback feature: https://github.com/eclipse-theia/theia/pull/9731: at the moment of disconnection there's also a notification signaling that Theia switched to HTTP fallback mode because Websockets are unavailable (but actually it's internet as a whole that's unavailable). Maybe the HTTP fallback feature interferes with Theia reconnecting.

Also possibly the HTTP fallback notification appears too soon: clearly HTTP fallback cannot be working either when the browser is offline.

### Steps to Reproduce:

1. Create a file and make some unsaved changes in the editor
2. Disconnect internet, e.g. by manually toggling the Wifi off
3. The bottom bar becomes yellow and a HTTP fallback notification pops up
4. Reconnect internet
5. Try to save the previous changes to the file

Below are some screen videos of this with Theia 1.17.0 and Theia 1.13.0 on Firefox.

#### Theia 1.17.0 on Firefox

https://user-images.githubusercontent.com/48094549/136992071-556254cf-5fc2-4916-8a6a-b8f2f6ed680b.mp4

https://user-images.githubusercontent.com/48094549/136992094-141e31c6-5b65-48f5-8e50-008b2f7721ac.mp4

#### Theia 1.13.0 on Firefox

https://user-images.githubusercontent.com/48094549/136992278-f34ea854-5e55-49aa-98cd-880afa99bec4.mp4

### Additional Information

- Operating System: Ubuntu, NayuOS (a ChromiumOS variant)
- Theia Version: 1.17.0, I did not test with newer versions yet

**Comment by perrinjerome** [comment]
Would it make sense to assume that once a websocket has been successfully used, we no longer want to fallback to http polling ? I'm not sure to fully understand https://github.com/eclipse-theia/theia/pull/9731 but it seem it was targeting environments where websockets are not available at all since the application load.

A patch like this seems to solve this issue: 
```diff
diff --git a/packages/core/src/browser/messaging/ws-connection-provider.ts b/packages/core/src/browser/messaging/ws-connection-provider.ts
index dac9216ecc9..722f5274c66 100644
--- a/packages/core/src/browser/messaging/ws-connection-provider.ts
+++ b/packages/core/src/browser/messaging/ws-connection-provider.ts
@@ -80,6 +80,7 @@ export class WebSocketConnectionProvider extends AbstractConnectionProvider<WebS
     protected readonly socket: ReconnectingWebSocket;
     protected useHttpFallback = false;
     protected websocketErrorCounter = 0;
+    protected websocketConnectionSucceeded = false;
     protected httpFallbackId = uuid();
     protected httpFallbackDisconnected = true;
 
@@ -99,6 +100,7 @@ export class WebSocketConnectionProvider extends AbstractConnectionProvider<WebS
         };
         socket.onmessage = ({ data }) => {
             this.websocketErrorCounter = 0;
+            this.websocketConnectionSucceeded = true;
             this.handleIncomingRawMessage(data);
         };
         this.socket = socket;
@@ -108,7 +110,7 @@ export class WebSocketConnectionProvider extends AbstractConnectionProvider<WebS
 
     handleSocketError(event: unknown): void {
         this.websocketErrorCounter += 1;
-        if (this.httpFallbackOptions?.allowed && this.websocketErrorCounter >= this.httpFallbackOptions?.maxAttempts) {
+        if (this.httpFallbackOptions?.allowed && this.websocketErrorCounter >= this.httpFallbackOptions?.maxAttempts && !this.websocketConnectionSucceeded) {
             this.useHttpFallback = true;
             this.socket.close();
             const httpUrl = this.createHttpWebSocketUrl(WebSocketChannel.wsPath);
```

but I did not try the patch except the problematic scenario, I posted a patch hoping it makes my idea easier to understand than just explaining with words.

**Comment by msujew** [comment]
@perrinjerome Yes, that was my thought process as well. I have a similiar implementation on [this Theia branch](https://github.com/eclipse-theia/theia/tree/msujew/disable-http-fallback), but didn't have the opportunity/time to create a PR for this. I'll give it a shot later today.
