### ISSUE TITLE
Update JSON-RPC and Related Dependencies

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#10264]
### Feature Description:

We use `vscode-ws-jsonrpc` a [wrapper around `vscode-jsonrpc`](https://github.com/TypeFox/vscode-ws-jsonrpc) developed by TypeFox that TypeFox has stopped supporting. That package currently only supports `vscode-jsonrpc` < 6 as `vscode-jsonrpc@6` introduced significant changes, and that affects the versions of the language server protocol that we can use. A [fork](https://github.com/CodinGame/monaco-jsonrpc) has been made of the `vscode-ws-jsonrpc` that has updated to use `vscode-jsonrpc` >= 6, and we should consider updating to use that package instead or dump the wrapper and use `vscode-jsonrpc` directly.

**Comment by paul-marechal** [comment]
+1 for moving what we use of that package into the Theia repository.

**Comment by colin-grant-work** [comment]
Superseded by the work to replace JSON-RPC.
