### ISSUE TITLE
File watcher creates lag in the terminal

### ISSUE THREAD

**Issue by anavarre** [eclipse-theia/theia#10283]
### Bug Description:

Having more than 1 file or directory tracked by the file watcher creates lag when typing in the terminal. Note that the issue with the file system watcher was reported multiple times:

* https://github.com/eclipse-theia/theia/issues/5897
* https://github.com/eclipse-theia/theia/issues/3697

### Steps to Reproduce:

1. Create a brand new IDE
2. Observe there is no terminal lag.

> Suggestion: hold down a single key on the terminal on 3-4 lines and observe whether the input is constant or has pauses where it stops and then catches up quickly. There should be NO pause or .5 sec max.

> Also, you can observe that incoming network traffic briefly stops on the web socket network tab in the Chrome inspector.

3. Open Theia's `settings.json` via `File->Settings->Open Preferences` and click on `{}` to edit the preferences as JSON.
5. Replace (or add) the `files.watcherExclude` block so it looks like this (which excludes ALL files from the watcher):

```
"files.watcherExclude": {
  "/**": true
}
```

6. Reload the Theia browser tab
7. Assuming you have PHP and Composer installed, add files to file system with:

```
composer create-project acquia/drupal-recommended-project .
```

As an alternative, the same observation should be possible with a large project with many files and directories...Theia's codebase maybe?

8. Observe there is still no terminal lag.
9. Refresh the Explorer pane with the "Refresh Explorer" icon
10. Observe file tree updates. Still no terminal lag.
11. Revert or remove changes to `settings.json`.
12. Reload the Theia browser tab
13. Observe terminal lag is now present. Pauses of about 2 seconds, pretty often happening (perhaps 5 times on 4 lines)
14. Revert the reversion. E.g., add back

```
"files.watcherExclude": {
  "/**": true
}
```  

15. Reload the Theia browser tab
16. Observe lag is still present! Once it’s there, you can’t get rid of it.
17. Now run `rm -rf ./*` to wipe all files and directories.
18. Lag still present!
19. But if actually if `rm -rf .git` and reload, then the lag goes away
20. Try to add the following to `settings.json`

```
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/.git/subtree-cache/**": true,
    "**/node_modules/**": true
  }
```

21. Reload the Theia browser tab
22. Observe the lag is still present

So somehow, **once the file watcher registers a file, the presence of it will continue to cause lag even when the file watcher is then disabled or updated to be more aggressive with excluding files**. You must both disable to file watcher and remove the files to remove the lag.

### Additional Information

- Operating System: Ubuntu Xenial (16.04)
- Theia Version: 1.18.0

**Comment by anavarre** [comment]
I've never tried the desktop version and don't know that we can easily build it to connect to our remote IDEs that are behind OAuth. But to your point:

>  I want to confirm it's actually an issue with file-watchers and not your setup or network.

It's happening to countless people all around the world (though we're hosted on AWS `us-east1`), I'm just the messenger here, and was able to reproduce the issue with the steps above.

**Comment by vince-fugnitto** [comment]
> Erm, how does trace and debug a watcher? I'm happy to learn new tools for this. Can you suggest a starting point?

The watchers would be debugged on the backend, likely a good place to start would be the following two files:
- https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/node/nsfw-watcher/nsfw-filesystem-watcher.ts
- https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/node/nsfw-watcher/nsfw-filesystem-service.ts

It should be possible to already set up tracing to see what exactly is going on, and consuming resources that would make the terminal lag in your case.

Also, the following is how `files.watcherExclude` is read and used to watch the workspace root:

https://github.com/eclipse-theia/theia/blob/88833b8b5c43746ab7c8a97efe1001ecd81a24c0/packages/workspace/src/browser/workspace-service.ts#L601-L620

**Comment by grasmash** [comment]
So, the lag is very regular. It happens for about 1 second every 5 seconds. I suspect this may be the debounce interval for nsfw. Would it be possible to configure this interval to be longer? If so, what is the best way to pass that configuration to Theia?

**Comment by anavarre** [comment]
Closing because we have updated 8 versions of Theia and have resolved Kubernetes issues participating in terminal lag, so I don't think there's anything to fix anymore.
