### ISSUE TITLE
Lost option icons of the search-input in the search-in-workspace widget

### ISSUE THREAD

**Issue by cenkce** [eclipse-theia/theia#10297]
I upgraded Theia to 1.18.0 then Icons got lost.

### Steps to Reproduce:

1. Upgrade Theia and widgets to 1.18

### Additional Information
<img width="416" alt="Screen Shot 2021-10-19 at 14 25 54" src="https://user-images.githubusercontent.com/176122/137900350-7c03abfe-3986-4a9d-b1b9-403d2bd6a1a0.png">

- Operating System: Macos
- Theia Version: 1.18.0

**Comment by vince-fugnitto** [comment]
> Hmm I think, something keeps old

Can you try performing <kbd>F1</kbd> > `refresh workbench layout`

**Comment by cenkce** [comment]
Where is the cache of those assets?

**Comment by vince-fugnitto** [comment]
> Where is the cache of those assets?

It'd be in the browser's/electron's local-storage :+1: 
The 'reset workbench layout' essentially clears the local-storage of any layout data that might persist.

https://github.com/eclipse-theia/theia/blob/8bf16975f53f5fa50137114c2dd38fdcfaf5eb6d/packages/core/src/browser/shell/shell-layout-restorer.ts#L138-L145
