### ISSUE TITLE
cli download:plugins does not correctly work for extensions defining an extensionPack

### ISSUE THREAD

**Issue by eneufeld** [eclipse-theia/theia#10308]
### Bug Description:
When using an extension which also defines additional extensions using the extensionPack keyword in the manifest, 
these extension are only stored in the .pack folder and thus are not available in the final application as the .pack folder is ignored.

### Steps to Reproduce:

1. take any theia application
2. add https://open-vsx.org/api/ms-vscode/cmake-tools/1.8.1/file/ms-vscode.cmake-tools-1.8.1.vsix as an extension 
  "vscode-cmake": "https://open-vsx.org/api/ms-vscode/cmake-tools/1.8.1/file/ms-vscode.cmake-tools-1.8.1.vsix"
  repo https://github.com/microsoft/vscode-cmake-tools
3. run the 'theia download:plugins'
4. see that the vscode-cmake is in .packs but the twxs.cmake extension is in plugins root, thus unfortunately all the functionality of vscode-cmake-tools is missing.

### Additional Information
As far as I can see it, the problem is this function https://github.com/eclipse-theia/theia/blob/f65e10105407b3186bb2a7eea18af58bdc670aaf/dev-packages/cli/src/download-plugins.ts#L311

With the requirement to exclude plugins this problem becomes quite hard I assume as you need to move the pack if it has excluded ids as a dependency but on the other hand you want to be able to use the extension itself.

- Operating System: all
- Theia Version: 1.17.0 and higher

**Comment by vince-fugnitto** [comment]
@eneufeld I'm not sure I follow the issue. 

The extension-pack resolvement will temporarily store the extension-pack under `.pack`, it should not be part of the final plugins as far as I understand? If `vscode-cmake` is in fact an extension-pack it will pull any extensions it references which is the case:

<img width="214" alt="Screen Shot 2021-10-20 at 5 23 49 PM" src="https://user-images.githubusercontent.com/40359487/138174643-8359bc20-0824-4611-88f1-044967dd7456.png">

If the `vscode-cmake` is simultaneously an extension (offering functionality) and an extension-pack, maybe that's incorrect in of itself?
