### ISSUE TITLE
Eclipse-theia using Podman backend

### ISSUE THREAD

**Issue by PavelSosin-320** [eclipse-theia/theia#10318]
### Feature Description: Using Podman on Linux Desktop, Windows WSL as a Container engine. 
I run Podman and Theia IDE both on Fedora Desktop and Windows WSL as rootless user.  
Taking into account that 

1. Average consumer-level Laptop has enough resources to be used as a development environment using over-the-air connectivity only (GSM)
2. Both Windows WSL BTRFS storage driver and Podman Pod storage are under development and BTRFS itself is advanced persistency provider with portable dev-machine and workspace capabilities.
3. OCI standards are respected, sidecar extansion architecture is easily implementable. 
2.

**Comment by PavelSosin-320** [comment]
Actually, Eclipse-theia itself works quite well with podman offering Theia backend as container , Docker API, and Libpod API via socket on multiple platforms including Windows WSL paired with Chrome or Chromium. The problem is extension mechanism "ectension-by-package" that causes very long startup time. Side car style extension using pre-pulled extension images communicating via Pod's networking is much faster and much more stable because extensions are well isolated. It can work vwey similar to the full-featured Eclipse/Che on almost any laptop using very limited connectivity for the image pre-pulling.

**Comment by msujew** [comment]
I don't think this issue warrants any action, given that Theia seems to work out of the box when packaged in a podman container.
