### ISSUE TITLE
Fix Flaky Tests

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#10348]
These tests are flaky and should be fixed to make CI more reliable and more informative:

À propos the discussion [here](https://github.com/eclipse-theia/theia/discussions/10790), this issue should be used to track tests that fail for no clear reason.

 - [x] 'workbench.editor.closeOnFileDelete' should close the editor when set to 'true'
 - [x] run reference code lens - this one is currently skipped, but its flakiness reflects a real problem with the display of code lenses: they often take a long time to appear for no very clear reason, and even when the editor leaves space between lines to render them.
 - [x] Different parts of the suite in `launch-preferences.spec.js` occasionally fail or time out. [E.g.](https://github.com/eclipse-theia/theia/runs/5432849366?check_suite_focus=true)
 > [Lately](https://github.com/eclipse-theia/theia/runs/5483226388?check_suite_focus=true) some failures of comparison where `undefined !== null`
 - [x] [Recent PR's](https://github.com/eclipse-theia/theia/runs/5469196473?check_suite_focus=true) have seen some issues with `Should toggle explorer` and basic menu tests. Many logs about view containers having been disposed.
 - [x] [A few failures](https://github.com/eclipse-theia/theia/runs/6120599915?check_suite_focus=true) that break down at the step of loading Mocha with messages like this:
 ```
loading mocha...
Uncaught Exception:  Error: Evaluation failed: TypeError: Cannot read property 'logger' of undefined
    at eval (eval at waitForPredicatePageFunction (:2:21), <anonymous>:3:66)
    at eval (eval at waitForPredicatePageFunction (:2:21), <anonymous>:3:73)
```
#11069 should help.
 - [x] Playwright tests cannot be run on MacOS: #10793 will fix that.
 
- [x] `delete and add again file for dirty` failed for https://github.com/eclipse-theia/theia/pull/11192 [here](https://github.com/eclipse-theia/theia/runs/6556102241?check_suite_focus=true)

**Comment by vince-fugnitto** [comment]
I believe we can close as tests have been pretty stable lately. We can open individual issues whenever we encounter future flakiness.
