### ISSUE TITLE
Rename `HostedPluginServer`

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#10351]
### Feature Description:
We currently have two interfaces named `HostedPluginServer`, one in `/plugin-ext` and one in ´plugin-dev`. This is confusing. I propose we rename the one in plugin-dev to `PluginDevServer`.

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/10352.
