### ISSUE TITLE
the action icon of tree-view extensions with menu icon contribution doesn't show up on hover

### ISSUE THREAD

**Issue by ChayaLau** [eclipse-theia/theia#10369]
### Bug Description:
when contributing a tree view menu item - the icon is showing up on hover as to vs code.
i tested on theia 15 - the icon appears when hovering.
but in theia 18 the icon appears only after the node is selected 

### Steps to Reproduce:

1. add a tree view extension with menu contribution
2. open the tree view to explore its content
3. hover on a node
expected - the icon should show up 
current - the icon shows up only after line is selected.

![icons-bug](https://user-images.githubusercontent.com/87074645/139826482-d47ae1b0-a1b9-4a10-ab52-4d4c3739632d.png)

### Additional Information

- Operating System:
- Theia Version:

**Comment by bodarajeshkumar** [comment]
@msujew @RomanNikitenko I am still seeing this issue in the latest Eclipse-Che(version 7.41.2). Not sure if eclipse-che is using the latest version of theia or not. Can you please let me know if I am missing anything?

**Comment by msujew** [comment]
@bodarajeshkumar You should be able to quickly test whether you're running the Theia version containing the fix (1.20.0) by searching for the `terminal.integrated.confirmOnExit` preference. If it exists, the fix does not seem to cover your use case. 

Alternatively you can also try to build the current `master` of Theia, install your extension there and determine whether the issue still exists. The easiest way to do that would be to run it in [Gitpod](https://gitpod.io/#https://github.com/eclipse-theia/theia), but we also have a guide for [local development](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites).

**Comment by bodarajeshkumar** [comment]
Thank you @msujew.I see the command terminal.integrated.confirmOnExit is available in the latest theia master branch. I tested it in my local and I see my issue is also fixed. But I don't see the same command in the latest Eclipse-Che (7.41.1). Could you please suggest what else I can check?

**Comment by msujew** [comment]
> But I don't see the same command in the latest Eclipse-Che (7.41.1).

@bodarajeshkumar You mean you don't see the preference in Eclipse-Che?

Anyway, since this issue is resolved from our side (Eclipse-Theia) there's not a lot we can do. It's on the Che team to update their Theia version.

**Comment by bodarajeshkumar** [comment]
ok got it. Thank you @msujew

**Comment by RomanNikitenko** [comment]
@bodarajeshkumar 
I had a quite long vacation, so I saw your question only now.

@msujew is right (thanks!)- we should upgrade `Theia` version on `Che-theia` side to pick up the fix.
