### ISSUE TITLE
Open VSX: plugin listing text should not be selectable

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#10372]
### Steps to Reproduce:

1. Open the Extensions view
2. Search for e.g. git.
3. Try to select some text in one of the results.

Expected: no selection in the extensions view nodes.

### Additional Information

![image](https://user-images.githubusercontent.com/62660806/139882393-a30825f6-307b-40de-a335-75408a1036ce.png)

- Operating System: RHEL7 (Electron)
- Theia Version: `master`

**Comment by vince-fugnitto** [comment]
The fix should be as simple as adding the `noselect` css class here:

https://github.com/eclipse-theia/theia/blob/e91bea493a1a74ee2405340903e0419f2e363cfa/packages/vsx-registry/src/browser/vsx-extension.tsx#L419
