### ISSUE TITLE
Remove redundant config files

### ISSUE THREAD

**Issue by tom-shan** [eclipse-theia/theia#10386]
This bug is blocked for the Hackathon, please do not fix

### Bug Description:
https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/compile.tsconfig.json and
https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext-vscode/compile.tsconfig.json
are redundant after the build system reworking(https://github.com/eclipse-theia/theia/pull/9710)

**Comment by vince-fugnitto** [comment]
@tom-shan thank you for reporting the issue, are you interested in contributing a fix?

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/9936.
