### ISSUE TITLE
vscode.window.showInformationMessage can‘t show in 1.19.0，but work well in 1.18.0

### ISSUE THREAD

**Issue by hyy215** [eclipse-theia/theia#10398]
### Bug Description:
install vsix，run vscode command to show an information message（vscode.window.showInformationMessage），but not show

### Steps to Reproduce:
1. run `yo code`， choose `New Extension (TypeScript)`
2. run `vsce package`，package the vscode extension
3. install the vsix in theia
4. run the `Hello World` command
5. work well in 1.18.0，but in 1.19.0，failed

in 1.18.0
![image](https://user-images.githubusercontent.com/34715914/140848432-79e44928-6d13-4f8a-bd3c-437c68a9a575.png)

### Additional Information

- Operating System: win10
- Theia Version: 1.19

**Comment by msujew** [comment]
@hyy215 Thank you for reporting this issue, this is a regression introduced by #10245. I'll take care of that.
