### ISSUE TITLE
validateInput does not get cleared between window.showInputBox calls

### ISSUE THREAD

**Issue by phaumer** [eclipse-theia/theia#10393]
### Bug Description:

VS Code extensions that use `vscode.window.showInputBox()` are broken in 1.18, 1.19 and current master if they used validateInput in any of their calls as the validation method is not cleared and reused by other calls to showInputBox if they do not provide a validateInput value.

This is a major regression that will break all VS Code extension that use input boxes with validation.

### Steps to Reproduce:

1. Clone and build https://github.com/microsoft/vscode-extension-samples/tree/main/quickinput-sample
2. Modify the `showInputBox()` method in file `basicInputs.tx` as shown below
3. Run it in Theia, do cmd-shift-p `Quick Input Samples`, select `showInputBox`
4. In the first prompt type `123` and you see the validation working
5. In the second prompt that does not specify a validation enter `123` and you see the old validation is still kicking in 
6. In the third prompt type `123` and you see the validation was cleared, which is the workaround for now 
7. Run the same in VS Code and the second prompt works as expected and I can enter `123`

```ts
export async function showInputBox() {
	const result = await window.showInputBox({
		value: 'abcdef',
		valueSelection: [2, 4],
		placeHolder: 'For example: fedcba. But not: 123',
		validateInput: text => {
			window.showInformationMessage(`Validating: ${text}`);
			return text === '123' ? 'Not 123!' : null;
		}
	});
	window.showInformationMessage(`Got: ${result}`);

        const result2 = await window.showInputBox({
		value: 'xyz',
		placeHolder: 'Type another, for example: xyz.',
	});
        window.showInformationMessage(`Got: ${result2}`);

        const result3 = await window.showInputBox({
		value: 'xyz',
		placeHolder: 'Type another, for example: xyz.',
                validateInput: text => null
	});
        window.showInformationMessage(`Got: ${result3}`);
}
```

### Additional Information

- Operating System: MacOS
- Theia Version: 1.18, 1.19, master at 39fe3728f7bdef75109564918b414607fdbe008b

**Comment by phaumer** [comment]
Thanks for the quick fix @vince-fugnitto. Would this be a significant enough regression that could trigger a 1.19.1 release?

**Comment by vince-fugnitto** [comment]
> Thanks for the quick fix @vince-fugnitto. Would this be a significant enough regression that could trigger a 1.19.1 release?

@phaumer thank you for reporting the issue :+1:
I don't believe that on it's own the bug would warrant a patch release, but if others want we can think about it.
There are alternatives however:
- using a `next` version which includes the fix.
- using a workaround `validateInput: () => ''` for input that should not be validated.

**Comment by EstherPerelman** [comment]
> I don't believe that on it's own the bug would warrant a patch release, but if others want we can think about it.
> There are alternatives however:

@vince-fugnitto, we need this fix urgently (our customers reported this), can you please publish v1.19.1?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto, we need this fix urgently (our customers reported this), can you please publish v1.19.1?

@EstherPerelman any reason you can't use a `next` version with the fix until `1.20.0`?

**Comment by EstherPerelman** [comment]
> any reason you can't use a `next` version with the fix until `1.20.0`?

@vince-fugnitto what is the `next` version? how to get it?

**Comment by msujew** [comment]
@EstherPerelman, instead of `"@theia/core": "1.19.0"` use `"@theia/core": "1.18.0-next.150"`, which was released yesterday. (Don't mind the `1.18.0` in front, it's an issue that's been introduced with a lerna update, it's still the 1.19.0 version of Theia + newer merged PRs)

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto what is the `next` version? how to get it?

For each commit on master, we publish a `next` version to npm, you can use this if you'd like instead of having to wait a whole month for the next release (for example if there is a change you require).

The following version should have the fix you require (update all `@theia` extensions as well):

```json
"@theia/core": "1.18.0-next.150"
```

**Comment by phaumer** [comment]
How can we avoid that 1.18 or 1.19.0 will never make it downstream releases such as Che or CodeReady Workspaces?

**Comment by paul-marechal** [comment]
@phaumer you need to see with the Eclipse Che project. How they consume Theia depends solely on them.

**Comment by EstherPerelman** [comment]
Hi @vince-fugnitto @msujew thank you for the quick reply, I updated all my `package.json`s `@theia/core` to the `next` version but I get this error after `yarn` (not only for this import): ```@sap/theia-hosted-plugin-manager:   Type 'import("C:/Projects/<myProject>/node_modules/@theia/core/lib/common/uri").default' is not assignable to 
type 'import("C:/Projects/<myProject>/packages/theia-hosted-plugin-manager/node_modules/@theia/core/lib/common/uri").default'.```
Trying to update other dependencies to the `next` version caused another error (something like ``1.18.0-next.150 version not found for `@theai/plugin-ext```)

**Comment by paul-marechal** [comment]
@EstherPerelman you have duplicated `@theia` modules (`/node_modules/@theia/core/...` vs `/packages/theia-hosted-plugin-manager/node_modules/@theia/core/...`). You need to ensure that only one version of `@theia/core` is being used. You may use yarn's resolutions to achieve this.

**Comment by EstherPerelman** [comment]
@paul-marechal thanks for the response, in our project inside `packages` folder we have `theia-extension`s which use separate `package.json`s than the `browser-app` I have changed for all of them the `theia/core` version but the error [above](https://github.com/eclipse-theia/theia/issues/10393#issuecomment-968257097) appears
If there's no solution - we would like you to publish 1.19.1 theia version because we can't wait so long to 1.20.0 version
