### ISSUE TITLE
Integrate `socket.io` for messaging

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#10403]
After a discussion related to the HTTP fallback feature in #10395, the idea came up to integrate [`socket.io`](https://socket.io/) into Theia. It comes with a built-in http fallback that doesn't require any additional support on our end. That would alleviate some of our problems that we had with that feature and messaging in general.

I will take a closer look at this issue once I have some more time to spend.

**Comment by matthewfisch** [comment]
++ for this
