### ISSUE TITLE
`vscode.window.showInformationMessage` with 1 parameter not working on Theia

### ISSUE THREAD

**Issue by EstherPerelman** [eclipse-theia/theia#10444]
### Steps to Reproduce:

1. Add [base-sample.zip](https://github.com/eclipse-theia/theia/files/7576070/base-sample.zip) `vsix` to theia project
2. `ctrl+shift+p` -> `Hello World` 
3. See only message2 appears on the bottom right

I used the `extension.ts` file with the next code:
![image](https://user-images.githubusercontent.com/71729183/142758213-32bbcc17-0170-4e60-b6b7-cc1b32a4afab.png)

### Additional Information

- Operating System:
- Theia Version:

**Comment by msujew** [comment]
@EstherPerelman You probably noticed it yourself, but just for others that see this issue: this was fixed by #10399 (originally introduced by #10245).
