### ISSUE TITLE
VS Code pop up notifications not showing in Theia 1.19.0

### ISSUE THREAD

**Issue by JillieBeanSim** [eclipse-theia/theia#10453]
### Bug Description:

VS Code pop up notifications (info, warning, error) not showing in Theia 1.19.0 for VS Code extensions.
I verified this with a simple VSC extension from microsoft/vscode-extension-samples helloworld-minimal-sample which has a new command pallet option `Hello World` which should just show an information message that says `Hello World` when the option is chosen in the command pallet.
https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-minimal-sample

### Additional Information

- Operating System: Docker container
- Theia Version: 1.19.0

**Comment by vince-fugnitto** [comment]
@JillieBeanSim thank you for the issue, it has already been fixed and will be part of the next release (November 25th):
- https://github.com/eclipse-theia/theia/issues/10398
