### ISSUE TITLE
Support Testing API

### ISSUE THREAD

**Issue by shuyaqian** [eclipse-theia/theia#10496]
### Feature Description:
Is there any plan to support the[ test API](https://code.visualstudio.com/api/extension-guides/testing)? Currently, the latest [Python ](https://marketplace.visualstudio.com/items?itemName=ms-python.python)and [Test Runner for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) have used this API. If the API is incompatible, these plugins cannot be used.

**Comment by msujew** [comment]
Hi @shuyaqian,

Sadly, I don't think its on any contributors roadmap, see [here](https://github.com/eclipse-theia/theia/wiki/Eclipse-Theia-Roadmap). Of course, contributions are welcome, but the testing API is quite a behemoth. We have another open issue on that https://github.com/eclipse-theia/theia/issues/10140. I will close this issue in favor of the other one.
