### ISSUE TITLE
Increase column mode

### ISSUE THREAD

**Issue by cws999** [eclipse-theia/theia#10507]
### Feature Description:
Increase column mode
Is there a column mode? Still i can't find

**Comment by msujew** [comment]
@cws999 Do you mean the column selection preference as mentioned in [this vscode documentation](https://code.visualstudio.com/docs/editor/codebasics#_column-selection-mode)? The preference doesn't seem to be implemented in Theia, but you can still use column selection by pressing `shift+alt` and dragging your mouse over the text.

![image](https://user-images.githubusercontent.com/4377073/144749228-22571024-9123-4da3-b4ae-74f920fa01d0.png)
