### ISSUE TITLE
Invalid generated webpack config when not using `@theia/monaco`

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#10535]
### Bug Description:

Originally found in #10534

When building Theia without including the `@theia/monaco` package (directly or transitively), the `application-manager` builds an invalid `CopyWebpackPlugin` instance (the array should contain [at least one item](https://github.com/webpack-contrib/copy-webpack-plugin/blob/d6a6cdbba1f66aa7c4261788c04e9bb43d78224c/src/options.json#L136)):

```js
new CopyWebpackPlugin({
    patterns: []
})
```

### Steps to Reproduce:

1. Create a Theia app without using `@theia/monaco` or remove `@theia/monaco` completely from your app
2. The build fails:

![](https://user-images.githubusercontent.com/25635994/145722259-5483b704-68a3-41b8-945d-855f9ad3c5e7.png)

### Additional Information

- Operating System: Ubuntu
- Theia Version: 1.20

**Comment by colin-grant-work** [comment]
Looks like this is similar to #544. @msujew, you may want to include that among the things closed by #10536.

**Comment by kittaakos** [comment]
> Looks like this is similar to #544.

#544 is a runtime issue.

But I do not know if #544 is still valid, though.
