### ISSUE TITLE
Backend source code not be build to on bundle.js in electron build

### ISSUE THREAD

**Issue by orange-pig** [eclipse-theia/theia#10563]
My application face to desktop, and i build to electron app use electron-builder.  

I want not to publish my source code, so i exclude my source code use the follow config all the time.

electron-builder.yml
```
files:
  - src-gen
  - "!src-gen/frontend/index.*"
  - lib
  - "!**node_modules/electron/**"
  - "!**node_modules/my-project-folder/**"

```
At same time webpack build to one bundle.js obfuscate my code, a happy times.

Until i added a backend service, my application not running after electron package. And then I find the reason:

Theia's webpack only biuld frontend srouce code to one bundle.js, and backend source code be copyed to 'node_modules/my-project-folder'.

And other, I try to add webpack.backend.config.js to build 'backend/main.js'. Not surprisingly, I failed.

### Bug Description:

Package to electron, my backend source code publich with source code.

### Steps to Reproduce:
Perpare to add a electron-builder.yml.

1. yarn
2. cd electron-app
3. yarn build
4. yarn electron dist  # or: yarn electron run pack
5. Running the myApp.exe, Not responding

Info:
1. Three process name myApp in the windows Task Manager, it look like shell running but main thread broking.
2. Don't find log file in 'c:/user/MyName/.theia/logs' 
3. Don't find event record in Windows Log
4. Copy the 'my-project-folder/lib/' into  '/resources/node_modules/my-project-folder/', it's woking.

### Additional Information

- Operating System: windows 11
- Theia Version: 1.18.0

### My question

I think it a bug that don't build the backend resource code to one bundle.js with electron-builder. And I try to add webpack.config build the backend/main.js, but it's failed. 

So, How to build backend source code to one bundle.js for product source code.

**Comment by anlate** [comment]
I met the same problem, did you solve it?

**Comment by orange-pig** [comment]
> 

Not yet! You may be able to compile '*.js' into a bytecode file in another way. Forget the build to bundle.js :)
