### ISSUE TITLE
Webview iconPath not work when using vscode plugin

### ISSUE THREAD

**Issue by jimwu11235** [eclipse-theia/theia#10585]
### Bug Description:
Webview iconPath not work when using vscode plugin
This issue was reported at #9553 and closed at #9608
But after I update my Theia project from v1.14.0 to v1.21.0, 
the webview iconPath is still not working

### Steps to Reproduce:

The reproduction steps are same as #9553 with webview example project.

### Additional Information
- Operating System: Windows 10
- Theia Version: v1.21.0
- Node Version: v12.14.1
- Yarn Version: v1.22.17

**Comment by colin-grant-work** [comment]
I'm able to reproduce this on Windows but not in Linux. On Linux, the icon appears correctly; on Windows I get this error:

```console
root ERROR Could not transfer '..\..\..\..\..\..\..\..\c:\Users\me\AppData\Local\Temp\vscode-unpacked\cat-coding-0.0.1.vsix\extension\resources\menu.svg' file from 'demo_cat_coding'
```

It looks like there's a problem with our identification of absolute paths on Windows or something.

**Comment by colin-grant-work** [comment]
I believe that this is the same issue described in #10370. Basically, the plugin path URI is correct, but when `Uri.joinPath` is run, we get a bad result with a double C: drive letter, which is the source of the many `../` in the eventual URL.

```
root INFO [hosted-plugin: 4852] EFFECTS OF JOINPATH
Before:
URI {
  scheme: 'file',
  authority: '',
  path: '/c:/Users/me/AppData/Local/Temp/vscode-unpacked/cat-coding-0.0.1.vsix/extension',
  query: '',
  fragment: ''
}
After:
URI {
  scheme: 'file',
  authority: '',
  path: '/C:\\c:\\Users\\me\\AppData\\Local\\Temp\\vscode-unpacked\\cat-coding-0.0.1.vsix\\extension\\resources\\menu.svg',
  query: '',
  fragment: ''
}
```
