### ISSUE TITLE
Order menu items in `Open With` according openers order not a command id

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#106]
Depends on: https://github.com/TypeFox/Theia/issues/105. Needs promises in Command's methods.

**Comment by vince-fugnitto** [comment]
@akosyakov correct me if I'm wrong but I believe the issue is fixed ?
When we call `getOpeners` we use `prioritize` to prioritize the list, and we only ever
display true handlers.

**Comment by vince-fugnitto** [comment]
> @akosyakov correct me if I'm wrong but I believe the issue is fixed ?
> When we call `getOpeners` we use `prioritize` to prioritize the list, and we only ever
> display true handlers.
