### ISSUE TITLE
CSS duplicate margin property without effect

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#10602]
### Bug Description:
.theia-breadcrumbs defines two properties "margin", the first one does not have any effect and should be removed (see https://github.com/eclipse-theia/theia/blob/2352920342db3322907f392c3d480b6d11fbe44c/packages/core/src/browser/style/breadcrumbs.css#L31-L35)

### Steps to Reproduce:

1. Adapt the first margin value and observer no effect. Breadcrumps are visible in open editors just below the title tab.
2. Adapt the second value, e.g. to 0.6rem and observe the breadcrump partially been cut due to the margin

### Additional Information
As the first margin has no effect, it should be removed.

**Comment by JonasHelming** [comment]
Sandeep

**Comment by hemanthemmady** [comment]
@JonasHelming - Can I take this up?

**Comment by msujew** [comment]
@hemanthemmady I assigned you to it 👍
