### ISSUE TITLE
ApplicationError.declare does not correctly verify the uniqueness of error codes

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#10603]
**This bug is blocked for the Hackathon, please do not fix**

### Bug Description:

ApplicationError.declare checks whether an error code is in the array "codes", but it never pushes existing values into this array. Hence, the check for code collisions is not working as expected.

### Steps to Reproduce:

Call ApplicationError.declare twice with the same code, e.g.
let code = 1;
ApplicationError.declare(code, () => ({ message: '', data: {} }));
expect(() => ApplicationError.declare(code, () => ({ message: '', data: {} }))).to.throw(`An application error for '${code}' code is already declared`);

This test case will fail.

**Comment by vince-fugnitto** [comment]
@JonasHelming should we convert `hackaton` issues to `good first issue` given the hackaton has completed?

**Comment by JonasHelming** [comment]
@vince-fugnitto : Good suggestion, but let me think about it, first. Maybe we conduct a similar event, soon.

**Comment by JonasHelming** [comment]
Fixed by https://github.com/eclipse-theia/theia/pull/11160
