### ISSUE TITLE
Use vscode builtins extension pack in example applications

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#10618]
Use the vscode built-ins pack in example apps

### Feature Description:
Theia now supports using vscode extensions packs, and the vscode built-in extensions we publish on open-vsx, have such a pack. We could easily replace the [current vscode built-ins](https://github.com/eclipse-theia/theia/blob/master/package.json#L91-L160) with such a pack. 

example: https://github.com/eclipse-theia/theia-blueprint/blob/master/applications/electron/package.json#L121-L122

We may need to exclude a couple of built-ins, like so: https://github.com/eclipse-theia/theia-blueprint/blob/master/applications/electron/package.json#L129-L132

**Comment by vince-fugnitto** [comment]
@marcdumais-work just to mention I have the following pull-request https://github.com/eclipse-theia/theia/pull/10049 but didn't get around to fixing the issues as to why the api-tests would fail for typescript.

**Comment by marcdumais-work** [comment]
Duplicate of https://github.com/eclipse-theia/theia/issues/9985
