### ISSUE TITLE
Add context menu items for copy path/copy relative path to Search in Workspace results

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#10629]
### Feature Description:
In VSCode, right-clicking on a search in workspace result gives the following options

Individual Result:

![image](https://user-images.githubusercontent.com/62660714/149224891-334e594b-685f-4e40-8a9b-5e5407521fdb.png)

File/Directory:

![image](https://user-images.githubusercontent.com/62660714/149225051-76cb13d9-ddb9-4cd3-b4c0-06273fee416e.png)

Where copy/copy all selectively copies the search result(s)

It would be nice to have the copy path/relative path options available at least.

**Comment by colin-grant-work** [comment]
(The screenshots are from the VSCode references view plugin, but I believe the OP's intent is to align the SIW context menu with VSCode's)
