### ISSUE TITLE
Add debug namespace VSCode API

### ISSUE THREAD

**Issue by lucas-koehler** [eclipse-theia/theia#10661]
### Feature Description:

Provide all methods of the VSCode API's `debug` namespace.

- [x] addBreakpoints
- [x] asDebugSourceUri
- [x] removeBreakpoints
- [x] startDebugging (https://github.com/eclipse-theia/theia/pull/10656)
- [x] stopDebugging (https://github.com/eclipse-theia/theia/pull/10638)

**Comment by lucas-koehler** [comment]
@vince-fugnitto Do you currently work on or plan to work on the other methods or are they open to do?

**Comment by msujew** [comment]
@lucas-koehler There is currently a PR to align the `startDebugging` API parameters, although it has been in place for quite a while. https://github.com/eclipse-theia/theia/pull/10656

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Do you currently work on or plan to work on the other methods or are they open to do?

@lucas-koehler you can work on them if you'd like, two of them should be quite simple (minor method signature alignment). 
I noticed however that there is quite a lot of bugs from the `debug` namespace, I've opened issues of what I found.

**Comment by lucas-koehler** [comment]
@vince-fugnitto For now, I am not working on them. I decided to go with #9992 instead. But I'll keep it in mind, thanks :)
