### ISSUE TITLE
Implement `env` namespace VSCode API

### ISSUE THREAD

**Issue by lucas-koehler** [eclipse-theia/theia#10662]
### Feature Description:

Add the `env` namespace of the VSCode API to the plugin API.

- appHost
- isNewAppInstall
- isTelemetryEnabled
- onDidChangeTelemetryEnabled
- remoteName

See the VSCode API for more information on the listed properties/event: https://code.visualstudio.com/api/references/vscode-api#env

**Comment by paul-marechal** [comment]
fyi: We have someone looking at this.
