### ISSUE TITLE
fix `TypeScript: run reference code lens` test case

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#10689]
PR to revert once fixed: https://github.com/eclipse-theia/theia/pull/10688

**Comment by alxflam** [comment]
@paul-marechal for some reason, dispatching some key event while waiting for the code lens animation makes the test pass. E.g. add 'keybindings.dispatchKeyDown('ArrowRight');' to the function codeLensNodeVisible makes the test pass for me locally. Maybe that helps for further analysis. Adding a key event outside of the codeLensNodeVisible function, e.g. right before the waitForAnimation call doesn't help. :confused:
