### ISSUE TITLE
GitLens extension does not work

### ISSUE THREAD

**Issue by MoHcmp** [eclipse-theia/theia#10697]
### Bug Description:
GitLens extension does not work. Without this extension working with git in Theia can be a problem. For example: Theia git does not have "Reset" command.

1. Build Theia master
2. Download GitLens extension from VsCode marketplace: https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
3. Put extension in plugins folder (guide here: https://github.com/eclipse-theia/theia/wiki/Testing-VS-Code-extensions)
4. Start Theia

When loading page we get error and plugin does not work.
![image](https://user-images.githubusercontent.com/24322410/151982829-8fb429e5-825e-4da6-8166-1be37469de44.png)

### Additional Information

- Operating System: Windows 10
- Theia Version: master branch on date 01.02.2022

**Comment by msujew** [comment]
Hi @MoHcmp,

the newest versions of the GitLens extension requires [VSCode version 1.63.1](https://github.com/gitkraken/vscode-gitlens/blob/ce6652474609c855bfee93da1c7ec5b86f4011ab/package.json#L7), and we are currently quite a bit behind that (1.53.2).

I would recommend you to install a matching version from the [`open-vsx` marketplace](https://open-vsx.org/extension/eamodio/gitlens) or let Theia install the matching version by itself using the vsx-registry view.

**Comment by MoHcmp** [comment]
Version 11.4.1 works. Thanks
