### ISSUE TITLE
Rename to `postConstruct` all methods decorated with the `@postConstruct()` decorator

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#10700]
- Rename to `postConstruct` all methods decorated with the `@postConstruct()` decorator.
- Type all those methods as `() => void`.

There are a lot of inconsistencies when it comes to this post-constructor callback method. most of the time the method is called `init`, but sometimes `configure`, or `initialize`. I would prefer to call it `postConstruct` as it better describes what the method is meant for, but since `init` is most commonly used I would be OK with renaming to this instead.

Inversify's `postConstruct` exist because when it tries to create the instances for our bindings, it has to call the constructor before it can inject properties (if any). See the following example:

```ts
@injectable()
class Component {

  @inject(SomeService)
  protected _service: SomeService;

  constructor() {
    // this._service is undefined here!
  }

  @postConstruct()
  protected postConstruct(): void {
    // this._service got injected, we can use it.
  }
}
```

A problem in our code base is that some of those `postConstruct` functions return promises. Inversify won't wait on them, as the instance creation step assumes everything happens synchronously. This means that more often than not, by the time our asynchronously-post-constructed services are injected, dependents might try to call into uninitialized properties...

**Comment by paul-marechal** [comment]
Naming is just for consistency/clarity but the asynchronous issue is an actual problem indeed. I'll open an issue just for it.

**Comment by msujew** [comment]
They are now all called `init`, see https://github.com/eclipse-theia/theia/pull/12425.
