### ISSUE TITLE
debug: issue when starting a js-debug session in electron

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10710]
#### Bug Description:

There is an issue when starting a debug session in electron (namely due to a poor user experience), where the builtin `js-debug` extension displays multiple dialog messages:

```
Attach to process: '${command:PickProcess}' doesn't look like a process id.
```

https://user-images.githubusercontent.com/40359487/152400530-73a85acb-7753-484c-a98e-e215e9c8a008.mp4

The error originates from:

```
root ERROR Failed to resolved 'command:PickProcess' variable Error: The command 'PickProcess' cannot be executed. There are no active handlers available for the command.
```

### Steps to Reproduce:

1. start the `example-electron` app with `theia` as a workspace
2. execute the command `Reset Workbench Layout` - just to be safe
3. execute the command `Debug: Start Debugging` - notice the multiple dialogs that appear
4. the same use-case works fine in the browser

**Comment by alvsan09** [comment]
Related to: 
https://github.com/eclipse-theia/theia/issues/2819
