### ISSUE TITLE
debug: debug incorrectly imports plugin code

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10714]
#### Bug Description:

The pull-request https://github.com/eclipse-theia/theia/pull/10163 incorrectly leaks plugin code to `@theia/debug`.

https://github.com/eclipse-theia/theia/blob/2faa18b0f6b31ad27fefd4fe73901c07c3d27cf9/packages/debug/src/node/inline-debug-adapter.ts#L19

No internal extension should explicitly depend on the plugin- system, we should refactor to implement the feature properly.

@tsmaeder was there a specific reason to directly depend on the plugin types from debug?

**Comment by tsmaeder** [comment]
I can't think of a reason right off the bat. Can we just move the class to the theia plugin package? It just seems to be a wrapper around the Theia inline debug adapter.
