### ISSUE TITLE
Theia doesn't support VS Code icon identifiers

### ISSUE THREAD

**Issue by thegecko** [eclipse-theia/theia#10746]
### Bug Description:

VS Code declares icons using identifiers or codIcon IDs as outlined here:

https://code.visualstudio.com/api/references/icons-in-labels#icon-listing

It's not clear when to use each identifier, but VS Code seems to only support the codicon ID when declaring contributions in `package.json` (e.g.`"$(add)"`) and only supports the identification form when setting an icon programmatically (e.g. `new vscode.ThemeIcon('settings-add')`).

Theia only supports codicon IDs in both of these cases which means VS Code extensions with icons set programmatically don't work.

### Steps to Reproduce:

This code should work in Theia:

```typescript
    item.iconPath = new vscode.ThemeIcon('ports-view-icon');
```

However, to get this to work, the other ID has to be used and switched based on the host running, e.g.:

```typescript
    const icon = vscode.env.appName === 'Visual Studio Code' ? 'ports-view-icon' : 'plug';
    item.iconPath = new vscode.ThemeIcon(icon);
```

**Comment by DmitryZagr** [comment]
+1 

I have the same issue

code to reproduce
`
   var statusBarItem = window.createStatusBarItem(StatusBarAlignment.Left, 100);
    let statusMenuIcon = `$(circle-large-outline)`;
    statusBarItem.text = statusMenuIcon + ' Title';
    statusBarItem.show();
`
