### ISSUE TITLE
electron: Open dialogs are not modal

### ISSUE THREAD

**Issue by AlexandraBuzila** [eclipse-theia/theia#10768]
### Bug Description:
The Open dialog in the electron application is not modal. Multiple ones can be opened at the same time. This affects the Open File, Open Folder, Open Workspace commands.

### Steps to Reproduce:

1. Go to the File menu, select the Open File... menu entry. A dialog to select the file should open.
2. Click outside the dialog, e.g. in the main window
3. The dialog goes into the background and a new dialog can be opened via the Open File... command, while the first one is still open.

The expectation would be that the dialog is modal and remains on top of the main window until it's dismissed.

**Comment by vince-fugnitto** [comment]
Closed thanks to #10769.
