### ISSUE TITLE
scm: history does not work when using builtin vscode extensions

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10786]
#### Bug Description:

The `scm-history` view does not work when using the vscode builtin extensions, there is a message stating that history does not work for git source control (the same is true when an individual file is selected to display it's history):

![image](https://user-images.githubusercontent.com/40359487/155328347-815edff1-4f33-43c2-b13d-a9dcd4907947.png)

#### Steps to Reproduce:

1. remove `@theia/git` from the example application(s)
2. use the git builtins (tested with `1.53.2`):

    ```json
    "vscode-git": "https://open-vsx.org/api/vscode/git/1.53.2/file/vscode.git-1.53.2.vsix",
    "vscode-git-ui": "https://open-vsx.org/api/vscode/git-ui/1.53.2/file/vscode.git-ui-1.53.2.vsix"
    ```

3. start the application with a folder that is under version control
4. confirm that version control works (scm-view), but not the history view

**Comment by vince-fugnitto** [comment]
It looks like it was never actually supported https://github.com/eclipse-theia/theia/pull/6381, the vscode api for extensions does not provide history, but it does provide timeline information. I believe it was the reason to have some `@theia/scm-extra` (which I had forgotten about). 

@msujew I believe there is no issue, if we use the builtin we should not use `@theia/git` or `@theia/scm-extra`.

**Comment by danepowell** [comment]
> if we use the builtin we should not use @theia/git or @theia/scm-extra

Since the Theia Blueprint uses the builtin Git extension instead of `@theia/git`, does that mean it should remove `@theia/scm` and `@theia/scm-extra`? I'm happy to open a PR if so.

**Comment by vince-fugnitto** [comment]
> Since the Theia Blueprint uses the builtin Git extension instead of `@theia/git`, does that mean it should remove `@theia/scm` and `@theia/scm-extra`? I'm happy to open a PR if so.

@danepowell `@theia/scm` is necessary is necessary for source-control support in which `vscode.git` is a contribution. The `@theia/scm-extra` can be safely removed I believe as it only contributes the history-view at this time.

**Comment by danepowell** [comment]
Thanks; PR to remove scm-extra: https://github.com/eclipse-theia/theia-blueprint/pull/293
