### ISSUE TITLE
custom-editor: restore editor as part of layout

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10787]
#### Bug Description:

The framework currently does not support restoring `custom-editors` as part of the layout. If a given custom-editor is opened and the application is restarted (reload the window for example) the editor will not be preserved.

https://user-images.githubusercontent.com/40359487/155335495-776c73c1-774e-4d67-af58-aa2d7a87e147.mp4

#### Steps to Reproduce:

1. use the [custom-editor-sample](https://github.com/eclipse-theia/theia/files/8124915/cat-customs-0.0.1.zip) extension.
2. start the application using [exampleFiles](https://github.com/lucas-koehler/vscode-extension-samples/tree/main/custom-editor-sample/exampleFiles) as a workspace.
3. open `example.cscratch` - the custom editor should open.
4. reload the application - confirm that the editor is not preserved.

**Comment by vince-fugnitto** [comment]
> Or, can you help on how to fix it using Theia extension?

@safisa I haven't worked on the issue, if you are interested please don't hesitate on contributing a fix. You'll need to debug as to why the `custom-editors` are not being properly stored or restored in the layout.

Some interesting places to look:

https://github.com/eclipse-theia/theia/blob/432602946323bc1500c585de4432021b6d6a4a0a/packages/plugin-ext/src/main/browser/custom-editors/custom-editor-widget.ts#L86-L97

https://github.com/eclipse-theia/theia/blob/432602946323bc1500c585de4432021b6d6a4a0a/packages/plugin-ext/src/main/browser/custom-editors/plugin-custom-editor-registry.ts#L56-L72

The layout is stored in the `localStorage` of the browser or electron.

**Comment by safisa** [comment]
To resolve this issue, we need to registerWebviewPanelSerializer in the vscode extension code. This was missing in my implementation, once I did it (in the following example) the custom editor layout was restored on reload. BUT there was a small issue on restore, getting undefined error in Theia CustomEditorWidget class, the _modelRef is undefined (we got there from a call to the setLayoutData in the application shell):

```
get saveable(): Saveable {
        return this._modelRef.object;
    }
```
Once overriding this in my Theia extension: 
```
@injectable()
export class MyCustomEditorWidget extends CustomEditorWidget {

    // override saveable() to fix the undefined _modelRef issue when reviving (restoring state) after reload (when using the registerWebviewPanelSerializer in the fabric vscode extesion)
    get saveable(): Saveable {
        return this._modelRef?.object;
    }
}
```

An example of a registerWebviewPanelSerializer in the vscode extension code:
```
let command = vscode.window.registerWebviewPanelSerializer(viewType, {
	async deserializeWebviewPanel(webviewPanel: vscode.WebviewPanel, state: any) {
		// `state` is the state persisted using `setState` inside the webview
		//console.log(`Got state: ${state}`);
		// Reset the webview options so we use latest uri for `localResourceRoots`.
		webviewPanel.webview.options = getWebviewOptions(context.extensionUri);
	}
});
context.subscriptions.push(command);
```

I will open a PR to fix the saveable issue in the CustomEditorWidget class.

**Comment by pisv** [comment]
Just a note that I'm working on a fix.

**Comment by msujew** [comment]
@pisv Just a quick FYI: We had a similar issue while implementing the notebook support for Theia. We introduced the `DelegatingSaveable` for this, which might be useful for your fix.

**Comment by pisv** [comment]
@msujew Sure, my fix is actually based on using the `DelegatingSaveable` :-) Thank you!

**Comment by msujew** [comment]
@pisv I think that's perfectly fine, just make sure to include testing steps for all the things you have fixed :)

**Comment by pisv** [comment]
I have submitted PR #13916, which contains a fix for this issue.
