### ISSUE TITLE
playwright: tests fail on MacOS

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10793]
#### Bug Description:

The playwright tests (https://github.com/eclipse-theia/theia/pull/10494) do not pass on macOS:

```
...
[playwright]   10 failed
...
[playwright]   10 skipped
[playwright]   28 passed (12m)
[playwright] yarn -s --cwd examples/playwright ui-tests-ci exited with code 1
```

I have not tested on windows, but since CI is only run on linux it is possible that it might also be problematic.

#### Steps to Reproduce:

1. on macOS run:
    a. perform `yarn`
    b. perform `yarn browser build`
    c. perform `yarn test:playwright`
3. confirm that the tests do not all pass, some are also skipped

#### Additional Info:

- https://github.com/eclipse-theia/theia/discussions/10790#discussioncomment-2245940

**Comment by ndoschek** [comment]
Hi! I had a look at the playwright tests and fixed them for MacOS and Windows. They failed mostly due to path issues (Windows) and differing shortcuts (MacOS). See #10826
