### ISSUE TITLE
Add ability to pass a QuotedString as a command to tasks.executeTask 

### ISSUE THREAD

**Issue by jdmchp** [eclipse-theia/theia#10805]
The motivation behind this request is to make [makefile-tools extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools) work under Theia. Currently the extension fails to execute the make commands. Any guidance on how to do a PR to allow commands to be `ShellQuotedString`s would be greatly appreciated.

### Feature Description:

This is because [this code](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/plugin/type-converters.ts#L894) specifically disallows passing a command that is not a `string`. The error message shows that `ShellQuotedStrings`s are not handled. And the makefile-tools extension [specifically](https://github.com/microsoft/vscode-makefile-tools/blob/main/src/make.ts#L328) passes the command as a `ShellQuotedStrings`

As an experiment, I changed [this code](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/plugin/type-converters.ts#L894) to allow a `ShellQuotedString` to be handled:
```
    const command = execution.command;
    if (typeof command === 'string' || (command && typeof command.value === 'string')) {
        taskDto.command = command;
        taskDto.args = getShellArgs(execution.args);
        return taskDto;
    } else {
        throw new Error('Converting ShellQuotedString command is not implemented');
    }
```
And I saw that the underlying task handler correctly ran the command (in this case `command.value='make', 
command.quoting=vscode.ShellQuoting.Strong`).

**Comment by vince-fugnitto** [comment]
>  Any guidance on how to do a PR to allow commands to be ShellQuotedStrings would be greatly appreciated.

@jdmchp thank you for the interest, if you're looking on how to contribute please see:

- https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md
- https://github.com/eclipse-theia/theia/blob/master/doc/pull-requests.md
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

It shouldn't be too complicated to contribute, please let us know if you have any questions :)

**Comment by jdmchp** [comment]
Thanks @vince-fugnitto .
In looking at how [args](https://github.com/eclipse-theia/theia/blob/6d67d664bd3f679fca68be51d06d360a115decb2/packages/plugin-ext/src/plugin/type-converters.ts#L932-L949) are handled, I noticed that if they are `theia.ShellQuotedString`s the code simply keeps the `value` and ignores the `ShellQuoting`.
Then later on in the [backend](https://github.com/eclipse-theia/theia/blob/6d67d664bd3f679fca68be51d06d360a115decb2/packages/task/src/node/process/process-task-runner.ts#L208-L218), both args and command are converted into `ShellQuotedStrings` with `ShellQuoting.Strong`.
So, my idea is to create a simple PR where the `command` is treated the same as the `args`.
