### ISSUE TITLE
Playwright tests affect user's config

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#10800]
### Bug Description:

The Playwright tests currently run without setting the `THEIA_CONFIG_DIR` environment variable, so they affect the user's general configs, including recent workspaces.

### Steps to Reproduce:

1. Run Playwright test suites locally.
2. Start the Theia browser app.
3. Observe that it opens in some nonsense directory like `/var/folders/ch/y1zm8h2574j01_f85j6yy_l00000gn/T/cloud-ws-AHRyyR`

### Additional Information

- Operating System: MacOS
- Theia Version: `master` (9a02be64d97095ca9a2e442f337d05e46dc546ab)

**Comment by vince-fugnitto** [comment]
I can confirm, after executing the tests locally my `recentworkspace.json` file looks like the following:

```ts
{
   "recentRoots":[
      "file:///tmp/cloud-ws-D88xU6",
      "/tmp/cloud-ws-pPwmWn",
      "/tmp/cloud-ws-fm4YaO",
      "/tmp/cloud-ws-NPT4hm",
      "/tmp/cloud-ws-fqw4kE",
      "/tmp/cloud-ws-vu0zC4",
      "/tmp/cloud-ws-B4lMBH",
      "/tmp/cloud-ws-VJ7j6V",
      "/tmp/cloud-ws-b5LfGJ",
      "/tmp/cloud-ws-xJnOGG",
      "/tmp/cloud-ws-ryXEQf"
   ]
}
```

I started by performing `rm -rf ~/.theia`.
