### ISSUE TITLE
Focus Editor and Toggle Terminal Commands

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#10803]
### Bug Description:

Two issues related to keyboard-first users:
### Missing workbench.action.terminal.toggleTerminal command
- In VSCode, ctrl+\` toggles the bottom panel and ensures focus is applied to the *terminal*, 
- In Theia ctrl+j toggles the bottom panel while ctrl+\` opens the bottom panel and adds a *new* terminal. This means that using ctrl+\` always results in a new terminal, which is not really expected. ctrl+j toggles the bottom panel, but does not apply focus to the "terminal" tab. So there is currently no equivalent way to toggle between an editor view and the terminal *and* switch focus

### Missing workbench.action.focusFirstEditorGroup, workbench.action.focusSecondEditorGroup, etc.
- In VSCode you can switch editor *groups* using ctrl+[1-9] while also switching focus to that editor. This functionality is missing from Theia

### Steps to Reproduce:

1. The description above should be self explanatory. Try both behaviors in the two different IDEs and also search for the missing commands in the keyboard shortcuts UI.

### Additional Information

- Operating System: Linux
- Theia Version: Master

**Comment by jaimemartinagui** [comment]
I am also looking for this option. There is no way, afaik, to toogle appropriately between the editor and the terminal as in VSCode, as the focus does not change accordingly.

**Comment by vince-fugnitto** [comment]
@jaimemartinagui thank you for the feedback, are you interested in possibly contributing the `workbench.action.terminal.toggleTerminal` command to the framework with the guidance of a contributor? It should not be too complicated.

**Comment by jaimemartinagui** [comment]
Thank you for your response @vince-fugnitto. I would be happy to give it a try.

**Comment by vince-fugnitto** [comment]
> Thank you for your response @vince-fugnitto. I would be happy to give it a try.

@jaimemartinagui no problem, let us know if you need any help, the idea would be to register a command here:

https://github.com/eclipse-theia/theia/blob/1972f21c93e510dcff3957fdf9f9c01556bc28ca/packages/terminal/src/browser/terminal-frontend-contribution.ts#L331

And properly handle how the command should behave using the available methods at your disposal.

Given the fact that our implementation of terminals is quite different than vscode as we can have separate terminals in any area of the workbench layout, we would need to adjust our implementation to handle different use-cases. What I'm thinking is the following:

| # | Use-Case | Expectation |
|:---:|:---|:---|
| 1 | no terminal exists| create a new terminal in the bottom-area |
| 2 | terminal exists - inactive (hidden) | activate last known terminal |
| 3 | terminal exists - active (in the bottom-area | hide the bottom area |
| 4 | terminal exists - active (not in the bottom-area ) | open a new terminal in the bottom area |

**Comment by jaimemartinagui** [comment]
Perfect @vince-fugnitto, I'll be looking at it and let you know if any doubts.

**Comment by jaimemartinagui** [comment]
Hello @vince-fugnitto. I would need some help to implement this new option. I have introduced the new command and the keybinding, but I am not able to find how to approach the 4 scenarios you mentioned in your last message.

**Comment by vince-fugnitto** [comment]
> Hello @vince-fugnitto. I would need some help to implement this new option. I have introduced the new command and the keybinding, but I am not able to find how to approach the 4 scenarios you mentioned in your last message.

No problem :) I would take a look at [ApplicationShell](https://eclipse-theia.github.io/theia/docs/next/classes/core.ApplicationShell-3.html) and [TerminalService](https://eclipse-theia.github.io/theia/docs/next/modules/terminal.html#TerminalService-1) which should provide you with the necessary methods to achieve the 4 use-cases.

**Comment by jaimemartinagui** [comment]
Hello @vince-fugnitto! Thank you for your help. Let me inform you about the way in which I am creating the new command (and shortcut):

- Case 1: if no terminal exists, a new one is created.
- Case 2: if a terminal exists, but is hidden, expand the bottom panel and set the focus to it.
- Case 3: if a terminal exists and is visible, but without the focus, set the focus to it.
- Case 4: if a terminal exists, is visible and has the focus, collapse the bottom panel and set the focus back to the editor.

I have been able to achieve all these functionalities except the part of managing the focus in cases 2, 3 and 4. I have tried several things, mainly using `this.shell.activateWidget(widget.id)` as I have seen that is used in other methods. However, I am receving a weird error that I'm not able to solve.

Any help would be appreciated.

**Comment by vince-fugnitto** [comment]
@jaimemartinagui sounds great! You can open a pull-request, even as a draft if you’re not yet ready and we’d be happy to take a look and review and hopefully resolve the last little bit of functionality :)

**Comment by jaimemartinagui** [comment]
Hi @vince-fugnitto, I have already opened the PR as a draft. Please let me know any updates or if anything is missing. Thanks!

**Comment by jaimemartinagui** [comment]
Hello @vince-fugnitto, there are some details to be improved on the draft PR I created and I am a bit stuck with it. Thank you in advance for your help.
