### ISSUE TITLE
Browser example failed to load webview extension, if launches with ip address instead of `localhost` address

### ISSUE THREAD

**Issue by mbilal100** [eclipse-theia/theia#10825]
### Bug Description:
Browser example failed to load webview extension, if launches with some ip address instead of `localhost` address

### Steps to Reproduce:
1. Start browser example with your machine ip address, in my case it is 192.168.8.101
```
./node_modules/.bin/theia start --plugins=local-dir:../../plugins -h 192.168.8.101
```
2. Install vscode webview-sample [extension](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample) 
3. Try to run the `Cat Coding: Start cat coding session` to create the webview from command palette
4. Unable to see any webview

Webview window create successfully if launch on `localhost` i.e
```./node_modules/.bin/theia start --plugins=local-dir:../../plugins -h localhost```

### Additional Information
- Operating System: Ubuntu 20.04
- Theia Version: Version: 1.23.0

**Comment by vince-fugnitto** [comment]
@mbilal100 thank you for the issue, please see the following [discussion](https://github.com/eclipse-theia/theia/discussions/10605#discussioncomment-1941074).

**Comment by vince-fugnitto** [comment]
Closing due to https://github.com/eclipse-theia/theia/issues/10825#issuecomment-1056888671.
