### ISSUE TITLE
Incorrect usage of `URI#path.toString()` on Windows

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#10830]
### Description

This issue is meant to collect incorrect usages of displaying URI strings on Windows systems. Simply calling `URI#path.toString()` usually results in incorrectly formatted paths. See #10591. See also the following as an example:

![example](https://user-images.githubusercontent.com/4377073/156186246-8a3ce710-55be-4612-a24c-eadf2d6e21fd.png)

- [x] [file-tree-widget.tsx](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/filesystem/src/browser/file-tree/file-tree-widget.tsx#L98)
- [ ] [workspace-frontend-contribution.ts](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/workspace/src/browser/workspace-frontend-contribution.ts#L470)
- [ ] [search-in-workspace-result-tree-widget.tsx](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L978)
- [ ] [scm-tree-widget.tsx](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/scm/src/browser/scm-tree-widget.tsx#L687) and [here](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/scm/src/browser/scm-tree-widget.tsx#L530)
- [ ] [resource-property-view-tree-widget.tsx](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/property-view/src/browser/resource-property-view/resource-property-view-tree-widget.tsx#L114)
- [ ] [preferences-contribution.ts](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/preferences/src/browser/preferences-contribution.ts#L229)
- [ ] [problem-decorator.ts](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/markers/src/browser/problem/problem-decorator.ts#L132)
- [ ] [location-renderer.tsx](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/filesystem/src/browser/location/location-renderer.tsx#L281) and [here](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/filesystem/src/browser/location/location-renderer.tsx#L190)
- [ ] [editor-widget-factory.ts](https://github.com/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/editor/src/browser/editor-widget-factory.ts#L74)
- [ ] [debug-source.ts](https://github.dev/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/debug/src/browser/model/debug-source.ts#L66)
- [ ] [label-provider.ts](https://github.dev/eclipse-theia/theia/blob/481d2cf0edd33d8495662b9589b9232dcd6c8b34/packages/core/src/browser/label-provider.ts#L182)
- [ ] [preference-file-input.ts](https://github.dev/eclipse-theia/theia/blob/7b8d3b71f4511fa55e11f739fa24375b2e1360e4/packages/preferences/src/browser/views/components/preference-file-input.ts#L96)

### Additional Information

- Operating System: Windows
- Theia Version: 1.23.0

**Comment by tsmaeder** [comment]
@msujew what's the problem with calling uri.path.toString()? Can you give an example that shows the problem?

**Comment by tsmaeder** [comment]
Also, doing a workspace find for ".path.toString()" reveals many more occurrences than the above. How did you come about the list above?
