### ISSUE TITLE
Getting Started Widget doesn't accept focus

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#10878]
### Steps to Reproduce:

1. Open the application with no workspace.
2. Try to focus the Getting Started Widget.
3. Observe that the tab is never marked active (brighter text) and you see a log:
```
root WARN Widget was activated, but did not accept focus after 2000ms: getting.started.widget
```

in order for a widget to accept focus it needs to implement onActivateRequest and needs something to focus on. The same was done in blueprint for the same view:

https://github.com/eclipse-theia/theia-blueprint/pull/201

### Additional Information

- Operating System: MacOS, Electron
- Theia Version: `master` (e62fd33ce46055d1633d781c08bf5852535f53c5)

**Comment by JonasHelming** [comment]
I also saw this behavior with the example widget generated by the Yeoman template. @vince-fugnitto : You marked this with good_first_issue, any idea what is causing this? I am pretty sure, this is a rather new behavior.

**Comment by vince-fugnitto** [comment]
> I also saw this behavior with the example widget generated by the Yeoman template. @vince-fugnitto : You marked this with good_first_issue, any idea what is causing this? I am pretty sure, this is a rather new behavior.

@JonasHelming since it is a simple fix, in order for a widget to accept focus it needs to implement `onActivateRequest` and needs something to focus on. The same was done in `blueprint` for the same view:

- https://github.com/eclipse-theia/theia-blueprint/pull/201

**Comment by WhiteHsu** [comment]
Hello @JonasHelming @vince-fugnitto 
This bug is interesting, and I would like to learn more about Theia, may I pick up this bug as my first task of this project? Thank you very much.  :-)

**Comment by JonasHelming** [comment]
Yes, we believe it would be a great first task, so please go ahead!

**Comment by WhiteHsu** [comment]
Thanks! Doing today!

**Comment by JonasHelming** [comment]
@WhiteHsu Thank you for working on this!
I think the warning is the main issue described in the bug report, it is fine to keep the current bug until the warning does not show up anymore.

**Comment by WhiteHsu** [comment]
@JonasHelming got it and thanks for feedback!

Do you suggest another ticket for me?  :-)

**Comment by JonasHelming** [comment]
Are you looking for a new ticket to contribute? I believe @vince-fugnitto commented on this one that there is no element on the page that can accept focus. Does it maybe make sense to add one?

**Comment by WhiteHsu** [comment]
Thanks @JonasHelming . Yes I've amended codes accordingly into the PR, and it seems workable without the warning msg. Pls kindly help review and feedback. Thank you.  :-)

**Comment by WhiteHsu** [comment]
Many thanks @vince-fugnitto @JonasHelming !

Do you recommend another ticket for me as the 2nd task to get familiar with Theia?  :-)

**Comment by JonasHelming** [comment]
Hi,

you can browse the "good first issues" or the "hackathon" label for more issues to get started.

Best regards,
Jonas
