### ISSUE TITLE
Regular translation update

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#10885]
I want to use this issue to have discussions on how to perform regular updates to our translation files.

### Proposal

My current idea is to use the CI to create a commit on a separate branch for every commit to `master`. This branch is always rebased to the latest `master` and runs the `theia nls-extract` and `theia nls-localize` commands to produce updated localization files. These can be merged/cherry-picked into the release-branch and will be then available for every release.

**Comment by msujew** [comment]
@vince-fugnitto regarding API-keys: I would simply store my API-key as a secret in the GitHub repo, which is then used on every GitHub actions workflow. So, from that perspective, it doesn't matter whether it's on a per-PR or per-release basis, since they use the stored API-key anyway. Contributors to Theia shouldn't have to touch that anyway.

**Comment by vince-fugnitto** [comment]
@msujew since we have the free API afaik and we were to do the per pr-basis we might need to check that we do not hit the limit for the month. I assume we should only translate the delta and not the whole codebase again?

**Comment by msujew** [comment]
@vince-fugnitto the command always works on a delta, since I anticipated this ;)

**Comment by msujew** [comment]
@vince-fugnitto Yeah, I will create a PR for this. Didn't have time to take care of this issue yet.
