### ISSUE TITLE
InitiallyCollasped property isn't working on Open Editors widget

### ISSUE THREAD

**Issue by Tpuljak** [eclipse-theia/theia#10928]
### Steps to Reproduce:

1. Open the file navigator widget
2. Observe that the Open Editors "subwidget" is expanded by default

This occurs even though the `initiallyCollapsed` option is set to true when creating the widget.
https://github.com/eclipse-theia/theia/blob/b1bd7bd528c257652f29451d168b750840c22e45/packages/navigator/src/browser/navigator-widget-factory.ts#L46

### Additional Information

The Open Editors widget has been a UX pain since it takes up half of the navigator widget when the IDE starts and it's pretty confusing to first-time users.

It would be great if this can be controlled through a preference (whether the widget is initially collapsed, hidden or expanded) and I would happily submit a PR to resolve this (with some guidance).

I tried to work around this with some container rebinding, but with no luck and I would appreciate some insight into why the `initiallyCollapsed` property does not work for this widget.

- Operating System: Mac
- Theia Version: 1.23.0

**Comment by vince-fugnitto** [comment]
@Tpuljak I believe the it is true by default in vscode as well (which is what we aim to support by default). You can customize this behavior in your downstream application if needed. I wouldn't necessarily be against having a preference for it, but I think would likely be better updated downstream?

cc @colin-grant-work any thoughts?

**Comment by colin-grant-work** [comment]
It looks like the reason it is getting uncollapsed even though its options say it should be collapsed initially is that it is added to the container before the `NavigatorWidget`, so it is the sole widget in the `ViewContainer`, and a lone `ViewContainerPart` is automatically uncollapsed. I've created a PR to fix it.
