### ISSUE TITLE
Theia@Next: Production Build leads to null access in monaco-theming-service.ts

### ISSUE THREAD

**Issue by jfaltermeier** [eclipse-theia/theia#10927]
### Bug Description:
Building a theia electron application with the next version of Theia  in production mode leads to the following error when starting the electron app. The application is stuck on the preload animation as a consequence. 
It might be possible to open the Developer Tools with Ctrl+Shift+I or Ctrl+Alt+I. 
You may also log console errors to the terminal via an environment variable: `ELECTRON_ENABLE_LOGGING=1`

The following error is logged to the console by the renderer process:

```
index.js:98 TypeError: Cannot read properties of null (reading 'classList')
    at Function.updateBodyUiTheme (monaco-theming-service.ts:160)
    at Function.init (monaco-theming-service.ts:141)
    at Object.47922 (monaco-frontend-module.ts:76)
    at i (bootstrap:19)
    at index.js:62
```

It seems that at this point, the document's body was not loaded yet and accessing the classList leads to the error. 
```
        document.body.classList.add(uiTheme);
```

<s>I can't reproduce it with the electron example from the main Theia repository. It seems like a race condition. </s>

### Steps to Reproduce (Theia Electron Example App):
1. Change `"bundle": "theia build --mode development",` to `"bundle": "theia build",` in `theia/examples/electron/package.json`
2. `yarn && yarn build`
3. `yarn electron start`

### Steps to Reproduce (Blueprint):

1. Checkout https://github.com/eclipse-theia/theia-blueprint
4. Run `yarn && yarn update:next` to update versions to next
5. Build with `yarn && yarn electron package:preview`
6. Launch blueprint

### Additional Information

- Operating System:
- Theia Version: next

**Comment by jfaltermeier** [comment]
Update: I was trying to guard against this null access but then ran into different issues after that. 
After some investigation I could narrow it down to the build mode. 

Building with `theia build --mode development` works. 
Using `theia build` leads to the errors. 

So by changing 
`"bundle": "theia build --mode development",` 
to
`"bundle": "theia build",`
in
`theia/examples/electron/package.json`
this may be reproduced with the electron example application in the repository as well.

**Comment by eugene-f02** [comment]
I'm seeing the same bug in the browser theia as well
