### ISSUE TITLE
Please add MIT licensed extensions to open-vsx

### ISSUE THREAD

**Issue by kevin-s-wang** [eclipse-theia/theia#10952]
### Feature Description:
There's a [Jupyter](https://open-vsx.org/extension/ms-toolsai/jupyter) extension exists on open-vsx but its dependencies are missing. However, I've checked on the license of these extensions, they are all MIT licensed. Could you help add these extensions to open-vsx?

Here are the github repositories of the extensions:
https://github.com/microsoft/vscode-notebook-renderers
https://github.com/microsoft/vscode-jupyter-keymap

**Comment by vince-fugnitto** [comment]
@kevin-s-wang thank you for reporting the issue, unfortunately publishing individual extensions it is out of scope for this repository (theia framework).

You should instead contact the authors of the extensions for them to publish their extensions themselves, or [publish yourself](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) if they are unresponsive according to the documentation.

- https://github.com/open-vsx/publish-extensions#when-to-add-an-extension

**Comment by kevin-s-wang** [comment]
@vince-fugnitto  Thank you for your response. Just one more question, does theia support local  *.vsx extensions rather than downloading from open-vsx.org when building a customized IDE?

**Comment by vince-fugnitto** [comment]
> Just one more question, does theia support local *.vsx extensions rather than downloading from open-vsx.org when building a customized IDE?

@kevin-s-wang yes, by default the extensions-view will use the `open-vsx` registry to install extensions, however at build time you have much more flexibility.

The framework supports the idea of builtin extensions, meaning extensions which are available by default in your application. You can use the [download cli](https://github.com/eclipse-theia/theia/tree/master/dev-packages/cli#downloading-plugins) script to pull an extension at build time to your application by referencing them in your `package.json` by URL (does not need to be open-vsx, any URL where the extension might be hosted) like so:

https://github.com/eclipse-theia/theia/blob/51443155c8c860c7d517e2f692336e149a8b4988/package.json#L91-L92

Or you can simply add the extension (programatically with a script or manually) to the folder that is referenced on startup.
In our examples we use the `plugins` folder to keep all builtin extensions, and we reference the folder on start:

https://github.com/eclipse-theia/theia/blob/51443155c8c860c7d517e2f692336e149a8b4988/package.json#L90

https://github.com/eclipse-theia/theia/blob/51443155c8c860c7d517e2f692336e149a8b4988/examples/electron/package.json#L67

**Comment by kevin-s-wang** [comment]
@vince-fugnitto Thank you very much for the detailed information. With your help, I now know how to build my very first customized theia IDE. I'll close this issue now.
