### ISSUE TITLE
monaco: adjust styling of toggle commands

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10960]
#### Bug Description:

The styling of toggled commands need to be adjusted, they are currently using a serif font.

![image](https://user-images.githubusercontent.com/40359487/160846061-9913cbeb-1c37-4c7e-bc4b-846b479e9c8a.png)

### Steps to Reproduce:

1. start the application
2. trigger the quick-command menu
3. search for `toggle minimap`
4. notice the incorrect styling when toggled

**Comment by vince-fugnitto** [comment]
@msujew after updating the styling I still feel as though the label looks off compared to the check, what do you think?

![image](https://user-images.githubusercontent.com/40359487/160848910-9ff70ccc-8e27-429a-8880-58e0bff3fd8a.png)

**Comment by msujew** [comment]
@vince-fugnitto Yeah, I believe that's also happening for menus. I had to [apply a scaling](https://github.com/eclipse-theia/theia/blob/ee9a07109922a0bb903558eb7d833dfdf7e1b40b/packages/core/src/browser/style/menus.css#L206-L209) of `0.8` there.
