### ISSUE TITLE
Support VS Code task configuration format

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#1096]
Our current tasks.json format is somwwhat similar but not as rich. Supporting the VS Code format would open the door to being able to use existing tasks from that IDE. Even a partial support could be worthwhile. 

Our current format:
https://github.com/theia-ide/theia/tree/master/packages/task

VS Code format: 
https://code.visualstudio.com/docs/editor/tasks-appendix#_schema-for-tasksjson

to consider: Explore future direction of the task runner system
https://github.com/Microsoft/vscode/issues/15179

**Comment by akosyakov** [comment]
Just stumbled on it, trying to run first `typescript` task from VS Code docs: https://code.visualstudio.com/docs/editor/tasks

Also i could not find a command to configure tasks and had to create `.theia/tasks.json` file myself. End users don't know it.

**Comment by tsmaeder** [comment]
I think we do support the format now.
