### ISSUE TITLE
Support "on start" tasks

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#1097]
ATM a task are user-triggered. 

It would be useful to support tasks that are executed automatically upon a workspace being "started". e.g. initial cloning of git repos.

**Comment by svenefftinge** [comment]
I wonder whether that should be a flag in the tasks description or better be a command line argument to start theia. There might be different states of "started", e.g. after first cloned vs. after revisiting an already built workspace.

**Comment by hexa00** [comment]
IMO this should be part of a 'start' hook instead of part of the task itself.

**Comment by marcdumais-work** [comment]
@svenefftinge with the current design, the reading/parsing of task configurations is done in the frontend, to simplify accommodating multiple clients that use the same workspace. When a client starts, it doesn't know if the workspace it's using was just created for its benefit or if was created a long time ago, and is already serving other client(s). So unless we only want a "on client started" type of tasks, this will not work. e.g. if we use 'on start' to clone git repos, we probably do not want that to happen every time a client connects.

Instead it feels like this could be done in the backend, where it's known or can be known what the workspace state is. e.g. ("starting for first time", "starting", "new client connected", 'shutting down', ...). @hexa00 is that approximately what you had in mind? Like you said, these hooks could be generalized and be independent of tasks, and could optionally trigger tasks, if needed.

**Comment by hexa00** [comment]
@marcdumais-work yes that feels like what i had in mind however I'm not sure that this should be in the backend.

Seems like considering that most of the intelligence is in the frontend. The backend could send events and the frontend could act on them.

For example staring a task I think is better done from the frontend....

**Comment by vince-fugnitto** [comment]
Closing, I believe this is already supported. VS Code extensions can contribution tasks and trigger them on different activation events such as when the application is first started.
