### ISSUE TITLE
vscode: support `createLanguageStatusItem` API

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#10979]
#### Feature Description:

The goal is to support the `createLanguageStatusItem` VS Code API:

![image](https://user-images.githubusercontent.com/40359487/161274380-ac534e00-5ce8-46a2-90b5-c4edbcd938fc.png)

For reference [`vscode-builtin-typescript-language-features@1.62.3`](https://open-vsx.org/extension/vscode/typescript-language-features) uses this API and it fails to activate.

**Comment by colin-grant-work** [comment]
Part of #10819
