### ISSUE TITLE
vscode: Support `TypeHierarchy` APIs

### ISSUE THREAD

**Issue by CsCherrYY** [eclipse-theia/theia#10993]
### Feature Description:

We are working on supporting TypeHierarchy feature in [vscode-java](https://github.com/redhat-developer/vscode-java) extension via LSP and there is a WIP PR here: https://github.com/redhat-developer/vscode-java/pull/2376. The new version of `vscode-languageclient` (8.0.0+) requires API `TypeHierarchyItem` from `vscode` module, and in theia we found in https://eclipse-theia.github.io/vscode-theia-comparator/status.html, `TypeHierarchyItem` has not been supported yet, which causes the extension fail to activate in Theia. 

Hope Theia can support the TypeHierarchy related APIs so the new implementation can work. 

- TypeHierarchyItem
- TypeHierarchyProvider
- registerTypeHierarchyProvider

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/11694.
