### ISSUE TITLE
Support globally-defined tasks

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#1099]
With the current implementation, tasks can be configured on a per-workspace basis: if the following file exists, it will be read/parsed by the client, upon starting to use that workspace: 
\<workspace root\>/.theia/tasks.json .  

It feels like it would be useful to be able to define tasks that are applicable more widely than a given workspace. 

We could take inspiration from the user preferences and use [ "user-storage" ](https://github.com/theia-ide/theia/tree/master/packages/userstorage) to store those

**Comment by svenefftinge** [comment]
Do you have any practical scenarios, where you would want to do that?

**Comment by vince-fugnitto** [comment]
It may come soon as it's a VS Code Insiders feature: https://github.com/microsoft/vscode/issues/60043#issuecomment-572932936
@marcdumais-work the visionary! :+1:

**Comment by tsmaeder** [comment]
@marcdumais I filed Support User Level Tasks #7446. Shall we merge the issues?

**Comment by tsmaeder** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/7446
