### ISSUE TITLE
Get more detailed language info

### ISSUE THREAD

**Issue by AlbyIanna** [eclipse-theia/theia#11010]
### Feature Description:
When asking the backend which are the languages available for localization, it's currently possible to do so calling [getAvailableLanguages()](https://github.com/eclipse-theia/theia/blob/master/packages/core/src/node/i18n/localization-provider.ts#L50-L58) in the LocalizationProvider.

This method returns only an array of _language ids_. I would really like this method to return a more detailed object, containing at least the language name (and maybe the localized language name too).

**Comment by msujew** [comment]
@AlbyIanna The [`LocalizationProvider#loadLocalization`](https://github.com/eclipse-theia/theia/blob/ec7ed046b56f803490c85363ea47a09967cd57ff/packages/core/src/common/i18n/localization.ts#L24) method should provide you with all the meta data that each language pack provides, since it returns an instance of `Localization`:

https://github.com/eclipse-theia/theia/blob/ec7ed046b56f803490c85363ea47a09967cd57ff/packages/core/src/common/i18n/localization.ts#L27-L33

**Comment by AlbyIanna** [comment]
@msujew [LocalizationProvider#loadLocalization](https://github.com/eclipse-theia/theia/blob/ec7ed046b56f803490c85363ea47a09967cd57ff/packages/core/src/common/i18n/localization.ts#L24) also returns the translations. If I want to show a list of all the available languages, I have to call [LocalizationProvider#loadLocalization](https://github.com/eclipse-theia/theia/blob/ec7ed046b56f803490c85363ea47a09967cd57ff/packages/core/src/common/i18n/localization.ts#L24) multiple times from the frontend, resulting in the backend returning thousands and thousands of strings, which I guess could impact on performances. I think it would be better to have a method that returns only the language metadata, without the translations.

**Comment by vince-fugnitto** [comment]
@AlbyIanna note that as an alternative you can use `localizationProvider['localizations']` to return you the map (even if it is `protected` it can be accessed).

https://github.com/eclipse-theia/theia/blob/1819ebf534c2f8685a61ab5409a708fb95293718/packages/core/src/node/i18n/localization-provider.ts#L23

**Comment by msujew** [comment]
@AlbyIanna I agree with @vince-fugnitto, the cleanest way to utilize `localizationProvider['localizations']` in the frontend would be to create a second proxy service, which returns only the localization meta data to the frontend. Alternatively, you could also override the default `LocalizationProvider` with an additional method that you could call, though that would require sneaking around the type definition of `AsyncLocalizationProvider` in the frontend.

While, we could add a new `getMetadata(localeId: string): { languageName?: string, localizedLanguageName?: string }` method, it would be unused in the framework itself, something which we should try to avoid.

**Comment by AlbyIanna** [comment]
> @AlbyIanna note that as an alternative you can use localizationProvider['localizations'] to return you the map (even if it is protected it can be accessed).

@vince-fugnitto I am not able to use `this.localizationProvider['localizations']` in the frontend as you suggested. TypeScript is complaining:
```
Property 'localizations' does not exist on type 'AsyncLocalizationProvider'.
```
Am I missing something?


> Alternatively, you could also override the default LocalizationProvider with an additional method that you could call, though that would require sneaking around the type definition of AsyncLocalizationProvider in the frontend.

@msujew that's what I tried, but it's kind of cumbersome to extend a class and rebind everything on both the frontend and the backend. 

> While, we could add a new getMetadata(localeId: string): { languageName?: string, localizedLanguageName?: string } method, it would be unused in the framework itself, something which we should try to avoid.

I believe this is a feature that is useful for the framework, because in the frontend I think it's very common to show the language names. I can't think of a situation where you want to show only the language ID to a user.

**Comment by AlbyIanna** [comment]
> It shouldn't be necessary to rebind anything in the frontend. But it breaks the contract created by `AsyncLocalizationProvider`, which then requires the use of `any` to access the newly defined method.

@msujew my fault then, I'll try to clean up a little my solution!

> Anyway, I guess it doesn't hurt to have another method for this use case. I'll create a PR for this later.

That would be great, thanks!
