### ISSUE TITLE
File search in Electron extremely slow on MacOS

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11035]
### Bug Description:

In Electron on MacOS, the quick input file search is extremely slow. It seems as though the search doesn't begin until several seconds after you have typed in a query.

### Steps to Reproduce:

1. On MacOS, open the Electron application.
2. Search for a file in your workspace.
3. Observe that for some time, nothing happens.
4. After a few seconds, the search will execute.

### Additional Information

![file-search-screencast](https://user-images.githubusercontent.com/62660806/163624043-32dc1c68-a5c7-4c6b-86d8-748f304a1f17.gif)

- Operating System: MacOS, Electron
- Theia Version: 4381be37a65f1be9d11d22391753e0c82aca5cea

**Comment by vince-fugnitto** [comment]
I can confirm that I also experience the issue when using macOS.

**Comment by JonasHelming** [comment]
It is maybe worth to retest this on https://github.com/eclipse-theia/theia/pull/11011

**Comment by colin-grant-work** [comment]
@JonasHelming, gave it a try, and it doesn't appear to make a difference. I don't think the issue is speed of communication between front- and backends or it wouldn't be peculiar to MacOS. I'll take a closer look tomorrow or next week.

**Comment by vince-fugnitto** [comment]
Confirmed it works well on macOS.
