### ISSUE TITLE
Question: VS Code API compatibility of `ProviderResult`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11041]
The [vscode-theia-comparator report](https://eclipse-theia.github.io/vscode-theia-comparator/filtered-status.html) shows `ProviderResult` as incompatible on master, but considered it as compatible in the last Theia release.

This seems to be related to change https://github.com/eclipse-theia/theia/commit/e6b57ba4edabf797f3b4e67bc2968cdb8cc25b1e by @alvsan09:
https://github.com/eclipse-theia/theia/blob/e6b57ba4edabf797f3b4e67bc2968cdb8cc25b1e/packages/plugin/src/theia.d.ts#L6882

Before it was defined as follows:
```typescript
export type ProviderResult<T> = T | undefined | PromiseLike<T | undefined>;
```

In VS Code it is defined as follows:
```typescript
export type ProviderResult<T> = T | undefined | null | Promise<T | undefined | null>;
```

So adding `null` as done by the change linked above, certainly makes sense.
Also, given that `Thenable` is a sub interface of `PromiseLike`, and `PromiseLike` was deemed to be OK by the report, it is surprising that it is now reported as incompatible. If at all `Promise` and `PromiseLike` could be considered as incompatible (missing `catch` in `PromiseLike`).

Anyway, @alvsan09 I was wondering, what was the reason for changing `PromiseLike` to `Thenable`?
Depending on that, we'll either see if we can adapt the vscode-theia-comparator or maybe change back to `PromiseLike` if there was no particular reason?

Thanks!

**Comment by paul-marechal** [comment]
> In VS Code it is defined as follows:
> 
> ```ts
> export type ProviderResult<T> = T | undefined | null | Promise<T | undefined | null>;
> ```

I don't see that?

- [`ProviderResult` definition](https://github.com/microsoft/vscode/blob/a576b4c066521fe52b248eac9b21e6a01e7d22bd/src/vscode-dts/vscode.d.ts#L2135)
- [`Thenable` definition](https://github.com/microsoft/vscode/blob/a576b4c066521fe52b248eac9b21e6a01e7d22bd/src/vscode-dts/vscode.d.ts#L15354-L15369)
