### ISSUE TITLE
Default file icon theme is not applied correctly

### ISSUE THREAD

**Issue by Tpuljak** [eclipse-theia/theia#11045]
### Bug Description:
Setting the default file icon theme to `theia-file-icons` will still result in `none` being applied once the IDE is started.

<img width="1390" alt="Screenshot 2022-04-19 at 21 25 27" src="https://user-images.githubusercontent.com/26512078/164080780-720f8e29-ddf6-4a10-8fd1-e14f409a826f.png">

Might be fixed with https://github.com/eclipse-theia/theia/pull/11028, but I still think it should be checked out.

### Steps to Reproduce:

1. Set `"workbench.iconTheme": "theia-file-icons"` in the `package.json`
2. Startup the IDE
3. Observe that no file icons are applied

### Additional Information

- Operating System: MacOS
- Theia Version: 1.24.0

**Comment by vince-fugnitto** [comment]
@Tpuljak thank you for reporting the issue, do you still experience the problem on `master`?

I verified with `master` and this is what I see:


https://user-images.githubusercontent.com/40359487/164087790-7b0033c7-ef4c-4c10-8b7a-74cb4ef95d0c.mov

**Comment by Tpuljak** [comment]
Hi @vince-fugnitto. That, of course, works fine.

I was referring to setting the default preference in the `package.json` file like so:

```json
"theia": {
    "frontend": {
      "config": {
        "applicationName": "APP",
        "preferences": {
          "workbench.iconTheme": "theia-file-icons"
        },
        "warnOnPotentiallyInsecureHostPattern": false
      }
    },
    "backend": {
      "config": {
        "warnOnPotentiallyInsecureHostPattern": false
      }
    }
  },
```

This kind of configuration results in `theia-file-icons` being set as a default for the workspace (as shown in my screenshot above) but not applied to the icons when loaded.

**Comment by vince-fugnitto** [comment]
@Tpuljak thanks for clarifying, in order to set the `defaultIconTheme` you should use the prop and not set the default preference:

```json
"theia": {
    "target": "electron",
    "frontend": {
      "config": {
        "applicationName": "Theia Electron Example",
        "defaultIconTheme": "theia-file-icons"
      }
    }
  },
```

https://github.com/eclipse-theia/theia/blob/1972f21c93e510dcff3957fdf9f9c01556bc28ca/dev-packages/application-package/src/application-props.ts#L79-L84

**Additional Info**
- https://github.com/eclipse-theia/theia/tree/master/dev-packages/cli#default-theme
- https://github.com/eclipse-theia/theia/blob/master/doc/changelogs/CHANGELOG-2020.md#1.5.0_declarative_default_themes

**Comment by Tpuljak** [comment]
Ah, okay. My bad on that one. Thanks for clarifying that @vince-fugnitto.

It might be useful to make a build warning for ambiguous cases like this one maybe 🤔.

**Comment by vince-fugnitto** [comment]
> It might be useful to make a build warning for ambiguous cases like this one maybe

We might be able to warn at runtime if a given configuration is not applied due to it being invalid, but to fail the build would likely be difficult and overkill. If you're interested you can open a new issue for the improvement and potentially contribute a pull-request :)

**Comment by Tpuljak** [comment]
I'll definitely try to contribute when I free up some time.
