### ISSUE TITLE
view in activity area cannot be dynamically controlled via enablement

### ISSUE THREAD

**Issue by jdmchp** [eclipse-theia/theia#11096]
### Bug Description:
When trying to use the [makefile](https://www.open-vsx.org/extension/ms-vscode/makefile-tools) extension in Theia,  I noticed that the icon for the extension was not shown in the activity bar. To 'force' it to appear, I had to toggle that specific view. The makefile view should be shown whenever a project containing a `Makefile` is open (and the makefile extension is loaded).
Here is a visual description (using eclipse-theia/theia):

![makefile_extension_needs_toggle](https://user-images.githubusercontent.com/100438651/166323753-992aac51-9778-44f8-a350-08816cdeb642.gif)

### Steps to Reproduce:
To try to reproduce the problem in a simpler environment, I created an [extension](https://github.com/jdmchp/show-enablement-issue) that enables a view based on the state a property.
```
     "viewsContainers": {
            "activitybar": [
                {
                    "id": "enablement_issue__viewContainer",
                    "title": "Enablement Issue",
                    "when": "enablement:enable",
                    "icon": "pass-filled.svg"
                }
            ]
        },
        "views": {
            "enablement_issue__viewContainer": [
                {
                    "id": "enablement.outline",
					"when": "enablement:enable",
					"name": "Show enablement issue"
                }
            ]
        }
```
Also, I created two commands: one to enable showing the extension (set `enablement:enable` to `true`) or hidinging it (set `enablement:enable` to `false`).

In this way I can change the value of the `when` clause. The [README.MD](https://github.com/jdmchp/show-enablement-issue/blob/main/README.md) in the repo shows that for vscode this is the observed behavior:

To reproduce:
1. build the  [extension](https://github.com/jdmchp/show-enablement-issue)
2. load the extension
3. ctrl-shift-p and execute "set enablement to true"

Here is a visual example using [Theia](https://github.com/jdmchp/show-enablement-issue/blob/main/theia_case.gif)

Here is the same example running in [vscode](https://github.com/jdmchp/show-enablement-issue/blob/main/vscode_case.gif)

### Additional Information

- Operating System: Linux, Linux 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/
- Theia Version: https://github.com/eclipse-theia/theia commit 92dcf245c498afd93e541f598e2540f8685e9287
- Or Theia-blueprint, version 1.25.0

**Comment by jdmchp** [comment]
@vince-fugnitto , @colin-grant-work , I ran using the fork with the fix:
```
$ git remote -v                                                                                                                                                                                    origin	https://github.com/colin-grant-work/theia.git (fetch)
origin	https://github.com/colin-grant-work/theia.git (push)
$ git rev-parse HEAD                                                                                                                                                                               
-parse HEAD- revert existing commits
cb8b05f67aca22239aa95649cd57ff7018e638a5
$ git status
 status
On branch bugfix/monaco-context-key-service
thing to commit, working tree clean
```
As you can see below, the originally reported issue is fixed:
![11096_fixed](https://user-images.githubusercontent.com/100438651/166707672-f5534f1a-a294-4da9-ae4a-3dc5cd076172.gif)
 Thanks!!!!

**Comment by colin-grant-work** [comment]
@jdmchp, thanks, glad to hear the fix is working. Hope to get it merged soon - just fixing some tests.
