### ISSUE TITLE
Plugin download duplicates extensions

### ISSUE THREAD

**Issue by ccorn** [eclipse-theia/theia#11109]
Summary: Processing `theiaPlugins` should add to `theiaPluginsExcludeIds` to avoid installing the same extension under different names (and perhaps versions).

Since release v1.25.0, Theia's toplevel `package.json` has changed `theiaPlugins` to replace a bunch of extension entries with a reference to an extension pack that bundles those extensions (and some more).

An additional parameter `theiaPluginsExcludeIds` allows to blacklist extension IDs that shall not be installed that way.

`theiaPlugins` is an associative array where the key determines the name of the subdirectory where the plugin gets installed, and the value is the extension URL.

`theiaPluginsExcludeIds` is an array (presumably with semantics of a set) containing VSX names (IDs) in the format `namespace.name`.

There seems to be no need for the `theiaPlugins` keys to match the associated VSX names, and traditionally the naming differs slightly.

If a plugin gets installed via an extension pack instead of directly via `theiaPlugins`, the subdirectory name to use for installation is the VSX name.

(I do hope that the naming of the keys has no big significance elsewhere. Otherwise, the switch to extension packs would have more consequences.)

Now `theiaPlugins` contains entries like

    "vscode-builtin-theme-kimbie-dark": "https://open-vsx.org/api/vscode/theme-kimbie-dark/1.62.3/file/vscode.theme-kimbie-dark-1.62.3.vsix",

to adjust theme versions.
However, the extension pack bundles `vscode.theme-kimbie-dark` too.
Consequently, the extension gets installed twice:

| Install location                         | Version |
|:-----------------------------------------|:--------|
| plugins/vscode-builtin-theme-kimbie-dark | 1.62.3  |
| plugins/vscode.theme-kimbie-dark         | 1.53.2  |

I suppose that this is unintended and should not be.

A quick fix would be to extract the VSX `namespace.name` from the URL in each `theiaPlugins` value and add it to the `theiaPluginsExcludeIds` array if that VSX name does not match the corresponding `theiaPlugins` key.
Here is a [jq] command to output the completed `theiaPluginsExcludeIds` array:

```sh
jq '(.theiaPluginsExcludeIds +
(.theiaPlugins | map_values(split("/") | .[4:6] | join(".")) |
 to_entries | map(select(.key != .value) | .value)
)) | unique' <package.json
```

[jq]: https://stedolan.github.io/jq/

A better solution would be to do so implicitly, presumably in [`download-plugins.ts`](https://github.com/eclipse-theia/theia/blob/master/dev-packages/cli/src/download-plugins.ts).

Note that this may formally exclude the extension pack itself, but currently that does not do harm because `collectExtensionPacks` only filters pack contents, not the pack itself.

**Comment by vince-fugnitto** [comment]
@ccorn I don't think that adding entries to `theiaPluginsExcludeIds` is a fix, it is really up to the application developer to properly manage the plugins. The plugins listed under `theiaPlugins` should refer to the proper `id` as a name, so they can consume `extension-packs` properly.

**Comment by vince-fugnitto** [comment]
> I'd like that. However, no Theia release so far has used namespace.name IDs in the theiaPlugins keys. And it did not seem to matter until v1.25.0.

@ccorn the extensions we list in our `package.json` have no effect on the release, or downstream applications, it is solely for this repository and the example applications we use during CI and testing.

Given that we updated our extensions to use the [pack](https://github.com/eclipse-theia/theia/pull/10049/files) (which reduced the number of entries to maintain), we should use the `namespace.name` as an `id` like you've mentioned so that extensionPack handling works fine.

**Comment by vince-fugnitto** [comment]
The duplicate entries should be fixed thanks to https://github.com/eclipse-theia/theia/pull/11111 :)
