### ISSUE TITLE
theia frontend is launch fail in safari

### ISSUE THREAD

**Issue by alexyuze** [eclipse-theia/theia#11114]
when Launch Theia in Safari，occurs an exception， in chrome and edge is ok

Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.path') — main.js:601
asyncFunctionResume
promiseReactionJobWithoutPromise
promiseReactionJob

**Comment by vince-fugnitto** [comment]
@alexyuze thank you for the discussion, do you have any additional information that may help?
I tried `master` (https://github.com/eclipse-theia/theia/commit/df80a993fc01a2d83117d56d9fd70e64ec6fd85f) and it works fine for me on Safari:

<img width="1236" alt="Screen Shot 2022-05-07 at 9 49 17 AM" src="https://user-images.githubusercontent.com/40359487/167257233-b8db9b1b-1907-4704-8053-99786f8faff6.png">

**Comment by alexyuze** [comment]
our theia  is within an iframe， if not in an iframe， it’s ok

**Comment by vince-fugnitto** [comment]
Thanks for clarifying, it was important to note that it was within an `iframe`.

We have https://github.com/eclipse-theia/theia/issues/7668 already so marking it as a duplicate.
