### ISSUE TITLE
Feature request: Limit simultaneous plugin downloads

### ISSUE THREAD

**Issue by ccorn** [eclipse-theia/theia#11110]
This is about `theia download:plugins`, apparently implemented in [`download-plugins.ts`](https://github.com/eclipse-theia/theia/blob/master/dev-packages/cli/src/download-plugins.ts).

Currently, all downloads seem to be scheduled in parallel, which in a fresh build amounts to typically more than 80 concurrent requests to the same `open-vsx.org` domain.

Try this with a mere 1000kbps connection (or imagine that the server limits connection numbers or rates) and you will run into nasty issues such as `ECONNRESET`, `ZBufError`, and `theia download:plugins` waiting forever.

I run into this issue regularly because I package each Theia release in a fresh chroot, and my connectivity is not really up to what NodeJS folks seem to take for granted. Others may have the bandwidth, but stressing `open-vsx.org` that way is probably not nice either.

Supposedly, the only realistic benefit from concurrency here is to avoid adding up the latencies for establishing the connections. However, a small number of parallel downloads would already achieve most of this, and keeping that number small would make the entire operation more robust and less DOS-like.

Therefore my feature request is the following: Limit plugin download concurrency (to the same domain) to a small number, say 5.

**Comment by vince-fugnitto** [comment]
@ccorn thank you for the issue, if the feature is important to you please don't hesitate in providing a pull-request, alternatively you can pass a `--parallel` flag if you wish when calling the script. Note that the script is just to help application developers, if it doesn't suit your needs or your restrictions you can always implement your own script for your product.

**Comment by xoriath** [comment]
I was actually about to prototype something like this internally at our end, as we are seeing some weird hangs in the theia-cli download:plugins (we do download from an internal mirror of open-vsx though to avoid the stress and network issues).

I was just about to send a PR adding a --no-parallel/--parallel option (and fix an issue in the argv parsing in download:plugins)

**Comment by vince-fugnitto** [comment]
> I was just about to send a PR adding a --no-parallel/--parallel option (and fix an issue in the argv parsing in download:plugins)

@xoriath please go ahead, new contributions are always welcome :)
