### ISSUE TITLE
[vscode] Support optional property `MarkdownString#supportThemeIcons`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11129]
### Feature Description:
Support optionally specifying whether a `MarkdownString` supports `ThemeIcons` via the constructor or property `supportThemeIcons`, see https://code.visualstudio.com/api/references/vscode-api#MarkdownString

See also #11128

**Comment by colin-grant-work** [comment]
This should be addressed by #11083, which pulls in VSCode's `MarkdownString` implementation.

**Comment by planger** [comment]
@colin-grant-work Thanks, that's great! Do you want to add this issue to the list of fixed issues by your PR?
I'm currently working through the 1.55.2 API and create issues for all missing API for which there isn't an issue and add respective notes to the [report](https://eclipse-theia.github.io/vscode-theia-comparator/filtered-status.html).
