### ISSUE TITLE
[vscode] Support optional property `SignatureInformation#activeParameter`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11134]
### Feature Description:
Support specifying an index of the `activeParameter` in a [`SignatureInformation`](https://code.visualstudio.com/api/references/vscode-api#SignatureInformation), that shall be used in place of the [`SignatureHelp#activeSignature`](https://code.visualstudio.com/api/references/vscode-api#SignatureHelp.activeSignature). As `SignatureHelp#activeSignature` is already available in Theia, this should be rather straightforward?

**Comment by msujew** [comment]
@jbicker Will take a look at this.
