### ISSUE TITLE
[vscode] Support `Terminal#exitStatus`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11139]
### Feature Description:
Add the type [`TerminalExitStatus`](https://code.visualstudio.com/api/references/vscode-api#TerminalExitStatus) and support specifying it in [`Terminal#exitStatus`](https://code.visualstudio.com/api/references/vscode-api#Terminal).

**Comment by alvsan09** [comment]
@educphi  has volunteered to start looking into it.
Lets track any discussions around it via this channel.
