### ISSUE TITLE
[vscode] Support `Task#runOptions`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11132]
### Feature Description:
Support specifying [`RunOptions`](https://code.visualstudio.com/api/references/vscode-api#RunOptions) for a [`Task`](https://code.visualstudio.com/api/references/vscode-api#Task). Both is missing, the type `RunOptions` and support for the property `Task#runOptions`.

**Comment by vince-fugnitto** [comment]
@sgraband do you have any update on the API?

**Comment by sgraband** [comment]
@vince-fugnitto I already added the API, but then i realized that the options passed via the API will have no effect, as they are currently not supported, so i wanted to add support for the `reevaluateOnRerun` option. But this requires some reworking of what information about the last tasks we store. 

I am planning to finish this in the beginning of October, if this is fine?
