### ISSUE TITLE
[vscode] Support property `SourceControlInputBox#visible`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11140]
### Feature Description:
Support specifying whether an [`SourceControlInputBox`](https://code.visualstudio.com/api/references/vscode-api#SourceControlInputBox) is visible.

**Comment by planger** [comment]
Related to #5458

**Comment by msujew** [comment]
> The UI of the InputBox is provided by the extension, so the API only needs to save and transmit the variables, correct?

@KevinK-9 Yes, that's correct. I believe that's the way it also works for the already existing parts of this API, such as the placeholder.

> Is there an extension to test this with, to see how the visibility variable is used by such an extension or another way to test the implementation?

Contributors of such features usually provide a small example vscode extension to test the changes. See for a more elaborate example [this PR](https://github.com/eclipse-theia/theia/pull/11290).
