### ISSUE TITLE
[vscode] Support `TreeDataProvider#resolveTreeItem()`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11147]
Add support in [TreeDataProvider](https://code.visualstudio.com/api/references/vscode-api#TreeDataProvider%3CT%3E) for resolving [tree items](https://code.visualstudio.com/api/references/vscode-api#TreeItem) on hover or click by adding the missing method
`resolveTreeItem(item: TreeItem, element: T, token: CancellationToken): ProviderResult<TreeItem>`
See https://code.visualstudio.com/api/references/vscode-api#TreeDataProvider%3CT%3E

**Comment by lucas-koehler** [comment]
I am looking into this.
