### ISSUE TITLE
[vscode] Support `TreeItemLabel` in `TreeItem`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11148]
### Feature Description:
The interface [`TreeItemLabel`](https://code.visualstudio.com/api/references/vscode-api#TreeItemLabel) can be used instead of plain strings for defining the [`TreeItem.label`](https://code.visualstudio.com/api/references/vscode-api#TreeItem). In addition to the plain string label, `TreeItemLabel` can also specify `highlights` to indicate ranges in the label to highlight, see https://code.visualstudio.com/api/references/vscode-api#TreeItemLabel.

**Comment by lucas-koehler** [comment]
I'm going to look into this :)
