### ISSUE TITLE
Unsupported activation events: onNotebook:jupyter-notebook,

### ISSUE THREAD

**Issue by ariana02880** [eclipse-theia/theia#11157]
Hi Team, I got this error today. any idea how to fix this?
```
root ERROR [hosted-plugin: 8110] Unsupported activation events: onNotebook:jupyter-notebook, please open an issue: https://github.com/eclipse-theia/theia/issues/new

```

**Comment by vince-fugnitto** [comment]
> any idea how to fix this?

@ariana02880 thank you for reporting the issue, notebook apis including the related activation event is not yet supported. You can see from the following comparator document (https://eclipse-theia.github.io/vscode-theia-comparator/status.html). 

We have the following https://github.com/eclipse-theia/theia/issues/9867 tracking the API, but there are no plans as of yet to implement it.

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/9867.
