### ISSUE TITLE
Hikvision

### ISSUE THREAD

**Issue by Rasdalharakaest** [eclipse-theia/theia#11156]
### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by Rasdalharakaest** [comment]
Please change your PIN email number
Fahad@rasd.sa

**Comment by Rasdalharakaest** [comment]
Hooo

**Comment by vince-fugnitto** [comment]
I believe this was opened by accident.
