### ISSUE TITLE
Can't exit out of setting's window. 

### ISSUE THREAD

**Issue by emmeb** [eclipse-theia/theia#11161]
The red exit button for setting is on top of the menu button (see attached screenshot). This makes it impossible to exit settings. Could the exit button be moved so that it is not on top of the menu button? Thank you! 

<img width="1213" alt="Screen Shot 2022-05-16 at 12 49 56 PM" src="https://user-images.githubusercontent.com/17111084/168643998-deca1183-506c-4f71-a502-6c3ec9c20e7c.png">

### Steps to Reproduce:
1. Open settings.

### Additional Information

- Operating System: macOS
- Theia Version: 1.14.0

**Comment by vince-fugnitto** [comment]
@emmeb that isn't the exit button that is the toolbar item to clear the search results (you can see it's tooltip). 
You can close the preferences by clicking the `x` on the preferences tabbar at the top (you can see it in the picture).

**Comment by emmeb** [comment]
Thanks, I figured that out after, but why is there a red x over the menu button.

**Comment by paul-marechal** [comment]
@emmeb it's not a menu button, it's a "clear results" icon.
