### ISSUE TITLE
Escape not working with Vim plugin

### ISSUE THREAD

**Issue by SolidTux** [eclipse-theia/theia#11173]
### Bug Description:

On a fresh Theia, after installing the vscodevim.vim plugin, pressing the escape key does not exit insert mode.

### Steps to Reproduce:

1. Install vscode.vim
2. Open file
3. Enter insert mode
4. Try to exit insert mode

### Additional Information

- Operating System: Debian
- Theia Version: 1.25.0
- vscode.vim Version: 1.21.5

[theia.log](https://github.com/eclipse-theia/theia/files/8715486/theia.log)

**Comment by SolidTux** [comment]
What additional information do you need?

**Comment by vince-fugnitto** [comment]
@SolidTux thank you for reporting the issue :+1: 

I verified and the `vscodevim.vim` extension works well for me, I am able to successfully exit `insert mode` using <kbd>ESC</kbd>. 
Do you have any additional information that may help?

https://user-images.githubusercontent.com/40359487/169039727-ff5e169a-1963-45aa-bf0d-b2b3c1c663d0.mp4

**Comment by SolidTux** [comment]
Looking at your screen capture it looks like I'm doing exactly the same thing except than I use a dedicated escape key (but I can't check capslock-escape as my keyboard has no capslock). `xev` shows the event as

```
KeyPress event, serial 35, synthetic NO, window 0x2c00001,
    root 0x294, subw 0x0, time 730052790, (118,74), root:(119,115),
    state 0x10, keycode 9 (keysym 0xff1b, Escape), same_screen YES,
    XLookupString gives 1 bytes: (1b) "
mbLookupString gives 1 bytes: (1b) "
FilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x2c00001,
    root 0x294, subw 0x0, time 730052798, (118,74), root:(119,115),
    state 0x10, keycode 9 (keysym 0xff1b, Escape), same_screen YES,
    XLookupString gives 1 bytes: (1b) "
FilterEvent returns: False
```

The extension does work as expected in VSCodium though, that's why I opened the issue here. I could check on a more up to date Fedora machine when I'm home again.

Here is also a screengrab (but I don't know how to get the overlay).

https://user-images.githubusercontent.com/17935831/169042526-e4ddb362-3dd1-4dbd-a1d7-84c8c756b3b0.mp4

**Comment by colin-grant-work** [comment]
I believe that this PR should have fixed the issue: https://github.com/eclipse-theia/theia/pull/11095. The VIM plugin relies heavily on contexts set by the plugin itself, and those settings were not propagating to the global `ContextKeyService` before #11095. @SolidTux, please try applying that PR to your version or testing on `master`.

**Comment by colin-grant-work** [comment]
Closing for now. Feel free to comment if you encounter the problem again.
