### ISSUE TITLE
Large amount of uninformative output from IPC system

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11196]
### Bug Description:

The IPC system appears to be making a large number of logs at `info` level. They should likely be demoted to `debug` or `trace` level, or removed if no longer necessary.

![image](https://user-images.githubusercontent.com/62660806/170278745-2c116b9b-3694-4a48-9e01-9d01acb4933a.png)

@tortmayr, @JonasHelming 

### Steps to Reproduce:

1. Start the application
2. Do some things (or walk away)
3. Find a large number of logs of IPC activity.

### Additional Information

- Theia Version: 9ec8835cf35d5a46101a62ae93285aeb37a2f382

**Comment by tortmayr** [comment]
Fixed with https://github.com/eclipse-theia/theia/pull/11197
A debug/dev log message was committed on accident an managed to sneak through the code reviews.
