### ISSUE TITLE
Use Thenable instead of PromiseLike in API

### ISSUE THREAD

**Issue by sgraband** [eclipse-theia/theia#11214]
### Feature Description:
Currently most of the Theia API uses `PromiseLike` and VSCode exports its own type `Thenable` and uses it. However, there a some usages of `Thenable` in the Theia API. For example [here](https://github.com/eclipse-theia/theia/blob/dbc574288c95108581d15849df498625d0d81c18/packages/plugin/src/theia.d.ts#L7003). IMHO the API should only use types, that are defined within the file (next to typescript native types obviously). On top of that this leads to problems in the `theia-vscode-comparator`.

We could either redefine the type in the API itself or just use the `PromiseLike` type consistently. I would prefer the second option, as having two of the "same" type seems weird. Would there be any objections or preferences to this?

**Comment by sgraband** [comment]
@colin-grant-work are there any objections/opinions about this? Otherwise i would open a PR for this.

**Comment by sgraband** [comment]
Thank you for your answer! I see your point. I will open a PR that adds the `Thenable` type to `theia.d.ts`. Should i then also update all of the `PromiseLike` references in the `theia.d.ts` files to `Thenable`, when they are declared with `Thenable` in the `vscode.d.ts`? Or would you say this is unneccesary overhead?

**Comment by colin-grant-work** [comment]
I think I'd probably prefer uniformity, so if it isn't too much trouble, replacing `PromiseLike` with the new `Thenable` is probably desirable?
