### ISSUE TITLE
future: support Node 18

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#11220]
While dropping support for Node 12 in https://github.com/eclipse-theia/theia/pull/11210 I tried adding testing for Node 18 but failed.

It seems like there's a couple breakages in Node 18 that we will need to adapt to once we decide to support it:

- It needs Ubuntu >= 20.04 to run because it uses a newer version of glibc.
- `net.Server.listen(port, address, ...)` now defaults to an IPv6 localhost address when unspecified.
- ~~The `macaddress` npm package used by `plugin-ext` breaks on Node 18.~~
- We need to update the `macaddress` package for it to work on Node 18.
- More?

**Comment by Alexander-Taran** [comment]
pull request to fix `macaddress` package
https://github.com/scravy/node-macaddress/pull/40

**Comment by Alexander-Taran** [comment]
Macaddress published fixes version to nomjs

**Comment by anavarre** [comment]
Any update on Node.js 18 support? It's been a year since this issue was raised and with the upcoming [EOL of Node.js 16 in September](https://nodejs.org/en/blog/announcements/nodejs16-eol) I'd like to make sure that we have a secure option then. Thanks!

**Comment by shriacquia** [comment]
Any update on Node.js 18 support?

**Comment by paul-marechal** [comment]
Gave it a quick try and it seems trivial to bump to node 18.x so I opened a PR for it.

Please try the PR and tell us if you find any regressions that weren't caught by our CI.

**Comment by vince-fugnitto** [comment]
Please note that we generally want to follow the same runtime present in VS Code for compatibility with extensions.
They declare that versions higher than 17 have not yet been tested, and still use 16 during CI:

- https://github.com/microsoft/vscode/blob/406618d71adb41af931ca787e178b797a475eb6c/build/npm/preinstall.js#L12-L18
- https://github.com/microsoft/vscode/blob/406618d71adb41af931ca787e178b797a475eb6c/.github/workflows/ci.yml#L26-L28

**Comment by paul-marechal** [comment]
We use [Electron 23](https://github.com/eclipse-theia/theia/blob/dab0aade1d0de8a1394975e249db636070b4b9b8/packages/electron/package.json#L15) which [embarks Node 18 already](https://www.electronjs.org/blog/electron-23-0).

**Comment by danepowell** [comment]
Since this seems to be blocked on vscode, note that vscode will move to Node 18 as part of Electron 25: https://github.com/microsoft/vscode/issues/184021

**Comment by paul-marechal** [comment]
I don't think moving to node 18 is "blocked on VS Code" as [our current version of Electron runs node 18](https://github.com/eclipse-theia/theia/issues/11220#issuecomment-1636309436).

There is [a PR opened that needs reviewing](https://github.com/eclipse-theia/theia/pull/12711) before moving forward.
