### ISSUE TITLE
community link is broken

### ISSUE THREAD

**Issue by saltylassi** [eclipse-theia/theia#11251]
### Steps to Reproduce:

1. check this link https://community.theia-ide.org/

### Additional Information

- Operating System:
- Theia Version:

**Comment by msujew** [comment]
@saltylassi The certificate of the website ran out and we are currently trying to reach the original owners of the domain (which isn't the same as the `www.theia.org` domain), but they're not part of the contributor team anymore, so it takes longer than expected.

**Comment by saltylassi** [comment]
oh... sorry. I'll close this issue.
