### ISSUE TITLE
Theia Discourse not accessible due to an outdated certificate

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#11266]
Since the night of the 31st the certificate for `https://community.theia-ide.org` is no longer valid, making the website mostly unusable.

Due to historical reasons, the Eclipse Foundation is currently not the owner of the domain. We currently try to contact the original owners and transfer ownership to EF. As they are no longer contributors, this is taking longer than expected.

In the meantime, please use our [GitHub discussions feature](https://github.com/eclipse-theia/theia/discussions) if you have any questions.

**Comment by tsmaeder** [comment]
@msujew any news on this? Are there other folks @gitpod we can escalate the issue to? If we get a hold of them, and get them to transfer the domain, who should be the new owner?

**Comment by msujew** [comment]
@tsmaeder I've actually just got a hold on the people who were responsible for this over at Gitpod's site of things. They are currently trying to locate the right resources in their GCP cluster and update the certificate. Hopefully, the website should be usable again within the next few hours.

Afterwards, we plan to transfer everything to TypeFox first, just so it becomes easier to manage directly. I'm open for anyone to own the page after that.

**Comment by tsmaeder** [comment]
@msujew were you able to establish a timeline for restoring the certificate with the GitPod folks? Would be good to know when service can be restored.

**Comment by msujew** [comment]
@tsmaeder Unfortunately they lost track of the GCP resources responsible for the service. Their platform team is looking for it, but it might take a bit. Renewing the certificate afterwards should be trivial.

**Comment by tsmaeder** [comment]
> they lost track of the GCP resources responsible for the service

I pray in the church of "write shit down" for this very reason ;-)

**Comment by msujew** [comment]
The situation has been resolved, the certificate has been updated. Thank you for your patience.

**Comment by tsmaeder** [comment]
Thanks for taking care of this.
