### ISSUE TITLE
Debug sessions failing to execute

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11263]
### Bug Description:

It appears that starting debug sessions is failing.

### Steps to Reproduce:

1. Open a `.spec.ts` file in the repo and try the `Run Mocha Tests` debug configuration.
2. Observe that the Threads widget shows the session, but no breakpoints are hit, no variables are shown, etc.
2. Try a dynamic Node configuration like 'Run current file'. 
3. Observe that the behavior is the same: Session appears, but nothing else happens.

### Additional Information

- Operating System: OS X
- Theia Version: 96a395099ec6c38432ba40022b6eb3575992d640

**Comment by colin-grant-work** [comment]
@JonasHelming, @tortmayr, this appears to be a problem with the RPC commit. Debugging is working at e1e200a7bfb9c7b9b87bf63dd8e101e734281222 and broken at 83d430846182a2ccd8465bcfd28ba7214c42abf3.

**Comment by tortmayr** [comment]
Thanks for reporting this. That's definitely a critical issue and I will have a look at it right away.

**Comment by tortmayr** [comment]
@colin-grant-work I have opened a PR that should fix the debugging issues: https://github.com/eclipse-theia/theia/pull/11268
