### ISSUE TITLE
Codicons spinning off-center in custom tree view

### ISSUE THREAD

**Issue by SanjulaGanepola** [eclipse-theia/theia#11273]
### Discussed in https://github.com/eclipse-theia/theia/discussions/11270

<div type='discussions-op-text'>

<sup>Originally posted by **SanjulaGanepola** June  7, 2022</sup>
When trying to apply a spinning animation to my icon as supported in VS Code [here](https://code.visualstudio.com/api/references/icons-in-labels#animation), I notice that in Theia the icons are spinning off-center when used in a custom tree view. I am currently running in Theia v1.18.0 where I noticed the issue, but I also verified the issue in Theia Blueprint v1.26.0.

I see that this was previously a known issue in VS Code (https://github.com/microsoft/vscode/issues/117859), but has since been resolved back in May 2021. Is there any current workaround to support spinning icons or is there a plan to resolve this issue in Theia?</div>

**Comment by pluralia** [comment]
I'll look into this.
