### ISSUE TITLE
Message Connection Stability Improvement

### ISSUE THREAD

**Issue by DanboDuan** [eclipse-theia/theia#11271]
Should we(Theia) provide a stable connection between server and browser ?

Here is the situation :

Theia would close the message connection at once when networking is disconnected, e.g. the socket.io emit the `disconnect` event. Then the browser would reconnect and is treated as a new browser connected. Some doing job would be stopped . 
For most situation there would be no problem, but for some case, this should be annoy. For example, if we are debugging some program and the network does not work well just for some moment, we will have to restart the job.

If we could provide a stable connection between server and browser, and do some job to manage the connections and re-connections, like [open-vscode-server](https://github.com/gitpod-io/openvscode-server), this could be better.

It not a cost or hard job. We could just add a `PersistentConnection` base on `WebSocketChannel` and do some management, and it should work fine

**Comment by kittaakos** [comment]
> For example, if we are debugging some program and the network does not work well just for some moment, we will have to restart the job.

I had a similar issue, @DanboDuan. Do you need this for dev only or production too? What's your use case? For me, it was a ping timeout in dev mode. I logged it here: https://github.com/eclipse-theia/theia/discussions/11543. Please chime in if you have the same problem.


> to manage the connections and re-connections

I develop electron apps, so there are no real connection issues between the backend and frontend, but even in dev mode, the reconnection happens automatically after a disconnect. In electron, there is nothing to manage. Theia does it. Do you experience no reconnect in web env?

**Comment by DanboDuan** [comment]
> > For example, if we are debugging some program and the network does not work well just for some moment, we will have to restart the job.
> 
> I had a similar issue, @DanboDuan. Do you need this for dev only or production too? What's your use case? For me, it was a ping timeout in dev mode. I logged it here: #11543. Please chime in if you have the same problem.
> 
> > to manage the connections and re-connections
> 
> I develop electron apps, so there are no real connection issues between the backend and frontend, but even in dev mode, the reconnection happens automatically after a disconnect. In electron, there is nothing to manage. Theia does it. Do you experience no reconnect in web env?

Well, I develop browser apps. So it would be much easy to meet the issues.

**Comment by tsmaeder** [comment]
I believe this request is acomplished with https://github.com/eclipse-theia/theia/pull/13082
