### ISSUE TITLE
too much `viewWelcomeNodes`

### ISSUE THREAD

**Issue by meng-jpg** [eclipse-theia/theia#11283]
### Bug Description:
When the state of workspace is `no folder opened`, close the `Explorer` panel and open it from the `View` menu again.
Then one more `visibleItem` of the `TreeViewWelcomeWidget` will be displayed.
This may be caused by the response mode of the `onDidCreateWidget` event and the storage form of the `viewWelcome` nodes.

### Steps to Reproduce:

1. run theia electron
2. right click on the explorer icon to call the context menu
3. choose close
4. reopen the  panel from `View->Explorer`
<img width="616" alt="截屏2022-06-10 下午2 15 32" src="https://user-images.githubusercontent.com/74631407/173003947-d64bb0df-57a4-41ad-909a-e6c9dd2a0898.png">

### Additional Information

- Operating System: macOS Big Sur 11.2
- Theia Version: 1.25

**Comment by inlann** [comment]
Theia 1.26 still has this bug

**Comment by yiliang114** [comment]
![image](https://user-images.githubusercontent.com/11473889/174540407-fa52ca73-2c8c-4b26-ae8b-20b70cbf6d48.png)

Same error in Theia Web (examples/browser)1.26
