### ISSUE TITLE
If the parent folder has only one child folder, the context menu of the child folder cannot be opened

### ISSUE THREAD

**Issue by inlann** [eclipse-theia/theia#11292]
### Bug Description:

If the parent folder has only one child folder, the context menu of the child folder cannot be opened. And the right-click of both parent and child folders becomes toggle expansion and collapse

For example, I have a folder named `test` which only contains a subdirectory name `test1`:

```bash
mac@Titan theia-1.20.0 % tree test 
test
└── test1
    └── test_file.md

1 directory, 1 file
mac@Titan theia-1.20.0 %
```

The right-click of both parent and child folders becomes toggle expansion and collapse:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/33852855/173521671-8faf1902-0940-410b-a73d-da640248a626.png">

<img width="354" alt="image" src="https://user-images.githubusercontent.com/33852855/173521710-ac8fe754-add2-4954-becb-1e804d688f32.png">

I can only open the context menu of the `test` folder  by right-clicking the blank area:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/33852855/173521881-1ed7ad8d-ad41-496a-b12c-82e5264e92ec.png">

But there is no way to open the context menu of the `test1` folder.

### Additional Information

- Operating System: MacOS, Windows
- Theia Version: 1.25.0, 1.26.0

**Comment by inlann** [comment]
BTW: The [community website](https://community.theia-ide.org/) is down? 

<img width="737" alt="image" src="https://user-images.githubusercontent.com/33852855/173524410-1db17afe-e7c5-4893-9c86-b7274a103f98.png">

**Comment by kittaakos** [comment]
> BTW: The [community website](https://community.theia-ide.org/) is down?

Yes. See here: https://github.com/eclipse-theia/theia/issues/11266

**Comment by vince-fugnitto** [comment]
@inlann thank you for reporting the issue, can you try using `master`, I believe the issue has already been fixed thanks to https://github.com/eclipse-theia/theia/pull/11230.

**Comment by vince-fugnitto** [comment]
Closing due to https://github.com/eclipse-theia/theia/issues/11292#issuecomment-1155069979, please comment if it is not the case :+1:
