### ISSUE TITLE
[editor] Widget manager should compare widget keys with deep equals instead of string equal

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#11309]
### Bug Description:

When opening editors, the opener `options` is used to generate an [identity key](https://github.com/eclipse-theia/theia/blob/024d8714393cc0d8f821d6350cba71c6df4a63ad/packages/core/src/browser/widget-manager.ts#L258-L260) for the widget. This is clear and works as expected. However, the property order of the opener `options` also matters when trying to [find an already opened widget](https://github.com/eclipse-theia/theia/blob/024d8714393cc0d8f821d6350cba71c6df4a63ad/packages/core/src/browser/widget-manager.ts#L195).

The following code causes unexpected behavior:

```ts
const uri = 'file:///path/to/an/existing/resource.txt';
const options = {
    counter: 0,
    mode: 'reveal',
    preview: false
} as EditorOpenerOptions;
await this.editorManager.open(uri, options);

const sameOptions = {
    ...options,
    preview: options.preview,
    mode: options.mode // change the property order
};
await this.editorManager.open(widget.editor.uri, sameOptions);
```

My code is here: https://github.com/eclipse-theia/theia/compare/master...kittaakos:opener-options
Steps to reproduce:
 - Open an editor,
 - Wait 2 sec

See in action:

https://user-images.githubusercontent.com/1405703/174308827-9fa9c652-caea-44d5-8365-c8f5f36576de.mp4

Do I misuse the APIs? if not, I think Theia should compare keys with deepEqual and try to find the existing widget instead doing `Map.get` by the JSON options.

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System: macOS 12.3.1
- Theia Version: 462376a7993

**Comment by colin-grant-work** [comment]
Alternatively, something like [this library](https://www.npmjs.com/package/json-stringify-deterministic) might solve the problem of key-order dependent stringification.
