### ISSUE TITLE
navigator: renaming a file doesn't update automatically in the navigator tree on Windows

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#11308]
### Bug Description:

Renaming a file in the navigator view doesn't update automatically on Windows.

### Steps to Reproduce:

1. Rename a file in your workspace.
2. The file won't update in the tree unless you press the "refresh tree" button at the top.

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.26.0

**Comment by colin-grant-work** [comment]
I believe that this is also a symptom of the same problem as #11442.

**Comment by JonasHelming** [comment]
@paul-marechal Can you confirm this is fixed?

**Comment by msujew** [comment]
@JonasHelming I can confirm that this was fixed by https://github.com/eclipse-theia/theia/pull/11530 👍
