### ISSUE TITLE
debug: support `compounds` launch configurations

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11302]
#### Feature Description:

The goal is to support [compound](https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations) for debug launch configurations. Currently the compound launch configurations are not present in the dropdown, or supported in the `launch.json` schema:

![image](https://user-images.githubusercontent.com/40359487/173908623-1388bc63-7fa1-4591-aa79-1dc437d2b1d6.png)

#### Steps to Reproduce

1. start the application using `theia` as a workspace
2. open the `debug` view and select the dropdown
3. notice that both compound launch configurations are missing

    https://github.com/eclipse-theia/theia/blob/f6c0689dde8b207726deab75bc3cb5cfdae6acfb/.vscode/launch.json#L196-L216

5. notice that there is no context assistance for the compounds in the `.vscode/launch.json` file

**Comment by martin-fleck-at** [comment]
@vince-fugnitto Do you know if anyone is already working on this? If not I might have a look at it one of these days.

**Comment by vince-fugnitto** [comment]
@martin-fleck-at I'm not aware of anyone looking into so please go ahead :)
