### ISSUE TITLE
Files without extension are filtered in `ElectronFileDialogService` even though no filter is provided

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11321]
### Bug Description:

The file selection dialog of Electron hides files without extensions also if no specific file filters are specified when calling `FileDialogService#showOpenDialog` in Electron with `OpenFileDialogProps#canSelectFiles = true` and `OpenFileDialogProps#canSelectFolders = false`.

`ElectronFileDialogService` adds an _All Files_ filter with an extension pattern of `'*'` in that case:

https://github.com/eclipse-theia/theia/blob/ce0128453165d9a9493a7a958fcfaa4b0a2c6e9e/packages/filesystem/src/electron-browser/file-dialog/electron-file-dialog-service.ts#L128

At least for Ubuntu / GTK, this results in hiding all files that have no extension due to Electron issue https://github.com/electron/electron/issues/34492. This issue has been fixed, but a backport of this fix only exists for Electron 18.x upwards.

I'm wondering why we are adding this _All Files_ filter in the first place.
If callers of the `FileDialogService` don't provide any filters, then all files should be shown, which is also accomplished if we don't add another _All Files_ filter. Not adding any filter by-passes the aforementioned Electron bug and thus also files without any extension would show up.
If callers of the `FileDialogService` provide filters, why do we want to "overrule" them by adding another _All Files_ filter?

Would you agree to remove the line linked above or maybe just adding it, if callers specify a filter?
According to your feedback, I'm happy to open a PR.

Thanks!

### Steps to Reproduce:

1. Use Ubuntu Linux
2. Start Electron Example App
3. _Open Settings (UI)_
4. Navigate to _Terminal › External: Windows Exec_
5. Click _Browse_
6. Navigate to a folder that contains a file without an extension
7. Observe how it doesn't show in the dialog even though it exists

### Additional Information

- Operating System: Linux
- Theia Version: 1.26.0

**Comment by vince-fugnitto** [comment]
@planger I believe the discussions from https://github.com/eclipse-theia/theia/pull/9659 might be interesting as to why we include the "all filters" filter.

**Comment by planger** [comment]
@vince-fugnitto Thanks for the feedback! The argument in #9659 certainly makes sense. How about only adding the _All Files_ filter if there is a filter specified by the caller? This would address the requirement in #9659, but still bypass the electron bug when no file filter is specified in the first place. If a file filter is specified, we'll run into the electron bug anyway.

**Comment by vince-fugnitto** [comment]
@planger I believe it should work, should it also only apply for Linux?

**Comment by planger** [comment]
@vince-fugnitto Yes I think so, as I believe the [electron bug](https://github.com/electron/electron/issues/34492) can only be observed on Linux, maybe even only on GTK. I'll prepare a PR that only omits the _All Files_ filter if no other filter is set and if we are on Linux. Thanks a lot for your feedback!
