### ISSUE TITLE
After inserting newlines into an editor, `Edit` > `Undo` works unreliably

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#11324]
### Bug Description:

Theia executes `Undo` unreliably after line insertion.

Electron, macOS
   - It does not work. Possibly related: https://github.com/eclipse-theia/theia/issues/11217.

https://user-images.githubusercontent.com/1405703/174971328-387c706d-112d-4b37-9615-fb190aadfd0e.mp4

Browser, macOS
   - Theia ignores every second `Undo` command.

https://user-images.githubusercontent.com/1405703/174971421-6f72c9d0-2efb-499d-b3fa-e51e10b5b12e.mp4

### Steps to Reproduce:

1. Open an editor,
2. Insert newlines,
3. Try to undo with `Edit` > `Undo` or with the `Undo` from the context menu,

### Additional Information

- Operating System: macOS
- Theia Version: ce012845316

**Comment by colin-grant-work** [comment]
@kittaakos, I'm having trouble reproducing this issue. I'm on MacOS 12.4, Chrome 102. What browser are you using?

**Comment by kittaakos** [comment]
Thank you for your time checking it.

I used Brave (`Version 1.40.105  Chromium: 103.0.5060.53 (Official Build)  (x86_64)`) on macOS 12.3.1, but I can confirm that it works with Chrome (`Version 103.0.5060.53 (Official Build) (x86_64)`).

#11217 already exists for the electron part, and the browser part is invalid. I am closing this issue.
