### ISSUE TITLE
Update to React 17

### ISSUE THREAD

**Issue by sdirix** [eclipse-theia/theia#11355]
To stay up to date with our dependencies we should raise the React version Theia is built against. At the moment this is React 16.

Updating to React 17 would make a lot of sense as this would allow [gradual updates of React components](https://reactjs.org/blog/2020/10/20/react-v17.html), i.e. users can integrate multiple versions of React in case they absolutely need to.

For testing we already built Theia against React 17 and did not notice any issue. To my knowledge no deprecated feature of React is used in Theia. As React 17 has barely any changes in the API surface almost all users should be trivially able to update their apps.

We could also update to React 18 but this might be too new for some users integrating libraries which are not compatible to React 18.

**Comment by vince-fugnitto** [comment]
Closed by https://github.com/eclipse-theia/theia/pull/11455.
