### ISSUE TITLE
scm: history does not respect max count

### ISSUE THREAD

**Issue by anavarre** [eclipse-theia/theia#11376]
### Bug Description:

See https://github.com/eclipse-theia/theia/discussions/11371 for all details

### Steps to Reproduce:

See https://github.com/eclipse-theia/theia/discussions/11371 for all details

### Additional Information

- Operating System: all
- Theia Version: 1.26

**Comment by rahulgupta-acquia** [comment]
Still this issue i am facing with Theia Version 1.35
[SCM_HISTORY_MAX_COUNT](https://github.com/eclipse-theia/theia/blob/0a960a6b200cc6c547a7e403cb21f32fa383001b/packages/scm-extra/src/browser/history/scm-history-contribution.ts#L31) is not working
when i checked all commits loading.
Could you please fix this and let me know if any other configuration needed from my side.
