### ISSUE TITLE
Incorrect conversions from `null` to `undefined` in new RPC

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11392]
### Bug Description:

In certain cases, `null` values from the backend are appearing on the frontend as `undefined`.

### Steps to Reproduce:

1. Install and activate the `vscode-lldb` plugin.
2. See error mentioned [here](https://github.com/eclipse-theia/theia/issues/9136#issuecomment-1175400641): Failure to activate because of problem in a method `startRpcServer`.
> The error does not occur in `1.26` (without new RPC) but does in `1.27` with new RPC.

---

You can also use [this plugin](https://github.com/eclipse-theia/theia/files/9067216/extension-preference-access-0.0.1.zip) ([source](https://github.com/colin-grant-work/demo-extensions/tree/main/extension-preference-access)). Assuming you have not set the preference `peaSoup.secretIngredients`, running the command `Access a (probably) non-existent preference` should show a toast with the default value `null`, but on master it shows `[]`.

### Additional Information

The relevant preference is defined [here](https://github.com/vadimcn/vscode-lldb/blob/54d4fbb2dead83e98bd44d07057b67efc4305531/package.json#L455-L463) with a default of `null`. However, when the plugin's data is transmitted to the frontend, that `null` becomes `undefined`, and we enter this code:

https://github.com/eclipse-theia/theia/blob/84b317ae4b6610b8e23ae5b87d845c4abee78116/packages/core/src/browser/preferences/preference-contribution.ts#L248-L271

Because the preference is typed as `["object", "null"]`, that method returns a default of `{}` rather than the configured default of `null`.

I have confirmed that `null` is present [here](https://github.com/eclipse-theia/theia/blob/84b317ae4b6610b8e23ae5b87d845c4abee78116/packages/plugin-ext/src/hosted/node/plugin-service.ts#L161), but becomes `undefined` when received [here](https://github.com/eclipse-theia/theia/blob/84b317ae4b6610b8e23ae5b87d845c4abee78116/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L344).

- Operating System: MacOS 12.4
- Theia Version: 1.27.0

**Comment by colin-grant-work** [comment]
Attn: @JonasHelming, @sgraband

**Comment by JonasHelming** [comment]
@tortmayr
