### ISSUE TITLE
Can't watch file change when start without --no-cluster flag

### ISSUE THREAD

**Issue by hyy215** [eclipse-theia/theia#11390]
### Bug Description:
Can't watch file change

### Steps to Reproduce:
1. yarn browser start
2. Enable verbose file watching logs.
![image](https://user-images.githubusercontent.com/34715914/177518078-70c0a687-aa45-4b6e-bc16-c1da8b566c5c.png)
3. modify test.txt
4. no log output
![change-file-demo-1](https://user-images.githubusercontent.com/34715914/177515198-f10cf8fa-5324-4cd0-aa8d-b6764c044e27.gif)
5. yarn browser start --no-cluster
6. modify test.txt
7. log output
![change-file-demo-2](https://user-images.githubusercontent.com/34715914/177524158-b545bcb0-4eea-4e32-b423-9b81d21d43b0.gif)

### Additional Information

- Operating System: win10
- Theia Version: master, commit 97ce5f89eccf866fdd2058c20b50a8271204790f
- Node：14.19.1

**Comment by colin-grant-work** [comment]
I believe that this is a symptom of the same issue that is causing #11442.
