### ISSUE TITLE
Conflicting shortcuts for CtrlCmd + Shift + L

### ISSUE THREAD

**Issue by perrinjerome** [eclipse-theia/theia#11403]
### Bug Description:

<kbd>CtrlCmd</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> is mapped to 
- "Select All Occurrences of Find Match" by monaco ( https://github.com/microsoft/vscode/blob/dce493cb6e36346ef2714e82c42ce14fc461b15c/src/vs/editor/contrib/multicursor/browser/multicursor.ts#L774 )
- "Toggle plugin view" by theia's plugin-ext 

I feel that opening the plugin ext is not something people need to do with "high efficiency" and that this does not really need a shortcut, so a fix I want to suggest is to remove this line where the keyboard is registered in plugin-ext :
https://github.com/eclipse-theia/theia/blob/ab55cbea5bd570863fae348d9abaf1a54f0c0624/packages/plugin-ext/src/main/browser/plugin-frontend-view-contribution.ts#L35

### Steps to Reproduce:

1. open a text editor
2. search for some string present in the file
3. press <kbd>CtrlCmd</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> to select all matches
4. the plugin view opens instead of selecting

### Additional Information

- Operating System: ChromeOS 104 
- Theia Version: current master

**Comment by vince-fugnitto** [comment]
@perrinjerome I don't believe the bug is necessarily that the plugins-view has a keybinding, more so that `Select All Occurrences of Find Match` should have priority when the `when` context is true (`editorFocus`):

![image](https://user-images.githubusercontent.com/40359487/178268409-7cb67561-3d39-40f6-859c-acc02f3609e3.png)

**Comment by perrinjerome** [comment]
Thank you @vince-fugnitto I did not notice your edit, I'm sending a pull request to drop the default keybinding in that case.
