### ISSUE TITLE
Bug in FileChangesEvent.contains() method causes unexpected behaviour

### ISSUE THREAD

**Issue by bbelyavsky-ti** [eclipse-theia/theia#11401]
### Bug Description:

The class `FileChangesEvent` has a simple bug in its contains() method - when event-type is `DELETED`, the method is supposed to return 'true' if the parent folder of the passed-in 'resource' argument was deleted.  Instead, it returns `true` if any child of the passed-in 'resource' was deleted.

https://github.com/eclipse-theia/theia/blob/3b689e0b4f37844f674b26fc9b2c4d735b0115fd/packages/filesystem/src/common/files.ts#L96-L99

To fix:

```diff
// For deleted also return true when deleted folder is parent of target path
if (change.type === FileChangeType.DELETED) {
-   return resource.isEqualOrParent(change.resource);
+   return change.resource.isEqualOrParent(resource);
}
```

### Steps to Reproduce:

Quick code-inspection should be enough to see the bug:
- File: packages/filesystem/src/common/files.ts
- Class: FileChangesEvent
- Method: contains(URI, FileChangeType)

### Additional Information

- Operating System: all
- Theia Version: 1.27.0

**Comment by vince-fugnitto** [comment]
@bbelyavsky-ti thank you for reporting the issue, are you interested in contributing a fix?

**Comment by bbelyavsky-ti** [comment]
@vince-fugnitto yes, I'd like to contribute.  Let me read up on the contribution process, and then I'll submit the patch...  Thanks!
