### ISSUE TITLE
PluginDeployer won't work correctly if plugin package name has @scope

### ISSUE THREAD

**Issue by vnfedotov** [eclipse-theia/theia#11419]
### Bug Description:

If plugins folder contains two or more plugins with `@scope` in the package name, PluginDeployer will confuse it for version and _silently_ uninstall these plugins.

### Steps to Reproduce:

1. Plugins folder has 2 plugins, package names: @my-org/pluginA, @my-org/pluginB, same publisher id.
2. On Theia startup, plugins are deployed successfully and marked as installed here: https://github.com/eclipse-theia/theia/blob/3bf8244332e57d5870c2aef1d0a7a1cdb021c7e9/packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts#L209
3. Their id and version will be evaluated here: https://github.com/eclipse-theia/theia/blob/3bf8244332e57d5870c2aef1d0a7a1cdb021c7e9/packages/plugin-ext/src/common/plugin-identifiers.ts#L76
4. And come out as: 
```
{
   id: "publisher-name."
   version: "my-org/pluginA@x.x.x"
}
```
5. Then these plugins will be uninstalled, as they have same id and different versions, here: https://github.com/eclipse-theia/theia/blob/3bf8244332e57d5870c2aef1d0a7a1cdb021c7e9/packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts#L216

### Additional Information

- Operating System: macos 12.2.1
- Theia Version: since 1.27, won't reproduce on 1.26

**Comment by vnfedotov** [comment]
cc @colin-grant-work 
I think it's an impact of https://github.com/eclipse-theia/theia/pull/11084
Could you please check?

**Comment by colin-grant-work** [comment]
Thanks for the report; I will take a look ASAP.

**Comment by vince-fugnitto** [comment]
@vnfedotov do you happen to have examples to test with, I don't believe that including `@` in the extension name is valid when packaging with [vsce](https://github.com/microsoft/vscode-vsce) ([reference](https://github.com/microsoft/vscode-vsce/blob/955c76056f8f173e8cef180936b8c11c42af6be9/src/validation.ts#L25-L28), [regex](https://github.com/microsoft/vscode-vsce/blob/955c76056f8f173e8cef180936b8c11c42af6be9/src/validation.ts#L4)) and likely not permitted in the open-vsx marketplace as a result.

**Comment by colin-grant-work** [comment]
@vnfedotov, as @vince-fugnitto points out, `@` was never intended to be a permitted character in plugin publishers or plugin names; that it happened not to cause problems previously was a coincidence. It is possible to restore the previous behavior - more or less - but doing so could have unintended consequences since it makes the `@` sign ambiguous. Could you describe your use case in a bit more detail so that we can decide whether and how to support it?

**Comment by vnfedotov** [comment]
@colin-grant-work @vince-fugnitto, yes, sorry i wasn't able to reply earlier. Our use case is quite simple: we have a single lerna monorepo for theia plugins and common packages, shared by these plugins. Theia applications are also included in the monorepo, so there are no actual 'deployment' process for plugins that would require ovsx or vsce packaging. Theia application is running plugins right from the same repository without any additional steps. 

At first, we've used both vsce and open-ovsx, but they felt redundant as we deliver the end product as a monolith app and plugins are not intended to be publicly available.

**Comment by colin-grant-work** [comment]
@vnfedotov, thanks for your reply. Given that setup, it sounds like it would be fairly straightforward to adjust to names matching the standard for published plugins, although your plugins are not actually published. Is there a particular reason why scoping with `@` is important, or could similar ends be achieved using only the prescribed characters?

**Comment by vnfedotov** [comment]
@colin-grant-work, it's possible to remove scopes from plugin packages, that would hurt a bit as `lerna --scope` masks will become more esoteric. It's just feels weird to me that an existing npm package naming convention breaks theia plugins.

**Comment by vince-fugnitto** [comment]
> @colin-grant-work, it's possible to remove scopes from plugin packages, that would hurt a bit as `lerna --scope` masks will become more esoteric. 

Unfortunately, I do not believe that support for non-standard characters in the `name` such as `@` is important or has a high priority given that it causes [complications](https://github.com/eclipse-theia/theia/issues/11419#issuecomment-1185655119) and edge-cases that would to be handled. 

> It just feels weird to me that an existing npm package naming convention breaks theia plugins.

Plugins are not standard npm packages nor are they published to npm so it feels odd to generalize and treat them as such.
