### ISSUE TITLE
Unsupported activation events: onNotebook:jupyter-notebook

### ISSUE THREAD

**Issue by ariana02880** [eclipse-theia/theia#11430]
Hi Theia, 
When I run my theia today, I got this error, could you please help me debug this? Should i use a different version of vscode plugins:
root ERROR [hosted-plugin: 4030] Unsupported activation events: onNotebook:jupyter-notebook, please open an issue: https://github.com/eclipse-theia/theia/issues/new

Here is the python version and theia version i am using:
```
"@theia/core": "1.19.0",
...
 "vscode-python-features": "https://open-vsx.org/api/ms-python/python/2020.10.332292344/file/ms-python.python-2020.10.332292344.vsix",

```

**Comment by vince-fugnitto** [comment]
@ariana02880 I believe you already opened a similar issue in the past (https://github.com/eclipse-theia/theia/issues/11157#issue-1236397425), please see https://github.com/eclipse-theia/theia/issues/9867. The activation event and notebook APIs are not yet supported, you'll need to use an older version of the extension. The https://github.com/eclipse-theia/theia/issues/9867#issuecomment-902668769 suggests [2020.10](https://open-vsx.org/extension/ms-python/python/2020.10.332292344).
