### ISSUE TITLE
File watching broken on Windows

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11442]
### Steps to Reproduce:

1. Open application with `theia` as workspace and open Navigator.
2. Observe that `.git` is not displayed in the navigator.
3. Open preferences, search for `files.exclude`, click `Edit in JSON` link.
4. Set the value for the `"**/.git"` field to `false`.
5. Observe that the `.git` folder doesn't immediately appear.
6. Reload the application.
7. Observe the `.git` folder does appear in the Navigator.

### Additional Information

- Operating System: Windows 10, Firefox
- Theia Version: 78b7f9558bc35c2f0283e098191f1b24af2721e3

**Comment by colin-grant-work** [comment]
It appears to be a problem in the file watching system. Although the PreferenceProvider requests that its file be watched, no change events are fired when the file is modified.

**Comment by colin-grant-work** [comment]
In fact, it appears that there's no response to any file change on Windows. E.g. modifying a file on disk that is open in an editor produces no update.

**Comment by colin-grant-work** [comment]
This appears to be a consequence of the new RPC. At 53a272e1138, changing a preference file triggers the associated file events and preference events, but at 12ce278eb640e835650c8e683feb676d359dae42, the breakage is evident. @tortmayr, @JonasHelming

**Comment by tortmayr** [comment]
@colin-grant-work  Thanks for catching this. I'm looking into this issue right now and can hopefully provide a fix soon.

**Comment by tortmayr** [comment]
After some testing with the Theia exampel applications I discovered the following:
File watching does work as expected when using the VS code launch configuration but does not work when started from commandline. The difference is that the launch config uses the `--no-cluster` argument. Apparently this argument is used to [evaluate ](https://github.com/eclipse-theia/theia/blob/4b1220ac6602b794ff0369d01acd8b35f910e757/packages/filesystem/src/node/filesystem-backend-module.ts#L91)whether the `FileWatcherService` should be configured as normal backend service or should be launched in a separate process.
It looks like file watching is broken when the watcher service is launched in a separate process. This could be  related to the [issues](https://github.com/eclipse-theia/theia/pull/11261#discussion_r922258601) that @paul-marechal encountered with the `BinaryMessagePipe` under Windows.

**Comment by paul-marechal** [comment]
Ah if you are opening an extra pipe to the watcher process then it will not work on Windows indeed,

Can you pass messages through `process.send` and `process.on('message', ...)` for now? This works on all platforms.

A more annoying setup using named-pipes/unix-domain-sockets also works and more closely emulates using process pipes.

**Comment by tortmayr** [comment]
> Can you pass messages through process.send and process.on('message', ...) for now?

 I guess so. The messages sent via `FileSystemWatcherService` protocol seem to be rather small, so the overhead of converting them from binary to string and back should be negligible for now. In the long run we need a better solution, especially when thinking of the Plugin RPC process (https://github.com/eclipse-theia/theia/pull/11261)

**Comment by paul-marechal** [comment]
Honestly this issue with extra process pipes sucks because it looks like a problem with node itself: https://github.com/nodejs/node/issues/43936

I don't know when this will be fixed, and I wouldn't know how to fix it myself, so in the meantime the best alternative I could find is to setup this named-pipe communication between processes. It's not as convenient to use/implement, but it seem to be just as performant as regular pipes if it were to work.

I'll push a commit on top of https://github.com/eclipse-theia/theia/pull/11261 to setup what I just described if you don't mind.

In the meantime you should still use the regular Node IPC APIs (`process.send`) for all IPC servers?

**Comment by tortmayr** [comment]
>In the meantime you should still use the regular Node IPC APIs (process.send) for all IPC servers?

Yes, I will prepare a fix for this right away.
