### ISSUE TITLE
VSIX Extension deleted from system on uninstall

### ISSUE THREAD

**Issue by eneufeld** [eclipse-theia/theia#11463]
### Bug Description:
I found a behavior change that I'm not sure was intentional.
If I install a vscode extension that I downloaded and have locally then on uninstall the original vsix file is deleted.
I was able to track the change down to https://github.com/eclipse-theia/theia/pull/11084 . This behavior differs from the behavior in VSCode were the original file is not deleted on uninstall.

### Steps to Reproduce:

1. Install any vscode extension from vsix:  
![image](https://user-images.githubusercontent.com/1176277/180987821-499fb7be-db42-4c72-805f-8103b0bdd6e3.png)
2. Uninstall this extension
3. See that the file you installed is gone on the file system

### Additional Information

- Operating System: Ubuntu 20
- Theia Version: 1.27

**Comment by msujew** [comment]
cc @colin-grant-work this looks like an unintended consequence of your change

**Comment by colin-grant-work** [comment]
@eneufeld, @msujew, are you finding that some source file _other_ than that found in your user plugins folder is deleted, or only that the file in the user plugins directory is deleted? If the latter, that is the the intended behavior. It's true that VSCode doesn't immediately delete the file, though it will eventually delete the file. Our problem is that we can't track active sessions in the same way VSCode can - there may multiple sessions of Theia running simultaneously that are unaware of eachother, which is impossible for (desktop) VSCode - and so we can either delete the file immediately when the user signals their intent to uninstall it, or we can pick some point in the application lifecycle when we hope that it might be the right time to delete the file. The compromise implemented in #11084 is that a copy will be made of all plugins found in user area and that copy will be used  to run the plugin. That way, if one session uninstalls the plugin and deletes the source in the user plugin directory, no other running session will be affected by that deletion. Previously, when the user unistalled the plugin, the source would be deleted, but that source was also the running source for any sessions using that plugin, and so all running sessions lost access to the plugins, with many errors. I'm certainly open to improvements in the timing of deletion, but I think it's a tricky problem.

**Comment by msujew** [comment]
@colin-grant-work Actually the former: My usual workflow to test vscode API related PRs is to put the vsix file into the Theia repo and then install it from there. Uninstalling it again not only removes the unzipped extension from the user plugins directory but the `.vsix` file from the repo as well.

**Comment by eneufeld** [comment]
Hi @colin-grant-work ,
thank you for the quick response.
So if I install a vscode extension from a vsix that is in the location `~/Downloads/foo.vsix` and then uninstall the extension, then the `~/Downloads/foo.vsix` file is removed for me.

**Comment by colin-grant-work** [comment]
@msujew, @eneufeld alright, then that needs fixing :-).
