### ISSUE TITLE
Property 'removeLocalizations' does not exist on type 'LocalizationProvider'.

### ISSUE THREAD

**Issue by Can2Nya** [eclipse-theia/theia#11462]
### Bug Description:
When I use @theia/core standalone I get the following error：
```
 TS2339: Property 'removeLocalizations' does not exist on type 'LocalizationProvider'.
 @ ./src/hosted/node/plugin-service.ts 38:45-92
 @ ./src/index.ts 17:13-52
```
I found that the LocalizationProvider method does not exist in the downloaded npm package, but the git repository exists。
Do you need to republish to fix this?

### Additional Information

- Operating System: windows 10
- Theia Version: @theia/core@1.27.0

**Comment by vince-fugnitto** [comment]
@Can2Nya thank you for the issue, you'll need to wait for `v1.28.0` as `removeLocalizations` was only recently added https://github.com/eclipse-theia/theia/commit/3bf8244332e57d5870c2aef1d0a7a1cdb021c7e9#diff-21444580240414590c4f8ffd38530edc5719c9e0e6b2b25cc88c2cbe32085690R30.

**Comment by Can2Nya** [comment]
> @Can2Nya thank you for the issue, you'll need to wait for `v1.28.0` as `removeLocalizations` was only recently added [3bf8244#diff-21444580240414590c4f8ffd38530edc5719c9e0e6b2b25cc88c2cbe32085690R30](https://github.com/eclipse-theia/theia/commit/3bf8244332e57d5870c2aef1d0a7a1cdb021c7e9#diff-21444580240414590c4f8ffd38530edc5719c9e0e6b2b25cc88c2cbe32085690R30).
> 
> If you look at the `v1.27.0` tag you'll see that it does not exist yet.
> 
> * https://github.com/eclipse-theia/theia/blob/v1.27.0/packages/core/src/node/i18n/localization-provider.ts

think！
