### ISSUE TITLE
"yarn run watch" takes too much resources when starting

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#1147]
It is my understanding that doing "yarn" limits the number of parallel compilation processes (probably to the # of cpus).  However, doing "yarn run watch" launches all the processes simultaneously (one per package), and you have something like 28 processes compiling at the same time (there are 28 packages right now), competing for cpu and memory.  Once the initial compilation is done, everything works fine.  This makes my computer unresponsive for a good 2 minutes when starting the watch (ok, I'll give you that it's not the most recent computer on the market).  As a comparison, it would not be reasonnable to build a C++ program using "make -j 28" on a 4-cores system.  I understand that all watch processes need to be started in parallel because they all need to watch in parallel, but this will become a bigger problem with time, as the number of packages grows.  It would be nice to find a way to avoid that.  For example, would it be possible to avoid unnecessary recompilation if you do "yarn" followed by "yarn run watch"?  Otherwise, could the watch processes coordinate themselves to always have a limited number of them actually compiling at the same time?

**Comment by svenefftinge** [comment]
We should fix https://github.com/theia-ide/theia/issues/1134 so that developing packages externally is not so painful. Then we can limit the number of packages we develop in the core repository.

OTOH, @akosyakov recently found this ticket: https://github.com/Microsoft/TypeScript/issues/3469 Which will hopefully enhance `tsc` to take care of watching multiple packages in a monorepo.

**Comment by svenefftinge** [comment]
Someone could investigate if the proposal from this comment, could work for development/watch:
https://github.com/Microsoft/TypeScript/issues/3469#issuecomment-358486593

**Comment by akosyakov** [comment]
As a workaround, you can [watch](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#watch-a-specific-package) and [build](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#build-extension-packages-individually) only packages which you are working on with `npx run`. 

I  usually run 3 processes from the root:
- `npx run watch extension`, you can add `--include-filtered-dependendencies` if you also want to watch dependencies of an extension, but it is overkill usually
- `npx run watch example`
- `npx run start  example`

**Comment by akosyakov** [comment]
@svenefftinge I don't think we can have generally a single `index.ts` per an extension, only for extensions which can be used only in browser or node environments.

**Comment by simark** [comment]
Ok, thanks for the tip.  I also found that running `nice yarn run watch` made it more manageable (it doesn't freeze my UI).

**Comment by JonasHelming** [comment]
Watching works smoothly (6 years later :-)
I am closing this, please reopen if the issue persists.
