### ISSUE TITLE
plugin: cannot install two different plugin

### ISSUE THREAD

**Issue by yuze168** [eclipse-theia/theia#11481]
### Bug Description:
I have two different vscode plugin， part of the package.json of  first plugin  is
```json
{
    "name": "@byted/aircode-snippets",
    "version": "1.27.0",
    "publisher": "aircode",
}
```
part of the package.json of  second plugin  is
```json
{
    "name": "@byted/aircode-sourcekit-lsp",
    "version": "1.27.0",
    "publisher": "aircode",
}
```
When I started debugging the Thaia backend，the first plugin will be uninstall。

the reason is  function `idAndVersionFromVersionedId` in `plugin-identifiers.ts` return a wrong result.
https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/common/plugin-identifiers.ts
```TypeScript
export function idAndVersionFromVersionedId(probablyId: string): IdAndVersion | undefined {
    const endOfPublisher = probablyId.indexOf('.');
    const endOfName = probablyId.indexOf('@', endOfPublisher);
    if (endOfPublisher === -1 || endOfName === -1) {
        return undefined;
    }
    return { id: probablyId.slice(0, endOfName) as UnversionedId, version: probablyId.slice(endOfName + 1) };
}
```

the first plugin's versionedId is  `aircode.@byted/aircode-snippets@1.27.0`. and return result is 
`
{
id: aircode.
version: byted/aircode-snippets@1.27.0
}
`
the secend plugin's versionedId is` aircode.@byted/aircode-sourcekit-lsp@1.27.0`. and return result is
` {
id: aircode.
version: byted/aircode-sourcekit-lsp@1.27.0
}`

two plugin's id is equal and version is not equal，the first plugin will be uninstall。
https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts
```TypeScript
protected markAsInstalled(id: PluginIdentifiers.VersionedId): void {
        const metadata = PluginIdentifiers.idAndVersionFromVersionedId(id);
        if (metadata) {
            const toMarkAsUninstalled: PluginIdentifiers.VersionedId[] = [];
            const checkForDifferentVersions = (others: Iterable<PluginIdentifiers.VersionedId>) => {
                for (const other of others) {
                    const otherMetadata = PluginIdentifiers.idAndVersionFromVersionedId(other);
                    if (metadata.id === otherMetadata?.id && metadata.version !== otherMetadata.version) {
                        toMarkAsUninstalled.push(other);
                    }
                }
            };
            checkForDifferentVersions(this.deployedFrontendPlugins.keys());
            checkForDifferentVersions(this.deployedBackendPlugins.keys());
            this.uninstallationManager.markAsUninstalled(...toMarkAsUninstalled);
            this.uninstallationManager.markAsInstalled(id);
            toMarkAsUninstalled.forEach(pluginToUninstall => this.uninstallPlugin(pluginToUninstall));
        }
    }
```

**Comment by msujew** [comment]
@yuze168 We already had a discussion on this issue two weeks ago, see [https://github.com/eclipse-theia/theia/issues/11419]. We decided that we won't support that use case, as vscode extensions aren't normal npm packages and even [vsce](https://github.com/microsoft/vscode-vsce/blob/955c76056f8f173e8cef180936b8c11c42af6be9/src/validation.ts#L25-L28) will reject those extension names.
