### ISSUE TITLE
Inline Suggestions Not Support 

### ISSUE THREAD

**Issue by venciallee** [eclipse-theia/theia#11488]
### Feature Description:

The inline suggestions API allows extensions to provide inline suggestions, which need to support `vscode.languages.registerInlineCompletionItemProvider` API, Any plan to support `registerInlineCompletionItemProvider` ?

![inline-suggestions](https://user-images.githubusercontent.com/3282495/182059949-1a84de23-3604-409e-899b-0146a5eca0be.gif)

[VSCode inline suggesstions](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_58.md#inline-suggestions)

**Comment by msujew** [comment]
Hey @venciallee we're currently closing in on vscode 1.55.2 compatibility with Theia, see https://github.com/eclipse-theia/theia/issues/9863. As the inline suggestions API has been added with vscode 1.58.0, it's not our highest priority right now, but contributions in that direction are still always welcome :)

**Comment by msujew** [comment]
This API is supported as of https://github.com/eclipse-theia/theia/pull/11901.
