### ISSUE TITLE
Trigger the save box twice

### ISSUE THREAD

**Issue by web-liuyang** [eclipse-theia/theia#11489]
### Bug Description:

The save Dialog was fired twice。

This is the method entry
https://github.com/eclipse-theia/theia/blob/0c0f8c7a7aedd67930bf65d6f63d827721707d60/packages/core/src/browser/shell/application-shell.ts#L1516-L1525

This is the method called in Saveable#confirmSaveBeforeClose
https://github.com/eclipse-theia/theia/blob/0c0f8c7a7aedd67930bf65d6f63d827721707d60/packages/core/src/browser/saveable.ts#L149

This is when the closeWithSaving method is called in this.closeWidget, which in turn calls createCloseWithSaving, however, this method reopens the save Dialog
https://github.com/eclipse-theia/theia/blob/0c0f8c7a7aedd67930bf65d6f63d827721707d60/packages/core/src/browser/saveable.ts#L128

#
### 

### Steps to Reproduce:

1. Call the EditorManager#closeAll method and pass in the undefined parameter

### Additional Information

- Operating System: all
- Theia Version: main

**Comment by msujew** [comment]
@web-liuyang Can you give more context on when this exactly happens? I can't reproduce the behavior. The `Close All` command for example calls the `closeMany` method without the `options` parameter, but I only see a single confirmation dialog nonetheless.

**Comment by web-liuyang** [comment]
> @web-liuyang Can you give more context on when this exactly happens? I can't reproduce the behavior. The `Close All` command for example calls the `closeMany` method without the `options` parameter, but I only see a single confirmation dialog nonetheless.

Thanked your reply.

I injected the class via IOC and called closeAll

https://github.com/eclipse-theia/theia/blob/0c0f8c7a7aedd67930bf65d6f63d827721707d60/packages/editor/src/browser/editor-manager.ts#L37
