### ISSUE TITLE
Handling of multiple paths referring to the same file

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#1148]
Context: sometimes, clangd will return non-normalized path, for example, `/home/simark/src/repro/build/../src/repro.h`.  If we happen to have `/home/simark/src/repro/src/repro.h` already open, Theia will open a new editor tab, thinking it is a new file.  In reality, it is the same file, and Theia should use the already open editor tab.

I don't know if clangd should return normalized paths (I asked [here](http://lists.llvm.org/pipermail/cfe-dev/2018-January/056710.html)), but I think that Theia should handle it gracefully, because it could happen in other situations too.

To make it easier to reproduce it (without involving clangd and a c/c++ project), I made a dummy change available in this branch:

https://github.com/theia-ide/theia/tree/repro-non-normalized-paths

I added two commands, that try to open `/usr/include/stdio.h` and `/usr/lib/../include/stdio.h` respectively.  The two paths refer to the same file, but the second one is not normalized.  If you execute the two commands (they are called "Hello 1!" and "Hello 2!"), two editor tabs will open.  I think that Theia should be smarter and open only one.

I tested this with vscode:

    $ code /usr/lib/../include/stdio.h
    $ code /usr/include/stdio.h

And it only opens one tab, referring to `/usr/include/stdio.h` (shown if you hover the editor tab).

**Comment by svenefftinge** [comment]
Yes, the EditorManager should normalize the URIs.

**Comment by svenefftinge** [comment]
CC/ @AlexTugarev It should solve the issue I found in the opening of links in rendered markdown, too, no?

**Comment by AlexTugarev** [comment]
This is about removing dot-segments to normalize the uri, and I added just the shortening of uri at https://github.com/theia-ide/theia/blob/master/packages/editor/src/browser/editor-manager.ts#L102. I think we need the full normalization of resource uris, and preferably in the namespace of `URI` to be able to reuse it easily, right? 

The preview extension should also normalize the dots.

**Comment by vince-fugnitto** [comment]
I've tested the following use case (using an example of my own since the original is unavailable), and found that the application now correctly handles normalization of paths.

Despite the different paths, only a single editor is opened 👍
