### ISSUE TITLE
Debug Hover Widget might not appear for evaluated expressions

### ISSUE THREAD

**Issue by ndoschek** [eclipse-theia/theia#11500]
### Bug Description:

If using the [VSCode Mock Debug extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mock-debug), the Debug Hover widget does not appear on evaluated variables.
Using the Debugger for Java (identifier: vscjava.vscode-java-debug) and an custom evaluatable expression provider for `java` works however without problems.

I investigated the matter timeboxed, and the behaviour of the variable evaluation cycle differs a little from the VSCode behaviour.
In [`debug-hover-source.tsx`](https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/editor/debug-hover-source.tsx) the expression is evaluated correctly, and returns an `ExpressionItem` (L#50).
Then it tries to fetch the available items (L#51), i.e. the declared variables, and sends another `variables` request to the `MockDebugSession`, which does not return any variables (which is not clear to me yet why it does not return them in that case, earlier it sure does return variables). Since this list of `elements` is empty, the hover widget is not rendered.
I could not track down the actual cause of this yet, it will most likely need some further investigation.

This originated from #11484

Remark: Currently it is necessary to omit the registration of an `InlineValuesProvider` and bundle the extension yourself to be able to use it with Theia (until #10028 is resolved).

### Steps to Reproduce:

1. Use the VSCode Mock Debug extension (currently necessary to omit the registration of an `InlineValuesProvider` and bundle yourself)
2. Debug the provided test readme file with variable declarations (e.g. `$i=123`).
3. Hovering over the declared variables triggers the evaluation of the variable, but does not show the hover widget with the evaluated variable value (would expect to show `123`, as it does in VSCode).

### Additional Information

- Operating System: Ubuntu 20.04
- Theia Version: `1.28.0`

**Comment by alvsan09** [comment]
Hi @ndoschek, 
Do you know if anyone has started on this task?
If not, I could take a look !
