### ISSUE TITLE
[vscode] Support specifying the `location` in terminal options

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11506]
The enum type [`TerminalLocation`](https://code.visualstudio.com/api/references/vscode-api#TerminalLocation) defines where a terminal shall be located (`Panel` or `Editor`) and can be specified in the property `location` of:

- [ ] [`TerminalOptions`](https://code.visualstudio.com/api/references/vscode-api#TerminalOptions): missing optional property `location`
- [ ] [`ExtensionTerminalOptions`](https://code.visualstudio.com/api/references/vscode-api#ExtensionTerminalOptions): missing optional property `location`
- [ ] [`TerminalEditorLocationOptions`](https://code.visualstudio.com/api/references/vscode-api#TerminalEditorLocationOptions): entire type is missing
- [ ] [`TerminalSplitLocationOptions`](https://code.visualstudio.com/api/references/vscode-api#TerminalSplitLocationOptions): entire type is missing

Related VSCode API issues:
- #11138
- #11504 
- #11503

**Comment by xai** [comment]
I'll have a look at this.
