### ISSUE TITLE
[vscode] Support querying whether file system and file stats are readonly

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11509]
The VS Code API can be used to query whether the file system or single file stats are readonly:

 - [ ] [`FileStat.permissions`](https://code.visualstudio.com/api/references/vscode-api#FileStat), which requires enum type [`FilePermission`](https://code.visualstudio.com/api/references/vscode-api#FilePermission)
 - [ ] [`FileSystem.isWritableFileSystem(scheme: string)`](https://code.visualstudio.com/api/references/vscode-api#FileSystem)

**Comment by JonasHelming** [comment]
@msujew volunteered to take this one

**Comment by msujew** [comment]
Note that this also requires support for https://github.com/eclipse-theia/theia/issues/199, as we currently have no way of actually defining that a file/editor is readonly.
