### ISSUE TITLE
[vscode] Support optional properties `iconPath` and `color` in `TerminalOptions` and `ExtensionTerminalOptions`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11504]
The type [`TerminalOptions`](https://code.visualstudio.com/api/references/vscode-api#TerminalOptions) and [`ExtensionTerminalOptions`](https://code.visualstudio.com/api/references/vscode-api#ExtensionTerminalOptions) miss the optional properties:

- [ ] `iconPath`: The icon path or `ThemeIcon` for the terminal
- [ ] `color`: `ThemeColor` for the terminal

Related VSCode API issues:
- #11503
- #11138
- #11506

**Comment by rschnekenbu** [comment]
I will work on this task, please assign it to me.

**Comment by JonasHelming** [comment]
@rschnekenbu Should we add a new ticket for the stubbed parts and add it to the stub umbrella ticket?

**Comment by rschnekenbu** [comment]
#12074 will track down the remaining part of the work. I'll ask Philip to edit the umbrella ticket.
