### ISSUE TITLE
[vscode] Support optional `WebviewOptions.enableForms`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11517]
See also https://code.visualstudio.com/api/references/vscode-api#WebviewOptions

**Comment by tsmaeder** [comment]
This should be rather easy to implement.

**Comment by planger** [comment]
@sgraband will look into this task.

**Comment by tsmaeder** [comment]
Have a look  at packages\plugin-ext\src\main\browser\webview\pre\main.js#479 ff.
