### ISSUE TITLE
[vscode] Support indicating and notifying changes on `Terminal.state`

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#11515]
Theia misses the property [`Terminal.state`](https://code.visualstudio.com/api/references/vscode-api#Terminal), its type [`TerminalState`](https://code.visualstudio.com/api/references/vscode-api#TerminalState) and the event emitter `window.onDidChangeTerminalState`.

**Comment by xai** [comment]
I'll have a look at this.
