### ISSUE TITLE
[docker] Theia development image

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#1153]
This discussion was started in this [PR](https://github.com/theia-ide/theia/pull/1135#discussion_r164103344) .

For convenience, here are screen captures: 

![image](https://user-images.githubusercontent.com/25749063/35512844-17e1b520-04cf-11e8-8781-ffaa10a48b7b.png)
![image](https://user-images.githubusercontent.com/25749063/35512873-2a3f1e7e-04cf-11e8-8727-78083a1656ba.png)

**Comment by marcdumais-work** [comment]
@svenefftinge So IIUC the plan would be, when we eventually move non-core extension each to their own repo, they could then have a (single) more specialized dev image, containing specific dependencies (e.g. JDK for the Java extension, clangd for the C/C++ ext, ..). That sounds good to me. 

What shall we do in the meantime? Would it be ok to temporarily add the dependencies in the dev image here, when needed (JDK)?

**Comment by marcdumais-work** [comment]
@akosyakov about running the Electron app in docker: this could be an enabler: https://github.com/theia-ide/theia/issues/174 . We plan to work on that issue relatively soon.

**Comment by svenefftinge** [comment]
> What shall we do in the meantime? Would it be ok to temporarily add the dependencies in the dev image here, when needed (JDK)?

Yes

**Comment by akosyakov** [comment]
Could we at least move dev docker files to another folder from the browser example? Like `dockerfiles` under the root?

**Comment by vince-fugnitto** [comment]
The issue is now outdated since the example `Dockerfile` has recently been removed from the repository since it was unmaintained/unused: https://github.com/eclipse-theia/theia/pull/6585
