### ISSUE TITLE
[vscode] Perform HTTP request fails after changing color theme.

### ISSUE THREAD

**Issue by hyy215** [eclipse-theia/theia#11551]
### Bug Description:
Perform HTTP request fails after changing color theme.

### Steps to Reproduce:
1. Install [vsix](https://github.com/hyy215/vsx-demo/blob/master/request-demo/request-demo-1.0.3.vsix).
2. Run `Perform A Get Request` command.
```ts
axios.get('https://www.google.com/').then(v => {
    vscode.window.showInformationMessage('status:' + v.status);
}).catch(e => {
    vscode.window.showErrorMessage('Error: ' + e);
});
```
3. Select another color theme, and run `Perform A Get Request` command again, but the result is fails.

![require-demo](https://user-images.githubusercontent.com/34715914/183847402-738d7aa0-0534-409e-8189-d32d6c13dbc0.gif)

### Additional Information

- Operating System: win10
- Theia Version: 1.28.0, but also lastest master (https://github.com/eclipse-theia/theia/commit/1c0253adc71fa59d6ca7aef0797d3ba0c7d7d36c)

**Comment by msujew** [comment]
I can confirm that it happens (on different platforms even), but I'm really confused about why.

**Comment by hyy215** [comment]
> I can confirm that it happens (on different platforms even), but I'm really confused about why.

@msujew It doesn't happen when removing this line. 
https://github.com/eclipse-theia/theia/blob/2293a5b7472309dcedfe094d8d183a42a95788fe/packages/monaco/src/browser/monaco-workspace.ts#L221

**Comment by hyy215** [comment]
It doesn't happen in the 1.39.0
