### ISSUE TITLE
Fix electron window close handling for secondary windows

### ISSUE THREAD

**Issue by lucas-koehler** [eclipse-theia/theia#11574]
### Bug Description:

This is a follow up issue of #11048 .
When closing a web view, which was moved to an external window, an `Uncaught illegal access` is logged in the console. This might not always happen but is reproducible quite easily with a few retries. When this error occurs, re-opening the same view again often fails. While the error was also observed on Ubuntu, the re-opening problems were so far only observed on Windows. However, they could stil appear on other OS, too

The problem most likely is that the error is thrown during closing of the external window. In turn, its close handlers are not executed. However, the `secondary-window-handler` relies on these handlers being executed correctly to keep track of widgets in external windows.

### Steps to Reproduce:

1. Install the cat coding extension or another extension providing a web view
2. Add the `secondary-window-ui` extension to the electron example application
3. Start the electron example app
4. Open the cat coding web view and move it to an external window
5. Close the external window
6. Observe the console. It should show an ``Uncaught illegal access` error. If not go back to step 4
7. Try to open the cat coding web view again. If it still works, go back to step 5.

### Additional Information

- Operating System: all but mainly Windows
- Theia Version: 1.28

**Comment by tsmaeder** [comment]
I was trying to find out why opening the file sometimes starts to fail: it looks like the sending of accumulated messages in the rpc-protocol doing the communication with the plugins starts to fail: messages are still added to `messageToSend`, `sendAccumulatedBound` does not seem to be invoked anymore. I really don't understand how that could happen, unless the `set immediate(...)` fails somehow.

**Comment by tsmaeder** [comment]
I experimented with @sdirix's suggestion to remove the widget before closing the window. This is the right direction, but it doesn't work: closing (and possibly saving) the widget creates promises, which we can't wait for in any DOM event handlers, so we can always construct a case where the "illegal access" comes back.

The only clean way to do this is this:

1. Prevent closing the window, but start a promise that will remove the widget from the secondary window. 
2. Once the closing of the widget is done (it may be canceled via the "save"-dialog), go ahead and really close the secondary window.

**Comment by tsmaeder** [comment]
This was a Electron bug related to disposing javascript contexts. This is fixed by using context isolation
