### ISSUE TITLE
Consider renaming eclipse-theia/theia-playwright-template => theia-example-use-playwright-tests

### ISSUE THREAD

**Issue by frank-dspeed** [eclipse-theia/theia#11591]
### Feature Description:
Consider renaming eclipse-theia/theia-playwright-template => theia-example-use-playwright-tests

i also want additional propose to name it only example-use-playwright-tests as theia is alredy included in the org

eclipse-theia/theia- the secund theia is redundant and maintainers of large repos do always use full url as reference anyway.

## Collection of Name change Proposals
see:
~- [ ] - https://github.com/eclipse-theia/theia-blueprint/issues/230~
~- [ ] - https://github.com/eclipse-theia/theia-cpp-extensions/issues/151~
~- [ ] - https://github.com/eclipse-theia/security-audit/issues/13~

**Comment by vince-fugnitto** [comment]
@frank-dspeed we do not plan on renaming as you've suggested, nor the other repos under the `eclipse-theia` organization, they will cause unnecessary breaking changes (for downstream applications, and documentation links, videos, articles). 

> eclipse-theia/theia- the secund theia is redundant and maintainers of large repos do always use full url as reference anyway.

The second `theia` is not redundant, [`eclipse-theia`](https://github.com/eclipse-theia) is the organization, and `theia` is the repository.

**Comment by frank-dspeed** [comment]
ok sure i understand that and its ok for me at last it will break backporting from us later to your documentation then. 

Thanks for the fast feedback.
