### ISSUE TITLE
New React error in TreeWidget after `react-virtuoso` change

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#11594]
### Steps to Reproduce:

1. Start the application
2. (Maybe open the plugin view?)
3. See an error like this: 

![image](https://user-images.githubusercontent.com/62660806/185945957-7515fc01-1a8c-46b0-9bca-a279e3fcc6db.png)

### Additional Information

- Operating System: Windows 10, Edge browser
- Theia Version: 3e664e7adcef4e19321ddfe209ec17796fa96bf4

**Comment by colin-grant-work** [comment]
@msujew

**Comment by msujew** [comment]
@colin-grant-work Thanks, I'll look into it 👍
