### ISSUE TITLE
Cannot create new window after reload the current empty window 

### ISSUE THREAD

**Issue by inlann** [eclipse-theia/theia#11600]
### Bug Description:

New Window does not work after reload the current window.  

BTW, you can open a new window (window 2) before reload it (window 1) and reload the window 2. And then, the menu item New Window of window 2 (that means window 2 is actived) does not work anymore, but the menu item New Window of window 1 (that means window 1 is actived) still works.

### Steps to Reproduce:

1. Run the electron example: (We can see the window 1)
    ![](https://community.theia-ide.org/uploads/default/original/2X/1/16b53ffabbc47925af67a219e74d2af488d0f9c7.jpeg)

2. Reload the window: (Reload the window 1)
    ![](https://community.theia-ide.org/uploads/default/original/2X/6/64bae7cb45bef19f9fb2bf0a40d75242a89f144a.jpeg)
    ![](https://community.theia-ide.org/uploads/default/original/2X/f/fdba5432f8692fb36a8fc2c9207bddc5525f0c40.png)

3. Click the New Window in the menu but it does not work: (Cannot create a new window)
    ![](https://community.theia-ide.org/uploads/default/original/2X/a/afdd80c99e02d545b7524fb6bef431848deaa2c7.jpeg)

### Additional Information

- Operating System: MacOS
- Theia Version: master branch

**Comment by kittaakos** [comment]
I am also having issues reloading the windows. I have noticed that the electron-main process and the `TheiaElectronWindow` receives the reload request, but all the `isSender` calls evaluate as `false`.

Wouldn't it be better to compare the `even.sender.id` with `this._window.webContents.id` here? 

https://github.com/eclipse-theia/theia/blob/0f949c2149154061efad01da50b6827985f3e454/packages/core/src/electron-main/theia-electron-window.ts#L183-L185

@colin-grant-work, could you please take a look? Thank you!

Related thread: https://github.com/electron/electron/issues/16863#issuecomment-1064469926

**Comment by msujew** [comment]
@kittaakos Thank you for investigating this. Do you plan on creating a PR on your own? I'll gladly review it.

**Comment by kittaakos** [comment]
Sure. If this seems to be the proper fix, I am happy to push it back.

**Comment by msujew** [comment]
It seems pretty reasonable to me. I assume that ids aren't reused by Electron, so comparing between the `BrowserWindow` instances and the IDs should accomplish the same thing.

**Comment by kittaakos** [comment]
I will take a look next week. Please assign the task to me.
