### ISSUE TITLE
secondary-window: Respect autoSave

### ISSUE THREAD

**Issue by lucas-koehler** [eclipse-theia/theia#11646]
### Feature Description:
The issue tracks a known limitation from https://github.com/eclipse-theia/theia/pull/11048 that webviews (esp. custom editors) in secondary windows do not respect the autoSave option.

### Steps to Reproduce:
1. start the browser-app with the [custom-editor-sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample)
2. start the application with [exampleFiles](https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample/exampleFiles) as a workspace
3. ensure that `autoSave` is `off`
4. open `example.cscratch`
5. add/remove entries in the file - confirm the file is dirty and closing the file prompts users
6. open `example.cscratch` in a secondary window
7. add/remove entries in the file - no visual indicator that the file is dirty
8. attempt to close the dirty window - the window is closed, and a dialog appears after the fact in the main window (related https://github.com/eclipse-theia/theia/issues/11647)
9. if you use `cancel` in the dialog the file can never be re-opened unless the app is restarted.

https://user-images.githubusercontent.com/40359487/191014715-4840d983-c0c9-44de-8305-511c854058c5.mov

**Comment by tsmaeder** [comment]
@lucas-koehler by "respecting autosave" you mean that there is no dialog asking to save when the editor is closed when dirty? If so, this is a problem that existed before.

**Comment by lucas-koehler** [comment]
I believe this was discovered by vince and means that the auto save was not executed after a change.
@vince-fugnitto Do you remember details on this, i.e. what didn't work and which extension you used when discovering this?

**Comment by vince-fugnitto** [comment]
@lucas-koehler @tsmaeder I updated the pr with additional steps to reproduce the bug.

**Comment by tsmaeder** [comment]
Done as part of #11642
