### ISSUE TITLE
search-in-workspace: add support for multi-line searches

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11656]
#### Feature Description:

The goal is to add support for **multi-line** searches in the `search-in-workspace` view.
The changes likely include:
- updating the `input` to a `textarea`
- passing the proper options to `ripgrep`

_vscode above - theia below_:

![Screen Shot 2022-09-09 at 12 45 16 PM](https://user-images.githubusercontent.com/40359487/189400359-333b0960-5bd4-4a3f-a9d5-9c16482e3fb5.png)

#### How to test:

1. search the following in the `search-in-workspace` view:

```ts
export const GettingStartedCommand = {
    id: GettingStartedWidget.ID,
    label: GettingStartedWidget.LABEL
};
```

**Comment by KR155E** [comment]
I have [implemented this feature](https://github.com/KR155E/theia/commit/b9b5d18d0472e53230ebdb7ee6fb678be3ef3909) and am almost ready to submit a PR. But there's one remaining issue I can't quite get to the bottom of. For _opened files_, only the first line of a multiline search is being returned as the search result. Do you have an idea what might be causing this?

**Comment by vince-fugnitto** [comment]
@KR155E the _opened files_ are handled separately since we cannot rely on their disk content given that there might be unsaved changes. We therefore search the in-memory editor model. You may be interested in the following:

- [`searchActiveEditor`](https://github.com/eclipse-theia/theia/blob/441c5a1cf432f29449eab2919ebc5781d0ea8787/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L375)
- [`searchInOpenEditors`](https://github.com/eclipse-theia/theia/blob/441c5a1cf432f29449eab2919ebc5781d0ea8787/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L411)
- [`searchInEditor`](https://github.com/eclipse-theia/theia/blob/441c5a1cf432f29449eab2919ebc5781d0ea8787/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L442)

and probably most importantly:

- [`findMatches`](https://github.com/eclipse-theia/theia/blob/441c5a1cf432f29449eab2919ebc5781d0ea8787/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L292)

**Comment by KR155E** [comment]
I see, makes a lot of sense. 

`lineText` in `findMatches` will always return only the first line of a match. Modifying that got things working correctly. I will see if I can clean up the code and will then submit a PR.

Thanks for the help!
