### ISSUE TITLE
Localization Source String Issue

### ISSUE THREAD

**Issue by chidcrushev** [eclipse-theia/theia#11662]
Hi team,

We're using theia 1.27.0 and I came across this string(https://github.com/eclipse-theia/theia/blob/v1.27.0/packages/workspace/src/browser/workspace-trust-preferences.ts#L37) for our language translation process. 

String ID: `'theia/workspace/trustEnabled'`
String: `Controls whether or not workspace trust is enabled. If disabled, all workspaces are trusted.`

The string is not meaningful. Actually, it should be, _Controls whether or not workspace trust is enabled. If **enabled**, all workspaces are trusted._ right?

Regards,
Chid.

**Comment by msujew** [comment]
Hey @chidcrushev,

"workspace trust" is a feature, which will prevent certain extensions from executing code within your workspace, if the workspace is not trusted. I.e. as long as the feature is enabled, certain workspaces will not be trusted, unless the user explicitly trusts them. On the other hand, if the feature is disabled, all workspaces are trusted by default. In that sense, the preference description is absolutely correct. Does that make sense to you?

**Comment by chidcrushev** [comment]
Yes, makes sense to me. Thanks and we can close this!!
