### ISSUE TITLE
Can't create terminal when launch electron backend in vscode.

### ISSUE THREAD

**Issue by hyy215** [eclipse-theia/theia#11668]
### Bug Description:
Can't create terminal when launch electron backend in vscode.

### Steps to Reproduce:
1. open vscode.
2. Enter 'F5'  to launch electron backend.
3. open the terminal.

![terminal](https://user-images.githubusercontent.com/34715914/190296258-9c7b7ad9-21b9-433a-9231-96219a88f6bd.gif)

### Additional Information

- Operating System: win10
- Theia Version: master([9142e6d](https://github.com/eclipse-theia/theia/commit/9142e6da3fccc078a5a9b06469fa2fcba1f8bd6c))

**Comment by inlann** [comment]
You need to check if there is any errors in your backend console since your titlebar is missing and your frontend windows does not work correctly.

**Comment by vince-fugnitto** [comment]
@hyy215 any update or can the issue be closed?

**Comment by hyy215** [comment]
> You need to check if there is any errors in your backend console since your titlebar is missing and your frontend windows does not work correctly.

@inlann @vince-fugnitto No error log in backend console.
![terminal](https://user-images.githubusercontent.com/34715914/194683713-bbe9c8a8-a6a7-4a08-a7a0-7e97d40e01f0.gif)

**Comment by mblout** [comment]
i am seeing something similar launching theia in a **browser on windows**
if I run from theia CLI and open localhost:3000, opening a cmd terminal works.  
but launched from (electron) theia ide, opening the terminal does not work
**except** when i set breakpoints to debug the issue, and then sometimes it works. a connection timing issue?
(Still trying to understand the proxy enough/code to debug, but no obvious console errors)

**Comment by msujew** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/12733, as that contains a bit more info on why this happens.
