### ISSUE TITLE
@theia/ffmpeg package is include for browser applications

### ISSUE THREAD

**Issue by federicobozzini** [eclipse-theia/theia#11698]
### Bug Description:

It looks like the @theia/ffmpeg extension is imported when a Theia browser app is created. [This is due to a dependency from `@theia/cli` to `@theia/ffmpeg`](https://github.com/eclipse-theia/theia/blob/master/dev-packages/cli/package.json#L35) (and [from `@theia/application-manager` to `@theia/ffmpeg`](https://github.com/eclipse-theia/theia/blob/master/dev-packages/application-manager/package.json#L37)). `ffmpeg` is not used by Theia browser, shouldn't this be avoided?

### Steps to Reproduce:

1. This should be clear from the chain of dependencies of `@theia/cli` and `@theia/application-manager`.

### Additional Information

- Operating System: All
- Theia Version: 1.29

**Comment by thegecko** [comment]
cc @paul-marechal

**Comment by paul-marechal** [comment]
I don't see the problem as `@theia/cli` is a development dependency only, i.e. it should not be included in the final application. Sure if you're only targeting the browser then you won't use it, but you're also not using all the Electron generator code included with the CLI.

Is there an issue beside just being present?

**Comment by paul-marechal** [comment]
I'd like to give some background info about why `@theia/ffmpeg` was added to `@theia/cli`:

1. It is more convenient to have it there and being able to run `@theia/cli` commands to execute the ffmpeg validation.
2. It is painful to properly handle the `@theia/ffmpeg` as an optional peer dependency, we also can't make it a dependency of `@theia/electron` because it is a runtime dependency and we don't want `@theia/ffmpeg` to be part of runtime dependencies.

I can't find a written record of when this decision was taken, but I remember asking at least part of community when this change was made, and it was agreed to do this way.

**Comment by federicobozzini** [comment]
Thanks for the explanation @paul-marechal .

I was just surprised that if one builds a basic Theia application following [the official documentation](https://theia-ide.org/docs/composing_applications#building), replacing `yarn` with `yarn --ignore-scripts` would generate an error about `@theia/ffmpeg` even when the package would not be used at all. I think this used to be possible prior to [this change](https://github.com/eclipse-theia/theia/pull/9936) where the `@theia/ffmpeg` extension and a `prepare` script for `@theia/cli` were introduced.

If there is no interest in supporting the `yarn --ignore-scripts` command, this change should not be a problem at all and this issue can be closed.

**Comment by federicobozzini** [comment]
Sure.

To reproduce you can use this basic `package.json` file:

```
{
  "name": "theia-example",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@theia/callhierarchy": "latest",
    "@theia/file-search": "latest",
    "@theia/git": "latest",
    "@theia/markers": "latest",
    "@theia/messages": "latest",
    "@theia/mini-browser": "latest",
    "@theia/navigator": "latest",
    "@theia/outline-view": "latest",
    "@theia/plugin-ext-vscode": "latest",
    "@theia/preferences": "latest",
    "@theia/preview": "latest",
    "@theia/search-in-workspace": "latest",
    "@theia/terminal": "latest",
    "@theia/vsx-registry": "latest"
  },
  "devDependencies": {
    "@theia/cli": "latest"
  },
  "scripts": {
    "prepare": "yarn run clean && yarn build",
    "clean": "theia clean",
    "build": "theia build --mode development",
    "start": "theia start"
  }
}
```

You can then run `yarn --ignore-scripts` (no errors here) and then `yarn build`. What you should see is something similar to:

```
$ yarn build
yarn run v1.22.19
$ theia build --mode development
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '../build/Debug/ffmpeg.node'
Require stack:
- /path_to_prj/node_modules/@theia/ffmpeg/lib/ffmpeg.js
- /path_to_prj/node_modules/@theia/ffmpeg/lib/index.js
- /path_to_prj/node_modules/@theia/application-manager/lib/application-package-manager.js
- /path_to_prj/node_modules/@theia/application-manager/lib/index.js
- /path_to_prj/node_modules/@theia/cli/lib/theia.js
- /path_to_prj/node_modules/@theia/cli/bin/theia
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/path_to_prj/node_modules/@theia/ffmpeg/lib/ffmpeg.js:27:37)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path_to_prj/node_modules/@theia/ffmpeg/lib/ffmpeg.js',
    '/path_to_prj/node_modules/@theia/ffmpeg/lib/index.js',
    '/path_to_prj/node_modules/@theia/application-manager/lib/application-package-manager.js',
    '/path_to_prj/node_modules/@theia/application-manager/lib/index.js',
    '/path_to_prj/node_modules/@theia/cli/lib/theia.js',
    '/path_to_prj/node_modules/@theia/cli/bin/theia'
  ]
}
error Command failed with exit code 1.
```
