### ISSUE TITLE
vscode: add `tab` related apis

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11692]
#### Feature Description:

The goal is to add support for `tab` related VS Code APIs including:

- [ ] [`Tab`](https://code.visualstudio.com/api/references/vscode-api#Tab)
- [ ] [`TabChangeEvent`](https://code.visualstudio.com/api/references/vscode-api#TabChangeEvent)
- [ ] [`TabGroup`](https://code.visualstudio.com/api/references/vscode-api#TabGroup)
- [ ] [`TabGroupChangeEvent`](https://code.visualstudio.com/api/references/vscode-api#TabGroupChangeEvent)
- [ ] [`TabGroups`](https://code.visualstudio.com/api/references/vscode-api#TabGroups)
- [ ] [`TabInputCustom`](https://code.visualstudio.com/api/references/vscode-api#TabInputCustom)
- [ ] [`TabInputNotebook`](https://code.visualstudio.com/api/references/vscode-api#TabInputNotebook)
- [ ] [`TabInputNotebookDiff`](https://code.visualstudio.com/api/references/vscode-api#TabInputNotebookDiff)
- [ ] [`TabInputTerminal`](https://code.visualstudio.com/api/references/vscode-api#TabInputTerminal)
- [ ] [`TabInputText`](https://code.visualstudio.com/api/references/vscode-api#TabInputText)
- [ ] [`TabInputTextDiff`](https://code.visualstudio.com/api/references/vscode-api#TabInputTextDiff)
- [ ] [`TabInputWebview`](https://code.visualstudio.com/api/references/vscode-api#TabInputWebview)

**Comment by b4s36t4** [comment]
@vince-fugnitto can you help me though implementing these things?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto can you help me though implementing these things?

@b4s36t4 the change is pretty significant but if you want more details you can take a look at https://github.com/eclipse-theia/theia/blob/master/doc/Plugin-API.md. If you want to work on these APIs or any API  please don't hesitate to ask specific questions.

**Comment by b4s36t4** [comment]
https://github.com/eclipse-theia/theia/tree/master/packages/plugin-ext
I need to add the API thing in this package right @vince-fugnitto? is there any simpler way to communicate I'm new to these things and might need help of you more 😅

**Comment by vince-fugnitto** [comment]
@b4s36t4 given you're new to the project I'd maybe suggest a simpler API to start, you can take a look at https://github.com/eclipse-theia/theia/issues/11683 if you'd like or any API that looks interesting.

If you want to have discussions throughout your implementation you can create a [discussion](https://github.com/eclipse-theia/theia/issues/11683) where I can respond without adding noise to the original issue.

**Comment by jbicker** [comment]
@b4s36t4 and @vince-fugnitto, if you don't mind I would assign myself to this one.

**Comment by JonasHelming** [comment]
@jbicker Do you have an update about this? It would be super great if you find the time to contribute to this!

**Comment by jbicker** [comment]
@JonasHelming  Not yet. Sorry! I will continue soon.

**Comment by JonasHelming** [comment]
Just a note: Maybe you want to stub the API first, so that it is already in place? We did the same for Notebook and the test API for now and it is rather low effort.

**Comment by jbicker** [comment]
I'll have to check again, but I think I've already done that. I've recently been stuck with the implementation of the functionality behind the API. So, I can split that up.

**Comment by JonasHelming** [comment]
That sounds great!

**Comment by jbicker** [comment]
@JonasHelming https://github.com/eclipse-theia/theia/pull/12031

**Comment by JonasHelming** [comment]
@jbicker Is there a chance the real impl makes it into the Jan release?

**Comment by jbicker** [comment]
@JonasHelming I think there is a chance. But I wouldn't promise.

**Comment by jbicker** [comment]
Btw. what is the release date?

**Comment by JonasHelming** [comment]
Jan 26th

**Comment by jbicker** [comment]
So far I implemented the functions to close tabs and tabgroups. Since I do not have time for further implementation this month @jonah-iden will take over that branch.
