### ISSUE TITLE
Toolbar items should be enabled/visible according to when-clause-contexts

### ISSUE THREAD

**Issue by ndoschek** [eclipse-theia/theia#11705]
### Feature Description:

The `TabBarToolbarItem` interface for items for the the main toolbar offers an optional `when` property, that is supposed to accept [when-clause-contexts](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts).
This can be set, but it has no impact on the toolbar item.
Also, editing the user's `toolbar.json` directly in the application does not allow to set such a clause:
![image](https://user-images.githubusercontent.com/47414588/192728591-789c86f7-91e9-4ac6-b2de-b70f961362e5.png)

I would like to see items to be enabled/visible only if the `when` clause returns `true` (e.g. only show item if the workbench has a valid workspace: `when: 'workbenchState != empty'`).

**Comment by colin-grant-work** [comment]
For the interested implementer, the points of reference are these:

https://github.com/eclipse-theia/theia/blob/22a5f7e98ec23c664bfa9916a0d7f81e727fa26a/packages/toolbar/src/browser/toolbar.tsx#L264-L297

https://github.com/eclipse-theia/theia/blob/22a5f7e98ec23c664bfa9916a0d7f81e727fa26a/packages/core/src/browser/shell/tab-bar-toolbar/tab-bar-toolbar.tsx#L107-L140

**Comment by ndoschek** [comment]
@colin-grant-work Thanks for your feedback!
I don't have a strong opinion, but looking at toolbars in other IDEs (VSCode, Eclipse RCP) items are mostly disabled (visible but inactive) if not relevant for the current context. So I'd suggest to go that way as well. WDYT?
