### ISSUE TITLE
`yarn download:plugins` fails with "Server returned code 500"

### ISSUE THREAD

**Issue by jgfoster** [eclipse-theia/theia#11747]
### Bug Description:

"Server returned code 500."

### Steps to Reproduce:

I'm following the instructions [here](https://theia-ide.org/docs/composing_applications) and `yarn download:plugins` fails as follows:

```text
#16 0.521 yarn run v1.22.19                                                                                                                                                                     
#16 0.585 $ theia download:plugins
#16 1.917 --- downloading plugins ---
#16 3.563 + eclipse-theia.builtin-extension-pack: downloaded successfully 
...
#16 68.08 + vscode.html-language-features@1.53.2: downloaded successfully 
#16 71.17 + ms-vscode.node-debug@1.44.28: downloaded successfully 
#16 71.17 --- collecting extension dependencies ---
#16 71.49 --- resolving 1 extension dependencies ---
#16 71.87 - ms-vscode.node-debug2: already downloaded - skipping
#16 71.87 Server returned code 500.
#16 71.87 Server returned code 500.
#16 71.87 Server returned code 500.
#16 71.87 Server returned code 500.
#16 71.87 Server returned code 500.
#16 71.87 Server returned code 500.
#16 71.87 Server returned code 500.
#16 71.87 Server returned code 500.
#16 71.87 Server returned code 500.
#16 71.87 Error: Errors downloading some plugins. To make these errors non fatal, re-run with --ignore-errors
#16 71.87     at downloadPlugins (/opt/theia/dev-packages/cli/lib/download-plugins.js:112:15)
#16 71.87     at async Object.handler (/opt/theia/dev-packages/cli/lib/theia.js:309:13)
#16 72.09 error Command failed with exit code 1.
#16 72.09 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional Information

This is based on the following `Dockerfile`:

```text
FROM ubuntu:22.04

# -----------------------------------------------------------------------------
# Prerequisites: https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites

# Install Node.js 16 (https://joshtronic.com/2021/05/09/how-to-install-nodejs-16-on-ubuntu-2004-lts/) 
RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

# Install Yarn (https://joshtronic.com/2021/05/09/how-to-install-nodejs-16-on-ubuntu-2004-lts/)
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo 'deb https://dl.yarnpkg.com/debian/ stable main' | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn

# Install additional tools and libraries
RUN apt-get install -y build-essential git libsecret-1-dev libx11-dev libxkbfile-dev pkg-config

# -----------------------------------------------------------------------------
# Install Theia
RUN git clone https://github.com/eclipse-theia/theia /opt/theia
WORKDIR /opt/theia
RUN yarn
RUN yarn download:plugins
RUN yarn browser build

EXPOSE 3000
```

**Comment by vince-fugnitto** [comment]
@jgfoster you already opened a duplicate issue https://github.com/eclipse-theia/theia/issues/11745 where a response was given of why it failed. There is nothing we can do from the framework’s point of view of the `open-vsx` service is down. If you do not care about the failure to download some builtins you can always run the download script with appropriate ignore flag.

**Comment by jgfoster** [comment]
@vince-fugnitto, Thank you for your reply. Unfortunately I'm sufficiently inexperienced that I didn't know that a 503 error in one part of the script is the same as a 500 error in another part of the script. I'm simply following the instructions provided and reporting errors. If the errors were more descriptive or pointed me in the proper direction, then perhaps I wouldn't need to ask for help. If the framework requires an unreliable external server, then perhaps there is something that could be improved with the framework. How will I be able to determine when things work again, or if anyone is working on the problem? The previous ("duplicate") issue was marked as fixed and I found that it got beyond the previous error and got a different error at a different place. I'm sorry that I didn't know that it was the same original issue.

**Comment by vince-fugnitto** [comment]
@jgfoster no problem, the `download:plugins` script is used to download plugins at the URL you provide. Given that you are likely using an [extension pack](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup) (an extension that lists other extensions by their `id(s)`) the `download:plugins` script will fetch compatible versions of these extensions in the [open-vsx](https://open-vsx.org/) registry. If the service is down due to outages or maintenance then you might encounter some problems like you've been seeing, a good place to look would be [open-vsx](https://open-vsx.org/) itself if such server errors occur like `500` or `503`.

> If the framework requires an unreliable external server, then perhaps there is something that could be improved with the framework.

The real fix would be to make [open-vsx](https://open-vsx.org/) aware of these issues and ensure that they have proper mechanisms to identify outages and have redundancy. Alternatives for yourself could be to:
- host your own private registry (which open-vsx allows)
- fetch extensions from another source given you can point to any URL

It all depends on your own product and needs.

> The previous ("duplicate") issue was marked as fixed and I found that it got beyond the previous error and got a different error at a different place. I'm sorry that I didn't know that it was the same original issue.

I closed the issue as the bug is not on the framework's end, and the server was already operational by the time I had commented.

- https://github.com/EclipseFdn/open-vsx.org/issues/1270
- https://github.com/EclipseFdn/open-vsx.org/issues/1274

**Comment by jgfoster** [comment]
@vince-fugnitto, 

> the URL you provide

I'm sorry, but I don't see that the `Dockerfile` I provided or the error messages I observed have any reference to `open-vsx`. Did I provide a URL in the `yarn download:plugins` command? Is there something else that I missed?

> a good place to look would be [open-vsx](https://open-vsx.org/) itself

I looked at the URL you provided but I don't see any "uptime" or "status" dashboard. Where should I look to find an explanation for these sort of errors?

Closing the issue is certainly fine, particularly if the provided instructions now work. Thanks!

**Comment by vince-fugnitto** [comment]
@jgfoster 
>I'm sorry, but I don't see that the Dockerfile I provided or the error messages I observed have any reference to open-vsx. Did I provide a URL in the yarn download:plugins command? Is there something else that I missed?

It wouldn't be in your dockerfile but your `package.json` which your dockerfile ultimately builds and starts.
It is likely in your `package.json` you reference plugins to be included by default (builtins) by referencing them and pointing their download URLs to `open-vsx`.

>  looked at the URL you provided but I don't see any "uptime" or "status" dashboard. 

I'm not sure there is a status page at the moment for the public instance of `open-vsx` managed by the Eclipse Foundation but I agree it would be useful. We can certainly inform them to report statuses at https://www.eclipsestatus.io/ and honour SLAs as documented in https://wiki.eclipse.org/IT_SLA.

cc @JonasHelming

**Comment by jgfoster** [comment]
@vince-fugnitto, Thanks very much for that explanation. As it happens I had removed the `package.json` file in an attempt to get around other errors, so there must be some sort of default plugins source. Anyway, I'll close this. Thanks!
