### ISSUE TITLE
`View: Show Previous Tab` on first tab no longer cycle to last tab

### ISSUE THREAD

**Issue by perrinjerome** [eclipse-theia/theia#11746]
### Steps to Reproduce:

1. Add two editors by using `File` -> `New File` twice, creating files named A and B
![image](https://user-images.githubusercontent.com/521510/194709963-cd2f6dd6-495c-4b31-841e-f394e6a81c3c.png)
3. focus editor A and use command `View: Show Previous Tab` 
![image](https://user-images.githubusercontent.com/521510/194709981-67769bb1-bcd4-4ac8-a272-25449808d08d.png)
 
Expected behavior: editor B gets focus

Actual behavior: focus stays on editor A

This behavior changed between Theia 1.22.0 and 1.23.0 . This seems to be a regression introduced by https://github.com/eclipse-theia/theia/commit/b00dc8378196e1c6615c66630c7962dfc92b8ddb , reverting this change restores the behavior.

/cc @alxflam @colin-grant-work

**Comment by Pranav2612000** [comment]
Hey, I'll like to work on this issue :) Is it a new contributor friendly one?
