### ISSUE TITLE
[vscode] Support optional property isTransient in TerminalOptions and ExtensionTerminalOptions

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#11777]
The type [TerminalOptions](https://code.visualstudio.com/api/references/vscode-api#TerminalOptions) and [ExtensionTerminalOptions](https://code.visualstudio.com/api/references/vscode-api#ExtensionTerminalOptions) miss the optional property:

- [ ] isTransient: Opt-out of the default terminal persistence on restart and reload. This will only take effect when `terminal.integrated.enablePersistentSessions` is enabled.

**Comment by lucas-koehler** [comment]
I'm having a look at this.
