### ISSUE TITLE
[vscode] Stub vscode 'NoteBook' API

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#11786]
As announced in #8395, vscode ships a [Notebook](https://code.visualstudio.com/api/extension-guides/notebook) API.

It would make sense to have the possibility to load and start plugins which depend on the 'Notebook' API. Even if the functionality relying on Notebook API would not work, the other parts of the extension would still work.

**Comment by rschnekenbu** [comment]
@vince-fugnitto , indeed, sorry for the noise. 
Can you assign me the issue #11100, as it contains more history? Then I can close this one.

**Comment by vince-fugnitto** [comment]
@rschnekenbu no problem, I kept this one open since you're not an author on the other one and I can't seem to assign you directly to it.
