### ISSUE TITLE
[Extension/Vue.volar] Unexpected token "."

### ISSUE THREAD

**Issue by FossPrime** [eclipse-theia/theia#11797]
### Bug Description:

After installing volar v1.0.9 for Vue support, I get the following error:

![Screenshot from 2022-10-24 18-30-39](https://user-images.githubusercontent.com/876076/197649202-35422408-65d1-4448-a99d-5dea8bb60d85.png)

### Steps to Reproduce:

I installed it by
1. Downloading the vscx from https://marketplace.visualstudio.com/items?itemName=Vue.volar
2. Running `sudo unzip Vue.volar-1.0.9@linux-x64.vsix -d /google/devshell/editor/theia/plugins/Vue.volar`
3. Restarting theia with:

```
sudo apt install pslist
ps ax | grep runuser | grep "theia start"
sudo rkill PID_OF_GREP_OUTPUT
```

### Additional Information

- Operating System: Debian
- Theia Version: Cloud Shell Editor v1.25.0

**Comment by msujew** [comment]
Hey @FossPrime,

can you tell which version of node.js is running in the background? Such errors usually indicate that the extension code is written in ES2020 (or similar) and therefore expects node 14, but was parsed using node 12. Older versions of Theia recommend to use node 12.

Note that I just tried installing the extension as well, which doesn't lead to the parse error on node 14. However, on startup, the extension still runs into an error, as it requires vscode API version >= 1.67, which isn't satisfied by Theia. The latest compatible version seems to be `0.34.11`.

**Comment by msujew** [comment]
I'll close this issue, as this likely doesn't occur on newer versions of Theia anymore (we no longer support old versions of Node.js).
