### ISSUE TITLE
No pathspec error when using unstage all

### ISSUE THREAD

**Issue by Hanksha** [eclipse-theia/theia#11801]
### Bug Description:

Whenever I use "Unstage All" in the Source Control view, via button (-) or the tab bar dropdown menu, I get this error: "fatal: No pathspec was given. Which files should I remove?"

![bug](https://user-images.githubusercontent.com/6960133/198043788-cc172e2b-fcc6-48f2-a05b-b6a21ef16dba.gif)

### Steps to Reproduce:

1. Create a directory
2. Run git init in that directory
3. Create a sample test.txt file
4. Open Theia with that directory as workspace
5. Go to Source Control view
6. Use the Unstage All via the button or tab bar dropdown menu

Note that it works fine to unstage a selected file or multiple selected files, it just does that with the unstage all command.

### Additional Information

- Operating System: macOS and Windows
- Theia Version: 1.30

**Comment by vince-fugnitto** [comment]
@Hanksha I believe the same scenario will produce errors in vscode as well:

![image](https://user-images.githubusercontent.com/40359487/198048349-c7c49578-0ced-47a7-9e48-7e702df64208.png)

**Comment by vince-fugnitto** [comment]
@Hanksha would you like to contribute a fix?
I believe adding `{ reset: 'index' }` works:

https://github.com/eclipse-theia/theia/blob/7e753f459e46a6c25695c9f80647d028c9d44af6/packages/git/src/browser/git-scm-provider.ts#L322

```diff
async unstageAll(): Promise<void> {
    try {
        const { repository, stagedChanges } = this;
        const uris = stagedChanges.map(c => c.uri);
-        await this.git.unstage(repository, uris);
+        await this.git.unstage(repository, uris, { reset: 'index' });
    } catch (error) {
        this.gitErrorHandler.handleError(error);
    }
}
```

**Comment by Hanksha** [comment]
@vince-fugnitto Sure I will

**Comment by Hanksha** [comment]
@vince-fugnitto I just saw you did a PR, I was about to create mine. I added a unit test for it as well, do you want me to send it to you so you can add it to your PR?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I just saw you did a PR, I was about to create mine. I added a unit test for it as well, do you want me to send it to you so you can add it to your PR?

@Hanksha sorry I just didn't know when you'd be done and I wanted to get it in for the release, you can open yours and I'll review :)

**Comment by Hanksha** [comment]
@vince-fugnitto Alright, on it.
