### ISSUE TITLE
vscode: update typings for `activeSignatureHelp`

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11828]
#### Feature Description:

The typings for `SignatureHelpContext.activeSignatureHelp` should be updated to align with the VS Code API:

https://github.com/eclipse-theia/theia/blob/1cdfae21899f1efacb2a8caec7f2147129518c8d/packages/plugin/src/theia.d.ts#L7267

The changes should be:

```diff
- readonly activeSignatureHelp?: SignatureHelp; 
+ readonly activeSignatureHelp: SignatureHelp | undefined;
```

**Comment by marcdumais-work** [comment]
Looking at the [vscode commit](https://github.com/microsoft/vscode/commit/91132cab87b6b057cab0e0fdaf6548bf84df2b45#diff-f127724f8c5dbf0c8371ad0a100f8a9bc0a398b6b8ec29aa6cd7f265bd01a096) that changed `activeSignatureHelp` I noticed that several other properties were similarly changed, that are not picked-up by our `vscode-theia-comparator` as being partially supported. 

I guess it might be worthwhile to also align these extra properties?

**Comment by ratika-12** [comment]
Hey @vince-fugnitto I am new here and want to work on this issue. please assign me :-)
