### ISSUE TITLE
Astro highlight for thea IDE

### ISSUE THREAD

**Issue by golam71** [eclipse-theia/theia#11840]
astro is a javascript framework 
please add support for it

**Comment by msujew** [comment]
With Theia supporting the vscode extension API, we don't add support for any particular language by ourselves. It seems like the official Astro extension is available on [Open-VSX](https://open-vsx.org/) and can be installed in Theia:

![image](https://user-images.githubusercontent.com/4377073/200174986-77e8fb12-6f19-4d40-a6d0-52caf3e89256.png)

**Comment by golam71** [comment]
thanx
