### ISSUE TITLE
Open() method from vscode.Pseudoterminal not called inside Task CustomExecution

### ISSUE THREAD

**Issue by arekzaluski** [eclipse-theia/theia#11858]
### Bug Description:

There is a difference in behaviour between extension that runs in VSCode and Theia (tested in Theia 1.31.1). `Open` function from `vscode.PseudoTerminal` is called only in VSCode and not in Theia (https://github.com/arekzaluski/vscode-task-extension/blob/main/src/hello-task-terminal.ts#L12).

### Steps to Reproduce:

VSCode:

1. Run https://github.com/arekzaluski/vscode-task-extension example extension in VSCode
2. Execute `Hello World` command from command pallette (ctrl+shift+P)
3. A new terminal will be opened and following message will be displayed: `Hello from Task terminal!`

![Screenshot 2022-11-10 at 12 02 35](https://user-images.githubusercontent.com/13417215/201088970-777603d2-122e-4e18-af32-f404fa380008.png)

Theia:
1. Run latest version of Theia in browser (tested on Theia 1.31.1)
2. Add https://github.com/arekzaluski/vscode-task-extension as a new plugin (vsix can be found here: https://github.com/arekzaluski/vscode-task-extension/releases/tag/0.0.1)
3. Execute `Hello World` command from command pallette (ctrl+shift+P)
4. A new terminal will be opened but `Hello from Task terminal!` will not be visible there

![Screenshot 2022-11-10 at 12 02 11](https://user-images.githubusercontent.com/13417215/201089984-1ad30686-5d9d-466a-b5f3-fa3acca58479.png)

### Additional Information

- Operating System: All (tested on macOS and Windows). Running inside browser environment
- Theia Version: 1.31.1

**Comment by thegecko** [comment]
It's likely this is due to my change here:

https://github.com/eclipse-theia/theia/pull/10780

I think this was masking a wider issue which has since been fixed, but please make sure any fix works in the frontend and backend host.
