### ISSUE TITLE
[debug]: Cannot stop debug session of `vscode-mock-debug`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#11879]
### Bug Description:

It's impossible to terminate the debug session in Theia. It works very well from Code.

### Steps to Reproduce:

1. Start the [Microsoft/vscode-mock-debug](https://github.com/Microsoft/vscode-mock-debug) debugger in Theia.
2. Stop the debug session.
3. It cannot terminate and will timeout after 5 sec

```
2022-11-18T11:59:05.246Z root ERROR Error on disconnect
```

```
{
    "type": "response",
    "seq": 0,
    "request_seq": 12,
    "success": false,
    "command": "disconnect",
    "message": "Request #12: disconnect timed out"
}
```

----
If you do not want to build the `vscode-mock-debug` extension on your own, you can use the VS Code extension mock debugger from https://github.com/eclipse-theia/theia/issues/11871

### Additional Information

- Operating System: macOS, 12.5.1
- Theia Version: fe8e4c1

**Comment by kittaakos** [comment]
I will handle this.

**Comment by kittaakos** [comment]
After https://github.com/microsoft/vscode/pull/166137, I can confirm Theia's behavior is the same as Code.

I was positive the debug session's fast termination was due to no `await` in Code's implementation, then https://github.com/microsoft/vscode/pull/166137 popped up. I debugged into the non-minified version of the `mock-debug` implementation, and I can confirm no `disconnect` response was sent back to the client. So a timeout is expected. See [here](https://github.com/microsoft/vscode-mock-debug/blob/95d0052629b1cc65a0647f927cc1b13f4407b7c8/src/mockDebug.ts#L240-L242). I downloaded latest Code Insider, and now I can see the 2-sec delay after terminating the debug session. The differences are that Theia uses 5000ms while [Code 2000ms](https://github.com/microsoft/vscode/blob/0131be02f4aa1e455ab9908002b6b482b4449acc/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L572). Code [ignores errors](https://github.com/microsoft/vscode/blob/0131be02f4aa1e455ab9908002b6b482b4449acc/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L574), Theia [does not](https://github.com/eclipse-theia/theia/blob/4d3d0c2e208caa6a0f3f7f9eab110001dcd10c0e/packages/debug/src/browser/debug-session.tsx#L352). 

Theia should adjust the UX, though. Shall Theia ignore the error and timeout after 2000ms (or make the timeout easily configurable from downstream code)?

We can close the issue. It's up to core committers. Thanks!

**Comment by msujew** [comment]
> Code [ignores errors](https://github.com/microsoft/vscode/blob/0131be02f4aa1e455ab9908002b6b482b4449acc/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L574), Theia [does not](https://github.com/eclipse-theia/theia/blob/4d3d0c2e208caa6a0f3f7f9eab110001dcd10c0e/packages/debug/src/browser/debug-session.tsx#L352).

Note that Theia also "ignores" the error. I wouldn't say that logging the error to console really counts as error handling. We don't show anything to the user or anything similar.

**Comment by kittaakos** [comment]
> Note that Theia also "ignores" the error.

Yes, thanks for the correction. What I meant is logging the error is misleading. No malfunction is happening when terminating the debug session with `'disconnect'`.

**Comment by kittaakos** [comment]
Let's leave this open. There are other places we could improve Theia. For example, when a request is timed out, the error object used for rejection does not have an error message. However, DAP has a spacial `ErrorResponse`, Theia could benefit from it:

```
	/** On error (whenever `success` is false), the body can provide more details. */
	interface ErrorResponse extends Response {
		body: {
			/** A structured error message. */
			error?: Message;
		};
	}
```

Current code:

https://github.com/eclipse-theia/theia/blob/b2c52e298361a7c1bd0fa2f10b9ca1dc5fb16e40/packages/debug/src/browser/debug-session-connection.ts#L224-L232

Also, it should be easier for downstream to specify a timeout for `terminate` and `disconnect`. I would also like to increase the visibility of the `isStopped` to improve the APIs for downstream:

https://github.com/eclipse-theia/theia/blob/b2c52e298361a7c1bd0fa2f10b9ca1dc5fb16e40/packages/debug/src/browser/debug-session.tsx#L75
