### ISSUE TITLE
[core] Consider getting the `schemastore.azurewebsites.net/api/json/catalog.json` at build time

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#11881]
### Feature Description:

Whenever I start Theia from the sources (electron, browser) or TheiaBluePrint (1.31.1 (1.31.1.85)), getting the default preference schema fails. The fetched JSON size has increased during the years, and getting the schema never completes in 500ms.

From the sources:
```
logger-protocol.ts:113 2022-11-18T13:42:37.774Z root ERROR DefaultJsonSchemaContribution.registerSchemas is taking more than 500.0 ms, new schemas are ignored.
```

From the bundled electron app:
```
logger-protocol.ts:113 2022-11-18T13:48:50.330Z root ERROR h.registerSchemas is taking more than 500.0 ms, new schemas are ignored.
```

Either increase the timeout or get the schema at build time. The current implementation makes no sense. Note that getting the schema at build time has one drawback, the most recent schema won't be fetched on app load, so it could be outdated. In one of the downstream projects, we get the schema at build time, which works well.

**Comment by umar-shabbir** [comment]
I am getting the same error in Theia 1.44.0. 
Is there any update on this issue?

**Comment by msujew** [comment]
@umar-shabbir A PR fixing this issue would probably link it. As far as I know, there wasn't anyone interested in fixing this issue yet.

**Comment by tsmaeder** [comment]
The implementation of this feature is a bit odd: it seems the JSON schemas is only ever used to pass it to the plugin manager in the plugin host at initialization time. So we're fetching the schema catalog each time we open a new Theia Window. Fetching it once from the back end would be sufficient, IMO. While the fetching is async, we need to wait for it to finish before we can start up the plugin host, so this might be relevant for start time.
Also, there seems to be no prioritization of schemas if they apply to the same file. IMO, the default schemas from the catalog should have lesser priority vs. schemas contributed in code.
