### ISSUE TITLE
Use "forEach" instead of "map" in search-in-workspace-result-tree-widget#updateRightResults

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#11898]
**Blocked for Hackathon**

The "map" function is used to iterate over an array, but its return value is not used. In this case, it is faster and also less confusing to use "forEach".

See https://github.com/eclipse-theia/theia/blob/700c25ca2cbbae5e10dd240a33e447b57d9af0c5/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L845

Operating System: All
Theia Version: Latest

Steps to test the behavior:

1. Open an example file with the same search String appearing multiple times in one row, e.g. "test foobar test"
2. Use the Theia search view to search for the test String occurring in the opened file
3. Enter a replace value
4. In the search results, select to replace the first occurrence of the search String only
5. Check that the second hit is correctly highlighted in the editor after the replacement
6. Replace the second hit in the same line

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/12071.
