### ISSUE TITLE
Extension Activation: a.window.registerTerminalProfileProvider is not a function

### ISSUE THREAD

**Issue by giflw** [eclipse-theia/theia#11894]
### Bug Description:

```
Activating extension 'JavaScript Debugger' failed: a.window.registerTerminalProfileProvider is not a function
```

It's Theia 1.3.1, builded using Blueprint as reference.
The extensions is ms-vscode.js-debug v1.72.1.

I'm trying to build an IDE to me,forked from Theia Blueprint, calling it Eos Thesis IDE (https://github.com/giflw/eos-thesis-ide)

### Steps to Reproduce:

1. Add ms-vscode.js-debug v1.72.1 to theiaPlugins
2. Build Theia (blueprint) (https://github.com/giflw/eos-thesis-ide)
3. Open IDE. The error appears as notification

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.31.1

**Comment by vince-fugnitto** [comment]
@giflw thank you for reporting the issue, we are tracking it as part of https://github.com/eclipse-theia/theia/issues/11503 (epic https://github.com/eclipse-theia/theia/issues/11520).

**Comment by AmeyaLokre** [comment]
Hello @vince-fugnitto, has this issue been resolved ?
We faced the same error prompt when using JavScript Debugger extension on Theia v1.27.0.

**Comment by msujew** [comment]
@AmeyaLokre The respective API has been supported as of version `1.34.0` of Theia.
