### ISSUE TITLE
Use "forEach" instead of "map" in search-in-workspace-result-tree-widget#updateCurrentEditorDecorations

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#11897]
**Blocked for Hackathon**

The "map" function is used to iterate over an array, but its return value is not used. In this case, it is faster and also less confusing to use "forEach".

See https://github.com/eclipse-theia/theia/blob/700c25ca2cbbae5e10dd240a33e447b57d9af0c5/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L633

- Operating System: All
- Theia Version: Latest

Steps to test the behavior:

1. Open two examples file with occurrences of the same test String
2. Search for this String in the Theia search view
3. Check that the search String is highlighted in both editors

There should be no functional change when replacing map with forEach

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/12071.
