### ISSUE TITLE
Use "forEach" instead of "map" in search-in-workspace-result-tree-widget#createEditorDecorations

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#11909]
**Blocked for Hackathon**

The "map" function is used to iterate over an array, but its return value is not used. In this case, it is faster and also les confusing to use "forEach".

see: https://github.com/eclipse-theia/theia/blob/700c25ca2cbbae5e10dd240a33e447b57d9af0c5/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L1125

Operating System: All
Theia Version: Latest
Steps to test the behavior:
1. Open an example file
2. Use the Theia search view to search for a String occurring in the opened file
3. Check that all instances of the search String are marked correctly

There should be no functional change when replacing map with forEach

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/12071.
