### ISSUE TITLE
Theia Blueprint does not start on macOS. Maybe an IPv6 issue?

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#11930]
### Bug Description:

We have received reports of non-functional Theia electron apps from multiple users:
 - https://github.com/arduino/arduino-ide/issues/1708
 - https://github.com/arduino/arduino-ide/issues/1527

Our users were friendly to help us, and [they could reproduce the bug with the TheiaBlueprint](https://github.com/arduino/arduino-ide/issues/1708#issuecomment-1330436208) application.

Relevant stack traces:

```
2022-11-25 18:27:24 root ERROR Failed to start the backend application:
2022-11-25 18:27:24 root ERROR Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
2022-11-25 18:27:24 root ERROR Uncaught Exception: 
2022-11-25 18:27:24 root ERROR Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
```

```
root ERROR Failed to start the backend application: root ERROR Error: listen EADDRNOTAVAIL: address not available 127.0.0.1 at Server.setupListenHandle [as _listen2] (node:net:1298:21) at listenInCluster (node:net:1363:12) at GetAddrInfoReqWrap.doListen [as callback] (node:net:1501:7) at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8) root ERROR Uncaught Exception: root ERROR Error: listen EADDRNOTAVAIL: address not available 127.0.0.1 at Server.setupListenHandle [as _listen2] (node:net:1298:21) at listenInCluster (node:net:1363:12) at GetAddrInfoReqWrap.doListen [as callback] (node:net:1501:7) at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8)
```

We do not yet know what's causing the problem, but we managed to figure out that [disabling the IPv6](https://github.com/arduino/arduino-ide/issues/1428#issuecomment-1330400076) support on macOS fixes the issue:

```
sudo networksetup -setv6off Wi-Fi
```

### Steps to Reproduce:

1. Download and start the latest Theia Blueprint app,
2. Sometimes, it does not start
3.

### Additional Information

- Operating System: macOS 11+ and 12+
- Theia Version: TheiaBlueprint, Version 1.31.1 (1.31.1.86)

----

I could not reproduce the bug on my macOS env. I will investigate the issue further and update this issue. If anybody has the seem issue, please let us know.

**Comment by marcdumais-work** [comment]
@kittaakos I have no specific reason to believe it will fix the issue, but we have a new macOS package available for Blueprint, based on Theia 1.32.0:

https://download.eclipse.org/theia/latest/macos/

**Comment by Zhek1ch** [comment]
Newest package doesn't fix the issue.

https://user-images.githubusercontent.com/108014500/204737572-fd2d729a-73ab-4263-8f07-0d6082af4288.mp4

**Comment by vince-fugnitto** [comment]
The issue at first glance looks similar to https://github.com/eclipse-theia/theia/issues/11578, is there an issue with `localhost` not being properly binded, or the loopback address somehow being messed up?

**Comment by kittaakos** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/11578.
