### ISSUE TITLE
getting-started: the `getting started` label is not localized

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11933]
#### Bug Description:

The "Getting Started" label is not being localized properly despite it being a default localization.

### Steps to Reproduce:

1. start the application
2. install a language pack through `configure display language`
3. open the "getting started" view
4. notice it is not properly localized

cc @msujew I could not understand why it was not being localized but I can spend more time debugging tomorrow.

**Comment by msujew** [comment]
@vince-fugnitto I cannot reproduce this on `master` with the German language pack:

![image](https://user-images.githubusercontent.com/4377073/204645272-956bf2f0-41ee-481c-8f2b-0dbac8c08a61.png)

**Comment by vince-fugnitto** [comment]
I re-verified and the bug no longer exists :+1:
