### ISSUE TITLE
Theia ignoring THEIA_PLUGINS environment variable

### ISSUE THREAD

**Issue by hyddel** [eclipse-theia/theia#11934]
### Bug Description:
Let's say THEIA_PLUGINS environment variable points to a directory that has test-1.2.2.vsix. While theia is starting, I have passed --plugins flag which points to a directory that has a different version of the test plugin, say test-1.3.0.vsix. 

Once theia is loaded, it shows only test-1.3.0 but not test-1.2.2 plugin. 

### Additional Information

- Operating System: macOS Monterey
- Theia Version: 1.19.0

**Comment by vince-fugnitto** [comment]
@hyddel thank you for reporting the issue, are your two plugins the same plugin but at different versions? I confirmed on master that plugins referenced by `THEIA_PLUGINS` and those from the cli are both correctly loaded into the application.

**Comment by hyddel** [comment]
@vince-fugnitto yes, two same plugins with different versions. 

And what's the difference between THEIA_DEFAULT_PLUGINS and THEIA_PLUGINS environment variable?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto yes, two same plugins with different versions.

@hyddel it should not be possible to load two plugins at different versions which is why you might only see one plugin loaded.

**Comment by hyddel** [comment]
I see. 

Does it give preference to the plugin pointed by the `--plugins` flag which is passed as a CLI option while starting theia? or 
is it random? 

On my local testing, I observed that it prefers the `--plugins` flag.

**Comment by colin-grant-work** [comment]
If two options are found at startup, preference is given to the [higher version number](https://github.com/eclipse-theia/theia/blob/2ec7d87d85cdd863b135a54b92c95b3eb0ee4415/packages/plugin-ext/src/main/node/plugin-deployer-impl.ts#L233); once plugins have been deployed, preference is given to [whatever has already been deployed](https://github.com/eclipse-theia/theia/blob/2ec7d87d85cdd863b135a54b92c95b3eb0ee4415/packages/plugin-ext/src/hosted/node/hosted-plugin-deployer-handler.ts#L169-L172).

**Comment by hyddel** [comment]
that makes sense, thank you.
