### ISSUE TITLE
search-in-workspace: update `cursor` for results

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11968]
#### Bug Description:

The **search-in-workspace** widget does not seem to use a `cursor: pointer` for tree-nodes in the results which can lead to confusion. The change should make sure that a proper cursor is being used.

https://user-images.githubusercontent.com/40359487/206224358-342aaebd-0f18-4106-b844-bc6418bfd6a9.mp4

#### Steps to Reproduce:

1. start the application
2. open the search widget
3. search for a term and confirm that results are displayed
4. hover over results and notice that the cursor is incorrect (should be a pointer)

**Comment by vince-fugnitto** [comment]
> And when you say "pointer", you mean a pointing hand, @vince-fugnitto ?

Right, the `pointer` is the actual keyword value for the pointing hand (https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#values):

![image](https://user-images.githubusercontent.com/40359487/207324344-04e168aa-5546-4f45-8c92-c5fc2c9e26e1.png)

**Comment by tsmaeder** [comment]
Seems like the "noselect" class is blocking the right css from being applied. See https://github.com/eclipse-theia/theia/pull/10371.

**Comment by tsmaeder** [comment]
Add the following to `tree.css` fixes the problem:
```
.theia-TreeNode .noselect:hover {
    cursor: pointer;
}
```

**Comment by JonasHelming** [comment]
Sathya is looking at this
