### ISSUE TITLE
On editor tab ' (deleted)' suffix is not localized

### ISSUE THREAD

**Issue by xcariba** [eclipse-theia/theia#11971]
### Bug Description:

If you create and open file in text editor and then delete file it will show up with (deleted) suffix. This suffix is not localized.

### Steps to Reproduce:

1. Open Theia
2. Install any language pack
3. Reload page (now interface should be in chosen language)
4. Create file launch.json
5. Open it in text editor
6. Remove file
7. Tab will show `launch.json (deleted)` instead of `launch.json (<localized value>)`

### Additional Information

Not localized value is located here [oh, here you are!](https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/browser/filesystem-frontend-contribution.ts#L270)

![image](https://user-images.githubusercontent.com/7170514/206481780-f1f11f6e-76bf-4a5d-a219-fa47b6964f8a.png)

**Comment by msujew** [comment]
Hey @xcariba, thanks for reporting. Are you interested in contributing a fix for that?

**Comment by xcariba** [comment]
@msujew yes I am =)
