### ISSUE TITLE
plugin-ext: typos in `terminal-main.ts`

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11989]
#### Bug Description:

There are typos present in `terminal-main.ts` where the function parameter name does not match the type:

https://github.com/eclipse-theia/theia/blob/ac7a9ff51afa71d26673a7a8f7968c8e9a3f51ff/packages/plugin-ext/src/main/browser/terminal-main.ts#L263-L269

The parameter `cancelationToken` should be updated to `cancellationToken`:

```patch
-async provideLinks(line: string, terminal: TerminalWidget, cancelationToken ?: CancellationToken | undefined): Promise < TerminalLink[] > {
+async provideLinks(line: string, terminal: TerminalWidget, cancellationToken?: CancellationToken | undefined): Promise<TerminalLink[]> {
    if (this.terminalLinkProviders.length < 1) {
        return [];
    }
-   const links = await this.extProxy.$provideTerminalLinks(line, terminal.id, cancelationToken ?? CancellationToken.None);
+   const links = await this.extProxy.$provideTerminalLinks(line, terminal.id, cancellationToken ?? CancellationToken.None);
    return links.map(link => ({ ...link, handle: () => this.extProxy.$handleTerminalLink(link) }));
 }
```

#### Steps to Confirm

1. perform the changes
2. confirm that the application successfully builds

**Comment by JonasHelming** [comment]
Rajesh is looking at this
