### ISSUE TITLE
dialog: `ConfirmDialog` should respect line-breaks for `msg`

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#11985]
#### Feature Description:

The `ConfirmDialog` does not currently respect line breaks for `msg` content.

Sample test code:
```ts
const dialog = new ConfirmDialog({
    title: 'Sample Dialog',
    msg: 'A\r\nB\r\nC\r\n'
});
return dialog.open();
```
You can add the code [here](https://github.com/eclipse-theia/theia/blob/master/examples/api-samples/src/browser/menu/sample-menu-contribution.ts#L58), rebuild the example application and trigger the menu using `Sample Command` like so:
![image](https://user-images.githubusercontent.com/25749063/207399170-518810b1-9c4f-4c55-8288-30dd075f79c0.png)

Will produce a dialog of:

![image](https://user-images.githubusercontent.com/40359487/207383409-caa8eba3-7f58-4bd1-a89e-cc20cc3732ae.png)

Instead of:

![image](https://user-images.githubusercontent.com/40359487/207383568-369bf85b-870a-40c0-8a1f-ae3a0d00229b.png)

The fix is to include the following CSS to respect the content passed as a `msg` ([dialogContent](https://github.com/eclipse-theia/theia/blob/ac7a9ff51afa71d26673a7a8f7968c8e9a3f51ff/packages/core/src/browser/style/dialog.css#L60-L68)):

```patch
.p-Widget.dialogOverlay .dialogContent {
    display: flex;
    flex-grow: 2;
    flex-direction: column;
    justify-content: space-around;
    align-items: stretch;
    position: relative;
    padding: calc(var(--theia-ui-padding)*2);
+   white-space: pre;
}
```

**Comment by jonah-iden** [comment]
Hi, as a new contributor would it be ok for me to work on this ticket even though it has the hackathon label or should i rather look for a different one?

**Comment by vince-fugnitto** [comment]
> Hi, as a new contributor would it be ok for me to work on this ticket even though it has the hackathon label or should i rather look for a different one?

@jonah-iden please go ahead :)
