### ISSUE TITLE
Potential filewatcher memory leak

### ISSUE THREAD

**Issue by tortmayr** [eclipse-theia/theia#12001]
### Bug Description:
The memory consumption of a Theia application steadily grows over time even if the application is in idle state.
We first discovered this issue with a deployed Theia-blueprint instance. After opening the workspace we kept the application in idle state for ~10 hours (apart from occasionally executing "top" in the terminal).
Over this timeperiod the memory consumption linearly increased from 0.18 Gib t o 0.72 Gib:

![demo](https://user-images.githubusercontent.com/2311075/208076332-46b67657-e3fb-4a62-9fdf-c19a7662499f.gif)

The issue can also be reproduced with the Theia example application.
After further investigating this it turns out that the culprit is the Theia filewatcher process. All of the memory overhead is allocated by this process.

It has to be tested whether the issue also occurs if the file watcher is not running in a child process (--no-cluster).

### Steps to Reproduce:

1. Start the browser example application via terminal (or explicitly set the --no-cluster option)
2. Note down the memory consumption of the Theia processes with special focus to the file watcher process.
   (On linux i did this with `top -bc |grep nsfwOptions` )
3. Let the application idling but don't close the browser
4. After some time measure the memory consumption again. Should have increased slowly but steadily.

### Additional Information

- Operating System: Linux
- Theia Version: 1.32.0

**Comment by tsmaeder** [comment]
There is an obvious problem visible in a heap dump:

The method `NsfwWatcher.orCancel()` is called endlessly from the while loop in `NsfwWatcher.start`. This adds a PromiseReaction object each time, leading to constant heap growth. Removing the `race` fixes the heap growth problem.

However, the native memory consumption still continues to grow, while the javascript heap peaks at 10.3 mb for my test case.

**Comment by tsmaeder** [comment]
The endless loop when starting the file watcher stems from our preference providers infrastructure: even if a preference file does not exist (and never will, probably), we still start a watcher for e.g. `.theia/tasks.jsons`. The `stat` will always fail and be retried half a second later.

**Comment by tsmaeder** [comment]
Hmh....upon further observation of the watcher process, it looks like the native memory consumption eventually settles.
