### ISSUE TITLE
Preferences Schema should ignore preferences that cannot be dendrified

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#12004]
### Bug Description:

For use in plugins and the editor, preferences need to be able to be properly dendrified, i.e. transformed into an object tree where keys with `.` are transformed into multiple objects:

```json
{
  "a.b": true,
  "a.c": false
}
```
Becomes
```javascript
{
  a: {
    b: true,
    c: false,
  }
}
```
As a consequence, it must not be permitted that any preference key be an extension of another preference key with a value:

```json
{
  "a": "already has a value!"
  "a.b": "now I can't be a key of object a!"
}
```

Internally, VSCode is careful to ensure that that doesn't happen, but Theia is not as strict, so problems can occur if plugins don't play by the rules. See [here](https://github.com/xaverh/vscode-clang-format/issues/128#issuecomment-1355153791), for example.

### Steps to Reproduce:

1. Install `clang-format`
2. Start the application.
3. See an error `TypeError: Cannot create property 'windows' on string 'clang-format'`

### Additional Information

- Operating System: RHEL7, Electron
- Theia Version: 1.28

**Comment by colin-grant-work** [comment]
It shouldn't be possible to get the error just by writing something bad in your `settings.json` because we ignore anything in the `settings.json` that isn't part of the schema - you need a bad schema to get the error. `clang-format` has written their preference schema so that there exist (they think) these keys:
```
clang-format.executable
clang-format.executable.windows
clang-format.executable.osx
clang-format.executable.linux`
```
But that can't be dendrified. VSCode recognizes that `clang-format.executable` has to be a leaf because it has type `string`, so it ignores the rest. We currently don't ignore the rest, so when we try to dendrify the structure, we try to say the equivalent of `'clang-format'.osx = 'clang-format'`, and an error gets thrown.

**Comment by tsmaeder** [comment]
Your wish is my command, @dhuebner
