### ISSUE TITLE
[vscode] Support LogOutputChannel

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12017]
see https://code.visualstudio.com/api/references/vscode-api#LogOutputChannel
since vscode 1.74

This requires also 
- support for [LogLevel](https://code.visualstudio.com/api/references/vscode-api#LogLevel) 
- support in [namespace/env](https://code.visualstudio.com/api/references/vscode-api#env): loglevel & onDidChangeLogLevel

**Comment by ndoschek** [comment]
@JonasHelming @rschnekenbu thanks!
