### ISSUE TITLE
[vscode] support WorkspaceEditMetadata

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12018]
see [WorkspaceEditMetadata](https://code.visualstudio.com/api/references/vscode-api#WorkspaceEditMetadata)
since vscode 1.73

This API is then used at least in function applyEdit as optional parameter in namespace [workspace](https://code.visualstudio.com/api/references/vscode-api#workspace).

**Comment by jonah-iden** [comment]
Hi, i would work on this on. Could be that i already implemented some of it in the SnippetTextEdit task
