### ISSUE TITLE
[vscode] Support DebugSessionOptions boolean options for suppression 

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12015]
see https://code.visualstudio.com/api/references/vscode-api#DebugSessionOptions

4 new options since 1.73:

- suppressDebugStatusbar?: boolean
_When true, the window statusbar color will not be changed for this session._

- suppressDebugToolbar?: boolean
_When true, the debug toolbar will not be shown for this session._

- suppressDebugView?: boolean
_When true, the debug viewlet will not be automatically revealed for this session._

- suppressSaveBeforeStart?: boolean
_When true, a save will not be triggered for open editors when starting a debug session, regardless of the value of the debug.saveBeforeStart setting._

**Comment by rschnekenbu** [comment]
Can you please assign this task to @sgraband?

**Comment by sgraband** [comment]
Sure
