### ISSUE TITLE
[vscode] Support CodeActionKind RefactorMove kind

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12021]
see [CodeActionKind](https://code.visualstudio.com/api/references/vscode-api#CodeActionKind) 
since vscode 1.72

RefactoreMove is missing.

**Comment by jonah-iden** [comment]
Hi, im trying to get into contributing to theias vscode integration and this seems like a good first task. So i would like to try working on this one

**Comment by JonasHelming** [comment]
@rschnekenbu I think the linked PR closes this ticket, could you confirm, please?

**Comment by rschnekenbu** [comment]
Merged PR #12039 added RefactorMove to CodeActionKind, so this task cvan be closed. Thanks!
