### ISSUE TITLE
[vscode] Support SnippetTextEdit

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12022]
see [SnippetTextEdit](https://code.visualstudio.com/api/references/vscode-api#SnippetTextEdit)
since vscode 1.72

see also https://code.visualstudio.com/updates/v1_72#_improved-workspace-editing-apis

**Comment by jonah-iden** [comment]
Hi, I would like to try working on this task as a good, bit more complex, next step in getting to know the theia vscode plugin integration
