### ISSUE TITLE
[vscode] Support DocumentDropEditProvider and DocumentDropEdit

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12025]
see [DocumentDropEditProvider](https://code.visualstudio.com/api/references/vscode-api#DocumentDropEditProvider) and [DocumentDropEdit](https://code.visualstudio.com/api/references/vscode-api#DocumentDropEdit)
since vscode 1.70

namespace [languages](https://code.visualstudio.com/api/references/vscode-api#languages) should probably be updated also.

**Comment by jonah-iden** [comment]
Hi, i would like to work on this issue. could someone assign me?

**Comment by jonah-iden** [comment]
just realized this depends on #11776. So I'll have to wait for #12065 to be merged
