### ISSUE TITLE
[vscode] Support TerminalExitStatus reason property

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12023]
see [TerminalExitReason](https://code.visualstudio.com/api/references/vscode-api#TerminalExitReason) & [TerminalExitStatus reason](https://code.visualstudio.com/api/references/vscode-api#TerminalExitStatus)

since 1.71

**Comment by jonah-iden** [comment]
Hi, i would implement this one. Could someone assign me?

**Comment by rschnekenbu** [comment]
Hi, I will take over this task.
