### ISSUE TITLE
Unreadable content assist selection

### ISSUE THREAD

**Issue by BarryDrez** [eclipse-theia/theia#12048]
### Bug Description:
In some cases when content assist is displayed, the item selected is unreadable.

### Steps to Reproduce:

1. Install Theia Blueprint for Windows from here: https://theia-ide.org/docs/blueprint_download
2. Start Theia Blueprint and create a Java class
3. In the class, start creating an import such as import org.
4. Notice that the content assist is displayed.
5. Use cursor arrows to move up and down within the list
6. Notice that the the org. text is not readable (probably due to a blue background with blue text)
7. This also happens when attempting to create a variable for example of type Integer.  On a new line, start typing the word Integer.  Notice the same issue in the content assist.
8. It does not happen when getting content assist for methods.  For example, create a string on one line: String s = "test";
9. On the next line type s.  You can use up/down arrows to go through the selections, and they are all readable.

### Additional Information
- Operating System: Windows
- Theia Version: 1.32.0

**Comment by vince-fugnitto** [comment]
@BarryDrez thank you for reporting the issue, do you mind providing a screenshot or screencast that shows the problem, when I tried on my end the behavior was correct (I was using the default theme).

https://user-images.githubusercontent.com/40359487/211312744-dc77fab4-e53f-44b7-a2e1-99db6901b9ee.mp4

**Comment by BarryDrez** [comment]
![TheiaBlueprint](https://user-images.githubusercontent.com/24534027/211316347-520e83a4-9e3b-45fb-b546-718de4695068.png)

Hi @vince-fugnitto Please see the above.  I am using a light theme.  Moving up and down the list with my cursor arrow keys, the "org." text is unreadable.  Thank you.

**Comment by vince-fugnitto** [comment]
It looks like vscode is making use of this newer color:

https://github.com/microsoft/vscode/commit/8c27c1f257b44acdf2c143df907eb975be89db35

![image](https://user-images.githubusercontent.com/40359487/211323050-2d603a93-9f4c-4204-b989-3bd3bc256597.png)

**Comment by BarryDrez** [comment]
@vince-fugnitto  Yes.  It looks fine in vscode.  I have developed my own Theia extension, and it has the issue using version 1.25.0.  Do I have to create a custom theme to fix this?

**Comment by vince-fugnitto** [comment]
I believe the issue stems from the fact that the handling for `focusHighlightForeground` is different than in vscode where they define a default for the default on condition that the selection is set.

- https://github.com/microsoft/vscode/blob/5b043e8af4b15febd268fc8c0e5676b24b280373/src/vs/platform/theme/common/colorRegistry.ts#L447

You could create a theme if you'd like, and make sure to explicitly set this color.

cc @msujew how would you suggest we handle `ifDefinedThenElse`? I believe we might run into problems where themes are cached and not properly updated as well (ex: switching themes).

**Comment by venciallee** [comment]
I think the problem is `!important` property in `highlightForeground` and it will override `focusHighlightForeground` ? and if i remove `!important` it work perfectly

```css
.monaco-list .monaco-list-row .monaco-highlighted-label .highlight {
	color: var(--theia-list-highlightForeground) !important;
}
```
