### ISSUE TITLE
Authority 

### ISSUE THREAD

**Issue by ReelLion** [eclipse-theia/theia#12059]
### Steps to Reproduce:

1.plan
2.patience
3.execute

### Additional Information

- Operating System: World Wide Web
- Theia Version: V1.0.0
[Master-Services-Agreement (1).pdf](https://github.com/eclipse-theia/theia/files/10393728/Master-Services-Agreement.1.pdf)

**Comment by vince-fugnitto** [comment]
I believe this was opened by accident, if not please provide additional details.
