### ISSUE TITLE
Navigation between changes in diff editor

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#1206]
The diff editor should reveal the first change on the first activation and there should be capabilities to navigate between changes at least with commands and key shortcuts.

**Comment by AlexTugarev** [comment]
this is resolved in #1255 and #1279, right?

though, one thing is missing: navigation to next and previous change in diff editor when it is opened in the *Git* view. @akosyakov, should we track it separately?

**Comment by akosyakov** [comment]
We can keep this issue for it.
