### ISSUE TITLE
vscode: Missing partial icon and color API support for ExtensionTerminalOptions and TerminalOptions

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12074]
With #11504, the added API was partially stub. Currently, only a ThemeIcon is supported, while the vscode API provides also support for URI and {dark: URI, liught: URI}. Also the color icon support has been stubbed, as the current implementation of the title widget as terminal title does not let an easy customization of the icon color.

**Comment by kittaakos** [comment]
From https://github.com/eclipse-theia/theia/issues/12645#issue-1769246548:

> [`ExtensionTerminalOptions#iconPath`](https://code.visualstudio.com/api/references/vscode-api#ExtensionTerminalOptions) is currently unsupported by Theia.
> 
> Create a terminal with `vscode.window.createTerminal(options: ExtensionTerminalOptions): Terminal`, set the `iconPath` to `heart`.
> 
> VS Code:
> 
> <img alt="Screen Shot 2023-06-22 at 10 50 13" width="312" src="https://user-images.githubusercontent.com/1405703/247879707-b7ccb85a-1617-42d5-ba64-809382ebb4de.png">
> Theia: <img alt="Screen Shot 2023-06-22 at 10 51 34" width="132" src="https://user-images.githubusercontent.com/1405703/247879771-352b5dec-b7e8-4442-aa3c-5412415d6b86.png">
> 
> ### Feature Description:
> `ExtensionTerminalOptions#iconPath` works as in VS Code.

**Comment by dhuebner** [comment]
I will take the PR over to apply the review suggestions.
