### ISSUE TITLE
Add "Reveal in File Explorer" to tab bar context menu

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#12073]
### Discussed in https://github.com/eclipse-theia/theia/discussions/12072

<div type='discussions-op-text'>

<sup>Originally posted by **ouliuquan** January 16, 2023</sup>
For now Theia don't have `Reveal in File Explorer`, Theia's `Reveal in Explorer` only locate file in resouce manager.
I think this real functional, can we consider adding this feature?

![open_in_explorer](https://user-images.githubusercontent.com/38776890/212586125-586cfccf-2d94-4c52-9b6b-1ffddaebc9e3.png)
</div>

**Comment by vince-fugnitto** [comment]
I believe the command already exists for electron (https://github.com/eclipse-theia/theia/pull/10523), not sure what it would look like in the browser:

https://github.com/eclipse-theia/theia/blob/7c9040139b359f002003b1a5c4af0507a2c0d6bc/packages/navigator/src/electron-browser/electron-navigator-menu-contribution.ts#L28-L34

**Comment by msujew** [comment]
@ouliuquan Do you run Theia in Electron or browser mode? I agree with Vince here, I believe it might not be possible to implement this feature in browser mode. VSCode also only has it when running locally in Electron.

**Comment by ouliuquan** [comment]
@vince-fugnitto Yes, I use the offical Eclipse `Theia Blueprint`, and my own build `yarn electron package`, this function(show file in file explorer) didn't show in Tabs, but show in Project Manager field.

My OS: Windows 11

**Comment by ouliuquan** [comment]
![image](https://user-images.githubusercontent.com/38776890/212687261-7bbb686f-01d6-4502-a98d-cb1c6079a492.png)
