### ISSUE TITLE
repo: update dependencies following `1.68.1` API bump

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#12080]
#### Feature Description:

With the bump of our default API to [1.68.1](https://github.com/eclipse-theia/theia/issues/12029) we should also think about aligning our dependencies to that version, mainly for **electron** and **node**.

We should:

- bump **electron** from `15.3.5` to [`17.4.7`](https://github.com/microsoft/vscode/blob/30d9c6cd9483b2cc586687151bcbcd635f373630/package.json#L139)
- drop support for [node 14](https://github.com/microsoft/vscode/blob/30d9c6cd9483b2cc586687151bcbcd635f373630/build/npm/preinstall.js#L12-L18)
- update any other dependencies as needed

We need to ensure that plugins built for `1.68.1` run in type of environment and conditions present in VS Code.

**Comment by paul-marechal** [comment]
Electron 22 still uses Node 16, let's aim for that? https://www.electronjs.org/blog/electron-22-0

**Comment by tsmaeder** [comment]
Note that our current electron version is causing problems: https://github.com/eclipse-theia/theia/pull/12192#issuecomment-1446453032

**Comment by tsmaeder** [comment]
I'm planning to update electron as part of https://github.com/eclipse-theia/theia/issues/2018

**Comment by vince-fugnitto** [comment]
I believe the issue can be closed:

- [x] electron was bumped
- [x] node 14 was dropped
