### ISSUE TITLE
The updateBreakpoints will send points infomaiton to gdb process yet when Use no debug mode run program

### ISSUE THREAD

**Issue by noneghost** [eclipse-theia/theia#12127]
### Steps to Reproduce:

1. set breakpoints 
2. click ``Run Without Debugging``

In configure() function , noDebug option is not judged and the breakpoint information is still sent.The set breakponites will trigger. 

![image](https://user-images.githubusercontent.com/24762470/215683664-6fa226d0-7dbe-4938-8e2b-4a3703235776.png)

### Additional Information

- Operating System:
- Theia Version:

**Comment by Noneghost** [comment]
#12148

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/12497.
