### ISSUE TITLE
[vscode] Can't show content of vscode plugin in the sidebar.

### ISSUE THREAD

**Issue by hyy215** [eclipse-theia/theia#12128]
### Bug Description:
Can't show content in the sidebar.

### Steps to Reproduce:

1. Download [tree view demo](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample) and package.
2. Install from vsix.
3. View is not shown in the sidebar.
![image](https://user-images.githubusercontent.com/34715914/215697942-4d382e47-4851-41ff-aa9a-b173ed2877aa.png)
![image](https://user-images.githubusercontent.com/34715914/215692380-0a1840ea-cb1a-4acb-ab4e-2ef40010eea1.png)
4. This is the error message, but not sure related to the bug.
![image](https://user-images.githubusercontent.com/34715914/215698652-3a8a30e0-8209-4ffc-b22c-d921ef7f85fc.png)

### Additional Information

- Operating System: win10
- Theia Version: master [fda6e9c](https://github.com/eclipse-theia/theia/commit/fda6e9cefaed08b730e8b2f5572b3429ffb24ffe)

**Comment by vince-fugnitto** [comment]
The extensions works fine when I built and tested it:

![image](https://user-images.githubusercontent.com/40359487/215764212-ce1683df-ef3c-4844-ba08-cc0dbdba1c56.png)

![image](https://user-images.githubusercontent.com/40359487/215764264-5391b742-43a4-4970-a109-06f3ed777318.png)

**Comment by hyy215** [comment]
@vince-fugnitto Thank you for you reply. It works after re-build the theia project.
