### ISSUE TITLE
vscode.window.registerTerminalProfileProvider is not a function

### ISSUE THREAD

**Issue by czadikem** [eclipse-theia/theia#12123]
### Steps to Reproduce:

1.  Install Pymakr Extension "https://github.com/pycom/pymakr-vsc/tree/v2.22.5 or https://marketplace.visualstudio.com/items?itemName=pycom.Pymakr"
2. Reload Theia Blueprint
3. Get error "Activating extension 'Pymakr' failed: vscode.window.registerTerminalProfileProvider is not a function"

### Additional Information

- Operating System: Fedora 37
- Theia Version: 1.32.0

**Comment by msujew** [comment]
The specific function that is missing has been [added in release `1.33.0`](https://eclipse-theia.github.io/vscode-theia-comparator/status.html) of Theia. Our newest release `1.34.0` targets vscode API version 1.68.2 and should therefore work with the extension in question. Try updating your Theia version and see whether that fixes your issue.

Note that we have [several tracker issues](https://github.com/eclipse-theia/theia/issues/12019) on the vscode API gap topic. In general, the Theia team will try to maintain a list of missing APIs in our trackers, so users and other contributors don't have to.
