### ISSUE TITLE
Backport Tabs API to 2023/1 Community Release

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12140]
### Feature Description:
There has been agreement in the community to backport the tabs API to the Jan. 2023 Community Release candidate. See https://github.com/eclipse-theia/theia/pull/12109

**Comment by tsmaeder** [comment]
@vince-fugnitto do you have info on how to do this?

**Comment by vince-fugnitto** [comment]
@tsmaeder I don't mind performing the actual release but if you want to give it a try the procedure is simpler for patch and community releases:

- prepare the release branch - test to confirm it works as expected
- build the changes - packages should have their `lib` folders
- `npm login` to get the access token to publish - I'll need to confirm if you have this
- perform the release using the command `yarn publish:latest` - when prompted choose an appropriate version, in this case it'd be `1.34.1`
- let the release complete, in the end there should be changes to `packages/core/README.md` - add these changes to a new commit (ex: https://github.com/eclipse-theia/theia/commit/b374c7f83fcb5b469c44d90dd2851173c0e2d2a5)
- preserve the two commits as is (not squashing) and push
- we want to create an `annotated tag` for the release on the first release commit (not the readme update) so we create one and delete any local versions that lerna might have created
- push the new annotated tag to the repo
- draft a new release on GitHub with that tag for the community release (https://github.com/eclipse-theia/theia/releases/new)

**Comment by tsmaeder** [comment]
> prepare the release branch - test to confirm it works as expected

This is where the trouble starts: how do we create the release branch? I guess off the release tag. What name?

**Comment by JonasHelming** [comment]
either 1.34-community or 1.34-community-2023-02
It does not make sense to include the micro version I guess, there might be several micro versions on the branch.
I prefer: 1.34-community-2023-02

**Comment by tsmaeder** [comment]
@vince-fugnitto I don't think I'll get my npm account sorted in time for this one. Would you be so kind as to do the release?

**Comment by tsmaeder** [comment]
> perform the release using the command yarn publish:latest - when prompted choose an appropriate version, in this case it'd be 1.34.1
let the release complete, in the end there should be changes to packages/core/README.md - add these changes to a new commit (ex: https://github.com/eclipse-theia/theia/commit/b374c7f83fcb5b469c44d90dd2851173c0e2d2a5)
preserve the two commits as is (not squashing) and push


@vince-fugnitto  on the 1.34 release branch, the last commits look like this:

```
commit b9b00921c2874fa03aee3fceb08b702e532aa7f9 (HEAD -> 1.34-community-2023-02, origin/1.34-community-2023-02)
Author: vince-fugnitto <vincent.fugnitto@ericsson.com>
Date:   Tue Feb 7 14:07:40 2023 -0500

    core: update re-exports for 1.34.1

    Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

commit 474bdc10b58be92953496b8bcac2af25ee2b48a3 (tag: v1.34.1-community)
Author: vince-fugnitto <vincent.fugnitto@ericsson.com>
Date:   Tue Feb 7 14:04:54 2023 -0500

    v1.34.1
```

I'm not how that chimes with your description above.

**Comment by vince-fugnitto** [comment]
@tsmaeder yes that looks correct, each release will have the two commits:
- version bump which will be the tag (ex: `v1.34.1`)
- re-exports update 

The double commits for a given release is due to `lerna` not performing one of the scripts which would perform the re-export for the same commit but rather as a second commit.

**Comment by tsmaeder** [comment]
But the "re-export update" changes will be created automatically?

**Comment by tsmaeder** [comment]
@vince-fugnitto the `yarn publish:latest` step fails with 

```
> @theia/core@1.34.2 prepare C:\Users\thomas\code\testdata\theia\packages\core
> yarn -s generate-theia-re-exports
lerna info lifecycle @theia/cli@1.34.2~prepare: @theia/cli@1.34.2

> @theia/cli@1.34.2 prepare C:\Users\thomas\code\testdata\theia\dev-packages\cli
> tsc -b

$ tsc --incremental && npx playwright install chromium
lerna ERR! E404 Not found
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vince-fugnitto** [comment]
It doesn't look like anything was actually published yet for `1.34.2` which is good, and if it was then there isn't much we can do besides using a new patch version (you can confirm if this is actually the case where no extensions were published). I'd make sure that everything is properly built with `yarn` where you have `lib` folders for each package (you can check just a couple as a sanity check), and also be sure to maybe not be on a vpn. The result of `yarn publish:latest` after choosing the new version when prompted should be successful if you let it run.

**Comment by tsmaeder** [comment]
> It doesn't look like anything was actually published yet for 1.34.2 which is good

so can I just `reset --hard` my local branch to the remote and try again?

**Comment by tsmaeder** [comment]
@vince-fugnitto the same problem keeps happening. Did anyone ever try to do a release from Windows?

**Comment by vince-fugnitto** [comment]
I think @paul-marechal has but I'm not 100% sure.

**Comment by tsmaeder** [comment]
@vince-fugnitto could you do the release once more, please? I'll try to find out what's wrong with my build, but I don't want to hold up the release

**Comment by paul-marechal** [comment]
I haven't released in a long while, but looking at your error:

> $ tsc --incremental && npx playwright install chromium
lerna ERR! E404 Not found

I would attribute the 404 error to the `npx playwright install chromium` part of the command but I don't think playwright is useful for releasing, so you might be able to remove it from the command that's failing?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto could you do the release once more, please? I'll try to find out what's wrong with my build, but I don't want to hold up the release. The release branch holds backported commits already.

@tsmaeder I can release if you'd like me to for sure, unless you want to keep trying.

**Comment by tsmaeder** [comment]
@vince-fugnitto yes, please.

@paul-marechal that was my first idea as well, but I can run `npx playwright install chromium` no problem inside the examples/playwright dir. The command terminates without any output.

**Comment by vince-fugnitto** [comment]
@tsmaeder it should be done :)

**Comment by tsmaeder** [comment]
@vince-fugnitto @paul-marechal still hitting the same 404 error as before, trying to do https://github.com/eclipse-theia/theia/issues/12297. I'm at a complete loss here. Can we force verbosity somehow to tell us what the script is trying to do?

**Comment by vince-fugnitto** [comment]
I'm wondering if we should include https://github.com/eclipse-theia/theia/pull/12248 which should help during the build process, and not be called during lerna as we remove it from the `prepare` script. It should help with issues you were experiencing with `playwright`. As for verbosity we might want to check if `lerna` includes such an option.

**Comment by tsmaeder** [comment]
I removed the line installing playwright from the script and it still fails with 404. I don't think that's the problem.

**Comment by tsmaeder** [comment]
Looking at network traffic at the time I get the 404, the build seems to be interacting with npmjs.org. My suspicion is that I do not have the proper access to publish the theia packages.

**Comment by tsmaeder** [comment]
Ping @vince-fugnitto could you check if I have the necessary access rights?
