### ISSUE TITLE
Unintended recursive set of title

### ISSUE THREAD

**Issue by emilhammarstedtst** [eclipse-theia/theia#12178]
This line creates an unintended infinite recursion when trying to set title of a webview.

https://github.com/eclipse-theia/theia/blob/81dd3ba42ed2cf6024913b3e0ea3e72feb26e976/packages/plugin-ext/src/plugin/webview-views.ts#L171

should use this._title when comparing and assigning within get/set function

**Comment by msujew** [comment]
@tsmaeder Since the getter of `this.title` accesses `_title` (which never changes) it doesn't stop at the second iteration. It should indeed lead to an infinite recursion.

**Comment by tsmaeder** [comment]
Ah, thanks. Property methods are a blessing and a curse.
