### ISSUE TITLE
QuickPickItem labels are hidden if description is too long

### ISSUE THREAD

**Issue by vnfedotov** [eclipse-theia/theia#12180]
### Bug Description:
Since Theia 1.34 item labels in QuickPick lists are hidden if item descriptions are too long.

### Steps to Reproduce:

1. Use vscode.window.showQuickPick
2. Provide vscode.QuickPickItem {label: 'myLabel', description: '${veryLongTextDescription}'}
3. QuickPick item will appear with clipped description and hidden label

![Screenshot 2023-02-14 144543](https://user-images.githubusercontent.com/590601/218729212-3c72dff5-9ab4-48a5-bd5c-031f0a4941b8.png)

### Additional Information

- Theia Version: 1.34

**Comment by vnfedotov** [comment]
Probably an impact of https://github.com/eclipse-theia/theia/pull/12095, as it's added `overflow: hidden` for the relevant css

**Comment by vince-fugnitto** [comment]
I believe it has been fixed by https://github.com/eclipse-theia/theia/pull/12239.
