### ISSUE TITLE
ShellTerminalProfile `modify` method broken

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#12197]
The type accepted by `modify` is basically used as a constructor argument for a new `ShellTerminalProfile`, but the types accepted by the `modify` method and the the constuctor of `ShellTerminalProfile` have almost nothing in common. The clearest manifestation of the bugs this causes is that opening a terminal in a multi-root workspace ignores the user's selection of root.

_Originally posted by @colin-grant-work in https://github.com/eclipse-theia/theia/pull/12066#discussion_r1110413890_

**Comment by colin-grant-work** [comment]
@tsmaeder, @JonasHelming, this may be worth considering for a hot fix for the community release.

**Comment by tsmaeder** [comment]
@colin-grant-work ignoring the selected workspace root is the _only_ manifestation of the bug I can see in the  code base. Not sure that warrants a bugfix release. Let's discuss severity.

**Comment by colin-grant-work** [comment]
@tsmaeder, I would agree it isn't _very_ severe, but it's an obvious regression in a not-uncommon scenario. In my view, that's exactly the sort of thing we want to avoid in the community releases.
