### ISSUE TITLE
[vscode] Support telemetry API 

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12232]
see https://code.visualstudio.com/updates/v1_75#_telemetry

**Summary:**
_This API aims to make using telemetry easier for extension authors and safer for the end user. The API enables things such as built-in secret cleaning, a telemetry output channel, error handlers, and automatic telemetry level management. This should result in a more cohesive telemetry experience that is guaranteed to follow our requirements._

![telemetry](https://user-images.githubusercontent.com/3964263/221524175-0b63e6cc-bc73-45ba-8d3a-3a689c589b2b.png)
![telemetry_namespace](https://user-images.githubusercontent.com/3964263/221524374-5271f8ec-ae70-41be-951d-22ed4d7ffc9b.png)

**Comment by JonasHelming** [comment]
@alvsan09 will analyze how and if to implement for Theia

**Comment by JonasHelming** [comment]
Please share your findings here

**Comment by rschnekenbu** [comment]
2 main classes are proposed with this API:
- **TelemetryLogger:** This class is responsible for the logging of events or errors. **Warning**: this API has a sensitive implementation, as it "guarantees" the cleaning of the data prior to sending it via the TelemetrySender. In API description, it also sends the info to the extension telemetry output channel. It manages also if the telemetry should be send or not based on user preferences and the telemetry level.   
  This one has an implementation in vscode. The implementation relies on regex to clean data. see https://github.com/microsoft/vscode/blob/main/src/vs/platform/telemetry/common/telemetryUtils.ts 
- **TelemetrySender:** This class is responsible to communicate with the service that will store the data coming from the logger. An example of this sender can be seen on this module: https://github.com/microsoft/vscode-extension-telemetry. This module communicates with Microsoft Azure Application Insights. By defaut, vscode does not provide any implementation of this sender. If none is set, the logger only sends to the Output Channel.

There are also minor additions, with telemetry levels, logger creation function and TrustedValues, that will not be cleaned by the logger.

**Comment by rschnekenbu** [comment]
I propose to implement the same way in Theia, with only the telemetry logger implemented and the interface for TelemetrySender. Only extensions would then provide and be responsible for the sending of data onto remote servers. 
There would then be one central point to log telemetry for extension providers, but by default, logged data would only be available locally via a specific output channel.
Other possibility is of course to stub this API.
