### ISSUE TITLE
The problem disappeared when we tested with a slightly newer version of the typescript vscode builtin extension.

### ISSUE THREAD

**Issue by Giangpro89** [eclipse-theia/theia#12245]
The problem disappeared when we tested with a slightly newer version of the typescript vscode builtin extension.

_Originally posted by @marcdumais-work in https://github.com/eclipse-theia/theia/issues/12227#issuecomment-1448739092_

**Comment by vince-fugnitto** [comment]
I believe the issue was opened by accident, if not please elaborate.
