### ISSUE TITLE
Terminal widget blink when resizing

### ISSUE THREAD

**Issue by meng-jpg** [eclipse-theia/theia#12280]
### Bug Description:

When I drag to adjust the window size of the application, the contents of the terminal widget will blink until I stop dragging.
To resolve this, maybe the following code can be changed:
#### packages/terminal/src/browser/terminal-widget-impl.ts
```
protected resizeTerminal(): void {
        const geo = this.fitAddon.proposeDimensions();
        const cols = geo.cols;
        const rows = geo.rows - 1; // subtract one row for margin
        this.term.resize(cols, rows);
    }
```
=>
```
// import debounce = require('p-debounce');
protected override resizeTerminal = debounce(() => {
        const geo = this.fitAddon.proposeDimensions();
        const cols = geo.cols;
        const rows = geo.rows - 1; // subtract one row for margin
        this.term.resize(cols, rows);
    }, 0);
```

### Steps to Reproduce:

1.start theia electron
2.open a new terminal
3.resize the window

### Additional Information

- Operating System: macOS Big Sur 11.2
- Theia Version: 1.34.0

**Comment by vince-fugnitto** [comment]
@meng-jpg thank you for reporting the issue, I believe that the flickering also happens in VS Code (which also uses xterm), but if you'd like to try and contribute a fix please don't hesitate to do so! :+1:

**Comment by meng-jpg** [comment]
> @meng-jpg thank you for reporting the issue, I believe that the flickering also happens in VS Code (which also uses xterm), but if you'd like to try and contribute a fix please don't hesitate to do so! 👍
Thank you for your suggestion.
https://github.com/eclipse-theia/theia/pull/12320
