### ISSUE TITLE
 Additional parameters for Theia CLI --list-extensions

### ISSUE THREAD

**Issue by emilhammarstedtst** [eclipse-theia/theia#12298]
### Feature Description: 

In VS Code one can use
`$ code --list-extensions --show-versions`
This could be applied 
`$ theia --list-extensions` 
output format:
`<extension-name>@<version>`

Similarly the `--install-extension` could be implemented. probably as a next issue.

**Comment by JonasHelming** [comment]
@vince-fugnitto @marcdumais-work FYI

**Comment by tsmaeder** [comment]
This is not as trivial as it first seems: the code that understands extension/plugin packages and deployment lives in the plugin-ext package. Depending on this package in the Theia cli would introduce a dependency cycle between the `cli` package and the `plugin-ext` package. Separating the deployment code from the `plugin-ext` package makes sense, though: adopters may very well have use cases where they don't need to deploy new plugins. An external installer mechanism might be responsible for that.

**Comment by msujew** [comment]
@tsmaeder If I understand this correctly, this is a user-command and not a dev-command (i.e. it doesn't come from the `@theia/cli` package, which users don't install). Instead, it should be handled in a `CliContribution` of the `plugin-dev` package.

**Comment by tsmaeder** [comment]
And anyway: it's still _desirable_ to have the deployment potentially separate from usage of plugins for the aforementioned reasons.

**Comment by msujew** [comment]
@tsmaeder We already have the ability to run the application, execute a command and quit again, see [here](https://github.com/eclipse-theia/theia/blob/6607185e37361b7251a5ef3df3016348bfa75fc9/packages/core/src/node/cli.ts#L42). It currently only works for `--help` and `--version`. I don't see why we shouldn't be able to do this with other commands as well.

**Comment by tsmaeder** [comment]
@msujew but `--help` and `--version` explicitly call `process.exit`, which is not what we want from a contribution. After some fiddling, I came to a solution where I start the `BackendApplication` as the default command when no other command is executed. That works fine after clearing some hurdles (like you can't have a command starting with `--` in yargs.

**Comment by msujew** [comment]
@tsmaeder Makes sense 👍
