### ISSUE TITLE
[vscode] Button in webview title bar not working

### ISSUE THREAD

**Issue by bhufmann** [eclipse-theia/theia#12314]
### Bug Description:
Installing the vscode-trace-extension as vsix file (build using PR https://github.com/eclipse-cdt-cloud/vscode-trace-extension/pull/90) in Theia blueprint (based Theia 1.35.0) the open feature doesn't work as expected. The newly added open button in the webview title bar is visible but it seems to be disabled. Installing the same vsix into a Theia application based 1.34.2 it works and the button is enabled and it opens the file dialog. I noticed that when I remove the `when` clause in the extension definition, then it works as well, however all webviews have that button which is not desired.

### Steps to Reproduce:

1. Build the vscode-trace-extension vsix file using PR https://github.com/eclipse-cdt-cloud/vscode-trace-extension/pull/90 and install it on Theia blueprint based on version 1.35.0
2. Switch to the trace viewer and hover over `Opened Traces` webview. The open button will appear. 
3. Click on button and nothing happens.

The following video shows the successful case:
[221713381-b9f81799-939a-4065-9966-2e7ade116c3e.webm](https://user-images.githubusercontent.com/413424/225389062-7e2e7442-afe4-4e2c-9543-c7e4c5464c19.webm)

### Additional Information

- Operating System: Linux Ubuntu 20.04
- Theia Version:  1.35.0

**Comment by msujew** [comment]
Possibly related to https://github.com/eclipse-theia/theia/pull/12182.

**Comment by vince-fugnitto** [comment]
> Possibly related to #12182.

@msujew it seems to be broken with https://github.com/eclipse-theia/theia/commit/81b98d671a07c545c2d30f01773da776856b34de, same with other toolbar items (ex: `vscode.git` that Alvaro was testing in https://github.com/eclipse-theia/theia/pull/12295).
