### ISSUE TITLE
Dynamic Editor Tab Sizing

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12328]
### Feature Description:
Currently, the editor tabs are always shown wide enough to show the full file name of the resource being shown. If there are more open tabs than can be shown in the available space, a scroll bar is shown to allow the user to scroll among the open editors.
We would like to offer the option to have an alternative tab layout based on variable width tabs inspired by how Chrome manages tabs. The tab behavior would be controlled by the following rules:

1. All tabs always have the same width
2. The  user can set a maximum tab width. No tab will ever be larger than the maximum width.
3. Tabs which are not wide enough to show the whole title will be shown as fading out towards the right (instead of `...`, for example)
4. The system defines a minimum width for tabs, typically enough to show the tab icon. 
5.  If there is not enough room to show all open tabs at their minimum size, we fall back to a scroll bar to move among the available tabs. An affordance (drop-down) is shown in this case to choose an open editor to reveal and activate.

We'll have to recompute the size of the tabs any time one of the following happens:

1. The minimum or maximum tab size changes
2. The number of open tabs changes
3. The width of the tab bar changes. In particular, this can happen when we activate and editor that contributes to the tab bar toolbar. 

Special care will be taken to support closing multiple tabs in succession: in order to keep the close button under the mouse, tabs should not be resized nor scrolled in while the mouse hovers over a tab. Any scrolling or resizing will delayed until the mouse leaves the tab area.

Since we might not show the whole file name anymore in the title, we'll improve the title hover to allow the user to quickly identify tabs.

**Comment by vince-fugnitto** [comment]
I believe the feature is similar to the proposal from https://github.com/eclipse-theia/theia/issues/5085.

**Comment by tsmaeder** [comment]
Thanks for the link, @vince-fugnitto I guess it's worth looking at the old behavior. I'll still keep this one open, though, as I think it's a more detailed request.

**Comment by tsmaeder** [comment]
In order to keep the PR's simpler, I'll try to start with implementing the dynamic tabs and do the drop down and effects later.
