### ISSUE TITLE
Python plugin fails to activate (2022.16.1)

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#12352]
### Bug Description:

On Theia master, after installing the latest python plugin available (2022.16.1) and opening a `.py` file, this toast message appears:

![image](https://user-images.githubusercontent.com/62660714/227954143-bee202c3-f52d-4c3e-83ff-681e22cc8e5d.png)

In the developer tools console, I see an earlier error that appears to be related: 

![image](https://user-images.githubusercontent.com/62660714/228027589-b9899a84-98fe-416c-bcd3-8b64e08de32f.png)

May be related to #12323

### Steps to Reproduce:

1. Start Theia master (I also had the default plugins installed)
2. Open the extensions view and install the latest ms-python plugin
3.  Open a python file, or just switch to the `python` language mode
4. See the toast message

### Additional Information

- Operating System:
Linux
- Theia Version:
Master

**Comment by colin-grant-work** [comment]
A little bit of digging suggests that there problems either internal to the plugin or has to do with our implementation of dynamic debug configurations.

The plugin around the specified version has code like this:

https://github.com/microsoft/vscode-python/blob/ad0286c9c44884c6d43a7648b14ca69bec9ae989/src/client/debugger/extension/configuration/dynamicdebugConfigurationService.ts#L18-L24

https://github.com/microsoft/vscode-python/blob/ad0286c9c44884c6d43a7648b14ca69bec9ae989/src/client/debugger/extension/types.ts#L46-L47

And `DebugConfigurationProvider` has this declaration:

```typescript
        /**
         * Provides {@link DebugConfiguration debug configuration} to the debug service. If more than one debug configuration provider is
         * registered for the same type, debug configurations are concatenated in arbitrary order.
         *
         * @param folder The workspace folder for which the configurations are used or `undefined` for a folderless setup.
         * @param token A cancellation token.
         * @return An array of {@link DebugConfiguration debug configurations}.
         */
        provideDebugConfigurations?(folder: WorkspaceFolder | undefined, token?: CancellationToken): ProviderResult<DebugConfiguration[]>;
```

So the class in the plugin just isn't handling the case where the `folder` argument can be undefined. That's certainly bad on their part, but it raises the question of whether there's a reason they were able to get away with. Is our version of the dynamic debug configuration work making calls that VSCode wouldn't?
