### ISSUE TITLE
Are not localized server's messages

### ISSUE THREAD

**Issue by Zebsterpasha** [eclipse-theia/theia#12393]
### Bug Description:
Localization of some notifications doesn't exist.
For example:
"Pending response rejected since connection got disposed"
"Restarting server failed"
"Server initialization failed."
"${this._name} client: couldn't create connection to server."
"The ${this.client.name} server crashed ${this.maxRestartCount + 1} times in the last 3 minutes. The server will not be restarted. See the output for more information."

I could find these phrases in module  vscode-jsonrpc/lub/common/connection.js

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.35

**Comment by msujew** [comment]
@Zebsterpasha Given that these messages don't come from vscode/Theia but from the `vscode-languageclient` package (or its dependencies), there is little that we can do on our side. VSCode extensions are responsible for their own localization, via the `vscode-nls` package or the `vscode/l10n` API.
