### ISSUE TITLE
https://github.com/eclipse-theia/theia/actions/workflows/playwright.yml/badge.svg?branch=master

### ISSUE THREAD

**Issue by taroenock** [eclipse-theia/theia#12439]
[[![Playwright Tests](https://github.com/eclipse-theia/theia/actions/workflows/playwright.yml/badge.svg?branch=master)](https://github.com/eclipse-theia/theia/actions/workflows/playwright.yml)]([![Playwright Tests](https://github.com/eclipse-theia/theia/actions/workflows/playwright.yml/badge.svg)](https://github.com/eclipse-theia/theia/actions/workflows/playwright.yml)) 

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by msujew** [comment]
@taroenock Do you mind giving a bit more context? Is this a request to add the badge to the readme?
