### ISSUE TITLE
Vue js Volar plugin fails to find typescript.js

### ISSUE THREAD

**Issue by CannyDuck** [eclipse-theia/theia#12443]
The volar plugin fails to finde the required typescript module to work.

` Message: Request initialize failed with message: Can't find typescript.js or tsserverlibrary.js in D:\Tools\theia-blueprint\node_modules\@theia\plugin-ext\lib\plugin\node\extensions\node_modules\typescript\lib`

Maybe the plugin search in the wrong path. I find the  typescript.js in  D:\Tools\theia\node_modules\typescriptt\lib

Any idea how to fix that?

### Bug Description:

1. install the volar plugin
2. see error in output window

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.36

**Comment by msujew** [comment]
For anyone looking to investigate this, the path in question seems to be very suspiciously looking like the path we return for [`vscode.env.appRoot`](https://github.com/eclipse-theia/theia/blob/17e52694b18bc25a375801f635555374df41c992/packages/plugin-ext/src/plugin/node/env-node-ext.ts#L55-L57). However, after a quick search, the `volar` extension doesn't seem to be using it. Neither can I find the error message. It might be that the extension is using some dependency that produces this error.

**Comment by mind-ar** [comment]
Hi, a workaround (for linux):
```sh
mkdir ~/node_modules/@theia/plugin-ext/lib/plugin/node/extensions
ln -s  ~/node_modules ~/node_modules/@theia/plugin-ext/lib/plugin/node/extensions/
```

**Comment by msujew** [comment]
@mind-ar Thanks for looking into it! Yeah, seems like the volar extension is using some very specific behavior of vscode that cannot be (easily) replicated by every Theia app. The volar extension seems to rely on the fact that there's always an `extensions` folder containing the TypeScript extension in the application root folder. This is always correct for vscode, but almost never in Theia. It might make sense to create an issue there, maybe someone is interested in fixing the behavior to also work in Theia.

Note that the value we return for [`vscode.env.appRoot`](https://github.com/eclipse-theia/theia/blob/17e52694b18bc25a375801f635555374df41c992/packages/plugin-ext/src/plugin/node/env-node-ext.ts#L55-L57) is still not correct.

**Comment by mind-ar** [comment]
Hi @msujew , thanks for the response. 
Another workaround is to install the  "JavaScript and TypeScript Nightly" (ms-vscode.vscode-typescript-next)

I agree that `vscode.env.appRoot` should point to the theia root folder, even if this doesn't solve the current problem.

I'll open an issue in volar to see if it can be solved at their side

BTW: i love theia!!

Thanks!

**Comment by msujew** [comment]
@mind-ar I've created a PR over at the Volar repo, see https://github.com/volarjs/volar.js/pull/195. Note that this doesn't really fix the issue (there is no real fix, since Theia just works differently from VS Code), but instead provides a helpful message when no TypeScript distribution can be found.

**Comment by msujew** [comment]
The PR https://github.com/volarjs/volar.js/pull/195 has been merged and the associated issue over at the volar repo closed. I'll close this one as well.
