### ISSUE TITLE
The default welcome view of the plugin is not displayed

### ISSUE THREAD

**Issue by helloworldmygithub** [eclipse-theia/theia#12458]
### Steps to Reproduce:

1.  Run start theia 
2.  Download the installation package in the vscode plugin market
     eg: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/rohinivsenthil/vsextensions/postcode/1.3.9/vspackage
4.  Install from VSIX
5.  The plugin doesn' have a welcom view to create request, in vsocde it works 
![image](https://user-images.githubusercontent.com/37649395/234500987-1bfe2c69-4f64-43ee-a3d7-fbfab2f21c59.png)

![image](https://user-images.githubusercontent.com/37649395/234498015-09b41161-bbca-4c2a-b659-72967e8e991f.png)

### Additional Information

- Operating System:
- Theia Version:

**Comment by helloworldmygithub** [comment]
I am trying to solve this problem
 https://github.com/eclipse-theia/theia/pull/12466

**Comment by helloworldmygithub** [comment]
I have submitted the code and it can solve the problem, but perhaps someone else has a better solution

**Comment by msujew** [comment]
I'll close this issue in favor of https://github.com/eclipse-theia/theia/issues/9361.
