### ISSUE TITLE
**breaking** `Edit` > `Copy` + `Edit` > `Paste` has no effect in the electron application after the electron version update

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#12487]
### Bug Description:

Originally from https://github.com/arduino/arduino-ide/pull/2027#pullrequestreview-1414148945.

It's impossible to copy-paste using the `Edit` menu with Theia Blueprint (Version 1.37.0 (Beta)).

### Steps to Reproduce:

1. You have an editor opened with some content
2. Select the content in the editor
3. Click `Edit` > `Copy`
4. Click `Edit` > `Paste`
5. Nothing happens besides the warning notification

⚠ Please use the browser's paste command or shortcut.

https://user-images.githubusercontent.com/1405703/236428486-7edb790b-fdcf-4755-b6d1-1e23f0d03106.mp4

It works when copy-pasting with the keyboard:

https://user-images.githubusercontent.com/1405703/236428543-afa7df24-0ac1-4fd3-887d-466804e53cbe.mp4

### Additional Information

It works on macOS due to this:

https://github.com/eclipse-theia/theia/blob/b6de8847ab17829e18c46745d58fb6ea1cd2902b/packages/core/src/electron-browser/menu/electron-main-menu-factory.ts#L190-L191

- Operating System: Windows/Linux
- Theia Version: 1.37.0

**Comment by kittaakos** [comment]
@tsmaeder, would you have the capacity to check this regression? I also take a look; maybe it's a quick fix.

**Comment by tsmaeder** [comment]
>I do not think so. Otherwise, I would remember to do that.

You're right...lost in the mega-PR 🤷

**Comment by alvsan09** [comment]
I have bisected the regression, and the issue was introduced recently with: 
https://github.com/eclipse-theia/theia/pull/12299

@tsmaeder , I think you would be in a better position to analyze the issue.

**Comment by tsmaeder** [comment]
@alvsan09 the reason is clear: https://github.com/eclipse-theia/theia/issues/12487#issuecomment-1536228858 I just don't know what the _intent_ of the predicate `isNative` is.
