### ISSUE TITLE
core: add confirmation prompt when executing `clear command history`

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#12495]
#### Feature Description

The goal is to prompt end-users to confirm whether or not they want to actually clear their command history when executing the command `Clear Command History`. The confirmation will prevent clearing history accidentally for instance, and aligns with the behavior present in VS Code.

#### Related Code

_Command Registration_:

https://github.com/eclipse-theia/theia/blob/18b25035b8f0205a16c03ded32b6213f2cee7139/packages/core/src/browser/quick-input/quick-command-frontend-contribution.ts#L38-L41

_ConfirmDialog_:

Definition:

https://github.com/eclipse-theia/theia/blob/18b25035b8f0205a16c03ded32b6213f2cee7139/packages/core/src/browser/dialogs.ts#L360

Example Usage:

https://github.com/eclipse-theia/theia/blob/18b25035b8f0205a16c03ded32b6213f2cee7139/packages/core/src/browser/dialogs.ts#L394-L402

**Comment by helloworldmygithub** [comment]
I want to work on this issue
