### ISSUE TITLE
Using `msgpackr@^1.9.0` causes maximum call stack exceeded error

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#12499]
From https://github.com/eclipse-theia/theia/pull/12484#issuecomment-1534747960

![image](https://user-images.githubusercontent.com/40359487/236213055-87a92ba7-3f51-4c61-aab2-8af324111792.png)

**Comment by paul-marechal** [comment]
Fix: https://github.com/kriszyp/msgpackr/pull/117

The cause is a bit weird... Sometimes we send monaco types directly to mspackr instead of clean DTOs. Said type returns `this` in its `toJSON` method which sends msgpackr into a recursion loop. I don't really understand why monaco types do that, we could also try to make sane DTOs before sending them. I opted for proposing a patch in msgpackr to handle this odd case more gracefully.

**Comment by paul-marechal** [comment]
The fix is now merged and released in `msgpackr@1.9.5`, we'll need to update our docs to tell people to update :)

**Comment by msujew** [comment]
We are now using `1.10.2`, which works without any hiccups.
