### ISSUE TITLE
documentation: fix typo in `readme`

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#12505]
#### Bug Description:

There is a typo in the `readme`:

https://github.com/eclipse-theia/theia/blob/d959af083ab98d8f7e982a69bac331fc48e18eca/README.md?plain=1#L93

`regularily` > `regularly`

**Comment by vince-fugnitto** [comment]
@tarunsamanta2k20 go ahead :)

**Comment by Niklas-Dahlquist** [comment]
> #### Bug Description:
> There is a typo in the `readme`:
> 
> https://github.com/eclipse-theia/theia/blob/d959af083ab98d8f7e982a69bac331fc48e18eca/README.md?plain=1#L93
> 
> `regularily` > `regularly`

Would like to add 'Github' > 'GitHub'
