### ISSUE TITLE
Is THEIA a good fit for mix of language editors and graphical HTML editors?

### ISSUE THREAD

**Issue by davag** [eclipse-theia/theia#1251]
I am interested in building a design platform that would support both textual editors (LSP and/or XText) as well as graphical editors (all types: form, complex graphics for flows, etc...). For the form editors, we would like to use modern web frameworks like React or Angular. For graphical editors Sirius would be great (based on Sprotty... ;-?)).

My main question is whether you think THEIA fits for this target. My main doubt is support of React/Angular for graphical editors? How extensible is THEIA for the graphical editors? Can we embed any HTML/javascript technology with the use of THEIA APIs to access files/workspace/etc..?

**Comment by svenefftinge** [comment]
I'd say it is a perfect fit as we designed it for such things. That said I've heard running Angular apps as components within larger websites is a bit tricky. With React or Vue.JS there are no issues.

**Comment by davag** [comment]
Thanks Sven, then kind of native integration if CHE to replace CHE IDE part and all perfect! But I think this is also ongoing

**Comment by abchakra** [comment]
@svenefftinge Do you have an example of formeditor running inside theia IDE? I want to understand if it will be same like GWT-JS/HTML integration in Eclipse Che or native Electron -Angular ?

**Comment by svenefftinge** [comment]
It would be simply creating a widget. You can use plain html/css for rendering or something like React or Vue.js. I don't have an example, though.

**Comment by dmarhas** [comment]
Let's suppose I create a standalone application with React ; how would I go about integrating that with Theia? As a plugin or as an extension? Also, how would I access the Theia APIs from this application? Let's say I want to create a wizard with React that intializes some files in the workspace.

**Comment by akosyakov** [comment]
With VS Code extensions (Theia plugins) you cannot access Theia extension APIs, only what is available in https://code.visualstudio.com/api/references/vscode-api.

With Theia extensions, you create a subclass of [ReactWidget](https://github.com/theia-ide/theia/blob/dc3d0e0787618d863dc6c86e0cd26377a2fa31dc/packages/core/src/browser/widgets/react-widget.tsx#L24), override [render](https://github.com/theia-ide/theia/blob/dc3d0e0787618d863dc6c86e0cd26377a2fa31dc/packages/core/src/browser/widgets/react-widget.tsx#L43) method to render your React component and inject Theia services which you want to use, as, for example, `OutputChannelManager` is injected in [OutputWidget](https://github.com/theia-ide/theia/blob/568d6f8f37de2e261f72586679f2a52617266fc7/packages/output/src/browser/output-widget.tsx#L27-L33).

**Comment by dmarhas** [comment]
Thanks Anton! I am wondering if someone will be kind enough to provide a "Hello React" sample extension that shows a simple usage of an injected Theia service. That will be so wonderful and will also accelerate the reach and adaoption of this awsome IDE.

I tried to look at some of the React based widget code in the core package and I must say it looks good but it is a bit mystifying. If end users like me start there,  it will take several weeks if not months to figure out and do something useful.

**Comment by kaviththiranga** [comment]
@dmarhas We had previously created a react widget with a diagram editor which modifies the current opened file. We used several theia extension APIs to handle the interactions. Code can be found here https://github.com/ballerina-platform/ballerina-lang/blob/master/tool-plugins/theia/ballerina-extension/src/browser/ballerina-preview-widget.tsx.
However, we no longer maintain this and we are trying to get our VSCode extension with same functionality working on Theia now.

**Comment by dmarhas** [comment]
@kaviththiranga Thanks! I am sure this will be very helpful to the entire Theia community.

**Comment by akosyakov** [comment]
@dmarhas unfortunately most of contributors are busy with own products based on Theia and there is no much time left for docs and examples :( 

If you figure it out by now, you are very welcome to build and document example. Here is https://github.com/theia-ide/theia-website/issues/26 for docs.

**Comment by akosyakov** [comment]
Also you can have a look at https://github.com/TypeFox/theia-workshop, but it could be a bit dated.

**Comment by JonasHelming** [comment]
For diagram editors, there is also Eclipse GLSP, which supports the creation of web-based diagram editors and also a full integration into Theia: https://www.eclipse.org/glsp/

For React widgets, the Theia extension generator allows you to create a simple template to get started with:
https://github.com/eclipse-theia/generator-theia-extension

I am closing this, please feel free to reopen in case you have any further questions!
