### ISSUE TITLE
Maximum call stack size exceeded (RangeError)

### ISSUE THREAD

**Issue by BarryDrez** [eclipse-theia/theia#12526]
### Bug Description:
Seeing many errors in the browser console: 
rpc-message-encoder.ts:151 Uncaught (in promise) Error: Error during encoding: 'Maximum call stack size exceeded'
    at MsgPackMessageEncoder.encode (rpc-message-encoder.ts:151:23)
    at MsgPackMessageEncoder.request (rpc-message-encoder.ts:137:14)
    at RpcProtocol.sendRequest (rpc-protocol.ts:161:22)
    at proxy-handler.ts:74:45

The message appears over and over when selecting different lines in the editor and when scrolling.

### Steps to Reproduce:

1. Clone the repository here: https://github.com/BarryDrez/java-service-editor.git
2. Build the project
3. Run the project and look at the browser logs

![image](https://github.com/eclipse-theia/theia/assets/24534027/65127afd-301f-478c-9ea5-75f9878f83ec)

![image](https://github.com/eclipse-theia/theia/assets/24534027/2aca3b3f-fd9a-4a45-9742-67ca79f44cfc)

### Additional Information

- Operating System:  Windows and Linux (in docker container)
- Theia Version:  1.37

**Comment by vince-fugnitto** [comment]
@BarryDrez can you confirm what version you're using of `msgpackr`? (ex: `yarn why msgpackr`) You may be experiencing https://github.com/eclipse-theia/theia/issues/12499.

**Comment by BarryDrez** [comment]
Hi @vince-fugnitto , thanks for the reply.  I do not specify this anywhere.  In my node modules, II see the following:
node_modules\@theia\core\package.json has "msgpackr": "^1.6.1",

**Comment by vince-fugnitto** [comment]
> Hi @vince-fugnitto , thanks for the reply. I do not specify this anywhere. In my node modules, II see the following: node_modules@theia\core\package.json has "msgpackr": "^1.6.1",

Can you check which version `msgpackr` is directly  in your `node_modules`? It should be one of the dependencies you see.

**Comment by vince-fugnitto** [comment]
It seems that you're running into https://github.com/eclipse-theia/theia/issues/12499 then, thanks for confirming :+1: Until it is fixed you can add a [yarn resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)  to pin the dependency to the version we use in this repo (`1.8.3`):

https://github.com/eclipse-theia/theia/blob/23e3df54c7bddcca953f2cc049ea104caf9cc4d5/yarn.lock#L7571-L7576

**Comment by BarryDrez** [comment]
Thanks a lot.  I will try that.

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/12499.
I updated the migration documentation to add a note for the resolution as well https://github.com/eclipse-theia/theia/commit/8194a49488f38a68ad4dc4ecf3f00c8b2097454b.

**Comment by BarryDrez** [comment]
@vince-fugnitto Just wanted to let you know that this solved the problem.

**Comment by BarryDrez** [comment]
@vince-fugnitto Ever since I made this change, the language server is taking a very long time to load.  Cleaning doesn't seem to help.  Is this related to the resolution?

**Comment by BarryDrez** [comment]
Here is a list of all of my plugins:
```
  "theiaPlugins": {
    "vscode.markdown-language-features": "https://open-vsx.org/api/vscode/markdown-language-features/1.70.2/file/vscode.markdown-language-features-1.70.2.vsix",
    "vscode-builtin-extensions-pack": "https://open-vsx.org/api/eclipse-theia/builtin-extension-pack/1.70.2/file/eclipse-theia.builtin-extension-pack-1.70.2.vsix",
    "redhat.java": "https://open-vsx.org/api/redhat/java/1.19.2023052304/file/redhat.java-1.19.2023052304.vsix",
    "vscjava.vscode-java-debug": "https://open-vsx.org/api/vscjava/vscode-java-debug/0.50.0/file/vscjava.vscode-java-debug-0.50.0.vsix",
    "vscjava.vscode-java-dependency": "https://open-vsx.org/api/vscjava/vscode-java-dependency/0.25.11/file/vscjava.vscode-java-dependency-0.25.11.vsix"
  },
```

**Comment by BarryDrez** [comment]
I tried some earlier versions of the plugins, and now it is starting up faster.
