### ISSUE TITLE
After executing the command, the terminal will have a blank title

### ISSUE THREAD

**Issue by helloworldmygithub** [eclipse-theia/theia#12524]
### Steps to Reproduce:

1. Press  ctrl+` to open a terminal
2. ping 127.0.0.1
3. after executing the command, the terminal will have a blank title

![terminal-issuse](https://github.com/eclipse-theia/theia/assets/37649395/536c4e40-7788-4dd9-9d5a-904b8388edb6)

### Additional Information

- Operating System: windows10
- Theia Version: 1.37.0

**Comment by vince-fugnitto** [comment]
Closed due to https://github.com/eclipse-theia/theia/pull/12525#issuecomment-1566358405.
