### ISSUE TITLE
Breakpoint context menu items are disabled in the editor

### ISSUE THREAD

**Issue by pisv** [eclipse-theia/theia#12548]
### Steps to Reproduce:

1. Using Theia *Electron* Example on the master branch,
try to add a source breakpoint in a JavaScript (or TypeScript) file
via the gutter context menu.

2. Note that all context menu items are disabled,
and use some other means to add a breakpoint (e.g. `F9`).

   <img width="235" alt="Screenshot" src="https://github.com/eclipse-theia/theia/assets/8298491/e800b61f-85b5-46df-af31-a1b4fa500fbe">

3. Right-click the breakpoint icon in the editor,
and try to remove the breakpoint via the context menu.

5. Note that all context menu items are disabled,
    but other means can be used to remove the breakpoint (e.g. `F9`).

   <img width="177" alt="Screenshot" src="https://github.com/eclipse-theia/theia/assets/8298491/8102efb9-1abe-4380-abd8-906575804e55">

### Additional Information

This issue occurs with the Electron Example, but not with the Browser Example.

- Operating System: macOS Ventura 13.3.1 (a) -- in case this may be OS-specific.

**Comment by vince-fugnitto** [comment]
@pisv thank you for reporting the issue, it is related to native context-menus in electron (and happens for other menus).
I narrowed down the regression to https://github.com/eclipse-theia/theia/pull/12483.

**Comment by tsmaeder** [comment]
@vince-fugnitto the fix is on the smaller side ;-)
