### ISSUE TITLE
UI not updated upon editing breakpoint condition

### ISSUE THREAD

**Issue by pisv** [eclipse-theia/theia#12546]
### Steps to Reproduce:

1. Using Theia Electron (or Browser) Example on the master branch,
add a source breakpoint in a JavaScript (or TypeScript) file.

2. Edit the breakpoint and set a condition (Expression or Hit Count).

3. Note that UI (e.g. the breakpoint's icon) is not updated after the condition is set.

| Observed | Expected |
|--------- | -------- |
| <img width="522" alt="Screenshot" src="https://github.com/eclipse-theia/theia/assets/8298491/0fdc9482-3a1f-45a6-a8b0-6ce49dc9479b"> | <img width="522" alt="Screenshot 2023-05-18 at 19 42 07" src="https://github.com/eclipse-theia/theia/assets/8298491/c7a1acb3-8cdc-418c-8e1f-861a13503e25"> |

### Additional Information

Debugging revealed that no `SourceBreakpointsChangeEvent` is fired from the `BreakpointManager.setMarkers` method upon setting breakpoint condition (step 2).

See also #8851.

**Comment by tsmaeder** [comment]
@pisv by "UI" you mean the hover message on the breakpoint?

**Comment by pisv** [comment]
By "UI" I mean that UI state in general is not updated in response to the action (e.g. the breakpoint's icon). The crux of the matter is that `SourceBreakpointsChangeEvent` is not fired from the `BreakpointManager.setMarkers` in this case. I've tried to patch it locally and can confirm that UI state is properly updated when the event is fired.

**Comment by pisv** [comment]
It looks like a regression introduced by #12183.

When a condition is set for a breakpoint, the `DebugSourceBreakpoint.updateOrigins` method updates the `breakpoint.raw` object using the given `data` before calling `this.breakpoints.setBreakpoints`. Therefore, when the `BreakpointManager.setMarkers` method is called from `setBreakpoints`, the breakpoint will have already been updated, so that the `newMarker` is deeply equal to the `oldMarker` at this line:

https://github.com/eclipse-theia/theia/blob/248f6b658e13f71b955d5f809f3c3c1528148a9b/packages/debug/src/browser/breakpoint/breakpoint-manager.ts#L78

So, `didChangeMarkers` stays `false`, and no event is fired in this case.

Here is the relevant call stack:

```
setMarkers (theia/packages/debug/src/browser/breakpoint/breakpoint-manager.ts:64)
setBreakpoints (theia/packages/debug/src/browser/breakpoint/breakpoint-manager.ts:114)
updateOrigins (theia/packages/debug/src/browser/model/debug-source-breakpoint.tsx:82)
acceptBreakpoint (theia/packages/debug/src/browser/editor/debug-editor-model.ts:398)
```

**Comment by pisv** [comment]
I could try to provide a patch, but I'm not quite sure what would be the proper way to fix it.

One way is to add an optional parameter to both `setBreakpoints` and `setMarkers` methods of `BreakpointManager`, which would force sending the event even if `didChangeMarkers` is `false` (but `changed.length > 0`).

In that way, both `setEnabled` and `updateOrigins` methods of `DebugSourceBreakpoint` would call `this.breakpoints.setBreakpoints` with the force flag.

I have tried this approach locally, and it seems to work fine.

But I'm not quite sure if it is a proper way.

What do you think?

**Comment by tsmaeder** [comment]
Hmh...a "force notification" flag sounds like a code smell. Whenever we have mutable data, we need change notification in order for users of the data to react to those changes. In our case, `DebugSourceBreakpoint" is mutable, but it has no change notification. The assumption in `breakpoint-manager.ts` seems to be that all mutation of breakpoints is done through `setBreakpoints()` with the breakpoints themselves being immutable. Unfortunately, the breakpoint-related code seems to be a bit messy, mixing UI concerns (markers, etc.) with the breakpoint data model. 
IMO, there are only two clean ways to solve this: either we keep the breakpoint objects mutable and introduce change notification on them or we make the breakpoints immutable (outside of the breakpoint manager) and delegate all updates to breakpoints to the breakpoint manager (either via `setBreakpoints()` or via more specific methods to update individual breakpoints).
