### ISSUE TITLE
[vscode] proposed API evolutions between 1.77.0 and 1.78.0

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12558]
### Sources
- **commit ref for tags** 
  - 1.77.0: 7f329fe
  - 1.78.0: 252e546
- **command used**
  - git difftool -d 7f329fe..252e546 -- src/vscode-dts/ 
  - git diff 7f329fe..252e546 -- src/vscode-dts/ > diff_1.77.0_to_1.78.0.txt
  - git log --oneline 7f329fe..252e546 -- src/vscode-dts/  > gitlog_1.77.0_to_1.78.0.txt

### Evaluation
- **new APIs:**
  - commentsDraftState.d.ts (https://github.com/microsoft/vscode/issues/171166)
  - debugFocus.d.ts (https://github.com/microsoft/vscode/pull/179132)
  - dropMetadata.d.ts (https://github.com/microsoft/vscode/pull/179918)
  - envCollectionWorkspace.d.ts (https://github.com/microsoft/vscode/issues/171173)
  - fileComments.d.ts (https://github.com/microsoft/vscode/pull/178478) 
  - formatMultipleRanges.d.ts (https://github.com/microsoft/vscode/pull/179166)
  - handleIssueUri.d.ts (https://github.com/microsoft/vscode/issues/46726)
  - inlineCompletionsAdditions.d.ts (https://github.com/microsoft/vscode/pull/180490 & https://github.com/microsoft/vscode/pull/180129) - note: added optional API on `InlineCompletionList` and added a required parameter on `handleDidShowCompletionItem()`
  - interactive.d.ts (https://github.com/microsoft/vscode/pull/179071) - note: some other updates there, but will likely disapear in next version (some code updated in 1.78 and then more code was deleted on main)
  - notebookExecution.d.ts (https://github.com/microsoft/vscode/pull/179258)
  - saveEditor.d.ts (https://github.com/microsoft/vscode/issues/178713)
  - scmTextDocument.d.ts (https://github.com/microsoft/vscode/issues/166615)
  - semanticSimilarity.d.ts (https://github.com/microsoft/vscode/pull/179640)
- **removed proposed APIs:**
  - vscode.proposed.contribEditorLineNumberMenu.d.ts (https://github.com/microsoft/vscode/pull/179168) - now a public placeholder
  - notebookDocumentWillSave.d.ts (https://github.com/microsoft/vscode/pull/179188) - now a public API
- **ignored changes:** 
  - documentPaste.d.ts (only comment changes)
  - quickPickItemTooltip.d.ts (comments update)
  - resolvers.d.ts (comments changed)

**Comment by msujew** [comment]
Given that we're now way further along in the API version, I think this can be closed.
