### ISSUE TITLE
Exception thrown when using Theia Blueprint 1.37

### ISSUE THREAD

**Issue by badrihcl** [eclipse-theia/theia#12574]
We have a vscode extension Rtist in Code which we test with Theia Blueprint. The extension was getting activated fine till Theia Blueprint 1.36 but now fails to get activated with Theia Blueprint 1.37. Exception is thrown
![image](https://github.com/eclipse-theia/theia/assets/127408770/86e02b42-f318-4e50-8695-ff26ea28fbe7)

### Steps to Reproduce:

1. Install latest Theia Blueprint 1.37
2. Open a workspace in Theia Blueprint. Install Rtist in Code extension from Open Vsix Registry
![image](https://github.com/eclipse-theia/theia/assets/127408770/1b5a567d-e2ea-4c68-a3c3-28a0d1ea5bd1)

Create a new File with .art extension.
The RTist in Code extension fails to load and the following error is seen
![image](https://github.com/eclipse-theia/theia/assets/127408770/50772d6d-7f54-46f2-abad-26860f1db21f)

 Also, this exception is thrown in console

![image](https://github.com/eclipse-theia/theia/assets/127408770/86e02b42-f318-4e50-8695-ff26ea28fbe7)

### Additional Information
The above steps worked fine with Theia Blueprint 1.36 and extension got activated fine.
![image](https://github.com/eclipse-theia/theia/assets/127408770/8f3da703-5754-4dfe-9143-491a80e10887)

The above steps also work fine with web version of Theia 1.37 but fail with Theia Blueprint 1.37.

Most likely this Theia Blueprint commit is causing the issue
![image](https://github.com/eclipse-theia/theia/assets/127408770/5e94243d-0f6b-4be5-8967-87d9281d4d88)

- Operating System: Windows
- Theia Version: 1.37 (Theia Blueprint)

**Comment by msujew** [comment]
@badrihcl We are aware of this issue (see https://github.com/eclipse-theia/theia/issues/12526) and provide a fix for users in the documentation (see https://github.com/eclipse-theia/theia/pull/12527).

**Comment by vince-fugnitto** [comment]
I've opened https://github.com/eclipse-theia/theia-blueprint/issues/265 in the `theia-blueprint` repo itself.
