### ISSUE TITLE
Linters not working continuously while editing JSON/Python files

### ISSUE THREAD

**Issue by muammereroglu** [eclipse-theia/theia#12595]
### Bug Description:

In Blueprint 1.37 or Theia 1.37 - 1.38,  for JSON or Python files, linting does not work continuously while editing; they perform just after opening the file and stop.  During editing, linters do not refresh and scan the file again; thus if there is a new error it does not show up, or if an error is corrected it stays at the editor and problems pane. 

### Steps to Reproduce:

1. Open Blueprint 1.37
2. Create a JSON file. Enter some random data with errors, eg.
`
{
"key1": "val1",
"key2": val2_no_quotes,
"key3": "val3_no_comma"
"key4": "val4"
}
` 
4. No errors are detected. Close and reopen the file, errors will be visible.
5. Fix some errors, they will not disappear. 

### Additional Information

- Operating System: Linux
- Theia Version: 1.37, 1.38
- This problem is not present in Blueprint 1.36.
- Demo app at theia-cloud.io has the same problem for JSON and JS files. However, linter for Java files was working correctly.

**Comment by msujew** [comment]
@muammereroglu Can you see whether you get the same error in the console as https://github.com/eclipse-theia/theia/issues/12499? If so, see https://github.com/eclipse-theia/theia/pull/12527 for a resolution.

**Comment by muammereroglu** [comment]
@msujew After downgrading msgpackr, the issue is resolved. The responsiveness of the editor was also a bit slow compared to previous versions; it also reverted back to normal after this solution.
