### ISSUE TITLE
When a debug session is not active, edits made to watch expressions are not immediately shown

### ISSUE THREAD

**Issue by sophiali23** [eclipse-theia/theia#12605]
### Bug Description:
When I don't have a debug session started, I notice that when I edit a watch expression, the updated expression is not shown until I click on the expression again.

### Steps to Reproduce:

1. Make sure you don't have a debug session running. Add a watch expression.
2. Edit that watch expression.
3. Observe that the old expression is still shown.
4. Click on the expression. The updated expression should now be shown.

### Additional Information

I believe it's caused by this block here: https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/view/debug-watch-expression.tsx#L45-L47
The function returns immediately when there is no debug session, so `this.options.onDidChange();` is not called.

My colleague suggested the following change:
```
    protected override setResult(body?: DebugProtocol.EvaluateResponse['body'], error?: string): void {
       if (this.options.session()) {
            super.setResult(body, error);
            this.isError = !!error;
        }
        this.options.onDidChange();
    }
```

- Operating System: Linux
- Theia Version: 1.36.0

**Comment by vince-fugnitto** [comment]
@sophiali23 thank you for reporting the bug, are you interested in contributing a pull-request to fix it?

**Comment by sophiali23** [comment]
@vince-fugnitto thanks for getting back to me! Yes, I'll open up a PR with the fix.
