### ISSUE TITLE
[vscode][proposed] documentPaste proposed API updates for 1.79

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12633]
documentPaste proposed API has evolved between 1.78 and 1.79:

- DocumentPasteEdit now has several required properties: id, label and optional priority. Constructor has also evolved to reflect these changes.
- DocumentPasteProviderMetadata has a new optional Property (copyMimeTypes) 
- DocumentPasteEditProvider#providerDocumentPasteEdits() is now optional.

This proposed API is used by several builtins (ipynb & markdown-language-feature)

**Comment by JonasHelming** [comment]
@msujew When do you plan to work on this? Would be nice to have this and https://github.com/eclipse-theia/theia/issues/12632
for the upcoming community release

**Comment by msujew** [comment]
@JonasHelming I should have some time to work on both of these issues this week.
