### ISSUE TITLE
Support `ExtensionTerminalOptions#iconPath`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#12645]
[`ExtensionTerminalOptions#iconPath`](https://code.visualstudio.com/api/references/vscode-api#ExtensionTerminalOptions) is currently unsupported by Theia.

Create a terminal with `vscode.window.createTerminal(options: ExtensionTerminalOptions): Terminal`, set the `iconPath` to `heart`.

VS Code:

<img width="312" alt="Screen Shot 2023-06-22 at 10 50 13" src="https://github.com/eclipse-theia/theia/assets/1405703/b7ccb85a-1617-42d5-ba64-809382ebb4de">

Theia:
<img width="132" alt="Screen Shot 2023-06-22 at 10 51 34" src="https://github.com/eclipse-theia/theia/assets/1405703/352b5dec-b7e8-4442-aa3c-5412415d6b86">

### Feature Description:

`ExtensionTerminalOptions#iconPath` works as in VS Code.

**Comment by msujew** [comment]
Related to https://github.com/eclipse-theia/theia/pull/12060 and https://github.com/eclipse-theia/theia/issues/12074

**Comment by kittaakos** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/12074.
