### ISSUE TITLE
When removing a folder from the workspace, the associated launch config still shows up in the debug widgets

### ISSUE THREAD

**Issue by Maddobun** [eclipse-theia/theia#12663]
### Bug Description:
After removing a folder from a multi-root workspace, debug configuration associated to that folder is still present in the debug widget dropdown

### Steps to Reproduce:

1. Open a multi-root work space
2. Verify that launch configuration for each root show up in the debug dropdown
3. Remove one of the root folder by right click -> remove folder from workspace
4. Verify that all launch configuration still persist

### Additional Information

- Operating System: Ubuntu 22.04
- Theia Version: 1.37.0

**Comment by Maddobun** [comment]
https://github.com/eclipse-theia/theia/blob/897f7a8766ab7159d6cf402b1f7e9b355b774597/packages/debug/src/browser/debug-configuration-manager.ts#L105-L115

My idea would be adding a callback `workspaceService.onWorkspaceChanged(this.updateModels)` on line 108, any thoughts?

**Comment by vince-fugnitto** [comment]
@Maddobun the idea seems promising, if you're interested you can contribute a pull-request where we can perform an in-depth review.
