### ISSUE TITLE
When using a symlink, it can not load a Theia frontend module

### ISSUE THREAD

**Issue by ikuta-tanigawa** [eclipse-theia/theia#12671]
### Bug Description:

`package.json` of `browser-app` can not load a Theia frontend module using a symlink.
The application does not finish loading when it runs if it used a symlink.
Below is an example of `package.json` using symlinks.

```
{
  "name": "browser-app",
  "version": "0.0.0",
  "dependencies": {
    ...
    "hello-world": "link:../../common-modules/hello-world"
  },
  ...
  "theia": {
    "target": "browser"
  }
}
```

Below is the error message by `Chrome` when running the application.

```
index.js:67 Failed to start the frontend application.
(anonymous) @ index.js:67

index.js:69 Error: The configuration is not set. Did you call FrontendApplicationConfigProvider#set?
    at FrontendApplicationConfigProvider.get (frontend-application-config-provider.ts:28:19)
    at ../../common-modules/node_modules/@theia/core/lib/browser/core-preferences.js (core-preferences.ts:189:87)
    at __webpack_require__ (bootstrap:19:1)
    at ../../common-modules/node_modules/@theia/core/lib/browser/shell/application-shell.js (application-shell.ts:38:1)
    at __webpack_require__ (bootstrap:19:1)
    at ../../common-modules/node_modules/@theia/core/lib/browser/shell/index.js (index.ts:17:1)
    at __webpack_require__ (bootstrap:19:1)
    at ../../common-modules/node_modules/@theia/core/lib/browser/index.js (index.ts:17:1)
    at __webpack_require__ (bootstrap:19:1)
    at ../../common-modules/hello-world/lib/browser/hello-world-contribution.js (hello-world-contribution.ts:3:1)
(anonymous) @ index.js:69
```

We want to separate repositories of shared modules and applications.
Therefore, we want to refer to the Theia module in another hierarchy with a symbolic link.
Could you tell me know if you have any solution?

### Steps to Reproduce:

[Sample Program](https://github.com/ikuta-tanigawa/theia-link-module-sample)

1. Create `browser-app` and Theia frontend module `hello-world` in different directory hierarchies.
2. Add `hello-world` to `dependencies` of `browser-app/package.json` using a symbolic link.
3. Build `hello-world` and `browser-app` respectively and run `browser-app`

### Additional Information

- Operating System: Ubuntu 20.04 (Windows10 WSL2)
- Theia Version: latest (1.32.0)

**Comment by vince-fugnitto** [comment]
> Could you tell me know if you have any solution?

@ikuta-tanigawa I'm not sure if the framework ever supported the `link` notation, but you could instead refer to external packages by [local path](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#local-paths) instead, or setting up a proper monorepo which can still separate packages as necessary (similarly to this repo for example).

If interested please also feel free to investigate why the link does not work and perhaps contribute a pull-request to support it.

**Comment by ikuta-tanigawa** [comment]
Thank you very much for your comment.
I tried to refer to external packages by local path and confirmed to work it.
We will use this method for the time being.
If we find the method used `link:`, I want to share it.

**Comment by ikuta-tanigawa** [comment]
We confirmed that we can load the front-end module using a symbolic link by rewriting `webpack.config.js` as follows.
```
const config = require('./gen-webpack.config.js');

config[0].resolve = {
    ...(config[0].resolve ?? {}),
    symlinks: false,
  };

module.exports = config;
```
