### ISSUE TITLE
Syntax issue with generated backend/frontend code

### ISSUE THREAD

**Issue by walisc** [eclipse-theia/theia#12670]
Is there any particular reason for the `return` statement here:

https://github.com/eclipse-theia/theia/blob/21fa2ec688e4a8bcf10203d6dc0f730af43a7f58/dev-packages/application-manager/src/generator/backend-generator.ts#L61-L67

Causes issues post-processing the generated file (e.g linting) as  the `return` statement is being used outside a function body. 

----
p.s in v1.37 / v1.38 this is here:

https://github.com/eclipse-theia/theia/blob/d17049652f630ced28280724ab4689c888788f6f/dev-packages/application-manager/src/generator/frontend-generator.ts#L161-L167

**Comment by kittaakos** [comment]
Same as https://github.com/eclipse-theia/theia/issues/6675.

**Comment by walisc** [comment]
> Same as #6675.

Do you know if there is any particular reason for it, or if it's a bug? Don't mind updating it if this is the case. Thanks!
