### ISSUE TITLE
Markdown Content not displayed in completion resolve from language server

### ISSUE THREAD

**Issue by AdhamRagabMCHP** [eclipse-theia/theia#12684]
### Bug Description:
I have made a language server plugin using VSCode’s language server API that can display some documentation for the command/parameter/keyword that we are autocompleting as part of the completion resolve - something like the first image.

The documentation displayed uses VSCode’s MarkupContent type for CompletionItem.documentation, which is analogous to MarkdownString, which is used for monaco.languages.CompletionItem.documentation.

Upon upgrading my Theia version from 1.32 to 1.34, and noticed that for the completion resolve, this MarkupContent is no longer displayed (see the second image).

While trying to diagnose when this changed, I figured out that some change between Theia versions 1.32 and 1.33 is behind this issue seeing as this issue exists in 1.33 - what this change is however, I am still trying to find out.

It is interesting to note that for Hover, documentation also uses this MarkupContent structure from the language server side yet it still displays properly, even though the completionItem resolve does not.

### Steps to Reproduce:
1. Use a language server with known autocompletion and completion resolve features - note that the VSCode built-in Javascript/TS Language server uses strings to display the autocompletion resolve, rather than MarkupContent
2. Try autocompletion and press on the arrow on the right of the autocompletion item 
3. An autocompletion resolve item should appear - if used on Theia 1.32 and less, something should show up. Any newer version seems to have this bug.

### Additional Information

![image](https://github.com/eclipse-theia/theia/assets/126698368/834e4250-1411-4fd8-9273-14e11f3dbdf7)

- Operating System: Ubuntu 18.04
- Theia Version:  1.32-1.33

**Comment by vince-fugnitto** [comment]
I narrowed the commit down to https://github.com/eclipse-theia/theia/commit/c8914a5b9f71e375a9576b9730762918c109c192 (using git bisect), there is likely a converter issue which causes the markdown to not display.

For those interested you can test using the [completions-sample-0.0.2.zip](https://github.com/eclipse-theia/theia/files/11968464/completions-sample-0.0.2.zip) plugin ([source](https://github.com/microsoft/vscode-extension-samples/tree/main/completions-sample).

_Before_:

https://github.com/eclipse-theia/theia/assets/40359487/d71e2104-79b6-4062-95a9-d5cdf8cbcb4c

_After_:

https://github.com/eclipse-theia/theia/assets/40359487/b703b7dd-363b-4c54-bea8-68675293f8b9
