### ISSUE TITLE
Icon-less VS Code “editor/title” menu contribution not rendered properly

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#12686]
### Bug Description:
In VS Code, if a menu contribution to “editor/title” is associated with a command that lacks an icon, the command is represented using its title. In the following screenshot, we see goodbyeWorld and helloWorld menu contributions. The former does not have an icon, so VS Code just shows "Goodbye World" for it. The latter (helloWorld) has a pen/edit SVG.
![image](https://github.com/eclipse-theia/theia/assets/109228283/2f11b62a-3aa6-40d8-9f48-22a9e3877d95)

In Theia, the goodbyeWorld menu item is present but with no title (and of course no icon). It's effectively "invisible"; on the surface, one can’t detect that the menu contribution is present. But if you hover over the area, a popup appears with the command’s title. And if you left click there, it will exercise the command. 
![image](https://github.com/eclipse-theia/theia/assets/109228283/dcafc35b-7dd7-4980-8118-acede6d1889e)

### Steps to Reproduce:
```
git clone -b menu_bug_1 https://github.com/jcortell68/theiasandbox
cd theiasandbox
yarn
yarn start:electron
```

### Additional Information
- Operating System: Windows
- Theia Version: 1.39

**Comment by cdamus** [comment]
I'm happy to look into this. Have recently been working in the vicinity 😀
