### ISSUE TITLE
Blueprint is Non-Responsive After Suspending for the Night

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#12707]
### Bug Description:
When I tried to "Open Folder" this morning after leaving Blueprint running overnight, nothing happened. In the log, I found 3 instances of this message:

```
Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED localhost:53433/socket.io/?EIO=4&transport=polling&t=ObE4dje&sid=eMQ_VeA3TV2iGx0GAAAK:1 
```

It seems anything requiring a connection to the back end (like opening a file from the navigator) is non-functional. Refreshing the window fixes the problem.

### Additional Information

- Operating System: Windows 11
- Theia Version: Blueprint 1.39.0

**Comment by tsmaeder** [comment]
@msujew since you are savvy about socket.io, maybe you can comment what the problem might be?

**Comment by tsmaeder** [comment]
https://github.com/eclipse-theia/theia/pull/13082/files

**Comment by JonasHelming** [comment]
@tsmaeder I also cannot reproduce this anymore, I suggest to close it. Great fix!
