### ISSUE TITLE
Copy-n-paste error in console.error() statement

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#12712]
https://github.com/eclipse-theia/theia/blob/dab0aade1d0de8a1394975e249db636070b4b9b8/packages/plugin-ext/src/hosted/node/scanners/scanner-theia.ts#L360

Probably should not be specifying `rawPlugin.contributes.colors` in that line :-)

**Comment by vince-fugnitto** [comment]
@jcortell68 are you interested in contributing a quick fix?

```diff
 try {
     contributions.localizations = this.readLocalizations(rawPlugin);
 } catch (err) {
-    console.error(`Could not read '${rawPlugin.name}' contribution 'localizations'.`, rawPlugin.contributes.colors, err);
+    console.error(`Could not read '${rawPlugin.name}' contribution 'localizations'.`, rawPlugin.contributes.localizations, err);
 }
```

**Comment by jcortell68** [comment]
@vince-fugnitto I knew what the proper line needs to be :-) But this is one of those no-brainer fixes that, IMO, is best handled with a pointer (this ticket) than a pull request. I'll probably be contributing to Theia in the future; at that time, I'd probably do a pull request.

**Comment by jcortell68** [comment]
BTW, a similar issue is present at line 360 (`rawplugin.contributes.colors` should be `rawplugin.contributes.localizations`)

**Comment by msujew** [comment]
Closed as a driveby in https://github.com/eclipse-theia/theia/pull/12798.
