### ISSUE TITLE
Unexpected folder behavior with file icon theme contribution from VS Code extension

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#12727]
### Bug Description:
I was playing around creating a file icon theme with a VS Code extension. My theme has but one icon--it tries to replace what's shown for a folder. 

And it works...kind of. My icon is shown when the folder is collapsed, but isn't shown when the folder is expanded. In VS Code, my icon override is shown in both collapsed and expanded states.

In Theia, it ends up looking like this:
![image](https://github.com/eclipse-theia/theia/assets/109228283/edd8dd99-23aa-4cac-a4ab-4a323c8c7735)
![image](https://github.com/eclipse-theia/theia/assets/109228283/8987edb4-2459-4276-9564-250a81e65304)

BTW, when the default icon theme is active, the folder icon is shown in both states. 

### Steps to Reproduce:
```
git clone -b icon_themes https://github.com/jcortell68/theiasandbox
cd theiasandbox
yarn
yarn start:electron
```
Choose `My File Icon Theme` as the icon theme in Theia's preferences.

### Additional Information

- Operating System: Windows
- Theia Version: 1.39

**Comment by cdamus** [comment]
I'll be happy to look into this.

**Comment by cdamus** [comment]
Hi, @jcortell68 . This appears to be working as expected. VS Code (and also Theia) distinguishes between "folder" and "folderExpanded" in the icon themes, to allow for visual differentiation of the expansion state. See the [VS Code API documentation](https://code.visualstudio.com/api/extension-guides/file-icon-theme#file-association) for details.

I've created a PR on your sandbox repo that fixes the problem: jcortell68/theiasandbox#2

**Comment by cdamus** [comment]
Oops, sorry, I did not observe (or forgot) that this shouldn't be necessary as it is not required in VS Code, where the expanded icon defaults to the folder icon if absent from the theme definition. Theia should provide the same fall-back behaviour.

**Comment by cdamus** [comment]
> Oops, sorry, I did not observe (or forgot) that this shouldn't be necessary as it is not required in VS Code, where the expanded icon defaults to the folder icon if absent from the theme definition. Theia should provide the same fall-back behaviour.

I've created PR #12776 to implement ape the VS Code fall-back behaviour.
