### ISSUE TITLE
UI regression in main menu and context menu when there is an icon

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#12738]
### Bug Description:
Hi,
In the last Theia 1.39 there is a regression in menu items having icons, the selection item will cut the left corner of the icon!
See the attached images.

![image](https://github.com/eclipse-theia/theia/assets/10339204/ae5f66bd-c30c-4290-a9a0-fe6dbcb77d27)

![image](https://github.com/eclipse-theia/theia/assets/10339204/d2824af8-6a21-43de-a277-8a2ae5152ba6)

### Steps to Reproduce:

1. just open the Run menu, or any context menu with an icon 
2. select an item with an icon
3. you will see the icon is cut

### Additional Information

- Operating System: mac and window
- Theia Version: Theia 1.39

**Comment by vince-fugnitto** [comment]
I can confirm the bug, it seems to be a regression introduced with https://github.com/eclipse-theia/theia/pull/12252.
