### ISSUE TITLE
Use of 'lastUsedTerminal' causing the typed character in terminal coming multiple times

### ISSUE THREAD

**Issue by glidingvish** [eclipse-theia/theia#12759]
### Bug Description:
If we reuse **terminalService**._lastUsedTerminal_ to start and open a terminal, we will see that the character we type coming multiple times. 
The many times we will reuse the lastUsedTerminal, that many times the chacracter duplication will happen.
In below way I am reusing the lastUsedTerminal: 

### Steps to Reproduce:

1. create a "hello world" extension
2. update the command contribution-> registerCommands with the following code:

```ts
@injectable()
export class SendTextExampleCommandContribution implements CommandContribution {

    constructor(
        @inject(TerminalService) private readonly terminalService: TerminalService
    ) { }

    registerCommands(registry: CommandRegistry): void {
        registry.registerCommand(SendTextExampleCommand, {
            execute: async () => {
                let terminalInstance:TerminalWidget;
                if (this.terminalService.lastUsedTerminal) {
                    console.log("reusing terminal.................");
                    terminalInstance = this.terminalService.lastUsedTerminal;
                } else {
                    terminalInstance = await this.terminalService.newTerminal({ title: "Sample terminal" });
                }
                await terminalInstance.start();
                this.terminalService.open(terminalInstance);
                terminalInstance.sendText("hey hellow!\n");
            }
        });
    }
}

```
4. execute the command multiple times using any manner (so that the last used terminal can be used while executing this command )
5. now start typing something in that used terminal
6. observe each keystroke occurring multiple times in the terminal input

### Additional Information

- Operating System: Ubuntu latest
- Theia Version:1.39.0

**Comment by vince-fugnitto** [comment]
@glidingvish thank you for reporting the issue, I'm a little confused by the snippet, given the `lastUsedTerminal` exists why the need to `start` and `open`. You should already be able to send text to it and prevent the multiple `sendText` appearing.

```ts
execute: async () => {
    let terminalInstance:TerminalWidget;
    if (this.terminalService.lastUsedTerminal) {
        console.log("reusing terminal.................");
        terminalInstance = this.terminalService.lastUsedTerminal;
    } else {
        terminalInstance = await this.terminalService.newTerminal({ title: "Sample terminal" });
        await terminalInstance.start();
        this.terminalService.open(terminalInstance);
    }
    terminalInstance.sendText("hey hello!\n");
}
```

**Comment by glidingvish** [comment]
> @glidingvish thank you for reporting the issue, I'm a little confused by the snippet, given the `lastUsedTerminal` exists why the need to `start` and `open`. You should already be able to send text to it and prevent the multiple `sendText` appearing.
> 
> ```ts
> execute: async () => {
>     let terminalInstance:TerminalWidget;
>     if (this.terminalService.lastUsedTerminal) {
>         console.log("reusing terminal.................");
>         terminalInstance = this.terminalService.lastUsedTerminal;
>     } else {
>         terminalInstance = await this.terminalService.newTerminal({ title: "Sample terminal" });
>         await terminalInstance.start();
>         this.terminalService.open(terminalInstance);
>     }
>     terminalInstance.sendText("hey hello!\n");
> }
> ```

thank you very much, this solves the issue.
