### ISSUE TITLE
[vscode][proposed] shareProvider proposed API updates for 1.80

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#12767]
The _shareProvider_ proposed API is used by the github builtin extension

ShareProvider#provideShare(item: ShareableItem, token: CancellationToken): ProviderResult<Uri **| string**> signature has changed with https://github.com/microsoft/vscode/commit/5504c4b854a2cd88800dcd2c44434307f23f99cf

Note that currently, the ShareProvider API is stubbed.

**Comment by tsmaeder** [comment]
From the category "oopsie": the version we currently have already _is_ the one present in 1.80.0. So move along, folks, nothing to see here (and nothing to do).
