### ISSUE TITLE
Editor should react on file changes done in a different editor, i. e. notepad

### ISSUE THREAD

**Issue by hannescmarits** [eclipse-theia/theia#12771]
If a file is open in the editor of theia and the file is changed and saved in an other editor, for example VS Code, than the changes should be displayed also in the editor of theia 

At least with the Eclipse Blueprint Version 1.39.0 (Beta) this did not work.

### Feature Description:
Just react on file changes done in other editors.

**Comment by vince-fugnitto** [comment]
@hannescmarits thank you for reporting the issue, as far as I am aware this works as expected (tested on both blueprint and from sources on Linux). Do you have any additional information about your system? Are you running out of inotify watchers?

**Comment by hannescmarits** [comment]
As mentioned i use the Blueprint Version 1.39.9 (Beta) under Windows 11. 
It doesn't matter if the file is on my pc or on a server.
It get no update information, and the file gets not updated. 
I am not sure how to check if the system runs out of inotify watchers. Can you please clarify how i can test this. 
Thanks in advance

**Comment by vladarama** [comment]
@hannescmarits 
I just tested on my Windows machine, using Blueprint 1.39.0 and I cannot reproduce this issue, seems to work fine on my end.

Demo:
![editor reacting file change](https://github.com/eclipse-theia/theia/assets/86936229/d4aa4bc3-4af9-4189-8347-a85333c55e64)

**Comment by vince-fugnitto** [comment]
@hannescmarits I had a colleague test on Windows (repo and blueprint) (https://github.com/eclipse-theia/theia/issues/12771#issuecomment-1655653305) and it worked as intended.

I'm not exactly sure what is happening in your case, does it work for smaller workspaces, are you certain you are modifying the same file and that it is being saved? If you would like to debug you can determine if you're properly receiving file watching events from `@theia/filesystem`.

**Comment by hannescmarits** [comment]
@vince-fugnitto 
I do not use a workspace, just have some files/one file opened. Looks similar to the video, but no update is shown.  
But the video shows, that it works. I ask some colleagues to test it on there machines and versions. :)
THANK YOU.

**Comment by msujew** [comment]
@hannescmarits Theia not being able to register updates on networks drives is a known issue, see https://github.com/eclipse-theia/theia/issues/12132.
