### ISSUE TITLE
Packaging theia 1.40.0 with electron fails

### ISSUE THREAD

**Issue by lewigZ** [eclipse-theia/theia#12811]
### Discussed in https://github.com/eclipse-theia/theia/discussions/12810

<div type='discussions-op-text'>

<sup>Originally posted by **lewigZ** August  8, 2023</sup>
Hey，when I use electron to package theia 1.40.0, I got a problem here, after executing "yarn" (pull dependencies) and "yarn build", I execute "yarn package:preview", and the following problem occurs:

yarn run v1.22.19
$ electron-builder --dir
  • electron-builder  version=24.6.3 os=10.0.19045
  • loaded configuration  file=D:\code\theia-electron1.40.0\electron-builder.yml
  • @electron/rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`   
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@vscode/windows-ca-certs@0.3.1, drivelist@9.2.4, keytar@7.2.0, msgpackr-extract@3.0.2, native-keymap@2.5.0, node-pty@0.11.0-beta17, nsfw@2.2.4 platform=win32 arch=x64
  • install prebuilt binary  name=drivelist version=9.2.4 platform=win32 arch=x64 napi=
  • build native dependency from sources  name=drivelist
                                          version=9.2.4
                                          platform=win32
                                          arch=x64
                                          napi=
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=D:\code\theia-electron1.40.0\node_modules\prebuild-install\node_modules\node-abi\index.js:36
      throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
      ^

    Error: Could not detect abi for version 23.3.12 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (D:\code\theia-electron1.40.0\node_modules\prebuild-install\node_modules\node-abi\index.js:36:9)
        at module.exports (D:\code\theia-electron1.40.0\node_modules\prebuild-install\rc.js:73:57)
        at Object.<anonymous> (D:\code\theia-electron1.40.0\node_modules\prebuild-install\bin.js:9:25)
        at Module._compile (node:internal/modules/cjs/loader:1126:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
        at Module.load (node:internal/modules/cjs/loader:1004:32)
        at Function.Module._load (node:internal/modules/cjs/loader:839:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        at node:internal/main/run_main_module:17:47

  • install prebuilt binary  name=keytar version=7.2.0 platform=win32 arch=x64 napi=
  • build native dependency from sources  name=keytar
                                          version=7.2.0
                                          platform=win32
                                          arch=x64
      ^

    Error: Could not detect abi for version 23.3.12 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
        at getAbi (D:\code\theia-electron1.40.0\node_modules\prebuild-install\node_modules\node-abi\index.js:36:9)
        at module.exports (D:\code\theia-electron1.40.0\node_modules\prebuild-install\rc.js:73:57)
        at Object.<anonymous> (D:\code\theia-electron1.40.0\node_modules\prebuild-install\bin.js:9:25)
        at Module._compile (node:internal/modules/cjs/loader:1126:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
        at Module.load (node:internal/modules/cjs/loader:1004:32)
        at Function.Module._load (node:internal/modules/cjs/loader:839:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        at node:internal/main/run_main_module:17:47

  • rebuilding native dependency  name=@vscode/windows-ca-certs version=0.3.1
  • rebuilding native dependency  name=drivelist version=9.2.4
  • rebuilding native dependency  name=keytar version=7.2.0
  • rebuilding native dependency  name=msgpackr-extract version=3.0.2
  • rebuilding native dependency  name=native-keymap version=2.5.0
  • rebuilding native dependency  name=node-pty version=0.11.0-beta17
  • rebuilding native dependency  name=nsfw version=2.2.4
  • packaging       platform=win32 arch=x64 electron=23.3.12 appOutDir=dist\win-unpacked
  • copying Electron  source=D:\code\theia-electron1.40.0\node_modules\electron\dist destination=D:\code\theia-electron1.40.0\dist\win-unpacked
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
Done in 80.81s.

"Error: Could not detect abi for version 23.3.12 and runtime electron"，this results in the packaged exe program having no content after clicking, just a blank page.  Could you tell me how to fix it,thanks.</div>

**Comment by msujew** [comment]
Given that this doesn't seem to be a general bug/issue, the discussion that you opened https://github.com/eclipse-theia/theia/discussions/12810, is the right place to discuss this. I'll close this one.
