### ISSUE TITLE
How can i show only fullscreen terminal

### ISSUE THREAD

**Issue by AlperRehaYAZGAN** [eclipse-theia/theia#12833]
Hi all,
I am grateful for the such a great tool. Thanks for your awesome works :) .  
  
I am just getting started to using Theia ide on my project. I need to use Theia-terminal as a iframe on my website page. But in [minimal setup](https://github.com/vince-fugnitto/theia-minimal/tree/main) and main monorepo example repositories setup instruction includes editor-fileexplorer-git-someextensions with "theia build" command. But i want to show only terminal view on my page.For this reason I want to open and attach only terminal view width 100% and height 100% page.  
  
Someone asked that before [Here](https://github.com/eclipse-theia/theia/issues/5663) But i need opposite of that question. How can i build Theia ide project that only displays machine terminal on port like 3030 (no editor or any other plugins needed.). 
Thanks.  

I also tried solution on previous issues like [open terminal by default](https://github.com/eclipse-theia/theia/discussions/10934) but it doesn't work  😞.  
I mean i want to create a view like Killercoda playground right section like shell view or Amazon Lightsail EC2 instance connect page SSH Web Terminal fullscreen like page.  
  
I used package.json likee below:  
```json  
{
  "name": "theia-minimal",
  "keywords": [
    "theia-extension"
  ],
  "version": "0.0.0",
  "files": [
    "lib",
    "src"
  ],
  "dependencies": {
    "@theia/core": "latest",
    "@theia/navigator": "latest",
    "@theia/outline-view": "latest"
  },
  "devDependencies": {
    "rimraf": "latest",
    "typescript": "latest"
  },
  "scripts": {
    "prepare": "yarn run clean && yarn run build",
    "clean": "rimraf lib",
    "build": "tsc",
    "watch": "tsc -w"
  },
  "theiaExtensions": [
    {
      "frontend": "lib/browser/theia-minimal-frontend-module"
    }
  ]
}

```  

  
And I tried to write a plugin for auto open terminal by default but i didn't work :(.  
```ts
// theia-minimal/src/browser/theia-minimal-frontend-module.ts
import { FrontendApplicationContribution } from "@theia/core/lib/browser/frontend-application";
import { TerminalService } from "@theia/terminal/lib/browser/base/terminal-service";
import { ContainerModule, inject } from "@theia/core/shared/inversify";

export class CustomFrontendApplicationContribution
  implements FrontendApplicationContribution
{
  @inject(TerminalService) private readonly terminalService: TerminalService;
  async initializeLayout(): Promise<void> {
    // Open a terminal in the bottom panel
    const terminal = await this.terminalService.newTerminal({});
    await terminal.start();
    this.terminalService.open(terminal, {
      widgetOptions: { area: "right" },
    });
  }
}

export default new ContainerModule((bind, _unbind, _isBound, rebind) => {
  // Bind it like this
  bind(FrontendApplicationContribution).toService(
    CustomFrontendApplicationContribution
  );
});
``` 

_Originally posted by @AlperRehaYAZGAN in https://github.com/eclipse-theia/theia/discussions/12831_

**Comment by vince-fugnitto** [comment]
@AlperRehaYAZGAN I believe you already opened the question [here](https://github.com/eclipse-theia/vscode-builtin-extensions/actions/runs/5787611586/job/15684903814#step:9:98) which is the proper location, I'll close the duplicate.

**Comment by AlperRehaYAZGAN** [comment]
Sorry for misunderstanding. What does that [link](https://github.com/eclipse-theia/vscode-builtin-extensions/actions/runs/5787611586/job/15684903814#step:9:98) do? Could i make fullscreen-terminal-only-view by using only built-in functions or I need to write custom extension to ensure that?

**Comment by msujew** [comment]
@AlperRehaYAZGAN I believe Vince just copied the wrong link and meant https://github.com/eclipse-theia/theia/discussions/12831.
