### ISSUE TITLE
Search view does not support replacing with regex groups

### ISSUE THREAD

**Issue by dpetroff** [eclipse-theia/theia#12847]
### Bug Description:
In an editor, it is possible to search using a regex and reference the regex groups in the replacement string with the `$n` syntax.

This does not work in the Search view. It simply replaces the matched groups with the literal replacement string.

### Steps to Reproduce:

1. Create a file containing the string `foobar`
2. In the editor, search for the regex `(foo)(bar)` and replace this with `$2$1` to see the text change to `barfoo`
3. In the search view, search for the regex `(bar)(foo)` and replace this with `$2$1` to see that the replacement is the literal string `$2$1` when the expected result is `foobar`

### Additional Information

- Operating System: Ubuntu 20.04.6 LTS
- Theia Version: 1.37

**Comment by msujew** [comment]
This is a rather longstanding issue, see https://github.com/eclipse-theia/theia/issues/6420. I'll close this in favor of the older one.

**Comment by dpetroff** [comment]
Ah, I was sure I had seen #6420 before. My mistake was searching for "regex" instead of real words.
