### ISSUE TITLE
electron: upgrade to `25.x.y`

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#12855]
#### Feature Description:

The goal is to upgrade **electron** to `25.x.y` (from `23.x.y` which is EOL) which includes the following [notable changes](https://www.electronjs.org/blog/electron-25-0#notable-changes).
In addition, VS Code `1.82.0` uses this [newer version](https://github.com/microsoft/vscode/pull/188268#issue-1811840991), and once we support the later API we can safely move as well.

**Comment by Sharyie** [comment]
hello, when will the plan be upgraded?

**Comment by vince-fugnitto** [comment]
> hello, when will the plan be upgraded?

@Sharyie thank you for the interest, there is no ETA at this moment regarding the electron upgrade.

**Comment by luckymark** [comment]
any new messages?

**Comment by sdirix** [comment]
To pick this up again: There is no technical reason to not support one of the later versions of Electron. VS Code is currently using [28.2.8](https://github.com/microsoft/vscode/blob/ace2b1b336da8888cf5dfe994bc9de32859eea2d/package.json#L152).
