### ISSUE TITLE
Cover how a new widget open handler can be added 

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#1287]
An example extension will be useful as well.

**Comment by JonasHelming** [comment]
I believe this was covered with https://github.com/eclipse-theia/theia/commit/f205aa59f0b7ec5e34ac6be2683e7b12c299caec#diff-470ca61928c22535df4c9e2201511224cf4c2c1c9a4426888c4e8af6f945908e

if we still want to add an example extension, we should probably do it here: https://github.com/eclipse-theia/generator-theia-extension

I suggest to close this issue
@vince-fugnitto

**Comment by vince-fugnitto** [comment]
Closing, if we believe that additional documentation should be added to cover creating new open handlers we can open a new issue.
