### ISSUE TITLE
nls: add missing `removeSession` localization when signing out

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#12874]
#### Feature Description:

There is a missing signing out localization for the `removeSession` method:

https://github.com/eclipse-theia/theia/blob/b3e8d425155eb92bb8a68773b2b7bb2f9584183b/packages/plugin-ext/src/main/browser/authentication-main.ts#L362-L365

We can benefit from the default localization:

```diff
removeSession(sessionId: string): Thenable<void> {
    return this.proxy.$removeSession(this.id, sessionId)
-       .then(() => { this.messageService.info('Successfully signed out.'); });
+       .then(() => this.messageService.info(nls.localizeByDefault('Successfully signed out.')));
}
```

**Comment by VanshSutariya** [comment]
I'd like to work on this issue , can you assign me this issue or I just raised the PR
