### ISSUE TITLE
How do I use vue's template compilation

### ISSUE THREAD

**Issue by woaixiaobo** [eclipse-theia/theia#12888]
### Discussed in https://github.com/eclipse-theia/theia/discussions/12877

<div type='discussions-op-text'>

<sup>Originally posted by **woaixiaobo** August 30, 2023</sup>
At present, I have implemented the functional writing method of vue to write widgets, but the template compilation method has failed, would like to ask if there is a method to achieve</div>

**Comment by msujew** [comment]
@woaixiaobo Please don't open issues for questions. The reason no one has commented on the discussion in question is probably because no one on the Theia team is familiar with Vue.
