### ISSUE TITLE
Webpack does not generate feedback when the backend component is bundled

### ISSUE THREAD

**Issue by meisenbarth-work** [eclipse-theia/theia#12899]
### Bug Description:
I've updated my project to use Theia 1.40.1 and enabled to bundling of the backend server (by deleting and letting theia regenerate webpack.config.js), now Webpack does not generate feedback messages anymore.

### Steps to Reproduce:

1. Update Theia in your project to 1.40.1
2. Build your project -> Build-Feedback is generated
3. Regenerate the webpack.config.js (or update it manually) to enable backend bundling
4. Build your project -> Build-Feedback is not generated

### Additional Information
I've updated all dependencies to the latest version using yarn upgrade to ensure it is not due to an old version in my setup.

When I disable the bundling by commenting out nodeConfig.config in the modules.exports array feedback is again generated, but I get the warning 'require function is used in a way in which dependencies cannot be statically extracted' (which should be suppressed according to gen-webpack.config.js)

- Operating System: Windows 10
- Theia Version: 1.40.1

**Comment by msujew** [comment]
I'm aware of this issue, but I have no idea why it occurs. There's nothing in the backend build step that "suppresses" the output - it just doesn't appear. Note that errors - if there are any - still appear. But in case of success, webpack prints nothing.

**Comment by meisenbarth-work** [comment]
I did some test, maybe that can help you pinpoint the issue.

When I try to include a file that does not exist in frontend bundle (import 'should-fail.css'; in ...frontend-module.ts) Webpack stays silent.
When I try to include the same file in backend bundle Webpack stays silent.
When I forcefully remove the native-webpack-plugin in my webpack.config.js (nodeConfig.config.plugins = nodeConfig.config.plugins?.filter((p) => p !== nodeConfig.nativePlugin);) build fails with missing modules (as expected) and the  warnings are reported for frontend and backend.

Then I've tried to disable parts of the native-webpack-plugin. As soon as compiler.hooks.afterEmit.tapAsync is called (even with an empty function as handler) Webpack stops generating messages.

**Comment by msujew** [comment]
> Then I've tried to disable parts of the native-webpack-plugin. As soon as compiler.hooks.afterEmit.tapAsync is called (even with an empty function as handler) Webpack stops generating messages.

Ha, that's pretty useful info, thanks! I'll see whether I can use another compiler hook to achieve the same behavior 👍

**Comment by meisenbarth-work** [comment]
That may not be needed, I've been tempering with the resulting js file of the plugin and when i change the result to:

        compiler.hooks.afterEmit.tapAsync(NativeWebpackPlugin.name, async (compilation, **callback**) => {
            await this.copyTrashHelper(compiler);
            if (this.options.ripgrep) {
                await this.copyRipgrep(compiler);
            }
            if (this.options.pty) {
                await this.copyNodePtySpawnHelper(compiler);
            }
            this.tracker.cleanupSync();

            **callback();**
        });
       
I get messages again (the callback parameter and the call of callback as last line).

**Comment by msujew** [comment]
@meisenbarth-work Using `tapPromise` instead of `tapAsync` did the trick (because who needs naming conventions?). See https://github.com/eclipse-theia/theia/pull/12902.

**Comment by meisenbarth-work** [comment]
Works for me, thanks a lot!
