### ISSUE TITLE
`Run build task` is failing to collect tasks

### ISSUE THREAD

**Issue by VGRSTM** [eclipse-theia/theia#12917]
### Bug Description:
`Task: Run Build Task` command is failing to collect build & test tasks out of the ones `Task: Run Task` is able to
PS: VSCode is able to

### Steps to Reproduce:
1. Just open a  Theia instance
2. Create a build type task running `Task: Configure Tasks ...` electing MSBuild as example. Save promoted tasks.json file.
2. Get a look at either `Task: Run Task` command or rely on `Terminal > Run Task` menu collected tasks. Just created `build` task is promoted.
3. Get a look at either `Task: Run Build Task` command or rely on `Terminal > Run Build Task` menu. No task is promoted .. `build` was expected one at least.

### Additional Information

- Operating System: All
- Theia Version: 1.41.0 (and older ones)

**Comment by planger** [comment]
Hi @VGRSTM,
thank you very much for your bug report. I was starting to review #12918 and first tried to reproduced this bug on `master` and `1.41.0`, but was unable to do that. Below is what I get in both versions:

https://github.com/eclipse-theia/theia/assets/588090/af28861a-3203-4c6c-bfa4-d2c925755d64

Am I doing something wrong?

**Comment by VGRSTM** [comment]
@planger you're right I'm not able neither right now to reproduce issue as described  (1.41.0 tag) ??? I'm ending with same as you.

What I'm able to reproduce (and this is a behavior delta to VSCode regarding build task collection) is editing generated task you've got moving from `"group": "build"` to `"group": {"kind": "build", "isDefault": false}`. 
My guess is for one reason or another at time I've reported this issue I was getting this `group` object syntax.

**Comment by planger** [comment]
Right, I can confirm two differences with respect to VS Code:
* If there is just one build task `"group": "build"` VS Code directly runs it without asking the user. Theia shows this task and the user has to confirm.
* Theia considers a task with `"group": {"kind": "build","isDefault": false}` to be invalid, while VS Code just treats it like a task with `"group": "build"`.

Is this the same you are seeing, or did you refer to another issue I didn't see so far?

**Comment by VGRSTM** [comment]
I'm seeing the same. My issue is behavior delta especially the one about invalidating `"group": {"kind": "build","isDefault": false}`. 
My extra pain is I'm creating programmatically tasks relying on `new vscode.Task(...` and sounds these tasks are internally relying on object usage as group definition (at least when we ask to dump them to tasks.json this syntax is promoted). Result in any case is these programmatically created tasks are not fetched doing `Run Build Task` despite proper group is set at creation time.

```
const task = new vscode.Task(....);
task.group = vscode.TaskGroup.Build;
```

**Comment by planger** [comment]
Ok, good that we see the same behavior. Now it is clear what the main issue is. To keep things clean, I suggest to close this issue and your PR and we open a new issue about the inconsistent handling of `"group": {"kind": "build","isDefault": false}` with a link to this issue as a reference.
I'm happy to do that (and also to look into it), if you wish.
WDYT?

**Comment by VGRSTM** [comment]
Feel free I'm ok. Thanks for taking care.

**Comment by planger** [comment]
I pushed https://github.com/eclipse-theia/theia/pull/13075 as a fix for the issue of `isDefault: false`. With this fix, tasks with `isDefault: false` should now be considered valid and correctly show up in the list of build / test tasks.
@VGRSTM Can you please confirm it now works?

**Comment by VGRSTM** [comment]
Works for me. Thanks @planger.
Still have on my own code base an issue while creating programmatically some tasks but your proposal is fixing anyway `isDefault` stuff what is good already.
