### ISSUE TITLE
Preference tree widget is failing to name extensions' nodes the same than VSCode

### ISSUE THREAD

**Issue by VGRSTM** [eclipse-theia/theia#12928]
### Bug Description:
See https://github.com/eclipse-theia/theia/discussions/12921

VSCode intellisense is promoting based on `package.json` : ![image](https://github.com/eclipse-theia/theia/assets/71082832/a1404938-7963-4046-b8f3-d5b185e10649)

### Steps to Reproduce:

1. Hack `package.json` of your preferred VSCode extension
2. Install it within Theia
3. Just check `configuration.title` is not considered at all asking for Settings widget

### Additional Information

Additional Information
Operating System: All
Theia Version: 1.41.0 (and older ones)

**Comment by msujew** [comment]
This has been resolved by https://github.com/eclipse-theia/theia/pull/13819.
