### ISSUE TITLE
Color Coding not working in Twig files in Chrome Browser 117.0.5938.132 

### ISSUE THREAD

**Issue by rahulgupta-acquia** [eclipse-theia/theia#12960]
### Bug Description:
Theia IDE color coding is not working in twig files only in Chrome Browser 117.0.5938.132  version.
In previous chrome version 116 it was working fine.

PFA
Chrome Browser 117.0.5938.132

<img width="925" alt="Screenshot 2023-09-29 at 5 33 14 PM" src="https://github.com/eclipse-theia/theia/assets/75003339/196cde72-8b9e-4017-a90a-d8d667f144cb">

Chrome Browser 116

<img width="902" alt="Screenshot 2023-09-29 at 5 25 03 PM" src="https://github.com/eclipse-theia/theia/assets/75003339/1478296d-c12b-4af6-b734-f92e906d1dad">

### Steps to Reproduce:

1. Use Chrome Browser 116.
2. Use Latest Theia version and create html.twig file
3. Check the color coding in twig file.

4. Use Latest chrome browser version 117
5. re-check the html.twig file color coding.

### Additional Information

- Operating System: MAC 
- Theia Version: 1.41.0
- Chrome Version 117 ( Latest version)

**Comment by vince-fugnitto** [comment]
@rahulgupta-acquia which `twigg` extension are you using which contributes syntax highlighting?

**Comment by rahulgupta-acquia** [comment]
@vince-fugnitto i don't used any twigg extension, As per my knowledge it is by-default provided by Theia previously and it is not working only in Chrome 117 browser.

**Comment by msujew** [comment]
@rahulgupta-acquia Theia doesn't provide any syntax highlighting by default. All syntax highlighting is contributed by vscode extensions. As far as I can tell, there is also no syntax highlighting for twig files in the builtin vscode extensions.

**Comment by rahulgupta-acquia** [comment]
Thanks @msujew ,
Might be the issue is related to Chrome 117 browser, because in Chrome 116 colour coding working fine.

**Comment by rahulgupta-acquia** [comment]
@msujew Could you please suggest which plugin we can use for support Chrome 117 support twigg color coding.

**Comment by msujew** [comment]
I was able to reproduce the issue using the [Twig Language](https://open-vsx.org/extension/mblode/twig-language) extension. I'm not sure why, but it seems like the newest version of Chrome doesn't play well with the version of `vscode-textmate` that we're using. See https://github.com/eclipse-theia/theia/pull/12963.

**Comment by rahulgupta-acquia** [comment]
Thanks for the update @msujew.
