### ISSUE TITLE
Notebook renderer basepath should be relative

### ISSUE THREAD

**Issue by bvenreply** [eclipse-theia/theia#12966]
### Bug Description:
The rendering of notebook output is not working in our app, as renderer scripts are imported from the root path whereas our app is mounted elsewhere. Any way this can be taken into account?

https://github.com/eclipse-theia/theia/blob/ab4627e4ffe15aec236793f98daab534c4e77f40/packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts#L416-L422C10

### Steps to Reproduce:

1. Access a Theia app through a reverse proxy rewriting the url path to anything other than the root 
3. Open e.g. a Jupyter notebook (the appropriate extension should ofc be installed)
4. Attempt to render outputs via cell execution
5. Observe 404 requests for renderer script

![image](https://github.com/eclipse-theia/theia/assets/105274814/e8282107-394d-4039-8284-667ef38a3ca4)

### Additional Information

- Operating System: `5.10.186-179.751.amzn2.x86_64 GNU/Linux`
- Theia Version: 1.41

**Comment by msujew** [comment]
@jonah-iden Can you take a look at this?
