### ISSUE TITLE
No download url for extension pack redhat.java (undefined)

### ISSUE THREAD

**Issue by sesky4** [eclipse-theia/theia#12978]
I'm running command `node_modules/.bin/theia download:plugins` and this happens
```
No download url for extension pack redhat.java (undefined)
Error: Errors downloading some plugins. To make these errors non fatal, re-run with --ignore-errors
    at downloadPlugins (/home/theia/dev-packages/cli/lib/download-plugins.js:113:15)
    at async Object.handler (/home/theia/dev-packages/cli/lib/theia.js:308:13)
```

I did some debugging and found that this may related to OVSXHttpClient.query() only fetches first 200 records and ignore the rest( and first 200 records is not compatiable with my theia version). The api seems paginated.

**Comment by msujew** [comment]
Hm, yeah that's pretty annoying. Unfortunately the open-vsx API does not provide a way to filter extensions by their supported vscode API version.

On another note, what Theia version are you running and prevents you from updating it?

**Comment by sesky4** [comment]
@msujew 
hi, thanks for your reply.
I'm using theia 1.55.2. Last time i tried at 2023-01-10 and it works.

**Comment by msujew** [comment]
@sesky4 1.55.2? I assume that's the supported vscode version. Then you're in dire need of an upgrade. Our most recent release was 1.42.1, supporting vscode version 1.81.0.

> Last time i tried at 2023-01-10 and it works.

I know that the java extensions update pretty regularly. It could simply be unfortunate timing that their last supported 1.55.2 version was pushed to down far enough to not appear on the first page anymore.

**Comment by sesky4** [comment]
@msujew  thanks ! 
I will try upgrading theia.
