### ISSUE TITLE
 Preloading Localization Occurs After Partial Internal Content Localization, Resulting in Localization Failure

### ISSUE THREAD

**Issue by likesubject** [eclipse-theia/theia#12977]
### Bug Description:

When preloading localization is performed during the `load` process, it causes a failure in localizing the commands within `CommonCommands`. This issue arises because the first import statement in the code snippet already attempts to localize the commands within `CommonCommands` before the localization is fully loaded.

```javascript
const { messagingFrontendModule } = require('@theia/core/lib/electron-browser/messaging/electron-messaging-frontend-module');
const container = new Container();
container.load(messagingFrontendModule);
```

This sequence of code triggers the localization process, but since the localization hasn't completed yet, it prevents proper localization for the commands within `CommonCommands`.

To resolve this issue, it is necessary to ensure that the localization process completes before attempting to localize any content, including the commands within `CommonCommands`.

### Steps to Reproduce:

1.When setting the language to Chinese, I noticed that some translations are not working properly.

### Additional Information

- Operating System: windows10 electron
- Theia Version: v1.42.1

**Comment by msujew** [comment]
I'll look into this once I'm back from vacation.
