### ISSUE TITLE
Theia does not respect StoppedEvent description in Debug Adapter Protocol

### ISSUE THREAD

**Issue by EvilBeaver** [eclipse-theia/theia#13049]
### Bug Description:

Theia does not use Description field of event, thus text "Paused on {0}" can't be properly localized

https://microsoft.github.io/debug-adapter-protocol/specification#Events_Stopped

>The full reason for the event, e.g. 'Paused on exception'. This string is shown in the UI as is and can be translated.

### Steps to Reproduce:

1. Write a debug adapter which sends Stopped event with 'description' field specified 
2. See that Theia does not show this string

https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/model/debug-thread.tsx#L233

In code above there is a localization of the reason, but there are two bad things here:

1. It does not localize "Paused on" part of text
2. It requires localization on Theia side, not in debug adapter side

## Expected behavior

Theia respects `description` field and if it exists - shows it AS IS without any prefixes, as required by DAP.

### Additional Information

- Operating System: any
- Theia Version: v1.43.0+

**Comment by msujew** [comment]
@EvilBeaver Are you interested in contributing a fix for this?

**Comment by EvilBeaver** [comment]
@msujew yes, I can fix it

**Comment by EvilBeaver** [comment]
@msujew one question: where translations are stored in the codebase?

```return nls.localize('theia/debug/breakpoint', 'breakpoint');``` - where lies the content of 'theia/debug/breakpoint'?

**Comment by msujew** [comment]
@EvilBeaver You can find all translation files [here](https://github.com/eclipse-theia/theia/tree/master/packages/core/i18n), with the requested key in particular [here](https://github.com/eclipse-theia/theia/blob/dcfff8326ed4272710e51665a52782a2a2ba2a5e/packages/core/i18n/nls.ru.json#L76).
