### ISSUE TITLE
Path that resolve to files in the workspace are not navigatable

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#13047]
### Feature Description:
In VSCode you can use paths printed in the console (e.g when transpile fails) to navigate to these files. This is a very nice feature.

**Comment by JonasHelming** [comment]
@vladarama @vince-fugnitto This might be a good issue for @vladarama ? Maybe a VS Code extension is missing providing this feature?

**Comment by AlexandraBuzila** [comment]
@JonasHelming I'd like to have a look at this.
