### ISSUE TITLE
Electron: Dialogs are not modal by default

### ISSUE THREAD

**Issue by zole40** [eclipse-theia/theia#13042]
### Bug Description:
There was a similar problem more than 1 year ago, which has been fixed.. https://github.com/eclipse-theia/theia/issues/10768
But there is a regression in later versions, and the dialogs are not modal by default but should be by this discussion. https://github.com/eclipse-theia/theia/discussions/13037#discussioncomment-7436537

### Steps to Reproduce:

1. Go to the File menu, and select the Open File... menu entry. A dialog to select the file should open.
2. Click outside the dialog, e.g. in the main window
3. The dialog goes into the background and a new dialog can be opened via the Open File... command, while the first one is still open.

### Additional Information

- Operating System: Win 10.
- Theia Version: 1.43.0

**Comment by bryanchenmchp** [comment]
Hi @zole40, could you close this issue to indicate that it's been resolved?
