### ISSUE TITLE
Notebooks: backspaces are rendered as printable rather than control characters in output cells

### ISSUE THREAD

**Issue by bvenreply** [eclipse-theia/theia#13069]
### Bug Description:

Backspaces are rendered as printable rather than control characters in notebook output cells.

Here's an example, from the Keras curses-like model training progress reporting interface:

![image](https://github.com/eclipse-theia/theia/assets/105274814/c04ad042-8ece-4902-82e7-21f2102dced5)

### Steps to Reproduce:

- Create a Jupyter notebook in Theia, and run this python code within a cell:
    ```python
    import time

    msg = "abcdef"

    for i in range(5):
        print(msg, end="")
        time.sleep(1)
        for j in msg:
            print("\b", end="", flush=True)
        time.sleep(0.5)

    ```
    
Here's a comparison with the same code run in vscode, which displays the expected output:

![image](https://github.com/eclipse-theia/theia/assets/105274814/d761c5a0-4eab-4bbc-8e1d-ffad072b83fa)

### Additional Information

- Operating System: `5.10.192-183.736.amzn2.x86_64 GNU/Linux` on the server `6.1.0-13-amd64 GNU/Linux` on the client
- Theia Version: `1.43.1`
- Browser: Chromium version `119.0.6045.105`
- Python jupyter kernel: tested with `3.8`, `3.11` and `3.12`

This is a less trivial issue than it may appear: taking the above example of Keras model training, note that many thousands of these lines are printed throughout the model training and the cell attempts to render them __all__, to the point that the browser is slowed down and the notebook becomes unusable.

**Comment by msujew** [comment]
@JonasHelming Seems to me like this should be treated as a separate thing to #13012.

@jonah-iden Can you take a look at this? I'm wondering whether vscode is doing preprocessing here, or whether the webview is doing something special that we don't support.

**Comment by jonah-iden** [comment]
sure i can take a look sometime this week

**Comment by kkistm** [comment]
Just curious if there are any updates about the ticket.

**Comment by jonah-iden** [comment]
I think i found the Solution and am currently testing it
