### ISSUE TITLE
Cannot configure provided tasks

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#13086]
### Bug Description:

In a Theia application that has VS Code extensions providing tasks (e.g. for npm, grunt, etc.), they are correctly shown when executing *Run Task...*. However, when I select a provided task folder (e.g. npm), I cannot click on the cogwheel to configure them in my `tasks.json`.

### Steps to Reproduce:

1. Open Blueprint (or any other Theia application with VS Code extension that contribute provided tasks)
2. Open a workspace where a provided task is discoverable (e.g. a folder with an npm module, like a Theia application)
3. Select *npm*
4. Try to click on the cogwheel

https://github.com/eclipse-theia/theia/assets/588090/3bfd4ca3-1c27-4ae5-bda8-ae80960b2956

What happens: nothing
What should happen: the provided task is copied over to tasks.json for further customization.

### Additional Information

- Operating System: Ubuntu Linux
- Theia Version: 1.43.0

**Comment by AlexandraBuzila** [comment]
@JonasHelming I can investigate this.
