### ISSUE TITLE
[navigator] Disable the `Open` and the `Open with` context menu contributions for folders

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#1308]
Currently, it results in a rejected promise. Or we just need to handle this on the frontend and log a warning instead.

**Comment by kittaakos** [comment]
From https://github.com/theia-ide/theia/issues/436#issue-253577779.

> testEnabled closure should be provided based on opener.canHandle for WorkspaceCommands.FILE_OPEN_WITH here:
https://github.com/theia-ide/theia/blob/master/packages/workspace/src/browser/workspace-commands.ts#L95
> 
> After #435 is fixed and testEnabled can handle Promise.

**Comment by marechal-p** [comment]
> I think #435 should be done for it to show these menu items only in the proper context, i.e. by checking the resource existence. It is not straightforward since phosphor and electron APIs don't accept promises.

While this is one way of doing it, we also already have the information in the navigator (which can already know if it is a file or a folder). IMO we should be able to access that information, somewhat synchronously.

wdyt?

**Comment by akosyakov** [comment]
@marechal-p if there is a way without coupling the editor with the navigator extension
