### ISSUE TITLE
bug: `go to definition` is blocked by the top menubar / toolbar

### ISSUE THREAD

**Issue by vladarama** [eclipse-theia/theia#13081]
### Bug Description:
Related issue: https://github.com/eclipse-theia/theia-blueprint/issues/314

Demo: 
![blueprint - go to definition blocked](https://github.com/eclipse-theia/theia-blueprint/assets/86936229/811d7bc9-8915-4550-929d-02be3098f39c)

### Steps to Reproduce:

1. Open Blueprint / Electron example.
2. Open an editor.
3. Right-click on anything in the upper-half of the page to open the context menu.
4. Try clicking on `Go To Definition (Ctrl +F12)`.
5. It will not work and the hover styling will not apply.

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.43

**Comment by msujew** [comment]
Resolved by https://github.com/eclipse-theia/theia/pull/14401.
