### ISSUE TITLE
vscode formatter settings are not correctly used in multi root workspaces

### ISSUE THREAD

**Issue by eneufeld** [eclipse-theia/theia#13108]
### Bug Description:

Using a multi root workspace where each folder has it's own .vscode folder with a settings.json which defines which formatter to use, is not usable in theia. On the first use of the formatter,  Theia asks which formatter to use and stores this data in the workspace file. This does not allow to use different formatters per folder. Furthermore this duplicates information that is already available.

I attached [a simple multiroot workspace](https://github.com/eclipse-theia/theia/files/13477920/multi-root-reproducer.zip) with a minimal set of dependencies. 
As formatter, prettier is used with eslint.

### Steps to Reproduce:

1. Install Prettier - Code formatter (https://open-vsx.org/extension/esbenp/prettier-vscode)
2. open the attached mutliroot workspace using the workspace file
3. run yarn in the root of the workspace
4. restart eslint or restart theia
5. open client/client1/src/index.ts
6. run save or format
7. see selection dropdown popping up
8. select prettier
9. see change in multi-root-reproducer.code-workspace

Running the same in vscode does not produce the same change and the correct formatter is used directly.

### Additional Information

- Operating System: Ubuntu 22.04
- Theia Version: Theia Blueprint 1.43.0 (Beta)

**Comment by sgraband** [comment]
I can take a look!
