### ISSUE TITLE
VS code API workspace.updateWorkspaceFolders is not working

### ISSUE THREAD

**Issue by umar-shabbir** [eclipse-theia/theia#13100]
### Bug Description:
Calling `workspace.updateWorkspaceFolders` from VS code API results in following error message being displayed in Theia browser and electron apps:
**"Failed to update workspace folders: Error: There is no active workspace"**

### Steps to Reproduce:

1. Clone this repository: https://github.com/umar-shabbir/theia-vscode-updateWorkspace
2. Run `yarn`, `yarn prepare` and `yarn start:browser` at the project root
3. Open the app in your browser using `http://localhost:3000/`
4. Run `Hello World `command from the Command Palette

### Additional Information

- Operating System: Windows 11
- Theia Version: 1.43.1, 1.44.0

**Comment by JonasHelming** [comment]
Do you by any chance have an example extension to reproduce this?

**Comment by umar-shabbir** [comment]
I just modified a Hello World sample to reproduce this issue. Please see https://github.com/umar-shabbir/theia-vscode-updateWorkspace
Also updated the Steps to Reproduce in issue description.

**Comment by JonasHelming** [comment]
Thank you. Just to be sure: The exact same extension works well in VS Code?

**Comment by umar-shabbir** [comment]
Yes, it worked in VS code. The directory was opened in a new untitled workspace as shown in the screenshot.
<img width="182" alt="image" src="https://github.com/eclipse-theia/theia/assets/48724934/d461e328-1623-44c1-ac00-675bfeae8065">

**Comment by rschnekenbu** [comment]
@JonasHelming, I can have a look. Can you assign me the task?
