### ISSUE TITLE
[vscode] Raise builtins version to 1.88.1

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#13147]
We need updated built-ins: even thought the official API we implement should be compatible with older built-ins, they use proposed API, with changes in random ways.

Moving to 1.84.2 version

**Comment by tsmaeder** [comment]
We're now at 1.88.1. Testing can only be done when we have closed the API gap, but I'll start the IP process.

**Comment by JonasHelming** [comment]
@tsmaeder @rschnekenbu is this done?
