### ISSUE TITLE
notebooks: incorrect handling of control characters if both `stdout` and `stderr` are used

### ISSUE THREAD

**Issue by bvenreply** [eclipse-theia/theia#13152]
### Bug Description:
When both `stdout` and `stderr` streams are used in an output cell of a notebook, erasing the last line using backspaces doesn't work; instead, the backspaces are ignored and the subsequent output is placed on a new line. Here's an example of this occurring in the Keras model training progress reporting UI:
![image](https://github.com/eclipse-theia/theia/assets/105274814/16689a64-ed0f-4383-826b-fde12455a5f6)

### Steps to Reproduce:
You can use the browser example app to reproduce this:

- Install the necessary vscode plugins:

    - ms-python.python (https://open-vsx.org/extension/ms-python/python)
    - ms-toolsai.jupyter (https://open-vsx.org/extension/ms-toolsai/jupyter)
    - vscode builtins (https://open-vsx.org/extension/eclipse-theia/builtin-extension-pack)

- Create a file with extension `.ipynb` and open it; it should be rendered as a notebook
- Create a code cell with the following code and run it:
    ```python
    import time
    import sys
    
    msg = "abcdef"
    print("spoiler!", flush=True, file=sys.stderr)
    
    for i in range(5):
        print(msg, end="", flush=True)
        time.sleep(1)
        for j in msg:
            print("\b", end="", flush=True)
        time.sleep(0.5)
    ```

- Observe the incorrect output. The line should be erased and printed again, here compared with vscode on the right:

![stdoutstderr](https://github.com/eclipse-theia/theia/assets/105274814/bbbec448-f00d-4219-854f-422913d21539)

### Additional Information

- Theia Version: The PR #13137 fixes a bug that prevented this other issue from manifesting. As soon as it is merged this issue will reproduce on `master` 
- Operating system: `Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux`
- Browser: Chromium version `119.0.6045.159`

cc: @jonah-iden

**Comment by jonah-iden** [comment]
Hi, I found the issue, the fix was super simple just very hard to spot. Added it t the Original PR since its just one modified line of code
