### ISSUE TITLE
registerUriHandler is not implemented

### ISSUE THREAD

**Issue by mathis-girault** [eclipse-theia/theia#13169]
### Feature Description:
The function [registerUriHandler](https://github.com/eclipse-theia/theia/blob/469bd744a02e5dcdbcbc338af178d410dd909616/packages/plugin-ext/src/plugin/plugin-context.ts#L571) is not implemented in theia.
It is defined in the [VS code API](https://code.visualstudio.com/api/references/vscode-api#window.registerUriHandler).

This is needed to handle callbacks to theia through URIs, for example when creating an extension using GitHub OAuth.

**Comment by tsmaeder** [comment]
@rschnekenbu this API is not marked as stubbed, that's why it does not appear on the comparator output. Can we put this on the backlog for API-compat?

**Comment by rschnekenbu** [comment]
@tsmaeder, I will take over this task. Can you assign it to me please? Thanks!

**Comment by npreiser** [comment]
I tested out the pull request today and its it not working with our handler for auth0.   Has this been tested/used yet?,   thanks.   Would love to get this working in our theia project if possible.  We are using electron, not (browser)

**Comment by tsmaeder** [comment]
Note that according to https://www.electronjs.org/docs/latest/tutorial/launch-app-from-url-in-another-app, we'll need some help from the packages in order to make this work on Linux/MacOS
