### ISSUE TITLE
Run theia on windows 7 and get a mesage about "GetPackageFamilyName could not be located in KERNEL32.dl"

### ISSUE THREAD

**Issue by yetaoup** [eclipse-theia/theia#13168]
### Bug Description:
I want to run theia on windows 7, and get a mesage about "GetPackageFamilyName could not be located in KERNEL32.dl"
Theia no support windows 7 ?

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System: windows 7 sp1
- Theia Version: 1.42

**Comment by msujew** [comment]
Theia uses Node 16 (at the very least). The last version of Node that supported Windows 7 was Node 13. Nothing we can do on Theia's side here.

Windows 7 hasn't even been supported by Microsoft for almost 4 years now. Closing the issue.
