### ISSUE TITLE
Terminal starts with incorrect size

### ISSUE THREAD

**Issue by Lythenas** [eclipse-theia/theia#13174]
### Steps to Reproduce:

1. Open a terminal
2. Try to write a very long line
3. Notice that it wraps at 80 characters even though the terminal is much wider
4. You can also run `tput cols` and `tput lines` to see the size
5. Resize (just wiggle slightly)
6. Try to write a very long line
7. Notice that it now wraps correctly

Note that in addition to the size being incorrect there is also a strange wrapping behavior that occurs, where it overwrite the same line instead of wrapping to the next line. This behavior is also fixed after a resize.

After some debugging I found the root problem to be that during start of the terminal widget, `resizeTerminal` is called together with `resizeTerminalProcess`. But `resizeTerminal` is the debounced `doResizeTerminal`. So `resizeTerminalProcess` actually runs first and before the actual size is updated.

I managed to fix the problem for me using the following:

```ts
@injectable()
export class TerminalWidgetImplFix extends TerminalWidgetImpl {
    protected doResizeTerminal(): void {
        super.doResizeTerminal();
        this.resizeTerminalProcess();
    }
}
```

and

```ts
rebind(TerminalWidget).to(TerminalWidgetImplFix);
```

I haven't tried if this problem also occurs on master, but I quickly looked at the code changes and didn't see anything that would fix it.

### Additional Information

- Operating System: Linux/Browser
- Theia Version: 1.43.1

**Comment by JonasHelming** [comment]
Thank you for the investigation. Would you consider contributing this fix?

**Comment by Lythenas** [comment]
Yes, I will look into it.
