### ISSUE TITLE
Support multi selection in the git view

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#1318]
It should be possible to select several files and apply the same action to all of them.

**Comment by kittaakos** [comment]
Also, a `stage all` and `unstage all` command would be useful too. Would that worth a separate ticket?

**Comment by JanKoehnlein** [comment]
Yeah, it's very annoying having to click on every file in a a bigger commit.

**Comment by vince-fugnitto** [comment]
Closing in favor of #7659.
