### ISSUE TITLE
Web socket disconnection: file explorer progress bar issue

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#13216]
### Bug Description:
Hi,

In the latest Theia 1.45, with the new web socket management and the front-end connection timeout, once I have a disconnection and try to expand a folder in the file explorer, the spinner on the folder keeps going also the progress bar in the file explorer keeps visible (although after getting connected back within the timeout period).

See the attached screenshot:

![image](https://github.com/eclipse-theia/theia/assets/10339204/d2466b46-7a7f-40fa-a271-5f2129ed23e7)

Thanks

### Steps to Reproduce:

1. set the frontendConnectionTimeout to some positive value and the reloadOnReconnect to false
2. build and start Theia browser
3. do a network disconnection
4. exand any folder in the file explorer
5. reconnect back
6. see thath the spinner icon and the progress bar still visible

Thanks

### Additional Information

- Operating System: Mac
- Theia Version: Theia 1.45

**Comment by JonasHelming** [comment]
@tsmaeder

**Comment by safisa** [comment]
I think the issue is in the "refresh" method of the TreeImpl class (packages/core/src/browser/tree/tree.ts).
The resolveChildren is failing (no connection), and maybe the CancellationToken is not working in this case to reset the busy status...

**Comment by tsmaeder** [comment]
Here's a scenario which I think could explain this:

1. `refresh()` calls `doMarkBusy()`
2. `doMarkBusy()` waits for a 800ms timeout
3. `refresh()` calls `resolveChildren()` which fails immediately.
4. `busySource.cancel()` is invoked
5. `doMarkBusy()` timeout expired, tree is marked as busy.
6. `doResetBusy()` is never invoked, because the token was canceled before the listener was added.

I think the fix would be to check `token.isCancellationRequested` before calling `doSetBusy()` in `doMakrBusy()`.

@safisa would you have time to give this a try?

**Comment by safisa** [comment]
Hi @tsmaeder 

This fix is not enough, I had to move the onCancellationRequested to be before the timeout:

```
protected async doMarkAsBusy(node: Mutable<TreeNode>, ms: number, token: CancellationToken): Promise<void> {
      try {
          token.onCancellationRequested(() => this.doResetBusy(node));
          await timeout(ms, token);
          if (token.isCancellationRequested) { return; }
          this.doSetBusy(node);
      } catch {
          /* no-op */
      }
  }
```

After this change, the problem is resolved, the user needs to expand the node again after the connection is back online, and then the node's busy state is reset (if we don't try to expand it, it will stay in a busy state, but I think this is the wanted behavior).

**Comment by safisa** [comment]
Hi @tsmaeder

If the code change above is good enough, do you want me to apply a PR? or you are doing it?

**Comment by tsmaeder** [comment]
@safisa please open a PR.
