### ISSUE TITLE
Handle `activeCustomEditorId` vs `activeWebviewPanelId`

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#13219]
### Bug Description:
In `webview-context-keys.ts` we update the context key `activeWebviewPanelId`. However, the documentation (https://code.visualstudio.com/api/references/when-clause-contexts) indicates that there should be two different context keys for custom editors and webview panels. I believe adding checking for `CustomEditorWidget` before checking for `WebviewWidget` would do the trick. 

### Additional Information

- Operating System:
- Theia Version: 1.45.0 master

**Comment by tsmaeder** [comment]
@rschnekenbu this might be something we can address as part of VS Code compat?

**Comment by rschnekenbu** [comment]
@tsmaeder, thanks for pointing this issue out! Definitely, this should be addressed as part of the VS Code compatibility effort.

**Comment by dhuebner** [comment]
@rschnekenbu @tsmaeder 
Is somebody already working on this? Otherwise I would like to take it over if it's okay.

**Comment by tsmaeder** [comment]
I'm not, don't know about @rschnekenbu

**Comment by dhuebner** [comment]
@rschnekenbu 
I've created a PR #13267

**Comment by dhuebner** [comment]
@tsmaeder 
My PR was merged. You can close this one.
