### ISSUE TITLE
Add Theia IDE Desktop to Homebrew Cask

### ISSUE THREAD

**Issue by zhoujian-official** [eclipse-theia/theia#13218]
Add Theia IDE Desktop to [Homebrew Cask](https://formulae.brew.sh/cask/)

### Feature Description:
Most eclipse IDEs are provided in [Homebrew Cask](https://formulae.brew.sh/cask/). It will be convenient if Theia IDE Desktop is also added to Homebrew Cask.

**Comment by tsekityam** [comment]
I've a PR to add Theia IDE to homebrew cask in review https://github.com/Homebrew/homebrew-cask/pull/164721

**Comment by tsekityam** [comment]
My PR was merged. Now we can install theia ide with `brew install --cask theiaide`

**Comment by JonasHelming** [comment]
Greta thank you!
