### ISSUE TITLE
VS code tree view context menu using view/item/context does not show properly

### ISSUE THREAD

**Issue by umar-shabbir** [eclipse-theia/theia#13213]
### Bug Description:
Adding custom context menu entries to a tree view using `view/item/context` in `package.json` does not work properly. The custom entry for context menu does not show properly and is barely visible in the UI. This means that menu item is being created but there is some bug with its UI rendering.
A screenshot from Theia and VS code is attached. Please see the difference how edit icon is appearing in both places.

### Steps to Reproduce:

1. Package a `.vsix` of [VS code tree view sample](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample) or use the attached `.vsix` file from `custom-view-samples-0.0.1.zip`
2. Run browser example app from Theia repository and install tree view sample `.vsix`
3. Open any folder in editor which contains a `package.json` file
4. Open package explorer from activity bar and hover on right side (where inline menu items are displayed) of any package
5. Notice the visibility of edit menu item

### Additional Information
Left side is Theia browser app. Right side is VS code extension development host preview
<img width="582" alt="theia-treeview-context-edit" src="https://github.com/eclipse-theia/theia/assets/48724934/2e5e4da3-8f6c-4efb-ac6e-ea143a04ad6e">

Tree view sample: 
[custom-view-samples-0.0.1.zip](https://github.com/eclipse-theia/theia/files/13770561/custom-view-samples-0.0.1.zip)

- Operating System: Windows 11
- Theia Version: 1.44.0

**Comment by JonasHelming** [comment]
@rschnekenbu

**Comment by rschnekenbu** [comment]
On master branch, the icons are now visible. They were indeed missing in version 1.44.0. 
This bug can be closed.
