### ISSUE TITLE
Notebooks: extra rendering of images

### ISSUE THREAD

**Issue by bvenreply** [eclipse-theia/theia#13223]
### Bug Description:

Images shown in a notebook using the `display` IPython builtin are rendered twice if they're above a certain size and  `display` is called more than once. That is, calling `display` twice will result in three images being rendered:

![image](https://github.com/eclipse-theia/theia/assets/105274814/3e80379b-f02d-4f8d-925e-d8dd511a5c58)

### Steps to Reproduce:

This can be reproduced in the Theia browser example.

- Install JN depencies: extensions for Python, Jupyter and VSCode builtins
- Install the required Python packages with `pip install ipykernel Pillow`. You may want to use a virtual environment
- Create a JN (a file with extension `.ipynb`) and open it
- Paste this example code:
```python
from PIL import Image

img_1 = Image.new("RGBA", (1600, 200), color="red")
img_2 = Image.new("RGBA", (1600, 200), color="blue")

display(img_1)
display(img_2)

```
- Run the notebook. Make sure the notebook is running in the environment where you installed the above packages

Observe the second image is sometimes rendered twice, once before the first image. The probability somehow depends on the size of the image, with the above size it should be around 50%, with larger images it approaches 100%.

In VSCode we only ever see the correct output, i.e. two images being rendered (one per `display` call):
![image](https://github.com/eclipse-theia/theia/assets/105274814/7478c645-5bdd-49ab-8293-d30cc62d998b)

### Additional Information

- Operating System: `Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux`
- Theia Version: `master`
- Python version: 3.10
- `Pillow` version: `10.2.0`
- `IPython` version: `8.19.0`

**Comment by JonasHelming** [comment]
@msujew
