### ISSUE TITLE
Builtin VSIX plugin is added to the installed list instead of the builtin list

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#13222]
### Bug Description:
Hi,

I have some vscode plugins (in a VSIX file format) in the plugins folder (where all builtin files exist). After upgrading to the latest Theia 1.45 those plugins are part of the installed view instead of the built-in view! They should be treated as builtin as before since they statically exist in the package plugins folder.

### Steps to Reproduce:

1. add any vsix file to the plugins folder
2. run the browser example
3. check and see that this plugin is under the installed list in the extensions view/panel.

### Additional Information

- Operating System: Mac
- Theia Version: Theia 1.45

**Comment by JonasHelming** [comment]
Hi,

I am actually not 100% sure what the correct behavior should be. The plugin you add was not present when the Theia application was built, so in a sense, it is not really "built-in"?

**Comment by safisa** [comment]
Hi,
The issue is that Theia 1.45 treats plugins under the plugins folder in two different ways now. Extracted plugins that were downloaded and extracted (based on the package.json definition) are added to the built-in list, and the VSIX files that were copied into the same plugins folder (manually or using the pipeline) when building the package are added to the installed list.
Moreover, since the VSIX plugins are added to the installed list, then I can uninstall them, and now this causes some confusion, the uninstall removes the plugin from the deployedPlugins (under user .theia folder), but when restarting the server (not reload) the server deploys it again and it shows up under the builtin list !!! Doing another server restart will show it under the installed list !!! VERY confusing...

I can overcome this issue, by extracting the VSIX files into that folder, but I thought this was an issue since it is a different behavior than before plus the misbehavior on server restarts...

Thanks

**Comment by xai** [comment]
Hi! Thanks for reporting! Sounds like this is due to the changed behavior introduced by my #13178 => I will look into this.
