### ISSUE TITLE
when a custom websocket provider is used, not all strings are getting localized

### ISSUE THREAD

**Issue by hyddel** [eclipse-theia/theia#13237]
### Bug Description:
when a custom websocket provider is used, not all strings are getting localized

### Steps to Reproduce:

1. Use the attached sample code
2. Run the following command: `yarn`
3. Include this change: https://github.com/eclipse-theia/theia/pull/13199/files  (I have directly edited the lib file in the node_modules present in the root)
4. Run the following command: `yarn prepare && cd browser-app && yarn download:plugins && yarn local_start`
5. Go to `http://localhost:4444/`
6. wait for code editor to load and then change locale to `es`
7. Observe that the strings under "File" and "Edit" are not translated.

### Additional Information

- Operating System: Mac
- Theia Version: 1.43.0

[custom-code-editor.zip](https://github.com/eclipse-theia/theia/files/13823959/custom-code-editor.zip)

**Comment by hyddel** [comment]
@msujew  any thoughts ?

**Comment by msujew** [comment]
@hyddel Do you have the same issue in 1.45 with the new `ServiceConnectionProvider` architecture? It seems to work for me pretty well:

![image](https://github.com/eclipse-theia/theia/assets/4377073/48b7aff6-eb0a-4a76-9318-e8e0e1a3f5c2)

<details>
<summary>Preload module for ServiceConnectionProvider override</summary>

```ts
import { ConnectionSource } from './messaging/connection-source';
import { LocalConnectionProvider, RemoteConnectionProvider, ServiceConnectionProvider } from './messaging/service-connection-provider';
import { ContainerModule, injectable } from 'inversify';
import { WebSocketConnectionSource } from './messaging/ws-connection-source';

@injectable()
export class CustomWebSocketConnectionProvider extends ServiceConnectionProvider {

    constructor() {
        super();
        console.log('=====================loading custom connection provider===============');
    }

}

export default new ContainerModule((bind, _, __, rebind) => {
    const backendServiceProvider = Symbol('backendServiceProvider');
    bind(CustomWebSocketConnectionProvider).toSelf().inSingletonScope();
    bind(backendServiceProvider).toDynamicValue(ctx => {
        bind(ServiceConnectionProvider).toSelf().inSingletonScope();
        const container = ctx.container.createChild();
        container.bind(ConnectionSource).toService(WebSocketConnectionSource);
        return container.get(CustomWebSocketConnectionProvider);
    }).inSingletonScope();
    rebind(LocalConnectionProvider).toService(backendServiceProvider);
    rebind(RemoteConnectionProvider).toService(backendServiceProvider);
});

```

</details>

**Comment by hyddel** [comment]
@msujew we are actually using 1.42.1 where we are seeing this issue. We have tried 1.43.0 to see if the issue is fixed but facing the same issue. I think we cannot upgrade to 1.45.0 because we might have to adjust our customizations and also the timeline does not permit us to migrate to 1.45.0.

Any thoughts on why it is not working in 1.43.0 or 1.42.1 ?

**Comment by msujew** [comment]
@hyddel in your code, you're importing by doing this: 
```ts
import { WebSocketConnectionProvider } from "@theia/core/lib/browser";
```

However, importing from `@theia/core/lib/browser` loads files that expect localizations are already loaded during load time. You need to adjust the import:

```ts
import { WebSocketConnectionProvider } from "@theia/core/lib/browser/messaging/ws-connection-provider";
```

That way you don't accidentally load files that aren't allowed to be loaded yet. The preload is a very special phase in the frontend application lifecycle and requires special care to work correctly.

**Comment by hyddel** [comment]
I have tried that but still facing the same issue.

**Comment by msujew** [comment]
@hyddel It works for me. I've just replaced both imports of the `WebSocketConnectionProvider` and it works as expected:

![image](https://github.com/eclipse-theia/theia/assets/4377073/26fcfa91-1f50-46c5-b702-5a0b0eea8278)
![image](https://github.com/eclipse-theia/theia/assets/4377073/7a0b488a-dfc5-4585-9fa5-2c36d19053f0)

Please ensure that you have no general `@theia/core/lib/browser` import in any of your preload code, even just transitively. It will automatically load code that expects that the localizations are already loaded.

**Comment by hyddel** [comment]
it is working for me too. I have missed to replace the import at one place.
thank you so much.
