### ISSUE TITLE
Spring Boot Tools extension fails to activate on command execution

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse-theia/theia#13241]
The [Spring Boot Tools](https://marketplace.visualstudio.com/items?itemName=vmware.vscode-spring-boot) vscode extension fails to activate on Theia.

There is a command that activates the extension. This command is registered during the extension activation. VSCode is fine to activate the extension just based on the attempt to execute the command based on the command id. However, Theia seems to require the command to be registered already.

**Comment by msujew** [comment]
@BoykoAlex Can you give a bit more context to this issue? Which command fails to execute? Which version of Theia are you using? Theia is supposed to be able to activate a plugin by just invoking any command that the vscode extension declares in its package.json.

**Comment by BoykoAlex** [comment]
@msujew looks like it is a false alarm... I could have sworn i saw this issue about a month ago with Theia BluePrint. I've downloaded TheiaIDE just now (i suppose this is the evolution of the BluePrint) and it seems to work fine when I install the whole pack of Spring Boot Extensions.
