### ISSUE TITLE
Emmet not working for React

### ISSUE THREAD

**Issue by patnan** [eclipse-theia/theia#13247]
### Bug Description:
Emmet not working for React

### Steps to Reproduce:

1.  Add to the seeting file:
     "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    }
}
2. open an jsx/js file and try emmet. Emmet is not triggered.

### Additional Information

- Operating System:
Ubuntu 22
- Theia Version:
Theia IDE

**Comment by JonasHelming** [comment]
Have you installed a VS Code extension, and if so which one?

**Comment by patnan** [comment]
I'm relying on the built in Emmed plugin 
![image](https://github.com/eclipse-theia/theia/assets/19404665/e8174abe-0a78-4640-ac0d-52fdf473c97e)

I'm using Theia IDE v 1.45.0

![image](https://github.com/eclipse-theia/theia/assets/19404665/dc5583f4-00fe-482e-9bd2-50ba1e665391)

I added this to the settings:

    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    }

**Comment by JonasHelming** [comment]
Does it work in VS Code? I have seen several people having problems wit this, e.g. https://stackoverflow.com/questions/50750263/trying-to-use-emmet-with-a-react-app-in-vs-code

**Comment by patnan** [comment]
"unfortunately" it works in VSCode.

**Comment by sgraband** [comment]
I can take a look!
