### ISSUE TITLE
File icons not rendering in the tree view of custom plugins from theia version 1.41.0 to 1.44.0

### ISSUE THREAD

**Issue by hyddel** [eclipse-theia/theia#13251]
### Bug Description:
File icons are not getting loading in the tree view of a custom plugin from theia version: 1.41.0 to 1.44.0. 

### Steps to Reproduce:

1. start theia either through source code or theia blueprint, any theia version from 1.41.0 to 1.44.0
2. install [oci-core](https://marketplace.visualstudio.com/items?itemName=Oracle.oci-core) and [oci-rms extensions](https://marketplace.visualstudio.com/items?itemName=Oracle.rms)
3. Once they are installed, you need an OCI account. you can create an [OCI Free Tier account](https://www.oracle.com/cloud/free/?intcmp=ohp052322ocift)
4. Then under the OCI RMS plugin, expand the resources.
5. Notice that the file icons are not getting loaded from theia versions: 1.41.0 to 1.44..0. They are getting loaded before 1.41.0 and from 1.45.0.
6. After debugging, the result at this [line](https://github.com/eclipse-theia/theia/blob/v1.38.0/packages/core/src/common/message-rpc/rpc-protocol.ts#L212) matches with the result in 1.42.1 but file icons are not getting loaded.

Is it a known bug that got fixed in 1.45.0 ? Curious to know if there is any rendering not happening as expected ?

Below are the screenshots tried on Theia blueprint with theia version: 1.38.0 and 1.42.1
![Screenshot 2024-01-04 141652 (1)](https://github.com/eclipse-theia/theia/assets/109118025/b585d957-61ab-4d9c-a2d5-7d2bd6d788da)
![Screenshot 2024-01-04 142317 (1)](https://github.com/eclipse-theia/theia/assets/109118025/dde6e862-4121-4eb1-9018-342c94167504)

**Comment by JonasHelming** [comment]
@planger Any idea?

**Comment by JonasHelming** [comment]
Potentially related to https://github.com/eclipse-theia/theia/issues/13213

**Comment by JonasHelming** [comment]
@hyddel Could you quickly retest with 1.45 just to be sure?

**Comment by planger** [comment]
No, without debugging into it I unfortunately don't have an idea why we don't see icons here. :-/ Sorry!

**Comment by msujew** [comment]
@hyddel @JonasHelming I assume that this is the same issue as https://github.com/eclipse-theia/theia/issues/13096, which has been resolved with 1.45.0. See also https://github.com/eclipse-theia/theia/pull/13101.

**Comment by hyddel** [comment]
The fix from #13101 did work in theia 1.42.1. Thank you so much.
