### ISSUE TITLE
Regarding No response on Security Bug report 

### ISSUE THREAD

**Issue by Sudistark** [eclipse-theia/theia#13252]
I have reported a security bug here: https://gitlab.eclipse.org/security/vulnerability-reports/-/issues/175
But haven't even recieved an initial response so just wanted to make sure you haven't missed it due to the holiday season

**Comment by vince-fugnitto** [comment]
@Sudistark thank you for the issue, however I believe the link is broken? 
For reporting security vulnerabilities please see [SECURITY.md](https://github.com/eclipse-theia/theia/blob/master/SECURITY.md).

**Comment by Sudistark** [comment]
Hey @vince-fugnitto I think people with reporter role only have the permission to view secuirty reports?
![image](https://github.com/eclipse-theia/theia/assets/31372554/d63617c2-336d-4e0c-90dc-ffaeaeb5d9f3)

**Comment by vince-fugnitto** [comment]
@Sudistark thanks, I believe that the Eclipse Foundation itself will handle the security report and cascade it down to committers once they confirm the issue. The best course of action would be to comment directly on the issue (on GitLab) for updates, especially if it was reported during the holiday season.

**Comment by Sudistark** [comment]
Ok got it, thankyou @vince-fugnitto for the swift responses
