### ISSUE TITLE
Empty VSCode plugin webview editor windows

### ISSUE THREAD

**Issue by bvenreply** [eclipse-theia/theia#13258]
### Bug Description:

VSCode plugin webview editor windows are not displayed correctly. See this screenshot:

![image](https://github.com/eclipse-theia/theia/assets/105274814/e5e23264-85e3-4be4-b2c7-59f4426ea772)

Left is a hello world vsce webview as loaded by current `master`. Right is the same webview after reverting this commit https://github.com/eclipse-theia/theia/commit/72421be24d0461f811a39324579913e91056d7c4

Upon opening the webview this error is logged:
```
2024-01-10T17:16:06.195Z root ERROR [hosted-plugin: 586850] Promise rejection not handled in one second: Error: Unknown Webview: 0917c540-d516-4f59-ace9-bb9fff13c70c , reason: Error: Unknown Webview: 0917c540-d516-4f59-ace9-bb9fff13c70c
With stack trace: Error: Unknown Webview: 0917c540-d516-4f59-ace9-bb9fff13c70c
    at WebviewsMainImpl.getWebview (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:13987:19)
    at async WebviewsMainImpl.$setHtml (http://localhost:3000/packages_plugin-ext_lib_hosted_browser_hosted-plugin_js.js:13917:25)
    at async RpcProtocol.handleRequest (http://localhost:3000/bundle.js:147209:28)
```

### Steps to Reproduce:

This can be reproduced on the Theia browser example. You will also need a sample VSCode extension, I pushed the source code for the one used above [here](https://github.com/bvenreply/helloworld-vsce-webview/tree/master). You can build it with `npm install && npx --yes --package @vscode/vsce vsce package --skip-license --allow-missing-repository`.

- Open Theia
- Install the sample vsce
- Open the command palette and select *Open HelloWorld webview*
- Observe the empty window and error logged in the backend

### Additional Information

- Operating System: `6.1.0-17-amd64 GNU/Linux`
- Theia Version: `master` (https://github.com/eclipse-theia/theia/commit/6a7bd87126e435a84deeda154838f8698ce9f723)
- Browser: Chromium version 119

**Comment by dhuebner** [comment]
I'm facing the same issue and can confirm that reverting https://github.com/eclipse-theia/theia/commit/72421be24d0461f811a39324579913e91056d7c4 solves the problem.

**Comment by JonasHelming** [comment]
@jfaltermeier Could you take a look, please?

**Comment by jfaltermeier** [comment]
Sure, the widget seems to be in the pending map still and `this.widgetManager.getWidgets` does not include pending widgets. I'll look for a fix.

**Comment by jfaltermeier** [comment]
@bvenreply @dhuebner If you have the time, could you please check whether #13265 fixes the issue for you?

**Comment by bvenreply** [comment]
I tested the new code, the issue is fixed on my end. Thank you @jfaltermeier.

**Comment by bvenreply** [comment]
Actually @jfaltermeier, when I wrote the above I'd tested only the "hello world" extension I'd provided as a minimum example, testing the extension that initially prompted the bug report I still se some problems.

The webview editor window is still empty in that case, and in the console I see errors when trying to fetch subresources:
![image](https://github.com/eclipse-theia/theia/assets/105274814/0f85867d-d758-4f31-b9a7-e6aa9547ed00)

There is no more `Unknown Webview` error logged in the backend, in fact there is no error at all except for the 404s in the browser.

Let me know if I can provide any more details. BTW The extension I'm using is proprietary and that is why I have avoided sharing it. If needed I can ask permission to share it, but probably any extension that loads subresources in an editor webview will have the same issue.

I'm also interested in any similar feedback from @dhuebner.

**Comment by jfaltermeier** [comment]
Thanks, I'll have another look. iwas able to create a reproducer. The wrong id seems to be used in the hostname

**Comment by dhuebner** [comment]
@bvenreply 
Sure! I can test the new state with my extension when @jfaltermeier is finished his PR.

**Comment by jfaltermeier** [comment]
I've updated the PR. The initial reproducer and the vs code coding cat example (https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/README.md) are both working + the initial reproducer of https://github.com/eclipse-theia/theia/commit/72421be24d0461f811a39324579913e91056d7c4

If there are still issues, I will open a 2nd PR to revert https://github.com/eclipse-theia/theia/commit/72421be24d0461f811a39324579913e91056d7c4 for now, and work on the further issues in parallel.

**Comment by bvenreply** [comment]
I checked again and I see no more issues on my end. Thank you @jfaltermeier.

**Comment by dhuebner** [comment]
@jfaltermeier 
Just a side note. I saw an other PR that deals with UUIDs https://github.com/eclipse-theia/theia/pull/13255  
Is it something your change needs to be conform to?

**Comment by dhuebner** [comment]
@jfaltermeier 
I tried the version from your branch [issues/13258_empty-webview](https://github.com/eclipse-theia/theia/compare/issues/13258_empty-webview) , everything works good!
