### ISSUE TITLE
Install vsix files from the explorer view

### ISSUE THREAD

**Issue by dhuebner** [eclipse-theia/theia#13269]
### Feature Description:
Right now there is an "Install from VSIX..." menu item in the "Extensions" view.
It would be handy to have a new "Install Extension VSIX" menu item also in the explorer context menu. This entry should only be active when `*.vsix` file is selected. 

<img width="638" alt="Bildschirmfoto 2024-01-12 um 15 40 20" src="https://github.com/eclipse-theia/theia/assets/454322/6492ba3b-2cc6-45a2-9d7b-69b6c0911ed6">

**Comment by dhuebner** [comment]
I could prepare a PR if the community is interested in having this feature.

**Comment by msujew** [comment]
@dhuebner I think that makes sense 👍

**Comment by dhuebner** [comment]
@msujew 
This feature request can be closed as fixed with #13291
