### ISSUE TITLE
theia start --plugins=local-dir:../plugins deletes all folders inside plugins folders

### ISSUE THREAD

**Issue by Shashi0838** [eclipse-theia/theia#13273]
Hi, 

I'm using theia version 1.45.0, and i use theia-plugins, is plugin-packager is outdated, i'm tying to map the compiled plugins to plugins directory.

When i run theia start --plugins=local-dir:../plugins command, its deleting all the folders (plugins) inside the plugins folder except the last one.

Could anyone please help me on this?

-
Thanks

**Comment by msujew** [comment]
Hey @Shashi0838,

can you provide a reproducible example? I cannot reproduce this using our example app in this repo.

**Comment by msujew** [comment]
@Shashi0838 You don't need to reproduce it using the example. We just need some repo/code, where the behavior is reproducible for us to debug what's going wrong.

**Comment by Shashi0838** [comment]
sure @msujew,  I will add a code snippet. meanwhile, would you tell me if there is any way to package the theia-plugins? if not, is it right to copy or symlink the source of the plugins inside the plugins folder?

**Comment by msujew** [comment]
@Shashi0838 I don't think there is an official way to package them. To make them portable, you can just zip it up. Copying or symlinking the plugins is perfectly fine as well.

Note that for general use, it is recommended to develop vscode extensions instead of Theia plugins. They are easier to package, test and deploy (open-vsx).

**Comment by Shashi0838** [comment]
Hi @msujew, looks like it had an issue with the plugins I had, i have created a new project, and it worked as expected. 

closing the issue
