### ISSUE TITLE
doc: coding guidelines don't mention the filtering feature of ContributionProvider

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#13277]
### Bug Description:
The guidelines [discourage the use of @multiInject](https://github.com/eclipse-theia/theia/blob/master/doc/coding-guidelines.md#no-multi-inject) and lists the benefits of `ContributionProvider`, but neglects to mention the filtering feature of that utility.

Will post a PR shortly with the markdown tweak.

**Comment by martin-fleck-at** [comment]
Closed with https://github.com/eclipse-theia/theia/pull/13278
