### ISSUE TITLE
Localization Issue: Commands Not Being Translated to Chinese in Version 1.45.0

### ISSUE THREAD

**Issue by likesubject** [eclipse-theia/theia#13270]
### Description
After updating from version 1.44.0 to 1.45.0, I've encountered an issue where the command labels defined in `common-frontend-contribution.ts` are not being translated into Chinese even when the interface language is set to Chinese.

### Steps to Reproduce
1. Update to version 1.45.0.
2. Switch the interface language setting to Chinese.
3. Observe that command labels such as 'Find', 'Replace', 'Show Next Tab', and 'Show Previous Tab' remain in English instead of being translated.

### Expected Behavior
When the interface language is set to Chinese, all command labels should be displayed in Chinese.

### Actual Behavior
The command labels do not change and are still displayed in English.

### Code Snippet
Here's the relevant code from `core/src/browser/common-frontend-contribution.ts`:

```typescript
export const FIND = Command.toDefaultLocalizedCommand({
    id: 'core.find',
    label: 'Find'
});
export const REPLACE = Command.toDefaultLocalizedCommand({
    id: 'core.replace',
    label: 'Replace'
});

export const NEXT_TAB = Command.toDefaultLocalizedCommand({
    id: 'core.nextTab',
    category: VIEW_CATEGORY,
    label: 'Show Next Tab'
});
export const PREVIOUS_TAB = Command.toDefaultLocalizedCommand({
    id: 'core.previousTab',
    category: VIEW_CATEGORY,
    label: 'Show Previous Tab'
});
export const NEXT_TAB_IN_GROUP = Command.toLocalizedCommand({
    id: 'core.nextTabInGroup',
    category: VIEW_CATEGORY,
    label: 'Switch to Next Tab in Group'
}, 'theia/core/common/showNextTabInGroup', VIEW_CATEGORY_KEY);
These command labels were properly localized to Chinese in the previous version (1.44.0).
```

### Environment
Theia Version: 1.45.0
Platform: Windows10
Possible Solution
N/A

**Comment by msujew** [comment]
@likesubject Have you accidentally installed [this chinese localization](https://open-vsx.org/extension/zhanghua/vscodium-language-pack-zh-cn)? This extension is outdated and is missing a lot of translations that are necessary for Theia. Adopters are recommended to install the [official extension here](https://open-vsx.org/extension/MS-CEINTL/vscode-language-pack-zh-hans) instead.

**Comment by msujew** [comment]
The outdated extension has been unpublished, see https://github.com/EclipseFdn/open-vsx.org/issues/2294. I'll close this.
