### ISSUE TITLE
v1.45.0 Release misses native dependencies breaking Remote SSH Support

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia#13294]
### Bug Description:

Releases should contain the native dependencies as zip file. However 1.45.0 doesn't include them.
See: https://github.com/eclipse-theia/theia/releases/tag/v1.45.0
vs: https://github.com/eclipse-theia/theia/releases/tag/v1.44.0
This file however is required by the [Remote SSH development support](https://github.com/eclipse-theia/theia/pull/12618). See [app-native-dependency-contribution.ts](https://github.com/eclipse-theia/theia/blob/master/packages/remote/src/electron-node/setup/app-native-dependency-contribution.ts).

### Steps to Reproduce:

1. Start v1.45.0 as Electron App
2. Try connecting to an SSH remote
3. Observe how it fails with the message that it can't download the native dependencies into the remote

### Additional Information

- Operating System: All
- Theia Version: 1.45.0

**Comment by msujew** [comment]
I've updated the release to include the binaries.
