### ISSUE TITLE
New File doesn't accept a filename

### ISSUE THREAD

**Issue by profbbrown** [eclipse-theia/theia#13303]
### Bug Description:
Selecting **New File...** from the File menu brings up a selection box prompting the user to "Select file type or enter file name." However, entering a filename doesn't do anything. The box disappears and no new editor is opened.

### Additional Information

- Operating System: MacOS Sonoma, Chrome browser
- Theia Version: 1.45

Extensions loaded:

```@theia/bulk-edit 1.45.0
@theia/callhierarchy 1.45.0
@theia/console 1.45.0
@theia/core 1.45.0
@theia/debug 1.45.0
@theia/editor 1.45.0
@theia/editor-preview 1.45.0
@theia/file-search 1.45.0
@theia/filesystem 1.45.0
@theia/getting-started 1.45.0
@theia/git 1.45.0
@theia/keymaps 1.45.0
@theia/markers 1.45.0
@theia/messages 1.45.0
@theia/metrics 1.45.0
@theia/mini-browser 1.45.0
@theia/monaco 1.45.0
@theia/navigator 1.45.0
@theia/notebook 1.45.0
@theia/outline-view 1.45.0
@theia/output 1.45.0
@theia/plugin-dev 1.45.0
@theia/plugin-ext 1.45.0
@theia/plugin-ext-vscode 1.45.0
@theia/plugin-metrics 1.45.0
@theia/preferences 1.45.0
@theia/preview 1.45.0
@theia/process 1.45.0
@theia/property-view 1.45.0
@theia/scm 1.45.0
@theia/scm-extra 1.45.0
@theia/search-in-workspace 1.45.0
@theia/task 1.45.0
@theia/terminal 1.45.0
@theia/timeline 1.45.0
@theia/toolbar 1.45.0
@theia/typehierarchy 1.45.0
@theia/userstorage 1.45.0
@theia/variable-resolver 1.45.0
@theia/vsx-registry 1.45.0
@theia/workspace 1.45.0
```

**Comment by profbbrown** [comment]
Clicking the small "new file" icon in the Explorer heading prompts for a filename and then opens an editor for it. I expected that the menu item "New File" would do something similar: I'll type in a filename and an editor will open for it.

**Comment by dhuebner** [comment]
@profbbrown @JonasHelming 
PR #13344 is ready for review.
