### ISSUE TITLE
No git status indication in the editor tab 

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#13301]
VSCode colors the file name and adds an indicator on changed files, just like in the navigator. Theia IDE does not:

![image](https://github.com/eclipse-theia/theia/assets/1052615/1cc27953-fa4d-40be-b208-ef78092e1fe8)

### Additional Information

- Operating System: Ubuntu
- Theia Version: 1.45

**Comment by dhuebner** [comment]
Note:
This editor tab behavior is configurable in vs-code:
`workbench.editor.decorations.badges`  to control marker/change indicator
`workbench.editor.decorations.colors` to control tab titel color

**Comment by JonasHelming** [comment]
@dhuebner Are you interested in working on this? This would be a nice addition I think.

**Comment by dhuebner** [comment]
@JonasHelming 
I'm interested, yes. But to be honest I am not sure where to start investigating.
It should be a badge contribution from the git extension similar to the explorer view, but I'm not sure.  
I will definitely spend some time to find it out and report my findings here.

**Comment by dhuebner** [comment]
@JonasHelming 
Now I found it. Thees are `tailDecorations` that need to be contributed within the `ScmTabBarDecorator`. I need to check  whether the tailDecorations are rendered in the Editors tab bar.

So yes, please assign me.

**Comment by dhuebner** [comment]
@JonasHelming 
I got it working, but need to handle all contributed decoration not just SCM. 
Now we can also see the problem marker tail decorations, which is good:
<img width="845" alt="Bildschirmfoto 2024-02-09 um 14 04 13" src="https://github.com/eclipse-theia/theia/assets/454322/3c641cf8-4dff-4aaf-ab68-a63aa0581417">
