### ISSUE TITLE
Pull request 1287 makes PluginSharedStyle.toIconClass() not work in some cases

### ISSUE THREAD

**Issue by jcortell68** [eclipse-theia/theia#13310]
@msujew Are you aware of any regression caused by [this pull request of yours, 12827](https://github.com/eclipse-theia/theia/pull/12827) ?

The addition of `::before` to the selector name causes the resulting icon class to not have effect in some cases. The icon isn't shown. I ran into this with my app. Creating a standalone reproducible case will take some effort. Before I dive into that, I want to make sure that you're not already aware of the issue.

### Bug Description:
TBD

### Steps to Reproduce:
TBD

### Additional Information
- Operating System: Windows
- Theia Version: 1.43.0

**Comment by msujew** [comment]
Hey @jcortell68, yes I am aware of that and this issue has been resolved by https://github.com/eclipse-theia/theia/pull/13101 which is included in Theia 1.45.0. Can you try using that to see whether it resolves the issues you were experiencing?

**Comment by jcortell68** [comment]
Ahh. Glad I asked. Let me see if the change fixes it in my situation. Glad I asked!

**Comment by jcortell68** [comment]
Bingo! It sure does. Thanks!
