### ISSUE TITLE
Disable the submenu, its nodes are still created

### ISSUE THREAD

**Issue by fly-bue** [eclipse-theia/theia#13329]
### Bug Description:

When I disable submenu via `unregisterMenuAction`, its node is still created. see [#4252](https://github.com/eclipse-theia/theia/issues/4252).

Did I miss anything? Please let me know. Thank you first.

![image](https://github.com/eclipse-theia/theia/assets/54001753/4154846d-cf8e-4887-a547-2a356e763fb8).

### Steps to Reproduce:
```ts
// examples\api-samples\src\browser\menu\sample-menu-contribution.ts
export class SampleMenuContribution implements MenuContribution {
    @inject(MenuModelRegistry) protected readonly menuModelRegistry: MenuModelRegistry;
    registerMenus(menus: MenuModelRegistry): void {

        menus.unregisterMenuAction(CommonMenus.VIEW[CommonMenus.VIEW.length - 1], MAIN_MENU_BAR);

    }
}
```

### Additional Information

- Operating System: Windows 11 家庭中文版
- Theia Version: master

**Comment by kittaakos** [comment]
> disable submenu via `unregisterMenuAction`,

A submenu is not a menu action. I expect that API will do something other than what you wish. We use [this](https://github.com/arduino/arduino-ide/blob/dda77701054e748f07d99e191eefb67b60239d5e/arduino-ide-extension/src/browser/menu/arduino-menus.ts#L194-L221) as a workaround downstream to remove submenus. You might need to adjust it for your needs. (Possibly related: #7299 and #7300.)
