### ISSUE TITLE
Shrink bundle by 500Kb with "importHelpers": true typescript setting

### ISSUE THREAD

**Issue by Alexander-Taran** [eclipse-theia/theia#13345]
Typescript emits helper functions into produced js modules depending on features used.
It also has a compiler option  "importHelpers": true 
Which emits something like `import {decorate} from "tslib"` or require equivalent depending on module format.
Size of tslib module is ~16kb

On large codebases source code of emitted helpers per module tends to grow large and it is duplicated code all over the transpiled codebase.

For example: __decorate helper
```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
```
is 563 bytes.
In Theia packages we use to build our IDE it is encountered 952 times which gives us roughly 500kb of minified bundle size for only the decorate helper `copy-pasted` all over.
`@theia` scoped packages contribute 872 of those copies.

### Feature Description:
Please consider taking a dependency on tslib for theia packages and changing `importHelpers` compiler option to `true`
One decorate function is plenty enough for the whole bundle.

**Comment by msujew** [comment]
Sounds pretty reasonable and should be doable without a lot of effort. @Alexander-Taran Are you interested in contributing this change?

**Comment by Alexander-Taran** [comment]
@msujew can make an attempt at it.
Seems like adding tslib to dependencies and modifying the tsconfig.json files would do.
Not familiar with the repo though. So might miss something or overdo somewhere.

Any rules on branch name in the fork?
Commit signing policies?
Been awhile since I created pull requests.

**Comment by Alexander-Taran** [comment]
@msujew I read the contributing guide.
Damn that's too much hassle.
I'll ask one of the colleagues who already summitted patches to create a PR on my behalf.

**Comment by Alexander-Taran** [comment]
@msujew 
Added a non-mergeable pull-request with proposed changes.
base.tsconfig.json - added `importHelpers: true`
Mostly all /packages/**/package.json files have added dependency on tslib
with exception of packages that have no tsconfig, a package with d.ts files only and test package.

I assumed that dev-packages do not need this (needs verification)

**Comment by Alexander-Taran** [comment]
@msujew 
How do we fix `3PP License Check / 3PP License Check (ubuntu-latest, 18.x, 11) (pull_request) ` ?
