### ISSUE TITLE
Performance hit by maybe unneeded double conversion uri->string->uri

### ISSUE THREAD

**Issue by Alexander-Taran** [eclipse-theia/theia#13348]
```ts
this.fetchData(new URI(uri.toString()));
```
https://github.com/eclipse-theia/theia/blob/3e7f6eec297c4029ef01b2ef2c8f20361360c48c/packages/core/src/browser/decorations-service.ts#L81C54-L81C55

Converting to either representation is compute-heavy.
Performed in a tight loop adds significant overhead.

Is there any reason for this double conversion? (From the source of URI I can't find a way to mutate it in "external" code, so maybe it is a possible memory leak you were guarding from). 

One way conversion takes about 63ms on my machine (i7800k @ 3.7GHz).
It is done on main thread which significantly hurts interactivity because decorations might get updated on any keypress.
And debounce 150 does nothing to alleviate the problem when iterating over 2-3 decorations takes more than 150ms just because of this double conversion instead of just passing the uri down the pipe. 

also here:
```ts
    getDecoration(uri: URI, includeChildren: boolean): Decoration[] {
        const data: Decoration[] = [];
        let containsChildren: boolean = false;
        for (const wrapper of this.data) {
            wrapper.getOrRetrieve(new URI(uri.toString()), includeChildren, (deco, isChild) => {
                if (!isChild || deco.bubble) {
                    data.push(deco);
                    containsChildren = isChild || containsChildren;
                }
            });
        }
        return data;
    }
```

**Comment by msujew** [comment]
Probably just some code where the contributor didn't think too much about the performance/it wasn't relevant in their use case. Since URIs are actually immutable (at least per their public API), we shouldn't need the conversion at all there.
