### ISSUE TITLE
WebView Extensions asset load 403 Forbidden

### ISSUE THREAD

**Issue by dineug** [eclipse-theia/theia#13373]
### Bug Description:

WebView Extensions asset load 403 Forbidden

### Steps to Reproduce:

1. install Theia IDE for desktop
2. install [custom-editor-sample vsix](https://github.com/microsoft/vscode-extension-samples/tree/main/custom-editor-sample)
3. create an empty file with a `.pawdraw` extension and open it in Theia IDE.

<img width="545" alt="pawDraw" src="https://github.com/eclipse-theia/theia/assets/45829489/4bab1202-ab63-4918-b697-59f9ee655504">

<img width="545" alt="pawDraw" src="https://github.com/eclipse-theia/theia/assets/45829489/7fb52e71-1892-41b4-b5a6-b009e07ee81b">

In the previous version v1.45.0, it works correctly, but in the latest version v1.46.100, it fails.
For detailed network information, please refer to the `.har` file.
[pawDraw.zip](https://github.com/eclipse-theia/theia/files/14229288/pawDraw.zip)

custom-editor-sample
```ts
const scriptUri = webview.asWebviewUri(vscode.Uri.joinPath(this._context.extensionUri, 'media', 'pawDraw.js'));
```

### Additional Information

- Operating System: Windows11, MacOS
- Theia Version: v1.46.100

**Comment by msujew** [comment]
cc @jfaltermeier assume that this is related to https://github.com/eclipse-theia/theia/pull/13225? It at least very much looks like that.
