### ISSUE TITLE
Uninstall an extension does not deleted the extension from the ".theia/deployedPlugins" folder

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#13379]
### Bug Description:
Hi,

When installing an extension from the OpenVSX store, the extension is installed and extracted into the user .theia/deployedPlugins folder, but when doing uninstall, the extension folder is not deleted from that folder.
Now once restarting Theia, it will re-install all the plugins under that folder, the same plugins that the user has uninstalled before !!!

I checked the Theia source code, and I think the issue is in the setSourceLocationsForPlugin method in the HostedPluginDeployerHandler class. I have created a new CustomHostedPluginDeployerHandler class rebind it instead of the original one and changed the following in that method which fixes the issue: entry.originalPath() --> entry.rootPath

Not sure if this is the correct fix, I opened this ticket is order to have the correct fix in the next Theia versions.

### Steps to Reproduce:

1. install any extension from open vsx store
2. uninstall this extension
3. validate that the extension folder still exists under the user .theia/deployedPlugins folder
4. restart Theia
5. you will see that the extension is installed again

### Additional Information

- Operating System: Mac
- Theia Version: Theia 1.45.1

**Comment by msujew** [comment]
cc @xai possible regression from https://github.com/eclipse-theia/theia/pull/13178?

**Comment by xai** [comment]
Possible! Thanks for pinging, I'll check!

**Comment by xai** [comment]
Hello @safisa,

Thank you for identifying this issue. I was able to reproduce the problem using both extensions from the registry and local .vsix files. Your suggested fix works and seems logical to me, so I have opened a draft PR (#13427) and included a `Co-authored-by` line in my commit to acknowledge your contribution. Is that ok for you?

**Comment by safisa** [comment]
Hi @xai,
Sure, this is OK, and thank you very much.
