### ISSUE TITLE
NPM Support builtin extension: Issue in the Refresh toolbar command

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#13375]
### Bug Description:
Hi,

There is an issue in the builtin vscode NPM support extension, where the refresh command could be added to other tree components like the file explorer and the extensions list.

### Steps to Reproduce:

1. have a project with some package.json files
2. open the npm view
3. expand a package.json item to see its scripts
4. collapse it back
5. you will see that a new refresh icon is added to the navigator tree, also to the whole explorer view, and to the extensions view...
6. if you do inspect on this icon, you will see that it comes from the npm.refresh command

### Additional Information

- Operating System: Mac
- Theia Version: 1.45.1

**Comment by safisa** [comment]
This could be related to the view/title menu contribution.

**Comment by vnfedotov** [comment]
Are there any workarounds for this issue? I've tried multiple ways of rewriting "when" predicate, but it doesn't seem to work.

**Comment by msujew** [comment]
@vnfedotov I assume this is a bug in the update logic of the toolbar renderer. I'm not aware of a workaround and I don't think there is one. Feel free to contribute a PR to fix the issue.

**Comment by tsmaeder** [comment]
@rschnekenbu to quote @msujew 

> @vnfedotov I assume this is a bug in the update logic of the toolbar renderer.

and I tend to agree: why would setting the context key lead to the icons being added to the wrong view?

**Comment by msujew** [comment]
@tsmaeder I believe the erroneous logic is explained pretty well in https://github.com/eclipse-theia/theia/pull/13768. At least it sounds pretty reasonable to me.

**Comment by tsmaeder** [comment]
Hmh...what I mean is this: the context key `view` does not make sense as a global value: "which view is this" is always local. Contrary to `activeViewlet`, etc. The local, scoped context is set, for example in `plugin-view-widget.ts#77`, but it's not using the constant from `view-context-service.ts`. If it's not supposed to be used, shouldn't we at least remove the constant?
