### ISSUE TITLE
Add command to install plugins from the command line

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#13406]
### Feature Description:
VS Code has a command to install plugins from the command line like so:
```
code --install-extension (<extension-id> | <extension-vsix-path>)
```

We should add a command to the Theia command line to do the same.

**Comment by msujew** [comment]
See PR that implements installing plugins via their IDs: https://github.com/eclipse-theia/theia/pull/13369

**Comment by tsmaeder** [comment]
Implementing this functionality the same way as in VS Code encounters a bunch of problems:

1. We cannot tell which plugins are present in the system until the plugins deployment has run as a side-effect of system startup. So doing the "this plugin is already installed" message is not possible before deployment is running
2. Determining the set of plugins in the system and uninstalling is done via "HostedPluginSupport", which is a service that runs in the plugin host and which is not available in the back end, only the front-end. Implementing a cli command in the front-end is not possible, because in the browser case, there may not be a front-end for a long time.

What we _can_ do is install the given version (or the latest version if none is given) unconditionally. I have sketched a change proposal that would allow to handle plugin management more robustly [here](https://github.com/eclipse-theia/theia/issues/13416)
