### ISSUE TITLE
Feature Request: Configurable Splash Screen for Theia Electron

### ISSUE THREAD

**Issue by sdirix** [eclipse-theia/theia#13410]
Splash screens are an often implemented feature as they can improve user experience while also offering a branding opportunity.

In case a splash screen is implemented for a Theia based application, it naturally makes sense to show it until the frontend is fully loaded, i.e. until the loading spinner vanishes. For this, framework support is useful.

Suggested requirements:

- The splash screen support is off by default and must be explicitly configured
- Typical splash screen use cases should be configurable via the package.json
- The splash screen should allow content customization similar to the `preloadContent`
- The splash screen should be displayed as early as possible during startup, with the frontend application loading invisible in the background.
- The splash screen should be hidden once the frontend app is fully loaded, revealing the frontend at the same time

The splash screen configuration could also support the following parameters:
- `minDuration: number`: Minimum duration to show the splash screen, in milliseconds. Defaults to `undefined`, indicating this feature is disabled.
- `maxDuration: number`: Maximum duration to show the splash screen, in milliseconds. Defaults to `undefined`, indicating this feature is disabled.
- `width: number`: Width of the splash screen in pixels. Default value `640`.
- `height: number`: Height of the splash screen in pixels. Default value `480`.

**Comment by msujew** [comment]
@kittaakos Is this still interesting for you guys over at Arduino?

**Comment by tsmaeder** [comment]
We now have a splash screen.
