### ISSUE TITLE
The Chinese internationalization of the right-click menu is incomplete

### ISSUE THREAD

**Issue by zx616456607** [eclipse-theia/theia#13438]
### Steps to Reproduce:

1.Install the Chinese package plug-in in theia.
2.Switch to the Chinese environment.
3.Open a cpp file and right-click in the edit area to see that the Chinese internationalization of the right-click menu is incomplete.
![1](https://github.com/eclipse-theia/theia/assets/19658190/7dc85766-0138-401a-9efb-512a6cc664e0)
![2](https://github.com/eclipse-theia/theia/assets/19658190/40d13abd-3c15-457b-baa4-877b1d96baea)
![3](https://github.com/eclipse-theia/theia/assets/19658190/f5af4038-3bff-4741-bac9-4c41b90005b9)

### Additional Information

- Operating System: Win 10
- Theia Version: 1.41.0
- Editor/LSP plugin: vscode-clangd 0.1.24，Language pack extension for Chinese (Simplified) 1.87.0

**Comment by tsmaeder** [comment]
@msujew
