### ISSUE TITLE
File Explorer keeps revealing selected element

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#13461]
### Bug Description:
Sometimes, when trying to scroll down in the file explorer, the explorer keeps revealing what I believe is the selected element at somewhat regular intervals. This makes it impossible to scroll, as the the system keeps scrolling back up. A workaround is to select an element immediately after scrolling.

### Steps to Reproduce:
I don't have any, but I think @jfaltermeier might have a tentative reproducer scenario.

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by jfaltermeier** [comment]
For me double clicking a file in the explorer and immediately scrolling seems to be a kind of reliable reproducer for me. 
When I don't scroll immediately it seems to be working:

![Peek 2024-03-07 09-49](https://github.com/eclipse-theia/theia/assets/5889696/878d94e5-384a-44c4-9920-ca31d53febb3)

**Comment by tsmaeder** [comment]
Note: `tree-widget.ts` look at `updateScrollToRow()`.

**Comment by tsmaeder** [comment]
Here's my theory: If we look at `tree-widget.ts#doUpdateRows()`, we see that it calls `updateScrollToRow()`, which scrolls to the node that has focus. I assume that the focus node does not change when we scroll down. So when we do a large update of the tree (like when expanding a node that has many children). This update may take enough time to allow us to scroll down the tree before the update is done. On the next call to `doUpdateRows()`, the focus node is revealed, causing the tree to scroll back up.
