### ISSUE TITLE
Formatter removes final newline on package.json

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#13475]
### Bug Description:
The Theia workspace contains a setting to turn on "format on save" for the workspace. This is problematic, since the formatter does not work as intended: if I edit a package.json file, the formatter will remove the final newline. This leads to problems on UNIX-derived platforms.

### Steps to Reproduce:

1. Edit a package.json in the Theia source
2. Save
3. Observe: the formatter removes the final newline.

### Additional Information

- Operating System: Windows
- Theia Version: 1.47.0

**Comment by xai** [comment]
I cannot reproduce this on current master either.

**Comment by tsmaeder** [comment]
@xai are you using the a Theia workspace to test? "Format on save" is turned on in the workspace settings. I just observed this again in the Theia IDE 1.47.100.

**Comment by xai** [comment]
I can reproduce this now.

**Comment by xai** [comment]
Unfortunately, Monaco Editor has no such thing as `editor.action.insertFinalNewline` that we could call.

I opened [a draft PR](https://github.com/eclipse-theia/theia/pull/13751) with a workaround to support the `files.insertFinalNewline` setting.
Also, I feel my current workaround (i.e., the protected function) is somehow in the wrong place. Any suggestions on where it would fit better?

**Comment by tsmaeder** [comment]
Do we understand why the formatter removes the final newline? As far as I can tell, this does not happen in VS Code.

**Comment by xai** [comment]
> Do we understand why the formatter removes the final newline? As far as I can tell, this does not happen in VS Code.

I think it does, see attached screencast.

https://github.com/eclipse-theia/theia/assets/1155551/64e08d34-9c70-49c4-a3d1-e761e8804166

**Comment by xai** [comment]
> I'm sorry, but what am I seeing?

This is vscode (cleaned user data) with a workspace that has formatOnSave enabled (see right pane).

Initially, insertFinalNewline is not set (right pane).
On the first save action, the empty line at the end of the package.json in the left pane is removed automatically.

Then, I enabled the insertFinalNewline setting in the right pane and repeated the experiment with the package.json. The second save does not remove the empty line.

**Comment by JonasHelming** [comment]
@tsmaeder

**Comment by tsmaeder** [comment]
@xai What's the reason the PR is in draft state?

**Comment by xai** [comment]
> @xai What's the reason the PR is in draft state?

>> Also, I feel my current workaround (i.e., the protected function) is somehow in the wrong place. Any suggestions on where it would fit better?

This concern of mine was the reason I kept it in draft state.
