### ISSUE TITLE
List of Theia extensions is missing in AboutDialog in packaged Theia Electron based applications

### ISSUE THREAD

**Issue by sdirix** [eclipse-theia/theia#13481]
### Bug Description:

In packaged Theia Electron based applications the default about dialog does not show the list of contained Theia extensions.

*Note that the [Theia IDE](https://theia-ide.org/#theiaidedownload) uses a customized about dialog and therefore the problem is not visually apparent.*

### Steps to Reproduce:

1. Build the Theia Browser example app
2. Delete the `node_modules` directory (it's not required as the backend is bundled by default)
3. Run the example app (`node examples/browser/lib/backend/main.js`)
4. Open the about dialog

![image](https://github.com/eclipse-theia/theia/assets/8998368/1dbefdc7-a010-40d8-b3f2-61921bf33111)

You can also reproduce this with the Theia Electron example app, however you need to keep all Electron related dependencies in `node_modules` as they are not bundled with Theia.

The issue typically occurs in packaged Theia Electron based applications as publishers no longer package `node_modules` since the backend bundling was introduced.

In development environments and in Docker images the `node_modules` are usually present, thereby the error does not manifest then. However in theory the `node_modules` could also not be present, as shown in the reproduction steps.

### Analysis

* [The dialog requests the information from the `AppServer`](https://github.com/eclipse-theia/theia/blob/9ff0cedff1d591b0eb4be97a05f6d992789d0a24/packages/core/src/browser/about-dialog.tsx#L64)
* [The `AppServer` receives the information from the injected `ApplicationPackage`](https://github.com/eclipse-theia/theia/blob/9ff0cedff1d591b0eb4be97a05f6d992789d0a24/packages/core/src/node/application-server.ts#L29)
* [The `ApplicationPackage` is created by the `backend-application-module`](https://github.com/eclipse-theia/theia/blob/9ff0cedff1d591b0eb4be97a05f6d992789d0a24/packages/core/src/node/backend-application-module.ts#L104-L108)
* [The `ApplicationPackage` uses the `ExtensionPackageCollector`](https://github.com/eclipse-theia/theia/blob/9ff0cedff1d591b0eb4be97a05f6d992789d0a24/dev-packages/application-package/src/application-package.ts#L106-L116)
* [The `ExtensionPackageCollector` walks through the fileystem and tries to collect `package.json` files](https://github.com/eclipse-theia/theia/blob/9ff0cedff1d591b0eb4be97a05f6d992789d0a24/dev-packages/application-package/src/extension-package-collector.ts)

As the extension information comes through the collector, it fails if the packages are not available, i.e. in the case the backend is bundled and the `node_modules` removed. Notably the `ApplicationPackage` as well as the `ExtensionPackageCollector` are actually coming from the `dev-packages`, so it can be argued they should not be used at all in Theia itself.

### Potential solution

The Theia extension information is already collected during the build process. So instead of re-discovering this information with the tools of `dev-packages` at runtime, the information could be included in src-gen instead.

**Comment by rschnekenbu** [comment]
This can be addressed at generation time, in the [backend-generator.ts](https://github.com/eclipse-theia/theia/blob/c2b0704669fa3e4b399bc6f13b7fac89730012c2/dev-packages/application-manager/src/generator/backend-generator.ts#L152) 
we could set the information in the backend application when it is started. We should have access to this information at that time as we can access the application package.

It will be interesting to also check where this information is also used. Maybe same issue could be seen here, and getting rid of the `dev-package` dependency may be good within the application.
