### ISSUE TITLE
Overflow behavior for sidepanels not working correctly

### ISSUE THREAD

**Issue by tortmayr** [eclipse-theia/theia#13482]
### Bug Description:
For certain corner cases the tab overflow behavior for sidebars introduced with #12593 is not working correctly:

- The overflow behavior does not work as expected if only two tabs are in the tabbar (and none are hidden via '...' menu)
- The last visible element never gets added to the `...` menu even if there is not enough space to show it. 
Overflow computation does not consider potential custom styling. Eg. if additional margin between icons are added in an adopter project the overflow calculation will be off.

**Comment by tsmaeder** [comment]
I don't really understand what the problem here is. For me, this seems to work just fine: any view that is hidden is added to the `...`-menu. Steps, please?

**Comment by tsmaeder** [comment]
@tortmayr

**Comment by tsmaeder** [comment]
@tortmayr ping.
