### ISSUE TITLE
Unable to Add Extensions 1.47.100

### ISSUE THREAD

**Issue by saravananmanigandan** [eclipse-theia/theia#13494]
Theia IDE: Version 1.47.100
VS Code API Version: 1.86.2

When i try to add Extensions(ex : Spring boot tools) it keeps saying Installing.
Gitlense -> Gitlense extension window not showing once i reopen the window.

![image](https://github.com/eclipse-theia/theia/assets/150358168/cbb10b5b-03f2-47cd-8965-bc359ca723df)

Before Install:
![image](https://github.com/eclipse-theia/theia/assets/150358168/ff77af22-b2ec-4646-a8a3-489f2b9a492c)
![image](https://github.com/eclipse-theia/theia/assets/150358168/bf358454-3583-48ed-b802-e82a9aafc443)

After Reopening the workspace:
![image](https://github.com/eclipse-theia/theia/assets/150358168/1a92f24d-4561-4610-ba1c-d819b11835e2)

**Comment by tsmaeder** [comment]
I just uninstalled/installed gitlens with no problems. Can you give concrete steps to reproduce? What OS are you on?

**Comment by tsmaeder** [comment]
Installing Spring Boot Tools worksa as well for me. It just takes a while to download and install (1-2 minutes)

**Comment by tsmaeder** [comment]
Also, could you provide any relevant info from the browser and console log?

**Comment by saravananmanigandan** [comment]
After One hour still showing as installing.
https://github.com/eclipse-theia/theia/assets/150358168/874b226a-dd77-486c-94da-42a32755c9e4

after reopening the IDE
https://github.com/eclipse-theia/theia/assets/150358168/79c9c24c-58c5-4c27-8984-8968d8c5b369

**Comment by saravananmanigandan** [comment]
how do i find the logs from TheiaIDE i do not find the progress Ends

**Comment by tsmaeder** [comment]
@saravananmanigandan the video shows the "Spring Boot Extension Pack", not the "Spring Boot Tools". Do they both exhibit the same behaviour for you?

You can open the developer tools via the help menu. Also, you can start TheiaIDE.exe from the command line to see console output. What do you have in `<home>\.theia-ide\deployedPlugins`?

**Comment by saravananmanigandan** [comment]
This is what i have in it

**Comment by saravananmanigandan** [comment]
I am closing this issue Since IDE Shows the plugin After closing it for a while.
i will raise bug with proper details once i find issues.
