### ISSUE TITLE
The IDE cannot use the terminal in the Windows 7 environment.

### ISSUE THREAD

**Issue by fanyipin** [eclipse-theia/theia#13508]
### Bug Description:
When I packaged the IDE as an exe to run in windows7, I found that the terminal did not work properly. I see the following error in the console:
1. cannnot find module ‘./build/Debug/pty.node’
2. node-loader: Error: The specified procedure could not be found

I debugged the code and found that error  was because build/release/pty.node was not loaded properly. The reason for this error is that winpty.dll and winpty-agent.exe are not loaded properly (these two files are placed in the lib/build/Release directory). The location of pty.node is lib/backend/native. After I manually move the two files to lib/backend/native, the terminal can run normally in windows7.

I noticed that the file copy logic above is in the @theia/native-webpack-plugin copyNodePtySpawnHelper method, and I was wondering if this method should be windows environment specific, and then targetDirectory should be different. You can't copy everything to lib/build/Release. spawn-helper in lib/build/Release in macos is normal.
Or is there any other solution？

By the way, in order to run under windows7,  my electron version is 22.x

### Additional Information

- Operating System: windows7
- Theia Version: 1.46.1

**Comment by msujew** [comment]
Support for Windows 7 has been dropped by Microsoft back in 2020. I'm honestly suprised that Theia even starts on Windows. Unfortunately, there's little we can do to change how node-pty works. It is an external dependency by Microsoft themselves.

Our copying logic is definitely correct and works as expected on Windows 10 and upwards. The error you're seeing is likely related to a native function call that doesn't exist on Windows 7. You can try disabling the backend bundling if your don't trust it, but it probably won't change anything.

**Comment by fanyipin** [comment]
> Support for Windows 7 has been dropped by Microsoft back in 2020. I'm honestly suprised that Theia even starts on Windows. Unfortunately, there's little we can do to change how node-pty works. It is an external dependency by Microsoft themselves.
> 
> Our copying logic is definitely correct and works as expected on Windows 10 and upwards. The error you're seeing is likely related to a native function call that doesn't exist on Windows 7. You can try disabling the backend bundling if your don't trust it, but it probably won't change anything.

Oh, all right. Then I will copy the file to the next copy of native through the script after webpack processing, so that it can be used normally under windows7. In addition, when I debug windows10, I find that windows10 uses conpty.node, and only windows7 uses pty.node. winpty.dll and winpty-agent.exe are used by pty.node, not windows10. Please confirm this problem when there is time.
