### ISSUE TITLE
Vscode extension LaTeX Workshop's Viewer does not open in Theia IDE in browser 

### ISSUE THREAD

**Issue by dannaf** [eclipse-theia/theia#13522]
### Bug Description:

The [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) vscode extension's Viewer does not work on [Theia IDE](https://github.com/eclipse-theia/theia-blueprint) in the browser.

(I considered opening this as a Discussion but decided on an Issue/Bug because this involves a vscode extension working in vscode but specifically not working on Theia.  I downloaded the extension on vscode locally and the extension's Viewer did open, so it seems that the problem has to do with Theia.  Moreover, while [the LaTeX Workshop vscode extension does not officially support Eclipse Theia](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ#eclipse-theia-is-not-supported), Theia does aim to support vscode extensions. So I can still expect that this extension should fully work on Theia, including on Theia IDE &mdash; correct?)

### Steps to Reproduce:

1. Run [Theia IDE](https://github.com/eclipse-theia/theia-blueprint) in the browser.
2. Install the [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop) vscode extension (and refresh the browser page).
3. Navigate in the Explorer to folder containing a latex file and its corresponding compiled pdf.  Open the latex file in the Editor.
4. Click on the extension's View LaTeX PDF file button <img style="display: inline;" src="https://github.com/eclipse-theia/theia/assets/1812425/433d3a5d-f5e0-4964-a67f-982eb900b8d6" width="30px"></img> at the top-right of the editor (or select this action via the command palette). (Or, select any of the extension's other actions beginning with "View LaTeX PDF" from the command palette &mdash; none of them worked for me.)
7. Expect to see the extension's Viewer open, and observe that it does not open.  (Compare to vscode where it does open.)

### Additional Information

This question is related to https://github.com/eclipse-theia/theia/discussions/7988, but that discussion was never answered (and in any case seems outdated, perhaps even dating to before Theia implemented vscode extensions at runtime?), so I would like to restart this discussion. Moreover, that is not the exact issue that I have. For me the LaTeX Workshop's Viewer is not even opening.

### System Information

- Operating System that Theia IDE is running on: Ubuntu 24.04
- Operating System that Theia IDE is accessed via: outdated Chrome Version 96.0.4664.110 on outdated macOS 10.15.7
- Theia Version: Version 1.46.1 (VS Code API Version: 1.85.1)

**Comment by JonasHelming** [comment]
@dannaf Could you quickly retest this with the latest Theia IDE desktop version? https://theia-ide.org/#theiaide

**Comment by dannaf** [comment]
Same issue, essentially: the extension's Viewer did not open for me upon clicking the View LaTex PDF file button at the top-right of the Editor.

However, when trying all the four command palette actions that the extension provides, the `View LaTeX PDF file in external viewer` command worked (it opened the PDF file in `Preview`) and the `View LaTeX PDF file in web browser` worked (it opened `Chrome` in what appears to me to be a version of pdf.js specific to the LaTeX Workshop, with the extension's icon, at the url http://localhost:54496/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRlVzZXJzJTJGTmFmdHklMkZFbGlqYWgtcGV0aXRpb24lMkZtYWluLnBkZg).  (I was not currently able to test the SyncTeX feature of this web viewer because I do not have LaTeX on my local machine &mdash; I'm trying to do everything on a remote server and generally access it only via the Theia IDE browser application.)

**Comment by dannaf** [comment]
Actually the `View LaTeX PDF file in web browser` command palette action also did something for me via Theia IDE in the browser.  (I am not sure what happened when I opened this issue, as I thought I had tried that and it didn't work, but now when I tried again it opened.) I was not able to test it yet due to my particular networking setup, but at least something opened at a url like I mentioned above.

The main bug that this issue represents is still open, however, because the main in-Theia Viewer that the extension implements is not working, neither in Theia IDE via the browser or via the desktop application.

**Comment by yuhorun** [comment]
look  chrome  console  after  click  'view in tab'

**Comment by tsmaeder** [comment]
Opening a pdf file in the latex workshop viewer works for me in 1.48.0. Please comment if you still have an issue.

**Comment by JonasHelming** [comment]
FYI, preview is available here: https://download.eclipse.org/theia/ide-preview/1.48.0/

**Comment by yuhorun** [comment]
> FYI, preview is available here: https://download.eclipse.org/theia/ide-preview/1.48.0/
i met the same problem, how could i update this in my project.

**Comment by yuhorun** [comment]
1.48.2 not works for me, chrome console show: maximum call stack exceeded error.
@dannaf We have the same problem. Did you solve it?
![Screenshot from 2024-04-04 14-01-16](https://github.com/eclipse-theia/theia/assets/45552382/36edf2e4-d82d-4e72-9fab-8db85924d570)

**Comment by tsmaeder** [comment]
@yuhorun obviously, we're doing something differently, because opening a pdf file works for me. Can you give exact steps what you are doing so we can figure it out?

**Comment by yuhorun** [comment]
@tsmaeder 

Thank you for your attention and contribution, my operation is as follows:
1. download the theia-1.48.2 source code, decompress it, and run yarn && yarn download:plugins && yarn browser build && yarn browser start
2. Go to http://localhost:3000/ and install the james-yu.latex-workshop extension
3. Open the latex source code, compile the output pdf file, and click the preview button on the top right
4.chrome console output: Error during encoding: 'Maximum call stack size exceeded'

I recorded a video reproducing the error.

os: ubuntu22.04
james-yu.latex-workshop: 9.19.1

https://github.com/eclipse-theia/theia/assets/45552382/4113b58c-6c51-4507-9d34-99b13ed08931

**Comment by tsmaeder** [comment]
@yuhorun can you open a pdf file from the navigator view if you already have it in the workspace?

**Comment by yuhorun** [comment]
yes, i can open a pdf file from the navigator view if i already have it in the workspace.

I re-uploaded the video to recreate the problem, and if you still can't open it, please play it on google Cloud Drive: 
 [https://drive.google.com/file/d/1kO1MlyKdkEttvdqZWp94cw29GsQNGKwL/view](url)

[issue.webm](https://github.com/eclipse-theia/theia/assets/45552382/80c935c2-cfad-47f4-a67b-1d082e28506f)

**Comment by madmini** [comment]
@tsmaeder Please reopen this. I'm experiencing the same issue in 1.49.1 and 1.50.0 preview.

Error message is: `Uncaught (in promise) Error: Command with id 'workbench.action.focusLeftGroup' is not registered.` (each time I try _View LaTeX PDF File_) and `Error during encoding: 'Maximum call stack size exceeded'` (only the first time). This matches the output described and shown above.

**Comment by madmini** [comment]
@tsmaeder The [LaTeX Workshop Requirements](https://github.com/James-Yu/LaTeX-Workshop/wiki/Install#requirements) section lists _TeX Live_ as recommended among possible alternative LaTeX distributions. I have tested with _TeX Live Full_ (comes at ~8gb install size and took >1h to install) on Windows 11 which (for reference) plays nicely with LaTeX Workshop in VSCode (1.90.0). I believe this issue is independent of the choice of latex distribution, though.

The LaTeX Workshop comes with a [_Build LaTeX project_](https://github.com/James-Yu/LaTeX-Workshop/wiki/Compile) button (play icon, see also @yuhorun's video) for automagic compilation.

**Comment by humphreylee** [comment]
Bumped.  Encountered same issue with Theia IDE ver. 1.52.0

**Comment by humphreylee** [comment]
Even the "SNIPPET VIEW" is broken. 
![image](https://github.com/user-attachments/assets/d7563782-e772-479d-9049-d5e45cd9323b)

**Comment by tsmaeder** [comment]
I believe this is a programming error in the LaTex Workshop extensions. Turns out the extension invokes `vscode.fs.stat(uri)`, but what it does (in pseudocode) is this:
```
const uri= Uri.file('path/to/file.pdf`);
const statFunction = vscode.workspace.fs.stat;
statFunction(uri)
`` 
Invoking the function in this way, the `this` variable inside the stat method is unbound and we get an error when the method tries to access instance variables off `this`. The extension interprets this as the pdf file not existing (which it prints to the output view).
This works in VS Code by accident because the FS instance is constructed in a way that does not require `this` to be defined.
Note that the API documentation clearly refers to `stat` as a "method", not a function (https://code.visualstudio.com/api/references/vscode-api#FileSystem).

Note that the corresponding VS Code implementation was done in https://github.com/microsoft/vscode/pull/115530, with the purpose of hiding the main-side proxies from the API consumers and the side effect of the `FileSystem` methods working without a `this` value. Maybe it's a good idea to do a similar refactor in Theia? @msujew @JonasHelming  thoughts?

**Comment by tsmaeder** [comment]
>  I would also think of the vscode API methods as functions that don't require a this context.

Namespaces have functions, but objects have methods. The VS Code doc explicitly distinguishes between the two 🤷

**Comment by tsmaeder** [comment]
The thing is, we'd have to refactor every interface instance we return and every class defined in the VS Code API. Not sure that's worth it for enabling what is basically a programming error.

**Comment by humphreylee** [comment]
I wanted to file an issue in LaTeX Workhop, but unfortunately Theia is [not officially supported](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ).

**Comment by tsmaeder** [comment]
@msujew invoking an object _method_ as a pure _function_ is a programming error. The equivalent in your example would be this:
```
import * as fs from 'node:fs';

const bla= fs.stat;
bla('/usr/bin/ls');
```
That might or might not work.

**Comment by tsmaeder** [comment]
>I wanted to file an issue in LaTeX Workhop repo, but unfortunately Theia is [not officially supported](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ).

They might still want to know about this. "Does not support" does not mean they are actively trying to be incompatible.

**Comment by tsmaeder** [comment]
Another problem is that if we rewrite the api objects we would have to make sure we convert them properly when sending stuff over the ext/main interface. The VS Code style is that they create a proxy object that has only getters/setters referring to some "original" object. Sending such an object will typically send an object without any properties.

**Comment by humphreylee** [comment]
LaTeX Workshop ver. 10.4.0 seems have fixed the issue opening the PDF in another tab (of TheiaIDE desktop) and web browser.
