### ISSUE TITLE
Feature Request: Add Support For 256 Truecolor

### ISSUE THREAD

**Issue by TigerC10** [eclipse-theia/theia#13523]
### Problem Statement:
Opening TheiaBlueprint on my MacOS, I've noticed some odd colors.  It seems Theia launches terminals with only 8 colors?
```shell
$> print $terminfo[colors]
8

$> echo $COLORTERM

```

### Feature Description:
Start the terminal with support for 256 TrueColor the way that VSCode does.

![image](https://github.com/eclipse-theia/theia/assets/247711/60a11055-8828-4a10-abba-1aa3024dcda8)

<br/>This also affects the web version of Theia.

<img width="1971" alt="image" src="https://github.com/eclipse-theia/theia/assets/247711/2f79918a-5469-4f77-8d5f-2c7c7f316c8d">

<br/>_Originally posted by @TigerC10 in https://github.com/eclipse-theia/theia/discussions/12890_

**Comment by TigerC10** [comment]
Interestingly, it seems that 256 colors is actually supported without issue.  It may just be the shell/environment variables that aren't populated.  That's getting the way of color support validation in the CLI tools.

```shell
curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/e50a28ec54188d2413518788de6c6367ffcea4f7/print256colours.sh | bash
```

<img width="1973" alt="image" src="https://github.com/eclipse-theia/theia/assets/247711/ad85f77c-07ed-4993-a080-42c4c3e87309">


<img width="1975" alt="image" src="https://github.com/eclipse-theia/theia/assets/247711/9af00b5a-2775-4136-881f-f57594cfc0f7">

**Comment by sgraband** [comment]
I can take a look.
