### ISSUE TITLE
vscode.env.openExternal opens a given file in Theia rather than in an external app

### ISSUE THREAD

**Issue by chroberino** [eclipse-theia/theia#13535]
### Bug Description:
I guess `vscode.env.openExternal` in Theia should do the same as in VS Code, i.e. use the OS' default application for opening a given URI. I was trying to use this call in a VS Code extension and observed that in Theia files are always be opened within Theia (while in VS Code they open in external apps).

### Steps to Reproduce:
1. Create a VS Code extension:
   - In `package.json` of your VS Code extension create a command like
            ```{
                "command": "myextension.open-in-external-app",
                "title": "Open in External App"
            }```
   - Implement this command by invoking `vscode.env.openExternal`, aiming to open the currently chosen file in its default app (as configured in the OS).

2. When using your VS Code extension in Theia select a file in the Explorer and pick the "Open in External App" command from the command palette
3. Unexpectedly, the file will be opened within Theia, not in an external app.

As an easy alternative (without any coding efforts) you could also reproduce this issue with the [Open in External App](https://open-vsx.org/extension/YuTengjing/open-in-external-app) extension: If you don't give it any specific configuration, it will utilize `vscode.env.openExternal` striving to open a given file URI in its default application. However, the result is the same as described above, the file will not be opened in an external app but within Theia.

<!-- Please provide any additional information available. -->
<!-- Additional information can be in the form of logs, screenshots, screencasts. -->

### Additional Information

- Operating System: Windows 10
- Theia Version:
  - I have tried with the follwing two:
    - Download of ready-made Eclipse Theia IDE 1.47.100 (https://theia-ide.org/#theiaidedownload)
    - Self-built Electron app from Eclipse Theia 1.45.0 sources

**Comment by dhuebner** [comment]
@chroberino 
Are you also missing the "Open in External App" file browser menu contribution after installing  Open in External App extension? 
I see the command in the palette, but not the menu entry...

**Comment by dhuebner** [comment]
Right now `theia.env.openExternal()` is called when the  `vscode.env.openExternal`  is triggered.  This calls `windowStateExt.openUri(uri)` and its current implementation just redirects to the `opener-service.ts` without providing any further information except the URI. The only handler that matches is the EditorPreview so the file is opened in Theia. I also didn't found a registered handler that can call external applications. In electron case such a handler should probably call `shell.openPath(fsPath)` to redirect to the OS editors.

**Comment by dhuebner** [comment]
Maybe we could also offer `Open With... -> System Editor` in Theia?

**Comment by chroberino** [comment]
> @chroberino Are you also missing the "Open in External App" file browser menu contribution after installing Open in External App extension? I see the command in the palette, but not the menu entry...

It's the same for me: I don't get this item in the context menu but only the entry in the command palette.
I have already created an issue for this: https://github.com/tjx666/open-in-external-app/issues/63

**Comment by dhuebner** [comment]
@chroberino 
Okay, thanks! I will check why the contribution doesn't work.

**Comment by dhuebner** [comment]
@chroberino 
Yes, it looks like Theia is missing context key handling for `isFileSystemResource`

**Comment by JonasHelming** [comment]
@dhuebner Is this solved with your PR?

**Comment by dhuebner** [comment]
@JonasHelming 
Yes, should be fixed. To check, try the new 'System Editor' opener in Theia electron.
