### ISSUE TITLE
hashicorp.terraform extension not working // wrong platform chosen when installing from open-vsx

### ISSUE THREAD

**Issue by jfaltermeier** [eclipse-theia/theia#13558]
### Bug Description:

I have a project with this recommendation in `.vscode/extensions.json`

```
{
    "recommendations": [
        "hashicorp.terraform"
    ]
}
```
The extension can be installed as expected, however it then fails when it tries to launch the language server.

![ksnip_20240403-125512](https://github.com/eclipse-theia/theia/assets/5889696/6293fc5c-ba9a-4dcc-b83c-5e38db506c2d)

I can see in the logs that the wrong platform is downloaded (darwin-arm64 instead of linux-x64):

```
2024-04-03T10:52:35.275Z root INFO [hashicorp.terraform]: resolved to 'hashicorp.terraform-2.29.5'
2024-04-03T10:52:35.276Z root INFO [hashicorp.terraform-2.29.5]: trying to download from "https://open-vsx.org/api/hashicorp/terraform/darwin-arm64/2.29.5/file/hashicorp.terraform-2.29.5@darwin-arm64.vsix"... to path /home/johannes/.theia/tmp/vscode-download
2024-04-03T10:52:36.755Z root INFO [hashicorp.terraform-2.29.5]: downloaded to /home/johannes/.theia/tmp/vscode-download/hashicorp.terraform-2.29.5@darwin-arm64.vsix"
```

I don't know if Theia detects the wrong platform or if there is a misconfiguration on open-vsx that leads to the wrong platform. 

### Steps to Reproduce:

1. Install `hashicorp.terraform`
2. After installation it should try to launch the server which will fail

### Additional Information

- Operating System: Ubuntu 22.04
- Theia Version: 1.48.2

**Comment by msujew** [comment]
> I don't know if Theia detects the wrong platform or if there is a misconfiguration on open-vsx that leads to the wrong platform.

FYI, I don't think that Theia respects the current platform at all - it just chooses the first download link it can find on open-vsx for the respective version of a plugin and tries to install that. See also here:

https://github.com/eclipse-theia/theia/blob/86bac3e4c153344c1c6d2a9463d05f123dfe454b/packages/vsx-registry/src/node/vsx-extension-resolver.ts#L55-L63

It should use the `targetPlatform` parameter available [here](https://open-vsx.org/swagger-ui/index.html#/registry-api/getQuery), but it doesn't.

**Comment by JonasHelming** [comment]
@xai Do you have an idea how to fix this?

**Comment by msujew** [comment]
@JonasHelming @xai I have a [WIP branch](https://github.com/eclipse-theia/theia/tree/msujew/ovsx-api-v2) that is supposed to address this. I'll get back to this in the coming days.

**Comment by msujew** [comment]
@JonasHelming see https://github.com/eclipse-theia/theia/pull/13825
