### ISSUE TITLE
Language pack install via `Configure Display Language` command broken

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#13556]
### Bug Description:

After https://github.com/eclipse-theia/theia/pull/13421 the arguments of the `VSCodeExtensionUri.fromId` method has changed without adapting the [caller site](https://github.com/eclipse-theia/theia/blob/627dad406f4562f7ec7676722d2a384ed997dd0a/packages/vsx-registry/src/browser/vsx-language-quick-pick-service.ts#L75). This results in an invalid URI that doesn't lead to a valid extension.

### Steps to Reproduce:

1. Run the `Configure Display Language` command
2. Select a language that isn't installed yet.
3. Observe the error message in the console: `Uncaught (in promise) Error: Deployment of extension with ID vscode-extension://vscode-language-pack-zh-hans/MS-CEINTL failed.`

### Additional Information

- Operating System: All
- Theia Version: Every commit after https://github.com/eclipse-theia/theia/pull/13421

**Comment by tsmaeder** [comment]
The URI that is being requested is  `https://open-vsx.org/api/-/query?extensionId=vscode-language-pack-de&extensionVersion=MS-CEINTL&includeAllVersions=true`. You get a 400 error on this uri. Note that the uri is not correct.
