### ISSUE TITLE
In the SelectComponent the dropdown is not visible when it is opened above the component

### ISSUE THREAD

**Issue by SIE-DII** [eclipse-theia/theia#13605]
### Bug Description:
In the SelectComponent the dropdown is not visible when it is opened above the component. It works when it's displayed below the component. I assume it's due to the changes in https://github.com/eclipse-theia/theia/issues/12895. When changing the CSS in DevTools to not include position : fixed it's displayed as it should.

### Steps to Reproduce:

1. Open Preferences
2. Scroll to "Editor Render Whitespace" for it to be at the bottom of the page
3. Try to open the dropdown
4. Scroll further until the "Editor Render Whitespace" is in the middle of the page
5. Try to open the dropdown again

### Additional Information

- Operating System: Windows 11
- Theia Version: 1.48.3

**Comment by msujew** [comment]
Hey @SIE-DII,

can you give a bit more context? What kind of popup are you talking about?

**Comment by SIE-DII** [comment]
I am sorry. My ticket did not give you enough context. I added more information.

**Comment by Luke-zhang-04** [comment]
This is still a problem on 1.54, the calculation for the bottom value is wrong. I'll open a PR.


https://github.com/user-attachments/assets/2f2ce41b-d79f-4f47-b5a4-21463477d36f
