### ISSUE TITLE
`vscode.chat.registerMappedEditsProvider` not implemented but used in `typescript-language-features` 1.88.1

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#13649]
### Bug Description:
When I start up `typescript-language-features@1.88.1`, I get an exception , because `chat.registerMappedEditsProvider` is not defined. 

Note that the error seems to have no untoward consequences, so maybe we can just ignore it.

### Steps to Reproduce:
Start up Theia and observe the log

### Additional Information

- Operating System:
- Theia Version: 1.48.0 master

**Comment by JonasHelming** [comment]
@rschnekenbu FYI
