### ISSUE TITLE
Add the same message. This message is not displayed at the top of the notification window.

### ISSUE THREAD

**Issue by baoqing1124** [eclipse-theia/theia#13661]
### Discussed in https://github.com/eclipse-theia/theia/discussions/13659

<div type='discussions-op-text'>

<sup>Originally posted by **baoqing1124** April 29, 2024</sup>
When the notification window is opened and the same message is added, there are no new messages in the window and the latest message is not moved to the top. What should I do to display the latest message at the top?

https://github.com/eclipse-theia/theia/assets/15626996/00c877d8-9be5-4d0e-be03-675de24a6d7c

</div>

**Comment by msujew** [comment]
@baoqing1124 FYI I've opened https://github.com/eclipse-theia/theia/pull/13668 to resolve this some time ago, I'm just waiting for a review. Can you confirm that the PR exhibits the behavior you're expecting?

**Comment by baoqing1124** [comment]
> @baoqing1124 FYI I've opened #13668 to resolve this some time ago, I'm just waiting for a review. Can you confirm that the PR exhibits the behavior you're expecting?
@msujew hi~ I tried your branch, this branch can solve this problem, when I add the same information it will appear at the top.
thanks a lot~
