### ISSUE TITLE
BrowserFS Deprecated

### ISSUE THREAD

**Issue by dr-vortex** [eclipse-theia/theia#13682]
Hi there, I'm the maintainer of BrowserFS. I've been going through the dependents of browserfs.

Please see https://github.com/browser-fs/NOTICE

Would you be interested in updating your project to use the updated fork, [ZenFS](https://github.com/zen-fs/core)?

**Comment by msujew** [comment]
Hey @dr-vortex, I believe you already opened an issue for this, https://github.com/eclipse-theia/theia/issues/13520. We plan to upgrade probably sometime soon. `browser-fs` is currently used in a WIP feature, so we're not in a hurry.

**Comment by dr-vortex** [comment]
@msujew Sorry, with the sheer volume of dependents, I can't easily keep track of which ones I've already opened an issue on.

**Comment by james-pre** [comment]
@msujew I've updated my GitHub username from @dr-vortex to @james-pre. Please update your comment, and I can delete this one. I'm writing this comment when I can't make the change myself.
