### ISSUE TITLE
 Failed to customize the data folder

### ISSUE THREAD

**Issue by fanyipin** [eclipse-theia/theia#13700]
### Bug Description:
Prior to version 1.44, the ConfigDirUri variable could be customized via process.env.THEIA_CONFIG_DIR. This meant users could set process.env.THEIA_CONFIG_DIR within their application to specify a custom data directory. However, after the introduction of the logic in the app directory in version 1.44, process.env.THEIA_CONFIG_DIR is being re-assigned, which seems to override previous settings. I understand that there should be a priority order where:

1. User-defined settings take precedence,
2. Followed by application-specific settings if defined,
3. Lastly, defaulting to the standard THEIA directory if neither is provided.

Here is the logical code for handling ConfigDirUri, which I understand should not be specified directly if process.env.THEIA_CONFIG_DIR has a value
```
protected async createConfigDirUri(): Promise<string> {
      const dataFolderPath = join(BackendApplicationPath, 'data');
      const userDataPath = join(dataFolderPath, 'user-data');
      const dataFolderExists = this.pathExistenceCache[dataFolderPath] ??= await pathExists(dataFolderPath);
      if (dataFolderExists) {
          const userDataExists = this.pathExistenceCache[userDataPath] ??= await pathExists(userDataPath);
          if (userDataExists) {
              process.env.THEIA_CONFIG_DIR = userDataPath;
          } else {
              await mkdir(userDataPath);
              process.env.THEIA_CONFIG_DIR = userDataPath;
              this.pathExistenceCache[userDataPath] = true;
          }
      } else {
          process.env.THEIA_CONFIG_DIR = join(homedir(), '.theia');
      }
      return FileUri.create(process.env.THEIA_CONFIG_DIR).toString();
  }
```

### Steps to Reproduce:
if process.env.THEIA_CONFIG_DIR is specified as a directory, the latest cache file address is not matched

### Additional Information

- Operating System:
- Theia Version: 1.44 ～1.49

**Comment by xai** [comment]
@JonasHelming, please assign this issue to me (cannot self-assign). Thanks!
