### ISSUE TITLE
How can I dynamically register the menu?

### ISSUE THREAD

**Issue by baoqing1124** [eclipse-theia/theia#13717]
### Discussed in https://github.com/eclipse-theia/theia/discussions/13716

<div type='discussions-op-text'>

<sup>Originally posted by **baoqing1124** May 16, 2024</sup>
I need to register the menu dynamically during the use of the application, but I have tested that the menu cannot be displayed when I register the menu asynchronously. What should I do to achieve this function? Can anyone help me?
![31a22891126ae9a389a3ef778825fb1](https://github.com/eclipse-theia/theia/assets/15626996/228d0499-a0ea-4872-91c2-1255c0abc2cc)
![e0266e0991223cb9a33921435942ce3](https://github.com/eclipse-theia/theia/assets/15626996/8c461999-418b-4e5e-bcc9-51c0baa77894)

</div>

**Comment by msujew** [comment]
Please don't create duplicate issues/discussions. See https://github.com/eclipse-theia/theia/discussions/13716 for an answer.
