### ISSUE TITLE
README: link to the documentation is broken

### ISSUE THREAD

**Issue by yasinzaehringer-paradime** [eclipse-theia/theia#13724]
The README reads like this:
```
## Website

[Visit the Eclipse Theia website](http://www.theia-ide.org) for more information and [the Theia documentation](http://www.theia-ide.org/doc).
```

However the documentation link here is broken, it should be:
```
https://theia-ide.org/docs/
```

**Comment by msujew** [comment]
I'm surprised that it took 6 years until someone made an issue for that (original commit c231041).

@yasinzaehringer-paradime Are you interested in contributing a fix for that? :)

**Comment by eric-sclafani** [comment]
Hello, if @yasinzaehringer-paradime is not interested in contributing a fix, may I please be assigned this issue?
