### ISSUE TITLE
How to design toolbar width adaptive?

### ISSUE THREAD

**Issue by WHUWeiYanLin** [eclipse-theia/theia#13767]
When a window covers a toolbar, I would like to be able to use a “small arrow” to close the covered toolbar icon and expand the inner icon when clicking on the small arrow (like a context menu).
Currently in theia I found the “onResize” function and the window screen size change related, but I do not understand in this process should be how to listen to changes in the toolbar and do not know how to use the window changes for different rendering options, in theia to achieve this function, then the process What should be the process to realize this function in theia, and what are the function interfaces to be used?

like turn 
![c1b7bc34-39e1-41f1-99a3-b06a6a49938c](https://github.com/eclipse-theia/theia/assets/134694184/eb844a6e-0c9a-4840-903b-886b4f913c88)
to
![03ada3e7-9aed-489a-9a32-766a5935dd1c](https://github.com/eclipse-theia/theia/assets/134694184/96336fe1-af37-49ff-8e2a-0afb2827b9eb)

**Comment by msujew** [comment]
Please don't create multiple issues for the same question, see https://github.com/eclipse-theia/theia/discussions/13736.
