### ISSUE TITLE
Jupyter Notebooks do not render

### ISSUE THREAD

**Issue by kineticsquid** [eclipse-theia/theia#13780]
### Bug Description:
I'm attempting to edit my Jupyter notebooks in Theia-IDE. They render and run fine in VS Code. I load https://open-vsx.org/extension/ms-toolsai/jupyter, which pulls in several other extensions:
![image](https://github.com/eclipse-theia/theia/assets/681707/47e4fdbf-070a-437f-8c6b-0e367019439d)

The Jupyter notebooks look like this:
![image](https://github.com/eclipse-theia/theia/assets/681707/c1cab8bc-1433-4f64-af84-c6886602f5f2)

I tried creating a new notebook, but same result.
- Operating System: Mac OSX 14.4.1
- Theia Version: Theia IDE Version 1.49.101 (1.49.101.151)

**Comment by msujew** [comment]
Is the `vscode.ipynb` extension installed? It's actually in charge of rendering the notebooks inside of Theia/VS Code. The Jupyter Extension is just there to actually make code cells executable.

**Comment by MatthewKhouzam** [comment]
That solves it for me!

**Comment by kineticsquid** [comment]
Me too! Thanks!
