### ISSUE TITLE
Allow to override connection settings

### ISSUE THREAD

**Issue by sdirix** [eclipse-theia/theia#13800]
In Theia, the desired connection settings are usually configured via the package.json, see for example [here where they are configured for the Theia IDE](https://github.com/eclipse-theia/theia-blueprint/blob/4580073933642b6cffb9e7aa90ba382330ab5551/applications/electron/package.json#L44-L45).

It's good practice to run e2e tests against the final built product. However, depending on how the tests are implemented, they might need a different set of connection settings than the actual delivered product itself. Therefore it would be nice to make them overridable, e.g. via environment variables. The e2e tests could then run against the same delivery, just with different settings.

**Comment by xai** [comment]
I'll have a look at this.
