### ISSUE TITLE
The dependency for treeEditor widget is outdated

### ISSUE THREAD

**Issue by fengwang913** [eclipse-theia/theia#13803]
Bug Description:
1. I generated a treeEditor extension using the "yo theia-extension" command and was able to run the treeEditor extension successfully.
2.  I created a new file named tree-example.tree using the "New Example File" option under the Tree Editor menu
3.  I refresh the webpage, the page fails to reopen. 

![image](https://github.com/eclipse-theia/theia/assets/65167225/6a9704d6-5cbc-4d14-96e0-68dd382a07c6)

### Additional Information

- Operating System: win10
- Theia Version: 1.50.0

**Comment by msujew** [comment]
You're probably looking for [this repo](https://github.com/eclipse-emfcloud/theia-tree-editor). We don't maintain the tree editor dependency here.
