### ISSUE TITLE
The browser-only Theia example application still tries to create a WebSocket connection

### ISSUE THREAD

**Issue by lessmost** [eclipse-theia/theia#13820]
### Bug Description:

The browser-only Theia example application still tries to create a WebSocket connection.

### Steps to Reproduce:

1. Clone the Theia repository

```bash
git clone https://github.com/eclipse-theia/theia.git
```

3. Build and run browser-only sample:

```bash
yarn
yarn download:plugins
yarn browser-only build
yarn browser-only start
```

5. Visit [http://localhost:3000](http://localhost), open dev tools and can find request like 

http://localhost:3000/socket.io/?EIO=4&transport=polling&t=P0cgjyV

and wait for a while, there should be a lots of socket.io request 404 error

<img width="864" alt="截屏2024-06-17 23 54 43" src="https://github.com/eclipse-theia/theia/assets/1142242/e27fef42-bf2d-490d-922a-1d473fdb26fa">

### Possible Cause

1. The socket.io request is triggered by [WebSocketConnectionSource:createWebSocket](https://github.com/eclipse-theia/theia/blob/63fb7e9fd7d42a6daea8d9bfcc26e356ab323a18/packages/core/src/browser/messaging/ws-connection-source.ts#L202), which is triggered by [postConstruct](https://github.com/eclipse-theia/theia/blob/63fb7e9fd7d42a6daea8d9bfcc26e356ab323a18/packages/core/src/browser/messaging/ws-connection-source.ts#L68) in WebSocketConnectionSource.

2. In `electron-messaging-frontend-module.ts` which in included by the Browser-only Theia application,  ElectronWebSocketConnectionSource is first bound to WebSocketConnectionSource at [L36](https://github.com/eclipse-theia/theia/blob/63fb7e9fd7d42a6daea8d9bfcc26e356ab323a18/packages/core/src/electron-browser/messaging/electron-messaging-frontend-module.ts#L36), but also bound as a FrontendApplicationContribution at [L74](https://github.com/eclipse-theia/theia/blob/63fb7e9fd7d42a6daea8d9bfcc26e356ab323a18/packages/core/src/electron-browser/messaging/electron-messaging-frontend-module.ts#L74)

3. In `messaging-frontend-only-module.ts`, although WebSocketConnectionSource is unbind at [L24](https://github.com/eclipse-theia/theia/blob/63fb7e9fd7d42a6daea8d9bfcc26e356ab323a18/packages/core/src/browser-only/messaging/messaging-frontend-only-module.ts#L24), the ElectronWebSocketConnectionSource FrontendApplicationContribution multiInject still exists. So when application start, ElectronWebSocketConnectionSource will be initialized anyway.

Maybe we can separate ElectronWebSocketConnectionSource from FrontendApplicationContribution and close the socket by an dynamic FrontendApplicationContribution?

[#L74](https://github.com/eclipse-theia/theia/blob/63fb7e9fd7d42a6daea8d9bfcc26e356ab323a18/packages/core/src/electron-browser/messaging/electron-messaging-frontend-module.ts#L74)
```ts
-    bind(FrontendApplicationContribution).toService(ElectronWebSocketConnectionSource);
+    bind(FrontendApplicationContribution).toDynamicValue(ctx => {
+        return {
+            onStop: () => {
+                const websocketConnectionSource = ctx.container.get(WebSocketConnectionSource);
+                websocketConnectionSource.socket.close();
+            }
+        }
+    });
```

### Additional Information

- Operating System: macOS 14.5
- Theia Version: 1.50.0

**Comment by sdirix** [comment]
Hi @lessmost,

Thanks for the report and analysis.

> 2\. ElectronWebSocketConnectionSource is first bound to WebSocketConnectionSource at [L36](https://github.com/eclipse-theia/theia/blob/63fb7e9fd7d42a6daea8d9bfcc26e356ab323a18/packages/core/src/electron-browser/messaging/electron-messaging-frontend-module.ts#L36), but also bound as a FrontendApplicationContribution at [L74](https://github.com/eclipse-theia/theia/blob/63fb7e9fd7d42a6daea8d9bfcc26e356ab323a18/packages/core/src/electron-browser/messaging/electron-messaging-frontend-module.ts#L74)

The electron code should never end up in the browser-only case as it's not needed there. So the cause of the issue seems to be [this check in the frontend-generator](https://github.com/eclipse-theia/theia/blame/63fb7e9fd7d42a6daea8d9bfcc26e356ab323a18/dev-packages/application-manager/src/generator/frontend-generator.ts#L111) which erroneously ends up in the electron path for browser-only.
