### ISSUE TITLE
Open With... not working on folders

### ISSUE THREAD

**Issue by bhufmann** [eclipse-theia/theia#13838]
### Bug Description:
`Open With -> Trace Viewer` of the Theia Trace Viewer doesn't work anymore starting with Theia version 1.50.0. This feature allowed users to open traces that are files as well as traces that are folders. The limitation should be put back or alternatively make OpenWidthHandler configurable for files or folders or both (default files only):

```javascript
this.openWithService.registerHandler({
            id: this.id + '-open-with',
            label: this.label,
            providerName: 'Theia Trace Viewer',
            appliesToFiles: true, // <----- suggestion
            appliesToFolders: true, // <----- suggestion
            canHandle: (uri: URI) => this.canHandle(uri),
            open: (uri: URI) => this.open(uri)
        });
```

### Steps to Reproduce:

1. Build and run the Theia trace viewer with PR https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1087
2. Right mouse-click on a folder
3. "Open With..." is not shown

### Additional Information

- Operating System: All
- Theia Version: 1.50.0
- related change: #13678

**Comment by JonasHelming** [comment]
@msujew

**Comment by msujew** [comment]
Sure, that sounds pretty reasonable to me. @bhufmann Interested in contributing something for this?

**Comment by bhufmann** [comment]
I'm not really familiar with Theia internals. It would be probably faster if you @msujew implement it :-)

I had a quick look, and thought it would be just updating [getHandler()](https://github.com/eclipse-theia/theia/blob/37e1f2c5c130988ff29bfbfa2415eada018732d6/packages/core/src/browser/open-with-service.ts#L89) and check if the URI points to folder and check if the handler is configured for folders and then include it or not. What is a quick way to check if the `uri` points to a file or folder? Please let me know.

**Comment by bhufmann** [comment]
We decided to not use the open with service for the theia-trace-extension and instead opted to implement a dedicated command and menu entry for opening of traces. I just wanted to let you know that there is no fix from our side planned for Theia. You can close this issue, or if the project thinks that it's still valid, keep it open. Thanks for the support.
