### ISSUE TITLE
OpenWithService change seems to be breaking changes

### ISSUE THREAD

**Issue by bhufmann** [eclipse-theia/theia#13837]
### Bug Description:
When upgrading the theia-traceviewer (https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1085) to recent Theia community release 1.49.1, I noticed that the feature `Open With -> Trace Viewer` is not working anymore. It is used to open trace files or trace folders from the navigator's Open With menu when selecting either a file or folder. I figured out how to fix it (see PR). 

I think this should be mentioned as a breaking change in the [CHANGELOG.md#breaking_changes](https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md#breaking_changes_1.49.0)

### Additional Information
- Operating System: All
- Theia Version: 1.49.1

Related change: #13573

**Comment by JonasHelming** [comment]
@msujew

**Comment by tortmayr** [comment]
I agree, we also encountered issues with the changed behavior of `open with` when upgrading GLSP projects.
The changes of https://github.com/eclipse-theia/theia/pull/13573 are technically not breaking any API, but they introduce a behavioral change which still should be mentioned in the changelog.
Before this change any widget/view etc. configured with a `OpenHandler` would indirectly also be available in the `open with` context menu. With the introduction of the `OpenWithService` this is no longer the case. If adopters want that their custom opener shows up as `open with` candidate they have to manually inject the `OpenWithService` and register a handler for it.

**Comment by msujew** [comment]
Sorry, right. I didn't really think about people relying on the implicit behavior that existed previously. I'll provide a patch for that tomorrow.
