### ISSUE TITLE
FileResource causes emitter memory leak

### ISSUE THREAD

**Issue by Hanksha** [eclipse-theia/theia#13877]
### Bug Description:

`FileResource` [class constructor](https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/browser/file-resource.ts#L100) calls `fileService.onDidChangeFileSystemProviderReadOnlyMessage` but doesn't add it to the `toDispose` collection which leads to emitter memory leak warnings.

### Steps to Reproduce:

1. Open files more than 175 times
2. You'll see a emitter memory leak warning in the logs

### Additional Information

- Operating System: Windows, Linux
- Theia Version: 1.50

**Comment by JonasHelming** [comment]
Thank you for the report! It seems you have already debugged this, are you interested in a contribution?

**Comment by Hanksha** [comment]
@JonasHelming Hi, yes I'll provide a PR.
