### ISSUE TITLE
Dev containers does not work (no errors, no logs, no visual state)

### ISSUE THREAD

**Issue by vitonsky** [eclipse-theia/theia#13888]
### Bug Description:

Dev containers is does not run. No errors, no logs, no visual response

https://github.com/eclipse-theia/theia/assets/86191922/e2969b39-8ebc-4d58-9ce0-387b340425f2

### Steps to Reproduce:

1. Donwload IDE for linux as AppImage with [official link](https://www.eclipse.org/downloads/download.php?file=/theia/ide/latest/linux/TheiaIDE.AppImage&r=1)
2. Open IDE, open any project folder
3. Create `.devcontainer.json` file ([follow the guide](https://code.visualstudio.com/docs/devcontainers/create-dev-container))
4. Run command "Reopen in container" with any way

### Behavior

Expected:
- Opened a new window of IDE with isolated context inside docker container

Actual:
- Nothing happened

### Additional Information

- Operating System: Ubuntu 22.04.4 LTS
- Theia Version: Latest AppImage (Version 1.51.0) SHA512: d97519f8486706bf18c6d1ea001004a6b2d6b591851dabd189a04c8063e83592c86d126678d63a31d9615af67f9be0b76420bcbe74afdc66758021d1f9839342

**Comment by JonasHelming** [comment]
@jonah-iden

**Comment by jonah-iden** [comment]
interesting, I can take look

**Comment by jonah-iden** [comment]
@JonasHelming for info. Could be that 1.51 broke the full remote feature including dev-containers. After my first investigation it seems like the electron reloading mechanism with new port is broken. But im not fully sure

**Comment by jonah-iden** [comment]
ok seems like it's just for when reloading the window instead of opening a new one
