### ISSUE TITLE
Secondary Window in browser not working

### ISSUE THREAD

**Issue by Lythenas** [eclipse-theia/theia#13890]
### Bug Description:

Opening a secondary window in the browser does not work. The window is opened but it stays blank.

In the original browser tab I get the following error:

```
Uncaught Error: Host is not attached.
    at e.attach (widget.js:913:19)
    at secondary-window-handler.ts:143:20
```

The console on the opened window shows nothing.

This happens for all views I tried (terminal, editor). In previous version the terminal was working.

### Steps to Reproduce:

1. open an editor tab (or a terminal tab)
2. click on "Move View to Secondary Window" button
3. see that window opens but stays blank

I didn't have time for that yet, but I will try to reproduce master. Are there some other information that would be useful to look for?

### Additional Information

- Operating System: Ubuntu, Chromium
- Theia Version: 1.51.0

**Comment by JonasHelming** [comment]
@tsmaeder

**Comment by Lythenas** [comment]
I think that is likely the issue. We don't have `"postinstall": "theia-patch"` and I think in general our setup might be outdated by now. I haven't had time to update theia recently.

Thanks for your help. I will close this ticket for now and check the issue again when we update theia the next time.
