### ISSUE TITLE
Plugin install fail from open-vsx.org

### ISSUE THREAD

**Issue by DigitLib** [eclipse-theia/theia#13904]
### Bug Description:
Using Extensions tab don't install from open-vsx.org

### Steps to Reproduce:

1. Open Thei IDE
2. Go to Extensions tab
3. Install Astro plugin

### Additional Information

- Operating System: Linux CachyOS (Arch based)
- Theia Version: 1.51.0

None of extensions are installed when use this tab. Tried Continue and Astro. Shows installing but nothing happened.
CachyOS added recently installation in their repo.
Tried to installed appimage (official) and in installed app from repo.

**Comment by JonasHelming** [comment]
I just tried, both extensions install for me without any issues. Can you describe exactly how you get to the "Extension tab", it is supposed to be the "Extension view" opened e.g. via the menue "View" => "Extensions"

**Comment by DigitLib** [comment]
I use regular tab on the left, also tried with View -> Extensions. 
Checked the INFO in terminal and see that old versions are used 
Continue is  v0.8.43 but get in Extensions 0.1.3

For Astro latest is v2.11.0 but get v0.26.2 and can not install because can not find a file

INFO [[object Object]]: trying to resolve latest version...
INFO [astro-build.astro-vscode]: resolved to 'astro-build.astro-vscode-0.26.2'
INFO [astro-build.astro-vscode-0.26.2]: trying to download from "https://open-vsx.org/api/astro-build/astro-vscode/0.26.2/file/astro-build.astro-vscode-0.26.2.vsix"... to path /home/andrax/.theia-ide/tmp/vscode-download
INFO [astro-build.astro-vscode-0.26.2]: not found

Thank you.

**Comment by msujew** [comment]
I can reproduce and found the issue, seems like the documentation is wrong... (note the `>=` and `<=` symbols)

![image](https://github.com/eclipse-theia/theia/assets/4377073/b06f25f9-7fb9-4809-a6da-9d61e31233e9)

**Comment by DigitLib** [comment]
@msujew Yes!
