### ISSUE TITLE
Align Notebook preferences registration with other preferences

### ISSUE THREAD

**Issue by cdamus** [eclipse-theia/theia#13913]
### Feature Description:

The registration of the Notebook preferences, added in [this pull request](https://github.com/eclipse-theia/theia/pull/13594/files#diff-5947cb0c6787219ad47d1b573bd6975f2cd86379beaa32ce806ced48f4a9b3ccR107), looks like this:

```typescript
bind(PreferenceContribution).toConstantValue({ schema: notebookPreferenceSchema });
```

This is different to the usual pattern of other established preferences, which would have looked more like this:

```typescript
export const NotebookPreferenceContribution = Symbol('NotebookPreferenceContribution');
bind(NotebookPreferenceContribution).toConstantValue({ schema: notebookPreferenceSchema });
bind(PreferenceContribution).toService(NotebookPreferenceContribution);
```

In my application, importantly, this previously established pattern of Inversify bindings lets me effectively suppress preferences that I don't want to expose to my users because they are not relevant (the capabilities configured by these preferences aren't manifest in my app at all). This is accomplished by rebinding individual preferences service-identifiers with blanks:

```typescript
rebind(NotebookPreferenceContribution).toConstantValue({
        schema: <PreferenceSchema>{
            type: 'object',
            properties: {}
        }
    });
```

This I cannot do with the Notebook preferences. I can only rebind the entire `PreferenceContribution` service-identifier, which means repeating the contributions of all of the preferences from Theia that my application does need.

So the request in this issue is to rework the Notebook preference contribution to follow the pattern previously established by other Theia preferences, unless there is some specific reason why it wasn't done that way?

**Comment by cdamus** [comment]
FYI @jonah-iden for any insight you'd like to offer on this question. Thanks!

**Comment by jonah-iden** [comment]
@cdamus there is no specific reason for the way notebooks does it. I probably just forgot about the ability to overwrite this when I implemented it. So feel free to create a PR to change this or I can create one

**Comment by cdamus** [comment]
> @cdamus there is no specific reason for the way notebooks does it. I probably just forgot about the ability to overwrite this when I implemented it. So feel free to create a PR to change this or I can create one

Thanks! Good to know. I've created a PR, as you can see linked. I would certainly appreciate a review and buddy-testing 😀 .

**Comment by jonah-iden** [comment]
sure I'll try and take a look later today

**Comment by cdamus** [comment]
Thanks @jonah-iden ! It is not so urgent as to require an interim/test build. I am happy to wait for the next regularly scheduled release.
