### ISSUE TITLE
Save All command blindly modifies all open files

### ISSUE THREAD

**Issue by KR155E** [eclipse-theia/theia#13923]
### Bug Description:

The "core.saveAll" command saves all open files to disk, despite them not having been changed, changing the "last modified" timestamp. In our case, this is unnecessarily causing the GCC compiler to pick these files up again in its next run.

I guess the correct behavior would be to check for each file's isDirty flag and refrain from touching it if the isDirty flag is false.

### Steps to Reproduce:

1. Open any file and aside to it, the Properties view
2. Note the "Last modified" timestamp in the Properties view
3. Run the command "File: Save All"
4. Check the "Last modified" timestamp again in the Properties view (make sure to switch to another file and back to update the view first, it won't update automatically)

### Additional Information

- Operating System: Observed on OSX & Linux
- Theia Version: 1.51.0

**Comment by JonasHelming** [comment]
Hi, thank you for the report. I can confirm the behavior you described. As you already describe the solution, are you interested in a contribution?

**Comment by KR155E** [comment]
Sure! Here's the PR: https://github.com/eclipse-theia/theia/pull/13942

**Comment by martin-fleck-at** [comment]
Thank you @KR155E for catching that! I'll have a look at your PR within the next few hours.

Out of curiosity, I had a look at how VS Code behaves and, interestingly, the 'Save' operation always seems to write the file and update the modified date whereas the 'Save All' operation only collects the [modified editors](https://github.com/microsoft/vscode/blob/b97d0a2cb5733af8e2c1fa71699c7d477fd30695/src/vs/workbench/services/editor/browser/editorService.ts#L1020).
