### ISSUE TITLE
Editor Config plugin not working as expected with Theia 1.50, 1.51

### ISSUE THREAD

**Issue by rahulgupta-acquia** [eclipse-theia/theia#13929]
### Bug Description:
When we changed the  indent size 2 to 15 then it is not reflect changes and not working.
```
[composer.{json,lock}]
indent_size = 15
```

### Steps to Reproduce:
1. Create theia build using 1.51.0 
2. Install Extension  "EditorConfig for VS Code - v0.16.6" https://open-vsx.org/extension/EditorConfig/EditorConfig
3. Edit .editorconfig file ->  below section  2 to 15 indent_size
```
[composer.{json,lock}]
indent_size = 15
```
4. check the composer.json file and add sample block and check the indent_size

Note - This extension is working on Theia 1.46.0.

### Additional Information

- Operating System: Every
- Theia Version: 1.51.0

**Comment by JonasHelming** [comment]
@tsmaeder Does this overlap with the Monaco Upgrade?

**Comment by JonasHelming** [comment]
Is this maybe related to https://github.com/eclipse-theia/theia/issues/13920?

**Comment by tsmaeder** [comment]
> Does this overlap with the Monaco Upgrade?

No clue 🤷

**Comment by tsmaeder** [comment]
After a bit of research, it seems that the 1.47 release is the first to include the updated monaco (1.83.1)

**Comment by tsmaeder** [comment]
Btw: the EditorConfig plugins is a vs code built-in and ships with Theia, no need to install it

**Comment by zhouxinghong** [comment]
@tsmaeder 
Please support the provision of an optimal lightweight version without any default extensions (like VSCode) for experienced developers
Another benefit is that it makes it easier to track down IDE or extension compatibility issues.

**Comment by msujew** [comment]
@zhouxinghong I believe this is unrelated to this issue? Also, since this is the framework repo, you're best bet would be to ask over in the [IDE repo](https://github.com/eclipse-theia/theia-blueprint/).

**Comment by zhouxinghong** [comment]
Thank you very much for your answer! 👍
