### ISSUE TITLE
[chore] downgrade jsdom to 22.1.0

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#13943]
Current version of `jsdom` pushed with #13903  requires node 18 as a minimum, where Theia only requires node 16 (see https://github.com/eclipse-theia/theia/pull/13903#issuecomment-2242925305).
The dependency shall be downgraded to be [22.1.0](https://github.com/jsdom/jsdom/releases/tag/22.1.0), to avoid test failures.

**Comment by msujew** [comment]
Given that there are quite a few of our dependencies that would require node `>=18` in their latest versions, shouldn't we just deprecate Node 16 support by now? It's been out of LTS for a few months now and nobody should continue using it anyway.

I think this would be a better solution to this than downgrading `jsdom` and therefore pulling a vulnerable extension in our dev environments.

**Comment by rschnekenbu** [comment]
That'a a good point. Should this decision be part of the next developer meeting?
