### ISSUE TITLE
Extension pages do not load and extensions do not install

### ISSUE THREAD

**Issue by iamfraggle** [eclipse-theia/theia#14001]
### Bug Description:
Clicking on an extension listing in the search bar or it's install icon starts a progress bar in the sidebar but no page loads or no installation occurs.

### Steps to Reproduce:

1. Open extension sidebar
2. Perform a search
3. Click on an entry in the search list or on it's install button

### Additional Information

- Operating System: Windows 10 (Build 19045.4651)
- Theia Version: 1.51.0

**Comment by JonasHelming** [comment]
Thank you for the report. This works for me. Could you maybe try it it again or from a different network?

**Comment by iamfraggle** [comment]
Tried again today.  No difference.  I use a desktop, so trying a different network would be tricky.  Is there some URL I can try from a browser to prove whether it's a network issue?

**Comment by JonasHelming** [comment]
Hmm, which particular extension do you install? Are you on any special network or just regular internet without any restrictions?

**Comment by iamfraggle** [comment]
I was initially trying to install the Git SCM Integration, but the issue applies to all extensions listed in the search results.

I'm using my regular internet (same I'm using to post this bug report and comments).  The main reason I don't think it's a simple network issue is that the search itself seems fine.  I get a list of extensions relevant to my search term, but I can't do anything with the items in the list.

**Comment by msujew** [comment]
@iamfraggle Are there any error logs in the backend/frontend logs? Anything that can give a hint in regard to what's wrong. Usually, we have pretty good logging when it comes to extension installs.

**Comment by iamfraggle** [comment]
Logging was reporting that it couldn't create the .theia-ide folder in my user profile.  Turns out I had somehow lost write permissions to my user profile root folder.  Once I corrected that, everything worked.  It actually auto-installed the Git SCM Integration.  Many thanks for your help.

**Comment by msujew** [comment]
Glad to hear it's resolved :)
