### ISSUE TITLE
Drop nsfw support 

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#14015]
NSFW (node-sentinel-file-watcher) is one of our dependencies and was not updated for the last 2 years.

In the context of #13957, there may be some evolution to do on the FileSystemWatcher mechanism, it could be a good point to evaluate changing this library to a newer one. In short about these evolutions:
- [file-system-event-service-ext-impl.ts ](https://github.com/eclipse-theia/theia/blob/267ed206e43d090a6392b158519a2e9f0cb9dccc/packages/plugin-ext/src/plugin/file-system-event-service-ext-impl.ts#L21C6-L21C7) may follow evolutions as indicated in its comment
- the proposed API used by typescript require API and behavior evolution on our current framework. 

As a note: VS Code is now using parcel (https://github.com/parcel-bundler/watcher).

**Comment by msujew** [comment]
For the necessary changes, see https://github.com/eclipse-theia/theia/pull/12784 :)
