### ISSUE TITLE
Mismatched "ffmpeg" Architecture

### ISSUE THREAD

**Issue by rroessler** [eclipse-theia/theia#14011]
### Bug Description:

There is a major issue for certain versions of Electron for MacOS x64 where building will fail due to a mismatched `ffmpeg` architecture.

For more information see the [original issue report](https://github.com/electron/electron/issues/43076) and the [subsequent pull-request](https://github.com/electron/electron/pull/43093). Noting that the "fix" [only applies to new releases](https://github.com/electron/electron/pull/43093#issuecomment-2269801432) that could force a large jump in versions for Theia's dependency of Electron.

I am unsure how many versions of Electron are effected, but it appears to be quite substantial (eg: various versions of 28 through to 32 at the time of writing). Any versions released [before this commit](https://github.com/electron/electron/commit/b92a4023c137b1850bd2a48712b8804d0f50a836) and [after this commit](https://github.com/electron/electron/commit/87fb2ad70cf778752aadc5496f534b7a0793da61) should be have the correct architecture and any in-between should be not targeted by when using Theia.

### Additional Information

- Operating System: MacOS x64
- Theia Version: Non-specific
- Electron Versions: Various

**Comment by JonasHelming** [comment]
@tsmaeder Could you check whether we are affected, please?

**Comment by tsmaeder** [comment]
`yarn.lock` currently uses electron 28.2.10. Downloading the release and checking the file yielded 
```
% file ./libffmpeg.dylib 
./libffmpeg.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

so I think we're good.

**Comment by tsmaeder** [comment]
While the fix has not been backported to the 28.* branch, any new builds for 29 onwards should be fine. Maybe this would be a good idea to consider another electron update?

**Comment by tsmaeder** [comment]
Closing this one as we are currently not affected and there's a separate issue for the electron update.
