### ISSUE TITLE
Preference/Setting issue when using the Redhat Java plugin

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#14034]
### Bug Description:
Hi,
In latest Theia there is a regression in the preference/setting view when the Redhat Java plugin is installed, all the Java settings were shown under one main category under Extenions--> Java, but now all the java sub-categories are rendered under the Extenions parent, making it difficult to know that those categories belong to the Java extension.

Maybe this was caused after this PR: https://github.com/eclipse-theia/theia/pull/13819

### Steps to Reproduce:

1. install Redhat java plugin (1.33)
2. open setting
3. you will see many new categories under the Extensions category, instead of adding only one Java category as before.

### Additional Information

- Operating System: Mac
- Theia Version: 1.52

**Comment by tsmaeder** [comment]
Invoking @msujew for comment.

**Comment by msujew** [comment]
Can reproduce, looking at it right now :)
