### ISSUE TITLE
Editor status bar items stay when switching to a custom editor

### ISSUE THREAD

**Issue by jonah-iden** [eclipse-theia/theia#14045]
### Bug Description:

![grafik](https://github.com/user-attachments/assets/d6982054-125c-4c46-af39-d7de95ed9b15)

When opening a custom editor like a webview or the notebook editor, the status bar items stay even though the editor they belong to is not visible anymore. In VSCode it disappears when the editor is not visible anymore.

### Steps to Reproduce:

1. Open some text file. The status bar should contain information about cursor position, encoding etc
2. Open a custom editor like a notebook or webview based (i also tested with the https://open-vsx.org/extension/redhat/vscode-extension-bpmn-editor)
3. The text editor is not visible anymore, but the status bar items still stay

### Additional Information

- Operating System: Windows/Firefox
- Theia Version: 1.52.0

**Comment by dhuebner** [comment]
See also  #14190
