### ISSUE TITLE
Tab Maximize issue on custom editors

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#14051]
### Bug Description:
Hi,
I think there is an issue in tab Maximize feature on custom editors. When using the maximized tab on a dirty tab, it will open it in dirty mode (modified state), but the issue is that if the user closes the maximized modified tab, and in the save modified file confirmation popup, select not to save, once the file is opened again it will open as modified !!!

### Steps to Reproduce:

1. open a custom editor file (e.g cat plugin)
2. do some changes
3. maximize the tab
4. see that it is still a dirty file (bullet on the tab)
5. close that tab
6. in the save confirmation popup, choose not to save
7. open the same file again, you will see that it is still in a modified state! it will keep like this until you save the file!

### Additional Information

- Operating System: Mac
- Theia Version: 1.52

**Comment by JonasHelming** [comment]
@dhuebner If I remember correctly, did you review or do a change in this area recently?

**Comment by dhuebner** [comment]
@JonasHelming 
Not sure I did something in the maximize editor workflow, but I can have a look.

**Comment by JonasHelming** [comment]
:-) Not with maximizing, but with the save behavior or am I mistaken? Anyways, thank you for having a look!

**Comment by msujew** [comment]
@JonasHelming I've recently refactored the saving mechanism in https://github.com/eclipse-theia/theia/pull/13683 :)

**Comment by msujew** [comment]
See https://github.com/eclipse-theia/theia/pull/14062 for a fix.
