### ISSUE TITLE
[vscode] Move stubbed implementation of TerminalShellIntegration from proposed to main theia.d.ts

### ISSUE THREAD

**Issue by rschnekenbu** [eclipse-theia/theia#14107]
TerminalShellIntegration proposed API was stubbed on last iteration, see #14058. Python extension is using this API.
This API has now been promoted to main vscode.d.ts on 1.93 version. 

First step would be to move the proposed API as stubbed, and then evaluate real implementation of it.
This task covers the deletion of the proposed API and addition to theia.d.ts.

**Comment by tsmaeder** [comment]
The policy in general is not to have stubs unless we are forced to. We should look at what it takes to implement this.

**Comment by rschnekenbu** [comment]
In order to have this feature implemented for extensions, we have to get some features already implemented in our Terminal implementation. 

The shell integration in VS Code relies in scripts automatically added when the shell execution starts. Those scripts depends on the OS and the kind of shell started. These are obviously different when on Windows, Linux or Mac. 
See for example: 
- https://github.com/microsoft/vscode/blob/4849ca9bdf9666755eb463db297b69e5385090e3/src/vs/platform/terminal/node/terminalEnvironment.ts#L330
- https://github.com/microsoft/vscode/tree/1.93.0/src/vs/workbench/contrib/terminal/browser/media for scripts

Once these scripts are added, the shell integration relies on proprietary escape sequences. 

Once these escape sequences are added, some addons can be added on the xterm Terminal to add some behavior based on these sequences. It allows identification of the current working directory, or the current command executed, its exit code, etc.
See for example the handler for specific VSCode sequences: https://github.com/microsoft/vscode/blob/4849ca9bdf9666755eb463db297b69e5385090e3/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L291

The implementation of the VS Code API would then be quite easy, with some events to handle when the shell integration is activated / modified and some events happen on the ShellIntegration. The ShellIntegration API also provides a way to start a command in the terminal.  

This main feature implementation would take quite some time and also quite some development and testing on various platforms. 
Once this main feature is implemented, we could imagine removing the stubs for the VS Code API. 
Among the work required, I can evaluate:
- implementation of the various scripts to be added to the execution of the shell
   - automatic addition
   - manual addition
 - implementation of the [addon](https://xtermjs.org/docs/api/terminal/interfaces/iterminaladdon/) on the xterm implementation
 - init of the shell integration when starting
 - service that reactsto required information: cwd update, command execution, etc.
 - implementation of the extension API.
