### ISSUE TITLE
Unable to run yarn behind a proxy: failed to execute download-catalog.js script in the @theia/core package

### ISSUE THREAD

**Issue by pchuong** [eclipse-theia/theia#14126]
### Bug Description:
Using the latest release/1.53.x branch, running "yarn" behind a proxy failed in the @theia/core package. It tries to execute the download-catalog.js script and this script required setting the proxy server url in the config object.

### Steps to Reproduce:

1. Clone the repository
2. Run 'yarn'

### Additional Information

Here is the error:

@theia/core: yarn run v1.22.21
$ yarn -s generate-theia-re-exports && yarn download:json-schema
$ tsc -b
@theia/core: $ node ./scripts/download-catalog.js
@theia/core: node:internal/process/promises:288
@theia/core:             triggerUncaughtException(err, true /* fromPromise */);
@theia/core:             ^
@theia/core: Error: getaddrinfo ENOTFOUND schemastore.org
@theia/core:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
@theia/core:   errno: -3008,
@theia/core:   code: 'ENOTFOUND',
@theia/core:   syscall: 'getaddrinfo',
@theia/core:   hostname: 'schemastore.org'
@theia/core: }
@theia/core: Node.js v18.19.1
@theia/core: error Command failed with exit code 1.
@theia/core: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@theia/core: error Command failed with exit code 1.
@theia/core: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@theia/cli: Done in 2.72s.

- Operating System: Ubuntu 22.04
- Theia Version: 1.53

**Comment by msujew** [comment]
Hey @pchuong,

care to provide a PR for this? I don't think that any of the core contributors to Theia are affected by this issue, so it's not all too high on our priority list.

**Comment by pchuong** [comment]
Is using the system environment variable http_proxy and HTTP_PROXY sufficient to set the proxy value? User would need to set either one of this environment variables.

**Comment by msujew** [comment]
@pchuong I don't know, I'm not too familiar with this, since I never work behind proxies. Can't you try it out?
