### ISSUE TITLE
Dev containers do not have built-in plugins

### ISSUE THREAD

**Issue by sgraband** [eclipse-theia/theia#14137]
### Bug Description:

Currently dev containers are started without the built-in plugins of the "parent" application (e.g. Theia IDE).
This leads to the application behaving differently than outside of the dev container, for example the syntax highlighting is missing.
I do not think, that the creator of the `devcontainer.json` file should be responsible for specifying the built-in plugins, as one would expect that they are "part of the application".

### Steps to Reproduce:

1. Open a dev container
2. Observe that there are no built-in plugins displayed in the extension view
3. Check that plugins are not installed (e.g. settings page, no syntax highlighting, etc..)

### Additional Information

- Operating System: Ubuntu 22.04
- Theia Version: Theia IDE 1.53.100

**Comment by msujew** [comment]
Note that this works in the Theia Dev Electron app:

![image](https://github.com/user-attachments/assets/3b8d7a4a-1122-4d8d-832f-261d8d8b7131)

@sgraband What application have you been using to replicate this? With the latest TheiaIDE, this doesn't work.

**Comment by sgraband** [comment]
Thanks for the fast reply. I replicated it with Theia IDE 1.53.100 as well(also updated the ticket).

I will take a detailed look at the PR you linked in a minute, but would you expect this to work automatically with any product or are there some requirements on the products side to configure this/install the plugins in a certain way?

**Comment by msujew** [comment]
It might be that the `localDir` call [here](https://github.com/eclipse-theia/theia/blob/41f8c72ad14a9afcdde7e17ce5440ec2630e2f8e/packages/plugin-ext/src/main/node/plugin-remote-copy-contribution.ts#L29) behaves somehow unexpected in a packaged environment.

**Comment by jonah-iden** [comment]
@sgraband Could you provide us with some more information on how your plugins setup is? Do you set the --plugins option or the THEIA_DEFAULT_PLUGINS env variable? Are you installing some plugins manually before connecting with the container? Is it a pacakges electron distribution with an asar file?

**Comment by jonah-iden** [comment]
@msujew ok thanks will try it out

**Comment by sgraband** [comment]
@jonah-iden. Yes i was reporting this straight from the Theia IDE. Thanks for looking into it.
