### ISSUE TITLE
Preferences/Setting scroll issue

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#14157]
### Bug Description:
Hi,
In the latest Theia build 1.53, there is an issue when opening an extension setting with an inner setting folders/categories like  Redhat java extension (Language support for java) or the CSS Language Features. When going to the settings of this extension, and trying to scroll on the right side view (settings properties), the left side tree view collapses all the extensions node and moves the focus to the node before --> bad UX.

### Steps to Reproduce:

1. see there attached recording

### Additional Information

https://github.com/user-attachments/assets/bcb404f2-7ca8-495f-8925-f107dcaf278e

- Operating System: Mac
- Theia Version: Theia 1.53

**Comment by tsmaeder** [comment]
Yeah, this is quite annyoing: added it to the Theia IDE epic.

**Comment by msujew** [comment]
Will be fixed by https://github.com/eclipse-theia/theia/pull/14170.
