### ISSUE TITLE
[bug] Style Error

### ISSUE THREAD

**Issue by fly-bue** [eclipse-theia/theia#14204]
### Bug Description:
The style in the `tabs.css` file is wrong，The + and - operators must be surrounded by whitespace. the source of the [problem](https://github.com/eclipse-theia/theia/pull/14028/files#diff-44c10cc59043f82133e5ae6399445049ad43aec70712f3dde8002c8ae1cba6bc).

![image](https://github.com/user-attachments/assets/a2c94b51-74cf-4542-8a27-2c23b94c236f)

### Additional Information

- Operating System: windows11
- Theia Version: master

**Comment by JonasHelming** [comment]
@tsmaeder

**Comment by tsmaeder** [comment]
@fly-bue what do you mean by "wrong"? Do you mean syntactically or does it have some negative effect?

**Comment by fly-bue** [comment]
@tsmaeder There is a syntax error, please see [calc()](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#rules_and_best_practices_while_using_calc)

**The + and - operators must be surrounded by whitespace**. For instance, calc(50% -8px) will be parsed as "a percentage followed by a negative length" — which is an invalid expression — while calc(50% - 8px) is "a percentage followed by a subtraction operator and a length". Likewise, calc(8px + -50%) is treated as "a length followed by an addition operator and a negative percentage".

**Comment by tsmaeder** [comment]
@fly-bue are you using a particular tool to check the css syntax, because it's not flagged as an error in the editor.
