### ISSUE TITLE
[Theia AI] History widget cannot be reopened

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#14236]
### Bug Description:
If you close and reopen the AI History View, it is in a broken state. Reloading helps.
- Operating System: Linux
- Theia Version: 1.54

**Comment by JonasHelming** [comment]
@planger Did you fix this on-the-go?

**Comment by planger** [comment]
@JonasHelming No, I don't think so. I just fixed the error that was reported for undefined agent descriptions.
