### ISSUE TITLE
Dev Container uses Wrong Window

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#14307]
### Bug Description:
When I have multiple windows open, clicking on the "><" icon on the bottom left of the the first opened window and invoking the command "Reopen in Container" Uses that last opened window instead of the window I clicked on.

### Steps to Reproduce:

1. Open a Theia window with a `.devcontainer` folder
2. Open another Theia window on a workspace that does not have the `.devcontainer` folder
3. In the first window, try starting the devcontainer as described above
4. Observe nothing happens. When I open the browser log, it says "Error: ENOENT: no such file or directory, scandir 'C:\Users\thomas\code\theia\theia2\.devcontainer'"

Further experimentation reveals that I have to restart all of Theia IDE to get rid of the error message once it happens

### Additional Information

- Operating System: Windows 11
- Theia Version: 1.54.0

**Comment by tsmaeder** [comment]
@sgraband

**Comment by JonasHelming** [comment]
@jonah-iden
