### ISSUE TITLE
Open workspace symbol doesn't show result when "::" is part of the query

### ISSUE THREAD

**Issue by MarkZ3** [eclipse-theia/theia#1430]
Using latest master of Theia (electron example) with C/C++ (Clangd). If I open the Open Workspace Symbol (Ctrl+O) pop-up and type "clang::" (to list all symbols , clang namespace), then the UI does not show any result. But I can see in the logs that the server correctly returns the result.

![workspace-symbol-bug](https://user-images.githubusercontent.com/311730/36918393-c8ad9ae2-1e27-11e8-9777-ae257184b87f.png)

**Comment by vince-fugnitto** [comment]
The following seems to now work, I confirmed using the [vscode-clangd](https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd) extension from llvm:


https://user-images.githubusercontent.com/40359487/109526859-0c42b400-7a81-11eb-9ffa-b709b7eda600.mp4
