### ISSUE TITLE
Unpinning an unclosable widget makes it closable

### ISSUE THREAD

**Issue by KR155E** [eclipse-theia/theia#14370]
### Bug Description:

By pinning and unpinning a tab containing an unclosable widget, it becomes closable. The reason lies in the unpin function making the widget closable no matter what in https://github.com/eclipse-theia/theia/blob/f29c3d04241b32791462c7027938abeb887f8140/packages/core/src/browser/widgets/widget.ts#L373

**Comment by JonasHelming** [comment]
Thank you for the report! Seems like you have already debugged this, would you be interested in contributing a fix?

**Comment by KR155E** [comment]
With little time at hand, I tried implementing a quick fix, but extending Title to include something like "originalClosable" seemed dirty. On the other hand, not modifying title.closable at all on pin/unpin, and instead checking for PINNED_CLASS everywhere, turned out to be quite the rabbit hole. So, I'd prefer to let the experts handle this. ;-)

**Comment by JonasHelming** [comment]
@tsmaeder Could you have a look at this?
