### ISSUE TITLE
Black Border appears on Top of Splash Screen in Theia Electron

### ISSUE THREAD

**Issue by chroberino** [eclipse-theia/theia#14397]
### Bug Description:
When adding a splash screen in an Electron-based Theia application, a black border line appears at the top of the splash screen image, which should not be present. This behavior occurs regardless of the image used. For testing purposes, a solid yellow splash screen image was used to clearly highlight the issue against a white background.

### Steps to Reproduce:
1. Create a splash screen PNG file with a pixel size of 640x360.
2. Add a splash screen configuration to package.json as shown below:
```
"electron": {
  "splashScreenOptions": {
    "content": "../my-ext/resources/SplashScreen.png",
    "width": 640,
    "height": 360,
    "minDuration": 1000,
    "maxDuration": 5000
  }
}
```
3. Launch the Theia application with the Electron runtime.
4. Observe the splash screen during startup.

### Additional Information
- Operating System: Windows 10
- Theia Version: 1.53.2
![grafik](https://github.com/user-attachments/assets/f7d63ec6-0c38-455a-b02f-4260f8fc6b09)

**Comment by JonasHelming** [comment]
@tsmaeder Can you see this on Windows with theia IDE 1.55?

**Comment by tsmaeder** [comment]
No, I'm not seeing this. It's very odd, in particular since the splash screen window has been set to transparent for a while now. @chroberino what happens when you change the size in the settings? Could you share the png you are using?

**Comment by chroberino** [comment]
Well... I tried to reproduce this issue today before sharing the PNG. But I failed, today everything looks just fine, the black border is gone. I will keep an eye on it but it seems like my laptop just needed a reboot.

Sorry for wasting your time!

**Comment by JonasHelming** [comment]
No worries. I will close this, please reopen if it occurs again.
