### ISSUE TITLE
It is not possible to open an editor for deleted files from the git widget

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#1440]
I get the following error:
`Request show failed with message: fatal: Path 'packages/git/src/browser/git-command.ts' does not exist (neither on disk nor in the index).`

It works in VS Code.

**Comment by vince-fugnitto** [comment]
The issue is fixed, we can open deleted files from the `scm` widget:

![Screen Shot 2022-07-20 at 3 03 57 PM](https://user-images.githubusercontent.com/40359487/180062027-902638c8-3b92-443e-930b-cb606c1e1919.png)
