### ISSUE TITLE
Update built-ins

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#14418]
### Feature Description:
We want updated built-ins before we declare the 1.55.0 community release. The API compatibility level of 1.55.x is '1.94.2', so this is the version the built-ins we should be aiming for.

**Comment by tsmaeder** [comment]
@msujew we discussed a while back that you would give this a go this time around, also to check that the doc is sufficient. Do you have capacity to do this right now?

**Comment by msujew** [comment]
Not right now ;) But I'll have time for this next week, yes.
