### ISSUE TITLE
Theia not synchronize the background color of the electron window when changing the theme

### ISSUE THREAD

**Issue by lqd1434** [eclipse-theia/theia#14428]
### Bug Description:
Theia not synchronize the background color of the electron window when changing the theme

### Steps to Reproduce:

1.open theia ide
2.change theme to dark
3.refresh window ,and we can see a white screen flash then become dark

### Additional Information
this issue can fixed by follow code 
```javascript
// core/src/electron-main/electron-main-application
override setBackgroundColor(webContents: WebContents, backgroundColor: string): void {
        BrowserWindow.fromWebContents(webContents)?.setBackgroundColor(backgroundColor);
        this.customBackgroundColor = backgroundColor;
        this.saveState(webContents);
    }
```
This seems like a simple fix, I wonder if theia has other considerations or if it's just me got the issue

- Operating System: ubuntu22
- Theia Version: latest

**Comment by JonasHelming** [comment]
@rschnekenbu

**Comment by Keithyumi** [comment]
Can we change theia's background colour? When using the light theme, when the page hasn't loaded yet, it will show a white screen, which makes the application look especially slow, and it won't feel so strong if it's a black background!
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/c76ad3f3-081f-41b8-b93e-b8ee56c79822">
