### ISSUE TITLE
Theia AI: Workspace Agent - allow overriding its methods + rebinding

### ISSUE THREAD

**Issue by safisa** [eclipse-theia/theia#14433]
### Feature Description:
Hi,
1. first can you change the signature of the workspace agent to be protected instead of private - especially the 'exclude' method.
2. second, how can I rebind the GetWorkspaceFileList? or a tool? since I want to change the exclude logic!

Thanks

**Comment by JonasHelming** [comment]
:-)
See https://github.com/eclipse-theia/theia/pull/14426

**Comment by JonasHelming** [comment]
In a nutshell, we are extracting the exclude logic to a rebindyble service and also plan to introduce a setting to 
1. Respect .gitignore
2. Allow configurable exclusions

**Comment by JonasHelming** [comment]
This is merged: https://github.com/eclipse-theia/theia/pull/14426
can you check whether it fixes this issue for you?

**Comment by safisa** [comment]
> This is merged: #14426 can you check whether it fixes this issue for you?

I will check it once it is released (in 1.56), from the code I see that this should resolve my issue. 
Thanks a lot, this was just on time :)

**Comment by JonasHelming** [comment]
I will close this, please reopen if the problem presists
