### ISSUE TITLE
Reopen in Container does not work

### ISSUE THREAD

**Issue by rubensa** [eclipse-theia/theia#14447]
### Bug Description:
Trying to open a project with _devcontainer.json_ using **Reopen in Container** does not work.  I get the following error message:

> (HTTP code 400) bad parameter - No command specified

### Steps to Reproduce:

1. Open a project with .devcontainer/devcontainer.json (working without problem in VSCode)
2. Execute **Dev Container: Reopen in Container**

Attached ([theia-log.txt](https://github.com/user-attachments/files/17736974/theia-log.txt)) is the full log shown in the terminal I used to start **Theia IDE** using **AppImage**.

### Additional Information

- Operating System: **Ubuntu 22.04.5 LTS**
- Theia Version: **1.52.0**, **1.53.200**, **1.54.0**, **1.55.0** (**AppImage** version)

**Comment by JonasHelming** [comment]
@rubensa Thank you for the report. Is it possible to share the (maybe minimized) dev file?

**Comment by JonasHelming** [comment]
@jonah-iden

**Comment by msujew** [comment]
@rubensa It might be that the devcontainer.json in there uses configuration that isn't supported by Theia. @jonah-iden Could you take a look?

**Comment by rubensa** [comment]
@msujew Where can I see what configuration does Theia support?  What happens if there are config options not supported?  Are they reported and ignored or there can't be any not supported configuration option present?

**Comment by jonah-iden** [comment]
currently not supported options are just ignored i think. 
There is a list in the readme of the @theia/devcontainer package but I'm not 100% sure that is up to date. According to the list its just:
- name
- Image
- dockerfile/build.dockerfile
- build.context
- location
- forwardPorts
- mounts

**Comment by jonah-iden** [comment]
But ican see settings should also be supported, as well as extensions, remoteUser and postCreate

**Comment by msujew** [comment]
@jonah-iden Thanks for chiming in! With that in mind, I assume the `dockerComposeFile` in the devcontainer.json will be simply ignored, which simply results in no container being started.

**Comment by jonah-iden** [comment]
oh yeag right, docker compose is currently not supported by theia

**Comment by rubensa** [comment]
Ummm...  Looks like fairly limited support right now as the [Dev Container reference](https://containers.dev/implementors/json_reference/) includes much more options.

I suppose I need to wait for the support to be more mature to use Theia as VSCode replacement for Dev Container development (as we use extensively docker compose).

In any case, thanks for your help on this.
