### ISSUE TITLE
Issue: Incorrect editor.selection Object in Jupyter Notebooks

### ISSUE THREAD

**Issue by garyb9** [eclipse-theia/theia#14475]
Description:

When working with a Jupyter Notebook in Theia and using the `vscode.window.activeTextEditor` API to retrieve the editor.selection object, the selection data appears to be incorrect. This behavior differs from the expected results in VS Code.

Steps to Reproduce:
	1.	Open a Jupyter Notebook in Theia.
	2.	Select two lines of text within a single cell.
	3.	Log the editor.selection object:
```typescript
const editor = vscode.window.activeTextEditor;
console.log('selection:', editor.selection);
```

**Note - this only happens when selecting bottom to top**

Expected Behavior (VS Code):

When selecting two lines in a cell, the editor.selection object accurately reflects the range, as shown below:
```json
{
  "start": {
    "line": 1,
    "character": 0
  },
  "end": {
    "line": 2,
    "character": 9
  },
  "active": {
    "line": 1,
    "character": 0
  },
  "anchor": {
    "line": 2,
    "character": 9
  }
}
```

Observed Behavior (Theia):

For the same file and same selection, the editor.selection object is incorrect and outputs:
```json
[
  {
    "line": 1,
    "character": 1
  },
  {
    "line": 1,
    "character": 1
  }
]
```

Attaching a screenshot of the ipynb file (notice the two highlighted lines): 
![image](https://github.com/user-attachments/assets/e84838a8-ac7f-4054-b84a-a66666e737bd)

The selection object does not reflect the correct range and appears to always point to a single character, regardless of the actual selection.

Impact:

This inconsistency affects extensions or code relying on the editor.selection API for Jupyter notebooks, leading to incorrect behavior or functionality.

Additional Context:

This issue appears specific to Jupyter notebooks and does not occur with standard text files. It might be related to how Theia handles notebook-specific editors versus standard text editors.

Request:

Please investigate this discrepancy and align the behavior of editor.selection in Jupyter notebooks with the expected behavior in VS Code.

**Comment by jonah-iden** [comment]
Oh interesting. When selecting from top to bottom it works fine. But selecting bottom-top it just sets the cursor position. Are you encountering it the same way?
I'll see if i can fix it tommorrow

**Comment by garyb9** [comment]
@jonah-iden you're correct, i usually select from right to left, bottom up so i didnt notice it only happens in this direction

i will update the ticket then

**Comment by garyb9** [comment]
although this one - 
https://github.com/eclipse-theia/theia/issues/14477

is unrelated to the direction of select and happens regardless

**Comment by jonah-iden** [comment]
already found the issue and fixed it. Will look at the other two and probably create a single PR for all three
