### ISSUE TITLE
Add blacklist/whitelist for downloadable/installable/runnable plugins

### ISSUE THREAD

**Issue by nimo23** [eclipse-theia/theia#14519]
### Feature Description:

When the extension manager is available in a Theia IDE, all available plugins are listed. It would be nice to introduce some kind of **blacklist/whitelist** of plugins that are (not) allowed to be downloaded/installed in Theia. This could be a JSON file for example:

```
extensionManager: {
// these plugins are not allowed to be downloaed or installed in theia (optional)
blacklist: [plugin1, plugin2, etc],

// these plugins are allowed to be explicitly downloaded or installed in theia
whitelist: [plugin1, plugin2, etc]

}
```

Another example by using wildcards:

```
extensionManager: {
// *: blocks all available plugins that are not listed in the whitelist
blacklist: [*],

// only these plugins are allowed to be downloaded or installed in theia
whitelist: [plugin1, plugin2, etc]

}
```

**Comment by JonasHelming** [comment]
Could you describe the use cases you want to solve with this?

**Comment by JonasHelming** [comment]
Please note that you can host your own instance/proxy of the openVSX registry, an open source marketplace for VS Code extensions. By connecting your Theia App to a custom instance, you can control on this instance, what extensions users are allowed to install. Filtering them only in the UI would make it pretty easy for users to circumvent the mechanism.
