### ISSUE TITLE
[Theia AI] Add Support for Model Context Protocol (MCP)

### ISSUE THREAD

**Issue by joelthe1** [eclipse-theia/theia#14523]
Given the promising nature of the Model Context Protocol introduced by Anthropic, it would be beneficial to have this supported within Theia AI. Since it already takes inspiration from LSP, it might already be partially supported.

https://www.anthropic.com/news/model-context-protocol

https://spec.modelcontextprotocol.io/specification/

**Comment by JonasHelming** [comment]
This looks interesting, I will have a look at this more in detail
