### ISSUE TITLE
Consider using Sass/SCSS 

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#1463]
CSS is hard to work with, and Sass preprocessor does not make CSS better. 

However, mixins, `@extends`, and other syntax sugars that Sass provides could help with the CSS reuse, and (hopefully) help maintain the consistent look-and-feel of theia, when more and more developers start contributing to the product.

**Comment by akosyakov** [comment]
If it does not make build slower.

**Comment by akosyakov** [comment]
Could you also explain which issue particularly you are going to solve with it?

**Comment by elaihau** [comment]
In my opinion, using Sass/SCSS could help 

- Promote the **CSS reuse**:
*******
.p-MenuBar-item {
  padding: 0px 8px;
  border-left: var(--theia-border-width) solid transparent;
  border-right: var(--theia-border-width) solid transparent;
  line-height: var(--theia-private-menubar-height);
}
.p-MenuBar.p-mod-active .p-MenuBar-item.p-mod-active {
  z-index: 10001;
  background: var(--theia-layout-color1);
  border-left: var(--theia-border-width) solid var(--theia-border-color1);
  border-right: var(--theia-border-width) solid var(--theia-border-color1);
  box-shadow: 0px 0px 6px rgba(0, 0, 0, 0.2);
}
*******
from the current code base, can be turned into
********
@mixin borders ($lineColor) {
  border-left: var(--theia-border-width) solid $lineColor;
  border-right: var(--theia-border-width) solid $lineColor;
}
.p-MenuBar-item {
  @include borders(transparent);
  padding: 0px 8px;
  line-height: var(--theia-private-menubar-height);
}
.p-MenuBar.p-mod-active .p-MenuBar-item.p-mod-active {
  @include borders(var(--theia-border-color1));
  z-index: 10001;
  background: var(--theia-layout-color1);
  box-shadow: 0px 0px 6px rgba(0, 0, 0, 0.2);
}
******

- Save time in typing, and make the CSS more concise, for example:

*******
.theia-extensions .extensionHeaderContainer {
    padding: 3px 15px;
    font-size: var(--theia-ui-font-size0);
    background: var(--theia-layout-color3);
}
.theia-extensions .extensionHeaderContainer:hover {
    background: var(--theia-layout-color0);
}
*******
from the current code base, can be turned into
*******
.theia-extensions .extensionHeaderContainer {
    padding: 3px 15px;
    font-size: var(--theia-ui-font-size0);
    background: var(--theia-layout-color3);
    &:hover {
        background: var(--theia-layout-color0);
    }
}
*******

- In future, if time and resource permits, we can even put our CSS stylings to ONE place, and other theia extension builders could simply import and customize in the way they want. 
 
I am new to this project and am not sure how much UI work is planned down the road. Probably it is not worth the effort if the UI is mostly done already  :-)

And to be very honest I don't know how much it will slow down the build and if there is a way to get around the overhead.

**Comment by akosyakov** [comment]
> In future, if time and resource permits, we can even put our CSS stylings in ONE place, and other theia extension builders could simply import and customize in the way they want.

We use CSS variables for theming if you are interested in improving existing CSS it would be worth to look at this issue: https://github.com/theia-ide/theia/issues/1486

**Comment by vince-fugnitto** [comment]
Closed thanks to #6475
