### ISSUE TITLE
System icon not working for electron example.

### ISSUE THREAD

**Issue by kalyan3d** [eclipse-theia/theia#14657]
### Steps to Reproduce:

1. Launch electron example in linux
2. Observer the system tray icon
3. It is not showing the theia icon

### Additional Information

- Operating System:
- Theia Version:

**Comment by msujew** [comment]
Hey @kalyan3d,

the electron example in this repo does not contain an app icon, therefore this is working as intended. If you need an example on how to add an icon to a Theia app, please refer to the [Theia-IDE repo](https://github.com/eclipse-theia/theia-ide).

**Comment by kalyan3d** [comment]
Closing as it is available in Theia IDE repo.
