### ISSUE TITLE
Revisit the inversify's `toDynamicValue` usage

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#1465]
Replace it with `toService` where applicable.

See: 
 - https://github.com/theia-ide/theia/pull/1273#discussion_r168219297
 - https://github.com/theia-ide/theia/pull/1294#pullrequestreview-97462580
 - https://github.com/theia-ide/theia/pull/1345#discussion_r170682422
 - https://github.com/theia-ide/theia/pull/1438#discussion_r173071605
 - etc...

**Comment by svenefftinge** [comment]
Also, in many cases it could be a simple to-binding, as the right hand side is never injected anywhere else.

**Comment by vince-fugnitto** [comment]
I believe the following PR handled most occurrences https://github.com/eclipse-theia/theia/pull/3153
Is the issue still applicable/valid?

**Comment by tsmaeder** [comment]
@kittaakos please close if this has been sufficiently addressed. Btw: why is "toDynamicValue()" a bad thing that needs to be replaced?

**Comment by kittaakos** [comment]
> why is "toDynamicValue()" a bad thing that needs to be replaced?

It's not a bad thing, but the `toService` API is better for this use-case: https://github.com/inversify/InversifyJS/issues/583

**Comment by msujew** [comment]
I believe we can close this. I couldn't find any usage of `toDynamicValue` that can be replaced with `toService` anymore.
