### ISSUE TITLE
Shift + Space should output a space (blank) character in the editor unless other key bindings are used

### ISSUE THREAD

**Issue by ReasonSharp** [eclipse-theia/theia#14665]
### Bug Description:
I'll often write SQL in the editor and capitalize keywords by holding down the SHIFT key. This means I will hold the SHIFT key while typing the space character as well (and sometimes will still hold the SHIFT key when I press the spacebar after I type other characters in code, such as {}!<>, etc. due to typing speed), as I do in multiple other IDEs and editors.

However, recently Theia stopped recognizing Shift + Space as me intending to type a space character, causing syntax errors and/or poorly formatted code.

I've checked for key bindings and indeed there was the Shift + Space and Ctrl + Shift + Space key binding to some actions I've never used, so I removed those. However, this hasn't resolved the issue - Shift + Space still doesn't type the space character as expected, even after restarting Theia.

### Steps to Reproduce:

1. Focus the editor
2. Press Shift + Space (the blank whitespace character will not be typed)
3. Remove all key bindings related to Shift + Space and restart Theia
4. Press Shift + Space while focused on editor (still, the blank isn't typed)

### Expected Behavior:
When pressing Shift + Space in code editor, Theia should place a blank whitespace character (0x20) at cursor position, as is the case with virtually all other editors, consoles, etc.

### Additional Information

- Operating System: Debian
- Theia Version: 1.57.0

**Comment by JonasHelming** [comment]
Thank you for the report. This is almost certainly a regression of https://github.com/eclipse-theia/theia/pull/14393
But what I don't get is why it does not work if you unbind the new command (inline completion). I will try to reprduce this and we should probably bind the inline completion to something else then.

**Comment by JonasHelming** [comment]
First identified issue is the the override of default commands does not work as expected, see https://github.com/eclipse-theia/theia/issues/14667 (I already pushed a fix)

**Comment by JonasHelming** [comment]
Second, this https://github.com/eclipse-theia/theia/pull/14669 changes the default of the trigger inline suggestion to Ctrl+Alt+Space to avoid the issue you reported in the first place.

**Comment by tsmaeder** [comment]
What's the trigger for "inline suggestion" in VS Code? No need to be different.

**Comment by JonasHelming** [comment]
None! The default of Github Copilot is to trigger automatically on the fly, which can be pretty annoying. Our default is via a key binding (you can turn automatic on)
