### ISSUE TITLE
Improve handling of large files

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#1470]
Currently, we keep the document buffers on the client and send the full file contents back and forth on save and some other operations (LSP). This is, of course, a bit naive and needs improvements.

I propose that we move the resources and documents to the backend, such that the communication between the monaco model and the backend documents will go through text edits and versioned documents. The contents only should need to be transferred once, when opening an editor. Fetching contents could be done through a regular GET, such that we don't need to wrap large files in JSON objects, hence can omit the parsing. The language clients could be moved to the backend, too.

**Comment by svenefftinge** [comment]
This also should be a good step towards collaborative editing and a sandboxed extension system like VS Code's.

**Comment by svenefftinge** [comment]
Before we go down that road, which will change some important parts in the architecture, we would like to try improving the protocol in the fs, to work with incremental changes.

The idea is that we 
 - fetch the contents on open once (through GET)
 - use hashes to communicate and compare document contents in file changes
 - send text edits instead of full contents on change

**Comment by akosyakov** [comment]
I don't think it is feasible anymore after https://github.com/eclipse-theia/theia/pull/7908 We will need to open an issue in VS Code to apply such improvements there first.
