### ISSUE TITLE
Focus issue in Firefox

### ISSUE THREAD

**Issue by gindik** [eclipse-theia/theia#1478]
This issue occurs only in Firefox, when embedding Theia through an IFrame. Steps to reproduce:

 - Open a file in Theia
 - Focus out of the IFrame (into any control of the host page)
 - Focus back into the Theia editor

Expected result: the editor should be back in focus (tab with filename should be underlined) and the content of the text should be editable.

Actual result: the editor remains out of focus (tab with filename is not underlined) and typing seems to have no effect on the content of the file

**Comment by kittaakos** [comment]
> This issue occurs only in Firefox, when embedding Theia through an IFrame.

@gindik, do you happen to have a git repository we can just use and clone to reproduce the defect? That would be helpful. Thanks!

**Comment by jopit** [comment]
Something similar (but worse) is happening when using Edge on Windows 10, even when Theia is not embedded in an iframe.

On a Windows 10 machine with Docker installed, I pulled and ran the latest Theia docker image from theiaide/theia on Docker Hub.  When I open Theia in Edge, and edit a file, as soon as I click anywhere in the text of the file, the edit window loses keyboard focus and I can't make changes.

The only way to recover the ability to edit is to click on a file in the tree view, then hit tab to move keyboard focus into the edit window, and then only use the keyboard to move around in the file.

**Comment by tsmaeder** [comment]
@gindik I cannot reproduce this on Firefox 86 / Windows 10. Please reopen if it's still an issue.
