### ISSUE TITLE
[typescript] improve error message when LS doesn't start correctly

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#1481]
It can happen that the TypeScript compiler [is missing](https://github.com/theia-ide/theia-apps/issues/29), when running Theia outside the development environment (e.g. docker images from theia-apps). This causes the TS LS to not start correctly. 

The message then given to the user is generic and doesn't help much : ```"Failed to start language server 'TypeScript'"```

We should have a message similar to the one for the C/C++ language client, which is more informative:

 https://github.com/theia-ide/theia/blob/e0222f81ddb35a2cdd862f8de81078bfe5b8ce4e/packages/cpp/src/browser/cpp-client-contribution.ts#L41-L58

The error message is customized to give the user useful info about the issue. In this case, we could tell the user to make sure they have the compiler installed:  ```npm install -g typescript```

**Comment by kittaakos** [comment]
See: https://github.com/theia-ide/typescript-language-server/issues/28

**Comment by tsmaeder** [comment]
Languages packages are gone.
