### ISSUE TITLE
fine-grained CSS variables

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#1486]
We use CSS variables for theming. Right now most of the variables are generic and changing them can break some parts of UI. It would be nice to introduce semantic specific CSS variables to have more fine-grained control.

**Comment by svenefftinge** [comment]
I don't think they should be extension specific, but they should be semantic. I.e. naming common UI elements, like we started doing with the scrollbar, buttons and dialogs already.

**Comment by spoenemann** [comment]
@akosyakov how is this related to #1504? Do you propose to replace the existing variables using new names, or to add new variables in addition to the existing ones?

**Comment by akosyakov** [comment]
No, it is not related, it is about adding new variables.

**Comment by spoenemann** [comment]
Could be of help here:
https://code.visualstudio.com/docs/getstarted/theme-color-reference
