### ISSUE TITLE
Have an integration for Gerrit

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#1509]
In Eclipse we had the [EGerrit](https://www.eclipse.org/egerrit/) plugin, that enabled to do code reviews from the IDE. There might be interest to have something similar for Theia

**Comment by JonasHelming** [comment]
There are VS Code extensions that you could use for this, e.g. https://marketplace.visualstudio.com/items?itemName=tht13.gerrit-vscode
I suggest to close this, cuase there are solutions and due to inactivity.
@marcdumais-work : Please reopne if you think this is still relevant
