### ISSUE TITLE
Starting the theia app from a directory other than where the `package.json` will mess up the ApplicationPackage

### ISSUE THREAD

**Issue by epatpol** [eclipse-theia/theia#1515]
If you start the backend from somewhere else like said [here](https://github.com/theia-ide/theia/issues/734) the `ApplicationPackage` won't be aware of the extensions and application infos. Things like the extension manager and the about dialog will break because they're missing informations about the app.

Like @akosyakov mentionned on Gitter it should probably be fixed by improving `ApplicationPackage`

**Comment by vince-fugnitto** [comment]
I don't believe the issue is valid anymore.
