### ISSUE TITLE
[linter] Make sure linter errors make the build fail

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#1527]
For instance, one can use `let` instead of `const` without a build failure.
See https://github.com/theia-ide/theia/pull/1521#discussion_r175043384

**Comment by vince-fugnitto** [comment]
Verified the issue using #7227 and confirmed that the use case does fail the CI successfully ✅ 
Closing the issue for the moment, and will re-open if the problem ever re-occurs.
