### ISSUE TITLE
Help-> about menu content is "fragile"

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#1529]
From gitter discussion, it came out that the help->menu extension information is sensitive to where Theia is started; I think there is an expectation that Theia is started in the same directory in which the application's package.json is located. If Theia is started from elsewhere, the menu end-up being almost empty, with no useful version information.

This happens in a few cases, like starting the Theia backend from VS Code in debug launch. I also had the issue with some internal Docker images (I have not yet tried with our image in theia-apps). 

It would be good to mitigate those issues. Maybe update the VS Code launch(es) and if needed adjust our docker images so that Theia is started in such a way that the menu works.

for VS Code, @akosyakov suggested we change (at least) the "Launch Backend" launch to add the "cwd" option in ```.vscode/launch.json```: 
```"cwd": "${workspaceRoot}/examples/browser”```

**Comment by lmcbout** [comment]
just be careful,
The command @akosyakov suggested, we need to adjust the last ”, we need to change it to "  (Th quotes are pointing left and the good one is pointing down.

command:  "cwd": "${workspaceRoot}/examples/browser"

Also, I though we were implementing this command in the file ( .vscode/launch.json), so everyone could benefit from it !
Another question, do we need to implement it also for the electron module as well!

**Comment by epatpol** [comment]
Not only is the Help -> about menu "fragile", but the extension manager isn't going to work at all either in this case.

**Comment by vince-fugnitto** [comment]
I've attempted to reproduce the issue but could not.

> this happens in a few cases, like starting the Theia backend from VS Code in debug launch...

I ran the following launch config use case (`launch backend`), and the result of the `About` menu was in fact correct.

**Comment by vince-fugnitto** [comment]
I've retried again and it still works correctly:
- first launch the backend through VS Code
- then launch the frontend through VS Code

The `About` menu does in fact show the correct content. I will close the issue as I don't believe there is a bug any longer, if the problem ever persists or through further testing we see that there is still in fact a bug, we can always re-open.
