### ISSUE TITLE
Improve Help->About Dialog

### ISSUE THREAD

**Issue by epatpol** [eclipse-theia/theia#1547]
I think it could be useful to show on the frontend what architecture the backend is running on and with what node.js version. VS code does it also.

**Comment by kittaakos** [comment]
> backend is running on and with what node.js version.

As a user, I can use two different Node.js versions in two separate terminals with [`nvm`](https://github.com/creationix/nvm). Where did you find this feature in VSCode?

**Comment by epatpol** [comment]
@kittaakos I just looked at what vscode does currently with the Help->About and I though the running node version shown could also be useful. See below:

![screenshot from 2018-03-20 10-30-26](https://user-images.githubusercontent.com/2881761/37660979-141b56bc-2c2a-11e8-94ad-0108ae9043fc.png)

In our case that would be the version of node the backend is running on, not the one I'm developing something with maybe? Unless I misunderstood above.

**Comment by kittaakos** [comment]
OK, go ahead then. I do see why this would be useful but most likely it's just me.

By the way, there is no Help > About on OS X. It is under Code > About ... and it does not show the Node.js version.

<img width="285" alt="screen shot 2018-03-20 at 15 53 50" src="https://user-images.githubusercontent.com/1405703/37662239-ecfe4328-2c56-11e8-9211-470dca0edae6.png">

**Comment by epatpol** [comment]
Ah I see, well just having the mac os version is good info as well so thank you for that.

**Comment by kittaakos** [comment]
Please, do not get me wrong, go ahead if you think it is useful. I just do not know what could a user do with the Node.js version that runs the backend.

**Comment by JonasHelming** [comment]
Thank you again for the report. However, it seems, there is no urgent need for displaying this information. As no contribution was made, I close this due to inactivity. Please feel free to reopen if you believe this is still relevant
