### ISSUE TITLE
Java Language Server doesn't build newly added project

### ISSUE THREAD

**Issue by jopit** [eclipse-theia/theia#1558]
Using browser based Theia, I have a workspace that contains a Java project, the Java LS populates it with it's metadata files (.project and .classpath) and builds it ok.  I then add a second folder, containing a different Java project.  When I edit a file in the new project, no metadata files are created and  I get a message from the language server that the classpath is incomplete and only syntax errors will be shown.

If I hit the reload button on the browser tab containing Theia, the language server will then create the metadata files for the new project and successfully compile it.

**Comment by svenefftinge** [comment]
@gorkem Is that something that should be handled by the JDT LS?

**Comment by gorkem** [comment]
I was looking at jdt.ls integration and I think there is some sort initialization issue that causes jdt.ls to work on a limited capacity. I will send some patches for it.

**Comment by gorkem** [comment]
@jopit How do you add the second folder? Using `Open..` menu item or some other way?

**Comment by tsmaeder** [comment]
I guess this refers to the java _extension_ closing
