### ISSUE TITLE
Formatting breaks codeLenses

### ISSUE THREAD

**Issue by gorkem** [eclipse-theia/theia#1577]
When the formatting from and LSP is applied the code lenses are not updated and the locations of the code lenses becomes incorrect. I have also noticed the same behavior with 'organize imports' command on jdt.ls

![formattingbroken](https://user-images.githubusercontent.com/82738/37857090-bb3e48cc-2ece-11e8-83de-35027abb2f92.gif)

**Comment by JonasHelming** [comment]
I have tested this and it works fine for me. I will close the issue, please reopen if the problem still persists!
