### ISSUE TITLE
[navigator] disturbing scroll behavior on selection

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse-theia/theia#1593]
In some situations (after expanding / collapsing / scrolling a larger tree for a while) selection scrolls the selected element away. This makes it almost impossible to open an unselected element.

![screencast 2018-03-28 08-54-44](https://user-images.githubusercontent.com/377752/38013651-2f5930c4-3266-11e8-9537-a2765bae842a.gif)

**Comment by JanKoehnlein** [comment]
Reloading the page might also be involved to reproduce

**Comment by jbicker** [comment]
Can't reproduce.

**Comment by kittaakos** [comment]
> Can't reproduce.

It happens only when you have "manually" scrolled. See: https://github.com/theia-ide/theia/issues/3347

**Comment by vince-fugnitto** [comment]
@jbicker I tried to look into the issue but could not find a proper solution, perhaps you'd know more.
Unfortunately the odd scroll behavior is one of the more annoying usability glitches in Theia :disappointed:

**Comment by akosyakov** [comment]
I think there is a race when we updated rows to render and a selected row, so sometimes it goes out of sync and something bogusly is selected. It is just a guess, someone has to verify.
