### ISSUE TITLE
Is there a way to hide root?

### ISSUE THREAD

**Issue by travis1111** [eclipse-theia/theia#1602]
So in left files navigation view, the top element is set to the workspace root, for example, if my workspace root is `/home/myroot`, and underneath it has two folders, `a` and `b`.  By default, the files navigation view shows `myroot` as the top element.  Is there a way to hide `myroot` so in the files navigation view, we do not see `myroot`, instead, we see `a` and `b`?

thanks

**Comment by epatpol** [comment]
I thought there was already an issue opened about this somewhere, but I can't find it. But yes I agree it would be better not to show the root (like VS code).

**Comment by kittaakos** [comment]
> Is there a way to hide myroot

No, unfortunately, it is not yet supported. I could assist you if you would like to contribute.

**Comment by vince-fugnitto** [comment]
The `explorer` behavior has been updated to be aligned with the behavior present in vscode in which we display the workspace root as the widget's title. Only in the case of a multi-root workspace are the workspace folders visible.

<div align='center'>

<img width="610" alt="Screen Shot 2020-01-16 at 5 57 29 PM" src="https://user-images.githubusercontent.com/40359487/72569986-ae0d3e80-3889-11ea-8558-d387a125b456.png">


</div>
