### ISSUE TITLE
Possible improvements in the Windows building documentation

### ISSUE THREAD

**Issue by epatpol** [eclipse-theia/theia#1614]
I just tried to build Theia in a windows 10 developer vbox image and following the steps [here](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#building-on-windows) to build it several steps failed. 

`choco install yarn --version 1.2.1 -y` Failed because we already installed a later version (1.5.0) at the time of this writing beforehand. But I also wondered if you couldn't install this one directly without doing that `choco install yarn` command before.

Also I noticed that we use both `cmd/Powershell/Git bash` just to build and run theia according to the docs. Maybe there's a good reason for using git bash but If possible I would like to avoid having that dependency in the documentation. It makes it so that new developers have to *possibly* install another program before running it. @kittaakos I know you tested a lof of stuff of Windows, so probably there's a valid reason for this (I just tried `yarn` in powershell and it didn't work and resulted in weird errors...).

**Comment by kittaakos** [comment]
> to build it several steps failed.

That is unfortunate. Documentation could get quickly out of sync.

> choco install yarn --version 1.2.1 -y Failed because we already installed a later version (1.5.0)

I do not understand this implication, but it could happen, we need to adjust the version numbers. I do not know the default `yarn` version on the AppVeyor image we are currently using, but I am positive, we still have `yarn` `1.2.1`for both the [Linux and the OS X builds](https://github.com/theia-ide/theia/blob/cd757dbd10059d65e4ff86f41f9ed01af511a928/.travis.yml#L30). I think I still use `1.2.1` on my local Windows image too. Worked so far.


> we use both cmd/Powershell/Git bash just to build and run theia according to the docs

Correct.

> Maybe there's a good reason for using git bash

There is. My Windows knowledge is pretty limited, but Windows does not come with Git by default. The out of the box solution is the Git installer that comes with Git Bash, right? By the way, I usually use either Cygwin or Git Bash on Windows.

> I would like to avoid having that dependency in the documentation

If you have a better approach, please, be my guest, adjust it; I could help verifying things on Windows. Our goal is to help Windows users start using Theia.

> It makes it so that new developers have to possibly install another program before running it

Ohh, they have to do that anyway; MS Build Tools, Python...

> it didn't work and resulted in weird errors...

I have to see the full console log from the very beginning (installing Python and so on) to the last failing `yarn` command to be able to see what went wrong.
