### ISSUE TITLE
Clojure syntax highlighter

### ISSUE THREAD

**Issue by avelino** [eclipse-theia/theia#1717]
![screenshot 2018-04-17 10 58 19](https://user-images.githubusercontent.com/31996/38874385-5019a50a-422e-11e8-85fc-7454f9e90071.png)

**Comment by kittaakos** [comment]
I am not aware of any Theia Clojure extension. Without that, you will get neither syntax coloring, nor LS support. @akosyakov, do we have support for Clojure?

**Comment by akosyakov** [comment]
We have coloring for languages from monaco-languages: https://github.com/Microsoft/monaco-languages/tree/master/src It does not seem to be there. You are welcome to open a PR there or create a Theia extension.

**Comment by svenefftinge** [comment]
Also there is https://github.com/snoe/clojure-lsp

**Comment by avelino** [comment]
@kittaakos  now the `monaco-languages` is supported Clojure, should be updated something in this repository?
refs:
https://github.com/Microsoft/monaco-languages/pull/36
https://github.com/Microsoft/monaco-editor/issues/828#issuecomment-393477284

**Comment by marcdumais-work** [comment]
@avelino I think we have a plan to upgrade to the latest monaco, sometime in the next month or two. Assuming this support is released by then, we should pick it up.

**Comment by avelino** [comment]
Almost 1 year was accepted the [PR](https://github.com/Microsoft/monaco-languages/pull/36), was updated the **monaco-editor** in Theia-IDE?

**Comment by akosyakov** [comment]
We don't use monaco-languages, but textmate grammars. There is already textmate grammar for clojure: https://github.com/theia-ide/theia/blob/master/packages/textmate-grammars/src/browser/clojure.ts It should work out of the box.

**Comment by vince-fugnitto** [comment]
Clojure syntax highlighting is now contributed by [`vscode-builtin-clojure`](https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/clojure-1.39.1-prel.vsix) (related PR #6883).

**Comment by vince-fugnitto** [comment]
Closed by #6883
