### ISSUE TITLE
Set connection configuration option

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-theia/theia#1721]
How do I set connection configuration options such as https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/messaging/connection.ts#L81 ?

**Comment by epatpol** [comment]
Right now it's not an option I believe, although it was discussed beforehand that maybe it should.

**Comment by JamesDrummond** [comment]
@epatpol Maybe set it via environment variables. This seems to be a the easiest solution. If later a configuration file is needed it would just set environment variable if not set already globally. 

```
const maxReconnectionDelay= GetEnvironmentVar("THEIA_MAXRECONNECTIONDELAY",10000);
.....
            const socketOptions = {
                maxReconnectionDelay: maxReconnectionDelay,
.....
            };
```

**Comment by epatpol** [comment]
Yes, we actually already have an env variable server which can be used to easily fetch the variable value from `connection.`ts [here](https://github.com/theia-ide/theia/blob/aef8737c78bc499ae156e9837895ef7b0d0b4e04/packages/core/src/common/env-variables/env-variables-protocol.ts). PRs are welcome :)

**Comment by JamesDrummond** [comment]
@epatpol How do I use the environment server?

**Comment by epatpol** [comment]
You need to inject it in the `WebSocketConnectionProvider` and use it afterwards. Look at how we inject an instance of `ILogger` in `KeybindingRegistry` for instance.

**Comment by svenefftinge** [comment]
Aren't those numbers too high anyway? It's good to be able to configure it through envs but we should have good defaults, too. @JamesDrummond what is the reason you want to change them?
