### ISSUE TITLE
[terminal] Spawning terminals too quickly merges them together inside one panel

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#1733]
TThhiiss iiss wweeiirrdd.

![echo_wat](https://user-images.githubusercontent.com/14182238/38952684-75315c24-431a-11e8-9a68-2ce1e0795c86.gif)

(~~using~~ spamming the `ctrl + backtick` shortcut)

**Comment by rv2e** [comment]
Recently, we've started to use Theia in my company and we also noticed this issue. Do you have an idea when you'll work on a fix and what is the underlying problem?

**Comment by marechal-p** [comment]
It has been a long time since I last encountered this bug. If it still happens, one would have to debug the terminal spawning and dig into how one xterm widget hooks itself to the remote terminals.

**Comment by FernandoAscencio** [comment]
The bug is still present. With the change of keybinds now it happens with `Ctrl`+`Shift`+`` ` ``
![Issue1733](https://user-images.githubusercontent.com/48699277/221017741-26fc12e7-c5c0-4343-9c1c-17c25faddc45.gif)
