### ISSUE TITLE
Wrong underline when hovering over a Typescript import while holding ctrl 

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#1766]
If you hover over the `logger` word of the `"./logger-cli-contribution"` part of this line while holding ctrl:

    import { LogLevelCliContribution } from "./logger-cli-contribution";

the underline will span only `logger`.  It should span the whole module name.  We would probably need the language server to tell us the span of the pointed token when doing a findDefinitions (which is what is used for ctrl-hovering IIRC).

**Comment by vince-fugnitto** [comment]
The bug has been resolved, likely since we switched to using `builtin` support for JS/TS.
