### ISSUE TITLE
[search in workspace] For replace use more generalised solution

### ISSUE THREAD

**Issue by jbicker** [eclipse-theia/theia#1788]
Depends on https://github.com/theia-ide/theia/issues/1756
After it is solved we should use that instead of https://github.com/theia-ide/theia/blob/SearchAndReplaceInWorkspace/packages/editor/src/browser/editor.ts#L89

**Comment by FernandoAscencio** [comment]
Is this still an issue?
The link to code now gives a 404 error message and Issue 1756 seems to be closed.
