### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#180]
User facing strings shall be able to be translated

Add support for internationalization in Theia, and translate strings used in the UI in at least one other language as an example. 

Two potential candidate libraries to help with this: 

https://github.com/globalizejs/globalize
https://github.com/messageformat/Jed

**Comment by lmcbout** [comment]
After investigation, It looks like the version that we  will implement is Globalize. It seems easier and a complete solution to internationalize the string in Theia. It has also some code to handle the date and number format. This solution seems a better fit.

**Comment by marcdumais-work** [comment]
Original attempt to add internationalization: https://github.com/theia-ide/theia/pull/396

**Comment by amiramw** [comment]
Is right to left support covered in this issue?

**Comment by JonasHelming** [comment]
@spoenemann : You mentioned you want to work on this topic. If you created a new ticket for this, please close this one...

**Comment by spoenemann** [comment]
This is continued here: #1327
