### ISSUE TITLE
add code format for erlang elixir

### ISSUE THREAD

**Issue by mrbnarayan** [eclipse-theia/theia#1818]
New help to add code highlighting for erlang and elixir.

**Comment by akosyakov** [comment]
We rely on monaco-languages for basic syntax highlighting: https://github.com/Microsoft/monaco-languages Could you open an issue there as well?

**Comment by vince-fugnitto** [comment]
The syntax highlighting should now be contributed by vscode extensions as language-specific extensions are deprecated in the framework. For example:
- https://open-vsx.org/extension/pgourlain/erlang
