### ISSUE TITLE
UI for displaying commands

### ISSUE THREAD

**Issue by dvc94ch** [eclipse-theia/theia#1826]
`<leader>` opens a popup window showing the next possible keys. If it is not a leaf node a category label shall be displayed.

All commands are also accessible via their id through `<leader> <commands-by-id>`.

Relates-to: #1816

**Comment by vince-fugnitto** [comment]
@dvc94ch I undertand the issue is quite old, but I am having trouble trying to understand the feature request. Are you looking for a UI to view commands, keybindings, and be able to edit them?
If so, the corresponding widget is the `keybindings-widget`.

**Comment by vince-fugnitto** [comment]
Please re-open the issue when you can with additional information.
