### ISSUE TITLE
Documentation system

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#186]
How the documentation is created and it’s lifecycle managed.
- Framework is documented with:
 - API automatic documentation

 - Examples for extension writers (examples should be directly in code in the form of tests so that they don’t get outdated)
 - Overview of architecture
 -  Contribution guide
- IDE  is documented with:
  - Installation guide (as a user)
  - Getting started guide (as a user)
  - Visual overview of the main features (using animated gifs)
  - Contribution guide
  - Contributor workflow guide

**Comment by lmcgupe** [comment]
- API automatic documentation
    - The documention is generated automatically using the typedoc tool. To generate it, simply issue the yarn docs command from the project's root directory. The resulting packages will be generated under each  package. Ex: packages/core/docs.
    -  Once this documentation is produced, it can be published by leveraging the github feature called git hub pages. 

    - GitHub Pages lets the project's documentation live alongside code on GitHub

     - Phoshor example:
       https://github.com/phosphorjs/phosphor. In the README.md file, a link refers to http://phosphorjs.github.io/. There, a web page hosted by github, documents the Phosphor project.

       In the upper section of the page, a hyperlink called DOCS (http://phosphorjs.github.io/docs.html) opens up another page which hosts the actual access to the API documentation that was automatically generated by typedoc.

     - The documentation is hosted on a special branch named gh-pages that coexists with master. Github has extensive support for hosting a web site which can be used, in the case of  the thiea project, as a platform for documentation.

     - Here are the steps in a nutshell.
         create a git branch named gh-pages (a detached orphan branch)
         from master, do:
         git checkout --orphan gh-pages
         add files like index.html
         git add index.html
         git commit -m ...
         git push -u origin gh-pages

     - For further information, several links with tutorial and information are available. Below are a few.

        References:
        https://github.com/blog/2233-publish-your-project-documentation-with-github-pages

        github pages tutorial:
        https://youtu.be/RaKX4A5EiQo

**Comment by svenefftinge** [comment]
Gitbook (https://github.com/GitbookIO/gitbook) looks good. I'd like to give it a try.

**Comment by JonasHelming** [comment]
@marcdumais-work : I think all bullets above are covered in the meantime. There is certainly room for imporvement, but I believe we can close this initial issue.

**Comment by JonasHelming** [comment]
I am closing this now, @marcdumais-work feel free to reopen if you think something is missing
