### ISSUE TITLE
Home/end keys don't work in the terminal

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#1870]
Home/end in the terminal don't work, to get to the beginning/end of the input line.

**Comment by kittaakos** [comment]
@simark, when you mark an issue with the `beginners` label, please add some instructions, so it is straightforward for the newcomers what to modify and where. Thanks!

**Comment by simark** [comment]
So I thought it would just be adding some passthrough keybindings (see 472d5b5adf03c06c7768a2103ca537e09cb4cd00), but it appears to be more complicated than that.  I'll just remove those tags.

**Comment by simark** [comment]
As a reference, home and end work in the xterm.js demo.

**Comment by vince-fugnitto** [comment]
I verified the behavior and it is working correctly :+1: 

<div align='center'>

![terminal](https://user-images.githubusercontent.com/40359487/88178596-a348b300-cbf8-11ea-99e3-cb7769182d76.gif)


</div>
