### ISSUE TITLE
Ctrl/Cmd+W should close tabs in Electron

### ISSUE THREAD

**Issue by MarkZ3** [eclipse-theia/theia#1890]
In the Electron version, Ctrl/Cmd+W should close tabs instead of Alt/Option+W. This is in line with browsers and other IDEs. It also feel more natural because switching tabs is Ctrl+Tab.

**Comment by MarkZ3** [comment]
> Actually what's the alternative for switching tab in the browser? Ctrl+Tab doesn't seem to work for me.

Yeah, I created GH-1891 for that.

> Maybe we should have a way for keybindings to be registered differently when on the electron version. Kinda like how you can supply a different key binding for mac in vscode, but in our case it would be for browser/electron.

Yes, that's what I think. Between having inconsistent key bindings of browser vs Electron and having worse experience in Electron, I'd rather have the keys be inconsistent. It won't be all of them anyway.

**Comment by vince-fugnitto** [comment]
I verified that the issue is resolved (electron):

https://github.com/eclipse-theia/theia/blob/be686eef3e394bc521480fe8203aa7467e2cb98b/packages/core/src/browser/common-frontend-contribution.ts#L903-L906
