### ISSUE TITLE
[Git history] Filter by Name, Date, Committer, etc

### ISSUE THREAD

**Issue by jbicker** [eclipse-theia/theia#1920]
If one searches for an old commit it can be very difficult to find it. Would be nice to have a filter which supports searching by name, date, committer, etc etc...

**Comment by kittaakos** [comment]
Just a quick question on this: did you mean filtering the results on the frontend or by somehow performing a `git log` that returns with the already filtered items?

**Comment by jbicker** [comment]
Since we do lazy loading with long history lists, we should consider to filter it somehow in the backend.

**Comment by kittaakos** [comment]
https://git-scm.com/book/it/v2/Git-Basics-Viewing-the-Commit-History#rlimit_options

**Comment by JonasHelming** [comment]
Closing this, as we deprecated our own git extension
