### ISSUE TITLE
Menu items do not respect isVisible

### ISSUE THREAD

**Issue by spoenemann** [eclipse-theia/theia#1921]
Register a command with this handler
```typescript
{
    execute: () => {},
    isEnabled: () => false,
    isVisible: () => false
}
```
and add it to the menu. The menu item is disabled, but visible.

**Comment by spoenemann** [comment]
See also #105.

**Comment by kittaakos** [comment]
Also: https://github.com/theia-ide/theia/issues/446.

**Comment by vince-fugnitto** [comment]
The issue seems outdated, menu items respect visibility.
