### ISSUE TITLE
[question][extensions] Theia minimal configuration packages as an IDE

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#1961]
When opening the "Extension"view, it shows all Theia pakages; i.e core, output, filesystem ...
Why do we allow to uninstall all of those packages, if the user uninstall the "@theia/core", Theia IDE will not exist !

Shouldn't we remove the option to uninstall the essential packages for Theia to live  as a minimal IDE ?

**Comment by kittaakos** [comment]
+1 for leaving it as is. I would not distinguish between extensions. For instance, `@theia/output` is not mandatory. But this is just my opinion.

**Comment by vince-fugnitto** [comment]
@lmcbout I will close the issue for the moment since the `extensions` view is deprecated.
I want to try and cleanup and only keep relevant issues for the moment I hope you understand :)
