### ISSUE TITLE
Escape should close Code Lens results

### ISSUE THREAD

**Issue by MarkZ3** [eclipse-theia/theia#1969]
For example, if you open a Java file, it shows the number of references with CodeLens. If you click on one, it shows the references. But you cannot press Escape to close the popup. In comparison, if I do "Find References" on the same symbol, then I can press Escape to close the results.

I also saw this in C/C++ (Clangd) so it seems general.

**Comment by msujew** [comment]
This doesn't seem to be reproducible anymore, with the code lens for references in TypeScript. One of the many monaco upgrade probably fixed this.
