### ISSUE TITLE
Initialize Git Repository with Theia

### ISSUE THREAD

**Issue by jeanlucburot** [eclipse-theia/theia#1974]
So, I didn't find any way to initialize a Git Repository using Theia in the browser. Hence, I guess this would be a feature request to be able to do that.

![image](https://user-images.githubusercontent.com/38067850/40612473-fe28b2be-627a-11e8-819d-e0df387a7437.png)

**Comment by svenefftinge** [comment]
The git view doesn't make sense when there is no git repository. Instead, a button `Initialize Git Repository` should be rendered, that when clicked calls a command that runs `git init`.

**Comment by jeanlucburot** [comment]
Indeed it would be quite convenient to have just a blue button "Initialize" instead of the current Commit button and above textbox.

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/6008 🍾

**Comment by hannescmarits** [comment]
The button + is no longer available. Instead the following warning is displayed:  "No repository found".
Now it works by F1> Git:  Initialize Repository. 
Maybe providing the possibility to select a Folder would be nice.
