### ISSUE TITLE
Handle readonly files

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#199]
- [ ] `FileStat` should have access flags. There should be utility methods to check flags on read, write and execute access
- [ ] `FileTreeModel` should mark file stat nodes without read access as invisible
- [ ] `Resource` should have an explicit optional `isReadonly` property with default based on the presence of `Resource.save` method. There should be a utility function to check it.
- [ ] `FileResource` should use `FileStat` flags to implement `isReadonly` property
- [ ] editor providers should use `Resource.isReadonly(resource)` to mark editors readonly or not

**Comment by hexa00** [comment]
I disagree that some files should be invisible you have the right to see them... but an error should be thrown when you try to open ?

**Comment by akosyakov** [comment]
I meant if the user doesn't have rights to see them he should not see them.

**Comment by hexa00** [comment]
Then it's the directory that does not have read access and thus you won't be able to get to the file at all...

Otherwise I can see a no permission file with ls without any problems:
----------  1 x x        0 Jun 13 08:22 testfi

**Comment by akosyakov** [comment]
PRs are welcomed.

**Comment by epatpol** [comment]
Would you rather have the fs.modes for the filestat (i.e bitmasks) or easier API like `Filestat.isReadable: boolean`, `isWriteable`, `isExecutable` and so on? Like so:

```
export interface FileStat {

    /**
     * The uri of the file.
     */
    uri: string;

    /**
     * File access
     */
    isReadable: boolean;
    isWriteable: boolean;
    isExecutable: boolean;

    /**
     * The last modification of this file.
     */
    lastModification: number;

    /**
     * The resource is a directory. Iff {{true}}
     * {{encoding}} has no meaning.
     */
    isDirectory: boolean;

    /**
     * The children of the file stat.
     * If it is undefined and isDirectory is true, then this file stat is unresolved.
     */
    children?: FileStat[];

    /**
     * The size of the file if known.
     */
    size?: number;
}
```

**Comment by akosyakov** [comment]
@epatpol Could you check how VS Code handle it? They don't seem to expose such apis, maybe we are overthinking it.

**Comment by aaqaishtyaq** [comment]
@epatpol @akosyakov Hey is there any way currently to now allow editing of readOnly files.

**Comment by dpetroff** [comment]
In theia 1.36, I set some files to read only on the file system with chmod, and all the resource, filestat, etc. properties all still say that it's not read-only.

It looks to me like `DiskFileSystemProvider` is entirely oblivious of file permissions:
 https://github.com/eclipse-theia/theia/blob/4539753ff2a6846b8b5609221b3da2fc6287cb05/packages/filesystem/src/node/disk-file-system-provider.ts#L151-L164

I think this issue should be reopened.

**Comment by msujew** [comment]
This issue will be resolved by https://github.com/eclipse-theia/theia/pull/12354 instead.
