### ISSUE TITLE
drag and drop a folder that contains a file opened in editor throws errors

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#2011]
I tested drag and drop a folder that contains a file opened in editor. 

![peek 2018-06-01 08-18](https://user-images.githubusercontent.com/37082801/40840480-d37714aa-6574-11e8-82b7-3058a4ec232e.gif)

Different from what #1366 and #1191 described, everything looked working from the UI, however, errors are logged, saying the file(s) being watched cannot be found anymore.

**Comment by kittaakos** [comment]
Thanks for logging. I would say, the current behavior is different what the earlier issues describe, because we have [changed the FS API](https://github.com/theia-ide/theia/pull/1722).

It does not mean, this bug is a duplicate. The others are outdated instead.

**Comment by vince-fugnitto** [comment]
I cannot reproduce the issue any longer (the issue is also quite old).
