### ISSUE TITLE
[inline-editor] Cannot close the inline editor with `Esc`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#2040]
- Open an inline editor with `Peek Definition`.
- Set the focus to the contained editor by clicking somewhere in the code.
- Press `Esc` the inline editor does not close.
- It works in VS Code.

VS Code:

![close_inline_editor_vscode](https://user-images.githubusercontent.com/1405703/40965535-430e45d6-68ae-11e8-86b3-4f8029b056d3.gif)

Theia:
![close_inline_editor_theia](https://user-images.githubusercontent.com/1405703/40965526-3dc06cda-68ae-11e8-8f70-2000b592da0a.gif)

**Comment by lmcbout** [comment]
On ubuntu, "ESC" seems to remove the dialog.
But if you go to an empty line (Nothing selected() and execute "SHIFT+F12) (Find All References), esc does not close the dialog, need to press the "X"

**Comment by FernandoAscencio** [comment]
Seems like it is working as intended now.
![Issue2040](https://user-images.githubusercontent.com/48699277/235240577-786df4cd-b73c-409e-b06b-e02c355e1036.gif)

**Comment by JonasHelming** [comment]
@kittaakos This works for me, could you retest and close?
