### ISSUE TITLE
Intermittent problem where new folder not shown

### ISSUE THREAD

**Issue by jopit** [eclipse-theia/theia#2048]
With 0.3.10 browser-based Theia, we are seeing an intermittent problem where a new folder created in the workspace from outside Theia isn't automatically being shown in the tree files view.

To get it to show requires refreshing the browser.

**Comment by marcdumais-work** [comment]
@jopit On Linux, one "classic" reason for this symptom is when the backend runs out of ```inotify``` watchers. If that's the case, there should be a log about it, in the backend. To show the current limit, you can try the following in a terminal: 
```
sudo sysctl -p
```

If you run in docker, that limit I think might be shared between all containers, running on a given host. This might make seem it a bit random, for example, if the limit is high enough to accommodate the first few containers, but not the rest.

**Comment by vince-fugnitto** [comment]
As Marc mentioned it is likely an issue with running out of `inotify` watchers.
Since there has not been activity in the issue for a while I will assume that the issue has been resolved on your end. Please re-open the issue if it is not the case.
