### ISSUE TITLE
[electron] Make the Browser backend serve the Electron's frontend

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#2057]
Relative to #2056 

This is part of the work required to make Electron able to connect to a remote backend: the backend must be able to provide Electron its required files.

**Comment by marechal-p** [comment]
Update: Good progress was made, here are the currently done tasks for this issue

- [x] 
- [x] 
- [x]

**Comment by marechal-p** [comment]
@lmcbout in case you want to break it
@marcdumais-work cc

**Comment by akosyakov** [comment]
@marechal-p please open a WIP PR to look at it

**Comment by marechal-p** [comment]
@akosyakov do you know why we don't use http to fetch Theia's frontend using Electron ?
I know it might be faster using the file directly from disk, but the gain is very very small.

Also there is an error when doing so, when loading monaco. How come that a protocol change will impact the loading ?

**Comment by marechal-p** [comment]
https://github.com/Microsoft/vscode-loader/issues/12
