### ISSUE TITLE
[fs][nsfw] error starting on chromebook/termux

### ISSUE THREAD

**Issue by jots** [eclipse-theia/theia#2085]
trying to run this in termux on chromebook and getting this error:
```
$ pwd
/data/data/com.termux/files/home/fromnet/theia/examples/browser
$ yarn run start
yarn run v1.7.0
$ theia start
Starting server worker...

Server worker has been started. [ID: 1 | PID: 8567]

/data/data/com.termux/files/home/fromnet/theia/packages/core/lib/node/cluster/main.js:49

    throw reason;
    ^

Error: Cannot find module '../../build/Release/nsfw.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/fromnet/theia/node_modules/nsfw/lib/src/index.js:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Server worker has been disconnected. [ID: 1 | PID: 8567]

Server worker failed to start.

Server worker has been stopped. [ID: 1 | PID: 8567]

Done in 2.4
```
This is after running yarn run build in the main dir.
has anyone gotten this to run on chromebook/chromeos without crouton?
any ideas how to fix?

**Comment by kittaakos** [comment]
@jots, what is your node version? There is a known issue with node 10. See here: https://github.com/theia-ide/theia/issues/2009

**Comment by marcdumais-work** [comment]
@jots AFAIK, you're the first one to report trying to build/run Theia on a chromebook - good/cool idea!

IIRC, ```nsfw``` has a native part, that is compiled at install time. Do you know if a chromebook comes with the required tools installed? e.g. a C++ compiler? 

Can you try to create an empty node project and add the ```nsfw``` npm module to it? e.g.: 
```
cd /tmp
mkdir test
cd test
npm init   #you can accept all proposed default values
npm i nsfw
```

**Comment by kittaakos** [comment]
> npm init   #you can accept all proposed default values
> npm i nsfw

```
npm init -y && npm i -S nsfw
```

**Comment by jots** [comment]
Thanks.  yes the problem is with nsfw.  I get errors when trying to build it.  Perhaps because termux only comes with clang and not gcc?  If I get it figured out I'll post here.
```
> nsfw@1.0.16 install /data/data/com.termux/files/home/node_modules/nsfw
> node-gyp rebuild

make: Entering directory '/data/data/com.termux/files/home/node_modules/nsfw/build'
  CC(target) Release/obj.target/openpa/openpa/src/opa_primitives.o
  CC(target) Release/obj.target/openpa/openpa/src/opa_queue.o
In file included from ../openpa/src/opa_queue.c:9:
In file included from ../openpa/src/opa_queue.h:14:
../openpa/src/opa_primitives.h:122:2: error: no primitives implementation specified
#error no primitives implementation specified
 ^
In file included from ../openpa/src/opa_queue.c:9:
../openpa/src/opa_queue.h:60:5: error: unknown type name 'OPA_ptr_t'
    OPA_ptr_t offset;
    ^
../openpa/src/opa_queue.h:67:20: warning: implicit declaration of function 'OPA_load_ptr' is invalid in C99 [-Wimplicit-function-dec
laration]
    void *offset = OPA_load_ptr(&r.offset);
[....]
```

**Comment by marcdumais-work** [comment]
@simark  or @MarkZ3  maybe you would have ideas for this? Maybe clang would need different switches to compile this vs gcc? 

Let's say we make ```nsfw``` successfully compile, do we expect that it would it work on a chromebook? AFAIK that uses a Linux kernel, but the user-space is different?

**Comment by simark** [comment]
I am not sure I understand, is this Android or ChromeOS?  Anyway, the important bit is this:

```
../openpa/src/opa_primitives.h:122:2: error: no primitives implementation specified
#error no primitives implementation specified
```

which corresponds to this: https://github.com/trevnorris/openpa/blob/master/src/opa_primitives.h#L97

So to get nsfw to work with that compiler and platform, somebody needs to port openpa to that first.

You could try to configure openpa with `--with-atomic-primitives=no`, to at least get past that point and see what's the next issue.  Taken from openpa's README

```
opa_by_lock.h - Used when you specify "--with-atomic-primitives=no" or when
                auto-detecting the primitive implementation and lock-based fall
                back is selected.  This uses pthread mutexes to emulate the
                atomic behavior.  This option typically has dramatically slower
                performance on most platforms where native primitives are
                available.  You should usually only use it for testing or on
                platforms where pthreads are available but no native primitives
                are currently implemented.  The library initialization function
                *must* be called when using this primitives implementation.
```

Note the last sentence though, I assume they talk about this function here:

**Comment by vince-fugnitto** [comment]
Closing the issue since it is quite old, and inactive. I believe the question may have been answered with the latest comment.
If the issue persists it may be worthwhile to open an issue or investigate directly in `nsfw` if it is possible to get it to work with `chromeOS`:
- https://github.com/Axosoft/nsfw.
