### ISSUE TITLE
"yarn theia build" works incorrectly for package.json which contains strict defined Theia components version

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-theia/theia#2137]
We containerized Theia build for Eclipse CHE workspaces. And for this stuff we are using package.json file with specified Theia version to build Theia with help command ```yarn theia build```.  This command  works correctly with Theia version strictly defined in the package.json. But it became broken after newer Theia release.

Steps to reproduce:
1. Create empty folder(0.3.10 because for now the latest is 0.3.11):
```mkdir -p theia-0.3.10 && cd theia-0.3.10 ```
2. Create Theia package.json  with strictly defined Theia components version, for example with such content: 
```
{
    "private": true,
    "dependencies": {
        "typescript": "2.7.2",
        "@theia/typescript": "0.3.10",
        "@theia/navigator": "0.3.10",
        "@theia/terminal": "0.3.10",
        "@theia/outline-view": "0.3.10",
        "@theia/preferences": "0.3.10",
        "@theia/messages": "0.3.10",
        "@theia/git": "0.3.10",
        "@theia/file-search": "0.3.10",
        "@theia/markers": "0.3.10",
        "@theia/preview": "0.3.10",
        "@theia/callhierarchy": "0.3.10",
        "@theia/merge-conflicts": "0.3.10",
        "@theia/search-in-workspace": "0.3.10"
    },
    "devDependencies": {
        "@theia/cli": "0.3.10"
    }
}
```
3. Build theia with help cli:
```yarn && yarn theia build```
2. Start generated theia:
```yarn theia start```
Expected result: theia should successfully start.
Actual result: theia after start is broken. Before release 0.3.11 it worked. Logs:
```
bundle.js:1 Error: No matching bindings found for serviceIdentifier: t
    at bundle.js:58
    at h (bundle.js:58)
    at e (bundle.js:58)
    at bundle.js:58
    at Array.forEach (<anonymous>)
    at bundle.js:58
    at Array.forEach (<anonymous>)
    at e (bundle.js:58)
    at Object.t.plan (bundle.js:58)
    at bundle.js:58
```
P.S.: We a bit investigate this issue and found that yarn.lock file generated after release always use "latest" artifacts instead of artifacts defined in the package.json:
[strange yarn.lock](https://gist.github.com/AndrienkoAleksandr/2b6fe641da517be08db8ee91b6ac399c)

If we manually edit yarn.lock (replace 0.3.11 to the 0.3.10 and fix dependency hashes) and rebuild Theia, then Theia starting works nice again:
[fixed yarn.lock](https://gist.github.com/AndrienkoAleksandr/aaa6efaaf7977d0951b13e6ef364150b)

**Comment by akosyakov** [comment]
I would delete yarn.lock to make sure that yarn does not try to preserve existing node modules.

**Comment by AndrienkoAleksandr** [comment]
I reproduced this issue from clear repository, without node_modules and without yarn.lock and without another auto-generated stuff.

**Comment by kittaakos** [comment]
First off, we have discussed this a couple of times. See here: https://github.com/theia-ide/theia/issues/1615

But let me try to clarify it once more. (So we can reference it later.)

When we have published for instance [`@theia/git@3.10.0`](https://www.npmjs.com/package/@theia/git/v/0.3.10) the `package.json` contained the upstream Theia dependencies as `"@theia/blabla": "^0.3.10"`. See here:

https://github.com/theia-ide/theia/blob/a4ccace67735a68624e3d65e33df1d541cc43113/packages/git/package.json#L6-L11

So even if you have pinned your version to `0.3.10` the latest valid version of a transitive import will be used instead. Some details on the "valid versions" are [here](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004). This will result in a state where for instance you have two different versions of `@theia/core`.

You can verify this with the followings:
```
mkdir theia-test \
&& cd theia-test \
&& npm init -y \
&& npm i -S --save-exact @theia/git@0.3.10 \
&& grep -r "\"@theia/core\":" .
```

(You can find more details about `--save-exact` [here](https://www.dalejefferson.com/how-to-save-exact-npm-package-versions).)

```
...
./node_modules/@theia/variable-resolver/package.json:    "@theia/core": "^0.3.11"
./node_modules/@theia/workspace/package.json:    "@theia/core": "^0.3.11",
./node_modules/@theia/output/package.json:    "@theia/core": "^0.3.11"
./node_modules/@theia/filesystem/package.json:    "@theia/core": "^0.3.11",
./node_modules/@theia/languages/package.json:    "@theia/core": "^0.3.11",
./node_modules/@theia/navigator/package.json:    "@theia/core": "^0.3.11",
./node_modules/@theia/editor/package.json:    "@theia/core": "^0.3.11",
./node_modules/@theia/git/package.json:    "@theia/core": "^0.3.10",
./node_modules/@theia/process/package.json:    "@theia/core": "^0.3.11",
./package-lock.json:    "@theia/core": {
./package-lock.json:        "@theia/core": "0.3.11",
./package-lock.json:        "@theia/core": "0.3.11",
./package-lock.json:        "@theia/core": "0.3.11",
./package-lock.json:        "@theia/core": "0.3.11",
./package-lock.json:        "@theia/core": "0.3.11",
./package-lock.json:        "@theia/core": "0.3.11"
./package-lock.json:        "@theia/core": "0.3.11",
./package-lock.json:        "@theia/core": "0.3.11"
./package-lock.json:        "@theia/core": "0.3.11",
```

As you can see there are two distinct `@theia/core` versions, that will lead to runtime problems with `inversify`.

We can either remove the caret (`^`) from the `package.json`s (probably no) or you can explicitly force the exact versions for all upstream dependencies as described [here](https://github.com/theia-ide/theia/issues/1615#issuecomment-377659319).

**Comment by kittaakos** [comment]
> bundle.js:1 Error: No matching bindings found for serviceIdentifier: t
>     at bundle.js:58
>     at h (bundle.js:58)
>     at e (bundle.js:58)
>     at bundle.js:58
>     at Array.forEach (<anonymous>)
>     at bundle.js:58
>     at Array.forEach (<anonymous>)
>     at e (bundle.js:58)
>     at Object.t.plan (bundle.js:58)
>     at bundle.js:58

Off: @akosyakov it will be super hard to give any kind of support if the `bundle.js` is minified. How can we tackle this in the future? Similar: https://github.com/theia-ide/theia/issues/1837
I [still believe](https://github.com/theia-ide/theia/pull/1540#issuecomment-374249786), the `development` mode should be the default unless `production` is not explicitly set.

**Comment by akosyakov** [comment]
We had exact versions at the beginning and it leads to duplicate packages, since 0.3.11 won't be compatible with 0.3.10. Using carets loosen up version constraints and make packages within 0.3.x compatible.

@AndrienkoAleksandr could you try to use carets as well, so `^0.3.10` instead of `0.3.10` and to upgrade just remove yarn.lock and run `yarn` again it should pick up the latest `0.3.x` version.  

When a new major is released, i.e `0.4.x`, it won't be compatible with `0.3.x` and versions has to be upgraded to `^0.4.0`.

> Off: @akosyakov it will be super hard to give any kind of support if the bundle.js is minified. How can we tackle this in the future? Similar: #1837
I still believe, the development mode should be the default unless production is not explicitly set.

There is a way to configure webpack to preserve proper stacktraces but still does not expose source maps in production mode. We can investigate it and discuss whether we want to have it by default, as another issue.

**Comment by kittaakos** [comment]
> There is a way to configure webpack to preserve proper stacktraces but still does not expose source maps in production mode

👍

> whether we want to have it by default, as another issue.

I agree.

**Comment by msujew** [comment]
I don't think this issue is relevant anymore. Theia dependencies are now always pinned, and users are recommended to use pinned versions.
