### ISSUE TITLE
Developing an application against a fork of Theia

### ISSUE THREAD

**Issue by thegecko** [eclipse-theia/theia#2192]
During [last week's dev meeting](https://github.com/theia-ide/theia/wiki/Dev-Meetings#minutes-2018-06-19) there was a discussion around ways to develop against Theia, specifically when a developer needs to take advantage of features which aren't yet published or still under proposal.

This is primarily difficult due to Theia being a monorepo and npm/yarn not being able to install packages from within a repo. Short of publishing newer/modified packages to a different registry, setting up this environment has been a little tricky, so I thought I'd share a pattern for using [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to bring in Theia packages as a separate workspace. The project can be seen here:

https://github.com/thegecko/theia-dev

I've had to [copy a lot of the package dependencies](https://github.com/thegecko/theia-dev/blob/master/package.json#L16) into the root `package.json` as AFAICT each package doesn't contain all of it's required dependencies.

Are there any thoughts around this approach? Can we make it simpler (perhaps by bringing all dependencies into each package)? Has anyone refined a better setup? Could something like this be turned into a starter project?

**Comment by akosyakov** [comment]
My concern is that it does not respect yarn.lock files in theia and extension repos, but creates a new one with different node_modules structure and packages' versions. So If it compiles and runs within such repo, it does not mean that it will within theia or extension repos. If it would not be an issue by moving dev dependencies from root to a single dev package and listing it as a workspace.

I wonder whether an approach with a local npm repo can work, e.g. with https://github.com/verdaccio/verdaccio.

**Comment by JonasHelming** [comment]
@thegecko : This has been inactive for quite a while. Can we close this or convert to a dicussion?

**Comment by thegecko** [comment]
Perhaps convert?
