### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#222]
Based on markers (#219) we want to support bookmarks.

Editors shall have command triggered from the context menu, that allows to create a bookmark marker for the current selection. On creation a pop up will ask the user to provide a description for the bookmark.

All bookmark markers shall be displayed in a Bookmarks View (based on #221). It shows the message, the file and the location. Double-clicking an entry will open and reveal the location in an editor. Right clicking allows deleting an entry.

**Comment by vince-fugnitto** [comment]
I think the feature should be handled by an external VS Code extension, namely [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) which is quite popular. 

If it's not the case please re-open the issue :)
