### ISSUE TITLE
[shell] transfer focus to next widget if the focused widget is closed

### ISSUE THREAD

**Issue by MarkZ3** [eclipse-theia/theia#2234]
Using Theia master (8a5132e), browser and electron examples.

1. Open two files
2. Close one of the editor (Alt+W or middle click)
3. The other editor comes on top but has no focus, i.e. you cannot type

**Comment by svenefftinge** [comment]
It would be good to focus the least recently focussed widget, when the one with focus gets closed.

**Comment by dhuebner** [comment]
The most annoying thing is when you do Alt+W again the `Files` view, or any other currently on top of the left view stack gets closed
