### ISSUE TITLE
not all files moved when drag'n'dropping them in File view

### ISSUE THREAD

**Issue by meysholdt** [eclipse-theia/theia#2240]
Steps to reproduce:
1. open File view
2. select two file2 via mouse and drag'n'drop them to another folder

Observe only one file arriving in the destination folder.
I'd expect all selected files to be moved.

**Comment by vince-fugnitto** [comment]
I confirmed that it is no longer an issue:
I tested the following:
1. dnd two files from the filesystem into the `explorer` - both files were added
2. dnd two files from the `explorer` into a different folder - both files were added

**Comment by vince-fugnitto** [comment]
I believe it's fixed by https://github.com/eclipse-theia/theia/pull/5174
