### ISSUE TITLE
[outline] Wrong outline when typescript code is put on the first line

### ISSUE THREAD

**Issue by MarkZ3** [eclipse-theia/theia#2302]
Using Theia master as of today.

![typescript-outline](https://user-images.githubusercontent.com/311730/42397589-8574e0f8-8134-11e8-806b-01d891f79db2.png)

If I add a blank line at the beginning of the file, then everything goes under "global"

**Comment by MarkZ3** [comment]
Here, "ns" and "global" are both at the same location (1,1) and global happens to be second in the list of symbols. When building the list of children, there is this condition "symbolInformationList[0] === sym" which makes "ns" a children at the top level even though that is incorrect. I'm not sure why this condition is there but removing it would fix it. There is also the oddity that global should be first when it gets returned by the language server but instead it is second. In fact, if I do Ctrl+shift+O (open document symbol), it is indeed second.

![typescript-global](https://user-images.githubusercontent.com/311730/42399106-88446578-813a-11e8-934a-26dab23d5ae6.png)

**Comment by akosyakov** [comment]
@MarkZ3 still the same?

**Comment by MarkZ3** [comment]
It's good now, just tested with latest (bb43e9e). Not sure which commit fixed it.
