### ISSUE TITLE
[java] Java LS process does not terminate correctly

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#2328]
After applying a local fix for [[java] Cannot start the Java LS in debug mode](https://github.com/theia-ide/theia/issues/2326#issuecomment-403761885), terminating the process and restarting the backend on can see the following error message:
```
root ERROR Java: ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)

root ERROR Java: JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
```

This suggests the process was not terminated correctly after shutting down the backend.

**Comment by tsmaeder** [comment]
I guess this refers to the Java _extensions_. Closing
