### ISSUE TITLE
[plug-in] output channel ANSI/terminal mode

### ISSUE THREAD

**Issue by benoitf** [eclipse-theia/theia#2335]
When displaying data on the output view with
```
theia.window.createOutputChannel('my output');
```

ANSI colors are not displayed.
Also by default the font is not fixed so output of some command result looks like ugly

if we could have an option of setting fixed font/setting terminal mode ?

example:
![image](https://user-images.githubusercontent.com/436777/42557728-92b931ec-84ef-11e8-99ba-95c50b13137b.png)

**Comment by azatsarynnyy** [comment]
I guess it's outdated.
Feel free to reopen.
