### ISSUE TITLE
Implement fields "readonly [key: string]: any;" for WorkspaceConfiguration in the plugin api

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-theia/theia#2339]
Implement fields "readonly [key: string]: any;" for WorkspaceConfiguration in the plugin api:
https://github.com/theia-ide/theia/blob/master/packages/plugin/src/theia.d.ts#L2207

**Comment by azatsarynnyy** [comment]
as I see, it's already implemented
https://github.com/eclipse-theia/theia/blob/2b13d55c7e62282b62d7ce212dba66f4c149031c/packages/plugin/src/theia.d.ts#L4168

Feel free to reopen
