### ISSUE TITLE
[merge-conflicts] Error: Model is disposed

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-theia/theia#2367]
Reported here: https://github.com/theia-ide/theia/issues/2366#issuecomment-405168617

I assume it happens when model is accessed delayed, but it got disposed already. Cancellation of that task would be really nice, but at least a disposed state check is necessary for sure.

**Comment by vince-fugnitto** [comment]
Closing since the [`@theia/merge-conflicts`](https://www.npmjs.com/package/@theia/merge-conflicts) extension has been deprecated (over 1 year ago).
If I misunderstood please re-open :)
