### ISSUE TITLE
[output] As a user I would like to customize the font style in the Output view

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#2385]
As a user, I would like to customize the font style in the Output view, or at least be able to switch between the current one and a `monospace` font (same as in the Code Editor maybe). Reading the current one is hard.

The Output is connected to the LS by default, and the LS produces log information. A monospaced font would help to consume this log.

Preferably, this should be adjusted per language. Some preference settings would be a pipe dream.

**Comment by simark** [comment]
I just noticed this after uploading #3092.  It's not configurable, but at least I think a monospace font makes for a better default.

**Comment by kittaakos** [comment]
> monospaced font would help

It has been implemented via https://github.com/eclipse-theia/theia/pull/7570. The output is an editor now.
