### ISSUE TITLE
[lsp][xtext] The Xtext language server cannot receive any `DidChangeWatchedFilesNotification` during the initialization

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#2420]
**Iff** the very first build creates "model" files during the initialization, then the client can receive these new file events, but cannot send it back to the server (through the language client) because it is still initializing.

One can work around this by queuing the events on the Theia frontend and send them once after the language client is ready.
 

Edit: typo

**Comment by tsmaeder** [comment]
We no longer implement any LSP functionality. Closing.
