### ISSUE TITLE
Outline data not restored when initializing a workspace

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#2448]
Outline data not restored when re-starting a workspace
Question:
- Should we save the outline data in the local-storage?
  - If we save the data, we should re-store it when initiating a workspace (may need to save the cursor position within the file)
  - If not saved, the outline data will be re-generated when the user select the file again .

- If the layout of a workspace was saved on the server side, the end user could start from any browser with the same layout.

**Comment by AlexTugarev** [comment]
> Should we save the outline data in the local-storage?

Why is that necessary? When the editor will be reopened and the LS fires updates, then the outline is updated again.

**Comment by lmcbout** [comment]
After futher investigation, it seems that the data is being re-generated when reloading the workspace. So I don't see the interest either why we maintain that outline data in the local storage. With Chrome, if the focus is on a file,  the outline gets re-generated on a reload. If the focus is not an a file, then the outline shows nothing after a reload. In firefox, even the focus on a file before re-loading does not populate the outline view.
I think we should re-generate the outline data after a reload by making sure the last edited file get in synch with the outline view.
There seems to be a sync missing from the outline wit the file in edition. Selecting a function in outline view highlight the same in the file in edition, but selecting something in the file does not highlight the data in the outline view

**Comment by vince-fugnitto** [comment]
@lmcbout  @AlexTugarev  one possible value of storing the state of the `Outline Widget` in local storage, is to potentially restore both the `File Editor` and `Outline Widget` in context of one another. 

For example, we can restore similar to the state shown in the screenshot. If a symbol is currently selected from the `Outline Widget` by the user, we can store the current `File Editor` index, as well as the last selected symbol to restore back to this point once Theia initializes. This will provide users with a seamless transition between opening/closing workspaces.


<img width="1232" alt="screen shot 2018-08-03 at 8 17 50 am" src="https://user-images.githubusercontent.com/40359487/43642577-23564344-96f6-11e8-9d16-a9d8b20a5f48.png">

This can however be completed in the future as I believe restoring the `File Editor Cursor` (line number, column number) when initializing Theia is the initial step and would provide more value to an end user.

**Comment by vince-fugnitto** [comment]
@lmcbout I believe it'd be fine to close the issue.
When restoring, we already keep the state of which line we currently are on, and the sync works.
When restoring we also wait for the LS to fire updates, which we see in the outline view when ready.

**Comment by lmcbout** [comment]
I just tried it and there is no more sync between the editor and the outline view  after restoring. I checked with chrome. I set the focus on a method in the editor, I see the outline data, then restore the client ==> nothing shows in the outline view until I click on the line in the editor after the restore

**Comment by marcdumais-work** [comment]
Retested - sync works and the outline view is restored. Closing. 

![Peek 2020-06-13 23-20](https://user-images.githubusercontent.com/25749063/84583896-7ec51400-adcc-11ea-8bea-598d4a6276da.gif)
