### ISSUE TITLE
Is Theia Python Extension for Python2 only?

### ISSUE THREAD

**Issue by dclong** [eclipse-theia/theia#2459]
Is there any plan to support Python3?

**Comment by AlexTugarev** [comment]
Current python extension uses pyls/jedi which supports python up to version 3.6. 

How is your python environment configured? Do you have any issues?

**Comment by dclong** [comment]
I tried the newly added Dockerfile for Python and replaced Python2 packages with Python 3 ones but it didn't work as expected. 

https://github.com/theia-ide/theia-apps/issues/74#

**Comment by vince-fugnitto** [comment]
Closing, the `theia-apps` example now supports both versions: https://github.com/theia-ide/theia-apps/pull/297
