### ISSUE TITLE
Inconsistent naming/capitalization of Theia menus/buttons/commands

### ISSUE THREAD

**Issue by orucky** [eclipse-theia/theia#2466]
Very low priority, but nice to do sometime: polish the titles of menu items, command names, button texts etc. in Theia so that they are consistent.

* Inconsistent caps example: *Add Cursors **t**o Line Ends* vs. *Add Selection **T**o Next Line Match*
* Inconsistent naming of grouped-together commands example: *Git: Fetch* vs. *Git: Merge...*
* Nonstandard title capitalization example: [avatar] -> Stop Workspace -> Do ***i***t

Suggestions:
  1. pick a particular casing style: sentence case or title case or start case. In case of title case, follow a particular manual of style (they differ in minor details)
  2. avoid using non-alphanumeric characters

**Comment by vince-fugnitto** [comment]
> * Inconsistent caps example: _Add Cursors **t**o Line Ends_ vs. _Add Selection **T**o Next Line Match_

I think it'd be good to in general add the capitalization of words in the command.
It also follows the same in VS Code:

<div align='center'>

<img width="601" alt="Screen Shot 2019-10-29 at 8 42 17 PM" src="https://user-images.githubusercontent.com/40359487/67819689-9c877800-fa8c-11e9-844f-a8e70d629827.png">

</div>

<br />
 
> * Inconsistent naming of grouped-together commands example: _Git: Fetch_ vs. _Git: Merge..._

Can you describe further what you mean?
Are you referring to the ellipsis? In general the ellipsis are used to signify that the command itself prompts the user for further actions.

> * Nonstandard title capitalization example: [avatar] -> Stop Workspace -> Do _**i**_t

I think this can be set using a CSS property (for buttons), but of course it should be the default and overridable by extenders & adopters.

**Comment by msujew** [comment]
We're generally now always using vscode's names basically whenever we can due to i18n compatibility. If anything there isn't holding up to standard, an issue should be filed upstream.
