### ISSUE TITLE
Find command doesn't work in Markdown preview

### ISSUE THREAD

**Issue by orucky** [eclipse-theia/theia#2468]
The `Find` command doesn't work in a preview. Instead, the last focused editor gets focus and opens the find dialog.

Expected behavior: searching in previews works too (can be useful). If that's not possible for now for technical reasons, the `Find` command should be removed from the preview context. Otherwise the user ends up constantly searching in a different file than s/he intended to and has to switch focus back after each such muscle-memory `Ctrl+F` key press.

**Comment by vince-fugnitto** [comment]
Closing since it is also referenced #2753.
