### ISSUE TITLE
Make sure that examples work without the internet connection

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#251]
- [ ] remove remote links from index.html
- [ ] provide removed things via npm packages

**Comment by vince-fugnitto** [comment]
@akosyakov I've been trying to do some backlog grooming / categorization whenever I can.
Is this an issue that can be closed? (it is quite old)
Sorry if this is noise :(

**Comment by akosyakov** [comment]
Yes, let's close it. If on does `yarn` once, then it should be possible to work with `yarn --offline`. Obviously not all features will work, like instilling VS Code extensions.
