### ISSUE TITLE
Cannot add a value via the preference widget

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#2547]
<img width="1316" alt="screen shot 2018-08-10 at 14 59 44" src="https://user-images.githubusercontent.com/3082655/43959125-0db2a68c-9cae-11e8-92d6-56c7600fff37.png">

It is reproducible with `Auto Save` disabled.

**Comment by elaihau** [comment]
I tested and found it cannot be reproduced on the master branch.
Tested with empty settings.json, and json that only has comments. Worked in both scenarios.
Could you please confirm ? thank you !

**Comment by lmcbout** [comment]
Could it be because the settings.json is corrupted
 i.e. just a "{" with no end or just the "}" with no begin
If so, may be we should display an error to the end user when it happens !

**Comment by elaihau** [comment]
@lmcbout displaying an error is a good idea. 
let me check if i can get anything from jsoncparser in this case.

**Comment by elaihau** [comment]
i am opening this issue as #3911 was reverted in https://github.com/theia-ide/theia/pull/4006.

i will try finding a better way to notify the user on data corruption.
