### ISSUE TITLE
[textmate] remove C#

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#2555]
We now have an extension, so the language definition and grammars are coming from there.

https://github.com/theia-ide/theia-csharp-extension

**Comment by vince-fugnitto** [comment]
We now have the `csharp` builtin providing syntax highlighting and `textmate-grammars` will be deprecated as of #6933. I'll close this issue once it is merged.

**Comment by vince-fugnitto** [comment]
Closing thanks to #6933.
