### ISSUE TITLE
[ts] improve responsiveness with a lot of file changes

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#2598]
For example during running yarn on Theia repo, LS receives tons of file changes and takes time to process them.
<img width="1306" alt="screen shot 2018-08-17 at 10 27 20" src="https://user-images.githubusercontent.com/3082655/44256013-29d40900-a208-11e8-8c61-0c60b2d14191.png">

**Comment by svenefftinge** [comment]
Maybe we could increase the throttling time after the first bunch of changes, so it doesn't affect the general editing behavior too much.

**Comment by akosyakov** [comment]
don't think it is relevant anymore, this part was changed a lot
