### ISSUE TITLE
Missing command to 'Show/Hide' terminal

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#2611]
I propose we have the ability to **Show/Hide** the terminal panel similar to other widgets.
Currently we only have the command `` Ctrl+` `` to **Open New Terminal**, but there is no command to collapse the panel out of view.

**Comment by akosyakov** [comment]
Do you mean the bottom bar? For the bottom bar, there is a command: `Toggle Bottom Panel`.

Generally for terminals: do you mean the last focused terminal?

**Comment by vince-fugnitto** [comment]
Hi @akosyakov, you're right I saw we do have the command `Toggle Bottom Panel`, I was just confused earlier since we don't have a `Terminal` menu entry under `View` like other widgets.
