### ISSUE TITLE
Consider to add vscode as depenedency

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#2614]
In order to prevent errors like that: https://github.com/theia-ide/theia/issues/2589#issuecomment-414035697

Probably, we are better to add it even in `monaco-languageclient`, I cannot imagine that someone wants to use monaco and vscode in one process.

For now, downstream packages can work it around by enabling `skipLibCheck`.

**Comment by tsmaeder** [comment]
We no longer implement any LSP functionality. Closing.
