### ISSUE TITLE
[terminal] Git diff shows control characters while using any shell

### ISSUE THREAD

**Issue by vboufleur** [eclipse-theia/theia#2623]
Hi all!

While doing `git diff` inside theia's terminal (with any shell) it shows control characters on it:

![screen shot 2018-08-20 at 21 44 28](https://user-images.githubusercontent.com/16310611/44373970-531fbe00-a4c2-11e8-90ff-23eaa560e60b.png)

These are probably color control characters. How can I enable its correct render into theia's terminal? Thanks for the help!

**Comment by vince-fugnitto** [comment]
Sorry for the late reply, I verified using `git diff` and it worked correctly in the terminal (no control characters were rendered as mentioned). If the issue persists please provide a reproducible example and re-open the issue :+1:
