### ISSUE TITLE
[ts] Incorrect TSC version is used in Theia

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#2636]
Steps to reproduce:
 - Clone https://github.com/theia-ide/typescript-language-server.
 - Start Theia with a workspace pointing to the previously cloned `typescript-language-server`.
 - Open a terminal. Do `yarn`.
 - Type `tsc --version`. It prints `2.9.2.`.
 - Type `which tsc`. It points to `${path/to/theia/source}/theia/node_modules/.bin/tsc`.

Workaround:
```
yarn tsc --version
$ ${/path/to/the/theia/workspace}/typescript-language-server/node_modules/.bin/tsc --version
Version 3.0.1
```
Then refresh the browser.

I ran into this during the verification of: https://github.com/theia-ide/theia/pull/2629

**Comment by akosyakov** [comment]
I don't think we can do anything, all features are coming from VS Code typescript extension, not from our implementation as before.
