### ISSUE TITLE
option to show line wrap marker

### ISSUE THREAD

**Issue by orucky** [eclipse-theia/theia#2643]
Standard feature of most source code editors - when one wants to tame too long lines ;-)

**Comment by vince-fugnitto** [comment]
@orucky I'm not 100% sure if this is the preference you are referring to, but Theia does have: 

`"editor.wordWrap": "off" | "on" | "wordWrapColumn" | "bounded"`
`"editor.wordWrapColumn": number`
`"editor.wrappingIndent": "same" | "indent"`

**Comment by orucky** [comment]
@vince-fugnitto Well, I was talking about an adjustable visual indicator of the n-th line ... this is very useful when you have to manually keep your lines plus or minus of some specified width (for instance when writing text files). See the screenshot from Kate, the marker is the thin gray line on the right, here configured to be at 100th column:

![image](https://user-images.githubusercontent.com/11638327/44571677-bd19bb00-a781-11e8-931b-2809bdf86b17.png)

However, as I just learned, we reuse the editor component from VS Code, so one should check first whether such a feature is there, and if not, we won't fix. Seems to me it's not there ... but not 100% sure.

**Comment by vince-fugnitto** [comment]
The line wrap marker is handled by the preference `"editor.rulers": []`
Example:

```json
{
    "editor.rulers": [80]
}
```

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/73478796-bfb01500-4364-11ea-8fb0-970e74c9fb07.png)


</div>
