### ISSUE TITLE
Add support for `deprecated` in CompletionItem/DocumentSymbol/SymbolInformation

### ISSUE THREAD

**Issue by fbricon** [eclipse-theia/theia#2687]
The [LSP spec](https://microsoft.github.io/language-server-protocol/specification) defines an optional `deprecated` property in `CompletionItem`, `DocumentSymbol`, `SymbolInformation`

The property is available in [lsp4j](https://github.com/eclipse/lsp4j/issues/195), which will allow [jdt.ls to implement the feature easily](https://github.com/eclipse/eclipse.jdt.ls/issues/695). I expect the IDE to display the deprecated items differently (using strikethrough, italic or other means).

**Comment by vince-fugnitto** [comment]
Closing as it is the same issue as https://github.com/eclipse-theia/theia/issues/8557.
We would need a monaco upgrade first before we can add it to the framework.

It continues the work of https://github.com/eclipse-theia/theia/pull/8553.
