### ISSUE TITLE
How do I install and run Theia on Termux?

### ISSUE THREAD

**Issue by emahuni** [eclipse-theia/theia#2693]
I am trying to install and run Theia on Termux and the installation fails when building stuff. It is trying to build electron app. Somehow this is not what the documentation says as it is doing the build process on the first steps. It's doing this a postinstall of the cli or when i run yarn to install packages. I have tried this many ways:

What's written here:
https://github.com/theia-ide/theia/blob/master/dev-packages/cli/README.md

and here:
https://www.theia-ide.org/doc/Composing_Applications.html

This is the error:
```sh
....
[4/4] Building fresh packages...                                                                  
[1/8] ⠈ electron                                                                                  
[2/8] ⠈ vscode-nsfw                                                                               
[3/8] ⠈ node-pty                                                                                  
[4/8] ⠈ dtrace-provider
error /data/data/com.termux/files/home/dev/ide/theia/node_modules/electron: Command failed.       Exit code: 1
Command: node install.js                                                                          Arguments:                                                                                        Directory: /data/data/com.termux/files/home/dev/ide/theia/node_modules/electron                   Output:
/data/data/com.termux/files/home/dev/ide/theia/node_modules/electron/install.js:62                      throw new Error('Electron builds are not available on platform: ' + platform)
      ^                                                                                           
Error: Electron builds are not available on platform: android                                         at getPlatformPath (/data/data/com.termux/files/home/dev/ide/theia/node_modules/electron/install.js:62:13)                                                                                          at Object.<anonymous> (/data/data/com.termux/files/home/dev/ide/theia/node_modules/electron/install.js:18:20)                                                                                       at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)                                            at tryModuleLoad (internal/modules/cjs/loader.js:506:12)                                          at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

Then it exits like that.

**Comment by akosyakov** [comment]
Hi, I'm not familiar with Termux, do I get it right that you would like to run the browser variant but electron dependency get on your way?

**Comment by emahuni** [comment]
yes, that's exactly right. Electron is not for Android so the build step is getting in the way of installation.

[Termux](www.termux.com) is an Android Terminal. Android doesn't have a descent IDE if at all that runs well on it. I think Theia and Termux are meant for each other.

**Comment by DVLP** [comment]
How about mapping local files to Theia with CLI in Termux and running Theia in the browser

This is how wcode works in Termux but it's a much simpler editor
https://github.com/fmsouza/wcode

**Comment by JesterOrNot** [comment]
How would theia even work on android? dosen't termux only serve as a CLI

**Comment by DVLP** [comment]
It's not going to work through Electron because electron still doesn't support Android but it can work just like the cloud solution, in the browser or as PWA but and it can access local files like wcode

**Comment by JesterOrNot** [comment]
of course, you might be able to access it through Gitpod

**Comment by DVLP** [comment]
that's not what I meant. What I mean is running it locally like wcode or web-code for termux. The whole thing is running in the browser but it's operating on local files

**Comment by JesterOrNot** [comment]
oh ok cool!

**Comment by akosyakov** [comment]
BTW all electron dependencies were removed, so now it should not be a blocker. I don't think committers are going to work. Community help is wanted.

**Comment by JonasHelming** [comment]
@emahuni Are you interested in working on this? Otherwise I would close this issue due to inactivity
