### ISSUE TITLE
Theia displays same warning from language server multiple times

### ISSUE THREAD

**Issue by soerendomroes** [eclipse-theia/theia#2696]
If there are multiple ways in a program to return the same warning, Theia displays all of them on top of each other instead of showing only one.
![multiple-markers](https://user-images.githubusercontent.com/6419799/44785088-0017cc00-ab90-11e8-86e7-61a1af11458d.png)

**Comment by svenefftinge** [comment]
Can you explain how to reproduce it?

**Comment by soerendomroes** [comment]
I use a costum xtext-dsl to generate my language server. The language server generates the message for every region which has no final state. So the message to annotate the `dadum` state is send twice as it should be. To reproduce it a dsl which annotates one line with the same message is enough somthing like:
```
<firstline>
annotate first line
annotate first line
```
If it helps I could try to provide the language server I used.

**Comment by svenefftinge** [comment]
I guess the same happens when running your LS in Vs Code?

**Comment by soerendomroes** [comment]
I have not tried it, but the underlying grammar is also used in a eclipse plugin (without an LS) and in eclipse it is not the case.

**Comment by tsmaeder** [comment]
Maybe a duplicate of https://github.com/theia-ide/theia/issues/4181?

**Comment by tsmaeder** [comment]
Are you hovering over the underlined "dadum" to see this?

**Comment by soerendomroes** [comment]
Yes, if I remember correctly.

**Comment by soerendomroes** [comment]
I am hovering over it. I run a LS via extending a `BaseLanguageServerContribution` and starting the language server (which is some executable somewhere).

**Comment by soerendomroes** [comment]
> 
> 
> Can you explain how to reproduce it?

Yes I can: If you have a windows system go to https://drive.google.com/open?id=1yUpEJXMDBLGbtZBOCRZjrqixh9Iv0x_y , for linux go to http://rtsys.informatik.uni-kiel.de/~kieler/files/nightly/sccharts-integration/ and download the appimage and run it (I am not sure if this version actually works or not, the windows version works for sure).
Run the executable, open a workspace, and create a new file with a .sctx extension and copy the following inside it:
```
scchart test {
    region a {
        initial state init
        go to dadum

        final state dadum
    }

    region b {
        initial state init
        go to dadum

        state dadum
    }

    region c {
        initial state init
        go to dadum

        state dadum
    }
}
```

**Comment by JonasHelming** [comment]
@soerendomroes: Could you retest this with the latest release, please? Might be fixed by: https://github.com/eclipse-theia/theia/pull/4632

**Comment by soerendomroes** [comment]
@JonasHelming Yes, but I might take a while to do so

**Comment by JonasHelming** [comment]
thanks!

**Comment by soerendomroes** [comment]
I think I don't have time to test this in the next half year so I will close this now.
