### ISSUE TITLE
Allow to search in the output view

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#2702]
With https://github.com/theia-ide/theia/issues/1674#issuecomment-416942445 the output view can show tracing information for language server. It would be nice to be able to search in printed messages.

**Comment by akosyakov** [comment]
Actually, VS code is using a read-only editor to work with the output as a file. Any objections to do the same? 

// cc @svenefftinge

**Comment by kittaakos** [comment]
Closed via https://github.com/eclipse-theia/theia/pull/7570.
