### ISSUE TITLE
[language support] Add R extension

### ISSUE THREAD

**Issue by lokinell** [eclipse-theia/theia#2709]
I find there is not exist R package, do you have plan to support R?

**Comment by svenefftinge** [comment]
Not concretely now, but something that should be easy to do, as there is a language server for it.

**Comment by svenefftinge** [comment]
It would/should be hosted in an external repository, of course.

**Comment by vince-fugnitto** [comment]
> I find there is not exist R package, do you have plan to support R?

While there were no plans to support **R** within the framework itself, support can be provided by the already well established [r tools vscode extension](https://marketplace.visualstudio.com/items?itemName=Mikhail-Arkhipov.r) among other R extensions. It should be possible to use this extension in Theia. If there are any problems regarding support for such extension(s) please feel free to open corresponding issues.
