### ISSUE TITLE
[Windows][file-search] File-search messes up the editor's name and the reveal in navigator functionality

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#2731]
When opening a file via the file search, the editor's (tab-) name contains the path instead of the name. Works fine when opening editors from the navigator. Once I have opened the file from the file-search, the editor-navigation linking does not work. It works for editors opened from the navigator.

![screen shot 2018-08-31 at 09 36 07](https://user-images.githubusercontent.com/1405703/44899251-8acc0880-ad01-11e8-9f04-f52c28305235.jpg)

**Comment by kittaakos** [comment]
Could be related to this: https://github.com/theia-ide/theia/issues/1591

**Comment by elaihau** [comment]
could we close this one as https://github.com/theia-ide/theia/pull/3749 was merged ?

**Comment by westbury** [comment]
I've just tested this.  The tab title and and linking all seem to work fine with files opened from the search results.  I'm therefore closing it.
