### ISSUE TITLE
add "open editors" and "workspace name" band to file navigator ?

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#2743]
![screenshot from 2018-08-31 06-57-19](https://user-images.githubusercontent.com/37082801/44913039-1b9ee600-acfa-11e8-93ad-8eafcad13bd0.png)

Do we want to make the theia file navigator look similar to the one in vsCode?

Having a band like "Open editors" would help in the case where we have too many editors open. And the band of the opened folder or workspace would help when we have the full fledged multi root workspace support.

**Comment by vince-fugnitto** [comment]
In addition, we can also include items such as the `root path` to the band which can be useful for multi-root workspaces, and can be controlled through an additional preference option.

Other items can include the addition of custom buttons which perform actions such `Collapse All` which will collapse all nodes within the TreeWidget

**Comment by vince-fugnitto** [comment]
This has been resolved with the latest subviews present in `tree` widgets 🎉
