### ISSUE TITLE
Support debugging with GDB

### ISSUE THREAD

**Issue by MarkZ3** [eclipse-theia/theia#2776]
It would be nice to be able to debug C/C++ projects using GDB. This issue can track possible approaches to achieving this.

**Comment by marcdumais-work** [comment]
@jonahgraham FYI.

**Comment by jonahgraham** [comment]
I am watching this issue, I am experimenting with some hardware debug based on https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug, see https://github.com/jonahgraham/theia/tree/master/packages/debug-cortex

**Comment by marcdumais-work** [comment]
@jonahgraham FYI the Theia debug extension code you started-from had a little bug, about its stated license in package.json, that should probably be fixed on your side as well: https://github.com/theia-ide/theia/pull/2787

**Comment by thegecko** [comment]
@jonahgraham We have that cortex DAP working with Theia for mbed debugging already, perhaps we should collude? :)

**Comment by marcdumais-work** [comment]
We would like to be part of the collusion too :)

@marechal-p is playing with [code-debug](https://github.com/WebFreak001/code-debug) ATM.

**Comment by marechal-p** [comment]
@thegecko from what I was gathering on this ARM Cortex Debug Access Port it seemed to be a technology to debug some periphal's processors. Is your Debug Adapter for it able to debug about any native (C/C++ built) application?

Trying to understand precisely what you did and what it enables us to do :)

**Comment by thegecko** [comment]
For reference, I've created a PR for the cortex debugger:

https://github.com/theia-ide/theia/pull/3000

**Comment by vince-fugnitto** [comment]
Closing the issue as there is now support for debugging using `gdb` both through the VS Code extensions as well as the extension [`@theia/cpp-debug`](https://github.com/eclipse-theia/theia-cpp-extensions). :tada:
