### ISSUE TITLE
[lsp] not all trace format are recognized

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#2777]
Reported by @dunnry_twitter on Gitter:
Interesting outcome. I used gitpod to open an arbitrary repository that contained golang code (https://github.com/genuinetools/reg). I then put "go.trace.server": "verbose" in the workspace settings and confirmed that go LSP messages started showing verbosely in output. However, if you used the other settings (I think this is correct) : "go.trace.server": { "verbosity": "verbose", "format": "json" }, it actually breaks the LSP and you get 
```
[Error - 12:17:35 PM] Starting client failed TypeError: t.toLowerCase is not a function
at Object.e.fromString (https://afa9d49d-565d-480b-97e2-38ff0d0a593d.ws-us.gitpod.io/bundle.js:1:77140)
at t.refreshTrace (https://afa9d49d-565d-480b-97e2-38ff0d0a593d.ws-us.gitpod.io/bundle.js:12:271510)
at t.initialize (https://afa9d49d-565d-480b-97e2-38ff0d0a593d.ws-us.gitpod.io/bundle.js:12:264069)
at https://afa9d49d-565d-480b-97e2-38ff0d0a593d.ws-us.gitpod.io/bundle.js:12:263625
```

**Comment by tsmaeder** [comment]
Label "Language Server Protocol"? Isn't this very golang LS specific?

**Comment by akosyakov** [comment]
Tracing is a generic feature, works the same way for all language servers, only language prefix is different in preferences.

**Comment by tsmaeder** [comment]
We no longer implement any LSP functionality. Closing.
