### ISSUE TITLE
LabelProviderContribution must handle both, URIs and FileStats in canHandle

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#2806]
The FileTree uses the URI of a File to retrieve the name and a FileStat to retrieve the Icon. 

see:
https://github.com/theia-ide/theia/blob/e695568f251f34794e381f459bfb5fabfe17f97f/packages/filesystem/src/browser/file-tree/file-tree.ts#L63-L64

Typical LabelProviderContributions, which handle both for a file need to cover both cases and therefore need conditional checks, whether it is a FileState or an URI. getName() and getIcon() get an URI again. This feels inconsistent, ideally all methods would get the URI or a FileStat. A FileStat contains the URI anyways...

**Comment by kittaakos** [comment]
Side note: it should be done like this as they do not depend on each other:
```ts
const [name, icon] = await Promise.all[
  this.labelProvider.getName(uri),
  this.labelProvider.getIcon(fileStat)
];
```

**Comment by vince-fugnitto** [comment]
@JonasHelming is the following issue still valid?

**Comment by JonasHelming** [comment]
Nope, it is not relevant anymore
