### ISSUE TITLE
[debug] Use a variable in the launch configuration asking the user for a PID?

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#2819]
Should we think about implementing templates in the configuration files in order to allow the user to interactively pick a process to debug?

```js
[
  {
    "type": "node",
    // ...
    "request": "attach",
    "name": "Attach by PID to a node process",
    "processId": "${pick-pid:node}"
  }
]
```

**Comment by akosyakov** [comment]
Variables resolution in debug configurations was implemented her: https://github.com/theia-ide/theia/pull/2915

**Comment by marechal-p** [comment]
> Only a variable should be added, it would be the best if it is aligned with VS Code.

Something like `${command:pickProcess}` then?

But in that case, it would require the variables to resolve based on a command, which in turn will need some context about the task to be resolved. As in, how would the process picker filter only `node` processes?

**Comment by akosyakov** [comment]
@marechal-p I think it should work already if you use VS Code nodejs extensions. Could you close it if it is so?
