### ISSUE TITLE
Errors on TS file  not reported at start time when using Chrome

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#2832]
Scenario: Chrome on Ubuntu
    File1:  browser-context-menu-renderer.ts
    File2:  shell-layout-restorer.ts

1- Open the two files on the web browser
2- In file 1, comment the first import --> generates 2 errors in problem view
3- In file 2, also comment out the first import --> generates 4 errors in problem view
4- Keep the focus on file 2 and restart the browser
==> Check the problem view, the errors reported for file 1 show but the errors for file 2 DO NOT show even if the focus is on this file.
5- In file 2, do a modification and then the errors show again
Why the errors on file 2 do not show like errors on file 1 after a restart of the browser!
 
Note: Tested the same scenario with Firefox and the errors for both files are reported  50% after a re-start and 50% only errors of one file

![errortsnotreported](https://user-images.githubusercontent.com/419051/45299998-36801000-b4db-11e8-91d4-92c48ad4003a.gif)

**Comment by msujew** [comment]
Cannot reproduce anymore.
