### ISSUE TITLE
Collaboration mode

### ISSUE THREAD

**Issue by romanrehacek** [eclipse-theia/theia#2842]
Hi,
I have one question. It is possible to work on code by multiple users at the same time? Like c9 ide [https://docs.c9.io/docs/share-a-workspace#section-collaboration-features](https://docs.c9.io/docs/share-a-workspace#section-collaboration-features)
I mean, when I share workspace URL with someone, I can see his typing live. 

Thanks.

**Comment by jarmediagmbh** [comment]
Realtime collaboration is a feature quite hard to implement, though very nice to have!
However, for a first shot, it would be great to just have a notification, when editing a file that changed on the disk. This would prevent two pleople from overwriting each others file contents.

**Comment by sunix** [comment]
FYI, we have plans to work on it (as part of Eclipse Che) for the next GSoC. You are very welcome to join the effort :)

https://wiki.eclipse.org/Google_Summer_of_Code_2019_Ideas#Topic_1:_Co_Editing

**Comment by Mustafa-C** [comment]
Any update on this?

**Comment by sunix** [comment]
@Mustafa-C we are going to work on this this summer :)

**Comment by akosyakov** [comment]
fyi live-share does not have MIT license and can be used only from Microsoft Visual Studio family of products: https://microsoftdocs.github.io/live-share/license/eula.html

**Comment by sunix** [comment]
> fyi live-share does not have MIT license and can be used only from Microsoft Visual Studio family of products: https://microsoftdocs.github.io/live-share/license/eula.html

yes, we will implement a flow with Atom Teletype.

**Comment by glingy** [comment]
Any update on this? I'd love to see this as a part of this editor.

**Comment by scheng123** [comment]
I dearly wish for this collab feature to be implemented. I'm currently using cloud9, which is already good but lacks maintaining (last commit was like years ago) and a bit too buggy.

I can't wait for this feature to be implemented. It gonna be big.
May the collaborators of this repo post their status?

**Comment by bendavis78** [comment]
I noticed gitpod has a sharing feature. Is this proprietary, or is it using some functionality built within Theia? https://www.gitpod.io/docs/sharing-and-collaboration/

**Comment by bendavis78** [comment]
@sunix was there any progress on this at GSoC?

**Comment by sunix** [comment]
hello yes, we will continue on this, this summer: so far, we have a Atom Teletype guest that is starting to work on VSCode.

**Comment by AP-Hunt** [comment]
Do you have any time frames for when we could expect to see the first alpha releases of the stuff you're working on?

**Comment by sunix** [comment]
hey, @Rijul5 will give a weekly update during the Che community meeting: https://github.com/eclipse/che/wiki/Che-Dev-Meetings

**Comment by AP-Hunt** [comment]
Excellent, thanks!

**Comment by bendavis78** [comment]
@sunix was there any progress made on this? Do you have any links you could share?

**Comment by sunix** [comment]
@bendavis78 Hey no progress since august, we were at a point where for some reasons, the extension wasn't working in container. Would need more investigation. You could give a try though https://github.com/che-incubator/vscode-teletype-guest
(setting up a teletype host portal with Atom and try to join in with theia or vscode + the extension)

**Comment by JonasHelming** [comment]
Interested parties can review the first concept here: https://github.com/eclipse-theia/theia/pull/12677

**Comment by JonasHelming** [comment]
see this screenshot: https://github.com/eclipse-theia/theia/pull/12677#issuecomment-1673301187

**Comment by msujew** [comment]
I've created a draft implementation of this feature over at https://github.com/eclipse-theia/theia/pull/13309. I'll improve the code some more in the coming days, but the feature is ready to test.

**Comment by msujew** [comment]
Initial feature for collaboration mode has been added in https://github.com/eclipse-theia/theia/pull/13309 as the `@theia/collaboration` package.

Additional features will be contributed over time as they come available. I'll close this issue since the main features (i.e. workspace, file and cursor sharing) are now implemented.
