### ISSUE TITLE
[Windows] Open recent workspace always disabled on Windows

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#2859]
Although I have a valid `~/.theia/recentworkspace.json` under the home folder, the command is disabled on Windows.

![screen shot 2018-09-12 at 08 42 46](https://user-images.githubusercontent.com/1405703/45406878-1598f580-b668-11e8-93ba-dfd0dc04b857.jpg)

**Comment by westbury** [comment]
This problem is easily reproduced in old commits (eg b8f66c71 from September) but does not show in latest master (cefa1fb2).  It appears to be fixed.

**Comment by DukeNgn** [comment]
I verified this is fixed:

**Steps**:
+ Open a new workspace
+ Close the workspace
+ `File` -> `Open Recent Workspace`
+ A box displayed with the choice to the closed workspace
+ Clicking on it opens the old workspace correctly

**Additional information**:
+ OS: `Windows 10`
+ Theia version: `Master v1.7.0`

@vince-fugnitto Can you close this issue?
