### ISSUE TITLE
Additional style for side panels

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-theia/theia#2865]
Does anyone think about additional style for side panels like in VS Code?
To change the style Theia could have a special command or a configuration in preferences or both.

Current version 
![theia side panel - current version](https://user-images.githubusercontent.com/1655894/45428051-100fcf80-b6a9-11e8-8957-77748597f5bb.png)

It could be simply displayed like in VS Code
![vscode side panel](https://user-images.githubusercontent.com/1655894/45428085-2158dc00-b6a9-11e8-8a9d-81db39d9bc5c.png)

On my screenshot of Theia you can see an additional widget 'Packae Explorer' which has been added when I was playing with my plugin.

**Comment by marechal-p** [comment]
You already merged the work required to add such new subtabs right? https://github.com/theia-ide/theia/pull/2810

If so yes, I really like this styling for the tabs :)

**Comment by akosyakov** [comment]
// cc @spoenemann @svenefftinge

**Comment by akosyakov** [comment]
Is it a dup of https://github.com/theia-ide/theia/issues/716?

**Comment by kittaakos** [comment]
> Is it a dup of #716?

It is.

**Comment by vitaliy-guliy** [comment]
@marechal-p it's another question :) I'm thinking now how can we improve Theia and add the ability to embed custom view widget to already opened part. Something like in VS Code: 'Explorer' part has 'Opened Editors' and 'Workspace Tree' views.

**Comment by marechal-p** [comment]
Yes, seems like I got confused :)
On the other hand, it seems like there's already a pull request for it, nice!

**Comment by marechal-p** [comment]
Misclick :(

**Comment by vince-fugnitto** [comment]
I believe this issue can be closed now with the tree view support (through plugins).
The referenced issue #716 is also closed (icons for vertical tabs).

Please re-open the issue if I am wrong :)
