### ISSUE TITLE
[editorconfig] content assist support

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#2913]
I wonder why nobody built a language server for it.

**Comment by vince-fugnitto** [comment]
The `editorconfig` vscode plugin added to our examples satisfies this condition:
https://github.com/eclipse-theia/theia/blob/e88b7f3c265025a4d97ebb178d164f84bdb11fab/package.json#L142

<div align=center>

![image](https://user-images.githubusercontent.com/40359487/73479522-2681fe00-4366-11ea-8789-e0b36427a183.png)

</div>
