### ISSUE TITLE
Git extension widgets "Git" and "Git History" not synchronized

### ISSUE THREAD

**Issue by jeanlucburot** [eclipse-theia/theia#2922]
When committing code using the Git extension on Theia, the _Git_ widget is used. After successfully committing, the second widget _Git History_ is not updated. I believe this is not intended  behaviour and thought I therefore mention it here. The current solution for that is to refresh the browser.

If it matters:

- operating system: Ubuntu 18.04
- node: v8.12.0
- npm: 6.4.1
- yarn: 1.9.4
- Google Chrome: Version 69.0.3497.92

**Comment by jbicker** [comment]
Can you still reproduce it?
![update-git-history](https://user-images.githubusercontent.com/28291421/46748762-932a4280-ccb4-11e8-93ef-28a7f6e0b56a.gif)

**Comment by erezmus** [comment]
Still a problem in 2023, will attempt a PR if I have time
