### ISSUE TITLE
[typescript] TS LS removes the copyright header when organizing import

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#2931]
It generates code with linter error in Theia.

![screencast 2018-09-20 16-34-16](https://user-images.githubusercontent.com/1405703/45825744-3d84fa80-bcf3-11e8-94e9-8c9abb1fc0ab.gif)

**Comment by akosyakov** [comment]
Can you try it in VS Code? I suspect it is tsserver behavior then we cannot do anything about it except failing an issue in the Typescript repo.

**Comment by kittaakos** [comment]
It works from VS Code (1.27.2 f46c4c469d6e6d8c46f268d1553c5dc4b475840f):

![screencast 2018-09-20 16-47-17](https://user-images.githubusercontent.com/1405703/45826545-f39d1400-bcf4-11e8-819d-e0488a6542a9.gif)
