### ISSUE TITLE
undo/redo does not work in the preferences widget

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#2943]

**Comment by elaihau** [comment]
i tested on the master branch, with the latest version of code, and found it is working. Could you please confirm ? @akosyakov

**Comment by vince-fugnitto** [comment]
I saw some issues with not being able to perform `undo/redo` operations for the `preferences-tree-widget` as well:

**Undo (normal use case)**: a user attempts to add a preference value and undo their change:

<div align='center'>


![a](https://user-images.githubusercontent.com/40359487/60185373-cd625280-97f7-11e9-9e29-18bb7fe878d8.gif)


</div>

**Undo (odd use case)**: with manual edits, perform an update through the tree, and undo the change.

<div align='center'>

![b](https://user-images.githubusercontent.com/40359487/60185473-ff73b480-97f7-11e9-95b2-5771ac37ce90.gif)


</div>

**Comment by akosyakov** [comment]
@vince-fugnitto @elaihau Could you verify it against https://github.com/eclipse-theia/theia/pull/7481 please?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto @elaihau Could you verify it against #7481 please?

I was unable to reproduce the issue any longer on `master`.
It was possible to **undo/redo** changes made manually or through the preferences-tree.

**Comment by akosyakov** [comment]
ok, maybe was fixed by rewriting preference service against Monaco models instead of fs
