### ISSUE TITLE
Out-of-sync filesystem detection does not work

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#2948]
I was looking at this code here, in the context of investigating another bug:

https://github.com/theia-ide/theia/blob/41b4d633ac04668a9e8c7068373a1e6494a5a66f/packages/filesystem/src/node/node-filesystem.ts#L91-L93

The `isInSync` detection looks broken, because the stat that the client (at least when saving a file in the editor) passes is the stat after the file was modified externally to Theia.  So this is the behavior that the implementation in node-filesystem.ts would expect from the client:

1. Client opens foo.txt, saves the stat somehwere.
2. foo.txt is modified externally
3. Client tries to save new content in foo.txt, passing the stat saved earlier
4. node-filesystem grabs a stat of the current foo.txt, realizes that it's different from the client's stat

However, this happens in reality:

1. Client opens foo.txt
2. foo.txt is modified externall
3. Client tries to save new content in foo.txt, grabs a stat of the current foo.txt and passes it
4. node-filesystem grabs a stat of the current foo.txt, ends up comparing two identical stats

Therefore, whatever I do, I am not able to get this dialog to appear:

https://github.com/theia-ide/theia/blob/41b4d633ac04668a9e8c7068373a1e6494a5a66f/packages/filesystem/src/browser/filesystem-watcher.ts#L179-L184

**Comment by simark** [comment]
Once fixed, it would be very good to have an end to end test of the feature (all we can do currently is a UI test).

**Comment by akosyakov** [comment]
@simark Which client tries to grab a current foo.txt stat? It should save a stat at step 1 and use it at step 3. If it grabs a current stat each time at step 3 => the client is broken.

**Comment by simark** [comment]
I don't recall where in the code, but it's the client that is handling the standard file saves from the editor.

**Comment by JonasHelming** [comment]
I just retested this, works fine for me. Please reopen, in case this still occurs.
