### ISSUE TITLE
[textmate] Consider using native oniguruma library inside Electron

### ISSUE THREAD

**Issue by mofux** [eclipse-theia/theia#2971]
We've recenly made the transition from `monaco-textmate` to `vscode-textmate`. This enables us to use the node native `oniguruma` package (instead of `onigasm`) when running Theia through Electron by simply using the `OnigScanner` and `OnigString` classes exported by the `oniguruma` package:

https://github.com/theia-ide/theia/blob/23ee961c168b535f5dcb3f6c439fa3691e6ca6ac/packages/monaco/src/browser/textmate/monaco-textmate-frontend-bindings.ts#L50-L57

It should give the tokenizer a significant performance boost  🚀

**Comment by kittaakos** [comment]
> Please feel free to close the issue if it is not relevant at the moment 😅

No, it is relevant.

**Comment by msujew** [comment]
This has been resolved with https://github.com/eclipse-theia/theia/pull/11331.
