### ISSUE TITLE
JS autocompletion is acting weird (keyboard layout with dead keys)

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#2988]
Given the following snippet:

```js
console.log('PID', process.pid);

while (true) {
    console.log();
}
```

When I try to open a single quote string inside the `console.log();` it behaves in a very weird way:

![theia-js-autocomplete-what](https://user-images.githubusercontent.com/14182238/46098097-93452100-c191-11e8-9145-b7a04254abf3.gif)

**Comment by marcdumais-work** [comment]
@marechal-p I am unable to reproduce this issue.

**Comment by marechal-p** [comment]
I am using an US internationnal keyboard (with dead keys). Is this a factor?

**Comment by marechal-p** [comment]
Yes, it only does this when I use `English (US, international with dead keys)`.

**Comment by akosyakov** [comment]
@marechal-p still valid?

**Comment by marechal-p** [comment]
Cannot reproduce anymore.
