### ISSUE TITLE
JUnit Integration

### ISSUE THREAD

**Issue by MiniDigger** [eclipse-theia/theia#3003]
I am using gitpod, and it would be really cool to allow running unit tests easily from the UI, just like every traditional IDE does.

**Comment by vince-fugnitto** [comment]
It is possible to run unit tests but it is provided by external extensions.
If you are looking into running **junit** tests specifically you can include the following [vscode java test runner](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) extension as a plugin.
