### ISSUE TITLE
Question: Using Theia behind a corporate proxy that blocks websocket

### ISSUE THREAD

**Issue by snapo** [eclipse-theia/theia#3053]
Hi,
I just wanted to know if if there is a way to use theia without websocket access. Our corporate proxy blocks all websockets and that really s*****. Maybe some one else is in the same position. HTTP/S tunneling would be possible over the proxy... but no clue how to achive that without local admin rights :-)
Any input welcome.
I am coming from ice ide, and would like to switch to theia... but that isnt possible so far.

**Comment by marcdumais-work** [comment]
@snapo can you expand a bit about what you're trying to achieve? In your use-case, where does the Theia backend run? Where does the web frontend run?

**Comment by marcdumais-work** [comment]
Thanks for the info. Have you tried to access Theia on your VM from another network (e.g. from home)? Did it then work as expected? What makes you think the issue is related to websockets?

**Comment by snapo** [comment]
Hi @marcdumais-work ,
Yes i did try it from home, ... there it works perfectly. As soon as i am in my company it looks like this:


```
index.js:123 WebSocket connection to 'wss://api.gitpod.io/gitpod' failed: Error during WebSocket handshake: Unexpected response code: 302
connect @ index.js:123
```



```
Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
log @ logging.js:123
errorLog @ logging.js:110
error @ logging.js:38
onerror @ service-factory.ts:20
(anonymous) @ connection.js:47
error (async)
(anonymous) @ index.js:42
(anonymous) @ index.js:40
reassignEventListeners @ index.js:39
connect @ index.js:144
setTimeout (async)
handleClose @ index.js:113
```

The reason for this is as i have already mentioned, from home everything works. It is because the company (and many others) block websockets for security reasons. Same as our company does SSL inspection ( i hate it like hell ).

Why the other ICE ide webeditor works is, it dosent use websockets ... it uses the standard http/s protocol with json requests/responses.

I dont think you can solve this easy, but maybe there is something possible that if websockets arent available on a client that it does a fallback to http requests.

**Comment by marcdumais-work** [comment]
@snapo  As you say, not sure there's an easy solution. 

@akosyakov ,  @svenefftinge - FYI - WDYT? Corporate proxies blocking wss makes it impossible to use e.g. gitpod.io from behind the proxy.

**Comment by jgroom33** [comment]
I'm seeing this behavior while using an nginx forwarding setup also.  Currently, the forwarding is only configured to forward http traffic.  This worked with previous versions of theia, but not with the latest.
It seems the operation of theia is to use http (port 3000) + wss (port 443)
Is that correct?

**Comment by amiramw** [comment]
what about if theia show some error message when websockets are blocked by proxy?
