### ISSUE TITLE
[plug-in] Unable to complete Authoring Plugins tutorial

### ISSUE THREAD

**Issue by jonathan-spruce** [eclipse-theia/theia#3063]
Following through the steps on [this page](https://www.theia-ide.org/doc/Authoring_Plugins.html), I am unable to complete the tutorial.

After starting the hosted instance, I cannot find the `Hello World` command on the hosted instance. I believe that I have followed through all of the steps correctly according to the page but no matter what I do I am unable to continue.

Could you give any advice on how to get plugins working?

**Comment by benoitf** [comment]
@jonathan-spruce
- could you say on which Browser you tried it ?

- Are you able to compile the plug-in before starting the hosted instance ? (launching yarn is ok ? )

- You should have also a output channel in theia with traces of the hosted instance. Do you see something on that view ?

- In the console of the browser (dev tools) do you see something ?

**Comment by jonathan-spruce** [comment]
@benoitf 

- I tried it on Chrome version 69.0 on OSX Mojave, and also using the electron version.
- Yes yarn has no problems compiling
- The output channel only has `<no output yet>`
- The console only complains about keybindings not being available

**Comment by benoitf** [comment]
@jonathan-spruce which version of theia are you using ?

**Comment by jonathan-spruce** [comment]
@benoitf I believe it's 0.3.15

**Comment by benoitf** [comment]
@jonathan-spruce the browser example ? (you mentioned electron)

**Comment by jonathan-spruce** [comment]
@benoitf Yes sorry, that's the browser example

**Comment by msujew** [comment]
We recommend to develop vscode extensions now. These can be tested in vscode.
