### ISSUE TITLE
Test node-extension-server.slow-spec.ts should not rely on external resources

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#3080]
This test reaches out to the npm registry:

https://github.com/theia-ide/theia/blob/master/packages/extension-manager/src/node/node-extension-server.slow-spec.ts

This is problematic because the test tails when trying to run it using a version of Theia that is older than the current one (according to the npm registry).  The test for the outdated method breaks, for example.  The method returns more packages than the test expects, because a package that is usually up-to-date compared to the version on the npm registry is now considered outdated.

The test should be changed to mock the npm registry.  I think in general it's good practice to make unit tests independent from such external resources.

**Comment by akosyakov** [comment]
It is an integration test of installing extensions with npm.js. It does not make sense to keep it if we don't want to test everything working together.

@svenefftinge Should we just skip it?

**Comment by akosyakov** [comment]
@simark I am not sure that it is it is worth the hassle. The dynamic part of the extension system does not seem to be used by anybody and it is going to be superseded by the plugin system. Maybe we can just skip all these tests.

// cc @svenefftinge

**Comment by vince-fugnitto** [comment]
Closing since the [`@theia/extension-manager`](https://www.npmjs.com/package/@theia/extension-manager) is deprecated and not longer present in the sources :+1:
