### ISSUE TITLE
[plug-in] onDidChangeActiveTextEditor event behaves wrong

### ISSUE THREAD

**Issue by mmorhun** [eclipse-theia/theia#3102]
`onDidChangeActiveTextEditor` event is not triggered after editor closing, but triggered when user clicks on another one. So, it is possible to do other stuff, but active editor remains outdated (for example expand tree in project explorer).
<details>
 <summary>Code to test</summary>

```
theia.window.onDidChangeActiveTextEditor((editor: theia.TextEditor | undefined) => {
    console.log('>>>>> Editor is ' + (editor ? 'present' : 'undefined'));
    if (editor) {
        console.log('>>>>> ', editor.document.fileName);
        editor.setDecorations(todoStyle, getTodoDecorations(editor.document));
    }
});
```

</details>

**Comment by mmorhun** [comment]
Also, it is triggered when browser tab becomes active. Just open new browser tab and return to Theia. New event will be fired. Also the same behaviour with developers tools.

**Comment by mmorhun** [comment]
And here is difference with VSCode behaviour. It triggers the event with `undefined` editor after each close. And then immediately with new editor if any.

**Comment by vince-fugnitto** [comment]
I confirmed that the bug has been resolved, when an active editor is closed it triggers the event with `undefined`.
I confirmed with the following extension: 
- https://github.com/vince-fugnitto/active-text-editor/releases/download/0.0.1/active-editor-0.0.1.vsix.
