### ISSUE TITLE
[java][lsp] The startup time is way slower when built-in Java types are opened in editors

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#3158]
I am talking about Java types from the JDK/JRE.

Files opened:
![screencast 2018-10-12 07-20-16](https://user-images.githubusercontent.com/1405703/46849726-27012900-cdf1-11e8-8cb8-cfc187a4dc59.gif)

Refresh with opened editors:
![screencast 2018-10-12 07-22-27](https://user-images.githubusercontent.com/1405703/46849733-308a9100-cdf1-11e8-82ca-26777dfe526b.gif)

Refresh without opened editors:
![screencast 2018-10-12 07-25-08](https://user-images.githubusercontent.com/1405703/46849742-3b452600-cdf1-11e8-840e-6049c10cf06e.gif)

**Comment by marcdumais-work** [comment]
For the reload without editors opened, it may not be a fair comparison. I think in that case the LS will not be started. You could try to have one small .java file opened instead, to factor this out.

Also if the opened files are together relatively big, they will take time to transfer. Doing tests some months ago we noticed that reloading the FE with big files open (e.g. a few megs size) had a disproportionate effect on reload time vs open time when FE is already started.

**Comment by msujew** [comment]
With the changes to the lsp mechanism/vscode extension usage, I don't think this usage is relevant anymore.
