### ISSUE TITLE
[tests] Improve electron example tests

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#317]
The Electron example tests need some improvements.

"wdio does not seem to be used at all
especs are working around of electron-main to start the server, also only checking that the window appears, regardless where it is showing something
Could we clean it up? Removed unused wdio configs, rename especs -> specs, write proper tests. With another PR for sure."

see comment in this PR: https://github.com/theia-ide/theia/pull/314

**Comment by marcdumais-work** [comment]
@epatpol Patrick, can you please have a look and comment on this issue?

**Comment by akosyakov** [comment]
@NazulIslam are you still looking into it?

Despite that so many issues popping up on different platforms from time to time, electron tests are always green.

**Comment by akosyakov** [comment]
unused wdio configs will be removed by https://github.com/theia-ide/theia/pull/1019

Still following should be done:
- [ ] rename especs -> specs
- [ ] write proper tests, i.e. using the real backend

**Comment by akosyakov** [comment]
I will keep it as a follow-up of https://github.com/eclipse-theia/theia/pull/6852 We can run the same tests with puppeteer against Electron, but we need latest version.

**Comment by JonasHelming** [comment]
@marcdumais-work I would close this, I think if we add further tests for electron we want to do this in Blueprint, OK?
