### ISSUE TITLE
pref widget stops working properly after drag n drop pref editors

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#3177]
As the GIF shows, the pref widget is unable to update the workspace preferences after the workspace preference editor is docked below the user preference editor.

maybe we should either disable the `drag and drop` in pref widget, or handle this use case.

![peek 2018-10-15 09-18](https://user-images.githubusercontent.com/37082801/46953692-88790000-d05c-11e8-933e-977971675e1c.gif)

**Comment by vince-fugnitto** [comment]
Closing as the bug is no longer reproducible with the new preferences user-interface: #7105 🍾
