### ISSUE TITLE
[pref] User preferences corrupted after reloading the Front-end application

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#3184]
"Copy" to a file when the preference  file container is available corrupts the user preferences.

Scenario:
- Start the browser
- Open a file
- Select some codes, open the context menu to copy and store the data in the clipboard
- Open the preference folder settings
- Put the focus on any files but the "Preference" container (First file you open in that workspace)
- Restart the browser
- Select Files-> Open  -> <Select a file, could be any file types ex: 123.theia-workspace>
 --> Try copy (CTRL+V inside the file) DOES NOT WORK -->but If you notice, each time you select "Copy", the "CIRCLE" over the preference container appears ands goes away meaning we auto-save the data in the user preferences, so it corrupts it.

Note: if you don't select "Files->Open", the copy works fine. Also works fine after selecting the preference container and back to the initial file.  If the focus was on the "Preference" container before restarting the browser application, then selecting the "File ->Open", any files to open here does not matter, the copy inside that files will work. 

![copycorruptionkeymonitor](https://user-images.githubusercontent.com/419051/46962078-317d2600-d070-11e8-9d71-a349e2335a0e.gif)

**Comment by colin-grant-work** [comment]
I cannot reproduce this bug, and the preference widget has changed substantially since it was reported, so I don't believe it is possible for this bug to recur in the form described.
