### ISSUE TITLE
Support Notebooks

### ISSUE THREAD

**Issue by adrienrenaud** [eclipse-theia/theia#3186]
How do I work with notebooks in Theia? I would like multi-language notebooks like Jupyter or Zeppelin... but inside Theia.

**Comment by svenefftinge** [comment]
You'd need to create an extension for those formats.

**Comment by adrienrenaud** [comment]
I started the extension.
I'm using @theia/mini-browser to embed a notebook served by a jupyter server.
It works fine:
![jupyter_ontop_theia](https://user-images.githubusercontent.com/6208157/52529058-3a62c900-2ceb-11e9-941b-2a5c62d1d1bf.gif)
I don't know how mini-browser works. Does it embed the requested url in an iframe? In the past, I have successfully embed jupyter-notebooks in applications using Iframe.

Would you support an extension that need a external jupyter-server? If yes, we could think of an extension that:
- starts a jupyter server at the root of the workspace
- open any notebook file with extension .ipynb in a iframe

**Comment by svenefftinge** [comment]
Nice! Instead of just embedding the jupyter views in an Iframe, I'd rather go for a full jupyter integration, where I can see and manage my running kernels. So basically an integration of the jupyterlab notebook support for Theia. Another alternative is to look at the VS Code extension and integrate that:
https://code.visualstudio.com/docs/python/jupyter-support

**Comment by adrienrenaud** [comment]
> Instead of just embedding the jupyter views in an Iframe, I'd rather go for a full jupyter integration,

I agree but iframes seem to give a quick practical solution.

> So basically an integration of the jupyterlab notebook support for Theia.

That would make coding great again. No less.

> Another alternative is to look at the VS Code extension

An excellent solution.

**Comment by rayh** [comment]
@svenefftinge any idea of what would be involved to port that plugin over?

**Comment by akosyakov** [comment]
@rayh python extension should work in Theia already, could you try: https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions

**Comment by adrienrenaud** [comment]
@akosyakov `vscode:extension/ms-python.python` works fine (debug, lint, refactor) for me on d380b17fee13d4c3042edd2884e58886d80528dd but I can't open the `Python interactive window`, neither from the command palette or on clicking on `Run Cell`. It might be related to using conda environment: see attached log. 
![theia_jupyter](https://user-images.githubusercontent.com/6208157/56030914-4cc6a680-5d1e-11e9-939c-0d7f4759aaef.gif)

[theia_jupyter.log](https://github.com/theia-ide/theia/files/3072832/theia_jupyter.log)

**Comment by adrienrenaud** [comment]
Adding the conda path in `.theia/settings.json` (in my case `"python.condaPath": "/opt/anaconda3/bin/conda"`) fix some of the issues. I'm able to open the Python Interactive window: **Python: Show Python Interactive window** and matplotlib graphs are rendering.
![image](https://user-images.githubusercontent.com/6208157/56088513-dabba200-5e82-11e9-8ab5-d8e9d521d182.png).
But hitting **Run Cell** does not produce any effect and nothing appears in the backend logs, only in the navigator console:
![image](https://user-images.githubusercontent.com/6208157/56088542-9250b400-5e83-11e9-8c51-126d5b3a0ff7.png)

**Comment by jgbradley1** [comment]
@adrienrenaud it's not related to the conda environment. I tested in a virtual environment and a regular environment (no virtual environment and no conda installed). Both have the same issue. **Run Cell** doesn't work in either environment setup.

**Comment by BroKun** [comment]
I think the integration of jupyterlab will bring a better experience. The editor, kernel manager and command panel can all be integrated. I am currently doing this. Do we need it as an extension? @akosyakov @svenefftinge

**Comment by akosyakov** [comment]
@adrienrenaud @jgbradley1 We landed webviews support last week. Could you check whether you still have issues with VS Code python extension.

Generally it would be helpful if someone have a look what is going on there.

**Comment by fGencturk** [comment]
I have installed `vscode-python` extension to `theia`. When I first created a `.ipynb` file everything works perfectly. Then, even if I exit without saving the file, I cannot open it again. If I delete it and re-create a file with the same name, same error occurs. With a different name, I do not get any errors.

![theia](https://user-images.githubusercontent.com/34229194/70699986-0b3a3100-1cdb-11ea-96ff-96fadb2f8dc8.gif)

**Comment by fGencturk** [comment]
vscode-python extension issue in `theia` https://github.com/eclipse-theia/theia/issues/4956#issuecomment-564931434

**Comment by dannaf** [comment]
Any recent progress with this?  Looks like @adrienrenaud and others have a nice start, thanks!

Also, is this relevant here? https://github.com/nteract/hydrogen/

**Comment by akosyakov** [comment]
Issues which observed with the latest version (2020.3.71659) of Python extension:
- `vscode.workspace.fs.stat` is not implemented:
```
root ERROR [hosted-plugin: 2692] Error Python Extension: 2020-04-07 12:19:27: stat() failed for "python" TypeError: this.vscfs.stat is not a function
    at v.stat (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:1:408800)
    at b.pathExists (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:1:411206)
    at b.fileExists (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:1:411423)
    at w.fileExists (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:1:413580)
    at p.getExecutablePath (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:1:467961)
    at C.getActiveInterpreter (/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/client/extension.js:75:1115839)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
- `Python: Create Blank New Jupyter Notebook` command fails with an error in the webview:
```
/tmp/vscode-unpacked/ms-python-release.vsix/extension/out/datascience-ui/notebook/monaco.bundle.js, /tmp/vscode-unpacked/ms-python-release.vsix/extension/out/datascience-ui/notebook/commons.initial.bundle.js, /tmp/vscode-unpacked/ms-python-release.vsix/extension/out/datascience-ui/notebook/nativeEditor.js is not a valid file name
```

**Comment by azatsarynnyy** [comment]
FYI:
Python extension [relies on `CustomEditor API`](https://github.com/microsoft/vscode-python/blob/e7136b1448d27e9a607ca0d8242d4272b48aabdb/src/client/datascience/interactive-ipynb/nativeEditorProvider.ts#L35) for rendering Jupyter Notebooks.
We (at Red Hat) are going to start working on https://github.com/eclipse-theia/theia/issues/6636

**Comment by akosyakov** [comment]
It is working from https://github.com/eclipse-theia/theia/pull/7908 if you use the last version which does not make use of the custom editor api, namely: https://github.com/microsoft/vscode-python/releases/tag/2020.5.86806

<img width="1904" alt="Screenshot 2020-06-28 at 12 33 33" src="https://user-images.githubusercontent.com/3082655/85945075-9ad3c400-b93b-11ea-8371-42042b506ec8.png">

There are still some issue with loading monaco within the webview:
<img width="1343" alt="Screenshot 2020-06-28 at 12 35 07" src="https://user-images.githubusercontent.com/3082655/85945126-e1c1b980-b93b-11ea-9dac-57f220fec724.png">

It should be handled in the separate PR from the VS Code fs support.

**Comment by azatsarynnyy** [comment]
I tried the latest Python extension and it works with #7908 as well.
As I see from https://github.com/microsoft/vscode-python/pull/12188/files#diff-b1e7b24833976c9e40041d298ee03890R201, the extension actually doesn't depend on CustomEditor Plugins API but it has some experimental feature which the user can opt-in.

**Comment by akosyakov** [comment]
> There are still some issue with loading monaco within the webview:

I've verified that VS Codespaces have the same issues. Nothing to fix here.

**Comment by akosyakov** [comment]
notebooks from python extension should work nicely now.

**Comment by tsmaeder** [comment]
Notebooks with the version of the extension you mentioned (2020.5.xxx) do not work on Firefox: I get 404's, for example:
```
GEThttp://ba7c8bf3-71b8-4260-bbc5-6e2fadff213a.webview.localhost:3000/webview/theia-resource/file///c%3A/Users/thomas/AppData/Local/Temp/vscode-unpacked/ms-python-release.vsix/extension/out/datascience-ui/notebook/nativeEditor.js
[HTTP/1.1 404 Not Found 15ms]
```
when doing "Python: Create New Blank Jupyter Notebook" The exact same thing works when doing it from Chromium.

**Comment by azatsarynnyy** [comment]
I've just checked it with the latest Python extension. Works well in Chrome:
![image](https://user-images.githubusercontent.com/1636395/94688151-dd8baa80-0335-11eb-9050-cb2de161e7de.png)

In Firefox, I got the same errors as @tsmaeder

**Comment by tsmaeder** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/8395
