### ISSUE TITLE
copy code from the editor with syntax highlighting

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#3203]
if I try to copy the code from an editor and paste into keynotes it loses coloring.

**Comment by vince-fugnitto** [comment]
@akosyakov I've tried copying the code to other locations (ex: outlook, word) and it does seem to work. The issue I believe is that we are copying in HTML format while Kenote only supports RTF. 

I did find this however if it meets your needs https://gist.github.com/ashrithr/7425121

**Comment by akosyakov** [comment]
It works from VS Code. Maybe we should support RTF as well, at least for code, pasting code as HTML table does not make sense.
