### ISSUE TITLE
Block Theia completely

### ISSUE THREAD

**Issue by jeanlucburot** [eclipse-theia/theia#3218]
Is there a recommended way to block Theia completely from showing? I would like to create an authentification for restricting access to the IDE.

My current thought is to simply visible=false Theia and show a username/password box instead. If the entered credentials are correct, then Theia is put to visible=true. I believe this just approach just handles the visibility, but Theia is still accessible in the background all along. So there might be more thought following on that.

**Comment by RailRunner16** [comment]
use nginx basic auth

**Comment by JonasHelming** [comment]
I believe the question was answered, please reopen in case there are any follow up questions.
