### ISSUE TITLE
pref editor is not set focus when user tries to open the same file from navigator or file dialog

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#3232]
When users try to open files that are already opened in the preference widget, theia should activate the corresponding preference editor. 

As of today on the master branch, from what we can see in the UI, theia does nothing to respond to the attempts of opening a file that is already opened in the preference widget (see attached GIF).

![peek 2018-10-19 08-48](https://user-images.githubusercontent.com/37082801/47219234-457c9c80-d37c-11e8-89c5-447ed9a65f37.gif)

**Comment by vince-fugnitto** [comment]
The issue is no longer relevant following the preferences-ui changes: https://github.com/eclipse-theia/theia/pull/7105
