### ISSUE TITLE
Correct usage of Events?

### ISSUE THREAD

**Issue by adambattenburg** [eclipse-theia/theia#3261]
I’m trying to better understand Events and am having trouble implementing my own example. I initially followed the documentation, but it seems like it may be outdated so I used `git-repository-provider.ts` and `git-resource.ts` for reference instead. I've looked through a few other examples of events, but is there a file in particular that I should study? 

My goal is to read the updates to a variable across classes but unfortunately, I'm only getting the first instance -- clearly not using the Event correctly. I made an example below of what I'm trying to accomplish. When I check `this._content` within the provider it's updating correctly and the `emitter.event` appears to be firing. However using it in my `example-resource` does not update, and I'm not sure how to check if it exists in `Emitter.event` which I see used more often to access Event data on the `resource` side. 

Thank you for the pointers and let me know if a full repo would be better instead.

**example-provider:**
``` javascript
@injectable()
export class ExampleProvider{
  public _content: string | undefined = 'test string';
  private onContentChangedEmitter = new Emitter<string | undefined>();
  constructor( ) {
  }

  get selectedContent(): string | undefined {
    return this._content;
  }

  set selectedContent(content: string | undefined) {
    this._content = content;
    this.fireDidChangeContent();
  }

  protected fireDidChangeContent(): void {
    this.onContentChangedEmitter.fire(this._content);
  }

  get onDidChangeContent(): Event<string | undefined> {
    return this.onContentChangedEmitter.event;
  }

  async getContents(content: string): Promise<String> {
    // Returns a string on click events from api
    this._content = content;
    this.selectedContent = this._content;
    await this.fireDidChangeContent();
    return content;
  }
}
```

**example-resource:**
``` javascript
@injectable()
export class ExampleResourceResolver implements ResourceResolver {
  constructor(@inject(ExampleProvider) protected readonly stringProvider: ExampleProvider) {}

  getContent(): Promise<string | undefined> {
    return this.stringProvider._content;
  }
}
```

**Comment by kittaakos** [comment]
> let me know if a full repo would be better

👍 Yes, a full repo would be better.

**Comment by adambattenburg** [comment]
Great @kittaakos I've added a little example here: https://github.com/adambattenburg/theia-testing. You can toggle the test extension with `ctrlcmd+shift+i` if interested. 

I've kept a little of the context in the code (I'm trying to open editors from an api), but can delete that as well if it makes it more difficult to follow. The creation of the Event is in the [hello-world-widget](https://github.com/adambattenburg/theia-testing/blob/master/hello-world/src/browser/hello-world-widget.tsx) file. Where I'm trying to access the event, is in the [hello-world-resource](https://github.com/adambattenburg/theia-testing/blob/master/hello-world/src/browser/hello-world-resource.ts) file. Thanks for taking a look!

**Comment by kittaakos** [comment]
I have checked your code (and the extension widget too) but it is still unclear to me what you want to achieve. Can you please write down, without code and any technical details what do you want to do?

**Comment by adambattenburg** [comment]
What I'm trying to accomplish, is listening for variable value changes across files. I want to make one file aware of the current state in another file. Right now I'm just able to get the initial state, but my files don't know when another has updated. I thought events were the best way to pass this information around, but maybe I'm wrong? 

At [line 44](https://github.com/adambattenburg/theia-testing/blob/master/hello-world/src/browser/hello-world-resource.ts#L44) in my `hello-world-resource`, I would like to get the value of `_parameter` in my `hello-world-widget` file.  I'm able to get it the first time, but when I am update the value I can't make my resource aware that it is changing. 

Practically, on every click in my list, I want to pass new contents to my `hello-world-resource`. This will open new editors and fill them with the current contents received from the click event.

**Comment by akosyakov** [comment]
@adambattenburg Sure you should use events :) Whether you need to use `Resource`, it depends. Should it support dirty changes, i.e. unsaved editor changes?

**Comment by adambattenburg** [comment]
Hi @akosyakov, sorry to take so long to respond. What I'm doing should support dirty changes, but I've actually accomplished it using websockets. For my implementation I needed to pass information to my backend anyway so it was the more logical solution. 

However I’m still curious what I was missing when trying to create my own event? How I expect to listen for my event is something like:

```javascript
    this.<provider>.<onDidChangeExample>(event => {
      // example using event
    });
```

But I'm never able to get any response which means I am creating my own events incorrectly. I think the `example-provider` in first post shows conceptually what I'm trying to accomplish, and I was just wondering what step I was doing wrong? I use events provided already in other places, which works fine, but the [documentation on creating my own events](https://github.com/theia-ide/theia-website/blob/master/doc/Events.md) was a little unclear to me. Is there a step I'm missing in the `example-provider` in the first post? Thank you!

**Comment by adambattenburg** [comment]
Hi @akosyakov I apologize, I think I might have made this too complicated. Is there an example implementation you can recommend of a basic event? Not updating a variable, but just being able to tell when a function in a different class was called? 

I'm currently looking at the `BreakpointsManager` class [in this file](https://github.com/theia-ide/theia/blob/d563b31acb8f1b6243dde4a055a878945174b571/packages/debug/src/browser/breakpoint/breakpoint-manager.ts) as a simple example (though it looks like this was all recently refactored out). It seems like the simplest steps are:

```javascript
export class Example {
  public readonly onDidChangeEmitter = new Emitter<void>();
  constructor() {
  }

  get onDidChange(): Event<void> {
    return this.onDidChangeEmitter.event;
  }

  // Function I want to listen for when called
  someOtherFunction() {

    // Triggering of Event
    this.onDidChangeEmitter.fire(undefined);
  }
}
```

and then I can listen for this event using:

```javascript
this.example.onDidChange((event) => {
    // do something when event fires
} )
```

Can you let me know if I'm missing a step or where I should look? Thank you so much for your patience on this!

**Comment by akosyakov** [comment]
@adambattenburg it looks good, why do you think you are missing the step?

**Comment by adambattenburg** [comment]
@akosyakov when I try and listen for any changes, my function listening for the event never fires. If I watch in the web browser dev tools, it fires when I start up the application, but not when I trigger new events afterward. 

I've simplified the repo from before to show you what I mean. [This function](https://github.com/adambattenburg/theia-testing/blob/master/hello-world/src/browser/hello-world-resource.ts#L31) is never triggered even when I fire the event in [this function](https://github.com/adambattenburg/theia-testing/blob/master/hello-world/src/browser/hello-world-widget.tsx#L32). The repo is located at https://github.com/adambattenburg/theia-testing if you wouldn't mind taking a look.

**Comment by akosyakov** [comment]
I have not found a single call to `listenForEvent`, without executing this code a listener is not installed.

**Comment by adambattenburg** [comment]
Sorry about that @akosyakov! I've now added the function in the `initialize` function [here](https://github.com/adambattenburg/theia-testing/blob/master/hello-world/src/browser/hello-world-resource.ts#L24).

When I was testing, I was wondering if I need to be disposing the listener and maybe it's only triggering the first time? It doesn't seem like that is a requirement looking at other places, but I'd love to know your thoughts. 

Thank you so much again for all the help. I know this has drawn out, but it seems foundational to working with Theia and I'd really like to understand. If it would help, I'd love to contribute to the docs/ write a blog that others struggling with events can be directed to. Let me know if that would be helpful and thanks again!

**Comment by akosyakov** [comment]
> When I was testing, I was wondering if I need to be disposing the listener and maybe it's only triggering the first time?

If an object gets disposed then it should dispose all acquired listeners. If an object exists throughout the entire user session and never disposed, then it does not make sense to collect and dispose listeners.

> Thank you so much again for all the help. I know this has drawn out, but it seems foundational to working with Theia and I'd really like to understand. If it would help, I'd love to contribute to the docs/ write a blog that others struggling with events can be directed to. Let me know if that would be helpful and thanks again!

Of course, you are welcomed to contribute to docs: https://github.com/theia-ide/theia-website

**Comment by adambattenburg** [comment]
Ah sorry @kittaakos I didn't make this clear in my last message. Even adding it to the initializer, it still does not listen for events. Do you think you could take a look at [this line](https://github.com/adambattenburg/theia-testing/blob/master/hello-world/src/browser/hello-world-resource.ts#L24) in the repo for what I'm missing?

**Comment by msujew** [comment]
Closing this issue, please reopen as a [discussion](https://github.com/eclipse-theia/theia/discussions) in case the question is still relevant.
