### ISSUE TITLE
error in build 

### ISSUE THREAD

**Issue by hosseinmh** [eclipse-theia/theia#3295]
hi 
when I want to install own Ide and I use  '' yarn theia build ''
I face with this error 
<img width="676" alt="screen shot 2018-10-28 at 9 54 43 am" src="https://user-images.githubusercontent.com/12621753/47612814-85880180-da97-11e8-8ee3-fdc673bab2ec.png">

**Comment by hosseinmh** [comment]
and another question is how to add python in terminal ??
thanks

**Comment by marcdumais-work** [comment]
@hosseinmh It's not clear from this issue what it is you're trying to build. Can you give some context? 

> how to add python in terminal ??

It just needs to be installed/available on the machine that runs your Theia back-end. e.g. in our theia-apps images, we install Python in some of the images.

**Comment by hosseinmh** [comment]
about first question 
I follow this  " ttps://www.theia-ide.org/doc/Composing_Applications.html "  to run theia

and about my seccond question i run docker image in server and when I open terminal i can access python command instead I have this in ubuntu terminal

**Comment by hosseinmh** [comment]
and another problem I see when use docker image is this error 
" root ERROR Request getFileStat failed with error: EACCES: permission denied, scandir '/home/project' Error: EACCES: permission denied, scandir '/home/project' "

**Comment by marcdumais-work** [comment]
hi @hosseinmh !

> I follow this " ttps://www.theia-ide.org/doc/Composing_Applications.html " to run theia

ok, understood, thanks. I just followed the guide, locally on my machine, and I was able to build the Theia application, without problem. In your screenshot, the error message is truncated. Can you provide it in full? 

> i run docker image in server and when I open terminal i can access python command instead I have this in ubuntu terminal

I am just trying to understand. Is the `python` thing a distinct issue from the build problem? If distinct, it would have been better to open separate GH issue, so not to mix things-up. 
 
The docker image you refer-to, is it one of our [docker images](https://hub.docker.com/u/theiaide/) or something else? Some of our images do have python pre-installed, some others not. 

> instead I have this in ubuntu terminal

I am sorry, but this part I lost your meaning. Maybe you can re-phrase?

**Comment by vince-fugnitto** [comment]
I think the issue can be closed as it is quite old and there hasn't been a response on the last comment.
If there are still problems please feel free to re-open this issue or open new ones describing in detail your problem.
