### ISSUE TITLE
[plug-in] Start Hosted Theia instance if Restart is called before Start

### ISSUE THREAD

**Issue by mmorhun** [eclipse-theia/theia#3306]
Now when user invokes Restart of Hosted Theia Instance command and the instance has not been started by user yet, it will show an error that a user should start it first. The goal of this issue is to change that behaviour and start Hosted Theia Instance even if it hasn't been started by user yet. In other words the goal is to make Restart behave as Start in case if it called first.

**Comment by DoroNahari** [comment]
This issue can be closed now. #6521

**Comment by mmorhun** [comment]
@DoroNahari thanks for fixing it.
