### ISSUE TITLE
[Preferences] Tool tip colors and position

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#3337]
Preference tool tip is using "white over gray", but using "white over black" over the pref UI schema.
The color should be aligned.

Second, over the UI schema, we display the tool tip  "below and shift right"  while on the editor, we display the tool tip " over and aligned "  which make impossible to select the pref just above the selected one. We should align the tool tip for the editor as the one for the UI schema. Also, when you select the first element from the editor and the line is partially hidden by the editor title, we cannot see the tool tip,it appears under the title.

**Comment by vince-fugnitto** [comment]
They aren't in fact similar tooltips:
 - The 'tooltips' from the editor are coming from `monaco` as a hover action of their definitions / documentation.
- The tooltips from other locations (ex: `widget-labels`) are browser tooltips with the use of `title=` property.

In fact `vscode` has the same exact behaviour, 

The issue of not being able to view the first tooltip in the editor isn't seen in master as of dc12d6d 
![selection_002](https://user-images.githubusercontent.com/40359487/47737803-21f10600-dc48-11e8-94e8-9641e5b4af9d.png)

**Comment by lmcbout** [comment]
Seen on master branch as of commit 85e39052ce
Seems it occurs when there is not enough space above the selected items to show the tool tip.

![tooltiphidden](https://user-images.githubusercontent.com/419051/47741631-1ce48480-dc51-11e8-8ccc-1ee5c835ad58.gif)

**Comment by vince-fugnitto** [comment]
I could not reproduce the issue, the behavior is from monaco so I don't believe it would be easy or worthwhile to modify. I also believe that with the new preferences user-interface the problem does exist anymore anyways. Please re-open the issue if the issue persists.
