### ISSUE TITLE
[file-tree] Undesired scrolling issue when toggling tree node expansion state

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#3347]
This happens in the `File Dialog` and the `Files` widget too. For some reason, it automatically scrolls when expanding tree nodes. It should not. See the attached screencasts.

`File Dialog`:
![screencast 2018-10-31 09-33-57](https://user-images.githubusercontent.com/1405703/47775871-3ccb8500-dcf1-11e8-8465-2e7bd3767a56.gif)

`Files`:
![screencast 2018-10-31 09-38-11](https://user-images.githubusercontent.com/1405703/47775874-41903900-dcf1-11e8-958f-ac9dd38c5985.gif)

It seems, the scrolling issue happens only when the scroll-bar has been adjusted by the user. Until that, it works fine. (See the screencast for `Files`.)

**Comment by teddibaer** [comment]
This still happens in the current version when running in the browser - and I have to say that it makes theia nearly unusable for larger projects (which involve a lot of scrolling in the tree).
