### ISSUE TITLE
[plug-in] Document how plug-ins can be used in Theia

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#3351]
It seems that plug-ins are an important part of Theia's future extendibility, specially at runtime. However, so far, it seems it takes some black magic to make them work in plain Theia. 

As a second step, once it's better known how, we can include some plug-ins in one or more of our docker images, providing a practical example of how it's done.

**Comment by vince-fugnitto** [comment]
I believe the necessary documentation and examples are now covered (examples, theia-apps, theia-blueprint).
I think we can close 👍
