### ISSUE TITLE
[Feature] Hook into electron main master process

### ISSUE THREAD

**Issue by bogthe** [eclipse-theia/theia#3364]
Hi everyone! 

I'm looking into adding updates through `electron-updater` into Theia and for this I need the code which checks for the updates to be running on electron's main master process.
As it currently is, all backend modules are loaded on Electron's main worker process which causes the `electron-updater` module to break. There's a possibility other modules / packages / features will need to have code running from the same location so I wanted to make the hook (binding) into the master process as reusable as possible.

I was thinking of:
- modifying the bit in theia cli which auto generates the electron files to either check for a custom property in the `package.json` file of packages (plugins) like the ones for `frontend`, `backend` etc. and then require them in the master process;
- or have an option which allows the user to specify which packages to be required when the master process is being ran;

What do you think?

**Comment by marechal-p** [comment]
> As it currently is, all backend modules are loaded on Electron's main worker process [...]

I am not so sure... The startup sequence is really confusing, so maybe I'm wrong, but unless you specify `--no-cluster` when starting electron, Theia's backend is ran inside a separate process from which the entry point `electron-main.js` was started in.

What files were you thinking about modifying in particular? (the generated ones)

**Comment by kittaakos** [comment]
FYI: only the bundled electron application has real forked processes. I am happy you are working on this, @bogthe. Make sure your `electron-updater` contribution works in production mode too ;)

https://github.com/theia-ide/theia/blob/accdbd7c440f96ce4b0e1b40b56a0cf78be83f37/dev-packages/application-manager/src/generator/frontend-generator.ts#L168-L186

**Comment by marechal-p** [comment]
@kittaakos but in the dev mode, we do require `main.js`, which in turn will go in `cluster/main.js` and do funny forks on `server.js`?

https://github.com/theia-ide/theia/blob/accdbd7c440f96ce4b0e1b40b56a0cf78be83f37/dev-packages/application-manager/src/generator/backend-generator.ts#L81

**Comment by kittaakos** [comment]
> funny forks

That is a different fork. We have the main electron process, we fork the backend from it, and the backend will fork cluster workers.

**Comment by marechal-p** [comment]
So the backend is in fact forked away from the main process?

**Comment by marechal-p** [comment]
@bogthe on the topic of customizing the start up sequence somehow, I would agree that it is a good idea.

We already drive the generators with infos in the `package.json`, sounds like a good idea to continue too :)

But again, what kind of flow would you expect to see happening? (what to define, how is it triggered and executed?)

**Comment by bogthe** [comment]
@marechal-p @kittaakos thanks for replying so quickly!

I was thinking of having an entra option in the `package.json` file under `theiaExtensions` called `electronMaster` (or something similar) for a theia package which tells the generator to require this module (and any other modules which have that option) [inside this stamement here](https://github.com/theia-ide/theia/blob/accdbd7c440f96ce4b0e1b40b56a0cf78be83f37/dev-packages/application-manager/src/generator/frontend-generator.ts#L150) by doing something like: 
```
require('../backend/masterElectron.js`);
```
(Also that require is present only if there are packages with that option available as to not cram the code too much)

Inside of `masterElectron.js` I only see the required modules as such:
```
\\ masterElectron.js
require('@theia/electron-updates');
require('@theia/some-random-master-package');
```

This in turn gives control to the packages to manage their messaging through `ipcRenderer, ipcMain` between the frontend and this new backend.

Maybe there is a more elegant way of doing this but for a first implementation I think the code is mostly there for generating the file + code, and handling updates it's a good first step.
