### ISSUE TITLE
json LS does not provide symbols for array elements properly

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#3382]
Theia - flat list of array elements' properties:
<img width="349" alt="screen shot 2018-11-02 at 16 18 05" src="https://user-images.githubusercontent.com/3082655/47923961-06d9fc80-debb-11e8-8142-1d7202eaccc6.png">

VS Code - a node for each array element:
<img width="345" alt="screen shot 2018-11-02 at 16 19 16" src="https://user-images.githubusercontent.com/3082655/47923992-1a856300-debb-11e8-8661-8754cdd0b625.png">

**Comment by kittaakos** [comment]
@akosyakov, can we close this?

**Comment by akosyakov** [comment]
@kittaakos yes, just verified that it works now nicely
