### ISSUE TITLE
Cache-control's max-age should be set to a non-zero value

### ISSUE THREAD

**Issue by uniibu** [eclipse-theia/theia#3393]
Theia is using `express.static` with it's default options, which sets the `Cache-Control` header to `max-age: 0` ([serve-static](https://expressjs.com/en/resources/middleware/serve-static.html)) which then tells any cdn services such as cloudflare to not cache any resources/artifacts.

One of the main point of using services such as cloudflare is to serve resources faster and to save server bandwith.  But with `max-age: 0`, cloudflare will always fetch the resources/artifacts from the origin server on every requests.

IMO, the max-age should be changed to a non-zero value to allow cdn services to cache the resources. Refer to the link above on how to configure the deafult options.

**Comment by svenefftinge** [comment]
Since this bit is generated it is hard to change. It should be configurable.

**Comment by vince-fugnitto** [comment]
Closed by #3398
