### ISSUE TITLE
Visual Debugger

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-theia/theia#3406]
Little confused on debugger status. Is the debugger usable yet as I don't see it in 3.16? I there a place where I can check for when it is released if not already?

**Comment by vince-fugnitto** [comment]
Hi @JamesDrummond, it looks like your question may have fallen under the cracks and never got a response so sorry about that. Do you still have questions/issues regarding the debugger?

**Comment by vince-fugnitto** [comment]
Please re-open the issue if you are still experience any additional issues regarding debugging.
The version 0.3.16 you mentioned is quite old (currently v0.12.0).

**Comment by JamesDrummond** [comment]
Have not had a chance to really test out the newer version. Hopefully I can sometime in the future. Closing the issue is of course fine. Thanks.
