### ISSUE TITLE
Add support for preLaunchTask and postDebugTask

### ISSUE THREAD

**Issue by mmorhun** [eclipse-theia/theia#3409]
It is common practice to do some things before/after debugging (manipulation with resources, watching some changes, etc.).
Theia should recognize `preLaunchTask` and `postDebugTask` parameters from debugger configuration file (`launch.json`).

**Comment by tsmaeder** [comment]
@mmorhun is this something VS Code supports? If yes, can you reference some doc?

**Comment by mmorhun** [comment]
Yes, that's comes from VSCode. Docs are [here](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes).
