### ISSUE TITLE
[quality] use SonarQube on Theia, so that we get a report on code quality

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#343]
At the moment, we control the ts linter through a file in our repo: packages/tslint.json . When we build Theia, all rules in that file have to be respected, or the build will fail.

Using SonarQube, we could apply a wider set of TSLint rules to Theia's source code, and have a report generated, that reflects how well we respect those rules. This means that we could include TSLint rules that are "nice to haves", but that we do not feel strongly enough about to enforce by breaking the build. Maybe the rules we aim-for in the longer term. Once we decide to spend time to fix one particular rule across the code base, we can then add it to tslint.json and enforce it from that point-on. In the meantime, the SonarQube report will be there to remind us that those "issues" are present in the code.

There is a hosted version of Sonar, that is free for open-source projects. I just need to confirm that they have the TypeScript plug-in available. I submitted a question to support about this. 
https://about.sonarcloud.io/

**Comment by marcdumais-work** [comment]
I got the following answer from sonarcloud.io support: 

"We don't yet provide a support for TypeScript but this support should come in September with the release of our upcoming SonarTS code analyzer https://github.com/SonarSource/sonarts."

So we can wait a bit before trying to use this SonarQube service to get the reports. We can still in the meantime see about providing an alternative,  wider-ranging version of tslint.json for Theia, that developers can optionally use in vscode, to highlight potential bad coding practices.

**Comment by vince-fugnitto** [comment]
At the moment I don't think there are any plans to add `SonarQube` in order to get metrics.
I will place the the issue on-hold for the moment and re-open it if the status ever changes.
