### ISSUE TITLE
UnhandledPromiseRejectionWarning after restating the BE when  FE has a diff file in the editor

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#3455]
Error reported when there is a "diff" file in the editor and we restart the backend.
Scenario:
1- Open BE and FE
2- Get a diff with a previous branch
3- Select a diff file to open in the editor
4- Stop the back-end
5- Restart the back-end and wait about 30 sec
==>
root ERROR TypeScript: (node:5331) UnhandledPromiseRejectionWarning: Error: geterr timeout
    at Timeout.Deferred.timer.setTimeout (/home/lmcbout/theia/theia/node_modules/typescript-language-server/lib/utils.js:24:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:5331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by akosyakov** [comment]
we don't use typesctipt-language-server anymore
