### ISSUE TITLE
[diff] Navigation does not show on the left side of the diff view

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#3482]
When using the diff view, I can see the tooltip when hovering a field for example on the diff right side, but has nothing when hovering over the same definition when navigating on the left side.
If I try it with vscode, the tooltip shows on both side.

**Comment by lmcbout** [comment]
While using Gitpod, I noticed the navigation was available on the left side of the diff view.

**Comment by vince-fugnitto** [comment]
@lmcbout can you confirm if this is still an issue? In `vscode` the behaviour seems to have aligned to us, they do not display the `hover`, or even `goto` commands from the left hand-side.

**Comment by akosyakov** [comment]
It probably depends whether you compare against local file or from some git revision. I doubt that there is some language support for files from git revision. Could you verify and close the issue if it is a case?

**Comment by vince-fugnitto** [comment]
Closing, confirmed that the behavior is consistent with vscode:
1. comparing with a local revision does not produce hovers
2. comparing with a remote revision (git) produces hovers
