### ISSUE TITLE
[git] Switching branch not working in forked repo

### ISSUE THREAD

**Issue by geropl** [eclipse-theia/theia#3507]
Switching branches in a forked repository using the status bar results in the error fatal: `invalid reference <branch name>`.

This seems to be cause by git being not able to tell which upstream it should choose to checkout from, because both - `origin` (fork) and `upstream` (original) - contain a branch with that name. 

To reproduce:
 1. Open a repository
 2. Fork the repository
 3. Try to switch to one of the forked branches that also exists in upstream

I'd expect Theia to successfully checkout the branch.

**Comment by JonasHelming** [comment]
@geropl : How do you trigger the above operations? On the command line?

**Comment by geropl** [comment]
@JonasHelming This is a very old bug, and I'm not sure it's relevant anymore. Also, I don't recal how to reproduce.

> How do you trigger the above operations? On the command line?

I don't recall, but IMO from the Command palette.

**Comment by JonasHelming** [comment]
OK, I suggest to close this, please comment in case your experience the issue again. Thank you for your feedback!
