### ISSUE TITLE
TS errors importing theia packages

### ISSUE THREAD

**Issue by srolel** [eclipse-theia/theia#3548]
I'm writing an extension, and when I try to import this package (or most other ones):

`import { EditorWidget } from "@theia/editor/lib/browser";`

I get TS errors such as:

`./node_modules/monaco-languageclient/lib/monaco-converter.d.ts(66,21): error TS2503: Cannot find namespace 'monaco'.`

**Comment by vince-fugnitto** [comment]
have you included the package `@theia/editor` in your extension's `package.json` ?

**Comment by Mosho1** [comment]
Yes, doesn't help

**Comment by vince-fugnitto** [comment]
> Yes, doesn't help

https://github.com/theia-ide/theia/issues/3558#issuecomment-440555524

Perhaps this will fix it :)

**Comment by Mosho1** [comment]
Yeah I did that, still an issue though :)

**Comment by vince-fugnitto** [comment]
> Yeah I did that, still an issue though :)

is your extension public? perhaps I can take a look for you

**Comment by Mosho1** [comment]
Sure, thanks :)

https://github.com/Mosho1/theia-serve-frontend/tree/master/theia-serve-ext

**Comment by vince-fugnitto** [comment]
> Sure, thanks :)
> 
> https://github.com/Mosho1/theia-serve-frontend/tree/master/theia-serve-ext

I got it to work!

**Comment by vince-fugnitto** [comment]
I added the following line to `tsconfig.json` under `theia-serve-ext/`
```json
"skipLibCheck": true
```

And since you are depending on both `@theia/workspace` and `@theia/editor` in your extension, you should also add the following dependencies to you `package.json` under `theia-serve-ext/`

```json
"dependencies": {
    "@theia/core": "latest",
    "@theia/editor": "latest",
    "@theia/workspace": "latest"
  }
```
