### ISSUE TITLE
[Terminal] The shell process in the teminal  widget is restored after reloading the browser

### ISSUE THREAD

**Issue by Alexzzzl** [eclipse-theia/theia#3562]
I made a runInTerminal() function by calling terminalService.newTerminal(options). 
The options.shellPath is set to "yo". 
1- When the function is called , a new terminal is created, in which  I see the output of my command "yo".
2- The terminal shows "terminated" on title
3- Reload the browser
4- The command "yo" runs again in the restored terminal.

**Comment by Alexzzzl** [comment]
similar issue with #3587

**Comment by legenddcr** [comment]
Yes. This is the same issue with 3587.

**Comment by vince-fugnitto** [comment]
Thank you for the contribution, closing in favor of tracking the issue from #3587.
