### ISSUE TITLE
[proposal] use 'probot/stale' to automatically close issues/prs after a period of inactivity

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#3563]
I believe it'd be useful for us to be more easily manage the repo and close abandoned `issues`/`pr` after a certain configurable period of inactivity. This means that our repo would stay up to date with relevant new features, and issues which can more easily be addressed and a way to more easily perform backlog grooming. 

A solution I came across was the following bot https://github.com/probot/stale

Other solutions involve manually closing issues and prs based on inactivity and or conflicts.

**Comment by akosyakov** [comment]
I like an idea, although maybe with the more sensitive number of days until stale, like half a year. Otherwise, it could be too much work right now to pin issues which are proper feature requests.

**Comment by kittaakos** [comment]
I have updated the agenda with this topic: https://github.com/theia-ide/theia/wiki/Dev-Meetings#agenda-2019-07-09

**Comment by marcdumais-work** [comment]
We have committed a probot config file on the theia-apps repo. Only need to install / enable the integration for this repo:

https://github.com/theia-ide/theia-apps/pull/201

Added an item on todays dev meeting agenda to discuss: https://github.com/theia-ide/theia/wiki/Dev-Meetings#agenda-2019-07-16

**Comment by vince-fugnitto** [comment]
I believe the conclusion was that there are issues which may be old but are still relevant, and determining what is still relevant each time the bot would notify us of outdated issues causes the project too much overhead to maintain. This is why we added it only to `theia-apps` as the list of issues and pull-requests were much more manageable.

I'll close the issue for the moment and re-open if we ever want to include a bot to closed outdated content.

**Comment by marcdumais-work** [comment]
Quick comment: I like having the bot for `theia-apps`. However it required to manually add the `no-stale` label for issues/PRs that we thing should be kept pass the default expiration timer. If unsure we slip adding the label, and e.g. if the submitter stops responding, we eventually close the issue/PR without further intervention on our part.

**Comment by vince-fugnitto** [comment]
> Quick comment: I like having the bot for `theia-apps`. However it required to manually add the `no-stale` label for issues/PRs that we thing should be kept pass the default expiration timer. If unsure we slip adding the label, and e.g. if the submitter stops responding, we eventually close the issue/PR without further intervention on our part.

Do you suggest we add the bot similarly to this repository? The number of issues and pull-requests are much greater so it might require us to do a lot of management to determine if an issue is still relevant and we add the `no-stale` label.

**Comment by vince-fugnitto** [comment]
@marcdumais-work github has a builtin workflow we could add if you think it'd be useful:

![stale](https://user-images.githubusercontent.com/40359487/87576293-23be5f80-c69f-11ea-9b9a-68cc9a3ec174.png)

**Comment by marcdumais-work** [comment]
No, just highlighting the trade-off.
