### ISSUE TITLE
Question: Why are some files in monaco package not linked against their sources?

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#3619]
_Firefox debugger navigator panel (same view on Chrome):_
![image](https://user-images.githubusercontent.com/14182238/48961687-9b78cd00-ef44-11e8-962f-85f6e4fd519b.png)

I wanted to debug `monaco-editor-model.ts` but wasn't entirely able because for some reason these files are not linked against their sources, I don't really know what is happening in this case...

**Comment by akosyakov** [comment]
With the browser example from this repo?

**Comment by marechal-p** [comment]
@akosyakov Yes.

**Comment by vince-fugnitto** [comment]
I believe this has been resolved thanks to #8744.
