### ISSUE TITLE
[preview] `Open With` > `Code Editor Preview` context menu oddities

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#3670]
Maybe this is the desired behavior, it was strange. The `Code Editor Preview` is only visible when I have opened a preview editor.

![screencast 2018-11-29 11-36-47](https://user-images.githubusercontent.com/1405703/49216525-98aa2c00-f3cb-11e8-9f28-23e13e6fbf22.gif)

**Comment by akosyakov** [comment]
I don't think `Code Editor Preview` should ever appear in `Open With`. It looks like a bug.

**Comment by kittaakos** [comment]
Thanks for confirming it. Note, this was with the electron example.

**Comment by akosyakov** [comment]
//cc @caseyflynn-google

**Comment by vince-fugnitto** [comment]
Confirmed that it is no longer an issue.
