### ISSUE TITLE
[typescript] Annoying auto-complete behavior when writing a string

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#3680]
There are two suspect behaviours that, when combined are annoying.  See this screenshot

![asdasd](https://user-images.githubusercontent.com/1758287/49238821-44a14680-f3cf-11e8-9dbd-41a8ac0cc615.gif)

1. When writing the closing single quote (`'`), the auto-complete menu opens.  I don't think there is a reason to show it at this moment.
2. Once the auto-complete menu is open, typing a comma (`,`) validates the choice, which writes the selected entry.

The problem would disappear if any of these two behaviours was changed, but I think that they are both erroneous and should be fixed.

**Comment by vince-fugnitto** [comment]
The issue has been resolved, likely thanks to the monaco editor upgrade.
