### ISSUE TITLE
[Java] Improve organize imports

### ISSUE THREAD

**Issue by Sandared** [eclipse-theia/theia#3689]
In a java file when I use the "organize imports" command only those imports are handled that are unambigous. Those that are ambigous are not resolved. A popup as in Eclipse would be nice to select the right import for the ambigous ones.

**Comment by liatbor** [comment]
Hi,
When are you planning to support this ?
Thanks!

**Comment by akosyakov** [comment]
We are planning to migrate completely to use vscode java extension. Please try it with Theia: https://github.com/theia-ide/theia/wiki/Testing-VS-Code-Extensions

If you are missing some features please file them against vscode java extension: https://github.com/redhat-developer/vscode-java

**Comment by vince-fugnitto** [comment]
> If you are missing some features please file them against vscode java extension: https://github.com/redhat-developer/vscode-java

Closing thanks to https://github.com/eclipse-theia/theia/pull/6933.

Java support should now be contributed by the various VS Code extensions (example found in the `theia-apps` [java image](https://github.com/theia-ide/theia-apps/blob/master/theia-java-docker/latest.package.json)). If there is still an issue with `organize imports` please feel free to file an issue at the VS Code extension: https://github.com/redhat-developer/vscode-java.
