### ISSUE TITLE
[Java] Fix classpath configuration setting for pom.xml

### ISSUE THREAD

**Issue by Sandared** [eclipse-theia/theia#3690]
Changing the pom.xml of a project results in a popup asking me if I want to synchronize the Java classpath/configuration. Although I chose "Always" as option, Gitpod keeps asking me the same question each time I change the pom.xml.

The expected behaviour would be to only be asked once if the option "always" is chosen.

**Comment by vince-fugnitto** [comment]
I believe the issue is no longer applicable given that `@theia/java` has been deprecated.
If its not the case please comment on the issue.
