### ISSUE TITLE
Wrong association for .schema.json files

### ISSUE THREAD

**Issue by mohschmid** [eclipse-theia/theia#3701]
Hi,

when editing *.schema.json files in Theia, it seems to automatically default to associating it with the JSON:API schema instead of the meta schema (i.e. http://json-schema.org/draft-07/schema), like it does in VS Code:

![theia schema association bug](https://user-images.githubusercontent.com/39480700/49341604-12524c00-f650-11e8-81ed-fc950eef37ef.jpg)

When associating a *.schema.json file with the meta schema explicitly via settings, either by url or inside the settings via "schema": {...}, Theia then provides the correct auto-completion suggestions, but somehow still associates it with the JSON:API schema instead and flags other properties with the warning "Property x is not allowed":

![theia schema association bug2](https://user-images.githubusercontent.com/39480700/49341747-272fdf00-f652-11e8-8e64-c73cae73b8d5.jpg)

The only way I can make the association of a *.schema.json file with the meta schema work seems to be to use the $schema property in the same file.

Is it supposed to behave like this?

**Comment by mohschmid** [comment]
No news on this?

**Comment by akosyakov** [comment]
@mohschmid not, it looks like a bug. In VS Code there are no such warnings.

**Comment by akosyakov** [comment]
PRs are welcomed.

**Comment by kittaakos** [comment]
@akosyakov, is this still valid?

**Comment by akosyakov** [comment]
It seems to be still valid, maybe because we are pulling from Azure schema storage.

**Comment by vince-fugnitto** [comment]
I confirmed that the warning is no longer present, the behavior is similar to VS Code.
