### ISSUE TITLE
CallHierarchyService Plugin API

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#3765]
Theia has a widget that shows the call hierarchy of a methods. Currently, there is a single implementation for Typescript. In order to convert Typescript support to a plugin, we'll need to add a plugin API for call hierarchy. 
IMO, the API should be:
```
theia.languages.registerCallHierarchyProvider(selector: DocumentSelector, provider: CallHierarchyProvider): Disposable;
```
CallHierarchyProvider would be based on the interface CallHierarchyService in the callhierarchy pacakge.

**Comment by benoitf** [comment]
some external links as well (to check also what will be vscode API)
https://github.com/Microsoft/vscode-languageserver-node/pull/346#issuecomment-440283344
https://github.com/Microsoft/vscode-languageserver-node/pull/420#issuecomment-440654266

**Comment by JonasHelming** [comment]
@tsmaeder : It seems the PRs are closed, can we also cllose this issue?

**Comment by tsmaeder** [comment]
No, we've only implemented the "incoming calls" part ("callers"). We're missing the "outgoing calls" part ("callees"). See https://code.visualstudio.com/api/references/vscode-api#CallHierarchyProvider

**Comment by JonasHelming** [comment]
@tsmaeder  According to the report https://eclipse-theia.github.io/vscode-theia-comparator/status.html
CallHierarchy provider is implemented. Is there something still missing?

**Comment by tsmaeder** [comment]
Methinks @colin-grant-work has added the rest in this PR: https://github.com/eclipse-theia/theia/pull/9681/files. Good to close, afaic.
