### ISSUE TITLE
Finish implementation of open command

### ISSUE THREAD

**Issue by mmorhun** [eclipse-theia/theia#3782]
For now we [have implemented](https://github.com/theia-ide/theia/issues/3639) open command (`vscode.open`) only for opening web pages, but VSCode implementation is designed to open some other types of documents. To have plugins compatibility we need add support for that types of documents.

**Comment by tsmaeder** [comment]
@mmorhun vscode.open delegates to "theaia.open" which in the end uses the opener service in Theia. Is this not sufficient? What would we have to add to be vscode compatible?

**Comment by mmorhun** [comment]
As far as I know there are more arguments then just URI in `vscode.open`. Also, I think, it can open wider set of URIs, but to get full list some investigation is needed.
Starting point might be sources of VSCode:
`vscode.open`: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/apiCommands.ts#L86
`_workbench.open`: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadEditors.ts#L265
