### ISSUE TITLE
[lsp] propose displaying lsp initialisation progress from status-bar

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#3784]
I propose we display `lsp` initialisation progress (startup and perhaps scanning for problems) from the status-bar for better transparency to end-users. Currently, when an `lsp` is initialising there is no feedback except for the `Java Language Server`.

Perhaps we can move this implementation to the `BaseLanguageClientContribution` so that all language server clients can benefit from displaying similar progress indicators.

Example from `vscode`:
![selection_021](https://user-images.githubusercontent.com/40359487/49650057-13410000-f9f9-11e8-9bb2-43625a6ac57f.png)

**Comment by akosyakov** [comment]
I don't think it can be generalized each language extension knows better when something can be reported.

VS Code API allows reporting the progress in the editor status bar (Window as location). You see it in the editor as running blueish bar + in the status bar. Each language decides when and what to report. Also if some language features take long VS Code runs the blueish progress bar at the top of the editor again. We can do it as well by implementing Monaco progress service.

**Comment by vince-fugnitto** [comment]
> I don't think it can be generalized each language extension knows better when something can be reported.
> 
> VS Code API allows reporting the progress in the editor status bar (Window as location). You see it in the editor as running blueish bar + in the status bar. Each language decides when and what to report. Also if some language features take long VS Code runs the blueish progress bar at the top of the editor again. We can do it as well by implementing Monaco progress service.

Closing for this exact reason 😄
