### ISSUE TITLE
[Electron] Opening a new folder/workspace shouldn't spawn a new process

### ISSUE THREAD

**Issue by sr229** [eclipse-theia/theia#3789]
Electron Theia shouldn't spawn a new process when opening a new folder unless explicitly done manually through manual means. Instead, Theia should restart and start at the selected folder's context, just like VSCode.

**Comment by vince-fugnitto** [comment]
@sr229 do you mean when opening a new folder/workspace, you'd expect that the electron window and process to be re-used for the new project, rather than having a new window and process spawned?

We have a preference to control that behavior, namely:

https://github.com/eclipse-theia/theia/blob/8814c201fc10b8081fb3d710873e8e0e3c09dc82/packages/workspace/src/browser/workspace-preferences.ts#L29-L33

**Comment by sr229** [comment]
> @sr229 do you mean when opening a new folder/workspace, you'd expect that the electron window and process to be re-used for the new project, rather than having a new window and process spawned?
> 
> We have a preference to control that behavior, namely:
> 
> https://github.com/eclipse-theia/theia/blob/8814c201fc10b8081fb3d710873e8e0e3c09dc82/packages/workspace/src/browser/workspace-preferences.ts#L29-L33

Previously when I opened this issue this wasn't the case AFAIR

**Comment by vince-fugnitto** [comment]
@sr229 ok great, does it resolve the issue you were having?
We wanted to have flexibility in letting applications/users decide how new applications instances should be spawned or behave.

**Comment by sr229** [comment]
I think so but for electron this should be default set to true IMO.

**Comment by vince-fugnitto** [comment]
Looking at VS Code, this seems to be their preference:

<div align='center'>

<img width="476" alt="Screen Shot 2019-10-30 at 8 50 03 AM" src="https://user-images.githubusercontent.com/40359487/67859563-5533d280-faf2-11e9-985c-6da5c228c907.png">


</div>

If you believe that it should be set to `true` in the electron example, you can open a pull request which updates the `package.json` to set the default preference value. Something similar has previously been done to our docker images:

https://github.com/theia-ide/theia-apps/blob/03dbdf5cd12ef00bfd0f947aec669b515538593f/theia-docker/latest.package.json#L4-L11

**Comment by sr229** [comment]
Alrighty, I'll be closing this off however since this was fixed already.
