### ISSUE TITLE
[debug] inline breakpoints support

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#3807]
- It should be possible to install an inline breakpoint at a certain column with `Shift + F9` and remove with `F9` when a cursor at a corresponding column.
- An inline breakpoint should be rendered at the proper column in the editor.
- An inline breakpoint should be rendered with the column info in the breakpoint view path of the debug view.

**Comment by vince-fugnitto** [comment]
I believe inline breakpoints has been resolved as part of https://github.com/eclipse-theia/theia/pull/5774/commits/e440b34f7c83cb5bf1b5db03bbeb445ab6f4f01a.
