### ISSUE TITLE
[plug-in] Ship VS Code's default extensions

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#3815]
VS Code comes with a couple of extensions preinstalled that are expected to exist by other VS Code extensions. So in order to make arbitrary VS Code we need to meet these expectations.

The simplest solution would be to ship with the default vscode extensions. AFAIK they are not on the marketplace, though.

**Comment by akosyakov** [comment]
Would it be fine if I look at it?

// cc @svenefftinge @benoitf

**Comment by akosyakov** [comment]
Here is a list of all built-in extension for VS Code `1.30.1`. Tested extensions which are marked.
- [x] bat
  - [x] https://github.com/theia-ide/theia/issues/3973
  - [ ] https://github.com/theia-ide/theia/issues/3976
  - [ ] https://github.com/theia-ide/theia/issues/3972
- [x] clojure
- [ ] coffeescript
- [ ] configuration-editing
- [ ] cpp
- [ ] csharp
- [ ] css
- [ ] css-language-features
- [ ] debug-auto-launch
- [ ] docker
- [ ] emmet
- [ ] extension-editing
- [ ] fsharp
- [ ] git
- [ ] go
- [ ] groovy
- [ ] grunt
- [ ] gulp
- [ ] handlebars
- [ ] hlsl
- [ ] html
- [ ] html-language-features
- [ ] ini
- [ ] jake
- [ ] java
- [ ] javascript
- [ ] json
- [ ] json-language-features
- [ ] less
- [ ] log
- [ ] lua
- [ ] make
- [ ] markdown-basics
- [ ] markdown-language-features
- [ ] merge-conflict
- [x] ms-vscode.node-debug
- [x] ms-vscode.node-debug2
- [ ] ms-vscode.references-view
- [ ] npm
- [ ] objective-c
- [ ] perl
- [ ] php
- [ ] php-language-features
- [ ] powershell
- [ ] pug
- [ ] python
- [ ] r
- [ ] razor
- [ ] ruby
- [ ] rust
- [ ] scss
- [ ] shaderlab
- [ ] shellscript
- [ ] sql
- [ ] swift
- [ ] theme-abyss
- [ ] theme-defaults
- [ ] theme-kimbie-dark
- [ ] theme-monokai
- [ ] theme-monokai-dimmed
- [ ] theme-quietlight
- [ ] theme-red
- [ ] theme-seti
- [ ] theme-solarized-dark
- [ ] theme-solarized-light
- [ ] theme-tomorrow-night-blue
- [ ] typescript-basics
- [ ] typescript-language-features
- [ ] vb
- [ ] xml
- [ ] yaml

**Comment by akosyakov** [comment]
Closing it since we have a way to consume built-in extensions by now and most of API and contribution points to support them are implemented. Please open individual issues if some incompatibilities arise.
