### ISSUE TITLE
[ts] Call hierarchy disabled for tsx files

### ISSUE THREAD

**Issue by dhuebner** [eclipse-theia/theia#3866]
Is there a reason why CMD+F1 doesn't work for tsx files? 
Context menu entry is also disabled

**Comment by vince-fugnitto** [comment]
Confirmed that `call hierarchy` works correctly for `*.tsx`.
For example:

![call-hierarchy](https://user-images.githubusercontent.com/40359487/88175644-21568b00-cbf4-11ea-98da-645eae4af7c9.png)
