### ISSUE TITLE
react components in debug widgets should have a minimum size

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#3891]
As the GIF shows, when users resize subwidgets inside the debug widget, the subwidget(s) could become almost invisible in some cases. It would be nice if a minimum size could be defined.

![peek 2018-12-21 15-17](https://user-images.githubusercontent.com/37082801/50361991-c2babe00-0533-11e9-99bc-b8d248d70a73.gif)

**Comment by akosyakov** [comment]
Don't know that they can be resized :) Could you point me where it was landed?

**Comment by svenefftinge** [comment]
https://github.com/theia-ide/theia/pull/3855

**Comment by vince-fugnitto** [comment]
This is no longer an issue :)
