### ISSUE TITLE
[FileDownloadService] Download status should be shown during 'await response.blob()'

### ISSUE THREAD

**Issue by zixuemeng** [eclipse-theia/theia#3894]
Download a file by FileDownloadService.download, if the network speed is slow or the file is too large, the response.blob() will take a long time, but 'Preparing download... ' in status bar is removed after fetching.

**Comment by legenddcr** [comment]
One possible solution is use browser download progress when prepare phase is done. If Theia needs control the status, it can be changed in future.

**Comment by vince-fugnitto** [comment]
I believe that `download` now reports progress:

https://github.com/eclipse-theia/theia/blob/b972e2b217da074d821d173a4f8517e171efbd45/packages/filesystem/src/browser/download/file-download-service.ts#L49-L59

Please re-open if this is not the case.
