### ISSUE TITLE
ARM docker image is missing

### ISSUE THREAD

**Issue by dimensi0n** [eclipse-theia/theia#3901]
I have this error while trying to run Theia with docker on my raspberry pi : 

```
docker: Error response from daemon: rpc error: code = 2 desc = "oci runtime error: exec format error".
```

This is because I am using the `next` docker image and I should use an ARM image but it seems it doesn't exist for Theia.

**Comment by vince-fugnitto** [comment]
Sorry for getting back to you so late, sometimes some issues go under the radar unfortunately.
If it hasn't already been resolved you can take a look at past [discussions](https://github.com/theia-ide/theia-apps/issues/130) regarding supporting arm in the docker images. I'll close the issue as it is is not an issue part of the main framework but rather one of [`theia-apps`](https://github.com/theia-ide/theia-apps).
