### ISSUE TITLE
Can't search Theia's Terminal

### ISSUE THREAD

**Issue by jankeromnes** [eclipse-theia/theia#3947]
Thanks a lot for making an amazing web-based IDE! 👍 

I have one small issue with it: I can't search for text in the Terminal.

This is somewhat of a blocker for me, because I'm trying to debug very verbose compilation logs, that have a lot of noise and a few relevant lines containing the word "error". (Additionally, the scrollback seems very limited, but I'll have a look in Theia's preferences to try and make the scrollback infinite.)

I've also tried using Cmd+F, but in-page browser search seems to ignore the Terminal entirely (in Firefox at least).

**Comment by AndrienkoAleksandr** [comment]
I think We could use search addon from xterm.js and implement this feature.

**Comment by vince-fugnitto** [comment]
Will be closeable by https://github.com/eclipse-theia/theia/pull/5471

**Comment by vince-fugnitto** [comment]
Closed by https://github.com/eclipse-theia/theia/pull/5471
