### ISSUE TITLE
Feature toggles in theia

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#3955]
Is there a correct way to manage feature toggles in theia extensions/plugins?
Does it make sence to have such functionality in @theia/core and allow connecting it to some feature toggle management service?

**Comment by akosyakov** [comment]
Controlling enablement of optional/experimental features is usually implemented via preferences.

**Comment by amiramw** [comment]
Preferences could work but in a cloud environment it might not be enough. 
As far as I understand preferneces are controlled by the user, but if you would like to do A-B testing or gradual deployment maybe you would want to control some features centrally.

**Comment by akosyakov** [comment]
I see, the core is about the application framework and lifecycle. New extensions should add extra functionality. I'm not sure that we will need such functionality now to support the application framework. You can start by creating a new extension. It could be located under theia-ide org probably.

// cc @svenefftinge

**Comment by amiramw** [comment]
I created an initial implementation of the extension: https://github.com/amiramw/theia-feature-toggle-extension
@akosyakov  Could you review and instruct how to proceed?

**Comment by amiramw** [comment]
Hi @svenefftinge,
Technically `PreferenceServiceImpl` is binded in the core layer. How can I override it in my extension?
What about making the internal internal preference scopes configurable so one can add new one that take precedence over the others?
