### ISSUE TITLE
theia-yaml-extension - release a stable version

### ISSUE THREAD

**Issue by shahar-h** [eclipse-theia/theia#3966]
I'm am trying to build theia-core latest version (0.3.18) along with theia-yaml-extension 0.1.0.
The problem is that theia breaks in runtime becuase theia-yaml-extension points to theia-core:next.
Currently the only solution is to copy theia-yaml-extension to my project and change its theia-core version to 0.3.18.
Is there a plan to release a stable version of theia-yaml-extension that points to theia-core stable version?

BTW I opened this issue here because it is not possible to open issues in theia-yaml-extension repo:
https://github.com/theia-ide/theia-yaml-extension/tree/master/yaml

**Comment by amiramw** [comment]
Generally, should every extension release new version when theia core version changes?

**Comment by svenefftinge** [comment]
> BTW I opened this issue here because it is not possible to open issues in theia-yaml-extension repo:

I changed the settings now.

**Comment by shahar-h** [comment]
Closing this since vscode yaml extension is now used instead.
