### ISSUE TITLE
[plugin] jsonValidation contribution support

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#3983]
https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation

**Comment by ShimiT** [comment]
Any update on this?  `contributes.jsonValidation`

**Comment by akosyakov** [comment]
Not really, if someone sends a PR it would help.

**Comment by Livven** [comment]
Is this issue still valid with the migration away from Theia-specific language extension to the VS Code ones? I believe this functionality would be provided by the default [`json-language-features`](https://github.com/microsoft/vscode/tree/master/extensions/json-language-features) VS Code extension (you can get a [prebuilt version here](https://github.com/theia-ide/vscode-builtin-extensions/releases)).

Now whether that works is another story (I'm getting a `r.languages.registerSelectionRangeProvider is not a function` error when opening a JSON file).

**Comment by marcdumais-work** [comment]
> Now whether that works is another story (I'm getting a `r.languages.registerSelectionRangeProvider is not a function` error when opening a JSON file).

Hi @Livven , You could try on top of this PR: https://github.com/eclipse-theia/theia/issues/6623
