### ISSUE TITLE
Support debugging VS Code extensions via the debug view

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4016]
There should be a debug configuration provider for `extensionHost` debug type. It allows a user to create a proper node debug configuration and does not require any extra UI.

**Comment by tsmaeder** [comment]
@akosyakov there is a command called "Hosted Plugin: Debug Instance" available from the command palette. Does that fulfil your need?

**Comment by akosyakov** [comment]
One can setup node debug configuration for time being, it is quite straightforward, see https://github.com/theia-ide/theia/issues/3251#issuecomment-468166533

**Comment by DoroNahari** [comment]
Hi @akosyakov,
Are you working on it? we can help

**Comment by akosyakov** [comment]
Nope, it is free to grab. VS Code exposes a command for Node.js debug extension to start another instance of VS Code. We should implement such command and start another instance of Theia plus translate arguments.

**Comment by DoroNahari** [comment]
@amiramw please assign @danarad05 to this issue.

**Comment by danarad05** [comment]
Hi @akosyakov @tsmaeder @amiramw @DoroNahari,

I need some assistance here. As far as I understand task I need to add another launch configuration to default launch configurations existing. 
![image](https://user-images.githubusercontent.com/71069170/95452688-514f3800-0972-11eb-8bbd-d6a5a8e2b196.png)

After debugging, I found that list of default configurations are coming from vscode builtin plugins: 
vscode-builtin-js-debug (https://github.com/microsoft/vscode-js-debug repo) 
vscode-builtin-node-debug (https://github.com/microsoft/vscode-node-debug repo)

Questions:
1. Is above correct?
2. Am I supposed to update these repos? I don't think so as these are vscode repos and not theia repos. So what is course of action here?

Thanks

-Dan

**Comment by amiramw** [comment]
@danarad05 in vcsode there is a launch configuration type called `"extensionHost"`. I think it is coming from https://github.com/microsoft/vscode-node-debug2/blob/15dd85748034c0d8567532271535e58345fd5354/package.json#L84 

Maybe try to look into this repo. vscode-node-debug2 is loaded in theia: https://github.com/eclipse-theia/theia/blob/master/package.json#L122

**Comment by danarad05** [comment]
@amiramw Thanks, I'll check it but there is still same issue as in my question #2 above as vscode-node-debug2 plugin is also a microsoft vscode repo - https://github.com/microsoft/vscode-node-debug2.

**Comment by akosyakov** [comment]
You don't need to add any new configurations. They are already contributed by node 2 vscode built-in extension. You only need to implement a command which this extension is calling to start another instance of VS Code.

**Comment by amiramw** [comment]
@akosyakov by command you mean theia cli option?
and then the below configuration will work with theia `execPath`?
https://github.com/microsoft/vscode-node-debug2/blob/master/package.json#L96-L100

**Comment by akosyakov** [comment]
I mean https://github.com/microsoft/vscode-node-debug2/blob/bcd333ef87642b817ac96d28fde7ab96fee3f6a9/src/nodeDebugAdapter.ts#L349
