### ISSUE TITLE
Error trying to run task

### ISSUE THREAD

**Issue by duemaster** [eclipse-theia/theia#4038]
I am having some trouble running tasks in theia/gitpod. 

Running any tasks gives me this error in the console.
![screenshot from 2019-01-14 15-20-39](https://user-images.githubusercontent.com/8973687/51100212-faa1e200-180f-11e9-9af2-113fe13fdfd1.png)

This is an example of the task that I am trying to run.
![screenshot from 2019-01-14 15-19-51](https://user-images.githubusercontent.com/8973687/51100198-ebbb2f80-180f-11e9-8e96-4b1fe3bb540a.png)

An empty shell will appear but there is no output in the shell at all.

Could this be related to this timing issue mentioned at #3929?

Am I doing something wrongly?

**Comment by vince-fugnitto** [comment]
It is likely due to the following problem https://github.com/eclipse-theia/theia/issues/2961 :(

**Comment by vince-fugnitto** [comment]
The following should be closed since #2961 is resolved thanks to https://github.com/eclipse-theia/theia/pull/9409.
