### ISSUE TITLE
implement `vscode.executeDocumentSymbolProvider` command for `emmet` VS Code extension

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4048]

**Comment by tsmaeder** [comment]
@akosyakov are you working on this?

**Comment by akosyakov** [comment]
@vzhukovskii are you looking into it, if not please remove from assignments that other could grab it

**Comment by vzhukovskii** [comment]
@akosyakov, I've removed assignment. In our task list this issue doesn't have high priority.

**Comment by tsmaeder** [comment]
See https://code.visualstudio.com/api/references/commands. Implementation is in plugin-vscode-commands-contribution.tx
