### ISSUE TITLE
`MonacoConfiguration` should support multiple roots

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#4093]
As of today `MonacoConfigurations` does not support having root uri sensitive preferences:

https://github.com/eclipse-theia/theia/blob/4572886d362f65c2e1857b37945a325d3bf09d8f/packages/monaco/src/browser/monaco-configurations.ts#L60-L64

Once multi-root is supported by preferences extension, the 
`MonacoConfigurations` should be rewritten.

_Originally posted by @akosyakov in https://github.com/theia-ide/theia/pull/3247#issuecomment-455075016_

**Comment by colin-grant-work** [comment]
The file referred to is no longer in the repo. @elaihau, @marechal-p, do you know if this problem has been resolved?

**Comment by marechal-p** [comment]
@colin-grant-work is this issue affecting you? Unless you noticed something related to this I would close the issue.

**Comment by colin-grant-work** [comment]
@marechal-p, I was just going over some of the old tickets with the preference label to see if they were still relevant and closing those that weren't. It sounds like this is in the latter category 🙂.
