### ISSUE TITLE
[monaco] Use original `when` instead of our simplified context

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#4114]
As a follow up to #4076 we should enhance `monaco-keybinding.ts` so that it uses the `when` instead of our `context`.

```ts
   when: monaco.contextkey.ContextKeyExpr.serialize(item.when)
```

**Comment by akosyakov** [comment]
It was resolved by https://github.com/eclipse-theia/theia/pull/5901/files#diff-292276635fa623039777fe10ae5fe4d5
