### ISSUE TITLE
Execute command on save

### ISSUE THREAD

**Issue by markkuit** [eclipse-theia/theia#4158]
Would it be possible to define a command to be executed when a file gets saved, perhaps rather even based on the file type? Basically, that would allow for custom formatters or refreshes to be run.

**Comment by vince-fugnitto** [comment]
There is a new preference `editor.formatOnSave` (as of 0.3.19) which formats files on manual save, based on the same formatting behaviour found in the command `Format Document` from monaco. If it doesn't meet your needs, you can most certainly be inspired by it's implementation. #4012

**Comment by akosyakov** [comment]
You can inject `MonacoWorkspace` and execute a command on `onWillSaveTextDocument` event.

**Comment by JonasHelming** [comment]
I belive this question has been answered, please reopen in case there are any follow ups
