### ISSUE TITLE
plugin http endpoints provide access to server file system

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4168]
One can fetch whatever he wants from the server with it:
https://github.com/theia-ide/theia/blob/74a46e43280220e952475bc37f1009f457620bc0/packages/plugin-ext/src/main/node/plugin-service.ts#L30-L36

The same issue with `/plugin/:path(*)` and `'/hostedPlugin/:pluginId/:path(*)'` endpoints, one can fetch whatever he wants using relative paths.

**Comment by akosyakov** [comment]
There should be an endpoint instead which expose static resources from plugins, but nothing more, no one should be able to pass relative paths and so on.

**Comment by benoitf** [comment]
BTW any plug-in has access to the entire file system. (all vs-code extensions can read any file of the server)

**Comment by akosyakov** [comment]
Providing access to user file system is fine, but not to server file system.

**Comment by akosyakov** [comment]
Theia provides many ways to access the backend filesystem and other system resources, except the plugin system. Securing access to them should be done as part of bigger system, e.g. with system roles, isolated docker containers and so on.
