### ISSUE TITLE
[Feature] Add menuAction to Submenu

### ISSUE THREAD

**Issue by aaqaishtyaq** [eclipse-theia/theia#4183]
Hey, 

As Theia is now part of Eclipse Che and will be used as default IDE for Che 7.
There are some things which are still missing from Theia.
For example Global Run button or A menu which can perform some action as compared to current implementation which requires a submenu to only have child menu which can perform some action.

Is there any way to create a button in Global menu which can perform some actions.
example:
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/22131756/51905757-24e6c880-23e8-11e9-99d0-adb01e5b76ab.gif)

**Comment by vince-fugnitto** [comment]
@aaqaishtyaq sorry it looks like the issue may have gone unnoticed.
Do you believe that this should be a generic Theia feature or Che?

**Comment by akosyakov** [comment]
I don't think it should be implemented in Theia. There is already a way to define and run tasks via the command palette and `Task` menu item aligned with VS Code.

You can transfer issue to che-theia repo if they are interested to implement it.
