### ISSUE TITLE
How do I add my own custom hint tooltip?

### ISSUE THREAD

**Issue by duemaster** [eclipse-theia/theia#4185]
I am trying to figure if I can override any existing hint tooltip with my own custom text.
The hint tooltip that I am referring to is this when you hover over certain text in the text editor.
![custom-tooltip](https://user-images.githubusercontent.com/8973687/51904674-35a03a00-23fa-11e9-8c03-8af094ac41f2.png)

**Comment by akosyakov** [comment]
It is not easy. You will need to intercept hover response from Java LS and augment results. You can start by looking at `JavaLanguageClientContribution`. I think there should be a way to get an instance of `LanguageClient` and inject some middleware.

**Comment by duemaster** [comment]
@akosyakov 
Are you referring to [JavaClientContribution](https://github.com/theia-ide/theia/blob/master/packages/java/src/browser/java-client-contribution.ts#L41)? I couldn't find any `JavaLanguageClientContribution` in the project.

**Comment by akosyakov** [comment]
@duemaster yes

**Comment by duemaster** [comment]
@akosyakov 
I cant seem to find where hover responses are returned to the client in the `JavaClientContribution`.

Also, would it be easier if I create a custom LS to return custom hover response only for selected codes?

**Comment by akosyakov** [comment]
> I cant seem to find where hover responses are returned to the client in the `JavaClientContribution`.

I am referring to https://github.com/TypeFox/vscode-languageserver-node/blob/fb80c5e2db4c714032c28d6f482e770642ae9e23/client/src/client.ts#L393

The middleware can be configured only at the instantiation time, i.e. in `
JavaLanguageClientContribution.createOptions`.

> Also, would it be easier if I create a custom LS to return custom hover response only for selected codes?

You can do it, but if it is based on java, it would be quite heavy to run java LS twice.

**Comment by tsmaeder** [comment]
We no longer implement any LSP functionality. Closing.
