### ISSUE TITLE
[devtools] Is that possible to embed a standalone devtools in theia's bottom panel?

### ISSUE THREAD

**Issue by ensorrow** [eclipse-theia/theia#4191]
Ite should be something like this:

![image](https://user-images.githubusercontent.com/13199771/51957259-e43d8c80-2485-11e9-88fd-8f9d196c42be.png)

I found it very difficult because [ChromeDevTools](https://github.com/ChromeDevTools/devtools-frontend) need **extra chrome boot args** to start a chrome(webview) with standalone devtools(see the start script in the repo).

![image](https://user-images.githubusercontent.com/13199771/51957465-befd4e00-2486-11e9-8b03-e3fc43f17c8b.png)

```javascript
var chromeArgs = [
  `--remote-debugging-port=${REMOTE_DEBUGGING_PORT}`,
  `--custom-devtools-frontend=http://localhost:${SERVER_PORT}/front_end/`, `--no-first-run`,
  '--enable-devtools-experiments', `http://localhost:${REMOTE_DEBUGGING_PORT}#custom=true&experiments=true`,
  `https://devtools.chrome.com`, `--user-data-dir=${CHROME_PROFILE_PATH}`, 'headless'
].concat(process.argv.slice(2));
```

Is there any solution? Or is there a better way for users to finish preview & debug process in Theia without jumping out?

**Comment by vince-fugnitto** [comment]
I usually open my devtools this way, is it not sufficient?

![selection_003](https://user-images.githubusercontent.com/40359487/51980674-c1e44880-245e-11e9-8900-7d465de8069b.png)

or

![selection_002](https://user-images.githubusercontent.com/40359487/51980675-c1e44880-245e-11e9-906e-f966e47b21f5.png)

**Comment by ensorrow** [comment]
> I usually open my devtools this way, is it not sufficient?
> 
> ![selection_003](https://user-images.githubusercontent.com/40359487/51980674-c1e44880-245e-11e9-8900-7d465de8069b.png)
> 
> or
> 
> ![selection_002](https://user-images.githubusercontent.com/40359487/51980675-c1e44880-245e-11e9-906e-f966e47b21f5.png)

It's not sufficient enough when you use Theia's mini-browser as your project's previewer.

**Comment by bjzhangtao** [comment]
how did you solve the problem
