### ISSUE TITLE
Align UX for tasks with VS Code

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4212]
It should be possible to follow along https://code.visualstudio.com/Docs/editor/tasks docs with Theia.

Related https://github.com/theia-ide/theia/issues/1096, https://github.com/theia-ide/theia/issues/4211, https://github.com/theia-ide/theia/issues/4216

cc @marcdumais-work @svenefftinge

**Comment by vince-fugnitto** [comment]
Given that the related issues are completed, and the UX is aligned with VS Code expectations, I would mark the epic as closed.
If we have concrete use-cases we can open specific issues to address any gaps or improvements.
