### ISSUE TITLE
[plug-in] `OutputChannel.show` does not show 

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4214]
Reproducible with `grunt` VS Code extension when `grunt` is not installed.

**Comment by wangshen-sap** [comment]
seems reproduced in latest version, please check it@akosyakov

**Comment by akosyakov** [comment]
@wangshen-sap Could you file a new issue with steps to reproduce please?

**Comment by wangshen-sap** [comment]
the code like this

if (!outputPanel) {
				outputPanel = vscode.window.createOutputChannel("mck");
			}
			outputPanel.show();
			outputPanel.appendLine(message);
		}

mck output channel is not shown after calling this, you need select "mck" from dropdown list, then the "mck" outputchannel will show @akosyakov

**Comment by wangshen-sap** [comment]
the version should be 0.16.1

**Comment by akosyakov** [comment]
It would help if someone prepares a VS Code extension and verify https://github.com/eclipse-theia/theia/issues/4214#issuecomment-601496863

**Comment by vince-fugnitto** [comment]
Closing. The API works well for me, and was confirmed with [output-show-0.0.1.vsix.zip](https://github.com/eclipse-theia/theia/files/8819320/output-show-0.0.1.vsix.zip).

```ts
export function activate(context: vscode.ExtensionContext) {
    const channel = vscode.window.createOutputChannel('test');
    let disposable = vscode.commands.registerCommand('output-show.show', () => {
        channel.show();
        channel.appendLine('test line.');
    });
    context.subscriptions.push(disposable);
}
```
