### ISSUE TITLE
remove dependencies to `@theia/json` in order to support VS Code JSON language features extensions

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4217]
Right now `@theia/json` Theia extension is always pulled via `@theia/debug` extension. We should remove such dependencies to make it possible to replace `@theia/json` extension by VS Code extension. 

cc @thegecko

**Comment by thegecko** [comment]
RE:
https://github.com/theia-ide/theia/issues/3657
https://github.com/theia-ide/theia/pull/3663

Without this dependency, the debug configuration integration in the editor didn't work. Perhaps that UI should have a fallback when `@theia/json` is missing?

**Comment by akosyakov** [comment]
> Without this dependency, the debug configuration integration in the editor didn't work. Perhaps that UI should have a fallback when @theia/json is missing?

One can always include it explicitly in `package.json`. We can add a notification please install `json` extension?

**Comment by marechal-p** [comment]
Would the debug configuration edition assistance work with the vscode json extension? IIUC we explicitly register schemas against our `SchemaRegistry` component, would this be picked up by the vscode ext?

**Comment by akosyakov** [comment]
> Would the debug configuration assistance work with the vscode json extension? IIUC we explicitly register schemas against our JsonSchemaStore component, would this be picked up by the vscode ext?

We need to test and if not, we should make sure that it does.
