### ISSUE TITLE
Theia YAML Extension custom tags

### ISSUE THREAD

**Issue by roflcoopter** [eclipse-theia/theia#4227]
I am having problems getting the YAML editors custom tags to work.

My settings.json contains this
``
"yaml.customTags": ["secret","!secret"],
``
yet, the editor still warns that the tag <!secret> is unknown.

This is what my YAML file looks like;
`latitude: !secret latitude`

Am i doing something wrong or is this a bug? I have restarted my theia container and also refreshed the browser.

I am using the Theia next packages

**Comment by vince-fugnitto** [comment]
@roflcoopter I assume you are using the following extension? 
https://github.com/theia-ide/theia-yaml-extension

I believe it'd be better to open the issue in that repository for a better response.
Please not that it is likely the extension is dropped in favor of using VS Code's builtin extensions.

**Comment by roflcoopter** [comment]
Forgot about this, however I moved over to using vscode directly
