### ISSUE TITLE
[plug-in]  VS Code Git extensions

### ISSUE THREAD

**Issue by vparfonov** [eclipse-theia/theia#4266]
Install VS Code Git extension https://github.com/Microsoft/vscode/tree/master/extensions/git

**Comment by vinokurig** [comment]
To have change decorations in the navigator and editor https://github.com/theia-ide/theia/issues/4666 is needed

**Comment by vparfonov** [comment]
we wait on CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19512
