### ISSUE TITLE
[Webpack] Assets could be compressed to improve delivery times

### ISSUE THREAD

**Issue by sr229** [eclipse-theia/theia#4285]
Problem with current Theia is when there is no CDN to back it up, `bundle.js` is slow to serve - causing the browser to sometimes drop the connection before it even completes.

I suggest to run compression on the assets so we can improve delivery times.

Webpack has a dedicated [plugin](https://webpack.js.org/plugins/compression-webpack-plugin/) for this.

**Comment by akosyakov** [comment]
Products also can install the proxy doing compression or have custom webpack config publishing and consuming artifacts from CDN. Deployment configuration is out of scope of Theia.

For development mode though enabling compression in Theia is beneficial.
