### ISSUE TITLE
[electron] Incorrect default port is used when starting Theia from a bundled Theia app 

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4288]
Steps to reproduce:
 - Open the Theia electron application and start Theia from it.

Problem:
 -  Some random port will be used instead of the default `3000`.

```
Akoss-MacBook-Pro:theia akos.kitta$ yarn --cwd ./examples/browser/ start
yarn run v1.12.3
$ export THEIA_DEFAULT_PLUGINS=local-dir:../../plugins && theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 20674]
Server worker is ready to accept messages. [ID: 1 | PID: 20674]
root WARN The directory referenced by local-dir:../../plugins does not exist.
root INFO Theia app listening on http://localhost:49878.
Received message which is neither a response nor a notification message:
"49878"
```

Workaround:
 - Start the app with `yarn --cwd ./examples/browser/ start --port 3000`.

**Comment by marechal-p** [comment]
When on Electron, some environment variable `THEIA_ELECTRON_VERSION` is set, which is propagated to any child process.

So when we start the browser example, we aren't running an electron environment, but the environment variable is still set.

Then we do some test:
https://github.com/theia-ide/theia/blob/master/packages/core/src/node/backend-application.ts#L41

Which triggers the following code, checking for said env-var:
https://github.com/theia-ide/theia/blob/master/dev-packages/application-package/src/environment.ts#L37

**Comment by kittaakos** [comment]
This issue will be obsolete once we get rid of extension-manager (and the clusters) and switch to the plug-ins.
