### ISSUE TITLE
[editor][ux] Saving the editor should be instantaneous

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4291]
It isn't. The UI should be more responsive in this case. Same with both `auto-save` `on` and `off`.

I used an electron application locally, hence networking/latency should not be a problem.

![screencast 2019-02-08 11-22-47](https://user-images.githubusercontent.com/1405703/52472796-7cc5c200-2b94-11e9-868d-a0c1f5f9848d.gif)

**Comment by msujew** [comment]
I haven't experienced that issue in the recent years, this has probably been resolved.
