### ISSUE TITLE
slow input on terminal

### ISSUE THREAD

**Issue by avelino** [eclipse-theia/theia#4299]
My server where the Theia-IDE is located in Switzerland, I am in Brazil.

It has a certain slowness when typing in the terminal. In the editor there is no slowness.

It would be interesting to use mosh or have buffering in typing

**Comment by svenefftinge** [comment]
AFAIU mosh doesn't have a browser client. There was some effort to run DomTerm in Theia as an alternative to xterm.js (see https://github.com/theia-ide/theia/pull/1204). 
But generally, you should think about moving closer to your servers :-) Seriously, the terminal is the first thing wher one notices bad ping times, but there will be other issues as a lot of communication happens between the frontend and the server side. 
That is why we run Gitpod.io in multiple clusters around the world.

**Comment by marechal-p** [comment]
> It would be interesting to use mosh or have buffering in typing

https://en.wikipedia.org/wiki/Mosh_(software) mosh looks like a good idea, no idea how it feels when we actually use it.

If you wanted, you could look into adding the support for that in Theia. If it is just a matter of communicating to mosh just like we would with a process/pty then it should be fairly doable.

**Comment by vince-fugnitto** [comment]
Closing since I believe the question was answered.
In addition, the following issue https://github.com/eclipse-theia/theia/issues/7832 might be a worthwhile enhancement, to support `local echo` for terminals.
