### ISSUE TITLE
Is it possible to add a dynamically changing badge number to a Widget label?

### ISSUE THREAD

**Issue by duemaster** [eclipse-theia/theia#4311]
It is something like Github's issue
![screenshot from 2019-02-12 17-56-50](https://user-images.githubusercontent.com/8973687/52627096-9f870c00-2eef-11e9-85c6-98e28e889cbe.png)
except that I can dynamically change the badge number via events.

This is displayed on a Widget label on the right area.

**Comment by kittaakos** [comment]
AFAIK, there is no such API yet. You have to implement your own, take a look into `tab-bar.ts`. We have customized the default PhosphorJS implementation. This would be a nice feature, so as always, we are open for PRs.
