### ISSUE TITLE
Integrate with Live Share

### ISSUE THREAD

**Issue by dunnry** [eclipse-theia/theia#4321]
Live Share is currently compatible with both Visual Studio as well as VS Code.  It would be really compelling to see Theia get the VS Code extension working and to be able to participate as well.

https://docs.microsoft.com/en-us/visualstudio/liveshare/use/vscode#installation

**Comment by akosyakov** [comment]
@dunnry you should try and report whatever issues you stumble upon: https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions

**Comment by Hartick** [comment]
root INFO [hosted-plugin: 1416] PLUGIN_HOST(1416): PluginManagerExtImpl/init()


root INFO [hosted-plugin: 1416] PLUGIN_HOST(1416): initializing(vsliveshare-pack@0.3.4 with /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)


root INFO [2681670d-e85e-4eab-b549-8558bb31ea3d][ms-vsliveshare.vsliveshare-pack]: Started plugin.


root INFO [2681670d-e85e-4eab-b549-8558bb31ea3d] Start of 1 plugin took: 684.9150000052759 ms


root INFO [2681670d-e85e-4eab-b549-8558bb31ea3d] Sync of 0 plugins took: 91.44499999820255 ms


root INFO [2681670d-e85e-4eab-b549-8558bb31ea3d] Load contributions of 0 plugins took: 0.05499999679159373 ms


root INFO [2681670d-e85e-4eab-b549-8558bb31ea3d] Start of 0 plugins took: 112.11000000184868 ms


root ERROR Python: 2019-11-08 10:28:41,414 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'autopep8': No module named autopep8




root ERROR Python: 2019-11-08 10:28:41,457 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'pycodestyle': No module named pycodestyle


2019-11-08 10:28:41,460 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'pyflakes': No module named pyflakes




root ERROR Python: 2019-11-08 10:28:41,475 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'yapf': No module named yapf.yapflib




root ERROR Python: 2019-11-08 10:28:41,517 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'pydocstyle': No module named pydocstyle




root ERROR Python: 2019-11-08 10:28:41,532 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'pylint': No module named pylint.epylint




root ERROR Python: 2019-11-08 10:28:41,544 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'rope_completion': No module named rope.contrib.codeassist


2019-11-08 10:28:41,547 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'mccabe': No module named mccabe




root ERROR Python: 2019-11-08 10:28:41,554 UTC - WARNING - pyls.config.config - Failed to load pyls entry point 'rope_rename': No module named rope.base

**Comment by akosyakov** [comment]
It is illegal to use Live Share with Theia, see https://marketplace.visualstudio.com/items/MS-vsliveshare.vsliveshare/license:

> 1. INSTALLATION AND USE RIGHTS. You may install and use any number of copies of the software to use **solely** with Microsoft Visual Studio family of products.

**Comment by JonasHelming** [comment]
Based on the previous comment, I am closing this issue

**Comment by julian-alarcon** [comment]
Related issue: https://github.com/eclipse-theia/theia/issues/2842
