### ISSUE TITLE
[terminal] Theia should not replay commands when terminal is missing.

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#4335]
When we relaunch the whole of Theia (backend/frontend) and open a workspace that had open terminals, Theia shouldn't try to restart the terminals by replaying the original command.

Last occurence was GDB opened like `gdb -i console -nx -ex "new-ui /dev/pts/X"`.
This is a command launched by a debug adapter to have an extra CLI UI in a terminal in Theia, useful for people used to debug using the tool in CLI, but still benefit from the code navigation and UI for local variables and such inside Theia.

In such a case, I do not want Theia to relaunch the command when I restart everything. Relaunching this command will actually restart GDB to debug a program, and it will even try to hook itself inside one of my pseudo-terminals, which actually hijacked one of my instances inside VS Code...

I would really like Theia to not restart processes like this.

**Comment by vince-fugnitto** [comment]
@marechal-p closing since the issue has been previously registered and it is a duplicate:
https://github.com/eclipse-theia/theia/issues/3562 https://github.com/eclipse-theia/theia/issues/3587
