### ISSUE TITLE
Render readonly files differently in sidebar widget

### ISSUE THREAD

**Issue by aaqaishtyaq** [eclipse-theia/theia#4356]
Hey,  I'm trying to deploy Theia 0.3.19 with Che 6.17.

Is there any way that readonly files can be rendered differently or they contain a tag which says [readonly].

**Comment by kittaakos** [comment]
The [`FileStat`](https://github.com/theia-ide/theia/blob/1730624aeabc09ed291c0ddb2614eed2a5a49c9e/packages/filesystem/src/common/filesystem.ts#L225-253) does not contain this information. If you want to implement something like this, I propose using a [`TreeDecorator`](https://github.com/theia-ide/theia/blob/1730624aeabc09ed291c0ddb2614eed2a5a49c9e/packages/core/src/browser/tree/tree-decorator.ts#L24-L43) and do it asynchronously.

You can use the [`access`](https://github.com/theia-ide/theia/blob/1730624aeabc09ed291c0ddb2614eed2a5a49c9e/packages/filesystem/src/common/filesystem.ts#L130) method from the `FileSystem`.
