### ISSUE TITLE
[preferences][keybinding] `Alt` + `Shift` + `W` (Close All) does not work when the preferences JSON editor has the focus

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4387]
It works when the left-hand-side tree viewer has the focus but when the focus is in the JSON editor, it does not work.

**Comment by colin-grant-work** [comment]
I believe that this problem has been resolved. The close all command now closes all open windows, including the preferences editor, which is now in a different form from when the ticket was filed.
