### ISSUE TITLE
[git] High CPU load with lots of changes and multiple clients

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-theia/theia#4436]
1. `git status` operations are scheduled per connected frontend client. if possible, no new `git status` should be scheduled, if one is pending. 

2. the auto scheduling of `git status` should take the average duration of last calls into account. otherwise there is no real pause in between.

**Comment by AlexTugarev** [comment]
CPU time burned with eager `git status` call in a Gitpod workspace:

with 2 connected frontend clients: 
![2019-02-27 12 16 25](https://user-images.githubusercontent.com/914497/53487926-2c53cd00-3a8d-11e9-8185-789ab8f6af68.gif)

with 3 connected frontend clients: 
![2019-02-27 12 24 05](https://user-images.githubusercontent.com/914497/53487927-2c53cd00-3a8d-11e9-8070-911901a18554.gif)

**Comment by akosyakov** [comment]
@svenefftinge critical? should someone look into it?

**Comment by jpuncher** [comment]
Is this issue still being investigated?

On my system this slows the machine down to a point where it is almost unusable (having as many as 30 'git status' requests queued up.  Driving the load average above 60.

` 39478 jpuncher  20   0 2061744  72012   4420 R  38.7  0.1   0:01.21 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39282 jpuncher  20   0 2454960  70964   4420 R  35.5  0.1   0:01.20 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39313 jpuncher  20   0 1996272  70924   4420 R  35.5  0.1   0:01.13 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39416 jpuncher  20   0 2192816  71964   4420 R  33.9  0.1   0:01.06 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39365 jpuncher  20   0 2323856  71236   4420 R  32.3  0.1   0:01.01 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39443 jpuncher  20   0 2258352  71372   4420 R  30.4  0.1   0:00.95 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39387 jpuncher  20   0 2389456  70932   4420 R  30.0  0.1   0:00.94 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39322 jpuncher  20   0 2258288  70908   4420 R  28.8  0.1   0:00.96 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39544 jpuncher  20   0 2258224  71248   4788 R  27.5  0.1   0:00.86 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39613 jpuncher  20   0 2258384  71280   4788 R  26.8  0.1   0:00.84 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39307 jpuncher  20   0 1930672  70916   4420 R  25.6  0.1   0:01.16 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39450 jpuncher  20   0 1996080  71548   4788 R  25.6  0.1   0:00.80 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39518 jpuncher  20   0 2585904  71748   4788 R  25.6  0.1   0:00.80 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39580 jpuncher  20   0 2258288  71340   4788 R  25.2  0.1   0:00.79 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39622 jpuncher  20   0 2127184  71160   4788 R  25.2  0.1   0:00.79 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39575 jpuncher  20   0 1996080  71676   4788 R  24.3  0.1   0:00.76 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39631 jpuncher  20   0 1995948  71080   4780 R  23.0  0.1   0:00.72 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39163 jpuncher  20   0 1930672  72032   4420 R  22.7  0.1   0:01.49 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39718 jpuncher  20   0 1254564  58984   1208 R  21.7  0.1   0:00.68 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39713 jpuncher  20   0 1377472  59040   1208 S  21.1  0.1   0:00.66 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39638 jpuncher  20   0 1451172  59744   1208 R  20.8  0.1   0:00.65 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39277 jpuncher  20   0 2586032  71824   4420 R  19.5  0.1   0:01.16 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39783 jpuncher  20   0 1516772  58948   1200 S  18.5  0.1   0:00.58 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39246 jpuncher  20   0 2454960  70976   4420 R  16.6  0.1   0:01.21 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z      
 39165 jpuncher  20   0 2454960  71012   4420 R  16.0  0.1   0:01.37 /usr/bin/bin/git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z
`

Thanks,

**Comment by AlexTugarev** [comment]
@jpuncher, I once started looking into it. The idea was to enqueue `git status` executions and return the promise of a currently running execution if that's still pending. This would at least eliminate concurring executions, which happens to happen because 1) status requests are schedules periodically regardless of their duration, and 2) after virtual each other git operation a synchronizing status request is made.
