### ISSUE TITLE
python vs code extension bug "this.debugService.onDidReceiveDebugSessionCustomEvent is not a function"

### ISSUE THREAD

**Issue by 113xiaoji** [eclipse-theia/theia#4449]
### Description
@akosyakov I download the python extension source code, add some logs, and compile it.I put .vsix file to theia docker container.When i start the theia image I figured out the error is "t**his.debugService.onDidReceiveDebugSessionCustomEvent is not a function**", i suppose the theia do not support this api?
I read the python extension source code, the error is at this place
`this.disposables.push(this.debugService.onDidReceiveDebugSessionCustomEvent(e => { this.eventHandlers.forEach(handler => handler.handleCustomEvent ? handler.handleCustomEvent(e).ignoreErrors() : undefined); }));`

### Reproduction Steps
1. add some log and build python extension source code 
2. put the python.vsix to theia docker images
3.start the theia 
4. show the error "this.debugService.onDidReceiveDebugSessionCustomEvent is not a function"

**OS and Theia version:**
theia 0.3.18-6.17.1
**Diagnostics:**

**Comment by 113xiaoji** [comment]
@tolusha do you have any ideas? thank you！

**Comment by tolusha** [comment]
@113xiaoji 
It seems Theia image is outdated.

**Comment by 113xiaoji** [comment]
@tolusha i use eclipse/che-theia: 0.3.18-6.17.1, is it out of data? i will use the latest images and try it again thank you

**Comment by 113xiaoji** [comment]
@tolusha I try to use theiaide/theia:next image bug it seams do not have plugins and debug, why? thank you very much, did i miss some configure or how to configure it, can you give me some doc or blog。Thanks again.
![image](https://user-images.githubusercontent.com/31875988/53576886-9fedfb00-3baf-11e9-8bf6-20ce2c9d1e45.png)

**Comment by 113xiaoji** [comment]
@tolusha @akosyakov thank you, i want to use python extension to debug remotely, can i join you? The docs are seemed not rich enough, i met some issue cannot figure out, so i asked you to use the right way to solve this problem.

**Comment by 113xiaoji** [comment]
@tolusha @akosyakov I execute python extension create termminal it shows
![image](https://user-images.githubusercontent.com/31875988/53581638-e98f1380-3bb8-11e9-9224-235a21425c10.png)
did you met before 
use the theiaide/theia-full

![image](https://user-images.githubusercontent.com/31875988/53581593-d2e8bc80-3bb8-11e9-92d7-689d57832f43.png)

**Comment by akosyakov** [comment]
@113xiaoji you will need to wait till the plugin system is ready to support it

in the meantime you can try https://github.com/vilkazz/theia-python-debug Theia extension @vilkazz probably can support on it?

**Comment by vilkazz** [comment]
@113xiaoji you are more than welcome to configure my extension for remote debug. I only tested the local debug, so I am very interested to know if the remote debug support is working!

I have most of the relevant configuration params dumped in the readme file in the repo, you can refer to the vs-python extension to see the full list of configurable parameters. Cheers!

**Comment by 113xiaoji** [comment]
@vilkazz HOW to use your npm package. 你是中国人吗？

**Comment by vilkazz** [comment]
i have written a short guide on how to use the ext in the spectrum app,
that you can find here:
https://spectrum.chat/theia/general/python-debuging~28800106-340a-468d-93a6-28700aaaa80d?m=MTU1MTQyMzA5MDU5OA==

you can also find my wechat id in my github profile and i can help you set
it up in more detail.


我不是中国人， 可是现在在中国工作。

**Comment by vince-fugnitto** [comment]
I believe the following issue can be closed, the `onDidReceiveDebugSessionCustomEvent` plugin API is supported in the framework. We have the following `theia-python-docker` image which makes use of the `python` vscode extension.
