### ISSUE TITLE
How to debug spring boot application?

### ISSUE THREAD

**Issue by devnewton** [eclipse-theia/theia#4457]
### Description

When I try to debug my application ( https://github.com/devnewton/jb3 ), I got the following error in Theia (no problem with a local IDE):

```
Binding to target org.springframework.boot.autoconfigure.web.ServerProperties@282ffbf5 failed:
    Property: server.port
    Value: tcp://10.100.5.114:3000
    Reason: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Integer' for property 'port'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.lang.Integer]
```

Maybe Theia is using environment variable that overrides Spring Boot configuration?

### Reproduction Steps

Launch https://gitpod.io/#https://github.com/devnewton/jb3 then debug.

**Comment by geropl** [comment]
Hi devnewton,

looks like this is more of a Gitpod issue. Could you move the ticket to https://github.com/gitpod-io/gitpod/issues? I'll look into it.
Thanks!

**Comment by vince-fugnitto** [comment]
@geropl I don't believe the issue was ever moved, either the author probably resolved the issue themselves or they have moved on. Should it be closed?
