### ISSUE TITLE
Preference editor focus problem when adding new build configuration

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#4465]
When I choose to create a new C++ build configuration (click on the status bar item, then choose create new), it opens the preferences editor, then switches directly to the "Workspace" tab of the preferences editor, which is fine.  However, it looks like the editor focus is still in the "User" tab:  when I type, nothing appears, it actually inserts content in the "User" tab, even though the "Workspace" tab is the visible one.

![bugfocuspreferences](https://user-images.githubusercontent.com/1758287/53652411-d27f0e80-3c16-11e9-8408-757b83fc4f93.gif)

**Comment by vince-fugnitto** [comment]
@elaihau didn't we notice this issue previously for the `preferences` widget in general ? I could not find the corresponding issue.

**Comment by vince-fugnitto** [comment]
@simark is it a dup of https://github.com/theia-ide/theia/issues/3184 ?

**Comment by simark** [comment]
> @simark is it a dup of #3184 ?

Maybe, I can't tell for sure.

**Comment by vince-fugnitto** [comment]
Closing since it is no longer an issue with the new _preferences-view_.
