### ISSUE TITLE
Failed to fetch workspace definition:getaddinfo EAI_AGAIN www.internalrequests.org:80

### ISSUE THREAD

**Issue by 113xiaoji** [eclipse-theia/theia#4474]
### Description

@akosyakov @tolusha I want to integrate che and theia with a new theia version , so i use dockerfiles to build new eclipse/che-theia images based on theia 0.4.0. I figure out it runs well aliyun. and pull the images from intranet proxy server and run again . It shows
![image](https://user-images.githubusercontent.com/31875988/53717711-fb600780-3e93-11e9-8810-2d72bdd98787.png)
and the terminal panel is unuseful. I want to know why the theia fetch the website www.internalrequests.org:80, what is it used to do.

does theia support run without network?

### Reproduction Steps
1. build theia source code
2. yarn add @eclipse-che/theia-generator
3. build docker image
4. pull image from  intranet proxy server
5. show error  

**OS and Theia version:**
theia 0.4.0
eclipse che 6.1.8
**Diagnostics:**

**Comment by 113xiaoji** [comment]
This issue is related by proxy

**Comment by akosyakov** [comment]
@113xiaoji please ask che related issue on che repo

**Comment by vince-fugnitto** [comment]
> @113xiaoji please ask che related questions on che repo

Closing since it is not related to framework.
