### ISSUE TITLE
plugin system breaks user storage abstraction

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4488]
[UserStorageService](https://github.com/theia-ide/theia/blob/ad9e62bd78bf4da3ce829b25de64f9aa3fc8aaeb/packages/userstorage/src/browser/user-storage-service.ts#L21) encapsulates where user data are stored, by default under `.theia` in user home.

Plugin system leaks it with own implementation: https://github.com/theia-ide/theia/blob/ad9e62bd78bf4da3ce829b25de64f9aa3fc8aaeb/packages/plugin-ext/src/main/node/paths/plugin-paths-service.ts#L140-L147

**Comment by kittaakos** [comment]
> [UserStorageService](https://github.com/theia-ide/theia/blob/ad9e62bd78bf4da3ce829b25de64f9aa3fc8aaeb/packages/userstorage/src/browser/user-storage-service.ts#L21) encapsulates where user data are stored, by default under `.theia` in user home.

The default workspace server uses a hard-coded `.theia` path too: https://github.com/eclipse-theia/theia/blob/1eaecd5cbf93468a74988ddcd347402fcbf14cbe/packages/workspace/src/node/default-workspace-server.ts#L165-L167

**Comment by mmorhun** [comment]
@kittaakos there is a PR which will handle that too: https://github.com/eclipse-theia/theia/pull/6650
I'm going to update it as soon as I regain write access into Theia repository.

**Comment by akosyakov** [comment]
@mmorhun if it is quite important change for 1.0, since we need Electron running vscode extensions properly. If it takes long please raise it that someone can add additional commits to finish it. You should also be able to open a new PR from your fork in the meantime as a workaround of missing write access.

**Comment by mmorhun** [comment]
@akosyakov I've pinged Eclipse Webmater, so I think in a day or so the issue should be resolved.
