### ISSUE TITLE
[terminal] On ubuntu 18.04 docker fonts looks bad

### ISSUE THREAD

**Issue by sudoec** [eclipse-theia/theia#4494]
**branch is tag v0.4.0**
![_20190306234457](https://user-images.githubusercontent.com/43877154/53893912-1a17f700-406a-11e9-8c46-3744cef975b8.png)

**Comment by msujew** [comment]
I don't think this issue is relevant anymore. It's at least not reproducible on Theia Blueprint, which uses Docker.
