### ISSUE TITLE
Can you publish WebdriverIO PageObjects to NPM?

### ISSUE THREAD

**Issue by jonnyhork** [eclipse-theia/theia#4497]
### Description
I am adding Theia extensions to my project and looking to setting up testing with WebdriverIO. I noticed that you have added some great PageObjects for Theia that would really help in my testing. I was wondering if you would be willing to publish those to make it easier to stay up to date and import via npm?

I was asked to open an issue for this by @akosyakov on Spectrum: https://spectrum.chat/theia/general/publishing-webdriverio-pageobjects~92840486-cdfd-4097-aacb-4c875b9a259b?m=MTU1MTg1Mjk5OTc1NA==

Thanks!

**Comment by akosyakov** [comment]
@marcdumais-work I remember you had an issue of reusable UI testing npm package which we can use in theia-apps as well.

**Comment by marcdumais-work** [comment]
@akosyakov Yes, or almost; as a first step I copied the test files over to the `theia-apps` repo. It would be one extra enhancement to publish the interesting/re-usable bits of our `wdio` test suite and re-use them for our Docker image tests, instead.

One impediment: Someone from Red Hat was working on replacing this test suite to use another framework (which name I do not remember right now). @benoitf do you know if this work is still ongoing? 

Here's the [commit](https://github.com/theia-ide/theia-apps/pull/110/commits/2fce4ff0eaf9ce7e6a89098cf5aaa027937278cc) where I copied-over the test files.

**Comment by jonnyhork** [comment]
@akosyakov Another thing I noticed is that the way the page objects are written don't seem to work with webdriverIO v5. That might cause some issues for people looking to import the published package that are using version 5, including myself. I'm not sure if there is any interest in updating those but that would be great!

**Comment by benoitf** [comment]
@marcdumais-work yes this is still ongoing work (to use cypress framework)
And in that case, pageobjects should be reused as well IMHO

**Comment by akosyakov** [comment]
Ok, so sounds like we can proceed with creating a new dev package and later upgrade it to wio 5 or cypress. It should go under [dev-packages](https://github.com/theia-ide/theia/tree/master/dev-packages) and named `@theia/ui-tests` or something similar.

I don't think TypeFox can do it. cc @svenefftinge 

Could Salesforce or Ericsson do it? @jonnyhork @marcdumais-work

**Comment by jonnyhork** [comment]
Do have any sense sense the timeline for switching Cypress officially? I'm if there are significant advantages to using Cypress with respect to Theia, other than and "All-in-one testing framework" as they say?

@akosyakov @marcdumais-work

**Comment by marcdumais-work** [comment]
@akosyakov I do not think we have the bandwidth to take this-on soon. Perhaps this could be part of the switch to Cypress?
 
@benoitf , WDYT?

**Comment by jonnyhork** [comment]
Hey @marcdumais-work, when you say 

> I do not think we have the bandwidth to take this-on soon 

Does that refer to publishing to NPM or the converting to WDIO 5.0, or both? Thanks for clarifying.

On a side note, after I switched to `"webdriverio": "4.9.2"`, from 5.0, I was able to use the PageObjects as is, imported via `yarn link`.

**Comment by marcdumais-work** [comment]
Hi @jonnyhork 

> Does that refer to publishing to NPM or the converting to WDIO 5.0, or both?

Both. We (Ericsson contributors) have put all non-essential work on this suite on hold for now, until the move to Cypress or decision to remain with WDIO.

**Comment by akosyakov** [comment]
> I'm if there are significant advantages to using Cypress with respect to Theia, other than and "All-in-one testing framework" as they say?

The main reason is that web driver based tests are flaky. Cypress tests run within Chrome and should be stable and faster. One has to verify it.

> On a side note, after I switched to "webdriverio": "4.9.2", from 5.0, I was able to use the PageObjects as is, imported via yarn link.

With yarn link, you have to always check out sources. It would be nice just to add dev dependency.

**Comment by jonnyhork** [comment]
@akosyakov 
>It would be nice just to add dev dependency
Yeah I agree, I just wanted to quickly verify they can be consumed as a package successfully.

**Comment by vince-fugnitto** [comment]
The `WebdriverIO` pages are no longer part of the repository, nor used to test the frontend of the framework.
Instead, the framework uses [@theia/api-tests](https://github.com/eclipse-theia/theia/blob/master/doc/api-testing.md#api-integration-testing) to verify integration tests.
