### ISSUE TITLE
Hitting Escape when IntelliSense (suggestions/completion widget) is open causes editor to lose focus

### ISSUE THREAD

**Issue by pzmarzly** [eclipse-theia/theia#4506]
Tested on Gitpod.

**To Reproduce**

- open editor
- start typing
- run IntelliSense with Ctrl+Space or just wait for it to pop up naturally
- hit Escape key
- try typing anything - editor doesn't have focus anymore!

**Expected behavior**

After hitting Escape, editor text area should have cursor again, you should be able to type.

**Comment by akosyakov** [comment]
I cannot reproduce it on master or in Gitpod. What browser do you use?

**Comment by pzmarzly** [comment]
Huh, indeed I can only reproduce it on Vivaldi (stable release). I don't have any shortcut bound to Esc though, and it also happens in incognito mode (no extensions loaded). [Video](https://youtu.be/w1TyJZH6liY)

Console output seems normal:

![screenshot from 2019-03-08 16-02-05](https://user-images.githubusercontent.com/8074163/54036289-92420200-41bb-11e9-94dd-2367728bed3c.png)

**Comment by vince-fugnitto** [comment]
I've confirmed that it is working for me with _vivaldi_, other browsers and electron for the same use-case.
I'll close since the issue is likely outdated.
