### ISSUE TITLE
Using Theia to build an entire system on the public server

### ISSUE THREAD

**Issue by djelenc** [eclipse-theia/theia#4534]
This is a question on how to approach a project that uses Theia at its core, not a bug report.

I’m working on a project that will contain an online IDE and I’m considering to use Theia. 

Users in my case should be able to create (rather simple) NPM projects (think React, Vue and similar, or even plain JS, HTML and CSS projects) and should see their preview in the pane next to IDE window. Something very similar to codesandbox, but less general, and using a few very specific options for my project.

I’ve been reading the Theia docs, but I’m unsure where to start. While the docs well explain how to run Theia on your local machine and run local projects, I’m trying to run it on a public server, that also builds and runs the projects that users create.

I’d appreciate any pointers on how to approach this.

**Comment by jankeromnes** [comment]
Hi @djelenc, the way we've done that in [gitpod.io](https://www.gitpod.io) (which uses Theia at its core) is to implement a [configuration file](https://docs.gitpod.io/41_Config_Gitpod_File.html) that allows doing things like:

```yaml
ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: npm install
  command: npm start
```

Maybe this approach can serve as inspiration, but note that Gitpod already supports your use cases well, and for free. 🙂

I'm happy to answer any more questions on this topic (in this GitHub issue, or somewhere that's better for general discussions) and in any case, good luck with your project! 👍

**Comment by deepakdahal** [comment]
@jankeromnes This page showed up on the search results and hope this is the right place for this question. 
I am looking for a browser based real time code sharing where I myself can host it rather than using the already hosted platform. Is it possible with Theia?

Thank you.

**Comment by akosyakov** [comment]
@deepakdahal Yes, you can build your own solution in the sense that you can share the same backend with other users. Unfortunately, there is no Theia extension yet for live collaboration like VS Code Live Share or Atom teletype.

**Comment by JonasHelming** [comment]
Question seems to be answered, please reopen in case there are any open questions left...
