### ISSUE TITLE
Request for Spell Checker

### ISSUE THREAD

**Issue by adrienrenaud** [eclipse-theia/theia#4546]
A spell checker would be useful for markdown files.

**Comment by vince-fugnitto** [comment]
I've had success in vscode using [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker), perhaps it'd be enough for your needs?
We are currently strengthening our plugin system to achieve compatibility with vscode extensions, and it'd be good to test the extension in Theia to notice any issues :)

**Comment by adrienrenaud** [comment]
Thanks @vince-fugnitto ! Does that mean that it is possible today to install vscode extensions in theia? Could you point me on an guide on how to do that?

**Comment by adrienrenaud** [comment]
Thanks a lot for this information, it looks amazing! I'm will try the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) in the coming days - as well as other extensions!

**Comment by kittaakos** [comment]
> vscode using [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker),

This. The one and only VS Code extension I am using. It works perfectly for markdown and code as well.

**Comment by vince-fugnitto** [comment]
> > vscode using [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker),
> 
> This. The one and only VS Code extension I am using. It works perfectly for markdown and code as well.

did you get the chance to try in Theia @kittaakos ? 😄

**Comment by vince-fugnitto** [comment]
@kittaakos I got the chance to try the `code spell checker` in Theia and got errors, so the compatibility is still not yet reached. One example error is the following:

```text
[Error - 15:47:28] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot destructure property `exclude` of 'undefined' or 'null'.
  Code: -32603 
```

**Comment by akosyakov** [comment]
@vince-fugnitto please file an issue, we need to track and fix them

**Comment by adrienrenaud** [comment]
`streetsidesoftware.code-spell-checker` seems to work fine for me with the browser example in  d380b17fee13d4c3042edd2884e58886d80528dd. Thanks

**Comment by vince-fugnitto** [comment]
@adrienrenaud thanks that's great news! 
If there are ever any incompatibilities or bugs regarding support for the extension please feel free to open issues so we can track and fix them 👍
