### ISSUE TITLE
recently opened files are not filtered in quick file

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4563]
see https://github.com/theia-ide/theia/pull/4549#issuecomment-472804656

**Comment by akosyakov** [comment]
@kittaakos is it  dup of https://github.com/theia-ide/theia/issues/4468?

**Comment by kittaakos** [comment]
I think so.

**Comment by vince-fugnitto** [comment]
> @kittaakos is it dup of #4468?

Closing in favor of https://github.com/eclipse-theia/theia/issues/4468.
