### ISSUE TITLE
Is there any reason why theia app can't run in Internet Explorer

### ISSUE THREAD

**Issue by jonghuyn** [eclipse-theia/theia#4575]
### Description
I am developing theia ide application using theia framework, but it couldn't run in i.e. so I am wondering why it couldn't. I thought the reason why i.e doesn't support some web technology what chrome support already.
### Reproduction Steps

**OS and Theia version:**
Windows 10
**Diagnostics:**

**Comment by akosyakov** [comment]
Which version do you mean? IE11? Older versions of IE are already out and IE11 is on the way out: https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support As far as I understood MS would prefer you to use Edge.  For us it would be an additional effort to rewrite codebase with only IE11 (which does not have future) compatible APIs.

What does not work concretely by the way?

**Comment by jonghuyn** [comment]
Thank you for your answer. I just tried to open browser i.e11. but anything dosen't show up.

![image](https://user-images.githubusercontent.com/14925542/54415076-8ff12200-473e-11e9-9efc-4c08735a3b22.png)

**Comment by akosyakov** [comment]
Are there any errors logs?

**Comment by jonghuyn** [comment]
No there aren't 
![image](https://user-images.githubusercontent.com/14925542/54416602-37705380-4743-11e9-9bd3-5de400bad225.png)

**Comment by vince-fugnitto** [comment]
I confirmed that on `IE 11` the application does not start, while `Edge` works.
I am getting an error from the console when starting, namely:

```console
SCRIPT1010: Expected identifier
bundle.js (106773,7)
```

which refers to the following line:

```js
const { Container } = __webpack_rquire__(/*! inversify */ "../../node_modules/inversify/lib/inversify.js"); 
```

Line @akosyakov mentioned, `IE 11` is at its end of life which means that any effort to support it would not be worthwhile at the moment.

**Comment by AlexandradelLago** [comment]
Hello, so is not possible to run in IE right?

**Comment by akosyakov** [comment]
No it won't be possible. Theia is based on Monaco (VS Code editor) and they don't have plans to support IE. It's also aligned with MS strategy to get rid of IE in favour of Chromium-based Edge.

**Comment by AlexandradelLago** [comment]
Hello again, would it be way can hook our code somewhere on a very early stage of application startup to identify that it is IE and redirect? bec it seems it just dont hit anything

**Comment by akosyakov** [comment]
There is a preload page which can be customized: https://github.com/eclipse-theia/theia/pull/4232

There also `initialize` and `configure` frontend app lifecycle callbacks: https://github.com/eclipse-theia/theia/blob/master/packages/core/src/browser/frontend-application.ts#L32-L43 the latter can delay the application activation.
