### ISSUE TITLE
language service of c/c++ vscode plugin is not working

### ISSUE THREAD

**Issue by tom-shan** [eclipse-theia/theia#4587]
### Description
When I start theia with [c/c++ vs code plugin,](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) the language service is not working.
The Auto-Completion, Go to Definition/Declaration and Quick Info (Hover) are not working at all.
### Reproduction Steps
1. git clone https://github.com/theia-ide/theia.git
2. cd theia
3. remove @theia/cpp dependency in examples/browser/package.json 
Because @theia/cpp extension also provide c/c++ language service and I don't want to confuse it with the vscode plugin.
4. yarn
5. mkdir plugins
6. wget https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/cpptools/0.21.0/vspackage -O plugins/ms-vscode.cpptools-0.21.0.vsix
7. cd examples/browser
8. yarn start
**OS and Theia version:**
OS: Ubuntu
Theia: latest master version
**Diagnostics:** 
![image](https://user-images.githubusercontent.com/7686800/54475729-f9049280-482f-11e9-9689-4755b686f9f8.png)

when refreshing the browser:
(node:7646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:7646) UnhandledPromiseRejectionWarning: Error: Unknown actor CommandRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/data/theia/packages/plugin-ext/lib/api/rpc-protocol.js:168:19)
    at RPCProtocolImpl.invokeHandler (/data/theia/packages/plugin-ext/lib/api/rpc-protocol.js:160:41)
    at RPCProtocolImpl.receiveRequest (/data/theia/packages/plugin-ext/lib/api/rpc-protocol.js:124:45)
    at RPCProtocolImpl.receiveOneMessage (/data/theia/packages/plugin-ext/lib/api/rpc-protocol.js:110:22)
    at /data/theia/packages/plugin-ext/lib/api/rpc-protocol.js:53:89
    at /data/theia/packages/plugin-ext/lib/api/rpc-protocol.js:201:17
    at /data/theia/packages/core/lib/common/event.js:161:33
    at CallbackList.invoke (/data/theia/packages/core/lib/common/event.js:176:39)
    at Emitter.fire (/data/theia/packages/core/lib/common/event.js:264:29)
    at ChildProcess.<anonymous> (/data/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:116:21)
(node:7646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)

**Comment by akosyakov** [comment]
@tom-shan Could you give a try again?

**Comment by akosyakov** [comment]
Could someone help to double check it?

**Comment by tom-shan** [comment]
@akosyakov sorry for my late reply. I tested the vscode cpp plugin in latest theia and it can work now. so I think this issue can be closed.

**Comment by akosyakov** [comment]
@tom-shan thank you for following up!
