### ISSUE TITLE
[cpp] Provide a way to specify directory of build configurations relative to the root of the workspace instead of full system path

### ISSUE THREAD

**Issue by lodup29** [eclipse-theia/theia#4588]
### Description
I tried different things but it looks like the only way to point Clangd to the build directory containing compile_commands.json is to specify the full path from the system's root which is not very portable. Being able to specify the directory from the workspace's root would be better. Of all the things I tried only the first one works:
```javascript   
      {
         "name": "build",
         "directory": "/home/theia/hello/build"
      },
      {
         "name": "build2",
         "directory": "${projectFolder}/build2"
      },
      {
         "name": "build3",
         "directory": "./build3"
      },
      {
         "name": "build4",
         "directory": "build4"
      },
      {
         "name": "build5",
         "directory": "${workspaceFolder}/build5"
      },
      {
         "name": "build6",
         "directory": "${workspaceRoot}/build6"
      },
```
### Reproduction Steps
- Run the theiaide/theia-full docker container
- download and untar the [attached simple cpp workspace](https://github.com/theia-ide/theia/files/2973977/hello.tar.gz) into /home/theia
- Toggle between the build configurations. Only with the first one the indexing result of clagd (.clang/index) will show up in the build directory

**OS and Theia version:**
theia-full docker container (theiaide/theia-full which I believe is based on Ubuntu 18.04)
Linux 42a80f21efaa 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Theia version : 0.5.0-next.da771757
**Diagnostics:** 
[hello.tar.gz](https://github.com/theia-ide/theia/files/2973977/hello.tar.gz)

**Comment by marechal-p** [comment]
```json
      {
         "name": "build5",
         "directory": "${workspaceFolder}/build5"
      }
```
Should work with latest master, are you able to confirm?

**Comment by vince-fugnitto** [comment]
@lodup29 were you able to resolve the issue?

**Comment by vince-fugnitto** [comment]
Closing the issue due to inactivity, please feel free to re-open if the issues still persists :+1:
