### ISSUE TITLE
open uri in vscode extension cannot take effect in theia

### ISSUE THREAD

**Issue by ouyangxizi** [eclipse-theia/theia#4593]
### Description
open uri in vscode extension cannot take effect in theia.

### Reproduction Steps
1.register command in vscode 
2.add code below
```vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://theia-ide.org'));```
3.cannot open the url in theia

**OS and Theia version:**
OS:Linux
Theia newest master code

**Diagnostics:** 
I have found mini-browser in theia, wonder how to call the mini-browser api to open the 
specific uri in theia？

**Comment by akosyakov** [comment]
> I have found mini-browser in theia, wonder how to call the mini-browser api to open the
specific uri in theia？

From Theia or VS Code extension?

**Comment by ouyangxizi** [comment]
> > I have found mini-browser in theia, wonder how to call the mini-browser api to open the
> > specific uri in theia？
> 
> From Theia or VS Code extension?

VS Code extension.

**Comment by akosyakov** [comment]
```ts
vscode.commands.executeCommand('mini-browser.openUrl', 'https://theia-ide.org');
```

**Comment by ouyangxizi** [comment]
> ```ts
> vscode.commands.executeCommand('mini-browser.openUrl', 'https://theia-ide.org');
> ```
> 
> But `vscode.open` should work, please keep an issue opened.

Thanks a lot. These codes worked!

**Comment by vince-fugnitto** [comment]
I confirmed the command `vscode.open` works with:

```ts
vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('https://theia-ide.org'));
```

https://github.com/eclipse-theia/theia/blob/cff1edad1c0fd3d9436e4119d18836a418e39cac/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L81-L83

https://github.com/eclipse-theia/theia/blob/cff1edad1c0fd3d9436e4119d18836a418e39cac/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L136-L159
