### ISSUE TITLE
Format Document command is always enabled

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#4608]
### Description
The context menu command "Format Document" is always available. Also when there is no formatting capability. 

### Reproduction Steps

- Create text document called aaa.bbb
- Right click the editor
- "Format Document" is enabled but doesn't do anything

**OS and Theia version:**
OS: Debian GNU/Linux
Thiea: 0.4.0

**Comment by vince-fugnitto** [comment]
The issue has been confirmed as resolved for both the `browser` and `electron` targets (confirmed using 763d3ba).
