### ISSUE TITLE
java doc show error when not open source file

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#4630]
### Description
Java Doc Show err
![image](https://user-images.githubusercontent.com/10203793/54734853-9a4b6a00-4bdd-11e9-8ef1-b2d2b3cd03b8.png)

if open the source file show Correct

![image](https://user-images.githubusercontent.com/10203793/54734897-d8488e00-4bdd-11e9-883e-df6e2cf53156.png)

### Reproduction Steps

**OS and Theia version:**
latest next version

**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 Could you provide an example project  and describe what you do?

**Comment by 502647092** [comment]
> @502647092 Could you provide an example project and describe what you do?

- Project Source https://github.com/502647092/MiaoScript
 
   - https://github.com/502647092/MiaoScript/blob/master/src/main/java/pw/yumc/MiaoScript/ScriptEngine.java
    - https://github.com/502647092/MiaoScript/blob/master/src/main/java/pw/yumc/MiaoScript/MiaoScriptEngine.java

**Comment by msujew** [comment]
Is this still reproducible? If so, it's probably an [java vscode extension](https://github.com/redhat-developer/vscode-java/issues) issue. I'm closing this.
