### ISSUE TITLE
Editorconfig properties not respected when anually changing file type

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#4672]
### Description
When manually changing a file type, the editorconfig properties are not respected anymore.

### Reproduction Steps

1. Start with a brand new workspace
2. Put this in the `.editorconfig` file
```
root = true

[*]
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.i]
indent_style = tab
tab_width = 8
```
3. Create the file `hello.i`.  You should see the correct whitespace setting, tabs and 8 columns:
![a](https://user-images.githubusercontent.com/1758287/54832633-ea383880-4c92-11e9-8c51-bf850b0c48ed.png)
4. Click on "Plain Text" and change the file type to some other type, like "C".
5. The whitespace settings will change to your default preference, ignoring what editorconfig says:
![b](https://user-images.githubusercontent.com/1758287/54832738-1b186d80-4c93-11e9-8492-4a03760c895f.png)

I think it should stay at "Tabs" and "8 columns".

Note that moving to another file and coming back to this one will re-apply the correct settings, since the editorconfig plugin reapplies the properties when focusing on an editor.

I investigated quickly, in `monaco-text-model-service.ts`, the `onDidChangeLanguage` callback gets called, which calls `updateModel`.  It then calls `getModelOptions`, which reads the whitespace settings from the preferences and applies them directly to the editor.  This doesn't give the editorconfig a chance to have a say.

**OS and Theia version:**

Linux, using the version of this PR (which fixes applying editorconfig properties on editors):

https://github.com/theia-ide/theia/pull/4584

**Comment by msujew** [comment]
The `@theia/editorconfig` package is deprecated for quite a few years now. Closing.
