### ISSUE TITLE
Create a meta package for base theia-ide extensions

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#469]
We should create a meta package called for example @theia/base-ide that contains all the extensions needed for a basic ide.

Since we're developing theia as many packages, it will become hard for a developer that wants to extend theia to figure out what extensions he needs and what are the proper versions of those packages.

This will help by providing 1 package you can include and develop from. 

At the moment this should contain all of theia-ide repo but the lsp extensions I think.

**Comment by svenefftinge** [comment]
Note, that we want to support automatic installation of transitive extensions (see #369). With that one really only needs to pick the 'end-user' extensions, i.e. what you care about. All the upstream dependencies will be pulled and installed automatically. Maybe this good enough.

**Comment by akosyakov** [comment]
I also would like to have it to have a single place to declare dependencies for examples.

**Comment by svenefftinge** [comment]
Isn't every example potentially different? Why is not the package.json of the concrete example the best place to put the list of extensions?

**Comment by akosyakov** [comment]
> Why is not the package.json of the concrete example the best place to put the list of extensions?

If one wants to support browser and electron at the same time with the same extensions then it also will be convenient to manage all dependencies in one place.

Theia CLI in https://github.com/theia-ide/theia/pull/391 allows removing generated code and build output with one command, maybe we can consider having one package instead of two.

**Comment by msujew** [comment]
I don't believe that this is still relevant. We have a yeoman project generator that already provides a list of "basic" Theia extensions for consumption.
