### ISSUE TITLE
[preferences] Moving the preferences editor makes the workspace tab view disappear

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#4702]
### Description
Dragging the preferences editor to the bottom/right side panel and the workspace preference page disappear, only the user preference remains.

### Reproduction Steps
1- File -> Settings -> Open Preferences
2- Drag the Preferences editor to the bottom panel
==> the workspace tab from the preference is gone

**OS and Theia version:**
Tested on Ubuntu 16.04

**Diagnostics:** 

![PreferencesMove](https://user-images.githubusercontent.com/419051/54931941-59f72f00-4ef0-11e9-8db1-f3ef2611dcb2.gif)

**Comment by vince-fugnitto** [comment]
Closing since the issue is no longer applicable with the updated UI.
