### ISSUE TITLE
[LS] Cannot use `CreateFile`, `RenameFile`, and `DeleteFile` inside a `WorkspaceEdit`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4723]
Spec: https://microsoft.github.io/language-server-protocol/specification#version_3_13_0

Currently, we use `vscode-base-languageclient@4.4.0` in Theia which has the following logic to handle `workspace/applyEdit`:
```js
if (change.textDocument.version && change.textDocument.version >= 0) {
```
Link: https://github.com/Microsoft/vscode-languageserver-node/blob/5f9c993ff38f5c369949aeb359b3e9b178172dbc/client/src/client.ts#L3019

VS. the `5.1.0` version:
```js
if (TextDocumentEdit.is(change) && change.textDocument.version && change.textDocument.version >= 0) {
```
Link: https://github.com/Microsoft/vscode-languageserver-node/blob/71fc1da3fed87329080f9c2a2c32e5e07aed3128/client/src/client.ts#L3167

The older version of the language client does not support these new `documentChanges` and will result in an error on the server side:
```
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request workspace/applyEdit failed with message: Cannot read property 'version' of undefined
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
```

**Comment by kittaakos** [comment]
This issue should be resolved as part of #4085. See [here](https://github.com/theia-ide/theia/issues/4085#issuecomment-454817896).

**Comment by kittaakos** [comment]
Here is a workaround, if you want to patch your extension's `LanguageClientFactory`:
```js
protected patch4085(client: MonacoLanguageClient): MonacoLanguageClient {
    let patchedClient = super.patch4085(client);
    patchedClient = this.patch4723(patchedClient);
    return patchedClient;
}

/**
 * https://github.com/theia-ide/theia/issues/4723
 * Patched with https://github.com/Microsoft/vscode-languageserver-node/blob/71fc1da3fed87329080f9c2a2c32e5e07aed3128/client/src/client.ts#L3158-L3180
 */
protected patch4723(client: MonacoLanguageClient): MonacoLanguageClient {
    (client as any).handleApplyWorkspaceEdit = ((params: ApplyWorkspaceEditParams): Thenable<ApplyWorkspaceEditResponse> => {
        // This is some sort of workaround since the version check should be done by VS Code in the Workspace.applyEdit.
        // However doing it here adds some safety since the server can lag more behind then an extension.
        let workspaceEdit: WorkspaceEdit = params.edit;
        let openTextDocuments: Map<string, number> = new Map<string, number>();
        this.editorManager.all.map(editorWidget => {
            if (editorWidget.editor instanceof MonacoEditor) {
                const model = editorWidget.editor.getControl().getModel();
                openTextDocuments.set(model.uri.toString(), model.getVersionId())
            }
        });
        let versionMismatch = false;
        if (workspaceEdit.documentChanges) {
            for (const change of workspaceEdit.documentChanges) {
                if (TextDocumentEdit.is(change) && change.textDocument.version && change.textDocument.version >= 0) {
                    let textDocumentVersion = openTextDocuments.get(change.textDocument.uri);
                    if (!!textDocumentVersion && textDocumentVersion !== change.textDocument.version) {
                        versionMismatch = true;
                        break;
                    }
                }
            }
        }
        if (versionMismatch) {
            return Promise.resolve({ applied: false });
        }
        return this.workspace.applyEdit((client as any)._p2c.asWorkspaceEdit(params.edit)).then((value) => { return { applied: value }; });
    }).bind(client);
    return client;
}
```

**Comment by kittaakos** [comment]
This is a bug too:
https://github.com/theia-ide/theia/blob/21d54a761f02c500677290d36af9f38a4d54578a/packages/monaco/src/browser/monaco-workspace.ts#L337

**Comment by kittaakos** [comment]
Upstream question: https://github.com/Microsoft/monaco-editor/issues/1396

**Comment by kittaakos** [comment]
@akosyakov, was this solved with https://github.com/eclipse-theia/theia/pull/5901? If so, I am going to verify it.

**Comment by akosyakov** [comment]
@kittaakos I've fixed in monaco-languageclient: https://github.com/TypeFox/monaco-languageclient/blame/b8f6f32429111f4d96f9581e63ecebc3cd104a7d/client/src/monaco-converter.ts#L405-L429

But we have to change [MonacoWorkspace.groupEdits[(https://github.com/eclipse-theia/theia/blob/bfe4bb577daa039008f6cb2e4deb4804cb53f61f/packages/monaco/src/browser/monaco-workspace.ts#L337) to respect `monaco.languages.ResourceFileEdit` as well. Would you be able to have a look at it?

**Comment by kittaakos** [comment]
> But we have to change [MonacoWorkspace.groupEdits](https://github.com/eclipse-theia/theia/blob/bfe4bb577daa039008f6cb2e4deb4804cb53f61f/packages/monaco/src/browser/monaco-workspace.ts#L337) to respect `monaco.languages.ResourceFileEdit` as well. Would you be able to have a look at it?

Thanks for your feedback. Sure; I'll take care of it.
