### ISSUE TITLE
[question] Is there a way to debug apps running in Chrome (like Vue)?

### ISSUE THREAD

**Issue by nils-mosbach** [eclipse-theia/theia#4727]
VS Code allows debugging of running applications within Chrome which is quite handy. To get this running an entry with type `chrome` can be defined in the `launch.json` configuration. 

This is basically the setting I used for vue (https://vuejs.org/v2/cookbook/debugging-in-vscode.html) in VS Code.
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "vuejs: chrome",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}/src",
      "breakOnLoad": true,
      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*"
      }
    }
  ]
}
```
If I try to run this in Theia it just gives me a warning that chrome is unsupported.
![image](https://user-images.githubusercontent.com/15126675/55039880-582f8780-5026-11e9-80c4-a6a39f32cc52.png)

I'm not a 100% sure if there's even a way to a attach a local chrome instance since VS Code might do this using native calls. Did I miss something or is this just not an option due to browser limitations?

By the way: I love to see how theia gets better every day. The UI changes of the last couple of days are teriffic.

**Comment by akosyakov** [comment]
Have you tried to install https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome? It should work for local Theia, for remote scenarios it could be tricky: https://stackoverflow.com/questions/6827310/chrome-remote-debugging-doesnt-work-with-ip

**Comment by nils-mosbach** [comment]
Installing the debugging extension works and might be an option for attaching to a running chrome instance if debugging is set to port 9229.
```
chrome.exe --user-data-dir="C:/temp/chrome" --remote-debugging-port=9229
```
`request` of type `launch` is not supported, but `attach` should do the trick.
```
{
  "version": "0.2.0",
  "configurations": [{
      "type": "chrome",
      "request": "attach",
      "name": "vuejs: chrome",
      ...
    }]
}
```
As you expected the challange is that this only works if theia can reach `localhost:9229`. I guess this might not be the default case for most theia deployments.

---

I was just wondering wether remote debugging could be channeled through a websocket connection which is currently opened anyway for hot deployments. Related to this I found a blog article from Microsoft that might head into the same direction.

https://blogs.windows.com/msedgedev/2018/05/11/introducing-edge-devtools-protocol/
https://blogs.windows.com/msedgedev/2018/04/25/introducing-the-microsoft-edge-devtools-preview-app/

Is debugging client applications written in angular, vue or react currently focused by theia? If so, I can also drop some requests in the react or vue communites. With all cloud development platforms popping up in the wild recently, someone might have had an idea on how to get remote debugging for client applications to work. What do you think?

**Comment by akosyakov** [comment]
Chrome has API to allow apps run debuggers: https://developer.chrome.com/extensions/debugger as far as I know chrome debug adapter is running on the top of Chrome debug protocol, so it could be that one can connect them without any need for remote communications if you run Theia and Vue app in the same instance of Chrome. One has to investigate further.

**Comment by sh7dm** [comment]
If you can SSH to the server, debugger port can be forwarded (`ssh -R`) from client to server, then you can use `attach` command to debug. Definitely, WebSocket debug will be a great thing! Chrome Debugger API can be used by an extension which then exposes it to `window` context, and then Theia or its extensions can use it and forward to host.

**Comment by sh7dm** [comment]
Off-topic: tested Firefox debugger with Theia, remote forwarding works just fine, so Chrome's one should be okay too.
