### ISSUE TITLE
[vscode] tasks.executeTask is missing

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4758]
Required for rust lang extension to install tooling and run tests from code lenses.

GH repo: https://github.com/rust-lang/rls-vscode

**Comment by vince-fugnitto** [comment]
Would you mind if I take a look into it  and learning @akosyakov?
I want to start contributing and helping out in the plugins area and @elaihau has already made significant efforts making our tasks compatible with vscode :)

**Comment by akosyakov** [comment]
sure, it would be nice if @elaihau opens a draft PR that progress is visible for others

**Comment by elaihau** [comment]
here it is: https://github.com/theia-ide/theia/pull/4761
i am currently on problem matchers, problem patterns, and task definition.

**Comment by benoitf** [comment]
hello, is there new status ?

**Comment by vince-fugnitto** [comment]
> hello, is there new status ?

I haven't been able to look at it this month, I believe @elaihau might take a look at it however, but you're more than welcome to work on it on your side if it's more urgent :)

**Comment by elaihau** [comment]
could this one be closed as we merged https://github.com/eclipse-theia/theia/pull/6058 ?

**Comment by akosyakov** [comment]
yes, thank you for taking care!
