### ISSUE TITLE
Vscode HTTPie extension compatibility

### ISSUE THREAD

**Issue by toonvd** [eclipse-theia/theia#4781]
### Description
The extension does not open the terminal when send request is clicked.
This is probably due to vscode.window.createTerminal not working.

https://github.com/wk-j/vscode-httpie/blob/d5a729d7c2f5b330bc419d5d7a30e74c41bcdf54/src/executor.ts#L4

### Reproduction Steps
- Install the extension:
   https://marketplace.visualstudio.com/items?itemName=wk-j.vscode-httpie#overview
- Create a request.httpie file
- Add ```http www.google.com search=='HTTPie logo' tbm==isch```
- Click send request

**OS and Theia version:**
Ubuntu - Theia v0.5.0

**Comment by benoitf** [comment]
cc @AndrienkoAleksandr

**Comment by benoitf** [comment]
Looking at the issue, there is a workaround if you select the whole text before clicking send request button
![httpie](https://user-images.githubusercontent.com/436777/56364533-0fb35600-61ef-11e9-9234-fb5bd01e7eb8.gif)

**Comment by benoitf** [comment]
https://github.com/theia-ide/theia/pull/4953 would fix one problem, there are still other issues after fixing one problem

**Comment by akosyakov** [comment]
was closed by mistake

**Comment by akosyakov** [comment]
@toonvd Does it work nicely now?

**Comment by toonvd** [comment]
Hi @akosyakov 

Apologies for the late reply, I can confirm that everything is working.
