### ISSUE TITLE
[ui/ux][enhancement] As a user I would like to see the number of Git changes on the side-bar's icon

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4782]
Just as VS Code does. It shows a notification badge with the number of changes.

VS Code:
![Screen Shot 2019-04-02 at 14 47 35](https://user-images.githubusercontent.com/1405703/55403508-4aae5c00-5556-11e9-8af4-3bf78ebaee4d.jpg)

Theia:
![Screen Shot 2019-04-02 at 14 53 43](https://user-images.githubusercontent.com/1405703/55403901-2606b400-5557-11e9-9a6b-5a225cbf360f.jpg)

Perhaps the notification badge should be able to show
 - a number, (from 1 up to a reasonable number),
 - a validation marker (error, warning so that we can have it for the editors like in Eclipse)

![Screen Shot 2019-04-02 at 14 52 09](https://user-images.githubusercontent.com/1405703/55403799-e93abd00-5556-11e9-97d5-c00e1637bdd5.jpg)

 - pending (same in VS Code)
 - tbd

**Comment by vince-fugnitto** [comment]
@kittaakos would you also expect the notification badge when not in the sidebar?
 (example: git was in the bottom panel)

**Comment by kittaakos** [comment]
> would you also expect the notification badge when not in the sidebar?

When it is feasible, sure, why not? If the badges are supported for the horizontal tabs too, we should use them. That's why I added the screenshot from Eclipse.
