### ISSUE TITLE
[explorer] flatten/compress folders in the explorer tree when possible

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#4783]
One enhancement to the current `Explorer` is to be able to flatten the tree when possible (whenever a parent directory contains a single child directory).

Such an improvement will allow for numerous benefits and improve the display of large workspaces. One such example is a large Java project with long package names.

In essence, the following tree:

```
+ com
  + domain
    + package
      + task 
        Task.java
...
```

can be optimized to the following:

```
+ com/domain/package/task
  Task.java
...
```
Here is the `VSCode` issue highlighting the change: https://github.com/Microsoft/vscode/issues/41627

**Benefits:**
1. Improves navigation of large projects (easier to navigate to the correct folder)
2. Improves display (easier to parse the tree visually)
3. Improves use of vertical space (more content can be displayed on the screen at once)
4. Removes useless information and manual intervention (takes longer to individually click each node that has no children in order to get to desired content)
5. Potentially speed up the display of the tree (no need to add unnecessary nodes with icons, labels, decorators)

**Limitations:**
1. Find a mechanism or way to add content in the middle, for example `domain` in the following package name `com.domain.package.task`
2. Users may not want to display a flattened `Explorer`, therefore a preference may be suitable, or simply flatten with the use of a `Toggle`.

**References:**
- [vscode flatten](https://github.com/Microsoft/vscode/issues/41627)

**Comment by marechal-p** [comment]
I like the idea, but I wonder about one use case. Say we have the followed compressed folders:

> + com/domain/package/task
>   Task.java
> ...

Would we be able to right-click only on the `domain` part of the compressed node, in order to create a new folder underneath it? Or a new file? I just want to make sure we still have some control on each directory.

**Comment by vince-fugnitto** [comment]
> I like the idea, but I wonder about one use case. Say we have the followed compressed folders:
> 
> > ```
> > + com/domain/package/task
> >   Task.java
> > ...
> > ```
> 
> Would we be able to right-click only on the `domain` part of the compressed node, in order to create a new folder underneath it? Or a new file? I just want to make sure we still have some control on each directory.

That exact scenario was previously discussed in the VS Code issue for the feature request.
I guess we'd have to try out `insiders` to see how VS Code handles it, and if its not to our liking think of a plan on how to tackle it. (perhaps double-clicking the compressed node expands it completely like we have today).
