### ISSUE TITLE
[proposal] add 'References' widget

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#4784]
I propose we implement and introduce the `References` widget in Theia.

![Screenshot from 2019-04-02 09-12-11](https://user-images.githubusercontent.com/40359487/55405183-7cf49500-5527-11e9-845b-b3371d021aaf.png)

The widget (triggered by the `Find All References` command) offers a more persistent option as compared to the `Peek References` command. It opens the search results in a designated widget as compared to the peek, and is great for todo lists. Since it is a widget, it is also possible to save it's state in local storage to easily be able to recover on startup.

**Comment by akosyakov** [comment]
We should use vscode extension: https://github.com/Microsoft/vscode-references-view

**Comment by vince-fugnitto** [comment]
> We should use vscode extension: https://github.com/Microsoft/vscode-references-view

Oh great! It looks like its the official extension and is shipped with vscode, it'd be great to try it in Theia :)

**Comment by akosyakov** [comment]
But there are many missing things yet to run it:
```json
  ],
  "missingSymbols": [
    "\"vscode\".Clipboard",
    "\"vscode\".Clipboard.writeText",
    "\"vscode\".ThemeIcon.File",
    "\"vscode\".TreeItem.description",
    "\"vscode\".TreeView.message",
    "\"vscode\".TreeView.onDidChangeVisibility",
    "\"vscode\".TreeView.visible",
    "\"vscode\".TreeViewVisibilityChangeEvent",
    "\"vscode\".TreeViewVisibilityChangeEvent.visible",
    "\"vscode\".env.clipboard"
  ],
  "missingCommands": [
    "editor.action.showReferences",
    "editor.findMatchHighlightBackground",
    "vscode.executeReferenceProvider"
  ],
  "dynamicCommanCalls": [
    "`${viewId}.focus` (/workspace/vscode-references-view/src/extension.ts 58:39)"
  ]
```

Someone has to look into them. Complete `TreeView` interface would be the easiest to start.

**Comment by tsmaeder** [comment]
TreeView.message and the commands "editor.findMatchingHighlightBackground" and "vscode.executeReferenceProvider" seem to be missing, the rest seems to work in master as of today

**Comment by tsmaeder** [comment]
See in plugin-vscode-commands-contribution.ts

**Comment by tsmaeder** [comment]
Btw: view.messages is the text that shows "20 results in 12 files" at the top of the view.

**Comment by akosyakov** [comment]
resolved by https://github.com/eclipse-theia/theia/pull/7055
