### ISSUE TITLE
[electron] support macOS mojave dark mode

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#4789]
Apple introduced a [system-wide dark mode](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/) in Mojave (10.14) update.

It would be nice to able to support this new [theming](https://electronjs.org/docs/tutorial/mojave-dark-mode-guide) in Electron for users who like the Dark Mode. 
This would mean enabling and supporting the dark mode for menus, application title bar, context menu and typography.

**Comment by benoitf** [comment]
FYI when using Safari, web sites can also be compliant with dark mode. (10.14.4)

**Comment by kittaakos** [comment]
For the bundled electron application, it is
```yaml
mac:
  darkModeSupport: true
```
in the `electron-builder.yml` configuration.

**Comment by vince-fugnitto** [comment]
> For the bundled electron application, it is
> 
> ```yaml
> mac:
>   darkModeSupport: true
> ```
> 
> in the `electron-builder.yml` configuration.

Moving the issue to `theia-apps` to update the `electron-builder.yml` :)
