### ISSUE TITLE
Support custom Shell widgets

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#479]

**Comment by hexa00** [comment]
Please give a bit more info/context ?

**Comment by akosyakov** [comment]
Currently, we assume that always `Shell` is used: https://github.com/theia-ide/theia/blob/fb0dca0f7e21bc16b64b765be7539e3ca558d40d/packages/core/src/browser/frontend-application.ts#L53-L64

If someone wants to have the different layout, more fixed or without side bars is not possible.

**Comment by spoenemann** [comment]
Now the ApplicationShell can be customized with dependency injection. If you want to change the layout, simply override `createLayout`.

> without side bars

How should it behave when side bars are disabled? E.g. if an extension contributes a widget and wants to add it to the left panel:

 * The widget is added to the main area instead?
 * The widget is not added? (silently? throwing an error?)

**Comment by akosyakov** [comment]
Related https://github.com/theia-ide/theia/issues/4482

**Comment by spoenemann** [comment]
Is there anything left to do here? Should we extract an interface from ApplicationShell?

**Comment by akosyakov** [comment]
It is hard right now, one has to understand `ApplicationShell` and remove stuff. Having an interface probably would help.

**Comment by spoenemann** [comment]
But that would mean we need to inject a Symbol instead of the class, so it's possibly a breaking change? Do you think it's worth the effort?

**Comment by JonasHelming** [comment]
@spoenemann : I suggest closing this, as FMPOV, the original issue is fixed...
