### ISSUE TITLE
gltf-vscode extension not working

### ISSUE THREAD

**Issue by mikestaub** [eclipse-theia/theia#4825]
### Description
I followed these instructions. The extension is loaded but there are no commands added to the palette. No errors either. https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions

### Reproduction Steps
Download this extension to the plugins folder. Then run the browser example:
https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode

**OS and Theia version:**
Debian thea@latest

**Comment by vince-fugnitto** [comment]
Sorry, it looks like the issue may have gone unnoticed.
I verified if the extension provided commands and it successfully does (as well as preferences):

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/67708114-00794600-f992-11e9-8493-67db1d6fc956.png)


![image](https://user-images.githubusercontent.com/40359487/67708159-0d963500-f992-11e9-9702-bba26ab38095.png)


</div>

I haven't done further investigation however if the extension works correctly.

**Comment by vince-fugnitto** [comment]
@mikestaub please re-open the issue if you still experience issues with the gltf extension.
Based on my previous investigation, the extension was successfully contributing commands and it's preferences.
