### ISSUE TITLE
support vscode theming

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4831]
See https://code.visualstudio.com/api/extension-capabilities/theming

**Comment by jgbradley1** [comment]
I was just reading about themes. From what I understand, if Theia wants to leverage existing VS code themes, then all of the variables referenced in the css files [here](https://github.com/theia-ide/theia/tree/master/packages/core/src/browser/style) will require refactoring. Namely, rename the variables and align them to their [VS Code equivalent](https://code.visualstudio.com/api/references/theme-color). Then Theia themes could rely on the same [theme creation process](https://code.visualstudio.com/docs/getstarted/themes#_creating-your-own-color-theme) as VS Code.

**Comment by akosyakov** [comment]
Something like that, or we will need to have some kind of mapping if we don't want to break.

**Comment by ghuntley** [comment]
Can't wait for this to land - thank you @akosyakov.

**Comment by ghuntley** [comment]
HUGE <3

**Comment by clovis-dugue** [comment]
@akosyakov Hi, I just stumbled upon this issue.  

Are product icon themes implemented ? When searching the commands, VSCode provides 2  while Theia only has the "File Icons" commands.
![image](https://user-images.githubusercontent.com/32169889/114987659-b2157b00-9e95-11eb-88c6-5aa84fd26216.png)  

VSCode does list it in its [capabilities](https://code.visualstudio.com/api/extension-capabilities/theming#product-icon-theme).

Furthermore, I could not find an equivalent to the [product icon reference](https://code.visualstudio.com/api/references/icons-in-labels#icon-listing) for Theia. Did I miss it ?
