### ISSUE TITLE
[ui/ux] It should be possible to avoid the `Reload site?, Changes you made may not be saved.` when refreshing the browser

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4848]
### Description
 

As of ce2f145017ff6bca715cddb96f876366eb1a4b22, whenever I refresh the browser with <kbd>Ctrl/⌘</kbd>+<kbd>R</kbd>, the application raises a native dialog and warns me: `Reload site?`. This was introduced to avoid accidental application closing with <kbd>Ctrl/⌘</kbd>+<kbd>W</kbd> but could be very annoying during the development.

Let's make this dialog configurable so that Theia developers can disable it for the dev phase.

### Reproduction Steps

 - Open a WS.
 - Refresh the browser.

**OS and Theia version:**
 - All.

**Comment by marechal-p** [comment]
Is this preference enough?

https://github.com/theia-ide/theia/blob/185412895a1dd52bd27e8c333011d46ff8bc003f/packages/core/src/browser/core-preferences.ts#L32-L41

**Comment by akosyakov** [comment]
@kittaakos @marechal-p fyi this preference disables confirmation completely even for dirty editors

**Comment by kittaakos** [comment]
> Is this preference enough?

Yes.
