### ISSUE TITLE
set up nightly builds of electron distribution

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#4877]
That end users can download it and report issues if it does not work, similarly how we get to know about issues in docker images.

It would be good:
- to have it outside of this repo to show how end users can do the same
- to build for mac, linux and win
- include custom branding extension to show how to brand (cc @vince-fugnitto)

It can be done in [theia-apps](https://github.com/theia-ide/theia-apps) and iteratively.

I don't know anything about how it can be set up, so any help is appreciated.

cc @kittaakos @thegecko @spoenemann @JanKoehnlein

**Comment by thegecko** [comment]
Nice idea. We use jenkins locally to do this so it can be built for windows, mac and Linux.

Different options are available based on the target platforms wanted. I assume Linux to start?

**Comment by kittaakos** [comment]
> * to have it outside of this repo

I do not like this, we won't be able to verify any electron related changes: #4874.

**Comment by spoenemann** [comment]
Microsoft Azure can be used partly for free for open source projects, and it can build for Mac, Linux and Windows. That might be an option for the Electron app build.

**Comment by akosyakov** [comment]
> I do not like this, we won't be able to verify any electron related changes: #4874.

It is the same now with docker images. I don't think delay in one day is too bad, we still have time till release (end of month) to fix/revert it.

End users have completely another setup it would be nice to replicate it.

**Comment by vince-fugnitto** [comment]
@akosyakov I've created a custom [C++ branding extension](https://github.com/vince-fugnitto/theia-cpp-branding) in the past, would it be enough to create a similar extension with Theia branding? It wouldn't necessarily be like https://github.com/theia-ide/theia/pull/3980 where it is customizable, it would just provide Theia branding for our own distributions.

**Comment by akosyakov** [comment]
Closed in favour of https://github.com/eclipse-theia/theia/issues/5481
