### ISSUE TITLE
Pressing from up in the open dialog topmost item loses selection and key control

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#488]
![open-dialog-selection-loss](https://user-images.githubusercontent.com/698076/30272486-c08ca3b8-96c2-11e7-9225-49349bfa7b01.gif)

Navigate in a sub-directory then use the up arrow to navigate up.
Observe that the cursor and selection is lost, using down to come back doesn't work.

Strangely if you just use up on the first shown directories (if you do not navigate to a sub directory) things work as expected, the topmost item keeps the selection and you don't lose your cursor.

**Comment by svenefftinge** [comment]
I cannot reproduce this in Chrome on OSX. Please reopen if that doesn't work the same on other platforms.

**Comment by hexa00** [comment]
I can still reproduce on Chrome Version 62.0.3202.94 in Linux
