### ISSUE TITLE
Question - how Debug server should be deployed to kubernetes cluster ? 

### ISSUE THREAD

**Issue by PavelSosin** [eclipse-theia/theia#4898]
### Description
Question: How application should be deployed to kubernetes cluster for debugging ? Single pod headless service and proxy afinity = cookies ? In such scenario any additional proxy will be redundant
### Reproduction Steps
See all tickets related to Theia debug session stability
Expected:
Debugging session stability regardless proxy and infra processing path of WebSocket protocol timeouts 
Actual:
Frozen sessions, Debug server failures, etc.
**Diagnostics:**

**Comment by akosyakov** [comment]
@geropl maybe you can help here. In Gitpod i don't see any frozen sessions, server failures and so on.

**Comment by PavelSosin** [comment]
@3 issues that are relevant for us:
 
https://github.com/theia-ide/theia/issues/4591 - enhancement debugger
https://github.com/theia-ide/theia/issues/4590 - bug debugger vscode integration
https://github.com/theia-ide/theia/issues/4608 - for this one they haven’t responded at all

Please, take into account that WebSocket protocol is extremely allergic for communication errors and proxy bad-doing, Server exits on communication error by default
DAP protocol doesn't define any recovery sequence too. I think that the best option is to isolate WS communication into WeWorker and close debugger window upon error. I created the skeleton code for WS Proxy WebWorker which transforms WS error into DAP close event to enforce UI close
[WebsocketProxyWorkker.txt](https://github.com/theia-ide/theia/files/3079614/WebsocketProxyWorkker.txt)

If Application is deployed as a part of Kubernetes Service based on persistent set and Proxy Afinity is configured then, after UI re-open User will return to the same debugging state

**Comment by akosyakov** [comment]
Plugin debug sessions will be closed for now on reconnection: https://github.com/eclipse-theia/theia/pull/6159

Track https://github.com/eclipse-theia/theia/issues/3361 and https://github.com/eclipse-theia/theia/issues/4590 for sharing and preserving sessions.
