### ISSUE TITLE
tree view right-click causes it to move to the top

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#4901]
### Description
Right-click causes the list to move to the top 

### Reproduction Steps
right click any file then click on the blank area

**OS and Theia version:**
latest next version

**Diagnostics:** 
![temp](https://user-images.githubusercontent.com/10203793/56093862-22344380-5f00-11e9-9a9b-a0e1feb02955.gif)

**Comment by 502647092** [comment]
@akosyakov how to solve this problem

**Comment by 502647092** [comment]
@akosyakov what caused the problem?
can we fix it ?

**Comment by akosyakov** [comment]
@502647092 i don't know, someone needs to investigate. The file navigator suppose to reveal selected file, somehow it reveals something else.

**Comment by 502647092** [comment]
@akosyakov 
i find all the tree view
rigit click will cause it move to top
![temp](https://user-images.githubusercontent.com/10203793/63149921-0c629680-c038-11e9-85d0-da8ee804198d.gif)

**Comment by akosyakov** [comment]
ok, i will have a look, it seems to be super annoying UI glitch

btw is it a dup of https://github.com/theia-ide/theia/issues/1593?

**Comment by 502647092** [comment]
> ok, i will have a look, it seems to be super annoying UI glitch
> 
> btw is it a dup of #1593?

not
#1593 is left click and scroll a little
this is right click and scroll to top

**Comment by akosyakov** [comment]
@svenefftinge I still can reproduce it by trying to create a new file and then cancelling it with `escape`.
