### ISSUE TITLE
alt+w doesn't close preview window

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#4903]
### Description
![image](https://user-images.githubusercontent.com/10203793/56096331-5831f180-5f19-11e9-8c0b-9aed9a1cda99.png)

### Reproduction Steps
click file in explorer
press alt+w doesn't close preview window

**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 electron right?

**Comment by 502647092** [comment]
> @502647092 electron right?

No
Chrome Browser
if i double click to open file 
alt + w can close

**Comment by sauny** [comment]
Just tried to reproduce this and it seems to work fine for me...

**Comment by 502647092** [comment]
@sauny 
at latest version i can't close also
