### ISSUE TITLE
[debug] Use type definitions for `ps-list`.

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4925]
I have stumbled upon this `TODO` in the source:

https://github.com/theia-ide/theia/blob/a388fc577b5a7694ab238678e1ff669487c520b4/packages/debug-nodejs/src/node/node-debug-adapter-contribution.ts#L18

It seems the [type definitions](https://github.com/sindresorhus/ps-list/pull/28) are available for `ps-list`.

Edit: fixed the npm package name.

**Comment by colin-grant-work** [comment]
I don't believe that this issue is relevant any longer. The file referred no longer exists, and the package does not appear to be used anywhere in the framework.
