### ISSUE TITLE
VSCode Docker extensions does not work

### ISSUE THREAD

**Issue by roflcoopter** [eclipse-theia/theia#4935]
### Description
 The VSCode docker extension does not load in Theia.

### Reproduction Steps
1) Install https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker
2) Start Theia

**OS and Theia version:**
Ubuntu 18.04 - Theia nex 0.6.0

**Diagnostics:** 
It fails with this error
`
root ERROR [hosted-plugin: 12451] (node:12451) UnhandledPromiseRejectionWarning: Error: Internal error: Could not find keytar module for reading and writing passwords
    at /home/theia/plugins/vscode-docker/extension/dist/extension.bundle.js:263:1618389
    at Function.tryCreate (/home/theia/plugins/vscode-docker/extension/dist/extension.bundle.js:263:1618481)
    at /home/theia/plugins/vscode-docker/extension/dist/extension.bundle.js:157:603905
    at Object.t.activateInternal (/home/theia/plugins/vscode-docker/extension/dist/extension.bundle.js:157:603957)
    at activate (/home/theia/plugins/vscode-docker/extension/main.js:22:28)
    at PluginManagerExtImpl.startPlugin (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:172:73)
`

**Comment by tetchel** [comment]
VS Code shipping Keytar is not API - see https://github.com/Microsoft/vscode/issues/68738

**Comment by roflcoopter** [comment]
I see, do you have any idea how I can install it manually?

Tried putting it in my package.json which doesn't seem to work

**Comment by tetchel** [comment]
Maybe someone from the Theia team can comment, but native modules are a difficult problem because they have to be compiled per-platform. https://github.com/Microsoft/vscode/issues/658

**Comment by dinvlad** [comment]
@roflcoopter have you gotten around this problem? I've tried everything it seems, but the core of the problem seems to be their use of `${vscode.env.appRoot}` value, which is undefined in Theia, afaiu: https://github.com/microsoft/vscode-docker/blob/e63ce0eea9f25e94a968005a41f72ad2982a77e3/src/utils/getCoreNodeModule.ts#L14

Or is there a way to resolve "hard-coded" `${vscode.env.appRoot}` inside Theia?

**Comment by akosyakov** [comment]
@dinvlad syntax highlighting is contributed by built-in vscode extensions: https://github.com/microsoft/vscode/tree/master/extensions/docker

We've republished them to npmjs to consume: https://www.npmjs.com/package/@theia/vscode-builtin-docker

**Comment by akosyakov** [comment]
You can try open an issue for vscode-docker to make it configurable somehow. How do you think we could help you from our side? In electron app it probably can be the same, but for browser target we don't have `node_modules.asar`. We should provide though proper `vscode.env.appRoot` so maybe you can have a script installing keytar in the proper location.

**Comment by dinvlad** [comment]
Thanks! Will use `@theia/vscode-builtin-docker`. I was confused by the claim on `vscode-docker` extension page that it provides syntax highlighting :)

Re `appRoot`, I’m still confused because it seems like `@theia/plugin-ext` already provides the `env` namespace with `appRoot`: https://github.com/theia-ide/theia/blob/4a54abb6741672d291af1919ec610a51fa4e7556/packages/plugin-ext/src/plugin/node/env-node-ext.ts#L54

I guess it’s just not getting converted to `vscode` import?

**Comment by dinvlad** [comment]
Sorry if this is off-topic here, but I got the highlighting working now too, by packaging https://github.com/microsoft/vscode/tree/master/extensions/docker directly with `vsce package`, and installing it as a VSCode plugin.

So at this point, everything seems to be working re `vscode-docker`, provided I replace `${vscode.env.appRoot}` with `__dirname` in it. I can no longer see errors in the console, and all relevant functionality seems to work well (incl. getting contextual help inside Dockerfiles).

**Comment by akosyakov** [comment]
It seems to be bogus that `appRoot` is implemented with `__dirname` in `ext-node-ext.ts`. I would expect that it point to cwd from which Theia is started. Probably just copying impl from vscode will do: https://github.com/microsoft/vscode/blob/6964233e81c68f5a5f34e7eb1da0836e1d539f14/src/vs/platform/environment/node/environmentService.ts#L83

cc @benoitf @evidolob

**Comment by dinvlad** [comment]
@akosyakov you're right, I spoke too soon - `__dirname` doesn't work after all. It only works when I replace `${vscode.env.appRoot}` with the literal value of the path from which Theia is started.. So the code you linked makes sense.

**Comment by dinvlad** [comment]
How about we replace `__dirname` with `process.cwd()` in https://github.com/theia-ide/theia/blob/4a54abb6741672d291af1919ec610a51fa4e7556/packages/plugin-ext/src/plugin/node/env-node-ext.ts#L54 ?

That seems to work, i.e. `process.cwd()` points to the folder from which Theia was started (`/opt/theia` in my setup).

**Comment by akosyakov** [comment]
@dinvlad please open a PR @benoitf @evidolob Do you see any concerns with it? My only concern that it relies on `child_process.fork` behaviour. If we at some point provide another `cwd` it will be silently broken. I would rather ask main Theia process for a proper app root.

**Comment by dinvlad** [comment]
That make sense @akosyakov! I'm not sure where to plug in that kind of code though..

**Comment by akosyakov** [comment]
@dinvlad we could pass it as env variable here: https://github.com/theia-ide/theia/blob/797db759bcdde66c8bbabf2ab0b041bc7d887d30/packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts#L158 you can get the proper app path from [here]( https://github.com/theia-ide/theia/blob/b67025d7165c8a3f0b7170efb044263992593813/dev-packages/application-package/src/application-package.ts#L39), i.e. via injecting `ApplicationPackage`

**Comment by JennyMet** [comment]
I've the same issue when using vscode-docker 1.6.0 , I saw that this is issue have started more then a year ago, is there any progres? or any workaround that we can use?

**Comment by sumeshkanayi** [comment]
Same here .I tried the steps mentioned by @dinvlad ie:by changing the path returned to /data/theia (in my case theia is started from here) but ended up with keytar error .I confirmed that keytar is available locally though

**Comment by Viromic** [comment]
Activating extension 'Docker' failed: Internal error: Could not find keytar module for reading and writing passwords is still not operational

**Comment by vince-fugnitto** [comment]
The issue seems to be fixed for newer versions of [vscode-docker](https://open-vsx.org/extension/ms-azuretools/vscode-docker) as `keytar` is deprecated in favor of using the secrets api.
In the future vscode will completely remove support for [`keytar`](https://code.visualstudio.com/updates/v1_80#_keytar-deprecation-plan).
