### ISSUE TITLE
[vscode] plugin php-intellisense not support

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#4959]
### Description
![image](https://user-images.githubusercontent.com/10203793/56431631-09ab9b00-62fd-11e9-8614-616f997f2d77.png)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by benoitf** [comment]
FYI in Eclipse Che we're working on supporting the other PHP extension https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client

which brings more stuff https://github.com/eclipse/che/issues/12796

**Comment by benoitf** [comment]
@502647092 are you expecting to use all these extensions in Theia or you're just doing some randoms checks on most popular extensions ?
Because I saw you're checking lot of VS Code extensions on top of Theia

**Comment by 502647092** [comment]
because Theia's extension has some problems
i try use vs-code extension replace it
like php java
If it can't be repaired in the near future
I can only both use theia extensions and vs-code extensions

**Comment by 502647092** [comment]
this maybe cause PHP environment is not configured correctly.
after install php7-tokenizer is can work
but syntax highlighting #4966 still unable to work both theia-ext and vs-code-ext
I remember that the previous version was okay.

**Comment by akosyakov** [comment]
For syntax highlighting we should upgrade to latest vscode-textmate package. There were some important fixes. PRs are welcomed!
