### ISSUE TITLE
Help `webpack` to pick up the  `ipc-bootstrap.js` from the IPC connection provider

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#4985]
This is required for #4541.

By default, `webpack` cannot do much with
https://github.com/theia-ide/theia/blob/b0aaeca92482ca2e50d601fa34093e05eeac29b1/packages/core/src/node/messaging/ipc-connection-provider.ts#L103

**Comment by marechal-p** [comment]
I managed to get this working. The method I used was to monkey-patch Theia's sources to replace the require call made at that point with `__non_webpack_require__` and exposing each individual entry point as separate Webpack entry points. See my prototype configuration: https://github.com/eclipse-theia/theia-blueprint/blob/dbe08f1/applications/browser/node-webpack.config.js#L15-L52

**Comment by msujew** [comment]
This should have been resolved with https://github.com/eclipse-theia/theia/pull/12412.
