### ISSUE TITLE
Need to make the explorer view visible by default

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#4992]
### Description
I need an extension API to make the explorer view maximized by default when editor opens with work-space.
Right now I have to click on the explorer icon to click on the explorer button to see the project tree
 I couldn't able to find the way to achieve this.

**Comment by akosyakov** [comment]
For Theia extension, it's already possible. You should inject the navigator contribution and call open on it. Do you mean VS Code extension?

**Comment by vince-fugnitto** [comment]
@dhananjayharel do you still require assistance?

**Comment by vince-fugnitto** [comment]
@dhananjayharel please feel free to re-open the issue if you do require additional assistance. 
Since there was no subsequent follow-up, I will assume that it is no longer an issue for you.
