### ISSUE TITLE
Support AtlasMap VS Code extension

### ISSUE THREAD

**Issue by apupier** [eclipse-theia/theia#5007]
### Description

it would be nice to support VS Code AtlasMap extension.
The extension has not been published yet on VS Marketplace. The source code is located here https://github.com/jboss-fuse/vscode-atlasmap . A built vsix is available [here ](https://drive.google.com/open?id=1yVqJgJtWr3zZ0h4eyV5-reNWtyv5-VAt)

### Reproduction Steps

- install the extension (currently I tried using _docker run -it --rm -p 3000:3000 -p 3030:3030 -p8585:8585 -v C:/git/theia/plugins:/plugins -e THEIA_PLUGINS=local-dir:///plugins theiaide/theia-full:next_ )

Different things to try 

- Go to command palette and try to call "AtlasMap: Open AtlasMap"
- Right-click on projects and "Upload file...", use an *.adm file, for instance this one https://drive.google.com/open?id=1kHoZJNScp9JyD9yDMSySPWRA_cnah3-J

**OS and Theia version:**

Windows 10
master

**Diagnostics:** 

Currently:

- port 8585 needs to be provided.
- the output for AtlasMap Server is showing that the AtlasMap server is starting well
- there is an "unhandled Navigation error" in console when opening AtlasMap (but seems to have no functional impact)
- when trying to "export a file", there is an error: _Refused to display 'http://localhost:8585/#' in a frame because it set 'X-Frame-Options' to 'deny'._
![image](https://user-images.githubusercontent.com/1105127/56792096-0aff2b00-6809-11e9-8506-f0d71e621dab.png)
- Progress notification is mentioning a negative progress number: "-1%"
- Import is opening File browser for filesystem of the browser (I guess it is fine), it might be interesting to have a way to import adm files from the Theia workspace too.

**Comment by apupier** [comment]
for the X-Frame-options, some explanations here https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/X-Frame-Options

I'm not sure who is providing the X-Frame-options.
A workaround would be to set X-Frame-Options: ALLOWALL but might not be very secure. Should be better with X-Frame-Options: ALLOW-FROM https://example.com/ but how to determine the url?

**Comment by akosyakov** [comment]
@apupier Is it about webviews? We should actually make sure that each webview is opened from own origin, otherwise any plugin can access browser shared state for the same origin, like cookies, local storage and so on.

**Comment by apupier** [comment]
> @apupier Is it about webviews?

yes, it is from a webview.

> We should actually make sure that each webview is opened from own origin, otherwise any plugin can access browser shared state for the same origin, like cookies, local storage and so on.

How are we doing that?

**Comment by apupier** [comment]
currently we are providing a localhost URL in the href attribute of the page used:

https://github.com/jboss-fuse/vscode-atlasmap/blob/a68b8150864cdce4040fe2be45823da3a88e82ad/src/atlasMapWebView.ts#L94

https://github.com/jboss-fuse/vscode-atlasmap/blob/a68b8150864cdce4040fe2be45823da3a88e82ad/src/extension.ts#L182

**Comment by akosyakov** [comment]
@apupier please try with https://github.com/eclipse-theia/theia/pull/6465

**Comment by akosyakov** [comment]
@apupier Could you change an extension to use [asExternalUri](https://code.visualstudio.com/updates/v1_40#_vscodeenvasexternaluri) instead of localhost, otherwise it is hard to make it work remotely.

**Comment by apupier** [comment]
> @apupier please try with #6465

currently trying to setup an environment to use a non-published Che version.

> @apupier Could you change an extension to use [asExternalUri](https://code.visualstudio.com/updates/v1_40#_vscodeenvasexternaluri) instead of localhost, otherwise it is hard to make it work remotely.

need to investigate. i'm not familiar with this. Don't know what is the difference.

**Comment by akosyakov** [comment]
It makes sure that localhost request are reserved to a proper remote URI. If an extension is deployed on the remote machine. `localhost` although should work as well, trying to get there, a bit tricky since nested iframe is involved.

**Comment by akosyakov** [comment]
> currently trying to setup an environment to use a non-published Che version. (but still at the very first step https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md#step-1-start-the-workspace )

But does it work with local Theia already? It could be that Che needs customizations to resolve localhost properly depending how Theia is deployed there.

**Comment by apupier** [comment]
> > currently trying to setup an environment to use a non-published Che version. (but still at the very first step https://github.com/eclipse/che-theia/blob/master/CONTRIBUTING.md#step-1-start-the-workspace )
> 
> But does it work with local Theia already? It could be that Che needs customizations to resolve localhost properly depending how Theia is deployed there.

not noticed the way to launch Theia locally in the contributing guide

**Comment by akosyakov** [comment]
I meant following https://github.com/eclipse-theia/theia/wiki/Testing-VS-Code-Extensions but building Theia from https://github.com/eclipse-theia/theia/pull/6465

**Comment by apupier** [comment]
created https://github.com/jboss-fuse/vscode-atlasmap/pull/239 to use asExternalURI

**Comment by akosyakov** [comment]
> created jboss-fuse/vscode-atlasmap#239 to use asExternalURI

thank you! will try it as well

**Comment by akosyakov** [comment]
@apupier an extension cannot work on remote in the way how it configured now because of CSP violations:
```
```
Access to font at 'http://localhost:8586/OpenSans-Regular-webfont.woff2' from origin 'https://webview-3000-d6dcec72-ba2f-49e9-9f72-4ff0446f67ec.ws-eu01.gitpod.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

`https://webview-3000-d6dcec72-ba2f-49e9-9f72-4ff0446f67ec.ws-eu01.gitpod.io` is an origin for webviews and it's provided as a scp source, but then the extension resets `base` on content to `http://localhost:8586` which is not covered by the scp source. `anExtensionUri` will generate an URI similar to the scp source, then it will work.

**Comment by akosyakov** [comment]
> Trying the version from the PR now.

I'm trying the PR, but for some reasons the server does not start for me anymore. Do you know what could it be?

**Comment by apupier** [comment]
> I'm trying the PR, but for some reasons the server does not start for me anymore. Do you know what could it be?

Do you mean the Webview is not opening? The webview is blank? the webview is giving a 404? You don't see any process for atlasmap when calling `ps -edf |grep java | grep atlasmap`?

When you stop everything, do you still have a process visible with `ps -edf |grep java | grep atlasmap`? If yes, can you try to kill it and relaunch.

**Comment by apupier** [comment]
Trying AtlasMap with the asExternalURI PR inside local Che theia based on you rPR branch.
The AtlasMap Ui is nto displayed.
There are 404 errors on the resources from the page:

```
runtime.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
polyfills.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
styles.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
scripts.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:1 Failed to load resource: the server responded with a status of 404 (Not Found
```
the exact link is like that:
`http://2d5aedd4-d207-4239-bee4-4c04ef449db2.webview.localhost:3000/runtime.js`

effectively I cannot reach it if I enter the URl directly in the browser.
I can reach it through http://localhost:8585/runtime.js

**Comment by akosyakov** [comment]
Yes, a result returned by `asExternalUri` cannot be fetched from where the extension is running, I've commented https://github.com/jboss-fuse/vscode-atlasmap/pull/239 how to use it properly.

Regarding running the server, i forgot to run `npm i` to download a jar file, it is fine now :)

**Comment by akosyakov** [comment]
> I'm not sure who is providing the X-Frame-options.
A workaround would be to set X-Frame-Options: ALLOWALL but might not be very secure. Should be better with X-Frame-Options: ALLOW-FROM https://example.com/ but how to determine the url?

Now, i understand the issue clearly. I think you should file an issue for atlasmap. I don't see how we can work it around in Theia.

**Comment by akosyakov** [comment]
@apupier I've merged https://github.com/eclipse-theia/theia/pull/6465. Now accessing localhost resources should work in remote env. Although issue with `X-Frame-Options` i think you need to sort out with atlasmap.

I'm closing it now. Please reopen if you think something else could be done on our side.

**Comment by apupier** [comment]
tried with VS Code AtlasMap 0.0.7 which has a disabled X-frame-options. There is still a black screen but with a different error:

```
VM8:3 GET http://localhost:8585/index.html net::ERR_TOO_MANY_REDIRECTS
injectAtlasmap @ VM8:3
(anonymous) @ VM8:10
(anonymous) @ main.js:501
setTimeout (async)
(anonymous) @ main.js:498
VM8:10  Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by apupier** [comment]
@akosyakov I do not have rights to reopen the issue myself

**Comment by apupier** [comment]
There are redirections called from and to identical URLs:

![Screenshot from 2021-09-08 10-43-44](https://user-images.githubusercontent.com/1105127/132477044-59b5c2df-a6f0-4eaf-846e-507a5379a4b2.png)

**Comment by apupier** [comment]
from a normal browser, there are no redirection at all:

![Screenshot from 2021-09-08 10-46-08](https://user-images.githubusercontent.com/1105127/132477411-48f50722-17f1-474b-b466-ab2ec576cf27.png)

**Comment by apupier** [comment]
I'm wondering if the redirection is coming from https://github.com/eclipse-theia/theia/blob/d3501165bb4e87c3612a1a02c34a1d16ab81802c/packages/plugin-ext/src/main/browser/webview/pre/service-worker.js#L256
(not found a way to put a breakpoint currently, I'm not a web developer which doesn't help)

**Comment by apupier** [comment]
foudn a patch to avoid the redirect which is displaying the UI. I will provide a PR this afternoon.

basically

**Comment by apupier** [comment]
After PR https://github.com/eclipse-theia/theia/pull/10063
remaining issues:
- exporting an *.adm file is not working. No message in UI. In Console, there is this warning:
```
Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.
```
- there is a refresh on first interaction in the UI after it is displayed
![refreshOnFirstInteraction](https://user-images.githubusercontent.com/1105127/132507287-d67d31d1-3c06-4363-ab45-df42aabbba8d.gif)


Other:
- Import is opening File browser for filesystem of the browser (I guess it is fine), it might be interesting to have a way to import adm files from the Theia workspace too.

**Comment by apupier** [comment]
About the refresh issue, Theia is calling `onDidChangeViewState` when the view is gaining/losing the focus. In VS Code, it is only when the view is visible/hidden. Is it on purpose or a bug?
I have a workaround on VS Code AtlasMap side https://github.com/jboss-fuse/vscode-atlasmap/pull/682 in any case.

**Comment by azatsarynnyy** [comment]
If it differs from VS Code behavior - then I'd say it's a bug. I don't see why it should be different comparing to VS Code.
@apupier it would be great if you could file an issue upstream. Thanks!
