### ISSUE TITLE
tasks configs as preferences

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5013]
Task extension should not access tasks.json directly but use preference for it.

In VS Code tasks can be defined in a separate file as well as part of setting.json. https://github.com/theia-ide/theia/pull/4947 allows to contribute such preferences and convert launch configs to them. It's a follow-up issue to do the same for tasks in order to provide VS Code compatibility.

cc @marcdumais-work @elaihau

**Comment by akosyakov** [comment]
I will try to take care about it. It is required to complete https://github.com/theia-ide/theia/issues/3434 for input variables in tasks: https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

**Comment by akosyakov** [comment]
I will leave it out for now and open a follow-up issue. It is very involving and deserve a separate PR.

**Comment by elaihau** [comment]
@akosyakov could you please advise where to find a tutorial / document that describes how "tasks from a separate file" is supported in vs code? I am interested. Thank you !

**Comment by akosyakov** [comment]
@elaihau i don't think there is proper docs on it, we've learned by testing and analyzing VS Code repo. The heavy-lifting of mixing preferences from external file or from settings already done by a preference service. You only need to rewrite a task extension that it does not manage tasks.json file anymore, but use a preference service to read it, the same way how the debug extension was refactored.

There is a notice [here](https://code.visualstudio.com/api/references/vscode-api):
> Note: Workspace and Workspace Folder configurations contains launch and tasks settings. Their basename will be part of the section identifier. The following snippets shows how to retrieve all configurations from launch.json:

**Comment by akosyakov** [comment]
Bindings for launch in the debug extension: https://github.com/theia-ide/theia/blob/aff18c8f31661e18b22d05f71b56b4ed65975093/packages/debug/src/browser/preferences/launch-preferences.ts#L36-L40

How launch configuration are loaded in the debug extension: https://github.com/theia-ide/theia/blob/aff18c8f31661e18b22d05f71b56b4ed65975093/packages/debug/src/browser/debug-configuration-model.ts#L68

**Comment by elaihau** [comment]
we had some discussions in the office.

since it is a good amount of work to do all the refactoring, would it be possible to keep the task extension as is, and simply make some modifications to the preference service, so that we can use the preference service as a proxy to access the task config ? 

in this way, the task configs wouldn't be stored with prefs or launch configs, but would be accessible from the preferences (or configurations, depending on how you want to call it). @akosyakov

**Comment by akosyakov** [comment]
@elaihau probably, yes, it could be enough to register tasks as preference configuration, i don’t think any modifications to preference service is required, it should not be aware of tasks

It could be error prone though since task extension and vscode extensions read the same state from different sources, not necessary consistent at any given moment of time. And not memory efficient since we have to keep the same data twice in memory.

**Comment by akosyakov** [comment]
Also you have to implement supporting tasks from settings.json separately for the task extension. I think it is easier to delete code from the task extension reading from a file and rely for it on the preferences service.

**Comment by elaihau** [comment]
> Also you have to implement supporting tasks from settings.json and merging them with tasks from tasks.json

earlier today I also noticed that `tasks from settings.json` could be supported if preference is used to access task configs, however I am not sure how useful it would be:

1, defining tasks in `settings.json` is not (visibly) supported in vscode UI. also, key-in "tasks" the setting.json does not give me any hints of auto-completion. so I don't think it is a feature documented and exposed to the end user. 

2, in theory, vscode extensions can add task configs to the pool through the preference API. but given all the flexibilities of contributing to the tasks pool directly through the tasks API, what is the advantage of going with the implicit way (i.e., using preferences) ? 

could you please kindly share some insights in regards to how much we are going to gain from having this in Theia vesus the effort ? @akosyakov

**Comment by akosyakov** [comment]
> earlier today I also noticed that tasks from settings.json could be supported if preference is used to access task configs,

What about handling different settings folders?  like reading from `.vscode` instead of `.theia`? There is `PreferenceConfiguration` which allow end products to change them. Would we reimplement it as well?

I don't think partial reimplementation of the preference logic in the task extension is the right direction. Otherwise whenever we will need to change the preference logic we will need to update the task extension or think whether it is worth of doing.

I think the right direction to hide this logic from the task extension in the preference service. It is correct even in corner cases, based on tested code (we have over 800 tests to make sure that preferences are merged in proper order from different folders and settings files) and with less memory consumption.

I don't know whether there are users or VS Code extensions doing it, but i could not exclude that, like one can have shared tasks between workspaces if one defines them in user settings or a vs code extension can modify tasks.json to add such task.

Also what is the effort? Register tasks as a preference contribution, replace watching with an event from `PreferenceService` and reading with a get call, or something else should be done?

**Comment by elaihau** [comment]
> Register tasks as a preference contribution, replace watching with an event from `PreferenceService` and reading with a get call, or something else should be done?

@akosyakov 
i am fine with your proposal. please see below - i just want to make sure i am not misunderstanding it:

all clients that retrieve task configs from task-service and task-configurations need change, as the task service will no longer be the place where the task configs are fetched from. 
 
all task related APIs in the plugin-ext need to be reviewed and adjusted.

**Comment by akosyakov** [comment]
> task-service and task-configurations can be removed

Not remove them, but change to use `PreferenceService` instead of `FileSystem`. You can have a look how the debug extension does it: https://github.com/theia-ide/theia/blob/fd8f83efd512fd68fb2cd7323cfa80c2561d7062/packages/debug/src/browser/debug-configuration-manager.ts#L83-L113

> all clients that retrieve task configs from task-service and task-configurations need change, as the task service will no longer be the place where the task configs are fetched from.
> all task related APIs in the plugin-ext need to be reviewed and adjusted.

no, if you aim for the minimal change with perseverance of APIs as much as possible and only updating implementations of `TaskService` and `TaskConfigurations`
