### ISSUE TITLE
content assist in workspace file settings

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5023]
We need to define a new JSON schema and match it for workspace settings files. It can use `$ref` to reference the settings schema.

**Comment by tsmaeder** [comment]
I don't really understand what this issue is about. Can you explain?

**Comment by akosyakov** [comment]
Theia support multi-root workspaces, definition of such workspace are stored in a [workspace file](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file). A workspace file allows allow to defined settings for all included workspaces. Right now a user does not get any editor support for such files.

**Comment by colin-grant-work** [comment]
I believe this functionality was added in #8917, which allows contributions to the schema for the workspace file (for e.g. `launch`, `tasks`, `settings`). See this file and the various services that contribute to it: https://github.com/eclipse-theia/theia/pull/8917/files#diff-1f5ebdda067fac8435d0ab33ef8d66e7db8b006cfd41cf6af6ee00b00ccfcde4
