### ISSUE TITLE
[editor-preview] unable to change language mode for preview editors

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5027]
### Description
![temp](https://user-images.githubusercontent.com/10203793/56856864-e042dd00-6996-11e9-982f-ed316b26e71a.gif)

### Reproduction Steps
open theia
click once file in view mode
change language
double click file in tab
change language

**OS and Theia version:**
**Diagnostics:**

**Comment by 502647092** [comment]
`alt + w` also not effect in this view mode

**Comment by vince-fugnitto** [comment]
@502647092 I changed the title so that it'll be easier to track the issue for the future and make it easier to discover, I hope you don't mind :)

**Comment by 502647092** [comment]
@vince-fugnitto Of course, my English is not very good. It's all machine-turning.

**Comment by vince-fugnitto** [comment]
It looks like the `widget` and `editor` for preview editors are both **undefined**.
https://github.com/theia-ide/theia/blob/61cf13d28e5d96da71bd5b606896fe0f99efd3c7/packages/editor/src/browser/editor-command.ts#L140-L143

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Of course, my English is not very good. It's all machine-turning.

That's fine :) I'm happy you take the time to test, and report bugs!
Everything is helpful :)

**Comment by vince-fugnitto** [comment]
The issue looks like when we open a preview editor, it does not get focused which results in the statusbar not having the `language mode` statusbar item. If the editor is clicked and gets focused, the item is shown and it works correctly. The fix is most likely making the editor active when opening a preview.
