### ISSUE TITLE
base href 

### ISSUE THREAD

**Issue by vilashProgrammr** [eclipse-theia/theia#5056]
### Description
I need to change the base href path for the theia editor application so that is should work
like http://mydomain.com/mypath:3000 in production build

Is there any config file to change the base href path?

**Comment by akosyakov** [comment]
Theia uses express.js on the backend, please google how to set base for all express.js requests. I assume it should be possible custom routing. Relevant code is backend-application.

Alternatively you can use a reverse proxy as nginx. It's a way to go if you want to have different instances for different paths.

**Comment by vilashProgrammr** [comment]
nginx reverse proxy didn't work, some requests are getting broken.

**Comment by akosyakov** [comment]
Could you be more specific?

**Comment by vince-fugnitto** [comment]
@vilashProgrammr I am closing the issue for the moment as there has been no response, please feel free however to re-open the issue if you require additional assistance.
