### ISSUE TITLE
[Plugin-Api] Apply 'comment.createCommentController' function

### ISSUE THREAD

**Issue by vinokurig** [eclipse-theia/theia#5076]
### Description
 

Related function in VsCode: https://github.com/Microsoft/vscode/blob/da3c97f3668393ebfcb9f8208d7616018d6d1859/src/vs/vscode.d.ts#L9207-L9216

Is needed for https://github.com/eclipse/che/issues/11867

**Comment by akosyakov** [comment]
We should check whether it is possible to create Monaco distribution including source code implementing comments support without pulling to much dependencies. It can save time reimplementing it ourself with similar to VS Code exp. Plus catching up with Monaco and LSP makes sense generally. We are already lagging behind behind for one year.

cc @svenefftinge

**Comment by akosyakov** [comment]
Regarding https://github.com/theia-ide/theia/issues/5076#issuecomment-489894372 unfortunately this code belongs completely to the workbench layer of VS Code and pulls a lot of dependencies. We will have to implement our own UI for it. It is quite involving task.

**Comment by vinokurig** [comment]
Is fixed by https://github.com/eclipse-theia/theia/pull/8870
