### ISSUE TITLE
[Plugin-API] Apply window.createInput() function

### ISSUE THREAD

**Issue by vinokurig** [eclipse-theia/theia#5107]
### Description
 
Related VsCode function:
https://github.com/microsoft/vscode/blob/d9d621ee9ef00cc6cb589954db72b50b3ea5ab67/src/vs/vscode.d.ts#L6524-L6533

Is needed for https://github.com/eclipse/che/issues/11867

**Comment by JPinkney** [comment]
Hi, I’ve already started work on both https://github.com/theia-ide/theia/issues/5107 and https://github.com/theia-ide/theia/issues/5109 as well as implementing the QuickInput API as part of https://github.com/theia-ide/theia/issues/5084. It should be done in a week or two. I just wanted to let you know so we don’t duplicate work (if you were going to work on this issue).
