### ISSUE TITLE
Copying and pasting a folder into its own subfolder keeps pasting recursively

### ISSUE THREAD

**Issue by Livven** [eclipse-theia/theia#5177]
### Description

Copying and pasting a folder into a subfolder of its own keeps pasting the resulting structure recursively, so you end up with a structure of `folder/subfolder/folder/subfolder` etc.

Similar to #3454 but by pasting into a subfolder rather than itself.

### Reproduction Steps

1. Create a folder.
2. Create a subfolder under the folder from step 1.
3. Copy the folder from step 1.
4. Paste it into the subfolder from step 2.

**OS and Theia version:**

0.5.0 and current gitpod.io version (presumably also 0.6.1)

**Diagnostics:**

**Comment by akosyakov** [comment]
Could you check whether it is still the case with https://github.com/eclipse-theia/theia/pull/7908?

**Comment by Livven** [comment]
Seems like it's been fixed for us 👍
