### ISSUE TITLE
Dugite tries to append a value on porcelain when porcelain takes no value.

### ISSUE THREAD

**Issue by sr229** [eclipse-theia/theia#5211]
### Description

This usually happens when you browse inside a folder with a Git repository.

Further checking it tries to append a value `2` when porcelain takes no values at all.

### Reproduction Steps

- Browse to a Git-enabled project
- Check logs on foreground.

**OS and Theia version:** Linux on Theia Package Version on current `next`

**Diagnostics:** 

```
root ERROR Error occurred while synchronizing the status of the repository. file:///root/projects/katacoda-scenarios GitError: error: option `porcelain' takes no value
usage: git status [<options>] [--] <pathspec>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    -b, --branch          show branch information
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)
    --ignored             show ignored files
    --ignore-submodules[=<when>]
                          ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
    --column[=<style>]    list untracked files in columns


    at new GitError (/root/node_modules/dugite-extra/lib/core/git.js:81:28)
    at Object.<anonymous> (/root/node_modules/dugite-extra/lib/core/git.js:256:27)
    at step (/root/node_modules/dugite-extra/lib/core/git.js:50:23)
    at Object.next (/root/node_modules/dugite-extra/lib/core/git.js:31:53)
    at fulfilled (/root/node_modules/dugite-extra/lib/core/git.js:22:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by sr229** [comment]
I believe this also causes the incremental memory rise because of the errors. Node fails to GC that part.

**Comment by kittaakos** [comment]
Thanks for reporting, @sr229. You [need Git `2.11` or higher](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#prerequisites). Can you please check whether your environment fulfills this requirement?

**Comment by sr229** [comment]
I have Git 2.17.1 as of this time of writing.

**Comment by kittaakos** [comment]
Thanks for the update, @sr229. Do you run Theia from Docker? If so, I still think it is a Git version issue.

Related: https://github.com/theia-ide/theia-apps/issues/156

**Comment by sr229** [comment]
yep @kittaakos!, I also replicated this on a Katacoda environment, so I think this is related.

**Comment by kittaakos** [comment]
The required Git version is documented here: https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites
