### ISSUE TITLE
Implement "DeclarationProvider" API 

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#5213]
Add an implementation of the API "registerDeclarationProvider" analogous to the "registerDefinitionProvider" API.

I

**Comment by tsmaeder** [comment]
https://github.com/theia-ide/theia/issues/4569 suggests this might need an newer version of monaco.

**Comment by vrubezhny** [comment]
As `monaco.d.ts` v.0.14.6 doesn't haveDeclarationProviderinterface exported. we cannot implement `$registerDeclarationProvider(handle: number, selector: SerializedDocumentFilter[]): void` in `LanguagesMainImpl`... Here we're blocked by `@typefox/monaco-editor-core` update which is planned by the end of July, see: https://spectrum.chat/theia/dev/update-monaco~d0b4d5a5-e688-4f0f-a54f-e2d2b24525ee
