### ISSUE TITLE
Error loading data file: A resource provider for 'k8sviewfiledata://file.properties' is not registered.

### ISSUE THREAD

**Issue by vzhukovskii** [eclipse-theia/theia#5218]
### Description
Seems we're missing API related to registering custom document content provider in vscode API.

```
Error loading data file: Error: Error: A resource provider for 'k8sviewfiledata://configmap/Y29sb3IuZ29vZD1wdXJwbGUKY29sb3IuYmFkPXllbGxvdwphbGxvdy50ZXh0bW9kZT10cnVlCmhvdy5uaWNlLnRvLmxvb2s9ZmFpcmx5TmljZQ%3D%3D/ui.properties' is not registered.
```

<img width="1680" alt="Снимок экрана 2019-05-22 в 14 35 45" src="https://user-images.githubusercontent.com/1968177/58171673-2e4db680-7c9f-11e9-9034-d349de0e9521.png">

Clicking on configuration file should open it contents:
<img width="1680" alt="Снимок экрана 2019-05-22 в 14 40 34" src="https://user-images.githubusercontent.com/1968177/58171900-baf87480-7c9f-11e9-98f7-3324bc09ff61.png">

**Comment by svenefftinge** [comment]
We use https://github.com/theia-ide/theia/blob/ebaf400c1812b0abc8c3ff8290300043287262f5/packages/core/src/common/resource.ts#L144-L145 for such cases.
