### ISSUE TITLE
[editor] [typescript] block comments not properly displayed for multiple lines

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#5229]
**Description**

Currently, if `block-comments` have multiple lines, they are rendered in the following way:

```ts

/**

Get a user's name

*/
protected getName(): string {
    return this.name;
}

```

I'd expect `block-comments` to work the same way they do in monaco and vscode and add a **`*`** for each new line:

```ts

/**
*
* Get a user's name
*
*/
protected getName(): string {
    return this.name;
}

```

**Comment by BroKun** [comment]
The language configuration item `onEnterRules` will solve this problem.

**Comment by akosyakov** [comment]
@BroKun Is it the same in VS Code? I thought our textmate grammar should be aligned with their? If it is the case maybe we should fix in the upstream first, otherwise then we can move to use VS Code completely this fix will be lost. If it is just outdated grammar then please make a PR to update it.

**Comment by BroKun** [comment]
@akosyakov  The basic part is the same as vscode, but there are some extra features that are different from javascript/javascriptreact/typescript/typescriptreact and jsx-tag. We are missing this part. 
Currently we have separate configurations for these languages, although some parts are the same.

**Comment by akosyakov** [comment]
@BroKun do you have an idea how to bring missing parts? Could you have a look into it?

**Comment by BroKun** [comment]
> @BroKun do you have an idea how to bring missing parts? Could you have a look into it?

Completing the configuration item should be fine, I will test it and give a PR.
