### ISSUE TITLE
[editor] import suggestions does not work reliably when narrowing down

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#5234]
**Description**

The fuzzy-search for import suggestions does not work reliably.
I cannot narrow down results past **`@`** when trying to import a theia package.

Typing **`@t`** I still expect to see the results **`@theia/core`** and **`@theia/debug`**

<div align='center'>

![bug-2](https://user-images.githubusercontent.com/40359487/58279106-8356fe80-7d6b-11e9-8297-6caef17b128c.gif)

</div>

**Comment by akosyakov** [comment]
Where do you create `a.ts`?

**Comment by vince-fugnitto** [comment]
> Where do you create `a.ts`?

It happens for any file, example if I'm in `cpp-build-configurations.ts` and write the import statement,

```ts
import * from '@'
```

I see all available `@theia` imports, but as soon as I write,

```ts
import * from '@t'
```

I lose them.

**Comment by akosyakov** [comment]
@vince-fugnitto still valid?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto still valid?

I confirmed that the bug no longer happens (master 96e3c72) 🍾
