### ISSUE TITLE
Using only the text editor

### ISSUE THREAD

**Issue by tvaintrob** [eclipse-theia/theia#5248]
Is it possible to only use the text editor (with language plugins like python auto complete)? (Without file explorer etc.)

**Comment by gorkem** [comment]
Isn't that just monaco editor?

**Comment by tvaintrob** [comment]
But with language plugins, like python autocomplete etc.

**Comment by akosyakov** [comment]
yes, try to create an app with only `@theia/monaco` extension without `@theia/navigator`, `@theia/terminal` extensions. See docs on how to create apps: https://www.theia-ide.org/doc/Composing_Applications.html

If you don't want Theia shell at all, look at https://github.com/TypeFox/monaco-languageclient
