### ISSUE TITLE
[debug] support `preLaunchTask`

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5249]
### Description
![image](https://user-images.githubusercontent.com/10203793/58363506-b6b69c00-7ed7-11e9-9442-b0084bf48e4b.png)
![image](https://user-images.githubusercontent.com/10203793/58363571-077ac480-7ed9-11e9-897b-b064ed07e9fe.png)

launch config preLaunchTask not run when i start debug

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
`preLaunchTask` is not supported at the moment, you have to run it manually before running the debug configuration

**Comment by veredcon** [comment]
@akosyakov do you have plans to support soon the preLaunchTask?

**Comment by akosyakov** [comment]
@veredcon I'm not aware that anyone is looking into it. You will be welcomed to do it.

**Comment by elaihau** [comment]
https://github.com/eclipse-theia/theia/pull/6247 resolved this issue.
