### ISSUE TITLE
[task] disallow running identical tasks

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#5269]
**Description**

Should we disallow identical tasks from running at the same time?
Currently, we can execute multiple versions of the same task simultaneously which be error prone.

In vscode, only one instance of a task can be active at a given time, and users are prompted to either **`Terminate`** or **`Restart`** the task or cancel the action.

<div align='center'>

![Screenshot from 2019-05-27 09-05-54](https://user-images.githubusercontent.com/40359487/58423165-6cadf180-8062-11e9-9e7e-1f90cbccbb11.png)

</div>

Should we do the same?

**Comment by akosyakov** [comment]
@vince-fugnitto as usual, aligning sounds good

**Comment by akosyakov** [comment]
Also if a task is finished but we run it again then we should reuse the terminal.
