### ISSUE TITLE
Right-click tab should not activate it

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5277]
### Description
![temp](https://user-images.githubusercontent.com/10203793/58446023-a4d03580-8131-11e9-8cff-db8f55cf1bf4.gif)

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
It's tricky since context menu shows items for the last focused widget.

**Comment by vince-fugnitto** [comment]
Duplication of #4367
The behavior is true for all widgets (main-panel, side-panel etc.)
