### ISSUE TITLE
tsconfig.json not support compilerOptions types

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5321]
### Description
```
{
    "compilerOptions": {
        "target": "es5",
        "lib": ["es6", "dom"],
        "types": ["mocha", "reflect-metadata"],
        "sourceMap": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "jsx": "react",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": false,
        "noResolve": false,
        "noUnusedParameters": false,
        "noUnusedLocals": true,
        "strictNullChecks": true
    }
}
```

### Reproduction Steps
direct open https://gitpod.io#https://github.com/inversify/InversifyJS

![image](https://user-images.githubusercontent.com/10203793/58692960-4ec5f100-83c2-11e9-870f-12b4232d83c5.png)

must import this package
![image](https://user-images.githubusercontent.com/10203793/58693054-803ebc80-83c2-11e9-8d1d-2ce71216213b.png)

**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 it is provided to Theia by tsserver coming with tsc. Which version of typescript do you use? Maybe `types` are not supported by it?

**Comment by 502647092** [comment]
@akosyakov i use the latest typescript
the same porject in vscode is correct

**Comment by akosyakov** [comment]
ok, we have not tested against latest typescript for long time, will have a look at this issue after doing https://github.com/theia-ide/theia/issues/5260

**Comment by vince-fugnitto** [comment]
I confirmed that the latest behavior is consistent with vscode, after building the project the `hasOwnMetadata` error is resolved.

For reference in vscode:

![image](https://user-images.githubusercontent.com/40359487/171635596-1669d44b-2b8b-449e-895e-86aa07c467c3.png)
