### ISSUE TITLE
[tasks | epic] implement tasks improvements 

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#5333]
### Description

This is a general tracker for **`Tasks`** usability improvements.

---

### Improvements

**`Task: Restart Running Task`** (#5330 )
- Add a new command and menu terminal menu item in order to restart a running task.

:+1:  **`Terminate Task...`** (#5331)
- Add the terminate task menu item to the terminal menu

**`Disallow running identical tasks`** (#5269)
- Disallow users from running the exact same task twice if it is currently running.
- If a user attempts to re-run a currently running task, prompt them to either `Terminate` or `Restart` the task instead. 

**`Display task info in the terminal`** (https://github.com/theia-ide/theia/issues/5332)
- When executing a task, report the task information directly in the terminal to be as transparent as possible to end-users.

**`Re-use an existing terminal for identical tasks`** (https://github.com/theia-ide/theia/issues/5269#issuecomment-496800867)
- If present, use an existing terminal to re-execute an identical task.

**`Automate the creation of tasks.json`** (https://github.com/theia-ide/theia/issues/1017)
- Add new command to automate the creation of the `tasks.json` file if not present.
- If a user attempts to `Add Configuration` without a `tasks.json` file present, add a quick-open item to trigger it's creation.

:+1: **`Show Running Tasks...`** (#5346)
- Add the new command and terminal menu item which describes the list of running tasks and upon selection sets the terminal focus of the given task.

👍 **`Allow users to put comments in tasks.json`** (https://github.com/theia-ide/theia/issues/5505)
- use jsonc in tasks.json

**`Support compound tasks`** (https://github.com/theia-ide/theia/issues/5517)
- See https://code.visualstudio.com/docs/editor/tasks#_compound-tasks for details

**`Align Theia Task schema with VS Code`** (https://github.com/theia-ide/theia/issues/5516, https://github.com/theia-ide/theia/issues/1096)

👍 **`Theia should not allow users to customize all properties of a detected task`** (https://github.com/theia-ide/theia/issues/5679)
- vs code only allows 3 properties to be customized: problem matcher: isBackground, and task group.

cc @elaihau

**Comment by lmcbout** [comment]
Should we also have the "Show Running Task" as we can find in VSCode !

**Comment by vince-fugnitto** [comment]
Closing the epic as the items have been completed, and follow-up issues have already been opened which are taking care of any missing functionality.
