### ISSUE TITLE
[IP] [tests] Run libffmpeg verification "with the other tests during the yarn test cycle"

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#5335]
### Description
This is a follow-up to [#5112 - [electron] Do not test ffmpeg replacement](https://github.com/theia-ide/theia/pull/5112). We did not have time to follow-through with all review suggestions and wanted to have part of the patch in for `0.7.0`. 

As well we received word from the Foundation about the terms of the exception we were granted to (indirectly) distribute `libffmpeg`. In short, I think the only thing to do immediately is to "protect" the publishing of @theia/electron. e.g.: If the `libffmpeg` test fails, it breaks CI and prevents publishing. We'll then quickly know that something is happening, and can take appropriate action. 

So let's consider to go ahead with something inspired by @kittaakos' suggestions:
[this](https://github.com/theia-ide/theia/pull/5112#issuecomment-491282767)
> Can we have a spec.ts in @theia/electron?The test would call the h264-test after performing the replace. But I am OK with the current state too.

[and this](https://github.com/theia-ide/theia/pull/5112#issuecomment-491712325):
> Why do you want to run the test on Travis and AppVeyor only? In other words, why is better to explicitly declare the tests in both CI configs, instead of running it with the other tests during the yarn test cycle?

Related: https://github.com/theia-ide/theia/pull/5210 :  

cc: @marechal-p

**Comment by vince-fugnitto** [comment]
During an offline discussion with Marc, it looks like the current way of doing things (running the ffmpeg verification on installation) is sufficient when the application uses the `@theia/electron` extension.
