### ISSUE TITLE
[bug] there is something wrong of autoClosingPairs

### ISSUE THREAD

**Issue by AlbertXiao1994** [eclipse-theia/theia#5350]
### Description
There is something wrong of autoClosingPairs when exiting a character behind

Expected:
![1](https://user-images.githubusercontent.com/23646755/58849662-c85d2800-86bd-11e9-934d-62614f4438be.gif)

Geted:
![2](https://user-images.githubusercontent.com/23646755/58849666-cd21dc00-86bd-11e9-9cd5-37a2a3eee8cf.gif)

**Theia version:**
0.7.0

**Comment by vince-fugnitto** [comment]
Confirmed that the bug no longer exists.
