### ISSUE TITLE
editor.action.codeAction keybinding is not working

### ISSUE THREAD

**Issue by dinvlad** [eclipse-theia/theia#5354]
### Description
 
Attempts to set an `editor.action.codeAction` shortcut fail.

### Reproduction Steps

(1st method) Type `editor.action.` in keybindings UI -  `codeAction` is not listed there, unlike others in the same category.

(2nd method) Create `keymaps.json`  - no effect:
```json
[
    {
        "command": "editor.action.codeAction",
        "keybinding": "shift+enter"
    }
]
```
(3rd method) Set the following in an extension config - no effect either:
```json
  "contributes": {
    "keybindings": [
      {
        "command": "editor.action.codeAction",
        "key": "shift+enter"
      }
    ]
  }
```

**OS and Theia version:**
Theia: 0.8.0-next.92cfe9a2
OS: `node:10-alpine` in Docker host, Mac 10.13.6 client

**Diagnostics:**

**Comment by akosyakov** [comment]
@dinvlad Could you try again? It should have been fixed by @JPinkney PR to drop `monaco.` prefix.

**Comment by vince-fugnitto** [comment]
Confirmed that the changes work well.
