### ISSUE TITLE
auto split terminal like vscode

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5372]
### Description
double click split line auto split
![temp](https://user-images.githubusercontent.com/10203793/59011756-3cd3ca80-8868-11e9-8620-dce35768b613.gif)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by svenefftinge** [comment]
I don't quite understand the request. Isn't the splitting in Theia already similar resp. even better as you can freely put your terminals within the shell?

**Comment by AlexTugarev** [comment]
Have you tried this?

![2019-06-06 14 25 25](https://user-images.githubusercontent.com/914497/59032596-fb8eeb00-8866-11e9-92d8-e32fe01885da.gif)

**Comment by 502647092** [comment]
Maybe I am not very clear. I mean, when the size of the two terminal windows is inconsistent, double-click the dividing line to automatically resize.

**Comment by vince-fugnitto** [comment]
Closing in favor of the more generic https://github.com/eclipse-theia/theia/issues/11977.
