### ISSUE TITLE
[electron]  scm extension is not included in the example-electron app

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#5387]
I was wondering if there was a reason for not including the `@theia/scm` extension in the `example-electron` application.

**Comment by akosyakov** [comment]
It is included transitively via `@theia/git`. Go ahead and add it explicitly for the consistency of examples. Generally it is not necessary.

**Comment by vince-fugnitto** [comment]
@kaiyue0329 would you like to handle the following issue?
