### ISSUE TITLE
[electron][JSON] Try to reuse `node` from the `PATH` instead of `process.execPath` in electron

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#5408]
This issue is a follow up of https://github.com/theia-ide/theia/pull/5324.

Currently, we always use the `process.execPath` to lunch the Node.js process for the TS-LS. When running in electron, it means, we use the bundled Node.js runtime instead of the one from the `PATH`.

For the sake of consistency, we should try to use the `node` command from the `PATH` and fall back to the `process.execPath`. The details are here: https://github.com/theia-ide/theia/pull/5324#issuecomment-499947962.

Note, the same adjustments have to be used for [JSON too](https://github.com/theia-ide/theia/blob/798ecc9304f395103e804d705a86565c14507364/packages/json/src/node/json-contribution.ts#L29).

**Comment by akosyakov** [comment]
@kittaakos Is it still valid? We don't have ts LS anymore.

**Comment by kittaakos** [comment]
> Is it still valid? We don't have ts LS anymore.

Yes. 👇 

> Note, the same adjustments have to be used for [JSON too](https://github.com/theia-ide/theia/blob/798ecc9304f395103e804d705a86565c14507364/packages/json/src/node/json-contribution.ts#L29).

**Comment by akosyakov** [comment]
ok, we have to get rid of JSON then too :)

**Comment by kittaakos** [comment]
I am retiring this issue, `@theia/json` has been deprecated and removed via https://github.com/eclipse-theia/theia/pull/8112.
