### ISSUE TITLE
support search in scm view

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5413]
It is hard to find a file when there are a lot of resources. It would be good to rewrite SCM groups/resources with `TreeWidget` when it will bring multi selection support and search as well.

**Comment by westbury** [comment]
This is mostly fixed by https://github.com/eclipse-theia/theia/pull/7505.  That PR added support for search.  It did not add support for multi-selection.  However multi-selection is specifically covered by https://github.com/eclipse-theia/theia/issues/7659 so I am closing this issue.
