### ISSUE TITLE
Dialogs should be injectable

### ISSUE THREAD

**Issue by johnwiseheart** [eclipse-theia/theia#5420]
### Description

I am trying to integrate theia into an existing ecosystem of products that are all using a particular UI component library. I want to be able to theme all dialogs to use the components from the library, but this is not possible, because the AbstractDialog is not injectable, and many other dialogs are just instantiated rather than using dependency injection.

Would it be possible to refactor this so that it was easier to change what dialogs look like? What do you think? Would you take a PR?

**Comment by vince-fugnitto** [comment]
@johnwiseheart if it means having a more flexible and extensible framework I'm all for it.

> Would you take a PR?

We are always happy to take PRs :smiley:, feel free to submit one!

**Comment by svenefftinge** [comment]
You cannot inject a super class, so this would mean refactor to composition, no?

**Comment by johnwiseheart** [comment]
Yeah this was my thought, probably worth some discussion about what the best way would be to do this. Certainly one way to do it would be to create some type of "DialogRenderer" that dialogs would call to render their content, but it felt a little dirty, and I wanted to make sure I was thinking about it in the right way, since I don't have a lot of knowledge of the existing paradigms within the theia codebase.

What do you think of the composition strategy/do you have any alternate suggestions?

**Comment by johnwiseheart** [comment]
I suppose another option would just be to make the components extending AbstractDialog injectable - that way, one could just completely replace the `SingleTextInputDialog` (for instance) with their own implementation. Might actually be a better option, since things like the dialog buttons are probably also going to become issues when trying to apply some type of broad UI change.

**Comment by svenefftinge** [comment]
With respect to API compatibility the second option sounds better to me.

**Comment by johnwiseheart** [comment]
Awesome - still investigating some other issues from our side, but will make a PR for this if we decide to start investing more time. Cheers!

**Comment by vince-fugnitto** [comment]
You can now use `ReactDialog`:

https://github.com/eclipse-theia/theia/blob/d0e00c5d07ec0c95a17da51a5b744934d7c4d1f8/packages/core/src/browser/dialogs/react-dialog.tsx#L24-L25

As an example, it is used in the `AboutDialog`:

https://github.com/eclipse-theia/theia/blob/d0e00c5d07ec0c95a17da51a5b744934d7c4d1f8/packages/core/src/browser/about-dialog.tsx#L32-L33
