### ISSUE TITLE
[search-in-workspace] replace all should apply immediately without dirty state

### ISSUE THREAD

**Issue by 32leaves** [eclipse-theia/theia#5452]
### Description
When I use the "Replace All" functionality in the search view I have to manually save each every file the search string was replaced in. In VS code, "replace all" immediately saves the changes.

### Reproduction Steps
1. Open the search view
2. Search for a string that is found in multiple files, with a replacement value set
3. Click "replace all", observe that the editors are opened and in 'dirty state'

**OS and Theia version:**
tested in gitpod.io.

**Comment by vince-fugnitto** [comment]
@32leaves I'm not sure the behavior in vscode is correct, I'd expect if I have `auto-save` disabled, performing a `replace-all` should not save all the editors.

In Theia, performing a replace all with `auto-save` off, results in the files updating with a dirty state. At that point users can perform manual saves, or `save all`. If `auto-save` is enabled, then you have the same behavior you are expecting.

**Comment by vince-fugnitto** [comment]
@32leaves on further investigation, you might be right, what I find annoying now that I think of it, is that we open all editors after performing a `replace-all`. This is annoying and problematic especially for large workspaces.

**Comment by vince-fugnitto** [comment]
Fixed in #5600
