### ISSUE TITLE
improve stage(all) git commands

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5457]
It is a follow-up of https://github.com/theia-ide/theia/pull/5456:
- It should prompt a user to confirm staging of files with merge conflicts.
- It should prompt a user to pick which version of a deleted file should be used.

Or we complete vscode SCM api and just use vscode git extension which does all of it already.

**Comment by JonasHelming** [comment]
I am closing this, as we went for the second option (switch to VS Code extension)
