### ISSUE TITLE
[navigation-history] Includes bad 0,0 positions

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#5465]
When navigating between editors using the navigation history I see 0,0 positions. Probably added by non-atomic editor open/reveal actions.

Reproduce:

1) open file a
2) go to declaration in file b
3) press CTRL+- and see how you end up on line 0 in file b (expected file a)

**Comment by kittaakos** [comment]
The `editor.enablePreview: true` preference further complicates this. The navigation is broken as we always open a new non-preview editor even if `editor.enablePreview` is `true`.

I try to fix both issues in one PR.

**Comment by kittaakos** [comment]
This change causes the issue: https://github.com/theia-ide/theia/pull/4423

**Comment by kittaakos** [comment]
Also, #4423 did not handle the case when a file is opened from the navigator with a **single click**.
With a **single click** open, the selection is not set into the editor, hence the location will not be registered into the stack only **double click** does it. It works properly in VS Code.

**Comment by colin-grant-work** [comment]
I believe that this particular problem was addressed by #9004.
