### ISSUE TITLE
[vscode] maven extension for java does not work

### ISSUE THREAD

**Issue by gloomuu** [eclipse-theia/theia#5470]
### Reproduction Steps
1. Install Vs Code Extension - Maven for Java by using "Deploy plugin by ID"
vscode:extension/vscjava.vscode-maven

2. From the log, the plugin is installed and we can see it in the Theia plugin list

3. The maven project does not show in the Theia view

**OS and Theia version:**
OS: Linux
Theia: v0.6.1

**Dignostics:** 

```
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer: PluginVsCodeFileHandler { unpackedFolder: '/tmp/vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'vscode:extension/vscjava.vscode-maven',
     pluginId: 'vscode:extension/vscjava.vscode-maven',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath: '/tmp/vscode-extension-marketplace/vscode_extension_vscjava_vscode_maven.vsix',
     initPath: '/tmp/vscode-extension-marketplace/vscode_extension_vscjava_vscode_maven.vsix',
     resolved: true,
     resolvedByName: 'VsCodePluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/vscode_extension_vscjava_vscode_maven.vsix
root INFO Resolved "vscode:extension/vscjava.vscode-maven" to a VS Code extension "vscode-maven@0.17.1" with engines: { vscode: '^1.22.0' }
root INFO Deploying backend plugin "vscode-maven@0.17.1" from "/tmp/vscode-unpacked/vscode_extension_vscjava_vscode_maven.vsix/extension/dist/extension"
root WARN Plugin contributes items to a menu with invalid identifier: view/title
root INFO [hosted-plugin: 138860] PLUGIN_HOST(138860) starting instance

root INFO [hosted-plugin: 138860] PLUGIN_HOST(138860): PluginManagerExtImpl/init()

root INFO [hosted-plugin: 138860] PLUGIN_HOST(138860): initializing(/home/admin/.cloud-ide/cloud.ide/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)

root INFO [hosted-plugin: 138860] PLUGIN_HOST(138860): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/vscode_extension_vscjava_vscode_maven.vsix/extension/dist/extension)

root INFO [hosted-plugin: 138860] localRepository not specified in Maven Settings.
```

**Comment by tom-shan** [comment]
I think this issue may be caused by not implemeted apis like visible, onDidChangeVisibility, onDidChangeSelection and so on.

**Comment by yeweiasia** [comment]
![image](https://user-images.githubusercontent.com/16164849/59648034-1ee35f80-91b0-11e9-81f0-9e995b7093ab.png)
https://che-incubator.github.io/vscode-theia-comparator/status.html
Is anyone working on these unimplemented objects related with treeview?

**Comment by akosyakov** [comment]
It does not look like that. PRs are welcomed.

Related issue: https://github.com/theia-ide/theia/issues/4605

**Comment by yeweiasia** [comment]
@akosyakov I will take a look.

**Comment by akosyakov** [comment]
@yeweiasia @gloomuu please check again, missing tree APIs were implemented already

**Comment by akosyakov** [comment]
Or if anyone can double check and look for the root cause it would be helpful.

**Comment by vince-fugnitto** [comment]
> Or if anyone can double check and look for the root cause it would be helpful.

The tree view is successfully added:

![image](https://user-images.githubusercontent.com/40359487/70072767-a2113a00-15c5-11ea-9150-8792da8c939d.png)

**Comment by akosyakov** [comment]
@vince-fugnitto thx

please reopen if there are still some issues related to this VS Code extension
