### ISSUE TITLE
Is having task model classes beneficial ?

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#5473]
vsCode has one abstract class [CommonTask](https://github.com/microsoft/vscode/blob/1.35.1/src/vs/workbench/contrib/tasks/common/tasks.ts#L501), and 4 model classes (i.e., Custom, Contributed, Configuring, InMemory) that extend `CommonTask` for different types of Tasks, while in Theia, we defined 2 interfaces: `TaskConfiguration` and `ContributedTaskConfiguration`.

I am not sure if having model classes (instead of interfaces) would be beneficial. 

Two major benefits that I can think of:

1. With model classes, we don't have to rely on the problematic [ContributedTaskConfiguration.is()](https://github.com/theia-ide/theia/blob/7b7721f39f97f3194b88688f5df21bd4860f5241/packages/task/src/common/task-protocol.ts#L52) to determine the type of Tasks. Code in places such as `quick-open-task.ts` and `task-service.ts` would be cleaner, as 
```ts
if (ContributedTaskConfiguration.is(commonTask)) {
   /** do something */
} else {
  /** do something in a slightly different way */
}
```

could be refactored into 
```ts
commonTask.doSomething();
```

2. The model classes would provide better support to the feature "Configure Tasks". Right now this feature in Theia simply dump the entire Task object into `tasks.json`, which could introduce unnecessary data redundancy. 

Thoughts of all kinds are welcomed.

**Comment by kittaakos** [comment]
> having model classes

Just asking: do classes work correctly through the wire (JSON-RPC), they should.

**Comment by elaihau** [comment]
> Just asking: do classes work correctly through the wire (JSON-RPC), they should.


Classes don't work correctly if they are passed from front end to backend. 
However, the task type (i.e., contributed vs configured) is not important to the backend. The only thing that the backend needs is the data that can be run in the terminal or as a process.

**Comment by kittaakos** [comment]
If you want to replace the `TaskConfiguration` interface with a class, this won't work:
https://github.com/theia-ide/theia/blob/7b7721f39f97f3194b88688f5df21bd4860f5241/packages/task/src/common/task-protocol.ts#L74

**Comment by elaihau** [comment]
> If you want to replace the `TaskConfiguration` interface with a class, this won't work:
> https://github.com/theia-ide/theia/blob/7b7721f39f97f3194b88688f5df21bd4860f5241/packages/task/src/common/task-protocol.ts#L74


`TaskConfiguration` doesn't have to be removed. Instead, it would serve as the interface for the frontend to pass data to the backend. 

The Task model classes would only by used in FE, and we could define an abstract method in the base class like this

```ts
export abstract class CommonTask {
    public abstract toTaskConfiguration(): TaskConfiguration;
}
```
for its subclasses to decide which properties should be passed through the wire for task execution.

**Comment by elaihau** [comment]
What do you think ? @RomanNikitenko @akosyakov

**Comment by akosyakov** [comment]
@elaihau we don't need to structure code as VS Code, only align with their specifications. If you think it would be beneficial go for it. My only concern is to avoid doing big refactoring just to refactor. If there is no much benefits over existing approach i won't do it.

**Comment by RomanNikitenko** [comment]
@elaihau 
About applying VS Code model for Theia it's difficult to assess for me at the moment. 
But in general I'm +1 for refactoring if we can separate responsibility of entities and simplify code this way.
