### ISSUE TITLE
[Java] Language server process is not dying after refresh

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#5490]
try reload a theia frontend with an opened java editor multiple times.
See how the processes are leaking.

**Comment by xieyuanhuata** [comment]
yes
i have solve the bug:
https://github.com/theia-ide/theia/pull/5253

**Comment by akosyakov** [comment]
It is not related to plugins, but to java theia extension.

**Comment by vince-fugnitto** [comment]
> It is not related to plugins, but to java theia extension.

Closing since the `@theia/java` extension is deprecated.
