### ISSUE TITLE
[Debug] Debug Console doesn't auto scroll

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#5495]
Running a debug process with lots of output, the scrolling behavior is not reliable.

Repro:
 - clone https://github.com/in28minutes/SpringBootForBeginners
 - create launch java configuration
 - launch it and open the debug console
 - UI should not freeze and the output should be displayed

**Comment by akosyakov** [comment]
I don't have time to have a look, feel free to grab.

**Comment by tsmaeder** [comment]
I don't know how to reproduce this: how do you create a launch configuration for a sprint boot app?

**Comment by akosyakov** [comment]
> how do you create a launch configuration for a spring boot app?

yes, any launch configuration which keeps producing content

**Comment by colin-grant-work** [comment]
I can no longer reproduce this bug, so I'm going to close this issue for now. Please comment / reopen if you encounter this issue in the current version of Theia.
