### ISSUE TITLE
"Undeploy" plugin

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#5507]
### Description

After running Deploy plugin by id, there should be a way to remove it. Maybe command?
Deleting manually the temp unpacked folder seems to remove it but it doesn't affect the plugins view.

### Reproduction Steps

1. Press F1 and then run "Plugin: Deploy plugin by id".
1. Insert vscode:extension/hypnoes.hello.
1. Now there is no nice way to remove it.

**Comment by akosyakov** [comment]
What should happen for existing opened windows? Should an extension be auto unloaded for everybody? Or it should be functional till next reload?

cc @benoitf @svenefftinge 

I would prefer if it is not loaded automatically, but a user can unload it by clicking a button on UI or reloading the window.

Another thing we should agree about terminology for a user. Extensions can be deployed and then loaded by a window. For management deployment state i would prefer to use `install/uninstall` and for a single user it should be enough, i.e. it gets undeployed and unloaded by uninstall. But for other users an extension then will be in a state that it was already undeployed but not unloaded yet. I'm not sure what will be the good terminology in this case. We can show something like `unload to uninstall` (`load to install`). Will it be clear for a user what  `load`/`unload` mean?

**Comment by amiramw** [comment]
Do we have multi users support? Or are you worried about shared workspace support?

**Comment by akosyakov** [comment]
> Do we have multi users support? Or are you worried about shared workspace support?

I'm concerned about shared workspaces. I think we can do a simple thing for now and load automatically. For unload there still should be a button to reload the page for now. Later when we support proper plugin unloading, we can do it automatically as well.

**Comment by akosyakov** [comment]
I will add a context menu entry to uninstall plugin in the plugin view.

**Comment by a1994846931931** [comment]
> I will add a context menu entry to uninstall plugin in the plugin view.

@akosyakov May I ask, apart from the menu entry, technically, if I want to expose a command to undeploy a plugin by its identifier, is there an easy way to do so? In other words, is there a counterpart of `PluginDeployerResolverContext.addPlugin` function?

**Comment by akosyakov** [comment]
https://github.com/eclipse-theia/theia/blob/73bd544d99a1f93159cc83cedd9769e627033811/packages/plugin-ext/src/common/plugin-protocol.ts#L763 should be used to deploy. See for instance how vsx-registry extension is unsung it

**Comment by amiramw** [comment]
@akosyakov i see that plugins installed with "deploy by id" command can now be uninstalled form the extension pane.
should we close this issue?

**Comment by akosyakov** [comment]
If it is enough for you then yes. It is fine with me.
