### ISSUE TITLE
[vscode] webview active state is bogus if iframe is focused

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5521]
The shell cannot detect that the webview widget is active then webview iframe is selected. The check should be based on `document.activeElement` to produce reliable results.

**Comment by akosyakov** [comment]
Not sure how approach is properly. It would be nice to fix in the shell, right now webviews with focused iframe are not highlighted as active, the same for the mini browser. It seems to be a generic shell issue.

**Comment by akosyakov** [comment]
Open an issue in phosphorjs https://github.com/phosphorjs/phosphor/issues/394 to learn their opinion.

**Comment by akosyakov** [comment]
The only reliable way to get whether iframe is focused, it actually listens for it inside iframe and then forwards events to the host window. After that we will need to have a custom shell focus tracker which is aware of these events as well. cc @svenefftinge @spoenemann

**Comment by spoenemann** [comment]
> it actually listens for it inside iframe

Seems unfeasible.

> Maybe other ideas?

We could ignore the `blur` event?

**Comment by akosyakov** [comment]
> We could ignore the blur event?

I've tried it does not work, there is not `focus` event afterwards. I'm thinking to go with https://github.com/theia-ide/theia/issues/5560#issuecomment-507136771
