### ISSUE TITLE
Add the build against the latest versions of yarn, npm and node

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#555]

**Comment by akosyakov** [comment]
PRs are welcomed.

A new job should be added at the stage after the deploy stage. It would be enough to run it only on the master branch.

**Comment by maferland** [comment]
Can you explain what you want? I was looking to do it but I am not sure I understood it properly.

**Comment by akosyakov** [comment]
@maferland Hi, thanks for looking into it.

We build Theia with Travis CI: https://travis-ci.org/theia-ide/theia. Build jobs are configured via [a yaml file](https://github.com/theia-ide/theia/blob/master/.travis.yml). As you can notice it consists of several stages and yarn version is pinned to 1.0.2 [here](https://github.com/theia-ide/theia/blob/05f2d772f7c6effdcc9afb2642944b5786d4ba6a/.travis.yml#L28). It is done to avoid breaking builds when new yarn version is released.

At the same time, we would like to have continuous testing against the latest version of yarn, npm and node, to know when it is saved to switch. Particularly, we would like to have a new stage, e.g. `test latest`, with a job overriding `before_install` and installing the latest node, npm and yarn. You should consult Travis documentation to learn more how to do it: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/. It is ok if such job is failing. Let us know if you need more guidance.

**Comment by maferland** [comment]
I will give it a try. I will let you know if I need other explanation or if, for whatever reason, I can't finish it.

**Comment by kittaakos** [comment]
Depends on #2009. First, we should be able to build with Node.js 10.x.

**Comment by brgirgis** [comment]
Any ETA on this issue? I can't get a simple startup project to run using nodejs 16 on an OpenSUSE Tumbleweed machine.

**Comment by msujew** [comment]
@brgirgis You should be able to build/run Theia by using the `--ignore-engines` flag when running the `yarn` command.

**Comment by brgirgis** [comment]
> @brgirgis You should be able to build/run Theia with newer versions of node by using the `--ignore-engines` flag when running the `yarn` command.

Thanks! That did help.

**Comment by msujew** [comment]
We are using fairly new versions of node in our GitHub Actions matrix now. We don't have any plans to migrate to newer versions of yarn.

I believe this can be closed, especially since we have other issues for yarn, like https://github.com/eclipse-theia/theia/issues/11924
