### ISSUE TITLE
Allow input from user during a task launch like VS Code

### ISSUE THREAD

**Issue by JillieBeanSim** [eclipse-theia/theia#5561]
### Description
When creating a task in tasks.json using the ${input:variable} as a shell argument to allow user to input an item that is saved in a variable doesn't work in theia as it does in VS Code.  The task at this time has to be hard-coded in the tasks.json

**OS and Theia version:**
Windows & MacOS
Theia 0.7.1

**Comment by marcdumais-work** [comment]
This looks like a duplicate of https://github.com/eclipse-theia/theia/issues/5836.
