### ISSUE TITLE
(VS Code Extensions) window.withProgress isCancellable is not respected

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#5578]
### Description
`ProgressOptions.isCancellable` is not respected by Theia. The "Cancel" button is always present.

https://code.visualstudio.com/api/references/vscode-api#ProgressOptions

### Reproduction Steps
- call `window.withProgress` setting the `isCancellable` `ProgressOptions` to `false`.
```
        const validateResponse = await vscode.window.withProgress({
            title: `Processing ${pathToBind}...`,
            location: vscode.ProgressLocation.Notification,
            cancellable: false,
        }, () => {
           // ... your callback
        });
```
In VS Code, the Cancel button is not shown if `cancellable: false` is given. In Theia, the Cancel button is always shown.

**OS and Theia version:**
macOS mojave, theia version `next`

**Diagnostics:**

**Comment by tetchel** [comment]
@akosyakov, is this any way I can get this prioritized, it's been silent for 3 months.

This is a pretty bad one because there is no workaround for me, and users get confused when the action they cancelled continues to run.

**Comment by tetchel** [comment]
Now that's service!

**Comment by AlexTugarev** [comment]
Thanks for reporting, btw.
