### ISSUE TITLE
How do I configure a c/ c ++ compilation environment?

### ISSUE THREAD

**Issue by xinsuinizhuan** [eclipse-theia/theia#5583]
I want use theia to run C/C++ code，but i do not know to to configure compilation environment, is there some specification?

**Comment by kittaakos** [comment]
We have a README for the `@theia/cpp` extension: https://github.com/theia-ide/theia/tree/master/packages/cpp

**Comment by xinsuinizhuan** [comment]
i read the README but still puzzle! Is there exmaple?
1、how the compile_commands.json is:
    1>Have the build system of the C/C++ project generate a compile_commands.json file.
    2>Point Clangd to the build directory containing said compile_commands.json.
2、whether is to and below to the settings.json?
   {
    "cpp.buildConfigurations": [{
        "name": "Release",
        "directory": "/path/to/my/release/build"
    },{
        "name": "Debug",
        "directory": "/path/to/my/debug/build"
    }]
}
{
      "cpp.clangdExecutable": "/path/to/my/clangd/executable"
  }
{
      "cpp.clangdArgs": "list of clangd arguments"
  }
{
        "cpp.clangdArgs": "--background-index"
    }

**Comment by vince-fugnitto** [comment]
@xinsuinizhuan you can perhaps try the following example, we should definitely look into improving the documentation present in the `cpp` readme.

https://github.com/theia-ide/theia/issues/4501#issuecomment-470633593

**Comment by xinsuinizhuan** [comment]
But i have the requirement to make project user python and others language. what should i do? If have the example to set the language？

**Comment by vince-fugnitto** [comment]
> But i have the requirement to make project user python and others language. what should i do? If have the example to set the language？

I'm sorry but I don't quite understand your question, do you mind elaborating?

**Comment by xinsuinizhuan** [comment]
I am a newer, and this is my fisrt to user cheia, i don not konw how to generate a compile_commands.json,Could you show me a compile_commands.json file?
because i do not konw the compile_commands.json function, it is to show the clangd the path, or to show the src file? if the compile_commands.json is to show the src file，my project have multi file, how i do? below is my project and compile_commands.json, but this compile_commands.json not point the clang path, i do not konw whether it is right ?
compile_commands.json ：
[
    {
        "arguments": [
            "c++", 
            "-c", 
            "-DNDEBUG", 
            "-std=c++14", 
            "-Wall", 
            "-Werror", 
            "-O2", 
            "-I../../nvngLib/tools", 
            "-o", 
            "test_stl_distance.out", 
            "test_stl_distance.cc"
        ], 
        "directory": "/home/lsw/git/notepad/test", 
        "file": "test_stl_distance.cc"
    }, 
    {
        "arguments": [
            "c++", 
            "-c", 
            "-DNDEBUG", 
            "-std=c++14", 
            "-Wall", 
            "-Werror", 
            "-O2", 
            "-I../../nvngLib/tools", 
            "-o", 
            "test_c++_global_var.out", 
            "test_c++_global_var.cc"
        ], 
        "directory": "/home/lsw/git/notepad/test", 
        "file": "test_c++_global_var.cc"
    }, 
    {
        "arguments": [
            "c++", 
            "-c", 
            "-DNDEBUG", 
            "-std=c++14", 
            "-Wall", 
            "-Werror", 
            "-O2", 
            "-I../../nvngLib/tools", 
            "-o", 
            "test_memcpy_single_thread.out", 
            "test_memcpy_single_thread.cc"
        ], 
        "directory": "/home/lsw/git/notepad/test", 
        "file": "test_memcpy_single_thread.cc"
    }, 
    {
        "arguments": [
            "c++", 
            "-c", 
            "-DNDEBUG", 
            "-std=c++14", 
            "-Wall", 
            "-Werror", 
            "-O2", 
            "-I../../nvngLib/tools", 
            "-o", 
            "test_c++_return.out", 
            "test_c++_return.cc"
        ], 
        "directory": "/home/lsw/git/notepad/test", 
        "file": "test_c++_return.cc"
    }, 
    {
        "arguments": [
            "c++", 
            "-c", 
            "-DNDEBUG", 
            "-std=c++14", 
            "-Wall", 
            "-Werror", 
            "-O2", 
            "-I../../nvngLib/tools", 
            "-o", 
            "test_map_key_value.out", 
            "test_map_key_value.cc"
        ], 
        "directory": "/home/lsw/git/notepad/test", 
        "file": "test_map_key_value.cc"
    }
]

**Comment by vince-fugnitto** [comment]
@marechal-p perhaps you can offer some help?

**Comment by marechal-p** [comment]
The `compile_commands.json` file simply describes all the options/flags/defines in effect when compiling a given source file, so that clangd can properly parse it.

You can generate it using different tools, see:
https://clang.llvm.org/docs/JSONCompilationDatabase.html#supported-systems

Then from Theia, you can create "build configurations", which are more like "build descriptions" since it only describes what is already built. You should keep building your projects using tools that you may already use (cmake, configure, make, ninja, etc...).

The build configurations are simply a name to identify the build, and a directory that contains the compilation database. From that depending on which configuration is active, the correct `compile_commands.json` will be sent to clangd in order to parse your sources.

This is useful when you have a debug build, but also a release build, maybe yet another release build but with different flags, etc... All coming from the same sources.

**Comment by mfouesneau** [comment]
I have also a hard time understanding how this all work. I have a working project and I'm trying to use Theia to continue its development. However, the editor gives me many "compilation error" (probably because some includes are not fully set properly)

The Makefile works fine but I cannot find where the equivalent is defined in the project.

I cannot find where the setup should happen and how to proceed. 
There are configurations and tasks, which one should I use for that?

**Comment by vince-fugnitto** [comment]
> I have also a hard time understanding how this all work. I have a working project and I'm trying to use Theia to continue its development. However, the editor gives me many "compilation error" (probably because some includes are not fully set properly)
> 
> 
> 
> The Makefile works fine but I cannot find where the equivalent is defined in the project.
> 
> 
> 
> I cannot find where the setup should happen and how to proceed. 
> 
> There are configurations and tasks, which one should I use for that? 

@mfouesneau it is difficult to help without a concrete project or example, but getting the environment to work is not specific to the Theia framework. Please note that we (as a community) have moved towards using the [`vscode-clangd`](https://open-vsx.org/extension/llvm-vs-code-extensions/vscode-clangd) extension for C/C++ language support.

**Comment by mfouesneau** [comment]
I'm trying theia through gitpod.  

My project is basically a set packages in an include directory.

/ main.cpp
/includes
       /library1
      /library2

It seems that (a) I cannot make use of a debugger. I tried using the configurations as in the documentation but they are ignored completely, (b) the editor does not recognize the libraries (includes etc) I provide.

**Comment by vince-fugnitto** [comment]
@mfouesneau the Theia repository does not contain C/C++ language and debugging extensions (this repository is used to develop the framework). If you require C/C++ features you will need to install the appropriate vscode extensions in your Theia-based application, similarly to out [`theia-cpp-docker`](https://github.com/theia-ide/theia-apps/blob/master/theia-cpp-docker/latest.package.json) example.

**Comment by mfouesneau** [comment]
Here is my task.json, can you tell me why this ends with code 1 and no message error anywhere to be seen?

```
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
        {
            "type": "shell",
            "label": "C/C++: g++ build active file",
            "command": "/usr/bin/g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${workspaceFolder}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
	]
}
```

**Comment by mfouesneau** [comment]
I made a minimalistic repo for example. I think I manage now to build a file and run it with debugger. However I do not know where to put the **include** information that would be also used in the editor (not just at compiler level)

https://github.com/mfouesneau/gitpod_cpp_template

Any idea?

**Comment by tsmaeder** [comment]
Reiterating that there is no more cpp extension in Theia. Closing.
