### ISSUE TITLE
[CI] Recent failures related to ffmpeg test

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#5596]
### Description

I think these are new CI failures. Maybe related to 33be284daa0775bb5d4aacf7731d2d48c635a12a 

For example: 
https://travis-ci.org/theia-ide/theia/jobs/550903314#L774
https://travis-ci.org/theia-ide/theia/jobs/551241748#L290

### Reproduction Steps
Submit new or updated PR, watch Travis CI's results. The issue may not happen all the time. 

**OS and Theia version:**
Seems to happen intermittently, at least Linux, Mac

**Diagnostics:** 
```
$ THEIA_SKIP_NPM_PREPARE=1 yarn install
yarn install v1.13.0
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ node scripts/post-install.js
Error: Cannot find the log file for the Electron codecs test.
    at main (/Users/travis/build/theia-ide/theia/scripts/post-install.js:30:15)
    at Object.<anonymous> (/Users/travis/build/theia-ide/theia/scripts/post-install.js:34:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "THEIA_SKIP_NPM_PREPARE=1 yarn install" failed and exited with 1 during .
```

**Comment by marcdumais-work** [comment]
@marechal-p Can you have a look?

**Comment by marechal-p** [comment]
Rebasing and deleting the cache worked in most cases.

I wonder why the cache keeps doing that. If it continues we may delete this log display.

**Comment by marcdumais-work** [comment]
PR: https://github.com/theia-ide/theia/pull/5601

**Comment by marcdumais-work** [comment]
Currently the build always fails if the cache is used, which is a bit annoying. Once #5601 is merged, all new PRs will not have this issue. Older PRs can rebase and be ok as well.

**Comment by marechal-p** [comment]
BTW, does that mean that travis's cache is ignoring some files?

**Comment by akosyakov** [comment]
Ideally we should not touch node_modules folder, otherwise yarn won't be able to install properly. I afraid that it will cause issues for downstream projects as well if they run ffmpeg test and do node_modules folder caching. Will they need to disable yarn integrity checks as well?

**Comment by marcdumais-work** [comment]
Hi @akosyakov 

> Ideally we should not touch node_module folders, otherwise yarn won't be able to install properly. 

Agreed. OTOH we want the `libffmpeg` test to be run fresh each time, or often at least. Maybe an alternative to the current setup would be to have a separate build, e.g. run nightly, that does not use cache and would run the `libffmpeg` test "fresh" each time. WDYT? 

> I afraid that it will cause issues for downstream projects as well if they run ffmpeg test and do node_module folders caching. Will they need to disable yarn integrity checks as well?

I think downstream projects should be ok, if they do not meddle with their cache like we do. However then their CI may not catch `libffmpeg' problems ASAP, which they may not care about in the general case.

**Comment by marechal-p** [comment]
> However then their CI may not catch `libffmpeg' problems ASAP, which they may not care about in the general case.

That is if they happen to cache `@theia/electron`, since it will not re-download the ffmpeg library on post-install then. But this shouldn't be an issue, unless a new electron version is pulled which would require a new library to be pulled as well.

> I afraid that it will cause issues for downstream projects as well if they run ffmpeg test

Shouldn't be a problem, the ffmpeg test only reads from disk, no write/delete. The issue in our repo was that because we cache deps, the library wouldn't be pulled each time and tested. It may be overkill to retest the same lib everytime, but at least it ensure that either the lib is clean or the test keeps working. If there is a failure we know there is something to investigate.

**Comment by akosyakov** [comment]
@marcdumais-work @marechal-p ok, if it is not common case and not enabled by default, let's stick with the current solution and see whether someone comes with the real issue later.

**Comment by vince-fugnitto** [comment]
I'll close the issue as the `ffmpeg` tests have been stable recently following the update #6436.
Work has also been done to remove the caching for `ffmpeg`.
