### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#56]
I would like to start thinking about how documentation will look like. The communication between the frontend and the backend will need to be documented, as well as (at the very least) the APIs that extensions will use.

To reduce overhead, at least in the beginning, I think that this doc should be embedded in the code.  It should be possible to generate an HTML version of it for easier browsing.

I'll make some research about the existing and popular documentation systems for Typescript.  If you already have some knowledge about that, please share!

**Comment by vince-fugnitto** [comment]
We are currently using `typedoc` to generate the documentation for every extension:
https://eclipse-theia.github.io/theia/docs/next/index.html 

I think the main idea would be to better document within the code but the overall documentation framework and generation is complete.
