### ISSUE TITLE
IDE seek help?

### ISSUE THREAD

**Issue by xinsuinizhuan** [eclipse-theia/theia#5604]
I have my own IDE that achieved by C++、python and plc，now i want to make it user theia, because theia could brower and destop, but i don't know how to do？ Make it a IDE、Extension or plugin-in？then how to embedded to theia？

**Comment by vince-fugnitto** [comment]
Do you mind sharing the details of what your current IDE achieves and what features it brings?

Keep in mind that Theia supports its own extensions that are part of the main repository and main organization, supports custom extensions, and also supports VSCode extensions.

If you'd like to start by using standard Theia, adding the languages and packages you want, then any missing features you might have had before can either be made as an extension or plugin :)

**Comment by akosyakov** [comment]
Hope you've already seen docs: https://www.theia-ide.org/doc/Composing_Applications.html

Theia is an IDE framework, you will need to compose your IDE using existing Theia and VS Code extensions. It's recommended to use VS Code extensions for custom functionality. If you reach a limitations though like you want to rebrand an IDE or have an access to DOM then add some Theia extensions.

**Comment by vince-fugnitto** [comment]
@xinsuinizhuan please feel free to re-open the issue if you still have questions :)
I assume that since there was no subsequent response that your answer was addressed and you no longer need assistance.
