### ISSUE TITLE
Whether support the customize IDE?

### ISSUE THREAD

**Issue by xinsuinizhuan** [eclipse-theia/theia#5607]
I want development own IDE，but my IDE support GUI. plus I will :
1、add my own some menu to theia menu.
2、dock my own Graphic control components, based on a UI library like React or much better a UI framework like Antd to panel left.
3、compile them by click buttom （in theia menu）or command. 
Whether theia support?

**Comment by vince-fugnitto** [comment]
Yes, all of that and more are supported :)

Please take a look at our extension-generator which easily creates a `hello-world` example, contributing a new top-level menu, and upon selection displays a message to end-users.

https://github.com/theia-ide/generator-theia-extension

There is also documentation on how to create a custom extension to Theia to provide the features you described, all of which will make it possible to fulfill your requirements.

https://www.theia-ide.org/doc/Authoring_Extensions.html

**Comment by vince-fugnitto** [comment]
@xinsuinizhuan I'm closing the issue for the moment, if you have further question please don't hesitate to ask 😄 Everyone is always happy to help!
