### ISSUE TITLE
Question: How have persistent open tabs state when reconnecting

### ISSUE THREAD

**Issue by gpoudrel** [eclipse-theia/theia#5613]
### Description
Question: How have persistent open tabs state in my workspace when reconnecting ?
I open tabs, files, etc in my current session.
Is there any way to make the current workspace state persistent ?

### Reproduction Steps
If I just close the Theia IDE tab, I open it again, ok I have all my files opened etc.
If I close the browser, empty cache, use private browsing etc, and I open Theia IDE again, I have nothing opened, no files etc.

**OS and Theia version:**
Docker theiaide/theia:next

**Comment by vince-fugnitto** [comment]
@gpoudrel Theia uses a browser's local storage for most of its persistent storage since it offers a quick and easy way to store the most essential elements of a workspace's state. If a more persistent storage is required it is definitely possible to use other forms of storage. For instance, the list of previously opened workspaces is stored under a user's home under `.theia/recentworkspaces.json`. The same should be possible for other elements you want to persist such as layout, and files opened.

**Comment by akosyakov** [comment]
If you are single user of your IDE then you can reimplement it to use the backend. Generally it does not work, since backend does not have information about user sessions. So saving a layout of one user could be used for another user.

**Comment by JonasHelming** [comment]
I believe the question was answered, please reopen in case there are open ends!

**Comment by vince-fugnitto** [comment]
> I believe the question was answered, please reopen in case there are open ends!

@JonasHelming alternatively we can convert `questions` to discussions and mark them as answered. 
I'm not sure what the better approach is however.

**Comment by JonasHelming** [comment]
IMHO closing them if the answered seems fine to me. What exactly do you mean by "convert to discussion"?

**Comment by vince-fugnitto** [comment]
> IMHO closing them if the answered seems fine to me. What exactly do you mean by "convert to discussion"?

@JonasHelming alternatively we can use the "convert to discussion" so they are added to our discussion board (https://github.com/eclipse-theia/theia/discussions) where new questions should be asked.

![image](https://user-images.githubusercontent.com/40359487/109849574-83ae4a00-7c1f-11eb-9567-160663aac82b.png)

**Comment by JonasHelming** [comment]
Ah, I wans't aware of this, yes that sounds reasonable! Should we then covert most questions to discussions actually?
