### ISSUE TITLE
Advice/help for plugin ideas

### ISSUE THREAD

**Issue by abalter** [eclipse-theia/theia#5618]
I have some plugins I'd like to build, but I'm kind of a hacky programmer who mostly does scientific programming. What might be a good place to go begging for some hand-holding? I'm thinking of something along the lines of:

Q: "I want to make a plugin that does X. Can you please point me to the hooks in the API I will need to access?"

A: "Sure, I'm so glad you asked! I love questions like this. You really made my day."

What I want to do is to mock up a Javascript data science environment as step 0.01 in a larger idea. I've already got most of these components working in just JS/JQuery on an html page, and they are pretty simple. But I want to make them work in Theia with tabs, menus, bling, etc.

* A javascript console where you type commands and get output. I already mocked this up really simply using the evil `eval`, but in an iframe, so it's safe(er). Really just a few lines of code. Ultimately would want a better solution.
* Variable explorer connected to the console. I can easily find all the global variables and throw them into a clickable list. Just need a `<div>` to write the stuff into. But it would be a separate tab.
* Command history. Again, need another tab I can write to.
* CTRL+Enter on a line of code or selection to send to console.
* Run code files in the same environment as the console.
* Plot window that is basically a `<div>` to where I can render plots. Again another tab.

Seems like the main starting point is the console.

**Comment by akosyakov** [comment]
I don't think you can do it via plugin, you need Theia extension for widgets and DOM integration. We have an extension to build [custom consoles](https://github.com/theia-ide/theia/tree/master/packages/console) which is used in [debug extension](https://github.com/theia-ide/theia/tree/master/packages/debug) already. You can study these two qw the starting point to create your own custom console.

**Comment by vince-fugnitto** [comment]
@abalter please feel free to re-open the issue or open additional issues if you require more concrete help. I believe with Anton's answer and no subsequent response there is no longer a need for help.
