### ISSUE TITLE
[monaco] support multiple simultaneous quick-fixes

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#5625]
**Description**

We should support `quick-fix` items that performs multiple quick-fixes simultaneously. 
For instance, if I have multiple identical quick-fixes for a given file, there should be logic present
to perform the quick-fix for all violations in that file.

Given a file `A`, and `A` has multiple `is declared but its value is never read.` errors, there should be a quick-fix to `Remove all unused declarations` which fixes all the similar issues.

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/60537416-7a483e00-9cd6-11e9-82ef-9a8c7a7905fe.png)

</div>

**Comment by akosyakov** [comment]
I think it is supported, just ts version which we use does not provide such quick fixes. We have try to catch up with latest ts: https://github.com/theia-ide/theia/issues/5260

**Comment by vince-fugnitto** [comment]
I verified and the `Delete all unused declarations` is now also supported.

![ts](https://user-images.githubusercontent.com/40359487/97471654-53783700-191f-11eb-8714-fa823cac6a05.gif)
