### ISSUE TITLE
quick palette not available in the maximized mode

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5629]
In order to reproduce:
- maximize the editor
- try to trigger the quick command palette (F1)

**Comment by kpge** [comment]
I can not reprofuce it :(
![image](https://user-images.githubusercontent.com/35068357/60594067-b793f500-9dd6-11e9-9196-e10af03121eb.png)

**Comment by vince-fugnitto** [comment]
@akosyakov I can't reproduce it either, I see the command palette even when an editor is maximized.

**Comment by lmcbout** [comment]
I tried with Chrome  and Firefox browser and electron on Ubuntu 16.04, I cannot reproduce it either, the quick palette is always available

**Comment by akosyakov** [comment]
I can reproduce it in Gitpod prod, but not with vanilla Theia. Although Gitpod does not have any specific in this area, strange :(

**Comment by vince-fugnitto** [comment]
@akosyakov tested lately in Gitpod and the issue does not persist :)

**Comment by akosyakov** [comment]
Ok, feel free to close

**Comment by vince-fugnitto** [comment]
Thanks @akosyakov :)
