### ISSUE TITLE
[vscode] TreeItem fails to render if it has a command tied to it 

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#5666]
#4975 seems to have regressed since #5556, on TreeItems which have their `command` field set.

```
root ERROR [hosted-plugin: 73] [ERRO: 03:36:57.738 extension.js.on():43]: Unhandled promise rejection: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.replyOK (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:280:103)
    at /home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:158:51
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

You can see that I had to not set `command` on my TreeItems to work around this bug. https://github.com/eclipse/codewind-vscode/commit/92b56836ce9b37a1db4bc5c29bb792f1e9972677

It also appears to be intermittent with some treeitems, but happens every time with others - I could not figure out what caused the difference.

@akosyakov since you fixed this originally

**Comment by akosyakov** [comment]
Please have a look at it after https://github.com/theia-ide/theia/pull/5665 gets merged, plugin trees were refactored to allow state restoration.

**Comment by tolusha** [comment]
@tetchel Is this issue still reproducible since #5665 has been merged

**Comment by tetchel** [comment]
Sorry, I verified this like a month ago! It's fixed.
