### ISSUE TITLE
[vscode] window.showQuickPick canPickMany is not supported

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#5673]
The `canPickMany` option of [QuickPickOptions](https://code.visualstudio.com/api/references/vscode-api#QuickPickOptions) appears to have no effect in Theia.

**Comment by akosyakov** [comment]
@tetchel Is it still the case?

**Comment by DanTup** [comment]
This is certainly still the case in my testing today, there are no tickboxes when I run **Dart: Capture Logs**.

**Comment by svenefftinge** [comment]
Still not supported. Java VS Code uses this for accessors.
<img width="988" alt="Screenshot 2020-05-25 at 15 30 36" src="https://user-images.githubusercontent.com/372735/82817361-2968a780-9e9d-11ea-9aee-73c8d0b9b312.png">

**Comment by vinokurig** [comment]
Depends on https://github.com/eclipse-theia/theia/issues/8969

**Comment by vince-fugnitto** [comment]
Closing as the issue seems outdated, and the feature supported:

![Screen Shot 2022-08-31 at 8 40 59 AM](https://user-images.githubusercontent.com/40359487/187680767-106eaeeb-bf44-4097-b877-9292d6a3550b.png)
