### ISSUE TITLE
settings.json file addition/edit doee not effect actual settings and does not trigger changeEvent

### ISSUE THREAD

**Issue by ariel-bentu** [eclipse-theia/theia#5683]
### Description
Using settings in a vscode-extention:

* If you add a settings.json file under .theia folder, does not fire the change event - after registering event: `vscode.workspace.onDidChangeConfiguration(...)`
* Also, trying to read the settings, using `let conf = workspace.getConfiguration(...)`, is not consistent in getting the changes (usually does not show the updates).

### Reproduction Steps
`git clone https://github.com/ariel-bentu/theia-vscode-gaps.git`

* when running it, you can run command called: `BUG: Show settings` - you can see the defaults: `{listOfBugs:[ {"name":"bug1"}]`
* Now create the folder .theia and a file settings.json
* In that file add: 
```
{
 "listOfBugs:[
  {"name":"newbug"}
]
}
```
* After saving there should have been an infoMessage saying "config changed" - in vscode works in theia not.
* Rerun the command `BUG: Show settings` - changes don't show

**OS and Theia version:**
all, latest
**Diagnostics:**

**Comment by akosyakov** [comment]
We need to write more unit tests for events, similarly how we did it for reading/writing preferences.

**Comment by amiramw** [comment]
@ariel-bentu does it still reproduce for you? With [this ](https://github.com/amiramw/theia-vscode-gaps) vscode extension the event handler is called on create and update of .theia/settings.json.

**Comment by ariel-bentu** [comment]
Hi,
I retested my code. When settings on User level - it works fine. when settings in settings.json  .theia (or .vscode) - it does not work, and changes are (1) don't trigger the event and (2) are not relected in `workspace.getConfiguration(...)` - I get the value that was read the first time before changes.

I noticed that I did not push into my github I mentioned above the latest code - so now I did: `https://github.com/ariel-bentu/theia-vscode-gaps.git`

**Comment by tsmaeder** [comment]
@ariel-bentu you comment is not clear to me: I did the following two things and both triggered a preference change for me:

1. Changed <workspace_root>/.theia/settings.json in a text editor and hit save
2. Changed <home_dir>/.theia/settings.json in a text editor and hit save.

Could you maybe post a screenshot of your workspace?

**Comment by danarad05** [comment]
@ariel-bentu @amiramw @tsmaeder @DoroNahari 

As far as I can tell, changes to settings files/preferences for User and Workspace work and are caught by vscode.workspace.onDidChangeConfiguration in Theia similarly to VSCODE.

These are the tests I ran and their results (also went over it with @DoroNahari), please verify @ariel-bentu if sufficient:

1. In VSCODE:
a) User preferences updates /user/Settings.json and vice versa (update to Settings.json file will update preferences). Also when running extension - change to files is caught by vscode.workspace.onDidChangeConfiguration.
b) Workspace preferences update /.vscode/Settings.json and vice versa. Also when running extension - change to files is caught by vscode.workspace.onDidChangeConfiguration.

2). In THEIA:
a) User preferences updates /user/.theia/Settings.json and vice versa. Also when running extension as Hosted Plugin in Theia - change to file is caught by vscode.workspace.onDidChangeConfiguration.
b) Workspace preferences updates /.theia/Settings.json or /.theia/Settings.json and vice versa. Also when running extension as Hosted Plugin in Theia - change to file is caught by vscode.workspace.onDidChangeConfiguration.

Thanks
-Dan

**Comment by ariel-bentu** [comment]
I opened this issue on Sep-2019. I suppose that by now, a year later this
works. So feel free to close.

בתאריך יום ד׳, 7 באוק׳ 2020 ב-11:25 מאת Dan Arad <notifications@github.com>:

**Comment by danarad05** [comment]
https://github.com/eclipse-theia/theia/issues/5683#issuecomment-704808089

@amiramw @DoroNahari Could you close issue as I do not have permissions.
Thanks
