### ISSUE TITLE
[git | scm] deleting file gives workspace root 'Deleted' decoration

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#5712]
**Description**

If a file under source-control is deleted, the workspace root gets a `Deleted` decoration.

**Steps to Reproduce**
1. Create a workspace folder (ex: `git-test`)
2. Create two files in the workspace (`a.ts` and `b.ts`)
3. Perform the command `git init` in the terminal for the workspace
4. Delete a file (ex: `a.ts`)
5. The `Deleted` decoration is added to the workspace root.

<div align='center'>

![Screenshot from 2019-07-15 14-56-58](https://user-images.githubusercontent.com/40359487/61241347-55f65380-a711-11e9-96f3-3a5defba9629.png)
![Screenshot from 2019-07-15 14-57-21](https://user-images.githubusercontent.com/40359487/61241348-568eea00-a711-11e9-9c14-6515cd87d628.png)

</div>

---

Is this the expected behavior?

**Comment by kittaakos** [comment]
> Is this the expected behavior?

Yes.
https://github.com/theia-ide/theia/blob/da653c2692ad65c865ca5ba96b865b270cc916ff/packages/git/src/browser/git-decorator.ts#L91

Do you have a better approach to show the deletions?

**Comment by vince-fugnitto** [comment]
> Yes.

Thank you @kittaakos, I was trying to understand the feature and how we can nicely display the decorations while attempting to keep the most information as possible. Based on the comment you provided, we only display the highest status (ex: `Deleted`) despite other statuses being present (ex: `Modified`).

Thank you for clarifying for me!

**Comment by vince-fugnitto** [comment]
@kittaakos 
Comparing the behavior between Theia and VSCode I can see two major differences:
1. VSCode does not display `Deleted` markers
2. VSCode displays a generic marker (`circle`) for parents of the given resource

Is it an area we'd want to align, or do you see added value in displayed `Deleted` markers?

| Current | After (Align with VSCode) |
|:---:|:---:|
| <img width="449" alt="Screen Shot 2019-09-20 at 1 14 12 PM" src="https://user-images.githubusercontent.com/40359487/65345768-fc932080-dba8-11e9-969c-b18a6f172e29.png">| <img width="447" alt="Screen Shot 2019-09-20 at 1 14 49 PM" src="https://user-images.githubusercontent.com/40359487/65345756-f7ce6c80-dba8-11e9-9fcd-b2da15a5a4ad.png">|

**Comment by kittaakos** [comment]
> Is it an area we'd want to align, or do you see added value in displayed `Deleted` markers?

I like to see if something was deleted, that's why we have the current behavior. But if the majority prefers adapting it to VS Code, I do not have any objections.

**Comment by vince-fugnitto** [comment]
I think the current approach is fine, we show the more informative decorations during a deletion and there doesn't seem to be a real push in the community to update the git decorations at the moment. I will close the issue and re-open it if that ever changes :)
