### ISSUE TITLE
Failed to decode text for a CPP file

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#5713]
### Description
When using the "File search" and some results are in a ".cpp" or in ".h" files, 
select the search result to open a diff editor showing the file before replacing 
( on the left side) while showing the modified file ( on the right side ).

When hovering on the left side, Git Lens sent info in the tooltip 
When hovering on the right side, it generates the following error on the server console. 
Also, when closing the editor, it also sent to the server console some info:

### Reproduction Steps
1. open a C/C++ project
2. open the `search-in-workspace` widget (menu `View` then `Search`)
3. search for a term present in the workspace, click extra options to get the `replace field`
4. on successfully searching, click the matched result generating a `diff` view between the old and new values.
5. `hover` over the right `diff` split (clangd generates error regarding the encoding). 

An illustrated example can be seen bellow:

<div align='center'>

![z](https://user-images.githubusercontent.com/40359487/61254294-f65c7000-a731-11e9-8900-0d1e7345c1e9.gif)

</div>

### Diagnostics

- When **hovering** over the file:
---
```
I[15:45:48.439] <-- textDocument/hover(16)
E[15:45:48.440] Clangd only supports 'file' URI scheme for workspace files: mem-txt:/home/lmcbout/theia/workspace-cpp/jb/bird-flocking-sim-tbb/Flock.h?%23ifndef%20BOIDS_FLOCK_H%0A%23define%20BOIDS_FLOCK_H%0A%0A%23include%20%3Cthread%3E%0A%23include%20%3Cvector%3E%0A%23include%20%22Boid.h%22%0A%23include%20%22Common.h%22%0A%23include%20%3Ctbb%2Ftask_group.h%3E%0A%0Aclass%20Flock%20%7B%0Apublic%3A%0A%20%20%20%20Color%20color%3B%0A%20%20%20%20std%3A%3Avector%3CBoid%3E%20boids%3B%0A%20%20%20%20Flock%28%29%3B%0A%20%20%20%20void%20bbbFlock%28%29%3B%0A%7D%3B%0A%0A%23endif%20%2F%2FBOIDS_FLOCK_H%0A
E[15:45:48.440] Failed to decode textDocument/hover request.
I[15:45:48.440] --> reply:textDocument/hover(16) 0 ms, error: -32600: failed to decode request
I[15:45:48.440] <-- $/cancelRequest
```

---
- When **closing** the file:

```
root ERROR C/C++: I[15:46:02.359] <-- textDocument/didClose
I[15:46:02.359] --> textDocument/publishDiagnostics
I[15:46:02.359] <-- textDocument/didClose
E[15:46:02.359] Clangd only supports 'file' URI scheme for workspace files: mem-txt:/home/lmcbout/theia/workspace-cpp/jb/bird-flocking-sim-tbb/Flock.h?%23ifndef%20BOIDS_FLOCK_H%0A%23define%20BOIDS_FLOCK_H%0A%0A%23include%20%3Cthread%3E%0A%23include%20%3Cvector%3E%0A%23include%20%22Boid.h%22%0A%23include%20%22Common.h%22%0A%23include%20%3Ctbb%2Ftask_group.h%3E%0A%0Aclass%20Flock%20%7B%0Apublic%3A%0A%20%20%20%20Color%20color%3B%0A%20%20%20%20std%3A%3Avector%3CBoid%3E%20boids%3B%0A%20%20%20%20Flock%28%29%3B%0A%20%20%20%20void%20bbbFlock%28%29%3B%0A%7D%3B%0A%0A%23endif%20%2F%2FBOIDS_FLOCK_H%0A
E[15:46:02.359] Failed to decode textDocument/didClose request.
```

**OS and Theia version:**
Ubuntu 16.04
Theia 0.8.0

**Comment by vince-fugnitto** [comment]
> it generates the following error on the server console

@lmcbout it's not actually an error reported on the console, it's just the communication with `clangd` which informs us that it failed to **decode**.

**Comment by vince-fugnitto** [comment]
@lmcbout I updated the description of the issue so it's a little easier to follow.

**Comment by vince-fugnitto** [comment]
I don't believe this is a bug since the `replace-diff` editor does not in fact have a `file://` scheme in which clangd knows about but it is just a representation of a file. In any case if it's really an issue is should now be moved to [theia-cpp-extensions](https://github.com/eclipse-theia/theia-cpp-extensions) repo.
