### ISSUE TITLE
`File > Upload Files...` should always be enabled + always upload into workspace root

### ISSUE THREAD

**Issue by jankeromnes** [eclipse-theia/theia#5739]
### Description

I was recently confused to find the `File > Upload Files...` menu entry disabled (greyed out).

Only after messing around for a while did I notice that I had to select a _directory_ in the File Tree panel for the feature to be enabled. In my mind, the `File` menu should not be influenced by the state of the File Tree panel.

For example, in Cloud9, `File > Upload Files...` was always enabled, and it always uploaded to the workspace root, regardless of which files or directory was currently selected in the File Tree -- only the File Tree context menu was able to upload into different locations.

### Reproduction Steps

1. Open any project in Theia
2. Click on `File`
3. Try to click on `Upload Files...`, be confused because it's disabled and you're not sure why

**OS and Theia version:** Mac OS, Firefox Nightly, latest Theia

**Diagnostics:**  (none)

**Comment by qx-juilliard** [comment]
I made a working demo:

https://github.com/qx-juilliard/theia/commit/81e69f2216bc93d055c113438177bb9f36554b45

It handles file upload menu item with the following strategy:

- if current selection is undefined, then upload to workspace root folder
- if current selection is a regular file, then upload to its containing folder

**Comment by akosyakov** [comment]
@qx-juilliard please propose a PR if you want a review, you can make it a draft (or WIP) if you want to check the design first

**Comment by qx-juilliard** [comment]
will do!

**Comment by federicobozzini** [comment]
Was this issue fixed by this commit https://github.com/eclipse-theia/theia/pull/11756 ?

**Comment by vince-fugnitto** [comment]
> Was this issue fixed by this commit #11756 ?

@federicobozzini it doesn't look like there is a default case where it'll upload to the workspace root, a selection is still needed in order for the command to be enabled, while #11756 only handles visibility.
