### ISSUE TITLE
TreeItem on click commands don't work

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#5744]
With #5661 in, `command`s no longer break the tree, but the commands do not work (they never execute, so I assume there is just no listener).

In VS Code, single-clicking a [tree item](https://code.visualstudio.com/api/references/vscode-api#TreeItem) runs the [`command`](https://code.visualstudio.com/api/references/vscode-api#Command) tied to it, eg opening a file in the Explorer view. 
This can be configured to be double-click instead with the setting `workbench.list.openMode`. (see https://github.com/Microsoft/vscode/issues/39601)

TreeItem onclick commands do not appear to have any effect in Theia.

**Comment by vince-fugnitto** [comment]
@tetchel which command were you attempting to execute with the tree?

**Comment by tetchel** [comment]
A custom one from my extension

**Comment by vince-fugnitto** [comment]
> Edit: also `revealInExplorer`, not sure if Theia has that builtin.

We do have the command `Reveal in Explorer`
https://github.com/theia-ide/theia/blob/d4a15ad515666ead71556faf04c226d9157d3a33/packages/navigator/src/browser/navigator-contribution.ts#L38

**Comment by tetchel** [comment]
hmm, that is a different command ID than vs code (again, `revealInExplorer`), perhaps that should be a separate issue.

**Comment by vince-fugnitto** [comment]
> hmm, that is a different command ID than vs code (again, `revealInExplorer`), perhaps that should be a separate issue.

I believe it will be, it's part of the https://github.com/theia-ide/theia/pull/5590 change :)

**Comment by akosyakov** [comment]
@tetchel Can it be closed by https://github.com/theia-ide/theia/issues/5744? Could you verify please?

**Comment by tetchel** [comment]
Indeed this is fixed in 0.10, thanks guys
