### ISSUE TITLE
[Terminal] SomeKey Can't Work

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5749]
### Description
latest version in terminal
Ctrl + C Can't Work on terminal

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by 502647092** [comment]
test on gitpod.io browers example also can't work
@akosyakov

**Comment by 502647092** [comment]
i add config to keymap.json fix this problem
```
[
    {
        "command": "core.copy",
        "keybinding": "ctrlcmd+c",
        "context": "strictEditorTextFocus"
    }
]
```

**Comment by akosyakov** [comment]
It works for me. @kittaakos @vince-fugnitto Could you try as well?

**Comment by akosyakov** [comment]
@502647092 Which os and browser versions?

**Comment by 502647092** [comment]
> @502647092 Which os and browser versions?

windows10 chrome 75.0

**Comment by kittaakos** [comment]
Works for me on Windows in Chrome:
```
 git clean -ffxqd && git reset --hard && git rev-parse --short HEAD && yarn && yarn --cwd ./examples/browser/ start
Checking out files: 100% (1731/1731), done.
HEAD is now at 3587c237c Add 'theia-widget-noInfo' css class to fix message inconsistencies
3587c237c
```

![screencast 2019-07-19 12-45-10](https://user-images.githubusercontent.com/1405703/61530199-b512db80-aa23-11e9-8704-4d10ffb017d2.gif)

**Comment by 502647092** [comment]
@kittaakos Not Copy
i want to close process

**Comment by kittaakos** [comment]
> @kittaakos Not Copy
> i want to close process

Well, yeah both cannot work. I can confirm, I could not SIGTERM the process from the terminal with `Ctrl` + `C` on Windows.

**Comment by akosyakov** [comment]
So it is not a regression?

**Comment by kittaakos** [comment]
> So it is not a regression?

Yeah, seems to be a bug.

I tried if disabling the copy in the terminal helps as quick workaround, but no.

https://github.com/theia-ide/theia/blob/3587c237cacc638dc54ec19dc3eaa755c2e69fb5/packages/terminal/src/browser/terminal-widget-impl.ts#L499-L500

![Screen Shot 2019-07-19 at 17 29 56](https://user-images.githubusercontent.com/1405703/61547140-19956100-aa4b-11e9-832e-850e85e6c955.jpg)


```
root ERROR Error: No option with key "enableCopy"
    at Terminal.push.../../node_modules/xterm/lib/Terminal.js.Terminal.setOption (http://localhost:3000/34.bundle.js:507
6:19)
    at Terminal.push.../../node_modules/xterm/lib/public/Terminal.js.Terminal.setOption (http://localhost:3000/34.bundle
.js:7906:20)
    at http://localhost:3000/40.bundle.js:363:28
    at http://localhost:3000/bundle.js:109260:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:109275:
39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:109363:29)
    at http://localhost:3000/bundle.js:93655:40
    at http://localhost:3000/bundle.js:109260:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:109275:
39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:109363:29)
root ERROR Error: No option with key "enablePaste"
    at Terminal.push.../../node_modules/xterm/lib/Terminal.js.Terminal.setOption (http://localhost:3000/34.bundle.js:507
6:19)
    at Terminal.push.../../node_modules/xterm/lib/public/Terminal.js.Terminal.setOption (http://localhost:3000/34.bundle
.js:7906:20)
    at http://localhost:3000/40.bundle.js:363:28
    at http://localhost:3000/bundle.js:109260:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:109275:
39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:109363:29)
    at http://localhost:3000/bundle.js:93655:40
    at http://localhost:3000/bundle.js:109260:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:109275:
39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:109363:29)
```

**Comment by kittaakos** [comment]
But my exception can be an unrelated issue.

**Comment by 502647092** [comment]
maybe is context problem?
i add config can fix it

**Comment by roflcoopter** [comment]
Experiencing the same.
Before i could use Ctrl+C to close a `tail -f` and if text was highlighted in the terminal Ctrl+C would copy it.

Now Ctrl+C to terminate the command doesn't work, same setup. Windows 10 Chrome 75

**Comment by AndrienkoAleksandr** [comment]
I think we should copy by Ctrl+C in case if terminal has selection

[xterm.js selection docs](https://xtermjs.org/docs/api/terminal/classes/terminal/#getselection)

 otherwise we shouldn't handle this hotkey at all.

**Comment by kittaakos** [comment]
> if terminal has selection

https://github.com/theia-ide/theia/blob/3587c237cacc638dc54ec19dc3eaa755c2e69fb5/packages/terminal/src/browser/terminal-widget-impl.ts#L501

**Comment by kittaakos** [comment]
I have switched back to da653c269, which is one commit before the #5326.

![Screen Shot 2019-07-22 at 10 22 31](https://user-images.githubusercontent.com/1405703/61619761-c819eb80-ac6f-11e9-8377-42192ea9fbec.jpg)

I can confirm, SIGTERM with `ctrl`+`c` works on Windows from the terminal:

![screencast 2019-07-22 10-58-28](https://user-images.githubusercontent.com/1405703/61619792-da942500-ac6f-11e9-9f3e-11f79ac78d5a.gif)

I am going to revert #5326.

**Comment by JPinkney** [comment]
My only guess would be that somewhere in https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/keybinding.ts#L557 its trying to apply ctrl+c for copy instead. I don't have a windows machine but I'll try to get one so I can find out whats causing the issue

**Comment by akosyakov** [comment]
Yes, it looks like there are 2 bindings matching and order before was different. A agree with https://github.com/theia-ide/theia/issues/5749#issuecomment-513287922 one this bindings should have more specific context or when closure to disambiguate.

@JPinkney we revert for now, please open a new PR

**Comment by akosyakov** [comment]
Reopen it since it should be taken into the consideration when someone reverts https://github.com/theia-ide/theia/commit/dd512441df7ef230f23134f726eb2e09e54de4dd

**Comment by eduprovide** [comment]
Visit my website for all educational related questions http://eduprovide.com

**Comment by akosyakov** [comment]
We should also revert https://github.com/eclipse-theia/theia/pull/6170 when we align with VS Code by reverting https://github.com/eclipse-theia/theia/commit/dd512441df7ef230f23134f726eb2e09e54de4dd.

**Comment by tsmaeder** [comment]
I'm observing this problem now: I was able to verify that it still worked in commit 3f28503e754bbb4fa6534612af3d1ed6da3ed66a, but is broken in 362e8f13e97a850387c103e8e7ee29d6e36b873e

**Comment by tsmaeder** [comment]
Was able to trace this back to this commit: https://github.com/eclipse-theia/theia/commit/62c9a8361c772b4bfa33084fd62bef8eec158f08

**Comment by akosyakov** [comment]
@tsmaeder I think it is a new regression. Could you file a new issue please with reproducible steps? I will have a look at it tomorrow.

**Comment by 502647092** [comment]
@akosyakov recent version cause Tmux can't received prefix
`Ctrl + A => d`
![github](https://user-images.githubusercontent.com/10203793/82277415-5eb35800-99ba-11ea-8274-8f634fd3e0b5.gif)

**Comment by akosyakov** [comment]
resolved by https://github.com/eclipse-theia/theia/pull/7839
