### ISSUE TITLE
[editor-preview] double-clicking editor tab maximizes view instead of docking

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#5757]
**Description**

In order to persist an `editor-preview` (dock the editor), the tab of the editor can be double-clicked similarly to vscode. However, after the change #4744 this is no longer the case since double-clicking any editor results in maximizing the view. Should the `editor-preview`'s behavior be updated in this case to first persist the tab (first double-click) and any subsequent double-clicks maximize the view (since it is now treated as a regular `editor`)?

**How to test**

1. start the application, confirm that the preferences `editor.enablePreview` is enabled and `list.openMode` is set to `singleClick`
2. open an editor by single-clicking a file in the explorer
3. double-click the editor's tab (expect the editor to be docked but instead the view is maximized)

**Comment by akosyakov** [comment]
Can we handle it somehow with DOM mouse click events? i.e. editor-preview should stop even propagation if it pins an editor.

**Comment by vince-fugnitto** [comment]
> Can we handle it somehow with DOM mouse click events? i.e. editor-preview should stop even propagation if it pins an editor.

It might be possible, if I have the time I can try it out :)
