### ISSUE TITLE
[vscode] window.showQuickPick CancellationToken is incomplete

### ISSUE THREAD

**Issue by hacke2** [eclipse-theia/theia#5764]
### Description

The CancellationToken option of the showpick component of the vscode extension seems to be incomplete.

I see vscode will [hide quickopen widget](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/quickinput/quickInput.ts#L1238).

`
token.onCancellationRequested(() => {
  input.hide();
})
`

but theia is no such logic.

I see canPickMany is not supported also #5673

**Comment by vince-fugnitto** [comment]
@hacke2 do you mind providing an extension to verify and test the bug?

**Comment by akosyakov** [comment]
Indeed, we never pass a token to the main thread, so a quick pick is not hidden if a client cancels the token.

**Comment by akosyakov** [comment]
@hacke2 Could you check please whether https://github.com/eclipse-theia/theia/pull/6921 resolves the issue for you? I'm fixing and adding more tests there, but would be nice to know earlier whether i've overlooked something.
