### ISSUE TITLE
[Eclipse Foundation] Update CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#5780]
That file pre-dates the intention to join the Eclipse Foundation and should probably be updated. 

Option 1: replace "enforcement" email address `info@typefox.io` with Eclipse Foundation equivalent: `codeofconduct@eclipse.org`

Option 2: replace content of current file with Eclipse Foundation ["Community Code of Conduct"](https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php)

**Comment by marcdumais-work** [comment]
I lean towards option 2. Opinions?

**Comment by vince-fugnitto** [comment]
> I lean towards option 2. Opinions?

I think option #2 is fine as well.
