### ISSUE TITLE
review how main electron process is forked

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5796]
We should make sure that whenever backend process is forked, it marks child process as no electron. Otherwise it opens a new electron window on desktop.

There are 2 clients not doing it:
- https://github.com/theia-ide/theia/blob/17f51ed20f055f516167526e7dab1773d15c6219/packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts#L190
- https://github.com/theia-ide/theia/blob/17f51ed20f055f516167526e7dab1773d15c6219/packages/core/src/node/messaging/ipc-connection-provider.ts#L104

**Comment by akosyakov** [comment]
It would be good to have `Process` section in the coding guidelines and document this.

**Comment by kittaakos** [comment]
> We should make sure that whenever backend process is forked, it marks child process as no electron.

That's the default electron behavior: https://github.com/electron/electron/issues/6656#issue-168436634 
When `process.fork` is called from electron, `ELECTRON_RUN_AS_NODE=1` is always set.
