### ISSUE TITLE
Open the outline view programmatically

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#5809]
### Description
I want to open the outline of the editor programmatically using my own extension 
I searched but didn't able to find the right API.
Any example code will help me ..

thanks

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
`OutlineViewContribution.openView` should work

**Comment by vince-fugnitto** [comment]
@dhananjayharel were you able to address your issue?

**Comment by dhananjayharel** [comment]
yes
