### ISSUE TITLE
support input variable substitution for tasks

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5836]
It's a follow-up of https://github.com/theia-ide/theia/issues/5835. It depends on https://github.com/theia-ide/theia/issues/5013.

cc @marcdumais-work @elaihau @vince-fugnitto

**Comment by elaihau** [comment]
@akosyakov 
could you please explain the reason that it is this one dependent on #5013 ?

please correct me if i am wrong: 
i believe we can support the `input` section in `tasks.json` and variable substitution even if tasks are not accessible from the configuration / preference. Having it is just one more round of "resolving task configuration".

**Comment by akosyakov** [comment]
@elaihau sorry i cannot remember already, probably I thought it would be easier to implement if tasks will be loaded through preferences, or did not want to implement it before refactoring loading via preferences to avoid double work

**Comment by akosyakov** [comment]
Content assist for input variables still don't work in tasks.json. It should work the same way as for launch configurations.

**Comment by elaihau** [comment]
Could this one be closed as #6334 is merged？

**Comment by akosyakov** [comment]
Sure
