### ISSUE TITLE
[language] WorkspaceEdit applier doesn't support  ResourceFileEdit

### ISSUE THREAD

**Issue by svor** [eclipse-theia/theia#5841]
### Description

WorkspaceEdit interface has a structure:
```js
interface WorkspaceEdit {
  edits: Array<ResourceTextEdit | ResourceFileEdit>;
  rejectReason?: string;
}
```
But If some language operation provides `WorkspaceEdit` which contains  `ResourceFileEdit` elements - they will be skipped. 

The problem is in [monaco-workspace.ts](https://github.com/theia-ide/theia/blob/master/packages/monaco/src/browser/monaco-workspace.ts#L333) where `WorkspaceEdit` element is parsed.

**Comment by akosyakov** [comment]
It will be addressed as part of Monaco migration.
