### ISSUE TITLE
latest next version can't save workspace status

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5852]
### Description
![temp](https://user-images.githubusercontent.com/10203793/62432274-66727a80-b761-11e9-96b7-d7350817d46c.gif)

### Reproduction Steps
see gif

**OS and Theia version:**
latest next version
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 thank you for the reporting, could you please provide browser and backend logs? Is there any errors?

**Comment by 502647092** [comment]
@akosyakov 
```
root ERROR Could not restore layout Error: Saved workbench layout (version 2.0) is incompatible with the current (3.0)
    at n.getValidatedLayoutData (https://theia.miaowoo.cc/bundle.js:1:325918)
    at n.<anonymous> (https://theia.miaowoo.cc/bundle.js:1:324809)
    at https://theia.miaowoo.cc/bundle.js:1:314739
    at Object.next (https://theia.miaowoo.cc/bundle.js:1:314844)
    at https://theia.miaowoo.cc/bundle.js:1:313757
    at new Promise (<anonymous>)
    at l (https://theia.miaowoo.cc/bundle.js:1:313534)
    at n.setLayoutData (https://theia.miaowoo.cc/bundle.js:1:324698)
    at e.<anonymous> (https://theia.miaowoo.cc/bundle.js:19:14748)
    at https://theia.miaowoo.cc/bundle.js:19:13088
```

**Comment by akosyakov** [comment]
@502647092 Is there anything else? This error is expected, it should then use default layout. I wonder why afterwards a new layout is not stored for you.

**Comment by akosyakov** [comment]
Also is it electron? which browser and os?

**Comment by 502647092** [comment]
Windows 10
Chrome 76.0.3809.87
after i delete old local storage theia:/:file:///home/project:layout and refresh
it is work

**Comment by akosyakov** [comment]
> after i delete old local storage theia:/:file:///home/project:layout and refresh

That's bad, that it does not work automatically :( I wonder why old layout is not discarded for you in first place.

**Comment by 502647092** [comment]
@akosyakov 
https://github.com/theia-ide/theia/blob/cc51575a2c8660f13794ed9099ee14daaca982b9/packages/core/src/browser/shell/application-shell.ts#L563-L565
https://github.com/theia-ide/theia/blob/cc51575a2c8660f13794ed9099ee14daaca982b9/packages/core/src/browser/shell/application-shell.ts#L602-L604
meybe before save content need get layout but throw error cause version incompatible

**Comment by akosyakov** [comment]
@502647092 When you reload next time a new layout should be generated with a new version, so there should not be version mismatch. For some reasons for you without resetting the layout, reload won't trigger serialization of a new layout.

**Comment by vince-fugnitto** [comment]
I believe this issue is no longer applicable given the layout is quite old. We can revisit the problem if it occurs again for newer layout migrations :+1:
