### ISSUE TITLE
Theia is producing unexpected semantic highlightings for c++.

### ISSUE THREAD

**Issue by jvikstrom** [eclipse-theia/theia#5854]
### Description
Theia's semantic highlighting client is producing unexpected colorings in certain cases after enabling it for the c++ client. (look at this PR [here](https://github.com/theia-ide/theia/pull/5850) for a reference on how to do it.

I've verified that clangd sends the correct source ranges for the test cases below.

### Reproduction Steps
* Enable semantic highlighting in the c++ client.
```
namespace aaa {
    void foo();
}
void foo() {
    aaa::foo();
}
```

In this case theia will color the `aaa::foo();` incorrectly. The entire `aaa::foo` range will be highlighted as a function. Clangd sends the `aaa` range as a namespace and the `foo` range as a function. 
On thing I tested was to add a custom rule to the color theme for namespaces (I gave namespaces a gray color). When doing that the `aaa` part will be highlighted as a namespace (which is correct). But the `::foo` will be highlighted as a function. So in this case it almost seems to work correctly, but the `::` should not be highlighted as a function.
 
Another case (probably related to the one above though) is this one.
```
namespace aaa {
  struct A {
    static void f();
  };
}
class A {};
void foo() {
  aaa::A::f();
  aaa::A a;
}
```

Here without the custom namespace rule the entire `aaa::A::f` range is highlighted as a function. When adding the custom namespace rule `aaa` is highlighted as a namespace, but the `::A::f` range is highlighted as a function.
However, the `aaa::A a` line is highlighted correctly. The `::` is not highlighted here. `aaa` is a namespace, `A` is a class and `a` is a variable.

But this is as far as I've looked into it, I don't know the theia code base but I hope this can help someone track this bug down.

**OS and Theia version:**
This happens on the latest master after enabling semantic highlighting the same way done in [this PR](https://github.com/theia-ide/theia/pull/5850).

**Comment by HighCommander4** [comment]
I checked and the arguments being passed by the semantic highlighting service to `TextEditor.deltaDecorations()` [here](https://github.com/theia-ide/theia/blob/cc51575a2c8660f13794ed9099ee14daaca982b9/packages/monaco/src/browser/monaco-semantic-highlighting-service.ts#L53) look correct to me. I think the bug is somewhere deeper.

It's possible we're running into [this bug / limitation](https://github.com/Microsoft/monaco-editor/issues/1070) in the `monaco-editor` component.

**Comment by HighCommander4** [comment]
In #5941, I have implemented a proposed workaround for Microsoft/monaco-editor#1070 in Theia. I'm not sure if it's the right approach, and even if it is the patch isn't complete, but it does fix this issue as well, confirming that it's the same underlying cause.

**Comment by kittaakos** [comment]
Closed via #5941.

**Comment by Menci** [comment]
I'm also working on adding custom semantic highlight on Monaco Editor. How did Theia add colors to the minimap?

**Comment by kittaakos** [comment]
> add colors to the minimap?

I think it's not supported.

From [here](https://github.com/microsoft/monaco-editor/issues/1070#issuecomment-422831616):

> decorations are not being drawn to the minimap, which means that the tokens that come from the semantic highlighting won't be shown in the minimap

**Comment by Menci** [comment]
Yes, I see Theia is using `deltaDecorations` too. But Theia have minimap, isn't it?
