### ISSUE TITLE
tslint rule to enforce project organization

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5873]
All code should be aligned with: https://github.com/theia-ide/theia/wiki/Code-Organization. It is critical since avoiding it increases amount of code which should be loaded and bundled. But it is very tedious to check import each time and new contributors very often miss it.

Maybe there is configurable tslin rule to check such things. Or we can write one based on regex.

cc @vince-fugnitto @marcdumais-work

**Comment by vince-fugnitto** [comment]
I think it'd be good, I don't see however a rule that can accomplish it so it'd most likely need to be a custom rule.

**Comment by akosyakov** [comment]
vscode guys seems to have such rules: https://github.com/microsoft/vscode/blob/5cad6c4879e40eb6212ea6df8d8e024958566221/tslint.json#L38-L602

Maybe we can copy and use them. Again need a CQ 🙈

**Comment by vince-fugnitto** [comment]
> Maybe we can copy and use them. Again need a CQ

I guess we will need a CQ then :see_no_evil:

**Comment by akosyakov** [comment]
@vince-fugnitto Do you think you can have a look into it? or you busy with something else?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Do you think you can have a look into it? or you busy with something else?

I'd like to resolve my existing task PR first then I can take a look into it for you :)
