### ISSUE TITLE
[outline-view] align outline tree expand/collapse behaviours with VS Code

### ISSUE THREAD

**Issue by fangnx** [eclipse-theia/theia#5876]
Currently, clicking on a outline-view tree node would:
1. Move the editor focus on the corresponding symbol
2. Expand/collapse the tree node
In many cases, a user click on the tree node to focus on the symbol. Toggling the tree expansion should be not done in the same action.

In Theia:
![theia-outline-behave](https://user-images.githubusercontent.com/25921074/62576442-e59fa580-b86a-11e9-8eb0-9f3cc3bc49ff.gif)

---

In VS Code, the two actions are effectively separated. Clicking on the expand/collapse icon toggles the node expansion without changing the focus, and clicking on the rest selects the symbol without expanding or collapsing the node. 

![theia-outline-behave-vs](https://user-images.githubusercontent.com/25921074/62576585-28fa1400-b86b-11e9-9039-72974096b5e9.gif)

I think it would be nice to align the outline-view tree behaviour with VS Code for better user experience.

**Comment by scottaxcell** [comment]
I'm interested in aligning this behavior and will investigate a generic fix for this as I'm interested in matching the same behavior in a custom widget.
