### ISSUE TITLE
"Error: The given uri is not file uri: user_storage:settings.json"

### ISSUE THREAD

**Issue by DanTup** [eclipse-theia/theia#5880]
I edited my user settings earlier, and now when I refresh the page, I see this error in the console:

![Screenshot 2019-08-07 at 1 39 18 pm](https://user-images.githubusercontent.com/1078012/62623452-c5c6bb00-b918-11e9-9939-cea140baee31.png)

**Comment by dxramax** [comment]
any way to disable it until it's solved ?

**Comment by akosyakov** [comment]
Is it reproducible against https://github.com/eclipse-theia/theia/pull/7302?

**Comment by dxramax** [comment]
I have reinstalled the OS, and the issue did not appear again, I could not be able to produce it again.

**Comment by colin-grant-work** [comment]
It's possible that the error was related to the problem fixed by [this PR](https://github.com/eclipse-theia/theia/pull/9049). Since the URI scheme has changed in the meantime and the original reporter was unable to reproduce, I'm going to close this ticket.
