### ISSUE TITLE
[navigator] add refresh command and toolbar item

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#5885]
The theia new-folder detection does not appear to be perfect - see https://github.com/eclipse/codewind/issues/67. I'd like to be able to manually refresh the Explorer from my extension.

In VS Code, I see the command `workbench.files.action.refreshFilesExplorer`. I suppose there should be an equivalent command in Theia, but perhaps there isn't yet because there is no refresh button in the Explorer view like there is in VS Code: 
![image](https://user-images.githubusercontent.com/8888438/62668744-f7f90c80-b95a-11e9-8065-ec2596758bed.png)

Currently we have to refresh the browser tab, which is not really an acceptable work around.

**Comment by akosyakov** [comment]
It is up to grab. One can add a refresh command and toolbar item first, and then add `workbench.files.action.refreshFilesExplorer` command to the plugin system which delegates to the navigator command. It could be 2 separate PRs.

**Comment by vince-fugnitto** [comment]
Closed in #5885

**Comment by akosyakov** [comment]
We need to register `workbench.files.action.refreshFilesExplore` in the plugin system which delegates to `navigator.refresh`.
