### ISSUE TITLE
Haxe language support extension not working

### ISSUE THREAD

**Issue by andyli** [eclipse-theia/theia#5938]
### Description

The [Haxe language support extension](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe) should provide code completion, but it doesn't work in gitpod.

### Reproduction Steps

My test gitpod branch can be found at https://github.com/andyli/jQueryExternForHaxe/tree/gitpod

Press F1, and select "Haxe: Select Configuration". It should show 4 selection items, which are "build.hxml", "generate.hxml", "runCi.hxml", and "test.hxml", but there is no selection menu or any other messages.

**Comment by vince-fugnitto** [comment]
Is it more a Gitpod issue? It can be filed here https://github.com/gitpod-io/gitpod

**Comment by andyli** [comment]
I thought you were the same group of people since Gitpod's [doc](https://www.gitpod.io/docs/vscode-extensions/#your-extension-doesnt-work-as-expected) point me to here. I will investigate a bit and see if theia alone works will with the Haxe extension or not.

**Comment by vince-fugnitto** [comment]
> I thought you were the same group of people since Gitpod's [doc](https://www.gitpod.io/docs/vscode-extensions/#your-extension-doesnt-work-as-expected) point me to here. I will investigate a bit and see if theia alone works will with the Haxe extension or not.

Yes, many Gitpod developers are Theia developers :)
I just wanted to confirm if it's in fact a Gitpod or Theia issue since the description mentioned Gitpod. It is good practice to check if it initially it works within Theia.

**Comment by vince-fugnitto** [comment]
I ran the application using the `haxe` extension you reference and can see errors being reported in the console. My project contains a simple hello-world haxe program.

<div align='center'>

<img width="827" alt="Screen Shot 2019-08-13 at 6 32 47 PM" src="https://user-images.githubusercontent.com/40359487/62982172-645f8a00-bdf9-11e9-9969-758da398914d.png">

</div>

**Comment by tsmaeder** [comment]
The latest API check indicates the missing call is now implemented. @andyli or @vince-fugnitto can you check against theia master?

**Comment by vince-fugnitto** [comment]
> The latest API check indicates the missing call is now implemented. @andyli or @vince-fugnitto can you check against theia master?

I don't see the error messages anymore, and the comment described in the issue (regarding selecting the configuration) looks to be resolved. I'll let @andyli confirm.

**Comment by akosyakov** [comment]
@tsmaeder @vince-fugnitto thank you for checking
@andyli please reopen it if it is still the issue
