### ISSUE TITLE
support `do not disturb` mode for notifications

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#5942]
It is a follow-up of https://github.com/theia-ide/theia/pull/5830.

As a user, i want to suppress pop up of all notifications. Instead counter should be updated in the status bar as a reminder that there are some messages. Counter should not blink or something to avoid distracting as well.

In VS Code it is not possible, so it is a proposal to implement in Theia.

cc @AlexTugarev

**Comment by AlexTugarev** [comment]
I think notifications could be even filtered by severity when it comes to show a toast, e.g. I'd still want to see errors.

**Comment by vince-fugnitto** [comment]
Would a preference be sufficient?
Something like being able to:
- hide all notifications - unless the user explicitly clicks the bell
- hide all infos
- hide all warnings
- never hide

**Comment by garethwhittaker** [comment]
I'd be interested in picking this task up.
I assume a new preference will be a suitable way to specify which notification types to mute.

**Comment by vince-fugnitto** [comment]
> I'd be interested in picking this task up.

@garethwhittaker sure!

> I assume a new preference will be a suitable way to specify which notification types to mute.

I think we can aim to have a single preference (ex: `workbench.silentNotifications`) which would affect all types of notifications. I could not find a preference in VS Code however.

It might also be interesting for at some point to have an enhancement in the form of a new command which toggles the `silentNotifications` preference (allows users to turn on/off the setting in different scenarios).

**Comment by AmeyaLokre** [comment]
@vince-fugnitto is there plan to support suppressing notifications based on levels as mentioned in your initial comment https://github.com/eclipse-theia/theia/issues/5942#issuecomment-531795301 ?

>     hide all notifications - unless the user explicitly clicks the bell
>     hide all infos
>     hide all warnings
>     never hide

**Comment by vince-fugnitto** [comment]
> Is there plan to support suppressing notifications based on levels as mentioned in your initial comment

@AmeyaLokre not that I am aware of, and I did not find a similar notification present in vscode. You can always add such a preference in your own application based on Theia if you require the use-case.
