### ISSUE TITLE
support "showOutput" flag in task config

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#5974]
### Description

In VS Code there is a `showOutput` flag we can use to toggle if task output should show up in the terminal
https://stackoverflow.com/a/38723286

In Theia we should implement the same thing to achieve the same user experiences. 

### Reproduction Steps

Run any task in Theia. The task output shows up in the terminal.

**OS and Theia version:**

Ubuntu 18.04. master branch as of Aug 16 2019. Example browser

**Comment by westbury** [comment]
This is related to https://github.com/theia-ide/theia/pull/5597 .  That PR exposes output on the frontend but does not dictate where it goes, so it can go to, for example, a progress monitor, output channel, or a problem marker generator.  Remember that Theia is extendable whereas VS Code is not, so while a toggle may be appropriate for VS Code, the ability to rebind API is more useful for Theia extenders.

**Comment by vince-fugnitto** [comment]
The `showOuput` flag has been deprecated for a while now (since 1.14 in VS Code) and was replaced by the `reveal` property. I believe we can safely close the issue as `reveal` provides even more options for end-users.

```ts
definitions.showOutputType.deprecationMessage = nls.localize(
	'JsonSchema.tasks.showOputput.deprecated',
	'The property showOutput is deprecated. Use the reveal property inside the presentation property instead. See also the 1.14 release notes.'
);
```
