### ISSUE TITLE
theia how to realize compatibility vscode

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#5977]
### Description
where is the vscode plugin entry point

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by 502647092** [comment]
@akosyakov

**Comment by akosyakov** [comment]
> where is the vscode plugin entry point

@502647092 i have not implemented Theia plugins, we usually do a VS Code extension with additional namespaces, like `sprotty`. When we use  `theia` namespace, it is troublesome for us to understand which API is implemented in VS Code as well or not.

You can have a look at https://www.theia-ide.org/doc/Authoring_Plugins.html 
It says `theiaPlugin/backend`

Maybe someone else from @theia-ide/plugin-system can help?

**Comment by vince-fugnitto** [comment]
@502647092 are you still experiencing issues?
