### ISSUE TITLE
[vscode] CodeLens not take effect

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6001]
### Description
open theia
the latest layout will restore
but CodeLens is not take effect
I need reopen file

### Reproduction Steps
![temp](https://user-images.githubusercontent.com/10203793/63416670-6ac1b780-c432-11e9-9f0e-b2546a61c7c0.gif)

- ext install humao.rest-client
- create a `test.http` file
```
GET http://baidu.com
```
- Click Send Request it's be OK
- Reload Theia
- Click Send Request nothing happed
- reopen http file
- Click Send Request it's be OK

**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 Is it still the issue?

**Comment by 502647092** [comment]
@akosyakov It looks like it works fine after refresh
