### ISSUE TITLE
When opening command palette by cmd+shift+p, the cursor is to the left of ">" sign

### ISSUE THREAD

**Issue by gennad** [eclipse-theia/theia#6011]
### Description
When opening command palette by cmd+shift+p, the cursor is to the left of ">" sign.
It should be to the right.

### Reproduction Steps
git clone latest Theia.
Follow the instructions to run Theia in a browser.
Open localhost:3000 in Safari.
Press cmd + shift + p. 
Observe that cursor is to the left of ">".

**OS and Theia version:**
Mac OS 10.14.6
Pulled from master, latest commit f46ebf4e0b01c3fe58212ca8927537aff0ddb3a0

**Comment by vince-fugnitto** [comment]
That's very odd, I only notice the bug on Safari.
