### ISSUE TITLE
[editor] preserve cursor (selection) in previously opened editor

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6016]
**Description**

The location of the cursor or selection is lost when an editor is closed.
As an enhancement, the location should be preserved so that users can easily navigate back to their previous context.

**Steps to Reproduce**
1. open a workspace in the application
1. open an editor, preferably a long file and navigate to the bottom
2. close the editor using the command `Close All Tabs`
3. re-open the closed editor using <kbd>ctrlcmd</kbd>+<kbd>p</kdb>
4. the cursor location is lost, the cursor now appears at the beginning of the file

**Additional Info**
- the cursor location is maintained in VSCode and I believe it is a nice enhancement

**Comment by akosyakov** [comment]
I was wondering generally, should not we preserve state for stateful widget between opening. We do it already for some views, maybe we should generalize it. @svenefftinge ?

**Comment by vince-fugnitto** [comment]
> I was wondering generally, should not we preserve state for stateful widget between opening. We do it already for some views, maybe we should generalize it. @svenefftinge ?

I think that'd be a great idea if possible :)
