### ISSUE TITLE
[VScode extension] Make language packs available

### ISSUE THREAD

**Issue by mouse484** [eclipse-theia/theia#6022]
### Description
Multilingualization is currently not available in Theia (Gitpod)
I tried to use the language pack (Japanese) provided as an extension of VScode, but it was not available 
I think it is important to be able to use language packs

### Reproduction Steps
Installation of extension language pack (Japanese)

**OS and Theia version:**

**Diagnostics:**

**Comment by Lzw2016** [comment]
I think it is important to be able to use language packs (Chinese (Simplified) )

**Comment by vince-fugnitto** [comment]
Thank you for the issue, at the moment localization is still not yet supported.
Closing as it is a duplicate of https://github.com/eclipse-theia/theia/issues/5000.
