### ISSUE TITLE
[debug] Doesn't always work

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#6023]
I experienced this with the java debugger.
To reproduce:
1) open this repo with gitpod: https://gitpod.io/#https://github.com/svenefftinge/spring-petclinic
2) Launch the config.

It often works but from time to time it doesn't, which means it will not respond for half a minute and then come up with an error notification, telling you that the debug type java is not available.

**Comment by akosyakov** [comment]
It's a dup of https://github.com/eclipse-theia/theia/issues/6361. The same errors in logs.

**Comment by akosyakov** [comment]
Please use `redhat.java@0.49.0` or never.
