### ISSUE TITLE
'Run Selected Text' is not working for some case

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#6027]
### Description
A new terminal is created for running selected text if you don't have active terminal at the moment,
but
creation of a new terminal is fail if you:
created a terminal manually -> closed the terminal -> try to run selected text  

### Reproduction Steps
1. Create a new terminal
2. Use 'Run Selected Text' to run some command - you can see output for the command 
3. Close the terminal
4. Try to repeat step 2.

You can see that new terminal has not created, selected command has not started.
Please see the video: https://youtu.be/FQXRB8jU8m0

**OS and Theia version:**
theia version: 566ebda6b9ede33984ff0d06044e889b2191c9d7

**Comment by elaihau** [comment]
I can no longer reproduce this one. Could you please confirm @RomanNikitenko ? Thank you !

**Comment by RomanNikitenko** [comment]
@elaihau 
you are right - I can not reproduce the bug now.
Thank you!
