### ISSUE TITLE
confused. is Theia is a platform or IDE? can I use it directly for development?

### ISSUE THREAD

**Issue by loganto** [eclipse-theia/theia#6042]
per **theia** website:

>Eclipse Theia is an extensible platform to develop multi-language Cloud & Desktop IDEs with state-of-the-art web technologies.

So my understanding is - theia is positioned a platform and not a ready-use ide...
So it'a  platform to use when building an IDE...
    
so then my question is - if I can't use it directly - did anyone already built a ready-use IDE based off theia? Could u recommend one?

**Comment by gorkem** [comment]
Take a look at Eclipse [Che,](https://github.com/eclipse/che) Che uses Theia as its IDE

**Comment by akosyakov** [comment]
Hi @loganto and thank you for the question!

In the first place, Theia is a platform to build IDEs.

Although, we distribute example docker images with vanilla Theia to use: https://github.com/theia-ide/theia-apps For js/ts development you can simply run:
```
docker run -it -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia
```

We also going to have vanilla electron distributable at some point: https://github.com/theia-ide/theia/issues/5481 For now, unfortunately, you have to build your own distributable. Here is a template: https://github.com/theia-ide/theia-apps/tree/master/theia-electron

You can also use products built on Theia, i.e. [Gitpod](www.gitpod.io), Google Cloud Shell, [ARM Mbed Studio](https://os.mbed.com/studio/) or Eclipse Che.

I'm using Gitpod on daily basis to develop and review PRs for Theia itself. You can try with: https://gitpod.io/#https://github.com/theia-ide/theia
