### ISSUE TITLE
Activation issue when vscodeintellicode and vscode-java by redhat installed together 

### ISSUE THREAD

**Issue by veredcon** [eclipse-theia/theia#6047]
### Description
Seems like starting of version 0.8.0 of theia, activation of 2 extensions like vscodeintellicode and vscode-java do not work well together.  When opening a java file, vscode-java extension should be activated - but that does not happen when vscodeintellicode also installed.

### Reproduction Steps
1. I downloaded both extensions:
https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode
https://marketplace.visualstudio.com/items?itemName=redhat.java

2. I ran theia locally as follows:
docker run --rm -it -p 3000:3000 -v <full_path_to_a_folder_contains_your_vsix>:/plugins -e THEIA_PLUGINS=local-dir:/plugins theiaide/theia-full:0.10.0-next.4d93bcff

3. Open a java file - I expect to see activation of java-vscode starts, however it does not happen. If I install only java vscode - it does being activated.

**OS and Theia version:**
Image of theia version: 0.10.0-next.4d93bcff

**Diagnostics:**

**Comment by akosyakov** [comment]
@veredcon Could you try against this PR: https://github.com/theia-ide/theia/pull/6044?

**Comment by akosyakov** [comment]
I suspect it should be addressed by https://github.com/theia-ide/theia/pull/6044/commits/b42bf5ca11b2104dfa2818a0a9bfb6ba7ef42c49 I will extract a PR for it tomorrow to verify.

**Comment by veredcon** [comment]
@akosyakov I have tried against your suggested PR but unfortunately the issue reproduces. Again when having only vscode-java extension I have no issue but when adding vscodeintellicode clicking on java file does not activates java extension.

**Comment by akosyakov** [comment]
btw @veredcon are you aware that theiaide/theia-full includes native java extension and you should not use it together with VS Code java extension?

**Comment by akosyakov** [comment]
@veredcon Could you share java project against which you test and specify which file you are trying to open and what expect to use there?

**Comment by veredcon** [comment]
We do not use the native java extension of theia, we use only the VS Code java extension. 
It happens in any java project...the steps I did to run it locally is cloning the project, checked out to your PR, yarn, added plugins folder that includes both extensions and ran theia from vscode (Launch Backend launch configuration).

**Comment by veredcon** [comment]
I have verified this against theia 1.7.0 and the issue of activation does not reproduce anymore. 
Closing this issue.
