### ISSUE TITLE
[git] add completion for '.gitignore'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6066]
**Description**

I propose to add completion for `.gitignore` files so that smart suggestions are displayed as a user types. Currently, there is no smart suggestion for the file and while it's not necessarily a problem, providing support for end-users editing a `.gitignore` file would allow the application to be more feature rich and provide a much better user experience.

_Example:_

| User Types | Suggestions |
|:---:|:---:|
| `packages/c` |  `packages/callhierarchy`, <br />`packages/console`, <br /> `packages/core`, <br />`packages/cpp`|

**Comment by akosyakov** [comment]
Have you looked is there already VS Code extension for it? We don't need to implement everything.

**Comment by vince-fugnitto** [comment]
I tried a plugin but it wasn't as feature rich as I had hoped (no suggestions or help typing).
I also noticed we don't have the following command from our `Git` extension and is present in VSCode where we can simply open a file and add it to out `.gitignore`:

https://github.com/microsoft/vscode/blob/5c40c5e9a5eb8f2b58f08c75be8cddf02c01290e/extensions/git/package.nls.json#L58

**Comment by vince-fugnitto** [comment]
I think the correct way to add additional features, especially for `.gitignore` files is to provide them through an extension. I agree that the platform does not need to provide all functionality. If we ever find the `.gitignore` plugin to be lacking we can always open pull requests on their repos to add the missing functionality.
