### ISSUE TITLE
[vscode] toolbar icons are not updated acordingly

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#6082]
### Description
For vscode maven extension there are two toolbar icons that should together immitate a toggle button. This is based on a when clause using the config.
See https://github.com/microsoft/vscode-maven/blob/19bde696fca4ec5acc06d68470a4e1d0ee515d70/package.json#L287

It works nicely in VS Code but in Theia I see both icons.

**Comment by akosyakov** [comment]
Is it sill the issue?

**Comment by vince-fugnitto** [comment]
Closing as it is no longer an issue.
