### ISSUE TITLE
Support `integratedTerminal` for debugging

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-theia/theia#6103]
Take the Python VS Code extension for instance, it's not possible to use `integratedTerminal` for launch configs. Though the Terminal opens as expected, it's not getting anything sourced, thus no debugger is attached.

**Comment by svor** [comment]
Same problem with java debug. Since v0.21.0 Java-debug VS Code extension uses `integratedTerminal` as a default type of console for debug configurations.

**Comment by tsmaeder** [comment]
As I understand it, this should not change anything in the way we run the programs, just where the output/input is redirected to.
