### ISSUE TITLE
[multi-workspace][ls] Support `workspace/didChangeWorkspaceFolders`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6108]
### Description
 

As an extension developer, I want my LS to be notified when a folder is added/removed to/from my Theia workspace. VS Code sends the `DidChangeWorkspaceFoldersParams` to the LS when the workspace has changed.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
Depends on https://github.com/theia-ide/theia/pull/5901

**Comment by tsmaeder** [comment]
Just to make sure I understand this right: in the plugin API, this works, right?

**Comment by akosyakov** [comment]
@tsmaeder Yes, it is only about native LSP support. Although it probably affects https://github.com/theia-ide/theia/blob/a9a39db21ee8d37365da72c8127ec1abb78d5248/packages/plugin/src/theia-proposed.d.ts#L22-L36. Not sure whether it is used.
