### ISSUE TITLE
[scm|git] update commit textarea placeholder to include branch name

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6114]
**Description**

Update the git commit textarea placeholder to include the branch name.

Currently the following is displayed:

<img width="331" alt="Screen Shot 2019-09-05 at 8 54 13 AM" src="https://user-images.githubusercontent.com/40359487/64343736-120a2700-cfbb-11e9-9782-ce7a9a978707.png">

While the placeholder can be updated to display the following:

<img width="333" alt="Screen Shot 2019-09-05 at 9 00 06 AM" src="https://user-images.githubusercontent.com/40359487/64344015-96f54080-cfbb-11e9-98a2-67aebc156120.png">

**Additional Info**

The feature was recently added in VSCode:
https://code.visualstudio.com/updates/v1_38#_source-control

---

**Bonus** 🥇 

Display ⌘ instead of Cmd for macOS

**Comment by xieyuanhuata** [comment]
Yes I do it
