### ISSUE TITLE
Update VSCode Icons

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6115]
**Description**

The repository [vscode-icons](https://github.com/microsoft/vscode-icons) has recently been created where we can re-use the same icons present in VSCode. Is it something we'd like to align to? If we use the outdated icons it's quite possible we will get a mismatch in our own applications when using plugins (which bring the new icons in their views).

**Comment by akosyakov** [comment]
New Monaco already using new VS Code icons, so probably it makes senes to align.

**Comment by JesterOrNot** [comment]
When would something like this come to pass?

**Comment by akosyakov** [comment]
@JesterOrNot there was not yet plans to work on it. Does anyone ask about it for Gitpod?

**Comment by JesterOrNot** [comment]
No but I think it would be pretty cool 😅

**Comment by akosyakov** [comment]
It seems that Monaco comes with icons already, ideally it would be good to use it from monaco distribution then that editor and IDE icons are aligned. It's a tricky and for the meantime just updating icon files could be enough.

**Comment by akosyakov** [comment]
After last Monaco upgrade we have codeicons in our css. So it should be a matter of going and changing css and then removing icon files. Please see for details on how to use codeicons: https://github.com/eclipse-theia/theia/issues/4835#issuecomment-607792884

We should also figure out how to deprecate old icons. They are probably used in end products.

**Comment by vince-fugnitto** [comment]
> After last Monaco upgrade we have codeicons in our css. So it should be a matter of going and changing css and then removing icon files. Please see for details on how to use codeicons: [#4835 (comment)](https://github.com/eclipse-theia/theia/issues/4835#issuecomment-607792884)
> 
> We should also figure out how to deprecate old icons. They are probably used in end products.

I tried to update an existing `font-awesome` icon into a `codicon` but it did not seem to work properly. I'm wondering if the icons are only available for monaco components (quick-open) at the moment, and some extra steps are required to use them across the application.

**Comment by akosyakov** [comment]
It would mean though that icons won't work without Monaco extension :( We could start like that and if someone comes with the issue later, we will need to provide such css classes through the core then.

**Comment by vince-fugnitto** [comment]
> It would mean though that icons won't work without Monaco extension :( We could start like that and if someone comes with the issue later, we will need to provide such css classes through the core then.

I think we can go ahead for now with these icons (since it is quite difficult not to use `monaco`), and if people experience issues we can somehow implement fallback icons: https://github.com/eclipse-theia/theia/issues/5009.
