### ISSUE TITLE
Custom Debug adapter - debugging does not work if a file is already open

### ISSUE THREAD

**Issue by svkr2k** [eclipse-theia/theia#6122]
### Description
Debugging does not start and source code line not highlighted if the file is already open in editor.

### Reproduction Steps
1. Create custom debug adapter and use it along with theia as described here: https://che.eclipse.org/how-to-add-support-for-a-new-debugger-for-che-theia-f459ea806ff

2. Add a file and add some content to it. Adding the file opens the file automatically in the editor. (the sample debugger will be able to debug any text file).

3. Start debugging => During this step, debugging does not work.

4. Close the file and open it. If debugging is started after close and reopen of a file, it works fine.
But, it should have worked fine during Step #3.

**Comment by tolusha** [comment]
I've checked and unfortunately I can't reproduce the issue.
Once I created a file and added some content I can debug it.

**Comment by tsmaeder** [comment]
Please reopen with more details if this is still a problem.
