### ISSUE TITLE
[scm] bad styling for commit message default text

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#6133]
Dark theme currently looks like this:
<img width="367" alt="Screenshot 2019-09-06 at 17 34 30" src="https://user-images.githubusercontent.com/372735/64440825-fbec8b80-d0cc-11e9-8f2f-fe8bc749e6ac.png">

**Comment by svenefftinge** [comment]
Apparently only happens in 
> Chrome Version 79.0.3906.0 (Official Build) canary (64-bit)

**Comment by JonasHelming** [comment]
I never saw this on any follow-up version. I guess it is probably not worth to fix this if it only happened in one specific version. I suggest to close this, please reopen in case you experience it again or disagree.
