### ISSUE TITLE
some icons are too big in plugin trees

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6142]
See inline actions below:
<img width="1552" alt="Screen Shot 2019-09-09 at 13 44 28" src="https://user-images.githubusercontent.com/3082655/64521776-0b104b00-d312-11e9-92a8-0b20efa756ca.png">

For comparison in VS Code: https://code.visualstudio.com/assets/docs/python/testing/test-explorer-run-scoped-tests.png

**Comment by AlexTugarev** [comment]
fixed in https://github.com/eclipse-theia/theia/pull/6342
