### ISSUE TITLE
[CI] prevent merging PRs that are failing CI

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6167]
**Description**

We should [prevent merging](https://help.github.com/en/articles/about-required-status-checks) PRs that are failing CI.
PRs should not be merged into `master` when they are breaking CI (ex: https://github.com/eclipse-theia/theia/pull/6155)

We can restrict merging PRs that fail:
- Travis (quite stable and verifies both Linux and macOS)
- AppVeyor (much more stable than in the past (covers Windows) but perhaps not mandatory).

**Comment by akosyakov** [comment]
I'm fine, if we can switch them off to merge something urgent.

**Comment by vince-fugnitto** [comment]
I think it is no longer a viable option, it would require contacting the webmaster in order to merge PRs which need to be immediate. Am I correct @marcdumais-work ?

**Comment by marcdumais-work** [comment]
> I think it is no longer a viable option, it would require contacting the webmaster in order to merge PRs which need to be immediate. Am I correct @marcdumais-work ?

Yes, I think so.
