### ISSUE TITLE
direction key can't select suggest view

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6168]
### Description
after yesterday build
direction key can't select suggest view

before build
![temp](https://user-images.githubusercontent.com/10203793/64746248-7db13e80-d53d-11e9-8e58-9308d9ff00e9.gif)

after build
![temp](https://user-images.githubusercontent.com/10203793/64746297-96b9ef80-d53d-11e9-8bc6-bdfc9aaa3b61.gif)

@akosyakov 

### Reproduction Steps

**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 Could you provide a repo where i can reproduce it? It works in theia repo for me. Also browser version and OS?
