### ISSUE TITLE
First argument should be the file to open, not root-dir

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#617]
Since #612 the first argument in theia cli is the root-dir.

This breaks workflows where Theia could be used as an $EDITOR like using it for git commit editing for example from the command line.

I think the 1st argument should be a file to open.

Note vscode, atom, emacs all work this way.

**Comment by hexa00** [comment]
@svenefftinge ^^

**Comment by svenefftinge** [comment]
If it points to a file it should open it, if it's a dir it should use the current behavior.

**Comment by hexa00** [comment]
Also we could make it so that it supports opening a file at location with file:line:col like atom does.

**Comment by epatpol** [comment]
I think that doesn't make sense anymore as the backend is kinda stateless now? @svenefftinge

**Comment by JonasHelming** [comment]
@hexa00 Can we close this or is it still relevant?

**Comment by vince-fugnitto** [comment]
> @hexa00 Can we close this or is it still relevant?

@JonasHelming the framework does not support yet opening a file from the `cli` (only a workspace) so I'd be inclined to close it for the time being and we can open a newer issue if we want to support that use-case.
