### ISSUE TITLE
Hidden file in the file navigator not updating glob regex expression

### ISSUE THREAD

**Issue by vinayb21** [eclipse-theia/theia#6171]
### Description
https://github.com/eclipse-theia/theia/blob/98f12a9fcc3a43c2b5d224e186f871e66a1e11b7/packages/filesystem/src/browser/filesystem-preferences.ts#L41-L46
When a new glob pattern is added to the above file, the value is not updated.

### Reproduction Steps
**Step 1:** Create a new file in your current workspace say 'hidden_file.txt'
**Step 2:** Add a new glob pattern: '**/hidden_file.txt' in https://github.com/eclipse-theia/theia/blob/98f12a9fcc3a43c2b5d224e186f871e66a1e11b7/packages/filesystem/src/browser/filesystem-preferences.ts#L41-L46
**Step 3:** The changes are not reflected in Theia
**Step 4:** `Open preferences` in Theia and add the glob pattern there (it works in this way but not by the way mentioned in Step 2)

**OS and Theia version:**
OS: MacOS 10.13.6
Theia: v0.11.0

**Diagnostics:** 
None

**Comment by vince-fugnitto** [comment]
@vinayb21 were you able to resolve your issue?

**Comment by vinayb21** [comment]
@vince-fugnitto 
Yes. It worked! How to write an extension to override the preferences of Theia?
Also would it be possible to also hide the files to be displayed in the terminal.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto
> Yes. It worked! How to write an extension to override the preferences of Theia?
> Also would it be possible to also hide the files to be displayed in the terminal.

Sorry I just saw this now, please open new issues to resolve your questions so they are easier to track :) Closing as the original issue has been resolved.
