### ISSUE TITLE
Run as regular user

### ISSUE THREAD

**Issue by MrMoronIV** [eclipse-theia/theia#6178]
On CentOS 7: I installed Theia using the root user and would like to allow other users to start a theia server as well, the main reason is that I want to limit the power of the user that runs the theia process, for example in the terminal, any advice on this?

For what I tried using a no-root is "yarn not found" in the $PATH variable, although it exists perfectly fine, `which yarn` gives nothing, although that works when logged in as root.

Is there a common approach to this problem I am missing somehow?

**Comment by sr229** [comment]
I think folks at Red Hat got this to work, we just need to set the UID dynamically and in user mode so it works.

**Comment by vince-fugnitto** [comment]
> I think folks at Red Hat got this to work, we just need to set the UID dynamically and in user mode so it works.

Closing since I believe the question has been successfully answered and there has not been much activity lately. Please re-open the issue if the problem persists.
