### ISSUE TITLE
Few documentation links doesnt seem to work

### ISSUE THREAD

**Issue by svkr2k** [eclipse-theia/theia#6182]
### Description
Some theia documentation links are broken

### Reproduction Steps
The following link is broken:
https://theia-ide.github.io/theia/docs/next/modules/plugin.__theia_plugin_-1.html

not sure of it is because of repo move (https://github.com/eclipse-theia/theia/pull/6175)? I will be happy if this is fixed today... I badly need it during the weekend :-(
Thanks in advance for your help.

**Comment by marcdumais-work** [comment]
Could you point-out where this link is defined?

**Comment by vince-fugnitto** [comment]
I've opened a PR fixing the links on `theia-website`: https://github.com/theia-ide/theia-website/pull/57

**Comment by svkr2k** [comment]
Thank you very much !

**Comment by vince-fugnitto** [comment]
Closing since the links have been recently updated :) https://github.com/theia-ide/theia-website/pull/58
