### ISSUE TITLE
replace java and debug native with vscode extensions

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6183]
Motivated by https://github.com/eclipse-theia/theia/pull/6113#issuecomment-528782824

- theia-apps should be updated: https://github.com/theia-ide/theia-apps/issues/239
- java, java-debug, nodes-debug extensions should be removed and replaced by auto-downloading corresponding vscode extensions into `plugins` folder for testing purporses with example apps
- a record in CHANGELOG should be added to explain for end products:
  - how to switch to use vscode extensions
  - how to use yarn `resolutions` to keep using old native extensions

cc @marcdumais-work

**Comment by vince-fugnitto** [comment]
Do we want to clean up before this week's release?

**Comment by akosyakov** [comment]
@vince-fugnitto i don't think anyone on our side has time for, if you can go ahead, if not we can do it later

**Comment by tsmaeder** [comment]
Make sure to now download from the vscode marketplace. It's a no-no.

**Comment by marcdumais-work** [comment]
@tsmaeder small typo I think: "now" -> "not", but the idea is correct. We can use the links currently in place in the theia extensions, that pull from GitHub releases:

https://github.com/eclipse-theia/theia/blob/master/packages/debug-nodejs/package.json#L52-L53
https://github.com/eclipse-theia/theia/blob/master/packages/java-debug/package.json#L53

**Comment by vince-fugnitto** [comment]
Closed by #6933
