### ISSUE TITLE
VSCode-YAML only works if you install it before opening up a yaml file

### ISSUE THREAD

**Issue by JPinkney** [eclipse-theia/theia#6185]
### Description
 

Currently if you open a yaml file before you install vscode-yaml then install vscode-yaml after that file is open for some reason none of the features work. There aren't any errors in console and re-opening the file doesn't register the features either.

I was able to reproduce this on latest version of os x and fedora 30.

### Reproduction Steps

Create a yaml file in a project and then open it. Then run `deploy by plugin id` then `ext install redhat.vscode-yaml`. Then none of the language features will be working.

If you install the plugin before you open a yaml file everything works as expected.

Heres a video of whats going on if it makes it clearer: https://www.youtube.com/watch?v=aTrnFD9zW3k

**OS and Theia version:**
I've tried on os x and fedora 30

**Diagnostics:**

**Comment by JPinkney** [comment]
57be198635ced9325aaad0ada885b60e02154128 is the first commit where it doesn't work for the latest vscode-yaml version

**Comment by vince-fugnitto** [comment]
I verified and it works correctly :)
I believe the issue can be closed, please re-open the issue if its not the case.
