### ISSUE TITLE
Created file/folder should be selected

### ISSUE THREAD

**Issue by shahar-h** [eclipse-theia/theia#6190]
### Description
When creating a new file or folder, it is not selected in file tree.

### Reproduction Steps
- Create a new file or folder.
- The created file/folder is not selected in file tree. instead the current folder stays selected.

**Comment by akosyakov** [comment]
@shahar-h feel free to have a look into it!

**Comment by tsmaeder** [comment]
Seems to work for files, but not folders.

**Comment by marcdumais-work** [comment]
@Anasshahidd21 do you want to have a look?
