### ISSUE TITLE
`Add Configuration` of debug panel shows wrong suggestions when a new websocket is created

### ISSUE THREAD

**Issue by tom-shan** [eclipse-theia/theia#6200]
### Description
After the websocket connection is recreated  for network problems, clicking `Add Configuration` of debug panel will only show some useless suggestions. 
This problem appears frequently because of my bad network and is very annoying.

**right suggestions**
![image](https://user-images.githubusercontent.com/7686800/65037877-3a156500-d981-11e9-8fe5-12fd1ce4fcd7.png)

**wrong suggestions after a new websocket is created**
![image](https://user-images.githubusercontent.com/7686800/65038034-95dfee00-d981-11e9-9005-0bac40d879ff.png)

### Reproduction Steps

This issue may be difficult to reproduce in reliable networks, so I use `iptables` to cut the network connection between the server and client as follows:
```
#/bin/bash
iptables -I INPUT -p tcp -s {client ip} --dport {connection port} -j DROP
sleep 20
iptables -D INPUT 1
```
The `sleep time` should be long enough, otherwise the old websocket connection will be reused and the problem will not be reproduced.
**OS and Theia version:**
os: centos 7
theia commit id: https://github.com/eclipse-theia/theia/commit/1808d782a947a52fbeeb900bb83b190cd578420c
**Diagnostics:**

**Comment by akosyakov** [comment]
@tom-shan Do you use VS Code extensions for node.js debugging?

**Comment by tom-shan** [comment]
> @tom-shan Do you use VS Code extensions for node.js debugging?

No, I did not use any vscode extension.

**Comment by akosyakov** [comment]
It's a regression since restart skips now if a server is not running, but it does not play nicely with reconnection. I will do a PR promptly. cc @AlexTugarev
