### ISSUE TITLE
preference defined in a more specific scope

### ISSUE THREAD

**Issue by acodercc** [eclipse-theia/theia#6202]
### Description

packages/core-browser/src/preferences/preference-service.ts
preference defined in a more specific scope

why break, not continue? 

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@acodercc I don't quite understand your issue/question, can you elaborate?

**Comment by acodercc** [comment]
![image](https://user-images.githubusercontent.com/8233657/65101735-8c936780-d9fb-11e9-9ffa-82dcafc0e53f.png)
packages/core-browser/src/preferences/preference-service.ts   line 190

**Comment by akosyakov** [comment]
@elaihau do you remember why?

**Comment by elaihau** [comment]
as explained in the comment (line 190 in your screenshot), the preference is defined in a more specific scope, so we don't accept the change. 

Take editor.fontsize for example: if you make a change in the user preference (scope = 1) and the same preference is already defined in your workspaceRoot/.theia/setting.json (scope = 2), there is no need to accept the change, as whatever you changed in user preference (in scope 1) would be overridden in scope 2.

**Comment by acodercc** [comment]
i understand , thanks for your answer
