### ISSUE TITLE
cpp build task does not work

### ISSUE THREAD

**Issue by simark** [eclipse-theia/theia#6204]
### Description
I have this in my workspace preferences:

```
{
   "cpp.buildConfigurations": [
      {
         "name": "/home/smarchi/build/babeltrace",
         "directory": "/home/smarchi/build/babeltrace",
         "commands": {
             "build": "make"
         }
      }
   ]
}
```

This generates a task in the task runner:

![bug](https://user-images.githubusercontent.com/1758287/65059625-55ae4a80-d944-11e9-9f72-e884f0ef0d6f.png)

First, notice the `undefined`, I don't think it's intended for it to be there.  Then, when I try to run it, nothing happens and I get this in the console:

```
task ERROR Can't get task launch configuration for label: C/C++ Build - /home/smarchi/build/babeltrace
```
I am at the following commit:

```
commit 1808d782a947a52fbeeb900bb83b190cd578420c (HEAD -> master, origin/master, origin/HEAD)
Author: Miro Spönemann <miro.spoenemann@typefox.io>
Date:   Fri Sep 13 08:00:07 2019 +0000
```

**Comment by elaihau** [comment]
I made this change https://github.com/elaihau/theia/commit/d080d6a4a4bd4064686d11d00a7c8c5380d17634 which fixed the display issue (i.e., `undefined: C/C++` in task label). Also the `Can't get task launch configuration for label: C/C++ Build ` error that Simon mentioned above was gone. 

Instead I was getting this error
```
task INFO Created new task, id: 4, process id: 13, OS PID: 15131, context: file:///home/elaihau/dev/test-dir
terminal ERROR Couldn't attach - can't find terminal with id: 13 
root ERROR Couldn't resize terminal -1, because it doesn't exist.
terminal ERROR Error attaching to terminal id 13, the terminal is most likely gone. Starting up a new terminal instead.
```

I know this looks like the problem of "the command finishes (too quickly) before it gets attached to the terminal", but my task was defined like this in the pref:

```
   "cpp.buildConfigurations": [{
     "name": "Simon task runs",
     "directory": "/home/elaihau/dev",
     "commands": {
       "build": "bash -c 'sleep 5 && ls'"
     }
   }]
```

"sleep 5" should be more than enough ... do you have any ideas of what could go wrong ? @vince-fugnitto @marechal-p

**Comment by simark** [comment]
I don't really know, but I just wanted to mention that you could just use:

    "build": "sleep 5 && ls"

That command is already interpreted by a shell.

**Comment by elaihau** [comment]
> I don't really know, but I just wanted to mention that you could just use:
> 
> ```
> "build": "sleep 5 && ls"
> ```
> 
> That command is already interpreted by a shell.

i got exactly the same error if i use `sleep 5 && ls`

i used `bash -c` because i wasn't sure if the error was caused by the command not interpreted properly :)
