### ISSUE TITLE
safari support

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#6211]
Editor is not working on Mac Safari browser.
I have created a docker machine having theia editor with my custom extensions.
When I see it on Mac's safari then pre-loader never goes away and when I see on console 
I can see lot of errors.
the main error is:

Root error
"could not start contribution"

However this works very well on Windows Chrome and Firefox

**Comment by vince-fugnitto** [comment]
> I have created a docker machine having theia editor with my custom extensions.

@dhananjayharel does it work without your custom extensions?

**Comment by dhananjayharel** [comment]
No not working without extensions too.
This happens only for Safari 10.1 (Sierra OS) and below versions.
With and without my custom extensions.

However 
11.2 (High Sierra) works ! 
12.1 (Mojave)  works !
with and without my extensions.

**Comment by akosyakov** [comment]
@dhananjayharel feel free to investigate what is wrong and propose a PR. So far we were only testing with Chrome and Firefox.

**Comment by dhananjayharel** [comment]
In my initial observation I found that the Editor does not work with the browsers who dont have [Web Assembly Support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module)(WASM) .
First up all I just want to ask that is Theia is supposed to work on browsers having no web assembly module?

**Comment by akosyakov** [comment]
Everything should work except code coloring.

**Comment by msujew** [comment]
WASM support was included in [release 11](https://caniuse.com/wasm) of Safari. Now, two years later, this probably isn't an issue anymore for Safari users.

I'll close this. @dhananjayharel please comment if the issue still persists.
