### ISSUE TITLE
Remote plugins

### ISSUE THREAD

**Issue by fgreinacher** [eclipse-theia/theia#6215]
Hey 👋 

is it currently supported to connect a Theia instance to one or more plugins running on remote hosts?

Use case: I want to provide some features in sidecar containers for better scalability and stricter isolation.

If there is no built-in mechanism could you give me a hint on a good place to hook into?

Thanks 🙏

**Comment by akosyakov** [comment]
@eclipse-theia/plugin-system Could someone help?

**Comment by benoitf** [comment]
Hello @fgreinacher 

FYI Eclipse Che which is provided on top of Eclipse Theia and Container ready is providing this feature.

So it means, each VS Code extension can run its own container and specific requirements.

https://www.eclipse.org/che/docs/che-7/using-a-visual-studio-code-extension-in-che/#choosing-the-sidecar-image_using-a-visual-studio-code-extension-in-che

**Comment by svenefftinge** [comment]
Please note, that this approach breaks the assumption that all vscode extensions run in the same process and can exchange objects (see [VS Code API / extensions](https://vscode.readthedocs.io/en/stable/extensionAPI/vscode-api/#extensions))

**Comment by fgreinacher** [comment]
Thanks for the hints! 

The Che approach sounds quite similar to what I’m looking for - is there some code to look at (Theia or Che)?

**Comment by benoitf** [comment]
@fgreinacher https://github.com/eclipse/che-theia ? (custom Eclipse Theia for Eclipse Che)

**Comment by tsmaeder** [comment]
> Please note, that this approach breaks the assumption that all vscode extensions run in the same process and can exchange objects (see [VS Code API / extensions](https://vscode.readthedocs.io/en/stable/extensionAPI/vscode-api/#extensions))

Maybe it would be possible to weigh in with the VS Code folks to restrict the form of API to something that can easily be called remotely. And yes, I know that many plugins still assume they're running on the same machine (I should know :man_facepalming:)

**Comment by fgreinacher** [comment]
Thanks, I’ll have in look in the Che repo!
