### ISSUE TITLE
[terminal] add an option to prevent the terminal right click browser menu

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6216]
### Description
![image](https://user-images.githubusercontent.com/10203793/65209528-00e90c00-dacb-11e9-9ce7-66dfac0eb0af.png)

### Reproduction Steps

**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
Or we can add a terminal context menu and open it. If it is empty nothing should happen, but extenders can add menu items.

**Comment by msujew** [comment]
Theia now has a dedicated context menu for the terminal widget:
![image](https://github.com/eclipse-theia/theia/assets/4377073/507c814f-10bd-4b03-8b25-a124971b9fe2)
