### ISSUE TITLE
[vscode][webview] can't copy content from webview use Ctrl + C

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6217]
### Reproduction Steps

- ext install humao.rest-client
- create a `test.http` file
```
GET http://baidu.com
```
- Click Send Request
- select response at webview
- Copy use hotkey `Ctrl + C`
- nothing happend

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
We should check it for Safari and Chrome.

**Comment by vince-fugnitto** [comment]
> We should check it for Chrome and Firefox.

@akosyakov I tested both Chrome and Firefox.
Oddly enough Firefox worked correctly while Chrome could not copy the contents correctly.

**Comment by a1994846931931** [comment]
@vince-fugnitto I could also reproduce it on Firefox. The version is 68.0.1 (64-bit).

**Comment by akosyakov** [comment]
I cannot reproduce it in https://github.com/eclipse-theia/theia/pull/6465 It works for Chrome and Firefox. @vince-fugnitto @502647092 Could you check as well?

**Comment by vince-fugnitto** [comment]
> I cannot reproduce it in #6465 It works for Chrome and Firefox. @vince-fugnitto @502647092 Could you check as well?

I confirm it works correctly with #6465

**Comment by 502647092** [comment]
@akosyakov also can't use hot key copy
![temp](https://user-images.githubusercontent.com/10203793/69470893-e554f700-0dd4-11ea-9748-8d1901976658.gif)

**Comment by akosyakov** [comment]
> I look latest commit ci build failed , maybe my auto build image is not latest
after ci build success I will test again

Yes, npm.js had an incident on Friday, `next` version with new webviews support has not been published yet. Please reopen if you will be able to reproduce after the build is successful.

**Comment by 502647092** [comment]
@akosyakov 
also can't copy use hot key
and webview menu can't open
but 
![image](https://user-images.githubusercontent.com/10203793/69515638-2b9f8700-0f8a-11ea-8e33-1ebabe9ff896.png)
button works fine

**Comment by akosyakov** [comment]
I'm wonder what else could be different between yours and my setup.

**Comment by akosyakov** [comment]
I've tested again and it works. My setup:
- Chrome: Version 78.0.3904.108 (Official Build) (64-bit)
- Mac: High Sierra 10.13.5 (17F77)

**Comment by 502647092** [comment]
@akosyakov @marcdumais-work 
I test latest theia version `1.2.0-next.f7cecf20`
it's also can't copy from webview use `Ctrl + C`
and webview can't use right mouse key
![github](https://user-images.githubusercontent.com/10203793/82859618-d39e0900-9f49-11ea-8809-9b5d0a71346b.gif)

**Comment by akosyakov** [comment]
> it's also can't copy from webview use Ctrl + C

I still cannot reproduce. Which browser, version, OS? Do you have any errors in browser or backend logs while trying to copy?

> and webview can't use right mouse key

It is the same in VS Code. Not sure what we can do about it.

**Comment by zhaomenghuan** [comment]
I use electron WebView tag in theia widget，can't copy content from webview use use ⌘ + C，same as paste.
