### ISSUE TITLE
upgrade to Monaco 0.18.1

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6223]
In order to solve scrolling issues on Firefox: https://github.com/eclipse-theia/theia/pull/5901#issuecomment-533146298

First we have to do: https://github.com/TypeFox/monaco-languageclient/issues/176

cc @danidoedel @marechal-p You are welcomed to look into it!

**Comment by akosyakov** [comment]
@svenefftinge or should I do it once more?

**Comment by BroKun** [comment]
@akosyakov The latest version of @typefox/monaco-editor-core 0.18.0-next.1 has problems with nls related files. The configuration files for all national languages ​​are in English. Please check it before the next release.

**Comment by akosyakov** [comment]
@BroKun thanks for the notice! Have you checked whether it is an issue with https://www.npmjs.com/package/monaco-editor-core as well? It would be good to open an issue in the upstream then.

**Comment by BroKun** [comment]
@akosyakov Their recent release of 0.18.0 and 0.18.1 are fine. I don't know what happened here, so I am looking for your help.
