### ISSUE TITLE
plugin system does not scale over JSON-RPC

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6228]
With many plugins, a lot of metadata gets send to the frontend and then back to the server (plugin host process) on each deployment. It happens in big chunks of plugins leading to massive ws messages which deprive all other ws channels from possibility to communicate.

Other ideas? cc @eclipse-theia/plugin-system @svenefftinge @AlexTugarev 

In order to reproduce install about 50 vscode extensions:
- install all vscode built-int language extensions
- install different language extensions
- install debug extensions for different runtimes

**Comment by akosyakov** [comment]
We need to reproduce it locally first, maybe it is caused by https://github.com/eclipse-theia/theia/issues/6230

**Comment by akosyakov** [comment]
I was able to measure it in Gitpod with 54 extensions. 
<img width="1487" alt="Screen Shot 2019-09-20 at 14 10 28" src="https://user-images.githubusercontent.com/3082655/65314844-81356d00-dbb0-11e9-8039-e82775c48989.png">

WS gets blocked for 24s, see 14:07:00 -> 14:07:24, to fetch metadata, after that second deployment happens blocking again for 24s, and the whole metadata are send to the plugin host eventually blocking for another 24s.

**Comment by akosyakov** [comment]
We should think how to tackle activation events: since a plugin will be initialized one by one, it could happen that dependent tries to activate first and will fail. It was an issue before but with such change it will be very apparent. So activation of a plugin should also try to activate again dependent plugins.

**Comment by akosyakov** [comment]
I don't think sending one by one solve the issue, it moves the problem to another place: on the slow connection loading plugin will take very long time. 50 extension is around 5.5 mb of data, on the network as at EclipseCon it is around half an hour of waiting when many people try to pull it.

I suggest we do differently:
- (1) never send plugin metadata via web sockets
  - not even a change to block
- (2) add an http endpoint which servers dynamically gzipped metadata for given set of plugins
  - very low size of transferred data, by my measurement gzipping bundle.js brings 9Mb to 1Mb, for 5.5Mb then it is around 0.5Mb if not less since very repetitive nature of contributions
  - fast, since only one request is required to fetch everything and no interruptions by other ws channels
- (3) never send plugin metadata back to server, instead we ask the plugin host process to fetch metadata directly from forked Theia backend for given set of plugins via IPC
  - fast, since no need to transfer metadata over new, only between local processes
- (4) for frontend plugins, we ask the worker to fetch metadata from the main browser process which were loaded at (2)

@svenefftinge @eclipse-theia/plugin-system sounds good? any concerns to take care during implementation?

**Comment by svenefftinge** [comment]
Sounds good. Can we do this in smaller PRs. I.e. at least do the gzip thing first and separated?
the other changes might have more effect and take longer and I can imagine that zipping might already relief a lot of the pressure.

**Comment by akosyakov** [comment]
> at least do the gzip thing first and separated?

It still will push unzipped metadata back from the frontend to the plugin host process blocking web socket or delaying plugin activation.

**Comment by akosyakov** [comment]
Another kind of very expensive messages are schema attributes for debug contributions:
<img width="1487" alt="Screen Shot 2019-09-22 at 12 16 03" src="https://user-images.githubusercontent.com/3082655/65383733-05176280-dd33-11e9-9599-4fd5193b5dba.png">

For some extensions is about 5Mb and blocks for 10s as you can see on the screenshot.

**Comment by benoitf** [comment]
as commented in the PR, metadata shouldn't be sent to the clients. All logic can be server-side, only orders need to be client-side (like adding a menu, a command, etc).
So changing the communication layer is not the way to go

**Comment by akosyakov** [comment]
@benoitf the most heavy part of metadata are static contributions, how it can be registered without sending? We can remove raw package to avoid duplication. Not sure whether frontend plugins need it. Backend plugins can recover it from the disk.

**Comment by benoitf** [comment]
So yest, I think the model is too heavy now, at first it was a couple of metata like the displayname and something, and at some point there was the full package.json content, etc.

Do you have try first to have permessage-deflate enabled on websockets as well ?

More lazy loading could be done.
I could argue that we don't need to register 100 languages if you edit only 10 of them in your session 
The same for the debugger if you don't try to open a debug session for a given type.

Also editor model should be server side instead of client side as well to limit the events.

**Comment by akosyakov** [comment]
> So yes, I think the model is too heavy now, at first it was a couple of metata like the displayname and something, and at some point there was the full package.json content, etc.

So would it be fine to remove raw model from package.json? We can read it again in the plugin host, from the plugin web worker [vscode.Extension.packageJSON](https://github.com/microsoft/vscode/blob/fe5315badcaa9e326d5e5737a290ee7b299903c5/src/vs/vscode.d.ts#L4764) won't work anymore.

> Do you have try first to have permessage-deflate enabled on websockets as well ?

I will try. What is the issue with serving big content in compressed way outside of web socket? I agree though that we should trim the plugin metadata to transfer even less data. It would help in any case, but it won't solve the issue, since we have to register all static contributions.

> More lazy loading could be done.
I could argue that we don't need to register 100 languages if you edit only 10 of them in your session. The same for the debugger if you don't try to open a debug session for a given type.

How could it be done without harming UX? Contributions from package.json have to be registered to fire proper language and debug activation events, provide content assist in launch.json and so on. Not sure how we can decide for which extensions debug snippets should be available in launch.json or make sure that a language highlighting is there when a user opens a file.

> Also editor model should be server side instead of client side as well to limit the events.

Sorry, did not get how it is related to metadata. Amount of events is not the issue if there are of reasonable size.

**Comment by benoitf** [comment]
about : 

> vscode.Extension.packageJSON won't work anymore.

well I'm fine by not having package.json for webworkers or only if required on demand. 99% of cases are with server side plug-ins/VS Code extensions. For VS Code extensions, as you said we only need it on the server side, not from the browser side.

> What is the issue with serving big content in compressed way outside of web socket?

it's yet another custom providing layer and it's not fixing a root problem of avoiding to send tons of stuff.

> Not sure how we can decide for which extensions debug snippets should be available in launch.json or make sure that a language highlighting is there when a user opens a file.

well if there is no `.java` file in the workspace root, probably I won't need `.java` language at all.
And BTW activation of the plug-in is already triggered by events like `on*.java`, `on:pom.xml` for vscode-java, etc.

>> Also editor model should be server side instead of client side as well to limit the events.

> Sorry, did not get how it is related to metadata. Amount of events is not the issue if there are of reasonable size.

It's to limit the trafic between client side and server side. (but let's move out from this discussion)

**Comment by akosyakov** [comment]
> well I'm fine by not having package.json for webworkers or only if required on demand. 99% of cases are with server side plug-ins/VS Code extensions. For VS Code extensions, as you said we only need it on the server side, not from the browser side.

ok, let's remove it for now and see whether anyone comes up with an issue? Since it's sync API, it would be a bit tricky. Maybe for frontend plugins we can define async version?
