### ISSUE TITLE
Differentiate serializable JSON-object interfaces from interfaces

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#623]
While discussing #610 

@akosyakov had this remark:

>The topic of distinguishing real interfaces from JSON-object interfaces troubles me since improper usage, like implementing JSON-object interfaces or using not serializable types as URI, will lead to troubles. Maybe we could have a rule that real interfaces (to be implemented) should start with I if it is not then it is JSON-object (should not be implemented, only instantiated). Then it should be enforced with some tslint rule

**Comment by akosyakov** [comment]
> Maybe we could have a rule that real interfaces (to be implemented) should start with I 

It will break a lot of existing code without a reason.

> if it is not then it is JSON-object (should not be implemented, only instantiated). Then it should be enforced with some tslint rule

We could use other means as another name prefix/suffix or a custom decorator to enforce it.

**Comment by vince-fugnitto** [comment]
The following is now covered in our coding guidelines:
- https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines#interfacessymbols

Related discussion:
- https://github.com/eclipse-theia/theia/issues/624
