### ISSUE TITLE
[debug] Unstable behaviour with breakpoint context menu

### ISSUE THREAD

**Issue by thegecko** [eclipse-theia/theia#6237]
### Description

More often than not, the context menu in code files acts in an unpredictable manner when managing breakpoints.
It's also different depending whether the file is in preview mode or fully opened for editing.

Observations:

- Setting and removing breakpoints using the mouse works as expected

- When setting a breakpoint via the context menu, the breakpoint either doesn't appear (preview mode) or appears on a different line (open mode).

- Removing a breakpoint (created with the mouse) doesn't work using the context menu. In preview mode, the option doesn't appear in the context menu as if the breakpoint isn't there. In open mode, it doesn't remove the breakpoint.

There may be other weirdness, but I think those are the main issues.

### Reproduction Steps

File open in preview mode (single-click on file tree):

![preview](https://user-images.githubusercontent.com/61341/65324985-9953bf00-dba5-11e9-986c-015402ce937c.gif)

File open in open mode (double-click on file tree):

![open](https://user-images.githubusercontent.com/61341/65324969-8f31c080-dba5-11e9-9962-2b61f642a7a7.gif)

**OS and Theia version:**
OS: MacOS 10.14.5
Theia: 0.10.0, master (24f77b) - electron flavour

cc @eclipse-theia/debug-extension

**Comment by akosyakov** [comment]
Is it the same in https://github.com/eclipse-theia/theia/pull/5774? Breakpoints were refactored there a bit.

**Comment by thegecko** [comment]
I'll check it out. Looking at that PR was next on my todo list actually :)

**Comment by thegecko** [comment]
Unfortunately these issues are still apparent in #5774 :(

**Comment by thegecko** [comment]
I've spent a little time delving into this issue, concentrating on the odd behaviour of breakpoints when a file is in preview mode.

The issue occurs because a [model is expected](https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/editor/debug-editor-service.ts#L106) by the breakpoint functionality in order to correctly [show the right context menu items](https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/debug-frontend-application-contribution.ts#L768).

The model doesn't exist in preview mode, because the preview window is an instanceof `EditorPreviewWidget` and not `EditorWidget`, therefore the [current editor is not being updated](https://github.com/eclipse-theia/theia/blob/master/packages/editor/src/browser/editor-manager.ts#L93) when the file is opened in preview and neither is the model.

I see two options for fixing this:

- Remove the ability to edit breakpoints in previewed files. I think this is counter-intuitive and doesn't match VS Code functionality.

- Change Theia so preview windows also update the editor model. If this is done using the existing `updateCurrentEditor()` functionality, care would need to be taken as it could have knock on effects (e.g. turning on the ability to save previewed files, etc.)

Thoughts @akosyakov @tolusha ?

**Comment by akosyakov** [comment]
> Remove the ability to edit breakpoints in previewed files. I think this is counter-intuitive and doesn't match VS Code functionality.

👍 

> Change Theia so preview windows also update the editor model. If this is done using the existing updateCurrentEditor() functionality, care would need to be taken as it could have knock on effects (e.g. turning on the ability to save previewed files, etc.)

It is not possible, since the editor preview extension is optional, i.e. the editor extension and other extensions cannot depend on it, only another way around. But we can check if a widget is not an editor widget, then find first child which is an editor widget, something like here: https://github.com/eclipse-theia/theia/blob/f255f5a8cb22010aacb8196c8a8f248e111e9945/packages/monaco/src/browser/monaco-editor-service.ts#L70-L86

**Comment by thegecko** [comment]
> Maybe there is a bug in the shell focus tracking

Nearly there, the issue is due to the preview widget not receiving focus and therefore never being set as the active or current editor.
I think the context-menu event needs to set this focus before trying to access the current editor model.
