### ISSUE TITLE
[preferences] some monaco preference descriptions are 'undefined'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6250]
**Description**

There is a number of monaco editor preferences which have `undefined` descriptions.
This may be the result of the recent monaco update. 
From testing, it looks to only be a cosmetic bug.

_Example:_
<div align='left'>

<img width="573" alt="Screen Shot 2019-09-23 at 7 12 15 PM" src="https://user-images.githubusercontent.com/40359487/65469693-4f353c80-de36-11e9-9549-fe36d6216036.png">

</div>

**Comment by vince-fugnitto** [comment]
@akosyakov 
Is there a reason we use `markdownDescription` instead of `description` for certain preferences?
https://github.com/eclipse-theia/theia/blob/8196e9dcf9c8de8ea0910efeb5334a974f426966/packages/editor/src/browser/editor-preferences.ts#L279-L283

I assume the fix is either to add `descriptions` or enhance the preferences-tree widget to check if a `markdownDescription` is present and fallback to the regular `description` if it isn't.

**Comment by akosyakov** [comment]
Oh, I hoped to avoid changing this code manually, since we had to copy each time from Monaco. But it is certainly bad.

Ideally, we should handle `markdownDescription` properly, i.e. render it as markdown. But for using it if  `description` is not present would be enough.
