### ISSUE TITLE
Make the plugin APIs extendable through extensions

### ISSUE THREAD

**Issue by svkr2k** [eclipse-theia/theia#6257]
### Description
Theia extensions should be able to introduce new APIs for plugins. Can this capability be added?

### Reproduction Steps
Currently, new plugin APIs needs to be defined/declared in both theia.d.ts & plugin-context.ts under @theia/plugin in order to add more APIs that plugins can use.

An extension cant define/declare those new plugin APIs (or extend the current APIs) without modifying theia source code.

Can this capability be added, so that any extension should be able to provide new plugin APIs (in addition to the current plugin APIs)?

**Comment by benoitf** [comment]
extensions can provide new APIs, it's just not under `@theia/plugin` scope

BTW it sounds logical as `@theia/plugin` API is theia API, so if you use theia API, you expect to have this API working on all theia instances.
But you can introduce `@svkr2k/plugin` scope for example

you may give a look on Eclipse Che API on top of theia  (providing `@eclipse-che/plugin` API )
https://github.com/eclipse/che-theia/tree/master/extensions/eclipse-che-theia-plugin-ext

**Comment by svkr2k** [comment]
Thank you, @benoitf .
I have tried with the following project: https://github.com/cherxp/my-theia

But, still, I'm unable to make it work.
I get the following error when I try to use the new api in a plugin:
`root ERROR [hosted-plugin: 12975] { Error: Cannot find module '@theia/plugin-ext/src/common/rpc-protocol'`
`at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15) at Function.Module._load (internal/modules/cjs/loader.js:508:25) at Module.require (internal/modules/cjs/loader.js:637:17)`
`at require (internal/modules/cjs/helpers.js:22:18) `
`at Object.<anonymous> (/home/xpress1/Xpress/theia/packages/test-service-ext/lib/node/testservice-api-node-provider.js:19:22) `
`at Module._compile (internal/modules/cjs/loader.js:701:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) `
`at Module.load (internal/modules/cjs/loader.js:600:32) `
`at tryModuleLoad (internal/modules/cjs/loader.js:539:12) `
`at Function.Module._load (internal/modules/cjs/loader.js:531:3) code: 'MODULE_NOT_FOUND' } `
`root INFO [hosted-plugin: 12975] `
`PLUGIN_HOST(12975): PluginManagerExtImpl/init() PLUGIN_HOST(12975): initializing(newplugin@0.0.1 with /home/xpress1/Xpress/theia/packages/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js) `
`root INFO [hosted-plugin: 12975] PLUGIN_HOST(12975): PluginManagerExtImpl/loadPlugin(/tmp/theia-unpacked/newplugin.theia/lib/newplugin-backend.js) `
`root ERROR [hosted-plugin: 12975] { Error: Cannot find module '@theia/testservice' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15) `
`at Function.Module._load (internal/modules/cjs/loader.js:508:25) `
`at Function.module._load (/home/xpress1/Xpress/theia/packages/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js:42:33) `
`at Module.require (internal/modules/cjs/loader.js:637:17) `
`at require (internal/modules/cjs/helpers.js:22:18) at Object.<anonymous> (/tmp/theia-unpacked/newplugin.theia/lib/newplugin-backend.js:7:15) `
`at Module._compile (internal/modules/cjs/loader.js:701:30) `
`at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10) `
`at Module.load (internal/modules/cjs/loader.js:600:32) `
`at tryModuleLoad (internal/modules/cjs/loader.js:539:12) code: 'MODULE_NOT_FOUND' } `
`root INFO [hosted-plugin: 12975] plugin theia.newplugin, start method is undefined so the module is the extension's exports`

**Comment by svkr2k** [comment]
Error: Cannot find module '@theia/testservice' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)

**Comment by svkr2k** [comment]
Updated the details here too: https://spectrum.chat/theia/general/enhancing-plugin-apis~4218fd77-adc7-4f2f-a78d-766e6e247138

**Comment by msujew** [comment]
I believe this question has become quite stale. If anyone is experiencing similar issues, importing from `@theia/plugin-ext/src/common/rpc-protocol` is not valid, you need to import from `lib` instead of `src` (`@theia/plugin-ext/lib/common/rpc-protocol`).
