### ISSUE TITLE
Theia Extensions with LaTeX

### ISSUE THREAD

**Issue by maxcordivani** [eclipse-theia/theia#6265]
### Description

Hi, can I do implement LaTeX as an extension in theia?  How can I do it?
if so how, if not why?  I do not know how to do.

Thanks

**Comment by akosyakov** [comment]
I've seen you opened: https://github.com/eclipse-theia/theia/issues/5794 Why VS Code extension did not work for you? I would rather recommend contributing to this extension.

**Comment by maxcordivani** [comment]
Hi and thanks for the reply.
LaTeX in VS Code works very well. My question is: I can use any programming language in Theia. if I don't have a .vsix file or a git clone, how can I implement it in Theia.
I can't find any documentation and I would like to learn more about theia.

Thanks again

**Comment by akosyakov** [comment]
We don't have any documentation yet. You need to provide:
- on the frontend a language client contribution which specifies when a language server should be started
- on the backend a language server contribution which specifies how it should be started

Please have a look at python extension for example:
https://github.com/eclipse-theia/theia/tree/master/packages/python

**Comment by maxcordivani** [comment]
Thanks for the reply.
I'm trying but it's not easy.
I would like to give a generic "X" language how to implement it in theia.

**Comment by tsmaeder** [comment]
We no longer support language contributions. Closing.
