### ISSUE TITLE
Java autocomplete stops after some time

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#6274]
### Description

Java autocomplete stops after some time

I am using 
@theia/java: latest 
extension in my editor which works good initially  (giving code autocomplete) but
after some couple minutes the autocomplete stops automatically.
May be language server stops. When I check the browser console for any error there is nothing.
Is there any default config present which disables the autocomplete after some timeout ?

**Comment by akosyakov** [comment]
@dhananjayharel I would recommend you to use vscode java extension instead. Currently the main effort to support it, the native one will be deprecated later this year.

**Comment by dhananjayharel** [comment]
Thanks for the reply
I think I should follow these steps to install vscode plugins ?
https://github.com/eclipse-theia/theia/wiki/Testing-VS-Code-extensions

**Comment by akosyakov** [comment]
To try from sources, yes. For the app you can pass cli option, please look at the browser example start script to learn how.

**Comment by dhananjayharel** [comment]
Thanks 
However I was able to resolve it using the same plugin.
It was not a plugin issue but language server issue.
Actually the java lsp was getting shut down automatically inside docker container.
then I set the jdt configuration to dont watch the parent process
and now its working fine.
https://github.com/eclipse/eclipse.jdt.ls/issues/1142#issuecomment-518010556

**Comment by akosyakov** [comment]
@dhananjayharel glad that you figured it out
