### ISSUE TITLE
compression theia layout data before save to localstorage

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6275]
### Description
![image](https://user-images.githubusercontent.com/10203793/65714579-fd0e4880-e0cd-11e9-92d6-709f56b6e5c1.png)
![image](https://user-images.githubusercontent.com/10203793/65714878-8d4c8d80-e0ce-11e9-9b0d-43a73ecc09d6.png)

sometime i open many editor
it will cause layout json very long
maybe we can compression it before save

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
Please measure first why does it takes long. It is not necessary because of reading data from local storage. Decompression will require more time.

**Comment by 502647092** [comment]
@akosyakov maybe it's a bug
![image](https://user-images.githubusercontent.com/10203793/65735517-585e2c00-e10a-11e9-9567-1614ba6ec2bb.png)
I clear localstorage and force close chrome
it be very short
and this issues #5979 is gone
I think explorer tree view cause cpu 100% maybe render view from this config

**Comment by akosyakov** [comment]
Could you share both versions as files?

**Comment by 502647092** [comment]
maybe not theia problem
it's chrome bug?
https://github.com/eclipse-theia/theia/issues/5979#issuecomment-535755550_
