### ISSUE TITLE
[debug] Styling issues in the debug hover

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6278]
### Description
 

Styling issues with the debug hover and the debug console.

### Reproduction Steps

Hover over a symbol while in debug mode:
 - it is hard to click on the collapse/expand icon as the scrollbar overlaps it,
 - the debug hover overflows the debug console.

See attached screencast:

![screencast 2019-09-27 08-29-48](https://user-images.githubusercontent.com/1405703/65747525-f5689700-e101-11e9-925a-6c7bbbb7137f.gif)

**OS and Theia version:**

**Diagnostics:**

**Comment by kaiyue0329** [comment]
I made changes to the index.css inside @theia/debug. It fixes both issues.

**Comment by kaiyue0329** [comment]
I made changes to the `index.css` inside `@theia/debug`. It fixes both issues.
