### ISSUE TITLE
[widgets] add preference to control default locations of widgets

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6286]
**Description**

In order to make the opening of widgets more configurable, I propose we include preferences to control the default location of widgets. This will allow applications to set their own default locations, give more control to users, and also make it less work for extenders to customize.

We already have an example with the `debug` view 
(propose to add it to more widgets perhaps in a generic way):

https://github.com/eclipse-theia/theia/blob/02c5c1d4539efa8b19f9d0991be9827c88e184f6/packages/debug/src/browser/debug-preferences.ts#L28-L31

**Comment by akosyakov** [comment]
@vince-fugnitto we probably should bring issues with `proposal` label to the dev meeting to decide what we do with them. At least if you want to work on them.

I'm not sure that it is good idea to give a control to a user over it. How the concrete app can ensure that the widget by default is opened in the particular place in some context?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto we probably should bring issues with `proposal` label to the dev meeting to decide what we do with them. At least if you want to work on them.

I wasn't planning necessarily to work on it, I just have some questions and proposals some times to see if it'd be a useful feature :) 

> I'm not sure that it is good idea to give a control to a user over it. How the concrete app can ensure that the widget by default is opened in the particular place in some context?

Perhaps you're right, it may be problematic to give that kind of control to a user.
