### ISSUE TITLE
Local storage sometimes gets corrupt, should we validate data from it?

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#6287]
### Description

A user once reported that layout was not restored correctly, with an `undefined` type error coming from the git extension. Turned out that the layout state was missing bits somehow? After looking into it, the layout data never changed since it was first introduced, so this is not a migration bug or anything, data was simply incomplete for some reason.

I was wondering if this issue was observed by someone else, and if it is worth assuming data coming out of local storage should be considered as "untrusted data", worth validation?

Of course I told him to call the "reset layout" command, which nukes local storage, but this is not great user experience.

### Reproduction Steps

Don't know how to reproduce.

**OS and Theia version:** Theia 0.9.0

**Diagnostics:**

**Comment by svenefftinge** [comment]
I have never seen that.

**Comment by akosyakov** [comment]
It would be good to be able to reproduce it first.

**Comment by JonasHelming** [comment]
@marechal-p Did this happen again? Otherwise I suggest to close this issue
