### ISSUE TITLE
[vscode][webview]plugin can't open webview after close

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6288]
### Description

after close plugin webview
plugin can't open it again

![temp](https://user-images.githubusercontent.com/10203793/65810765-5d41df00-e1e1-11e9-9bb3-36d644551018.gif)

### Reproduction Steps

- ext install `vscode:extension/humao.rest-client`
- create simple http file
```
GET https://www.google.com
```
- send request
- close webivew
- send request again
- webview can't show

**OS and Theia version:**
latest theia 
window10
chrome 77

**Diagnostics:**

**Comment by 502647092** [comment]
@akosyakov

**Comment by akosyakov** [comment]
It could be a regression after fixing handling reconnections by the plugin system. I'm not available till Tuesday. If someone can have a look before it would be helpful.
