### ISSUE TITLE
Theia does not like typing space quickly :)

### ISSUE THREAD

**Issue by gorkem** [eclipse-theia/theia#6289]
### Description
If I  quickly tap my space bar multiple times quickly after `|` character. Theia prints a `.` dot character instead of a space. If I pace the tapping space slow I do not see the affect
![Untitled](https://user-images.githubusercontent.com/82738/65817692-7003e600-e1d8-11e9-80aa-9435b92f5526.gif)

### Reproduction Steps
Open a file on and type `|` and start tapping on the space bar quickly
**OS and Theia version:**
I have tested on master, also various versions of Che (7.1.0 and 7.2.0)
**Diagnostics:**

**Comment by svenefftinge** [comment]
I can reproduce in monaco playground: https://github.com/microsoft/monaco-editor/issues/1600

**Comment by AlexTugarev** [comment]
@gorkem and @svenefftinge please disable "add period with double space" in keyboard settings.

<img width="780" alt="Screen Shot 2019-09-30 at 08 32 18" src="https://user-images.githubusercontent.com/914497/65854437-edf0fa00-e35c-11e9-86a4-143e1a4e0ff9.png">

**Comment by gorkem** [comment]
@AlexTugarev OMG, I would have never guessed such a setting. Thanks. 
Closing this one
