### ISSUE TITLE
[vscode] Java Test Runner extension doesn't work properly

### ISSUE THREAD

**Issue by jankeromnes** [eclipse-theia/theia#6294]
### Description
Originally reported as https://github.com/gitpod-io/gitpod/issues/798:

> I have installed jave test runner extension but it is not working

I believe the extension meant is https://github.com/Microsoft/vscode-java-test

### Reproduction Steps

> Install test runner extension , try using the extension
> 
> The installed extension should work properly

> I have used that extension and noticed a couple of other rough edged, i.e. bad rendering of test results and test result icons in the tree were missing. Didn't noticed the reloading issues, though.

**OS and Theia version:** `master`

**Diagnostics:**

**Comment by akosyakov** [comment]
@jankeromnes Is it still the case? Rendering of trees were improved in October.

**Comment by akosyakov** [comment]
It worked for me last time when I tried
