### ISSUE TITLE
[vscode] vscode-icons extension doesn't work

### ISSUE THREAD

**Issue by jankeromnes** [eclipse-theia/theia#6300]
### Description
It seems that the [vscode-icons](https://github.com/vscode-icons/vscode-icons/releases) extension doesn't work in Theia:

> When installing the extension vsicons the icons don't change and this shows up in preferences
> ![image](https://user-images.githubusercontent.com/50386709/65898911-2fdb6980-e378-11e9-9d37-1aa9471eefb6.png)

(from the original issue https://github.com/gitpod-io/gitpod/issues/818)

### Reproduction Steps

1. Install https://github.com/vscode-icons/vscode-icons/releases in Theia
2. The icons don't change. Also, this error shows up in user preferences:

```
Property workbench.iconTheme is not allowed
```

**OS and Theia version:** `master`

**Diagnostics:**

**Comment by akosyakov** [comment]
VS Code like theming is not supported yet: https://github.com/eclipse-theia/theia/issues/4831

**Comment by akosyakov** [comment]
It would be delivered in December.

**Comment by JesterOrNot** [comment]
K cool!

**Comment by akosyakov** [comment]
VS Code icons with One Pro Dark color theme:
<img width="1552" alt="Screen Shot 2019-12-19 at 11 51 08" src="https://user-images.githubusercontent.com/3082655/71167912-e94e2a80-2255-11ea-8192-99fb12cf9100.png">

**Comment by JesterOrNot** [comment]
Can you show an example repo @akosyakov

**Comment by akosyakov** [comment]
@JesterOrNot Do you mean for Gitpod? Unfortunately it is only PR for Theia for now, first it has to be landed here, then Gitpod needs an upgrade to use a new version of Theia. It will happen in January.

**Comment by JesterOrNot** [comment]
Ok @akosyakov my bad!
