### ISSUE TITLE
Client is not notified when language server process terminates

### ISSUE THREAD

**Issue by spoenemann** [eclipse-theia/theia#6308]
### Description
I have a language server that terminates with an exit code in certain situations due to a fatal error. That's bad, but what's even worse is that the Theia frontend doesn't know about it and so it does not trigger a restart. Even an explicit restart through the respective command does not create a new language server process.

### Reproduction Steps
Create a LanguageServerContribution that spawns a terminating command like this:
```typescript
const serverConnection = await this.createProcessStreamConnectionAsync(command, args);
this.forward(clientConnection, serverConnection);
```

**OS and Theia version:**
macOS 10.14.6, Theia 0.11.0-next.fbd63c5d

**Diagnostics:** 
This workaround helps:
```typescript
serverConnection.onClose(() => (clientConnection as any).reader.socket.close());
```

**Comment by kittaakos** [comment]
I did a  quick check and VS Code seamlessly restarts the TS LS if I explicitly `kill` the process:
```
[Info  - 15:41:35 GMT+0100 (Central European Standard Time)] TSServer exited
[Info  - 15:41:35 GMT+0100 (Central European Standard Time)] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 15:41:35 GMT+0100 (Central European Standard Time)] <syntax> Forking...
[Info  - 15:41:35 GMT+0100 (Central European Standard Time)] <syntax> Starting...
[Info  - 15:41:35 GMT+0100 (Central European Standard Time)] <semantic> Forking...
[Info  - 15:41:35 GMT+0100 (Central European Standard Time)] <semantic> Starting...
``` 

Maybe that's all we have to do. No need to notifying the client about the issue. VS Code does not do it either.

**Comment by spoenemann** [comment]
Currently the seamless restart of the LS is triggered by the client:

https://github.com/eclipse-theia/theia/blob/master/packages/languages/src/browser/language-client-contribution.ts#L162

That's why we need to make sure to notify the client about the closed connection.
