### ISSUE TITLE
Theia window couldn't been opened.

### ISSUE THREAD

**Issue by RimShao** [eclipse-theia/theia#6311]
Hi Jan, Sven,

Today we build new theia application package, and we found the theia window couldn't be opened in the new build image, and it keep loading icon.

from the chrome console logging, there is error: 

"ReferenceError: undefinedundefinedundefined is not defined.
at Object. <anonymous> (bundle.js:110)
...."
monaco-textmate-frontend-bindings.ts:44

we do not have this error before, Is this because of new Theia extension? 

And I attach the error screen.

![Yang-Issue](https://user-images.githubusercontent.com/36630897/66051705-98207b80-e52f-11e9-8ade-17172d96aebf.PNG)

**Comment by akosyakov** [comment]
@RimShao Is there a way to reproduce it? Could you provide a github repo?

**Comment by RimShao** [comment]
we have private yang-extension git repo and that shall not be accessible by you.

The error failed at below line in ...-yang-contribution.ts

import { Diagnostic, DiagnosticSeverity, Range } from 'vscode-languageserver-types/lib/umd/main';

And I share the package.json we used:

{
  "private": true,
  "name": "theia-yt-app",
  "version": "0.0.1",
  "dependencies": {
    "@theia/core": "latest",
    "@theia/editor": "latest",
    "@theia/extension-manager": "latest",
    "@theia/filesystem": "latest",
    "@theia/file-search": "latest",
    "@theia/git": "latest",
    "@theia/java": "latest",
    "@theia/json": "latest",
    "@theia/languages": "latest",
    "@theia/markers": "latest",
    "@theia/messages": "latest",
    "@theia/metrics": "latest",
    "@theia/mini-browser": "latest",
    "@theia/monaco": "latest",
    "@theia/navigator": "latest",
    "@theia/plantuml": "latest",
    "@theia/preferences": "latest",
    "@theia/preview": "latest",
    "@theia/process": "latest",
    "@theia/output": "latest",
    "@theia/outline-view": "latest",
    "@theia/search-in-workspace": "latest",
    "@theia/task": "latest",
    "@theia/terminal": "latest",
    "@theia/textmate-grammars": "latest",
    "@theia/userstorage": "latest",
    "@theia/workspace": "latest",
    "theia-yang-extension": "latest",
    "...-yang-extension": "0.1.0"
  },
  "devDependencies": {
    "@theia/cli": "latest"
  },
  "theia": {
    "target": "browser"
  }
}

**Comment by kittaakos** [comment]
@RimShao, I could reproduce the error by with the following import.

```
ReferenceError: undefinedundefinedundefined is not defined
    at Object.../node_modules/vscode-languageserver-types/lib/umd/main.js 
```

Incorrect import:
```
import { Diagnostic, DiagnosticSeverity, Range } from 'vscode-languageserver-types/lib/umd/main';
console.log(Diagnostic, DiagnosticSeverity, Range);
```

Correct import:
```
import { Diagnostic, DiagnosticSeverity, Range } from 'vscode-languageserver-types';
console.log(Diagnostic, DiagnosticSeverity, Range);
```

I am going to close this.

**Comment by RimShao** [comment]
Thanks a lot. I will check that.

**Comment by kittaakos** [comment]
> I will check that.

And please feel free reopening the issues if the problem persists.
