### ISSUE TITLE
Opening a second frontend generates plugin error

### ISSUE THREAD

**Issue by JPinkney** [eclipse-theia/theia#6314]
### Description
 
Opening a second instance of the frontend is generating:
```
Plugin runtime crashed unexpectedly, all plugins are not working, please reload the page. It might happen if there is not enough memory for the plugins.
```
### Reproduction Steps

- Start browser backend, navigate to localhost:3000
- Install vscode-yaml: `ext install redhat.vscode-yaml`
- Open a yaml file
- Navigate to localhost:3000 on a second tab
- You should see the error notification pop up in the bottom right of theia.
- Attempting to use the yaml file doesn't give any features

**OS and Theia version:**
Tested on: 74d3790981c96ab664df300c9d05fcb31d3a94f8
Fedora 30

**Diagnostics:** 

No related errors in the console

**Comment by akosyakov** [comment]
It worked for me. I've tried with yaml and go vs code extensions. Could it be that you don't have enough memory as a warning says?

**Comment by akosyakov** [comment]
> It might happen if there is not enough memory for the plugins.

@mmorhun @benoitf It would be helpful if it suggest how to fix it.

**Comment by mmorhun** [comment]
I think this is not problem with memory, because if Theia runs on host machine it may use all the free memory and in most cases it should be enough. Otherwise just increase memory limit for container or VM.

**Comment by tsmaeder** [comment]
@JPinkney can you try to installing the plugin outside of the IDE? I think I remember that using "ext install" only installs it cleanly for one front end.

**Comment by JPinkney** [comment]
I just tried:
- Putting vscode-yaml into plugins folder
- Launch browser backend
- Open localhost:3000
- Test out yaml file (everything works)
- Open localhost:3000 in another tab
- Still the same error in the bottom right

**Comment by tsmaeder** [comment]
Sorry, works for me useing master of theia and vscode-yml 0.5.3

**Comment by benoitf** [comment]
browser = ? chrome / firefox ?

**Comment by tsmaeder** [comment]
FF for me, but I doubt it makes a difference for a back-end plugin

**Comment by akosyakov** [comment]
@JPinkney Do you have anything in backend and devtools logs? There is a probably some info why the process dies.

**Comment by benoitf** [comment]
not reproducing as well

For each new tab I've a new plugin-host process and it's still alive

I've opened 3 tabs
```
$ ps aux | grep node | grep plugin-host
benoitf          15875   0.0  0.1  6205460  41292 s004  S+    4:43PM   0:00.30 /Users/benoitf/.nvm/versions/node/v11.15.0/bin/node /Users/benoitf/git/eclipse/theia/packages/plugin-ext/lib/hosted/node/plugin-host.js
benoitf          15825   0.0  0.1  6076436  42140 s004  S+    4:42PM   0:00.37 /Users/benoitf/.nvm/versions/node/v11.15.0/bin/node /Users/benoitf/git/eclipse/theia/packages/plugin-ext/lib/hosted/node/plugin-host.js
benoitf          15803   0.0  0.1  6075924  47836 s004  S+    4:41PM   0:00.43 /Users/benoitf/.nvm/versions/node/v11.15.0/bin/node /Users/benoitf/git/eclipse/theia/packages/plugin-ext/lib/hosted/node/plugin-host.js
```

**Comment by benoitf** [comment]
@JPinkney you could add breakpoints on handling errors/exit

https://github.com/eclipse-theia/theia/blob/7655b5362a5b2b75a9a6becdbc04a707583d1df3/packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts#L174-L192

**Comment by JPinkney** [comment]
Yeah, looks like its getting code 12 which is: ENOMEM 12 Cannot allocate memory

**Comment by JPinkney** [comment]
Interestingly enough, when I run `yarn run start` from inside of examples/browser the issue doesn't occur. It only occurs when i'm using the `Launch Browser Backend` launch configuration

**Comment by JPinkney** [comment]
I've made another interesting discovery:

I ended up getting this in the debug console:
```
root ERROR [hosted-plugin: 20669] Starting inspector on 127.0.0.1:9339 failed: address already in use
root ERROR [hosted-plugin: 20669] IPC exited, with signal: null, and exit code: 12
```
and if I remove `"--hosted-plugin-inspect=9339"` from the `Launch Browser Backend` launch configuration or if I remove `--inspect${inspectArg.substr(inspectArgPrefix.length)}` from https://github.com/eclipse-theia/theia/blob/7655b5362a5b2b75a9a6becdbc04a707583d1df3/packages/plugin-ext/src/hosted/node/hosted-plugin-process.ts#L166

then everything works as expected

**Comment by akosyakov** [comment]
@JPinkney a new plugin host process is started for each window, since launch configuration is configured to use port 9339 for debugging then the second window won't be able to start the process

you can do `--hosted-plugin-inspect=0` that a port randomly generated for each plugin host

**Comment by akosyakov** [comment]
> It might happen if there is not enough memory for the plugins

It is confusing. The better would be a recommendation to check out server logs.

**Comment by mmorhun** [comment]
@akosyakov created PR: https://github.com/eclipse-theia/theia/pull/6335
