### ISSUE TITLE
[Fylesystem] Renaming a file on windows generates the wrong event

### ISSUE THREAD

**Issue by federicobozzini** [eclipse-theia/theia#6315]
### Description
 
When a file or a folder is renamed on Windows, [I would expect Theia to generate 2 events, 1 for the file getting deleted and another one for the file getting created](https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/node/nsfw-watcher/nsfw-filesystem-watcher.ts#L122). This doesn't happen, due to [an unexpected behaviour of`nsfw`](https://github.com/Axosoft/nsfw/issues/26).

### Reproduction Steps

On Windows, try to rename a file that is watched by `NsfwFileSystemWatcherServer`. When doing that 2 events are generated by `nsfw`, one for the renamed file with type RENAMED'containing both the old path and the new path and another one with type CREATED for the deleted file. The second event is then merged with the events generated for the file renaming according to the rule [DELETED + ADDED => UPDATED](https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/node/file-change-collection.ts#L29) and the result is the old file being described as UPDATED instead of DELETED.

I think this is a bug in `nsfw`, but it begs the question, do you fillit might be appropriate to address this in Theia?

**OS and Theia version:**

Seen on Windows 10, with the latest Theia version (master). 

**Diagnostics:**

**Comment by akosyakov** [comment]
@federicobozzini If there is a way to work it around on windows, without affecting other platforms, please do

**Comment by federicobozzini** [comment]
I think the only reasonable way would be to ignore the unwanted event when we can assume it was generated by error.

I'm not sure if there might be a risk of false positives (events getting ignored when they shouldn't) though.

**Comment by akosyakov** [comment]
@federicobozzini Could you please check whether you can reproduce it with VS Code? They use nsfw as well. If you cannot it would be good to have a look how they handle events.

> I'm not sure if there might be a risk of false positives (events getting ignored when they shouldn't) though.

I'm not sure either. How would you decide which CREATED event we should ignore?

**Comment by akosyakov** [comment]
We also should file an issue for nsfw with a reproducible example.

**Comment by dschafhauser** [comment]
This issue seems to be the root cause for https://github.com/eclipse-theia/theia/issues/6309, at least for the erroneous behavior on Windows.
