### ISSUE TITLE
[Question] Getting customized json file values

### ISSUE THREAD

**Issue by wonjooncho** [eclipse-theia/theia#6324]
### Description
I am trying to make theia-extension.
In my theia-extension, I created a setting-test.json file under the .setting-test directory of the root workspace as a sample, and made a code that the front end reads the file contents through the back end.
However, the initial value is read well, but the value does not change even after modification.
Is there anything I missed?
If possible, check out my source code and videos.

[Source Code](https://github.com/wonjooncho/theia-backend/commit/f5383cb41b8f8d9dd43fc029081b169f5f548bc5)

### Reproduction Steps

[Video](https://youtu.be/lb_m7eub4hg)

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
Don't use `require` to read JSON files. `require` loads it as a Node module and caches to avoid sequential loading. Use `readJSON` from `fs-extra`.

Some more hints:
- don't use sync Node.js APIs, it can harm backend performance
- Workspace can be access only on the frontend from `WorkspaceService`. Never cache it on the backend or try to get somehow differently, always pass a root URI to the backend instead. Different windows can work with different workspaces.
- See general URI guidelines: https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines#uripath

**Comment by wonjooncho** [comment]
@akosyakov Thank you for your help.
As you said, I solved this issue using `readJSON` from `fs-extra`.

Additional question about  
> Workspace can be access only on the frontend from WorkspaceService. Never cache it on the backend or try to get somehow differently, always pass a root URI to the backend instead. Different windows can work with different workspaces.

Can I get some sample code or additional information?
How can I get the workspace root RUL on the frontend?

**Comment by akosyakov** [comment]
> Can I get some sample code or additional information?
> How can I get the workspace root RUL on the frontend?

See how [WorkspaceService.tryGetRoots](https://github.com/eclipse-theia/theia/blob/e3ff100b485915eeaf8ec426b48eff933a3a5ced/packages/workspace/src/browser/workspace-service.ts#L116) is used in Theia repo.

**Comment by wonjooncho** [comment]
@akosyakov  Thanks a lot!!!
I will refer it! :)
