### ISSUE TITLE
[Windows] I can see multiple stale Node.js processes after terminating the application

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#633]
I do not know if that is related to the clusters or not, but previously, there were no running Node.js processes after I have terminated the `$example/browser yarn run start` process from the terminal.

It requires further investigations, though.

**Comment by hexa00** [comment]
This was happening before the clusters

**Comment by kittaakos** [comment]
That's great! It does not happen on OS X, but on Windows. It kills the CPU on my image.

**Comment by hexa00** [comment]
hahah ok I did not notice the cpu usage.

**Comment by kittaakos** [comment]
This makes the development on Windows almost impossible. I need to kill the processes one by one after 20 minutes. As the attached image depicts, I have tons of running Node.js processes although only the task manager and Chrome runs.

![gh_633](https://user-images.githubusercontent.com/1405703/31887252-e375aaea-b7f7-11e7-950b-1a43a99e617a.png)

**Comment by hexa00** [comment]
I agree this totally sucks... especially given you can't do like `killall node` maybe in powershell you can?
But it would need to be fixed by us...

**Comment by kittaakos** [comment]
#815?

**Comment by kittaakos** [comment]
I will verify this once more after merging #815 to the master.

**Comment by hexa00** [comment]
Btw not a solution but as workaround one can use the taskkill command it seems be the killall like equivalent see : https://technet.microsoft.com/en-us/library/bb491009.aspx  `taskkill /fi node` I guess would work.

**Comment by kittaakos** [comment]
> taskkill /fi node

```
C:\Users\kittaakos>taskkill /fi node
ERROR: The search filter cannot be recognized.
```

This did the trick here:
```
taskkill /f /im "node.exe"
```

**Comment by tsmaeder** [comment]
I don't see this behaviour: stopping the "yarn run start" stops all node instances.
