### ISSUE TITLE
Properly handle "same" notification results

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-theia/theia#6337]
Currently, for a client of `MessageService` will get the same result promise for `showMessage` calls with the same content, e.g. `For more on this follow this... [LINK]`. It's already unfortunate we need to handle this weird behavior of clients, but happens to be that resolving with `LINK`, leads to multiple execution of handlers to open new tabs for instance.

The situation can be improved by returning distinct promises, and only resolving the last one; or maybe the first one? It would be interesting to see, how those cases are handles in vscode extensions to align with the assumptions.

**Comment by kittaakos** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/9349. The other bug report has a ref to an example.
