### ISSUE TITLE
do we want to add "version" in .theia/tasks.json ?

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#6338]
### Description
Since vscode supports the task versions of `1.x.x` and `2.x.x`, `version` is a mandatory property in `.vscode/tasks.json`.

In `.theia/tasks.json`, `version` is not required, because we are only compatible with `2.x.x`.

Here are the potential problems:
- `Run task` in Theia is very likely to fail if users run v1.x.x task configs that were defined in vscode. Users wouldn't be properly notified why `Run task` fails.
- vscode would notify users that `tasks.json`, which was created in Theia, has scehma errors. This is not as bad as the first problem - at least the user knows what went wrong, thanks to the message from vscode.

A few things we could do to fix / alleviate the problems:
- add a mandatory `version` to the task schema in Theia. This way, Theia users would see errors from the problem view.
- if `version` is missing, prompt Theia users to add `version` to `tasks.json`, before a task is started.
- throw an error if Theia users run / configure v1.x.x tasks.

There are also voice from my office that says we could leave it as is until vsCode makes another major release of task version, say, v3.x.x.

@eclipse-theia/task-extension What do you think?

**Comment by vince-fugnitto** [comment]
I'd be fine to add `version` to the schema so we can get better handling, and more meaningful end user messages regarding versioning compatibility. 

> `Run task` in Theia is very likely to fail if users run v1.x.x task configs that were defined in vscode. Users wouldn't be properly notified why `Run task` fails.

I think we can simply not attempt to run tasks from VSCode which are of version less than v2, and notify end users that the task is incompatible.

> * add a mandatory `version` to the task schema in Theia. This way, Theia users would see errors from the problem view.

I'm not sure it has to be mandatory, but if we read from VSCode tasks which are of an incompatible version, we can simply not execute them. If a version is not present, we can assume it is v2 and proceed.

**Comment by akosyakov** [comment]
Maybe we don't overthink it and wait till the real issue is filed?

> vscode would notify users that tasks.json, which was created in Theia, has scehma errors.

This one sounds a bit like a real issue. If we create something under `.vscode` folder. It should be readable in VS Code.
