### ISSUE TITLE
Gitlens Issue

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse-theia/theia#6347]
Describe the bug
Original issue: https://github.com/gitpod-io/gitpod/issues/829
Got the error:
![image](https://user-images.githubusercontent.com/50386709/66398198-fa9bd080-e9a2-11e9-900d-b55b424b4a9f.png)

To Reproduce
Install gitlens extension
or open my workspace JesterOrNot/pycalc
Expected behavior
Works normally

**Comment by vince-fugnitto** [comment]
I believe it's being addressed in #6341

**Comment by JesterOrNot** [comment]
so should this issue be closed?

**Comment by vince-fugnitto** [comment]
Yes, thank you @JesterOrNot !
