### ISSUE TITLE
LabeIs for tasks are inconsistent in notifications

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#6360]
### Description
Notification about starting/completing for the same task contains different label.
It depends on - is task `detected` or `configured`, but for all these cases the item for task in `Terminal -> Run Task` menu has identical label.

Another question - notification for `configured` task contains different label before and after page refreshing. 

### Reproduction Steps
1. Run a `tsc` `detected` task -> see notification
![detected_notification](https://user-images.githubusercontent.com/5676062/66547102-2bb50600-eb47-11e9-89eb-5c4794fb47c0.png)

2. Configure the task and run it -> see notification
![configured_notification](https://user-images.githubusercontent.com/5676062/66547115-2f488d00-eb47-11e9-90e3-8b2035c885c8.png)

3. Refresh page and run the task again -> see notification
![configured_refresh_notification](https://user-images.githubusercontent.com/5676062/66547127-32dc1400-eb47-11e9-896c-c72f37959f6c.png)
 
please see https://youtu.be/z5R6vYC9Qyo

**OS and Theia version:**
Theia 46a3bf3ba91c75082fb32fab6cec1b7a04a4b559

**Comment by RomanNikitenko** [comment]
> on the notification rendering part of this issue:
does the last screenshot show a crop, or is the bottom margin that bad?

My goal was to display problems with labels, so I think I just did the screenshots a little sloppy :-)

**Comment by elaihau** [comment]
Not sure about che tasks, but the inconsistent messaging issue regarding `tsc: build` should have been fixed. @RomanNikitenko could you please confirm when you have time to do so? Thank you !

**Comment by RomanNikitenko** [comment]
@elaihau 
Hello!
The issue was reproduced on `theia` project for `tsc` tasks, not `che` tasks. 
You can check it using `git reset --hard 46a3bf3ba91c75082fb32fab6cec1b7a04a4b559`
Please see the video https://youtu.be/rY2d2VIQeCI

I can not reproduce it for current master branch, so I'm closing the issue.
Do you know which commit brought the fix for the issue?

**Comment by elaihau** [comment]
@RomanNikitenko i believe https://github.com/eclipse-theia/theia/commit/979556c337d656d31e660e2ff5b726fbd54a4386 fixes the problem
