### ISSUE TITLE
Debugging Fails Silently While LS is Starting

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#6361]
When I tried to attach the debugger to  a Java program that was still being imported by the Java LS, nothing happend, no success and no error message.

### Reproduction Steps
I reproduced this with the Che 7.1.0 and the spring http-booster example (https://github.com/snowdrop/spring-boot-http-booster). Howerver, I think any example that takes a long time to import might help

1. Install the vscode-java extension into theia
2. clear your local .m2 folder
3. import the example project
4. Do _not_ open an java files or do anything to activate the vscode-java extension
5. Run the example in debug mode 
mvn  -Duser.home=${HOME} spring-boot:run -Drun.jvmArguments="-Xdebug
          -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"
6. Make a "remote attach" debug config and try to run it
7. Observe: the java language server is started and taking a long time stuck at "57% import maven projects"
8. Observe: nothing else happens

The browser log showed the following exception:

```
Uncaught (in promise) Error: It is not possible to provide debug adapter executable.
    at DebugExtImpl.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:501)
    at step (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:32)
    at Object.next (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:13)
    at fulfilled (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/node/debug/debug.js:4)
    at process._tickCallback (/dashboard/internal/process/next_tick.js:68)
```

**Comment by tsmaeder** [comment]
Once the language server is through importing, debugging works fine.

**Comment by akosyakov** [comment]
@tsmaeder Do you remember which version of vscode-java was it?

**Comment by akosyakov** [comment]
I can reproduce it with redhat.java@0.47.0 and vscode-java-debug@0.21.0.

But not with latest versions, i.e. redhat.java@0.54.2 and vscode-java-debug@0.23.0.

**Comment by akosyakov** [comment]
https://github.com/microsoft/vscode-java-debug/issues/728#issuecomment-567757572 - so it is probably not Theia issue

**Comment by akosyakov** [comment]
Please use `redhat.java@0.49.0` or never.
