### ISSUE TITLE
Syntax highlight vscode extension will not work after reload browser

### ISSUE THREAD

**Issue by datou0412** [eclipse-theia/theia#6366]
### Description
Syntax highlight vscode extension will not work after reload browser（the first time will be ok）
![image](https://user-images.githubusercontent.com/5847142/66627724-2d59f900-ec2f-11e9-8d37-74914ad3875f.png)

### Reproduction Steps
1. Start a theia server with a syntax highlight vscode extension, [vue](https://marketplace.visualstudio.com/items?itemName=jcbuisson.vue) for instance
2. Open a .vue file, syntax highlight will work in the right way
3. Reload that page, syntax highlight will disappear

**OS and Theia version:** theia v0.11.0

**Comment by akosyakov** [comment]
It was fixed in `next`. Please reopen if you can reproduce on the master.

**Comment by datou0412** [comment]
is there a commit id? just curious  :P

**Comment by akosyakov** [comment]
@datou0412 https://github.com/eclipse-theia/theia/commit/6347c5ccbf016b7cfa70976f69616eb1bb49c5b0 should fix it.
