### ISSUE TITLE
[kemaps] internal commands should NOT be available 

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6368]
<img width="1552" alt="Screen Shot 2019-10-11 at 14 48 20" src="https://user-images.githubusercontent.com/3082655/66652534-3dc1a200-ec36-11e9-9e5c-4a8687512de6.png">

VS Code filters out commands starting from `_`.  We can do the same.

**Comment by vince-fugnitto** [comment]
Is the idea only to filter out commands which are prefixed by `_`?

**Comment by akosyakov** [comment]
Yes, it would be enough. But you can go through all command in keybindings view and see whether there is something else suspicious.
