### ISSUE TITLE
webview resource path is incorrect in some cases

### ISSUE THREAD

**Issue by BroKun** [eclipse-theia/theia#6373]
### Description

We fixed the #5503 problem before, which brought new problems.
On some plugins, such as [vscode-python](https://marketplace.visualstudio.com/items?itemName=ms-python.python), their webview already contains a `base` tag.
```
<base href="vscode-resource:/pathToExtension/">
<script type="text/javascript" src="vscode-resource:/pathToExtensionr/index_bundle.js"></script>
```
 If there is no slash prefix, you will get the wrong path.
```
webview/pathToExtension/webview/pathToExtension/index_bundle.js
```

### Reproduction Steps
1. download [vscode-python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) to the plugin directory.
2. open the interactive python window via a notebook file.

**OS and Theia version:**
ALL
Theia master branch

**Diagnostics:** 
I can't find a way to support proxy mode in the case of only modifying the front end. I think we can add some configuration to support it.

**Comment by akosyakov** [comment]
@BroKun i believe it is a dup of https://github.com/eclipse-theia/theia/issues/6282#issuecomment-535870742 and we should something similar to https://github.com/eclipse-theia/theia/issues/6282#issuecomment-535879977
