### ISSUE TITLE
Failed to start JSON language server

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6393]
### Description

start theia get error

Failed to start JSON language server: Request initialize failed with message: Cannot read property 'provideFormatter' of undefined

```
Uncaught (in promise) Error: Request initialize failed with message: Cannot read property 'provideFormatter' of undefined
    at main.js:448
    at main.js:275
    at main.js:259
    at setImmediate.js:40
    at f (setImmediate.js:69)
    at s (setImmediate.js:109)
main.js:903 Uncaught (in promise) Error: Connection got disposed.
    at Object.dispose (main.js:903)
    at t.<anonymous> (language-client-contribution.ts:158)
    at bundle.js:8
    at Object.throw (bundle.js:8)
    at s (bundle.js:8)
logger-protocol.ts:112 root ERROR The ws channel does not exist 24
```

when I start JSON language server use command get  other error

```
Uncaught (in promise) Error: Connection is disposed.
    at te (main.js:676)
    at Object.onNotification (main.js:753)
    at Object.onLogMessage (connection.ts:110)
    at client.js:1920
i @ construct.js:30
t @ wrapNativeSuper.js:26
t @ main.js:154
te @ main.js:676
onNotification @ main.js:753
onLogMessage @ connection.ts:110
(anonymous) @ client.js:1920
Promise.then (async)
e.onWillStart @ language-client-contribution.ts:194
onConnection @ language-client-contribution.ts:165
(anonymous) @ ws-connection-provider.ts:112
(anonymous) @ ws-connection-provider.ts:142
e.handleMessage @ web-socket-channel.ts:47
n.onmessage @ ws-connection-provider.ts:74
```

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 how do you get it? I cannot reproduce it on master.

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/66898883-9aed9700-f02c-11e9-820b-aba5254fbc3d.png)
this error report from json-rpc at my docker image
but I can't find some error log

I'll test it on gitpod later.

**Comment by 502647092** [comment]
I cannot reproduce it on gitpod at master.
@akosyakov 
can you help test Docker image miaowoo/theia:alpine

**Comment by akosyakov** [comment]
@502647092 Unfortunately, not now. We are preparing for EclipseCon next week.

maybe somebody else from @eclipse-theia/eclipse-theia can help you to investigate

**Comment by 502647092** [comment]
@akosyakov I compare package vscode-json-languageserver
gitpod version is 1.2.1
my docker version is 1.2.2
at 1.2.2 have new params `params.initializationOptions.provideFormatter`

**Comment by akosyakov** [comment]
@502647092 I can reproduce it by removing `vscode-json-languageserver` from yarn.lock and running the build again.

**Comment by akosyakov** [comment]
You can use yarn resolutions for now to pin it.

**Comment by akosyakov** [comment]
@502647092 please try #6398
