### ISSUE TITLE
[output] preserve selected output channel

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6400]
**Description**

The selected output channel gets lost when reloading the application (or a language server is restarted). This leads to a poor experience where users must constantly re-select the output channel. I believe it should be preserved if possible, similarly to VS Code. 

<div align='center'>

<img width="560" alt="Screen Shot 2019-10-16 at 8 46 15 AM" src="https://user-images.githubusercontent.com/40359487/66920537-80e29300-eff1-11e9-959a-d20626775a17.png">

</div>

---

**Bonus** 🏅
Should we also provide the functionality to set the default channel or sort the channels (there is no clear indication on how the channels are actually represented at the moment)?

**Comment by akosyakov** [comment]
Not sure about language servers. As far as I understand integrating extensions (native or VS Code) are responsible to decide what to do with the output channels.

**Comment by vince-fugnitto** [comment]
You're correct, it does not look like VS Code preserves language servers when reloading.
(ex: `Typescript` > reload ).

**Comment by vince-fugnitto** [comment]
Perhaps the issue can be closed if there's nothing to do.
