### ISSUE TITLE
Multiple views of a single file

### ISSUE THREAD

**Issue by dannaf** [eclipse-theia/theia#6404]
### Description
I would like to view a code file in multiple views simultaneously, each of which is independently scrollable (not like the 'Compare With..' feature, which scrolls in sync).  

### Envisioned usage
Right click on a file in the Explorer, and have an option 'Open Additional View', which when clicked would add the file again to a new tab in the Editor, even if that file is already viewed in the editor.

From there, a user can use existing features to drag the second/third+ editor tab(s) of the file to arrange multi-views of the file as desired (eg side-by-side left/right, above/below, or even something like [this](https://user-images.githubusercontent.com/14182238/52871969-48647f80-3119-11e9-97f8-d24933a72017.png)).  [Currently, it seems to me that this kind of multi-subwindow viewing is limited only to distinct files].

(I believe this feature is available in VS Code.  I think there is via the View menu, View -> Split Window, or something like that)

### Version
0.11.0-next.1808d782
Chrome 77.0.3865.120 (Official Build) (64-bit)
Windows 10

**Comment by vince-fugnitto** [comment]
@dannaf do you mean the ability to open the same file (ex: `a.ts`) in multiple editors?
If so, the issue https://github.com/eclipse-theia/theia/issues/3857 has been previously opened.

**Comment by dannaf** [comment]
Yes, that's what I am talking about.  Thanks, didn't see that issue.

**Comment by vince-fugnitto** [comment]
No problem! You can always write in the issue of how you'd like the feature :) 
I understand it's very useful when dealing with large files. 

Closing as it's a duplicate #3857
