### ISSUE TITLE
how to install vscode build-in plugin like git

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6406]
### Description

how to install vscode build-in plugin like git

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
All built-int extensions are republished to npmjs with `@theia/vscode-builtin-` prefix as a name, e.g. for git: https://www.npmjs.com/package/@theia/vscode-builtin-git

You can use `npm info @theia/vscode-builtin-git dist.tarball` to find out URL to tar file.

**Comment by 502647092** [comment]
@akosyakov 
I add `@theia/vscode-builtin-git` to `package.json` and remove `@theia/git`
![image](https://user-images.githubusercontent.com/10203793/67080277-72e66b00-f1c7-11e9-8f98-3ed86a5d9cf9.png)

**Comment by akosyakov** [comment]
You should install it as a plugin, i.e. use `plugins` cli option as in the browser example start script.
