### ISSUE TITLE
[vscode][plugin] some plugin get vscode Module but not found

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6407]
### Description

code from ext `formulahendry.vscode-mysql`

```
Global.keytar = getCoreNodeModule(`keytar`);
exports.Global = Global;
/**
 * Returns a node module installed with VSCode, or null if it fails.
 */
function getCoreNodeModule(moduleName) {
    console.log(vscode.env.appRoot)
    try {
        return require(`${vscode.env.appRoot}/node_modules.asar/${moduleName}`);
    }
    catch (err) { }
    try {
        return require(`${vscode.env.appRoot}/node_modules/${moduleName}`);
    }
    catch (err) { }
    return null;
}
```

it cause plugin can't use
how to fix this problem

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
It looks the same as https://github.com/eclipse-theia/theia/issues/4935#issuecomment-496792594

**Comment by akosyakov** [comment]
If we do https://github.com/eclipse-theia/theia/issues/4935#issuecomment-497581848 then you should be able to add required modules as dependencies to your app to install them under `${vscode.env.appRoot}/node_modules`.
