### ISSUE TITLE
Integration Test Framework

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6409]
- program tests against Theia APIs via dependency injection instead of browser elements. 
- run tests inside Theia application 
- rerunning and debugging an individual test 
- launching multiple-instances of Theia applications with a different set of test extensions, VS Code extensions, settings, like a workspace directory or an application targets, i.e. browser or electron, and so on.

This work item will include the implementation of the testing framework as well as replacement of the existing integration tests in the Theia repository based on the new framework. 

It will be based on https://github.com/eclipse-theia/theia/pull/5654, i.e. we don't really implementing our own testing framework, but integrating existing frameworks like Mocha to run within the application, each extension will be able to provide an entry point to contribute more tests.

**Comment by akosyakov** [comment]
An approach in #5654 although give nice development exp, but does not scale to real products:
- It requires the special build. Consider docker images for example, to apply tests we will need to include them into the build image increasing the size of image and including unnecessary code into the production. It would be better if tests are not coupled with the build but added later, as it is now with wdio.
- As a consequence of the previous point some interesting use cases are not possible. Consider for example test repos for Gitpod, i.e. the repo which has all tools installed, project built, but as well tests to run against such project. Such tests has to be loaded dynamically. cc @meysholdt 

Because of such reasons, I don't want to pursue the approach with extension test contribution points, but allow to define tests separately, for example, with puppeteer:
```ts
const browser = await puppeteer.launch();
const page = await browser.newPage();
// do authentication of your product, set cookies and so on
await page.goto("https://localhost:3000/");
const editorCount = await page.evaluate(() => {
    // code which evaluates in the browser context
    import applicationContainer from '@theia/core/lib/browser/frontend-application-container';
    import { EditorManager } from '@theia/editor/lib/browser/editor-manager';
    const editorManager = applicationContainer.get(EditorManager);
    return editorManager.all.length;
});
browser.close();
```

The issue with code above that such import syntax is not supported by browsers and our bundle files are not exposing any APIs, so there is no way to access constructors. The way to outcome this issue will be to install `theia` global variable and populate it with loaded modules, i.e.
```ts
const editorCount = await page.evaluate(() => {
    // code which evaluates in the browser context
    const applicationContainer = theia['@theia/core/lib/browser/frontend-application-container'];
    const { EditorManager } = theia['@theia/editor/lib/browser/editor-manager'];
    const editorManager = applicationContainer.get(EditorManager);
    return editorManager.all.length;
});
```

We will also need to generate d.ts files to make dev experience nice. Inserting such global variable and generating d.ts. file is possible with custom webpack loader running on js files before the primary loader.

Does it sound reasonable? Does anyone see the better way to have both:
- good development and debug experience by testing against real APIs
- avoid rebuilding a product to add new tests

@amiramw Do you have separate builds to insert tests? Do I overlook the simpler approach?

**Comment by akosyakov** [comment]
@amiramw actually i've just seen https://github.com/eclipse-theia/theia/issues/2919#issuecomment-454547044, but you don't have any statically typed support with such approach, do you?

**Comment by amiramw** [comment]
> @amiramw actually i've just seen [#2919 (comment)](https://github.com/eclipse-theia/theia/issues/2919#issuecomment-454547044), but you don't have any statically typed support with such approach, do you? How do you query instances for symbols?

I didn't investigate further than query by class names.

> 
> A bit off-topic:
> 
> * how many such tests do you have?

Only one API is tested like that. This code injection framework is pretty fragile as it is not in part of theia core and any change in webpack config can break it. Also it doesn't work in production build of webpack. I guess that it can also be solved if the framework is part of theia build. Also it is a limitation we can leave with.

So we currently do more UI tests than API tests. If it is part of theia build we will probably prefer it for some of the scenarios.


> * how easy it to debug code executed in the browser context?

With puppeteer you have a config file and you need to change the following configuration:
```javascript
  launch: {
    headless: false,
    devtools: true
  }
```
Then chrome opens up with dev tools and you can debug there.
(I'm not sure if this is the smoothest way to debug browser code in puppeteer out there.)




> * how reliable are they from your experience so far?

They are probably better than UI tests we have but as I said we didn't expand to more than a single scenario so I'm not sure.

> * how fast?

Our single test runs in 13 seconds while the UI tests we have need much more. Also the API test doesn't require any set timeouts which unfortunately we are forced to use in our UI tests.

**Comment by amiramw** [comment]
> @amiramw Do you have separate builds to insert tests? Do I overlook the simpler approach?

Ideally we would like it to be separate so that each team contributing functionality to the IDE can run such tests. 

However, I think there is value to such framework even in the theia build scope (for example if it can only run with some dev build flag).

**Comment by akosyakov** [comment]
> Then chrome opens up with dev tools and you can debug there.
(I'm not sure if this is the smoothest way to debug browser code in puppeteer out there.

It would work in the local scenario, but won't work for remote development. It would be nice if opening a page (even remotely) triggers tests and one could rerun the individual test somehow. I'm still thinking about running mocha and tests within the browser using puppeteer to inject chai, mocha and test suites.

**Comment by akosyakov** [comment]
@amiramw I've experimented a bit with your approach a bit and hit very fast a need to reference other classes, like URI, constant strings and so on. I think I still have to go with a special function allowing to import modules from bundled code. It also will be more performant and correct, since we will use a proper constructor instead of trying to guess a binding based on class. I've learned though that using pure javascript and @type js-doc annotations is enough for type safety and we don't need to generate d.ts files.

I also try to use puppeteer debugging as described here: https://developers.google.com/web/tools/puppeteer/debugging It works nicely with VNC in remote scenarious, but requires changing code to tune timings.

**Comment by akosyakov** [comment]
To run puppeteer with Electron we need Electron 5 at least: https://github.com/puppeteer/puppeteer/issues/4283#issuecomment-496325603

**Comment by marechal-p** [comment]
>     * It requires the special build. Consider docker images for example, to apply tests we will need to include them into the build image increasing the size of image and including unnecessary code into the production. It would be better if tests are not coupled with the build but added later, as it is now with wdio.

Is it not possible to have one production image, and one test image based on the production one?

This way the test build wouldn't pollute the production image, but still test the production code?

**Comment by akosyakov** [comment]
@marechal-p How would you do it in theia-apps without including tests in the image or avoiding building another image, not actually one which will be used by end users? How would you inject tests in Gitpod Theia without rebuilding it for each test repo? We want to avoid testing not production artifacts.

You can follow the new approach on https://github.com/eclipse-theia/theia/tree/ak/integration_tests
