### ISSUE TITLE
theia java extension  high cpu for multiple projects opened in same container

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#6412]
### Description
I am using the latest theia editor having java and java-debug extensions and when I open multiple 
projects in the browser(on multiple tabs) then that time the CPU usage of the machine goes high and sometimes machine also gets hanged.
When I monitored the running process in my host machine , I realized that every time opening the project it creates the new Java Language Server process.
Is it  possible that only one language server will be used at the back-end for multiple front end clients of the java plugin?
Is there any configuration available in the preference?

### Reproduction Steps
Lunch the editor in multiple tabs.

**OS and Theia version:**
Alpine node 10.6 having jdk 8
thiea version = 0.11.0
**Diagnostics:**

**Comment by akosyakov** [comment]
Each window has own user session, i.e opened workspace, dirty document buffers, and so on, so each window needs own language server. Language servers cannot be reused for different clients.

**Comment by dhananjayharel** [comment]
Oh I see!
thats true.
Thanks for reply.
