### ISSUE TITLE
Theia LS client does not support LocationLink

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse-theia/theia#6414]
Theia IDE Language Server Client does not support `LocationLink` as a response to `textDocument/definition` message. Only `Location` is supported at the moment.

Therefore for `LocationLink` there is an error in the console for validating the URL from `Location#uri` property as there is no such property on `LocationLink` instead there is `targetUri`

See docs here: https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_definition

**Comment by tsmaeder** [comment]
We no longer implement any LSP functionality. Closing.
