### ISSUE TITLE
[tasks] support modifying existing problem matchers

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6427]
**Description**

VS Code supports the possibility of modifying existing **problem matchers**.
For instance, a user can define a `base` problem matcher in which they can further customize:

```json
{
  "type": "npm",
  "script": "watch",
  "problemMatcher": {
    "base": "$tsc-watch",
    "applyTo": "allDocuments"
  },
  "isBackground": true
}
```

Based on their documentation, further customization includes the following properties:
- `background`
- `fileLocation`
- `owner`
- `pattern`
- `severity`
- `source`

**Additional Information**
- [VS Code: Modifying Existing Problem Matchers](https://code.visualstudio.com/docs/editor/tasks#_modifying-an-existing-problem-matcher)

**Comment by elaihau** [comment]
As [the example in vscode documentation](https://code.visualstudio.com/docs/editor/tasks#_modifying-an-existing-problem-matcher) shows, "applyTo" is also modifiable.
