### ISSUE TITLE
[electron] The `Select All` command executes incorrectly

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6428]
### Description
 

I have forcefully enabled all menu items in electron to see the `Selection` menu (#6425). When I did a `Select All`, not the focus item was selected, but the monaco editor's content. It works perfectly in the browser.

Electron:
![screencast 2019-10-21 19-16-51](https://user-images.githubusercontent.com/1405703/67227997-ac71dd00-f438-11e9-97dc-28f10bb8bf4c.gif)

Browser:
![screencast 2019-10-21 19-19-16](https://user-images.githubusercontent.com/1405703/67228007-b3005480-f438-11e9-95e7-8f4e2ecbf3a3.gif)

Note, the `Select All` does not work in electron either when I close the editor and have the focus on an  `input`.

### Reproduction Steps

**OS and Theia version:**
macOS, f255f5a8c

**Diagnostics:**

**Comment by kittaakos** [comment]
We have to distinguish between Theia command and pure DOM command executions just like VS Code does:
https://github.com/microsoft/vscode/blob/f7118fd368dd088d66ed95527e5c16e9504c4081/src/vs/editor/browser/controller/coreCommands.ts#L1648-L1655

https://github.com/microsoft/vscode/blob/f7118fd368dd088d66ed95527e5c16e9504c4081/src/vs/editor/browser/controller/coreCommands.ts#L1607-L1611

We have to do the same for `Undo` and `Redo`.

**Comment by kittaakos** [comment]
VS Code makes differences whether the text has the focus in the active editor or not.

https://github.com/microsoft/vscode/blob/f7118fd368dd088d66ed95527e5c16e9504c4081/src/vs/editor/browser/controller/coreCommands.ts#L1602-L1603

We don't:
https://github.com/eclipse-theia/theia/blob/9457f8087bb421b7aa1c6cf124c6dfe57659df5f/packages/editor/src/browser/editor-keybinding-contexts.ts#L25-L28

**Comment by akosyakov** [comment]
There is `strictEditorTextFocus` for only text focus.
