### ISSUE TITLE
Plugins not loading from plugins folder

### ISSUE THREAD

**Issue by dannaf** [eclipse-theia/theia#6429]
### Description
Placing a vscode `.vsix` plugin file in a `plugins` folder while building theia from source does not work for loading the plugin when starting theia.

### Reproduction Steps
Following the vscode plugin instructions [here](https://github.com/eclipse-theia/theia/wiki/Testing-VS-Code-extensions), and the building instructions [here](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start):
`git clone https://github.com/eclipse-theia/theia`
`cd theia`
`nvm use 10`, since node 10 is stated as the preferred version
`yarn`
`mkdir plugins`
`cd plugins`
`curl -OJ 'https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/java/0.51.0/vspackage'`, downloads the vscode redhat java extension, which was tested here: https://github.com/eclipse-theia/theia/issues/6136#
`cd ../examples/browser`
`yarn theia build`
`yarn theia start`

**OS and Theia version:**
Theia source: [f255f5](https://github.com/eclipse-theia/theia/commit/f255f5a8cb22010aacb8196c8a8f248e111e9945)
Theia backend: Ubuntu 18.04 LTS
Theia frontend: Windows 10, Chrome 77
Backend node: v10.16.3 (npm v6.9.0)

**Diagnostics:** 
```
$ yarn theia start
yarn run v1.17.3
$ /home/my_path/theia/node_modules/.bin/theia start
root INFO Theia app listening on http://localhost:3000.
root INFO unzipping the VS Code extension 'redhat.java-0.51.0.vsix' to directory: /tmp/vscode-unpacked/redhat.java-0.51.0.vsix
root ERROR Failed to resolve plugins from 'local-dir:../../plugins' Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
    at Object.exports.decode (/home/my_path/theia/node_modules/tar-stream/headers.js:267:43)
    at Extract.onheader (/home/my_path/theia/node_modules/tar-stream/extract.js:124:39)
    at Extract._write (/home/my_path/theia/node_modules/tar-stream/extract.js:250:8)
    at doWrite (/home/my_path/theia/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/my_path/theia/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Extract.Writable.write (/home/my_path/theia/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Gunzip.ondata (_stream_readable.js:709:20)
    at Gunzip.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
```

The same extension is successfully loaded in-app via `Deploy Plugin by Id`, resulting in:

```
root INFO unzipping the VS Code extension 'redhat_java.vsix' to directory: /tmp/vscode-unpacked/redhat_java.vsix
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/redhat_java.vsix
root INFO Resolved "vscode:extension/redhat.java" to a VS Code extension "java@0.51.0" with engines: { vscode: '^1.36.0' }
root INFO Deploying backend plugin "java@0.51.0" from "/tmp/vscode-unpacked/redhat_java.vsix/extension/dist/extension"
root INFO [hosted-plugin: 1313] PLUGIN_HOST(1313) starting instance
root INFO [7b8418fb-1d5b-4a17-bed3-28b625e73cfe] Sync of 1 plugin took: 15.20999998319894 ms
root ERROR Preference name collision detected in the schema for property: java.home
root ERROR Preference name collision detected in the schema for property: java.jdt.ls.vmargs
root ERROR Preference name collision detected in the schema for property: java.errors.incompleteClasspath.severity
root ERROR Preference name collision detected in the schema for property: java.configuration.updateBuildConfiguration
root ERROR Preference name collision detected in the schema for property: java.trace.server
root ERROR Preference name collision detected in the schema for property: java.import.maven.enabled
root ERROR Preference name collision detected in the schema for property: java.import.gradle.enabled
root ERROR Preference name collision detected in the schema for property: java.referencesCodeLens.enabled
root ERROR Preference name collision detected in the schema for property: java.signatureHelp.enabled
root ERROR Preference name collision detected in the schema for property: java.implementationsCodeLens.enabled
root ERROR Preference name collision detected in the schema for property: java.configuration.maven.userSettings
root ERROR Preference name collision detected in the schema for property: java.format.enabled
root ERROR Preference name collision detected in the schema for property: java.saveActions.organizeImports
root ERROR Preference name collision detected in the schema for property: java.import.exclusions
root ERROR Preference name collision detected in the schema for property: java.contentProvider.preferred
root ERROR Preference name collision detected in the schema for property: java.autobuild.enabled
root ERROR Preference name collision detected in the schema for property: java.completion.enabled
root ERROR Preference name collision detected in the schema for property: java.completion.overwrite
root ERROR Preference name collision detected in the schema for property: java.completion.guessMethodArguments
root ERROR Preference name collision detected in the schema for property: java.completion.favoriteStaticMembers
root ERROR Preference name collision detected in the schema for property: java.completion.importOrder
root ERROR Preference name collision detected in the schema for property: java.progressReports.enabled
root ERROR Preference name collision detected in the schema for property: java.format.settings.url
root ERROR Preference name collision detected in the schema for property: java.format.settings.profile
root ERROR Preference name collision detected in the schema for property: java.format.comments.enabled
root ERROR Preference name collision detected in the schema for property: java.format.onType.enabled
root WARN A command java.workspace.compile is already registered.
root INFO [7b8418fb-1d5b-4a17-bed3-28b625e73cfe][redhat.java]: Loaded contributions.
root INFO [7b8418fb-1d5b-4a17-bed3-28b625e73cfe] Load contributions of 1 plugin took: 188.71000001672655 ms
root INFO [hosted-plugin: 1313] PLUGIN_HOST(1313): PluginManagerExtImpl/init()
root INFO [hosted-plugin: 1313] PLUGIN_HOST(1313): initializing(java@0.51.0 with /home/my_path/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
root INFO [7b8418fb-1d5b-4a17-bed3-28b625e73cfe][redhat.java]: Started plugin.
root INFO [7b8418fb-1d5b-4a17-bed3-28b625e73cfe] Start of 1 plugin took: 132.60000001173466 ms
```

**Comment by akosyakov** [comment]
> https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/java/0.51.0/vspackage

it is not a proper URL, a proper marketplace URL should be similar to `https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/Go/0.11.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage`

**Comment by dannaf** [comment]
These result in slightly different files:

**URL 1**:
https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/2019.10.41019/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
--> `Microsoft.VisualStudio.Services.VSIXPackage` (40080395 bytes)

**URL 2**:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2019.10.41019/vspackage
--> `ms-python.python-2019.10.41019.vsix` (38926987 bytes)

**Method 3**:
Clicking 'download' [here](https://marketplace.visualstudio.com/items?itemName=ms-python.python)
--> Same file as from **URL 2** (that's how I acquired URL 2)


However, the url I used previously ([URL 2](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2019.10.41019/vspackage)) is the same as when manually downloading the extension, which I would expect to work given how [the instructions ](https://github.com/eclipse-theia/theia/wiki/Testing-VS-Code-extensions) just say to download the `.vsix` file.  So maybe the instructions could be clarified.

____

Using the file from [URL 1](https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/2019.10.41019/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage) seems to have solved my problem, with renaming it to a `.vsix` extension in the plugin folder and also starting using `yarn run start` (not `yarn theia start`)

**Comment by akosyakov** [comment]
Legally only VS Code or Visual Studio, not even open source  VS Code built from sources, can be used to deploy vsix files downloaded from VS Code marketplace, that's why an instructions says to google.

**Comment by dannaf** [comment]
Thanks @benoitf!  Good lesson
