### ISSUE TITLE
On Safari the cursor in the command palette is placed before the >

### ISSUE THREAD

**Issue by tony--** [eclipse-theia/theia#6434]
<img width="756" alt="Screen Shot 2019-10-22 at 1 01 44 PM" src="https://user-images.githubusercontent.com/513830/67279853-20a99080-f4cc-11e9-82a8-8d3dc23b16db.png">

**Comment by vince-fugnitto** [comment]
@tony-- thank you for the issue, it has already been registered here https://github.com/eclipse-theia/theia/issues/6011

**Comment by tony--** [comment]
Thanks for the pointer @vince-fugnitto!

**Comment by vince-fugnitto** [comment]
@tony-- no problem, if you'd like to try and resolve the issue please let me know! :)

**Comment by vince-fugnitto** [comment]
@tony-- I managed to find a fix for it, thanks for pointing out the problem again! 
https://github.com/eclipse-theia/theia/pull/6435
