### ISSUE TITLE
Theia is free ?

### ISSUE THREAD

**Issue by lucked** [eclipse-theia/theia#6445]
HI theia is free for commercial projects?
its possible implement this in my online course platform for free?

**Comment by akosyakov** [comment]
Yes, it is free to integrate in your platform. Eclipse Theia is an open source project under Eclipse Foundation. It's distributed under EPL2: https://github.com/eclipse-theia/theia#license

**Comment by vince-fugnitto** [comment]
> Yes, it is free to integrate in your platform. Eclipse Theia is an open source project under Eclipse Foundation. It's distributed under EPL2: https://github.com/eclipse-theia/theia#license

The question has been previously answered, feel free to re-open the issue if you have any subsequent questions/issues :)
