### ISSUE TITLE
[editor-preview] preview ext can't use

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6446]
### Description

I test at gitpod also can't run
![image](https://user-images.githubusercontent.com/10203793/67502124-fe746600-f6b7-11e9-9993-7876cba8f74c.png)
This function was normal before
![image](https://user-images.githubusercontent.com/10203793/67502174-121fcc80-f6b8-11e9-8ed2-e2f66bd96b4d.png)

### Reproduction Steps

package.json

```
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/debug-nodejs": "next",
    "@theia/plugin-dev": "next",
    "@theia/editor": "next",
    "@theia/editor-preview": "next",
    "@theia/plugin-ext-vscode": "next",
    "@theia/textmate-grammars": "next",
    "@theia/git": "next"
  },
  "devDependencies": {
    "@theia/cli": "next",
    "@theia/debug": "next"
  },
  "scripts": {
    "postinstall": "download-debug-adapters"
  },
  "adapterDir": "plugins",
  "adapters": {
    "humao.rest-client": "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/humao/extension/rest-client/0.22.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage",
    "EditorConfig.EditorConfig": "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/EditorConfig/extension/EditorConfig/0.14.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage",
    "redhat.vscode-yaml": "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode-yaml/0.5.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage",
    "ms-vscode.vscode-typescript-tslint-plugin": "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/vscode-typescript-tslint-plugin/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage"
  }
}
```

- build `yarn --pure-lockfile && yarn theia build && yarn --production`
- start `node /home/theia/src-gen/backend/main.js /home/project --hostname=0.0.0.0`

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@502647092 are you perhaps missing the `@theia/preview` extension?

**Comment by vince-fugnitto** [comment]
@502647092 for information, the `editor-preview` is not the preview editor for markdown files, it is the extension used to preview editors (single-click). The `preview` extension is used to render/display all different types of files including markdown, and images.

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/67507448-7dba6780-f6c1-11e9-81bd-215dcef7d58a.png)
