### ISSUE TITLE
How can I use theia with an Apache webserver?

### ISSUE THREAD

**Issue by BluCobalt** [eclipse-theia/theia#6448]
Long story short, I want to have theia available at ide.`mydomain`.dev. Unfortunately, .dev is a tld that uses hsts ( http strict transport security, it just means you *have* to use ssl) so I need to use a webserver with ssl support. My end goal is to use it with Apache and a let's encrypt certificate. Thanks, I appreciate any help

**Comment by akosyakov** [comment]
Theia backend is express.js server. It can not be replaced with Apache server. But you can start it with `ssl` support, i.e. `theia start --ssl`, see in source code: https://github.com/eclipse-theia/theia/blob/c9f3a636b7735a96529c3132928c410aa5d7aea7/packages/core/src/node/backend-application.ts#L166

Alternatively, you should be able to put the apache server as a proxy server in the front of Theia server. Someone were able to do it already: https://github.com/eclipse-theia/theia/issues/6189#issuecomment-538662976

**Comment by BluCobalt** [comment]
That works, thanks!
