### ISSUE TITLE
 URI serialization error

### ISSUE THREAD

**Issue by BroKun** [eclipse-theia/theia#6456]
### Description
There are problems with URI serialization in webscoket and IPC mode , and I can't handle them as described in the Coding Guidelines.

1. The URI that got the `path` attribute could not be serialized, which made it impossible to send a request.
2. The URI received by the backend cannot get the correct information through `FileUri.fsPath`.

**Reproduction Steps:**
Create a new extension, add a protocol that uses URI parameters, try to use it.

**OS and Theia version:**
all
latest

**Diagnostics:**
1. When we access the `path` attribute of the `URI`, we create a private attribute `_path` in the URI. There is a circular reference in this attribute, causing `jsonrpc` to generate an error when processing it using the `JSON.stringify` method.
```
// before
"{"codeUri":{"$mid":1,"path":"/xxx/Untitled.ipynb","scheme":"file"}}"
```
```
// after
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Path'
    --- property 'root' closes the circle
    at JSON.stringify (<anonymous>)
    at <anonymous>:1:6
```
2. The URI we actually get through jsonrpc is Plain Object, unable to get the `codeUri.fsPath` property, only `codeUri.path`.

I noticed that in `plugin-ext`, we defined the serialization process using `rpc-protocol`. Although it is currently centralized, should it be used in extension?

**Comment by akosyakov** [comment]
URIs should be send as strings over JSON-RPC, e.g. `FileSystem.getFileStat` accepts a string not a URI. To serialize clients should use `URI.toString()`, to deserialize `URI.parse`.

**Comment by akosyakov** [comment]
I've added a clarification to the first point: https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines#uri-over-path

**Comment by BroKun** [comment]
@akosyakov Ok, I misunderstood the meaning of the documentation, and I even started to refactor my code. Let's close this issue.
