### ISSUE TITLE
[scm] support displays folders

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6458]
### Description

![](https://code.visualstudio.com/raw/images/1_39/scm.gif)

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by 502647092** [comment]
@akosyakov maybe rebuild build-in git plugin can support it ?

**Comment by akosyakov** [comment]
a dup of https://github.com/eclipse-theia/theia/issues/4835

>  maybe rebuild build-in git plugin can support it ?

no, it is implemented by VS Code scm widget, we have to reimplement our widget as a tree as well
