### ISSUE TITLE
Maven preference settings not available initially when the application starts with the preference page opened

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#6467]
### Description
Starting a maven project when the preference editor is open does not show the maven sub-folder

### Reproduction Steps
Tested on Electron.

Open a maven project
Open the preference settings page
Close the backend application (File->Close workspace) 
Restart the electron application (Open the workspace)
--> should open with the latest workspace and the preference settings page open in the editor
--> Look to find the tab for the maven settings, not there
Close the preference settings page
Re-open the preference setting page (File-> Settings-> Open Preference)
--> The maven tab settings is available 

**OS and Theia version:**
Electron on Ubuntu 16.04
Theia: master
```
Configuration: package.json: remove @theia/java
Plugins installed:
    redhat.java-051.0.vsix
    vscjava.vscode-java-debug-0.22.0.vsix
    vscode-java-dependency-0.6.0.vsix
    vscode-java-test-0.20.0.vsix
    vscjava.vscode-maven-0.19.1.vsix
```
**Diagnostics:** 
![MavenPrefNotAvailable](https://user-images.githubusercontent.com/419051/67792507-a5a62400-fa4f-11e9-867c-935a572843c3.gif)

**Comment by lmcbout** [comment]
Tested with the pr #6510 and it will solved this issue when merged.

**Comment by vzhukovskii** [comment]
PR https://github.com/eclipse-theia/theia/pull/6510 has been merged to the master. @lmcbout, recheck the new changes

**Comment by lmcbout** [comment]
Tested with the next version of Theia and the problem is solved
This issue will be fixed and merged in the next official release of Theia end of November
@vzhukovskii  Thanks,

**Comment by vzhukovskii** [comment]
@lmcbout you're welcome
