### ISSUE TITLE
Dockerfile in examples/browser fails to build.

### ISSUE THREAD

**Issue by kamilkloch** [eclipse-theia/theia#6474]
Running 
```
docker build -t x-theia .
``` 
results in 
```
E: Unable to locate package npm
The command '/bin/sh -c apt-get update && apt-get install -y npm && npm install -g yarn@1.3.2' returned a non-zero code: 100
```

**Comment by vince-fugnitto** [comment]
@kamilkloch thanks for pointing out the issue, it looks like the Dockerfile may have been neglected in the main repository. You can however find many examples of Theia docker images at the following repo: https://github.com/theia-ide/theia-apps.

**Comment by kamilkloch** [comment]
@vince-fugnitto Thanks from pointing me to the Theia example images!

**Comment by vince-fugnitto** [comment]
@kamilkloch glad to help!

**Comment by vince-fugnitto** [comment]
@marcdumais-work @svenefftinge should the Dockerfile present under the `example-browser` be removed (as it does not seem to be maintained) or should it be updated? I also understand that users must now log into `play-with-docker` to try it out.

**Comment by marcdumais-work** [comment]
+1 to remove. 

We already have a link to an equivalent from `theia-apps` in the [README](https://github.com/eclipse-theia/theia/blame/master/README.md#L49)
