### ISSUE TITLE
Question: relation between eclipse-theia and gitpod

### ISSUE THREAD

**Issue by koying** [eclipse-theia/theia#6484]
I'm a bit confused regarding the relation between eclipse-theia and "theia-ide" / gitpod.
Is gitpod only a "user" of theia or has theia been given to the eclipse foundation by gitpod?

**Comment by marechal-p** [comment]
Gitpod is "only a user of Theia".

The Theia project started under the theia-ide GitHub organization, and later became a project within the Eclipse Foundation.

Theia is a framework, and Gitpod is one product based on it.

**Comment by koying** [comment]
Okido. Thanks for the clarification.
