### ISSUE TITLE
Update task schema according to installed extensions/plugins

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#6485]
### Description
Task schema should be updated according to installed extensions/plugins.

Task types support for installed plugins is coming with [the PR](https://github.com/eclipse-theia/theia/pull/6483) from @elaihau  - thank you very much!
Would be nice to support other fields of task configurations.

### Reproduction Steps
1. Install `npm` vs code extension
2. Open `tasks.json` file
3. Start to create a new configuration: `"type": "npm",`
4. Press `Ctrl + space` = > you can see that expected  `script` field is absent in the list of the suggestions.

**Expected behavior:**
vs code displays the filed:
![script_vscode](https://user-images.githubusercontent.com/5676062/68106749-4468cf80-feeb-11e9-9b6b-b1a38de25185.png)

and warning:
![warning_npm](https://user-images.githubusercontent.com/5676062/68106773-55194580-feeb-11e9-8177-984805f4c9b5.png)

I tested the same behavior for `typescript` task:
![tsc_warning](https://user-images.githubusercontent.com/5676062/68106918-cb1dac80-feeb-11e9-88aa-631a7ffd0e41.png)

**OS and Theia version:**
Ubuntu 18.04.1
Theia version: 05f2e07bb77637723e6720231342b9accesta01a159

**Comment by elaihau** [comment]
I can resolve this one as the first step of fixing #6482

**Comment by ShimonBenYair** [comment]
@elaihau 

i have took your change, installed eslint and npm vs code extension in my theia/plgins folder.
But it fails to recognize a task of type "npm" , see screenshots  :
![npm_installed_plugin](https://user-images.githubusercontent.com/18531202/68279660-93923a00-007c-11ea-9c4d-414561b19029.gif)
![npm_type_not_dispaly](https://user-images.githubusercontent.com/18531202/68279661-93923a00-007c-11ea-9a0e-6ef80965affc.gif)

**Comment by elaihau** [comment]
@ShimonBenYair 
Thank you for the review !
I guess we installed different vs code extensions, my plugins view looks like this:

![Screenshot from 2019-11-06 07-09-25](https://user-images.githubusercontent.com/37082801/68297262-7cdfe900-0064-11ea-9f11-e2ee69c8c7ce.png)

**Comment by akosyakov** [comment]
@elaihau It would be helpful it you provide how to install correct VS Code extensions.

**Comment by ShimonBenYair** [comment]
@elaihau 
Thanks for the answer.
can you write the  link for the npm extension you installed ?

**Comment by RomanNikitenko** [comment]
@ShimonBenYair 
I use [these](https://github.com/theia-ide/vscode-builtin-extensions) extensions for testing

**Comment by ShimonBenYair** [comment]
@elaihau   @RomanNikitenko 

I can't build this project ( always get the error  :"spawn e2big")
can you please attach here the .vsix files as zip file ?

Thanks
Shimon

**Comment by elaihau** [comment]
@ShimonBenYair 
These are the ones I copied into the `theia/plugins` - you don't need to compile them.
[vs_extensions.zip](https://github.com/eclipse-theia/theia/files/3856718/vs_extensions.zip)

Could you please confirm if you can use them?

**Comment by ShimonBenYair** [comment]
sure, thanks lot

**Comment by ShimonBenYair** [comment]
@elaihau 

I can use them successfully.
Thanks a lot
