### ISSUE TITLE
Breakpoints do not appear in the editor gutter

### ISSUE THREAD

**Issue by DanTup** [eclipse-theia/theia#6488]
When I add breakpoints in Dart files, they show up in the debug side bar (bottom left) but not in the gutter for the editor:

![Screenshot 2019-11-04 at 2 43 38 pm](https://user-images.githubusercontent.com/1078012/68129532-a1777c00-ff11-11e9-9bd2-9e2f5385e041.png)

There are other screenshots in this issue tracker showing them appearing in the gutter, so I'm not sure what's up here.

**Comment by tsmaeder** [comment]
@vince-fugnitto does this happen for other debuggers as well or only dart?

**Comment by DanTup** [comment]
I'm not sure what the difference is, but this seems to be working ok now:

![Screenshot 2019-11-04 at 5 33 01 pm](https://user-images.githubusercontent.com/1078012/68143365-3c2f8500-ff29-11e9-8632-3d031d77185b.png)

**Comment by vince-fugnitto** [comment]
> @DanTup does this happen for other debuggers as well or only dart?

I've tried with other debuggers (example: running mocha tests) and it was fine.
I haven't tried myself the `dart` extension or debugger.

**Comment by svenefftinge** [comment]
Thanks for reporting. I've seen this issue too, where breakpoints are sporadically not rendered correctly.

**Comment by akosyakov** [comment]
Could someone to verify against https://github.com/eclipse-theia/theia/pull/5774? I have seen such issues during refactoring breakpoints to support other kinds and possibly addressed it already there.

**Comment by JonasHelming** [comment]
I have tried to reproduce this but couldn't.
This has not been reported again since Antons refactoring, so it is potentially solved. If this is observed again, please reopen the issue.
