### ISSUE TITLE
[vscode][plugin]support Visual Studio Online

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6491]
### Description

maybe need impl some api

```
Activating extension Visual Studio Online failed: vscode.workspace.registerRemoteAuthorityResolver is not a function.
```

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 Could you point to the extension?

We should for sure implement this API, regardless VS Code online, just to avoid runtime errors.

**Comment by akosyakov** [comment]
@502647092 Any updates on what you are trying to install?

**Comment by 502647092** [comment]
@akosyakov 
![image](https://user-images.githubusercontent.com/10203793/69938569-a3d0f400-1518-11ea-81c8-0310ea6af566.png)

**Comment by akosyakov** [comment]
Where can one download such extension? VS online is not open sourced

**Comment by 502647092** [comment]
[ms_vsonline_vsonline.zip](https://github.com/eclipse-theia/theia/files/3914056/ms_vsonline_vsonline.zip)
