### ISSUE TITLE
How to install and run Theia on Ubuntu??

### ISSUE THREAD

**Issue by soerendip** [eclipse-theia/theia#6493]
I don't find instructions on how to install and run the program. I am using ubuntu and installed the app with pip. But, I don't know how to start it. Also, I tried this command:

    python -m theia.cli --help
    > asyncio_ensure_future = asyncio.async           # Python < 3.5
    > SyntaxError: invalid syntax

**Comment by AlexTugarev** [comment]
There is a `theia` package for Python? Not really. 

https://pypi.org/project/theia/ it is if you've installed via pip.

If you're looking at examples for how to start Theia applications, see https://github.com/theia-ide/theia-apps

**Comment by vince-fugnitto** [comment]
@soerendip I believe you've might have mistaken the correct repository for the Python tool.
The correct repository is the following: https://github.com/theia-log/theia.

**Comment by soerendip** [comment]
I managed to start Theia with the docker container. But I would rather install it and run it without docker. There is no way to install and run Theia via `pip install` or `conda install`? I installed the theia package that is available on pip, but I am not sure whether this is the correct one. Apparently, there is no executable installed. The link that you provided only contains info about docker.

**Comment by vince-fugnitto** [comment]
> I managed to start Theia with the docker container. But I would rather install it and run it without docker. There is no way to install and run Theia via `pip install` or `conda install`? I installed the theia package that is available on pip, but I am not sure whether this is the correct one. Apparently, there is no executable installed. The link that you provided only contains info about docker.

@soerendip  I believe you've mistaken projects and are looking at https://github.com/theia-log/theia.
Are you trying to build and run your own IDE or are you trying to use https://github.com/theia-log/theia?

**Comment by soerendip** [comment]
I am trying to use a web-based ide called Theia. Not sure which one is which. I can run it with docker
    
    docker run -it --init -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia:next

**Comment by vince-fugnitto** [comment]
> I am trying to use a web-based ide called Theia. Not sure which one is which. I can run it with docker
> 
> ```
> docker run -it --init -p 3000:3000 -v "$(pwd):/home/project:cached" theiaide/theia:next
> ```

Yes that's correct, the Python tool is not this project.

You can find additional documentation on how to make your own IDE, or build this repository from sources:
- https://theia-ide.org/docs/composing_applications/
- https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start
