### ISSUE TITLE
[vscode] builtin extensions not recognized

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6495]
**Description**

I've created a custom VS Code [`plugin`](https://github.com/vince-fugnitto/ts-tools-plugin) which simply verifies that the `vscode-builtin-typescript-language-features` builtin extension correctly works. The plugin itself works perfectly in VS Code while in Theia it fails to find the extension.

**Screenshots**

_VS Code:_

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/68216550-0b922e80-ffaf-11e9-81cc-e01d3a309d33.png)

</div>

_Theia:_

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/68216623-28c6fd00-ffaf-11e9-873f-1870f6370933.png)

</div>

**Setup**

The following updates were made to the example-browser [package.json](https://github.com/eclipse-theia/theia/blob/master/examples/browser/package.json):

_Additions:_

```json
"@theia/vscode-builtin-typescript": "0.2.1",
"@theia/vscode-builtin-typescript-language-features": "0.2.1",
```

_Deletions:_

```json
"@theia/typescript": "^0.12.0"
```

---

Am I doing something wrong when attempting to consume builtin extensions in Theia?

**Comment by akosyakov** [comment]
You cannot install Theia plugins like Theia extensions. You should use `--plugins` cli options or `DEFAULT_THEIA_PLUGIN` env variable.

**Comment by vince-fugnitto** [comment]
> You cannot install Theia plugins like Theia extensions. You should use `--plugins` cli options or `DEFAULT_THEIA_PLUGIN` env variable.

Thank you! I was able to resolve the issue, I might create additional issues if I find problems regarding the plugin support.
