### ISSUE TITLE
[search-in-workspace] 'Clear Search Results' still highlights last result

### ISSUE THREAD

**Issue by ericschmidt14** [eclipse-theia/theia#6498]
### Description
When clicking 'Clear Search Results' in the _search-in-workspace_ widget of Theia, the last result remains highlighted in the editor. By clearing the search input manually, the same behavior occurs. I would expect, that the decoration of the code editor disappears like e.g. in VS Code.

![clear](https://user-images.githubusercontent.com/33349733/68244380-0667ca80-0015-11ea-92e6-b3d3f27c8010.gif)

### Reproduction Steps
- Open a workspace
- Press **Ctrl** + **Shift** + **F**
- Search for anything
- Click on a file in the result tree 
- Press **Clear Search Results** 

**Additional Information:**
- Theia: latest
- OS: Windows 10
- Browser: Google Chrome 77.0.3865.90

**Comment by ericschmidt14** [comment]
I patched this issue in `updateCurrentEditorDecorations()` of _search-in-workspace-result-tree-widget.tsx_. The decorations are only updated, if any file nodes are found, which is not the case when the search term is cleared. I will fix this and contribute.

**Comment by akosyakov** [comment]
@ericschmidt14 feel free to open a PR 🙏
