### ISSUE TITLE
tabs are not highlighted as active with the vertical split

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6502]
To reproduce:
- open one editor in the main area
- split another editor down relative to the first
- focus the second editor
- it is focused, but the tab is not highlighted as active

It's reproducible for all widgets and in the bottom area as well.

**Comment by Anasshahidd21** [comment]
@vince-fugnitto I tried reproducing the issue, but I think its already fixed.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I tried reproducing the issue, but I think its already fixed.

Sounds good, we can close the issue and re-open it if it persists.
I was unable to reproduce the problem following the reproduction steps.

**Comment by vince-fugnitto** [comment]
I was unable to reproduce the problem @akosyakov but what I do notice is that we have two files (potentially more if we split further) decorated as active at the same time, is it the intended behavior?

Example: (both files are active (blue))

![image](https://user-images.githubusercontent.com/40359487/73282623-e8e37080-41bf-11ea-8c23-0efb1029b594.png)

**Comment by akosyakov** [comment]
No, only focused should be active

**Comment by vince-fugnitto** [comment]
I believe the issue is fixed.

**Comment by msujew** [comment]
I believe this was a drive-by fix of https://github.com/eclipse-theia/theia/pull/10908.
