### ISSUE TITLE
[vscode] 'async' activation of extension does not work properly

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6504]
**Description**

I have created the following example [extension](https://github.com/vince-fugnitto/async-ext-activation) in VS Code which activates an existing external extension and provides a single command. The extension itself works correctly in VS Code but fails to work in Theia. I don't believe the `async` activation of an extension is handled properly. 

It looks like Theia fails during the call `await extension.activate()`.

<details>
<summary>Extension Activation</summary>

```ts
export const id = 'vscode.typescript-language-features';


export async function activate(context: vscode.ExtensionContext): Promise<void> {
	console.log('"async" verification extension is activating...');
	// Get the extension based on ID.
	const extension = vscode.extensions.getExtension(id);
	let disposable: vscode.Disposable[] = [];
	if (!extension) {
		disposable.push(
			vscode.commands.registerCommand('extension.verify-async', () => {
				// If the extension does not exist, display an error message.
				vscode.window.showInformationMessage(`ext "${id}" could not be found.`);
			})
		);
	} else {
		// Activate the builtin extension.
		await extension.activate();
		// Register the command which displays information regarding the extension.
		disposable.push(
			vscode.commands.registerCommand('extension.verify-async', () => {
				// Display information regarding the extension. The extension should be active since we `activated` it previously.
				vscode.window.showInformationMessage(`ext "${extension.id}" is ${extension.isActive ? 'active' : 'inactive'}.`);
			})
		);
	}
	context.subscriptions.push(...disposable);
}
```

</details>

**Setup**

The following builtin extensions were included as plugins:
- `typescript-basics`
- `typescript-language-features`

The following Theia extensions were removed:
- `typescript`
- `textmate-grammars`

cc @eclipse-theia/plugin-system

**Comment by akosyakov** [comment]
> It looks like Theia fails during the call await extension.activate().

What do you mean by fail? Nothing happens?

**Comment by akosyakov** [comment]
@vince-fugnitto Maybe https://github.com/eclipse-theia/theia/pull/6921/commits/401f143706278c7367eff027bd04dd0a4de4fa62 was a reason?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Maybe [401f143](https://github.com/eclipse-theia/theia/commit/401f143706278c7367eff027bd04dd0a4de4fa62) was a reason?

I will retry my extension against the latest changes.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Maybe [401f143](https://github.com/eclipse-theia/theia/commit/401f143706278c7367eff027bd04dd0a4de4fa62) was a reason?

It seems to work now, thank you! :+1:
