### ISSUE TITLE
Hide progress notifications without title

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#6506]
Description
Some notifications have no text. I _think_ that I've only seen the problem on progress notifications.

![image](https://user-images.githubusercontent.com/8888438/68333444-8722d700-00a6-11ea-9f50-ec81fb8d2248.png)

**OS and Theia version:** 
![image](https://user-images.githubusercontent.com/8888438/68333430-825e2300-00a6-11ea-915f-5d0310b7bf57.png)

**Diagnostics:** 

I don't see any pertinent log messages, but here they are anyway:
[theia-logs.txt](https://github.com/eclipse-theia/theia/files/3816496/theia-logs.txt)

**Comment by AlexTugarev** [comment]
@tetchel please help me to reproduce it.

**Comment by tetchel** [comment]
sure, do you know how to use eclipse Che? 

you can use this devfile to install my extension https://github.com/eclipse/codewind-che-plugin/blob/master/devfiles/latest/devfile.yaml
But replace the che-theia version (line 19) with 7.3 instead of 7.1

**Comment by AlexTugarev** [comment]
that's not what I meant. 😢 that doesn't help me to narrow it down.

'you at least which command you called, from which plugin? where to find the sources? maybe that helps.

**Comment by tetchel** [comment]
the plugin won't work properly outside of che, so that's why I directed you there

but sure here is one of the notifications that wasn't working in the screenshot
https://github.com/eclipse/codewind-vscode/blob/master/dev/src/codewind/connection/UserProjectCreator.ts#L138

but it seems to be intermittent, for example I just saw this one work 
https://github.com/eclipse/codewind-vscode/blob/master/dev/src/codewind/connection/Connection.ts#L349

**Comment by AlexTugarev** [comment]
@tetchel, please review the `withProgress` usage in https://github.com/eclipse/codewind-vscode.

I found several call sites leading to this [empty title](https://github.com/eclipse/codewind-vscode/blob/b7f64c125476940b83ad80ea7ac22bf3cfde2d0b/dev/src/codewind/connection/CLIWrapper.ts#L109) property.

**Comment by tetchel** [comment]
that's true, but the one pictured in the screenshot which I linked above is not one of them

the one you linked is meant to not be shown in some cases

**Comment by tetchel** [comment]
to clarify, when withProgress is called with an empty title in vs code, it doesn't show a notification at all, which is not the same as showing a notification with no text like I see here (but again, that's a different code path than the problem i'm seeing)

**Comment by AlexTugarev** [comment]
> when withProgress is called with an empty title in vs code

thanks for the hint @tetchel! going to check this, and align the behavior.

> but again, that's a different code path than the problem i'm seeing

if you know the call site which includes a `title` property with not `undefined` value, please tell point to that. I've a test project for `withProgress` API at https://github.com/AlexTugarev/txt, would be nice if you can contribute an isolated repro there. thanks!

**Comment by tetchel** [comment]
The 'fetching project types' progress, which is one of the ones shown in the original screenshot, has a `title` https://github.com/eclipse/codewind-vscode/blob/master/dev/src/codewind/connection/UserProjectCreator.ts#L138

**Comment by tetchel** [comment]
Okay, I dove into it. It is, as you correctly identified, that the `title` attribute is sometimes undefined. So I will remove those paths from my extension.

_However_ I still do consider this a Theia bug, because in VS Code if the `title` is not set, the progress is not shown, while in Theia, the progress is shown with blank text, which does not make sense.

**Comment by AlexTugarev** [comment]
@tetchel, I'm glad you could identify the cause 🙌 

I totally agree on aligning the behavior with vscode as [mentioned before](https://github.com/eclipse-theia/theia/issues/6506#issuecomment-550878621). Just need to figure out a way to tell it to extension developer, in order to give a hint that something won't work as expected, right? Die silent is a as bad as show empty.
