### ISSUE TITLE
support overwriting the label of detected tasks

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#6507]
### Description

It would be nice if overwriting the labels of detected tasks is supported in Theia.

### Reproduction Steps

It is a feature in vs code. Users are able to replace the label of a detected task with a custom one by add "label" property in the config.

See GIF below to see ***how it works in vs code***:

![Peek 2019-11-06 23-58](https://user-images.githubusercontent.com/37082801/68361313-5f0c9580-00f1-11ea-9ee1-9c10fa4fae53.gif)

**OS and Theia version:**

Ubuntu 18.04. Example browser. 

Version 0e16fe033a0e59e294891db8997175b31575b56f

**Diagnostics:** 

In theia, we don't handle the "label" property in TaskCustomization properly.

**Comment by lmcbout** [comment]
I also noticed that the task are being kept in the local storage. So when you restart the application, the "label" of the task remains even if you removed the label from the tasks.json

**Comment by tsmaeder** [comment]
@lmcbout that would be quite a different error than what this issue is about. Could you open a separate issue with steps to reproduce, please?

**Comment by lmcbout** [comment]
@tsmaeder I tried to reproduce the issue I reported last november with the latest Theia 1.0. I could not. If ever I can reproduce it, I will raise a new issue with steps to reproduce.
