### ISSUE TITLE
[documentation] improve the documentation of extension 'readme'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6518]
**Description**

The `readme` is the first source of documentation of every extension when consumed from `npm`. I believe that we can definitely improve the documentation overall by updating the documentation present in the readme of extensions, describing to end-users and adopters the overall functionality the extension provides.

Some example of relevant information can include:
- overall description of the extension
- high-level features (widgets, functionality)
- contributed commands
- contributed preferences

My only worry is that if we do happen to update the documentation present in the `readme`, it might be a significant effort to keep updating (and also remember to update).

The documentation in the `readme` is however insufficient, for example:
https://www.npmjs.com/package/@theia/workspace

**Reason**
- informs users and adopters the high-level description of the extension
- informs users of relevant features and functionality the extension provides
- describes available commands
- describes available preferences

**Comment by akosyakov** [comment]
My worry that it will be fragile. We need to decide what it stable and when create documentation around it. In this ways docs won't get outdated soon.

**Comment by vince-fugnitto** [comment]
> My worry that it will be fragile. We need to decide what it stable and when create documentation around it. In this ways docs won't get outdated soon. 

I understand your concern regarding having the docs being fragile. I think we should at least attempt at a high level to better describe an extension's functionality more so than what we have today. I think it'll also help adopters and users better understand the features of an extension.

> It could be done on per package basis, not like one huge PR. We can discuss what should be a stable API and how we mark it in the doc in first PR?

I understood that the API would be a separate step but I agree on the per package basis. I think determining what is stable API would be a good way forward. I was also wondering if we should generate the docs the same way the `plugin` extension does through Github pages.

**Comment by akosyakov** [comment]
> I understand your concern regarding having the docs being fragile. I think we should at least attempt at a high level to better describe an extension's functionality more so than what we have today. I think it'll also help adopters and users better understand the features of an extension.

High level description of responsibilities without mentioning particular APIs would be fine first step for me. But it is not really helpful when someone look for services and contribution points.

**Comment by m-vignesh** [comment]
> My worry that it will be fragile. We need to decide what it stable and when create documentation around it. In this ways docs won't get outdated soon. It could be done on per package basis, not like one huge PR. We can discuss what should be a stable API and how we mark it in the doc in first PR?

@akosyakov  , 
I have a couple of queries:
1. When (appx.)  will the stable version be released along with the full documentation?
2. Is there any temporary version of the full documentation? (Fine even if it is subject to change)

**Comment by akosyakov** [comment]
@m-vignesh currently we don't have capacity to identify stable APIs, for 1.0 only theia plugin will be considered as stable, but we for sure won't break apis which are used a lot regardless of 1.0 (it was like that always)

@vince-fugnitto @benoitf could you please share a link to github pages with full API docs, i could not find it, thank you!

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto @benoitf could you please share a link to github pages with full API docs, i could not find it, thank you!

Its [here](https://eclipse-theia.github.io/theia/docs/next/index.html) :) I think a link directly from the **readme** might be worthwhile so it is more discoverable.

**Comment by vince-fugnitto** [comment]
Closing in favor of #7229

**Comment by vince-fugnitto** [comment]
Reopened :)
