### ISSUE TITLE
update buildin plugins @theia/vscode-buildin-xxx

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6523]
### Description

update buildin plugins

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
transfered to https://github.com/theia-ide/vscode-builtin-extensions/issues/6

**Comment by akosyakov** [comment]
@502647092 All built-in extensions are published nightly now under `next` tag.
```bash
> npm info @theia/vscode-builtin-git@next dist.tarball
https://registry.npmjs.org/@theia/vscode-builtin-git/-/vscode-builtin-git-0.3.0-next.db32534bf1.tgz
```

You can follow the build job here: https://github.com/theia-ide/vscode-builtin-extensions/actions?query=workflow%3A%22Publish+Next%22

**Comment by 502647092** [comment]
@akosyakov ok thank you
