### ISSUE TITLE
how to disable plugin after install

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6528]
### Description

how to disable plugin after install

### Reproduction Steps
**OS and Theia version:**
**Diagnostics:**

**Comment by vince-fugnitto** [comment]
Is it the same as un-deployment? (https://github.com/eclipse-theia/theia/issues/5507)
Or is the issue more about simply disabling the plugin but it still exists.

**Comment by akosyakov** [comment]
It is different, plugin is still installed but disabled.
