### ISSUE TITLE
Support background tasks

### ISSUE THREAD

**Issue by tolusha** [eclipse-theia/theia#6534]
### Description
We have `Task.isBackground` [1] which is supposed to use for background tasks.

[1] https://github.com/eclipse-theia/theia/blob/master/packages/plugin/src/theia.d.ts#L8304

https://github.com/eclipse-theia/theia/blob/145f9137176497ec0a02a720d2b4697b76cf2547/packages/plugin/src/theia.d.ts#L8387-L8423

### Context
I try to adopt `quarkus` extension. This extension generates `preLaunch` task which is a background one. It means Theia should launch the task and then start a debug session without waiting when task is finished.

[1] https://github.com/redhat-developer/vscode-quarkus

**Comment by tsmaeder** [comment]
The todo's here are:

1. The debugger should not wait for tasks that are marked "background"
2. Problem matchers should fire events when matching certain start/end patterns. The debugger (task watcher) needs to listen to those issues and act accordingly.

**Comment by tsmaeder** [comment]
The issue is that the debugger does not start the debug session, but first waits for the background task to finish. The debugger should listen for the "task finished" event (exact name will be different, see VS Code doc), and then start the debug session.

**Comment by ShimonBenYair** [comment]
Hi @tsmaeder 

I am working on it as part of the #5517 
I will send a pull request on few days ...
