### ISSUE TITLE
No grammar for this language id yaml

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6540]
### Description

```
logger-protocol.ts:112 root WARN No grammar for this language id yaml Error: No grammar provided for <source.yaml>
    at e._collectDependenciesForDep (https://127.0.0.1/bundle.js:14:312596)
    at e.<anonymous> (https://127.0.0.1/bundle.js:14:313092)
    at https://127.0.0.1/bundle.js:14:310646
    at Object.next (https://127.0.0.1/bundle.js:14:310751)
    at a (https://127.0.0.1/bundle.js:14:309494)
```

### Reproduction Steps

- install vscode ext `redhat.vscode-yaml`
- open yaml file

**OS and Theia version:**
**Diagnostics:**

**Comment by akosyakov** [comment]
@502647092 is it only a warning, or there is not syntax coloring as well?

**Comment by 502647092** [comment]
@akosyakov not syntax coloring
before it was normal

**Comment by vince-fugnitto** [comment]
@502647092 I tested the latest `master` and it seems to work correctly:

<div align='center'>

<img width="1382" alt="Screen Shot 2019-11-13 at 11 50 57 AM" src="https://user-images.githubusercontent.com/40359487/68785272-ea16ef80-060b-11ea-9687-da16b355f1a3.png">


</div>

**Comment by vince-fugnitto** [comment]
I verified again and it works correctly. I am able to install the plugin and whether I have an opened `.yml` file or not, the extension still works correctly and am able to get the highlighting :)

Please re-open the issue if the problem persists.

**Comment by 502647092** [comment]
@vince-fugnitto I test at master now it work correctly

**Comment by 502647092** [comment]
@vince-fugnitto 
![image](https://user-images.githubusercontent.com/10203793/69214411-df2b0480-0ba1-11ea-92f8-4d2ad5af9dfd.png)
I don't know what happen
highlighting miss after I reload window

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto
> I don't know what happen
> highlighting miss after I reload window

Do you mean just reloading the `browser` window?
I've tried reloading and it's working correctly, the `yaml` files still have their syntax highlighting.

**Comment by akosyakov** [comment]
In Gitpod periodically I see that some editors don't get highlighted, like 4 typesctips editors and only one does not work. I don't get any errors and impossible to reproduce.

**Comment by 502647092** [comment]
@vince-fugnitto I can't reopen this issue 
![image](https://user-images.githubusercontent.com/10203793/69294091-d855cd80-0c45-11ea-845c-77cee14603af.png)

**Comment by vince-fugnitto** [comment]
The syntax highlighting should now be provided by [vscode-builtin-yaml](https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/yaml-1.39.1-prel.vsix) once `@theia/textmate-grammars` is deprecated.

**Comment by akosyakov** [comment]
@vince-fugnitto don’t think that it will change anything in regards to this issue. Coloring itself is still implemented with vscode-textmate.
