### ISSUE TITLE
how to get message from the plugin

### ISSUE THREAD

**Issue by Gnails** [eclipse-theia/theia#6541]
### Description
hello, I succeed getting message in plugin with the webView function named "postMessage()",
is there  any way to receive message from the plugin? I use webView.onDidReceiveMessage(),It takes no effect. It seems to be the cause of "window.parent is undefined in the plugin",and I find the code(" delete window.parent;") in  the html  script label that the id is "webview-widget-codeApi"

### Reproduction Steps
this is my code to creat webView:
    const panel = theia.window.createWebviewPanel(
                    "div",
                   "unity",
                    theia.ViewColumn.Active,
                    {
                        enableFindWidget:true,
                        retainContextWhenHidden:true,
                        enableScripts: true
                    }
                );
                panel.webview.onDidReceiveMessage((e)=>{
                    console.log("mesg:"+e.data["creator"])
                })
                panel.webview.html = IoTWebview.generateHTML(
                    args[0]
                );
                panel.webview.postMessage("ok u right")

this is the plugin html :
    <html>
          <script type="text/javascript">
          async  function messagePost() {
            p=window.parent
            if(p==undefined)
            console.log("p is undefined")
            else
           p.postMessage({
                creator:"nihao"
      
            },"http://localhost:3000")
            
         }
         
         window.onload = function () {
             var btn = document.getElementById("postbtn");
             btn.onclick = function () {
                 messagePost()
             }
             window.addEventListener("message", (ev) => {
                console.log("frame:"+ev.data)
            })
         }          
          </script>        
        <body>
          <div> script has been loaded</div>
          <button id="postbtn">click to post message</button>
        </body>
        </html>

**Comment by akosyakov** [comment]
`onDidReceiveMessage` should work, do you have a VS Code extension to reproduce? 

webviews are getting aligned with VS Code implementation right now: https://github.com/eclipse-theia/theia/pull/6465 If it works against the PR, you will need to wait a bit, sorry

**Comment by Gnails** [comment]
> `onDidReceiveMessage` should work, do you have a VS Code extension to reproduce?
> 
> webviews are getting aligned with VS Code implementation right now: #6465 If it works against the PR, you will need to wait a bit, sorry

thank a lot^.^ ,  It  use object acquired by acquireVsCodeApi() instead of window.parent  to postMessage() , there is a example in https://code.visualstudio.com/api/extension-guides/webview

**Comment by akosyakov** [comment]
> It use object acquired by acquireVsCodeApi() instead of window.parent to postMessage() 

Yes, that's how it should work. `parent` is deleted to isolate webview window from the parent window.

**Comment by Gnails** [comment]
ok
