### ISSUE TITLE
display path to a new file in create file/folder dialog

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6544]
Creation of a file based on a selection, sometimes it is tricky to figure out from UI where file is going to be created. Seeing the path would be helpful. One has to use `LabelProvider.getLongName` to get a proper path to display.

**Comment by vince-fugnitto** [comment]
@akosyakov do you propose we display the path directly in the file dialog?

**Comment by akosyakov** [comment]
Yes, there is space above the input field.
