### ISSUE TITLE
[navigator] Explorer is not updated after creating a new folder

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6548]
### Description
 

New folders are not visible in the `Explorer` after creation. I have to collapse and expand the parent of the new folders to see them.

![screencast 2019-11-14 13-56-45](https://user-images.githubusercontent.com/1405703/68859277-33883d00-06e7-11ea-889b-93652f450aed.gif)

### Reproduction Steps

 - Create a new folder. (It is not visible, it **should**.)
 - Collapse and expand the parent of the new folder. (The new folder is not visible.)

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
Something wrong with fs watching probably :( One has to investigate.

**Comment by Anasshahidd21** [comment]
I tried testing it, and it works on my machine. I wanted to know if this is still a issue that we should be looking at?

**Comment by kittaakos** [comment]
> I tried testing it

Thanks for taking care of it! 👍 

> and it works on my machine

I can confirm. fd2d38434

> I wanted to know if this is still a issue that we should be looking at?

Good point, let's close it now, we can reopen if the problem pops up again.
