### ISSUE TITLE
[vscode][plugin] Indication when plugins/vscode are activated

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#6550]
### Description

Some times plugins/vscode extensions take time to activate on theia startup or on other event.
Until it is activated the functionality is not available for the end user.
I believe that in VS Code there are messages showing the user that vscode extensions are now activated. (https://github.com/TypeFox/vscode/blob/9f3bb89b857a0ceb37ce1eee17a860a7b54ab62d/src/vs/workbench/contrib/extensions/browser/extensionsActivationProgress.ts#L31)
I suggest to have that in theia as well.

This also relevant to reconnect flow where plugins are reloaded.

### Reproduction Steps

- Start theia with several vscode extensions that take some time to activate on startup
- There is no indication while activating unlike vscode

**OS and Theia version:**
All

**Diagnostics:** 
N/A

**Comment by akosyakov** [comment]
So you mean run blueish progress bar in the plugin view while plugin is activating? Could you provide UI how VS Code does it?

**Comment by akosyakov** [comment]
Checked with VS Code, it is just a message in the status bar. Let's do it. PRs are welcomed!
