### ISSUE TITLE
Adopt LSP 3.15 `window/workDoneProgress` family of messages

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse-theia/theia#6553]
LSP is going to have support for showing an operation progress.
https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workDoneProgress

Support for this message in the language client component is needed.

**Comment by akosyakov** [comment]
@AlexTugarev Should be straighforward to implement with new progress services API?

**Comment by AlexTugarev** [comment]
The protocol actual looks quite familiar ;-) 
The payload is interesting, I'm curious to see it's integration in insiders.
