### ISSUE TITLE
QuickpickInput / canPickMany result

### ISSUE THREAD

**Issue by benoitf** [eclipse-theia/theia#6557]
### Description
When using `QuickPickInput`, if `canPickMany` flag is given
https://github.com/microsoft/vscode/blob/1876ce6361634423d0d5534b12dad1270c1373ff/src/vs/vscode.d.ts#L1630

It should always return an array as result

note: it does not provide multiple selection support, just comply with expected result.

### Reproduction Steps
Trying extension using `canPickMany` and expecting array result is failing. (like result.forEach)

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
I believe it is not supported yet https://github.com/eclipse-theia/theia/issues/5673. Is it a duplicate?

**Comment by benoitf** [comment]
@vince-fugnitto it's not to support the display, just to make compliant the result that should be an array.
It's like avoiding crash

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto it's not to support the display, just to make compliant the result that should be an array.
> It's like avoiding crash

Thanks I understand!
