### ISSUE TITLE
Running a standalone frontend.

### ISSUE THREAD

**Issue by 5sWind** [eclipse-theia/theia#6560]
### Description
 
How to run a standalone frontend without theia backend.

### Reproduction Steps

**OS and Theia version:** 0.12

**Diagnostics:**

**Comment by marechal-p** [comment]
Why?

**Comment by 5sWind** [comment]
> Why?

Because the architectures like microservice or blockchain of applying theia, on most time they’re not necessarily required backend. The backend and frontend should be pluggable.

**Comment by akosyakov** [comment]
Theia is not designed to run without the backend. It relies on many JSON-RPC services, e.g. to provide languages or filesystem access. In theory, if you can reimplement them when it is possible, but it would be a lot of development and maintenance work.

**Comment by 5sWind** [comment]
thx.
