### ISSUE TITLE
copy whole directory recursively

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#6563]
### Description
 

Is there any way to copy directory recursively?
I am looking at the Filesystem API but I can see copy API for a single file.

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
`FileSystem.copy(sourceUri, targetUri, { recursive: true })`?

**Comment by vince-fugnitto** [comment]
@dhananjayharel you can use what Anton said:

https://github.com/eclipse-theia/theia/blob/d84655dee2a315c577ac806cb3a4d0790e8effba/packages/filesystem/src/common/filesystem.ts#L79-L84
