### ISSUE TITLE
[problems] support preference to control default severity level

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6570]
**Description**

Proposal to include a new preference to control the default **severity** of problem markers:

| Preference Value | Preference Description |
|:---|:---|
| `all` (default) | display all problem marker severities |
| `info` | display problem markers with severity `info` or higher |
| `warning` | display problem markers with severity `warning` or higher |
| `error` | display problem markers with severity `error` or higher |

This will allow users to greatly reduce the noise of problem markers if they so choose.

**Comment by akosyakov** [comment]
Should not we have rather a filter in the problems view similar to VS Code?

**Comment by vince-fugnitto** [comment]
> Should not we have rather a filter in the problems view similar to VS Code?

I was hoping to have both eventually :)
With a filter, a user who does not care about `hints` would constantly need to re-filter so I thought a preference controlling the default minimum would be nice as well.
