### ISSUE TITLE
problems: update problem marker sorting (severity, line, column number)

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6572]
**Description**

Based on the following https://github.com/eclipse-theia/theia/issues/6572#issuecomment-594960684, problem markers should be consistently sorted using the following guidelines:

1. markers for a given resource are first sorted by `severity`
2. if the `severity` are equal, sort by lowest line number
3. if the `severity` and `line number` are equal, sort by lowest column number
4. if all props are equal, do not perform a sort

Example:
```
example/a.ts
- error [typescript] "message" (1, 20)
- error [typescript] "message" (2, 10)
- error [typescript] "message" (4, 10)
- warning [typescript] "message" (1, 10)
- info [typescript] "message" (3, 10)

example/b.ts
- error [typescript] "message" (3, 6)
```
<details>

<summary>Original Post</summary>

<br />
Currently, _problem markers_ are sorted based on `line number + position`.

I propose that a new preference is created which controls the sorting behavior of markers present in the problems widget, by sorting based on `severity + line number + position`.

For example:
```
example/a.ts
- warning [typescript] "message" (1, 10)
- error [typescript] "message" (1, 20)
- error [typescript] "message" (2, 10)
- info [typescript] "message" (3, 10)
- error [typescript] "message" (4, 10)
```

Can also be sorted as:
```
example/a.ts
- error [typescript] "message" (1, 20)
- error [typescript] "message" (2, 10)
- error [typescript] "message" (4, 10)
- warning [typescript] "message" (1, 10)
- info [typescript] "message" (3, 10)
```

</details>

**Comment by akosyakov** [comment]
Or just do it like that always?

**Comment by vince-fugnitto** [comment]
> Or just do it like that always?

You mean as in sort by `severity + line number + position` always?
I guess it's up to the team, but if we want to support the default behavior present in VS Code, I thought a preference might be nice so users can choose what they'd like.

**Comment by akosyakov** [comment]
>  if we want to support the default behavior present in VS Code,

They don't sort by severity?

**Comment by vince-fugnitto** [comment]
> > if we want to support the default behavior present in VS Code,
> 
> They don't sort by severity?

I might have been mistaken this entire time 🙈.
This is the behavior I see in Theia:

<div align='center'>

<img width="624" alt="Screen Shot 2019-11-19 at 8 30 43 AM" src="https://user-images.githubusercontent.com/40359487/69150607-08b33580-0aa7-11ea-860e-52a3918afd5c.png">


</div> 

It looks like we sort by severity, but also by the source and error message.
The (line number + position) seems to be one of the last things we sort by.

**Comment by akosyakov** [comment]
I actually not sure that Theia or VS Code does any sorting. It could be a responsibility of diagnostics owner. Were you able to find the code doing sorting?

**Comment by vince-fugnitto** [comment]
I verified and VS Code performs the following sorting (as described by their test case):
1. they sort by resources by [file path](https://github.com/microsoft/vscode/blob/2431cd6a2d85b335296acba0230d431fe47b41cb/src/vs/workbench/contrib/markers/test/browser/markersModel.test.ts#L66-L83)
2. they sort by [severity, line and column number](https://github.com/microsoft/vscode/blob/2431cd6a2d85b335296acba0230d431fe47b41cb/src/vs/workbench/contrib/markers/test/browser/markersModel.test.ts#L85-L120)

**Comment by JonasHelming** [comment]
Sorting can jump if two markers with identical severity, line and column from different owners are shown. This is due the fact that some owner (e.g. typescript) completely clear and re add their marker. I therefore suggest to also sort by owner to prevent the jump (see screens capture)
![orderproblemsview](https://user-images.githubusercontent.com/1052615/111390723-82672d80-86b3-11eb-8e5d-2e68dac57adb.gif)
