### ISSUE TITLE
[question] potential clash for '.theia' when using multiple theia-based products

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6573]
**Description**

I believe there may be a potential issue with the configuration folder (`.theia`) when a user uses multiple different theia-based applications.

For instance:
- `A` - theia-based application
- `B` - theia-based application

They will both share the same `.theia` folder under the user's home, and will have conflicts between _preferences_, _recentWorkspaces_, ...

Should we not allow applications to define their own config folder name, perhaps through the `package.json` similarly to `applicationName`. For instance, Armbed Studio would use `.armbed/settings.json` instead of `.theia/settings.json`.

**Comment by akosyakov** [comment]
We should always use https://github.com/eclipse-theia/theia/tree/master/packages/userstorage extension to manipulate such data and get rid of `.theia` hardcoded value in the codebase. Products should customize this extension with own value.

**Comment by vince-fugnitto** [comment]
I believe this issue is resolved now that we can rebind the configuration directory :+1:
This is the type of change we made and it worked correctly thanks to https://github.com/eclipse-theia/theia/pull/7214.
