### ISSUE TITLE
VSCode extension, activity bar view - no icon

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [eclipse-theia/theia#6575]
### Description
Ionide adds a custom activity bar view. This works just fine, with small issue - the button in the activity bar has no icon.

How it looks like in Code:

<img width="117" alt="Screenshot 2019-11-18 at 11 55 13" src="https://user-images.githubusercontent.com/5427083/69085093-56259900-09fa-11ea-84ad-0bf1968aacf3.png">

How it looks like in GitPod:

<img width="194" alt="Screenshot 2019-11-18 at 11 52 06" src="https://user-images.githubusercontent.com/5427083/69084858-f7601f80-09f9-11ea-86d6-380928c19e99.png">

Definition of the activity bar view in Ionide's extension definition:
https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/package.json#L511-L520

### Reproduction Steps

1. Go to https://gitpod.io/#https://github.com/Krzysztof-Cieslak/GitPodSample
2. Notice lack of F# icon in the activity bar
3. Click at the area under last visible icon to notice the button is there just without any icon

**OS and Theia version:**

GitPod

**Comment by vince-fugnitto** [comment]
@Krzysztof-Cieslak which browser are you using?
I tried your link (using Chrome):

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/69087625-c80adc00-0a14-11ea-9181-3f0628a66b7a.png)


</div>

**Comment by Krzysztof-Cieslak** [comment]
Hey, I haven't thought about that. 

The problem is present on Safari, both Chrome and Firefox works fine.

**Comment by vince-fugnitto** [comment]
> Hey, I haven't thought about that.
> 
> The problem is present on Safari, both Chrome and Firefox work fine.

Thanks for getting back, oddly enough it worked in all three browsers for me:

<div align='center'>


<img width="1280" alt="Screen Shot 2019-11-19 at 12 25 47 PM" src="https://user-images.githubusercontent.com/40359487/69170272-d5cd6980-0ac7-11ea-96f6-5e9e93d52d9d.png">

<img width="1284" alt="Screen Shot 2019-11-19 at 12 26 08 PM" src="https://user-images.githubusercontent.com/40359487/69170273-d5cd6980-0ac7-11ea-8a2c-f2bda27e09a4.png">

<img width="1282" alt="Screen Shot 2019-11-19 at 12 26 26 PM" src="https://user-images.githubusercontent.com/40359487/69170274-d5cd6980-0ac7-11ea-898e-94cfdb431849.png">


</div>

**Comment by vince-fugnitto** [comment]
@Krzysztof-Cieslak do you still experience issues with the icon?

**Comment by vince-fugnitto** [comment]
@akosyakov I've rechecked and the bug only exists in Gitpod (when using Safari).
I've tried with vanilla Theia and the icon is always displayed properly.

**Comment by vince-fugnitto** [comment]
Opened the issue in Gitpod: https://github.com/gitpod-io/gitpod/issues/969
