### ISSUE TITLE
Variables View Loses Expansion State when Stepping

### ISSUE THREAD

**Issue by ParOvBroadcom** [eclipse-theia/theia#6580]
### Description
When using the resume, step next or step in functions, the scope tree in the Variables view refreshes completely in Theia, this leads to a collapsed tree, while the tree in VSC remains to the previous state and leaves any expanded part as it is, by just refreshing whatever needs to. Is there a way to do the same in Theia?

### Reproduction Steps
Start a debug session using DAP through Theia. When stopped in a specific breakpoint expand the scope and maybe some of the variables. Resume or step in or step over to the next breakpoint. The variable tree is completely disappearing and reappearing (really fast) and thus it is collapsed to the original scope only

**Windows 10 and Theia version: 0.11.0**

**Diagnostics:** 
No diagnostics

**Comment by tsmaeder** [comment]
Changed the title to reflect the problem being described. Yeah, this behaviour is annoying.

**Comment by tolusha** [comment]
I can't reproduce. Is it os or browser specific issue?
![screencast-localhost_3000-2019 12 04-17_20_38](https://user-images.githubusercontent.com/1640675/70155269-9d7a7d80-16ba-11ea-840a-39007c04a965.gif)

**Comment by tolusha** [comment]
@ParOvBroadcom Is it still actual?

**Comment by akosyakov** [comment]
It could be timing issue, we debounce with 400ms: https://github.com/eclipse-theia/theia/blob/dbe5b5aab829a0ac1ca81193089cf0e0ca1aa384/packages/debug/src/browser/view/debug-variables-source.ts#L41

@ParOvBroadcom Could you provide more concrete steps?

**Comment by ParOvBroadcom** [comment]
It doesn't work properly in either way (resume or step over)
First having a running session
![1](https://user-images.githubusercontent.com/54706061/70250059-9a949100-177d-11ea-8f05-e64fa877e13e.png)
Then expanding the local variables
![2](https://user-images.githubusercontent.com/54706061/70250067-9bc5be00-177d-11ea-9b52-54d9d442f3c6.png)
Clicking on Resume
![3](https://user-images.githubusercontent.com/54706061/70250066-9bc5be00-177d-11ea-8aeb-6a45b4eba32c.png)
It collapses the Local variables
![4](https://user-images.githubusercontent.com/54706061/70250065-9bc5be00-177d-11ea-9835-f8f83c77a221.png)
Expanding again the variables
![5](https://user-images.githubusercontent.com/54706061/70250064-9bc5be00-177d-11ea-8264-2e2e1a47ae00.png)
Clicking on step over
![6](https://user-images.githubusercontent.com/54706061/70250063-9b2d2780-177d-11ea-9cbc-aad5cfdc1f68.png)
Collapses the local variables also
![7](https://user-images.githubusercontent.com/54706061/70250060-9a949100-177d-11ea-8429-848efe2ce3be.png)

**Comment by akosyakov** [comment]
@ParOvBroadcom Is there a way to run your debug adapter or reproduce without it? It does not seem to happen with other.

**Comment by ParOvBroadcom** [comment]
@akosyakov What do you mean without "it"? This happens in Theia, but not in VScode.

**Comment by tolusha** [comment]
We need a debugger to reproduce the issue,
It can't be reproduced neither with node nor java debug.

**Comment by ishche** [comment]
> It could be timing issue, we debounce with 400ms:
> 
> https://github.com/eclipse-theia/theia/blob/dbe5b5aab829a0ac1ca81193089cf0e0ca1aa384/packages/debug/src/browser/view/debug-variables-source.ts#L41

I increase debounce and it makes things better.
@akosyakov seems you right about it. We have pretty big delays in communication to target.

@tolusha, unfortunately, we can't provide our debugger.

**Comment by akosyakov** [comment]
@ishche How much do you need to increase?

**Comment by tolusha** [comment]
@akosyakov 
@ishche 
I've submitted a draft PR to check if proposed solution make sense.
https://github.com/eclipse-theia/theia/pull/6734
