### ISSUE TITLE
"Compressed Folders" in Navigator

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#6583]
### Description
VS Code is in the process of adding support for "compressed folders" (see https://github.com/microsoft/vscode/issues/41627). This is a very useful feature, especially for languages with lots of empty dirs like Java.

**Comment by tsmaeder** [comment]
![image](https://user-images.githubusercontent.com/13163770/69152384-ad039f00-0adc-11ea-9ee5-eb13725d56f2.png)

**Comment by tsmaeder** [comment]
Screenshot kindly provided by @fbricon

**Comment by vince-fugnitto** [comment]
@tsmaeder duplicate of https://github.com/eclipse-theia/theia/issues/4783?

**Comment by tsmaeder** [comment]
I guess, but I like "compressed folders" better as a title :-) I searched issues but did not find the issue you referenced.

**Comment by vince-fugnitto** [comment]
> I guess, but I like "compressed folders" better as a title :-) I searched issues but did not find the issue you referenced.

Updated the title on the original issue :)
I'll close this one to avoid duplication.
