### ISSUE TITLE
Support UTF-8 for the LSP protocol 

### ISSUE THREAD

**Issue by XVilka** [eclipse-theia/theia#6597]
See the lengthy discussion here: https://github.com/microsoft/language-server-protocol/issues/376

It seems that theia is one of a few that uses UTF-16 https://github.com/Avi-D-coder/lsp-range-unit-survey

Would be nice if it will have UTF-8 support as well, at least optionally.

**Comment by akosyakov** [comment]
Theia is based on monaco-editor-core (VS Code editor) and monaco-languageclient. First there should be agreement to adopt it there. See also: https://github.com/TypeFox/monaco-languageclient/issues/188#issuecomment-556986838

**Comment by tsmaeder** [comment]
We no longer implement any lsp-related functionality. Closing.
