### ISSUE TITLE
[editor] chinese input method can't input when select content

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6603]
### Description

![temp](https://user-images.githubusercontent.com/10203793/69393440-1caf9f00-0d14-11ea-9502-f17727f52c13.gif)

select content and use input method will cause editor freeze
Maybe like #6459 

### Reproduction Steps
look gif

**OS and Theia version:**
**Diagnostics:**

**Comment by monaka** [comment]
Note: [your comment](https://github.com/eclipse-theia/theia/pull/6673#issuecomment-560985252) in #6673 by @502647092, the environment is:

* Windows10
* Chrome
* Chinese IME

**Comment by monaka** [comment]
@502647092 Could you open the developer tool in your browser running Theia.
I guess you'll find errors in the `console` tab.

**Comment by 502647092** [comment]
@monaka not have error in console

**Comment by 502647092** [comment]
@monaka I test at monaco had this error too

**Comment by 502647092** [comment]
I create issue at https://github.com/microsoft/monaco-editor/issues/1699
