### ISSUE TITLE
Support for "Remote - ssh"  extension on gitpod

### ISSUE THREAD

**Issue by KrishnaChaitanya-Gopaluni** [eclipse-theia/theia#6604]
### Description
 
Does theia on gitpod app supports "Remote - ssh" extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

Error message : Activating extension Remote SSH failed: n.env.onDidChangeLogLevel is not a function.

### Reproduction Steps

Tried installing "Remote-ssh" extension on Gitpod. The following error occurred as shown on the bottom right corner of the screenshot.

![Screenshot from 2019-11-21 21-15-18](https://user-images.githubusercontent.com/23066556/69400751-ae34f780-0ca7-11ea-8126-fc44be72142e.png)

**OS and Theia version:** On Gitpod app

**Diagnostics:** 
the follwing error occured
Activating extension Remote SSH failed: n.env.onDidChangeLogLevel is not a function.

**Comment by akosyakov** [comment]
This extensions is not open-sourced and have a license prohibiting using it with any other products except VS Code: https://marketplace.visualstudio.com/items/ms-vscode-remote.remote-ssh/license

cc @svenefftinge

**Comment by KrishnaChaitanya-Gopaluni** [comment]
Thanks.
