### ISSUE TITLE
[keybinding] wrong keybinding for "Open Preferences" on Mac (Electron): should be Cmd+, not Ctrl+,

### ISSUE THREAD

**Issue by jankeromnes** [eclipse-theia/theia#6606]
On Mac OS (Electron), the keybinding for `Settings > Open Preferences` is <kbd>Ctrl</kbd> + <kbd>,</kbd>.

Instead, it should be <kbd>Cmd</kbd> + <kbd>,</kbd> because that seems to be the expected keybinding, and it's what VS Code uses for `Preferences > Settings`.

Notes:
- This probably won't work in browsers, because it conflicts with the browser preferences keybinding, so we'll likely need different keybindings for Electron vs. browsers
- Requested by Arduino here: https://github.com/arduino/arduino-pro-ide/issues/16

**Comment by svenefftinge** [comment]
Could you also take care of the other 'non-native' keybindings, e.g. <kbd>Cmd</kbd> + <kbd>w</kbd>?
Also I think they should be registered in addition so we don't unnecessarily break electron users that already got familiar with our alternative bindings.

**Comment by jankeromnes** [comment]
Two excellent ideas, thanks! Will do.

**Comment by jankeromnes** [comment]
The keybinding is currently hard-coded as <kbd>Ctrl</kbd> + <kbd>,</kbd>, regardless of build or OS:

https://github.com/eclipse-theia/theia/blob/2938cd0e72ac03056925c9de8c6d706a34e2dd27/packages/preferences/src/browser/preferences-contribution.ts#L63-L68

I'll take a look at Windows to see if this actually works (in browser and in Electron).

**Comment by marechal-p** [comment]
Does replacing the `keybinding` field by `ctrlcmd+,` do the trick?

**Comment by jankeromnes** [comment]
> Does replacing the `keybinding` field by `'ctrlcmd+,'` do the trick?

This would almost do the trick, except:
- In Firefox, on Mac, `cmd+,` is intercepted by the browser (and opens the browser settings)
- Some Mac users may already be used to the non-standard `ctrl+,` shortcut, so it should probably still work (even if it's not the default)
