### ISSUE TITLE
Is there a list of theia extensions somewhere along with brief explanation of what each does?

### ISSUE THREAD

**Issue by kdvolder** [eclipse-theia/theia#6609]
Here's the crux of my problem... I'm just starting to explore putting together a Theia setup to use as a IDE. 

I'm following the instructions to build something using a 'package.json' file: 

https://theia-ide.org/docs/composing_applications

Where things are breaking down  for me is... I cannot seem to find out what kind of extensions I should/could add to this 'bare bones' setup to build an actually useful / usable Theia instance from.

The list in that tutorial is very bare-bones and does not really define a practically 'usable' development environment. Sure, that makes sense, every user may want to select what kind of languages / support / extension he really needs.

But without a good orgainised 'catalog' of available optional extensions one could want to add on it is kind of impossible to build this out to something more useful.

PS: The closest I've come to a 'list' is by using npm to provide a list of everything under Theia: https://www.npmjs.com/~theia

But this is...

- a bit disorganized.
- lacks useful summary descriptions of the different packages

It would also be helpful to have an example of something more 'full-featured'. E.g. maybe something that compares to the kind of thing you get when you install vscode (has already built-in support for many common languages etc.)

For consideration. When I'm building up my 'personalised' setup, it is probably much easier to start with something that has as many extensions already pre-installed as possible, and customise this by removing things that I don't think I need than the other way around (especially if its difficult to determine what sort of things are available to add).

**Comment by vince-fugnitto** [comment]
@kdvolder I'm happy to hear you starting to look into building your own IDE :)
I understand your concern about trying to discover extensions/plugins which you'd like to include.

We have some issues tracking improving the overall documentation of the project, as well as giving the most information to adopters and users about the available functionalities offered
(for example: https://github.com/eclipse-theia/theia/issues/6518).

Please note that the `example-browser` contains all available packages present in the main repository, but as an adopter, the idea would be to think of what end-user functionalities you'd like to be present. For example, let's say you want to display the `outline` for languages, then you'd add the `@theia/outline` extension. If users want to perform file-searching, then the extension should be included. Perhaps you can describe what type of IDE you'd like and we could assist you.

I'd like to have a central location for describing extensions, their commands, preferences, and their functionalities, and I believe a good place for that would be the [main website](https://theia-ide.org/).

**Comment by vince-fugnitto** [comment]
> The list in that tutorial is very bare-bones and does not really define a practically 'usable' 
> It would also be helpful to have an example of something more 'full-featured'. E.g. maybe something that compares to the kind of thing you get when you install vscode (has already built-in support for many common languages etc.)
> 
> For consideration. When I'm building up my 'personalised' setup, it is probably much easier to start with something that has as many extensions already pre-installed as possible, and customise this by removing things that I don't think I need than the other way around (especially if its difficult to determine what sort of things are available to add).

I think a good place to start would be checking the `example-browser` and seeing what you'd wanna keep/remove :)

https://github.com/eclipse-theia/theia/blob/b9969ba4870288a994e2a24294e96af33760df87/examples/browser/package.json#L16-L63

**Comment by kdvolder** [comment]
> Please note that the example-browser contains all available packages present in the main repository,

Great! Thanks, I'll refer to that then as my starting point from here on forward. 

> but as an adopter, the idea would be to think of what end-user functionalities you'd like to be present. 

Indeed, but its rather hard to select what you want to include if you don't know what functionality is available to opt-in or opt-out of.

> Perhaps you can describe what type of IDE you'd like and we could assist you.

In short.... something similar to vscode :-)

But we want to have a focus on Java spring boot development, so we definitely want the Java support as well as some specific vscode extensions (I understand we can now install vscode extensions relatively easily which is really great!).

Anyhow... thanks for your help so far.

> We also have example applications in the form of docker images if you'd like to try those:
https://hub.docker.com/u/theiaide

Being able to try these via docker image is quite nice really. But it would be great to also be able to see how these Docker images are built as well. What's in their Dockerfile and package.json? I assume the source for these images is available somewhere? I clicked around this github repo a bit but couldn't easily find them though. So adding a link to the docker image's readme would be very helpful for someone like me.

> I'd like to have a central location for describing extensions, their commands, preferences, and their functionalities, and I believe a good place for that would be the main website.

Yes, that would definitely be very helpful :-)

At my current stage of exploration, mainly I wouldn't need very detailed documentation. I.e. docs describing every preference and command in detail would be a bit overkill. I'd be more trying to determine at a fairly high level the kinds of functionality that a package provides (i.e. to choose if I want that or not). I.e. like you were describing earlier 'add this if you want users to be able to do text searches'.

**Comment by vince-fugnitto** [comment]
> Being able to try these via docker image is quite nice really. But it would be great to also be able to see how these Docker images are built as well. What's in their Dockerfile and package.json? I assume the source for these images is available somewhere? I clicked around this github repo a bit but couldn't easily find them though. So adding a link to the docker image's readme would be very helpful for someone like me.

Sure, the repository which contains the source code for all the Docker images is: https://github.com/theia-ide/theia-apps

**Comment by vince-fugnitto** [comment]
Closed by #7254

**Comment by vince-fugnitto** [comment]
If there is additional feedback on the current implementation (after #7254), we should create concrete issues for improvement.
