### ISSUE TITLE
Installing a vscode extension **pack** is not working

### ISSUE THREAD

**Issue by kdvolder** [eclipse-theia/theia#6611]
### Description

Installing a vscode 'extension pack' does not install the extensions in the pack

### Reproduction Steps

1. Create theia instance with this package.json

```
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next",
    "@theia/plugin-ext": "next",
    "@theia/plugin-ext-vscode": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
```

2. Use 'Plugin:  Deploy plugin by id' to install this: `vscode:extension/Pivotal.vscode-boot-dev-pack`

3. Observe that the dev pack is indeed installed, but nothing else is. 

This is wrong, since the devpack contains several vscode extensions which should have been installed.

See: https://github.com/spring-projects/sts4/blob/master/vscode-extensions/boot-dev-pack/package.json

Which has this:

```
 "extensionPack": [
    "Pivotal.vscode-spring-boot",
    "Pivotal.vscode-concourse",
    "Pivotal.vscode-manifest-yaml",
    "vscjava.vscode-spring-initializr",
    "vscjava.vscode-spring-boot-dashboard"
  ]
```

**OS and Theia version:**

Theia version: 0.13.0-next.0860ab1b
Ubuntu 18.04 (running inside ubuntu docker container).

**Comment by vince-fugnitto** [comment]
cc @eclipse-theia/plugin-system

**Comment by akosyakov** [comment]
We don't support `extensionPack` property yet. One has to improve this method: https://github.com/eclipse-theia/theia/blob/145f9137176497ec0a02a720d2b4697b76cf2547/packages/plugin-ext-vscode/src/node/scanner-vscode.ts#L51-L63

**Comment by vince-fugnitto** [comment]
> We don't support `extensionPack` property yet. One has to improve this method:
> 
> https://github.com/eclipse-theia/theia/blob/145f9137176497ec0a02a720d2b4697b76cf2547/packages/plugin-ext-vscode/src/node/scanner-vscode.ts#L51-L63
> 
> It would be interesting to know why `exetnsionPack` is needed in addition to `extensionDependencies`. Maybe there is different semantics.

Ideally we'd likely need to support the entire `manifest`: https://code.visualstudio.com/api/references/extension-manifest

**Comment by akosyakov** [comment]
@vince-fugnitto for dependencies, not. Most of other attributes are handled already: https://github.com/akosyakov/theia/blob/dafd7ca0e988fcec958d3435f1b94df7bfeadf71/packages/plugin-ext/src/common/plugin-protocol.ts#L38-L57 Or will be used by the vsx registry extension, e.g. markdown. What is missing?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto for dependencies, not. Most of other attributes are handled already: https://github.com/akosyakov/theia/blob/dafd7ca0e988fcec958d3435f1b94df7bfeadf71/packages/plugin-ext/src/common/plugin-protocol.ts#L38-L57 Or will be used by the vsx registry extension, e.g. markdown. What is missing?

I just wanted to reference the docs in the issue :)
I tried my hand at adding the functionality to support extension packs.
