### ISSUE TITLE
Provide a easy way to uninstall a vscode extension after installing it via 'Deploy plugin by id'

### ISSUE THREAD

**Issue by kdvolder** [eclipse-theia/theia#6612]
Since there is a command to install a vscode plugin by id... shouldn't there also be a similar command to uninstall it? Or maybe I should be able to do this via the 'Plugins' view? This doesn't seem to be the case. I can see installed plugins but found no way to remove them.

**Comment by vince-fugnitto** [comment]
@kdvolder the issue has already been reported in other issues, please see their discussions:
https://github.com/eclipse-theia/theia/issues/6528 https://github.com/eclipse-theia/theia/issues/5507. Closing the issue since it is a duplicate.
