### ISSUE TITLE
Limit opened file size

### ISSUE THREAD

**Issue by shahar-h** [eclipse-theia/theia#6615]
### Description
Currently there is no limit to opened files size. as a result, when opening a huge file it could lead to out of memory issues.

### Reproduction Steps
* Create a file with 1GB random text data via terminal:
`openssl rand -base64 $((1024*1024*1024)) >> large.out`
* Open the file via file explorer.
* As a result, Theia main process reaches ~1.5GB memory, which could lead to out of memory issues on hosted environments with limited memory.

When trying the same in vscode the following error message appears:
![image](https://user-images.githubusercontent.com/16555289/69496491-672f4800-0edb-11ea-9e88-9442eef476eb.png)

**Comment by vince-fugnitto** [comment]
@shahar-h thank you for the issue!
At the moment, we already have an existing issue tracking the feature #4731. I will close this one as it's a duplicate.
