### ISSUE TITLE
application log viewing in output tab

### ISSUE THREAD

**Issue by NitinKhandelwal1947** [eclipse-theia/theia#6617]
### Description
I am running a script in theia which write its execution log in a log file. Is there anyway to view the content of the log file in Output tab. Is there anyway to customised Output tab to view user defined log file.  

### Reproduction Steps
 I took ```eclipse-theia/theia``` code base and running a script in theia which write its execution log in a log file. 

**OS and Theia version:**
yarn version:- 1.7.0
node version:- 10.15.3
npm version:- 4.6.1
Windows 10 

**Diagnostics:**

**Comment by akosyakov** [comment]
A custom extension can inject `OutputChannelManager`, create a new channel and write down content to it

**Comment by NitinKhandelwal1947** [comment]
> A custom extension can inject `OutputChannelManager`, create a new channel and write down content to it

@akosyakov Thanks for your quick reply. Do you have any sample example for the same.

**Comment by westbury** [comment]
This issue has been raised in https://github.com/eclipse-theia/theia/issues/4297 and  https://github.com/eclipse-theia/theia/pull/5039 is an attempt to address this .  This PR results in log content being sent to the output view.  It is configured to do so only for electron because the logs would be available to the server admin anyway in the browser version.

The PR has been rather forgotten, partly because we are no longer dependent on it in our Theia-based product.  However I am happy to resurrect it if it would be useful to you.

**Comment by kittaakos** [comment]
> been rather forgotten,

Not really, but it would be better to use a connection-scoped injection instead of the current approach. (And I forgot to click on the button to show my comments.)

**Comment by NitinKhandelwal1947** [comment]
> This issue has been raised in #4297 and #5039 is an attempt to address this . This PR results in log content being sent to the output view. It is configured to do so only for electron because the logs would be available to the server admin anyway in the browser version.
> 
> The PR has been rather forgotten, partly because we are no longer dependent on it in our Theia-based product. However I am happy to resurrect it if it would be useful to you.

@westbury I have tried the approach mentioned  in https://github.com/eclipse-theia/theia/pull/5039
and modified all the files linked to this PR. But when i try to run ```yarn``` on root folder i am getting below error.

```
@theia/output: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run prepare
lerna ERR! error Command failed with exit code 1.
lerna ERR! error Command failed with exit code 1.
lerna ERR! 
lerna ERR! $ yarn run clean && yarn run build
lerna ERR! $ theiaext clean
lerna ERR! $ theiaext build
lerna ERR! [compile] theiaext compile exited with code 0
lerna ERR! [lint] 
lerna ERR! [lint] ERROR: /Users/Documents/theia/packages/output/src/browser/output-channel-readers.ts:46:5 - expected call-signature: 'onProcessOutput' to have a typedef
lerna ERR! [lint] ERROR: /Users/Documents/theia/packages/output/src/browser/output-channel-readers.ts:50:5 - expected call-signature: 'setService' to have a typedef
lerna ERR! [lint] ERROR: /Users/Documents/theia/packages/output/src/browser/output-channel-readers.ts:77:11 - expected call-signature: 'init' to have a typedef
lerna ERR! [lint] ERROR: /Users/Documents/theia/packages/output/src/browser/output-channel-readers.ts:121:5 - expected call-signature: 'onChannelDeleted' to have a typedef
lerna ERR! [lint] ERROR: /Users/Documents/theia/packages/output/src/browser/output-channel-readers.ts:126:5 - expected call-signature: 'onProcessOutput' to have a typedef
lerna ERR! [lint] ERROR: /Users/Documents/theia/packages/output/src/electron-node/output-channel-logger-server.ts:40:15 - expected call-signature: 'init' to have a typedef
lerna ERR! [lint] ERROR: /Users/Documents/theia/packages/output/src/electron-node/output-channel-logger-server.ts:91:5 - expected call-signature: 'setClient' to have a typedef
lerna ERR! [lint] ERROR: /Users/Documents/theia/packages/output/src/node/output-channel-service-impl.ts:75:12 - expected call-signature: 'log' to have a typedef
lerna ERR! [lint] 
lerna ERR! [lint] theiaext lint exited with code 2
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Note:- I took ```eclipse-theia/theia``` code base from master branch one month back.

**Comment by westbury** [comment]
@NitinKhandelwal1947 I've rebased the PR to latest master, so it should work for you now.  The errors you saw were due to missing typedefs on the return values, which are now required in Theia.

**Comment by NitinKhandelwal1947** [comment]
> @NitinKhandelwal1947 I've rebased the PR to latest master, so it should work for you now. The errors you saw were due to missing typedefs on the return values, which are now required in Theia.

@westbury Thanks it worked. But as per my requirements i want to view my application  log file content (which write in some location in my machine) in Output tab. Can you please help me . Which part of the code i need to change to accommodate this changes.

**Comment by westbury** [comment]
> Which part of the code i need to change to accommodate this changes.

It really depends on the details.  If you can get the file contents at the frontend then you simply need to follow instructions in https://github.com/eclipse-theia/theia/issues/6617#issuecomment-558009490 .  For example, if the script in initiated by the frontend code and it knows when the script has completed then you could, for example, inject the filesystem
`
    @inject(FileSystem)
    protected readonly filesystem: FileSystem;
`
and read the file.  Inject OutputChannelManager and pass the content line-by-line to it.  Search for `@inject(OutputChannelManager)` and you will see examples.

Now if it is not easy to get the file content to the frontend, or if you are able to read each line from the file as it is written, then it will be a lot easier to use the changes in the PR.  It adds support for channel writing from the backend.  Have a look at output-channel-logger-server.  Do not import anything from that file but do use it as an example.  See how the code in that file injects OutputChannelServiceImpl, gets a channel from it, and writes text to the channel.
