### ISSUE TITLE
Integrated terminal cannot be reused

### ISSUE THREAD

**Issue by a1994846931931** [eclipse-theia/theia#6618]
### Description
Theia can now support integrated terminal, thanks to commit 0327a4d666ae2d5b8616e2603e672fb23ad7b0e3. But there remains a problem that the terminal cannot be reused (see the posted gif below).

### Reproduction Steps
1. Install python plugin (from VSCode marketplace)
2. Debug with the following configuration ( `console` should be `integratedTerminal` )
```
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal"
    }
```
3. End the debug session but keep the integrated terminal. Then run another debug session and see how theia lanch it in a new terminal.

![python-integrated](https://user-images.githubusercontent.com/17487291/69508836-dbb4c600-0f71-11ea-822e-5df4b8c33e0d.gif)

**OS and Theia version:**
OS: Ubuntu
Version: 145f9137176497ec0

**Diagnostics:** 
In line
https://github.com/eclipse-theia/theia/blob/145f9137176497ec0a02a720d2b4697b76cf2547/packages/debug/src/browser/debug-session.tsx#L377

The `options.title` is compared with `t.title.label`, but `t.title.label` changes.

**Comment by akosyakov** [comment]
@elaihau Would it be possible to refactor tasks that they preserve identity as in VS Code? It breaks in many places not only for debugging. Generally running the same task multiple times should NOT be allowed and the same terminal should be used. Right now it is most annoying mismatch.

**Comment by elaihau** [comment]
> Would it be possible to refactor tasks that they preserve identity as in VS Code? It breaks in many places not only for debugging. Generally running the same task multiple times should NOT be allowed and the same terminal should be used. Right now it is most annoying mismatch.

Let me take a look. Will get back to you later

**Comment by elaihau** [comment]
@a1994846931931 
quick question: is the python plugin mentioned in this ticket
- the python extension in Theia, or 
- the python extension from vsCode?

Thanks !

**Comment by a1994846931931** [comment]
> @a1994846931931
> quick question: is the python plugin mentioned in this ticket
> 
> * the python extension in Theia, or
> * the python extension from vsCode?
> 
> I was getting a "The debug session type "python" is not supported." error when tried to reproduce this error. Could you please advise what I should do to make debugging python code work?
> 
> Thanks !

@elaihau 
Hi, sorry I forgot to mention that it's VSCode's python extension.
