### ISSUE TITLE
Avoid duplicating java ls when installing vscode extensions that depend on Java language server

### ISSUE THREAD

**Issue by kdvolder** [eclipse-theia/theia#6629]
### Description

When we install a vscode extension that depend on the vscode-java extension, it is easy to end up with basically duplicating the Java language server support in the resulting Theia instance. I.e. we get the functionality from `@theia/java` package. And we also get the vscode-java plugin installed.

Both of these provide Java language support that is identical (well, I'm not 100% sure it is completely identical, but it seems very nearly so at least, since both are based on the Java language server, and the LSP and if there is any difference in their functionality I don't know what it is).

### Reproduction Steps

1. Create a full-featured Theia instance but without the `@theia/java` module listed in its package.json

2. Install the `Pivotal.vscode-spring-boot' (https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-spring-boot) vscode extension into running theia instance.

Note: The easiest way to reproduce my setup exactly is to build docker file as per the Dockerfile and package.json file here:

https://github.com/spring-projects/sts4/tree/vscode-in-theia/theia-extensions/k8s-app

3. Open a .java file inside of a Java project.

4. Open a terminal inside theia and use `jps` command to check for running Java processes. You will see that two jdt language server processes are present. For example:

```
root@396e01c4840f:/home/project# jps
611 org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar
547 org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar
908 Jps
```

We also see this duplication of functionality (for example). When hovering over Java elements. The hovers shown are duplicated. The same also happens with completions. For example:

![duplicated-completions](https://user-images.githubusercontent.com/1002156/69589726-e0916e00-0fa1-11ea-9809-167375bb0e54.png)

I guess what is happening here is that we have both the vscode.java support installed as an wrapped vscode extension (because it is a dependency of our spring-boot vscode support). We also have the `@theia/java` package installed because it is a dependency of the `@theia/java-debug` package. 

Note 1: We do have an equivalent 'theia-spring-boot' package we could install instead of the vscode-spring-boot' extension. And in that case the problem doesn't happen. However... we would like to avoid maintaining multiple packagings of basically the same spring boot language server support. If we could just build a single .vsix package that works both in vscode and Theia, that would really be preferable (less code to maintain, less builds to run etc. etc.). The Theia support for installing vscode extension is really a wonderful idea, and it kind of promises that we ought to be able to do this. Unfortunately, having the Java language support duplicated is not acceptable.

Note 2: I probably wouldn't really call this a 'bug'. Theia did more or less what I would expect given that I installed our vscode extension which depends on the vscode Java support. Still I think this behavior is wholly undesirable and will be rather hard/impossible to avoid from happening, especially when users start installing vscode plugins at their own initiative at runtime.

Question / thoughts. Are the vscode.java and theia Java support really functionally equivalent? If yes, then why do we even have need of a `@theia/java` package? Why not simply use the vscode.java extension 'as is'. It would be one less Theia package to maintain and effort could instead be spent on ensuring / testing the vscode plugin works as desired in both vscode and theia. (It is also exactly this kind of reasoning that has us looking to discontinue maintaining separate vscode and theia packages for our language servers and instead focus on making sure our vscode extensions work properly when installed into Theia).

Note 3: I think we can also avoid this problem by not installing any `@theia/java*` packages (i.e. including the Java debug support). That is, assuming all packages that end up pulling in `@theia/java` as a dependency can effectively be replaced with some equivalent vscode extensions instead. (Again, though, if we are to avoid installing the `@theia/java*` packages, maybe they shouldn't even exist).

Finally... I acknowledge that perhaps this isn't really a bug, and it just 'works as designed'. But still thought it would be good to make sure you are aware of this problem. Also I would be interested to hear any thoughts / suggestions on how to deal with this in a good way that you may have.

**OS and Theia version:**

Theia: 0.13.0-next.98ac397e
OS: Ubuntu 18.04 (in docker image).

**Comment by vince-fugnitto** [comment]
@kdvolder perhaps others can speak further on this but the idea was to deprecate and remove the `@theia/java` and `@theia/java-debug` extensions in favor of directly using VS Code extensions https://github.com/eclipse-theia/theia/issues/6183. In this way, the java language server, and debug capabilities would come from well tested and maintained extensions and more closely follow the VS Code experience.

**Comment by akosyakov** [comment]
@kdvolder please remove Theia java extensions from your product, it you are using vscode extensions. We will remove them from example applications eventually as well.

**Comment by kdvolder** [comment]
Thanks, seeing issue https://github.com/eclipse-theia/theia/issues/6183 and the comments here, tells me you are already moving in the direction of phasing out the `@theia/java` packages in favor of using equivalent vscode extensions. And we should do the same.

I think that answers my questions perfectly.
