### ISSUE TITLE
[keybinding] Align Ctrl/Cmd+T and Ctrl/Cmd+O with VS Code

### ISSUE THREAD

**Issue by jankeromnes** [eclipse-theia/theia#6633]
So this is a bit tricky. Currently, here are the relevant keybindings used in VS Code:

- <kbd>Ctrl/Cmd</kbd> + <kbd>O</kbd>: `File` > `Open...`
- <kbd>Ctrl/Cmd</kbd> + <kbd>T</kbd>: `Go` > `Go to Symbol in Workspace...`
- ~~<kbd>Ctrl/Cmd</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd>: `Go` > `Go to Symbol in File...`~~ (EDIT: this doesn't seem to exist in Theia)

But today, Theia uses this:

- <kbd>Ctrl/Cmd</kbd> + <kbd>O</kbd>: `F1` > `Open Workspace Symbol...`
- <kbd>Ctrl/Cmd</kbd> + <kbd>Alt/Opt</kbd> + <kbd>O</kbd>: `File` > `Open...` (~~only in Electron, item is not visible in browsers~~ EDIT: it seems only Gitpod disables it in browsers)

I think we should map <kbd>Ctrl/Cmd</kbd> + <kbd>O</kbd> to `File` > `Open...` in Theia, however:
- This conflicts with `F1` > `Open Workspace Symbol...`, which may surprise users of that feature
- `Open Workspace Symbol` is mapped to <kbd>Ctrl/Cmd</kbd> + <kbd>T</kbd> in VS Code, which obviously wouldn't work for Theia in browsers (but it could work in Electron)
- ~~`File` > `Open...` is disabled in browsers, because there is no file system access (well, there is, but you have to use `File` > `Upload Files...` instead), so <kbd>Ctrl/Cmd</kbd> + <kbd>O</kbd> is available in browsers (would be sad to leave it unmapped)~~

**Comment by vince-fugnitto** [comment]
> File > Open... is disabled in browsers, because there is no file system access...

Please note that `File` > `Open...` is not disabled in browsers, at least on Linux it is available:

![image](https://user-images.githubusercontent.com/40359487/69634315-f2195b00-101f-11ea-99f6-1a672c20966f.png)

**Comment by jankeromnes** [comment]
> Please note that `File` > `Open...` is not disabled in browsers, at least on Linux it is available:

Ah, indeed, thank you for catching that. I tested Gitpod's Theia as a reference, but it does have a few modifications that should be minded.

**Comment by kittaakos** [comment]
> used in VS Code:
> 
> * Ctrl/Cmd + O: `File` > `Open...`

Watch out, it is on macOS. On Windows and Linux, VS Code uses [keychords](https://github.com/microsoft/vscode/blob/a8158aee897bea1c1ec6545b55c4f7d0de57ed38/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L49-L54). For instance,  <kbd>Ctrl</kbd>+<kbd>K</kbd>|<kbd>Ctrl</kbd>+<kbd>O</kbd> is for opening a folder. And there's no such thing as `File` > `Open...`.

Native file dialogs behave differently:
https://github.com/eclipse-theia/theia/blob/f8aa946e9890b6a1b4c6eae1c15c401edd13e542/packages/filesystem/src/electron-browser/file-dialog/electron-file-dialog-service.ts#L147-L151

**Comment by jankeromnes** [comment]
Indeed, good catch:

- VS Code on Windows:

![windows](https://user-images.githubusercontent.com/599268/69713325-a12f6280-1104-11ea-956c-445926daa15d.png)

- Theia (https://github.com/eclipse-theia/theia/pull/6635) on Windows:

![windows-theia](https://user-images.githubusercontent.com/599268/69713362-af7d7e80-1104-11ea-86c1-6bf4207a19f4.png)
