### ISSUE TITLE
[question] why is '@theia/bunyan' part of the main repository

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6637]
**Description**

I have a question regarding the `@theia/bunyan` extension present in the main repository.
It looks like there are no extensions (part of the main repo) that depend or use the extension, and it is not included in the `example-browser` or `example-electron` applications. It also does not seem to be updated frequently. Is it a source for clean-up, or is there a reason it is present in the main repo?

**Comment by akosyakov** [comment]
Initially we though to use it as a primary logger, but after gaining some experience with end products it becomes clear that using console by default is better. So it is kind of an additional implementation of logging. I'm not sure whether anyone is using it @eclipse-theia/ecd-theia-committers ? If not pulling it out of repo or removing would be fine to make our build faster.

**Comment by thegecko** [comment]
Happy to have it removed

**Comment by westbury** [comment]
Mbed Studio uses log4js, implemented in its own extension based on @theia/bunyan.  So it might be useful to keep in another repo somewhere as an example for those who want file logging.

**Comment by marcdumais-work** [comment]
> Mbed Studio uses log4js, implemented in its own extension based on @theia/bunyan. 

Is your extension a standalone implementation based-on or inspired from `@theia/bunyan` or does it depend-on / extend it? 

>So it might be useful to keep in another repo somewhere as an example for those who want file logging.

We can easily create a new project under `theia-ide/` and move it there, but it will be of limited long-term usefulness unless it's maintained/used. Is there interest from someone in taking ownership of this, maybe also adding an example application that uses it, CI, etc?

**Comment by vince-fugnitto** [comment]
> > Mbed Studio uses log4js, implemented in its own extension based on @theia/bunyan.
> 
> Is your extension a standalone implementation based-on or inspired from `@theia/bunyan` or does it depend-on / extend it?

I think it might simply be inspired by, and that the suggestion was to have it as an example, but I'm not sure the effort in maintaining it is worthwhile. At the moment since it is not even used, we don't know if it is actually working correctly or not.

> > So it might be useful to keep in another repo somewhere as an example for those who want file logging.
> 
> We can easily create a new project under `theia-ide/` and move it there, but it will be of limited long-term usefulness unless it's maintained/used. Is there interest from someone in taking ownership of this, maybe also adding an example application that uses it, CI, etc?

Perhaps if we just want it as an example of file based logging we can simply create a repo and name it as an `{name}-example`? There might not be a need for CI but just have it for educational purposes.

**Comment by westbury** [comment]
> Is your extension a standalone implementation based-on or inspired from `@theia/bunyan` or does it depend-on / extend it?

Yes, I meant 'Inspired by'.  Sorry to be confusing.

**Comment by marcdumais-work** [comment]
> Perhaps if we just want it as an example of file based logging we can simply create a repo and name it as an `{name}-example`? There might not be a need for CI but just have it for educational purposes.

I vote to remove it unless someone will put some effort to maintain it as a working example. We probably do not even know if it still works. If it's needed later, it will still exist in the project's git history.

**Comment by vince-fugnitto** [comment]
> > Perhaps if we just want it as an example of file based logging we can simply create a repo and name it as an `{name}-example`? There might not be a need for CI but just have it for educational purposes.
> 
> I vote to remove it unless someone will put some effort to maintain it as a working example. We probably do not even know if it still works. If it's needed later, it will still exist in the project's git history.

+1 I'll create a PR which removes it
