### ISSUE TITLE
Custom tasks are not available for running

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#6640]
### Description
Tasks with a custom type are not available for running despite the adding the corresponding task schema for them.

### Reproduction Steps
Please use my forked repo for testing, it contains:
- the [test extension](https://github.com/RomanNikitenko/theia/commit/1cc07cead52a5537bbc9826df36c75795426823b) which allows to add/remove schemes for custom types
- tasks with custom type for testing 

1. `git clone https://github.com/RomanNikitenko/theia.git`
2. `cd theia/` and `git checkout task-extension`.
3. Build the project and run it.
4. The project contains prepared tasks in `tasks.json` file, so please open the cloned project: `File=>Open...` and select the project.   
4. Go to `Terminal => Run Task` menu: 
you can see that only `SHELL task` is available for running
5. Open `tasks.json` file and `Problems` view
you can see warnings that custom types are not supported.  
6. Go to `Help` menu and select `Add CHE task schema` and `Add EXEC task schema`
you can see that `Problems` view is empty and now the configurations are valid.
7. Go to `Terminal => Run Task` menu: 
the configurations are NOT available for running

Expected behavior: the configurations are available for running after adding the corresponding task schema.

**OS and Theia version:**
Ubuntu 18.04.1
Theia version: acbb2b4ef87d1637c0824066beb7580df5702342

**Diagnostics:** 
The cause of the problem: the logic for checking is task configuration valid or not was recently changed and moved from task service.

Before the changes: [the logic](https://github.com/eclipse-theia/theia/pull/6616/files#diff-794cdf6ef93aef7cc827f31f92ebe226L250) was executed every time we took the configured tasks

After the changes: this logic is executed on events like `onDidRegisterTaskDefinition`.

The problem is the logic is not executed when task schema is updated.
This leads to the bug, that some tasks are considered as invalid after updating task schema and are not available for running.

**Comment by RomanNikitenko** [comment]
@elaihau 
Is it possible to get back the logic with checking is a configuration valid or not when we take the configured tasks?

At least we should validate configurations when task schema was updated, something like https://github.com/eclipse-theia/theia/compare/reorganizeTasks?expand=1 

But from my point of view before [the changes](https://github.com/eclipse-theia/theia/pull/6616/files#diff-794cdf6ef93aef7cc827f31f92ebe226L250) it was more reliably.

WDYT?

Thanks in advance!

**Comment by elaihau** [comment]
Thank you for pointing out the bug I introduced recently !

I totally agree with [your comments](https://github.com/eclipse-theia/theia/pull/6616/files#r350946933)

I also went through your code in the `reorganizeTasks` branch. Subscribing to `this.taskSchemaUpdater.onTaskSchemaChanged()` is very smart and i believe it fixes the problem. Could you please create a pull request at your convenience?

Thank you !
