### ISSUE TITLE
There is no auto-completion for @theia/vscode-builtin-markdown-language-features@0.2.1

### ISSUE THREAD

**Issue by tolusha** [eclipse-theia/theia#6646]
### Description
I've built Theia without `@theia/preview` package. Installed markdown-language-features extension [1]. Preview works, but auto-completion doesn't, and there are not any errors in console. 
BTW, auto-completion doesn't works in markdown files even with `@theia/preview`.

[1] https://www.npmjs.com/package/@theia/vscode-builtin-markdown-language-features

**Comment by vince-fugnitto** [comment]
@tolusha what type of autocompletion are you looking for in markdown files?
I tried VS Code (reloaded with external extensions disabled), and don't see any completion either.

**Comment by tolusha** [comment]
@vince-fugnitto 
![image](https://user-images.githubusercontent.com/1640675/69784811-5888af80-11bf-11ea-9bb4-1587bdffba6d.png)

**Comment by akosyakov** [comment]
@tolusha Do you have both `@theia/vscode-builtin-markdown-language-features` and `@theia/vscode-builtin-markdown` without `@theia/textmate-grammars`? It could be that it is snippet which is not contributed by `markdown-language-features`.

**Comment by tolusha** [comment]
@akosyakov 
You are right! Thank you!
