### ISSUE TITLE
[scm] support 'undo last commit'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6652]
**Description**

As a user, I'd like to be able to `undo last commit` similarly to VS Code.
At the moment, the option is not available from the context menu:

<img width="260" alt="Screen Shot 2019-11-27 at 11 56 19 AM" src="https://user-images.githubusercontent.com/40359487/69743742-f53e4500-110c-11ea-841d-ea73fc344bf1.png">

I noticed the PR https://github.com/eclipse-theia/theia/pull/1779 but I do not see the option (where the `amend` is at the bottom).
@kittaakos is it perhaps a regression?

**Comment by westbury** [comment]
If I run with the native git package (@theia/git) then I see the same menu as you show above and I see the HEAD COMMIT section at the bottom with the 'Amend' button.

If I run with vscode built-in git extension ( https://registry.npmjs.org/@theia/vscode-builtin-git/-/vscode-builtin-git-0.2.1.tgz) then I see additional items in the menu such as Pull (Rebase), Sync, Checkout to..., Publish Branch, and Undo Last Commit.  There is no HEAD COMMIT section when using vscode's git extension.

I don't see a regression.  It is true that some items are missing from the menu in the @theia/git extension compared to the vscode extension.  However the requirement at the time https://github.com/eclipse-theia/theia/pull/4279 was merged was only that the extension supported at least what was previously supported in Theia, not that it supports everything in the vscode extension.

HEAD COMMIT sections shows only if the extension supports Theia's amend api, which of course the vscode extension does not.  'Undo Last Commit' does the same thing as the 'Amend' button but has no feedback and does not allow the Amend to be unamended (one of the many reasons why we want to continue to use the native Theia extension).

**Comment by kittaakos** [comment]
> @kittaakos is it perhaps a regression?

No, it was removed on purpose.

**Comment by vince-fugnitto** [comment]
@westbury @kittaakos thanks for the clarification, I noticed the `undo last commit` button previously in the application and was wondering if it was removed on purpose (I have seen the command in the `builtin`).
