### ISSUE TITLE
'TextDocumentSaveReason' namespace is moved to vscode-languageserver-protocol

### ISSUE THREAD

**Issue by theBuzzyCoder** [eclipse-theia/theia#6653]
### Description

Module '"../../../../vscode-languageserver-types/lib/umd/main"' has no exported member 'TextDocumentSaveReason'

Error in `node_modules/@theia/monaco/src/browser/monaco-editor-model.ts`

### Reproduction Steps

```console
$ pwd
/home/karthik

$ mkdir theia-test-extension
$ cd theia-test-extension
$ yo theia-extension  
# Install the theia extension
# lot of output
$ cd browser-app
$ yarn start
```

- Load http://localhost:3000
- In Menu > File > New File > Enter filename dialog > Give test.py as filename > Create
- Edit the file / add some content to the file
- In Menu > File > Save

Check chrome inspector > console to see the error

**OS and Theia version:**
Ubuntu 18.04
@theia/monaco: 0.12.0
Browser: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Diagnostics:** 

From google chrome console
```
monaco-editor-model.js:288 Uncaught (in promise) TypeError: Cannot read property 'Manual' of undefined
    at MonacoEditorModel.push.../node_modules/@theia/monaco/lib/browser/monaco-editor-model.js.MonacoEditorModel.save (monaco-editor-model.js:288)
    at Object.<anonymous> (saveable.ts:69)
    at step (saveable.ts:15)
    at Object.next (saveable.ts:15)
    at saveable.ts:15
    at new Promise (<anonymous>)
    at ../node_modules/@theia/core/lib/browser/saveable.js.__awaiter (saveable.ts:15)
    at Object.save (saveable.ts:66)
    at ApplicationShell.<anonymous> (application-shell.ts:1499)
    at step (application-shell.ts:15)
```

**Comment by theBuzzyCoder** [comment]
Found the missing namespace here:

File: `vscode-languageserver-protocol/lib/protocol.d.ts`
Line: 975

```js
/**
 * Represents reasons why a text document is saved.
 */
export declare namespace TextDocumentSaveReason {
    /**
     * Manually triggered, e.g. by the user pressing save, by starting debugging,
     * or by an API call.
     */
    const Manual: 1;
    /**
     * Automatic after a delay.
     */
    const AfterDelay: 2;
    /**
     * When the editor lost focus.
     */
    const FocusOut: 3;
}
```

**Comment by theBuzzyCoder** [comment]
This project: https://github.com/eclipse-theia/theia/ is using `"version": "3.15.0-next.4"` of vscode-languageserver-types and extension is using "version": "3.15.0-next.9"

**Comment by vince-fugnitto** [comment]
@theBuzzyCoder thank you for looking into it!
It will likely be fixed after the release tomorrow. I verified using `next` packages of Theia and it worked as intended (just like this repository).

**Comment by theBuzzyCoder** [comment]
This is working as expected after `0.13.0` version. Hence closing this bug.
