### ISSUE TITLE
[vscode] icons for editor decorators cannot be fetched 

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6661]
The issue is that icons are provided as absolute fs paths: https://github.com/gitpod-io/gitpod/issues/958 It does not work in the browser context. We have to translate such paths to http URLs to make it work.

@DanTup Could you share how it can be tested?

**Comment by akosyakov** [comment]
@DanTup how do you create an icon path btw? Do you call any VS Code APIs for it?

**Comment by DanTup** [comment]
It's just a normal file URI:

```
vs.window.createTextEditorDecorationType({
	gutterIconPath: vs.Uri.file(filePath),
	gutterIconSize: "50%",
});
```

`filePath` here is just an arbitrary file path. In Dart-Code's case it lives inside the extension globalStorage folder, though in VS Code it could literally be anywhere on disk.

There's a VS code sample for using decorations at https://github.com/Microsoft/vscode-extension-samples/tree/master/decorator-sample that you could use (and just add a `gutterIconPath` to it) that's probably much easier to test with than configuring Flutter (though if you want to use Flutter, the branch I've been testing with is https://github.com/DanTup/gitpod-flutter-web/tree/debug-testing, open it in GitPod and write some code that uses colours - see https://dartcode.org/releases/v3-6/#preview-flutter-gutter-icons-and-colors).
