### ISSUE TITLE
[vscode] builtin git extensions fail to contribute toolbar items

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6662]
**Description**

When testing the builtin git extensions, I noticed that the toolbar items (when viewing a `diff editor` were not contributed correctly).

<div align='center'>

<img width="61" alt="Screen Shot 2019-11-29 at 10 03 24 AM" src="https://user-images.githubusercontent.com/40359487/69877372-05caf880-1290-11ea-96b9-53947edfcfbd.png">

</div>

The `ellipsis` do not contain a context menu, and I don't see the `previous` and `next` changes arrows like in VS Code:

<div align='center'>

<img width="106" alt="Screen Shot 2019-11-29 at 10 08 24 AM" src="https://user-images.githubusercontent.com/40359487/69877440-3743c400-1290-11ea-80ea-1105192ef7d8.png">

</div>

**Test**
- tested without the `@theia/git` extension
- included the `@theia/vscode-builtin-git` and `@theia/vscode-builtin-git-ui` extensions

**Additional Info**

<div align='center'>

<img width="632" alt="Screen Shot 2019-11-29 at 10 03 53 AM" src="https://user-images.githubusercontent.com/40359487/69877465-488cd080-1290-11ea-93ca-a137db03875a.png">

</div>

**Comment by akosyakov** [comment]
It is a dub of https://github.com/eclipse-theia/theia/issues/5407 and https://github.com/eclipse-theia/theia/issues/4544
