### ISSUE TITLE
Debug configuration throws error when trying run configuration contains 'preLaunchTask' attribute

### ISSUE THREAD

**Issue by I051950** [eclipse-theia/theia#6669]
### Description
Starting debugging - vscode.debug.startDebugging() – in 'Theia13' candidate doesn't support for 'preLaunchTask' configuration property (and throws warning), but it does support this configuration when it starting via the native debug view .
It is a regression from the previous version when that functionality didn't work in both cases but an exception is not thrown. 

### Reproduction Steps
Create some debug configuration that contains a 'preLaunchTask' definition. Try to run it programmatic via vscode.debug.startDebugging() api.

**OS and Theia version:**
Theia-13

**Diagnostics:** 
Exception appears in notification area.

**Comment by tolusha** [comment]
@I051950 
It will be very helpfull if we have some test extension to reproduce the issue.

**Comment by I051950** [comment]
Actually an any extension can fit for that purpose - just try to run the following code :
const configuration = {
      "name": "Run node",
      "type": "node",
      "request": "launch",
      "projectName": "bookshop-srv",
      "preLaunchTask": "my task"
	};
**vscode.debug.startDebugging(undefined, configuration);**

Even it does not matter whether the task "my task" is defined properly or not. The warning appears before.

**Comment by ShimonBenYair** [comment]
@I051950 

What is the exception text ?
Can you attach a screenshot ?

**Comment by I051950** [comment]
The issue does not happen by run vscode.debug.startDebugging() with specified workspace folder as a first argument.
Close the issue.
