### ISSUE TITLE
[tree] Child node 'path/to/my/file.ext' does not belong to this 'WorkspaceNodeId' tree

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6688]
### Description
 

I can see multiple `Child node 'path/to/my/file.ext' does not belong to this 'WorkspaceNodeId' tree` errors in the console after updating to `next@0.14.0-next.d5c81105` (d5c81105).

This seems to be a regression after https://github.com/eclipse-theia/theia/pull/6679. (CC: @akosyakov)

Related change: 
https://github.com/eclipse-theia/theia/commit/5b45e1240590c1582c8bf6cfb3ee0fa5994e3770#diff-c4f0263c39593601b3f84451c2de4106R281-R283

### Reproduction Steps

Start the application.

**OS and Theia version:**
d5c81105

**Diagnostics:**

**Comment by kittaakos** [comment]
`this.nodes[root.id] !== root` is always `false`:
![Screen Shot 2019-12-04 at 11 47 31](https://user-images.githubusercontent.com/1405703/70136346-1ca48d00-168c-11ea-9f60-b02d1dbc77ef.jpg)

**Comment by akosyakov** [comment]
@kittaakos Do you know how to reproduce it from sources? the issue is that we used to reset the tree with some old state, now we don't reset it, but report as an error that it has to be fixed by the developer.

I don't think we want to go back with resetting some old root.

**Comment by kittaakos** [comment]
> Do you know how to reproduce

Not yet. If I put a breakpoint and stop for a second or two here:
https://github.com/eclipse-theia/theia/blob/d5c81105393a811de3097ff06bdf64ab98ef3d80/packages/navigator/src/browser/navigator-tree.ts#L75-L82

I do not see the error. Otherwise, it pops up twice per each app start.

**Comment by akosyakov** [comment]
> I do not see the error. Otherwise, it pops up twice per each app start.

Do you start the browser example from theia repo and a workspace is using this repo? I'm looking for a way to reproduce it. You can debug how many times `NavigatorMode.updateRoot` is called and from there.

Popping up twice also does not sound bad, before it could go in the infinite loop. Maybe we should just remove `console.error` and wait till someone reports the real functional issue. cc @svenefftinge

**Comment by kittaakos** [comment]
> You don't see any real issues

Correct, I don't.

I will take care of the investigation as it does not happen from the Theia source but from a downstream project. 😕

**Comment by akosyakov** [comment]
Ok, please check why it happens that the navigator replace twice for you on startup. It should not happen without explicit workspace changes from the user. Also check that your code does not keep references to navigator nodes and pass them to the navigator model after the navigator root is changed.

**Comment by kittaakos** [comment]
> twice for you on the startup

Once the model initialization, the second time is the layout restorer.

> Also check that your code does not keep references to navigator nodes

I am not aware of any tree/tree-model customizations. It rather seems like a timing issue that I cannot reproduce in Theia. See the GIF, the roots are out of sync. I am still on this issue, as from time to time, the navigator is empty 😕
![screencast 2019-12-04 15-52-13](https://user-images.githubusercontent.com/1405703/70153022-87ff5680-16ae-11ea-85b3-91321abc68ce.gif)

**Comment by kittaakos** [comment]
This is not a Theia bug but was in my code. The missing return messed up the app state, and `'initialized_layout'` was resolved before the layout was restored.

Bad code:
```js
@injectable()
export class MyCustomFrontendApplication extends FrontendApplication {

    protected async initializeLayout(): Promise<void> {
       /*no return here!!!*/ super.initializeLayout().then(() => {
            // Do some custom things here
        });
    }

}
```

Good code:
```js
@injectable()
export class MyCustomFrontendApplication extends FrontendApplication {

    protected async initializeLayout(): Promise<void> {
        return super.initializeLayout().then(() => {
            // Do some custom things here
        });
    }

}
```

Sorry for the noise, with the fix, it works as expected.

**Comment by akosyakov** [comment]
So then we keep this error message. It seems to be helpful :)

**Comment by kittaakos** [comment]
> It seems to be helpful :)

It is 👍
