### ISSUE TITLE
[enhancement] display the number of 'enabled' plugins

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#6710]
### Description
When you deal with list of plugins, It would be nice to know how many plugins are active or eventually recommended. Something similar to what is available in VSCode.

### Reproduction Steps
Open Theia plugins view with many plugins in it

**OS and Theia version:**
Ubuntu 16.04
Theia: latest

**Diagnostics:** 
VSCode examle:

![VscodePluginNumber](https://user-images.githubusercontent.com/419051/70329854-4edbf900-180a-11ea-91e2-9c485c12a7c7.png)

**Comment by vince-fugnitto** [comment]
@lmcbout just as an FYI, the widget's content will be replaced by the following: https://github.com/eclipse-theia/theia/pull/6655.

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/11248.
