### ISSUE TITLE
[tree] display ellipsis when content cannot be displayed fully

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6711]
**Description**

I'm wondering if we should display `ellipsis` for when content in **trees** cannot be displayed fully.
This is currently not the case for the `explorer` but is true for other tree-based widgets.

| Currently | After |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/40359487/70337633-7d150500-1819-11ea-9888-63e0ef0809a1.png)  | ![image](https://user-images.githubusercontent.com/40359487/70337578-62db2700-1819-11ea-8284-6b8125636c8d.png) |

**Comment by akosyakov** [comment]
Could you check theming PR please? it could be fixed there already

**Comment by vince-fugnitto** [comment]
> Could you check theming PR please? it could be fixed there already

I'll try after lunch :)

**Comment by vince-fugnitto** [comment]
> Could you check theming PR please? it could be fixed there already

I verified and it's still the case in https://github.com/eclipse-theia/theia/pull/6475

**Comment by akosyakov** [comment]
it sounds fine, but please do after theming is landed. We had to change a lot of css styles and recheck the whole UI.
