### ISSUE TITLE
support "presentation" in task config

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#6713]
### Description

The way Theia organizes the output of tasks could be controlled by adding the support of "presentation":

https://code.visualstudio.com/docs/editor/tasks#_output-behavior

### Reproduction Steps

- Open the `tasks.json` of the workspace, and add a task config. 

Expected: Users can add the "presentation" object to the config to control the way that the output is presented.
Reality: "presentation" is not supported

**OS and Theia version:**

Ubuntu 18.04. Example browser.
Version b87052c095dadcef4991c428c58d8c608f547874

**Comment by elaihau** [comment]
This one covers the feature described in https://github.com/eclipse-theia/theia/issues/5332

**Comment by elaihau** [comment]
I am currently working on `presentation.panel`, trying to reuse terminal widget(s) across tasks. This is most recent progress I made:

![Peek 2020-02-04 21-58](https://user-images.githubusercontent.com/37082801/74111585-d3792980-4b63-11ea-9200-d7ca1ef2b068.gif)

**Comment by akosyakov** [comment]
> Next step is finishing up the "widget manager"

What does it mean? :)

**Comment by elaihau** [comment]
> > Next step is finishing up the "widget manager"
> 
> What does it mean? :)

Sorry for the confusion. I should have said "**terminal** widget manager".
My idea is having a manager class to decide if a new terminal widget needs to be created. @akosyakov

**Comment by akosyakov** [comment]
ok, so something like editor manager based on widget open handler?

**Comment by elaihau** [comment]
@akosyakov thank you for sharing the insight with me.

yep, similar. but i guess at this point i don't have to extend `NavigatableWidgetOpenHandler` as i don't need as many features. Also, this "terminal widget manager" will be placed inside the "task" extension, as it would only be used by tasks.

**Comment by akosyakov** [comment]
> yep, similar. but i guess at this point i don't have to extend NavigatableWidgetOpenHandler as i don't need as many features. It could be as simple as a class with only one public method getOrCreateTerminalWidget().

I thought just about `WidgetOpenHandler` to reuse implementation of `open` method.

> Also, this "terminal widget manager" will be placed inside the "task" extension, as it would only be used by tasks.

We should name it differently then, `TerminalManager` should leave in the terminal extension. We actually already have it, it is called `TerminalService`.

**Comment by elaihau** [comment]
Now we support `echo`, `reveal`, `focus`, `panel`, `showReuseMessage`, and `clear`. am i missing anything for this ticket ?
@vince-fugnitto @RomanNikitenko  @akosyakov

**Comment by a1994846931931** [comment]
@elaihau Hi, `reuse terminal widget` sounds fantastic and I'm really looking forward to the feature coming out. May I ask how's your progress?

**Comment by elaihau** [comment]
> Update: I just found out that this feature is already merged into master. Clearly my local repository is far behind master. But nevertheless, l found it behave oddly. See below:
> ![reuse-task](https://user-images.githubusercontent.com/17487291/80581618-fec33480-8a3f-11ea-9093-65f26f50ced4.gif)
> 
> It doesn't act as I expected:
> 
> 1. the task failed;
> 2. the label of the task terminal seems not correct;
> 3. the terminal can not be reused.
> 
@a1994846931931 
As per your GIF, what you task did was `echo Hello`.

I guess the error you saw was due to https://github.com/eclipse-theia/theia/issues/2961

In your task config, could you please add a `sleep 1` before running `echo hello`, and check if it works ?

**Comment by a1994846931931** [comment]
> > Update: I just found out that this feature is already merged into master. Clearly my local repository is far behind master. But nevertheless, l found it behave oddly. See below:
> 
> > It doesn't act as I expected:
> > 
> > 1. the task failed;
> > 2. the label of the task terminal seems not correct;
> > 3. the terminal can not be reused.
> 
> @a1994846931931
> As per your GIF, what you task did was `echo Hello`.
> 
> I guess the error you saw was due to #2961
> 
> In your task config, could you please add a `sleep 1` before running `echo hello`, and check if it works ?

@elaihau 
No, it doesn't work. It seems that the command `sleep 1` is not executed at all for it returns so quickly.
![reuse-task-2](https://user-images.githubusercontent.com/17487291/80660204-acc0f400-8abd-11ea-915a-95917e859777.gif)

Actually I've also encountered #2961 before, but they look different.

**Comment by vince-fugnitto** [comment]
> No, it doesn't work. It seems that the command `sleep 1` is not executed at all for it returns so quickly.

@a1994846931931 do you mind sharing your `tasks.json`? 
You might also want to check what a bash error code of [127 means](https://forum.linuxconfig.org/t/bash-127-error-return-code/943).

**Comment by vince-fugnitto** [comment]
> No, it doesn't work. It seems that the command `sleep 1` is not executed at all for it returns so quickly.

@a1994846931931 do you mind sharing your `tasks.json`? 
You might also want to check what a bash error code of [127 means](https://forum.linuxconfig.org/t/bash-127-error-return-code/943) as it might help you with your problem.

**Comment by elaihau** [comment]
> @elaihau
> No, it doesn't work. It seems that the command `sleep 1` is not executed at all for it returns so quickly.
> Actually I've also encountered #2961 before, but they look different.

I tried running your task in my env and it worked:

![Screenshot from 2020-04-29 22-06-50](https://user-images.githubusercontent.com/37082801/80664855-e0702f80-8a65-11ea-8c66-d16086990f5e.png)

**Comment by RomanNikitenko** [comment]
@a1994846931931 
I tried your configuration and it works well for me

![test_task](https://user-images.githubusercontent.com/5676062/80673030-dde9f600-8ab6-11ea-8a15-19c3530167f8.gif)

But it's interesting to know what's the problem...

**Comment by a1994846931931** [comment]
@vince-fugnitto @elaihau @RomanNikitenko Hi, I just found out that the issue has something to do with the shell I use - `zsh`. It worked fine after I shifted back to `bash`.

**Comment by elaihau** [comment]
If there are no objections I will close this ticket in a day.
