### ISSUE TITLE
Theia stuck at loai

### ISSUE THREAD

**Issue by slipdip123** [eclipse-theia/theia#6725]
### Description
When loading theia from the web inteface, it is stuck loading at the blue loading circle, but worked yesterday.
### Reproduction Steps
I am running theia as root (I know, I know, but it needs to access files at /nextcloudShare) and I am running from yarn at port 8080. Here is the script I use to start theia:

```#!/bin/bash
cd /home/toffee/theia
yarn theia start /nextcloudShare/Programming/ --hostname 0.0.0.0 --port 8080
```

I am using pm2 to start it as startup, but even without theia is not loading.

**OS and Theia version:**

Ubuntu 18.04
Theia 0.14.0-next.b87052c0

**Diagnostics:** 
I am using node 10 with the command `nvm use 10`
This is the log I get when I run theia and go to the page:

```root@theia:/home/toffee/theia# ./theia.sh
yarn run v1.21.0
$ /home/toffee/theia/node_modules/.bin/theia start /nextcloudShare/Programming/ --hostname 0.0.0.0 --port 8080
root INFO Theia app listening on http://0.0.0.0:8080.
```

**Comment by vince-fugnitto** [comment]
@slipdip123 can you share the frontend logs? (through the devtools console)

**Comment by slipdip123** [comment]
> @slipdip123 can you share the frontend logs? (through the devtools console)

Okay you are a genius im pretty sure my proxy is getting in the way, I am so sorry for wasting your time!
![image](https://user-images.githubusercontent.com/38812289/70460473-4f94b980-1aae-11ea-88e4-43c53cbe2c6f.png)
Im going to turn of my proxy, then edit it to allow port 8080 okay I am really sorry!

**Comment by slipdip123** [comment]
Right okay I am so sorry! It is working without my proxy. Thank you so much!

**Comment by vince-fugnitto** [comment]
> Right okay I am so sorry! It is working without my proxy. Thank you so much!

No, that's fine no worries :) I'm happy to see you're using the platform.

**Comment by slipdip123** [comment]
Right I am so sorry! Thank you so much for the help, it was my proxy.
