### ISSUE TITLE
[markdown] builtin command not working correctly

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6730]
**Description**

Attempting to follow a link in a markdown file (<kbd>cmd</kbd>+click) does not work correctly.
The following error is displayed in the console:
```
Uncaught (in promise) command '_markdown.openDocumentLink' NOT known
```

The error was reproduced when using:
- `@theia/vscode-builtin-markdown`
- `@theia/vscode-buitlin-markdown-language-features`

---

**Update**

The following occurred when attempting to click relative links (not external).
Example:

```markdown
[Eclipse Public License 2.0](LICENSE)
```

**Comment by akosyakov** [comment]
@vince-fugnitto Maybe https://github.com/eclipse-theia/theia/pull/6921/commits/401f143706278c7367eff027bd04dd0a4de4fa62 was a reason?

**Comment by benjaminhdavis** [comment]
Saw this issue popup again while trying to do something similar to  the [solargraph plugin](https://github.com/castwide/vscode-solargraph/blob/c0cc829e2e1876bf2dbeeaee020d2953117ce5fd/src/language-client.ts#L14). It appears that the command list available for execution of markdown is completely different than the command list of theia. 

I was able to get my plugin to execute my command in vscode (clicking the link in MD) with something like:
```
[label](command:myplugin.commandId)
```

But in theia it's unable to find the error message on [openerService._doOpen](
https://github.com/microsoft/vscode/blob/8283078f9305d1c4dec90179fbba5dede1ef3432/src/vs/editor/browser/services/openerService.ts#L97)

**Comment by akosyakov** [comment]
Could you try `[label](command:commandId)`?

**Comment by vince-fugnitto** [comment]
I confirmed that my original use-case now works:

```markdown
[Eclipse Public License 2.0](LICENSE)
```

**Steps:**
1. start the example application using `theia` as a workspace
2. open the root `readme.md`
3. ctrl+click the license link
4. the file opens
