### ISSUE TITLE
Is it possible to use theia without a backend? (Web-worker based language server)

### ISSUE THREAD

**Issue by tomenden** [eclipse-theia/theia#6732]
We're looking into building a cloud ide and considering theia, it looks amazing!
We currently use `monaco-editor` directly without a backend, with intellisense provided from a webWorker, and I was wondering whether it was possible to do this with theia (and perhaps introduce a backend at a later stage)
Monaco-typescript runs a typescript language server implementation in a webWorker. Is it possible to do the same with theia?
We're interested in typescript based intellisense, but with a bit of custom behavior.

Thanks in advance!

**Comment by vince-fugnitto** [comment]
I believe the same type of question was previously asked and answered: https://github.com/eclipse-theia/theia/issues/6560#issuecomment-554605358

**Comment by tomenden** [comment]
You are right, thank you very much for the prompt reply! I really appreciate it :)
