### ISSUE TITLE
[LS] LanguageClientOptions.errorHandler#close is not called when the LS process terminates

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6739]
### Description
 
The [`errorHandler`](https://github.com/eclipse-theia/theia/blob/e3abddeb647980a4f1eb59c41abd15009a245ef0/packages/languages/src/browser/language-client-factory.ts#L60-L64) is not invoked when the LS process terminates on the backend. It can be a problem with my LS for sure, I am still investigating it. One note, when I refresh the browser windows, then I hit a breakpoint in the `close` function but this is not what I want. I would have expected, the client is "notified" (`close`) when the LS process terminates on the Theia backend.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
> when I refresh the browser windows

When I refresh the browser, `close` is called from the WebSocket channel's `onClosel`.

**Comment by kittaakos** [comment]
So something like this is missing from the backend's language contribution after spawning the process here:
https://github.com/eclipse-theia/theia/blob/e3abddeb647980a4f1eb59c41abd15009a245ef0/packages/languages/src/node/language-server-contribution.ts#L109-L110

```ts
rawProcess.onExit(({ code, signal }) => {
  if (typeof code === 'number' && code > 0) {
    // Notify the client about the exited LS process and trigger a restart if required.
  } else {
    // Something else?
  }
});
```

It seems to be a missing feature. Does this make any sense, @akosyakov? If so, I can take care of it.

**Comment by kittaakos** [comment]
Same as https://github.com/eclipse-theia/theia/issues/6308?

**Comment by tsmaeder** [comment]
Closing, since the languages package is gone.
