### ISSUE TITLE
How to rebind FileSystemNode

### ISSUE THREAD

**Issue by datou0412** [eclipse-theia/theia#6740]
### Description
I want to customize `resolveContent` method, i tried this way but failed

#### `node-filesystem.ts`
```ts
import { injectable } from 'inversify';
import { FileStat } from '@theia/filesystem/lib/common';
import { FileSystemNode } from '@theia/filesystem/lib/node/node-filesystem';

@injectable()
export class SecurityFileSystemNode extends FileSystemNode {
  async resolveContent(uri: string, options?: { encoding?: string }): Promise<{ stat: FileStat, content: string }> {
    console.log('ahahahahahha')
    return super.resolveContent(uri, options);
  }
}

```

#### `security-backend-module.ts`

```ts
import { ContainerModule, interfaces } from 'inversify';
import { ConnectionHandler, JsonRpcConnectionHandler } from '@theia/core/lib/common';
import { FileSystem, DispatchingFileSystemClient, FileSystemClient } from '@theia/filesystem/lib/common';
import { SecurityFileSystemNode } from './node-filesystem';

export default new ContainerModule((bind: interfaces.Bind, unbind: interfaces.Unbind, isBound: interfaces.IsBound, rebind: interfaces.Rebind) => {
  bind(SecurityFileSystemNode).toSelf().inSingletonScope().onActivation((context, fs) => {
    const client = context.container.get(DispatchingFileSystemClient);
    fs.setClient(client);
    fs.setClient = () => {
      throw new Error('use DispatchingFileSystemClient');
    };
    return fs;
  });

  rebind(FileSystem).toService(SecurityFileSystemNode);
});

```

![image](https://user-images.githubusercontent.com/5847142/70711251-0649a180-1d1c-11ea-8786-6ef34c5db63d.png)

**Comment by kittaakos** [comment]
You are on the right path, just use the following as your backend binding in the module:
```ts
import { ContainerModule, interfaces } from 'inversify';
import { ConnectionHandler, JsonRpcConnectionHandler } from '@theia/core/lib/common';
import { FileSystem, DispatchingFileSystemClient, FileSystemClient } from '@theia/filesystem/lib/common';
import { SecurityFileSystemNode } from './node-filesystem';

export default new ContainerModule((bind: interfaces.Bind, unbind: interfaces.Unbind, isBound: interfaces.IsBound, rebind: interfaces.Rebind) => {
  bind(SecurityFileSystemNode).toSelf().inSingletonScope();
  rebind(FileSystem).toService(SecurityFileSystemNode);
});
```

I have just tried it and it works. If you still have issues, let us know. Otherwise, please close the issue. Thank you!

**Comment by datou0412** [comment]
> You are on the right path, just use the following as your backend binding in the module:
> 
> ```ts
> import { ContainerModule, interfaces } from 'inversify';
> import { ConnectionHandler, JsonRpcConnectionHandler } from '@theia/core/lib/common';
> import { FileSystem, DispatchingFileSystemClient, FileSystemClient } from '@theia/filesystem/lib/common';
> import { SecurityFileSystemNode } from './node-filesystem';
> 
> export default new ContainerModule((bind: interfaces.Bind, unbind: interfaces.Unbind, isBound: interfaces.IsBound, rebind: interfaces.Rebind) => {
>   bind(SecurityFileSystemNode).toSelf().inSingletonScope();
>   rebind(FileSystem).toService(SecurityFileSystemNode);
> });
> ```
> 
> I have just tried it and it works. If you still have issues, let us know. Otherwise, please close the issue. Thank you!

Wont work for me!
Can you open any file after this rebinding?

I come to this error when open any file
![image](https://user-images.githubusercontent.com/5847142/70716354-321e5480-1d27-11ea-9f5c-09d9e6595903.png)

![image](https://user-images.githubusercontent.com/5847142/70716410-4cf0c900-1d27-11ea-829d-b63fbb9eed0f.png)

**Comment by kittaakos** [comment]
> Can you open any file after this rebinding?

Yes, I could. Please share your backend module with the binding customization and your custom FS class. If you could push your code to a public repo, that would help.

**Comment by datou0412** [comment]
> > Can you open any file after this rebinding?
> 
> Yes, I could. Please share your backend module with the binding customization and your custom FS class. If you could push your code to a public repo, that would help.


I push my code to a public repo [https://github.com/datou0412/theia-test](https://github.com/datou0412/theia-test)

Follow the README to reproduce

**Comment by JPinkney** [comment]
@kittaakos in your code snippet shouldn't FileSystem be FileSystemNode? like:
```
export default new ContainerModule((bind: interfaces.Bind, unbind: interfaces.Unbind, isBound: interfaces.IsBound, rebind: interfaces.Rebind) => {
  bind(SecurityFileSystemNode).toSelf().inSingletonScope();
  rebind(FileSystemNode).toService(SecurityFileSystemNode);
});
``` 

I wonder if that might be the issue

**Comment by datou0412** [comment]
> @kittaakos in your code snippet shouldn't FileSystem be FileSystemNode? like:
> 
> ```
> export default new ContainerModule((bind: interfaces.Bind, unbind: interfaces.Unbind, isBound: interfaces.IsBound, rebind: interfaces.Rebind) => {
>   bind(SecurityFileSystemNode).toSelf().inSingletonScope();
>   rebind(FileSystemNode).toService(SecurityFileSystemNode);
> });
> ```
> 
> I wonder if that might be the issue

wont work --

**Comment by kittaakos** [comment]
> I push my code to a public repo https://github.com/datou0412/theia-test

I could reproduce. Thanks! Please compile against `es5`.

My changes:
```diff
diff --git a/browser-app/package.json b/browser-app/package.json
index cc221ef..c73f34b 100644
--- a/browser-app/package.json
+++ b/browser-app/package.json
@@ -2,7 +2,8 @@
   "name": "theia-test",
   "version": "0.0.1",
   "scripts": {
-    "prepare": "yarn theia build"
+    "prepare": "yarn theia build",
+    "start": "yarn theia start"
   },
   "dependencies": {
     "typescript": "latest",
diff --git a/packages/security/tsconfig.json b/packages/security/tsconfig.json
index 6cab26f..fe0e937 100644
--- a/packages/security/tsconfig.json
+++ b/packages/security/tsconfig.json
@@ -16,7 +16,7 @@
     "resolveJsonModule": true,
     "module": "commonjs",
     "moduleResolution": "node",
-    "target": "es6",
+    "target": "es5",
     "jsx": "react",
     "lib": ["es6", "dom"],
     "sourceMap": true
```

I also had to wipe the `yarn.lock` and run `yarn` from scratch as it was failing with an NPM error, probably some proxy thing.
```
error An unexpected error occurred: "https://registry.npm.alibaba-inc.com/@types/node/download/@types/node-12.12.17.tgz: ETIMEDOUT".
```

For more details on why we have to use `es5`, check these threads or ask on [Spectrum](https://spectrum.chat/theia):
 - https://github.com/eclipse-theia/theia/pull/6060
 - https://github.com/inversify/InversifyJS/issues/928

Closing as answered.

**Comment by kittaakos** [comment]
Follow-up: https://github.com/eclipse-theia/theia/issues/6761
