### ISSUE TITLE
[webview] Refused to frame because it violates the following Content Security Policy

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#6749]
### Description
Refused to frame 'https://theia.miaowoo.cc/webview/fake.html?id=fdc8cdf6-f249-41be-9966-e04140eac4d2' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

### Reproduction Steps

- Press F1
- Deploy Plugin By Id
- ext install humao.rest-client
- create simple http file
```
GET https://google.com
```
- Send Request
- WebView don't have something
- Look Console have error
```
Refused to frame 'https://theia.miaowoo.cc/webview/fake.html?id=fdc8cdf6-f249-41be-9966-e04140eac4d2' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**OS and Theia version:**
Chrome 
Windows10

**Diagnostics:**

**Comment by akosyakov** [comment]
Please describe how the issue can be reproduced from sources? I'm not sure that there is an issue right now.

**Comment by 502647092** [comment]
@akosyakov I update Reproduction Steps

**Comment by vince-fugnitto** [comment]
@502647092 I followed the steps you provided using `master` (4070136), and it worked correctly.
Is this the result you expect when selecting `send request`?

<div align='center'>

<img width="1461" alt="Screen Shot 2019-12-13 at 11 38 27 AM" src="https://user-images.githubusercontent.com/40359487/70816266-1bb2e000-1d9d-11ea-9cfe-ca5461e0a18f.png">


</div>

**Comment by akosyakov** [comment]
@502647092 Which browser do you use? I found a similar issue in VS Code, it seems to happen in Edge: https://github.com/microsoft/vscode/issues/86468

**Comment by 502647092** [comment]
@akosyakov 
Microsoft Edge
Version 80.0.355.1 dev (x64)

**Comment by akosyakov** [comment]
@502647092 try to use Chrome as a workaround :)

**Comment by akosyakov** [comment]
It seems to be fixed in latest Chromium based Edge: https://github.com/microsoft/vscode/issues/86399#issuecomment-572312243 Please reopen if it is still the case.
