### ISSUE TITLE
Shellcheck -x is not recognized

### ISSUE THREAD

**Issue by Kreyren** [eclipse-theia/theia#6754]
Disclaimer: Submitting this here according to gitpod's instructions (https://www.gitpod.io/docs/vscode-extensions/#your-extension-doesnt-work-as-expected)

### Description
I'm using gitpod with shellcheck extension (https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck) where my repository (https://github.com/Kreyrock/Kreyrock) is using `source` directive (https://github.com/koalaman/shellcheck/wiki/Directive#source) which doesn't work on Theia. 

### Reproduction Steps

- Open https://gitpod.io/#https://github.com/Kreyrock/Kreyrock/tree/theia_shellcheck
- Examine the error

Note: Repository configuration is overwritten by your local configuration in `File -> Settings -> Open Preferences`

**OS and Theia version:** Gitpod 14122019

**Diagnostics:** 

none

**Comment by Kreyren** [comment]
Any info on this?

**Comment by vince-fugnitto** [comment]
@Kreyren is this still an issue, I'm not sure what the expectation is?

**Comment by Kreyren** [comment]
@vince-fugnitto afaik this issue has been resolved as far as i understood it seemed that the shellcheck extension wasn't processing the `shellcheck --external-sources` correctly which resulted in a linting failure when using sourced files with `source` directive.
