### ISSUE TITLE
how to package theia plugin?

### ISSUE THREAD

**Issue by HuangJunjia** [eclipse-theia/theia#6759]
how can I package the plugin?

**Comment by akosyakov** [comment]
cc @eclipse-theia/plugin-system

**Comment by HuangJunjia** [comment]
Hi:
This address is 404 now, can you send me a new one?

[cid:E13A32A7-E288-4D02-AF98-D41CEFA300FA]

2019年12月17日 16:22，Anton Kosyakov <notifications@github.com<mailto:notifications@github.com>> 写道：


cc @eclipse-theia/plugin-system<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forgs%2Feclipse-theia%2Fteams%2Fplugin-system&data=02%7C01%7C%7C07df74e7917a48be260308d782ca33c6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637121677269242375&sdata=z%2B9hYtOL9HIUIi%2B3FIgtQp40L%2BNSEb7i65Hw1DVLnZE%3D&reserved=0>

**Comment by vince-fugnitto** [comment]
> how can I package the plugin?

Do you still require assistance?

**Comment by vince-fugnitto** [comment]
@HuangJunjia please re-open the issue if you're still experiencing problems :)
