### ISSUE TITLE
uri parameter of `vscode.window.showTextDocument` is losing its fragment in theia.

### ISSUE THREAD

**Issue by a1994846931931** [eclipse-theia/theia#6763]
### Description
It is possible to register a `TextDocumentContentProvider` on theia, just like VSCode. But I recently found that the `Uri` parameter passed to the overridden `provideTextDocumentContent` is losing its fragment.

For example, if an extension tried to do
```
vscode.window.showTextDocument(uri)
```
where uri is `test-provider://this-is-path#this-is-fragment`, the uri passed to the `TextDocumentContentProvider` becomes  `test-provider://this-is-path`

This will be buggy for plugins that rely on the fragment of the Uri. For example:
https://github.com/WebFreak001/code-debug/blob/95fa94b954ca78ee34ad95f3aa49c191a0436253/src/frontend/extension.ts#L75

### Reproduction Steps
I wrote a simple plugin for testing. Please download and uncompress [custom-text-document-provider-0.0.1.zip](https://github.com/eclipse-theia/theia/files/3973305/custom-text-document-provider-0.0.1.zip) and:
1. Install plugin both on theia and VSCode;
2. Run `Check custom text provider` command both on theia and VSCode;
3. Compare the result. In VSCode, the content of the opened text document should be 
```
uri is test-provider://this-is-path#this-is-fragment
```
while on theia, the content is
```
uri is test-provider://this-is-path
```

**OS and Theia version:**
OS: Linux
Theia: Latest(582ae9d)

**Diagnostics:** 
The fragment part is losing because of:
https://github.com/eclipse-theia/theia/blob/582ae9dd88a58f3053e9445199ee54e42179923f/packages/core/src/browser/navigatable.ts#L93
I am wondering if `withoutFragment()` is necessary here?

**Comment by akosyakov** [comment]
> I am wondering if withoutFragment() is necessary here?

It is, otherwise we will open 2 different editors for the same URI. A fragment semantic usually is to reveal something inside the URI. It does not mean completely other uri, i.e. think html header element references for a page.

Could you point me where this URI gets used and how?

**Comment by a1994846931931** [comment]
> > I am wondering if withoutFragment() is necessary here?
> 
> It is, otherwise we will open 2 different editors for the same URI. A fragment semantic usually is to reveal something inside the URI. It does not mean completely other uri, i.e. think html header element references for a page.
> 
> Could you point me where this URI gets used and how?

@akosyakov In a plugin called `Native Debug`, the Uri is used to open a text document for memory view.
https://github.com/WebFreak001/code-debug/blob/95fa94b954ca78ee34ad95f3aa49c191a0436253/src/frontend/extension.ts#L75
The plugin has some problems running in theia, so you can try the test plugin I uploaded above.

**Comment by akosyakov** [comment]
@a1994846931931 I think they should have used `query` not `fragment` to resolve content, `fragment` should be used later to reveal something within fetched content. 

Just imagine that calling `file:///foo/bar.txt#L2` and `file:///foo/bar.txt#L5` will return different content.

**Comment by akosyakov** [comment]
But we should fix it somehow in the plugin system without affecting the rest of Theia...

**Comment by akosyakov** [comment]
Maybe we can extract the default logic of `serializeUri` to a separate class, then rebind it in the plugin system that it checks whether `TextContentResourceResolver` has scheme for such URI and if it has then serialize URI as is, otherwise use the default logic. Not sure whether it can break other VS Code extensions.

**Comment by a1994846931931** [comment]
> @a1994846931931 I think they should have used `query` not `fragment` to resolve content, `fragment` should be used later to reveal something within fetched content.
> 
> Just imagine that calling `file:///foo/bar.txt#L2` and `file:///foo/bar.txt#L5` will return different content.

@akosyakov 
I agree that they should move the `fragment` part to `query`, though we still should have it fixed.

Nevertheless, however, I found it interesting that VSCode actually opens different text documents for URIs that differ in fragments.

Try this in VSCode:
[custom-text-document-provider-0.0.2.zip](https://github.com/eclipse-theia/theia/files/3982348/custom-text-document-provider-0.0.2.zip)
Demo:
![text-document](https://user-images.githubusercontent.com/17487291/71155938-ce8dad00-2279-11ea-80db-1c90ba82c1c7.gif)

But I don't know whether the logic only works for custom schemes or not.

**Comment by akosyakov** [comment]
@a1994846931931 We can allow fragments if there is `TextDocumentContentProvider` is registered for such schema as I've described here: https://github.com/eclipse-theia/theia/issues/6763#issuecomment-566560366

**Comment by akosyakov** [comment]
@a1994846931931 I've asked:
- for VS Code https://github.com/microsoft/vscode/issues/87332
- and code-debug https://github.com/WebFreak001/code-debug/issues/199

Maybe I read the spec wrong, will see. Anyway since there are extension doing it let's work on allowing it in the plugin system.
