### ISSUE TITLE
Integrated terminal should not be resused if a process is running in it

### ISSUE THREAD

**Issue by a1994846931931** [eclipse-theia/theia#6767]
### Description
If a process is running in an integrated terminal, then a new integrated terminal should be provided for `runInTerminal` request. Otherwise, it could be problematic, even dangerous.

### Reproduction Steps
![integrated-terminal](https://user-images.githubusercontent.com/17487291/71049658-10d1c400-217e-11ea-8769-8879c7bd192f.gif)
In the demo above, if the terminal is already running python, sending command text to that terminal will end in chaos.

**What's worse?** Think about a situation where a user happens to be operating a database, e.g. MySQL, in the opened integrated terminal, it could be dangerous to send commands to that terminal!

### Propose
1. Remove integrated terminals with any child process from for-reuse candidates
I learned the logic from VSCode. Please refer to:
https://github.com/microsoft/vscode/blob/4636be2b71c87bfb0bfe3c94278b447a5efcc1f1/src/vs/workbench/api/node/extHostDebugService.ts#L83-L87
and
https://github.com/microsoft/vscode/blob/4636be2b71c87bfb0bfe3c94278b447a5efcc1f1/src/vs/workbench/contrib/debug/node/terminals.ts#L50-L75

Demo from VSCode:
![integrated-terminal-vscode](https://user-images.githubusercontent.com/17487291/71051248-9e171780-2182-11ea-85c8-17f9222ede6a.gif)

2. Don't change the title of the integrated terminal
Compare the title of the integrated terminal of VSCode to theia:
VSCode:
![image](https://user-images.githubusercontent.com/17487291/71051255-a8d1ac80-2182-11ea-9230-6e4b04a55631.png)
Theia:
![image](https://user-images.githubusercontent.com/17487291/71051308-de769580-2182-11ea-86e5-c95c66dfe5b8.png)
- In the case of theia, I believe it is hard for users to distinguish the *special* integrated terminals from the *normal* ones and they are more likely to run command in that terminal.
- In the case of VSCode, it's not hard to imagine that users will be aware of which ones are integrated terminal. And even if they mistakenly run a process in that terminal, which ends in prompting VSCode opening a new terminal, they are more likely to understand what's happening and avoid using that terminal the next time.

**OS and Theia version:**
OS: Linux
Theia: Latest(582ae9d)

**Diagnostics:**

**Comment by akosyakov** [comment]
@a1994846931931 PRs are welcomed.
