### ISSUE TITLE
allow to change menu order

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#6768]
### Description

Is there any way to change the order of the top menus?
eg: change 
File  Edit Selection View 
to
File MyMenu Edit Selection View
 

### Reproduction Steps
If I add a new menu then it gets added after 'View' menu 
How can I force it to add it to the initial place?
I did it with DOM manipulation ([insertBefore](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore)) but on hover, it retains the original menu orders again.

**Comment by akosyakov** [comment]
I think you will need to unregsiter and register them again with different order attribute.

**Comment by dhananjayharel** [comment]
Thanks for the reply!
I think there is no direct API to unregister the subMenu
https://github.com/eclipse-theia/theia/issues/4252

**Comment by akosyakov** [comment]
Looking at the code it does not seem to be possible. Menus are always sorted by an id, i.e. the last segment of a menu path.

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/7958
