### ISSUE TITLE
Pressing `Esc` not closing input box when focus is out    

### ISSUE THREAD

**Issue by DoroNahari** [eclipse-theia/theia#6773]
### Description
In vscode, when some input box is opened and you press `esc` the input box is closing(Regardless of focus).
In Theia, `esc` close the input box only when the focus is in the input box.

### Reproduction Steps
[hello-0.0.1.vsix.zip](https://github.com/eclipse-theia/theia/files/3983406/hello-0.0.1.vsix.zip)
Activate the vsix above (remove the `.zip`) in Theia.
Activate the command "hello world" from the command pallete -> An input box should apear.
Change the focus from the input box to something else.
Press `esc` the input box remain although it shouldn't.

**OS and Theia version:**
Local Theia 13, Theia gitpod 13

**Comment by akosyakov** [comment]
Input box do you mean modal dialogs? As far as I know the plugin system does not use Theia dialogs for some reasons, but has own implementation. We should fix it and have one implementation of dialogs.

**Comment by DoroNahari** [comment]
By input box i mean https://code.visualstudio.com/api/references/vscode-api#window.showInputBox
![image](https://user-images.githubusercontent.com/24614792/71179092-29bea000-2278-11ea-9e09-6f4f3ef80873.png)

**Comment by akosyakov** [comment]
@DoroNahari ok, thanks for following up
