### ISSUE TITLE
file-icons vscode extension does not work

### ISSUE THREAD

**Issue by RDIL** [eclipse-theia/theia#6776]
https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons doesn't work

**Comment by akosyakov** [comment]
We have a PR for it already: https://github.com/eclipse-theia/theia/pull/6475

**Comment by akosyakov** [comment]
Checked against the PR, it works nicely:
<img width="1552" alt="Screen Shot 2019-12-20 at 08 57 20" src="https://user-images.githubusercontent.com/3082655/71239451-df383480-2306-11ea-8cf8-16ae7f66a201.png">

The only issue that theme name is `File Icons`, and it is the same name which we use for the default Theia file icons theme. I will rename the default theme to something else.
