### ISSUE TITLE
code lens should support octicons

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6778]
Originally reported here: https://github.com/gitpod-io/gitpod/issues/1018#issuecomment-567865925

> Your screenshot shows the $(check) placeholder on the test (should be a "tick" or "cross" to indicate success or failure).

<img width="1552" alt="Screen Shot 2019-12-20 at 10 52 18" src="https://user-images.githubusercontent.com/3082655/71251275-297adf00-2322-11ea-910f-17b1944bb1fe.png">

**Comment by vince-fugnitto** [comment]
The issue is fixed.
