### ISSUE TITLE
[theming] input area not visible on light themes when in the main area

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6781]
**Description**

The `--theia-input-background` color used for input areas is not visible on light themes when widgets are present in the main area. The color works well for the sidebars but is hardly visible otherwise.

For example (the `keyboard shortcuts` widget):
Notice the input area with the **add** search term.

_Main Area_

<div align='center'>

<img width="1196" alt="Screen Shot 2019-12-20 at 11 57 40 AM" src="https://user-images.githubusercontent.com/40359487/71270631-0e0ed480-2320-11ea-99e8-19fe5d46e25e.png">

</div>

_Sidebar_ (Activity Bar)

<div align='center'>

<img width="1196" alt="Screen Shot 2019-12-20 at 11 57 49 AM" src="https://user-images.githubusercontent.com/40359487/71270638-123af200-2320-11ea-9bc6-0ef982a2af18.png">

</div>

**Steps to Reproduce**
1. prerequisite: https://github.com/eclipse-theia/theia/pull/6475
2. start the application
3. navigate to the `keyboard shortcuts` widget
4. switch to a **light** theme
5. notice the input is hardly visible (dock the widget to the side)

**Comment by akosyakov** [comment]
Background seems to be fine, it is the same in VS Code:
<img width="1552" alt="Screen Shot 2019-12-20 at 20 10 30" src="https://user-images.githubusercontent.com/3082655/71285203-e857ee80-2364-11ea-8f6b-8f14ca79f7f0.png">

But input borders are missing. We should check which colors are used in VS Code for the keybinidng widget and apply them as well.

**Comment by akosyakov** [comment]
It's turned out to be hardcoded in css styles for VS Code: https://github.com/microsoft/vscode/blob/ff5f581425da6230b6f9216ecf19abf6c9d285a6/src/vs/workbench/contrib/preferences/browser/media/preferences.css#L127

will do the same
