### ISSUE TITLE
[getting-started] add widget icon to 'getting-started' widget

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6783]
**Description**

When the default file icons have been changed (#6475), the `getting-started` widget (which does not have a widget icon), gets a blank square. 

_Master_:

<div align='center'>

<img width="1148" alt="Screen Shot 2019-12-20 at 2 37 59 PM" src="https://user-images.githubusercontent.com/40359487/71287516-94ceac00-2336-11ea-8486-4792a84bc733.png">

</div>

_PR_: (#6475 with file-icon changed)

<div align='center'>

<img width="1148" alt="Screen Shot 2019-12-20 at 2 37 41 PM" src="https://user-images.githubusercontent.com/40359487/71287553-a9ab3f80-2336-11ea-8b42-1830c957d353.png">

</div>

**Comment by vince-fugnitto** [comment]
It is likely that any widget that does not have a widget icon will experience a similar issue.

**Comment by akosyakov** [comment]
It's a bug, icon element should not rendered if an icon is not set.
