### ISSUE TITLE
[theming] remove scrollbar rail background color on dark themes

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6787]
**Description**

There is a regression regarding the scrollbar on dark themes with #6475.
There should not be a white scrollbar rail background color.

For example:

_Master:_

![before](https://user-images.githubusercontent.com/40359487/71361303-967bb800-2560-11ea-9632-581b3a74e77d.gif)

_VS Code:_

![vscode](https://user-images.githubusercontent.com/40359487/71361311-9da2c600-2560-11ea-8347-1a9b70f8690d.gif)

_#6475:_

![new](https://user-images.githubusercontent.com/40359487/71361323-a72c2e00-2560-11ea-9d71-8ce6dcfdbd06.gif)

**Comment by akosyakov** [comment]
fixed in https://github.com/eclipse-theia/theia/pull/6475
