### ISSUE TITLE
centos error in build

### ISSUE THREAD

**Issue by 1637410810** [eclipse-theia/theia#6793]
- node:10.15.3

- python:2.7.5

- yarn:1.7.0

Red Hat-based: sudo yum install libX11-devel.x86_64 libxkbfile-devel.x86_64 # or .i686

I failed to execute lerna bootstrap in the directory
`native-keymap: Command failed`

**Comment by akosyakov** [comment]
@1637410810 Which command do you execute? Could you provide the entire log please?

**Comment by akosyakov** [comment]
@apupier @marechal-p Maybe you have an idea what goes wrong? I don't have an experience with CentOS.

**Comment by 1637410810** [comment]
This issue is resolved, g ++ is missing on centos

**Comment by 1637410810** [comment]
But the dependency always cannot be downloaded sometimes

**Comment by 1637410810** [comment]
@akosyakov This issue is resolved, g ++ is missing on centos。But the dependency always cannot be downloaded sometimes

**Comment by akosyakov** [comment]
@1637410810 Should we update [prerequisites](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites)? If not please please feel free to close the issue. Otherwise PRs are welcome! 😊

**Comment by 1637410810** [comment]
Centos lacks gcc or low version, the latest dynamic library of gcc is not found after update. The dynamic library of gcc needs to be updated

**Comment by 1637410810** [comment]
@akosyakov Centos lacks gcc or low version, the latest dynamic library of gcc is not found after update. The dynamic library of gcc needs to be updated

**Comment by 1637410810** [comment]
@akosyakov Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /theia/node_modules/nsfw/build/Release/nsfw.node)

**Comment by 1637410810** [comment]
I think should update

**Comment by 1637410810** [comment]
@akosyakov 
The solution I found:
Install Anaconda3-2019.10-Linux-x86_64.sh
`source ~ / .bashrc`

`LD_LIBRARY_PATH = / root / anaconda3 / lib: $ LD_LIBRARY_PATH` (add the anaconda3 library file path to the system's library file path)
`export LD_LIBRARY_PATH`

**Comment by vince-fugnitto** [comment]
@1637410810 what's left or required to resolve the issue?

**Comment by 1637410810** [comment]
No more
