### ISSUE TITLE
Plugin api window.activeTerminal can't get the right active terminal

### ISSUE THREAD

**Issue by godlin-gh** [eclipse-theia/theia#6797]
### Description
 
I've written a vscode extension(also a theia plugin) which use the api window.activeTerminal. It works well on vscode but not on theia.

I've debugged the theia source code and found the bug here:
https://github.com/eclipse-theia/theia/blob/c99cc1d574864d3ef4049775645313032b36b66d/packages/terminal/src/browser/terminal-frontend-contribution.ts#L116-L120

The `onDidChangeCurrentTerminal` should not be assigned `this.onDidCreateTerminalEmitter.event`, it shoud be `this.onDidChangeCurrentTerminalEmitter.event`

### Reproduction Steps

1. debug source code
2. set breakpoint on `TerminalServiceMainImpl.updateCurrentTerminal` method
3. change active terminal on theia UI, you'll find out that the breakpoint never be reached.

or you can try to write a plugin use window.activeTerminal api

**OS and Theia version:**
master
**Diagnostics:**

**Comment by akosyakov** [comment]
@Godlinbupt please feel free to send a PR

**Comment by Godlinbupt** [comment]
> @Godlinbupt please feel free to send a PR

OK，I will send a PR later.
