### ISSUE TITLE
plugin api window.showTextDocument was't implemented correctly

### ISSUE THREAD

**Issue by godlin-gh** [eclipse-theia/theia#6800]
### Description
 

definition here:
https://github.com/eclipse-theia/theia/blob/a99b5854361b2e1c94d92efd430fd38287541684/packages/plugin/src/theia.d.ts#L3169

implementation here:
https://github.com/eclipse-theia/theia/blob/a99b5854361b2e1c94d92efd430fd38287541684/packages/plugin-ext/src/plugin/plugin-context.ts#L266-L278

the second arg can be ViewColumn type, but the implementation ignore that type

### Reproduction Steps

try to call the api like this: showTextDocument(xx, ViewColumn.Two, true)

**OS and Theia version:**
master
**Diagnostics:**

**Comment by godlin-gh** [comment]
I can send a PR if needed.

**Comment by akosyakov** [comment]
@godlin-gh sure, PRs are always welcomed
