### ISSUE TITLE
DocumentsMainImpl.toEditorOpenerOptions should convert ViewColumn to zero-based index

### ISSUE THREAD

**Issue by godlin-gh** [eclipse-theia/theia#6801]
### Description
 

when i call plugin api window.showTextDocument, the call hierarchy looks like:
DocumentsMainImpl.$tryShowDocument -> DocumentsMainImpl.toEditorOpenerOptions

https://github.com/eclipse-theia/theia/blob/a99b5854361b2e1c94d92efd430fd38287541684/packages/plugin-ext/src/main/browser/documents-main.ts#L176-L188

https://github.com/eclipse-theia/theia/blob/a99b5854361b2e1c94d92efd430fd38287541684/packages/plugin-ext/src/main/browser/documents-main.ts#L240-L246

the ViewColumn type use one-based index which should be convert to zero-based index inside `toEditorOpenerOptions` method

### Reproduction Steps

try to call window.showTextDocument(xx, { viewColumn: ViewColumn.One }), you can never open an editor on first column.

**OS and Theia version:**
master
**Diagnostics:**

**Comment by godlin-gh** [comment]
I found there are two other reference of `toEditorOpenerOptions` method at [plugin-vscode-commands-contribution.ts](https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts)

one of that convert the viewColumn to zero-based index using `fromViewColumn` method outside `toEditorOpenerOptions` like below:
https://github.com/eclipse-theia/theia/blob/a99b5854361b2e1c94d92efd430fd38287541684/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L105-L123

I think assigned 0 to a viewColumn may be confused, we shoud do that inside the `toEditorOpenerOptions` instead.

**Comment by akosyakov** [comment]
@godlin-gh it sounds reasonable, feel free to work on it.
