### ISSUE TITLE
dispose all terminals 

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#6802]
### Description
Is there a way to close all opened terminals programmatically?

### Reproduction Steps
I didn't find any API to close the terminals which are opened in the editor.

**OS and Theia version:**

**Diagnostics:**

**Comment by dhananjayharel** [comment]
Actually I got the way to do it by simply calling the  API
https://github.com/eclipse-theia/theia/blob/fc49b2c3b8a690ba5b94e1fd48cf17469b51057d/packages/core/src/browser/shell/application-shell.ts#L1169

shell.collapsePanel('bottom')

**Comment by akosyakov** [comment]
You can also access all terminals from `WidgetManager` by a terminal factory id and then iterate and close them.
