### ISSUE TITLE
[Theming] View Icons seem a little dark

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#6805]
### Description
In the default dark mode the view icons seem a little too dark.

<img width="76" alt="Screenshot 2020-01-02 at 09 04 43" src="https://user-images.githubusercontent.com/372735/71660223-a5295280-2d4a-11ea-853c-2ff097593194.png">

vs

<img width="98" alt="Screenshot 2020-01-02 at 08 48 44" src="https://user-images.githubusercontent.com/372735/71660225-a5295280-2d4a-11ea-8da6-ac3f7553faa5.png">

**Comment by akosyakov** [comment]
With the approach there is a color variable for an inactive tab, but we still apply opacity on top of it making color even darker.
