### ISSUE TITLE
secondary buttons are not distinguishable from primary

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6806]
Before:
<img width="522" alt="Screen Shot 2020-01-02 at 14 37 35" src="https://user-images.githubusercontent.com/3082655/71660689-b0da4080-2d6d-11ea-9a84-cc90ac965091.png">

Now:
<img width="525" alt="Screen Shot 2020-01-02 at 14 36 08" src="https://user-images.githubusercontent.com/3082655/71660690-b172d700-2d6d-11ea-8fb4-6b4d9e88274a.png">

**Comment by vince-fugnitto** [comment]
At the moment, it looks like secondary button backgrounds are calculated from primary buttons but also lightening or darkening. Perhaps it'd be enough to also calculate a grayscale value? (unless secondary colors should also be similar to primary buttons but different shades)

**Comment by akosyakov** [comment]
>  Perhaps it'd be enough to also calculate a grayscale value? (unless secondary colors should also be similar to primary buttons but different shades)

Unfortunately we can simple change color values only for our themes, but variables should be always derived from VS Code variables: https://github.com/eclipse-theia/theia/wiki/Coding-Guidelines#theming-derive-colors-from-vscode We could try to pick another variable as a base which is grayish.
