### ISSUE TITLE
How to add plugins in Windows 10 machine

### ISSUE THREAD

**Issue by NitinKhandelwal1947** [eclipse-theia/theia#6823]
### Description
How to add theia plugins in Windows 10 machine. i am trying to add a sample plugins in theia electron which is bundle with electron-builder.
It throws below error when i start the application
```root ERROR No plugin resolver found for the entry C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins```

### Reproduction Steps
If I set ```THEIA_DEFAULT_PLUGINS``` as below command  ```setx THEIA_DEFAULT_PLUGINS "C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins\" ```
it throws below error..
```root ERROR No plugin resolver found for the entry C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins```

And If i set ```THEIA_DEFAULT_PLUGINS``` as below command 
```local-dir:C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins``` it throws below ```error root WARN The directory referenced by 
 local-dir:C:\theia\examples\electron\dist\win-ia32-unpacked\resources\app\plugins" does not exist```

**OS and Theia version:**

yarn version:- 1.7.0
node version:- 10.15.3
npm version:- 4.6.1
Windows 10 System
Theia:- 0.11.0

**Diagnostics:**

**Comment by NitinKhandelwal1947** [comment]
@akosyakov  The issue is resolved by setting THEIA_DEFAULT_PLUGINS as below
```setx THEIA_DEFAULT_PLUGINS "local-dir:C:\\theia\\examples\\electron\\dist\\win-ia32-unpacked\\resources\\app\\plugins"```

**Comment by marcdumais-work** [comment]
@NitinKhandelwal1947 thanks for providing the solution that resolved this issue for you.
