### ISSUE TITLE
[theming] adjust selected node foreground color (description, decorators)

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6831]
**Description**

The foreground color for secondary data present in tree nodes should be updated so they are easily visible when they have selection, for instance, the following occurs in the `preferences-tree-widget`:

![image](https://user-images.githubusercontent.com/40359487/71824552-d1551400-3067-11ea-8551-f0780adf3a01.png)

And in the `explorer` for decorations:

![image](https://user-images.githubusercontent.com/40359487/71824593-eaf65b80-3067-11ea-9c83-a36162b65577.png)

**Comment by akosyakov** [comment]
Are you sure that it is not the same for explorer in vs code?

**Comment by vince-fugnitto** [comment]
> Are you sure that it is not the same for explorer in vs code?

Yes, it is more clearly displayed, I believe with selection, the entire row has the same foreground color for visibility:

![image](https://user-images.githubusercontent.com/40359487/71825039-f8f8ac00-3068-11ea-8fd4-9ab63024df2a.png)

![image](https://user-images.githubusercontent.com/40359487/71825068-0a41b880-3069-11ea-89b9-d5e5a4ff4a5a.png)
