### ISSUE TITLE
Open new terminal using the selected folder as path

### ISSUE THREAD

**Issue by hugleo** [eclipse-theia/theia#6838]
When I open a terminal the work path generally is:

/workspace/theia

Maybe would be interesting if when I select for example the doc folder in the file tree a new terminal would be opened with the path:

/workspace/theia/doc

**Comment by akosyakov** [comment]
You can use `Open in Terminal` in the context menu for any folder. This command is always available in the quick command palette when a folder is selected in the navigator.

**Comment by hugleo** [comment]
I didn't notice the option in the context menu. I recheck and now i figure out.
