### ISSUE TITLE
Update of preferences from VSCode plugin triggers multiple overwrite popup confirmation

### ISSUE THREAD

**Issue by crawr** [eclipse-theia/theia#6845]
### Description
It seems there is an inconsistency between the vscode.workspace.getConfiguration().update API in VSCode and Theia. 
Even though there are no changes in the configuration, the update is triggered and is trying to overwrite the contents in the settings.json file.

Is there a way to turn off the overwrite confirmation?
Is this a bug in the FileSystem watcher?

### Reproduction Steps
Extension: [Zowe Explorer](https://github.com/zowe/vscode-extension-for-zowe/)
Whenever the browser is refreshed or left idle for a while, the following popup appears multiple times:
![overwrite](https://user-images.githubusercontent.com/45845502/71983058-3fdfd080-3226-11ea-982d-bf915bf2540c.png)

**OS and Theia version:**
Windows 10
latest Theia

**Comment by vince-fugnitto** [comment]
Related https://github.com/eclipse-theia/theia/issues/6786

**Comment by akosyakov** [comment]
@vince-fugnitto yes, I think the fix should have both cases

**Comment by venkatzhub** [comment]
@akosyakov - The above mentioned error message is happening very frequently. Our end users/customers of Zowe Explorer are experiencing this a lot and are complaining about it. Wondering if there is a workaround of some sort to at least minimize the frequency of the pop up, while you are working on the fix?

**Comment by vince-fugnitto** [comment]
> @akosyakov - The above mentioned error message is happening very frequently. Our end users/customers of Zowe Explorer are experiencing this a lot and are complaining about it. Wondering if there is a workaround of some sort to at least minimize the frequency of the pop up, while you are working on the fix?

I think if you don't want to display the dialog any longer until there is a proper fix, you can unbind the following:

https://github.com/eclipse-theia/theia/blob/554f99edf3f0c98a87986686aa8aa9bfcfcba4f2/packages/filesystem/src/browser/filesystem-frontend-module.ts#L44-L53

**Comment by venkatzhub** [comment]
@vince-fugnitto - Thank you, we will try that.

**Comment by akosyakov** [comment]
I had to fix tests yet, but could someone try please whether you can reproduce it with https://github.com/eclipse-theia/theia/pull/7110?
