### ISSUE TITLE
Some VSCode theme colours missing in Webviews

### ISSUE THREAD

**Issue by lopesc** [eclipse-theia/theia#6849]
### Description
Some of the vscode colour variables are not injected into the webview. Example: Neither`--vscode-input-border` and `--theia-input-border` are available:
<img width="518" alt="Screen Shot 2020-01-08 at 16 58 01" src="https://user-images.githubusercontent.com/7646447/71998743-1891ff00-3238-11ea-9095-cf909c9ad0e3.png">

This example (input-border) is available in VSCode:
https://code.visualstudio.com/api/references/theme-color#input-control

### Reproduction Steps
- Open a webview extension containing html elements which are coloured using either`--theia-input-border` or `--vscode-input-border` variable. 
- The colour is not applied because the variables are missing from the Document

**OS and Theia version:**
Mac OS X,  Theia version v.14
**Diagnostics:** 

@akosyakov

**Comment by akosyakov** [comment]
If value of a variable is undefined for some theme then css variable won’t be available. To truly check whether variable is missing one should check whether its identifier does not belong to `ColorRegistry.getColors`. Generally VS code themes use transparent borders and play with background contrast except high contrast theme which reverse the logic, i.e. the same background but 2 different colors for borders to indicate usual boundaries and special element.

**Comment by lopesc** [comment]
Hi @akosyakov, Thanks for your reply. 

>If value of a variable is undefined for some theme then css variable won’t be available

I don't think that is the case in VSCode. If you do not define a variable in your theme, then it should fallback to the light or dark default (depending on your theme type). To demonstrate, I have created an example theme where the only colour defined in the theme is `"input.background": "#0000ff"` : https://github.com/lopesc/input-blue-theme. 

Here is the result in the webview:
![Screen Shot 2020-01-08 at 19 19 54](https://user-images.githubusercontent.com/7646447/72008750-729cbf80-324c-11ea-8ea5-f149bc1eef37.png)


I would have expected the same behaviour in Theia.

> Generally VS code themes use transparent borders and play with background contrast except high contrast theme which reverse the logic, i.e. the same background but 2 different colors for borders to indicate usual boundaries and special element.

My example is a very simplistic - what would happen to the UI of VSCode if there where no definitions in the themes for things like the editor background, or text foreground colour?

**Comment by akosyakov** [comment]
> I don't think that is the case in VSCode. If you do not define a variable in your theme, then it should fallback to the light or dark default (depending on your theme type).

It is the same in Theia, I meant when even the base light or dark theme does not have default value.

**Comment by akosyakov** [comment]
But color is there in main window, so something wrong with webviews. I will send a PR.

**Comment by akosyakov** [comment]
I could not find what is broken, as I suspected `input.border` is only have value for base HC theme: https://github.com/microsoft/vscode/blob/d3cda21f0e7e3187d53b4db9c52465f1cc660d74/src/vs/platform/theme/common/colorRegistry.ts#L206

All other variables are there in Theia and VS Code.

**Comment by lopesc** [comment]
> I could not find what is broken, as I suspected `input.border` is only have value for base HC theme: https://github.com/microsoft/vscode/blob/d3cda21f0e7e3187d53b4db9c52465f1cc660d74/src/vs/platform/theme/common/colorRegistry.ts#L206
> 
> All other variables are there in Theia and VS Code.
> 
> Do you have any real visual issue?

It is given a value the light themes as well, even when the theme does not define it. See my example:
![Screen Shot 2020-01-08 at 19 19 54](https://user-images.githubusercontent.com/7646447/72008750-729cbf80-324c-11ea-8ea5-f149bc1eef37.png)

**Comment by lopesc** [comment]
Take look at his theme in vscode and you will see that input border is given a value:
https://github.com/lopesc/input-blue-theme

**Comment by akosyakov** [comment]
> It is given a value the light themes as well, even when the theme does not define it. See my example:

@lopesc There is no `--vscode-input-border` on the picture. Could you try to look exactly for this variable?

How do you look up styles in VS Code? For which element?
