### ISSUE TITLE
Plugins keep reloading

### ISSUE THREAD

**Issue by toonvd** [eclipse-theia/theia#6860]
### Description
Plugins keep reloading due to  Language client not being ready

### Reproduction Steps
- Install Theia 0.14.0 with node v11.15.0 and npm v6.7.0 on Debian Stretch
- start developing

**OS and Theia version:**
Debian Stretch, 0.14.0

**Diagnostics:** 
```
Uncaught Error: Language client is not ready yet

Error: Language client is not ready yet
    at t.value (bundle.js:1)
    at n (bundle.js:1)
    at Object.provideCodeActions (bundle.js:1)
    at Object.provideCodeActions (bundle.js:82)
    at t.<anonymous> (bundle.js:82)
    at bundle.js:82
    at Object.next (bundle.js:82)
    at bundle.js:82
    at new Promise (<anonymous>)
    at c (bundle.js:82)
    at /vs/editor/editor.main.js:42
```

```
logger-protocol.ts:112 root WARN Error: Possible Emitter memory leak detected. 31 listeners added. Use event.maxListeners to increase the limit (30)
    at e.checkMaxListeners (xxx/bundle.js:1:64957)
    at Object.<anonymous> (xxx/bundle.js:1:64499)
    at t.value (xxx/bundle.js:1:517845)
    at xxx/bundle.js:1:511711
```

```
editor.main.js:42 Uncaught Error: Language client is not ready yet

Error: Language client is not ready yet
    at t.value (client.js:1709)
    at n (client.js:1122)
    at Object.provideCodeActions (client.js:1147)
    at Object.provideCodeActions (vscode-api.ts:259)
    at t.<anonymous> (monaco-languages.ts:176)
    at bundle.js:82
    at Object.next (bundle.js:82)
    at bundle.js:82
    at new Promise (<anonymous>)
    at c (bundle.js:82)
    at editor.main.js:42
```

```
logger-protocol.ts:112 root WARN Error: Possible Emitter memory leak detected. 32 listeners added. Use event.maxListeners to increase the limit (30)
    at e.checkMaxListeners (xxx/bundle.js:1:64957)
    at Object.<anonymous> (xxx/bundle.js:1:64499)
    at t.value (xxx/bundle.js:1:517845)
    at xxx/bundle.js:1:511711
```

**Comment by vince-fugnitto** [comment]
@toonvd can you describe in further details the reproduction steps? For example, which plugin(s) were currently deployed, which language server was throwing errors, etc. It's hard at the moment to pinpoint what is happening.

**Comment by toonvd** [comment]
Hi

Thank you for the feedback.
I am using the standard package.json from theia applications with no additional plugins.

```
{
    "private": true,
    "theia": {
        "frontend": {
            "config": {
                "applicationName": "Theia JavaScript/TypeScript Example",
                "preferences": {
                    "files.enableTrash": false
                }
            }
        }
    },
    "dependencies": {
        "@theia/callhierarchy": "latest",
        "@theia/debug": "latest",
        "@theia/debug-nodejs": "latest",
        "@theia/file-search": "latest",
        "@theia/git": "latest",
        "@theia/json": "latest",
        "@theia/markers": "latest",
        "@theia/merge-conflicts": "latest",
        "@theia/messages": "latest",
        "@theia/mini-browser": "latest",
        "@theia/navigator": "latest",
        "@theia/outline-view": "latest",
        "@theia/preferences": "latest",
        "@theia/preview": "latest",
        "@theia/search-in-workspace": "latest",
        "@theia/terminal": "latest",
        "@theia/textmate-grammars": "latest",
        "@theia/tslint": "latest",
        "@theia/typescript": "latest",
        "typescript": "latest"
    },
    "resolutions": {
        "vscode-languageserver-protocol": "3.15.0-next.9",
        "vscode-languageserver-types": "3.15.0-next.5",
        "**/vscode-json-languageserver/**/vscode-languageserver": "6.0.0-next.1"
    },
    "devDependencies": {
        "@theia/cli": "latest"
    }
}
```

**Comment by vince-fugnitto** [comment]
@toonvd sorry I was confused as the title mentioned `plugins`. What is the issue?

**Comment by toonvd** [comment]
Hi

Together with these messages, my Vscode plugins got reloaded.
When I disabled them, the behaviour stays te same. Under network, at this moment, I see a new services websocket opened.

**Comment by vince-fugnitto** [comment]
> Hi
> 
> Together with these messages, my Vscode plugins got reloaded.
> When I disabled them, the behaviour stays te same. Under network, at this moment, I see a new services websocket opened.

Which VS Code plugins are you using? I'm sorry but it is unclear and hard to determine what is failing at the moment based on the information provided.

**Comment by toonvd** [comment]
Hi

Sorry for being unclear.

I took a step back to analyse the problem more properly.
I am now running a clean install of 0.14.0 and have the same issue.
It seems like the editor completely disconnects for a second.

I cannot type and my terminal gets reloaded.

This goes together with a reopen of the /services endpoint and the js error and warning I mentioned before. (they all have the exact same timing)

**Comment by toonvd** [comment]
Hi

Looking at this more properly, it looks like a timeout.
Reconnecting-websocket-mjs.js:483 is making a request to /services every 30 seconds.
This is indeed when the reload happens. I think the Google Loadbalancer in front of the server might have something to do with this. Shall I close the issue and investigate further?

**Comment by vince-fugnitto** [comment]
> Hi
> 
> Looking at this more properly, it looks like a timeout.
> Reconnecting-websocket-mjs.js:483 is making a request to /services every 30 seconds.
> This is indeed when the reload happens. I think the Google Loadbalancer in front of the server might have something to do with this. Shall I close the issue and investigate further?

Sure sounds good! Thank you for continuing to investigate further.

**Comment by toonvd** [comment]
Hi

The Google docs made this more clear. Usualy, a timeout only happens on inactive websockets, but Google LBs also enforce it over active connections.

> The timeout for a WebSocket connection depends on the configurable response timeout of the load balancer, which is 30 seconds by default. This timeout is applied to WebSocket connections regardless of whether they are in use. For more information about the response timeout and how to configure it, see Timeouts and retries.

You can just configure a higher timeout in the backend settings of the loadbalancer.
I hope maybe my comment can help others with this issue.
