### ISSUE TITLE
Can't Activate the Neo Vim plugin.

### ISSUE THREAD

**Issue by carl-parrish** [eclipse-theia/theia#6861]
### Description
Tried installing the neoVim plugin https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim. Install seemed to go well. I set the path to nvim then I got a message saying that Activating the extension failed. 

### Reproduction Steps

**OS and Theia version:**
ChromeOS - Version 79.0.3945.86 (Official Build) (64-bit)
The latest version of GitPod. 

**Diagnostics:** 
Activating extension Neo Vim failed: nvim_ui_attach: No such UI option: ext_messages.

**Comment by vince-fugnitto** [comment]
@carl-parrish I assume you've also installed https://github.com/neovim/neovim/wiki/Installing-Neovim version 0.4.2 or greater? It is described as a pre-requisite in the extension's [README](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim).

**Comment by carl-parrish** [comment]
nvim -v
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3

I'll see if I can upgrade the version.

**Comment by vince-fugnitto** [comment]
Please re-open the issue if the problem persists with the correct pre-requisite versions.

**Comment by carl-parrish** [comment]
I see this has already been closed but wanted to follow up and say that it seems to work find with the upgraded version of neovim.
