### ISSUE TITLE
Can't install the WakaTime Extention

### ISSUE THREAD

**Issue by carl-parrish** [eclipse-theia/theia#6862]
### Description
https://marketplace.visualstudio.com/items?itemName=WakaTime.WakaTime

### Reproduction Steps
Install the WakaTime extension at the above URL Try to run it get the error message below. 

**OS and Theia version:**

**Diagnostics:** 
A valid extension cannot be found in WakaTime.vsix.

**Comment by vince-fugnitto** [comment]
The extension [WakaTime](https://marketplace.visualstudio.com/items?itemName=WakaTime.WakaTime) is a **Visual Studio** extension and not a **VS Code** one.
**Visual Studio** extensions are not supported.

Please use the following instead: 
https://marketplace.visualstudio.com/items?itemName=WakaTime.vscode-wakatime

**Comment by carl-parrish** [comment]
Thank you I wasn't aware that there was a difference in extensions. This one worked fine.

**Comment by vince-fugnitto** [comment]
> Thank you I wasn't aware that there was a difference in extensions. This one worked fine.

No problem, they are two completely different products:
- Visual Studio: https://visualstudio.microsoft.com/vs/
- Visual Studio Code: https://code.visualstudio.com/?wt.mc_id=DX_841432

The application supports [Visual Studio Code](https://code.visualstudio.com/?wt.mc_id=DX_841432) extensions as plugins :)
