### ISSUE TITLE
LaTeX Preview vscode extension/plugin fails

### ISSUE THREAD

**Issue by dannaf** [eclipse-theia/theia#6865]
### Description
Deploying the vscode [LaTeX Preview](https://marketplace.visualstudio.com/items?itemName=ajshort.latex-preview) plugin does not work

(Especially limiting since other LaTeX plugins are also failing, see https://github.com/eclipse-theia/theia/issues/6408 / https://github.com/eclipse-theia/theia/issues/5794)

### Reproduction Steps
`Deploy plugin by id` with `vscode:extension/ajshort.latex-preview`

Create/open a `.tex` file

Expect a tab to appear with button to `Open Preview`, like in the documentation of the vscode extension.  It does not appear.  Also none of the `Latex: ` commands that the app exposes seem to do anything (except the `Latex: Create Build Task` command makes a `tasks.json` file in `.theia`, but there seems to be no effect).

### Theia version
`latest` via docker on Ubuntu 18.04, frontend via Windows 10

### Diagnostics

```
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf] Sync of 2 plugins took: 502.2549999994226 ms
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf][ms-python.python]: Loaded contributions.
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf][ajshort.latex-preview]: Loaded contributions.
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf] Load contributions of 2 plugins took: 124.4099999894388 ms
root INFO [hosted-plugin: 4522] PLUGIN_HOST(4522): PluginManagerExtImpl/init()
root INFO [hosted-plugin: 4522] PLUGIN_HOST(4522): initializing(python@2019.11.50794 with /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
root INFO [hosted-plugin: 4522] Debugger contribution has been registered: python
root INFO [hosted-plugin: 4522] PLUGIN_HOST(4522): initializing(latex-preview@0.5.1 with /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf][ms-python.python]: Started plugin.
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf][ajshort.latex-preview]: Started plugin.
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf] Start of 2 plugins took: 106.57499998342246 ms
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf] Sync of 0 plugins took: 3.3699999912641943 ms
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf] Load contributions of 0 plugins took: 0.020000035874545574 ms
root INFO [10e9afb7-2825-440d-aaa9-8e2e0452e5bf] Start of 0 plugins took: 14.989999996032566 ms
```

**Comment by vince-fugnitto** [comment]
@dannaf the [extension](https://github.com/ajshort/vscode-latex-preview) you referenced is quite old, and unmaintained (latest release was over 3 years ago). I tested the extension in VS Code and it also did no work with the same error displayed in Theia, mainly:

```
command 'vscode.previewHtml' not found
```

If an extension is not maintained and is not updated regularly (against new APIs and breaking changes) I'm not sure there is much we can do. Especially since the extension fails to work properly in newer versions of VS Code.

**Comment by vince-fugnitto** [comment]
Ideally, when testing for plugin support and before opening issues, it's important to first determine:
- If the extension properly works in VS Code.
- If there are known issues regarding the plugin (browsing the issues in the extensions repository).
