### ISSUE TITLE
Add configurable clean for .theia/logs folder.

### ISSUE THREAD

**Issue by ira-gordin-sap** [eclipse-theia/theia#6866]
### Description
.theia/logs folder is not cleaned.

### Reproduction Steps
Create VS code extension which writes logs to context.logPath received in activate() method.
In my VS Code extension I have:
export function activate(context: vscode.ExtensionContext). 
The value of context.logPath on my environment is .theia/logs/20200109T092254/host/<my-ext-pablisher>.<my-ext-name>. I use this folder to create my logs files there. 

**OS and Theia version:**
OS: Linux
Theia version: v0.14.0

**Diagnostics:** 
"ls .theia/logs/" shows many folders named as timestamps like 20200109T092254. Currently I see that the oldest one is from the time I created my container.

**Comment by vince-fugnitto** [comment]
@ira-gordin-sap 
Thanks for the issue, do you know the current behavior in VS Code?
When are log files cleaned? At which interval? I assume log files are generally cleaned when an extension is deactivated/uninstalled.

**Comment by ira-gordin-sap** [comment]
I don't know the current behavior in VS Code.
I am not sure it should happen when an extension is deactivated/uninstalled. I am not sure when deactivate happens on theia.
I thought about automatic clean once a configurable time.

**Comment by vince-fugnitto** [comment]
@ira-gordin-sap when testing, which plugins were you using?
I'm trying to determine if it is the responsibility of the plugins to cleanup their log files, or the application itself at some point (and which point/interval).

**Comment by ira-gordin-sap** [comment]
@vince-fugnitto I am implementing log in my VS code extension.
My colleague have found here: https://github.com/microsoft/vscode/issues/75539 that VS Code retains logs of last 10 sessions. (I verified it on my environment.)
The relevant code is here: https://github.com/Microsoft/vscode/blob/613447d6b3f458ef7fee227e3876303bf5184580/src/vs/code/electron-browser/sharedProcess/contrib/logsDataCleaner.ts#L12

**Comment by vince-fugnitto** [comment]
> microsoft/vscode#75539

Thank you for investigating further and following up.
Is it something you'd like to handle? PRs are always welcome and you can copy the code from VS Code directly so long as a [Contribution Questionnaire (CQ)](https://github.com/eclipse-theia/theia/wiki/Registering-CQs) is registered.

**Comment by bd82** [comment]
> you can copy the code from VS Code directly

Are these APIs available directly in Theia or should alternatives be used?
```javascript
import { IEnvironmentService } from 'vs/platform/environment/common/environment';
import { join, dirname, basename } from 'vs/base/common/path';
import { readdir, rimraf } from 'vs/base/node/pfs';
import { onUnexpectedError } from 'vs/base/common/errors';
import { Disposable, toDisposable } from 'vs/base/common/lifecycle';
```

**Comment by vince-fugnitto** [comment]
> > you can copy the code from VS Code directly
> 
> Are these APIs available directly in Theia or should alternatives be used?
> 
> ```js
> import { IEnvironmentService } from 'vs/platform/environment/common/environment';
> import { join, dirname, basename } from 'vs/base/common/path';
> import { readdir, rimraf } from 'vs/base/node/pfs';
> import { onUnexpectedError } from 'vs/base/common/errors';
> import { Disposable, toDisposable } from 'vs/base/common/lifecycle';
> ```

Looking at the code previously referenced, there does not seem to be anything preventing getting the feature to work properly. There are definitely internal Theia methods and APIs that can be used to compliment the feature. Please note that if a straight copy+paste cannot be used, you can always inspire yourself from their implementation.

**Comment by ira-gordin-sap** [comment]
> > [microsoft/vscode#75539](https://github.com/microsoft/vscode/issues/75539)
> 
> Thank you for investigating further and following up.
> Is it something you'd like to handle? PRs are always welcome and you can copy the code from VS Code directly so long as a [Contribution Questionnaire (CQ)](https://github.com/eclipse-theia/theia/wiki/Registering-CQs) is registered.

I would very much like to handle. Waiting for approval from my product owner.

**Comment by vince-fugnitto** [comment]
> > > [microsoft/vscode#75539](https://github.com/microsoft/vscode/issues/75539)
> > 
> > 
> > Thank you for investigating further and following up.
> > Is it something you'd like to handle? PRs are always welcome and you can copy the code from VS Code directly so long as a [Contribution Questionnaire (CQ)](https://github.com/eclipse-theia/theia/wiki/Registering-CQs) is registered.
> 
> I would very much like to handle. Waiting for approval from my product owner.

Sounds great!

**Comment by bd82** [comment]
Hello. 

I have a fix here:
- https://github.com/bd82/theia/commit/5e4abe350d660d1c9d5a51af474ffc3dd5554e32

However I have reservations regarding the Eclipse Foundation Licensing.
- https://www.eclipse.org/legal/ECA.php
- Particularly as the filling the ECA seems to require a providing a **physical postal address**.
- Combined with waving the rights related to personal information (GDPR)
 > I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my signoff) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.

Does providing a Physical Postal Address Mandatory to Sign the eclipse ECA?
Is this a question that should be forwarded to eclipse foundation legal department?

**Comment by bd82** [comment]
Could my Employer's (who I am making the contribution on behalf of) address be provided?
Even more generally an address of my Employer in a different country than the one I reside in?

**Comment by vince-fugnitto** [comment]
@marcdumais-work perhaps you can help regarding the Eclipse ECA questions?
@bd82 when I signed up, I did not provide any address information as I believe it is unnecessary (although I'm not sure if this policy has changed).

**Comment by marcdumais-work** [comment]
Hi @bd82,

> Could my Employer's (who I am making the contribution on behalf of) address be provided?
> Even more generally an address of my Employer in a different country than the one I reside in?

First I do not speak for the Eclipse Foundation and IINAL. If you feel the need, we can involve someone from the foundation to get a more definitive answer. 

Looking at my own ECA, I provided the address of my employer, so I think that's fine if you contribute in the context of your work. As far as I know, the country of your employer being different from your own would not matter - your employer's address is what it is.

**Comment by bd82** [comment]
> Looking at my own ECA, I provided the address of my employer, so I think that's fine if you contribute in the context of your work. As far as I know, the country of your employer being different from your own would not matter - your employer's address is what it is.

O.k. sounds good enough. I will continue creating the PR tomorrow.

Cheers.

**Comment by bd82** [comment]
o.k. I used my employer's physical address.

A PR was created: https://github.com/eclipse-theia/theia/pull/6956

This could be used as a stepping stone to include also **configurable** options: e.g:
- Instead of hard-coded 10 last sessions, keep **X** last sessions.

Cheers.
Shahar.

**Comment by marcdumais-work** [comment]
> o.k. I used my employer's physical address.

The ECA check on your PR passed, so you're all set
