### ISSUE TITLE
[search-in-workspace] opening files outside the workspace root are not included in the search results

### ISSUE THREAD

**Issue by spoenemann** [eclipse-theia/theia#6867]
### Description
When using the Search view, no results are shown for files that are opened in an editor, but are not contained in the workspace root. I would expect such files to be included in the search.
Related: #6641

### Reproduction Steps
 * Open a file that is not in the workspace root directory
 * Open the Search view and enter a string that should be found in that file

**Comment by vince-fugnitto** [comment]
The issue is the `search-in-workspace` and not the `file-search` correct?

**Comment by spoenemann** [comment]
It's in the _Search_ view. I don't know how it's called internally.

**Comment by vince-fugnitto** [comment]
> It's in the _Search_ view. I don't know how it's called internally.

The `search-in-workspace` extension :) That's why I was confused by `file-search` which is in fact simply being able to quickly open files by <kbd>ctrlcmd</kbd>+<kbd>p</kbd>.
