### ISSUE TITLE
Automatically render `Pipfile`s as TOML

### ISSUE THREAD

**Issue by RDIL** [eclipse-theia/theia#6890]
`Pipfile` files are TOML and should be highlighted as such.

**Comment by vince-fugnitto** [comment]
@RDIL thanks for the issue, can you perhaps describe the problem in further detail?
I assume that you do not see syntax highlighting for pipfiles? 

This will likely be covered by the [VS Code Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python)

Related issue:
- https://github.com/Microsoft/vscode-python/issues/995

**Comment by RDIL** [comment]
Yup, theia thinks that it's just plain text.

The issue had a merged PR attached: https://github.com/microsoft/vscode-python/pull/1975

**Comment by vince-fugnitto** [comment]
> Yup, theia thinks that it's just plain text.
> 
> The issue had a merged PR attached: [microsoft/vscode-python#1975](https://github.com/microsoft/vscode-python/pull/1975)

The idea is to use [vscode-python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) over the soon-to-be-deprecated `@theia/python` extension. As a platform, we are trying to keep language specific extensions out of the framework in favor of them being contributed through external plugins (by applications), therefore there is no update to be made on the Theia side.

**Comment by vince-fugnitto** [comment]
If there is an issue using the [vscode-python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension within Theia (including syntax highlighting for `pipfiles`), then issues should be opened so that we can track and fix them.
