### ISSUE TITLE
Submenu icon

### ISSUE THREAD

**Issue by Hanksha** [eclipse-theia/theia#6891]
Add possibility to set an icon for a submenu. Current `MenuModelRegistry.registerSubmenu` only accept a label.

For example:
![Screen Shot 2020-01-16 at 9 13 35 AM](https://user-images.githubusercontent.com/6960133/72487245-5f8b8000-3848-11ea-880f-a2902942920d.png)
I'd like the `Add` submenu to have a `+` green icon.

**Comment by akosyakov** [comment]
@Hanksha I don't think active committers will work on it any time soon. An idea will be to add another argument to `registerSubmenu`, something like `SubmenuOptions`, which should be optional and it can have different properties in it. Feel free to work on it and send a PR.

**Comment by Hanksha** [comment]
@akosyakov Alright, I will do when I get some free time.

**Comment by Hanksha** [comment]
Got something working.
![Screen Shot 2020-02-06 at 10 24 58 AM](https://user-images.githubusercontent.com/6960133/73900509-fb9a2b80-48ca-11ea-8eb1-0881f87e41ac.png)

**Comment by vince-fugnitto** [comment]
Closed by https://github.com/eclipse-theia/theia/pull/7091
