### ISSUE TITLE
[core] fix typos present in '@theia/core'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6899]
**Description**

The following typos were discovered in `@theia/core` and should be properly fixed:

`offlline` > `offline`

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/common-frontend-contribution.ts#L1567

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/common-frontend-contribution.ts#L1575

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/common-frontend-contribution.ts#L1583

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/common-frontend-contribution.ts#L1591

---

`retrive` > `retrieve`

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/external-uri-service.ts#L31

---

`Comosition` > `Composition` (this is a breaking change and should properly documented in the `CHANGELOG`)

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/frontend-application.ts#L169-L176

---

`expexted` > `expected`

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/keyboard/browser-keyboard-layout-provider.ts#L391

---

`seprator` > `separator`

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/keyboard/keys.spec.ts#L237

---

`overriden` > `overridden`

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/preferences/preference-contribution.ts#L282-L290

---

`unversiouned` > `unversioned` 
https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/shell/application-shell.ts#L50

---

`renderes` > `renderers`
https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/shell/tab-bars.ts#L76

**Comment by justinang1** [comment]
What is the protocol for updating CHANGELOG.md? I read through the code guidelines and didn't find anything about it. Should entries be alphabetical and include a reference to the issue?

**Comment by vince-fugnitto** [comment]
> What is the protocol for updating CHANGELOG.md? I read through the code guidelines and didn't find anything about it. Should entries be alphabetical and include a reference to the issue?

In general changelog updates are done for a given release where items are sorted alphabetically and a reference to the corresponding pull request is added. In any case, before a release the changelog is revisited to format the document + add any missing entries.

**Comment by justinang1** [comment]
I'm having trouble figuring out merging/branches so I'm going to look into that and re-create the changes properly. Sorry!
