### ISSUE TITLE
hello world extension getting error

### ISSUE THREAD

**Issue by dhananjayharel** [eclipse-theia/theia#6902]
### Reproduction Steps
Here are the logs when I execute yarn command after 'yo theia-extension'

./node_modules/@theia/core/lib/browser/diff-uris.d.ts(31,5): error TS2416: **Property 'getConstituentUris' in type 'DiffUriLabelProviderContribution' is not assignable to the same property in base type 'LabelProviderContribution'.**
  Type '(uri: URI) => URI[]' is not assignable to type '(compositeElement: object) => URI[]'.
    Types of parameters 'uri' and 'compositeElement' are incompatible.
      Type '{}' is missing the following properties from type 'URI': codeUri, _path, displayName, allLocations, and 19 more.
../node_modules/@theia/core/lib/common/keyboard/keyboard-layout-provider.d.ts(16,55): error TS2307: Cannot find module 'native-keymap'.
../node_modules/reconnecting-websocket/dist/reconnecting-websocket.d.ts(7,10): error TS2440: Import declaration conflicts with local declaration of 'CloseEvent'.
../node_modules/reconnecting-websocket/dist/reconnecting-websocket.d.ts(7,22): error TS2440: Import declaration conflicts with local declaration of 'ErrorEvent'.
../node_modules/reconnecting-websocket/dist/reconnecting-websocket.d.ts(7,34): error TS2440: Import declaration conflicts with local declaration of 'Event'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/home/ubuntu/theia2/theia/programmr_testcasepopup/node_modules/
**OS and Theia version:**
Node version: 10.3
Theia version : latest
**Diagnostics:**

**Comment by dhananjayharel** [comment]
Was able to remove this error by replacing `_"strict":true_`  to `_"skipLibCheck":true_`
in tsconfig.json file.

**Comment by vince-fugnitto** [comment]
Closing since the proper repository is https://github.com/theia-ide/generator-theia-extension, please feel free to open an issue there. 

`skipLibChek` has been added as far as I know:

https://github.com/theia-ide/generator-theia-extension/pull/30/files#diff-0bdb67dbc524e1064bdf7aa65e73d6e4R3
