### ISSUE TITLE
Java language server not starting

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#6906]
### Description
Original report: https://github.com/theia-ide/theia-apps/issues/285

The Java LS is no longer starting correctly. I have reproduced the issue using the example application. 

### Reproduction Steps
Build the browser example and open a `.java` file. After a few seconds, an error message appears: "Failed to start Java language server: Message could not be parsed."

**OS and Theia version:**
Ubuntu 18.04, Theia most recent master

**Diagnostics:** 
Java LS log, mentioned in BE trace:
```
!SESSION 2020-01-17 10:58:14.584 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_232
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_CA
Command-line arguments:  -data /home/lmcmcds/.theia/jdt.ls/_ws_5fcbd99ae731c84e919a28bcee59808a51f4de24_0

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-01-17 10:58:16.012
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-01-17 10:58:16.138
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-01-17 10:58:16.185
!MESSAGE >> shutdown
```

**Comment by akosyakov** [comment]
@marcdumais-work Do we need to look into or rather switching an image to VS Code extension? It works much better.

**Comment by marcdumais-work** [comment]
> @marcdumais-work Do we need to look into or rather switching an image to VS Code extension? It works much better.

Either way works for me. We can keep this issue until @vince-fugnitto removes Java support from this repo or the current Java LS problem is fixed.

**Comment by marcdumais-work** [comment]
This issue is about the `@theia/java` extension that was removed from the repo and is no longer supported. Closing.
