### ISSUE TITLE
[Feature-Request] No toggle view for terminal

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse-theia/theia#6913]
### Description
Originally posted at https://github.com/gitpod-io/gitpod/issues/1120
There currently is no toggle view for teminal

**Comment by akosyakov** [comment]
Which terminal do you want to toggle? Terminals can be rearranged and put in other areas, not only in bottom. For the bottom panel there should be already a command to do it. You can also do it from the status bar, the most right element.

**Comment by JesterOrNot** [comment]
@ccssmnn Can you explain?

**Comment by ccssmnn** [comment]
When you open the command palette (cmd-shift-p on mac and iPad) you can type **toggle** to toggle the visibility of certain view elements, e.g. Outline, Explorer ... . There is a rich list when typing **toggle view** into the command palette.

Terminal is missing in this list, which makes it difficult to hide via command palette or keyboard shortcut.

**Comment by vince-fugnitto** [comment]
> When you open the command palette (cmd-shift-p on mac and iPad) you can type **toggle** to toggle the visibility of certain view elements, e.g. Outline, Explorer ... . There is a rich list when typing **toggle view** into the command palette.
> 
> Terminal is missing in this list, which makes it difficult to hide via command palette or keyboard shortcut.

The terminal is quite different than other views as many terminals can be opened and place in different areas of the IDE at once. In such a case, what would toggle terminal do?

**Comment by vince-fugnitto** [comment]
The same issue has been previously opened in the past and closed with a similar explanation https://github.com/eclipse-theia/theia/issues/2611

**Comment by akosyakov** [comment]
@ccssmnn Please use `Toggle Bottom Panel`. It will completely collapse the area. You can do it from the status bar as well:
<img width="1552" alt="Screen Shot 2020-01-14 at 14 31 30" src="https://user-images.githubusercontent.com/3082655/72692549-581ced00-3b4e-11ea-9823-e27f91193d44.png">

There can not be toggle terminal command, since there is no a single view or panel for it.

**Comment by akosyakov** [comment]
Although, we can add `Toggle Bottom Panel` to `View` menu to make it easy to discover.

**Comment by JesterOrNot** [comment]
We should add a good first issue label to this

**Comment by akosyakov** [comment]
Turned out it is already there:
<img width="1552" alt="Screen Shot 2020-01-20 at 08 00 32" src="https://user-images.githubusercontent.com/3082655/72695612-f7e07800-3b5a-11ea-8121-afe12524eb05.png">
