### ISSUE TITLE
support scm/resourceFolder/context menu contribution

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6915]

**Comment by westbury** [comment]
It is not possible to support scm/resourceFolder/context unless there is a folder resource change UI element somewhere on which to put the context menu.  So this issue does require https://github.com/eclipse-theia/theia/pull/7505 .  As it happens, that PR does use scm/resourceFolder/context to get the menu for folders, so it does fix this issue.

However it would be nice to get https://open-vsx.org/api/vscode/git/1.39.1/file/vscode.git-1.39.1.vsix  working first.  That version, unlike  [vscode-git-1.3.0.1](https://github.com/che-incubator/vscode-git/releases/download/1.30.1/vscode-git-1.3.0.1.vsix), makes contributions to this location.  It would be nice to be able to test with this builtin version before closing this issue.

**Comment by akosyakov** [comment]
I will try to look at https://github.com/eclipse-theia/theia/pull/6921 next week. I've tested it against 1.39.1.

**Comment by westbury** [comment]
I've now been able to test with vscode.git-1.39.1.vsix.  The scm/resourceFolder/context menu items show correctly when switching Source Control view to tree mode and right-clicking on a folder.  I'm therefore closing this.
