### ISSUE TITLE
cannot clean terminal with keybindings anymore

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6916]
<img width="1552" alt="Screen Shot 2020-01-20 at 12 03 04" src="https://user-images.githubusercontent.com/3082655/72705417-35ee9380-3b7d-11ea-99fa-fc5e37086f7b.png">

Keybinding service waits for next chord. Caused by changes in this line: https://github.com/eclipse-theia/theia/commit/582ae9dd88a58f3053e9445199ee54e42179923f#diff-0291e1b92ff01c13c0dc1c98263ac426R631

cc @vinokurig

**Comment by akosyakov** [comment]
That's possibly critical if none of terminal keybinding are working anymore. I suggest we revert this file and someone else will need to look into support of emacs vscode extension without breaking terminals again.

**Comment by vinokurig** [comment]
I am working on it.

**Comment by akosyakov** [comment]
@vinokurig ok, do you have estimation when it can be fixed?

**Comment by vinokurig** [comment]
@akosyakov I am going to open a PR today

**Comment by akosyakov** [comment]
@vinokurig how are you going to fix it? I was thinking try to check whether there is at least one partial keybinding which is active, i.e. its context/when closure evaluates to true, instead of checking only for existence.

**Comment by vinokurig** [comment]
@akosyakov The PR is ready
