### ISSUE TITLE
what is amazonaws request for?

### ISSUE THREAD

**Issue by lxn179208** [eclipse-theia/theia#6917]
### Description
Some times, I found a tcp connection to amazonaws.com, can somebody tell me what is this?

node    429 root   32u     IPv4         2589619845      0t0        TCP xxxxx:port->ec2-54-186-65-123.us-west-2.compute.amazonaws.com:https (ESTABLISHED)

### Reproduction Steps
lsof -p {theia worker process id}

**OS and Theia version:**
linux  theia version is 0.14.0

```json
{
"private": true,
"dependencies": {
"@theia/callhierarchy": "latest",
"@theia/debug": "latest",
"@theia/extension-manager": "latest",
"@theia/file-search": "latest",
"@theia/git": "latest",
"@theia/json": "latest",
"@theia/keymaps": "latest",
"@theia/markers": "latest",
"@theia/merge-conflicts": "latest",
"@theia/messages": "latest",
"@theia/mini-browser": "latest",
"@theia/navigator": "latest",
"@theia/outline-view": "latest",
"@theia/plugin-ext": "latest",
"@theia/plugin-ext-vscode": "latest",
"@theia/preferences": "latest",
"@theia/preview": "latest",
"@theia/python": "latest",
"@theia/search-in-workspace": "latest",
"@theia/terminal": "latest",
"@theia/textmate-grammars": "latest",
"@theia/typescript": "latest",
"@theia/variable-resolver": "latest",
"agentx": "^1.10.7",
"commandx": "^1.5.4",
"debug": "^4.1.1",
"typescript": "latest"
},
"devDependencies": {
"@theia/cli": "latest"
},
"engines": {
"install-alinode": "4"
}
}
```

**Diagnostics:**

**Comment by akosyakov** [comment]
Hi @lxn179208 Could you elaborate which commands you run? in which environments? how do you track down this request?

**Comment by lxn179208** [comment]
Hi @akosyakov , 
First I type the startup commands "yarn theia start ./ --hostname=0.0.0.0 ", 
Second, I open the editor url with chrome and new a terminal
Third, in the terminal, I will find the amazonaws.com request sometimes.

**Comment by akosyakov** [comment]
@lexcorp16 probably a command which you run in terminal does it?

**Comment by lxn179208** [comment]
@akosyakov no, I did not exec any commands.

**Comment by vince-fugnitto** [comment]
@lxn179208 I'm thinking they are perhaps caused by the `agentx` and `commanderx` dependencies?
There are no requests made to amazonaws from the platform.
