### ISSUE TITLE
vscode_1.env.onDidChangeLogLevel is not a function

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6918]
[vscode git extension v1.39](https://github.com/theia-ide/vscode-builtin-extensions/releases/download/v1.39.1-prel/git-1.39.1-prel.vsix) does not start

**Comment by akosyakov** [comment]
@marcdumais-work could you help me to figure out from which vscode commit 1.39.1-prel is built? If i tag `release/1.39` it does not work.

**Comment by akosyakov** [comment]
I'm going to stub these apis. It does not seem that they are going to make it to vscode.d.ts: https://github.com/microsoft/vscode/issues/85992#issuecomment-566205811

**Comment by marcdumais-work** [comment]
> @marcdumais-work could you help me to figure out from which vscode commit 1.39.1-prel is built? If i tag `release/1.39` it does not work. I need to run this extension from sources to debug it, but it seems I'm using a wrong version.

Hi @akosyakov ,

The tag is `1.39.1`, commit `88f15d17dca836346e787762685a40bb5cce75a8`. In the [release commit](https://github.com/theia-ide/vscode-builtin-extensions/commit/89ddd51a1a064fed4f410b7fb7a59f0cc47608ea), I moved the vscode submodule to match that tag.
