### ISSUE TITLE
[ui/ux] The tree highlighting differs from VS Code

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#6919]
### Description
 

Theia uses different styles in the tree than VS Code. Something is odd with the `mark` style.

VS Code:
![Screen Shot 2020-01-20 at 09 36 53](https://user-images.githubusercontent.com/1405703/72711576-9247b800-3b69-11ea-901a-5bce70a559dd.jpg)

Theia Tree:
![Screen Shot 2020-01-20 at 09 40 06](https://user-images.githubusercontent.com/1405703/72711560-8bb94080-3b69-11ea-9334-52cbeb13aa22.jpg)

Theia File Dialog:
![Screen Shot 2020-01-20 at 09 37 03](https://user-images.githubusercontent.com/1405703/72711592-9b388980-3b69-11ea-8490-25844069ac56.jpg)

API:
https://github.com/eclipse-theia/theia/blob/fd2d384348348061eadaf67a3651b631cba288bc/packages/core/src/browser/widget-decoration.ts#L212-L214

CSS:
https://github.com/eclipse-theia/theia/blob/fd2d384348348061eadaf67a3651b631cba288bc/packages/core/src/browser/style/tree.css#L129-L131

TSX:
https://github.com/eclipse-theia/theia/blob/fd2d384348348061eadaf67a3651b631cba288bc/packages/core/src/browser/tree/tree-widget.tsx#L590

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by justinang1** [comment]
Going to take a look at this issue.
