### ISSUE TITLE
window.showQuickPick is never resolve if closed with esc

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6929]
It should resolve with undefined

**Comment by benoitf** [comment]
report is quite obvious but maybe you could reference existing VS Code extension that is reproducing the error ?

**Comment by akosyakov** [comment]
I got it with vscode-gitlens, it never unset context keys which should happen after `showQuickPick` exits: https://github.com/eamodio/vscode-gitlens/blob/30e1d290e8f337d56596a030ff097eeabdd98eb7/src/quickpicks/commitQuickPick.ts#L220-L241
