### ISSUE TITLE
task terminal is not reused

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6941]
It's reproducible with theia repo:
- start from sources
- from npm scripts view run `textmage-grammars` test
- run again when task is finished
- a new terminal is created

Also if you don't wait for termination but try to run again, click return in notificaiont then it fails alltogether with error notification.

Here you see 2 terminals for very same taks and an error notification:
<img width="1552" alt="Screen Shot 2020-01-22 at 11 35 05" src="https://user-images.githubusercontent.com/3082655/72870930-551b2b80-3d0b-11ea-9f6f-d7412d41b460.png">

cc @elaihau @RomanNikitenko

**Comment by vince-fugnitto** [comment]
I believe it is a known issue that terminals created from tasks cannot be re-used?
- https://github.com/eclipse-theia/theia/issues/5825
- https://github.com/eclipse-theia/theia/issues/5269#issuecomment-496800867

**Comment by akosyakov** [comment]
@vince-fugnitto I see i thought it was already addressed. :(
