### ISSUE TITLE
provide migration steps to builtins for Electron distributions

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6946]
See discussions started here: https://github.com/theia-ide/theia-apps/pull/287#issuecomment-577167107

**Comment by vince-fugnitto** [comment]
I created a new wiki page [Consuming Builtin and External VS Code Extensions](https://github.com/eclipse-theia/theia/wiki/Consuming-Builtin-and-External-VS-Code-Extensions) to describe how to consume builtin and external VS Code extensions. Anyone is free to update/enhance the documentation.

cc @marcdumais-work

**Comment by marcdumais-work** [comment]
Looks good enough to start, thanks @vince.
