### ISSUE TITLE
update theia docs to use built-ins instead of deprecated extensions

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#6947]
See https://github.com/eclipse-theia/theia/pull/6933#issuecomment-576992922

**Comment by vince-fugnitto** [comment]
I created the issue under `theia-website` since both the website and our docs in the main repo should be updated to properly reflect the new updates.

**Comment by marcdumais-work** [comment]
PR: https://github.com/theia-ide/theia-website/pull/89

**Comment by marcdumais-work** [comment]
> PR: [theia-ide/theia-website#89](https://github.com/theia-ide/theia-website/pull/89)

PR merged.
