### ISSUE TITLE
workbench.action.closeActiveEditor command doesn't close a WebviewWidget

### ISSUE THREAD

**Issue by tomer-epstein** [eclipse-theia/theia#6955]
### Description
workbench.action.closeActiveEditor command doesn't close a WebviewWidget

### Reproduction Steps
Open the  'Getting Started' (Help -> 'Getting Started')
execute workbench.action.closeActiveEditor command. 

**Diagnostics:** 
it seems that the reason is that WebviewWidget doesn't implement Navigatable interface.

**Comment by amiramw** [comment]
@tomer-epstein does it work in VS Code?

**Comment by tomer-epstein** [comment]
Yes.

**Comment by vince-fugnitto** [comment]
> Open the 'Getting Started' (Help -> 'Getting Started')

Are you referring to the `Getting Started` from Theia?

**Comment by tomer-epstein** [comment]
> > Open the 'Getting Started' (Help -> 'Getting Started')
> 
> Are you referring to the `Getting Started` from Theia?

Yes. it's an example for WebviewWidget.
another vscode extension wich opens WebviewWidget is https://github.com/SAP/yeoman-ui

**Comment by vince-fugnitto** [comment]
> > > Open the 'Getting Started' (Help -> 'Getting Started')
> > 
> > 
> > Are you referring to the `Getting Started` from Theia?
> 
> Yes. it's an example for WebviewWidget.
> another vscode extension wich opens WebviewWidget is https://github.com/SAP/yeoman-ui

@tomer-epstein 
I don't think our `Getting Started` is a WebviewWidget,  what makes you believe it is?
https://github.com/eclipse-theia/theia/blob/master/packages/getting-started/src/browser/getting-started-widget.tsx

**Comment by tomer-epstein** [comment]
debuging plugin-vscode-commands-contribution

![image](https://user-images.githubusercontent.com/57438361/72986666-650d3b00-3df1-11ea-92bb-62cf78cdeca6.png)

**Comment by akosyakov** [comment]
In VS Code there is a difference between editor and code editor. Editor is any widget opened in the editor area (main area in Theia). Code editor is Monaco-based widget. So yes, webview is an editor in VS Code sense and closeActiveEditor should close the webview as well. https://github.com/eclipse-theia/theia/blob/9fb6351621583f4a3e51954debbea9ed1e080168/packages/plugin-ext/src/main/browser/menus/menus-contribution-handler.ts#L45 is a function which can be checked whether a given widget is an editor in VS Code sense. We should rewrite all vscode editor commands using it.

**Comment by marechal-p** [comment]
PR was merged.
