### ISSUE TITLE
Theia does not start 

### ISSUE THREAD

**Issue by sinamoeini** [eclipse-theia/theia#6960]
### Reproduction Steps

followed the instruction [https://theia-ide.org/docs/composing_applications/](here). The server starts fine. But when the browser is opened it gets stuck. I have the exact same program that I installed on Jan 16 it works fine so it must be some recent update

**OS and Theia version:**
I ran the server on Mac OS and RHEL-7 and tested the program on Firefox for developer and safari.

**Diagnostics:** 

In the console I see the following:

<img width="641" alt="theia" src="https://user-images.githubusercontent.com/4393595/73035438-145c0900-3e16-11ea-9f46-f8cae4c10e47.png">

**Comment by akosyakov** [comment]
Hi, do you use latest or next version?

**Comment by sinamoeini** [comment]
This is  my package.json 

{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/debug-nodejs": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next",
    "@theia/php": "next",
    "@theia/debug": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}

Does that answer the question?

**Comment by sinamoeini** [comment]
It might be related to a dependency of theia. 
I attached the output of `yarn list --depth 0 ` 

One from the version that works and the one that doesn't 

[Archive.zip](https://github.com/eclipse-theia/theia/files/4106380/Archive.zip)

**Comment by akosyakov** [comment]
yes, it is next ) Next is nighlty build, the last one failed to publish all packages because of the npm registry instability. So you pull currently the mix of different versions of Theia which does not seem to be compatible. I've restarted the deployment job (https://travis-ci.com/eclipse-theia/theia/jobs/279125953) if it is successful then you will need to delete node_modules, yarn.lock and run yarn again. Alternatively use latest, it is the last stable release.

**Comment by sinamoeini** [comment]
Excellent! Thank you so much for all of your contributions. Theia project is amazing. Hopefully it will become more popular.

**Comment by akosyakov** [comment]
Ah, one package is missing access config and fail the build, I will create a PR.

**Comment by sinamoeini** [comment]
thanks

**Comment by akosyakov** [comment]
a fix is here: https://github.com/eclipse-theia/theia/pull/6962

**Comment by vince-fugnitto** [comment]
Closeable by #6962?

**Comment by akosyakov** [comment]
No, only when a build is successful, now it fails with another error, cannot install yarn, will restart again :(

**Comment by akosyakov** [comment]
should be alright now, if not please open a new issue
