### ISSUE TITLE
eslint: use vscode extension compatible with Theia

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#6975]
### Description

We switched from TSLint to ESLint, but we don't currently provide any kind of support for the latter within Theia applications. We should see at making the VS Code extension work.

### Reproduction Steps

Navigate Theia's code base and remove any `eslint-disable` comment to see that errors are not reported from a Theia application. It works on VS Code using the ESLint extension.

**OS and Theia version:** Ubuntu 16.04 - Theia 0.14

**Comment by akosyakov** [comment]
https://github.com/microsoft/vscode-eslint/commit/8586a674f681b017b096f1769fe585aa520c905c this commit is last compatible with Theia, it could be good to package it, publish to Github and add to theia plugins

**Comment by vince-fugnitto** [comment]
@kaiyue0329 @Anasshahidd21 

I published a [`.vsix`](https://github.com/theia-ide/vscode-eslint/releases/download/release%2F2.0.15/vscode-eslint-2.0.15.vsix) for us to consume.

We'd need to properly test to see if it provides the appropriate information.
One can follow how builtin plugins are added to the examples and add this entry as well.

**Comment by marechal-p** [comment]
@vince-fugnitto hmm, the plugin you distributed outputs the following:

> The language client requires VS Code version ^1.41.0 but received version 1.38.0

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto hmm, the plugin you distributed outputs the following:
> 
> > The language client requires VS Code version ^1.41.0 but received version 1.38.0

I noticed that when initially tried out the plugin following #6897 

> edit: It seems to work when I override the `VSCODE_API_VERSION` env var to `1.41.0` 🎉

Great, hopefully it's just a sanity check performed by plugins, I wonder when we should actually bump our version. I also wonder if we should look for a version that is compatible with ours at the moment. I would not want devs to have to pass the API version through the cli when starting the app.

https://github.com/eclipse-theia/theia/blob/1ca3ec37c079a6b316278cf292609653e57b8151/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts#L22

**Comment by akosyakov** [comment]
@marechal-p @vince-fugnitto bumping up VSCODE_API_VERSION is fine as well

**Comment by marechal-p** [comment]
It might be best to simply add a commit on our fork and update the plugin's package.json to declare using `^1.38.0` since it seems to work...

**Comment by akosyakov** [comment]
https://github.com/eclipse-theia/theia/pull/6924 bumps up vscode api version already

**Comment by akosyakov** [comment]
>  I think the API check is done on Theia's side, not the plugin.

api check is done by vscode-languageclient: https://github.com/microsoft/vscode-languageserver-node/blob/4c0963d6fdfd657044092c5d4db61a87b54471ef/client/src/main.ts#L195

**Comment by vince-fugnitto** [comment]
It's been bumped already :)
https://github.com/eclipse-theia/theia/pull/6924/files#diff-66cd2825aa616ad9a26b1f62e1b21e5bR22
