### ISSUE TITLE
[browser dialogs] XSS venerability in file dialog

### ISSUE THREAD

**Issue by caseyflynn-google** [eclipse-theia/theia#6976]
### Description

There is an XSS venerability in the Create File / Folder dialog.

### Reproduction Steps

1. Click File -> New File to open the New File dialog
2. In the text box enter <style onload=alert(0)>

The alert is triggered on the page.

![theia_file_dialog_xss](https://user-images.githubusercontent.com/23463108/73226439-e8e26280-4124-11ea-845e-07b81a58e90f.png)

**OS and Theia version:**
Linux
Theia 0.14.0

**Comment by akosyakov** [comment]
Resolved by https://github.com/eclipse-theia/theia/pull/6977
