### ISSUE TITLE
Possible contribution for a new preference editor

### ISSUE THREAD

**Issue by lucas-koehler** [eclipse-theia/theia#6985]
Hello Theia community,

would you be interested in a contribution for a tree-master-detail based preference editor?
The tree shows the preference categories on the left side. The detail renders the selected category's preferences on the right side.
Thus, the main difference to the current editor is that the preferences are edited via suitable controls
in the detail view instead of showing the raw JSON on the right side. The following screenshots shows a first, minimal demo implementation.

![image](https://user-images.githubusercontent.com/6959840/73271172-64edb080-41e0-11ea-9990-114abbd4da27.png)

![image](https://user-images.githubusercontent.com/6959840/73273328-1510e880-41e4-11ea-9341-4150e686ca45.png)

Are you interested in a contribution of such a preference editor?

**Comment by akosyakov** [comment]
It would be good to have the same UI as in VS Code.

**Comment by lucas-koehler** [comment]
Thanks for the fast feedback! Great that there is interest in such a preference editor.
We'll go ahead and prepare a draft PR for further discussion then.
I had a look at the code of VSCode's preference editor and it doesn't seem to be a component that can easily be reused.
However, we'll try to align the UI and make it compatible from a styling point of view.

**Comment by danieltomasku** [comment]
Hi @lucas-koehler , just wanted to mention that my team has developed a Preferences UI for Theia that has a very similar UI as VSCode. It includes fuzzy searching and the ability to jump to sections from the side navigation. We have been using it internally and find it very nice. We were planning on upstreaming after we received approval to do so internally. I wanted to see if you were interested in viewing that as a draft PR before you continue working on the feature separately? We could have that up by next Friday (February 7) or possibly sooner. It's up to you if you want to continue with your implementation, but I thought I would mention it as to avoid doing duplicate work :)

**Comment by akosyakov** [comment]
@danieltomasku wow, I would like to see a PR )

**Comment by lucas-koehler** [comment]
Hi @danieltomasku, thanks for letting me know. I indeed would like to see the draft PR as your implementation already sounds quite mature and avoiding duplicate work is always good :)

**Comment by danieltomasku** [comment]
@lucas-koehler @akosyakov  Sounds good. We'll work on cleaning it up internally, then we should be able to have a PR up by Friday.

**Comment by akosyakov** [comment]
@danieltomasku You can open it anyway and ask for the community help to clean up certain aspects.

**Comment by marcdumais-work** [comment]
@lucas-koehler @akosyakov  the PR, promised by @danieltomasku, has been created: https://github.com/eclipse-theia/theia/pull/7105 . Please have a look and give feedback.

**Comment by akosyakov** [comment]
resolved with https://github.com/eclipse-theia/theia/pull/7105
