### ISSUE TITLE
[firefox] incorrect display of workspace settings file icon

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#6990]
**Description**

The **workspace** `settings.json` file displayed in the tab when using the `preferences view` is incorrectly displayed (the file icon is too large) when using the application on **Firefox**.

<div align='center'>

<img width="536" alt="Screen Shot 2020-01-28 at 7 24 59 PM" src="https://user-images.githubusercontent.com/40359487/73317406-eacf2300-4203-11ea-92ab-c13b1262e9d1.png">

</div>

**Steps to Reproduce**
1. start the application on **Firefox** with a workspace (ex: theia)
2. open the `preferences widget`
3. notice the _workspace_ tab's icon is displayed too large

**Comment by elaihau** [comment]
i can also reproduce it in latest Chrome
