### ISSUE TITLE
workbench.action.closeEditorsInGroup doesn't close it self (the current Widget)

### ISSUE THREAD

**Issue by tomer-epstein** [eclipse-theia/theia#6997]
Description
workbench.action.closeEditorsInGroup command doesn't close it self (the current Widget)

Reproduction Steps
Open couple of files in agroup
execute workbench.action.closeEditorsInGroup command.
Can also be tested with this vscode ext -  https://github.com/tomer-epstein/vscode-close-editor.git 

Diagnostics:
plugin-vscode-commands-contribution.ts
 ({ owner }) => CodeEditorWidget.is(owner) && owner !== editor

**Comment by amiramw** [comment]
@tomer-epstein add your vscode that makes it easy to reproduce.
