### ISSUE TITLE
Prevent dragging bottom panel widgets to leftSideBar/ rightSideBar/ mainPanelTabBar

### ISSUE THREAD

**Issue by najaarv** [eclipse-theia/theia#7001]
I believe most of the IDEs out there don't allow moving widgets like terminal out of the bottom panel where it's supposed to be. But I could move around terminal widgets generated in the bottom panel anywhere within the layout which my users think is not ideal behavior. I understand theia team might have different opinion/ thought process to have enabled that. But in my product, I want to restrict widgets like **Problems, Terminal**, etc. to the _bottom panel only_. How can I do that? Code snippets/ files to modify mention appreciated. Thanks.

**Comment by akosyakov** [comment]
You will need to customize the application shell that it rejects widgets for certain areas as well as disable animation.

**Comment by vince-fugnitto** [comment]
Closing as the question has been opened for some time now without any follow-up and is likely resolved.
