### ISSUE TITLE
Cannot build the `api-samples`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7002]
### Description
 

I cannot build and run the `api-samples`. I did

```
% pwd && yarn --cwd ./examples/api-samples/ build
/Users/akos.kitta/git/theia
yarn run v1.21.1
$ theiaext build
/bin/sh: theiaext: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

See: https://github.com/eclipse-theia/theia/commit/1ca3ec37c079a6b316278cf292609653e57b8151#commitcomment-37020190

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by kittaakos** [comment]
Also, the NPM `prepare` script is missing, hence nothing will happen with the `api-sample` if I run `yarn` from the root. Did I understand the changes correctly?

**Comment by kittaakos** [comment]
Works now, I must have missed a build step 😕

**Comment by marechal-p** [comment]
Since `theiaext` is an npm bin contributed by `dev-packages/ext-scripts` you have to install that first.
