### ISSUE TITLE
[shell] Widget activation causes a resource leak

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7008]
### Description
 

In a downstream project, I have updated to recent Theia and it started to fail with a resource leak. I added an example to reproduce it. Note: `yourViewContribution.openView({ activate: true })` causes the leak, `yourViewContribution..openView({ reveal: true })` does not. I think the bug is here

https://github.com/eclipse-theia/theia/blob/914e9e2ec39e55a61981eb8150198d6524a85827/packages/core/src/browser/shell/application-shell.ts#L968

And this is the actual problem, the condition will be `false`, unless I manually activate the `Output` view which does not make sense.

https://github.com/eclipse-theia/theia/blob/914e9e2ec39e55a61981eb8150198d6524a85827/packages/core/src/browser/shell/application-shell.ts#L981

**Workaround**:
Use `yourViewContribution..openView({ reveal: true })`.

### Reproduction Steps

Start the example app from here: https://github.com/eclipse-theia/theia/pull/7007

CC: @akosyakov 

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
> And this is the actual problem, the condition will be false, unless I manually activate the Output view which does not make sense.

Not sure what you mean, If someone passes activate as true then a widget should become focused, otherwise that’s a bug. A user don’t have to focus anything manually.

**Comment by akosyakov** [comment]
A leak is a follow-up of a bogus output implementation. I don't think anything in the core, if someone implemented activation bogusly they should not expect it to work. In this case seeing multiple warnings that shell is trying to find active widget is good thing, since it tells a developer something is wrong.
