### ISSUE TITLE
Highlight is misspelled

### ISSUE THREAD

**Issue by justinang1** [eclipse-theia/theia#7026]
**Description**
 
Highlight is misspelled in spec.ts, tree-widget.tsx and widget-decoration.ts. 

`highligh` > `highlight`

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/tree/tree-decorator.spec.ts#L155-L159

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/tree/tree-widget.tsx#L589

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/widget-decoration.ts#L254

https://github.com/eclipse-theia/theia/blob/8dcd4319b36f3acb9aa238b39cca10511a62251c/packages/core/src/browser/widget-decoration.ts#L273

**Comment by garethwhittaker** [comment]
I'm happy to pick this up as a way of familiarising myself with the Theia contribution process.

**Comment by justinang1** [comment]
Thank you for looking into this and fixing it @garethwhittaker !
