### ISSUE TITLE
[ui/ux] Discard the active modal dialog with `Esc`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7030]
### Description
 

I want to discard the current modal dialog, such as `Open Workspace`, with `Esc`.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by overhead525** [comment]
I tried to reproduce this and it seems that you can already discard modals with `Esc`

1. Click `File`
2. Click `Open Workspace...`
3. Press `Esc`

Result: Modal Disappears Successfully

If I'm wrong, I'd be happy to implement the solution, but I currently don't see a problem.

**Comment by kittaakos** [comment]
> If I'm wrong

No, I have quickly verified it again with 86704a9ca and it is OK. I must have been blind. Thanks for looking into it, @overhead525.
