### ISSUE TITLE
[tree-view] hiding a tree view is re-opened on reload

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7037]
**Description**

There is currently a bug with hiding `tree-views` (ex: `npm scripts`) where it is re-opened on reload despite a user hiding it.

**Steps to Reproduce**
1. start the application using `theia` as a workspace
2. verify that the `tree-view` 'npm scripts' is opened
3. right click 'npm scripts' header and un-select it or 'hide'
4. the `tree-view` should be properly hidden
5. reload the frontent (refresh the browser)
6. notice how the 'npm scripts' tree-view is re-opened

<div align='center'>

![a](https://user-images.githubusercontent.com/40359487/73538241-7c9f8180-43f8-11ea-8d75-ac34ee20bafc.gif)

</div>

**Comment by vince-fugnitto** [comment]
Corresponding related issue in vscode: https://github.com/microsoft/vscode/issues/35462

**Comment by vince-fugnitto** [comment]
@akosyakov I looked at the pull-request https://github.com/eclipse-theia/theia/pull/5855 and while explicitly hiding a view should work, it does not work in this case anymore.

**Comment by akosyakov** [comment]
I will need to debug it. If it is a regression then we should add a new api test for it to catch in the future. I have not thought yet how to test page reload and reconnections.

**Comment by vince-fugnitto** [comment]
I can no longer reproduce the issue, likely thanks to https://github.com/eclipse-theia/theia/pull/9156.

**Comment by vince-fugnitto** [comment]
I believe this issue has not been resolved (it was recently reproduced).
