### ISSUE TITLE
[Electron] Plugins icons not showed on Electron

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7040]
### Description
On Electron, some icons are not shown when the plugins is installed.
May be related to https://github.com/eclipse-theia/theia/issues/6834

### Reproduction Steps
To test, install gitlens plugins and select View-> Gitlens
You will see the views, but no icon on the sidebar. (Look on the left side panel)
Tested with electron on Ubuntu 16.04 and plugin:gitlens-10.2.0.vsix
Note: If you run the same GitLens plugins on a browser (Chrome), the icon is displayed on the sidebar.

**OS and Theia version:**
Theia: latest (0.15.0)
OS: Ubuntu 16.04

**Diagnostics:** 
Electron:
![GitLensElectron](https://user-images.githubusercontent.com/419051/73546607-8383bf80-440b-11ea-8ed2-a2a948e585ff.png)

Browser:
![GitLensBrowser](https://user-images.githubusercontent.com/419051/73546305-02c4c380-440b-11ea-9a6d-a0b049aa417c.png)

**Comment by Johannes-B-stock** [comment]
It looks like we might have the same issue. In the DevTool it shows that instead of looking for the icons in the plugins folder, the extensionContext path leads to a asar-packed path which cant be resolved. 
The path looks something like app.asar/lib/hostedPlugin/plugin-name/*

**Comment by vince-fugnitto** [comment]
@akosyakov @kittaakos do you happen to have an idea as to why the assets are not properly displayed in electron? I suspect it's the same reason that #6834 does not work properly.
I thought it might have to do with how we webpack the resources.

**Comment by akosyakov** [comment]
@vince-fugnitto no, one has to debug why such paths are generated

**Comment by Johannes-B-stock** [comment]
We found a workaround. Apparently the pluginUrl needs to be an absolute path when running in Electron and a relative when running in the browser. 
We fixed it by changing the function `toPluginUrl()` in plugin-ext/common/plugin-protocol.ts to return the absolute path `"file:///" + path.join(pck.packagePath, relativePath).replace(/\\/g, "/");` when the extension is running in Electron.

**Comment by vince-fugnitto** [comment]
> We found a workaround. Apparently the pluginUrl needs to be an absolute path when running in Electron and a relative when running in the browser.
> We fixed it by changing the function `toPluginUrl()` in plugin-ext/common/plugin-protocol.ts to return the absolute path `"file:///" + path.join(pck.packagePath, relativePath).replace(/\\/g, "/");` when the extension is running in Electron.

Would you like to propose your changes in a pull-request? We can add a check to determine if the target is Electron and compute the path accordingly.

**Comment by Johannes-B-stock** [comment]
Will take care

**Comment by vince-fugnitto** [comment]
Closed by #7583
