### ISSUE TITLE
Where can I find built Theia Desktop for Windows?

### ISSUE THREAD

**Issue by chrisjj** [eclipse-theia/theia#7048]
(Anyone able to label this as a question, please do.)

Please?

https://github.com/theia-ide/theia-apps says

```
This repository contains example Theia applications based on published Theia extension packages.
...
Theia Desktop
```

but no info is given for Theia Desktop.

**Comment by vince-fugnitto** [comment]
Hi @chrisjj, the desktop version uses `electron` and an example application can be found here:

https://github.com/theia-ide/theia-apps/tree/master/theia-electron

**Comment by chrisjj** [comment]
Thanks, but there's no built .exe there AFAICS.

**Comment by vince-fugnitto** [comment]
> Thanks, but there's no built .exe there AFAICS.

You must follow the steps in the `readme` to build and package the application (the installer for the application). There is no build present for any of the OS (windows, linux distro, mac).

**Comment by vince-fugnitto** [comment]
There is a recommendation to provide such vanilla theia electron applications so they are easier to consume, but the examples in `theia-apps` are simply examples. https://github.com/theia-ide/theia-apps/issues/280

If one wants to create an electron theia-based IDE, they can follow the example provided in that same repo. For instance, we also have a `C/C++` IDE example as well: https://github.com/theia-ide/theia-apps/tree/master/theia-cpp-electron

**Comment by chrisjj** [comment]
> You must follow the steps in the readme to build and package the application

I would do that if I was intending to build it.

> There is no build present for any of the OS (windows, linux distro, mac).

Ah. Thanks.

**Comment by vince-fugnitto** [comment]
> > You must follow the steps in the readme to build and package the application
> 
> I would do that if I was intending to build it.

It is an example of how one can prepare and package their own desktop theia-based IDE.
For this example, you will need to build and package it following the steps in the `readme`.

**Comment by chrisjj** [comment]
> It is an example of how one can prepare and package their own desktop theia-based IDE.

Indeed. Whereas the request was for something else.

**Comment by vince-fugnitto** [comment]
> > It is an example of how one can prepare and package their own desktop theia-based IDE.
> 
> Indeed. Whereas the request was for something else.

You mentioned `theia-apps` initially so I referenced the desktop example present in the repo. One must remember that Theia is a framework to build IDE-like applications. What was your specific request?

**Comment by chrisjj** [comment]
Sorry if my request was unclear. My"Where can I find built Theia Desktop for Windows" was asking for built distributions. not the sources. 

> One must remember that Theia is a framework to build IDE-like applications.

I did remember thanks. That's why I was on the applications page. It ays "Theia applications - docker images and desktop distributions", but has no applications' desktop distributions AFAICT.

**Comment by vince-fugnitto** [comment]
> Sorry if my request was unclear. My"Where can I find built Theia Desktop for Windows" was asking for built distributions. not the sources.
> 
> > One must remember that Theia is a framework to build IDE-like applications.
> 
> I did remember thanks. That's why I was on the applications page. It ays "Theia applications - docker images and desktop distributions", but has no applications' desktop distributions AFAICT.

If you are in fact looking for a desktop distribution and do not want to create our own or build and use the example, then you can look for others who have done so who have used Theia to build their own custom IDEs.

**Comment by vince-fugnitto** [comment]
If the following does not satisfy your request, please note that there has been past discussion on potentially providing users with a desktop installer for vanilla theia (basically the `example-electron` provided in this repository) https://github.com/eclipse-theia/theia/issues/5481

**Comment by chrisjj** [comment]
> If the following does not satisfy your request,

There was nothing following.

> please note that there has been past discussion on potentially providing users with a desktop installer for vanilla theia (basically the example-electron provided in this repository) #5481

Thanks. No progress there for the last three months, I see.

**Comment by vince-fugnitto** [comment]
> Thanks. No progress there for the last three months, I see.

The main contributors have been busy with other priorities (ex: vscode extension support), but please feel free to open a pull-request :)

**Comment by vince-fugnitto** [comment]
Closing in favor of tracking the issue at #5481
