### ISSUE TITLE
How can I improve the legibility of the Keyboard Shortcuts (sic) list?

### ISSUE THREAD

**Issue by chrisjj** [eclipse-theia/theia#7049]
(Anyone who knows how to label this "question", please do. The necessary checkbox is missing here.)

For me, the text is too small to read comfortably e.g. lower case characters only 4 pixels tall.

![image](https://user-images.githubusercontent.com/6157073/73596169-e5315000-4517-11ea-8df1-ff10a67ce709.png)

**Comment by chrisjj** [comment]
Oops. Github shrunk the image. Click it to see in correct size and legibility.

**Comment by vince-fugnitto** [comment]
> For me, the text is too small to read comfortably e.g. lower case characters only 4 pixels tall.

You can either do the following:
- zoom in/out the page (this will zoom other contents as well) provided you are using the browser target or use the `zoom in` electron command
- extend the base widget from the `@theia/keymaps` extension to be able to customize the layout to your liking.

**Comment by chrisjj** [comment]
Thanks. I'll report this issue.
