### ISSUE TITLE
"Keyboard shortcuts" (sic) text is too small

### ISSUE THREAD

**Issue by chrisjj** [eclipse-theia/theia#7051]
E.g. on the Browser Example in latest Google Chrome, some of the characters are only 4 pixels tall:

https://user-images.githubusercontent.com/6157073/73596169-e5315000-4517-11ea-8df1-ff10a67ce709.png
![image](https://user-images.githubusercontent.com/6157073/73616166-ef327c00-4607-11ea-9ea7-fb2156f275f0.png)

The legibility is so poor and the small size so unnecessary that I assume this is a bug.

**Comment by vince-fugnitto** [comment]
Closed by #7060.
