### ISSUE TITLE
[preferences] The preferences widget does not store/restore its layout between sessions

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7057]
### Description
 
Each time I open the preferences widget, it has the same default layout.

### Reproduction Steps

 1. Open the preferences widget.
 2. Grab the vertical split between the tree view and the editor, adjust it.
 3. Close the preferences widget.
 4. Open the preferences widget. The preferences widget uses the default layout, instead of the one I have configured in _step 2_. It would be great if the widget could preserve its layout.

![screencast 2020-02-03 17-29-14](https://user-images.githubusercontent.com/1405703/73671253-e1820280-46aa-11ea-821d-880bad8df153.gif)

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
I will have a look at it as a part of rewriting preference providers with text models.

**Comment by colin-grant-work** [comment]
@kittaakos, is this issue still relevant after the switch to the new preferences UI?

**Comment by vince-fugnitto** [comment]
I believe it is no longer relevant :+1:
