### ISSUE TITLE
[preferences] Adding a default preference value messes up the formatting in the JSON file

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7058]
### Description
 

Adding a default value from the tree viewer messes up the formatting in the JSON editor.
See the screencast.

![screencast 2020-02-03 17-38-51](https://user-images.githubusercontent.com/1405703/73671978-5bff5200-46ac-11ea-87e3-b449f0b17fd4.gif)

### Reproduction Steps

Add a default preference value.

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
I thought it was fixed as part of https://github.com/eclipse-theia/theia/pull/6736 :(

**Comment by akosyakov** [comment]
Preferences engine and UI were rewritten since then, not sure that it is a case anymore.

**Comment by vince-fugnitto** [comment]
The change is no longer applicable with the updated preferences UI.
