### ISSUE TITLE
ci: build failure on windows during `@theia/git` unit test

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7064]
**Description**

There is a recent Windows CI failure for one of the unit tests present in the `@theia/git` extension.

https://github.com/eclipse-theia/theia/blob/cc0da4e69f8141122496c119bb72f4df46584e76/packages/git/src/node/dugite-git.spec.ts#L76-L92

**Examples:**
- https://travis-ci.com/eclipse-theia/theia/jobs/283368405#L7439-L7457
- https://travis-ci.com/eclipse-theia/theia/jobs/283176162#L6180-L6198
- https://travis-ci.com/eclipse-theia/theia/jobs/283159823#L4692-L4707
- https://travis-ci.com/eclipse-theia/theia/jobs/283264445#L4704-L4721

**Comment by vince-fugnitto** [comment]
The tests seem to pass locally on a Windows machine, not sure as to why the tests are failing suddenly at the moment.

**Comment by kittaakos** [comment]
Related? https://github.com/eclipse-theia/theia/issues/933

**Comment by vince-fugnitto** [comment]
> Related? #933

Yes, it looks like it is possibly related to #933
