### ISSUE TITLE
showTextDocument is not compatible to vscode and assumes non zero-based range

### ISSUE THREAD

**Issue by veredcon** [eclipse-theia/theia#7065]
### Description
showTextDocument is not compatible to vscode and assumes non zero-based range

### Reproduction Steps
See: https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/main/browser/documents-main.ts#L225
it converts to zero-based although TextDocumentShowOptions has selection with type Range with zero-based positions.
it is not compatible with vscode.

See the options received is already zero-based and should be kept like that.
![image](https://user-images.githubusercontent.com/9718939/73747062-4139e580-475f-11ea-9696-9afe591491e3.png)

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
Yes, it looks like it should be +1 instead, since we use 1-based positions internally.

**Comment by akosyakov** [comment]
@veredcon PRs are welcomed! Feel free to send a PR, please check our contribution docs, there are certain criterias.

**Comment by justinang1** [comment]
I see that type Range should be have startLineNumber and startColumn > 1, so should the range definition underneath just be:
                start: { line: selection.startLineNumber - 1, character: selection.startColumn + 1},
                end: { line: selection.endLineNumber - 1, character: selection.endColumn - 1 }
instead? 

Also not too sure about how to debug/verify this, I see it's called in plugin-vscode-commands-contribution so would I need to define a command to test it?

**Comment by akosyakov** [comment]
@justinang1 You will need to create a VS Code extension fist reproducing the issue reliably. After that you can try to fix it.
