### ISSUE TITLE
Syntax highlighting fails to process an esnext feature

### ISSUE THREAD

**Issue by RDIL** [eclipse-theia/theia#7066]
Failing to process https://www.npmjs.com/package/@babel/plugin-proposal-nullish-coalescing-operator

It thinks the second `?` is a syntax error

**Comment by marechal-p** [comment]
What does "processing" mean here?

**Comment by RDIL** [comment]
Syntax highlighting, sorry for not clarifying.

**Comment by RDIL** [comment]
You can reproduce by trying to paste ```js
let config = {}

let mystring = config.somestringvalue ?? "default"
```

**Comment by vince-fugnitto** [comment]
The [**nulish coalescing operators**](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing) (`??`) are supported as a of `3.7.0`.

One must install 3.7 and configure it as the default typescript version when using the application.
At the moment `3.6.3` is used:

![image](https://user-images.githubusercontent.com/40359487/73755863-b04e1480-4734-11ea-9998-e48bc301896b.png)

**Comment by RDIL** [comment]
How would I change it?

**Comment by akosyakov** [comment]
@RDIL You can configure typescript version in your package.json and then select to use it instead of bundled one.

**Comment by RDIL** [comment]
Okay, thanks!
