### ISSUE TITLE
registry: register 'open-vsx.org' and host a marketplace

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7072]
**Description**

The issue tracks the feature required for **Theia v1.0.0**, which is mainly to:
- [x] register `open-vsx.org`
- [x] host a markeplace

The issue should be closed **manually** since it is a feature which is not part of the repo per se.

**Comment by jankeromnes** [comment]
Update: `open-vsx.org` was registered by TypeFox. I've updated the issue description accordingly (added checkboxes; checked the relevant one).

**Comment by akosyakov** [comment]
Is it done?

**Comment by jankeromnes** [comment]
> Is it done?

I think it is, as demonstrated by visiting https://open-vsx.org/
