### ISSUE TITLE
[webview] because it violates the following Content Security Policy directive: "script-src vscode-resource: 'nonce-JfIzlyXyDil0jxipMkkmeQ6CwO4wrl3B'".

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#7083]
### Description

```
Refused to load the script 'https://ide.miaowoo.cc/webview/theia-resource/file/tmp/vscode-unpacked/mhutchie_git_graph.vsix/extension/media/out.min.js' because it violates the following Content Security Policy directive: "script-src vscode-resource: 'nonce-JfIzlyXyDil0jxipMkkmeQ6CwO4wrl3B'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
``` 

### Reproduction Steps

- install plugin `https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph`
- open git view

**OS and Theia version:**
Windows 10
Chrome 79.0.3945.117
Theia 0.16.0-next.b74b53ad

**Diagnostics:** 

```
Refused to load the script 'https://ide.miaowoo.cc/webview/theia-resource/file/tmp/vscode-unpacked/mhutchie_git_graph.vsix/extension/media/out.min.js' because it violates the following Content Security Policy directive: "script-src vscode-resource: 'nonce-JfIzlyXyDil0jxipMkkmeQ6CwO4wrl3B'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

(anonymous) @ main.js:458
```

**Comment by vince-fugnitto** [comment]
@502647092 I believe you must set up secure webviews:
Taken from the changelog:
> [plugin] re-implemented webviews to align with VS Code browser implementation #6465
Security: vscode.previewHTML is removed, see https://code.visualstudio.com/updates/v1_33#_removing-the-vscodepreviewhtml-command
Security: Before all webviews were deployed on the same origin allowing them to break out and manipulate shared data as cookies, local storage or even start service workers for the main window as well as for each other. Now each webview will be deployed on own origin by default.
Webview origin pattern can be configured with THEIA_WEBVIEW_EXTERNAL_ENDPOINT env variable. The default value is {{uuid}}.webview.{{hostname}}. Here {{uuid}} and {{hostname}} are placeholders which get replaced at runtime with proper webview uuid and hostname correspondingly.
To switch to un-secure mode as before configure THEIA_WEBVIEW_EXTERNAL_ENDPOINT with {{hostname}} as a value. You can also drop {{uuid}}. prefix, in this case, webviews still will be able to access each other but not the main window.

Others have asked similar questions in the past, please see:
- https://spectrum.chat/theia/dev/any-breaking-changes-made-recently-to-webview~e5bd31a3-eee7-4288-b092-cf7407468780

**Comment by vince-fugnitto** [comment]
Also, I believe it is a duplicate of https://github.com/eclipse-theia/theia/issues/6749

**Comment by vince-fugnitto** [comment]
Closing since it is a duplicate of #6749, if it is not the case feel free to re-open the issue :)
As always, thank you for reporting problems!

**Comment by 502647092** [comment]
this problem is at Chrome not Eege
I can use webview at theia
![image](https://user-images.githubusercontent.com/10203793/73860488-9583b900-4876-11ea-8d4e-24583493c56f.png)
but can't use this plugin
![image](https://user-images.githubusercontent.com/10203793/73860529-a6342f00-4876-11ea-8aaa-e257f12ae516.png)
![image](https://user-images.githubusercontent.com/10203793/73860573-b2b88780-4876-11ea-8d35-c18bc38dc558.png)

**Comment by vince-fugnitto** [comment]
> this problem is at Chrome not Edge
> I can use webview at theia
> ![image](https://user-images.githubusercontent.com/10203793/73860488-9583b900-4876-11ea-8d4e-24583493c56f.png)
> but can't use this plugin
> ![image](https://user-images.githubusercontent.com/10203793/73860529-a6342f00-4876-11ea-8aaa-e257f12ae516.png)
> ![image](https://user-images.githubusercontent.com/10203793/73860573-b2b88780-4876-11ea-8d35-c18bc38dc558.png)

Please see discussions about using secure webviews: https://code.visualstudio.com/api/extension-guides/webview#content-security-policy @akosyakov perhaps you have further information?

**Comment by akosyakov** [comment]
It could be that some vscode extension has not be rewritten to work remotely. Please file a new issue please that we don't continue discussion on the closed issue.
