### ISSUE TITLE
Plugin Host swallows `PREFIX_THEIA_SUFFIX` Env Vars

### ISSUE THREAD

**Issue by AlexTugarev** [eclipse-theia/theia#7084]
If it's not doing any harm I propose to change the regex for filtering of Env Var to be passed on to the plugin host to mach for `^THEIA_` instead fo `THEIA_`, cf. 

https://github.com/eclipse-theia/theia/blob/a0e1fd2c39d3d0b97b7eb2c71b14096609d0c230/packages/core/src/node/messaging/ipc-protocol.ts#L48

The use case is the debug console where we miss some of the Env Vars.

**Comment by AlexTugarev** [comment]
@akosyakov and @tolusha, what do you think about this?

**Comment by benoitf** [comment]
I think it was the original intent/idea
