### ISSUE TITLE
multiline InputBox prompts

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#7090]
### Description
InputBox prompts can only be one line in length, then they get cut off with an ellipse. Multiline prompts are supported in VS Code and should be in Theia, too.

In Theia:
![image](https://user-images.githubusercontent.com/8888438/73873633-ef0cc900-481f-11ea-99b1-4dc593a4011b.png)

In VS Code:
![image](https://user-images.githubusercontent.com/8888438/73873644-f338e680-481f-11ea-8e7a-64404104f5d7.png)

### Reproduction Steps
create/show an InputBox with a long prompt.

**OS and Theia version:** Chrome, 0.11

**Comment by vince-fugnitto** [comment]
@tetchel thank you for the issue, is it something you'd like to work on? :)

**Comment by nisarhassan12** [comment]
I would like to give it a try :slightly_smiling_face:

**Comment by vince-fugnitto** [comment]
I believe this has been fixed, likely with newer versions of monaco:

![image](https://user-images.githubusercontent.com/40359487/213790305-e4f3ba36-4e56-4775-9e78-7f3ed7745c90.png)
