### ISSUE TITLE
Failed to start Java language server: Message could not be parsed

### ISSUE THREAD

**Issue by tsiyona** [eclipse-theia/theia#7092]
### Description

Hi, I am trying to add java language server extension to Theia version 0.11.0
Yet, it seems that the language server is not started/connected-to properly.
It looks like Theia is not recognizing the used language.

Can anyone help please?

### Reproduction Steps

I added in theia/examples/browser/package.json an entry for the Java lang server:
 "dependencies": {
 ...
 "@theia/java": "^0.11.0"
}, ...

and re-built.

When I restart Theia, I get the following error:
Failed to start Java language server: Message could not be parsed.
See also attached image.

**OS and Theia version:**
Linux 

**Diagnostics:** 

![jls](https://user-images.githubusercontent.com/9335329/73926373-3191dc80-48d8-11ea-83db-dc60545517de.gif)

**Comment by akosyakov** [comment]
Please use vscode java extension, Theia extension is deprecated and will be removed next months.

**Comment by tsiyona** [comment]
redhat.java ?

**Comment by akosyakov** [comment]
@tsiyona yes, look at root package how plugins can be installed

**Comment by akosyakov** [comment]
Also this image can help: https://github.com/theia-ide/theia-apps/tree/master/theia-java-docker

**Comment by tsiyona** [comment]
Do you mean I should add to my top-most package.json the following (after "dependencies"):

  "theiaPluginsDir": "plugins",
  "theiaPlugins": {
    "vscode-java-redhat": "https://github.com/redhat-developer/vscode-java/releases/download/v0.54.2/redhat.java-0.54.2.vsix"
  },

**Comment by vince-fugnitto** [comment]
@tsiyona have you called the script `download:plugins`?

For example:
https://github.com/eclipse-theia/theia/blob/5034fbe0e64959722027df517f42ce5d443d0f9f/package.json#L45

**Comment by tsiyona** [comment]
For now, I downloaded an older version of redhat.java and put it manually undet the 'plugins' folder, and it works.

**Comment by vince-fugnitto** [comment]
The issue is no longer valid as `@theia/java` has been deprecated for some time now: https://github.com/eclipse-theia/theia/pull/6933.

<img width="1002" alt="Screen Shot 2020-10-27 at 6 23 12 PM" src="https://user-images.githubusercontent.com/40359487/97368527-879d1a80-1881-11eb-846a-1d58bc5cf0c7.png">
