### ISSUE TITLE
No syntax highlights for any language

### ISSUE THREAD

**Issue by DoroNahari** [eclipse-theia/theia#7094]
### Description
 
No syntax highlights for any language.

### Reproduction Steps

Create any code file and write some code. no syntax highlights for it.

I run Theia localhost. on Gitpod it is working. I think this is since https://github.com/eclipse-theia/theia/pull/6883
**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@DoroNahari can you please provide additional information, I've tested against `master` d54c2f0
and it works correctly for both the `browser` and `electron` example applications.

<img width="1155" alt="Screen Shot 2020-02-06 at 11 23 12 AM" src="https://user-images.githubusercontent.com/40359487/73956707-559eef00-48d3-11ea-9e03-567220fcd007.png">
<img width="1153" alt="Screen Shot 2020-02-06 at 11 23 52 AM" src="https://user-images.githubusercontent.com/40359487/73956717-58014900-48d3-11ea-8133-397d9645d330.png">


Are you running the examples from this repo?
