### ISSUE TITLE
Undo can fail to restore previous text

### ISSUE THREAD

**Issue by chrisjj** [eclipse-theia/theia#7099]
On Windows 7.

1 In a new file type `int bob`
2 Press Ctrl+Shift+LeftArrow, selecting `bob`
3 Type `jim`
4 Press Ctrl+Z to Undo

Expected: `int bob`
Observed: `int`

Workaround: at 2, instead press Press Shift+LeftArrow thrice.

[Same in VS Code](https://github.com/microsoft/vscode/issues/90168), FWIW.

Note: github's manky rendering has extended the code background region looking almost as if a space before jim was included e.g. on Chrome:

![image](https://user-images.githubusercontent.com/6157073/74779596-b811cb00-5295-11ea-9b50-24d7c8933d8d.png)

There is actually none:

![image](https://user-images.githubusercontent.com/6157073/74779554-a7615500-5295-11ea-9782-d1324862c26f.png)

**Comment by vince-fugnitto** [comment]
@chrisjj are you able to reproduce the issue on the [monaco-playground](https://microsoft.github.io/monaco-editor/playground.html)? If so, the issue is caused by the [monaco-editor](https://github.com/microsoft/monaco-editor) and an issue should be opened there (vscode created and uses the monaco editor as well).

**Comment by chrisjj** [comment]
> Are you able to reproduce the issue on the monaco-playground?

Yes.

> If so, the issue is caused by the monaco-editor and an issue should be opened there

Meaning this issue should not be reported here?

**Comment by vince-fugnitto** [comment]
> > If so, the issue is caused by the monaco-editor and an issue should be opened there
> 
> Meaning this issue should not be reported here?

Correct, there's nothing that I know of to resolve the issue on our end (since it is the behavior originates from the `monaco-editor`). I believe the fix should exist in the upstream repo so that others can benefit from the same change including VS Code.

**Comment by chrisjj** [comment]
> Correct

That requires a user experiencing an issue to determine what part of Theia's code was the cause, before reporting, right?

**Comment by vince-fugnitto** [comment]
> > Correct
> 
> That requires a user experiencing an issue to determine what part of Theia's code was the cause, before reporting, right?

I always welcome reports from devs and users :) After some investigation, we determined the root cause for the issue was and now best we can address it. At this time, I believe an issue should be opened on the [monaco-editor](https://github.com/microsoft/monaco-editor) repo so they are aware of the improvement and downstream projects such as ours and VS Code can benefit from it.

**Comment by chrisjj** [comment]
>>>> Meaning this issue should not be reported here?
>>> Correct
> I always welcome reports from devs and users :)

Yet this issue should not be reported here??

**Comment by vince-fugnitto** [comment]
> > I always welcome reports from devs and users :)
> 
> Yet this issue should not be reported here??

It is fine that you initially opened the issue here, but after further investigation it looks like it is better suited at `monaco-editor` since it is an improvement to be made on their end. Opening an issue in `monaco-editor` so they are aware of the problem would be the best course of action.

**Comment by chrisjj** [comment]
OK, so I take it "Meaning this issue should not be reported here?" is answered Incorrect. Thanks.

**Comment by vince-fugnitto** [comment]
> OK, so I take it "Meaning this issue should not be reported here?" is answered Incorrect. Thanks.

No problem, I must have misinterpreted the question to be "this issue should not be fixed here?".

**Comment by vince-fugnitto** [comment]
I manually `hid` the discussions so we can keep the issue on topic and focused.
Thank you for reporting the improvement @chrisjj, the next step as mentioned is to track it through an issue in `monaco-editor`.

**Comment by chrisjj** [comment]
> the next step as mentioned is to track it through an issue in monaco-editor.

If that is how a Theia dev chooses to address this, fine.

**Comment by vince-fugnitto** [comment]
> > the next step as mentioned is to track it through an issue in monaco-editor.
> 
> If that is how a Theia dev chooses to address this, fine.

Not sure what you meant by that, but I figured since you opened both an issue here and in VS Code you’d like to be the one to open it in the upstream repo of `monaco-editor`.

**Comment by chrisjj** [comment]
No, I wouldn't. I'm not  a user of monaco-edit and have no interest in following internal #includes.

**Comment by vince-fugnitto** [comment]
> No, I wouldn't. I'm not a user of monaco-edit and have no interest in following internal #includes.

Suit yourself. 
It looks like your original [issue](https://github.com/microsoft/vscode/issues/90168) is sufficient to track the issue according to the [issue template](https://github.com/microsoft/monaco-editor/blame/master/.github/ISSUE_TEMPLATE/bug_report.md#L10) in `monaco-editor`.

**Comment by chrisjj** [comment]
> Looks nominal to me. 

@marechal-p , could you clarify? I know no meaning of _nominal_ under which this statement makes sense.

**Comment by marechal-p** [comment]
Current behavior doesn't look odd to me.

**Comment by chrisjj** [comment]
> Current behavior doesn't look odd to me. 

Did you notice that Undo failed to undo the edit?

> The monaco editor seems to delimit edition operations based on when you put whitespace (like when writing words).

There's no whitespace in this edit. In case you were mislead by github's manky styling, I've added a source screenshot.

This edit is simply one word being overtyped by another.

**Comment by msujew** [comment]
@vince-fugnitto I can't reproduce this issue anymore:

https://user-images.githubusercontent.com/4377073/126677413-b8ee66e0-7e5a-4047-908f-b997132c94dc.mp4
