### ISSUE TITLE
plugin tree rows are bogusly rendered

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7109]
Some recent PR, broke plugin tree rendering, rows are not rendered inline anymore
<img width="1904" alt="Screenshot 2020-02-09 at 07 25 26" src="https://user-images.githubusercontent.com/3082655/74097556-7fdbf100-4b0d-11ea-9c27-f7b8c934fb47.png">

@vince-fugnitto Do you remember which PR? Could we revert it? It is quite bad now. I think it was about missing ellipses in some trees, but it broke more than fixed as it seems.

**Comment by vince-fugnitto** [comment]
@akosyakov I haven’t tried but perhaps you meant this pull-request? 

https://github.com/eclipse-theia/theia/pull/6939

**Comment by akosyakov** [comment]
yes, it looks like space is missing in `.theia-tree-view.theia-TreeNodeSegment`. 🙈

**Comment by vince-fugnitto** [comment]
> yes, it looks like space is missing in `.theia-tree-view.theia-TreeNodeSegment`.

@Anasshahidd21 do you mind taking care of the regression?

**Comment by Anasshahidd21** [comment]
> > yes, it looks like space is missing in `.theia-tree-view.theia-TreeNodeSegment`.
> 
> @Anasshahidd21 do you mind taking care of the regression?

I made a change, which fixes the issue with the gitlens but the problem still remains with displaying ellipses, I am working on it until then if you want to merge it as it is assumed to be high priority, you can.
