### ISSUE TITLE
can't activate vscode python plugin when opening an ipynb file

### ISSUE THREAD

**Issue by tom-shan** [eclipse-theia/theia#7111]
### Description
The vscode python plugin is not activated when an ipynb file is opened, so the notbook editor is not showing. Only when a python file is opened first and vscode python plugin is activated successfully, the ipynb file can be opened in notebook editor.

### Reproduction Steps

![image](https://user-images.githubusercontent.com/7686800/74114256-f6e3b900-4be3-11ea-823a-178cf3ba0ea2.png)

**OS and Theia version:**
OS: centos 7
theia: d5f32625017a6ea38bc2a6bcdd0060ec8a92ab9c
python plugin: 2020.1.58038
**Diagnostics:** 

Per https://github.com/eclipse-theia/theia/blob/d5f32625017a6ea38bc2a6bcdd0060ec8a92ab9c/packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts#L212, only the language which contains grammars contaibutions can be activated.

vscode python plugin contains no grammars contribution of jupyter according to: 
https://github.com/microsoft/vscode-python/blob/master/package.json#L45
and 
https://github.com/microsoft/vscode-python/blob/ead69d5e2e910153e5715b6f4a7abf41f23efac5/package.json#L2778-L2784

**Comment by vince-fugnitto** [comment]
@tom-shan does the plugin activate correctly in vscode when first opening a `.ipynb` file?

**Comment by tom-shan** [comment]
> @tom-shan does the plugin activate correctly in vscode when first opening a `.ipynb` file?
yes, it activate correctly
