### ISSUE TITLE
about: dialog does not display correctly when re-opened

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7129]
**Description**

The `About` dialog does not display correctly when re-opened (opened subsequent times).

_First:_

![image](https://user-images.githubusercontent.com/40359487/74238153-31605b00-4ca3-11ea-965f-31b5b5071235.png)

_Second:_

![image](https://user-images.githubusercontent.com/40359487/74238124-21487b80-4ca3-11ea-93db-0a32086fb2cc.png)

**Comment by RomanNikitenko** [comment]
I can not reproduce it when I close the dialog by `OK` button, but it's reproduced permanently when I close the dialog by `X`(close) action.
