### ISSUE TITLE
workbench.action.showAllSymbols VSCode commands is missing

### ISSUE THREAD

**Issue by veredcon** [eclipse-theia/theia#7132]
### Description
In VSCode the command workbench.action.showAllSymbols - opens list of all symbols in workspace.
It seems it was implemented in theia but was called differently?
The command id in theia is: languages.workspace.symbol.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
Thank you for the issue @veredcon, I believe it is covered by the issue https://github.com/eclipse-theia/theia/issues/4569
