### ISSUE TITLE
tree-view: update styling when the tree row content cannot be fully displayed

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7145]
**Description**

The styling of `tree-view` components (ex: 'npm scripts') should be updated so we are consistent with the rest of the application. 

Namely, when a `tree-view` row's content cannot be fully displayed, the row should display **ellipsis** like other trees in the application. At the moment, the styling is inconsistent:

<img width="300" alt="Screen Shot 2020-02-12 at 11 05 02 AM" src="https://user-images.githubusercontent.com/40359487/74353494-fe43c780-4d87-11ea-8807-72ad2cd4b834.png">

**Additional Information**

Related Pull-Requests:
- https://github.com/eclipse-theia/theia/pull/7124
- https://github.com/eclipse-theia/theia/pull/6939

**Comment by garethwhittaker** [comment]
Hi @vince-fugnitto.

I don't see this issue in Gitpod. I've taken a screenshot showing the ellipsis being applied.
Notably the spanner icon for npm scripts is also different.

<img src="https://user-images.githubusercontent.com/2885325/74589424-2556ff00-4ffd-11ea-8c3e-fc6affab449f.png" width="250">

**Comment by vince-fugnitto** [comment]
> Hi @vince-fugnitto.
> 
> I don't see this issue in Gitpod. I've taken a screenshot showing the ellipsis being applied.
> Notably the spanner icon for npm scripts is also different.
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/2885325/74589424-2556ff00-4ffd-11ea-8c3e-fc6affab449f.png">

Hi @garethwhittaker, in your screenshot, are you displaying Gitpod itself or simply using Gitpod to open Theia? If it’s the former, it’s possible that Gitpod is using an older version of Theia that does not have this regression.

**Comment by vince-fugnitto** [comment]
@garethwhittaker I've verified again with `master`:

<img width="224" alt="Screen Shot 2020-02-15 at 10 23 25 AM" src="https://user-images.githubusercontent.com/40359487/74590537-49a2e380-4fdd-11ea-854f-bb1dcff4b78d.png">

The fix was initially present as part of #6939 but due to other issues it was reverted as part of #7124. #7124 fixed some problems with how other plugin views were displayed at the expense that rows present in `tree-views` did not successfully display ellipsis when their content could not be displayed entirely.

**Comment by garethwhittaker** [comment]
Yes you're right @vince-fugnitto. Whilst the issue doesn't appear in Gitpod, it does when using Gitpod to view latest Theia.

I can take a look at resolving this regression and provide an update in the next week.

**Comment by vince-fugnitto** [comment]
> I can take a look at resolving this regression and provide an update in the next week.

Sure! That'd be great, please keep #7124 in mind during your updates, other plugin views (such as gitlens) should be displayed correctly as well.

**Comment by vince-fugnitto** [comment]
Closed by #7237
