### ISSUE TITLE
ext-scripts: Not found

### ISSUE THREAD

**Issue by woaiwuchihan** [eclipse-theia/theia#7150]
When executed yarn,Give me a hint of the error。

Error: https://registry.npmjs.org/@theia%2fext-scripts: Not found

**Comment by vince-fugnitto** [comment]
@woaiwuchihan do you mind sharing additional information? The `@theia/ext-scripts` is not published on npm.

**Comment by woaiwuchihan** [comment]
in the theia-ide\my-app\node_modules\@theia\core，I want to execute yarn,and Download dependency package.But results of enforcement is https://registry.npmjs.org/@theia/ext-scripts: Not found
