### ISSUE TITLE
ext-scripts: Not found

### ISSUE THREAD

**Issue by woaiwuchihan** [eclipse-theia/theia#7151]
### Description
ext-scripts: Not found

### Reproduction Steps
in the theia-ide\my-app\node_modules@theia\core，I want to execute yarn,and Download dependency package.But results of enforcement is https://registry.npmjs.org/@theia/ext-scripts: Not found
**OS and Theia version:**
win7
**Diagnostics:**

**Comment by akosyakov** [comment]
ext-scripts is utility dev package just for this repo, it is never distributed, you cannot run scripts of installed packages, also why do you want it?

**Comment by woaiwuchihan** [comment]
I change some typescript code,then want to build them.

**Comment by akosyakov** [comment]
It is not possible. Distributed typescript is not for changed, but for reading.

**Comment by woaiwuchihan** [comment]
For example,I would like to change some menu text，Do I have to use DI?

**Comment by akosyakov** [comment]
yes
