### ISSUE TITLE
Live Preview: reflect changes without having to save again and again.

### ISSUE THREAD

**Issue by nisarhassan12** [eclipse-theia/theia#7165]
It would be nice if the Live Preview can reflect the changes made to HTML, CSS and JS files on the fly without having to save the file again and again.

There are extensions and CLI tools that reflect the changes once files are saved but they don't reflect the changes as they are made.

https://codepen.io does this quite well.

**Comment by nisarhassan12** [comment]
Also if an HTML file links to a CSS file and you make changes to that, in order for them to be reflected in the preview only saving the CSS file does not work. You have to re-open the HTML file's preview after saving the CSS.

**Comment by akosyakov** [comment]
Do you mean that we should reflect dirty editor changes? What should happen while you are typing and thinking?

**Comment by nisarhassan12** [comment]
> Do you mean that we should reflect dirty editor changes? What should happen while you are typing and thinking?

Thanks! There can be a slight delay for the changes to be reflected(let say 800ms) like it is in Codepen.

**Comment by svenefftinge** [comment]
The mini browser is pointing to a regular web-server and there are web-servers that know how to do hot-reload on file changes. The file preview (right top icon) for HTML does already update on document change. I know online playgrounds that are specifically built for small web projects come with such a preview environment, but Theia is targeting all kinds of development. So making assumptions about how to serve and properly update/reload would break many user cases.

**Comment by scheng123** [comment]
cloud9 ide does this quite well, especially with HTML including another CSS file.

Even though it might break use cases, giving the user the option to enable/disable preview can easily let the user adjust to their specific needs (thus, targeting all kinds of development)
