### ISSUE TITLE
Snippets should support an array prefix

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#7167]
[VS Code snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets) allow an array of prefix while theia [does not](https://github.com/eclipse-theia/theia/blob/master/packages/monaco/src/browser/monaco-snippet-suggest-provider.ts#L245)

**Comment by garethwhittaker** [comment]
I'll take a look at implementing this enhancement and provide an update in the next week.
