### ISSUE TITLE
Implement stabilized workspace VS Code APIs

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7171]
Some events like `on(Did|Will)(Create|Delete|Rename)Files` were finalized and marked as stable in vscode.d.ts We should implement it to support latest version of typescript built-in extension. It should be quite straightforward after  https://github.com/eclipse-theia/theia/pull/7139 gets merged.

**Comment by akosyakov** [comment]
It is important to run latest version of Java extension.

**Comment by kittaakos** [comment]
It affects TS also (#7840), I am removing the `java` label.
