### ISSUE TITLE
make sure the browser state is not shared between applications

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7172]
### Description
 
This is a follow-up of #6650. Currently,  the `theme`, `icon-theme` and the `theme.background` are globally set on the `window.localStorage`.

![Screen Shot 2020-02-18 at 16 13 07](https://user-images.githubusercontent.com/1405703/74749176-0a3cf700-526a-11ea-82aa-7902aaef7ba1.jpg)

We have to prefix it with the application name. (Or something we derive from the application's name.) So when running two completely different applications on the same port, domain, and port triplet, one app won't mess up the local storage of the other app.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
@kittaakos Do you mean that 2 different electron apps share the exactly the same local storage?

**Comment by akosyakov** [comment]
@thegecko @westbury Maybe you know how one can configure user data folder for the concrete electron app?

**Comment by kittaakos** [comment]
> Do you mean that 2 different electron apps share the exactly the same local storage

Yes.

Also when testing/running any browser app from the localhost. So it's not electron specific.

**Comment by akosyakov** [comment]
> Yes.

https://github.com/electron/electron/issues/10831#issuecomment-337466983 says that local storage is different per the app. The application name is specified here: https://www.electronjs.org/docs/api/app#appname. As I read it it should be enough to specify a unique name for electron app in package.json to isolated browser user data for different electron apps.  

> Also when testing/running any browser app from the localhost. So it's not electron specific.

Each browser has own user data folder including local storage as well.

**Comment by akosyakov** [comment]
So, then i run electron with:
```
console.log('appName', app.getName());
console.log('appData', app.getPath('appData'));
console.log('userData', app.getPath('userData'));
```
I get:
```
appName Electron
appData /home/gitpod/.config
userData /home/gitpod/.config/Electron
```

It is obviously bogus. The app name should not be Electron (some default placeholder). It seems that electron has some assumptions about how it should be started to pick up the app name correctly: https://github.com/electron/electron/issues/3391#issuecomment-155606143

I don't see how this issue have anything to do with browser target.

**Comment by akosyakov** [comment]
Ok, now I've realised that it affects the browser target too. I don't think that the issue still can be resolved just by prefixing keys in local storage. Browser store more user data, except local storage, like cookies, indexed db, sessions and so on, everything will be shared. The easy will be to use the different port in this case? cc @svenefftinge

**Comment by akosyakov** [comment]
Discussed with @svenefftinge:
- for browser it is not the issue. In production origins are defined by embedding product. For development one can configure different ports.
- for electron, we should fix how application are named, that not everything is stored under `/home/gitpod/.config/Electron`, but per a project.

Trying to prefix records in local storage, cookies, indexed db and so on is insecure (allowing each app to read each other user data) and inconvenient for adopters (one has to care about it at all).

**Comment by kittaakos** [comment]
> * for browser it is not the issue

Very sad.

> * or electron, we should fix how application are named, that not everything is stored under `/home/gitpod/.config/Electron`, but per a product.

It's not an issue. Once you package it, it will have a different name.

**Comment by akosyakov** [comment]
> It's not an issue. Once you package it, it will have a different name.

but it breaks if one start from sources?

**Comment by thegecko** [comment]
I seem to remember our tests showed this wasn't an issue for Electron as it automatically sets up local storage per application. The only times we've seen this problem is when bringing up the browser version of different Theia apps on localhost.

cc @mcgordonite

**Comment by mcgordonite** [comment]
> I seem to remember our tests showed this wasn't an issue for Electron as it automatically sets up local storage per application.

That's correct. Once the Electron app is packaged, `app.getName()` will return the correct product name, not `"Electron"`. Electron ensures that each app gets an isolated local storage, like browsers do for sites at different origins.
