### ISSUE TITLE
Plugin loading breaks when resistFingerprinting is enabled

### ISSUE THREAD

**Issue by Luzifer** [eclipse-theia/theia#7173]
### Description
When Firefox is hardened against fingerprinting by enabling `privacy.resistFingerprinting` loading of plugins breaks with an error to the console. This for example breaks language-support-plugins.

### Reproduction Steps
- Fetch `theiaide/theia:next` docker image and start it (`:latest` shows same behavior)
- Get a recent Firefox
- Access `about:config` and enable `privacy.resistFingerprinting`
- Try to load the application
- See error:

```
root ERROR Failed to load plugins: U</e.prototype.createMeasurement/<@https://***HOST***/bundle.js:8:376112
U</e.prototype.logMeasurement@https://***HOST***/bundle.js:8:376368
U</e.prototype.syncPlugins/</<@https://***HOST***/bundle.js:8:366859
s/</<@https://***HOST***/bundle.js:8:360880
s/<@https://***HOST***/bundle.js:8:360985
a@https://***HOST***/bundle.js:8:359728
```

**OS and Theia version:**
- Theia: `@theia/core 0.16.0-next.00c1747c`
- OS: Archlinux, Firefox 73.0

**Diagnostics:** 
- [Firefox Bug 1369303](https://bugzilla.mozilla.org/show_bug.cgi?id=1369303)
- [Firefox Bug 1511941](https://bugzilla.mozilla.org/show_bug.cgi?id=1511941) (Possible fix)
- Relevant code: https://github.com/eclipse-theia/theia/blob/00c1747c98aefe946d2f2c6b7db5b8e356183abf/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L577-L594
- Failing code: https://github.com/eclipse-theia/theia/blob/00c1747c98aefe946d2f2c6b7db5b8e356183abf/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L588

**Example (tested in dev-console):**
```
21:27:49.736 performance.mark('foo-start')
21:27:49.756 undefined
21:28:08.117 performance.mark('foo-end')
21:28:08.178 undefined
21:28:32.134 performance.measure('foo-name', 'foo-start', 'foo-end')
21:28:32.152 undefined
21:28:42.935 performance.getEntriesByName('foo-name')
21:28:42.982 Array []
21:28:46.752 performance.getEntriesByName('foo-name')[0]
21:28:46.763 undefined
21:28:51.444 performance.getEntriesByName('foo-name')[0].duration
21:28:51.487 TypeError: performance.getEntriesByName(...)[0] is undefined
```

refs / obsoletes https://github.com/theia-ide/theia-apps/issues/306

**Comment by akosyakov** [comment]
I wonder what their recommendation to use instead of performance API in such case. As far as I know that the standardised API and expected to work in all browsers.

**Comment by Luzifer** [comment]
@akosyakov the API itself works. It just does not return performance data. While in `core` there is an iteration through the returned array which in that case would be an iteration over `Array[]` in this code the first element is just accessed.

Firefox does not return any elements when `resistFingerprinting` is enabled and therefore a length check is required in before accessing the `duration` of the first element.
