### ISSUE TITLE
support vscode.CustomExecution api

### ISSUE THREAD

**Issue by svor** [eclipse-theia/theia#7185]
### Description
To see that Java language server is initializing need to click on the task button:
![screenshot-localhost_3000-2020 02 (1)](https://user-images.githubusercontent.com/1271546/74926976-7856fa80-53df-11ea-88bb-d8f8cc6865f0.png)
But this button doesn't work:
```log
command.ts:15 Uncaught (in promise) TypeError: i.CustomExecution is not a constructor
    at :3000/tmp/vscode-unpacked/java-0.57.0-2029.vsix/extension/dist/extension.js:7
    at Generator.next (<anonymous>)
    at o (:3000/tmp/vscode-unpacked/java-0.57.0-2029.vsix/extension/dist/extension.js:7)
```

### Reproduction Steps

1. Download vscode java plugin https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.57.0-2029.vsix and put it into plugins folder
2. Open the workspace with java project and try to click on the active task button

**OS and Theia version:**
Linux
@theia/example-browser 0.15.0

**Diagnostics:** 

That's how it looks in vscode:

![](https://user-images.githubusercontent.com/148698/71910157-b79ff380-3171-11ea-806e-5fb53abafc51.gif)

**Comment by akosyakov** [comment]
I don't think we support `CustomExecution` VS Code api for tasks yet.

**Comment by marcdumais-work** [comment]
Version `0.54.2` of that extension is known to work well in Theia AFAIK. Could you try that version and report if you have the same issue? 

https://github.com/redhat-developer/vscode-java/releases/download/v0.54.2/redhat.java-0.54.2.vsix

**Comment by 502647092** [comment]
@marcdumais-work I test `redhat.java@0.62.0` it's work
but console have error `Uncaught (in promise) TypeError: i.CustomExecution is not a constructor`
when i click 
![image](https://user-images.githubusercontent.com/10203793/82858936-ddbf0800-9f47-11ea-9a2f-d3a32d8b65e3.png)

**Comment by allaVolkov** [comment]
Is implementation of CustomExecution planned?

**Comment by akosyakov** [comment]
Contributions to issues marked as `help wanted` and without any assignments are welcomed. It means that nobody is working or planning to work on them right now.

**Comment by ericwill** [comment]
Someone from my team will take a look at this after the upcoming Che sprint, so sometime late August. Of course by no means should that stop someone else from working on it before then, if they want to!

**Comment by gsmachado** [comment]
Hey @ericwill 

Some info:

I'm running theia 1.60, and tried to add [this extension here](https://open-vsx.org/extension/richardwillis/vscode-gradle).

However, I see this error when the extension starts:

```
[error] Unable to generate vscode tasks from gradle tasks: vscode.CustomExecution is not a constructor
```

Are you guys working on this? Anything I could do as a workaround to make it work?

**Comment by tsmaeder** [comment]
@gsmachado no, it's not in the sprint plan. We're aware that this API is not implemented. It's a question of assigning resources.

**Comment by ericwill** [comment]
> @gsmachado no, it's not in the sprint plan. We're aware that this API is not implemented. It's a question of assigning resources.

Correct. @gsmachado if you propose a PR to theia, someone from our team can review it.

**Comment by gsmachado** [comment]
> Correct. @gsmachado if you propose a PR to theia, someone from our team can review it.

Alright! I would be interested to do it, but I'm not even sure what's the correct behavior of this `vscode.customExecutior` API, and where I can find the "reference implementation" of it.

I would appreciate any leads on this -- maybe I get inspired and get something done. 😄

**Comment by marcdumais-work** [comment]
Hi @gsmachado,

A few pointers - those around here that know more than me can correct or complete:

vscode API doc: https://code.visualstudio.com/api/references/vscode-api#CustomExecution

implementation:
https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostTypes.ts#L1874
https://github.com/microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostTask.ts#L480

On the Theia side: 
need to define `CustomExecution` in this file I think: https://github.com/eclipse-theia/theia/blob/master/packages/plugin/src/theia.d.ts#L8834 

And probably to enhance this to look more like vscode above:
https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext/src/plugin/tasks/tasks.ts#L62

examples of the API being used by `vscode-gradle`, that could be used to test: [1](https://github.com/badsyntax/vscode-gradle/blob/0811602a2f632fb16718790fce4d9744b10a27ff/extension/src/commands/RunBuildCommand.ts#L46), [2](https://github.com/badsyntax/vscode-gradle/blob/0811602a2f632fb16718790fce4d9744b10a27ff/extension/src/tasks/taskUtil.ts#L179)


P.S. We generally do not reinvent the wheel. It's permissible to copy code from the `vscode` repo (MIT) so long as credit is given and the license respected. See [this for example](https://github.com/eclipse-theia/theia/blob/master/packages/plugin/src/theia.d.ts#L17-L22). If you do copy some code, please keep a log for each snippet, including file(s)/line(s)/range and from which vscode version. We'll need to go through an internal Eclipse Foundation process, that vets copied code, before we can merge, and your detailed log will facilitate this.

**Comment by gsmachado** [comment]
@marcdumais-work awesome answer. You know, being in the open-source space for some time, that's what I believe we need more: people willing to at least explain, with a reasonable level of detail, what needs to be done, where people can start with, etc. This kind of thing motivates people. 👍 😄

**Comment by marcdumais-work** [comment]
@gsmachado I hope this is good to get you started. Please ask here if you have questions along the way.

**Comment by mauricioszabo** [comment]
Well, while this API is not implemented, is there a work-around? A way for plug-in authors to implement a Task that's simply a callback, for example, even if I have to keep two code versions (one for vscode and one for Theia)

Otherwise, my plug-in will not work at all :(

**Comment by vince-fugnitto** [comment]
> Well, while this API is not implemented, is there a work-around? A way for plug-in authors to implement a Task that's simply a callback, for example, even if I have to keep two code versions (one for vscode and one for Theia)

@mauricioszabo I do not believe there is a workaround at the moment, if the feature is important to your use-case you can always attempt to implement the API yourself and submit a pull-request. The following https://github.com/eclipse-theia/theia/issues/7185#issuecomment-703740249 describes the necessary changes in detail.

**Comment by TomHermanSAP** [comment]
Hi @gsmachado,
It has been some time since your last comment in this thread.
Are you working on a PR to implement the `vscode.CustomExecution` API?

Thank you!

**Comment by kittaakos** [comment]
I will look into this.

**Comment by shyshywhy** [comment]
I have an implementation，https://github.com/eclipse-theia/theia/pull/9189
