### ISSUE TITLE
VS Code webview sample not running

### ISSUE THREAD

**Issue by vibhormda** [eclipse-theia/theia#7190]
### Description
Running the vs code webview sample inside theia browser instance does not work as expected.

### Reproduction Steps
1). Build theia from latest sources from master branch.
[https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start](url)

2). Follow the link to test VS code sample extensions **without** building the vsix file.
[https://github.com/eclipse-theia/theia/wiki/Testing-VS-Code-extensions](url)

3). The gif loads successfully but the script file fails to load inside the webview resulting in unexpected behaviour.

This issue is reproducible even after generating the vsix file from the sample and deploying it inside the plugins folder.

Webview is unable to fetch any of the locally referenced resources.
Accessing the complete resource URL externally (outside webview) also fetched nothing(404). 

I observed that the URL genrateed to fecth the main.js file is also incorrect.
http://my_theia_server_hostname/webview/theia-resource/file///tmp/vscode-unpacked/cat-coding-0.0.1.vsix/extension/media/main.js

After correcting the URL (replacing file/// -> file/) the file still fails to load.

![network_calls](https://user-images.githubusercontent.com/8724923/74964715-2a101e80-5414-11ea-920a-4128c2664e98.png)

Theia server is running remotely on centOS machine and the application is accessed from browser(chrome) running on windows 10.

OS - CentOS(7.2) 
Theia - build from master branch

**Comment by akosyakov** [comment]
Which browser do you use? What is the hostname on which you deploy? Do you have any errors in browser console?

Webviews work only in the secure content, https or localhost, not over http. Firefox has a bug that it does not treat subdomains of localhost as secure, so by default only Chrome.

**Comment by akosyakov** [comment]
Fetching of resources is done by Theia via the service worker, not by browser, so a URL is fine.

**Comment by vibhormda** [comment]
I am using Chrome and theia is running over non-https mode.
The host is on a local CentOS box inside internal network. Will the self signed certificate be good to make webview work ?

**Comment by akosyakov** [comment]
@vibhormda i did not try, but stackoverflow says no: https://stackoverflow.com/questions/38728176/can-you-use-a-service-worker-with-a-self-signed-certificate see for a workaround in the answer

**Comment by vibhormda** [comment]
@akosyakov  Thank You for the links. I was succesfully able to run the webview sample after your inputs.

### Here are the steps I am following to run theia on HTTPS mode -

export THEIA_WEBVIEW_EXTERNAL_ENDPOINT=my-theia-host
yarn run start --ssl --cert host.cert --certkey host.key --hostname 0.0.0.0 --port 443
start chrome : chrome.exe --user-data-dir=/tmp/foo --ignore-certificate-errors --unsafely-treat-insecure-origin-as-secure=http://my-theia-host/

**Comment by akosyakov** [comment]
Webviews are designated to be treated as remote content which can access your browser states if you deployed as in https://github.com/eclipse-theia/theia/issues/7190#issuecomment-589721450 It is fine if you don't have any secrets, i.el cookies, access to filesystem.

> Is there any way to run the webview without setting THEIA_WEBVIEW_EXTERNAL_ENDPOINT parameter. I mean does this parameter required to be set in production environment as well ?

By default, it is set to be secured with unique origins for each webview that they cannot break out via the main window. If someone wants to disable it in production environment, then they have to consciously set it. In your case webview can access anything from Theia main window.
