### ISSUE TITLE
[regression] description is not aligned properly in the plugin tree

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7199]
It should be aligned to the right.

Now it is:
<img width="385" alt="Screenshot 2020-02-24 at 11 26 24" src="https://user-images.githubusercontent.com/3082655/75145085-9894fb00-56f8-11ea-977c-7b47eded4cbc.png">

How it used to be:
<img width="396" alt="Screenshot 2020-02-24 at 11 27 16" src="https://user-images.githubusercontent.com/3082655/75145100-a0ed3600-56f8-11ea-9c15-f66ddaffd1fe.png">

@vince-fugnitto I am not sure which styling PR broke it. It would be good to find and revert it.

**Comment by akosyakov** [comment]
It would be good to fix, all plugin trees are affected now.

**Comment by vince-fugnitto** [comment]
> It would be good to fix, all plugin trees are affected now.

I could not identify which pull-request affected the plugin trees unfortunately.

**Comment by akosyakov** [comment]
@vince-fugnitto ok, i will try to fix it later. Let's release without it. It does not look nice, but it does not break.

**Comment by akosyakov** [comment]
https://github.com/eclipse-theia/theia/commit/d7e4d54a286e9c989a4bcdde301833514305a5a0#diff-54e02e62e25266d75875fd54a1ca1c15R284 this line broke it
