### ISSUE TITLE
Use the user's account Icon instead of a generic one

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse-theia/theia#7206]
### Description
Currently seemingly at random generic icons are used for git-history/head commit
![image](https://user-images.githubusercontent.com/50386709/75169086-94171500-56ed-11ea-8ea1-c892fc0b03a4.png)
![image](https://user-images.githubusercontent.com/50386709/75169203-c3c61d00-56ed-11ea-8623-bd4004532d11.png)

### Reproduction Steps
Look at git history in theia and see that some people have their icon and some have a random png

Gitpod

**Comment by westbury** [comment]
The icons come from gravatar.com.  If someone does not upload an image then a random image is used.  Most sites assign random images until someone uploads one, e.g. github does this (speaking as someone who has not uploaded a github image).

If you prefer a different service then you can rebind ScmAvatarService.

**Comment by JesterOrNot** [comment]
Thanks! Do we document this?

**Comment by akosyakov** [comment]
@JesterOrNot It should be already overridden in Gitpod. For Gitpod we are also going to get rid of current history view and reuse Gitlens instead.
