### ISSUE TITLE
Refactoring features?

### ISSUE THREAD

**Issue by DavyKoravand** [eclipse-theia/theia#7223]
Hi,

I'm wondering if Theia will get some built-in refactoring features like many local IDEs have. For example, with IntelliJ you can extract Java code into a method with a single shortcut. Are features like these planned, or will they require a plugin?

**Comment by akosyakov** [comment]
Theia is running vscode-java: https://github.com/redhat-developer/vscode-java Any refactoring supported by this extension should work.
