### ISSUE TITLE
Render .markdown files in preview

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse-theia/theia#7228]
### Description
Allow live previews for `.markdown` file just like `.md` files

**OS and Theia version:**
Gitpod

`.markdown` file UI
![image](https://user-images.githubusercontent.com/50386709/75404666-d77da900-58d0-11ea-9ded-4e38910c8792.png)
Notice no preview button
`.md` file UI
![image](https://user-images.githubusercontent.com/50386709/75404701-f54b0e00-58d0-11ea-8883-18c08c1db1f6.png)

**Comment by vince-fugnitto** [comment]
@JesterOrNot this issue looks more suitable for Gitpod itself.
Theia `master` does have **preview** support for `.markdown` files.

<div align='center'>

<img width="1772" alt="Screen Shot 2020-02-26 at 9 39 42 PM" src="https://user-images.githubusercontent.com/40359487/75407295-9c837180-58e0-11ea-8528-34e2a38d9a83.png">


</div>

**Comment by akosyakov** [comment]
@vince-fugnitto with theia extension only?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto with theia extension only?

I haven’t tried with only the `@theia/preview` extension, by the looks of the tabbar toolbar icon it looks like the functionality comes from the builtin. Updating our own extension should be fairly trivial if Gitpod is using the Theia extension.

**Comment by akosyakov** [comment]
Right now VS Code extension allows only one preview at the time, that's limiting. They are working on allowing multiple then we can get rid of our extension completely.
