### ISSUE TITLE
[documentation] Update other extension's READMEs

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#7229]
### Description
`@theia/getting-started` was done first as template:  https://github.com/eclipse-theia/theia/pull/7077 . The remaining extensions of the repo should be updated to be similar.

**Comment by vince-fugnitto** [comment]
Closing https://github.com/eclipse-theia/theia/issues/6518 in favor of tracking the feature here.

**Comment by marcdumais-work** [comment]
Ah, you already had an issue with nicer description :)  The milestone had only the issue about updating `getting-started` as example for the others, so I thought the overall one was missing. Feel free to re-open your issue and add it to the milestone and instead close this one here as duplicate.

**Comment by vince-fugnitto** [comment]
Closing in favor of #6518.
