### ISSUE TITLE
Open Dialog Navigation using keyboard

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#723]
It would be nice to be able to use the keyboard to filter or select directories/folders inside the File Open dialog like the native open can do.

Otherwise just trying to graphically find the right folder can be quite irritating.

**Comment by svenefftinge** [comment]
Navigation with keyboard is supported. 
I assume you mean filtering by typing parts of names?

**Comment by hexa00** [comment]
In native linux open dialog you don't get filtering but you get a "goto behavior" like typing `h` will get to to the directories starting with h ? 

How is it on macOS ?

I'd rather have filtering however... but emulative the native way may be good too...

**Comment by svenefftinge** [comment]
Would be solved with #853 but in general it would be good to support this in our tree widgets generally. I.e. it would be useful in outline and navigator, too.

**Comment by kittaakos** [comment]
It's supported by trees and file-trees in general.

![screencast 2020-04-04 14-25-09](https://user-images.githubusercontent.com/1405703/78450651-717b0300-7680-11ea-9a6f-7d30c03eba4a.gif)

Please reopen if required.
