### ISSUE TITLE
i18n.properties files cannot be viewed  at command "Preview: Open URL"

### ISSUE THREAD

**Issue by i501378** [eclipse-theia/theia#7231]
### Description
We need to view the files by calling the command "Preview: Open URL"
General file types are OK, but i18n.properties files cannot be viewed now.

### Reproduction Steps
1) create or upload file "i18n.properties" into the root of workspace.

2) execute command "Preview: Open URL", and input the url as file:///workspace/theia/i18n.properties

3) it's not shown in the preview widget.

**OS and Theia version: gitpod latest version

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@i501378 do you have an example project with a `i18n.properties` file so we can verify the issue? You mentioned that:
> i18n.properties files cannot be viewed now

Was it ever the case that the file could be successfully previewed?

**Comment by akosyakov** [comment]
It should be possible to preview local html files or pictures and so on

**Comment by i501378** [comment]
> @i501378 do you have an example project with a `i18n.properties` file so we can verify the issue? You mentioned that:
> 
> > i18n.properties files cannot be viewed now
> 
> Was it ever the case that the file could be successfully previewed?

[i18n.zip](https://github.com/eclipse-theia/theia/files/4271447/i18n.zip)

it supported on vscode with extension Unique Identifier: "auchenberg.vscode-browser-preview"

**Comment by akosyakov** [comment]
@i501378 You can use `auchenberg.vscode-browser-preview` with Theia as well.

**Comment by i501378** [comment]
The i18n.properties cannot be fetched, that means any html using i18n.properties will not work as expected. 
The issue may be reproduced by the below steps:
[test.zip](https://github.com/eclipse-theia/theia/files/4311901/test.zip)
upload the file and unzip it into the root of workspace.
execute command "Preview: Open URL", and input the "test/test.html" url
in the shown card, we will find the "TITLE" and "SUBTITLE" are not replaced by the related translation texts.

The cause to this bug is that we don't get the content from the defaultHandler() response when file type is not exists at mime-db.
If we will update the [response](https://github.com/eclipse-theia/theia/blob/master/packages/mini-browser/src/node/mini-browser-endpoint.ts#L183) at this scenario and send the content too this issue will be fixed.
@akosyakov what do you this about this solution?

**Comment by akosyakov** [comment]
> is not exists at mime-db. If the response at this scenario will send the content too this issue will be fixed.

cc @kittaakos maybe you know how to support other mime types

**Comment by i501378** [comment]
@kittaakos can you update?

**Comment by kittaakos** [comment]
> We need to view the files by calling the command "Preview: Open URL"

Can you explain why do you want to preview a `*.properties` file in the `Preview`?

> 2\. execute command "Preview: Open URL", and input the url as file:///workspace/theia/i18n.properties

How often do you open such file in your favorite browser?

**Comment by i501378** [comment]
Please see the use case below:
> The i18n.properties cannot be fetched, that means any html using i18n.properties will not work as expected.
The issue may be reproduced by the below steps:
test.zip
upload the file and unzip it into the root of workspace.
execute command "Preview: Open URL", and input the "test/test.html" url
in the shown card, we will find the "TITLE" and "SUBTITLE" are not replaced by the related translation text.

**Comment by kittaakos** [comment]
@i501378, do you have your own Theia extension?

**Comment by i501378** [comment]
yes, but i checked it without extensions

**Comment by kittaakos** [comment]
> yes,

Super, for the time being, you can fix it on your side by customing the code you have mentioned 👇

> If the [response](https://github.com/eclipse-theia/theia/blob/master/packages/mini-browser/src/node/mini-browser-endpoint.ts#L183) at this scenario will send the content too this issue will be fixed.

PRs are welcome! Feel free to create one if you think this is a bug and should behave differently. Thanks!
