### ISSUE TITLE
vscode webview input tag cannot enter anything

### ISSUE THREAD

**Issue by HuangJunjia** [eclipse-theia/theia#7232]
### Description
 
vscode extension create a webview but input element cannot enter anything.

### Reproduction Steps

1. vscode extension create a webview
2. Enter characters in the input element

**OS and Theia version:**
![image](https://user-images.githubusercontent.com/19429582/75437081-a2d12680-5990-11ea-8b0b-5ffc031702c2.png)

**Diagnostics:** 

![image](https://gitee.com/huangjunjia1995/pic/raw/master/uPic/Kapture%202020-02-27%20at%2018.32.40.gif)

**Comment by akosyakov** [comment]
@HuangJunjia Could you try before this PR: https://github.com/eclipse-theia/theia/pull/7216?

cc @azatsarynnyy @vrubezhny @vince-fugnitto Could you check please? If it is the case we have to revert it before the release. cc @marcdumais-work

**Comment by vince-fugnitto** [comment]
> @HuangJunjia Could you try before this PR: #7216?
> 
> cc @azatsarynnyy @vrubezhny @vince-fugnitto Could you check please? If it is the case we have to revert it before the release today. cc @marcdumais-work

I confirmed it is caused by #7216 and have provided a fix https://github.com/eclipse-theia/theia/pull/7233
