### ISSUE TITLE
Elm Extension won't start because it requires VSCode 1.42

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse-theia/theia#7243]
### Description
Language server fails to start due to an outdated version of VSCode

### Reproduction Steps
![image](https://user-images.githubusercontent.com/50386709/75571622-2cc7d080-5a1f-11ea-9f26-e908be14e03b.png)
Open https://gitpod.io/#https://github.com/jesterornot/gitpod-elm/tree/bug
The relevant extension is https://marketplace.visualstudio.com/items?itemName=Elmtooling.elm-ls-vscode

**OS and Theia version:**
Gitpod

**Diagnostics:** 
```
The language client requires VS Code version ^1.42.0 but received version 1.41.1
```

**Comment by vince-fugnitto** [comment]
@JesterOrNot you can specify a `VSCODE_API_VERSION` when starting the application if you'd like, else I'd suggest using an older version of the `elm` extension. We are still working towards supporting newer versions of the API (and ultimately extensions). (related https://github.com/eclipse-theia/theia/issues/6804)

For the moment I think we can hold-off creating issues for each extension we encounter which requires the newer API as it will become noisy and instead work towards supporting the new API.
In the meantime it is acceptable to use older versions of extensions (it is actually what we do with the `builtins`).

**Comment by akosyakov** [comment]
We should bump up VSCODE_API_VERSION. It's again `vscode-languageclient` defaults to 1.42. Any extension which is using this version regardless whether it actually uses unsupported by us features won't work.

**Comment by akosyakov** [comment]
Yes, just checked that they are using progress enhancements from new `vscode-languageclient`: https://github.com/elm-tooling/elm-language-client-vscode/commit/b6516fb2ed38d5b070e47c48c69600d601af3382#diff-bc3c0f2fe3aca9ddbe96347ffb00641e

It is already supported by us.

**Comment by akosyakov** [comment]
@JesterOrNot it can be bumped up here: https://github.com/eclipse-theia/theia/blob/764b74045fc1d8e1f4db2870e5517b5dd44693de/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts#L22

**Comment by JesterOrNot** [comment]
On it!

**Comment by sh7dm** [comment]
Vetur is also affected, v0.24.0 doesn't work without VS Code API v1.42.x

**Comment by akosyakov** [comment]
@sh7dm Could you send a PR bumping up the version and check whether vetur works with it?

**Comment by sh7dm** [comment]
Of course :cowboy_hat_face: !

**Comment by sh7dm** [comment]
@akosyakov that works, I'll submit a PR.
