### ISSUE TITLE
[vscode][builtin][plugin] vscode-builtin-npm r.Task2 is not a constructor

### ISSUE THREAD

**Issue by 502647092** [eclipse-theia/theia#7245]
### Description

install vscode-builtin-npm next version have some error

### Reproduction Steps

install next version builtin plugin
- `@theia/vscode-builtin-npm`

**OS and Theia version:**
Theia 0.17.0-next.c965552a

**Diagnostics:** 

```
theia_1  | root ERROR Failed to fetch children for 'npm' TypeError: r.Task2 is not a constructor
theia_1  |     at w (/home/theia/plugins/vscode-builtin-npm/package/dist/main.js:1:10219)
theia_1  |     at Object.keys.forEach.t (/home/theia/plugins/vscode-builtin-npm/package/dist/main.js:1:9332)
theia_1  |     at Array.forEach (<anonymous>)
theia_1  |     at b (/home/theia/plugins/vscode-builtin-npm/package/dist/main.js:1:9312)
```

**Comment by vince-fugnitto** [comment]
Thank you for the issue!
Closing since we have a more up-to-date issue tracking the incompatibility: https://github.com/eclipse-theia/theia/issues/7779
