### ISSUE TITLE
Theia should support `editor.defaultFormatter` key

### ISSUE THREAD

**Issue by felipecrs** [eclipse-theia/theia#7252]
This setting aims to set a default formatter for a language (or every language). 

Reference and use case:
https://github.com/prettier/prettier-vscode/blob/master/README.md#default-formatter

In this project: https://gitpod.io/#https://github.com/felipecassiors/ubuntu1804-4dev, I want to enforce the default formatter to prettier, however, the Ruby one comes on by default. To make Prettier work for Ruby I have to edit any of its settings (and revert back), and then Prettier starts to work for Ruby.

**Comment by Eliav2** [comment]
hey friend - can you explain in more detail what you did to make prettier work? I'm facing the same issue with javascript/typescript files

**Comment by felipecrs** [comment]
Hi @Eliav2. I'm not sure, it has been a while and I'm not using Theia anymore. A lot has changed since I opened this issue also.

**Comment by vince-fugnitto** [comment]
I believe https://github.com/eclipse-theia/theia/pull/8446 resolved the issue :+1: Please comment again if it's not the case.
