### ISSUE TITLE
VSCode Extension Todo Tree does not work

### ISSUE THREAD

**Issue by Sandared** [eclipse-theia/theia#7266]
### Description
The extension (Todo Tree)[https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree] does not work in Theia.

When I install it it complained about not being able to find vscode-ripgrep. I installed that too, but vscode-ripgrep then complained about not being able to execute some binaries.
I then tried to download ripgrep directly and made it executbale for everyone, then set the todo-tree.ripgrep.ripgrep property to point to the downloaded ripgrep executable, but the extension complains about “permission denied” when it tries to execute ripgrep.

### Reproduction Steps
Install Todo Tree Extension. Then an error message should come up complaining about not being able to  find vscode-ripgrep

**OS and Theia version:**
I tried that in Gitpod

**Comment by vince-fugnitto** [comment]
The extension worked correctly when updating the following **preference**:

```json
"todo-tree.ripgrep.ripgrep": "/Users/vince/workspace/theia/node_modules/vscode-ripgrep/bin/rg",
```

<img width="486" alt="Screen Shot 2020-03-03 at 8 24 05 AM" src="https://user-images.githubusercontent.com/40359487/75779948-98b07e80-5d28-11ea-9924-49b098d78b07.png">
<img width="486" alt="Screen Shot 2020-03-03 at 8 24 13 AM" src="https://user-images.githubusercontent.com/40359487/75779949-99491500-5d28-11ea-83b7-0e8bb9d5c888.png">

**Comment by akosyakov** [comment]
@vince-fugnitto I wonder does it work out of box in VS Code or there it is also necessary to configure the preference? If some extensions have some assumptions about location of vscode-rigrep, maybe we could do something about it.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I wonder does it work out of box in VS Code or there it is also necessary to configure the preference? If some extensions have some assumptions about location of vscode-rigrep, maybe we could do something about it.

This is what I could find for `vscode-ripgrep` in that particular extension:

https://github.com/Gruntfuggly/todo-tree/search?q=vscode-ripgrep&unscoped_q=vscode-ripgrep

**Comment by akosyakov** [comment]
ok, i see it could be possible to make it work for Electron if we put under the same location in asar file, not sure for browser target

**Comment by vince-fugnitto** [comment]
> There were already similar issue for docker extension.

I guess the `emmet` has a similar issue:
- https://github.com/eclipse-theia/theia/issues/7019#issuecomment-598479317

**Comment by kittaakos** [comment]
Here is the solution: https://github.com/gitpod-io/gitpod/issues/1846#issuecomment-692593645
