### ISSUE TITLE
Integrate VSCode API FileSystemProvider in FileSystem

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#7269]
Currently, when we register a file system provider via the VS Code API, we only register a resource provider. This means that we cannot do many interesting things like listing directories or accessing raw byte content or deleting files for files provided by plugins.
I propose that we refactor file system support to be modeled on VS Code files system providers with the node file system just being the provider for the "file" scheme.

**Comment by tsmaeder** [comment]
Possible dupe: https://github.com/eclipse-theia/theia/issues/7127 but I'm not sure what @akosyakov means there.

**Comment by akosyakov** [comment]
@tsmaeder it is fine to close #7127. 

Yes, we should do it. It has to be done diligently though, FileSystem is very commonly used API.
