### ISSUE TITLE
Extend Theia Extensions to support onWillExecute and onDidExecute listeners

### ISSUE THREAD

**Issue by joazvsoares** [eclipse-theia/theia#7270]
### Description

Would be great to have an interface to hook into commands from Theia extensions (e.g. onWillExecute and onDidExecute)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
@joazvsoares I thought we are talking about Theia extensions?

**Comment by joazvsoares** [comment]
> @joazvsoares I thought we are talking about Theia extensions? for plugin apis someone will need to send a PR after it is possible in Theia extensions

@akosyakov Awesome! We can start with Theia extensions, that would be already helpful, we can add support for Plugins later
