### ISSUE TITLE
search-in-workspace: does not respect 'files.exclude'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7273]
**Description**

The `search-in-workspace` search does not respect the `globs` presented in the `files.exlude` preference. The default preference consists of:

```json
"files.exclude": {
  "**/.git": true,
  "**/.svn": true,
  "**/.hg": true,
  "**/CVS": true,
  "**/.DS_Store": true
}
```

However, when searching, I can see results from the `.git` folder:

![image](https://user-images.githubusercontent.com/40359487/75892998-332fc100-5e00-11ea-8ce9-f36aaf8c3108.png)

Using the `Include Ignored Files` option has no effect as well.

**Comment by akosyakov** [comment]
@vince-fugnitto Does it in VS Code?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Does it in VS Code?

VS Code does respect the property but they have an additional preference to control the behavior, namely `search.exclude` which inherits values from `files.exclude`:

https://github.com/microsoft/vscode/blob/4c59cdd20dc90f9d6a9d4c2b11661f0a026672c1/src/vs/workbench/contrib/search/browser/search.contribution.ts#L649-L671

We should look to support such a preference as well.

**Comment by akosyakov** [comment]
ok, we should align it
