### ISSUE TITLE
Question: It's possible to add custom panel to theia debug extension?

### ISSUE THREAD

**Issue by eli88p** [eclipse-theia/theia#7279]
Hello,
There is some way to add panel to @theia/debug widget (like in my image)

Thanks in advance.
![Capture](https://user-images.githubusercontent.com/11608934/75960887-989bb480-5ec9-11ea-8405-9e70427df037.PNG)

**Comment by akosyakov** [comment]
Yes, you should be able to grab debug view container and call `addWidget` on it via custom Theia extension.
