### ISSUE TITLE
terminal: fix terminal theming

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7280]
**Description**

**terminal** theming from VS Code theming extensions does not work properly.
For example, the [vscode-builtin-theme-tomorrow-night-blue](https://github.com/microsoft/vscode/blob/583dc037dc55d8e70fc2f4ab9ddbbd7691e5b483/extensions/theme-tomorrow-night-blue/themes/tomorrow-night-blue-theme.json#L42-L57) theme contributes colors to the terminal:

```json
"terminal.ansiBlack": "#111111",
"terminal.ansiRed": "#ff9da4",
"terminal.ansiGreen": "#d1f1a9",
"terminal.ansiYellow": "#ffeead",
"terminal.ansiBlue": "#bbdaff",
"terminal.ansiMagenta": "#ebbbff",
"terminal.ansiCyan": "#99ffff",
"terminal.ansiWhite": "#cccccc",
"terminal.ansiBrightBlack": "#333333",
"terminal.ansiBrightRed": "#ff7882",
"terminal.ansiBrightGreen": "#b8f171",
"terminal.ansiBrightYellow": "#ffe580",
"terminal.ansiBrightBlue": "#80baff",
"terminal.ansiBrightMagenta": "#d778ff",
"terminal.ansiBrightCyan": "#78ffff",
"terminal.ansiBrightWhite": "#ffffff"
```

_Theia_

![image](https://user-images.githubusercontent.com/40359487/75984948-5ec2b200-5eb9-11ea-9d36-d3e3f86588e1.png)

_VS Code_

![image](https://user-images.githubusercontent.com/40359487/75984984-6eda9180-5eb9-11ea-884f-76114b0a177b.png)

**Comment by vince-fugnitto** [comment]
It looks like we have logic already to handle the foreground colors but they do not seem to be applied properly:

https://github.com/eclipse-theia/theia/blob/42b73d5a84f7335b722c7decad24d8069dfc3722/packages/terminal/src/browser/terminal-theme-service.ts#L25

**Comment by vince-fugnitto** [comment]
From the looks of it, we will need to convert colors from themes into valid `ansi` colors.

**Comment by akosyakov** [comment]
It should be already supported: https://github.com/eclipse-theia/theia/blob/357b8e9d4413bc5c566a7d4b751bb381b8fe5db8/packages/terminal/src/browser/terminal-theme-service.ts#L25

Maybe some regression.

**Comment by vince-fugnitto** [comment]
> Maybe some regression.

I thought it might have been caused by the xterm update (#7121) but it was not the case.
I verified with the commit c5569a44565dc073c9455df07d7da02e2106f723

**Comment by varmanishant** [comment]
One problem that I noticed is, we need to lower case the first letter after ansi to make it compatible with `xterm.js`. For example, `ansiBlack` should be added as `black` and not `Black` when it is supplied to `xterm.js`. Does that make sense? But we need to see if that is applicable to loading them from VS Code plugins.

**Comment by varmanishant** [comment]
Here is a simple correction that cab be applied [here](https://github.com/eclipse-theia/theia/blob/924e6a2f201cb3609b48903118d55762369222e2/packages/terminal/src/browser/terminal-theme-service.ts#L180-L182):

+            const colorKey = id.substring(13);
+            const colorName = colorKey.charAt(0).toLowerCase() + colorKey.substring(1);

to make it load correctly.
