### ISSUE TITLE
[search-in-workspace] Search finds different substrings of search term

### ISSUE THREAD

**Issue by corneliusludmann** [eclipse-theia/theia#7282]
### Description
When I type a search term in the search widget of Theia it starts the search on keystroke in the background. However, this leads to search result with different substrings of my current search term in the result list. E.g. I search for “ContainerMod” and the result list has results where “contai”, “contain”, and “container” are highlightend as search matches:

![image](https://user-images.githubusercontent.com/24960040/75987902-04454800-5ef1-11ea-826f-d13eaab7be4f.png)

As you can see, the same search result (the same line/word) is listed for each substring. 
- When I hit [Enter] the duplicated disappear.
- When I pause typing, wait for the results and add a character to the search term, the duplicates disappear.

There seems to be race condition / sync problem in creating the result list.

### Reproduction Steps
Type into the search box a search term and keep typing while the search is performed in the background. E.g. search for “ContainerModule”. Stop typing and wait for the result list. See the duplicates / substring matches.

I've seen it happen dozens of times. That means it is reproducible for me.

**OS and Theia version:**
- Theia version: 42b73d5a84f7335b722c7decad24d8069dfc3722
- OS: Arch Linux
- Browser: Google Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- I started a Theia instance from Gitpod (`yarn start`)

**Comment by vince-fugnitto** [comment]
Might it be a symptom of https://github.com/eclipse-theia/theia/issues/889? (and potentially slow networks speeds)
I was unable to successfully reproduce it from sources.

**Comment by corneliusludmann** [comment]
Maybe it really has something to do with network latencies. When I start Theia in a local Docker container I'm **not** able to reproduce this as well. Started in the cloud (here Gitpod) I have this almost always. Although I don't notice any other limitations in terms of internet speed.

**Comment by akosyakov** [comment]
I'm pretty sure there is a race :) Someone just needs to read the code carefully a part where we trigger search on typing and process results, something is not cancelled and previous results override latest.
