### ISSUE TITLE
comparing conflict markers does not work

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7297]
- Copy in any file:
```
<<<<<<< HEAD:file.txt
Hello world
=======
Goodbye
>>>>>>> 77976da35a11db4580b80ae27e8d65caf5208086:file.txt
```
- Press `Compare Changes` in code lenses.

It should open a diff editor, but fails with the error notification:
<img width="1904" alt="Screenshot 2020-03-09 at 10 18 56" src="https://user-images.githubusercontent.com/3082655/76199427-26d8a900-61f0-11ea-8d41-d5051ba0d061.png">

**Comment by vince-fugnitto** [comment]
The following has been fixed, likely thanks to https://github.com/eclipse-theia/theia/pull/9652.
