### ISSUE TITLE
[terminal] Pressing HOME no longer goes to beginning of line, but scrolls up

### ISSUE THREAD

**Issue by jankeromnes** [eclipse-theia/theia#7304]
### Description
There was an XtermJS upgrade recently, and I think that it broke the `HOME` shortcut in Theia's Terminal.

Here is a screencast showing the new problem: https://youtu.be/_auOJvi17Rs

### Reproduction Steps
1. Start typing some command into Theia's terminal
2. Press your `HOME` key (or corresponding key-stroke, e.g. `fn` + `LeftArrow` on a Macbook)

Expected: Cursor jumps to beginning of typed command

Actual: Terminal scrolls all the way to the top(!)

**OS and Theia version:** latest Theia (in Gitpod on Mac OS)

**Diagnostics:**

**Comment by akosyakov** [comment]
It's a regression after https://github.com/eclipse-theia/theia/pull/7121

**Comment by AndrienkoAleksandr** [comment]
I will take a look.

**Comment by AndrienkoAleksandr** [comment]
We should use `shift+Home' shortcut.

**Comment by akosyakov** [comment]
Resolved by https://github.com/eclipse-theia/theia/pull/7305

**Comment by jankeromnes** [comment]
Thanks again for fixing this @AndrienkoAleksandr!

I confirm that it now works well, but I also noticed a few weird behaviors FYI:

- <kbd>Home</kbd> works as expected 🎉 ❤️ 
- <kbd>End</kbd> too
- <kbd>Shift</kbd>+<kbd>Home</kbd> scrolls to top of Terminal, so works as expected too
- <kbd>Shift</kbd>+<kbd>End</kbd> just adds the letter `F` for some reason (keybinding not actually implemented in Theia, so this is probably Mac OS weirdness, and <kbd>End</kbd> already scrolls to bottom of Terminal)
- <kbd>PageUp</kbd> / <kbd>PageDown</kbd> don't work in Terminals, except in paginated output (`less` / `git log`) where it works well. I think this behavior was pre-existing, and is fine by me.
- <kbd>Shift</kbd>+<kbd>PageUp</kbd> / <kbd>Shift</kbd>+<kbd>PageDown</kbd> forcefully jumps one page up or down, even if you're looking at paginated content (i.e. the `less` "window" will scroll out of view). I guess that's ok.

**Comment by jankeromnes** [comment]
I also added two minor questions in https://github.com/eclipse-theia/theia/pull/7305#issuecomment-597054454, please take a look when you have time.

**Comment by akosyakov** [comment]
@jankeromnes it would be better to put weird behaviour in a new issue, closed issues are not actionable.
