### ISSUE TITLE
Unable to select a pulldown menu if the last file opened is in preview mode

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7306]
### Description
Unable to select a pulldown menu if the last file opened is in preview mode

### Reproduction Steps
- Open a workspace
- Open a file with a single click (Preview mode)
- Try to select the menu: File-> New file
--> Try any menu item, they will not open until you double-click on a file to have it in regular editor, not in preview mode, then you will be able to select a menu item

**OS and Theia version:**
OS: Ubuntu 18.04
Theia: latest master commit d5a60bb069bdb126dcdf0166bc69cca1014eb291
Web: Chrome

**Diagnostics:** 
![UnableSelectMenu](https://user-images.githubusercontent.com/419051/76307127-9c9b4e00-629e-11ea-8ce2-203872e25950.gif)

**Comment by vince-fugnitto** [comment]
Just to clarify, the bug happens for an `editor` opened as a `preview`.
The bug still occurs in `master` without `@theia/editor-preview` being included.

**Comment by akosyakov** [comment]
It sounds quite bad. Could it be cause by https://github.com/eclipse-theia/theia/pull/7276? @lmcbout @vince-fugnitto Could you check please?

**Comment by vince-fugnitto** [comment]
> It sounds quite bad. Could it be cause by #7276? @lmcbout @vince-fugnitto Could you check please?

I confirmed that prior to #7276 it worked correctly.

**Comment by akosyakov** [comment]
@vince-fugnitto Could you prepare a PR to revert it?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Could you prepare a PR to revert it?

I don't mind, but should we give @kittaakos some time to check if he can fix the regression first?

**Comment by akosyakov** [comment]
Ok, sounds good. I meant we can do it in parallel, if there is no a fix PR today/tomorrow we merge a revert PR for now.

**Comment by vince-fugnitto** [comment]
> Ok, sounds good. I meant we can do it in parallel, if there is no a fix PR today/tomorrow we merge a revert PR for now.

Tentative pull-request https://github.com/eclipse-theia/theia/pull/7307

**Comment by lmcbout** [comment]
I confirm as well , it works on the commit 842e717475697676c0f298e605b3674bea451ec9 which is the one just before
