### ISSUE TITLE
repo: rework dependency management

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#7312]
Theia extensions are NPM packages. We develop the most important ones inside a yarn monorepo, where everything is under our control. We started relying on hoisting and implicit dependencies, which might work well in our controlled setup, but it becomes very fragile once taken outside of the monorepo.

Some issues (click to expand):

<details>
<summary>We try to not break APIs, but our version ranges don't even target new versions.</summary>
<br />

`^0.16.0` only targets `0.16.x` packages, not `0.17.0` or up.
</details>

<details>
<summary>We define cross-extension dependencies as regular NPM's dependencies</summary>
<br/>

This can lead to duplication, but we cannot afford it because we play with global state and it breaks if we do it twice.

Example: `Symbol` instances, if the same script is triggered twice from different installation location, the references won't be compatible anymore.

Example: ad-hoc inversify decorators, we apply those at the script level, meaning that if two script try to do it in the same runtime it will fail.
</details>

<details>
<summary>We re-expose a lot of third-party APIs.</summary>
<br />

Example: `BackendApplicationContribution.onStart` takes an express application as first argument. This seems trivial, but it makes us expose types from express though `@theia/core`. This makes us put `@types/express` from `devDependencies` to `dependencies` because Theia being libraries, people would not be able to resolve express's typings without us bringing it along.

The issue is that this usually means that core will actually be developed around a specific version of express, and clients willing to contribute to it should also expect to handle this exact version.

If `@theia/core` uses express 4, clients shouldn't expect to use version 2 or version 5. **We may not advertise these constraints very well.**

Express is just one example, there's a lot of different packages that are like this (phosphorjs, react, among others).
</details>

<details>
<summary>We rely on implicit dependencies + hoisting, this is fragile.</summary>
<br />

While this works well inside the monorepo, this can easily break outside of it. This is a consequence of exposing lot of third-party APIs: we want everyone to use the same packages, but we don't want to declare it so. So we cross fingers and hope that our package manager will install node_modules in a way that pleases packages that don't even ask for a package as dependency, yet they require it.

I saw this fail with at least `electron-builder`, but any other tooling using manifest files as their source of truth can get the layout wrong, unless we explicitly declare dependencies.
</details>

<details>
<summary>No way to tell what extension to omit or not in a Theia application</summary>
<br />

This comes from the way we define cross-extension dependencies as regular deps. NPM will gladly pull what is missing, but it is really not clear what will automatically pulled or not. In most cases, we end up explicitly declaring what we want when writing an app's package.json because we don't know better, but we still end-up with extensions we did not expect because everything is implicit.
</details>

See https://classic.yarnpkg.com/blog/2018/04/18/dependencies-done-right/.

**A potential single step forward**

Peer dependencies would solve the "Theia extensions should be unique" issue, along with the "Theia extensions implicitly pull stuff" problem.

Since it is obscure what will be pulled or not, making extensions rely on each other via peer deps allow application makers to be explicitly told what is needed or not. It will also prevent any duplication from happening, at least regarding Theia packages.

App developers would be in direct control of what is installed.

I would rather have to write in some `theia-app.json` file all the extensions I want, and have tooling add all the required peer deps inside the app's package.json file. This way the implicit behavior can be kept, but we can also inspect what will be pulled because of the peer deps. And it makes more sense with NPM's semantics (which Yarn respects).

Peer dependencies can even be made optional, so that tooling doesn't complain when devs purposefully omit certain extensions! Then we can make runtime checks.

**Comment by marechal-p** [comment]
@akosyakov @svenefftinge

**Comment by akosyakov** [comment]
> ^0.16.0 only targets 0.16.x packages, not 0.17.0 or up.

It’s expected a product to explicitly upgrade for the major release and switching from 0.16 to 0.17 is a major according to the semver semantic, since next release a range will be 1.0.0 - 2.0.0.

Regarding everything else extensions resolution relies on yarn semantics of installing transitive dependencies. There are shortcomings with this but they are not crucial to break all downstream products.
