### ISSUE TITLE
[ux] Keybindings: numpad 7/1 (HOME/END) not working as expected (German layout)

### ISSUE THREAD

**Issue by geropl** [eclipse-theia/theia#7315]
### Description
When having the cursor in the middle of the line in a regular editor, the key 'numpad 7' (numpad disabled) should act like the `HOME` key and move the cursor to the beginning of that line. This does not work; instead the cursor seems to be untouched. The same goes for 'numpad 1' (`END`).

This (seems to have) appeared after https://github.com/eclipse-theia/theia/pull/6881 got merged.

Interesting detail:
When following this sequence:
 1. press 'numpad 7' (`HOME`) (numpad disabled)
 1. enable numpad
 1. press numpad 7 (`7`) repeatedly: the first `7` is inserted at the _beginning_ of the line while the cursor seems to _stay at it's original position_ in the middle of that line (see screencast). Further key presses insert `7`s at the current cursor position as expected...
![numpad](https://user-images.githubusercontent.com/32448529/76397886-31c04480-637c-11ea-81a8-662b8459e4f4.gif)

### Reproduction Steps
 - open a regular editor
 - move the cursor in the middle of a line
 - make sure numpad is disabled
 - press 'numpad 7', observe the not-moving cursor

**OS and Theia version:**
 - Linux Mint 19.1
 - Firefox 73.0.1 (64-bit) and Chrome 80.0.3987.87 (occurs in both)
 - German Keyboard layout

**Diagnostics:** 
@spoenemann told me how to analyze a bit further, here's the `event` from `@theia/core/src/browser/keybinding.ts`, line 592 (some fields omitted for brevity):
```
KeyboardEvent {isTrusted: true, key: "7", code: "Numpad7", location: 3, ctrlKey: false, …}
isTrusted: true
key: "7"
code: "Numpad7"
location: 3
ctrlKey: false
shiftKey: false
altKey: false
metaKey: false
repeat: false
isComposing: false
charCode: 0
keyCode: 103
detail: 0
which: 103
type: "keydown"
[...]
```
Also:
 - `bindings` (line 594) is an empty array
 - `full` (line 595) is `undefined`

**Comment by geropl** [comment]
I did investigated a bit more: It seems the `KeyEvent`s `Numpad7 w/o Numlock` and `Numpad7 with Numlock` are distinguishable by two properties:
 - key: `Home` / `7`
 - keyCode: `36` / `103`
(cmp. attached files)

It seems that in in [`keys.ts:toKey`](https://github.com/eclipse-theia/theia/blob/1ca3ec37c079a6b316278cf292609653e57b8151/packages/core/src/browser/keyboard/keys.ts#L347) we're trying to derive the `Key` from `event.code` first which is not distinct but succeeds (with wrong results).

IMO this problem would be solved by moving
```
const key = Key.getKey(code);
if (key) {
    return key;
}
```
below the `Key.getKey(keyCode)` lines - but I'm 100% unsure about unwanted side effects. :slightly_smiling_face: 

@spoenemann Does that make sense?
[7.txt (as reference)](https://github.com/eclipse-theia/theia/files/4318199/7.txt)
[Numpad7 (numpad disabled).txt](https://github.com/eclipse-theia/theia/files/4318200/Numpad7.numpad.disabled.txt)
[Numpad7 (numpad enabled).txt](https://github.com/eclipse-theia/theia/files/4318201/Numpad7.numpad.enabled.txt)

**Comment by akosyakov** [comment]
@spoenemann probably you are the best to look at it

**Comment by spoenemann** [comment]
> IMO this problem would be solved by moving `...` below the `Key.getKey(keyCode)` lines - but I'm 100% unsure about unwanted side effects.

We cannot do this in general: https://github.com/eclipse-theia/theia/issues/7137#issuecomment-585617300

But I think it would be feasible to add an exception for numpad keys: If `code` starts with `Numpad`, then check `keyCode` first.

@geropl could you try whether that fixes your problem?

**Comment by geropl** [comment]
> We cannot do this in general: #7137 (comment)

Ah, that makes sense, thanks.

> @geropl could you try whether that fixes your problem?

@spoenemann Yes, will give it a try.

**Comment by spoenemann** [comment]
> But what about the key property? (In this case HOME) Is that also subject to differences between layouts?

We use `key` only to get the actual character that was typed.
