### ISSUE TITLE
preferences: the command 'open settings' should support a 'query' 

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7328]
**Description**

The command to open the **preferences widget** should accept a `query` parameter for which plugins can trigger. This change will likely be acceptable once #7105 is completed (since it introduces a search).

**Additional Information**
- [original comment](https://github.com/eclipse-theia/theia/pull/7320#issuecomment-598174439)
- [preferences pull-request](https://github.com/eclipse-theia/theia/pull/7105)

**Comment by vince-fugnitto** [comment]
It should now be possible to support the feature as the new preferences user-interface has been merged and includes a search.

**Comment by colin-grant-work** [comment]
> The command to open the **preferences widget** should accept a `query` parameter for which plugins can trigger.

Could you clarify what you mean by 'for which plugins can trigger'? Do you mean a parameter than can be used by plugins when they trigger some action, or some indication of which plugins contribute preferences, or which plugins are affected by particular preferences? Or something else?

**Comment by vince-fugnitto** [comment]
> Could you clarify what you mean by 'for which plugins can trigger'? Do you mean a parameter than can be used by plugins when they trigger some action, or some indication of which plugins contribute preferences, or which plugins are affected by particular preferences? Or something else?

Sure, the idea is that we should support passing a `query` argument to our `open preferences` command which will ultimately be used to pre-populate the search upon opening the preferences-view:

https://github.com/eclipse-theia/theia/blob/f97ec33eea89b9f5efae2860920bc3bd569c9477/packages/preferences/src/browser/preference-contribution.ts#L75-L77

From the plugin side, extensions are able to call the method and pass the query as well.
For example, in my custom [vscode-open-settings](https://github.com/vince-fugnitto/settings-open) extension, I describe how extension developers have the flexibility to call the `open settings` along with passing a parameter:

```ts
vscode.commands.executeCommand('workbench.action.openSettings', 'font size');
```

I included a [`.vsix`](https://github.com/vince-fugnitto/settings-open/releases/download/2.0.0/settings-open-0.0.1.vsix) for you to try if you'd like:
- `Ext: Open Settings`: triggers opening the preferences-view
- `Ext: Open Settings With Query`: triggers opening the preferences-view with the search pre-populated.
