### ISSUE TITLE
VSCodeAPI  'showInformationMessage' do not support newlines. (\n)

### ISSUE THREAD

**Issue by raphaelsantos** [eclipse-theia/theia#7332]
### Description

It should be possible for users to call `showInformationMessage` (VS Code API) with newlines included (`\n`). The following does not work for notification messages, but does work when passing [MessageOption](https://code.visualstudio.com/api/references/vscode-api#MessageOptions) `modal` as `true`.

### Reproduction Steps

1. create a simple vscode extension which calls `showInformationMessage` passing `modal: true` and include newlines in the message.

  Ex:

```ts
vscode.commands.registerCommand('extension.showModalMessage', () => {
  vscode.window.showInformationMessage('Hello World!\nHello World!\nHello World!', { modal: true });
})
```

**OS and Theia version:**

10.14.6
0.12.0

**Comment by vince-fugnitto** [comment]
@raphaelsantos are you certain it is supported in vscode?
I performed the following call in my extension, and the result was without newlines:

```ts
vscode.window.showInformationMessage('t\ne\ns\nt');
```

<img width="476" alt="Screen Shot 2020-03-12 at 6 04 15 PM" src="https://user-images.githubusercontent.com/40359487/76570555-f01ebf00-648b-11ea-9cf2-c8b5a4dd8447.png">

Also, looking at their source code and  past discussions, it looks like newlines aren't supported:
- [vscode code](https://github.com/Microsoft/vscode/blob/5651fa0a8a482ba8427797ba2c053b1943ff15fb/src/vs/workbench/common/notifications.ts#L492-L493)
- https://github.com/eclipse-theia/theia/issues/7283#issuecomment-595629862

**Comment by vince-fugnitto** [comment]
@raphaelsantos can you provide an example of a `showInformationMessage` extension which works in VS Code and not Theia?

**Comment by vince-fugnitto** [comment]
> @raphaelsantos can you provide an example of a `showInformationMessage` extension which works in VS Code and not Theia?

**Comment by raphaelsantos** [comment]
Hi @vince-fugnitto , I'm really sorry for taking all this time to answer.

Entering newline with `\n` actually works when using `showInformationMessage` with `MessageOptions` `{userModal:true}`.

**Comment by vince-fugnitto** [comment]
> Hi @vince-fugnitto , I'm really sorry for taking all this time to answer.
> 
> Entering newline with `\n` actually works when calling `showInformationMessage` with `MessageOptions` `{modal:true}` on VSCode, but does not work on Theia.

No problem, thanks for getting back!
I confirmed it works for the modal dialog, I'll update the issue description to reflect that.
