### ISSUE TITLE
Failed to resolve modules

### ISSUE THREAD

**Issue by cenkce** [eclipse-theia/theia#7334]
### Description
I receive errors while yarn runs in the Theia's root with our ide extension. It's causing yarn.lock file created after `che:theia init` runs. When I delete the yarn.lock file, it successfully builds.

@theia/example-browser: Failed to resolve module: @primer/octicons-react
@theia/example-browser: Failed to resolve module: react-virtualized
@theia/example-electron: Failed to resolve module: @primer/octicons-react
@theia/example-electron: Failed to resolve module: react-virtualized

Any suggestions ?
### Reproduction Steps

**OS and Theia version:**
7.8.0 - 7.9.1
**Diagnostics:**

**Comment by akosyakov** [comment]
@cenkce please ask Che related question on https://github.com/eclipse/che-theia
