### ISSUE TITLE
Pods are getting evicted!! After every new image i pushed to ECR and update the same in devregistry yaml files. Che core pods will fail

### ISSUE THREAD

**Issue by Shashi0838** [eclipse-theia/theia#7337]
### Description
I'm observing from past months. after every new build of che editor or che plugin images i upload.

Che, plugin registry etc mostly all pods will get evicted. and it won't settle back in one go there will be multiple pods will create and evicts.

I did set up in AWS EKS and Using ECR for images.

Here is the list of pods from che:
ubuntu@myserver:~$ kubectl get pods -n che
NAME                                                           READY   STATUS      RESTARTS   AGE
che-7cf575fb8d-2gqbk                                           0/1     Evicted     0          9h
che-7cf575fb8d-2hnkw                                           0/1     Evicted     0          10h
che-7cf575fb8d-2kxcs                                           0/1     Evicted     0          21h
che-7cf575fb8d-2n5dl                                           0/1     Evicted     0          9h
che-7cf575fb8d-2n65p                                           0/1     Evicted     0          7h44m
che-7cf575fb8d-2sk5f                                           0/1     Evicted     0          8h
che-7cf575fb8d-2wpd8                                           0/1     Evicted     0          9h
che-7cf575fb8d-4z75q                                           0/1     Evicted     0          8h
che-7cf575fb8d-55vhb                                           0/1     Evicted     0          9h
che-7cf575fb8d-64trp                                           0/1     Evicted     0          8h
che-7cf575fb8d-7c5bm                                           0/1     Evicted     0          9h
che-7cf575fb8d-7mk6v                                           0/1     Evicted     0          8h
che-7cf575fb8d-7qbrc                                           0/1     Evicted     0          9h
che-7cf575fb8d-7rkqq                                           0/1     Evicted     0          8h
che-7cf575fb8d-8l7qh                                           0/1     Evicted     0          7h56m
che-7cf575fb8d-8nh4g                                           0/1     Evicted     0          9h
che-7cf575fb8d-8sqmm                                           0/1     Evicted     0          9h
che-7cf575fb8d-96m2v                                           0/1     Evicted     0          10h
che-7cf575fb8d-97jkd                                           0/1     Evicted     0          9h
che-7cf575fb8d-9m4lp                                           0/1     Evicted     0          20h
che-7cf575fb8d-9m7t9                                           0/1     Evicted     0          9h
che-7cf575fb8d-9mftt                                           0/1     Evicted     0          7h
che-7cf575fb8d-b7qf6                                           0/1     Evicted     0          7h9m
che-7cf575fb8d-cfnfl                                           0/1     Evicted     0          10h
che-7cf575fb8d-ckhtz                                           0/1     Evicted     0          8h
che-7cf575fb8d-ckmd7                                           0/1     Evicted     0          8h
che-7cf575fb8d-cvczs                                           0/1     Evicted     0          8h
che-7cf575fb8d-d9srh                                           1/1     Running     0          26m
che-7cf575fb8d-dkvzn                                           0/1     Evicted     0          9h
che-7cf575fb8d-dlmp8                                           0/1     Evicted     0          8h
che-7cf575fb8d-f7bgj                                           0/1     Evicted     0          21h
che-7cf575fb8d-fzw4f                                           0/1     Evicted     0          8h
che-7cf575fb8d-ghzp4                                           0/1     Evicted     0          7h44m
che-7cf575fb8d-h52jf                                           0/1     Evicted     0          10h
che-7cf575fb8d-hlmnq                                           0/1     Evicted     0          10h
che-7cf575fb8d-k9vgv                                           0/1     Evicted     0          9h
che-7cf575fb8d-l69st                                           0/1     Evicted     0          8h
che-7cf575fb8d-lcgng                                           0/1     Evicted     0          8h
che-7cf575fb8d-lflv8                                           0/1     Evicted     0          8h
che-7cf575fb8d-lnv7m                                           0/1     Evicted     0          7h31m
che-7cf575fb8d-lt5pm                                           0/1     Evicted     0          7h44m
che-7cf575fb8d-lxm5g                                           0/1     Evicted     0          7h57m
che-7cf575fb8d-m2t7f                                           0/1     Evicted     0          10h
che-7cf575fb8d-mdk6b                                           0/1     Evicted     0          9h
che-7cf575fb8d-n7hpx                                           0/1     Evicted     0          7h44m
che-7cf575fb8d-ntzh2                                           0/1     Evicted     0          10h
che-7cf575fb8d-nz4hn                                           0/1     Evicted     0          8h
che-7cf575fb8d-pc27t                                           0/1     Evicted     0          10h
che-7cf575fb8d-pp8fm                                           0/1     Evicted     0          10h
che-7cf575fb8d-qjwbg                                           0/1     Evicted     0          9h
che-7cf575fb8d-rhvrn                                           0/1     Evicted     0          9h
che-7cf575fb8d-s7kvx                                           0/1     Evicted     0          10h
che-7cf575fb8d-tsh6c                                           0/1     Evicted     0          8h
che-7cf575fb8d-tssp9                                           0/1     Evicted     0          7h44m
che-7cf575fb8d-vj7nk                                           0/1     Evicted     0          7h44m
che-7cf575fb8d-vjjkp                                           0/1     Evicted     0          7h44m
che-7cf575fb8d-wqtkt                                           0/1     Evicted     0          8h
che-7cf575fb8d-x2jxz                                           0/1     Evicted     0          9h
che-7cf575fb8d-x72lp                                           0/1     Evicted     0          7h44m
che-7cf575fb8d-z5zw5                                           0/1     Evicted     0          10h
che-7cf575fb8d-zzngm                                           0/1     Evicted     0          9h
devfile-registry-6556945bd5-bffkh                              0/1     Evicted     0          21h
devfile-registry-6556945bd5-t8q4m                              0/1     Evicted     0          10h
devfile-registry-6556945bd5-zpl4k                              1/1     Running     0          12m
keycloak-55455bc47-2ntvq                                       0/1     Evicted     0          9h
keycloak-55455bc47-4wfwj                                       0/1     Evicted     0          6h59m
keycloak-55455bc47-5hstv                                       0/1     Evicted     0          21h
keycloak-55455bc47-6b4sn                                       0/1     Evicted     0          9h
keycloak-55455bc47-75wlq                                       0/1     Evicted     0          7h30m
keycloak-55455bc47-p7g78                                       0/1     Evicted     0          8h
keycloak-55455bc47-slqjg                                       1/1     Running     0          6h14m
keycloak-55455bc47-t2mns                                       0/1     Evicted     0          9h
keycloak-55455bc47-x72s7                                       0/1     Evicted     0          10h
mkdir-workspacekr9i9ft353512gjl                                0/1     Completed   0          10h
plugin-registry-7db794b8f7-mtc9x                               1/1     Running     0          10h
plugin-registry-7db794b8f7-ws9h8                               0/1     Evicted     0          21h
postgres-786d8bb9d5-99lg6                                      1/1     Running     0          21h
workspacelh3l9sekic7035ap.che-plugin-broker                    0/1     Evicted     0          10h
workspacep9kk8erbjzzowucv.che-jwtproxy-6f57595485-wn2gd        1/1     Running     0          34m
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-7r6xq    0/2     Evicted     0          91s
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-cmw9j    0/2     Evicted     0          93s
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-cw6p8    0/2     Evicted     0          96s
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-dccjw    0/2     Evicted     0          98s
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-dgmg5    0/2     Evicted     0          98s
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-k5pj9    0/2     Evicted     0          13m
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-m2h8l    0/2     Evicted     0          92s
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-pl5zw    0/2     Evicted     0          98s
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-qgpcx    0/2     Evicted     0          34m
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-sf4p6    0/2     Pending     0          90s
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-trjbb    0/2     Evicted     0          25m
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-vg5zk    0/2     Evicted     0          95s
workspacep9kk8erbjzzowucv.che-workspace-pod-6fc796c48-xng2b    0/2     Evicted     0          97s
workspacex2imyqum4a2d9krr.che-jwtproxy-54bdfc456c-vh9jg        1/1     Running     0          10h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-269hq   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-2gvfx   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-2zj44   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-4n2qf   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-5g9vq   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-5x4th   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-6lr28   0/2     Evicted     0          7m21s
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-6mtfj   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-6px5f   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-6x2hx   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-7dfhw   0/2     Evicted     0          7h31m
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-968zw   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-9lkgk   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-bjsx4   0/2     Evicted     0          7m22s
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-cbbnl   0/2     Error       0          7h43m
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-cbxmc   2/2     Failed      2          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-ckzd6   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-cs92p   0/2     Error       0          10h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-cwmpp   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-d25nv   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-dds8c   0/2     Evicted     0          26m
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-dj4zm   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-dmh6d   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-f25g7   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-fm2cc   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-fwlzv   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-g2cpt   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-g9frc   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-gwlxk   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-h6xvt   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-hfpgr   0/2     Evicted     0          10h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-hg6w2   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-hlmf7   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-hlvdj   0/2     Evicted     0          7m21s
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-hmmrl   0/2     Evicted     0          7h21m
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-hx8vm   0/2     Evicted     0          7m21s
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-kqgpl   0/2     Evicted     0          7h56m
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-lffwl   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-mrqpm   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-mzpph   0/2     Evicted     0          7m21s
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-p6jx7   2/2     Failed      2          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-pchd8   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-qgjw6   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-r4mdt   0/2     Evicted     0          7m21s
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-r54lx   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-rdfjb   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-rznx4   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-s64j9   0/2     Evicted     0          7m21s
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-s8m8d   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-sph74   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-szjgf   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-t48m2   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-tfg6q   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-tmzvs   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-tndt8   2/2     Running     0          7m20s
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-tvvtl   0/2     Evicted     0          10h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-wnp98   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-xkt45   0/2     Evicted     0          8h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-xt9bv   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-z4f2k   0/2     Evicted     0          9h
workspacex2imyqum4a2d9krr.che-workspace-pod-7fcbd9c579-zx4ss   0/2     Evicted     0          8h

Can someone help me with this?

**Comment by akosyakov** [comment]
Please open Che issue for Che: https://github.com/eclipse/che-theia
