### ISSUE TITLE
[SIW] The search should not run when `input` does not change

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7346]
### Description
 
We run the SIW each time the "selection"? changes in the SIW `input`. It's a bug.
![screencast 2020-03-16 09-19-37](https://user-images.githubusercontent.com/1405703/76736622-762a5680-6767-11ea-812a-bf1f39c84b2c.gif)

### Reproduction Steps

Write something into the SIW `input` change the cursor location, try to `Select All` (if you are not in electron).

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
yes, it is a bug there is also a race because of it: https://github.com/eclipse-theia/theia/blob/9457f8087bb421b7aa1c6cf124c6dfe57659df5f/packages/core/src/browser/style/index.css#L58

**Comment by akosyakov** [comment]
We should debounce and use cancellation token.

**Comment by kittaakos** [comment]
> We should debounce and use cancellation token

Or we could not run the query when the input does not change. Can we do that instead of debouncing and cancellation?

**Comment by akosyakov** [comment]
> Or we could not run the query when the input does not change. Can we do that instead of debouncing and cancellation?

true, we should not trigger search at all

**Comment by akosyakov** [comment]
What btw should happen if there are new files? Does search automatically adjust or one has to press enter to rerun. In this case disabling rerunning will break.

**Comment by kittaakos** [comment]
> What btw should happen if there are new files?

We have to do what VS Code does; it does not update the search results on new file creation. Which is what I would expect as a user.

**Comment by vince-fugnitto** [comment]
I'll close the pre-existing issue in favor of this one since it has additional discussions:
- https://github.com/eclipse-theia/theia/issues/7271

**Comment by akosyakov** [comment]
> We have to do what VS Code does; it does not update the search results on new file creation. Which is what I would expect as a user.

But I see that VS Code runs search again if I press enter.

**Comment by kittaakos** [comment]
> But I see that VS Code runs search again if I press enter and then it finds new results.

I didn't say it does not re-run the query when you hit enter, I said:

> it does not update the search results on new file creation. Which is what I would expect as a user.

I meant automatically.
