### ISSUE TITLE
[quality] Removed the obsolete Quit command 

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7370]
### Description
 

It's unused. Left from here: https://github.com/eclipse-theia/theia/issues/1331#issue-298864179

https://github.com/eclipse-theia/theia/blob/5fb75c73bea6fc54563c4b969551c3f3cd8c8d62/packages/core/src/browser/common-frontend-contribution.ts#L210-L213

We had this for escaping some keybindings, but it did not work and is legacy now.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by anir1ghosh** [comment]
Hi! I can take this up, if no one else is working on this already.

**Comment by kittaakos** [comment]
@anir1ghosh, please go ahead. It's yours. Let us know if you need help.
