### ISSUE TITLE
outputChannel.show() no longer reveals output channel

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#7383]
### Description
`outputChannel.show()` no longer works. I believe this is a regression (see Theia versions below).

The output channel is created, but the Output view is not opened, and the channel is not brought to the front of the Output view. This means that calling `show` on an existing output channel has no effect.

### Reproduction Steps

I've created a repository with a plugin (source and vsix) that you can reproduce with: https://github.com/tetchel/theia-output-show-bug

**OS and Theia version:** 
I see the issue in Theia 0.15, 0.16, 0.16.1, and `master` branch.
I do NOT see the issue in theia 0.14, it works as expected.

**Diagnostics:** 

I see this in the logs:
`root WARN Widget was activated, but did not accept focus after 2000ms: outputView`

**Comment by akosyakov** [comment]
@tetchel Could you check against https://github.com/eclipse-theia/theia/pull/7570 please? The output view was completely reimplemented for better performance and user interactions.

**Comment by tetchel** [comment]
It is fixed
