### ISSUE TITLE
"applyTo" property in taskConfig.problemMatcher doesn't work properly

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#7396]
### Description

`applyTo` is a property that controls if a problem reported on a text document is applied only to open, closed or all documents. It is not working in Theia.

### Reproduction Steps

1. As the GIF shows, open a workspace and define a task that produces problem markers. In my workspace, I had 

```
        "type": "npm",
        "script": "lintAAB",
        "problemMatcher": [
            {
                "owner": "eslint97",
                "source": "eslint97",
                "applyTo": "openDocuments",
                "fileLocation": "absolute",
                "pattern": [
                {
                    "regexp": "^([^\\s].*)$",
                    "kind": "location",
                    "file": 1
                },
                {
                    "regexp": "^\\s+(\\d+):(\\d+)\\s+(error|warning|info)\\s+(.+?)(?:\\s\\s+(.*))?$",
                    "line": 1,
                    "column": 2,
                    "severity": 3,
                    "message": 4,
                    "code": 5,
                    "loop": true
                }
                ]
          }
        ]
    }
```
in the task config, and 
```
  "scripts": {
    "lintAAB": "eslint ."
  },
```
in my package.json

2. Run the task. The lint warnings / errors that are found by the task all show up in the problems view, which is WRONG, because `applyTo` is set "openDocuments", while the markers displayed in the problems view are found from not-opened files.

![Peek 2020-03-22 22-31](https://user-images.githubusercontent.com/37082801/77275049-b0c35000-6c8d-11ea-84c0-643b27e10c96.gif)

**OS and Theia version:**

Ubuntu 18.04. Chrome, example browser.
version ae5591edb22b06f890b090e5c4eb36ddeed05122

**Comment by elaihau** [comment]
@akosyakov 

To tell which files are opened which are not, the way that I can think of, is to iterate through all editor widgets to check the URI. 

dumb question: is there an easier way to achieve this? Thank you !

**Comment by akosyakov** [comment]
@elaihau First of all, documents are not editors. There can be multiple widgets for the same document, i.e. you can open a code editor and diff editor using the same documnet. You can access all open documents via [MonacoWorkspace.textDocuments](https://github.com/eclipse-theia/theia/blob/9d59a4e0c51712cb260d29d98061dec0c5f5884c/packages/monaco/src/browser/monaco-workspace.ts#L248-L250).  There is also a method to get a document for URI already: `MonacoWorkspace.getTextDocument`.
