### ISSUE TITLE
[ci] Publishing empty `next` packages

### ISSUE THREAD

**Issue by cdietrich** [eclipse-theia/theia#7403]
### Description
the steps in the documentation do not work

### Reproduction Steps
create package.json
```
{
  "private": true,
  "dependencies": {
    "@theia/callhierarchy": "next",
    "@theia/file-search": "next",
    "@theia/git": "next",
    "@theia/json": "next",
    "@theia/markers": "next",
    "@theia/messages": "next",
    "@theia/mini-browser": "next",
    "@theia/navigator": "next",
    "@theia/outline-view": "next",
    "@theia/plugin-ext-vscode": "next",
    "@theia/preferences": "next",
    "@theia/preview": "next",
    "@theia/search-in-workspace": "next",
    "@theia/terminal": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
```
run
```
yarn
yarn theia build
```

fails with

```
cdietrich:~/git/my-app > yarn
cdietrich:~/git/my-app > yarn theia build
yarn run v1.22.4
$ /Users/cdietrich/git/my-app/node_modules/.bin/theia build
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../lib/theia'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/cdietrich/git/my-app/node_modules/@theia/cli/bin/theia:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1
```
(tested on both mac and linux mint)

**Comment by vince-fugnitto** [comment]
@cdietrich which documentation are you referring to?

**Comment by akosyakov** [comment]
Maybe related to newer version of yarn?

**Comment by cdietrich** [comment]
https://theia-ide.org/docs/composing_applications/

**Comment by cdietrich** [comment]
```
yarn --version
1.22.4
```

```
node --version
v10.19.0
```

```
nvm --version
0.33.11
```

**Comment by vince-fugnitto** [comment]
> Maybe related to newer version of yarn? Which nvm, yarn, node?

I verified and can reproduce the error, it is a problem when using `next` but not `latest`.
I'm wondering if we have a pretty serious regression.

**Comment by marechal-p** [comment]
The most recent `next` release is missing the `lib` folder for some reason. Most other `next` tags before that look ok.

**Comment by marcdumais-work** [comment]
It looks like a problem during the publishing phase of CI: https://travis-ci.com/github/eclipse-theia/theia/jobs/301333835#L504 :`

```
Error: GET https://github.com/electron/electron/releases/download/v4.2.12/SHASUMS256.txt returned 429
```
(HTTP 429: "The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting").")

There is this early failure, apparently being denied access to the Electron checksum file on GitHub, that goes un-noticed. The build stops there, causing the extensions we publish to npm to be empty.

**Comment by marcdumais-work** [comment]
Not sure if a recent change in our repo might be hammering GitHub more than previously, causing this issue or something else. The Travis executors are shared among many projects, so it would not necessarily be our project causing this, but it's happened twice now - earlier today and again with a more recent merge on master.

**Comment by marcdumais-work** [comment]
I cleared the Travis cache and restarted the publish of the lastest commit. It looks to be pass the failure point. I do not think npm will let us re-publish the same packages, but next commit we merge will hopefully work like normal.

**Comment by akosyakov** [comment]
@marcdumais-work It did not help. I've just tried to upgrade Gitpod and there is no lib folders at all.

**Comment by akosyakov** [comment]
please try again, it should be good now

**Comment by marcdumais-work** [comment]
> please try again, it should be good now

Confirmed.

**Comment by cdietrich** [comment]
works for me now, too
