### ISSUE TITLE
[monaco][quick-open] Clarification on QuickOpenItemOptions.labelHighlights

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7419]
### Description
 

I want to run my own fuzzy search with the quick open service. So I decided to **not**  set `fuzzyMatchLabel: true`. Instead, I get back matches from the search engine and I convert them to an array of `Highlight`.

I have multiple match regions:

![Screen Shot 2020-03-25 at 15 15 53](https://user-images.githubusercontent.com/1405703/77546443-2c9ae380-6eac-11ea-80d7-2ffc045eaf82.jpg)

On the UI I can see only one matching region, the last one.
![Screen Shot 2020-03-25 at 15 16 05](https://user-images.githubusercontent.com/1405703/77546563-56540a80-6eac-11ea-9975-55893a018dee.jpg)

Can someone please clarify the `Highlight` interface?
```ts
export interface Highlight {
    start: number
    end: number
}
```

I bet, monaco has different semantics and if `start===end` it does not mean 1 length long region, but no match.
Also, does index start with 1 or 0? (It's monaco)

Thanks you!

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
Monaco is 1-based. 

> I bet, monaco has different semantics and if start===end it does not mean 1 length long region, but no match.

I think you are right. It makes sense, like for other string apis, i.e end is not included.

**Comment by akosyakov** [comment]
Implementation: https://github.com/microsoft/vscode/blob/17d6b13a35344ba36a4aad6d7dbbc77359f137b3/src/vs/base/browser/ui/highlightedlabel/highlightedLabel.ts#L63

**Comment by kittaakos** [comment]
> Implementation:

Thank you! 👍

**Comment by akosyakov** [comment]
@kittaakos for the quick pick they seem to use 0-based though: https://github.com/microsoft/vscode/blob/17d6b13a35344ba36a4aad6d7dbbc77359f137b3/src/vs/base/browser/ui/highlightedlabel/highlightedLabel.ts#L60

**Comment by kittaakos** [comment]
> for the quick pick they seem to use 0-based though:

I cam confirm it 😄

**Comment by akosyakov** [comment]
I always wonder why someone came up with such idea to use 1-based column and line number, although underlying strings are always 0 based 🙈
