### ISSUE TITLE
It should be possible to provide options to ReactWidget.

### ISSUE THREAD

**Issue by jbicker** [eclipse-theia/theia#7420]
### Description
It is currently not possible to provide widget options to ReactWidget. This should be possible.

### Reproduction Steps
Extend ReactWidget and try to provide options to super class.
https://github.com/eclipse-theia/theia/blob/cc9453d3a01644f371e9e94134b93ff65e1e4112/packages/core/src/browser/widgets/react-widget.tsx#L29

**Comment by akosyakov** [comment]
The motivation here is ability to provide custom html node without dealing with embedded widgets, i.e. something like:
```
super({
   node: document.createElement('div').appendChild(document.createElement('div'))
});
this.node.id = 'child-node'; // this is node which is used for react rendering
(this.node.parentNode as HTMLElement).id = 'parent-node'; // this first div, now we can mutate it without being afraid that react will wipe out manually added content
```
