### ISSUE TITLE
Codicons are not rendered when filtering in quick pick

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#7429]
### Description
We are getting `codicons` support within Monaco upgrade to 0.19.3: https://github.com/eclipse-theia/theia/pull/7149
`codicon`s are rendered correctly for the most use cases.

To face with the bug a few conditions should be met:
- quick pick
- filtering
- `codicon` variable contains filtering word 

So you never face with the bug if you filter `branch` or `create` and a `codicon` is `$(plus)`.

I can see the same behavior for Monaco Playground:
![mon_playg](https://user-images.githubusercontent.com/5676062/77661381-3d6a5880-6f83-11ea-9248-e2f46e307788.gif)

### Reproduction Steps
I can reproduce it using git VS Code extension:
- turned off `@theia/git` [here](https://github.com/eclipse-theia/theia/blob/715cda98a8561caf5b3105d63533489dc2ee4ee5/examples/browser/package.json#L27) 
- add  `vscode-git-1.3.0.1.vsix` into the `plugins` folder.
- use `Git: Checkout to` command
- try to filter by `plus` word

I understand that it's bad example, but it's good for testing goals.
I think all extensions with `codicons` will be affected and the better example if you have item with `$(link) Open Link` label and word for filtering is `link`. 

![git_checkout](https://user-images.githubusercontent.com/5676062/77650554-5586ab80-6f74-11ea-87ed-ac45af343328.gif)

**Comment by vince-fugnitto** [comment]
I believe the issue is resolved, please re-open if it is not the case:

https://user-images.githubusercontent.com/40359487/140994295-42d8489d-3bfe-4a96-9bd9-7b7621a1b04f.mp4
