### ISSUE TITLE
vsx: update extension information in the extension-editor

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7434]
**Description**

There are some key differences between our extension headers, and that of vscode, namely:
- ~we include a `globe` icon (not sure as to what the reason might be - perhaps global install?)~
- the alignment of items in the header are different than vscode (harder to read, inconsistent)
- ~we omit data, for example the `license` field (brackets has a license in [open-vsx](https://open-vsx.org/extension/CoenraadS/bracket-pair-colorizer) but none is shown in the editor)~: #7381
- font-weight of action items are inconsistent

_Theia_

<div align='center'>

<img width="497" alt="Screen Shot 2020-03-27 at 10 50 14 AM" src="https://user-images.githubusercontent.com/40359487/77768877-7d7c1a80-7019-11ea-8f6a-a326669a4052.png">

</div>

_VS Code_

<div align='center'>

<img width="525" alt="Screen Shot 2020-03-27 at 10 56 15 AM" src="https://user-images.githubusercontent.com/40359487/77768964-9ab0e900-7019-11ea-82ed-4e592c5e5abe.png">

</div>

**Comment by vince-fugnitto** [comment]
@kaiyue0329 would you like to address the issue?

**Comment by vince-fugnitto** [comment]
The license bug might be related to:
- https://github.com/eclipse-theia/theia/issues/7381

**Comment by akosyakov** [comment]
> we include a globe icon (not sure as to what the reason might be - perhaps global install?)

global means that namespace is not claimed and anyone can publish, please read tooltip on hover

**Comment by akosyakov** [comment]
> we omit data, for example the license field (brackets has a license in open-vsx but none is shown in the editor)

Because of https://github.com/eclipse-theia/theia/issues/7381?

**Comment by vince-fugnitto** [comment]
> > we include a globe icon (not sure as to what the reason might be - perhaps global install?)
> 
> global means that namespace is not claimed and anyone can publish, please read tooltip on hover

I was wondering it it made sense for end-users to see this info?
I understand it is present in the `open-vsx`, but is it useful for end-users?

**Comment by vince-fugnitto** [comment]
> > we omit data, for example the license field (brackets has a license in open-vsx but none is shown in the editor)
> 
> Because of #7381?

Right, I mentioned it https://github.com/eclipse-theia/theia/issues/7434#issuecomment-605048757

**Comment by akosyakov** [comment]
> I understand it is present in the open-vsx, but is it useful for end-users?

Yes, it is important that one who instals was aware that an extension is not published by verified author but by some person on the internet.

**Comment by vince-fugnitto** [comment]
> > I understand it is present in the open-vsx, but is it useful for end-users?
> 
> Yes, it is important that one who instals was aware that an extension is not published by verified author but by some person on the internet.

Thank you for clarifying for me :)
