### ISSUE TITLE
markers: better sync between editor and problems-view

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7436]
**Description**

At the moment, there is no sync between the active editor and the `problems-view` meaning that problems are not revealed in the tree based on the editor.

There are two main use-cases not handled:
- switching/opening an editor does not reveal it's markers in the problems-view
- if markers are collapsed in the problems-view, the active editor's node is not expanded

Both use-cases are successfully handled by vscode:

_Expanding_

<div align='center'>

![expand](https://user-images.githubusercontent.com/40359487/77775952-a9040280-7023-11ea-8909-f470593031c7.gif)

</div>

**Comment by Anasshahidd21** [comment]
In order to sync the markers with the `activeEditor`. We will need to couple the `Editor` with `Markers`, imo. Is there any other way/suggestion for fixing this issue without coupling the two?

**Comment by akosyakov** [comment]
You can rely on `NavigatableWidget`. `EditorWidget` implements it.

**Comment by akosyakov** [comment]
@vince-fugnitto Are there any preferences to control it?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Are there any preferences to control it?

Yes, it looks like the following preference in vscode controls it (`problems.autoReveal`):

<img width="497" alt="Screen Shot 2020-04-09 at 10 54 16 AM" src="https://user-images.githubusercontent.com/40359487/78908783-9ab8dc00-7a50-11ea-88c9-3bffceacadfb.png">
