### ISSUE TITLE
Refactor the task terminal opener option

### ISSUE THREAD

**Issue by elaihau** [eclipse-theia/theia#7438]
### Description

This issue was brought up by @akosyakov in https://github.com/eclipse-theia/theia/pull/7260#discussion_r396985825

As this code snippet shows 

https://github.com/eclipse-theia/theia/blob/3cf2837ca278671d4f49c8d6c1d10bb02a87910a/packages/task/src/browser/task-service.ts#L998-L1008

The opener option for task terminals (and potentially all terminals in general) contains identity properties, such as `widgetOptions`, `mode`, `taskConfig`. Those properties are stored in local stoage when the workspace / browser is closed. 

Since local storage has limited space, we should refactor the code, to only store the essential properties.

**OS and Theia version:**

All OSes. 
Theia version  3cf2837ca278671d4f49c8d6c1d10bb02a87910a

**Comment by elaihau** [comment]
I drop two breakpoints, one here
https://github.com/eclipse-theia/theia/blob/3cf2837ca278671d4f49c8d6c1d10bb02a87910a/packages/terminal/src/browser/terminal-widget-impl.ts#L89

and the other here
https://github.com/eclipse-theia/theia/blob/3cf2837ca278671d4f49c8d6c1d10bb02a87910a/packages/terminal/src/browser/terminal-widget-impl.ts#L315

I found every time I refreshed the browser, opener options did get restored (from the 1st breakpoint), however the opener options were not restored in the restore state function (from the 2nd breakpoint). Could you please tell me what is the mechanism behind the save&restore opener options? @akosyakov Thank you !

**Comment by akosyakov** [comment]
> save&restore opener options

there is no such thing, opener options should not be never stored

There are 2 states are stored:
- factoryId + widget options which is widget identifier, it's used to recreate the widget
- StatefulWidget which is used to store/resource internal state of the widget
