### ISSUE TITLE
Update Theia Logo in PMI

### ISSUE THREAD

**Issue by ChristieWittEclipse** [eclipse-theia/theia#7441]
I'm not sure if this is the correct place to put this request, so if it should go somewhere else, just let me know!

We're working on the ECD Tools website and noticed that the Theia logo has not been uploaded:
https://ecdtools.eclipse.org/#projects

Can you please update the logo in your PMI: https://projects.eclipse.org/projects/ecd.theia
I've attached the assets.
[theia-logos.zip](https://github.com/eclipse-theia/theia/files/4395649/theia-logos.zip)

**Comment by vince-fugnitto** [comment]
cc @marcdumais-work

**Comment by marcdumais-work** [comment]
Hi @ChristieWittEclipse ,

Done. However there may be a problem:: I see the logo when I am logged-in, but when I am not it's not visible. 

Logged-in:
![image](https://user-images.githubusercontent.com/25749063/77807676-f3ef3b80-705e-11ea-9c7f-7b4da6365243.png)

and not:
![image](https://user-images.githubusercontent.com/25749063/77807725-12edcd80-705f-11ea-86d6-2dd37ad93e44.png)

Can you see the logo?

**Comment by marcdumais-work** [comment]
I see the logo now on the Theia project page but not on the ECD tools page. I do not have write access to that one. Is is maybe supposed to automatically pick project logos?

**Comment by jpersonna** [comment]
Hi Christie,

Can you please update the ECD Tools website with the THEIA logo provided by Marc?
If we need to do anything else from our end for this, please let us know.

Thanks a lot/Jean

**Comment by ChristieWittEclipse** [comment]
@marcdumais-work thank you for uploading that. I see the logo on this page when I'm not logged in: https://projects.eclipse.org/projects/ecd.theia

@jpersonna and @marcdumais-work – The ECD Tools website should pick up the project logo automatically and it isn't. I will troubleshoot this with @chrisguindon today.

**Comment by chrisguindon** [comment]
@ChristieWittEclipse The website will update the next time we push a change! I will force it now to rebuilt so that we can test!

**Comment by chrisguindon** [comment]
@marcdumais-work We have aggressive caching rules if you are not logged in! That's why you could see it when logged in but not when you logged out!

**Comment by ChristieWittEclipse** [comment]
The Theia logo is now updated on the ECD Tools website. Thank you so much!
![Screen Shot 2020-03-30 at 9 23 19 AM](https://user-images.githubusercontent.com/58480647/77917138-27e97d00-7268-11ea-8cbf-0f926506f358.png)
