### ISSUE TITLE
[DialogBox] : Improve display for remove folder from workspace

### ISSUE THREAD

**Issue by Anasshahidd21** [eclipse-theia/theia#7443]
### Description
Removing multiple workspaces roots currently displays this dialog box.
![current](https://user-images.githubusercontent.com/43870550/77816358-8cee7880-7098-11ea-9407-60729f646ba1.PNG)

The dialog box could be improved to be either like. 
![rm](https://user-images.githubusercontent.com/43870550/77816373-ad1e3780-7098-11ea-9527-f167189df0fc.PNG)

Or 

![rm-2](https://user-images.githubusercontent.com/43870550/77816375-b14a5500-7098-11ea-9ddf-f87d996a4c2e.PNG)

### Reproduction Steps
1. Open Theia
2. Open a workspace
3. Add more folder to the workspace
4. Remove the folder from workspace

**OS and Theia version:**

**Diagnostics:**

**Comment by lmcbout** [comment]
Question:
 Can we select which folder(s) to remove or all of them will be removed  when selecting OK?
If we choose the following, we could indicate which one to delete ?

https://user-images.githubusercontent.com/43870550/77816373-ad1e3780-7098-11ea-9527-f167189df0fc.PNG

**Comment by Anasshahidd21** [comment]
> Question:
> Can we select which folder(s) to remove or all of them will be removed when selecting OK?
> If we choose the following, we could indicate which one to delete ?
> 
> https://user-images.githubusercontent.com/43870550/77816373-ad1e3780-7098-11ea-9527-f167189df0fc.PNG

@lmcbout the current implementation removes only the folder which is selected from the workspace and only that folder-name is reflected in the dialog box. In the example above I have selected to remove three folders from the workspace. So having a selection at this point seems unnecessary imo.

**Comment by lmcbout** [comment]
@Anasshahidd21 Thanks for the explanation. FRom the picture above, I though you were proposing a list of folders you can remove, but there was no options to select which one to remove :+1:
