### ISSUE TITLE
Improve Monaco upgrade process

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#7457]
The issue is based on discussion with @akosyakov @azatsarynnyy @RomanNikitenko 
The last upgrade Monaco PR: https://github.com/eclipse-theia/theia/pull/7149

### The main steps at upgrade Monaco version are the following:
- upgrade `monaco-languageclient`
- types' signatures alignment 
- editor configurations alignment
- testing/fixing

### What we could improve:

- upgrade `monaco-languageclient` 
We have an issue to remove the dependency `monaco-languageclient`, please see the discussion here: https://github.com/eclipse-theia/theia/issues/7100

- types' signatures alignment 
This step is very time consuming one, so it would be nice to avoid working on it manually. Anton's (@akosyakov)  idea is getting types from the corresponding version of VS Code automatically, for example, by generating `index.d.ts` file/files. We need more investigation regarding this step. 
Related issue: https://github.com/eclipse-theia/theia/issues/7261 

- editor configurations alignment
At last upgrade @RomanNikitenko  did this kind of work in semi-automatic way: 
                 -  read properties from `editorOptionsRegistry` of VS Code
                 -  write the data as Json to a file
                 -  copy to the `codeEditorPreferenceProperties` of Theia 
                 -  check manually
The idea for improvement from Anton: read these properties in `@theia/monaco` module of Theia and fill `codeEditorPreferenceProperties`.

- testing/fixing
At last upgrade `Monaco` version Anton provided integration tests: https://github.com/eclipse-theia/theia/pull/7265. It helped to test the changes and will speed up the process of testing of next Monaco upgrade.
We consider adding more tests to reduce manual testing, avoid regressions and provide more smooth process of upgrade.

**Comment by RomanNikitenko** [comment]
@akosyakov @azatsarynnyy 
Please feel free to edit the description, add comments and so on if I missed something
thanks!

**Comment by azatsarynnyy** [comment]
@RomanNikitenko thank you for outlining the possible directions for improving Monaco upgrade process.

ATM working on these improvements is not in our short-term plans however, these are undoubtedly important directions that have to be considered before the next Monaco upgrade.
cc: @akosyakov ^^

**Comment by vince-fugnitto** [comment]
@colin-grant-work would you agree that the upgrade process for monaco is now improved following the latest update?
For example we no longer rely on `monaco-languageclient`, the `editor-preferences` are now automated and for future upgrades things should be far simpler.

**Comment by colin-grant-work** [comment]
@vince-fugnitto I think the process is definitely better than it was before or than it was when this issue was opened. I'll assign this to myself, and I'll make a PR updating our documentation in the repo and - apart from the PR - in the wiki, and close this that way. Keep up the pressure on me to actually do the documentation part :-).

**Comment by colin-grant-work** [comment]
Closing as done via #11331 where the steps for performing a Monaco upgrade are outlined.
