### ISSUE TITLE
Search behaves differently than it used to (and compared to VS code)

### ISSUE THREAD

**Issue by csweichel** [eclipse-theia/theia#7460]
### Description
When searching in an editor (Cmd+F) is used to be able to jump to the next search result by pressing `enter`. Now, when pressing enter the editor gets the focus with the cursor placed at the last found result.

### Reproduction Steps
1. Open an editor
2. Open the search box (Cmd+F) and search for a string that's present in the editor
3. Press enter

**OS and Theia version:**
latest master

**Comment by akosyakov** [comment]
It seems to be a regression from latest Monaco migration. cc @RomanNikitenko

**Comment by RomanNikitenko** [comment]
@csweichel 
I reproduced the issue, thank you for reporting!
