### ISSUE TITLE
[vsx registry] client should take into account the extension's `engines.vscode` value

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#7464]
### Description
ATM the VSX client in Theia always shows/fetches the latest version of an extension. Open VSX offers an API that permits being more picky about which version of an extension is shown and eventually fetched. 

The client could take into account the version of "VS Code api engine" that Theia's plugin system supports and filter Open VSX extensions down to those that should be compatible according to that criteria, eventually showing and fetching the latest such, for a given extension. 
See: https://github.com/eclipse-theia/theia/issues/7448#issuecomment-606428240

update: this is the vscode equivalent feature [described](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#visual-studio-code-compatibility) to extensions authors:

---

_When authoring an extension, you will need to describe what is the extension's compatibility to Visual Studio Code itself. This can be done via the engines.vscode field inside package.json:_
```
{
  "engines": {
    "vscode": "^1.8.0"
  }
}
```
_You can use the engines.vscode field to make sure the extension only gets installed for clients that contain the API you depend on. This mechanism plays well with the Stable release as well as the Insiders one._

**Comment by kaiyue0329** [comment]
@Anasshahidd21 and I are working on this issue. We will create a PR for it soon.
