### ISSUE TITLE
Multiple errors from different schemas

### ISSUE THREAD

**Issue by sapirpol** [eclipse-theia/theia#7469]
### Description
When opening a 'manifest.json' file in theia, there is a default validation which is coming from jsonSchemaStore schemas (was tested both locally and in gitpod).
I'm trying to load my schema for 'manifest.json' through code using json contribution file and I received both errors from my schema and from jsonSchemaStore.

```
this.jsonSchemaStore.registerSchema({ 
      url:
        "file:///Users/schema.json",
      fileMatch: ["/manifest.json", "manifest.json"]
```

For 'FileMatch' I was trying the following conventions:
1. fileMatch: ["/manifest.json", "manifest.json"].
2. fileMatch: ["**/manifest.json"].

These conventions work when I set the schema through theia's preferences, but not using the code.
How can I fix it?

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
> When opening a 'manifest.json' file in theia, there is a default validation which is coming from jsonSchemaStore schemas (was tested both locally and in gitpod).

Do you know who is contributing default schema associations?

> I'm trying to load my schema for 'manifest.json' through code using json contribution file and I received both errors from my schema and from jsonSchemaStore.

`registerSchema` won't override any preconfigured schema associations, it adds one additional.

> These conventions work when I set the schema through theia's preferences, but not using the code.
How can I fix it?

The same logic applied to schema associations contributed programmatically and from preferences. You can try to debug: https://github.com/eclipse-theia/theia/blob/9481af8e21f3be4b2e6658854327d8fa2b390da3/packages/json/src/browser/json-client-contribution.ts#L51-L69

**Comment by sapirpol** [comment]
The schemas are coming as default from json schema store. 
After debugging I see that using `registerSchema` place my schema at the beginning of allConfigs array, and then it's url replaced with the one coming from json schema store.

Is there any other way I can use my schema?

**Comment by akosyakov** [comment]
Could you check whether you still have an issue with master branch? We switch to using vscode built-in extension to support it. If something does not work then we have to test and report against VS Code.

**Comment by tsmaeder** [comment]
@sapirpol since there has been no further input, I'm closing this one. Please let me know if you're still have this issue.
