### ISSUE TITLE
DebugAdapterTracker-onDidSendMessage(): theia sends string, vscode sends object

### ISSUE THREAD

**Issue by tomascechatbroadcomcom** [eclipse-theia/theia#7470]
### Description
It seems that theia sends string to method onDidSendMessage() in DebugAdapterTracker comparing to vscode that sends object.

### Reproduction Steps
Debug onDidSendMessage() implementation of DebugAdapterTracker in theia and in vscode.

**OS and Theia version:**
OS: ubuntu wsl 18.04 in windows 10
Theia version: @theia/example-browser 0.16.0

**Diagnostics:** 
Theia sends json string, vscode sends json object.

**Comment by sh7dm** [comment]
@tomascechatbroadcomcom what did cause this issue and what was the fault? Could you please tell what extension failed and what errors were printed or any other wrong behaviour?

**Comment by ishche** [comment]
> @tomascechatbroadcomcom what did cause this issue and what was the fault? Could you please tell what extension failed and what errors were printed or any other wrong behaviour?

I've updated my sample extension: https://github.com/ishche/vscode-samples-extension/releases/tag/0.0.2 or https://marketplace.visualstudio.com/items?itemName=x0a.vscode-samples-extension

Steps to reproduce:
1. run command: "Example: Track DAP message"
2. Start any debug session
Expected: Info message with Type: object
Actual: Info message with Type: string

**Comment by sh7dm** [comment]
Thank you! Will test
