### ISSUE TITLE
[core] Cannot render webviews when theia is behind a reverse-proxy

### ISSUE THREAD

**Issue by bsteinfeld** [eclipse-theia/theia#7484]
### Description
The [getRestUrl](https://github.com/eclipse-theia/theia/blob/master/packages/core/src/browser/endpoint.ts#L38-L40) function reads the pathname from `window.location`.  This normally is fine, however this breaks webviews (`<uuid>.webview`) when theia is sitting behind a reverse-proxy that alters the path.

### Reproduction Steps

To reproduce the issue, you'll need to setup a reverse-proxy that proxy's the connection from either a different port or path (both demonstrated in **NOT WORKING** example below):

When **WORKING** (just running theia directly on localhost:3000):
![webview-working](https://user-images.githubusercontent.com/276912/78175785-6c704680-7429-11ea-9bf4-f2511a0b55fa.gif)

When **NOT WORKING** (running theia behind a reverse-proxy, notice root url is: http://localhost:8888/user/dev/):
![webview-fail](https://user-images.githubusercontent.com/276912/78175805-76924500-7429-11ea-869d-f2b0c7b90937.gif)

**OS and Theia version:** Reproduced on MacOS & linux (likely would be the same on Windows). Reproduced many theia versions including current latest/next.

**Diagnostics:** 
I am able to fix the issue running in development locally by modifying `@theia/core`'s [getRestUrl](https://github.com/eclipse-theia/theia/blob/master/packages/core/src/browser/endpoint.ts#L38-L40) function to the following:

```
getRestUrl(): URI {
        const newHost = this.host.replace(/:8888$/, ':3000');
        const newPathname = this.pathname.replace(/\/user\/\w+/, '');
        return new URI(`${this.httpScheme}//${newHost}${newPathname}${this.path}`);
}
```

While this works locally in development, I am unable to run this in production (I am using a dockerized deployment based off of  [theia-full](https://github.com/theia-ide/theia-apps/blob/master/theia-full-docker), specifically I am trying [this](https://gist.github.com/bsteinfeld/ff5ae904b770e82a8728310e558c4997) package.json) due to running multiple versions of `core` (e.g. my customized one, and the official one within each package). 

For more details see the [Spectrum thread](https://spectrum.chat/theia/theiadevcon/need-help-updating-theia-core-and-deploying-it-to-a-docker-container~65a8f6ac-3f36-4eb8-b68f-9647b34475e8)

**Comment by akosyakov** [comment]
Webviews are running fine in Gitpod behind reverse-proxy. Answered on Spectrum with differerent approaches how to tackle it.

**Comment by bsteinfeld** [comment]
@akosyakov I've responded in Spectrum - not sure how the approaches you mentioned will fix the issues I'm facing (they don't seem to address the modifications to the `pathname` that the reverse-proxy I'm using adds).

From the gifs above:

• Works (no reverse proxy): `<uuid>.webview.localhost:3000/#/home/project`
• Breaks (with reverse proxy that runs on port 8888): `<uuid>.webview.localhost:8888/user/dev/#/home/project`

**Comment by mridup** [comment]
@bsteinfeld did you get the nginx redirection working for this issue? I have a similar issue behind nginx reverse proxy.
