### ISSUE TITLE
[git] 'Initialize Repository' available even no open workspace 

### ISSUE THREAD

**Issue by alex-gilin** [eclipse-theia/theia#7487]
When IDE is opened and there is no open workspace, if you switch to the "Source Control" perspective and click on the "Initialize Repository" ( + ) icon nothing happens. 

I'd expect either the button to be disabled or an message to be displayed informing the user that initializing a repository requires an open workspace.

BTW, in vscode -> scm view - nothing available exclude the options 'open folder' and 'clone repository'.

**Comment by kittaakos** [comment]
Nice catch, it is an unhandled case. We check the widget and the selected repository but not the workspace status.

https://github.com/eclipse-theia/theia/blob/ce3987283c421e225a86edfcb8ca2719e52030fd/packages/git/src/browser/git-contribution.ts#L440-L444

**Comment by kittaakos** [comment]
`good first issue`: It has to be something like this:

```ts
registry.registerCommand(GIT_COMMANDS.INIT_REPOSITORY, {
  execute: () => this.quickOpenService.initRepository(),
  isEnabled: widget => this.workspaceService.opened && (!widget || widget instanceof ScmWidget) && !this.repositoryProvider.selectedRepository,
  isVisible: widget => this.workspaceService.opened && (!widget || widget instanceof ScmWidget) && !this.repositoryProvider.selectedRepository
});
```

**Comment by kittaakos** [comment]
> Can I still take on this one?

@umcconnell, it's yours. Go ahead, please. Let us know if you need assistance.

**Comment by kittaakos** [comment]
> nothing happens.

```
Uncaught (in promise) TypeError: Cannot read property 'uri' of undefined
    at GitQuickOpenService.<anonymous> (git-quick-open-service.ts:488)
    at step (git-quick-open-service.ts:15)
    at Object.next (git-quick-open-service.ts:15)
    at fulfilled (git-quick-open-service.ts:15)
```
