### ISSUE TITLE
[TS] Syntax coloring differs from VS Code with the HC theme

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7489]
### Description
 

VS Code:
![Screen Shot 2020-04-02 at 16 09 25](https://user-images.githubusercontent.com/1405703/78259052-73b45480-74fc-11ea-8cf2-80dca1f4c596.jpg)

Theia:
![Screen Shot 2020-04-02 at 16 09 34](https://user-images.githubusercontent.com/1405703/78259038-6e570a00-74fc-11ea-9dd8-0143f589259d.jpg)

Also, switching between color themes could leave the editor without syntax coloring. Everything was black and white. I can't reproduce it consistently.

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
It could be outdated built-in extension.

**Comment by akosyakov** [comment]
@kittaakos We upgraded to latest typescript and built-in extension. Could you still reproduce it?

**Comment by akosyakov** [comment]
It is still the same, so it seem to be relevant to textmate and monaco integrations, not to typescript.

**Comment by vince-fugnitto** [comment]
The issue has been resolved:

![Screen Shot 2022-08-19 at 11 42 44 AM](https://user-images.githubusercontent.com/40359487/185656560-25db257e-9141-4d3f-985e-62d15aee1598.png)
