### ISSUE TITLE
switch to latest VS Code URI

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7495]
See for the motivation: https://github.com/eclipse-theia/theia/issues/7462#issuecomment-608384688

**Comment by kittaakos** [comment]
See: https://github.com/eclipse-theia/theia/pull/6712

**Comment by kittaakos** [comment]
I already did it once because it was failing in the bundled electron app.

**Comment by akosyakov** [comment]
> I already did it once because it was failing in the bundled electron app.

Where did we get another vscode-uri? It should be declared only in core and never in any other extension?

**Comment by kittaakos** [comment]
The new version of VS Code URI comes from `vscode-json-languageservice`.
Here is the issue for electron: https://github.com/kittaakos/test-electron-builder
