### ISSUE TITLE
Fail to find "Desktop" edition

### ISSUE THREAD

**Issue by ctron** [eclipse-theia/theia#7497]
### Description

On the homepage of Theia is says:

> Not sure whether you need a web or desktop version or both?
> With Theia you can develop one IDE and run it in browsers or native desktop application from a single source.

Also:

> Theia is designed from the ground to run on Desktop and Cloud

However, I fail to find any download for a desktop version of Theia.

### Reproduction Steps

* Take a look at the homepage
* Or the documentation
* Or github

**Comment by akosyakov** [comment]
Please upvote here: https://github.com/eclipse-theia/theia/issues/5481
