### ISSUE TITLE
terminal: send `\r` to submit commands on Windows shells

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#7509]
### Description

Follow-up of https://github.com/eclipse-theia/theia/pull/6836.

I originally did not understand why in some circumstances I had to send `\n` twice for commands to be evaluated, but I now realize it is because shells seems to expect `\r` instead.

### Reproduction Steps

See https://github.com/eclipse-theia/theia/issues/7141#issuecomment-609030444

**OS and Theia version:** Windows 10, Theia 1.0.0

**Comment by msujew** [comment]
This has been resolved by https://github.com/eclipse-theia/theia/pull/12620.
