### ISSUE TITLE
nsfw build error: 'ThreadSafeFunction': is not a member of 'Napi'

### ISSUE THREAD

**Issue by owlJaeger** [eclipse-theia/theia#7510]
### Description
Building the nsfw package throws node-gyp error.
Example: ('ThreadSafeFunction': is not a member of 'Napi')

### Reproduction Steps
1. Clone the theia-apps repository.
2. Cd into theia-cpp-electron.
3. Run `yarn`

**OS and Theia version:**
@theia/core: 1.0.0
Tested on:
Windows 10 version 2004 (Build 19041.vb_release.191206-1406)
Ubuntu 19.10

**Diagnostics:** 
[log.txt](https://github.com/eclipse-theia/theia/files/4441583/log.txt)
```
c:\users\luca\desktop\theia\theia\node_modules\nsfw\includes\nsfw.h(21): error C2039: 'ThreadSafeFunction': is not a member of 'Napi' (compiling source file ..\src\NSFW.cpp) [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\node-addon-api\napi-inl.h(17): note: see declaration of 'Napi' (compiling source file ..\src\NSFW.cpp)
c:\users\luca\desktop\theia\theia\node_modules\nsfw\includes\nsfw.h(21): error C3646: 'mErrorCallback': unknown override specifier (compiling source file ..\src\NSFW.cpp) [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\includes\nsfw.h(21): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\src\NSFW.cpp) [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\includes\nsfw.h(22): error C2039: 'ThreadSafeFunction': is not a member of 'Napi' (compiling source file ..\src\NSFW.cpp) [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\node-addon-api\napi-inl.h(17): note: see declaration of 'Napi' (compiling source file ..\src\NSFW.cpp)
c:\users\luca\desktop\theia\theia\node_modules\nsfw\includes\nsfw.h(22): error C3646: 'mEventCallback': unknown override specifier (compiling source file ..\src\NSFW.cpp) [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\includes\nsfw.h(22): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ..\src\NSFW.cpp) [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(30): error C2065: 'mEventCallback': undeclared identifier [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(30): error C2039: 'ThreadSafeFunction': is not a member of 'Napi' [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\node-addon-api\napi-inl.h(17): note: see declaration of 'Napi'
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(30): error C3083: 'ThreadSafeFunction': the symbol to the left of a '::' must be a type [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(30): error C2039: 'New': is not a member of 'Napi' [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\node-addon-api\napi-inl.h(17): note: see declaration of 'Napi'
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(30): error C2660: 'Napi::Reference<Napi::Object>::New': function does not take 5 arguments [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\node-addon-api\napi.h(1102): note: see declaration of 'Napi::Reference<Napi::Object>::New' (compiling source file ..\src\NSFW.cpp)
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(64): error C2065: 'mErrorCallback': undeclared identifier [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(64): error C2039: 'ThreadSafeFunction': is not a member of 'Napi' [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\node-addon-api\napi-inl.h(17): note: see declaration of 'Napi'
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(64): error C3083: 'ThreadSafeFunction': the symbol to the left of a '::' must be a type [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(64): error C2039: 'New': is not a member of 'Napi' [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\node-addon-api\napi-inl.h(17): note: see declaration of 'Napi'
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(64): error C2660: 'Napi::Reference<Napi::Object>::New': function does not take 5 arguments [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\node-addon-api\napi.h(1102): note: see declaration of 'Napi::Reference<Napi::Object>::New' (compiling source file ..\src\NSFW.cpp)
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(77): error C2065: 'mErrorCallback': undeclared identifier [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(78): error C2065: 'mEventCallback': undeclared identifier [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(113): error C2039: 'mErrorCallback': is not a member of 'NSFW' [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\nsfw\includes\nsfw.h(14): note: see declaration of 'NSFW'
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(114): error C2039: 'mEventCallback': is not a member of 'NSFW' [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\luca\desktop\theia\theia\node_modules\nsfw\includes\nsfw.h(14): note: see declaration of 'NSFW'
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(204): error C2065: 'mErrorCallback': undeclared identifier [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(242): error C2065: 'mEventCallback': undeclared identifier [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(250): error C2065: 'mErrorCallback': undeclared identifier [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
c:\users\luca\desktop\theia\theia\node_modules\nsfw\src\nsfw.cpp(251): error C2065: 'mEventCallback': undeclared identifier [C:\Users\luca\Desktop\Theia\Theia\node_modules\nsfw\build\nsfw.vcxproj]
```

**Comment by vince-fugnitto** [comment]
Thank you for the issue, I think it might be better to open the issue directly in [theia-apps](https://github.com/theia-ide/theia-apps). I haven’t verified myself (if it is reproducible from sources in the main repository) but you may want to take a look at the project’s prerequisites which may prove to be useful:
- https://github.com/theia-ide/theia-apps

**Comment by akosyakov** [comment]
@vince-fugnitto please close and reopen there with a link

**Comment by kittaakos** [comment]
I can confirm this. I hit the same issue today in a downstream project after wiping the `yarn.lock` and re-running `yarn`.

```
[4/4] 🔨  Building fresh packages...
[1/17] ⠈ fsevents
[7/17] ⠈ drivelist
[9/17] ⠈ find-git-repositories
[8/17] ⠈ oniguruma
error /Users/akos.kitta/git/arduino-editor/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/akos.kitta/git/arduino-editor/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@10.15.3 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [ '/Users/akos.kitta/git/arduino-editor/node_modules/electron-rebuild/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/akos.kitta/git/arduino-editor/node_modules/nsfw/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/akos.kitta/git/arduino-editor/node_modules/electron-rebuild/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/akos.kitta/Library/Caches/node-gyp/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/akos.kitta/Library/Caches/node-gyp/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/akos.kitta/git/arduino-editor/node_modules/electron-rebuild/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/akos.kitta/Library/Caches/node-gyp/10.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/akos.kitta/git/arduino-editor/node_modules/nsfw',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/nsfw/src/NSFW.o
In file included from ../src/NSFW.cpp:1:
../src/../includes/NSFW.h:21:11: error: no type named 'ThreadSafeFunction' in namespace 'Napi'
    Napi::ThreadSafeFunction mErrorCallback;
    ~~~~~~^
../src/../includes/NSFW.h:22:11: error: no type named 'ThreadSafeFunction' in namespace 'Napi'
    Napi::ThreadSafeFunction mEventCallback;
    ~~~~~~^
../src/NSFW.cpp:30:26: error: no member named 'ThreadSafeFunction' in namespace 'Napi'
  mEventCallback = Napi::ThreadSafeFunction::New(
                   ~~~~~~^
../src/NSFW.cpp:64:28: error: no member named 'ThreadSafeFunction' in namespace 'Napi'
    mErrorCallback = Napi::ThreadSafeFunction::New(
                     ~~~~~~^
../src/NSFW.cpp:93:3: error: cannot initialize object parameter of type 'Napi::Reference<Napi::Object>' with an expression of type 'NSFW'
  mNSFW->Ref();
  ^~~~~
../src/NSFW.cpp:127:7: error: cannot initialize object parameter of type 'Napi::Reference<Napi::Object>' with an expression of type 'NSFW'
      mNSFW->Unref();
      ^~~~~
../src/NSFW.cpp:132:7: error: cannot initialize object parameter of type 'Napi::Reference<Napi::Object>' with an expression of type 'NSFW'
      mNSFW->Unref();
      ^~~~~
../src/NSFW.cpp:141:7: error: cannot initialize object parameter of type 'Napi::Reference<Napi::Object>' with an expression of type 'NSFW'
      mNSFW->Unref();
      ^~~~~
../src/NSFW.cpp:185:5: error: cannot initialize object parameter of type 'Napi::Reference<Napi::Object>' with an expression of type 'NSFW'
    mNSFW->Unref();
    ^~~~~
In file included from ../src/NSFW.cpp:1:
In file included from ../src/../includes/NSFW.h:7:
In file included from /Users/akos.kitta/git/arduino-editor/node_modules/nsfw/node_modules/node-addon-api/napi.h:2169:
/Users/akos.kitta/git/arduino-editor/node_modules/nsfw/node_modules/node-addon-api/napi-inl.h:2975:22: error: cannot initialize a variable of type 'Reference<Napi::Object> *' with an lvalue of type 'NSFW *'
  Reference<Object>* instanceRef = instance;
                     ^             ~~~~~~~~
../src/NSFW.cpp:8:3: note: in instantiation of member function 'Napi::ObjectWrap<NSFW>::ObjectWrap' requested here
  Napi::ObjectWrap<NSFW>(info),
  ^
In file included from ../src/NSFW.cpp:1:
In file included from ../src/../includes/NSFW.h:7:
In file included from /Users/akos.kitta/git/arduino-editor/node_modules/nsfw/node_modules/node-addon-api/napi.h:2169:
/Users/akos.kitta/git/arduino-editor/node_modules/nsfw/node_modules/node-addon-api/napi-inl.h:3501:3: error: cannot initialize object parameter of type 'Napi::ObjectWrap<NSFW>' with an expression of type 'NSFW'
  instance->Finalize(Napi::Env(env));
  ^~~~~~~~
/Users/akos.kitta/git/arduino-editor/node_modules/nsfw/node_modules/node-addon-api/napi-inl.h:2972:46: note: in instantiation of member function 'Napi::ObjectWrap<NSFW>::FinalizeCallback' requested here
  status = napi_wrap(env, wrapper, instance, FinalizeCallback, nullptr, &ref);
                                             ^
../src/NSFW.cpp:8:3: note: in instantiation of member function 'Napi::ObjectWrap<NSFW>::ObjectWrap' requested here
  Napi::ObjectWrap<NSFW>(info),
  ^
In file included from ../src/NSFW.cpp:1:
../src/../includes/NSFW.h:21:30: warning: private field 'mErrorCallback' is not used [-Wunused-private-field]
    Napi::ThreadSafeFunction mErrorCallback;
                             ^
../src/../includes/NSFW.h:22:30: warning: private field 'mEventCallback' is not used [-Wunused-private-field]
    Napi::ThreadSafeFunction mEventCallback;
                             ^
2 warnings and 11 errors generated.
make: *** [Release/obj.target/nsfw/src/NSFW.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/akos.kitta/git/arduino-editor/node_modules/electron-rebuild/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/akos.kitta/.nvm/versions/node/v10.15.3/bin/node" "/Users/akos.kitta/git/arduino-editor/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/akos.kitta/git/arduino-editor/node_modules/nsfw
```

@JanKoehnlein had the same issue today. So if anyone who is interested in a workaround; you should copy the `yarn.lock` from `eclipse-theia/theia` into your workspace root and run `yarn`. I do not have a better idea now, but it will come back for sure. Most likely, the real fix is to use `resolutions` in the downstream project.

**Comment by benoitf** [comment]
```json
  "resolutions": {
    "**/**/nsfw": "1.2.7"
   },
```

in package.json should fix the issue

**Comment by vince-fugnitto** [comment]
> ```json
>   "resolutions": {
>     "**/**/nsfw": "1.2.7"
>    },
> ```
> 
> in package.json should fix the issue

I confirmed it worked in a downstream project (fresh from the generator).

**Comment by akosyakov** [comment]
cc @azatsarynnyy Maybe it has to do something with ARM's fix in nsfw? :)

**Comment by benoitf** [comment]
not sure issue is for @azatsarynnyy but more for @arekzaluski

**Comment by arekzaluski** [comment]
@akosyakov @benoitf @vince-fugnitto  I don't think that this issue is caused by our change in nsfw (fixing the rename events on Windows). It is most likely due to the Napi refactor in release `1.2.8`. We will check it.

**Comment by implausible** [comment]
If it's within your power you might want to consider upgrading to Node 10.16.0 or higher.

**Comment by thegecko** [comment]
I think it would be sensible to keep the node version inline with the version used in the electron we support.

Currently, on Electron 4.x we have node 10.11.0.
Upgrading to Electron 5.x will push us to Node 12.0.0

**Comment by owlJaeger** [comment]
I've tried building again and now no workaround is needed to build it without errors. Seems to be fixed, closing this issue

**Comment by rajattyagi200** [comment]
I am getting nsfw build error in Ubuntu

[4/4] Building fresh packages...
[1/12] ⠂ command-join
[2/12] ⠂ drivelist
[7/12] ⠂ node-pty
[6/12] ⠂ find-git-repositories
error /home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@14.19.0 | linux | x64
gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/nsfw/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/rajat/.cache/node-gyp/14.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/rajat/.cache/node-gyp/14.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/rajat/.cache/node-gyp/14.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/nsfw',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/nsfw/build'
  CXX(target) Release/obj.target/nsfw/src/NSFW.o
In file included from ../src/NSFW.cpp:1:
../src/../includes/NSFW.h:7:10: fatal error: napi.h: No such file or directory
    7 | #include <napi.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [nsfw.target.mk:128: Release/obj.target/nsfw/src/NSFW.o] Error 1
make: Leaving directory '/home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/nsfw/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.15.0-48-generic
gyp ERR! command "/home/rajat/.nvm/versions/node/v14.19.0/bin/node" "/home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/rajat/Desktop/Codejudge Repos/codejudge-ide/node_modules/nsfw

**Comment by amunrarara** [comment]
I am currently getting this error, as well. This occurs with a fresh clone of /theia, andalso  /theia-blueprint. MacOS 12.6 Monterey, M1 2020

`[4/10] ⡀ nsfw
error /Volumes/T7 Touch/Projects/theia-sundragon/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Volumes/T7 Touch/Projects/theia-sundragon/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@19.2.0 | darwin | arm64
gyp info find Python using Python version 3.9.2 found at "/usr/local/bin/python3"
gyp info spawn /usr/local/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/aceaspades/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/T7 Touch/Projects/theia-sundragon/node_modules/nsfw/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aceaspades/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/aceaspades/Library/Caches/node-gyp/19.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/aceaspades/Library/Caches/node-gyp/19.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/aceaspades/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/aceaspades/Library/Caches/node-gyp/19.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/T7 Touch/Projects/theia-sundragon/node_modules/nsfw',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/nsfw/src/NSFW.o
clang: error: no such file or directory: 'Touch/Projects/theia-sundragon/node_modules/nsfw/node_modules/node-addon-api'
make: *** [Release/obj.target/nsfw/src/NSFW.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/aceaspades/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/aceaspades/.nvm/versions/node/v19.2.0/bin/node" "/Users/aceaspades/.nvm/versions/node/v19.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/T7 Touch/Projects/theia-sundragon/node_modules/nsfw`
