### ISSUE TITLE
Some extensions descriptions are displayed wrong

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7511]
### Description
With some extensions, `%extension.description%` is displayed instead of description. Looks like they don't have descriptions in Open-VSX registry.

### Reproduction Steps
Search Open-VSX for Chrome Debugger using Theia browser example.

**OS and Theia version:**
Ubuntu 19.10, Theia 1.0.0

**Diagnostics:** 

![image](https://user-images.githubusercontent.com/19504461/78633627-bf734f00-78aa-11ea-8ca7-e3968b277c9d.png)

**Comment by akosyakov** [comment]
It was already resolved, but extensions has to be republished with the proper description: https://github.com/eclipse/openvsx/issues/19#issuecomment-609811125
