### ISSUE TITLE
Checkboxes for boolean config values

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7518]
### Description
It's not very comfortable to use dropdown when the value is boolean.

### Reproduction Steps
1. Open settings
2. Edit any boolean prop, like this:
![image](https://user-images.githubusercontent.com/19504461/78681767-d1c6aa80-78f5-11ea-9c5a-329272076f6c.png)
3. See a dropdown with 2 options:
![image](https://user-images.githubusercontent.com/19504461/78682091-3e41a980-78f6-11ea-8951-aeb536ee420c.png)

**OS and Theia version:**
Ubuntu 19.10
Theia 1.0.0

**Diagnostics:** 

--

**Comment by vince-fugnitto** [comment]
@sh7dm please see the following pull-request which updates the preferences UI more closely to that of VS Code: #7105 

Some screenshots (still a WIP):

<img width="873" alt="Screen Shot 2020-04-07 at 9 21 37 AM" src="https://user-images.githubusercontent.com/40359487/78684474-7fb66280-78be-11ea-8be4-17f044b35bea.png">
