### ISSUE TITLE
As a user I want to copy the content of the current Output channel with `Ctrl/Cmd+A`

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7521]
### Description
 

When the Output channel is opened and is the active widget, I want to be able to copy the content (`Select All`) with the <kbd>Ctrl/Cmd</kbd>+<kbd>A</kbd> keybindings.

Inspired by: https://github.com/arduino/arduino-pro-ide/issues/37

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
@kittaakos Do you think it would be hard to replace output with Monaco editor as it is done in VS Code: https://github.com/eclipse-theia/theia/issues/2702#issuecomment-417661012
