### ISSUE TITLE
[quick-open] The fuzzy search should handle whitespace gracefully

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7522]
### Description
 

I want to be able to see and run the command `Toggle Minimap` if I type `tog mi`. It does not work now. I think we can call it a bug.

Theia:
`toggle mi` 👍 
![Screen Shot 2020-04-08 at 10 11 14](https://user-images.githubusercontent.com/1405703/78760537-983b8100-7981-11ea-958c-e5f95148105b.jpg)

`tog mi` 👎 
![Screen Shot 2020-04-08 at 10 11 22](https://user-images.githubusercontent.com/1405703/78760607-b43f2280-7981-11ea-9dc9-7ea24bd68a26.jpg)

VS Code:
`tog mi`: 👍 
![Screen Shot 2020-04-08 at 10 11 01](https://user-images.githubusercontent.com/1405703/78760627-bacd9a00-7981-11ea-9df7-65f6001d2f3d.jpg)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
I'm wondering if we should enable the fuzzy option `enableSeparateSubstringMatching` but it might give us more results than expected. For example:

<div align='center'>

<img width="717" alt="Screen Shot 2020-04-08 at 11 14 49 AM" src="https://user-images.githubusercontent.com/40359487/78801072-2f0c3b80-798a-11ea-8d2a-f2add438ac50.png">


</div>

**Comment by kittaakos** [comment]
Interesting. We could align it with VS Code. But strangely, VS Code boosts a few items (marked as red) above longer matches (marked as green):

![Screen Shot 2020-04-08 at 17 17 17](https://user-images.githubusercontent.com/1405703/78801610-339e1780-79bd-11ea-991a-7d9652ca4330.jpg)

**Comment by akosyakov** [comment]
Don't we use fuzzy matching from Monaco? Maybe we should upgrade to latest Monaco again to align with current VS Code behaviour?

**Comment by vince-fugnitto** [comment]
The issue has been resolved, likely from https://github.com/eclipse-theia/theia/pull/9928.
