### ISSUE TITLE
Recently used commands include ones triggered by mouse

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7527]
### Description
I expect commands triggered from UI or by keyboard not to be added to recent commands list, just as in VS Code. Theia does so. If this is expected, it'll be nice to have a setting for that.

### Reproduction Steps
A (Theia):
1. Click notifications bell
2. Press F1 and see that it was added to recent commands list
B (VS Code)
1. Click notifications bell
2. Press F1 and see that it was __NOT__ added to recent commands list. Recent list contains only commands that were triggered from `F1`/`Ctrl`+`Shift`+`P` menu.

**OS and Theia version:**
Ubuntu 19.10
Theia 1.0.0 (`master`)

**Diagnostics:** 

No errors

**Comment by vince-fugnitto** [comment]
@sh7dm you're right, at the moment the framework makes no distinction on how a command was executed, meaning that it will register a recent command whenever a command is executed:
- through the quick-open command menu (vscode use-case)
- through manual selection by a user
- through it's keybinding value (if present)

Would you like to handle fixing the issue, meaning only registering commands in the quick-open if it's triggered by the first use-case?

**Comment by sh7dm** [comment]
Would like to try myself on it!

**Comment by vince-fugnitto** [comment]
> Would like to try myself on it!

Great! Please let us know if you're having difficulties or are blocked in any way :)
