### ISSUE TITLE
[change] new foldingStrategy behaviour

### ISSUE THREAD

**Issue by daiyam** [eclipse-theia/theia#7541]
## Description

I would like to change how the folding ranges are provided.

### VSCode behaviour

The editor is using the folding ranges provided:
- by the folding range provider defined by the setting `editor.foldingStrategy` (`auto` or `indentation`)
- <ins>**and**</ins> by the folding range provider defined by an extension

### Expected behaviour

The editor is using the folding ranges provided:
- by the folding range provider defined by the setting `editor.foldingStrategy` (`auto` or `indentation`)
- <ins>**or**</ins> by the folding range provider, defined by an extension, whose `id` is the value of the setting `editor.foldingStrategy`

I already have a [patch](https://github.com/zokugun/MrCode/blob/master/patches/editor-folding-strategy--custom.patch) to change that behaviour in VSCode and the extension [Explicit Folding](https://github.com/zokugun/vscode-explicit-folding) which support the old and new behaviours.

Do you think it is a reasonable change and can be included in a future version of theia? Thx

**Comment by vince-fugnitto** [comment]
> Do you think it is a reasonable change and can be included in a future version of theia? Thx

@daiyam thank you for the issue!

A couple of discussion points:
- do you have the pull-request link to vscode from which you suggesting updating the folding strategy?  (I'd like to see/reference any discussions that might have been had with the proposal and why it was not accepted).
- what issue are you attempting to fix/enhance by introducing a different folding strategy?
- another possibility would be to create a custom theia extension which overrides the default folding strategy to meet your requirements (if the overall community disagrees in changing the default behaviour directly in the framework). Ideally we'd like to have a similar behavior as that of vscode unless there is a clear need to diverge. Once the second question is answered can we really agree/disagree on the feature.

**Comment by daiyam** [comment]
@vince-fugnitto thx for the answer.

- the PR is microsoft/vscode#54200.
- I'm used to manually control how the code is folded which improve, for me, the code readability. It's come from [Emacs](https://www.emacswiki.org/emacs/FoldingMode).
- Can a theia extension change the default behaviour? I'm asking because in VSCode, it can't be done.

**Comment by vince-fugnitto** [comment]
> * Can a theia extension change the default behaviour? 
> I'm asking because in VSCode, it can't be done.

Theia is a framework for building IDE-like applications, while VS Code is a product so it is possible for application developers to customize their applications to suit their needs.

In the framework we attempt to make things highly customizable and extensible meaning that any feature or behavior present can in theory be overridden/extended. In the case of the folding regions, we might rely directly on the behavior from the [monaco editor](https://microsoft.github.io/monaco-editor/) and I am unsure at the moment how one can update it easily. 

Perhaps @akosyakov you might have some ideas?

**Comment by akosyakov** [comment]
@vince-fugnitto Yes, it can be changed only in the upstream.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Yes, it can be changed only in the upstream.

**Comment by goyalyashpal** [comment]
> * the PR is [add custom folding strategy microsoft/vscode#54200](https://github.com/microsoft/vscode/pull/54200).

just noticed today that it was merged upstream at https://github.com/microsoft/vscode/pull/157434
