### ISSUE TITLE
Cut/Copy/Paste Keyboard Shortcuts Work Intermittently

### ISSUE THREAD

**Issue by PTrottier** [eclipse-theia/theia#7542]
### Description
 
Once in a while, particularly after loading Theia (in Gitpod for me), the keyboard shortcuts for Cut/Copy/Paste don't work. For instance, when cutting text, the text just stay highlighted.

### Reproduction Steps

1. Pick a file that can be opened with Theia's text editor
2. Select text
3. Press CTRL-X, CTRL-C, or CTRL-V

**OS and Theia version:**
Firefox 73.0 on macOS Catalina and Firefox 75.0 on Ubuntu 19.10
Theia from Gitpod (I don't know how to get the Theia version from Gitpod)

**Diagnostics:** 

I didn't see errors in the browser console.
This issue seems to be rectified after selecting the desired control using the right-click context menu, then later trying the keyboard shortcut again.

cc @jankeromnes

**Comment by jankeromnes** [comment]
Thanks @PTrottier for reporting this issue! @geropl and myself are also seeing it (in Firefox as well).

**Comment by akosyakov** [comment]
We intercept this keybinding and delegate to Monaco for evaluation which may to perfrom some editor action or delegate to `document.execCommand`. Such command should be executed in event-loop triggered by a user which is true for keydown event, but there some async code is involved. Chrome seems to be able to track down that async code origins from event-loop triggered by a user, but Firefox is not capable always and prohibits execution of `document.execCommand`:
<img width="1362" alt="Screenshot 2020-05-20 at 14 45 53" src="https://user-images.githubusercontent.com/3082655/82447489-aadcc600-9aa8-11ea-8124-7859ea7f95c0.png">

I will investigate whether it is possible to get rid fo async code.

**Comment by akosyakov** [comment]
FF issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1640883

**Comment by geropl** [comment]
Works for me with Firefox 78 (target release for https://bugzilla.mozilla.org/show_bug.cgi?id=1640883). @PTrottier @akosyakov

**Comment by akosyakov** [comment]
ok, please use Firefox 78 or higher. It was FF issue.
