### ISSUE TITLE
PDF Preview not Tillable on Main panel

### ISSUE THREAD

**Issue by PTrottier** [eclipse-theia/theia#7543]
### Description
 
I like to have my PDFs beside a text editor in Theia but when I try to click the tab in the Main panel and move it a side on the Main panel, it's animation imply that it can't be moved there (no outlines and when dragging towards the side, it doesn't move as it does when it works).

Please note, with some trial and error, I am able to move it to the left panel (the sidebar) and it appears as a menu option as such:

![PDF](https://user-images.githubusercontent.com/31802216/78940966-bdfd7e80-7a84-11ea-8e20-710deb9150a5.png)

### Reproduction Steps

1. Open a PDF
2. Try to drag it to a side (left or right) on the main panel

**OS and Theia version:**
Firefox 73.0 on macOS Catalina and Firefox 75.0 on Ubuntu 19.10
Theia from Gitpod (I don't know how to get the Theia version from Gitpod)

**Diagnostics:** 

No errors in the browser console.

**Comment by vince-fugnitto** [comment]
@PTrottier thank you for the issue, I'm not sure what your exact setup is (if you are using a plugin to render the pdf or only the default preview), but moving views around works correctly. Some more information such as a reproducible setup would greatly help:

<div align='center'>

![pdf2](https://user-images.githubusercontent.com/40359487/78944041-061f9f80-7a8b-11ea-9595-eabefa10735e.gif)


</div>

**Comment by vince-fugnitto** [comment]
Closing the issue at the moment.
Please re-open the issue if you are able to successfully reproduce it from sources/have additional information.
