### ISSUE TITLE
Unable to edit "When" field in keyboard shortcuts editor

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7551]
### Description
When trying to edit keyboard shortcuts from the UI I can't edit `When`. I can only do so after I create a custom keybinding and edit it in JSON.
In VS Code a context menu pops up when user right-clicks on a keybinding, like this:
![image](https://user-images.githubusercontent.com/19504461/79064572-af94aa00-7cb2-11ea-88ae-a7cbea6580c4.png)
2nd item from the and means `Change When expression`, this is the option I couldn't find in Theia.

### Reproduction Steps
1. Open Keyboard Shortcuts (`Ctrl`+`Alt`+`,`)
2. Try to find any button or right-click on a keybinding item
3. Find no way to set its `When` condition

**OS and Theia version:**
OS: Ubuntu 19.10
Theia: `master`

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/7582
