### ISSUE TITLE
Browser console errors: Language for 'X' not found.

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#7556]
### Description

There are errors on browser console when theia starts:
![image](https://user-images.githubusercontent.com/9420921/79102478-7e2fe300-7d73-11ea-86a4-e3c52db154c2.png)

### Reproduction Steps
Start theia from master.

**OS and Theia version:**
windows/debian

**Diagnostics:** 
N/A

**Comment by vince-fugnitto** [comment]
I understand that there are still missing APIs that have yet to be fully implemented (either missing at the moment/stubbed). The markdown errors are likely for embedded languages (when using triple backticks and a language identifier), in order to get the correct syntax highlighting.

**Comment by akosyakov** [comment]
We have to test it against latest built-in extensions. It seems in which we use not all languages are present. If it is the same with them, then maybe we should have sensible guards to quiet them or report only once.
