### ISSUE TITLE
Warn about unknown target

### ISSUE THREAD

**Issue by maksimr** [eclipse-theia/theia#7559]
## Reproduction Steps

- Crate simple Theia project
- Add `”theia”: {“target”: “foo”}` to package.json 

ER: Warn about unknown target “foo”
AR: No warning. Project build as for “browser”

**Comment by vince-fugnitto** [comment]
The default prop is `browser` if no/incorrect value is provided.

https://github.com/eclipse-theia/theia/blob/cb3db2a1191b350bc46784d8e699e4f15a7647d8/dev-packages/application-package/src/application-props.ts#L45-L48

@maksimr would you like to take care of submitting a quick pull-request to warn about an unknown target?
