### ISSUE TITLE
Breakpoints aren't updated while debugging view is inactive

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7571]
### Description
When I change (set, move, delete) a breakpoint when e.g. File Explorer is opened at side panel and then switch to debug view, I see no changes, but when I change any breakpoint again (e.g. create on arbitrary line and then remove) all of my previous changes are shown.

### Reproduction Steps

1. Open a workspace with no breakpoints at the moment
2. Move focus to File Explorer, SCM or another view
3. Add some breakpoints
4. Open Debug view
5. See no breakpoints there, but they're present in the editor
6. Add another breakpoint
7. See that all other breakpoints are shown now.

**OS and Theia version:**
OS: Ubuntu 19.10
Theia: `master`

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@sh7dm would you like to try to provide a fix? 😄

**Comment by sh7dm** [comment]
I would like to try with no guarantee :smiley: . I haven't got a lot of time now, so it might take long.

**Comment by sh7dm** [comment]
@vince-fugnitto I couldn't determine the cause of the problem, sorry.

**Comment by vince-fugnitto** [comment]
I'm unable to reproduce the issue any longer, are you @sh7dm?

**Comment by sh7dm** [comment]
I'm unable to check it at the moment. Probably it's been already fixed.

**Comment by vince-fugnitto** [comment]
> I'm unable to check it at the moment. Probably it's been already fixed.

I re-verified the issue and I can no longer reproduce it.
We can re-open if the bug persists.
