### ISSUE TITLE
Support for VSCode Command workbench.action.revertAndCloseActiveEditor

### ISSUE THREAD

**Issue by nmorenor** [eclipse-theia/theia#7575]
We have an extension and we are looking to be compatible with Theia IDE I see that there are already work in progress to support the vscode built-in commands at [4050](https://github.com/eclipse-theia/theia/issues/4050). Which will make the extension to work as if it were running on vscode.

We are using also the command `workbench.action.revertAndCloseActiveEditor`. I've just cloned the Theia repo and manually and dropped the .vsix under plugins directory.

**Comment by akosyakov** [comment]
Missing editor commands should be added here: https://github.com/eclipse-theia/theia/blob/master/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L348

Referenced implementation in VS Code: https://github.com/microsoft/vscode/blob/3f0e5b4ab059cb6c05ecac091b652cfc50b9292f/src/vs/workbench/browser/parts/editor/editorActions.ts#L462

In Theia:
- to revert: `MonacoEditor.getCurrent(EditorManager).document.revert`
- to close: `EditorManager.close(EditorManager.current.id)`

Don't forget to await.
