### ISSUE TITLE
Support for `vscode.workspace.findTextInFiles` API

### ISSUE THREAD

**Issue by nmorenor** [eclipse-theia/theia#7576]
We are working on a VSCode extension and we are looking to have it compatible with the Theia IDE. We have a search in workspace "feature" that works by using a non yet public vscode API. "vscode.workspace.findTextInFiles". Basically it allow you to search text in all your workspace files.

I have tested out of the master branch by dropping the *.visx file under the plugins directory.

**Comment by vince-fugnitto** [comment]
I believe that VS Code APIs are added to the framework when they are finalized and not still proposed since they are still under development/clarification. It looks like extensions which use proposed APIs are only capable of successfully running on their  [Insiders](https://code.visualstudio.com/api/advanced-topics/using-proposed-api#using-proposed-api) build.

The `vscode.workspace.findTextInFiles` is still a proposed API as of https://github.com/microsoft/vscode/commit/3d9eab77d318490044ce27430053789638cf4535:

- https://github.com/microsoft/vscode/blob/061f4967f9d10172d61a149bbdfa9322f3a7ea01/src/vs/vscode.proposed.d.ts#L576-L665

**Comment by nmorenor** [comment]
So I was trying to get this to work. However I just got stuck at some error while running yarn, the code compiles (changes) but while building the electron/browser examples it just fails. 

Here is the link of the change I'm trying: 
https://github.com/Genuitec/theia/commit/777b9191b5deca2199eacda9245cb51223c6c174

And this is a bit of the error I get while trying to run yarn:

```
WARNING in /Users/nacho/Development/codetogether/theia/node_modules/vscode-textmate/release/main.js 23:15-27
Critical dependency: the request of a dependency is an expression
 @ /Users/nacho/Development/codetogether/theia/packages/monaco/lib/browser/textmate/monaco-textmate-service.js
 @ /Users/nacho/Development/codetogether/theia/packages/monaco/lib/browser/textmate/index.js
 @ /Users/nacho/Development/codetogether/theia/packages/plugin-ext/lib/main/browser/plugin-contribution-handler.js
 @ /Users/nacho/Development/codetogether/theia/packages/plugin-ext/lib/hosted/browser/hosted-plugin.js
 @ /Users/nacho/Development/codetogether/theia/packages/vsx-registry/lib/browser/vsx-extensions-model.js
 @ /Users/nacho/Development/codetogether/theia/packages/vsx-registry/lib/browser/vsx-registry-frontend-module.js
 @ ./src-gen/frontend/index.js

WARNING in /Users/nacho/Development/codetogether/theia/node_modules/vscode-textmate/release/main.js
Module Warning (from /Users/nacho/Development/codetogether/theia/node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'main.js.map': Error: Can't resolve './main.js.map' in '/Users/nacho/Development/codetogether/theia/node_modules/vscode-textmate/release'
 @ /Users/nacho/Development/codetogether/theia/packages/monaco/lib/browser/textmate/monaco-textmate-service.js 76:24-50
 @ /Users/nacho/Development/codetogether/theia/packages/monaco/lib/browser/textmate/index.js
 @ /Users/nacho/Development/codetogether/theia/packages/plugin-ext/lib/main/browser/plugin-contribution-handler.js
 @ /Users/nacho/Development/codetogether/theia/packages/plugin-ext/lib/hosted/browser/hosted-plugin.js
 @ /Users/nacho/Development/codetogether/theia/packages/vsx-registry/lib/browser/vsx-extensions-model.js
 @ /Users/nacho/Development/codetogether/theia/packages/vsx-registry/lib/browser/vsx-registry-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in /Users/nacho/Development/codetogether/theia/packages/plugin-ext/lib/main/browser/workspace-main.js
Module not found: Error: Can't resolve '@theia/plugin' in '/Users/nacho/Development/codetogether/theia/packages/plugin-ext/lib/main/browser'
 @ /Users/nacho/Development/codetogether/theia/packages/plugin-ext/lib/main/browser/workspace-main.js 92:12-36
 @ /Users/nacho/Development/codetogether/theia/packages/plugin-ext/lib/main/browser/main-context.js
 @ /Users/nacho/Development/codetogether/theia/packages/plugin-ext/lib/hosted/browser/hosted-plugin.js
 @ /Users/nacho/Development/codetogether/theia/packages/vsx-registry/lib/browser/vsx-extensions-model.js
 @ /Users/nacho/Development/codetogether/theia/packages/vsx-registry/lib/browser/vsx-registry-frontend-module.js
 @ ./src-gen/frontend/index.js
```

Any ideas or pointer on how to solve this?

Cheers

**Comment by nmorenor** [comment]
The issue looks to be on how `WorkspaceMainImpl` is trying to use the `ISearchInWorkspaceService` if I comment the reference to that interface I get no errors. :|
