### ISSUE TITLE
Timeline API

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7577]
### Description
 
Support Timeline API (beta now).

### Reproduction Steps

VS Code Insiders has a proposed API for timelines. [this extension](https://github.com/JacksonKearl/vscode-solunar-timeline) can be used for testing .
Maybe this API can only be implemented when VS Code adds it into stable.

**OS and Theia version:**
Any

**Diagnostics:** 

No

**Comment by akosyakov** [comment]
We have to implement the widget first in `@theia/scm` after that connect it with VS Code APIs in `@theia/plugin-ext`.

**Comment by sh7dm** [comment]
@akosyakov it shouldn't be bound to scm, maybe another extension is required.

**Comment by akosyakov** [comment]
ok, something like `@theia/timeline` sounds good as well.

**Comment by sh7dm** [comment]
Great! Not only SCMs can provide timeline data. I think this extension should provide both Theia internal API for extensions to connect to as well as VS Code compliant API for plugins, is this correct? Or only VS Code API will be enough?

**Comment by akosyakov** [comment]
`@theia/timeline` should provide API for extensions it is correct, wiring to VS Code API should be done `@theia/plugin-ext`. APIs should be aligned though.

**Comment by sh7dm** [comment]
As I've seen from VS Code source, only APIs for Timelines are types and `workspace.registerTimelineProvider`.

**Comment by sh7dm** [comment]
@akosyakov Looks like existing History View is good for it, maybe with some changes.

**Comment by akosyakov** [comment]
@sh7dm Yes, it could be used as the basis. @westbury would it be fine?

**Comment by sh7dm** [comment]
TODO for converting History to Timeline (@ maintainers feel free to update):
- [ ] Add icons support
- [ ] Add VS Code compatible API
More actions me be required too.
