### ISSUE TITLE
JAVA dependencies missing when using version 0.9.0 from open-vsx registry

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7584]
### Description
 
Using vscode-java-dependency-viewer.vsix version 0.9.0  (From https://open-vsx.org/api/vscjava/vscode-java-dependency/0.9.0/file/vscjava.vscode-java-dependency-0.9.0.vsix) does not show the icon anymore. Using an older version  (0.6.0) works fine. This is a regression.

### Reproduction Steps

- Use a JAVA project with latest Theia
- Install  vscode-java-dependency-viewer.vsix version 0.9.0  (From https://open-vsx.org/api/vscjava/vscode-java-dependency/0.9.0/file/vscjava.vscode-java-dependency-0.9.0.vsix)
--> verify the icon in the java dependencies are missing
- Install (for testing purpose an older version : https://github.com/microsoft/vscode-java-dependency/releases/download/0.6.0/vscode-java-dependency-0.6.0.vsix) 
--> verify the icon in the JAVA dependency view, they are displayed

**OS and Theia version:**
OS: Ubuntu 18.04
Tested with Chrome
Theia latest ( commit 46f5a08a540fbace521315fbe8c23de8a6b3c92c )

**Diagnostics:** 

Error reported:
root ERROR Could not transfer '$(refresh)' file from 'vscjava_vscode_java_dependency' Error: ENOENT: no such file or directory, stat '/home/lmcbout/.theia/extensions/vscjava.vscode-java-dependency-0.9.0/extension/$(refresh)'
root ERROR Could not transfer '$(list-tree)' file from 'vscjava_vscode_java_dependency' Error: ENOENT: no such file or directory, stat '/home/lmcbout/.theia/extensions/vscjava.vscode-java-dependency-0.9.0/extension/$(list-tree)'

**Comment by vince-fugnitto** [comment]
@lmcbout please update the referenced links, they are broken.

**Comment by lmcbout** [comment]
Link fixed, pointing to the folder

**Comment by vince-fugnitto** [comment]
> Link fixed, pointing to the folder

The correct link would be: https://open-vsx.org/extension/vscjava/vscode-java-dependency

**Comment by lmcbout** [comment]
Link updated to point to the specific plugin

**Comment by vince-fugnitto** [comment]
There are no issues in rendering icons anymore. Tested with newer versions of the plugin.
