### ISSUE TITLE
Download plugins does not unzip the ...tar.gz

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7588]
### Description
 
Use MAVEN from github repository and the plugins does not get unpacked. It is a package.tar.gz

### Reproduction Steps

- Add in you package.json the following:
  "vscode-maven": "https://github.com/microsoft/vscode-maven/archive/v0.21.0.tar.gz"
Test 1:
yarn download:plugins
--> vscode-maven.tar.gz is downloaded but not unzip
Test 2:
- Open a JAVA project using maven
- The extension did not start since the package does not unpacked in the plugin folder

**OS and Theia version:**
Ubuntu 18.04

**Diagnostics:** 

root ERROR Failed to load plugin dependencies from '/home/lmcbout/theia/ericsson/gitlab/theia-bdgs/electron/dist/linux-unpacked/resources/app/plugins/vscode-maven.tar.gz' path Error: ENOENT: no such file or directory,

**Comment by vince-fugnitto** [comment]
@lmcbout looking at the result of the `yarn download:plugins` script, the unpacking does occur:

```
┌─[±][master U:1 ✗][theia][]
└─▪ ls -al plugins/
total 0
drwxr-xr-x   3 vincentfugnitto  staff    96 15 Apr 17:38 .
drwxr-xr-x  34 vincentfugnitto  staff  1088 15 Apr 17:38 ..
drwxr-xr-x   3 vincentfugnitto  staff    96 15 Apr 17:38 vscode-maven
```

It does not work well since you should not be using a tar of the source code but rather a properly packaged **.vsix** when referencing plugins.

**Comment by akosyakov** [comment]
I think there is nothing can be done. Provided link does not point to correct vsix file.

**Comment by lmcbout** [comment]
>It does not work well since you should not be using a tar of the source code but rather a properly packaged .vsix when referencing plugins.

@vince-fugnitto where can I get a maven.vsix version 0.21.0 which does not comes from microsoft marketplace, but from github. The version 0.21.2 from open-vsx has incompatibility for the context menu with Theia 1.0

**Comment by vince-fugnitto** [comment]
> > It does not work well since you should not be using a tar of the source code but rather a properly packaged .vsix when referencing plugins.
> 
> @vince-fugnitto where can I get a maven.vsix version 0.21.0 which does not comes from microsoft marketplace, but from github. The version 0.21.2 from open-vsx has incompatibility for the context menu with Theia 1.0

If no version exists, then you should publish one yourself.
For example, we did so for [theia-ide/vscode-eslint](https://github.com/theia-ide/vscode-eslint) in the past.

**Comment by akosyakov** [comment]
Can you download it from the Open VSX Registry: https://open-vsx.org/api/vscjava/vscode-maven/0.21.2/file/vscjava.vscode-maven-0.21.2.vsix?

**Comment by lmcbout** [comment]
I can download it from https://open-vsx.org/api/vscjava/vscode-maven/0.21.2/file/vscjava.vscode-maven-0.21.2.vsix but it generates an error when I used the context menu "Install"
 Refer to issue #7586
