### ISSUE TITLE
File search doesn't open files as preview

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7589]
### Description
When you click (1 time) on any search result, the file is opened in edit mode, not preview one.

### Reproduction Steps
1. `Ctrl` + `Shift` + `F`
2. Search for anything
3. Click on a result

**OS and Theia version:**
OS: Ubuntu 19.10
Theia: `master`

**Diagnostics:**

**Comment by akosyakov** [comment]
It should be easy to fix by passing `preview: true` in the opener options.

**Comment by sh7dm** [comment]
@akosyakov if so, please add `good first issue` or another beginner-friendly label to it.

**Comment by akosyakov** [comment]
I think this line should be changed: https://github.com/maksimr/theia/blob/eabdf8800811c56435c499b84792f360616e360c/packages/search-in-workspace/src/browser/search-in-workspace-result-tree-widget.tsx#L708

But please pay attention there is some `preview` flag. It could be worth to test different paths leading to this code with different `preview` value.

cc @vince-fugnitto @elaihau @marechal-p I remember you tried to improve it last time?

**Comment by vince-fugnitto** [comment]
I thought such a behavior would not be possible without coupling `search-in-workspace` with `editor-preview` (if we want to have previewable editors which are updated upon new selections in the tree). I also think this behavior will not work if a application-developer does not explicitly depend on `editor-preview`.

**Comment by sh7dm** [comment]
@vince-fugnitto what's about dynamical detection of required services and using preview if it's available? Sorry if it's impossible, didn't dig into those parts of code.

**Comment by akosyakov** [comment]
You don't need to add a dependency. If `editor-preview` is not installed then `preview` flag will be ignored.

**Comment by ronabet** [comment]
> It should be easy to fix by passing `preview: true` in the opener options.
@akosyakov 
I checked it and it didn`t solve the issue.
