### ISSUE TITLE
Warn before closing a terminal

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7590]
### Description
Show a warning if user attempts to close a terminal which has running processes in it.

### Reproduction Steps
1. Run a command (e.g. `top`) in Theia terminal and any other one.
2. Close both terminals

**OS and Theia version:**
OS: Ubuntu 19.10
Theia: `master`

**Diagnostics:**

**Comment by akosyakov** [comment]
I am not sure whether it is possible. Terminals are stream based, we don't really know what a user is doing. We could have something like that for tasks.

cc @elaihau @RomanNikitenko @marechal-p ?

**Comment by marechal-p** [comment]
I think a new internal method was added to test if a shell has a subprocess running (meaning the shell is in use). See https://github.com/eclipse-theia/theia/blob/master/packages/terminal/src/node/shell-terminal-server.ts#L66-L88

**Comment by elaihau** [comment]
> I think a new internal method was added to test if a shell has a subprocess running (meaning the shell is in use). See https://github.com/eclipse-theia/theia/blob/master/packages/terminal/src/node/shell-terminal-server.ts#L66-L88

+1

**Comment by akosyakov** [comment]
We should check though it does not break VS Code extensions. If they can close terminal programmatically then there should not be such dialogs. Maybe also make it configurable via preferences.

**Comment by sh7dm** [comment]
@akosyakov right, it should work only when clicking `X` button manually, not by commands. Preference should be added as well, but its default must prevent closing.
