### ISSUE TITLE
Add "Inspect TM scopes" command

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7606]
### Description
Add "Inspect TM scopes" for debugging themes and editor like in VS Code.

### Reproduction Steps
1. Open quick menu
2. Try to find `Inspect TM scopes` command

**OS and Theia version:**
OS: Ubuntu 19.10
Theia: `master`

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@sh7dm is the same as triggering the command `Developer: Inspect Tokens`?

<div align='center'>

<img width="1197" alt="Screen Shot 2020-04-18 at 10 16 32 AM" src="https://user-images.githubusercontent.com/40359487/79640108-b6f9fe80-815d-11ea-9743-4aa30483fff1.png">


</div>

**Comment by sh7dm** [comment]
It is. Sorry for spam.

**Comment by vince-fugnitto** [comment]
> It is. Sorry for spam.

I don't think it's spam :) the command in vscode is named differently, it should help to align:

- **theia**: 'Developer: Inspect Tokens'
- **vscode**: 'Developer: Inspect Editor Tokens and Scope'

In addition, VS Code includes textmate scopes which we do not:

<div align='center'>

<img width="602" alt="Screen Shot 2020-04-18 at 10 22 18 AM" src="https://user-images.githubusercontent.com/40359487/79640255-8c5c7580-815e-11ea-9b38-ca5ec47a46a1.png">


</div>

**Comment by sh7dm** [comment]
Isn't the line on the bottom the TM scopes line?
![image](https://user-images.githubusercontent.com/19504461/79640320-a10a2f00-8199-11ea-9377-36abeb029dd2.png)
The missing in Theia thing is contrast ratio, that is really useful for theme developers.

**Comment by vince-fugnitto** [comment]
> Isn't the line on the bottom the TM scopes line?

Ahh you're right, I thought we could improve the following however:
- the naming of the command
- the presentation in the overlay (granted that we have control over it), to better align with vscode
- adding the missing properties

**Comment by akosyakov** [comment]
This is coming from Monaco. I don't think we can change it.

**Comment by vince-fugnitto** [comment]
> This is coming from Monaco? I don't think we can change it.

I wasn't sure, I thought that maybe we could do something custom like vscode did:
- [vscode/inspectTokens.ts](https://github.com/microsoft/vscode/blob/master/src/vs/editor/standalone/browser/inspectTokens/inspectTokens.ts)
- [vscode/inspectEditorTokens.ts](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/codeEditor/browser/inspectEditorTokens/inspectEditorTokens.ts)

**Comment by vince-fugnitto** [comment]
> This is coming from Monaco? I don't think we can change it.
