### ISSUE TITLE
Better welcome page

### ISSUE THREAD

**Issue by sh7dm** [eclipse-theia/theia#7609]
### Description
1. Welcome page looks incomplete, at least for me. I think it should have multi-column design like VS Code has, with more space between items.
2. There isn't a placeholder on empty screen:
![image](https://user-images.githubusercontent.com/19504461/79689849-16403780-8260-11ea-80e2-42e4044bf010.png)
vs
![image](https://user-images.githubusercontent.com/19504461/79689855-21936300-8260-11ea-8ec1-92229eba996b.png)
It'll be great if there were some keybindings to get started with, like there are in VS Code.

### Reproduction Steps
See `Description`

**OS and Theia version:**
Doesn't matter

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
> 1. Welcome page looks incomplete, at least for me. I think it should have multi-column design like VS Code has, with more space between items.

The current 'Getting Started' page is a template or default implementation, applications can extend it to provide their own styling, design, and items. If they want a multi-column display they can most certainly do so.

> 2. There isn't a placeholder on empty screen:

This is also possible for downstream applications, they can provide custom placeholder content when there are empty screens, see the following for [example](https://github.com/vince-fugnitto/theia-cpp-branding):


<div align='center'>

<img src='https://raw.githubusercontent.com/vince-fugnitto/theia-cpp-branding/master/assets/light-screenshot.png' />

</div>

**Comment by sh7dm** [comment]
I know about that. Theia should provide better defaults while preserving the ability to change them.

**Comment by vince-fugnitto** [comment]
> I know about that. Theia should provide better defaults while preserving the ability to change them.

Is there something wrong with the defaults the framework provides?

**Comment by sh7dm** [comment]
Nothing really "wrong", but something can be improved. Theia Browser/Electron Example should be a useable IDE, it is a usable IDE.

**Comment by vince-fugnitto** [comment]
> Nothing really "wrong", but something can be improved. 

We should decide on what/why the defaults need to be improved, saying "something can be improved", and "it looks incomplete to me" are not helpful in making that decision.

> Theia Browser/Electron Example should be a useable IDE, it is a usable IDE.

I'm not sure what you're trying to say.

**Comment by sh7dm** [comment]
You're right. Let the users customize that.
