### ISSUE TITLE
The Git diff editor should show the changed files as a tree

### ISSUE THREAD

**Issue by westbury** [eclipse-theia/theia#7616]
### Description

https://github.com/eclipse-theia/theia/pull/7505 replaces the list in the Source Control view with a tree.  The same should be done for the Git diff editor.

### Reproduction Steps

Press the 'eye' icon on a commit in the History view to open the diff editor.

**Comment by akosyakov** [comment]
@westbury no chance that you will work on it?

**Comment by westbury** [comment]
> @westbury no chance that you will work on it?

Yes, by next week.
