### ISSUE TITLE
Annoying text at the top of the editor

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7623]
Initially reported for Gitpod: https://github.com/gitpod-io/gitpod/issues/1406
Steps to reproduce: https://github.com/gitpod-io/gitpod/issues/1406#issuecomment-615315543

We need to figure what are these features about and then see whether we can make them work nicely or disable them.

**Comment by kittaakos** [comment]
I assume it is the same as https://github.com/eclipse-theia/theia/issues/7411

Please reopen if I was wrong.
