### ISSUE TITLE
terminal: add context-menu

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7632]
### Description

We should include a terminal context-menu to include the following items:
- **Copy**
- **Paste**
- **Select All**
- **Clear** (clears the terminal output)
- **Split Terminal**
- **New Terminal**
- **Kill Terminal** (close terminal)

**Additional Info**
- 7d56c34

**Comment by vince-fugnitto** [comment]
I updated the issue to include the items that should be present in the menu (based on the items present in vscode). I don't think there is anything preventing us from adding the menu, and I think its a nice improvement for end-users over the current functionality.

**Comment by lmcbout** [comment]
Thanks @vince-fugnitto for the completion.

**Comment by VietHungPhan** [comment]
We should have a new Teal-IDE 1.1.0 release.
