### ISSUE TITLE
Support VS Code Standard Icons in Contributions

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7634]
It is reproducible with https://github.com/microsoft/vscode-java-test:
<img width="352" alt="Screenshot 2020-04-21 at 13 01 28" src="https://user-images.githubusercontent.com/3082655/79858839-51fa0f00-83d0-11ea-9587-1c595ecf18ef.png">

URLs like `hostedPlugin/vscjava_vscode_java_test/%24(refresh)`. It seems to be that it is not a path, but rather codicons.

**Comment by tsmaeder** [comment]
The well-know icons are described in the documentation: https://code.visualstudio.com/api/references/icons-in-labels

I've taken the liberty of updating the title; I think it better describes the issue.

**Comment by akosyakov** [comment]
@tsmaeder Are you fine if I look at it or you were planning?

**Comment by tsmaeder** [comment]
Please do, @akosyakov
