### ISSUE TITLE
investigate why typescript integration tests timesout sometimes

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7635]

**Comment by akosyakov** [comment]
fixed by https://github.com/eclipse-theia/theia/pull/7655

**Comment by akosyakov** [comment]
One TS test timed out again.

**Comment by amiramw** [comment]
I find also this one to fail sometime locally, not sure about CI:

root INFO   1) Find and Replace
       Replace in the active explorer with the current editor:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Test.Runnable._timeoutError (C:\Users\i066470\repos\theia\node_modules\mocha\mocha.js:5488:10)
      at C:\Users\i066470\repos\theia\node_modules\mocha\mocha.js:5301:24

**Comment by akosyakov** [comment]
> I find also this one to fail sometime locally, not sure about CI:

@amiramw Could you file another issue? I have not seen it failing on Linux. I guess it is Windows related somehow.
