### ISSUE TITLE
How to dowload, there is no link for download exe/msi

### ISSUE THREAD

**Issue by gsmental** [eclipse-theia/theia#7637]

**Comment by vince-fugnitto** [comment]
Please see the following discussion: https://github.com/eclipse-theia/theia/issues/5481

**Comment by gsmental** [comment]
there is nothing for end-user. :-(

**Comment by vince-fugnitto** [comment]
> there is nothing for end-user. :-(

Theia is a framework, I’m not quite sure what you’d like to download.
