### ISSUE TITLE
wakatime not initialised

### ISSUE THREAD

**Issue by cedric-r-mycelium** [eclipse-theia/theia#7647]
### Description
i have installe wakatime extensions for vscode on theia but it always on initializing and i have this notification error: 
Activating extension Remote - WSL failed:
n.workspace.registerRemoteAuthorityResolvers is not a function.

### Reproduction Steps
Just install plugin on theia plugin directory
an load theia after set api key for wakatime i have the error.

**OS and Theia version:**
ubuntu 18.04 theia 1.1.0-next

**Comment by akosyakov** [comment]
I am not sure whether it makes sense for us to implement `registerRemoteAuthorityResolvers`. Maybe we just stub it? cc @benoitf ?

**Comment by akosyakov** [comment]
@cedric-r-mycelium Are you talking about this extension: https://github.com/wakatime/vscode-wakatime It does not seem to have any calls to `registerRemoteAuthorityResolvers`.

**Comment by cedric-r-mycelium** [comment]
I am so sorry for my mistake,  it's another plugins who made the first error.

But i have this error on screen log "root ERROR [hosted-plugin: 14648] [WakaTime][ERROR] Error: Command failed: /home/cedric.r/theia/plugins/wakatime.vscode-wakatime-4.0.0/wakatime-cli/wakatime-cli --today --plugin "vscode/1.44.0 vscode-wakatime/4.0.0"

but if i run this command myself no error reported.

**Comment by akosyakov** [comment]
What do you do to reproduce it? I tried in Gitpod and seen something like `Error: could not read /home/gitpod/.wakatime.cfg`.  But it seems to be fine there are code in the extension which can lead to race on the activation. But I could not see your error.

**Comment by cedric-r-mycelium** [comment]
I have found the problem, it's an error on copy of api key, thanks for your help !!!

**Comment by akosyakov** [comment]
@cedric-r-mycelium Just to confirm. Is there anything that can be done from our side or this issue can be closed?

**Comment by cedric-r-mycelium** [comment]
You can close this isssue all is ok for me

**Comment by akosyakov** [comment]
ok, please feel free to reopen
