### ISSUE TITLE
Remap capslock to esc

### ISSUE THREAD

**Issue by havogt** [eclipse-theia/theia#7654]
### Bug Description:
If I remap `capslock` to `esc` in Linux, the remapping is ignored in theia (gitpod). It is still triggering a capslock event (verified by having a key sequence with capslock: I get `(Capslock) was pressed, waiting for more keys` in the status bar).

Note that this is also a problem in vscode, however there is a work-around by setting `"keyboard.dispatch": "keyCode"`, see https://github.com/microsoft/vscode/issues/23991.

### Steps to Reproduce:

1. Remap `capslock` to `esc`, e.g. `setxkbmap -option caps:escape`
2. Hit `capslock` doesn't do `esc`

### Additional Information

- Operating System: Linux (OpenSuse)
- Theia Version: gitpod version as of today

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/8609.
