### ISSUE TITLE
[Plugin-Api] Apply authentication API

### ISSUE THREAD

**Issue by vinokurig** [eclipse-theia/theia#7661]
Apply `authentication` VsCode Plugin API. Is needed for [vscode-github-pr-plugin](https://github.com/microsoft/vscode-pull-request-github) authentication.

### Feature Description:
VsCode implementation: https://github.com/microsoft/vscode/blob/ab42ffc44c709aded523b15399a070ae8c724824/src/vs/vscode.proposed.d.ts#L98-L131

**Comment by akosyakov** [comment]
That's still a proposed API: https://github.com/microsoft/vscode/issues/88309

**Comment by vinokurig** [comment]
The Github PR plugin already uses it in last 3 releases: https://github.com/microsoft/vscode-pull-request-github/blob/ea819cdf03e49322d2eaf0b81edcf0098f5986b3/src/github/credentials.ts#L52

**Comment by vinokurig** [comment]
Is fixed by https://github.com/eclipse-theia/theia/pull/8402
