### ISSUE TITLE
SQLTools connection details disappears after refreshing the browser.

### ISSUE THREAD

**Issue by ShimonBenYair** [eclipse-theia/theia#7669]
After adding a new connection (for example sqlite/hana) it is being saved in the settings.json and is displayed, but after refresh it disapprears.

### Steps to Reproduce:

1. Run theia locally : docker run -it -p 3000:3000 theiaide/theia:0.16.1
2. Open browser: http://localhost:3000/
3.  Download sqltools-0.21.6.vsix  from: https://github.com/mtxr/vscode-sqltools/releases
4. Drag sqltools-0.21.6.vsix to /home/project 
5. Deploy sqltools to theia: F1 --> Plugin: Deploy Plugin by Id and enter local-dir:/home/project (the place where you have dragged the vsix).
6.  Add connections to settings.json: File-> Open Preferences -> Workspace
{ "sqltools.connections": [ { "dialect": "SAPHana", "port": 30041, "server": "127.0.0.1", "username": "SBSS_65777809047259144689506533332535056682063655272136883233100863223", "database": "6DD598386E64465DB5F936BDAC639D6C", "password": "Oc8l92nQ6b1._Pgs0WED96xNz_81N1rT0bDMQxPq.Klt_IXR2amIwwUEBglwsTH60ZzXbQfApOmIN4OtVM.X4Ud2rVyHBL59ZvsHak1ED3CbIxnlnJpfXIXzUXeYjnsI", "name": "connection_liat_simple_db" }, { "name": "sqlite", "dialect": "SQLite", "database": "./testdb.db" } ] }
7. you can see the connections in the SQL Tools pane as expected
8. Refresh the page and these connections disappear!

Expected behavior
Expecting the connections to still be displayed in the SQL Tools pane.
The settings themselves in the settings.json exists but are just not being displayed in the UI.

### please see scenario gif attached : 
![refreshissuesqltools](https://user-images.githubusercontent.com/18531202/80303696-6f591f80-87ba-11ea-9102-f83c5a55c21e.gif)

- Operating System: Linux
- Theia Version: 0.16.1 and also 1.0.0
in VSCode it works ok

**Comment by akosyakov** [comment]
@ShimonBenYair Could you please try against this branch: https://github.com/eclipse-theia/theia/pull/6921 There is one nasty bug with reading subsections in the plugin host process: https://github.com/eclipse-theia/theia/pull/6921/commits/5cd954375ae4a600d7db16c5a0ae2f137ef37d74 Maybe it helps, if not someone has to debug the extension and see what we do differently.

**Comment by ShimonBenYair** [comment]
@akosyakov 

thanks , i have checked it with the branch you proposed but this issue still occurs

**Comment by ShimonBenYair** [comment]
After invastigating the issue i have found the root cause and it is from the extension and not from Theia.

**Comment by wibrt** [comment]
Hello, 
i tried more or less the same:

1. docker run -it -p 3000:3000 theiaide/theia
2. Open browser: http://localhost:3000/
3. Browsed and search the plugins on the left side
4. Click on install sqltools
5. Two database icons appear on the left
6. Unable to add a new connections by clicking on 'add new connection'.
7. Any suggestions?

![image](https://user-images.githubusercontent.com/17875724/113279148-11df2400-92e3-11eb-8e17-70310b3589ec.png)
