### ISSUE TITLE
[plugin] fetching tasks is slow for big multi-root workspaces

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7672]
`validateSchema` should be computed once and cached

but I am not sure that we need it at all, does VS Code validate task configs? 

We removed such logic already for preferences, since it is slow and VS Code does not care about.

cc @elaihau @RomanNikitenko

**Comment by akosyakov** [comment]
<img width="1692" alt="Screenshot 2020-04-27 at 13 57 00" src="https://user-images.githubusercontent.com/3082655/80369701-fd9ed580-888e-11ea-8195-365222b38992.png">

Actually performance seems to be super bad in multi-root workspace.

I created with the following workspace in Gitpod based on this repo (please adjust paths in your environments):
```json
{
   "folders": [
      {
         "path": "file:///workspace/theia"
      },
      {
         "path": "file:///workspace/theia/dev-packages"
      },
      {
         "path": "file:///workspace/theia/plugins"
      },
      {
         "path": "file:///workspace/theia/examples"
      },
      {
         "path": "file:///workspace/theia/scripts"
      },
      {
         "path": "file:///workspace/theia/node_modules"
      }
   ],
   "settings": {}
}
```

After that reload page and try to traverse the explorer. UI hangs almost for half a minute.

**Comment by akosyakov** [comment]
I was able to reproduce it with a bit of customizations JLab project:
- check out https://github.com/jupyterlab/jupyterlab
- create `.vscode/tasks.json` with the following content in the project root
```json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "build",
      "problemMatcher": [
        "$tsc"
      ]
    }
  ]
}
```
- create a multi-root workspace from this JSON (replace `file:///workspace` with your absolute path) :
```json
{
   "folders": [
      {
         "path": "file:///workspace/jupyterlab"
      },
      {
         "path": "file:///workspace/jupyterlab/dev_mode"
      },
      {
         "path": "file:///workspace/jupyterlab/examples"
      },
      {
         "path": "file:///workspace/jupyterlab/packages"
      },
      {
         "path": "file:///workspace/jupyterlab/packages/services/examples/node"
      },
      {
         "path": "file:///workspace/jupyterlab/packages/services/examples/browser"
      },
      {
         "path": "file:///workspace/jupyterlab/packages/services/examples/typescript-browser-with-output"
      },
      {
         "path": "file:///workspace/jupyterlab/buildutils"
      },
      {
         "path": "file:///workspace/jupyterlab/buildutils/template"
      },
      {
         "path": "file:///workspace/jupyterlab/buildutils/buildutils/test-template"
      },
      {
         "path": "file:///workspace/jupyterlab/tests"
      },
      {
         "path": "file:///workspace/jupyterlab/testutils"
      },
      {
         "path": "file:///workspace/jupyterlab/jupyterlab/tests/mock_packages/extension"
      }
   ],
   "settings": {}
}
```
- start Theia and pass the path to the multi-root workspace
- try to navigate in the explorer, till npm scripts appear
- notice how sluggish it is and how long does it take for npm scripts to appear

The profiling snapshot: https://drive.google.com/file/d/1pyCUMaGm-7scjJ-KMqHmfm2gINs6BdVx/view?usp=sharing

There are 2 hot spots:
- `isTaskConfigValid` (it only happens if you have tasks.json)
<img width="1692" alt="Screenshot 2020-04-27 at 14 59 41" src="https://user-images.githubusercontent.com/3082655/80374988-d39de100-8897-11ea-82da-b19739eedd38.png">
- comparing tasks in `$fetchTasks` from the plugin system:
<img width="1692" alt="Screenshot 2020-04-27 at 14 59 51" src="https://user-images.githubusercontent.com/3082655/80374996-d8629500-8897-11ea-9b1b-5569feb58cc7.png">

**Comment by akosyakov** [comment]
`isTaskConfigValid` is handled in https://github.com/eclipse-theia/theia/pull/7676

**Comment by akosyakov** [comment]
@elaihau Do you know how to test whether we need to call `compareTasks` in `$fetchTasks`? I wonder do we need it at all or we simply should return all tasks? How did you validate VS Code extensions' expectations?

**Comment by akosyakov** [comment]
VS Code does not remove duplicate, it returns all tasks: 
<img width="991" alt="Screenshot 2020-04-28 at 10 35 14" src="https://user-images.githubusercontent.com/3082655/80465831-000b3900-893c-11ea-86f4-d0eeca27891b.png">

I does not look like `$fetchTasks` is aligned with VS Code extensions' expectations

**Comment by elaihau** [comment]
> @elaihau Do you know how to test whether we need to call `compareTasks` in `$fetchTasks`? I wonder do we need it at all or we simply should return all tasks? How did you validate VS Code extensions' expectations?

If we don't want to 
- take care of identical tasks, or
- filter out the invalid task configs,
we probably can make `$fetchTasks()` a lot faster

I took a look at the `$fetchTasks()` function in `tasks-main.ts` and noticed that it does not take the cutomized detected tasks into consideration.
Say, you have `npm: build` defined in `package.json`, and customize it in `tasks.json` this way:
```
{
  "type": "npm",
  "script": "build",
  "label": "Build the project"
}
```

The current `$fetchTasks()` simply returns the `npm: build` - the label you added to the task (i.e., "Build the project") is not taken care of. Do we want to keep it this way? @akosyakov

**Comment by akosyakov** [comment]
> If we don't want to take care of identical tasks, or filter out the invalid task configs, we probably can make $fetchTasks() a lot faster

I've simplified it in https://github.com/eclipse-theia/theia/pull/7676/commits/aba5392b106f2b66b1431b8b51d5d7bfa1282bd0 Could you have a look there? But it only to make it faster it does not make sure that it aligned with VS Code extensions' expectations.

> I took a look at the $fetchTasks() function in tasks-main.ts and noticed that it does not take the cutomized detected tasks into consideration.
Say, you have npm: build defined in package.json, and customize it in tasks.json this way:

I've opened https://github.com/eclipse-theia/theia/issues/7681 for VS Code compatibility. Ideally results should be aligned as much as possible. But you can also try to investigate whether it worth it. Let's have a look at it separate from performance optimisations.

**Comment by elaihau** [comment]
> I've simplified it in [aba5392](https://github.com/eclipse-theia/theia/commit/aba5392b106f2b66b1431b8b51d5d7bfa1282bd0) Could you have a look there? But it only to make it faster it does not make sure that it aligned with VS Code extensions' expectations.

@akosyakov 
Sorry for the late response.
I believe we missed the part that avoids duplications.

I tried it in vscode with an extension.
If a detected task is configured in `tasks.json`, fetchTasks() in vscode returns one task.
In the current Theia, it returns both.

However, in vscode, same tasks, or tasks with same labels, can be contributed by different providers multiple times.

Do you want me to create an issue for it?

**Comment by akosyakov** [comment]
@elaihau It should be covered by doing https://github.com/eclipse-theia/theia/issues/7681. That we have broken tests if we miss something again.
