### ISSUE TITLE
VS Code debuggers using resolveDebugConfigurationWithSubstitutedVariables do not launch

### ISSUE THREAD

**Issue by DanTup** [eclipse-theia/theia#7690]
I'm trying to track down an issue with debug sessions in the Dart VS Code extension not launching, and my suspicion is that it's due to us switching to using `resolveDebugConfigurationWithSubstitutedVariables` (see https://github.com/microsoft/vscode/issues/87450).

VS Code now calls `resolveDebugConfiguration` as it previously did, then it resolves any variables (for example `${file}`, `${workspaceFolder}` etc.) and then calls `resolveDebugConfigurationWithSubstitutedVariables`. I think the code doing this is https://github.com/microsoft/vscode/blob/921b9a92a1b662fbe3aa21f47b0f8ed1fd89c947/src/vs/workbench/contrib/debug/browser/debugService.ts#L672-L685.

**Comment by akosyakov** [comment]
True, we don't support this API yet. Relevant PR in VS Code: https://github.com/microsoft/vscode/commit/dba0076c9fba7b857e7b4de96f5f46f4c004a412 PRs are welcomed.

**Comment by DanTup** [comment]
@akosyakov is there an easy way to tell when a change is included in production GitPod? I'm going to build an updated Dart extension today, and I'm trying to figure out if I still need a workaround for this.

**Comment by akosyakov** [comment]
@DanTup I'm planning to update Gitpod staging today. Do you have access to it? I can let you know. I don't know when it will make to production. cc @svenefftinge

**Comment by DanTup** [comment]
Yep, I think I do still have access to staging. The question was mainly whether I needed the workaround for production though - if it's not already live, I'll include it (I'm building a specific copy of the extension to make my GitPod/Flutter web sample work again with the latest release of Dart-Code for those that want to try it out). Thanks!

**Comment by DanTup** [comment]
@akosyakov what's the status of this - were you waiting for me to test on staging? I tried on live today, but this doesn't seem to be working (`resolveDebugConfiguration` is called, but `resolveDebugConfigurationWithSubstitutedVariables` is not).
