### ISSUE TITLE
upgrade to typescript 3.9

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7693]
`Promise.all` issues seems to be fixed: https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-rc/#promise-improvements

So it should be possible. cc @marechal-p @tsmaeder I though you mentioned that you want to do it when you have time.

**Comment by marechal-p** [comment]
Nope, still issues with our promises... But it seems fixable, I would have to look into it more.

**Comment by akosyakov** [comment]
I'm going to look into otherwise i have to change code copied from vscode extension host process and i don't want to deviate.
