### ISSUE TITLE
upgrade to Monaco 0.20.0

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7697]
It's required to support semantic highlighting, for instance to run latest rust extension: https://github.com/eclipse-theia/theia/issues/7608

There are 2 ways:
- do it after https://github.com/eclipse-theia/theia/issues/7100 (hopefully we do it in next 2 
months)
- do it as the previous Monaco migration, see TODOs and tests in https://github.com/eclipse-theia/theia/pull/7149
  - there is already a PR for monaco-languageclient: https://github.com/TypeFox/monaco-languageclient/pull/207

**Comment by azatsarynnyy** [comment]
Hi @akosyakov 
probably, we (at Red Hat) can work on it starting next week, by doing it as the [previous Monaco migration](https://github.com/eclipse-theia/theia/issues/6900).
I'll let you know here by Friday, May 8.

**Comment by azatsarynnyy** [comment]
We need a couple of more days to finalize our plans for May. So, I will come back next week with more accurate dates.

**Comment by azatsarynnyy** [comment]
We'll work on it during May. Most likely, starting next week.

**Comment by leo-lb** [comment]
Cool! Thanks @azatsarynny - rust-analyzer support (requiring newer Monaco) will be awesome!!

**Comment by azatsarynnyy** [comment]
@leo-lb I wonder are you interested in some features of newer Monaco or more in Plugin APIs that we'll be able to implement after the upgrade?

**Comment by leo-lb** [comment]
@azatsarynnyy the latter - see: https://github.com/eclipse-theia/theia/issues/7608

**Comment by RomanNikitenko** [comment]
@akosyakov 
I'm ready to take this issue in progress, if you don't mind.

Please let me know if you have some things I should pay attention.
From my side I remember:
- [this place](https://github.com/eclipse-theia/theia/blob/eeaf506e65c934642233a1d45e05231339bc4b30/packages/console/src/browser/console-widget.ts#L116)
-  hotfix for IME support

I'll add these items to my TODO list when I have the corresponding PR in `Theia`

**Comment by RomanNikitenko** [comment]
@akosyakov 
I see you published next version of `monaco-languageclient`. 

Can I ask you publish 0.20 version of `@theia/monaco-editor-core` when you have a chance.

Then I can apply these versions for `Theia` and open a draft PR for testing and adaptation.

**Comment by akosyakov** [comment]
@RomanNikitenko Hi, I will do tomorrow morning.

**Comment by akosyakov** [comment]
Published https://www.npmjs.com/package/@theia/monaco-editor-core/v/0.20.0 from https://github.com/theia-ide/vscode/commits/standalone/0.20.x

Recap for next time:
- clone https://github.com/theia-ide/vscode
- check out proper tag
```
git checkout --track origin/standalone/0.20.x
```
- sync latest changes from upstream tag
```
git reset --hard upstream/standalone/0.20.x
```
- disable tree-shaking: https://github.com/theia-ide/vscode/commit/f0c7c1abfa7b34c390a497eb92c55ade039b4801
- update monaco package.json: https://github.com/theia-ide/vscode/commit/b0b47123a5da83d42c2675f2bfff5bb9f1b2673c
- push all changes
```
git push -f
```
- run `yarn` to install dependencies
- prepare distribution with `/src/vscode> node_modules/.bin/gulp editor-distro`
- publish with `npm publish`

Relevant VS Code docs: https://github.com/microsoft/monaco-editor/blob/master/CONTRIBUTING.md#1-ship-a-new-monaco-editor-core-npm-module
