### ISSUE TITLE
Electron ContextMenuRenderer does not use passed-in anchor values

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#7722]
### Bug Description:
In #7105 we have refactored the context menu generation to use `ContextMenuRenderer`. However, in Electron, the context menu is not generated at the location provided using the `anchor` argument. On closer inspection, we noticed that https://github.com/eclipse-theia/theia/blob/cea62337848477b12b61ed7acf30634e12acc52d/packages/core/src/electron-browser/menu/electron-context-menu-renderer.ts#L28-L34 does not utilize this argument.

### Steps to Reproduce:

1. Pull latest changes to #7105
2. Build & Run in Electron
3. Open preferences UI with multiroot workspace
4. Click on Folder tab and observe context menu rendering under mouse-click rather than below dom-rect
5. Observe alternate (working) behavior in Browser

### Additional Information

- Operating System:
Linux (Ubuntu and RHEL)
- Theia Version:
Master

**Comment by akosyakov** [comment]
Yeah it was like that before refactoring. I was wondering why. Do you mind to send a PR?

**Comment by kenneth-marut-work** [comment]
@akosyakov 

Here is a PR that addresses the issue: #7735
