### ISSUE TITLE
flatpak packaging

### ISSUE THREAD

**Issue by devkral** [eclipse-theia/theia#7723]
It would be nice to have theia as a flatpak package

**Comment by devkral** [comment]
I think we can use this flatpak definition as base:
https://github.com/flathub/com.visualstudio.code.oss

**Comment by vince-fugnitto** [comment]
Thank you for the issue, please see relevant discussions about providing a vanilla distribution here:
- https://github.com/eclipse-theia/theia/issues/5481

Please also note that discussions were previously had about including a flatpack example for application-developers to reference as part of `theia-apps`:

- https://github.com/theia-ide/theia-apps/issues/341

**Comment by RasheedAZ** [comment]
> 
> Please also note that discussions were previously had about including a flatpack example for application-developers to reference as part of `theia-apps`:
> 
>     * [Flatpak app theia-ide/theia-apps#341](https://github.com/theia-ide/theia-apps/issues/341)

That repo is archived so perhaps this issue here needs to be reopened? Thanks.

**Comment by exfat-matt** [comment]
It would be great if this was revisited.  Flatpak has a number of technical advantages but the most important advantage it has is it is much more popular at this point.

**Comment by msujew** [comment]
Please continue discussion over at https://github.com/eclipse-theia/theia-blueprint/issues/360 for this topic. This repo is reserved for the development of the underlying Theia framework.
