### ISSUE TITLE
vscode extension johnstoncode.svn-scm does not work

### ISSUE THREAD

**Issue by GitMensch** [eclipse-theia/theia#7724]
While other .vsix I've tested in gitpod's theia work perfectly fine, it looks like https://github.com/JohnstonCode/svn-scm does not work correctly yet (you get the new button on the left but a bunch of "missing dependency" warnings and the UI controls of the plugin don't work).

**Comment by vince-fugnitto** [comment]
@GitMensch thank you for the issue, in the future please provide additional information so we can more accurately address the issue (ex: frontend logs, screenshots). Looking at the extension, it seems that there is a prerequisite to `svn`, is this included in your setup?

- https://github.com/JohnstonCode/svn-scm#prerequisites

**Comment by GitMensch** [comment]
I've used the plain theia "test on gitpod" which includes `svn`. Even if anyone with a gitpod login should be able to find it, it will likely be different soon and therefore still reasonable to add the requested info - how to get it after opening the workspace?

**Comment by akosyakov** [comment]
These extension rely on `keytar`, `iconv-lite` and `jschardet` dependencies: https://github.com/JohnstonCode/svn-scm/blob/00769abd81a75cfec56954d4e486ac5db6ed123c/src/vscodeModules.ts#L9-L33

It is similar to https://github.com/eclipse-theia/theia/issues/6407

**Comment by Ali-Libra** [comment]
I also have such a mistake, how should I solve it
![image](https://user-images.githubusercontent.com/67216143/145318811-69deca67-2b8f-4a11-bb84-a434e4b9bab7.png)

**Comment by simplast** [comment]
> 

yes ,today morning i got same error after vscode update!

**Comment by ChuYangshisan** [comment]
me to, how should I solve it
![image](https://user-images.githubusercontent.com/46879119/145328569-5619eb03-9cd7-4056-9380-c68a1e84f813.png)

**Comment by netsesame2** [comment]
me too. wait for reply

**Comment by littleCutePig** [comment]
![image](https://user-images.githubusercontent.com/44634462/145329425-a8c268de-ebf0-4a78-9b7c-320a86bde899.png)
一样，一样，怎么解决

**Comment by litium** [comment]
same here, not working since this morning

**Comment by yamaguchiweb** [comment]
I get the same error "No dependencies: jschardet". I can't use subversion from vscode.

**Comment by telk5093** [comment]
Same here after I have updated vscode 1.63.0

**Comment by GitMensch** [comment]
You guys confuse something: this is the issue Tracker for the Eclipse Theia IDE.
You likely want to create an issue in the vscode issue tracker instead.

... you may want to delete or at least hide the out-of-topic posts.

**Comment by NemanjaJovanovic98** [comment]
Try going to 'directory where is your vc code installed'/resources/app and doing npm install jschardet

**Comment by vince-fugnitto** [comment]
Thank you everyone but this is not the repository for the `ohnstoncode.svn-scm` extension itself, please refer and comment on the proper repo if you'd like to get it resolved:
- https://github.com/JohnstonCode/svn-scm/issues/1542
