### ISSUE TITLE
bug: menu fails to render

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7726]
### Bug Description:

The application's main-menu fails to render due to an error with **momentjs**:

```
logger-protocol.ts:112 root ERROR TypeError: moment is not a function
    at new BlameDecorator (http://localhost:9090/64.bundle.js:458:20)
    at _createInstance (http://localhost:9090/bundle.js:46628:12)
    at Object.resolveInstance (http://localhost:9090/bundle.js:46648:18)
    at http://localhost:9090/bundle.js:46745:42
    at Array.map (<anonymous>)
    at _injectProperties (http://localhost:9090/bundle.js:46618:57)
    at Object.resolveInstance (http://localhost:9090/bundle.js:46649:18)
    at http://localhost:9090/bundle.js:46745:42
    at Object.resolve (http://localhost:9090/bundle.js:46769:12)
    at http://localhost:9090/bundle.js:45731:37
```

<div align='center'>

<img width="1157" alt="Screen Shot 2020-05-02 at 6 43 35 PM" src="https://user-images.githubusercontent.com/40359487/80893974-de47e400-8ca4-11ea-97b4-7586ee98a137.png">

</div>

The following error has been reported and reproduced in a number of ways:
- docker images
- electron-builder apps
- 'composing applications' website guide
- spectrum

There is an issue where others have expressed similar breaking changes for **moment** and they performed the same rollback in version:
- https://github.com/moment/moment/issues/5507

### Steps to Reproduce:

There are numerous ways to produce the bug, one possible way is to run the docker image, or to compose your own application following the guide from the [website](https://theia-ide.org/docs/composing_applications/).

**Comment by vince-fugnitto** [comment]
We should have better handling in such situations (when a single menu item cannot be rendered), so we do not fail to create the entire menu.

**Comment by scheng123** [comment]
Also experiencing the same issue.
Reproduced with node version `v10.20.1`.
Followed all the steps with https://theia-ide.org/docs/composing_applications

**Comment by scheng123** [comment]
@vince-fugnitto do you currently have a workaround available?

**Comment by kittaakos** [comment]
Based on the [PR](https://github.com/eclipse-theia/theia/pull/7727), you can try to force the desired version of `moment`. I have not tried it yet; does it work if you add this to your root `packages.json`?
```json
"resolutions": {
  "**/**/moment": "2.24.0"
},
```

**Comment by scheng123** [comment]
It does work for me. We'll have to use this as a workaround until the maintainers fix the moment version.

(First time installing theia; I thought the broken UI was really the awesome ide everyone's happy about lamo)

**Comment by zhengfc** [comment]
> Based on the [PR](https://github.com/eclipse-theia/theia/pull/7727), you can try to force the desired version of `moment`. I have not tried it yet; does it work if you add this to your root `packages.json`?
> 
> ```json
> "resolutions": {
>   "**/**/moment": "2.24.0"
> },
> ```

It work for me too, ths

**Comment by akosyakov** [comment]
There are 2 things:
- guard such cases, i.e. the menu bar still should be there even if one command is missing
- fix a broken command

**Comment by scheng123** [comment]
I don’t think it was a missing command, as it is just a broken dependency.

**Comment by vince-fugnitto** [comment]
There is an issue where others have expressed similar breaking changes for **moment** and they performed the same rollback in version:
- https://github.com/moment/moment/issues/5507

**Comment by akosyakov** [comment]
@vinayb21 it is fine to pin it.

But I meant that the menu registration should not blow up the whole menu bar if one command failed to be registered.

**Comment by vince-fugnitto** [comment]
> @https://github.com/vince-fugnitto it is fine to pin it.
> 
> But I meant that the menu registration should not blow up the whole menu bar if one command failed to be registered.

Yes I agree, there should be better handling in order to prevent such issues, especially since it breaks the entire main menu.

**Comment by vince-fugnitto** [comment]
> But I meant that the menu registration should not blow up the whole menu bar if one command failed to be registered.

Should we open a follow-up issue to be more robust when creating menus/commands and not fail if one is missing?

**Comment by akosyakov** [comment]
@vince-fugnitto yes, thanks

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto yes, thanks

#7733
