### ISSUE TITLE
Setting default height for ViewContainerPart

### ISSUE THREAD

**Issue by hx8563** [eclipse-theia/theia#7728]
### Feature Description:
Is there a way to specify an initial height for every ViewContainerPart in ViewContainer instead of having all parts with same height?

**Comment by vince-fugnitto** [comment]
@hx8563 thank you for the issue, please post questions on [discussions](https://github.com/eclipse-theia/theia/discussions) in the future.
Are you looking to create a new `ViewContainerPart` or are you attempting to update existing containers?
