### ISSUE TITLE
Child node 'file-change-tree-root' does not belong to this 'file-change-tree-root' tree.

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7732]
Not sure how to reproduce, but logs are filled now with such errors. It could be related to how and when the scm tree constructed and refreshed. Usually indicates a race condition. 

cc @westbury

**Comment by akosyakov** [comment]
A tree usually should be implemented by providing `Tree.resolveChildren` function I could not find such for the scm tree. Maybe new nodes are created all the time?

**Comment by westbury** [comment]
I have the fix for this.  I'm in a meeting now but I'll put in the PR shortly.

**Comment by ncshrikanth** [comment]
This 'file-change-tree-root' error is still thrown while Testing VS Code Extensions (setup from source).
