### ISSUE TITLE
quality: make menus/commands more robust

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7733]
#### Feature Description:

We should make the creation of menus (main-menu, context-menus) more **robust** so that the rendering does not fail entirely when there are errors. The framework should be more robust in such cases and skip rendering these items (while logging errors to application-developers), so end-users do not end up with broken user-interfaces.

For example, due to a small dependency error (#7726), the entire main-menu failed to render.
In such cases, if there is a faulty menu item, the item should be skipped and the menu should still render.

**Comment by scheng123** [comment]
IMO, if something breaks, then the underlying issue is more obvious then if something is error handled, leading to shorter time for tracking down critical issues (like what just happened with `moment`)

Please critique my statement if you think otherwise. I’m not experienced in developing big projects like these.

**Comment by vince-fugnitto** [comment]
> IMO, if something breaks, then the underlying issue is more obvious then if something is error handled, leading to shorter time for tracking down critical issues (like what just happened with `moment`)

@scheng123 reporting the error for application-developers would be just as useful imo, without the negative side-effect of breaking a major component of the framework (menus). The only reason the issue was **critical** was because of the breakage of the menu not the usage of `moment`. The framework should be robust enough to handle such cases and not attempt to register menu items for commands which do not exist or throw errors. I don't think we should keep a broken UI state for the sake of visualizing/discovering errors more easily as it will lead to poor user experiences. In the worst case, a simple command will simply be unavailable until resolved instead of the entire menu being broken.

**Comment by vince-fugnitto** [comment]
I believe it is resolved by https://github.com/eclipse-theia/theia/pull/9886.
