### ISSUE TITLE
the scm commit input is gone

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7734]
After working for a while, restarting the server and resetting the layout, the commit input is completely gone:
<img width="1017" alt="Screenshot 2020-05-04 at 15 05 04" src="https://user-images.githubusercontent.com/3082655/80968804-e032b400-8e18-11ea-8bea-759670a215ec.png">

Sorry, I don't have concrete steps :( but it did happen during testing and now happens in production.

cc @westbury

**Comment by akosyakov** [comment]
One can recover only by cleaning origin caches and reloading afterwards. There seem to be some state layout mismanaged.

**Comment by westbury** [comment]
I have never seen this one.  Is there anything in console output, or clues from dev tools?

We might also see if https://github.com/eclipse-theia/theia/pull/7736 fixes this, as that does improve the storeState/restoreState.

**Comment by akosyakov** [comment]
I can reproduce it by opening another folder on the disk which I've never opened before:
![commig](https://user-images.githubusercontent.com/3082655/81160316-35420780-8f8a-11ea-8251-c9dcc31afd40.gif)

I've tested against https://github.com/eclipse-theia/theia/pull/7736

@westbury Can you have a look at it please? If not please let us know, that's quite critical to resolve.

**Comment by westbury** [comment]
Thanks for the info.  I can now reproduce it.
