### ISSUE TITLE
cli: download:plugins does not support HTTP_PROXY environment variable

### ISSUE THREAD

**Issue by slhultgren** [eclipse-theia/theia#7739]
The HTTP_PROXY environment variable is not respected when running download:plugins.

**Comment by vince-fugnitto** [comment]
I believe @marechal-p had already prepared a commit to address such an issue: https://github.com/eclipse-theia/theia/compare/mp/proxy-download

**Comment by slhultgren** [comment]
@vince-fugnitto @marechal-p Ok, fine for me to merge that instead. Please note the lastError change in this pull request though, maybe it could be added to the pull request?

**Comment by lmcbout** [comment]
IT looks like one is looking at "Http**S**" proxy and the other is looking at "Http" proxy. WE should have a solution which take care of both typeof proxy

**Comment by marechal-p** [comment]
> Please note the lastError change in this pull request though

Can you explain why this is required? The idea behind this variable is to know in which state we got out of the retry loop: if `lastError` is set during retry \#2 but works in \#3 your change will make the script fail.

**Comment by marechal-p** [comment]
Ok my bad I see the mistake: I did not realize that this statement was evaluated on the last iteration of the loop, this is bogus indeed.
