### ISSUE TITLE
preferences: use custom context-menu for browser target

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7744]
#### Feature Description:

Following #7105, the context-menu from the preferences-widget incorrectly uses the native menu when in the browser. This is correct for electron, but in the browser we should use the custom context-menu like the rest of the application:

_Browser_:

<div align='center'>

<img width="390" alt="Screen Shot 2020-05-05 at 9 33 11 AM" src="https://user-images.githubusercontent.com/40359487/81072238-ddd16800-8eb3-11ea-95b9-7b6602cbc7a2.png">

</div>

**Comment by colin-grant-work** [comment]
@vince-fugnitto , could you give a little more information here? Late in the process, we switched from using Phosphor's `Menu` directly to using Theia's `ContextMenuRenderer` - is this related to that change?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto , could you give a little more information here? Late in the process, we switched from using Phosphor's `Menu` directly to using Theia's `ContextMenuRenderer` - is this related to that change?

@colin-grant-work I'm sorry, I made the mistake of thinking the dropdown was a context-menu, the fact that dropdowns are native in the browser is an issue across the framework: https://github.com/eclipse-theia/theia/issues/4673
