### ISSUE TITLE
preferences: improve category headers

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7745]
#### Feature Description:

Following #7105, we should improve category headers present in the view.
At the moment, subcategories are styled similarly to categories which makes their appearance confusing. For instance, take the preference `markdown.links.openLocation` for example:

_Theia_:

<img width="373" alt="Screen Shot 2020-05-05 at 9 37 57 AM" src="https://user-images.githubusercontent.com/40359487/81072589-5cc6a080-8eb4-11ea-919b-caa869725939.png">

_VS Code_:

<img width="395" alt="Screen Shot 2020-05-05 at 9 37 48 AM" src="https://user-images.githubusercontent.com/40359487/81072608-618b5480-8eb4-11ea-81e8-9ff25d4a2d1e.png">

In Theia, it looks like there are two categories (**Markdown** and **Links**), and it gives the impression that **Markdown** is empty.

**Comment by liorfr** [comment]
Also, 

_Theia_:
The category in the leaf starts from the second category word when the category has more than one word 
![image](https://user-images.githubusercontent.com/6076791/93187317-5bea2900-f748-11ea-963f-ca1e51a73f46.png)

 


_VS Code_: 
VS Code Has the following after categories and subcategories  
![image](https://user-images.githubusercontent.com/6076791/93187343-60aedd00-f748-11ea-9f61-9e102c6cdace.png)

**Comment by vince-fugnitto** [comment]
I believe this can be closed thanks to https://github.com/eclipse-theia/theia/pull/9439.

_when no search is present_:

<img width="366" alt="Screen Shot 2021-07-15 at 4 13 07 PM" src="https://user-images.githubusercontent.com/40359487/125851512-4f1e0a64-9398-4158-8365-ee10faa41f69.png">

_when a search is present ('markdown')_

<img width="367" alt="Screen Shot 2021-07-15 at 4 13 36 PM" src="https://user-images.githubusercontent.com/40359487/125851569-9148df0d-c347-4d6d-92b3-800ba695681d.png">
