### ISSUE TITLE
Counter in the git widget (same as vscode)

### ISSUE THREAD

**Issue by cortopy** [eclipse-theia/theia#7759]
In vscode, there's a counter of the number of files changed in the git repository

![image](https://user-images.githubusercontent.com/8725825/81168456-ee0a4580-8f8e-11ea-9916-9790194e478c.png)

I personally find this counter particularly useful in day-to-day coding

### Feature Description:

The git widget in the sidebar displays the number of files that have changed since last commit

**Comment by kittaakos** [comment]
Same as #4782.
