### ISSUE TITLE
Preference view have different focus when there is another view panel visible

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7770]
### Bug Description:
While testing issue #7764 , I noticed the focus on the left side of the preferences panel is different when there is a bottom view panel . The highlight of the preferences does not change from one section to the others, the highlight is just removed. When there is another view panel, the highlight of the preferences on the left side panel changes.

### Steps to Reproduce:

1. Open the preference editor
2. Set a search pref (I used "cursor" )
3. Observe the focus on the left side panel of the preferences when scrolling on the right side and 
     there is no bottom panel view and when there is one other view (I used the output view)
--> The preference focus is different 

### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: latest with commit for issue #7764 

Theia with no bottom panel
![PrefNoBottomViewPanel](https://user-images.githubusercontent.com/419051/81295902-1fdae500-903f-11ea-98e9-78a980a6eb00.gif)

Theia having the output view panel
![PrefWithBottomPanel](https://user-images.githubusercontent.com/419051/81295944-2c5f3d80-903f-11ea-886b-2dcd68ed117c.gif)

**Comment by vince-fugnitto** [comment]
@lmcbout I don't understand the bug, I don't see any issue.

**Comment by lmcbout** [comment]
Another interesting thing, if you search for "curs", scroll slowly and between "Editor/Goto Location" and "Editor/Suggest", there is a dead zone where there is no highlight at all on the left side of the preferences

**Comment by colin-grant-work** [comment]
Thanks for identifying this issue. I'm not sure I'm able to discern the problem from the screencasts. It looks like in the bottom cast, there's a moment when neither `Editor` nor `Suggest`, is that what is problematic? In the top cast, the scrolling pauses at that moment, so the highlight never moves to `Suggest`. There should be a highlighted / selected element at all times during the scroll, so that seems like a problem, but I'm not sure it's the problem you mean.

**Comment by lmcbout** [comment]
Yes the issue is between  "Editor/Goto Location" and "Editor/Suggest"  Just use "curs" in the search field and you should see it more easily

**Comment by colin-grant-work** [comment]
👍 , I will look into the logic that implements the select-on-scroll to see why there's a gap there.
