### ISSUE TITLE
firefox: application fails to load

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7771]
#### Bug Description:

The application fails to load on **firefox**.
The loading screen is displayed, and there is an error on startup:

<div align='center'>

<img width="1328" alt="Screen Shot 2020-05-07 at 9 10 21 AM" src="https://user-images.githubusercontent.com/40359487/81298454-cb396900-9042-11ea-8de2-ae927c688cca.png">

</div>

It would be good for others to confirm that it is broken as well.

#### Steps to Reproduce:

1. start the example-brower application (`yarn start:browser`)
2. open [localhost](http://localhost:3000/) on **firefox**

#### Additional Information

- Operating System: macOS
- Theia Version: 7cf845b

**Comment by kittaakos** [comment]
> It would be good for others to confirm that it is broken as well.

Confirmed.

![Screen Shot 2020-05-07 at 15 37 44](https://user-images.githubusercontent.com/1405703/81300976-bbd51280-9078-11ea-8d59-a9f752be6292.jpg)

**Comment by kittaakos** [comment]
I have seen this before, not all the browsers(?) allow positive lookahead groups for regexp, it's an ES7 thing (I am just guessing, though). I have seen lookahead groups commit recently, not sure where.

**Comment by kittaakos** [comment]
[Here](https://stackoverflow.com/questions/59488172/firefox-regex-syntaxerror-invalid-regexp-group), FF and IE does not support groups, I remember I had the same issue a year ago.

**Comment by vince-fugnitto** [comment]
@kittaakos this is what I could find that was added recently (following #7105):

https://github.com/eclipse-theia/theia/blob/7cf845b389780846bf727f6ef914d97b6f16d368/packages/preferences/src/browser/util/preference-tree-generator.ts#L72

https://github.com/eclipse-theia/theia/blob/7cf845b389780846bf727f6ef914d97b6f16d368/packages/preferences/src/browser/util/preference-tree-generator.ts#L103

I'll try a commit before and see if the changes affected firefox.

**Comment by vince-fugnitto** [comment]
> @kittaakos this is what I could find that was added recently (following #7105):
> 
> https://github.com/eclipse-theia/theia/blob/7cf845b389780846bf727f6ef914d97b6f16d368/packages/preferences/src/browser/util/preference-tree-generator.ts#L72
> 
> https://github.com/eclipse-theia/theia/blob/7cf845b389780846bf727f6ef914d97b6f16d368/packages/preferences/src/browser/util/preference-tree-generator.ts#L103
> 
> I'll try a commit before and see if the changes affected firefox.

I confirmed that a commit before the problem was not there, we will need to update the regular expressions.

**Comment by akosyakov** [comment]
@vince-fugnitto Do you take care about it?

**Comment by akosyakov** [comment]
I wonder is there some es linting for regex that we use only syntax supported by all browsers.
