### ISSUE TITLE
Download:plugins does not refresh the plugins folder with the latest version

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7778]
### Bug Description:
Script:  **yarn download:plugins**
If there is already a plugin with the same name but a different version, the script WILL NOT download the new version, it will keep the old one. You need to remove the old version to allow the download script to kick in and download the newest version. 
It only check for the name and does not check for the version (or sha) of the plugin

### Steps to Reproduce:

1.Open your package.json
2.Replace the following:
```
"vscode-builtin-bat": "https://open-vsx.org/api/vscode/bat/1.39.1/file/vscode.bat-1.39.1.vsix",
BY
"vscode-builtin-bat": "https://open-vsx.org/api/vscode/bat/1.44.2/file/vscode.bat-1.44.2.vsix",
```
3.--> You are looking to change the version from 1.39.1 to 1.44.2
4. execute the script: yarn download:plugins
--> observe the console and notice the new version of the plugins did not get downloaded
-> you can verify also by starting Theia, open the plugins view and verify the version of this plugin.

### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: Latest commit

**Comment by vince-fugnitto** [comment]
@lmcbout it is not meant to update the version, it verifies the `key` (identifier) and if it is already present then it doesn't attempt to re-download the extensions.

**Comment by vince-fugnitto** [comment]
If you want fresh extensions then you should delete the extensions present, and re-download.

**Comment by vince-fugnitto** [comment]
Misclick.

**Comment by lmcbout** [comment]
As discuss during the scrum meeting, there are two choices:
1 - We add a clean plugins and then download the new plugins each time we build
  this will always make sure we use the right plugins that are defined in package.json
2- The user has the responsability to clean himself the plugins folder before compiling when there are new plugins

**Comment by vince-fugnitto** [comment]
> As discuss during the scrum meeting, there are two choices:
> 1 - We add a clean plugins and then download the new plugins each time we build
> this will always make sure we use the right plugins that are defined in package.json
> 2- The user has the responsability to clean himself the plugins folder before compiling when there are new plugins

@lmcbout I think it's the user's responsibility to clean. If they have manually included plugins in the `plugins` folder, the fact that we do an auto-clean before running the script will cause them to lose the plugins they've added and will force them to re-add them manually again.

**Comment by akosyakov** [comment]
> We add a clean plugins and then download the new plugins each time we build
this will always make sure we use the right plugins that are defined in package.json

I frequently replace particular VS Code extension with counterpart from sources. It would break my flow.

**Comment by vince-fugnitto** [comment]
I do not believe there is anything to do here, it should be up to the user to determine when to clean (and automatic cleans will likely result in more issues than it solves). 

> I frequently replace particular VS Code extension with counterpart from sources. It would break my flow.

This is another reason not to do automatic cleans.
