### ISSUE TITLE
Upgrade the built-in to use version 1.44.2

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7781]
### Bug Description:
Upgrade Theia with a new version of the built-ins 
The upgrade will use the version 1.44.2 from open-vsx registry with the **exception** of two built-ins

**"vscode-builtin-markdown-language-features"** which still use version 1.39.1 see issue #7780 
**"vscode-builtin-npm"** which still use version 1.39.1 see issue #7779 

### Steps to Reproduce:

1.clean your build: git clean -fdx
2. compile Theia: yarn
3. Start Theia 
4. If your use Theia as a workspace
  --> Open plugins view, the version of the built in will be 1.44.2

### Additional Information

- Operating System: UBUNTU 18.04
- Theia Version: LATEST

**Comment by akosyakov** [comment]
done?

**Comment by lmcbout** [comment]
Done, but I am looking at the errors reported on the console. Will raise new issues about it
