### ISSUE TITLE
Right Click on iPad

### ISSUE THREAD

**Issue by XenfoMC** [eclipse-theia/theia#7790]
### Bug Description:
No right click.

### Additional Information
I was told that if you hold on something it acts as a right click. If this is true it is not working and it is a bug. If it is false can you please let me know how to right click on mobile devices. Thanks.

- Operating System: Latest iPadOS
- Theia Version: Latest

**Comment by vince-fugnitto** [comment]
@XenfoMC as mentioned in the following issue, it looks like long press should work:
- https://github.com/eclipse-theia/theia/issues/6322

**Comment by vartanbeno** [comment]
I can confirm that long pressing emulates a right click on my iPad.

**Comment by XenfoMC** [comment]
Ok. Seems to work now.

**Comment by vince-fugnitto** [comment]
> Ok. Seems to work now.
