### ISSUE TITLE
Impossible to run a task w/o a problem matcher specified

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-theia/theia#7802]
### Bug Description:
It's impossible to run a task w/o a problem matcher specified.

### Steps to Reproduce:

1. Run any task w/o a problem marcher specified.
2. Theia should ask you what problem matcher to use.
3. Actually, the list of problem matcher is empty

![image](https://user-images.githubusercontent.com/1636395/81708867-31c2ea80-947a-11ea-93a5-edcb5f0c1dec.png)

### Additional Information

- Operating System: Fedora
- Theia Version: [`362e8f13e97a850387c103e8e7ee29d6e36b873e`](https://github.com/eclipse-theia/theia/commit/362e8f13e97a850387c103e8e7ee29d6e36b873e)

**Comment by azatsarynnyy** [comment]
It works before this PR https://github.com/eclipse-theia/theia/pull/6921 changes, on commit `3f28503e754bbb4fa6534612af3d1ed6da3ed66a`.
But it doesn't work after the mentioned PR, on commit `362e8f13e97a850387c103e8e7ee29d6e36b873e`.

cc/ @akosyakov

**Comment by akosyakov** [comment]
@azatsarynnyy i will look at it tomorrow morning

**Comment by akosyakov** [comment]
that's even worse: try to change language or encoding of an editor, it just shows an empty quick pick.

**Comment by akosyakov** [comment]
@azatsarynnyy here is the fix: https://github.com/eclipse-theia/theia/pull/7804
