### ISSUE TITLE
TypeError: i.workspace.onDidRenameFiles is not a function when using builtin version 1.44.2

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7809]
### Bug Description:
With the latest builtin version 1.44.2, I see the following error on the console.log when working with typescript file.
root ERROR [hosted-plugin: 1469] Promise rejection not handled in one second: TypeError: i.workspace.`onDidRenameFiles is not a function` , reason: TypeError: i.workspace.onDidRenameFiles is not a function
root ERROR [hosted-plugin: 1469] With stack trace: **TypeError: i.workspace.onDidRenameFiles is not a function**
    at new e (/home/lmcbout/theia/stable/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:56306)
    at s.u.VersionDependentRegistration [as _doRegister] (/home/lmcbout/theia/stable/theia/plugins/vscode-builtin-typescript-language-features/extension/dist/extension.js:53:59522)

### Steps to Reproduce:

1. Open a typescript project in your workspace (ex: Theia)
--> observe  the error reported on the console

### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: Latest
- Builtin version: 1.44.2

**Comment by vince-fugnitto** [comment]
The issue is already being tracked and worked on:
- issue: #7171
- pull-request: https://github.com/eclipse-theia/theia/pull/7718
