### ISSUE TITLE
VSCode's TreeView.reveal() function does nothing in Theia

### ISSUE THREAD

**Issue by katelynienaber** [eclipse-theia/theia#7815]
### Steps to Reproduce:
My custom VSCode tree looks like this, very simple:
```
parentNode
    childNode
```

I am trying to run this function:
```
    public setItem(treeView: vscode.TreeView<IZoweTreeNode>, item: IZoweTreeNode) {
        treeView.reveal(item, {select: true, focus: true, expand: true});
    }
```
If item = parentNode, then parentNode is expanded and selected properly.
If item = childNode, then nothing happens
If I expand parentNode by clicking on the arrow, and then try to run setItem on childNode, then childNode is expanded and selected properly.

I also tried:
```
    public setItem(treeView: vscode.TreeView<IZoweTreeNode>, item: IZoweTreeNode) {
        treeView.reveal(item.getParent(), {select: true, focus: true, expand: true});
        treeView.reveal(item, {select: true, focus: true, expand: true});
    }
```
(getParent just gets parentNode from childNode, and during debugging it gives the correct value)

And last I tried:
```
    public setItem(treeView: vscode.TreeView<IZoweTreeNode>, item: IZoweTreeNode) {
        treeView.reveal(item.getParent(), {select: true, focus: true, expand: true}).then(() => {
            treeView.reveal(item, {select: true, focus: true, expand: true});
        });
    }
```

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.0??

**Comment by akosyakov** [comment]
There was a bug which was fixed this week: https://github.com/eclipse-theia/theia/pull/6921/commits/2f06b86f9e4e9f53e7ab96f20b187338b74cf241 Pleas try the latest master.

**Comment by katelynienaber** [comment]
Thank youu!
