### ISSUE TITLE
does not support Chrome 58?

### ISSUE THREAD

**Issue by hojas** [eclipse-theia/theia#7830]
### Bug Description:

Error on Chrome 58

### Steps to Reproduce:

On Chrome 58

![image](https://user-images.githubusercontent.com/4729039/82184885-ed709800-991a-11ea-89c5-18042b65ed84.png)

### Additional Information

- Operating System: windows 10, Chrome 58
- Theia Version: 1.0

**Comment by kittaakos** [comment]
It's possible that we do not support browser version from 2017 😊, did you try upgrading?

**Comment by kittaakos** [comment]
Can you open Theia in Gitpod with your Chrome? Here is the link: https://gitpod.io/#https://github.com/eclipse-theia/theia

**Comment by hojas** [comment]
My browser is from 2020, but many users of my application use old version of Chrome like 58. @kittaakos

**Comment by kittaakos** [comment]
> My browser is from 2020, but many users of my application use old version of Chrome like 58. @kittaakos

You can verify it quickly: if you can open Theia in Gitpod with Chrome 58; it works.

**Comment by hojas** [comment]
> > My browser is from 2020, but many users of my application use old version of Chrome like 58. @kittaakos
> 
> You can verify it quickly: if you can open Theia in Gitpod with Chrome 58; it works.

It works, but my build version is not work. Which version of node should I use? Or maybe some VS Code extensions I added is not work in Chrome 58?

**Comment by kittaakos** [comment]
> It works

Nice. 

> , but my build version is not work.

Yeah, I have noticed, you have some customization... 👇 

![82184885-ed709800-991a-11ea-89c5-18042b65ed84](https://user-images.githubusercontent.com/1405703/82196788-71665800-98fa-11ea-9e60-32b14cce6823.png)



> Which version of node should I use? Or maybe some VS Code extensions I added is not work in Chrome 58?

You can find the Theia prerequisites [here](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites).

**Comment by hojas** [comment]
> > It works
> 
> Nice.
> 
> > , but my build version is not work.
> 
> Yeah, I have noticed, you have some customization... 👇
> 
> ![82184885-ed709800-991a-11ea-89c5-18042b65ed84](https://user-images.githubusercontent.com/1405703/82196788-71665800-98fa-11ea-9e60-32b14cce6823.png)
> 
> > Which version of node should I use? Or maybe some VS Code extensions I added is not work in Chrome 58?
> 
> You can find the Theia prerequisites [here](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites).

I found that, my version is not work because I build it from theia-apps/theia-docker. @kittaakos

**Comment by kittaakos** [comment]
@hojas, have you found a fix for your issue?

**Comment by hojas** [comment]
> @hojas, have you found a fix for your issue?

Yes, now works fine on Chrome 58. I use the package.json from official [document](https://theia-ide.org/docs/composing_applications/) not from theia-apps/theia-docker. Thanks so much!

**Comment by kittaakos** [comment]
> Yes, now works fine on Chrome 58

👍 Great, I am glad you've figured this out.
