### ISSUE TITLE
Can not terminate a process using Ctrl+C  

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#7833]
### Bug Description:
It was possible to terminate a task or some process in a terminal using `Ctrl+C`
But now it's not working

### Steps to Reproduce:

1. Open some project
2. Open a terminal and try to build it
3. Try to terminate the build process by `Ctrl+C`

Another case:
1. Add the configuration to `tasks.json` file
```
        {
            "type": "shell",
            "label": "shell:test",
            "command": "sleep 40 && echo test shell task"
        }
```
2. Run the configuration from `Terminal` ---> `Run Task` menu
3. Go to the corresponding terminal and try to terminate the task using `Ctrl+C`

### Expected behavior
![terminate_process](https://user-images.githubusercontent.com/5676062/82247330-e2375f80-994e-11ea-8dba-4b2b7c2bbf77.gif)

### Additional Information

- Operating System: Fedora 31
- Theia Version: bb43e9ea7508687932e386a344f2afc0e915e451

**Comment by akosyakov** [comment]
@RomanNikitenko on Windows?

**Comment by RomanNikitenko** [comment]
@akosyakov 
I faced with the problem on linux

**Comment by akosyakov** [comment]
@RomanNikitenko yes, makes sense `ctrl+c` is copy on mac as well

I will close it as a dup of https://github.com/eclipse-theia/theia/issues/7836
