### ISSUE TITLE
Ctrl-c (terminate) not working in Terminals

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#7836]
### Bug Description:
When I run a task and type `<ctrl>-c` in the terminal, the task is not interrupted

### Steps to Reproduce:

1. Start any long running task
2. Click in the terminal window executing said task to give it focus
3. Type `<ctrl>-c?`
4. Observe: the task continues to execute

My expectation would be that the task be interrupted, like in a regular shell.

### Additional Information

- Operating System: Windows 10, Chromium, but also does not work on Linux
- Theia Version: Master

**Comment by tsmaeder** [comment]
A bisection of commits was able to trace this back to this commit: 62c9a83

**Comment by akosyakov** [comment]
So https://github.com/eclipse-theia/theia/commit/62c9a8361c772b4bfa33084fd62bef8eec158f08 makes sure that we don't mess with an order of registered keybindings, i.e. the logic should be a keybinding in the higher scope should have a priority and within a scope keybinding which registered later should have a priority. The code will just randomly put some keybinding with `context` property as the higher priority disregarding scopes and order of registration.

I think the proper solution will be to delete `DEFAULT_OVERRIDING` scope and evaluate all keybindings in the reverse order not only for `DEFAULT_OVERRIDING` scope as before. I will send a PR soon for testing. I hope we don't break something else with it.

**Comment by tsmaeder** [comment]
@akosyakov it's all greek to me 🤷, that's why I did not propose a fix.

**Comment by marcdumais-work** [comment]
> it's all greek to me

Pretty much :) But I guesstimate that, given the context, another shortcut is currently "winning" the battle and overriding the `terminate` one we all know and love. Perhaps `copy`?
