### ISSUE TITLE
replace usages of `Keybinding.context` with `Keybinding.when`

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7849]
`Command.context` is deprecated and should be remove in future releases

**Comment by kittaakos** [comment]
> `Command.context` is deprecated and should be remove in future releases

Let's remove it once we have some sort of documentation about the transition. Thanks!

**Comment by akosyakov** [comment]
It should be the part of the task to update `CHANGELOG.md` explaining what should be used instead and how.

**Comment by tsmaeder** [comment]
Closing in favor of #12657, which contains more info about motivation. Good catch, @vince-fugnitto
