### ISSUE TITLE
[Logging] Show logs command

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#786]
In #185 was the following requirement:

> View for IDE messages, like Debug info or error messages of the IDE.

This basically means 'show me the log', which we should do in a text editor.
It is unrelated to notifications but should be triggered through a command.

**Comment by JanKoehnlein** [comment]
I'd prefer a log view. https://github.com/theia-ide/theia/pull/1040

**Comment by svenefftinge** [comment]
In an offline discussion, we agreed, that the concept 'log' is already used and since the (now named) output extension is not using that infrastructure it should be named differently.

**Comment by vince-fugnitto** [comment]
I believe this is closed by the `output-view` (based on the referenced commits).
