### ISSUE TITLE
Git changes list does not get updated

### ISSUE THREAD

**Issue by jbicker** [eclipse-theia/theia#7873]
### Bug Description:
The list of git changes is not updated automatically. One has to do some action first in the git widget (such as expanding/collapsing the list or refreshing it...)
Note: this happens with non-active git widget only.
![theia-git-list-not-updated](https://user-images.githubusercontent.com/28291421/82805649-a3406700-9e84-11ea-98b0-51a3fb461b96.gif)
 

### Steps to Reproduce:

1. open a file and leave filebrowser active
2. change something
3. open git widget - changes are not displayed until some action in git widget

### Additional Information

- Operating System:
- Theia Version:

**Comment by akosyakov** [comment]
cc @westbury

**Comment by svenefftinge** [comment]
I cannot reproduce the behavior with current master.

**Comment by svenefftinge** [comment]
I can now. Will look into it.
