### ISSUE TITLE
preference UI creates a new settings file instead of using vscode settings

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7877]
It's reproducible with https://github.com/gitpod-io/spring-petclinic repo

- open the preference UI for workspace
- and then click the toolbar action to reveal the file
- it creates a new file under `.theia` instead fo opening one under `.vscode`

The preference UI should use `PreferenceService.resolve` method to retrieve a proper config URI.

**Comment by vince-fugnitto** [comment]
The issue can no longer be reproduced given the reproduction steps:

![image](https://user-images.githubusercontent.com/40359487/127674695-787feb2e-4eb3-4309-8761-63f90b174d1d.png)
