### ISSUE TITLE
vscode.window.createTerminal is not fully implemented.

### ISSUE THREAD

**Issue by datou0412** [eclipse-theia/theia#7892]
### Feature Description:
vscode plugin's `window.createTerminal` API support "Creates a Terminal where an extension controls its input and output" by the option [ExtensionTerminalOptions](https://code.visualstudio.com/api/references/vscode-api#ExtensionTerminalOptions)
which is not implemented in [theia.window.createTerminal](https://github.com/eclipse-theia/theia/blob/master/packages/plugin/src/theia.d.ts#L3511)

**Comment by akosyakov** [comment]
@datou0412 Thank you for the issue. PRs are welcomed!

**Comment by akosyakov** [comment]
Is it related to https://github.com/eclipse-theia/theia/issues/6589?
