### ISSUE TITLE
Starting all plugins when closing the workspace looks strange

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7895]
### Bug Description:
When you close a workspace, we can observe on the console that we start all plugins. 
Should we just activate the plugins when we open a workspace? It looks weird to see the traces about all started plugins when you close a workspace.

Note: comes from the discussion #7885 

### Steps to Reproduce:

1. Start Theia with a workspace 
2. Close the workspace, not Theia (File-> Close Workspace)
--> Observe the traces on the console, all plugins get started

### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: Latest

**Comment by akosyakov** [comment]
That's expected: close workspace reloads the window, plugins are reloaded for a new window, a empty workspace needs plugins as well, since you still can open a file or a plugin can contribute an action to create a new project.
