### ISSUE TITLE
alt+n triggers a new file while editor is focused

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#7896]
Instead it should insert `~` only. It is not a regression.

**Comment by balajiv113** [comment]
Hi, i would like to work on this issue.

**Comment by akosyakov** [comment]
I am not sure how we should tackle it. What would better keybinding? cc @eclipse-theia/ecd-theia-committers

**Comment by azatsarynnyy** [comment]
Sorry @akosyakov, I didn't get what the actual issue with Alt+N keybinding.
Is it about using the same keybinding for both browser and electron? Or something else?

**Comment by akosyakov** [comment]
Steps to reproduce:
- use Theia via the browser
- open a new file
- press `alt+n`
- expected that `~` is inserted and the new file dialog does not pop up

@azatsarynnyy is it better?

**Comment by azatsarynnyy** [comment]
why pressing alt+n should insert `~`?

**Comment by akosyakov** [comment]
Maybe it is related to germany layout on mac only 🤔

**Comment by akosyakov** [comment]
Most importantly here that the new file dialog does not pop up on any platform if an editor is focused and such keys expected to insert something.

**Comment by kittaakos** [comment]
> why pressing alt+n should insert `~`?

Well, I had the same question yesterday and tried it locally with EN_US layout on macOS;  it really inserts a tilde but another one:
```
~
˜
```
The first one is with <kbd>Shift</kbd>+<kbd>`</kbd>, the second is with <kbd>Alt</kbd>+<kbd>N</kbd>.

![screencast 2020-05-28 12-58-06](https://user-images.githubusercontent.com/1405703/83133608-6a51fd80-a0e3-11ea-84da-2dff0deeadf1.gif)

**Comment by AlexTugarev** [comment]
BTW: on mac with US layout `alt+n` inserts a superscript tilde, which when followed e.g. by an `n` allows to enter Enye (Ñ, ñ).

**Comment by spoenemann** [comment]
Maybe change to `cmd+alt+n` on Mac?

**Comment by akosyakov** [comment]
@spoenemann sounds good if it does not affect other platforms.

**Comment by azatsarynnyy** [comment]
> Most importantly here that the new file dialog does not pop up on any platform if an editor is focused and such keys expected to insert something.

interesting...
for me, alt+n opens New File dialog
![Peek 2020-05-28 14-56](https://user-images.githubusercontent.com/1636395/83138488-89f12200-a0f3-11ea-9971-d27aba0b468f.gif)
Linux Fedora, Chrome, en_US

**Comment by vzhukovskii** [comment]
Have the same behavior as @azatsarynnyy has, but on the macOS under Chrome 81:

![tilda](https://user-images.githubusercontent.com/1968177/83140613-03d6da80-a0f7-11ea-96ce-97621ec34c11.gif)

**Comment by akosyakov** [comment]
https://github.com/eclipse-theia/theia/issues/7896#issuecomment-635291528 sounds good?

**Comment by tsmaeder** [comment]
Given that we have https://github.com/eclipse-theia/theia/issues/11342, I assume this one has been drive-by fixed :-)
