### ISSUE TITLE
[monaco][quick-open] Using `fuzzySort: true` throws an error

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#7899]
### Steps to Reproduce:

1.` F1` --> `Variable:List All`
2. You can see empty list and an error in browser console

**Actual behavior:**
![variables_actual](https://user-images.githubusercontent.com/5676062/82933546-be999800-9f92-11ea-955b-19130e9f6bc6.gif)

**Expected behavior:**
![variables_expected](https://user-images.githubusercontent.com/5676062/82933337-6c587700-9f92-11ea-87fd-19753f567935.gif)

### Additional Information
[This place](https://github.com/eclipse-theia/theia/blob/84408de86de835e26ca6100f8d69b311e0d0b0a5/packages/monaco/src/typings/monaco/index.d.ts#L1032) should be revisited at the next upgrade Monaco version.

The workaround is: use [here](https://github.com/eclipse-theia/theia/blob/84408de86de835e26ca6100f8d69b311e0d0b0a5/packages/variable-resolver/src/browser/variable-quick-open-service.ts#L61) `false` instead.

- Operating System: Fedora 31
- Theia Version: 84408de86de835e26ca6100f8d69b311e0d0b0a5

**Comment by akosyakov** [comment]
@RomanNikitenko Do you take care about it?

**Comment by RomanNikitenko** [comment]
@akosyakov 
Do you mean apply the workaround or more complex solution?

**Comment by akosyakov** [comment]
> Do you mean apply the workaround or more complex solution?

I hoped for the solution. If not I can have a look.

**Comment by RomanNikitenko** [comment]
@akosyakov 
I didn't find a good solution quickly and I don't see how to fix it before `Theia` release, that's why I created the issue. 
So if you see a solution, please do it.

**Comment by danieltomasku** [comment]
I am also getting the same error when using the `QuickOpenService` with `fuzzySort: true`:
![image](https://user-images.githubusercontent.com/14880569/83440003-c2ea0900-a409-11ea-8509-416c70f8a4ea.png)

**Comment by RomanNikitenko** [comment]
I investigated the problem, this [function](https://github.com/eclipse-theia/theia/blob/84408de86de835e26ca6100f8d69b311e0d0b0a5/packages/monaco/src/typings/monaco/index.d.ts#L1032) was removed from VS Code.

The function provided ability to sort quick open entries respecting highlight info.
So, it contained two parts:
- label highlights comparison 
- [compareAnything](https://github.com/theia-ide/vscode/blob/standalone/0.20.x/src/vs/base/common/comparers.ts#L125) function

I tried to solve the problem by :
- provide on `Theia` side logic to compare label highlights
- then use [compareAnything](https://github.com/theia-ide/vscode/blob/standalone/0.20.x/src/vs/base/common/comparers.ts#L125) function of VS Code

But I faced with the problem: Monaco loader did not bring [comparers](https://github.com/theia-ide/vscode/blob/standalone/0.20.x/src/vs/base/common/comparers.ts) despite I added the corresponding items to Monaco loader [here](https://github.com/eclipse-theia/theia/blob/bb85452514d004245929bc5bbb4c39ed9fcef116/packages/monaco/src/browser/monaco-loader.ts#L43)

**Comment by akosyakov** [comment]
We coudl either drop it if it is not used much or copy missing functions via CQs.
