### ISSUE TITLE
Keyboard bindings for hotkeys do not work with Dvorak Qwerty CMD layout

### ISSUE THREAD

**Issue by grasmash** [eclipse-theia/theia#7919]
### Bug Description:

There is a corresponding bug for VSCode here: https://github.com/microsoft/vscode/issues/23964

It appears the new key-rebinding feature when changing keyboard layout does not detect the Dvorak - Cmd-QWERTY layout correctly.

### Steps to Reproduce:

- Set up Dvorak - QWERTY layout
- Use any keyboard binding
- Keybindings no longer revert to QWERTY layout as they should

### Additional Information

The workaround listed in [this vscode issue](https://github.com/microsoft/vscode/issues/23964#issuecomment-292344329) does not seem to work in Theia:
```
"keyboard.dispatch": "keyCode" 
```

I've tried adding it to the User Preferences file but it has no effect.

**Comment by vince-fugnitto** [comment]
@grasmash you're correct we don't have support for `keyboard.dispatch` yet.

**Comment by grasmash** [comment]
Thanks for the quick response. Is this a difficult thing to add?

**Comment by vince-fugnitto** [comment]
> Thanks for the quick response. Is this a difficult thing to add?

I looked at the implementation from vscode and does not look too difficult, it's a preference to treat keybindings as either `code` or `keyCode`. If you'd like to add it please feel free to open a pull-request :)

These are the files I found:
- [dispatchConfig.ts](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/keybinding/common/dispatchConfig.ts)
- [keyboard.dispatch](https://github.com/microsoft/vscode/blob/1dc2f7cb42d8c8c39775acd5020b92632799dd3f/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L805-L822)

**Comment by vince-fugnitto** [comment]
The workaround for `keyCode` is now merged (https://github.com/eclipse-theia/theia/pull/8609), if there are still issues please re-open the pull-request.
