### ISSUE TITLE
Admin control over extension pane in enterprise IDE editions

### ISSUE THREAD

**Issue by katunin-ng** [eclipse-theia/theia#7930]
Hi,

In Enterprise editions of Theia based IDEs usage for Open VSX registry extensions should be controlled by the tenant/account owners.
We propose to add an environment variable that each IDE can set base on they own logic/need.
The value of this variable will enable/disable the possibility to open the Extensions pane in the IDE.
By default, e.g. variable is not set, the pane can be opened.

Please consider.
Natalia

**Comment by vince-fugnitto** [comment]
Hi @katunin-ng, like any widget present in the framework, an application-developer can customize the opening of widgets and actually prevent opening some if it meets your needs. I’m not sure it’s necessary to include such an environment variable.

**Comment by akosyakov** [comment]
DI is a primary way to change the default behaviour via the Theia extension.

**Comment by vince-fugnitto** [comment]
I believe the question is answered, if one does not want the extensions-view for any reason they can customize the behavior in their downstream application.
