### ISSUE TITLE
Align TaskScope with API object

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#7931]
I think [TaskScope](https://github.com/eclipse-theia/theia/blob/2aa2fa1ab091ec36ef851c4e364b322301cddb40/packages/task/src/common/task-protocol.ts#L150) should be aligned with the corresponding object in [theia.d.ts](https://github.com/eclipse-theia/theia/blob/2aa2fa1ab091ec36ef851c4e364b322301cddb40/packages/plugin/src/theia.d.ts#L8637) and [VS Code](https://github.com/microsoft/vscode/blob/50f907f0ba9b0c799a7c1d2f28a625bf30041636/src/vs/vscode.d.ts#L5923) object

### Additional Information

- Theia Version: 2aa2fa1ab091ec36ef851c4e364b322301cddb40

**Comment by tsmaeder** [comment]
Could you clarify what you mean by "aligned"? What change do you propose?

**Comment by RomanNikitenko** [comment]
I mean we have the difference for `Workspace` scope:

Theia object from task protocol:

```
export enum TaskScope {
    Workspace = 0,
    Global = 1
}
```

Objects from `theia.d.ts` and `vscode.d.ts`

```
export enum TaskScope {
        Global = 1,
        Workspace = 2
    }
```

**Comment by tsmaeder** [comment]
Thx, didn't realize that.

**Comment by vince-fugnitto** [comment]
@alvsan09 has expressed he'd like to work on the feature :+1:
