### ISSUE TITLE
Yaml file 'dockerfile.yml' is assigned with a wrong file icon

### ISSUE THREAD

**Issue by Kreyren** [eclipse-theia/theia#7937]
![image](https://user-images.githubusercontent.com/11302521/83371254-408a2680-a3c2-11ea-8756-666b3e43ff19.png)

Transfer from https://github.com/gitpod-io/gitpod/issues/1570 as requested by @akosyakov

**Comment by kittaakos** [comment]
Seems like the words `dockerfile` has greater precedence than the `.yml` extension. See [here](https://github.com/websemantics/file-icons-js/blob/9ceebffdefe63be331cb5d073b5761423655ac4c/index.js#L354).

I do not think there is much we can do without a dependency update/customization.
This issue is basically the same as https://github.com/eclipse-theia/theia/issues/7825.

**Comment by kittaakos** [comment]
@Kreyren, you can customize the `WorkspaceUriLabelProviderContribution` as a workaround.

I am going to close this issue and move your description to #7825. It's easier to track them together.

**Comment by Kreyren** [comment]
> you can customize the WorkspaceUriLabelProviderContribution as a workaround. @kittaakos 

elaborate

**Comment by kittaakos** [comment]
> elaborate assuming that i am gitpod user

Do you have your own Theia extension? You need one for the customization. Otherwise, you cannot do much about it.

**Comment by Kreyren** [comment]
> Do you have your own Theia extension? @kittaakos 

I have this which i didn't have a timeframe to finish yet https://github.com/gitpod-io/autopod

Or what kind of extension do you mean.

**Comment by kittaakos** [comment]
> what kind of extension do you mean.

A Theia extension: https://theia-ide.org/docs/authoring_extensions/

**Comment by Kreyren** [comment]
@kittaakos can you provide an abstract so that i know how to implement that

**Comment by Kreyren** [comment]
and is there something like bare minimum theia extension that i can just copy paste in gitpod to adapt this?

**Comment by kittaakos** [comment]
You could use the [`generator-theia-extension`](https://github.com/theia-ide/generator-theia-extension) to generate some boilerplate, but it won't work well as-is in Gitpod. I am not sure if there is a thing you can do now to have the desired icons.

**Comment by Kreyren** [comment]
> I am not sure if there is a thing you can do now to have the desired icons. @kittaakos 

stalling on the implementation then
