### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by munchkindev** [eclipse-theia/theia#7942]
### Bug Description:
The system limit for number of file watchers reached error appears when trying to host both frontend and backend on Theia using `ng serve` and `node index.js`. The backend and frontend run on ports 8080 and 4200. This is running inside of a docker container.

### Steps to Reproduce:

1. Setup your backend and frontend code on Theia.
2. Run `node index.js` on your backend
3. Run `npm install --save-dev @angular/cli` in the frontend folder and then run `./node_modules/@angular/cli/bin/ng serve --host=0.0.0.0 --disable-host-check`

### Additional Information

- Operating System: CentOS 7
- Theia Version: Theia 1.1.0

**Comment by vince-fugnitto** [comment]
@munchkindev the idea is to update the number of default `inotify` watchers on Linux as [documented here](https://github.com/eclipse-theia/theia/blob/bda9ff9d4cf15b28b5ffc2e984f11834adfc8f33/doc/Developing.md#linux). 

For additional information please see:
- https://github.com/theia-ide/theia-apps/pull/238#issuecomment-532925010

**Comment by munchkindev** [comment]
@vince-fugnitto thank you for your quick response. How do I execute that properly? If I try to execute it I get an error saying that it's a read-only filesystem... Should I mendle with the docker-init somehow?

**Comment by munchkindev** [comment]
Or do I need to attach a volume with `sysctl.conf` in it?

**Comment by vince-fugnitto** [comment]
@munchkindev I believe you should update the system's default `inotify` value and not from docker, as docker likely does not expose the value to be updated (based on searching online). You are likely to find better documentation online on how to update the `inotify` value when using docker.

- https://github.com/moby/moby/issues/1044#issuecomment-273243860
