### ISSUE TITLE
[Plugin API] Apply workspace.registerResourceLabelFormatter function

### ISSUE THREAD

**Issue by vinokurig** [eclipse-theia/theia#7946]
### Feature Description:
Apply `workspace.registerResourceLabelFormatter` plugin API function.
See: https://github.com/microsoft/vscode/blob/3b55119a98f460dae77830f802fa25ea44deff2e/src/vs/vscode.proposed.d.ts#L380
VsCode PR: https://github.com/microsoft/vscode/pull/66352

**Comment by akosyakov** [comment]
@vinokurig Do you remember which VS Code extension was a motivation to file this issue?

**Comment by vinokurig** [comment]
@akosyakov Yes, it is used in the vscode git extension: https://github.com/microsoft/vscode/blob/24f1b69a901f941c4a0a327798e2f9f9058af008/extensions/git/src/fileSystemProvider.ts#L51
