### ISSUE TITLE
Icons missing on the editor tabbar when opening a file from the SCM view

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#7947]
### Bug Description:
Using GIt-UI and GIT plugins version 1.39.1, there are some commands missing on the editor tabbar. The icons are not present as they are on VSCODE.

On the editor tab, the missings icons are when the file is open in a single editor
```
- Open changes With Previous revision
- Show Revision details
- Open Changes with Next Revision
- Toggle File Blame annotation 
- More actions
```
When  the editor is showing the diff editor, then other icons are added
```
- Open File (Alternate with the "Open Changes"
- Previous changes
- Next changes
- Show leading/Trailing Whitespace Differences
```

### Steps to Reproduce:

1. Open the Source control View (Git)
2. Select a modified file in the list 
--> This open the file in diff editor
-> Observe the icons missing to navigate/execute commands in the editor tabbar
--> Compare with the icons in VSCODE

### Additional Information

- Operating System: Tested on Ubuntu 18.04, but is probably missing on all platforms
- Theia Version: Latest
- GIt /Git-UI version 1.39.1

Theia icons on the editor tabbar
![TheiaIcons](https://user-images.githubusercontent.com/419051/83641610-c3a2ac80-a57b-11ea-9f40-287542167dda.png)

VSCode icon on the tabbar
![VSCodeIcons](https://user-images.githubusercontent.com/419051/83641637-cc937e00-a57b-11ea-8dee-a18ebeed310b.png)

**Comment by akosyakov** [comment]
Just to clarify VS Code was tested with git 1.39.1 extension as well? It could be that this extension is simply out-dated?

**Comment by lmcbout** [comment]
In Theia, git version 1.44.2 from ope-vsx registry does not work right now. On VSCode, this is a different version . This is why I mentioned the version I discovered this issue. When we will be able to upgrade , may be this issue might be gone !

**Comment by vince-fugnitto** [comment]
@lmcbout the icons you see in vscode come from `gitlens` not the builtin.
You can test in vscode by running the command `Reload with Extensions Disabled`:

<div align='center'>

![Screenshot from 2020-06-03 09-29-24](https://user-images.githubusercontent.com/40359487/83642472-df5a8280-a57c-11ea-92d9-47fe60122a97.png)


</div>

**Comment by lmcbout** [comment]
Sorry, @vince-fugnitto found the icons comes from GITLens. Tested it and the icons are available.
