### ISSUE TITLE
[git][scm] Duplicate Clear actions on the toolbar

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#7948]
### Bug Description:

Happens in the browser and the electron env too:

![Screen Shot 2020-06-03 at 15 37 04](https://user-images.githubusercontent.com/1405703/83643436-4d6c6d00-a5b0-11ea-90ce-365d5dc9ff7e.jpg)
![Screen Shot 2020-06-03 at 15 37 11](https://user-images.githubusercontent.com/1405703/83643440-4e9d9a00-a5b0-11ea-90ac-8f2d1554fdff.jpg)

Also, they do not have a tooltip.

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by kittaakos** [comment]
I do not know why the actions have a different order.

**Comment by vince-fugnitto** [comment]
I think the issue is that one of the toolbar items is incorrectly displayed in all views at the moment, for example, if you open the explorer:

<div align='center'>

![Screenshot from 2020-06-03 09-57-24](https://user-images.githubusercontent.com/40359487/83645574-a45a4e00-a580-11ea-9e1d-4dc2e9dee9d0.png)


</div>

**Comment by vince-fugnitto** [comment]
@kittaakos the issue seems to be related to the recent changes to the `output-view`:

https://github.com/eclipse-theia/theia/commit/60437227287773d7b4e032ce4b6e2568cbb87d65#diff-f039d25a52fcd004ad127516a0330b02R125-R128

**Comment by vince-fugnitto** [comment]
For the case of the ordering of the scm toolbar items, they aren't making use of `priority` so they are likely to be added in order that their registration completes:

https://github.com/eclipse-theia/theia/blob/60437227287773d7b4e032ce4b6e2568cbb87d65/packages/core/src/browser/shell/tab-bar-toolbar.tsx#L261-L264
