### ISSUE TITLE
html: builtin displays an error notification

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#7987]
#### Bug Description:

Following #7972, the `vscode-builtin-html-language-features` displays an error notification when a `html` file is opened. Originally commented: https://github.com/eclipse-theia/theia/pull/7972#pullrequestreview-427467884

<div align='center'>

![Screenshot from 2020-06-10 07-57-38](https://user-images.githubusercontent.com/40359487/84265178-6d3feb80-aaf0-11ea-9b74-36e534fcd93c.png)

</div>

#### Steps to Reproduce:

I reproduced the issue in the following way:

1. start the application
2. create a new `html` file, ex: `a.html`
3. the error is displayed

**Comment by vince-fugnitto** [comment]
`registerOnTypeRenameProvider` is currently a **proposed API**:
- https://github.com/microsoft/vscode/blob/cda677da090fa640646b676706ab2e8fe059580e/src/vs/vscode.proposed.d.ts#L1216-L1230

**Comment by akosyakov** [comment]
But experience is bad, we should either try a version before or port the implementation. I am not sure whether it is possible, maybe a new version of Monaco is required, not even 0.20 but newer.

**Comment by shahar-h** [comment]
Error notification is not displayed with 1.39.1, but rename is not supported there.
All other features are working according to the tests in #7972.

**Comment by akosyakov** [comment]
Confirmed we need a new Monaco version which was not even yet published.

**Comment by a1994846931931** [comment]
I can confirm that the latest version (1.47.1) of [`HTML Language Features (built-in)`](https://open-vsx.org/extension/vscode/html-language-features) works fine with Theia.

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/8224.
