### ISSUE TITLE
"Refactor Preview" pane

### ISSUE THREAD

**Issue by idoprz** [eclipse-theia/theia#7989]
VSCode now support a new refactoring capability called refactor preview.
It enables viewing the WorkspaceEdit before applying the changes.

The red-hat Java language support extension already supports it.
![image](https://user-images.githubusercontent.com/13120146/84283985-53c88f00-ab44-11ea-8df6-f6a36c27c3d7.png)

**Comment by danarad05** [comment]
@idoprz @akosyakov @amiramw @DoroNahari 
Hi,

As I am new to Theia development, I would appreciate if you could go over my current plan for implementing the Refactor Preview functionality and see if it makes sense. Needless to say that any suggestions would be greatly appreciated.

Requirement:
1. Upon rename refactoring enable shift+enter to open refactoring preview pane on bottom.
2. Refactoring Preview pane will be accessible only from rename refactoring shift+enter and not from menus
3. On Refactoring Preview pane, pending changes will be displayed with ability to accept or decline those changes.
4. Additional functionality for selecting what changes to apply + group by as in vscode and other.

Remarks:
1. As far as I can tell, we are talking about rename refactor preview only and not preview for every refactoring option available (see https://code.visualstudio.com/updates/v1_42#_workbench)
2. I'm referencing the vscode implementation "bulkEdit" contribution for implementation in Theia and will try to create as close as possible implementation (see https://github.com/microsoft/vscode/tree/master/src/vs/workbench/contrib/bulkEdit)
3. I suggest splitting task to a few phases - that way we can supervise better the progress:
Phase I) Opening Refactor Preview pane upon Shift+Enter when doing rename refactoring
Phase II) Displaying list of changes in refactor preview (just list without actions on it)
Phase III) Support "Accept Refactoring" + "Discard Refactoring"
Phase IV) Enable additional functionality on list of refactor changes - checkboxes to add/remove changes to refactoring.

Tasks Phase I: 
1. Under packages folder add new package "bulkEdit" - make it first a copy of output and make required changes.
2. Add bulkEdit-contribution.ts:
	a) register commands & keybindings for shift+enter functionality.
3. Update rename input widget text to include shift+enter text in widget
(not sure if can pass text to it of need to update source code is in microsoft/vscode/.../rename repo?)
4. 	Display new empty Refactor Preview pane.

I have yet to understand and define next phases specific tasks.

Thanks

Dan

**Comment by idoprz** [comment]
Hi Dan,
Refactor preview pane should not work only upon rename.
It should work when WorkspaceEditEntryMetadata has needsConfirmation set to true.
[See more info here](https://code.visualstudio.com/api/references/vscode-api#WorkspaceEditEntryMetadata)

**Comment by danarad05** [comment]
@idoprz 
> Refactor preview pane should not work only upon rename.
> It should work when WorkspaceEditEntryMetadata has needsConfirmation set to true.
> [See more info here](https://code.visualstudio.com/api/references/vscode-api#WorkspaceEditEntryMetadata)

1) This is the functionality that displays the Refactor Preview pane when doing rename refactoring:
https://code.visualstudio.com/updates/v1_42#_workbench
I haven't found the Refactor Preview pane in regard to other types of refactoring. Could you point me to them?

2) From what I understand from [WorkspaceEditEntryMetadata](https://code.visualstudio.com/api/references/vscode-api#WorkspaceEditEntryMetadata), it's not related to refactoring. Does this issue #7989 include also changes done not in refactoring capacity or am I missing something?

Thanks
Dan

**Comment by idoprz** [comment]
> @idoprz
> 
> > Refactor preview pane should not work only upon rename.
> > It should work when WorkspaceEditEntryMetadata has needsConfirmation set to true.
> > [See more info here](https://code.visualstudio.com/api/references/vscode-api#WorkspaceEditEntryMetadata)
> 
> 1. This is the functionality that displays the Refactor Preview pane when doing rename refactoring:
>    https://code.visualstudio.com/updates/v1_42#_workbench
>    I haven't found the Refactor Preview pane in regard to other types of refactoring. Could you point me to them?
> 2. From what I understand from [WorkspaceEditEntryMetadata](https://code.visualstudio.com/api/references/vscode-api#WorkspaceEditEntryMetadata), it's not related to refactoring. Does this issue #7989 include also changes done not in refactoring capacity or am I missing something?
> 
> Thanks
> Dan

1. It can be invoked by extensions, using the needsConfirmation flag on the WorkspaceEditEntryMetadata object. So you will not see it documented in the VSCode user guide.
You can create new extension that uses WorkspaceEdit https://code.visualstudio.com/api/references/vscode-api#WorkspaceEdit. make sure to have the "needsConfirmation" flag in the WorkspaceEditEntryMetadata.
2. WorkspaceEdit is related to refactoring, as it is the API that enables extensions to refactor. So this issue also should apply to WorkspaceEdit API.

**Comment by danarad05** [comment]
Thanks @idoprz 

@akosyakov Awaiting also your input please. Thanks

**Comment by akosyakov** [comment]
How do you want to take it from VS Code?

**Comment by danarad05** [comment]
Hi @akosyakov 
Cc: @idoprz @amiramw @DoroNahari 

First, thanks for replying.

Second: 
After more testing and digging in code, I would like to reconfirm my understanding of task boundaries and requirement:
1. After trying out @idoprz guidance with regard to usage of WorkspaceEditEntryMetadata.needsConfirmation - it seems to me that theia implementation in regard to renaming files is similar to vscode' - both open the changed files as tabs and await approval of user (user needs to save changes). So in this regard, from my understanding, this should remain as it it - and not display the Refactor Preview pane. 
 @akosyakov @idoprz @amiramw : Please approve that for this section (renaming files) - "needsConfirmation" usage should be implemented to reference config settings + confirm popup and that result should be as it is - opening tabs of changed files and not Refactor Preview panel. 
2. In continuation of #1, it seems to me that Refactor Preview is displayed only when invoking rename refactor. Running other refactor types on vscode does not result in the display of Refactor Preview. only after extract method refactoring for instance - if you rename method - you can also display Refactor Preview pane using shift+enter.
So for this section rename refactoring should be display Refactor Preview.
Please approve: @akosyakov @idoprz @amiramw

Third: 
In regard to your question @akosyakov:
> How do you want to take it from VS Code?

1) After some more digging, I found that there exist in Theia repo also MonacoBulkEditService which is used with MonacoEditorProvider. Could you elaborate on it's usage - what is it used for and if it is relevant for this task? From what I understand it is used by text editor by I am unable to debug it to see it at work - what actions do I need to invoke to debug it?
2) Also, when debugging this function while doing rename refactoring of method:
https://github.com/eclipse-theia/theia/blob/63c21f6980763036144eda3d4d3f82ce95c59b2e/packages/plugin-ext/src/plugin/file-system-event-service-ext-impl.ts#L225
I never seem to arrive to this section
![image](https://user-images.githubusercontent.com/71069170/93745601-7c106100-fbfc-11ea-8a8e-cfd3fb5f3d8c.png)

and so _return this._mainThreadTextEditors.$tryApplyWorkspaceEdit_ is never reached. What am I missing?

@akosyakov 
If I'm not on track or if you have any suggestions or if you can elaborate subtasks required in this task please let me know. 
Thanks
Dan

**Comment by idoprz** [comment]
Hi Dan,
I have not tested all of the VSCode/Theia current behavior. On my use-case, we need this pane when we use the WorkspaceEdit API directly and not specifically from an editor.
