### ISSUE TITLE
Autoclose HTML tags

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse-theia/theia#7991]
VSCode has support for autoclosing HTML tags.

https://www.loom.com/share/9a9d5a66198f404b92e44d019d9be93b

This support should be mirrored in VSCode.

**Comment by vince-fugnitto** [comment]
@JesterOrNot please try with the following pull-request: https://github.com/eclipse-theia/theia/pull/7972

**Comment by vince-fugnitto** [comment]
I've verified that the autoclosing of HTML tags works as of cb5bdbda505359945feef7797b2d8f6f8091dea4.
Please re-open if there are still issues.

**Comment by kittaakos** [comment]
![auto-closing-tag](https://user-images.githubusercontent.com/1405703/84387895-fab83400-abf3-11ea-8d10-c540c6da4ca1.gif)
