### ISSUE TITLE
[monaco] Open recent workspace command is broken if editor has the focus

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8001]
### Bug Description:

![screencast 2020-06-12 15-03-07](https://user-images.githubusercontent.com/1405703/84505704-7d0d2a80-acbe-11ea-8cf6-e919d7119fde.gif)

### Steps to Reproduce:

1. Close all editors and trigger Open recent workspace with `Ctrl/Cmd+Shift+R`, it works.
2. Open an editor, make sure the editor has the focus (the cursor blinks in the editor), 
3. Open recent workspace with `Ctrl/Cmd+Shift+R`while one of the editors has the focus,
4. It does not work. (`Use regular expression` from monaco activates instead)

### Additional Information

- Operating System:
- Theia Version: 310ff528d

**Comment by msujew** [comment]
@vince-fugnitto @kittaakos I can't reproduce this anymore. Probably because the Shortcut changed from `Ctrl+Shift+R` to `Ctrl+Alt+R`.

**Comment by vince-fugnitto** [comment]
Confirmed the issue does not occur anymore :+1:
