### ISSUE TITLE
[vscode] Java Test Runner extension doesn't activate and icons are not loaded

### ISSUE THREAD

**Issue by veredcon** [eclipse-theia/theia#8007]
### Bug Description:
VScode extension https://github.com/microsoft/vscode-java-test (0.22.3) is not activated in theia and icons are not loaded. It is stuck on activation.

### Steps to Reproduce:

1. Go to https://theia-ide.org/
2. Click on "Try in Git Pod"
3. Drag & Drop the vsix to the extensions area

You can see the new panel of the Java:Test is added but the task bar shows the status of activating and it seems stuck there.
When I open the panel I cannot see the icons, tests are not recognized - seems like the activation really never finish.

![image](https://user-images.githubusercontent.com/9718939/84630552-c6df5600-aef4-11ea-9cfe-bbce82529e16.png)

Debugging it as hosted plugin shows:
![image](https://user-images.githubusercontent.com/9718939/84630705-fd1cd580-aef4-11ea-89be-3997d42413d4.png)

![image](https://user-images.githubusercontent.com/9718939/84630733-05751080-aef5-11ea-90b0-c8a3d487ffb5.png)

Versions:
theia: 1.1.0
vscode-java-test: https://github.com/microsoft/vscode-java-test/releases/tag/0.22.3

**In vscode-java-test 0.22.1** it was activated successfully and icons can be seen!

**Comment by akosyakov** [comment]
We could stub uiKind with desktop till we allow to run VS Code extensions in the web. But we should have the issue for later.

**Comment by tsmaeder** [comment]
@akosyakov doc says 
> The UI kind property indicates from which UI extensions are accessed from. For example, extensions could be accessed from a desktop application or a web browser.

Isn't this just electron->Desktop or browser->Web?

**Comment by tsmaeder** [comment]
I'll whip up a PR, shouldn't take more than a couple of hours.
