### ISSUE TITLE
vscode: plugin system incorrectly registers 'open views'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#8016]
#### Bug Description:

The plugin system incorrectly registers 'open views' to the `open view` prefix quick-open menu.
Instead of registering the container (actual views), it registers the individual view entries which does not align with VS Code. For example, when adding the **Gitlens** extension, the entry is not available in the quick-open menu.

#### Steps to Reproduce:

1. add [gitlens](https://open-vsx.org/api/eamodio/gitlens/10.2.1/file/eamodio.gitlens-10.2.1.vsix) extension
2. trigger `view` > `open view`
3. notice there is no **Gitlens** entry like in VS Code (there is `line history`)

### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: https://github.com/eclipse-theia/theia/commit/2f648281b30690fb5e0f07f7d1eb689bf622d13c

**Comment by akosyakov** [comment]
There is `when` context for such entries. Maybe there is none matching?

**Comment by vince-fugnitto** [comment]
> There is `when` context for such entries. Maybe there is none matching?

Is it intended that the `when` clause would influence adding entries in the `open view`?
For example, the `open view` is better in vscode as it also categorizes items, and the bug I mentioned does not occur, the `Gitlens` entry is present.

**Comment by akosyakov** [comment]
> Is it intended that the when clause would influence adding entries in the open view?

Yes, it is the same in VS Code. GitLens extension is adding multiple views with the same name to quick open view, but only one is visible according to `when` closure.

> For example, the open view is better in vscode as it also categorizes items, and the bug I mentioned does not occur, the Gitlens entry is present.

I am not sure that categorisation is relevant here or should be another issue. We should show `line history` view when it is shown in VS Code regardless of categorization.

**Comment by vince-fugnitto** [comment]
@akosyakov the main issue I noticed is that view containers such as Gitlens are not added to the `open view` menu while in vscode they are. I also do not believe that view containers support `when` contexts. For individual parts yes however (which we have today).

**Comment by akosyakov** [comment]
@vince-fugnitto VS Code groups view by shell areas, nothing about view containers

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto VS Code groups views by shell areas, nothing about view containers.

@akosyakov yes I know, I thought for now grouping this way for now would add some value but I dropped the changes.
