### ISSUE TITLE
debug: As a Debug Adapter developer, I would like to support Exception Breakpoints

### ISSUE THREAD

**Issue by tsiyona** [eclipse-theia/theia#8019]
### Bug Description:
Theia does not enable Exception Breakpoints option in BREAKPOINTS view, although my debug adapter provides Theia with exceptionBreakpointFilters in the debugger capabilities returned in DAP 'initialize' response.

### Steps to Reproduce:

1. Set exceptionBreakpointFilters values in debug-adapter code as follows:

```
export class ExceptionBreakpointFilter implements DebugProtocol.ExceptionBreakpointsFilter {
	label: string;
	filter: string;
	enabled: boolean;

	public constructor(value: string, label: string, enabled: boolean) {
		this.filter = value;
		this.label = label;
		this.enabled = enabled;
	}
}

// handles DAP 'initialize' request. Response should contain the debugger capabilities.
protected initializeRequest(response: DebugProtocol.InitializeResponse,
			args: DebugProtocol.InitializeRequestArguments): void {

	response.body = response.body || {};

	// set some capabilities . . .
	
	response.body.supportsConfigurationDoneRequest = true;

        // now declare that debug-adapter supports exception breakpoints
	let exceptionFilters: Array<ExceptionBreakpointFilter>  = Array<ExceptionBreakpointFilter>();
	exceptionFilters.push(new ExceptionBreakpointFilter("uncaught", "Uncaught Exceptions", true));
	exceptionFilters.push(new ExceptionBreakpointFilter("caught", "Caught Exceptions", true));
	response.body.exceptionBreakpointFilters = exceptionFilters;

	response.body.supportsExceptionInfoRequest = true;
	response.body.supportsExceptionOptions = true;
	this.sendResponse(response);
 }

```
2. Build
3. Start debugging
Result: BREAKPOINTS view does not show an exception breakpoints option

### Additional Information
- I see an example in vscode, which refers to exceptionBreakpointFilters attribute in the debugger capabilities:
https://github.com/microsoft/vscode/blob/77b5058284a50445674ee3b237ad64793b38965e/src/vs/workbench/contrib/debug/browser/debugService.ts

```
private sendExceptionBreakpoints(session?: IDebugSession): Promise<void> {
		const enabledExceptionBps = this.model.getExceptionBreakpoints().filter(exb => exb.enabled);

	return sendToOneOrAllSessions(this.model, session, async s => {
			if (s.capabilities.supportsConfigurationDoneRequest && (!s.capabilities.exceptionBreakpointFilters || s.capabilities.exceptionBreakpointFilters.length === 0)) {
				// Only call `setExceptionBreakpoints` as specified in dap protocol #90001
				return;
			}
			await s.sendExceptionBreakpoints(enabledExceptionBps);
		});
}
```

See also [here](https://github.com/microsoft/vscode/blob/77b5058284a50445674ee3b237ad64793b38965e/src/vs/workbench/contrib/debug/common/debugModel.ts)

- originally referenced on the [discussions](https://github.com/eclipse-theia/theia/discussions/8006) board

**Comment by akosyakov** [comment]
`debug-adapter code` - Where do we get the debug adapter code? Please provide drop-in VS Code extension if you can.

**Comment by tsiyona** [comment]
We upgraded to Theia 1.1.0 and it supports Exception Breakpoints.

**Comment by vince-fugnitto** [comment]
> We upgraded to Theia 1.1.0 and it supports Exception Breakpoints.

@tsiyona can the issue be closed?
