### ISSUE TITLE
Theia crashes on minifed files

### ISSUE THREAD

**Issue by jgaiao** [eclipse-theia/theia#8021]
### Bug Description:
With the latest version of theia, you simply open a minified file and the tab hangs (and another I have an app that spawns theia tabs). Google Chrome shows the warning that it is not responding, and if I wait enough (about 5min or so) it eventually goes back to responding, but only unlil I type 1 character or anything in the file.

Might have something to do with the tokenization? In VS Code when I open this kind of files it shows a warning mentioning it exceeds "editor.maxTokenizationLineLength" and disables code coloring.

This did not happen in 1.1 or 1.2 (not sure). Started happening recently.

### Steps to Reproduce:

1. you simply open a minified file, i suppose it's a file with one line longer than it should.

### Additional Information

- Operating System: Linux
- Theia Version: 1.3.0-next.2aa2fa1a

**Comment by akosyakov** [comment]
I think max tokenization line length was increased from 400 to 20000 to align with VS Code: https://github.com/eclipse-theia/theia/blob/57fcabfbbc81f01486fcab50aaf2e9b40b6ed9a5/packages/editor/src/browser/editor-preferences.ts#L113

Maybe we should use 400 as default for browser version and 20000 for electron.

**Comment by jgaiao** [comment]
Sounds like a plan. Changed settings to 400 and works like a charm as before.

To note, with 20000 it hanged on both a PC with an intel i7 and 6Gb of RAM and another with intel i5 and 8Gb of RAM. Both with linux that is more memory efficient.

**Comment by akosyakov** [comment]
> To note, with 20000 it hanged on both a PC with an intel i7 and 6Gb of RAM and another with intel i5 and 8Gb of RAM. Both with linux that is more memory efficient.

You need to increase memory limit of your browser to make use of it: https://stackoverflow.com/a/32671934/961588

**Comment by jgaiao** [comment]
Nice tip, was not aware of that (even tho I change that limit on Node.js all the time). But It still hanged juicing up to 6144MB the limit on the 20000 line length.

running with:    google-chrome-stable --js-flags="--max_old_space_size=6144"

At least now that I know, will keep it at 400. Gladly it can be controlled in settings.

**Comment by gabihodoroaga** [comment]
This is happening also for Electron 9 on Mac. The application hangs completely the CPU is 100% and the only way to fix it is to close the application. I updated the  editor.maxTokenizationLineLength to be 400 and now work fine.

**Comment by akosyakov** [comment]
Could someone send a PR please to set 400 by default always? 🙏

**Comment by jgaiao** [comment]
Just sent a PR, needs reviewing

**Comment by vince-fugnitto** [comment]
Fixed by: #8027
