### ISSUE TITLE
Missing dependency for core package

### ISSUE THREAD

**Issue by mikael-desharnais** [eclipse-theia/theia#8030]
### Bug Description:
In the core package, the src/common/resource.ts file imports a class from vscode-languageserver-protocol but, vscode-languageserver-protocol does not belong to the dependencies. The problem shows only when some other package that provides this dependecy is provided

### How to solve
Simply add  "vscode-languageserver-protocol" : "^3.15.0-next.8" to the package.json

**Comment by vince-fugnitto** [comment]
@mikael-desharnais would you like to prepare a pull-request? :)

**Comment by mikael-desharnais** [comment]
Here it is : https://github.com/mikael-desharnais/theia/pull/1

**Comment by vince-fugnitto** [comment]
> Here it is : [mikael-desharnais#1](https://github.com/mikael-desharnais/theia/pull/1)

@mikael-desharnais you'll have to open the pull-request on the remote (this repository).

**Comment by mikael-desharnais** [comment]
Better now : https://github.com/eclipse-theia/theia/pull/8033
