### ISSUE TITLE
download:plugins fails if "theiaPlugins" is not present in package.json

### ISSUE THREAD

**Issue by lal12** [eclipse-theia/theia#8053]
### Bug Description:
download:plugins fails if "theiaPlugins" is not present in package.json

### Steps to Reproduce:
1. Follow guide on https://theia-ide.org/docs/composing_applications/
2. Remove "theiaPlugins" key from package.json
3. Run "theia download:plugins" or just "yarn"

### Additional Information

- Operating System: Ubuntu 20.04
- Theia Version: 1.2.0 and next

**Comment by akosyakov** [comment]
What would you expect? Docs says that you should have `theiaPlugins`.

**Comment by vince-fugnitto** [comment]
@lal12 the `download:plugins` script should only be used if you are actually planning to download the plugins defined in the `package.json`. If this is not your intentions then you should not call it (and neither should your prepare script). There is no reason to call the script if this is not your goal.

**Comment by lal12** [comment]
I would assume that you could have no object in there, if you are using a bunch of standard scripts. I would expect npm/yarn similar behavior, which also won't fail if no dependency property is specified.

However I also get your position. But in this case I think there should be a proper error message, currently there is just a TypeError.

**Comment by lal12** [comment]
I would assume that you could have no object in there, if you are using a bunch of standard scripts maybe from another project. I expected a npm/yarn compatible behavior, which also won't fail if no dependency property is specified.

However I also get your position and think failing is an acceptable option. But in this case I think there should be a proper error message, currently there is just a TypeError.

**Comment by vince-fugnitto** [comment]
> I would assume that you could have no object in there, if you are using a bunch of standard scripts. I would expect npm/yarn similar behavior, which also won't fail if no dependency property is specified.

It is a custom script, there is no real reason to call it if your intentions are not to download plugins.

> However I also get your position. But in this case I think there should be a proper error message, currently there is just a TypeError.

I'll update the error message, but the use-case is incorrect unfortunately.
