### ISSUE TITLE
preference: add support for 'files.trimTrailingWhitespace'

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#8059]
#### Feature Description:

The following preference should be included in the framework: `files.trimTrailingWhitespace`.
The preference is useful to control the automatic trimming of whitespace characters when saving a text document. At the moment, there is no automatic trimming present in the framework.

```ts
'files.trimTrailingWhitespace': {
  'type': 'boolean',
  'default': false,
  'description': nls.localize('trimTrailingWhitespace', "When enabled, will trim trailing whitespace when saving a file."),
  'scope': ConfigurationScope.LANGUAGE_OVERRIDABLE
}
```

#### Additional Information

- [VS Code Implementation](https://github.com/microsoft/vscode/blob/002d722585735a5b18c67f4dbf10d62e3f951c04/src/vs/workbench/contrib/files/browser/files.contribution.ts#L282-L286)

**Comment by colin-grant-work** [comment]
I'll take a crack at it.
