### ISSUE TITLE
Modal notification does not render newlines or have a max-width

### ISSUE THREAD

**Issue by tetchel** [eclipse-theia/theia#8071]
### Bug Description:
A modal dialog shown using
 ```
vscode.window.showWarningMessage(<msg>, { modal: true })
````

does not render newlines or have a max-width, which makes long messages stretch the dialog the width of the viewport, which looks weird.

### Steps to Reproduce:

Have a modal notification with a long message in it and newlines. In VS Code, the text is wrapped, and newlines are rendered.
![image](https://user-images.githubusercontent.com/8888438/85305377-fa812980-b47a-11ea-81ee-e75b91e5f044.png)

But in Theia, the newlines are ignored, and the dialog stretches.
![image](https://user-images.githubusercontent.com/8888438/85305537-30bea900-b47b-11ea-95f3-3ebfbeaccc92.png)

### Additional Information

- Operating System: all
- Theia Version: 0.15.0

**Comment by vince-fugnitto** [comment]
@tetchel would you like to prepare a pull-request to address the issue?

**Comment by kittaakos** [comment]
Known limitation: https://github.com/eclipse-theia/theia/issues/7283#issuecomment-595629453?

**Comment by vince-fugnitto** [comment]
> Known limitation: [#7283 (comment)](https://github.com/eclipse-theia/theia/issues/7283#issuecomment-595629453)?

The limitation is only for notification messages (toasts) similarly to vscode.
For notifications which are present in a dialog window, the explicit newlines are respected:

<div align='left'>

![aaa](https://user-images.githubusercontent.com/40359487/85404501-03cace80-b52d-11ea-9bde-6a5bb4664f47.png)

</div>

The issue I believe is that we likely do not handle template literal newlines and we don't have a `max-width` to the dialog to look consistent.

**Comment by kittaakos** [comment]
> The limitation is only for notification messages (toasts) similarly to vscode.

Yes, that was clear. `vscode.window.showWarningMessage` uses the notification messages.

**Comment by vince-fugnitto** [comment]
> > The limitation is only for notification messages (toasts) similarly to vscode.
> 
> Yes, that was clear. `vscode.window.showWarningMessage` uses the notification messages.

Unless we use `modal: true` as an option (then it is rendered as a modal and not a toast):

```ts
vscode.window.showWarningMessage(<msg>, { modal: true })
```

**Comment by kittaakos** [comment]
> Unless we use `modal: true` as an option (then it is rendered as a modal and not a toast):

I see your point. Is it a missing feature? So when `modal` is `true`, we should open a `Dialog` instead of a notification popup?

**Comment by vince-fugnitto** [comment]
> > Unless we use `modal: true` as an option (then it is rendered as a modal and not a toast):
> 
> I see your point. Is it a missing feature? So when `modal` is `true`, we should open a `Dialog` instead of a notification popup?

The custom dialog that I sent a screenshot of is the modal implementation that we currently have (we do not use the browser modal). The issue is that we probably do not support string literals with newlines (which is what the codewind extension uses), and we likely do not have any `max-width` to force wrapping of the textual content.
