### ISSUE TITLE
Browser, Electron restore widgets differently on show

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#8078]
### Bug Description:

A propos #8077, the behavior of the Preferences Widget, and perhaps React widgets more generally, is different in when Theia is run in the browser and when it is run in Electron. Here is an example of the `scrollTop` of the preferences-editor-widget during switch from that widget to another editor widget and back.

Here's the browser during a show-hide sequence:

![browser-hide-show](https://user-images.githubusercontent.com/62660806/83926174-b984d780-a74e-11ea-8f6d-9378a77fb151.png)

And here's Electron with the same code:

![electron-hide-show](https://user-images.githubusercontent.com/62660806/83926179-c275a900-a74e-11ea-83ab-9152959b9cbe.png)

### Steps to Reproduce:

1. Running in the browser,
1. Open the preferences widget
1. In the main pane, scroll down to an arbitrary point
1. Open another editor widget and switch focus to that widget (at this point, do not enter Zen mode by double-clicking on a widget tab. If you do that, your scroll will be lost on both platforms)
1. Switch focus back to the preferences widget.
1. Observe that your scroll position was preserved
1. Repeat in Electron, observe that your scroll position was lost.

<div align='center'>

![preferences](https://user-images.githubusercontent.com/40359487/85407065-b51f3380-b530-11ea-9efe-d234d7ec2897.gif)

</div>

### Additional Information

- Operating System: RHEL 7
- Theia Version: 1.2.0

**Comment by vince-fugnitto** [comment]
@colin-grant-work I opened the following issue but I'll keep yours opened since it has additional information: https://github.com/eclipse-theia/theia/issues/8077 :)

**Comment by colin-grant-work** [comment]
@vince-fugnitto, yes, sorry it took me a while to open the issue!

**Comment by vince-fugnitto** [comment]
@colin-grant-work I believe the issue has been fixed, I cannot reproduce it any longer.

**Comment by colin-grant-work** [comment]
I can't reproduce it either. 👍
