### ISSUE TITLE
[preview] Duplicate tab-toolbar action for the preview editor

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8088]
### Steps to Reproduce:

1. Open a `*.md` file,
2. Check the tab-toolbar.

![Screen Shot 2020-06-25 at 09 51 48](https://user-images.githubusercontent.com/1405703/85679294-91dbbc00-b6c9-11ea-8c86-cb378e07bf7e.jpg)

### Additional Information

- Operating System:
- Theia Version:

**Comment by vince-fugnitto** [comment]
@kittaakos I believe it is a duplicate of https://github.com/eclipse-theia/theia/issues/6984.
I wouldn’t say it is a bug as the builtin is contributing the extra toolbar item duplicating the functionality present. For downstream apps, they can choose to use the builtin or the theia extension.

**Comment by kittaakos** [comment]
Dupe of #6984
