### ISSUE TITLE
Some browser tests do not succeed anymore

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#8093]
### Bug Description:
It looks like the test don't run anymore. While publishing Theia version 1.3.0, I had to by-pass the browser test.
- On the other hand, Travis seems to pass all tests. 
- On my local computer, cleaning and executing the tests fail

Note: removing the $HOME/.theia solved some errors but not all
Do we have dependencies on the home folder?

The tests have been running a few times and we get the same result 

### Steps to Reproduce:

1. git clean -ffdx
2. yarn
3. yarn test
-> some tests don't succeed

### Additional Information
Errors:
1) **Find and Replace**
       Replace in the active editor:
     **TypeError: Cannot read property 'widgets' of null**
      at ViewContainer.../../packages/core/lib/browser/view-container.js.ViewContainer.getParts (bundle.js:128607:37)

root INFO   2) Menus
       **should toggle 'Explorer' view:
     Error: Timeout of 2000ms exceeded.** For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

root INFO   3) Menus
       reveal more **context menu in the explorer view** container toolbar:
     **TypeError: Cannot read property 'widgets' of null**
      at ViewContainer.../../packages/core/lib/browser/view-container.js.ViewContainer.getParts (bundle.js:128607:37)
      at Context.<anonymous> (/home/lmcbout/theia/stable/theia/examples/api-tests/src/menus.spec.js:88:42)

- Operating System: Ubuntu 18.04
- Theia Version: Latest

**Comment by vince-fugnitto** [comment]
The `view-spec.js` work when executed by themselves, but during the suite it fails locally.
I think it might be in a weird state due to other tests which are executed before.

**Comment by akosyakov** [comment]
Could we trace back to which PR started triggering a weird state?

**Comment by vince-fugnitto** [comment]
> Could we trace back to which PR started triggering a weird state?

I tested with the `v1.2.0` tag and the api integration test cases passed successfully, I'll try to pinpoint the regression.

**Comment by vince-fugnitto** [comment]
I identified the breaking commit as fdd7c41afccc4bd3358374cfe42edf1a1d2c848b using [git bisect](https://git-scm.com/docs/git-bisect).

**Comment by vince-fugnitto** [comment]
> I identified the breaking commit as [fdd7c41](https://github.com/eclipse-theia/theia/commit/fdd7c41afccc4bd3358374cfe42edf1a1d2c848b) using [git bisect](https://git-scm.com/docs/git-bisect).

I identified the commit (where the tests started to fail locally), however I was unable to determine how to fix them.
I tried temporarily to skip the failing tests but it still causes the entire suite to fail. I'm wondering if the tests are interdependent on eachother causing them to be in a weird state.

**Comment by akosyakov** [comment]
I will have a look later this week. Tests are run together in the same app.

**Comment by akosyakov** [comment]
It is reproducible when menus and views tests are enabled.

**Comment by akosyakov** [comment]
It is timing issue, https://github.com/eclipse-theia/theia/commit/fdd7c41afccc4bd3358374cfe42edf1a1d2c848b makes sure that VS Code extensions views are properly registered in the explorer (shell). It slows down the creation of the navigator.
