### ISSUE TITLE
vsx-registry: installed licenseUrl cannot be opened

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#8094]
#### Bug Description:

Selecting the `license` field of a builtin extension fails to open the proper webpage.

#### Steps to Reproduce:

1. start the browser application
2. open the extensions-view
3. select a builtin extension (opening the extension info including the readme)
4. select the license, notice the incorrect webpage opened 

#### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: Latest

![Vsx-NoLicenseLink](https://user-images.githubusercontent.com/419051/85787691-c5363f00-b6f9-11ea-9689-3f8a7cc7d9b6.gif)

**Comment by vince-fugnitto** [comment]
The error occurs for builtin extensions, I updated the issue to reflect it.
