### ISSUE TITLE
[vsx] VSX registry should return license and other information for the currently installed version and not the latest

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8097]
### Bug Description:

Originally logged [here](https://github.com/eclipse-theia/theia/pull/8095#issuecomment-650113825):
> Nice, I have tried it with the electron example, and I could open the license in my OS browser 👍
> When I open the license for this extension
> ![Screen Shot 2020-06-26 at 12 40 51](https://user-images.githubusercontent.com/1405703/85848990-6ed50900-b7aa-11ea-8758-4293a5d004ba.jpg),
> it opens the following URL: https://open-vsx.org/api/vscode/xml/1.46.1/file/LICENSE-vscode.txt
> I do not understand the version difference between the VS Code extension and the link.

----
If I have `vscode-builtin-xml@1.44.2` installed, I want to see the license for that particular version and for the latest, as they might not be in sync.

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by vince-fugnitto** [comment]
I believe the issue is resolved, the information present when opening the `readme.md` of the extension reflects the actual supported version (including the license) and not the `latest`. Please re-open if this is not the intention of the fix.
