### ISSUE TITLE
Create a plugin to log theia logs to a centralised server 

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#810]
Log to https://github.com/jaegertracing/jaeger for example

**Comment by hexa00** [comment]
Talking to more people it seems this stack with fluentd is more common https://www.digitalocean.com/community/tutorials/elasticsearch-fluentd-and-kibana-open-source-log-search-and-visualization

**Comment by vince-fugnitto** [comment]
I do not believe there are any plans at the moment to provide a vscode extension to send logs to a centralized server.
The issue is quite outdated, we can open a new issue if there are any needs for such an extension in the community.
