### ISSUE TITLE
vsx-registry: scrolling and selecting a tree-node jumps back to the top

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#8101]
#### Bug Description:

I notice the issue constantly when attempting to navigate through the builtins extensions.
When scrolling the builtin extensions and selecting a tree-node (extension), the tree jumps back to the top of the list.
Therefore, in order to successfully navigate to the extension I am interested in, it requires me to perform the selection twice.

![extensions](https://user-images.githubusercontent.com/40359487/85875119-bc994380-b7a1-11ea-8cc7-fb2c84931591.gif)

#### Steps to Reproduce:

1. open the extensions-view
2. expand the builtin extensions section, scroll and select an extension
3. notice the selection jumps to the top

**Comment by colin-grant-work** [comment]
I recently ran into a related bug on another tree widget. I think it is related to the fact that priority is given to `focus` in the `scrollToSelected` method. It seems that the first selection causes a scroll to selected targeting the focused element of the tree, and then the second selection actually takes hold and transfers both selection and focus to the new element.

```
    protected scrollToSelected(): void {
        if (this.props.scrollIfActive === true && !this.node.contains(document.activeElement)) {
            return;
        }
        const focus = this.node.getElementsByClassName(FOCUS_CLASS)[0];
        if (focus) {
            ElementExt.scrollIntoViewIfNeeded(this.scrollArea, focus);
        } else {
            const selected = this.node.getElementsByClassName(SELECTED_CLASS)[0];
            if (selected) {
                ElementExt.scrollIntoViewIfNeeded(this.scrollArea, selected);
            }
        }
    }
```

**Comment by vince-fugnitto** [comment]
> I recently ran into a related bug on another tree widget. I think it is related to the fact that priority is given to `focus` in the `scrollToSelected` method. It seems that the first selection causes a scroll to selected targeting the focused element of the tree, and then the second selection actually takes hold and transfers both selection and focus to the new element.

That description seems consistent with what I experienced as well, the second selection as you mentioned works and sets the selection and focus to the intended element.

**Comment by colin-grant-work** [comment]
Yes, it looks like a click on the widget when focus isn't on it causes two render cycles, and the first one triggers scroll to selected before the selection is registered.

**Comment by gaomin** [comment]
> I recently ran into a related bug on another tree widget. I think it is related to the fact that priority is given to `focus` in the `scrollToSelected` method. It seems that the first selection causes a scroll to selected targeting the focused element of the tree, and then the second selection actually takes hold and transfers both selection and focus to the new element.
> 
> ```ts
>     protected scrollToSelected(): void {
>         if (this.props.scrollIfActive === true && !this.node.contains(document.activeElement)) {
>             return;
>         }
>         const focus = this.node.getElementsByClassName(FOCUS_CLASS)[0];
>         if (focus) {
>             ElementExt.scrollIntoViewIfNeeded(this.scrollArea, focus);
>         } else {
>             const selected = this.node.getElementsByClassName(SELECTED_CLASS)[0];
>             if (selected) {
>                 ElementExt.scrollIntoViewIfNeeded(this.scrollArea, selected);
>             }
>         }
>     }
> ```

Hello, I reproduced the problem in the vscode tree view plugin, just like #10280 ,and when I debug, I found after click tree item toggle icon, scrollToSelected function is not called, handleScroll function is called and scrollTop is the selected tree item.
I feel like the problem is caused by the List rerender, maybe this is a bug of react-virtualized, and I found a this issue, but I'm not sure it's the same problem :
https://github.com/bvaughn/react-virtualized/issues/1745
