### ISSUE TITLE
Error while creating theia hello world plugin

### ISSUE THREAD

**Issue by itthought** [eclipse-theia/theia#8104]
I am getting error while trying to create hello world plugin. 

➜  mkdir theia-plugin
➜  cd theia-plugin 
➜  yo @theia/plugin

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │   Welcome to the 'Theia  │
   `---------´   │    Plug-in' generator!   │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What is the plug-in's name? hello world plugin
? What type of plug-in do you want? Backend plug-in, it will run on the server side.
? Please, choose a template: Hello World plug-in
License is not specified. You can do it via --license parameter.
   create hello-world-plugin/package.json
   create hello-world-plugin/.gitignore
   create hello-world-plugin/README.md
   create hello-world-plugin/tsconfig.json
   create hello-world-plugin/tsfmt.json
   create hello-world-plugin/src/hello-world-plugin-backend.ts
Installing dependencies with yarn...
yarn install v1.22.0
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
$ yarn run clean && yarn run build
yarn run v1.22.0
$ rimraf lib
Done in 0.32s.
yarn run v1.22.0
$ yarn run format-code && yarn run compile && theia-plugin pack
$ tsfmt -r
$ tsc
node_modules/@theia/plugin/src/theia.d.ts(4733,29): error TS2304: Cannot find name 'Thenable'.
node_modules/@theia/plugin/src/theia.d.ts(4742,29): error TS2304: Cannot find name 'Thenable'.
node_modules/@theia/plugin/src/theia.d.ts(4788,29): error TS2304: Cannot find name 'Thenable'.
node_modules/@theia/plugin/src/theia.d.ts(4797,29): error TS2304: Cannot find name 'Thenable'.
node_modules/@theia/plugin/src/theia.d.ts(4843,29): error TS2304: Cannot find name 'Thenable'.
node_modules/@theia/plugin/src/theia.d.ts(4852,29): error TS2304: Cannot find name 'Thenable'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

- Operating System: MAC and Debian os(ubuntu 16.04)

**Comment by akosyakov** [comment]
Please move to https://github.com/eclipse/theia-generator-plugin
