### ISSUE TITLE
Open deleted file in GIT SCM causes errors

### ISSUE THREAD

**Issue by datou0412** [eclipse-theia/theia#8106]
### Bug Description:
Open deleted file in GIT SCM causes errors

### Steps to Reproduce:
1. delete any file
2. open it in scm

UnStaged Case
![image](https://user-images.githubusercontent.com/5847142/85986985-984a9a80-ba1f-11ea-9f65-bcd2ec5185a7.png)

Staged Case
![image](https://user-images.githubusercontent.com/5847142/85987172-dfd12680-ba1f-11ea-9573-5e1e8f754cd5.png)

### VS Code Case 
UnStaged Case
![image](https://user-images.githubusercontent.com/5847142/85987882-d7c5b680-ba20-11ea-92a5-e7b9372c492a.png)

Staged Case
![image](https://user-images.githubusercontent.com/5847142/85987947-edd37700-ba20-11ea-90d5-4c1fe4e8257b.png)

### Additional Information

- Operating System: MacOS Mojave 10.14.6
- Theia Version: 1.3.0

**Comment by akosyakov** [comment]
We should not use `file` scheme for deleted files. It won't be able to resolve anything from the disk.
