### ISSUE TITLE
Storing the previously opened WS roots should be application specific

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#811]
This task is a follow-up of #809.

If one uses multiple Theia-based applications, one application might override the WS root settings of another application in the user's home directory.

See also: https://github.com/theia-ide/theia/pull/809#issuecomment-343409646

**Comment by hexa00** [comment]
Actually should we juste have a .application name directory instead of a .theia ?

**Comment by kittaakos** [comment]
It is up to the implementation. If we go with the application name folder approach, we have to know the name of the application at runtime. Perhaps, we would need an app specific binding which is not the best because we would force each Theia adapter to customize that binding.

I do not know the proper solution yet. I thought we could distinguish based on the path of the underlying process. That should be unique per application. One needs to define this before implementing this task.

**Comment by hexa00** [comment]
I vote for a binding since I don't want to give to much meaning to the path.

This binding was proposed before in #687 so it may come up again.

**Comment by kittaakos** [comment]
Resolved via https://github.com/eclipse-theia/theia/pull/7214.
