### ISSUE TITLE
[output][ui/ux] Remove the margin of the editor

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8110]
### Bug Description:

It's a minor styling issue but I assume we do not want to see the editor margin in the `Output` view. See the attached images.
![Screen Shot 2020-06-29 at 13 40 47](https://user-images.githubusercontent.com/1405703/86000902-709f0680-ba0e-11ea-88c9-8ea88b564027.jpg)
![Screen Shot 2020-06-29 at 13 41 00](https://user-images.githubusercontent.com/1405703/86000909-71d03380-ba0e-11ea-9ff4-364f07d3c2b8.jpg)

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by mikael-desharnais** [comment]
Hi,
which version of theia do you use ?
I don't have the same border : 
![image](https://user-images.githubusercontent.com/1853427/86340728-a7b32900-bc55-11ea-8372-adeb93f78ac8.png)
Regards,

**Comment by kittaakos** [comment]
Hm, good point. I made the screenshots from the electron application, but that app was slightly customized. Maybe it's a problem only on my side. Let me check with vanilla Theia and update this thread. Thanks for the heads-up, @mikael-desharnais!

**Comment by kittaakos** [comment]
> Maybe it's a problem only on my side

It is.
