### ISSUE TITLE
There has anyway to override the Chrome's / OS's shortcuts ?

### ISSUE THREAD

**Issue by howel52** [eclipse-theia/theia#8118]
### Feature Description:
Some shortcuts are often used like `cmd + w`, `cmd + t` when we use the VSCode(Electron App).

But in the web environment,  there has some conflicts  between `Web Editor` And `Browser`

Has anyway to resolve this problem ?

Maybe we need some feature to proxy user's keyboard event  in the web environment？  Or in some other ways.

**Comment by akosyakov** [comment]
Generally it is impossible as for now browsers don't allow to override certain shortcuts. There is a special browser window mode which allows it, i.e. a pop-up window. But that's it. One possible solution would be to provide Electron Theia but which talks to remote Theia backend.
