### ISSUE TITLE
package @theia/plugin : Cannot find name 'Thenable'.

### ISSUE THREAD

**Issue by mikael-desharnais** [eclipse-theia/theia#8119]
### Bug Description:
node_modules/@theia/plugin/src/theia.d.ts:4797:29 - error TS2304: Cannot find name 'Thenable'.

### Steps to Reproduce:

1.Pull the Theia repo
2.follow : https://theia-ide.org/docs/authoring_plugins to create a backend plugin
3.execute yarn in your plugin's folder

### Additional Information

- Operating System: Windows 10
- Theia Version: latest

**Comment by kittaakos** [comment]
You have to add `"skipLibCheck": true` to your `tsconfig.json`. I had the exact same problem an hour ago, so I am going to close it. Feel free to reopen if the suggested solution does not work. Also, make sure you [compile against ES5](https://github.com/eclipse-theia/theia/issues/6761): `"target": "es5",`.
