### ISSUE TITLE
Unable to install theia dependencies 

### ISSUE THREAD

**Issue by varadekd** [eclipse-theia/theia#8120]
### Steps to Reproduce:

1.  Create a dir name theiaEditor
2.  Go to the theiaEditor
3.  add package.json from here https://theia-ide.org/docs/composing_applications/
4. run yarn in your terminal 

Error 
```
warning monaco-languageclient@0.13.0: The engine "vscode" appears to be invalid.
warning vscode-languageclient@6.1.3: The engine "vscode" appears to be invalid.
error find-git-exec@0.0.2: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <12". Got "12.18.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Additional Information

- Operating System: Mac OS catalina 10.15.5
- Node Version: 12.8.1

**Comment by vince-fugnitto** [comment]
@varadekd the error message is quite clear, you attempted to install with an unsupported `node` version:

>  Expected version ">=10.11.0 <12". Got "12.18.1"

Additional Info:
- https://github.com/eclipse-theia/theia/issues/7349

**Comment by vince-fugnitto** [comment]
You can also reference the [prerequisites](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites).

**Comment by Unifex** [comment]
I was having this issue today also.  Old version of node led me here.

The Prerequisites no longer work.  There is a reference to the Active LTS for NodeJS.  You need to use the v12 Maintenance LTS instead.

Looking at the release history at the time @vince-fugnitto made their comment v12 would have been the Active LTS.

**Comment by vince-fugnitto** [comment]
@Unifex thank you for the discussion, what exact issue were you having and at what version of the framework?

**Comment by DayronDLR** [comment]
![image](https://user-images.githubusercontent.com/37316384/218350645-1b81bb7d-eba1-4a18-bc2d-11ddb0a4f5f9.png)

In the prerequisites they said this... however, yarn doesn't work in the Theia package even complying with the prerequisites.

![image](https://user-images.githubusercontent.com/37316384/218351107-ba75d7cf-1124-4734-8c4d-f1ae71947a23.png)

Now, when I use nvm 11, the error is this...

![image](https://user-images.githubusercontent.com/37316384/218351312-d508a825-1b3b-4652-bf90-afc31cdb5d99.png)

**Comment by vince-fugnitto** [comment]
@DayronDLR what version of `@theia` are you attempting to build? If you try the latest or build `master` it should definitely work, I haven't seen Node 11 used for quite some time. It may also be that you need to upgrade your `yarn.lock` if you haven't already done so.
