### ISSUE TITLE
vscode extension - jupyter notebook fails.

### ISSUE THREAD

**Issue by rholland** [eclipse-theia/theia#8161]
I am running Theia at Gitpod. They directed me here.

visx extension here:
(https://marketplace.visualstudio.com/items?itemName=ms-python.python)

When I click on "run cell" in Python  editor I get:

![image](https://user-images.githubusercontent.com/3033195/87274757-5f83da00-c491-11ea-932e-d0b5f5dd9466.png)

**Comment by vince-fugnitto** [comment]
Thank you for the issue @rholland.
Closing since we already have duplicate issues tracking `jupyter notebook support` at the moment:
- https://github.com/eclipse-theia/theia/issues/3186
- https://github.com/eclipse-theia/theia/issues/4956
