### ISSUE TITLE
Upgrade vscode-ripgrep, to solve proxy issue

### ISSUE THREAD

**Issue by Niklas-Dahlquist** [eclipse-theia/theia#8171]
### Bug Description:
Current used version of vscode-ripgrep doesn't handle proxy settings correctly. This is fixed in version 1.8.0. Upgrade yarn.lock file to use this version

vscode-ripgrep@^1.2.4:
  version "1.8.0"
  resolved "https://registry.yarnpkg.com/vscode-ripgrep/-/vscode-ripgrep-1.8.0.tgz#dfe7c2ae2a2032df8a8108765c2feef73474888a"
  integrity sha512-/Q5XtePkTLLi8yplr5ai24pVEymRF62xH9xXrtj35GTaDCJg3zq1s1/L1UqhVbfNDv4OcMBYjyIAt/quEi3d5w==
  dependencies:
    https-proxy-agent "^4.0.0"
    proxy-from-env "^1.1.0"

### Steps to Reproduce:

1. do yarn behind a proxy
2. without the upgraded vscode-ripgrep it will fail like #7384

**Comment by vince-fugnitto** [comment]
@Niklas-Dahlquist would you like to prepare a pull-request to resolve the issue?
