### ISSUE TITLE
ElectronTokenBackendContribution may add a whitelist config that does not need to carry tokens.

### ISSUE THREAD

**Issue by zhaomenghuan** [eclipse-theia/theia#8176]
I try to write a BackendApplicationContribution to use express.static to host my static resources，when I use the Electron WebView tag to load the page of my resources, the html file of the entrance is accessed normally, and the inline JS and CSS files cannot be accessed and show a 403 error.

I tried to inject cookies into the Electron WebView tag and tried to intercept resource requests to add headers, but none of them worked.

I tried the following code, because the execution timing problem does not take effect：
```
configure(app: express.Application): void {
  app.use('/devtools', (req, res, next) => {
    const tokenValue = process.env[ElectronSecurityToken]?.toString() as string;
    req.headers.cookie = `${ElectronSecurityToken}=${tokenValue}`;
    next();
  }, express.static(path.join(DevToolsFrontend, 'devtools')));
}
```

So I think it is necessary to provide the configuration of ElectronTokenBackendContribution to allow certain requests not to be verified, but to be verified by the extension itself.

**Comment by akosyakov** [comment]
cc @marechal-p
