### ISSUE TITLE
[quality][json] Check why we depend on `@theia/json` in the TS tests

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8183]
### Bug Description:

Follow-up of: https://github.com/eclipse-theia/theia/issues/8181

Let's check why we have this in the code and how does the test pass?
https://github.com/eclipse-theia/theia/blob/9afc819182ae94cd44f19efe42828ce704d9fecc/examples/api-tests/src/typescript.spec.js#L115

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by tsmaeder** [comment]
@kittaakos you openend a PR that _removes_ that dependency, but then close it. Can you comment why?

**Comment by vince-fugnitto** [comment]
We no longer make use of `@theia/json` in https://github.com/eclipse-theia/theia/blob/master/examples/api-tests/src/typescript.spec.js.
