### ISSUE TITLE
Node12, can't install

### ISSUE THREAD

**Issue by mikael-desharnais** [eclipse-theia/theia#8189]
### Bug Description:
When trying to launch yarn for the current master branch of the repo, I get the following error :

error dugite-extra@0.1.12: The engine "node" is incompatible with this module. Expected version ">=10.11.0 <12". Got "12.18.2"
error Found incompatible module.

### Steps to Reproduce:

1. clone repo
2. launch yarn

### Additional Information

- Operating System: Windows 10
- Theia Version: latest

**Comment by vince-fugnitto** [comment]
@mikael-desharnais do you mind identifying the commit `sha` you are currently building?
I quickly verified and was able to build with `v12.18.2`. Based on your engines restriction it looks like you may be on an old commit.

**Comment by mikael-desharnais** [comment]
My latest commit : 
commit 9afc819182ae94cd44f19efe42828ce704d9fecc (HEAD -> master, origin/master, origin/HEAD)
Author: Akos Kitta <kittaakos@typefox.io>
Date:   Thu Jun 4 16:33:07 2020 +0200

    GH-7349: Support for Node.js 12.x

     - Updated the `@babel` dependencies to fix babel/babel#11216#issuecomment-634460665.
     - Pinned the `node-abi` version in the `resolutions` to support latest `electron`.
     - Use Node.js 12.14.1 for Gitpod.

    Closes #7349

    Co-authored-by: Anton Kosyakov <anton.kosyakov@typefox.io>
    Signed-off-by: Akos Kitta <kittaakos@typefox.io>

**Comment by vince-fugnitto** [comment]
I just built using the node version I referenced and it works correctly on my end.
As you can see, the `engines` tag was [updated](https://github.com/eclipse-theia/theia/commit/9afc819182ae94cd44f19efe42828ce704d9fecc#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7). At which point does your build fail?

You can try to do a fresh build:

```
git clean -ffdx
yarn
```

**Comment by mikael-desharnais** [comment]
It works now.

I reinstalled from repo and now it works fine too, sorry for the bother...
