### ISSUE TITLE
Cannot start electron using node 12

### ISSUE THREAD

**Issue by lmcbout** [eclipse-theia/theia#8190]
### Bug Description:
Upgrade node to use version 12 and electron does not start
Tested with the browser and it works

### Steps to Reproduce:

1. git pull
2. git clean -ffdx
3. yarn 
4. yarn start:electron

gyp ERR! System Linux 4.15.0-111-generic
gyp ERR! command "/home/lmcbout/.nvm/versions/node/v12.18.2/bin/node" "/home/lmcbout/theia/stable/theia/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=9.0.2" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /home/lmcbout/theia/stable/theia/node_modules/@theia/node-pty
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1

### Additional Information

- Operating System: Ubuntu 18.04
- Theia Version: latest commit 9afc819182ae94cd44f19efe42828ce704d9fecc

**Comment by kittaakos** [comment]
> 4\. yarn start:electron

I am not sure what you did, but I usually start the app with either `cd ./examples/electron && yarn start` or `yarn --cwd ./examples/electron start`. Please do not forget to run `yarn rebuild:electron`, I do not see that in your steps.

Can you please try again. Frankly, I did not try it on Linux, but it [was verified on Gitpod](https://github.com/eclipse-theia/theia/pull/7968#issuecomment-658689629) (running on Linux) with VNC.

**Comment by kittaakos** [comment]
If it still does not work, please share the entire error log.

**Comment by lmcbout** [comment]
I don't know what happen, I also use electron for another application and when I tried again with Theia  with yarn start:electron (which does "yarn rebuild:electron && yarn --cwd examples/electron start" ) it started to work using node 12.

False alarm 
Thanks @kittaakos
