### ISSUE TITLE
API change in @theia/core without version change

### ISSUE THREAD

**Issue by mikael-desharnais** [eclipse-theia/theia#8194]
### Bug Description:
The following commit : https://github.com/eclipse-theia/theia/commit/fa71e1be509f20edf163eb0310fa8a42ab198bef
changed the API of the @theia/core adding JsonSchemaRegisterContext & JsonSchemaContribution to the /browser/json-schema-store.ts file but there was no change in versions.

So if you remove the core package in the packages older, restart a yarn to install the missing package your get some errors like : 
Module '"../../../../node_modules/@theia/core/lib/browser/json-schema-store"' has no exported member 'JsonSchemaReg
isterContext'.
because yarn fetches the original 1.3 version not the one that was created by this commit.

Of course, you could ask me why I would want to remove the core package, I'm investigating a bug that appears only if the core package is in node_modules and a other packages are in packages folder (on windows : related to this bug : https://github.com/nodejs/node/issues/6978).

### Steps to Reproduce:

1. Clone the repo
2. remove the packages/core
3.launch yarn

### Additional Information

- Operating System: Windows/NodeJS 12
- Theia Version: latest master

**Comment by vince-fugnitto** [comment]
@mikael-desharnais I'm not sure I understand the issue you described but note that `@theia/core` is a mandatory extension, it is not possible to remove it from your application.

**Comment by mikael-desharnais** [comment]
If I remove the packages/core folder, and restart yarn, the version 1.3.0 specified by the package.json is downloaded. The problem is that the 1.3.0 provided by yarn does not contain the same code then the 1.3.0 present in the current master branch.
As I understand it, if the packages/core exists, yarn just creates a symbolic link to this folder in the node_modules/@theia/core to point to this extension but if it does not exist, it gets downloaded by yarn.
The problem is that as the version number did not change with the API modification, the wrong version is downloaded.
This problem will be present with the yeoman extension generator as the core package is downloaded by yarn in this case.

**Comment by vince-fugnitto** [comment]
@mikael-desharnais I believe it may be a misunderstanding of how npm versioning works, the new changes (`master`) are not `1.30.0`, they are picked up by using `^1.3.0` as can be seen by packages maintained in this repository:

https://github.com/eclipse-theia/theia/blob/349fd069f2e1fbe0fccbaa6c5e917f01d41411db/packages/getting-started/package.json#L5-L10

We have releases at the endd of each month to actually publish `latest` versions (`1.4.0`) if that's what you are interested in.

**Comment by mikael-desharnais** [comment]
Ok thanks
