### ISSUE TITLE
[dialog][workspace] Enhance the validation message when creating a new resource

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8210]
It would be great to know whether it is a file or a directory:

https://github.com/eclipse-theia/theia/blob/4c63f08a6283f19f6f28727727378f7c1e38e316/packages/workspace/src/browser/workspace-commands.ts#L386

Let's improve the validation message.

**Comment by xpomul** [comment]
This issue should be closed. See discussion in PR #10527 for details.
