### ISSUE TITLE
Allow for no-results message in editor.action.goToLocations-command

### ISSUE THREAD

**Issue by jdneo** [eclipse-theia/theia#8212]
### Feature Description:
Now VS Code supports to show a no result found message when calling the command `editor.action.goToLocations`. It would be great if theia could also support this.

reference: https://github.com/microsoft/vscode/issues/95308

**Comment by akosyakov** [comment]
We need new Monaco for it which was not even released yet. Please file an issue of VS Code to repo to release a new version. The last released version is 6 months old.

**Comment by vince-fugnitto** [comment]
The feature should work out-of-the-box with the updated version of monaco. If it doesn't please re-open or comment.
