### ISSUE TITLE
Add a setting menu on left-side-bar-bottom

### ISSUE THREAD

**Issue by datou0412** [eclipse-theia/theia#8226]
### Feature Description:
Theia's setting menu is placed as a submenu of file menu. Its too deep for users to find and operate
![image](https://user-images.githubusercontent.com/5847142/88259141-47fbeb00-ccf4-11ea-95b6-2101d130dfe4.png)

VSCode placed its setting menu on the left sidebar bottom, its easier for users to notice
![image](https://user-images.githubusercontent.com/5847142/88259027-11be6b80-ccf4-11ea-92a9-8228e3305f81.png)

**Comment by bowei-jbw** [comment]
+1
