### ISSUE TITLE
Task schema support stops working

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#8230]
### Bug Description:
Last time during my work using `Theia` project I'm facing with the state when Task schema support stops working.
Please see additional info below

### Steps to Reproduce:
I don't have reliable steps to reproduce at the moment.
Looks like I face with the problem after a few cycles: 
`open tasks.json` ---> `edit/add a configuration` ---> `close tasks.json` --->... 

Page refresh resolves the problem, but then I face with the problem again...

### Additional Information
The error message is: `Unable to load schema from 'vscode://schemas/tasks': A resource provider for 'vscode://schemas/tasks' is not registered.`

![tasks_schema_error1](https://user-images.githubusercontent.com/5676062/88405463-fc227200-cdd7-11ea-9553-860a25fb482e.gif)

- Operating System: Fedora-31
- Theia Version: fd239889618f16b8ac48d50a754bf363ee5230c9

**Comment by akosyakov** [comment]
It seems to be a race between registration of task schema configurations and activation the json built-in extension, i.e. it tries to fetch schema configurations too early. That's quite critical if it is true, since it can affect all other schema configurations.

**Comment by akosyakov** [comment]
It is a race condition between initial registration of the resource and schema update. I am not sure how to reproduce but from the code it makes sense. I will move initial registration in post construct hook to ensure existence of a resource.
