### ISSUE TITLE
Gitlens "You, XYZ minutes ago | Y authors" overlay text in the wrong position

### ISSUE THREAD

**Issue by timonbimon** [eclipse-theia/theia#8232]
### Bug Description:
The layout of Gitlens does not seem to be working properly for Theia. Please compare the two screenshots (the first one from Theia, the second from VS Code).

![image](https://user-images.githubusercontent.com/14793026/88456823-5aeff600-ce81-11ea-8325-bec444c2e698.png)
![image](https://user-images.githubusercontent.com/14793026/88456826-63e0c780-ce81-11ea-9ec9-618ea3e2c047.png)

I'm not super reliant on GitLens so will probably just de-install it for now, but just wanted to let you guys know :)
(Also not 100% sure if this is a Theia issue or a Gitlens issue)

### Steps to Reproduce:
1. Install the GitLens extension
2. Seems to work fine on the file that is currently open
3. Navigate to another file and be bothered by the ugly overlay of the Gitlens added text

### Additional Information

- Operating System: Gitpod
- Theia Version: The one that comes with Gitpod ^^

**Comment by svenefftinge** [comment]
I've seen this with other code lenses as well.

**Comment by vince-fugnitto** [comment]
I haven't noticed the issue in a while, if we reproduce again we can always open a new issue with updated steps to reproduce.
