### ISSUE TITLE
[terminal] cursor obscures the terminal prompt

### ISSUE THREAD

**Issue by tekumara** [eclipse-theia/theia#8233]
### Bug Description:

When typing in the terminal, the text is obscured by the cursor:

<img width="475" alt="Screen Shot 2020-07-26 at 3 01 07 pm" src="https://user-images.githubusercontent.com/125105/88471836-d9679900-cf50-11ea-923e-bfb15999ddf9.png">

### Steps to Reproduce:

1. Run `docker run -it --init -p 3000:3000 -v "$(pwd):/home/project" theiaide/theia-python:latest`
1. Open a terminal

### Additional Information

- Operating System: macOS
- Theia Version: 1.3.0

Digest: sha256:4af87860f934056ce7ded9ea2972308d27fe41b9c51eace4fc5788869d616678
Status: Downloaded newer image for theiaide/theia-python:latest

**Comment by vince-fugnitto** [comment]
The issue has been fixed https://github.com/eclipse-theia/theia/pull/8204 (`next` version). The `latest` version will be updated this week with the release (July 31st).
