### ISSUE TITLE
No "Close on File Delete" Setting option compared to vscode

### ISSUE THREAD

**Issue by DoroNahari** [eclipse-theia/theia#8235]
### Bug Description:
No "Close on File Delete" Setting option compared to vscode.

vscode:
![image](https://user-images.githubusercontent.com/24614792/88509357-8db4fe00-cfe9-11ea-9aff-982c525d81db.png)

- Operating System: Mac os
- Theia Version: latest

**Comment by akosyakov** [comment]
It probably will be covered as a part of https://github.com/eclipse-theia/theia/issues/8138.

**Comment by vince-fugnitto** [comment]
Fixed thanks to https://github.com/eclipse-theia/theia/pull/8731.
