### ISSUE TITLE
[languages] Expose document symbols agnostic to monaco

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#825]
It will be nice to expose `provideDocumentSymbols` function or `documentSymbolProviders` in `Languages`:
https://github.com/theia-ide/theia/blob/720bbd2245f477334890a1f471798b02a072e0f3/packages/languages/src/common/languageclient-services.ts#L19-L21

Otherwise, extension developers have to deal with Monaco to access them. Probably most of the outline integration code then can be moved out of the monaco extension to the outline or editor extension. And other views based on document symbol information can be supported agnostic to monaco, like https://github.com/Bogdan-Lyashenko/js-code-to-svg-flowchart.

**Comment by tsmaeder** [comment]
Languages support is gone.
