### ISSUE TITLE
[VSCode extension] Ruby Language Server throws "TypeError: Cannot read property 'workspaceFolderUri' of null"

### ISSUE THREAD

**Issue by corneliusludmann** [eclipse-theia/theia#8255]
### Bug Description:

The [Ruby extension](https://open-vsx.org/extension/rebornix/ruby) does not work due to this error:

```
[Info  - 1:21:01 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /tmp/vscode-extensions/rebornix.ruby@0.27.0/extension/dist/server/tree-sitter-ruby.wasm
/tmp/vscode-extensions/rebornix.ruby@0.27.0/extension/dist/server/index.js:16
var r=function(t,e){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in e)e.hasOwnProperty(n)&&(t[n]=e[n])})(t,e)};function i(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}},function(t,e,n){"use strict";n.d(e,"a",function(){return l});var r=n(0),i=n(26),o=n(57),s=n(5),u=n(42),a=n(14),c=n(37),l=function(t){function e(n,r,i){var s=t.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof e?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new f(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new f(s,n,r,i)}return s}return r.a(e,t),e.prototype[u.a]=function(){ret
TypeError: Cannot read property 'workspaceFolderUri' of null
    at e.i.from.pipe.o.mergeMap.t [as project] (/tmp/vscode-extensions/rebornix.ruby@0.27.0/extension/dist/server/index.js:16:293003)
    at e._tryNext (/tmp/vscode-extensions/rebornix.ruby@0.27.0/extension/dist/server/index.js:16:30637)
    at e._next (/tmp/vscode-extensions/rebornix.ruby@0.27.0/extension/dist/server/index.js:16:30539)
    at e.next (/tmp/vscode-extensions/rebornix.ruby@0.27.0/extension/dist/server/index.js:16:1083)
    at /tmp/vscode-extensions/rebornix.ruby@0.27.0/extension/dist/server/index.js:16:134530
[Info  - 1:24:31 PM] Connection to server got closed. Server will restart.
```

Note: This happens only when the Ruby Language Server is activated in `.theia/settings.json` like this:
```json
{
    "ruby.codeCompletion": "rcodetools",
    "ruby.format": "standard",
    "ruby.intellisense": "rubyLocate",
    "ruby.useBundler": true,
    "ruby.useLanguageServer": true,
    "ruby.lint": {
      "rubocop": true,
      "useBundler": true
    }
}
```

According to the ruby extension docu using the Ruby Language Server is highly recommended.

Comment of @akosyakov:

> This extension does not use workspace.fs  API and does not contribute fs providers. It seems to be that configuration send to the language server is null then it should not be. … it is better to file an issue in Theia for it 

### Steps to Reproduce:

1. Use the Theia config provided above
1. Install Ruby extension: https://open-vsx.org/extension/rebornix/ruby
1. Open a ruby file
1. Watch the output of the Ruby Language Server in the output view

(I used Gitpod for this.)

### Additional Information

- Operating System: Web/Gitpod
- Theia Version: 1.2.0-next.99a7aa3c

Also with Theia version from sources: fd239889618f16b8ac48d50a754bf363ee5230c9

**Comment by corneliusludmann** [comment]
Extension versions:

- [rebornix.ruby](https://open-vsx.org/extension/rebornix/ruby): 0.27.0
- [wingrunr21.vscode-ruby](https://open-vsx.org/extension/wingrunr21/vscode-ruby): 0.27.0

**Comment by akosyakov** [comment]
@corneliusludmann Would you be able to verify against Theia from sources? Maybe it was fixed in the meantime and Gitpod Theia simple needs an upgrade?

**Comment by corneliusludmann** [comment]
> @corneliusludmann Would you be able to verify against Theia from sources? Maybe it was fixed in the meantime and Gitpod Theia simple needs an upgrade?

Sure. Verified in current master (fd239889618f16b8ac48d50a754bf363ee5230c9). I have adapted the description accordingly.
