### ISSUE TITLE
Relative Patterns don't work accross Platforms

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#8261]
### Bug Description:
When running the back end on linux and running the front end on Windows, document selectors using relative paths never match: For example, the CodeLensProvider for the Java Test Runner plugin never gets invoked when opening a Java file with a test in it. This works when both back-end and front-end run on the same platform

### Steps to Reproduce:

1. Install the Java Test Runner plugin (https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test)
2. Run Theia back-end on linux, open the browser on Windows
3. Clone https://github.com/che-samples/console-java-simple
4. Open the Singe file containing tests.
4. Observe: after initializing all plugins (you'll need java, java debug), you do not get a code lens saysing "Debug Test | Run Test".

### Additional Information

The problem arises that monaco compares the currently opened file with a relative glob pattern in the DocumentSelector by using URI.fsPath, which in turn calls this method: https://github.com/microsoft/vscode/blob/90efeb4f2dc41827b382c8bb5da1c3abfff9459f/src/vs/base/common/uri.ts#L579
This results in the path separators being converted to backslashes. However, the same treatment is not done with the pattern, so the paths will not match. For example, the open file might be file:///projects/foo/bar and the pattern we match might be /projects/foo/bar, but we'll end up comparing \projects\foo\bar with /projects/foo/bar, which obviously fails.
On VS Code this does not arise, since they're always running on the same machine.
The problem seems fixed in the master version of vs code: https://github.com/microsoft/vscode/blob/c86411397d528d96686345d94f0478fbd77cc0b2/src/vs/editor/common/modes/languageSelector.ts#L96

**Comment by akosyakov** [comment]
> On VS Code this does not arise, since they're always running on the same machine.

Not anymore with codespaces.

> The problem seems fixed in the master version of vs code: https://github.com/microsoft/vscode/blob/c86411397d528d96686345d94f0478fbd77cc0b2/src/vs/editor/common/modes/languageSelector.ts#L96

We need another Monaco upgrade 😬

**Comment by benoitf** [comment]
not here ? https://github.com/eclipse-theia/theia/blob/764b74045fc1d8e1f4db2870e5517b5dd44693de/packages/languages/src/common/language-selector/language-selector.ts

**Comment by akosyakov** [comment]
We could work it around though by patching `IRelativePattern` here: https://github.com/eclipse-theia/theia/blob/896948679a2a2fbb492841e5aa25ec5382066ba2/packages/plugin-ext/src/main/browser/languages-main.ts#L415

**Comment by benoitf** [comment]
Hi, we're not using https://github.com/eclipse-theia/theia/blob/764b74045fc1d8e1f4db2870e5517b5dd44693de/packages/languages/src/common/language-selector/language-selector.ts ?

**Comment by akosyakov** [comment]
> Hi, we're not using https://github.com/eclipse-theia/theia/blob/764b74045fc1d8e1f4db2870e5517b5dd44693de/packages/languages/src/common/language-selector/language-selector.ts ?

Monaco using internally https://github.com/microsoft/vscode/blob/c86411397d528d96686345d94f0478fbd77cc0b2/src/vs/editor/common/modes/languageSelector.ts#L96 for all feature registries.

**Comment by akosyakov** [comment]
@tsmaeder Are you going to make a PR or it is free to grab?

**Comment by tsmaeder** [comment]
Free to grab....currently just analyzing issues with java test runner, not fixing.
