### ISSUE TITLE
vscode: unable to run drawio extension 

### ISSUE THREAD

**Issue by hasegetc** [eclipse-theia/theia#8266]
### Bug Description:
I test the vs code drawio extention in theia, but when i open a drawio file, it pop out  :
"Activation extension Draw.io Integration failed: o.window.registerCustomEditorProvider is not a function"

### Steps to Reproduce:

1. download drawio vsix files from   https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio
2. put it in the theia/plugins file
3. run theia and open a drawio file

### Additional Information

- Operating System: Mac os
- Theia Version: v1.3.0

**Comment by vince-fugnitto** [comment]
@hasegetc thank you for reporting the issue, the custom editor API is not yet supported: https://github.com/eclipse-theia/theia/issues/6636

**Comment by vince-fugnitto** [comment]
Closing in favor of the parent issue: #6636.
