### ISSUE TITLE
KeybindingRegistry returns copies and original keybindings

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#8270]
### Bug Description:
KeybindingRegistry.getKeybindingsForCommand returns a list with copies of registered keybindings
KeybindingRegistry.getScopedKeybindingsForCommand returns a list with the original keybindings
I discovered this while testing. I guess it currently does not produce a visible bug, but is very confusing when you use the API, so I think it would be better to have the same behavior on both functions. If there is an agreement for either or option, I can provide a fix.
Reproduction:
See the following test case, the second assert fails.

```ts
const keybinding: Keybinding = {
  command: TEST_COMMAND.id,
  keybinding: 'F5'
};
keybindingRegistry.registerKeybinding(keybinding);
const registeredBindings = keybindingRegistry.getKeybindingsForCommand(TEST_COMMAND.id);
registeredBindings.forEach(element => {
  expect(element === keybinding, 'This suceeds').to.be.false;
});

const scopedBindings = keybindingRegistry.getScopedKeybindingsForCommand(KeybindingScope.DEFAULT, TEST_COMMAND.id);
scopedBindings.forEach(element => {
  expect(element === keybinding, 'This fails').to.be.false;
});
```
### Additional Information

- Operating System: Linux
- Theia Version: latest

**Comment by vince-fugnitto** [comment]
@JonasHelming I believe that `getScopedKeybindingsForCommand` is currently unused (based on not finding any references for it), I'd be fine to remove it if its the case (the code is also 3 years old and has not bee updated since).

**Comment by JonasHelming** [comment]
@vince-fugnitto : Thanks, let us keep this open for a week or so. If nobody objects, I will submit a fix removing it...

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto : Thanks, let us keep this open for a week or so. If nobody objects, I will submit a fix removing it...

I don't think there would be objections, others can comment on the pull-request itself anyways.
Ideally, code present in the project should at least have one client (caller) so we are able to verify it is working correctly, dangling code such as `getScopedKeybindingsForCommand` is not really benefiting anyone (no callers, no tests) so I believe it should be fine to remove.
