### ISSUE TITLE
Automated trailing white space trimming on save is making the auto-save feature unusable

### ISSUE THREAD

**Issue by anavarre** [eclipse-theia/theia#8286]
### Bug Description:

Upon saving any file, the trailing white space is being removed automatically. While great in practice, it makes the auto-save feature unusable if you save, say, every second. The reason why is as the user is typing code and pausing, then auto-save kicks in and removes the trailing white space. But it might very well be the user was pausing to think and then started typing again without realizing the trailing white space had been removed, thus causing frustration as the line of code will have become messed up.

### Steps to reproduce

1. Make sure `settings.json` is empty for both `User` and `Workspace`, which I _think_ makes settings back to the defaults?
2. Now open up any file, write anything and and with one or multiple white spaces
3. Save manually and observe any trailing white space is being removed automatically
4. Trying enabling auto-save, say to 1 second, and then try typing code, then pause for a bit without looking at your editor, now type again and pause. Observe how it becomes unusable to work with the default behavior as legit white spaces have been removed.

![theia-space-save](https://user-images.githubusercontent.com/293478/89095168-7bf99f00-d3cb-11ea-93c3-e5f5b99e4ba9.gif)

I did try to toggle promising preferences related to trimming white spaces and saving, but nothing worked.

I have 2 questions:

* Is this a default preference?
* Can it be overridden?
* Can't we instead have the option to auto-save when the user loses focus (e.g. when clicking in a different panel or changing context, as VSCode allows for)

### Additional Information

- Operating System: Ubuntu Linux, Chromium Version 84.0.4147.105 (Official Build) snap (64-bit)
- Theia Version: 1.2.0

**Comment by vince-fugnitto** [comment]
@anavarre thank you for reporting the issue, unfortunately I am unable to reproduce the behavior on newer versions of the framework. Do you happen to have a workspace to reproduce the issue (ex: perhaps you have an [`editorconfig`](https://github.com/editorconfig/editorconfig/wiki/Property-research:-Trim-trailing-spaces) file which takes effect), list of vscode extensions which you have included in your application?

**Comment by anavarre** [comment]
Thanks for looking into this. I understand you need more info so my next step will be to try and reproduce without our extensions and I'll report back here with findings and more info overall.

**Comment by anavarre** [comment]
Ok @vince-fugnitto sorry for the delay. This wasn't easy to find the root cause! Turns out it seems related to https://github.com/editorconfig/editorconfig-vscode/issues/268 so we'll try and pursue this there.

**Comment by vince-fugnitto** [comment]
> Ok @vince-fugnitto sorry for the delay. This wasn't easy to find the root cause! Turns out it seems related to [editorconfig/editorconfig-vscode#268](https://github.com/editorconfig/editorconfig-vscode/issues/268) so we'll try and pursue this there.

No problem! Thank you for following up!
