### ISSUE TITLE
Support vscode.DebugConfigurationProviderTriggerKind

### ISSUE THREAD

**Issue by DanTup** [eclipse-theia/theia#8289]
The latest version of VS Code has an enum `DebugConfigurationProviderTriggerKind` which allows a debug config provider to provide either debug configurations for `launch.json` or for the "automatic launch configs" feature.

Currently, accessing values from this enum (for ex. `DebugConfigurationProviderTriggerKind.Initial`) in an extension will fail on GitPod with "Activating extension foo failed: Cannot read property 'Initial' of undefined".

**Comment by vince-fugnitto** [comment]
Closing as I believe `DebugConfigurationProviderTriggerKind` is supported.
