### ISSUE TITLE
keymaps: 'Open Keyboard Shortcuts in JSON' command should create file if it does not exist

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#8301]
#### Bug Description:

The command `Open Keyboard Shortcuts in JSON` should create the `keymaps.json` file if it does not exist instead of throwing an error:

```
monaco-editor-provider.js:203 Uncaught (in promise) Error: 'user_storage:/keymaps.json' is invalid
    at MonacoEditorProvider.<anonymous> (monaco-editor-provider.js:203)
    at step (monaco-editor-provider.js:71)
    at Object.next (monaco-editor-provider.js:52)
    at fulfilled (monaco-editor-provider.js:43)
```

#### Steps to Reproduce:

1. make sure that the `keymaps.json` file does not exist (ex: `rm -rf ~/.theia`)
2. open the keyboard shortcuts view, and attempt to open the `keymaps.json` with the toolbar item (`{ }`)
3. the error is thrown

<div align='center'>

![bug](https://user-images.githubusercontent.com/40359487/89296965-26263080-d631-11ea-96f4-9c0704322835.gif)

</div>

**Comment by akosyakov** [comment]
New fs API regression? Could you check how it works before? If it is used to please assign to me.

**Comment by vince-fugnitto** [comment]
> New fs API regression? Could you check how it works before? If it is used to please assign to me.

I also noticed regressions with actually using the widget to write keymaps updates.
I'm rebuilding at the moment to confirm this regression as well.

**Comment by vince-fugnitto** [comment]
The `keymaps.json` file is created in `v1.4.0`, I believe it is a regression.

**Comment by akosyakov** [comment]
We replaced `UserStorageResoure` with `UserStorageFileSystemProvider`. There was a bug in  `UserStorageResource` that it won't throw not found exception if file does not exist and clients don't handle it well. With `UserStorageFileSystemProvider` exception is thrown properly. We have to adjust clients to respect it.
