### ISSUE TITLE
[debug] Consider removing `threads` view

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8305]
### Bug Description:

VS Code does not have it anymore, at least when having one single debug session. Tried with JS.

![Screen Shot 2020-08-04 at 17 05 29](https://user-images.githubusercontent.com/1405703/89310286-c6517900-d674-11ea-940e-cb488fa6f400.jpg)
![Screen Shot 2020-08-04 at 17 05 39](https://user-images.githubusercontent.com/1405703/89310289-c81b3c80-d674-11ea-922d-dfb5c590fbd3.jpg)

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by akosyakov** [comment]
VS Code never had it. We designed it like that on purpose at the beginning. cc @svenefftinge

**Comment by kittaakos** [comment]
> What is motivation besides VS Code does not have it?

Nothing else; it's consuming 20% of the available space.

**Comment by vince-fugnitto** [comment]
> > What is motivation besides VS Code does not have it?
> 
> Nothing else; it's consuming 20% of the available space.

Since the `threads` part serves a purpose, users are used to it and it can be hidden can the issue be closed?
