### ISSUE TITLE
Deprecated code completions crash

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8310]
### Bug Description:

When providing code completion result with deprecated: true property there is an error on code completion and no suggestions are displayed.

### Steps to Reproduce:

[lsp-sample-deprecated.zip](https://github.com/eclipse-theia/theia/files/5028388/lsp-sample-deprecated.zip) contains the vscode extension source code for reference.
[vsix.zip](https://github.com/eclipse-theia/theia/files/5028409/vsix.zip) contains two vsix files lsp-sample-deprecated-item-1.0.0.vsix that provides deprecated code completion. It works on vscode but not on theia. The other one provide code completions without deprecated items and it work on both.

1. Deploy vscode extension lsp-sample-deprecated-item-1.0.0.vsix
2. Create empty text file
3. Try to do code completion.

Nothing works and the browser console shows this error:

Uncaught Error: Cannot read property 'Deprecated' of undefined

TypeError: Cannot read property 'Deprecated' of undefined
    at asCompletionItem (c:\Users\i066470\AppData\Local\Temp\vscode-unpacked\lsp-sample-deprecated-item-1.0.0.vsix\extension\client\node_modules\vscode-languageclient\lib\protocolConverter.js:244:50)
    at Array.map (<anonymous>)
    at asCompletionResult (c:\Users\i066470\AppData\Local\Temp\vscode-unpacked\lsp-sample-deprecated-item-1.0.0.vsix\extension\client\node_modules\vscode-languageclient\lib\protocolConverter.js:171:26)
    at http://localhost:3000/vs/editor/editor.main.js:1532:31

On VS code it works like this:

![vsc](https://user-images.githubusercontent.com/9420921/89413841-2528f800-d732-11ea-92af-735b9f99a619.jpg)

### Additional Information

- Operating System: windows, debian
- Theia Version: master

**Comment by keka-star** [comment]
!
