### ISSUE TITLE
When the editor changes are not saved and exit the application, clicking the confirm button does not take effect

### ISSUE THREAD

**Issue by zhaomenghuan** [eclipse-theia/theia#8317]
### Bug Description:
When I modify the problem in the editor without saving, click the menu bar to exit the application, and the pop-up'Are you sure you want to quit?' pops up. Click the yes button to exit normally.
View devtools error message as follows:
<img width="697" alt="" src="https://user-images.githubusercontent.com/13075561/89489033-1c8cfc00-d7dc-11ea-91b7-08bcc53ac709.png">
After using the system to forcibly exit the application, check the process information, the background process did not exit normally.

### Steps to Reproduce:

1. Run the theia repository examples/electron project.
2. Modify the project file without saving, ⌘ + Q quit.

### Additional Information

- Operating System: mac OS
- Theia Version: v1.4.0

**Comment by vince-fugnitto** [comment]
@zhaomenghuan thank you for reporting the issue, it is already registered here: https://github.com/eclipse-theia/theia/issues/8186
Closing as it is a dupplicate.
