### ISSUE TITLE
vscode git built-in extension (1.47.3) does not work

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#8318]
<img width="1786" alt="Screenshot 2020-08-06 at 10 51 58" src="https://user-images.githubusercontent.com/3082655/89512030-f1ea7580-d7d2-11ea-87dd-c9b7dc147933.png">

**Comment by amiramw** [comment]
@akosyakov we are interested in adopting git pane capabilities from vscode.
Do I understand correctly that this issue is the same? 
We noticed their pane has sub menus, is this supported by theia?
Is [this](https://open-vsx.org/extension/vscode/git) the git builtin extension used in this scenario?
Does this task involve disabling existing git pane?

**Comment by amiramw** [comment]
After https://github.com/eclipse-theia/theia/pull/8523, when running with git builtin version 1.50.0 the error is different:
![image](https://user-images.githubusercontent.com/9420921/95786824-feaeac80-0ce0-11eb-9f60-b3e4d0a063cb.png)

**Comment by benoitf** [comment]
Try 1.49.3

**Comment by ashwanth1109** [comment]
@benoitf , I have a similar issue but with a different error message.

`Activating extension 'Git (built-in)' failed: Class extends value undefined is not a constructor or null`

I initially installed git `1.51.1` and faced this issue. So I tried downloading `1.49.3` and installing it, but faced the same issue

**Comment by benoitf** [comment]
we're using `"vscode-git": "https://open-vsx.org/api/vscode/git/1.49.3/file/vscode.git-1.49.3.vsix"` in che-theia and git plug-in is activating fine

**Comment by ashwanth1109** [comment]
Thanks for responding.
Hmm, I'm not sure why I was having this issue then. Anyway, I found a workaround to do my stuff without using the vscode-git api.

**Comment by tomer-epstein** [comment]
It works for us with 1.49.3.
In version 1.5x it shows error.

**Comment by vince-fugnitto** [comment]
> It works for us with 1.49.3.
> In version 1.5x it shows error.

@tomer-epstein likely fixed with the following pull-requests:
- https://github.com/eclipse-theia/theia/pull/8911
- https://github.com/eclipse-theia/theia/pull/9045

**Comment by vince-fugnitto** [comment]
Closing the issue as the git plugin (version `1.52.1` is the latest to be confirmed to work).
If there are additional issue please don't hesitate to comment on the issue.
