### ISSUE TITLE
Json schema registration overwrite

### ISSUE THREAD

**Issue by sapirpol** [eclipse-theia/theia#8324]
### Bug Description:

I'm familiar with 4 options to register JSON schemas:
1. Add "$schema" with schema's URL in the file.
2. Configure schema in settings.json.
3. Add the following to `package.json`:
```
"contributes": {
    "jsonValidation": [
      {
        "fileMatch": ".jshintrc",
        "url": "https://json.schemastore.org/jshintrc"
      }
    ]
  }
```
4. Enable using schemas coming from schema store.

I tried to overwrite schemas coming from schema store and only succeded by using the first option.
What is the right order of the options and how can I overwrite schemas coming from schema store?

**Comment by bd82** [comment]
Basically is there a specification / definition on this behavior? 

- What is the precedence order between these four registration options?
- Which of these options add additional schema registrations to a file?
- Which of these options overwrite previous schema registrations to a file?

VSCode does not support the SchemaStore yet, but I wonder how it behaves in regards to the first three options.

Relevant references:
- https://github.com/microsoft/vscode/issues/26289#issuecomment-578768254
