### ISSUE TITLE
Remove tasks start and exit with code 0 notifications

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8327]
### Feature Description:

Currently when running a task there are user notifactions for:
- Task 'X' has been started.
- Task 'X' has exited with code 0.

Can we remove those messages? VS Code doesn't have those and they seems too much information for the user.

**Comment by vince-fugnitto** [comment]
I'd be fine with the notifications removed, the notifications were present before we added the message when tasks were started and terminated directly in the terminal: https://github.com/eclipse-theia/theia/commit/ef0eba68b6f7e98d2b11d254fa1b493b8ac4a419.

**Comment by akosyakov** [comment]
I think aligning with VS code here is good.
