### ISSUE TITLE
Unclear schema error messages

### ISSUE THREAD

**Issue by sapirpol** [eclipse-theia/theia#8330]
### Bug Description:

The error messages coming from schema automatically acquired from schema store are not clear and contain the string  "_generated_diagnostic_collection_name".

![image](https://user-images.githubusercontent.com/30637290/89728768-6a9e3b80-da38-11ea-9a74-a95f366741cf.png)

### Steps to Reproduce:

1. Checkout theia v1.4.0.
2. Build and run theia - https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start
3. Create manifest.json file.

**Comment by vince-fugnitto** [comment]
I no longer see the error with recent versions of the framework.

![image](https://github.com/eclipse-theia/theia/assets/40359487/4a67070a-0b16-4eee-bc94-be5cd7691dee)
