### ISSUE TITLE
node-gyp@3.8.0 outmoded in yarn.lock and cause an error

### ISSUE THREAD

**Issue by veluxa** [eclipse-theia/theia#8332]
the node-gyp@3.8.0 is outmoded and cause an error in cmd by use yarn

https://github.com/eclipse-theia/theia/blob/e95311d16baa865e50a356dc108e1bd800952a33/yarn.lock#L9240

**Comment by akosyakov** [comment]
How one can reproduce it? For me build does not fail.

**Comment by veluxa** [comment]
I deleted the 9240 line to 9256 line in the yarn.lock file, and manually modified the dev-packages\electron\package.json node-gyp to 6.0.1, and then compiled normally.
