### ISSUE TITLE
Font settings show under "Find" section, should be under "Fonts" section

### ISSUE THREAD

**Issue by bendavis78** [eclipse-theia/theia#8341]
### Bug Description: 

In the preferences, the font preferences show under the "Editor -> Find" section. The options should appear under a section labeled "Fonts".

### Steps to Reproduce:

1. Go to file -> Settings -> Preferences
2. Search for "font"
3. See how the result for font size only shows under the "Find" section

![image](https://user-images.githubusercontent.com/324392/89811979-0eedb400-db05-11ea-9f03-a3f83b8b3bea.png)

### Additional Information

- Theia Version: 1.5.0-next.fe246304

**Comment by bendavis78** [comment]
After navigating preferences some more, it looks like this is an issue in multiple places, and is an overall UX issue. It seems that the menu builds itself from sections and subsections that are defined in the settings, but many settings do not belong to sections. 

The problem occurs when a single preference exists directly under a main category, but there are also sub-categories within that main category. The sub-categories lead the user to believe that all preferences within the main category are organized into sub-categories, but that's not the case. 

I'm not sure what the best fix is for this. Looking at the source, it's not clear to me how preferences are organized into sub-categories in the first place.

**Comment by vince-fugnitto** [comment]
Thanks to #9439 the _preferences-tree_ is now refactored to a similar behavior to that of vscode:
The `Font` preferences are correctly placed under `Text Editor`:

![image](https://user-images.githubusercontent.com/40359487/121697204-d0b18000-ca9a-11eb-8244-ed9b33fcddd4.png)
