### ISSUE TITLE
FrontendApplicationConfigProvider.get returns a configuration without the application name

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#8350]
It happens in the case if `frontend.config` section in package.json does not contain application name property. It breaks VS Code extensions like python.

We should inject the default application name if it was not set in package.json or throw an exception in FrontendApplicationConfigProvider.get

**Comment by kittaakos** [comment]
> if `frontend.config` section in package.json does not contain application name property.

How can it be not there when we use defaults? Do you have an example?

https://github.com/eclipse-theia/theia/blob/eafb64587c1ec203ca363d99bcfbab0f763763ed/dev-packages/application-package/src/application-props.ts#L83

https://github.com/eclipse-theia/theia/blob/eafb64587c1ec203ca363d99bcfbab0f763763ed/dev-packages/application-package/src/application-package.ts#L90

**Comment by akosyakov** [comment]
These defaults are never used by FrontendApplicationConfigProvider. In order reproduce:
- remove applicationName from package.json of browser example
- rebuild
- open and install python extension from open vsx
- open python file and still failure notifications
