### ISSUE TITLE
"Save As..." should open the new file

### ISSUE THREAD

**Issue by havogt** [eclipse-theia/theia#8373]
### Bug Description:
Currently "Save as..." will keep the original file open, instead of opening the new file which is very unintuitive as most (all?) programs open the new file. In particular, vscode will open the new file. 

### Steps to Reproduce:

1. Execute "Save as..."

### Additional Information

- Operating System: Linux
- Theia Version: Current Gitpod version

**Comment by leopoldwe** [comment]
Can I be assigned this issue?

**Comment by vince-fugnitto** [comment]
> Can I be assigned this issue?

Sure, please feel free to submit a pull-request.

**Comment by leopoldwe** [comment]
So when I was testing this bug, I found that using "save as" saves the changes to the original file, then copies it over to the new file. This also seems like a bug. Should I fix this also, or is this bug unrelated?

**Comment by vince-fugnitto** [comment]
> So when I was testing this bug, I found that using "save as" saves the changes to the original file, then copies it over to the new file. This also seems like a bug. Should I fix this also, or is this bug unrelated?

I confirmed it is a bug as well you're right :+1:
Please open a new issue to track the issue (if none already exists), you can then choose to fix it together or separately if you like.
