### ISSUE TITLE
[ip] jschardet dependency stepped to new major version

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#8389]
We pull a new major version of `jschardet` since recently, without having noticed. This dependency is special, since it's `LGPL` and required special Eclipse Board permission to use. The permission we got is still good, but a check by the IP team is required to make sure nothing license-related changed. I opened a CQ for this (need to be committer to see):

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22481

Hopefully the CQ can be approved before the release date. If not I think we'd need to delay the release or momentarily go back to the previously approved dependency version (`jschardet@1.6.0` IIRC).

I gave it a quick try to pin the version using a `resolutions` block entry,  but was unsuccessful - it looks like we'd need to add a TS typing for it, that's provided with the later version:
https://github.com/eclipse-theia/theia/pull/8353#issuecomment-672180395

**Comment by marechal-p** [comment]
Relevant change: https://github.com/eclipse-theia/theia/commit/8bf15dc1d9b186b11c1f954b4c51500e611d3072#diff-f4f412caa68d8fde92b3d6bd3c2b3be1R37

**Comment by vince-fugnitto** [comment]
The CQ has been approved (per previous board exception), there is no further action required :+1: 
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22481 (must be a committer to view)
