### ISSUE TITLE
[QuickPick] support multi-select

### ISSUE THREAD

**Issue by vinokurig** [eclipse-theia/theia#8393]
`Quickpick` should be able to select more than one item by selecting check-boxes:

### Feature Description:
The feature should be handled by the  `canSelectMany` argument from the plugin API:
https://github.com/eclipse-theia/theia/blob/f1380635f043103c9bb018bcc76e37c18926954a/packages/plugin-ext/src/common/plugin-api-rpc.ts#L321

**Comment by akosyakov** [comment]
duplicate of https://github.com/eclipse-theia/theia/issues/6193?

**Comment by vinokurig** [comment]
duplicates https://github.com/eclipse-theia/theia/issues/6193

**Comment by vinokurig** [comment]
Reopening, https://github.com/eclipse-theia/theia/issues/6193 is about **multi step**, but this is about **multi select**

**Comment by akosyakov** [comment]
then it is a duplicate of https://github.com/eclipse-theia/theia/issues/5673 :)?

**Comment by vinokurig** [comment]
duplicates https://github.com/eclipse-theia/theia/issues/5673
