### ISSUE TITLE
latest python extension is activated always

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#8394]
The issue is that it has a new activation event for custom editors which we don't support yet. I suggest that we list this activation event as supported. It will fixes this bug as well as prevent activating extensions which we cannot support yet.
@eclipse-theia/ecd-theia-committers what do you think?

**Comment by benoitf** [comment]
yes, it makes sense (even if we don't support yet custom editors)

**Comment by akosyakov** [comment]
@benoitf looking at unsupported activation events: https://github.com/eclipse-theia/theia/issues/4199#issuecomment-507253188 I think maybe we should stop activating eagerly at all. These events either are not used in practice a lot or as a primary or will break experience.

**Comment by tsmaeder** [comment]
@akosyakov but if we don't activate eagerly, and we don't support a particular event, how will an extension ever get activated if it only uses unsupported events?

**Comment by benoitf** [comment]
There are lot of activation events on VS Code extensions.

So for example, python extension can be activated with a lot of them that are already supported.

And if we don't support it today, probably it will fail in any case. (It was a good behavior only when we were implementing only few of them)

**Comment by akosyakov** [comment]
@tsmaeder Please have a look at list of activation events which we don't support: https://github.com/eclipse-theia/theia/issues/4199#issuecomment-507253188 In all cases, but `onSearch`, we don't support corresponding functionality as well, extension will fail anyway. For `onSearch` I found only one built-in VS Code extension `search-rg` which was removed in the meantime and this one also were using `*` activation event.

Because of it, it feels that activating eagerly on unsupported event is false positive in all cases.

**Comment by marechal-p** [comment]
@akosyakov @tsmaeder is the conclusion that if an extension's activation events are all supported then we don't activate eagerly, and if at least just one activation event is not supported then we activate early?

**Comment by akosyakov** [comment]
@marechal-p We follow activation events as [defined by VS Code]( https://code.visualstudio.com/api/references/activation-events) without any guessing whether we should activate eagerly anymore. If an extension defines `*` or `workspaceContains` activation events only when it will be activated eagerly.
