### ISSUE TITLE
[vscode] native notebook support

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#8395]
VS Code is working on new API to support notebooks natively: https://code.visualstudio.com/api/extension-guides/notebook

It is still proposed API and for now does not require actions from us. But python extension is already make an experimental use of it. So eventually we will have to implement it too.

We probably can integrate JLab notebooks since widgets APIs are very similar.

**Comment by msujew** [comment]
TypeFox is currently estimating the amount of work it would take to implement this. We might implement support for this over the course of Q1 and Q2 of next year. I'll update this comment to reflect our input in this task.

**Comment by ouliuquan** [comment]
I'm keeping an eye on this issue and it's still there

**Comment by msujew** [comment]
Our current technical spike for this feature is available at https://github.com/eclipse-theia/theia/pull/12442. Future work can build on top of it to fully support this feature.
