### ISSUE TITLE
Is Theia interested in expanding their ESLint config to include XSS sink scanning

### ISSUE THREAD

**Issue by LukeWood** [eclipse-theia/theia#8398]
### Feature Description:
I work on Cloud Shell (ide.cloud.google.com).  We use Theia to build our editor.  We have created an eslint config that has generated a list of XSS sinks in Theia (which I am currently sending fixes out for).

Are you all potentially interested in having this upstreamed?

**Comment by benoitf** [comment]
If it doesn't slow down too much linting I think it's always nice to have something more secure directly in upstream

**Comment by akosyakov** [comment]
Yes, it sounds great. I thought @caseyflynn-google was looking into it: https://github.com/eclipse-theia/theia/issues/7954#issuecomment-641545532

**Comment by LukeWood** [comment]
Ah cool - yeah I didn't realize Casey had already commented here.  I will get a commit ready.

**Comment by marcdumais-work** [comment]
There was a fix for this issue: https://github.com/eclipse-theia/theia/pull/8481, so closing.
