### ISSUE TITLE
[git] Group the context menu items per Git command

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8400]
The latest VS Code has the context menu items logically grouped by the corresponding Git command. We could do something similar.

VS Code:
![Screen Shot 2020-08-18 at 14 59 36](https://user-images.githubusercontent.com/1405703/90516052-c5841100-e163-11ea-87b6-9b6bc0296441.jpg)

Theia:
![Screen Shot 2020-08-18 at 15 00 06](https://user-images.githubusercontent.com/1405703/90516040-c157f380-e163-11ea-9726-f46eb73c2142.jpg)

**Comment by alexyiangou** [comment]
@kittaakos Hey there! I would like to try this if possible! 🙂 Can you assign this on me please?

**Comment by kittaakos** [comment]
> I would like to try this if possible!

Great!

> Can you assign this on me please?

It's yours, go ahead.

**Comment by alexyiangou** [comment]
Just a quick question.
Would you like the grouping to be like VSCode, I mean with secondary menus for each category?
Or would you like to keep your current design of seperating each category with a line?

**Comment by kittaakos** [comment]
> Would you like the grouping to be like VSCode, I mean with secondary menus for each category?

I would do the same what VS Code does; group them by the Git command.

@akosyakov, @vince-fugnitto what do you think?

**Comment by vince-fugnitto** [comment]
> > Would you like the grouping to be like VSCode, I mean with secondary menus for each category?
> 
> I would do the same what VS Code does; group them by the Git command.
> 
> @akosyakov, @vince-fugnitto what do you think?

Sorry I must have missed the ping, I assume you are talking about the `@theia/git` extension?
The plugin API has been updated to support the same behavior as vscode with the changes proposed in https://github.com/eclipse-theia/theia/pull/8996.

**Comment by vince-fugnitto** [comment]
Closed thanks to https://github.com/eclipse-theia/theia/pull/9324
