### ISSUE TITLE
Add environmentVariableCollection to PluginContext

### ISSUE THREAD

**Issue by vinokurig** [eclipse-theia/theia#8405]
Recently `environmentVariableCollection` was added to vscode plugin API by https://github.com/microsoft/vscode/commit/af3c79edcbc5b353b1ed3a69bca2ae95831ad089.

### Feature Description:
Need to align theia's `PluginContext` with [`ExtensionContext`](https://github.com/microsoft/vscode/blob/f0283ed23950bd5c729ded6964874452c593994f/src/vs/vscode.d.ts#L5527-L5604) from vscode. It is needed to use the latest vscode git extension: https://github.com/microsoft/vscode/blob/5185d7e6f8a1ca1c5e03f21d62f0a113d234a95d/extensions/git/src/terminal.ts#L20

**Comment by akosyakov** [comment]
@vinokurig Could you elaborate which extensions are using it please?

**Comment by vinokurig** [comment]
The built-in vscode Git extension uses it since 1.45.0: https://github.com/microsoft/vscode/blob/d69a79b73808559a91206d73d7717ff5f798f23c/extensions/git/src/terminal.ts#L20-L24

**Comment by amiramw** [comment]
@vinokurig are you working on this issue any time soon or we can try?

**Comment by vinokurig** [comment]
@amiramw I am working om it right now. I am going to open a PR this week

**Comment by amiramw** [comment]
@vinokurig That's great. Do you know if this the only gap in order to support builtin git?

**Comment by vinokurig** [comment]
It is already possible to use the vscode git version 1.44.2. This is needed to use later versions.
