### ISSUE TITLE
[shell][ui/ux] Undesired tabbar flickering when opening editors in main area

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8410]
### Bug Description:

The tabbar flickers every time I open an editor in the main area. Maybe other use-cases/areas are affected too. See the attached screencast, for a second, the entire tabbar disappears then comes back when I open an editor:

![screencast 2020-08-21 09-08-51](https://user-images.githubusercontent.com/1405703/90863569-8e924300-e38f-11ea-9e15-5ef7b6666faa.gif)

### Steps to Reproduce:

1. Close all editor.
2. Open an editor.
3. Open another editor, you see the flickering.

### Additional Information

- Operating System:
- Theia Version:

**Comment by tsmaeder** [comment]
@kittaakos I don't see this problem anymore. Can you confirm and close this one?

**Comment by kittaakos** [comment]
Thanks for the ping. It works great. I verified it with the blueprint application (`Version 1.44.0 (1.44.0.130)`).
