### ISSUE TITLE
[menu] Broken menu widget layout

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8416]
### Bug Description:

![screencast 2020-08-23 17-48-54](https://user-images.githubusercontent.com/1405703/90982711-33b44380-e569-11ea-9686-3ee422541d4c.gif)

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by akosyakov** [comment]
Is it on master?

**Comment by kittaakos** [comment]
Yes.
