### ISSUE TITLE
Icon truncated  on Activity Bar

### ISSUE THREAD

**Issue by daimor** [eclipse-theia/theia#8425]
### Bug Description:
I'm an author of [VSCode-ObjectScript](https://open-vsx.org/extension/daimor/vscode-objectscript) extension.
We have an item on the Activity bar
How it looks in VSCode
![image](https://user-images.githubusercontent.com/1212251/91098275-de139000-e669-11ea-9fe3-99145c08c223.png)

And how this icon looks like in Theia
![image](https://user-images.githubusercontent.com/1212251/91098905-fdf78380-e66a-11ea-9a25-41fc10a41858.png)
It's truncated, while VSCode does not truncate the icon, just place it in the middle.
If I would change the size, it will not look so good.
![image](https://user-images.githubusercontent.com/1212251/91099001-2c755e80-e66b-11ea-836c-5e4929ab31f9.png)

### Steps to Reproduce:

1. Install extension daimor.vscode-objectscript, keywords: intersystems, objectscript

### Additional Information

- Operating System:
- Theia Version:
from the current master branch

**Comment by brianking** [comment]
I'm just curious, but why do you make the icon bigger than standard icons?

**Comment by daimor** [comment]
It's a real logo of [InterSystems](https://www.intersystems.com/) company, the vendor of IRIS Data Platform, which my extension for. So, don't have so many options for what to use.

**Comment by vince-fugnitto** [comment]
Closed thanks to #8426 and #8505.
