### ISSUE TITLE
Causing TypeError: issue in webpack  

### ISSUE THREAD

**Issue by abhishekvermax** [eclipse-theia/theia#8432]
https://github.com/eclipse-theia/theia/blob/4390a7d6497a46bc5e5d73911cd563c20cd1a5a2/packages/core/src/browser/frontend-application-module.ts#L18

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Uncaught TypeError: __webpack_require__(...).use is not a function
    at eval (frontend-application-module.js:40)
    at Object../node_modules/@theia/core/lib/browser/frontend-application-module.js (main.js:1359)
    at __webpack_require__ (main.js:20)
    at eval (app.ts:7)
    at Object../src/app.ts (main.js:9631)
    at __webpack_require__ (main.js:20)
    at eval (index.ts:22)
    at Object../src/index.ts (main.js:9654)
    at __webpack_require__ (main.js:20)
    at eval (webpack:///multi_(:8080/webpack)-dev-server/client?:2:18)

**Comment by vince-fugnitto** [comment]
@abhishekvermax thank you for the issue, when reporting bugs please follow the template so the community can better help, identify problems more easily. Do you have reproduction steps which causes the error?

**Comment by abhishekvermax** [comment]
@vince-fugnitto Thans for reply... You could see the steps in readme.md of below git repo

https://github.com/abhishekvermax/theia-embedded-webpack-app

**Comment by kittaakos** [comment]
> below git repo

Please update your repo that it does not have compiled code and the node_modules. Then I can look into your issue.

**Comment by parliament718** [comment]
> > below git repo
> 
> Please update your repo that it does not have compiled code and the node_modules. Then I can look into your issue.

I've removed the extraneous bits. Though this issue is old I'm having the same issue in my Angular app and would love to know what's causing it in the demo below. Thank you

https://github.com/parliament718/theia-embedded-webpack-app
