### ISSUE TITLE
Get default value from workspaceState/globalState

### ISSUE THREAD

**Issue by daimor** [eclipse-theia/theia#8435]
I found a case where such errors happen.

Clear any previous value, how it supposed to work in VSCode.
```
globalState.update('someKey', undefined); 
```
After that, any `get` should return `defaultValue`, as there are no values supposed to be stored anymore.
```
globalState.get('someKey', 'defaultValue');
```
But, it logs an error and returns `undefined` instead.

Test code
```
			// Just clear start, completely nothing in globalState, yet
			val = globalState.get('test', "default") || "WTF";

			globalState.update('test1', undefined);
			val1 = globalState.get('test1', "default") || "WTF";

			globalState.update('test2', "somevalue");
			val2 = globalState.get('test2', "default") || "WTF";	
```
Expected values, 
```
val="default"
val1="default"
val2="somevalue"
```
but it gets
```
val1="WTF"
```

_Originally posted by @daimor in https://github.com/eclipse-theia/theia/issues/8384#issuecomment-675503743_

**Comment by vince-fugnitto** [comment]
Fixed thanks to https://github.com/eclipse-theia/theia/pull/8424.
