### ISSUE TITLE
Cannot build theia after 1.5.0 release: Module not found: Error: Can't resolve 'vscode' 

### ISSUE THREAD

**Issue by bendavis78** [eclipse-theia/theia#8440]
### Bug Description
I'm attempting to build the [theia-docker](https://github.com/theia-ide/theia-apps/tree/master/theia-docker) image, and the `theia build` command fails with following error:
```
ERROR in ./node_modules/vscode-languageclient/lib/client.js
Module not found: Error: Can't resolve 'vscode' in '/home/theia/node_modules/vscode-languageclient/lib'
 @ ./node_modules/vscode-languageclient/lib/client.js 10:17-34
 @ ./node_modules/monaco-languageclient/lib/monaco-language-client.js
 @ ./node_modules/monaco-languageclient/lib/index.js
 @ ./node_modules/@theia/languages/lib/browser/language-client-services.js
 @ ./node_modules/@theia/languages/lib/browser/languages-frontend-module.js
 @ ./src-gen/frontend/index.js    
```

### Steps to Reproduce:
Build the `theia-docker` image found here: https://github.com/theia-ide/theia-apps/tree/master/theia-docker

    $ git clone git@github.com/theia-ide/theia-apps
    $ cd theia-apps/theia-docker
    $ docker build .

This can also be reproduced outside of docker by just using the package.json found [here](https://github.com/theia-ide/theia-apps/blob/master/theia-docker/latest.package.json).

### Possible cause
This seems to have been caused by the recent [removal of this line](https://github.com/eclipse-theia/theia/commit/1e09b816511769eb206494c1bac1a595e95795f9#diff-e4ddacc08834b7870ddb2e67f6d73e8eL203) from the webpack config generator:

![image](https://user-images.githubusercontent.com/324392/91614842-ea3c6d80-e947-11ea-826d-7b89f4ef250d.png)

**Comment by vince-fugnitto** [comment]
@bendavis78 I attempted a fresh build from `theia-apps` and it was successful. 
As well, the CI (cron job) was also successful for all `latest` images following the release:
- https://travis-ci.org/github/theia-ide/theia-apps/builds/721908840

**Comment by bendavis78** [comment]
Ah, you're right, this seems to have been a cache issue. I was able to build with `--no-cache`.
