### ISSUE TITLE
Debugging Go application remotely not working when breakpoint is hit

### ISSUE THREAD

**Issue by quoctruong** [eclipse-theia/theia#8455]
### Bug Description:
When debugging a Go application remotely, after the breakpoint is hit, I have no way to advance the breakpoint (see screenshot):
<img width="1678" alt="Screen Shot 2020-09-01 at 2 38 53 PM" src="https://user-images.githubusercontent.com/4371645/91908812-fa628e80-ec60-11ea-9847-08f3257c6dbe.png">

### Steps to Reproduce:

1. Setup remote debugging for a Go program ((link)[https://github.com/golang/vscode-go/blob/master/docs/debugging.md#remote-debugging])
2. Set a breakpoint
3. Run the program until the breakpoint is hit.

### Additional Information

- Operating System:
- Theia Version:

**Comment by quoctruong** [comment]
Also I just notice that you can right clicked on the call stack to Continue (see image). Is this a bug in Theia?


![image](https://user-images.githubusercontent.com/4371645/92142251-66133b80-edc8-11ea-9dad-f0340c24f864.png)

**Comment by vince-fugnitto** [comment]
@quoctruong does the issue still exist, or was it an issue with the `vscode-go` extension?
- https://go-review.googlesource.com/c/vscode-go/+/254959
