### ISSUE TITLE
calling extension activate() by other extension doesn't work.

### ISSUE THREAD

**Issue by tomer-epstein** [eclipse-theia/theia#8463]
Description
calling extension.activate() method from another extension doesn't activate the extension.

Reproduction Steps
tested with those vscode extensions - https://github.com/tomer-epstein/vscode-extension-activate.git

1. Pack (create vsix) for https://github.com/tomer-epstein/vscode-extension-activate/tree/master/vscode-manager
2. Pack (create vsix) for https://github.com/tomer-epstein/vscode-extension-activate/tree/master/vscode-contrib1
3. execute 'extension.activateContributor' command.

**Comment by tomer-epstein** [comment]
Failed at --> https://github.com/tomer-epstein/vscode-extension-activate/blob/master/vscode-manager/src/extension.ts#L14

**Comment by akosyakov** [comment]
Hi, could you provide what do you mean by does not work and fail? Are there any logs on backend or in browser?

**Comment by tomer-epstein** [comment]
logs shows no errors. the vscode-contribtor activate func is not being caled.

**Comment by vince-fugnitto** [comment]
Fixed by: https://github.com/eclipse-theia/theia/pull/8542.
