### ISSUE TITLE
[scm] root WARN Widget was activated, but did not accept focus after 2000ms: scm-view

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8471]
### Bug Description:

This happens when there is no repository in the workspace.
![Screen Shot 2020-09-04 at 11 51 46](https://user-images.githubusercontent.com/1405703/92226429-05a5fc00-eea5-11ea-96cf-670bdedc7b91.jpg)

**Comment by akosyakov** [comment]
We should focus the widget node in such case.
