### ISSUE TITLE
@inject(FileSystem) will inject the type instead of the actual object

### ISSUE THREAD

**Issue by slhultgren** [eclipse-theia/theia#8497]
I know that the FileSystem is deprecated, however it is currently broken since the bad thing is injected.

https://github.com/eclipse-theia/theia/blob/master/packages/filesystem/src/browser/filesystem-frontend-module.ts#L85

Shouldn't this return a new instance instead of just a class?

When running this code:
@inject(FileSystem) private fileSystem: FileSystem;
...
console.log("fs.exists: " + this.fileSystem.exists);

You will get "fs.exists: undefined"

However, (this.fileSystem as any).prototype.exists does exist.

**Comment by vince-fugnitto** [comment]
cc @akosyakov

**Comment by akosyakov** [comment]
Good catch! Please send a PR.
