### ISSUE TITLE
Backspace key doesn't delete text, on Android

### ISSUE THREAD

**Issue by Pictor13** [eclipse-theia/theia#8501]
### Bug Description:

With theia loaded in Gitpod as a browser tab, on Android, the `backspace` key doesn't work with virtual keyboards.

The bug doesn't occur if I use a physical keyboard connected to the micro-USB of the mobile device.

### Steps to Reproduce:

1. Open a workspace gitpod.io 
2. Type something in the editor text/code area, using a virtual keyboard (app).
3. Press backspace to delete one character, and see how nothing happens (or how it takes tens of taps to delete a single character).

### Additional Information

- Operating System: Android with virtual keyboards
- Theia Version: n/a (version currently used by gitpod.io)
- Browser: Opera Touch or Chrome (on Moro G5) and Silk Browser (on Amazon Fire HD)

On an Amazon Fire HD 10, tapping backspace in the code doesn't delete any character.
On a Moto G5, tapping backspace in the code deletes one character every 10 to 30 taps (is weird and always different; might be related to the number of columns in the current line, or related to the keyboard predictions, that I see getting deleted while the same word in the editor is not changing).

**Comment by vince-fugnitto** [comment]
@Pictor13 thank you for the issue, it may be related to https://github.com/microsoft/monaco-editor/issues/48 (we use the monaco editor). It would be good to confirm the bug outside the framework using the monaco editor playground example: https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-multi-line-example

**Comment by Pictor13** [comment]
It's a fallback of dependencies... 😓  (GitPod -> Theia -> Monaco? Not sure if there's VSCode in the middle of it too 😶)
Thanks for the information, though.

I tried in the linked playground, with Chrome on Android 7 and, yes, the behaviour is buggy even on the *monaco-editor*.

Looks that monaco not supporting mobile development is a blocker for every other project that derives from it.
That is weird to me, since I think that the whole online coding revolution makes even more sense on mobile devices and am not sure why the support for it was skipped 🙁  (since 2017 there are no improvements; maybe technical limitations of the mobile devices? Even if with an external keyboard it works perfectly 🤔).

**Comment by vince-fugnitto** [comment]
@Pictor13 I found some additional issues related to `android` and the `monaco-editor`:
- https://github.com/microsoft/monaco-editor/issues/563
- https://github.com/microsoft/monaco-editor/issues/1365
- https://github.com/microsoft/monaco-editor/issues/1538

> Thanks for the information, though.

Sure, I just wanted to confirm if it was in fact a bug in the framework or the `monaco editor` itself not properly supporting android devices.

**Comment by Pictor13** [comment]
Yes, I also found them looking around; thank you.

I close the ticket for now since is not properly a Theia problem but some behaviour from the dependency.
