### ISSUE TITLE
Regression when opening an .MD file in editor: I can see two tabs for one editor

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8511]
See the screencast:

![screencast 2020-09-16 16-49-47](https://user-images.githubusercontent.com/1405703/93354309-24a97400-f83d-11ea-895f-76241cc4e6ef.gif)

- Theia Version: 993b7a8bc

**Comment by kittaakos** [comment]
It must be related to the editor preview, the extra tab has this CSS class: `p-TabBar-tab  theia-editor-preview-title-unpinned p-mod-closable`

**Comment by vince-fugnitto** [comment]
I also noticed the bug, it is one of the reasons I turned the `editor-preview` off.

**Comment by kena0ki** [comment]
The issue happens not only with .MD files. In browser example through Gitpod, with any file opened by double click the issue always happens.
