### ISSUE TITLE
vscode API completeness: startDebugging to respect DebugSessionOptions param

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8518]
### Bug Description:

vscode API `startDebugging` has optional parameter of type `DebugSessionOptions` which currently theia ignore:

https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L11512

It has several options like no debug, console mode, etc.

### Steps to Reproduce:

Call `startDebugging` from an extension and make sure all options in `DebugSessionOptions` are treated. Example for such options: https://github.com/microsoft/vscode-js-debug/blob/088e5a28b2f97205fc5fca1f19b4cd7657685d7d/src/ui/vsCodeSessionManager.ts#L38-L43

### Additional Information

- Operating System: all
- Theia Version: master

**Comment by msujew** [comment]
Hi, just wanted so say that I will take care of this issue starting in july.
