### ISSUE TITLE
Add "tasks" to .theia-workspace file

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#8519]
### Feature Description:
Currently, a `.theia-workspace` configuration file can store preference settings scoped to that particular workspace, but does not have the ability to store workspace scoped "tasks" as [VSCode does](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-task-configuration). 
Are there plans to add support for workspace-scoped tasks?

**Comment by vince-fugnitto** [comment]
> Are there plans to add support for workspace-scoped tasks?

I believe we should support `tasks` in the workspace configuration file (multi-root).
At the moment, the only way to share tasks between folders (in a multi-root workspace) is to use `user scoped tasks`.
