### ISSUE TITLE
Mount directories over browser with my desktop

### ISSUE THREAD

**Issue by posix4e** [eclipse-theia/theia#8526]
For things like passwords, for instance, ~/.kube wouldn't it be nice if it was stored on my desktop and just tunneled as needed back to my desktop rather than storing it on the backend?

**Comment by vince-fugnitto** [comment]
@posix4e thank you for the discussion, in the future please respect the issue templates, and if you have questions direct them to https://github.com/eclipse-theia/theia/discussions. Please provide additional details in the issue, it is difficult to understand what you are referring to.

**Comment by posix4e** [comment]
Great will do!
