### ISSUE TITLE
Theia Electron app extracts plugins multiple times

### ISSUE THREAD

**Issue by fgreinacher** [eclipse-theia/theia#8527]
### Bug Description

It seems like a Theia Electron app extracts plugins multiple times. This causes problems when starting a second Theia instance that is alreading using files from the extracted plugins directory (in our case a language server executable).

### Steps to Reproduce:

1. Build an Electron app based on Theia with some non-extracted plugins (`.vsix` files) added to it (via env var or `--plugins` param)
2. Start one instance of this app and obsever that plugins are extracted to a temp dir (on Windows `%temp%\vscode-unpacked`). 3. Start another instance of the same and observe that plugings are extracted again to the same dir. This might either succeed or fail badly, depending on the set of plugins and the timing on your machine.

### Additional Information

- Operating System: Windows
- Theia Version: 1.4

The specific problem we are seeing:

```
root INFO [abc-0.10.1.vsix]: decompressed
root INFO [def-0.1.339.vsix]: decompressed
root INFO [nsfw-watcher: 23540] Started watching: c:\workspace
root INFO [ghi-0.1.0.vsix]: decompressed
root INFO [jkl.vsix]: decompressed
root ERROR Failed to resolve plugins from 'local-dir:C:\Users\me\AppData\Local\Programs\app\resources/plugins' Error: EBUSY: resource busy or locked, open 'c:\Users\me\AppData\Local\Temp\vscode-unpacked\mno-0.9.59.vsix\path\to\some.dll'
```

This seems to be caused by the logic starting at https://github.com/eclipse-theia/theia/blob/252cae73ae2d2b47c32c9b2774cfbace0d455293/packages/plugin-ext-vscode/src/node/plugin-vscode-file-handler.ts#L46

I'm not sure why "system plugins" are extracted again in this case. This line was introduced in https://github.com/eclipse-theia/theia/commit/c3e162cd816d5448177c703559fba04bc79c8386 by @akosyakov.

**Comment by akosyakov** [comment]
User plugins are persisted between server restarts. System plugins are installed each time (as it was before always). You can extract system plugins before starting the server, otherwise Theia extract them in the temporary location.

**Comment by fgreinacher** [comment]
> User plugins are persisted between server restarts. System plugins are installed each time (as it was before always). 

Thanks! I assume user plugins need to installed through plugin manager? Or is there a way to predefine them?

> You can extract system plugins before starting the server, otherwise Theia extract them in the temporary location.

Got it. Still I'm wondering why Theia extracts them to the temporary location _multiple times_. I'd assume that plugins are extracted to temp once and then reused from temp for subsequent runs.
