### ISSUE TITLE
Support `isWeb` Operating System context for theia

### ISSUE THREAD

**Issue by mohitsuman** [eclipse-theia/theia#8529]
### Feature Description:
Currently theia supports OS context for `isWin/Mac/Linux` . VSCode [context AP](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts)I has added `isWeb` context too which should be supported in Theia API.

**Comment by mohitsuman** [comment]
cc :  @azatsarynnyy @ericwill

**Comment by azatsarynnyy** [comment]
Thanks for the feature request @mohitsuman!

BTW, it should be as easy as just adding
```typescript
this.contextKeyService.createKey<boolean>('isWeb', !this.isElectron());
```
to https://github.com/eclipse-theia/theia/blob/4739e26c36a87ee31ffba20e738eddafc86bd8ee/packages/core/src/browser/common-frontend-contribution.ts#L342-L344

**Comment by azatsarynnyy** [comment]
Another solution can be `env.UIKind` API.
It returns `UIKind.Desktop` or `UIKind.Web`
