### ISSUE TITLE
Press compare changes codelens in a conflict file causes errors

### ISSUE THREAD

**Issue by datou0412** [eclipse-theia/theia#8535]
### Bug Description:
Press `Compare Changes` codelens in a conflict file will cause an `Unable to show comparison` error.

![Sep-21-2020 17-11-30](https://user-images.githubusercontent.com/5847142/93750249-c3fbac00-fc2d-11ea-9c03-cb70c5e875d6.gif)

### Steps to Reproduce:

1. Browser Example
2. Install the `vscode builtin merge-conflict extension`.
3. Open a conflict file and press the `Compare Changes` codelens

### Additional Information

- Operating System: MacOs 10.15.6
- Theia Version: 1.5.0

**Comment by vince-fugnitto** [comment]
The issue has been resolved :+1:
