### ISSUE TITLE
Use vim in terminal and reload will output weird 2R in the terminal

### ISSUE THREAD

**Issue by datou0412** [eclipse-theia/theia#8538]
### Bug Description:
Use vim in the terminal will output weird `2R` in term after reload browser.
How many `2R` depends on how many times you open vim.
1->2R, 2->2R2R, 3->2R2R2R ...
![Sep-21-2020 20-10-38](https://user-images.githubusercontent.com/5847142/93764903-9111e200-fc46-11ea-9d7e-2311713ef910.gif)

### Steps to Reproduce:

1. Browser Example
2. Open a terminal
3. type `vim xxx` and quit vim use `:q`
4. do it again
5. reload the browser

### Additional Information

- Operating System: MacOs 15.5.6
- Theia Version: 1.5.0
- Vim Version: 8.0/8.1

**Comment by DukeNgn** [comment]
Hi @datou0412 
A workaround for this issue would be adding `set t_u7=` to the top of your `vimrc` in the mean time. It works for me.
This bug might have something to do with xterm.

**Comment by datou0412** [comment]
> Hi @datou0412
> A workaround for this issue would be adding `set t_u7=` to the top of your `vimrc` in the mean time. It works for me.
> This bug might have something to do with xterm.

Thanks，it works well for me
