### ISSUE TITLE
"workspaceContains" activation event does not work

### ISSUE THREAD

**Issue by fgreinacher** [eclipse-theia/theia#8550]
WIP

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by vince-fugnitto** [comment]
@fgreinacher thank you for reporting the issue! However, please provide additional information so the project can help further including a description of the bug, steps to reproduce it and additional information (namely the `theia` version tested with).

Please re-open the issue when additional information is added.

**Comment by fgreinacher** [comment]
Sorry, I actually wanted to close this one for adding more information. I just needed an issue link for our internal tracking. Will add more details and reopen!
