### ISSUE TITLE
No indication for deprecated variables

### ISSUE THREAD

**Issue by EstherPerelman** [eclipse-theia/theia#8552]
When providing code completion result with deprecated: true property there is no indication in the UI - deprecated value should appear with strike-through.
### Bug Description:

[lsp-sample plugin.zip](https://github.com/eclipse-theia/theia/files/5269510/lsp-sample.plugin.zip) contains the vsix file lsp-sample-1.0.0.vsix
### Steps to Reproduce:

1. Deploy vscode extension lsp-sample-1.0.0.vsix
2. Create empty text file
3. Try to do code completion.

There's no indication for the deprecated one:
![no-indication](https://user-images.githubusercontent.com/71729183/94040604-d4e52280-fdd1-11ea-8fb2-d1ebdca644bb.png)

While on VSCode it appears with strikethrough:
![indication](https://user-images.githubusercontent.com/71729183/94040653-e0384e00-fdd1-11ea-9d54-3ea7a63bad70.png)

### Additional Information

- Operating System: Windows
- Theia Version: Master

**Comment by vince-fugnitto** [comment]
Related VS Code [changes](https://github.com/microsoft/vscode/pull/78092/files).
