### ISSUE TITLE
Support deprecated strikethrough directly in the editor

### ISSUE THREAD

**Issue by DukeNgn** [eclipse-theia/theia#8557]
### Feature Description:
Would be nice if Theia highlights deprecated calls with strikethrough in the editor

+ Similar to VSCode:
![strikethrough](https://user-images.githubusercontent.com/43587865/94155516-064f0400-fe4d-11ea-86cd-5edf4490d778.png)

**Comment by vince-fugnitto** [comment]
I believe it will require an update to **monaco v0.21.0** in order to make use of the `showDeprecated` flag:

https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#showdeprecated

**Comment by vince-fugnitto** [comment]
The following should now be possible with the latest monaco upgrade.
The preference `editor.showDeprecated` is not yet supported at the moment (it does not display deprecations in the editor as is).

https://github.com/eclipse-theia/theia/blob/f5d042f00eaf973d4c3156d161ab1252b616b257/packages/editor/src/browser/editor-preferences.ts#L1078-L1082
