### ISSUE TITLE
Some files are unexpectedly created when Theia (browser version, run on Linux) is accessed by a Windows machine if a slow frontend contribution is present

### ISSUE THREAD

**Issue by federicobozzini** [eclipse-theia/theia#8562]
### Bug Description:
When Theia (browser version) is run on Linux, if there is a frontend contribution with a long starting time and Theia is accessed by a Windows machine some files (`.theia/tasks.json`, `.theia/launch.json`, `.theia/settings.json`, `.vscode/tasks.json`, `.vscode/launch.json`, `.vscode/settings.json`) might be created.

### Steps to Reproduce:

1. Add a frontend application contribution to Theia with a long starting time. Ideally a `FrontendApplicationContribution` with a configure method taking a few (>3) seconds to be completed.
2. Start Theia (browser version) on a Linux machine.
3. Access Theia from a Windows machine.
4. The files mentioned above are created.

### Additional Information

- Operating System: Observed on Ubuntu 18, but any Linux version should work.
- Theia Version: Tested with Theia 1.2.0 and 1.5.0

**Comment by vince-fugnitto** [comment]
I think it's best to try and debug why the bug is happening for this particular use-case.
I think it's difficult for anyone in the community to properly reproduce the issue and it looks like you have the proper setup already to do so.

**Comment by federicobozzini** [comment]
It's actually pretty simple to reproduce.

Even just delaying [the step where the `configure` method is called for all frontend contributions](https://github.com/eclipse-theia/theia/blob/master/packages/core/src/browser/frontend-application.ts#L316) is enough to see it.

The simplest way would be to just use something like 

```
        const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
        await wait (4000);
``` 

before that step.

In any case if I can help you to reproduce it, I'd be happy to do it.

**Comment by vince-fugnitto** [comment]
> It's actually pretty simple to reproduce.

The part I was referring to was more steps 2-3 (which is not possible for everyone in the community to reproduce):
> Start Theia (browser version) on a Linux machine.
> Access Theia from a Windows machine.

**Comment by federicobozzini** [comment]
I see. Using docker on a Windows machine would work too.
