### ISSUE TITLE
[vscode][showTextDocument] different behavior from vscode when showing sbs editors

### ISSUE THREAD

**Issue by veredcon** [eclipse-theia/theia#8574]
### Bug Description: 
When programmatically opening a text editor on a newly created file, the editor opens  but an error message appears afterwards.
This only happens if the new editors opens side-by-side (second ViewColumn). 
If I use the same column and replace the old editor - no error message appears.

File plugin-context, line 302
const textEditor = editors.getVisibleTextEditors().find(editor => editor.document.uri.toString() === uri.toString());
The call editors.getVisibleTextEditors() only returns one editor (the original one) not the other if they are in different ViewColoums

### Steps to Reproduce:

1. Take the example vsix -->
[vscode-ext-sample-0.0.5.vsix.zip](https://github.com/eclipse-theia/theia/files/5305552/vscode-ext-sample-0.0.5.vsix.zip)
or build it from the following source code:
* git clone https://github.com/veredcon/vscodetests.git -b **fixpreview**
* npm i && npm run compile && npm run build

2. Make sure editors are being opened in new tabs (settings property "editor.enablePreview": false)
3. Use this extension in theia 1.5.0, 1.6.0 or master
4. Right Click on some json file --> "Show Text Editor"

You will see in the extension ourput channel the errors. visibleTextEditors is not being updated to include the newly opened file and this no textEditor is found and an error is thrown.

### Additional Information
editors.getVisibleTextEditors() returns only one (the original) visible editor although there should already be 2:
![image](https://user-images.githubusercontent.com/9718939/94687839-75d55f80-0335-11eb-910f-17a6c2d4bda9.png)

![image](https://user-images.githubusercontent.com/9718939/94687933-96051e80-0335-11eb-93f7-bd3fd4c60e9a.png)

When running this extension with this code snippet in VSCode I do get 2 active visible editors.

- Operating System: linux
- Theia Version: 1.6.0, 1.5.0 (also checked on master and it reproduces)

**Comment by veredcon** [comment]
Please review this PR: https://github.com/eclipse-theia/theia/pull/8588 
I have checked it with the given simple extension vsix that uses this API.

**Comment by amiramw** [comment]
@veredcon does your vscode extension repo need to be with https://github.com/veredcon/vscodetests/pull/2 ?

**Comment by veredcon** [comment]
yes - the relevant code is in **fixpreview** branch only.
Of course can simply just take the attached vsix (vscode-ext-sample-0.0.5.vsix.zip) instead.

**Comment by vince-fugnitto** [comment]
Fixed by: https://github.com/eclipse-theia/theia/pull/8588.
