### ISSUE TITLE
scm: tree-search should highlight matched nodes

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#8581]
### Bug Description:

The `tree-search` for `scm` should properly highlight matched nodes like in other areas (ex: `explorer`).
At the moment, nodes are not highlighted which is both confusing and inconsistent with the rest of the framework.

<div align='center'>

<img src='https://user-images.githubusercontent.com/40359487/94928636-fc9f4f00-0491-11eb-9140-b297da3fd7c0.png'  width='800px'/>

<img src='https://user-images.githubusercontent.com/40359487/94928691-150f6980-0492-11eb-85ec-10e373365ecd.png'  width='800px'/>

</div>

### Steps to Reproduce:

1. start the application, perform changes and open the `scm` view
2. type to start the `tree-search` 
3. notice how no highlights are present

**Comment by colin-grant-work** [comment]
The problem here seems to be that `TreeSearch` relies on this to get the string to filter on:
```
(node: TreeNode) => this.labelProvider.getName(node);
```

But the SCM tree itself extracts the URI from a node before it asks the label provider for the name:

```
const name = this.labelProvider.getName(new URI(node.sourceUri));
```

I'll look into reconciling the behavior.
