### ISSUE TITLE
Show files ignored by git in a different color 

### ISSUE THREAD

**Issue by Leon0402** [eclipse-theia/theia#8602]
Could ignored files/folders get a different color in the file editor as seen in the screenshot?

![image](https://user-images.githubusercontent.com/33933142/95351354-6e77fe00-08c1-11eb-9011-2d023e01eefb.png)

The .vscode is in the gitignore file and therefore is written in a darker white

**Comment by vince-fugnitto** [comment]
@Leon0402 thank you for the issue, it's already being tracked as part of https://github.com/eclipse-theia/theia/issues/1564.
