### ISSUE TITLE
Rename Debug main menu according to VS Code

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-theia/theia#8603]
### Feature Description:
In VS Code, `Debug` menu has been renamed to `Run`
![image](https://user-images.githubusercontent.com/1636395/95353509-024ec780-08cc-11eb-8928-30d445be629e.png)

In Theia, we still have `Debug`
![image](https://user-images.githubusercontent.com/1636395/95353551-109ce380-08cc-11eb-84a2-d70e45c1a05b.png)

It should be renamed according to VS Code.

**Comment by dhairyanadapara** [comment]
Hey @vince-fugnitto, I would love to help. From the description what I understood is the change is to update the menu name from `Debug` to `Go`.

**Comment by azatsarynnyy** [comment]
Hello @dhairyanadapara!
`Debug` menu has to be renamed to `Run`.

**Comment by dhairyanadapara** [comment]
@azatsarynnyy My bad :|. I got wrong mapping in both menu while writing the comment. Thanks  for correction. I will raise the PR once the changes are done. thanks :)

**Comment by dhairyanadapara** [comment]
https://github.com/eclipse-theia/theia/blob/e33708b77117a044f5f0a3fa97309c8b9fe3664f/packages/debug/src/browser/debug-frontend-application-contribution.ts#L494

@azatsarynnyy I found the change requied for updating the menu name. I changed the name to `Run` and ran `npm run start` but the change is not showing in the browser. Can you please help me with the problem?

**Comment by azatsarynnyy** [comment]
@dhairyanadapara have you rebuilt Theia with your changes with `yarn` command?
See https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start

**Comment by azatsarynnyy** [comment]
Hello @dhairyanadapara,
how thing are going with renaming the menu? Can you the results after rebuilding it with `yarn` command?
Do you need any help?

**Comment by dhairyanadapara** [comment]
Hey @azatsarynnyy, sorry for the delay. I tried with the `yarn` command but still the change is not shown. I'm using `wsl(ubuntu)` for development because in windows I'm getting some issue while running `yarn` for installing dependencies.  Do you think this issue is coming due to `wsl`?

**Comment by dhairyanadapara** [comment]
Can you please confirm that the change I suggested is correct?

Also, one other issue I found is that if there are any other server running on same port(3000) then the theia overrides the other server. It would be better to run the server on other port like(3001) if some service is already running on 3000

**Comment by azatsarynnyy** [comment]
> Hey @azatsarynnyy, sorry for the delay. I tried with the `yarn` command but still the change is not shown. I'm using `wsl(ubuntu)` for development because in windows I'm getting some issue while running `yarn` for installing dependencies. Do you think this issue is coming due to `wsl`?

I think it might be related to a browser's cache. Try to reload the page in incognito mode. Or clean-up the cache. If you're using Chrome, try Shift+F5.

**Comment by azatsarynnyy** [comment]
> Can you please confirm that the change I suggested is correct?
> 
> Also, one other issue I found is that if there are any other server running on same port(3000) then the theia overrides the other server. It would be better to run the server on other port like(3001) if some service is already running on 3000. (this issue might be coming due to `wsl`)

@dhairyanadapara 3000 is a default port. It can be specified through the command line arg, e.g. `yarn start -p 3001`

**Comment by azatsarynnyy** [comment]
@dhairyanadapara please, let me know if you still have your changes not visible in Theia.
I will provide a PR then.

**Comment by dhairyanadapara** [comment]
@azatsarynnyy I just tried followed the instructions you gave, but still no success. You can raise the PR. Thanks :)

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy I just followed the instructions you gave, but still no success. You can raise the PR. Thanks :)

No problem. BTW, you can pick another good first issue from https://github.com/eclipse-theia/theia/labels/good%20first%20issue :wink:
