### ISSUE TITLE
Monaco hover content is squashed, needs more margin

### ISSUE THREAD

**Issue by mcgordonite** [eclipse-theia/theia#8613]
I have added the [vscode-clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) plugin to the latest commit from master (https://github.com/eclipse-theia/theia/commit/fd7d9d2ff0a8c2909b7459865c06a0f447e1734f).

The content in the popover shown when mousing over a symbol in the source is squashed. Note the text overlapping the `<hr>`:
![theia-hover](https://user-images.githubusercontent.com/12599255/95589964-61801980-0a3d-11eb-8b63-0b1f8e0001d1.png)

Compare with VS Code:
![vscode-hover](https://user-images.githubusercontent.com/12599255/95590002-6f359f00-0a3d-11eb-8623-fbdd0a6a48f5.png)

I have narrowed the problem down to this style rule from monaco's [standalone-tokens.css file](https://github.com/theia-ide/vscode/blob/master/src/vs/editor/standalone/browser/standalone-tokens.css#L21-L23):
```css
.monaco-editor-hover p {
	margin: 0;
}
```

This rule overrides the correct margins from here: https://github.com/theia-ide/vscode/blob/master/src/vs/editor/contrib/hover/hover.css#L36-L39. It does not seem to be applied in VS Code.

However, I'm not sure how the [@theia/monaco-editor-core](https://www.npmjs.com/package/@theia/monaco-editor-core) package is built, so I'm not sure how to proceed.

- Will an eventual monaco upgrade fix this problem?
- Or is there something different about how monaco is packaged for Theia vs VS Code that means different style rules are applied?

Any help or pointers to information on packaging of @theia/monaco-editor-core would be greatly appreciated, thanks! :)

**Comment by vince-fugnitto** [comment]
I believe the issue has been resolved, the hover display is much better.
