### ISSUE TITLE
Anonymous functions in constructors make extension more difficult (DebugSession)

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#8614]
### Feature Description:

My particular interest at the moment is in the `DebugSession` class, but it is true more generally that if any anonymous function with a non-trivial implementation appears in a constructor, the whole constructor has to be rewritten if the class is extended and that listener is to be modified.

https://github.com/eclipse-theia/theia/blob/5eb6efa40129101b74a88a16e0c45e81545ab966/packages/debug/src/browser/debug-session.tsx#L77-L112

Here, if an adopter wants to modify the behavior of the class on a `continued`, `stopped`, `thread`, or `terminated` event, or access the full `capabilities` or `breakpoint` event in a custom implementation of `updateBreakpoint()` or `updateCapabilities()`, they have to rewrite the whole constructor.

Instead, it would be better to pass all of these through to named, overridable functions, e.g.

`this.on('stopped', (e) => this.handleStopped(e))`

The same is true for `init` functions, of course, and it might be worth codifying the avoidance of non-trivial anonymous functions in such contexts in the Coding Guidelines.

**Comment by akosyakov** [comment]
For such cases adopters should open a PR and make it more customizable. But forcing on everybody to extract a function because someone maybe somtimes wants to customize it is not a good reason to hold off PRs.

**Comment by colin-grant-work** [comment]
I'm not advocating that any particular PR be held up, only that good practice that doesn't hurt anything upstream and makes life easier for downstream projects should be considered for inclusion in the coding guidelines in the future.

**Comment by vince-fugnitto** [comment]
Closed by https://github.com/eclipse-theia/theia/pull/8616.
