### ISSUE TITLE
Error when restoring editor area if webview is opened

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-theia/theia#8620]
### Bug Description:
Editor area cannot be restored properly when it contains webview, and when there is no registered `vscode.WebviewPanelSerializer` for this webview.

The problem is because the method, which creates widgets, returns `undefined` for the webview.
In fact, the webview was created but immediately destroyed, because there is no appropriate `WebviewPanelSerializer`.
https://github.com/eclipse-theia/theia/blob/416b12d259e07d1e61ffbc687cf55f496df8f7bc/packages/core/src/browser/shell/shell-layout-restorer.ts#L336-L338

Then `undefined` was set to the array without any checks
https://github.com/eclipse-theia/theia/blob/416b12d259e07d1e61ffbc687cf55f496df8f7bc/packages/core/src/browser/shell/shell-layout-restorer.ts#L267-L275

### Steps to Reproduce:

1. Run Theia with any plugin, which opens a webview and don't register webview serializer. I used simple plugin https://github.com/vitaliy-guliy/greeting-extension. Clone it and build with `npm install && vsce package` command.
2. Open Theia. A new 'Greeting' webview will be opened by a plugin.
3. Create and open few files. The webview must be left in the first tab.
4. Reload Theia.

Linkin with https://github.com/eclipse-theia/theia/issues/6877 as it's easily reproducible with `greeting-extension` (Theia is loaded but no tabs are opened)

Video demonstrating the bug https://www.youtube.com/watch?v=9ir1hTov350

**Comment by tsmaeder** [comment]
I'm not convinced this is the right fix: if we don't have a WebviewPanelSerializer, shouldn't we just recreate the webview to it's default state? After all, there are webviews that simply do not have mutable state.

**Comment by akosyakov** [comment]
VS Code contract: webviews which don't have serialiser are not restorable.

**Comment by tsmaeder** [comment]
@akosyakov correct: https://code.visualstudio.com/api/extension-guides/webview#serialization
