### ISSUE TITLE
activeColorTheme api is not supported by THEIA

### ISSUE THREAD

**Issue by NetaMolcho** [eclipse-theia/theia#8635]
### Bug Description:

I try to check if the current theme is a light theme or dark theme and accordingly provide a suitable icon.

![image](https://user-images.githubusercontent.com/35297731/96105662-f45c0080-0ee2-11eb-8539-c93bfdbe8567.png)

This code works in vscode but is not supported by theia, return undefined.
Is there a way that activeColorTheme will also be supported by theia?

### Additional Information

- Operating System: 
- Theia Version: 1.6.0

**Comment by vince-fugnitto** [comment]
> Is there a way that activeColorTheme will also be supported by theia?

@NetaMolcho feel free to open a pull-request to add the `activeColorTheme` API to the plugin-system so it is supported by the framework when consuming VS Code extensions. The `activeColorTheme` API was finalized [6 months ago](https://github.com/microsoft/vscode/commit/af44ead34cb412c0db254e4bc2d01f126cdb700a).

Internally, the new API would use `theming.ts` and/or `theming-service.ts` to provide functionality:

https://github.com/eclipse-theia/theia/blob/c4f324ada78e8074c401fa52a0a655bbb64de017/packages/core/src/browser/theming.ts#L24

https://github.com/eclipse-theia/theia/blob/c4f324ada78e8074c401fa52a0a655bbb64de017/packages/core/src/browser/theming.ts#L126-L129

https://github.com/eclipse-theia/theia/blob/c4f324ada78e8074c401fa52a0a655bbb64de017/packages/core/src/browser/theming.ts#L47
