### ISSUE TITLE
SelectAll/Copy/Paste Keyboard Shortcuts are not working within DevTools and native input and file dialogs

### ISSUE THREAD

**Issue by christlee1989** [eclipse-theia/theia#8654]
### Bug Description:
Copy/Paste Keyboard Shortcuts are not working within DevTools

### Steps to Reproduce:

1.Open Devtools
2.try Cmd+C/Cmd+V  copy/paste anything in Devtools, Nothing happened

I can see that it executed the COPY command, but nothing todo
![image](https://user-images.githubusercontent.com/10151385/96683963-7057bc00-13ad-11eb-8f70-42b0f882536e.png)

### Additional Information

- Operating System: macOS 10.15.6
- Theia Version: 1.6.0

**Comment by vince-fugnitto** [comment]
@christlee1989 I'm not sure I understand correctly, are you stating that keyboard shortcuts from the application are not working in chrome's devtools? "Copy/Paste Keyboard Shortcuts are not working within DevTools" seems to suggest this is what the issue is talking about.

**Comment by christlee1989** [comment]
> @christlee1989 I'm not sure I understand correctly, are you stating that keyboard shortcuts from the application are not working in chrome's devtools? "Copy/Paste Keyboard Shortcuts are not working within DevTools" seems to suggest this is what the issue is talking about.

yes, as shown in the figure

![image](https://user-images.githubusercontent.com/10151385/96816662-473c3780-1450-11eb-9339-f1f79b03f432.png)

**Comment by vince-fugnitto** [comment]
@christlee1989 it is still not clear what the exact issue is, commands from `theia` should not work in `devTools`, and the standard copy & paste work well in `devTools`.

**Comment by kittaakos** [comment]
Where exactly do you have the issues with copy/paster, @christlee1989? Can you share a screencast that depicts the defect?

**Comment by christlee1989** [comment]
> commands from `theia` should not work in `devTools`, and the standard copy & paste work well in `devTools`.

When I execute the CMD+C shortcut in devtool, the copy command of theia is triggered，and can’t paste copied content

**Comment by kittaakos** [comment]
> the copy command of theia is triggered

Yes, I can confirm this. It isn't an enjoyable dev experience, especially when you have another (non-theia) Electron browser window opened; keybindings just does not work. For example, for logging in, you open a new browser window.

For the record, this is a dev thing only. It does not cause any core-Theia malfunction. Feel free providing a PR with the fix, @christlee1989  ;)

**Comment by kittaakos** [comment]
I have converted this issue into a bug: the SelectAll + Copy + Paste functionality does not work with the native dialogs either.

**Comment by zhaomenghuan** [comment]
@kittaakos Hello，I also encountered this problem here，is there any solution to this problem?
