### ISSUE TITLE
Navigator allows users to collapse workspace node

### ISSUE THREAD

**Issue by caseyflynn-google** [eclipse-theia/theia#8658]
### Bug Description: Navigator allows users collapsing the workspace node
Theia allows the default workspace node to be collapsed which seems odd, and may be unintentionally invoked by users.

### Steps to Reproduce:

1. Open the File Navigator view.
2. Ensure no file/directory is currently selected in the navigator (this may be accomplished by clicking the collapse all button)
3. Click an area in the File navigator that is not populated with a file
4. Press enter, or the left arrow key

Observe there are no files displayed.

Mitigation: After you are in this state, you may expand the workspace by pressing enter, or the right arrow, however this would not be apparent to a user who entered this state unintentionally.

![Weird Navigator UX](https://user-images.githubusercontent.com/23463108/96784863-dee34c80-13a2-11eb-9848-0e435b3f0d6b.gif)

### Additional Information

- Operating System: Chrome OS / Linux:
- Theia Version: 1.6.0

**Comment by vince-fugnitto** [comment]
The following method seems to be the issue when there is no selection in the `explorer`:

https://github.com/eclipse-theia/theia/blob/60def5302c271db3cdb8212f2e1a18af814d9599/packages/core/src/browser/tree/tree-widget.tsx#L1107-L1114
