### ISSUE TITLE
Git clone from file explorer when no workspace

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#8667]
### Feature Description:

Similar to vs code I would like to git clone a repo before opening any workspace.

Vscode:
![image](https://user-images.githubusercontent.com/9420921/97177128-abd3fb00-179e-11eb-9f28-dc9b7fc71697.png)

**Comment by kittaakos** [comment]
We should support the [`ViewsWelcomeExtensionPoint`](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/welcome/common/viewsWelcomeExtensionPoint.ts) properly, and not do another hack as we did for the `Open Workspace` and `Init Repository`.

**Comment by vince-fugnitto** [comment]
Some additional information regarding contributing [welcome content](https://code.visualstudio.com/api/extension-guides/tree-view#welcome-content). The clone repository welcome content is actually contributed through the builtin git extension and once the API is supported we can benefit from it's functionality.

**Comment by amiramw** [comment]
Is it contained in https://github.com/eclipse-theia/theia/issues/7178?

**Comment by vince-fugnitto** [comment]
> Is it contained in #7178?

I believe so yes :)

**Comment by EstherPerelman** [comment]
@amiramw 
For now the git.clone command in theia is enabled only if a workspace is opened
This is the code in git-contribution.ts:
    registry.registerCommand(GIT_COMMANDS.CLONE, {
            isEnabled: () => this.workspaceService.opened,
            execute: (url?: string, folder?: string, branch?: string) =>
                this.quickOpenService.clone(url, folder, branch)
        });
So supporting view-welcome for explorer will display the "clone repository" button **disabled**

**Comment by vince-fugnitto** [comment]
> @amiramw
> For now the git.clone command in theia is enabled only if a workspace is opened
> This is the code in git-contribution.ts:

@EstherPerelman the `@theia/git` extension does not contribute any welcome views, the support should come when using the `builtin-git` and `builtin-git-ui` vscode extensions which replace `@theia/git`.

**Comment by EstherPerelman** [comment]
> @EstherPerelman the `@theia/git` extension does not contribute any welcome views, the support should come when using the `builtin-git` and `builtin-git-ui` vscode extensions which replace `@theia/git`.

@vince-fugnitto  But in order to clone a repository we use the git.clone command

**Comment by amiramw** [comment]
It is also implemented in the git builtin extension. 
You can see those extensions here: https://open-vsx.org/?search=git&category=&sortBy=relevance&sortOrder=desc

I'm not sure the lastest versions work in theia.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto But in order to clone a repository in the **explorer** view we use the git.clone command

@EstherPerelman the `git.clone` command you referenced comes from `@theia/git` which should not be used alongside the `builtin-git` and `builtin-git-ui` vscode extensions (which provides the 'welcome-view'), these extensions replace `@theia/git`. 

The builtin defines it's own `git.clone` command with a different `when` clause which you can view through it's sources.

**Comment by amiramw** [comment]
After support to welcome views and adoption of builtin git this feature works. Closing.
