### ISSUE TITLE
Problems loading reference 'vscode://schemas/settings/folder'

### ISSUE THREAD

**Issue by shahar-h** [eclipse-theia/theia#8673]
### Bug Description:
The following warning appears for `settings.json` file in workspace: 
`Problems loading reference 'vscode://schemas/settings/folder': Unable to load schema from 'vscode://schemas/settings/folder': A resource provider for 'vscode://schemas/settings/folder' is not registered.` 

### Steps to Reproduce:

Create `settings.json` file under .`vscode` folder.

### Additional Information

- Operating System: Windows 10
- Theia Version: Master

**Comment by vince-fugnitto** [comment]
It is a duplicate issue of https://github.com/eclipse-theia/theia/issues/8349, which tracks supporting multiple schemas such as:

```ts
export const defaultSettingsSchemaId = 'vscode://schemas/settings/default';
export const userSettingsSchemaId = 'vscode://schemas/settings/user';
export const machineSettingsSchemaId = 'vscode://schemas/settings/machine';
export const workspaceSettingsSchemaId = 'vscode://schemas/settings/workspace';
export const folderSettingsSchemaId = 'vscode://schemas/settings/folder';
export const launchSchemaId = 'vscode://schemas/launch';
