### ISSUE TITLE
Switching preference scopes in Preference UI does not properly populate tree

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#8689]
### Bug Description:
For preference contributions which explicitly are scoped to USER, switching scope tabs in the preferences UI does properly update the Preference Tree view which leads to odd behavior and misleading interactions. 

### Steps to Reproduce:

1. Create a new PreferenceSchema with a single preference that is scoped to 'PreferenceScope.User', for example:
```
export const MyNewPreferenceSchema: PreferenceSchema = {
    type: 'object',
    properties: {
        'test.preference': {
            'type': 'string',
            'default': 'default value',
            'description': 'this is a test preference',
            'scope': PreferenceScope.User
        },
    },
};
```
2. Build, and open preference UI in multiroot workspace, the `User` tab will be select, observe that the preference exists in User scope
3. Switch to `Workspace` scope, observe that the Preference contribution still appears (even though it shouldn't)
4. Switch to a folder scope observe the preference disappears (this is correct)
5. Switch back to Workspace scope, the preference is still gone 
6. Switch back to User scope, the preference is still not visible
7. Switch back to Folder scope, then back to User scope, the preference is now back!

### Additional Information

- Operating System:
Linux
- Theia Version:
Master

**Comment by colin-grant-work** [comment]
I believe that this bug is fixed by #8263
