### ISSUE TITLE
Installers for all major operating systems

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia#8707]
To make Theia more approachable to new users, it would be great to have a pre-build version of Theia that can be installed with a nativ installer for all major operating systems (Windows, MacOS and Linux). 
This effort has been driven by Rob Moran so far and he has already created installer packages for all operating systems. Thank you very much, @thegecko!
We see the following remaining points to be addressed:
- Testing: testing installed instance with a smoke/system test to make sure it is functional (also see [Issue](https://github.com/eclipse-theia/theia-example/issues/6))
- Define default package: define which plugins and extensions to include (also see [Issue](https://github.com/eclipse-theia/theia-example/issues/5))
- Marketing: Create a web-page for the download and announce the new installer (also see [Issue](https://github.com/eclipse-theia/theia-example/issues/7) and [other Issue](https://github.com/eclipse-theia/theia-example/issues/8))
- Welcome page: Add a welcome page in the Theia instance with some information about the product. (also see [Issue](https://github.com/eclipse-theia/theia-example/issues/9))
- About dialog: Beautify about dialog and add some information and links (also see [Issue](https://github.com/eclipse-theia/theia-example/issues/10))
- Release: Define a release process for the installer and its relation to the Theia release process (also see [Issue](https://github.com/eclipse-theia/theia-example/issues/12))
- Updates: Enable in-place updates for installed instances (also see [Issue](https://github.com/eclipse-theia/theia-example/issues/13))
- Customization: Enable and document how to customize the installer for custom products (also see [Issue](https://github.com/eclipse-theia/theia-example/issues/14))

We plan to contribute this work to the project on behalf of ST Microelectronics.

**Comment by thegecko** [comment]
Cc @marcdumais-work @brianking

**Comment by brianking** [comment]
I'm very excited about this. Let me know how we (the ECD Tools Working Group) can support.

**Comment by Jeeppler** [comment]
I am very excited about this feature. I would really like to get my hands-on Eclipse Theia. Never, used it, but watched some talks at Eclipse Con mentioning Theia. An installer would make it easy for me to test it.

**Comment by thegecko** [comment]
@Jeeppler https://download.eclipse.org/theia/

**Comment by koegel** [comment]
> I'm very excited about this. Let me know how we (the ECD Tools Working Group) can support.

Will do, thanks for offering your support!

**Comment by Jeeppler** [comment]
@thegecko thanks. I tried it. I really liked it, especially because it appears to be fast. One thing which took me a moment to understand is, that the Theia package does not come with basic syntax highlighting. I had to install the "*Basic Language (built-in)" packages. The `built-in` part confused me at the beginning, until I figured out those are build into VS Codium and not available in the Theia by default.

I am really used to Gedit (GNOME) to providing me with basic Syntax highlighting for several languages. Having syntax highlighting is really convenient. I do not expect any other "fancy" features, by default.

The only plugins I would expect more features from in Theia are plugins for: YAML, JSON and XML. Those file formats are very common and a plugin with more features would be preferable. A plugin supporting formatting would be nice for all of those formats.

**Comment by koegel** [comment]
> @thegecko thanks. I tried it. I really liked it, especially because it appears to be fast. One thing which took me a moment to understand is, that the Theia package does not come with basic syntax highlighting. I had to install the "*Basic Language (built-in)" packages. The `built-in` part confused me at the beginning, until I figured out those are build into VS Codium and not available in the Theia by default.
> 
> I am really used to Gedit (GNOME) to providing me with basic Syntax highlighting for several languages. Having syntax highlighting is really convenient. I do not expect any other "fancy" features, by default.
> 
> The only plugins I would expect more features from in Theia are plugins for: YAML, JSON and XML. Those file formats are very common and a plugin with more features would be preferable. A plugin supporting formatting would be nice for all of those formats.

Thanks for the feedback, this is good input for defining the default package!

**Comment by marcdumais-work** [comment]
Hi @koegel ,

Thank you and ST Microelectronics for stepping-up and offering to take @thegecko 's nice work to the next level. 

> it would be great to have a pre-build version of Theia

So we're on the same page, Theia is a platform/framework used to develop IDE applications. What Rob did is a nice multi-OS packaging for an example Theia application. 

That being said, since there is currently no Eclipse Foundation project, dedicated to developing such a Theia-based IDE application, this example can quickly become the best we have, with a bit of TLC, and I hope it can eventually spawn its own EF project, offering a full-fledged extensible IDE application, for everyone to use and improve.

The "points left to address" in the description above sound good, to start-with.

**Comment by marcdumais-work** [comment]
@koegel would you like to visit us in our [dev-meeting](https://github.com/eclipse-theia/theia/wiki/Dev-Meetings) to talk about your plans regarding the packaged Theia example app? It could be this coming Tuesday or perhaps the next one.

**Comment by brianking** [comment]
We should consider making it an Eclipse project sooner rather than later.

**Comment by koegel** [comment]
> Hi @koegel ,
> 
> Thank you and ST Microelectronics for stepping-up and offering to take @thegecko 's nice work to the next level.
> 
> > it would be great to have a pre-build version of Theia
> 
> So we're on the same page, Theia is a platform/framework used to develop IDE applications. What Rob did is a nice multi-OS packaging for an example Theia application.
> 
> That being said, since there is currently no Eclipse Foundation project, dedicated to developing such a Theia-based IDE application, this example can quickly become the best we have, with a bit of TLC, and I hope it can eventually spawn its own EF project, offering a full-fledged extensible IDE application, for everyone to use and improve.
> 
> The "points left to address" in the description above sound good, to start-with.

Yes, I agree, this could be the starting point for project dedicated to build a Theia-based IDE application - maybe even in its own project at some point. For now I would like to focus on getting it out of the door and see where it goes :).

**Comment by koegel** [comment]
> @koegel would you like to visit us in our [dev-meeting](https://github.com/eclipse-theia/theia/wiki/Dev-Meetings) to talk about your plans regarding the packaged Theia example app? It could be this coming Tuesday or perhaps the next one.
Yes, thank you for the invitation, I will join you on upcoming Tuesday. Looking forward to meeting you!

**Comment by chalcosoma** [comment]
Hello! I'm a Visual Studio Code user and when I saw Theia I was amazed by the product. But I was hoping to see a easy way to install it. I'm very happy that now I can install Theia without having to build it myself or use Docker, because I could not do either. 

Thank you for made this process simpler.

 I tried to install and it was easy but when I ran the program I could not drag and drop Visual Studio Code Extensions. How do I install those extensions in Theia?

**Comment by koegel** [comment]
> Hello! I'm a Visual Studio Code user and when I saw Theia I was amazed by the product. But I was hoping to see a easy way to install it. I'm very happy that now I can install Theia without having to build it myself or use Docker, because I could not do either.
> 
> Thank you for made this process simpler.
> 
> I tried to install and it was easy but when I ran the program I could not drag and drop Visual Studio Code Extensions. How do I 
install those extensions in Theia?

Thank you for your nice feedback!

To my best knowledge you cannot directly install VS Code extensions from the VS Code marketplace due to license restrictions. You can however install from an alternative marketplace called Open VSX, for details please see this blog post:
https://eclipsesource.com/blogs/2019/10/31/using-vs-code-extensions-in-eclipse-theia-and-che/
Please let me know if it works for you, I did not try this feature so far in this product.

Please also note that this is effort was only meant to create e a blueprint product showcasing how to build custom Theia-based products. It is not meant for use in production. Also it is currently only an alpha version and still under development and lacking proper testing. So use with caution.
Thanks for testing!

**Comment by koegel** [comment]
BTW: Most of us are currently on vacation, we will be back next week and will then also take a look ourselves.

**Comment by jfaltermeier** [comment]
> Hello! I'm a Visual Studio Code user and when I saw Theia I was amazed by the product. But I was hoping to see a easy way to install it. I'm very happy that now I can install Theia without having to build it myself or use Docker, because I could not do either.
> 
> Thank you for made this process simpler.
> 
> I tried to install and it was easy but when I ran the program I could not drag and drop Visual Studio Code Extensions. How do I install those extensions in Theia?

Hi, we tested installing vs code extensions and the two approaches from the blogpost shared above should work as expected.  

You can use the Open VSX Registry like this:
in the menu bar -> View -> Extensions
Search for the plugin you want and install the extension

The approach to install directly from the VSCode marketplace should work, however there are license restrictions for the VSCode marketplace, so this is forbidden.
Press F1 -> Plugin: Deploy Plugin by Id
vscode:extension/ms-python.python

You can use "Deploy plugin by id" with other sources as well: https://eclipsesource.com/blogs/2019/10/17/how-to-add-extensions-and-plugins-to-eclipse-theia/ (See "How to add plugins to Eclipse Theia at runtime") So you may bypass the VSCode marketplace

**Comment by vince-fugnitto** [comment]
@koegel is there anything outstanding left before this issue can be closed? Should it perhaps be moved to `theia-blueprint` instead?

**Comment by koegel** [comment]
@vince-fugnitto Feel free to close it, it was meant as an umbrella issue for the effort going on in the blueprint repo and to raise awareness.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Feel free to close it, it was meant as an umbrella issue for the effort going on in the blueprint repo and to raise awareness.

Closing, the issues are now opened on [theia-blueprint](https://github.com/eclipse-theia/theia-blueprint).
