### ISSUE TITLE
Add VS Code API to contribute submenus

### ISSUE THREAD

**Issue by devinea** [eclipse-theia/theia#8724]
# Feature Description: 
VS Code recently added support to contribute sub menus in the context explorer as part of https://github.com/microsoft/vscode/issues/100172

Could this be ported to Theia?

Syntax
```
{
  "contributes": {
    "menus": {
      "scm/title": [
        {
          "command": "git.commit",
          "group": "navigation"
        },
        {
          "submenu": "git.stage",
          "group": "navigation"
        }
      ],
      "git.stage": [
        {
          "command": "git.stageAll",
          "group": "navigation"
        },
        {
          "command": "git.stageUntracked",
          "group": "navigation"
        }
      ]
    },
    "submenus": [
      {
        "id": "git.stage",
        "label": "Stage",
        "icon": "$(something)"
      }
    ]
  }
}

```
![image](https://user-images.githubusercontent.com/10102054/98357820-ab005c00-201d-11eb-952b-098709c31cc6.png)

Implementation https://github.com/microsoft/vscode/pull/102784
Some updates https://github.com/microsoft/vscode/commit/130aa96b42113e4ff008ed53ce0e396891bd4090 & https://github.com/microsoft/vscode/commit/98262ef05017cc79ab33be09a2de921c4141ada4

**Comment by yuki-yukiyu** [comment]
Hi @vinokurig 
The submenu under "scm/title" can totally work. But I wonder if it will also work under “explorer/context”？It seems not work in this case.
My code:
"contributes": {
	"commands": [
              {
		      "command": "normal.menu",
		      "title": "Menu"
	      },
	      {
		      "command": "custom.submenu.one",
		      "title": "SubMenu-1"
	      },
	      {
		      "command": "custom.submenu.two",
		      "title": "SubMenu-2"
	      }
        ],
        "menus": {
	        "explorer/context": [
		        {
			        "command": "normal.menu",
			        "group": "navigation"
		        },
		        {
			        "submenu": "custom.submenu",
			        "group": "navigation"
		        }
	        ],
	        "custom.submenu": [
		        {
			        "command": "custom.submenu.one",
			        "group": "navigation"
		        },
		        {
			        "command": "custom.submenu.two",
			        "group": "navigation"
		        }
	        ]
        },
        "submenus": [
	        {
		        "id": "custom.submenu",
		        "label": "Custom Submenu"
	        }
        ]
},
