### ISSUE TITLE
Allow notifications to have newlines

### ISSUE THREAD

**Issue by NiklasRentzCAU** [eclipse-theia/theia#8743]
### Feature Description:
As of [this commit](https://github.com/eclipse-theia/theia/commit/a7ec8088e475c0ce811e96fdc846172568cbfd84), notifications cannot be rendered using any form of newline supported by markdown. As all HTML tags, including `<br>` are removed (sensible for preventing any XSS attacks) and all `'\n'` are removed, no way of defining newlines in markdown can be used anymore. This behavior is the same in VSCode, but highly requested to change there as well (see their issue [#101589](https://github.com/microsoft/vscode/issues/101589)).

I would specifically like this feature to be able to show exception traces generated on a server application to the user. Those notifications are currently being butchered as all formatting for the stack trace is removed.

Other than aligning with VSCode, is there any specific reason to not support newlines in the notifications? Or is there some way around this to still be able to configure the notifications to allow for newlines?

**Comment by vince-fugnitto** [comment]
@NiklasRentzCAU 

> Other than aligning with VSCode, is there any specific reason to not support newlines in the notifications?

The main reason is to align with vscode, and have a consistent representation of `newlines` in standard notifications.
Please note that it is possible to use `modal` notifications to render `newlines` if needed: https://github.com/eclipse-theia/theia/pull/7500.

>  I would specifically like this feature to be able to show exception traces generated on a server application to the user.

I do not believe the framework wants to deviate from vscode at this time and have an inconsistent behavior when displaying messages. If and when [#101589](https://github.com/microsoft/vscode/issues/101589) has been implemented we can re-work the current default implementation.

> Or is there some way around this to still be able to configure the notifications to allow for newlines?

The framework provides a default implementation, it is always possible for downstream application developers to define their own custom `@theia/` extensions which extend/override the default implementation to suit their needs and use-cases. In this case, you can extend the implementation for `notifications` to support markdown and/or newlines.

**Comment by NiklasRentzCAU** [comment]
Thank you, I just extended the implementation for my application to allow newlines again. Thank you for the insight!

**Comment by vince-fugnitto** [comment]
Closing the issue due to the following reasons:
- there are no plans on deviating the default behavior with vscode, downstream applications may define their own behavior
- notifications with `newlines` are possible using the `modal` option
- the previous implementation had security concerns
