### ISSUE TITLE
Support workbench.action.files.openFileFolder built-in command

### ISSUE THREAD

**Issue by bfitzpat** [eclipse-theia/theia#8750]
### Feature Description:

In addition to the many other command Ids you have supported for us to get Didact working on Theia, it turns out we also need `workbench.action.files.openFileFolder` to support opening a didact file from a didact file. 

See https://github.com/redhat-developer/vscode-didact/issues/280

**Comment by azatsarynnyy** [comment]
The command is contributed by https://github.com/eclipse-theia/theia/pull/9213
