### ISSUE TITLE
vscode.Uri.joinPath is not a function

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#8752]
### Bug Description:
I got the error in the browser console at using for `Theia` project `VS Code` test extension  with the following code:
```
vscode.Uri.joinPath(folder.uri, defaultFile);
```
The same extension works well for `VS Code`.

### Steps to Reproduce:

1. Clone https://github.com/RomanNikitenko/vscode-test-extension.git
2. Build the extension using yarn and copy it to `theia/plugins` folder.
3. Start `Theia` and open `Theia` project as a workspace folder - it's required to have some files for testing.
4. `F1` => run `Test 'vscode.Uri.joinPath'`

The command for testing should just display a notification with info about path to `package.json` file. 
Please see the source code [here](https://github.com/RomanNikitenko/vscode-test-extension/blob/7529fa097c2e9d9b47e4fb35fbe7acf1f048beaa/src/extension.ts#L96-L99)

It works well for `VS Code`. But it doesn't work for `Theia` - you can see an exception in the browser console.

![joinPath_error](https://user-images.githubusercontent.com/5676062/99123526-011a6400-2609-11eb-8919-065538276487.gif)

The same command in `VS Code`:
![joinPath_vscode](https://user-images.githubusercontent.com/5676062/99123872-c2d17480-2609-11eb-8bff-7189ca77fbcb.gif)

### Additional Information

- Operating System: Fedora-31
- Theia Version: 476c8df3c987bb04db9c72b38a648fc47f0bbe1e

**Comment by PEZ** [comment]
I'm also running into this. Effectively stops my extension from working. Is it supposed to work?

**Comment by danarad05** [comment]
@RomanNikitenko @vince-fugnitto @amiramw 

Seems like for the support of **joinPath** (and the other uri Utils functions added in latest vscode version) - we need to upgrade **@theia/monaco-editor-core** to vscode standalone@0.21 version. #8691 also exists in that matter.

Current version is 0.20.x:
![image](https://user-images.githubusercontent.com/71069170/104838882-4fc4d280-58c6-11eb-98df-4f801f152ac8.png)

VS Code standalone/0.21.x contains joinPath function:
https://github.com/microsoft/vscode/blob/standalone/0.21.x/src/vs/base/common/uri.ts

VS Code standalone/0.20.x **does not** contain joinPath function:
https://github.com/microsoft/vscode/blob/standalone/0.20.x/src/vs/base/common/uri.ts

**Comment by kittaakos** [comment]
Closed via https://github.com/eclipse-theia/theia/pull/9199.

**Comment by vince-fugnitto** [comment]
> Closed via #9199.

@kittaakos it was reverted https://github.com/eclipse-theia/theia/pull/9222 :smile:

**Comment by danielfireman-ifal** [comment]
The [golang.Go](https://marketplace.visualstudio.com/items?itemName=golang.Go) extension is not working due to this error. Any workarounds, so far? Thanks!

**Comment by vince-fugnitto** [comment]
> The [golang.Go](https://marketplace.visualstudio.com/items?itemName=golang.Go) extension is not working due to this error. Any workarounds, so far? Thanks!

@danielfireman-ifal the only workaround I would suggest until the _monaco upgrade_ would be to use an older version of `golang.go` which does not use the newer `vscode.Uri.joinPath` function.

**Comment by danielfireman-ifal** [comment]
In case someone ran into the same problem, adding the following snippet to your `gitpod.yml" does the trick:

```yml
  extensions:
    - golang.go@0.21.0
```

does the trick. Thanks a lot @vince-fugnitto !

**Comment by tsmaeder** [comment]
I have a fix for this one. Please stand by....
