### ISSUE TITLE
Python debugger exits with error in Theia 1.7.0

### ISSUE THREAD

**Issue by buvoli** [eclipse-theia/theia#8754]
In my previous build of Theia (1.4.0) I was able to use the python debugger with the the vscode-python extension. In Theia 1.7.0 the debugger fails with an error. This issue is reproducible using the official python docker container `theiaide/theia-python:latest`

The following error message appears in the debug console:
```
Debugger Error: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.
Debugger Error: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.
Error
Error: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.
    at /home/theia/plugins/vscode-python/extension/out/client/debugger/debugAdapter/main.js:16:27311
    at Array.forEach ()
    at e (/home/theia/plugins/vscode-python/extension/out/client/debugger/debugAdapter/main.js:16:26875)
    at Object.t.plan (/home/theia/plugins/vscode-python/extension/out/client/debugger/debugAdapter/main.js:16:27386)
    at /home/theia/plugins/vscode-python/extension/out/client/debugger/debugAdapter/main.js:16:24044
    at e._get (/home/theia/plugins/vscode-python/extension/out/client/debugger/debugAdapter/main.js:16:23953)
    at e.get (/home/theia/plugins/vscode-python/extension/out/client/debugger/debugAdapter/main.js:16:22664)
    at s.get (/home/theia/plugins/vscode-python/extension/out/client/debugger/debugAdapter/main.js:68:141080)
    at new _ (/home/theia/plugins/vscode-python/extension/out/client/debugger/debugAdapter/main.js:1:269045)
    at /home/theia/plugins/vscode-python/extension/out/client/debugger/debugAdapter/main.js:1:272287
```

### Steps to Reproduce:

1. start Theia python container: `docker run -it --init -p 3000:3000  theiaide/theia-python:latest`
2. Add a configuration for debugging a single file
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal"
    }
  ]
}
```
3. Create a file `hello.py` with any code, then add a break point and start the debugger ( See Screenshot below)

![theia-bug-screenshot](https://user-images.githubusercontent.com/9490185/99160818-4473e180-26a0-11eb-8fce-87b4941b10df.png)

### Additional Information

- Operating System: Debian (Docker)
- Theia Version: 1.7.0

**Comment by appmlk** [comment]
the same as you 😫

**Comment by vince-fugnitto** [comment]
The following works correctly for me, when building this repository from sources:

<img width="1431" alt="Screen Shot 2020-11-15 at 12 50 00 PM" src="https://user-images.githubusercontent.com/40359487/99192490-27431f80-2741-11eb-80ce-e35c8d523288.png">

Here is my python debugging configuration:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "${file}",
      "console": "integratedTerminal"
    }
  ]
}
```

> This issue is reproducible using the official python docker container theiaide/theia-python:latest

Please note these images are not "official", they are used as examples for application developers to create their own applications, and are used for continuous integration purposes. The `readme` for [theia-apps](https://github.com/theia-ide/theia-apps) reflects this: https://github.com/theia-ide/theia-apps#overview

> Overview
This repository contains a collection of Theia-based IDE applications (both electron desktop apps and docker images) as examples, for demo and continuous-integration purposes.

**Comment by buvoli** [comment]
Could you clarify what you mean by "building from this repository"? I just cloned the repository [https://github.com/theia-ide/theia-apps](https://github.com/theia-ide/theia-apps), cd into the directory `theia-python-docker` and built the image using `docker build . -t theiaide/theia-python:latest`. After I run the docker container and try to debug python, I still get the same error.

I also noticed from your screenshot the python version is 3.8.2, however if you run a fresh build of the container from the theia-apps repository you will get python version 3.8.3, so we are not testing the same thing.

**Comment by vince-fugnitto** [comment]
> Could you clarify what you mean by "building from this repository"?

@buvoli [this](https://github.com/eclipse-theia/theia) repository contains the sources for the **theia framework**, and I wanted to make sure that the use-case works correctly on `master` (as the https://github.com/eclipse-theia/theia/issues/8754#issuecomment-727609599 suggests). As mentioned, the [theia-apps](https://github.com/theia-ide/theia-apps) repository is a collection of docker images and apps for example and continuous integration purposes. If there's an issue with one of the docker images (ex: python), an issue should be opened there instead of the framework: https://github.com/theia-ide/theia-apps/issues.

> I also noticed from your screenshot the python version is 3.8.2, however if you run a fresh build of the container from the theia-apps repository you will get python version 3.8.3, so we are not testing the same thing.

A [`patch`](https://semver.org/#semantic-versioning-200) version should not break debugging functionality.

**Comment by djmaze** [comment]
There is now a suitable issue: https://github.com/theia-ide/theia-apps/issues/441

**Comment by vince-fugnitto** [comment]
Closing as it has been moved to the `theia-apps` repository.
