### ISSUE TITLE
Gradle Tasks extension does not work in Theia

### ISSUE THREAD

**Issue by melaasar** [eclipse-theia/theia#8767]
The (VSCode) "Gradle Tasks" extension can be searched and installed in Gitpod (Theia). However, unlike in VSCode, the side bar does not show up after the install. Trying to show it by selecting View -> Open View makes the side bar visible. However, you get an error when trying to click on the bar saying that it cannot contact the gradle server. All the views of the bar are also empty and they appear to spin with no result (I think trying to contact some server). 

### Steps to Reproduce:

1. Select extensions bar in Gitpod (Theia). Search for "Gradle Tasks" and install it (for user or project).
2. At this point the Gradle side bar should appear on the left but it does not
3. Go to View -> Open View and search for Gradle and choose it. The side bar appears.
4. Click on the side bar, you get an error trying to contact a gradle server, 
5. All the Gradle tabbed views (especially Gradle Tasks,,) are not there initially. However, you can make them visible.
6. The Gradle Tasks view is empty (unexpected since there is a gradle script in the workspace).

### Exampe repo to try on:
https://gitpod.io/#https://github.com/opencaesar/core-vocabularies

- Operating System: I tried it in Gitpod but I believe it is a Theia bug

**Comment by vince-fugnitto** [comment]
@melaasar I verified your linked workspace and I see the following error:

```
[error] Unable to refresh tasks: vscode.CustomExecution is not a constructor
[error] [gradle-server] Error running gradle wrapper: Picked up JAVA_TOOL_OPTIONS: -Xmx2254m
[error] Unable to get daemon status: Error running gradle wrapper: Picked up JAVA_TOOL_OPTIONS: -Xmx2254m
```

The parent issue seems to be that ` vscode.CustomExecution` is not yet supported: https://github.com/eclipse-theia/theia/issues/7185

I do see the view, but the missing API looks like the main issue about tasks not being provided:

![image](https://user-images.githubusercontent.com/40359487/99840118-ee88b900-2b39-11eb-8c0a-c691201d44f0.png)
