### ISSUE TITLE
Code folding state should persist when closing & opening files

### ISSUE THREAD

**Issue by bjornhansen** [eclipse-theia/theia#8782]
## Feature Description:
When I fold a code block in Theia, the state of the folded block doesn't persist after I close the file. This behavior isn't optimal, as I have to re-fold code blocks whenever a file is closed or opened. This also doesn't match the behavior of VSCode.

_Can the behavior of code folding be modified to match that of VSCode?_

### Behavior in VSCode (expected):

1. Open a file
2. Fold a code block
3. Close the file
4. Re-open the file
5. _Code block is still folded_

### Behavior in Theia:

1. Open a file
2. Fold a code block
3. Close the file
4. Re-open the file
5. _All folded code blocks are unfolded_

This could also be considered a bug depending on your point of view. Apologies if it's mislabeled.

:star: **_Thanks for all your work on Theia!_** :star:

**Comment by kittaakos** [comment]
I have tried it with a random XML file from my workspace, it worked.

![screencast 2020-11-26 23-15-59](https://user-images.githubusercontent.com/1405703/100394560-d59e6d00-303d-11eb-9dd7-a1460b1b0ce7.gif)

I debug into the code, the folding range contribution is called correctly on restore state.

**Comment by vince-fugnitto** [comment]
@kittaakos the use-case you mentioned does work, but I believe the use-case of the author is preserving the folding state when a file is closed and re-opened, not when the app is reloaded:

**Use-Case 1** (_works_):
- open an editor and fold regions
- reload the app, the folding state **is** preserved

**Use-Case 2** (doesn't work while in vscode it does):
- open a file and fold regions
- close the editor
- re-open the same editor, the folding state **is not** preserved

**Comment by bjornhansen** [comment]
Yes, the second case is what I'm referring to.
