### ISSUE TITLE
Editor delta decorations not rendering

### ISSUE THREAD

**Issue by Tpuljak** [eclipse-theia/theia#8791]
### Bug Description:
Editor delta decorations are not rendering inside the editor but are rending on the minimap.

<img width="1170" alt="Screenshot 2020-11-27 at 14 20 36" src="https://user-images.githubusercontent.com/26512078/100453728-c1995080-30bb-11eb-9535-15dbe9f5001c.png">

```typescript
      const newDecorations: EditorDecoration[] = []
      newDecorations.push({
        range: Range.create(editor.document.positionAt(0), editor.document.positionAt(10)),
        options: {
          className: 'selection',
          afterContentClassName: 'after',
          beforeContentClassName: 'before',
          minimap: {
            color: 'red',
            position: MinimapPosition.Inline
          }
        }
      })

      console.log(JSON.stringify(newDecorations))

      editor.deltaDecorations({ oldDecorations: [], newDecorations })
```

As you can see on the right, the minimap selection added by the method is displayed in red, but the selection is not present in the editor.

Example [repo](https://github.com/Tpuljak/editor-decorations-example)

### Steps to Reproduce:

1. Run the example repo and open any file.

### Additional Information

- Operating System: MacOS
- Theia Version: latest

**Comment by vince-fugnitto** [comment]
@Tpuljak can you reproduce the issue from [sources](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start)? The example you provided only has a subset of functionality (`@theia` extensions) and does not include plugins.

**Comment by Tpuljak** [comment]
I need the delta decorator functionality to work inside an extension. That is why I created such an example. I will try to reproduce it now by building the whole theia repo

**Comment by vince-fugnitto** [comment]
@Tpuljak you may want to look at the `dirty-diff` decoration example on how to also decorate the editor, not only the minimap:
- https://github.com/eclipse-theia/theia/blob/master/packages/scm/src/browser/dirty-diff/dirty-diff-decorator.ts

**Comment by Tpuljak** [comment]
It seems that the decorations are indeed working, I just assumed that there was a default style for them, I included the style and they render correctly.
