### ISSUE TITLE
Adding a security policy to the repo

### ISSUE THREAD

**Issue by luigigubello** [eclipse-theia/theia#8795]
### Feature Description:

**Theia IDE Security Policy**

Theia IDE is a popular open-source project, but it misses a policy for reporting vulnerabilities. I think it would be important for people who want to report a critical issue in the right way. In addition, I suggest tracking critical bugs in the [Github security advisories](https://github.com/eclipse-theia/theia/security/advisories) section (e.g. Will issue #7954 receive a CVE?).

Thank you

Best regards

**Comment by kittaakos** [comment]
@marcdumais-work, can set up security policies in this repo? Does the Eclipse community have such a template that we can reuse as-is?

**Comment by luigigubello** [comment]
If you want, I can help to write a draft CVD policy for the Theia repo. At the moment, Eclipse Foundation has a [generic security policy](https://www.eclipse.org/security/policy.php), maybe we can adapt it to this repo. I suggest tracking Theia IDE security issues also using _Github security advisories_.

**Comment by marcdumais-work** [comment]
> I suggest tracking Theia IDE security issues also using Github security advisories.

@luigigubello I guess it depends what you have in mind exactly. I agree that currently it's not easy for a visitor to this repo, to find what to do, in case they found a security vulnerability. If you can propose a PR that helps with that, great. 

Theia is an Eclipse Foundation project, and they set the high-level security policy that we have to follow. So your draft should explicitly point-to and extend the Foundation's security policy, not try replace it. In case of doubt, I can have them have a look.

sounds like a plan?

**Comment by luigigubello** [comment]
> Theia is an Eclipse Foundation project, and they set the high-level security policy that we have to follow.

Eclipse Foundation's security policy seems to be good, but I'm not clear how security issues are tracked at the moment. I mean, in [the policy](https://www.eclipse.org/security/policy.php) I read:
> _All Vulnerabilities must be disclosed, regardless of the resolution._

I think this point is **really** important, Github security advisories don't have to replace the Eclipse Foundation bug tracking, but they can be a user-friendly mirror. So, my question is: how are security issues tracked and disclosed at the moment? Both fixed and open bugs. I mean, I have this list:

**_Security issues:_**

- Issue #8794 
- Issue #7954
- Issue #7498
- Issue #7283
- Issue #6987
- Issue #6976

Is there a way to track them? (CVE or GH advisories or Eclipse Foundation bug ID, just be public)

I will open a PR for suggesting a policy for this repo, it will be based on Eclipse Found. policy, but I think this project needs a better vulnerabilities tracking. Do you agree? Can we work together to improve this security process? :)
