### ISSUE TITLE
Define and propose outline service for LSP

### ISSUE THREAD

**Issue by svenefftinge** [eclipse-theia/theia#880]
Our current outline implementation is trying to compute a tree from `SymbolInformation` which lack information about hierarchies. It does that based on a mixture of range overlapping and `containerName` matching, which is rough and has problems with some language servers.

We should define a propose `OutlineTreeProvider` on the LSP level and propose it to the protocol. 
We can have a default implementation that does what we do today and can even have LS specific variants. E.g. Java and Python LS don't provide full ranges, but only for the actual identifier.

**Comment by AlexTugarev** [comment]
Is that still required? `DocumentSymbol`s are hierarchical.
