### ISSUE TITLE
electron: killing backend process and then closing all windows shows error popup

### ISSUE THREAD

**Issue by marechal-p** [eclipse-theia/theia#8804]
### Bug Description:

![image](https://user-images.githubusercontent.com/14182238/100647924-3368d880-330e-11eb-9f3d-908dcf341d49.png)

### Steps to Reproduce:

1. Build and run the electron example
2. Kill the backend process
3. Close all electron windows

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.8.0

**Comment by kittaakos** [comment]
Thanks for the note. This was logged [here](https://github.com/eclipse-theia/theia/issues/8534#issuecomment-708940820). I have the patch on my branch but go for it if you want the fix sooner.
