### ISSUE TITLE
Activating extension 'Go' failed: Command "go.gopath" already has handler

### ISSUE THREAD

**Issue by Kami-no** [eclipse-theia/theia#8810]
### Bug Description:

Unable to use extension "Go" with "theia-go"

### Steps to Reproduce:

1. run `theiaide/theia-go:next` or `theiaide/theia-go:latest` container
2. install `Go` extension
3. you have `Activating extension 'Go' failed: Command "go.gopath" already has handler`

### Additional Information

```
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
theiaide/theia-go   next                c682cb2a6abe        8 days ago          2.95GB
```

Built-in functionality for Golang has less features than "Go" extension. Is there a way to have golang in Thea container and still be able to use "Go" extension?

Optionally: I'd like to have an ability for extensions to override built-in features.

**Comment by kittaakos** [comment]
Can you please log your request to the appropriate repo? Thanks! https://github.com/theia-ide/theia-apps/issues/new

**Comment by Kami-no** [comment]
Ok
