### ISSUE TITLE
api-test: failure on 'navigator' suite

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#8812]
#### Bug Description:

The `navigator` `@theia/api-tests` suite is currently failing on recent builds:

```
root INFO   Navigator
root INFO     1) "before each" hook for "copy file"
root INFO     2) "after each" hook for "copy file"
```

#### Steps to reproduce:

The error is reproduced in recent builds (github actions), but locally the tests pass (using `npx run test @theia/example-browser`)

**Comment by tsmaeder** [comment]
@vince-fugnitto for me, they fail locally as well, but only when running all tests. Running `navigator-spec.js' in isolation always succeeds. 
https://github.com/eclipse-theia/theia/pull/9027 first failed on the windows run, rerunning them made them fail on ubuntu. This smells like timing issues.

**Comment by vince-fugnitto** [comment]
@tsmaeder I've noticed that as well, alone the test-suite is fine but with the rest it fails intermittently (and pretty often on github actions). I'll have to try and find the time to see what can be done to resolve the issue unless someone else wants to try their hand at fixing it.

**Comment by tsmaeder** [comment]
I have a suspicion that the underlying issue is https://github.com/eclipse-theia/theia/issues/7953 making the IDE super-slow.

**Comment by vince-fugnitto** [comment]
> I have a suspicion that the underlying issue is #7953 making the IDE super-slow.

@tsmaeder I'm not sure, the following PR https://github.com/eclipse-theia/theia/pull/9045 is mentioned as fixing #7953 but the CI still fails for it with the `navigator` test-suite.

**Comment by vince-fugnitto** [comment]
Closing for now thanks to https://github.com/eclipse-theia/theia/pull/9123.
I'll re-open the issue if the `navigator` test-suite regresses again.
