### ISSUE TITLE
Cannot register menu items asynchronously 

### ISSUE THREAD

**Issue by bendavis78** [eclipse-theia/theia#8815]
When creating a MenuContribution + CommandContribution, I am unable to use asynchronous logic inside the `registerCommands` and `registerMenus` functions. When you use async in either function, the menus are not registered properly (they simply don't appear).

You can reproduce this by starting from generator-theia-extension using the "widget" template. Update the `reigsterMenus` or `registerCommands` functions to register asynchronously, like so:

```typescript
    registerCommands(commands: CommandRegistry): void {
        setTimeout(() => {
            commands.registerCommand(TheiaTestCommand, {
                execute: () => super.openView({ activate: false, reveal: true })
            });
        });
    }

    registerMenus(menus: MenuModelRegistry): void {
        setTimeout(() => {
            super.registerMenus(menus);
        });
    }
```

To answer the question of "why would you want to do this", I need to create menu items dynamically based on a server-side configuration. That configuration is fetched asynchronously via JSONRPC.

**Comment by kittaakos** [comment]
> menu items dynamically based on a server-side configuration

See here: https://community.theia-ide.org/t/menuactions-based-on-data-recieved-from-backend/1200/2
