### ISSUE TITLE
rust-analyzer compatibility issue 

### ISSUE THREAD

**Issue by gengjiawen** [eclipse-theia/theia#8828]
### Describe the bug
Activating extension 'rust-analyzer' failed: The language client requires VS Code version ^1.51.0 but received version 1.44.0

### Steps to reproduce
Install latest https://github.com/rust-analyzer/rust-analyzer/releases

### Expected behavior
Works as expected

Original issue: https://github.com/gitpod-io/gitpod/issues/2438

**Comment by vince-fugnitto** [comment]
The following issue can be closed, the default api version was bumped:

https://github.com/eclipse-theia/theia/blob/8d5e12accfbd6bbe0cd720d3ebd151b700f4dc80/packages/plugin-ext-vscode/src/common/plugin-vscode-types.ts#L17

You can always bump the version through the `cli` when starting the application:

```bash
$ cd examples/browser
$ yarn start --vscode-api-version={version}
```

**Comment by vince-fugnitto** [comment]
When installing extensions you must respect the default API version by the framework.

https://github.com/eclipse-theia/theia/blob/8d5e12accfbd6bbe0cd720d3ebd151b700f4dc80/packages/plugin-ext-vscode/src/common/plugin-vscode-types.ts#L17

You can always bump the version through the `cli` when starting the application:

```bash
$ cd examples/browser
$ yarn start --vscode-api-version={version}
```

Note that the `extensions-view` will install extensions which are compatible through the API version.
