### ISSUE TITLE
Link from the output window does not work

### ISSUE THREAD

**Issue by deepak-jacob** [eclipse-theia/theia#8841]
### Bug Description:

 Ctrl+ clicking the link mentioned in the output widow does no action. It does not take to the file location, for a vscode extension added to theia electron IDE
![ouput_bug](https://user-images.githubusercontent.com/34061970/101646892-6579e900-3a38-11eb-8d19-0b0a136192fa.png)

Getting error though the file exists and the same link works in vscode: 

```
ERROR Fail to open 'file:///d%3A/test123/RegCheck/test-reg/test/test.st%3A8%3A0': 
Error: 'file:///d%3A/test123/RegCheck/test-reg/test/test.st%3A8%3A0' is invalid
```

### Steps to Reproduce:

1. Create/have a vscode extension which has a custom output channel which outputs file links to the output  channel
2. Ctrl+Click the link, and it does not respond

### Additional Information

- Operating System: Win 10
- Theia Version: @theia/core 1.7.0

**Comment by vince-fugnitto** [comment]
@deepak-jacob thank you for reporting the issue, do you happen to have a reproducible extension that the community can verify and test with?

**Comment by deepak-jacob** [comment]
Sorry for the delayed response. Please try to reproduce with this extension in theia (in the plugins folder, delete existing 'hbenl.vscode-test-explorer' folder, and then unzip this and place it there)
[vscode-test-explorer-2.19.3.vsix.zip](https://github.com/eclipse-theia/theia/files/5689320/vscode-test-explorer-2.19.3.vsix.zip)


Open the the theia IDE and please place this file in the workspace folder. For simplicity I hardcoded the file name
[sample123axb.txt](https://github.com/eclipse-theia/theia/files/5689321/sample123axb.txt)
Please open test explorer, which then open an output window. Try CTRL+clicking  on the link and it does not work. But the same works in vscode

**Comment by SandLZ** [comment]
I tested it recently.
position like below can be work
`file:///Users/xxx/Desktop/workspace/58Ihcr/pages/index.js#10:1`
Note that `#`, not `:`

**Comment by deepak-jacob** [comment]
Thank you @SandLZ . It works now.  Since this fix fails in vscode, I put a condition with "vscode.env.appName"

**Comment by JonasHelming** [comment]
This can also be reproduce with Theia Blueprint:
- Start any Theia-based browser app from within Blueprint
- Try to open the link printed in the terminal

**Comment by AlexandraBuzila** [comment]
I opened a PR that fixes the handling of localhost links in the terminal: https://github.com/eclipse-theia/theia/pull/10574

**Comment by koegel** [comment]
@colin-grant-work This issue is fixed, right?

**Comment by colin-grant-work** [comment]
@koegel, I believe so. In the Electron application, web links are opened in an external window and file links in the application; in the browser, web links open in a new tab and file links in the application.

**Comment by jfaltermeier** [comment]
Problem should be fixed, please feel free to reopen if this is not the case for you.
