### ISSUE TITLE
Websocket getting blocked in https  - THEIA_HOSTS

### ISSUE THREAD

**Issue by vishaakm** [eclipse-theia/theia#8845]
### Bug Description:
- `THEIA_HOSTS`
  - A comma-separated list of hosts expected to resolve to the current application.
    - e.g: `theia.app.com,some.other.domain:3000`
  - The port number is important if your application is not hosted on either `80` or `443`.
  - If possible, you should set this environment variable:
    - When not set, Theia will allow any origin to access the WebSocket services.
    - When set, Theia will only allow the origins defined in this environment variable.

I followed the above comment and didn't set the `THEIA_HOSTS` env 
and the IDE is working fine through localhost
but when accessed through a HTTPS endpoint websockets is getting blocked

happening after 1.8.1 update was working fine in 1.8.0

### Steps to Reproduce:

1. Don't set `THEIA_HOSTS` env.
2. Access theia from a https endpoint

### Additional Information

- Operating System: ubuntu (docker)
- Theia Version: 1.8.1

**Comment by 502647092** [comment]
after update to 1.8.1
try below env set
THEIA_HOSTS=hostname.com
THEIA_HOSTS=https://hostname.com
THEIA_HOSTS=hostname.com:443
THEIA_HOSTS=https://hostname.com:443
websocket response 403 code

**Comment by vishaakm** [comment]
> after update to 1.8.1
> try below env set
> THEIA_HOSTS=hostname.com
> THEIA_HOSTS=https://hostname.com
> THEIA_HOSTS=hostname.com:443
> THEIA_HOSTS=https://hostname.com:443
> websocket response 403 code

Thank you for the reply 
I tried this still facing same issuee


the https endpoint is a reverse proxy

**Comment by akosyakov** [comment]
@vishaakm Do you already have CORS or authentication checks for web socket in the reverse proxy? If so don't set `THEIA_HOSTS`.

**Comment by marechal-p** [comment]
Most likely related: https://github.com/eclipse-theia/theia/issues/8852

**Comment by vishaakm** [comment]
> @vishaakm Do you already have CORS or authentication checks for web sockets in the reverse proxy? If so don't set `THEIA_HOSTS`.

#8852   is the issue related to this

so I'll we be closing this issue
