### ISSUE TITLE
Broken link for theia api plugins

### ISSUE THREAD

**Issue by irohitb** [eclipse-theia/theia#8859]
### Bug Description:

Api of the plugins report 404 page not found when navigating from Authoring plugin

### Steps to Reproduce:
1. Visit [this link](https://theia-ide.org/docs/authoring_plugins)
2. Browse to API of plug-ins Section 
3. Click on Browse typedoc of plug-ins link

<img width="1440" alt="Screenshot 2020-12-14 at 11 52 22 AM" src="https://user-images.githubusercontent.com/32276134/102047186-d63b4f80-3e02-11eb-897b-59aa1155e214.png">

**Comment by kittaakos** [comment]
Moved to https://github.com/theia-ide/theia-website/issues/129.
