### ISSUE TITLE
vscode-mysql plug-in does not work in Chrome

### ISSUE THREAD

**Issue by sivaraam** [eclipse-theia/theia#8874]
### Bug Description:
When trying to use the [vscode-mysql](https://github.com/cweijan/vscode-mysql) plug-in as a [Theia extension](https://eclipsesource.com/blogs/2019/10/17/how-to-add-extensions-and-plugins-to-eclipse-theia/) in Chrome it loads properly. But when trying to add a connection, I get the following errors in the console:

```js
GET http://0d1333a9-5168-4ada-95fd-ac55af880111.webview.localhost:3000/webview/theia-resource/file///REDACTED/PATH/TO/theia/plugins/vscode-mysql/extension/out/webview/js/antv.js net::ERR_ABORTED 404 (Not Found)
GET http://0d1333a9-5168-4ada-95fd-ac55af880111.webview.localhost:3000/webview/theia-resource/file///REDACTED/PATH/TO/plugins/vscode-mysql/extension/out/webview/js/vendor.js net::ERR_ABORTED 404 (Not Found)
GET http://0d1333a9-5168-4ada-95fd-ac55af880111.webview.localhost:3000/webview/theia-resource/file///REDACTED/PATH/TO/plugins/vscode-mysql/extension/out/webview/js/app.js net::ERR_ABORTED 404 (Not Found)
```

### Steps to Reproduce:
1. Clone the Theia repository
    ```bash
    git clone --depth=1 https://github.com/eclipse-theia/theia/
    ```
2. In the `package.json` found in the repository root, add "vscode-mysql" to the plug-ins like so:
    ```js
      ...

      "theiaPluginsDir": "plugins",
      "theiaPlugins": {
        ...,
        "vscode-mysql": "https://open-vsx.org/api/cweijan/vscode-mysql-client2/2.7.3/file/cweijan.vscode-mysql-client2-2.7.3.vsix"
      }

      ...
    ```
3. Run `yarn` in the root directory.
4. Switch to the `examples/browser` directory.
5. Run `yarn start` to start the server.
6. Open the theia window in a browser and execute the "MySQL: Add connection" command.
7. Observe the error noted before in the console.

This was observed in v2.7.3 but is also reproducible with v2.7.7. Note that the plug-in seems to be working fine on Firefox (albeit [with a workaround](https://github.com/eclipse-theia/theia/pull/6465#issuecomment-556443218) to make the webview work properly for local testing).

Related issue in extension repo: https://github.com/cweijan/vscode-mysql/issues/79

### Additional Information

- Operating System: Windows 10
- Theia Version: @theia/example-browser 1.6.0 (let me know if I should be mentioning some other version here)

**Comment by vince-fugnitto** [comment]
The upstream issue states its been fixed in a newer version which does not use `localStorage` in the webviews.
Please try that version and comment if there are any additional issues/feedback.
