### ISSUE TITLE
file-search: support sub-queries (ex: line, symbol)

### ISSUE THREAD

**Issue by titivermeesch** [eclipse-theia/theia#8878]
So I noticed that the searchbar has a different behaviour than what I'm used to, is this because VS Code has some differences?

These are the points that are different:

- I can't seem to search for files that start with . (so searching .git does not return .gitignore or .gitpod.yml)
- Entering line number in the file opener does not work, writing index.js:42 should open index.js on line 42
- Writing :10 should go to line 10 in current file when writing in the file opener
- Spaces in file search are handled weird

This picture shows how I get results
![image](https://user-images.githubusercontent.com/12189066/102463192-14c34b00-404b-11eb-96c8-871954eaffc3.png)

This one shows the behaviour in Theia
![image](https://user-images.githubusercontent.com/12189066/102463234-20167680-404b-11eb-8669-8fc390338c33.png)

**Comment by vince-fugnitto** [comment]
@titivermeesch thank you for the issue, I have the following observations:

> I can't seem to search for files that start with . (so searching .git does not return .gitignore or .gitpod.yml)

This seems to work on `master`, for instance, searching for `.gitignore` files:

![quick-open-dot](https://user-images.githubusercontent.com/40359487/102491847-ce67ef00-403e-11eb-905e-cb366f03e300.gif)

> Entering line number in the file opener does not work, writing index.js:42 should open index.js on line 42
Writing :10 should go to line 10 in current file when writing in the file opener

The following is not yet supported from the `quick-file-open` implementation. It is currently not possible to:
- `:line`: append line number, to go to line when opening the file
- `@symbol`: append symbol, to go to symbol when opening the file

> Spaces in file search are handled weird

There is an issue tracking it: https://github.com/eclipse-theia/theia/issues/8747

**Comment by vince-fugnitto** [comment]
I've opened the following issues to track the remaining features:
- #9476 
- #9477 

Closing in favor of tracking them separately.
