### ISSUE TITLE
Theia application builds should be easy to reproduce

### ISSUE THREAD

**Issue by Niklas-Dahlquist** [eclipse-theia/theia#8879]
### Bug Description:

Theia is using "^1.x.y" instead of "1.x.y" in all modules, this causes two problems
1) Since romantic versioning is used within Theia repo, API breakage might be introduced between any version

2) It's harder to build applications using old versions of Theia extensions since if not every needed Theia extension is explicitly stated in dependencies/resolutions you will likely end up with pulling several parallel versions of @theia/core for example. Due to dependency injection we can not have multiple parallel versions of the same Theia extension module

### Steps to Reproduce:

1.  $ yo theia-extension:app none --browser 1 --electron 0 --extensionType empty --theia-version 1.3.0 --skip-install
2.  $ yarn
3.  Observe error:
ERROR in ../node_modules/@theia/monaco/lib/browser/monaco-frontend-module.js
Module not found: Error: Can't resolve '@theia/editor/lib/browser/semantic-highlight/semantic-highlighting-service' in '/local/home/<user>/dev/test/broken-again/node_modules
/@theia/monaco/lib/browser'

4. Observe that you have serveral different Theia extensions versions: $ yarn why @theia/core | grep Found
=> Found "@theia/core@1.9.0"
=> Found "none#@theia/core@1.3.0"
=> Found "browser-app#@theia/core@1.3.0"
=> Found "browser-app#@theia/editor#@theia/core@1.9.0"
=> Found "browser-app#@theia/filesystem#@theia/core@1.9.0"
=> Found "browser-app#@theia/markers#@theia/core@1.9.0"
=> Found "browser-app#@theia/navigator#@theia/core@1.9.0"
=> Found "browser-app#@theia/process#@theia/core@1.9.0"
=> Found "browser-app#@theia/workspace#@theia/core@1.9.0"

### Additional Information
See this discussion regarding the issue: https://github.com/eclipse-theia/theia/discussions/8445 - Versioning and Releases etc. 

The discussion suggests to use resolutions as a work-around, this shouldn't be needed if package.json uses specific versions "1.x.y" instead of "^1.x.y"

Work-around for @theia/core:
"resolutions": {​​
"@theia/core": "1.3.0"
}​​
However the work-around gives these warnings:
$ yarn why @theia/core | grep Found
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.4.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
warning Resolution field "@theia/core@1.3.0" is incompatible with requested version "@theia/core@^1.9.0"
=> Found "@theia/core@1.3.0"

- Theia Version: All that has been delivered so far.

**Comment by marechal-p** [comment]
I think you are onto something. Although I'd keep dependencies as `~x.y.z` because we actually try not to break API and only fix bugs using patch releases.

**Comment by Niklas-Dahlquist** [comment]
Hi Paul!
Yes that will possibly solve issue 1) API breakage, but it will not solve 2) Multiple simultaneous instances of same module

See https://github.com/eclipse-theia/theia-cpp-extensions/issues/106#issuecomment-670591239

/Niklas

**Comment by marechal-p** [comment]
What about third party extensions then? Say an extension is not released as often as the framework is. In such a case it would be expected to see both `1.x.0` and `1.y.0` pulled? App developers would need to use resolutions in such a case?

**Comment by Niklas-Dahlquist** [comment]
The general problem is described in 2), is caused by dependency injection. We cannot have both version x and version y of extension in a single application, because this will break at runtime.

Example:
third party extension has a dependency to @theia/core "1.5.0" and @theia/editor "1.5.0"

Lets imagine that at the time of this example, the latest released versions are @theia/core "1.9.0" and @theia/editor "1.9.0"

Building this application will put these theia extensions in the application:
@theia/core "1.5.0"	// Pulled in by direct dependency from our 3rd party extension
@theia/core "1.9.0"	// Pulled in by indirect dependency from @theia/editor "1.5.0" which depends on @theia/core "^1.5.0"
@theia/editor "1.5.0"	// Pulled in by direct dependency from our 3rd party extension

This causes the application to have 2 parallel instances of @theia/core which breaks dependency injection.

**Comment by marechal-p** [comment]
So one would have to use yarn resolutions to force the same version to be pulled no matter the range used by dependencies, crossing fingers that packages are still compatible with newer versions. I think this is already what clients have to do so sounds fine to me.

**Comment by marcdumais-work** [comment]
> Since romantic versioning is used within Theia repo, API breakage might be introduced between any version

It's true that breakage can occur without a major release. But, in my understanding, we still kind of use semantic versioning. We're just a bit picky about what we consider a stable API (since everything, more-or-less, is an API): 

https://github.com/eclipse-theia/theia/blob/master/doc/api-management.md

In practice, if one's application breaks and needs update following a framework release, it offers little solace that the break was to a API that's not officially stable. So I do not know that it makes a difference.

**Comment by marechal-p** [comment]
@marcdumais-work in the context of applications solely composed of "main" Theia applications, then yes it makes a difference. If `1.y.0` refactored something (even just internally) then some `1.x.0` packages could become incompatible as they are sometimes coupled to some other's package internal API, and breaking that breaks applications... It might be fair to say that there's some strong coupling between some main extensions, and it is always safer to always use the same version for all of those.
