### ISSUE TITLE
Implement "vscode.ExtensionContext.storageUri" API

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-theia/theia#8883]
### Feature Description:
We need to implement [`vscode.ExtensionContext.storageUri`](https://github.com/microsoft/vscode/blob/dadb18c39e811d343e0dafc88efdf8cf0ffdc2af/src/vs/vscode.d.ts#L5838-L5850) and [`vscode.ExtensionContext.globalStorageUri`](https://github.com/microsoft/vscode/blob/dadb18c39e811d343e0dafc88efdf8cf0ffdc2af/src/vs/vscode.d.ts#L5864-L5874) APIs.
Note that [`vscode.ExtensionContext.storagePath`](https://github.com/microsoft/vscode/blob/dadb18c39e811d343e0dafc88efdf8cf0ffdc2af/src/vs/vscode.d.ts#L5852-L5862) and [`vscode.ExtensionContext.globalStoragePath`](https://github.com/microsoft/vscode/blob/dadb18c39e811d343e0dafc88efdf8cf0ffdc2af/src/vs/vscode.d.ts#L5876-L5885) APIs are implemented in Theia but they are deprecated now in VS Code.

**Comment by bfitzpat** [comment]
Any updates on this one after about 30 days of inactivity over the holidays? @azatsarynnyy ?

**Comment by azatsarynnyy** [comment]
I doubt we will be able to look at it in the coming month.
I marked it as `help wanted`, so if anyone wants to take it - help is more than welcomed.

**Comment by RomanNikitenko** [comment]
Within current issue I added support for the following:
- [`vscode.ExtensionContext.storageUri`](https://github.com/microsoft/vscode/blob/dadb18c39e811d343e0dafc88efdf8cf0ffdc2af/src/vs/vscode.d.ts#L5838-L5850) 
- [`vscode.ExtensionContext.globalStorageUri`](https://github.com/microsoft/vscode/blob/dadb18c39e811d343e0dafc88efdf8cf0ffdc2af/src/vs/vscode.d.ts#L5864-L5874)
- [`vscode.ExtensionContext.extensionUri`](https://github.com/microsoft/vscode/blob/dadb18c39e811d343e0dafc88efdf8cf0ffdc2af/src/vs/vscode.d.ts#L5813)
