### ISSUE TITLE
Horizontal scroll bar under tabs can disappear

### ISSUE THREAD

**Issue by kena0ki** [eclipse-theia/theia#8886]
### Bug Description:
Unlike VS Code, the horizontal scroll bar under the tabs can disappear when opening many files.
(Maybe this is not clearly a bug, but I think this is a bug in terms of usability.)

### Steps to Reproduce:

1. open many files
2. scroll to right
3. scroll bar disappears

Theia (Gitpod):
![theascroll](https://user-images.githubusercontent.com/29003390/102714526-6bae7600-4312-11eb-847d-8ba76d6393d0.gif)

VS Code:
![vscodescroll](https://user-images.githubusercontent.com/29003390/102714534-7bc65580-4312-11eb-9fe4-7be8d02b0d26.gif)

### Additional Information

- Operating System: any (not related)
- Theia Version: 1.9.0

**Comment by colin-grant-work** [comment]
This is particularly problematic when the central panel is split. Then one scroll bar easily extends into (and behind) the other side's tabbar.
