### ISSUE TITLE
file-search in the docker is very slow

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#889]
I am testing it with `typefox/theia` image.

**Comment by svenefftinge** [comment]
Because file access in docker on mac on a mounted folder is super slow.

https://medium.freecodecamp.org/speed-up-file-access-in-docker-for-mac-fbeee65d0ee7

**Comment by tsmaeder** [comment]
@akosyakov sounds like a docker on mac limitation. Unless we want to start doing rsync or something, we should close this one.
