### ISSUE TITLE
Some menu items are not rendered when applying Project Manager extension

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8893]
### Bug Description:
Some of the menu items of the Project Manager extension are not rendered.

### Steps to Reproduce:

1. Install 'Project Manager' extension: https://open-vsx.org/extension/alefragnani/project-manager
2. Create a project in your workspace
3. Ctrl + Shift + p
4. Project Manager: Save Project
5. Give a name to the project and click 'Enter'
6. Go to the Project Manager view on the left side bar
7.  Right click on your project name
8. 2 items in the menu are not rendered, as in the screenshot below

<img width="628" alt="Screen Shot 2020-12-23 at 15 17 19" src="https://user-images.githubusercontent.com/49866055/103000342-8b70b480-4533-11eb-9312-aa8568a865b6.png">

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: master

**Comment by odeliat** [comment]
This extension is no longer available. This issue can be close.

**Comment by vince-fugnitto** [comment]
> This extension is no longer available. This issue can be close.
