### ISSUE TITLE
PreBuild Releases

### ISSUE THREAD

**Issue by feamsr00** [eclipse-theia/theia#890]
Hello,

I'm hoping to explore Theia and try to use and extend it in a cloud/browser environment. Unfortunately, I'm having difficulty with trying to stage its development environment. Instead of asking for support for that (as I really don't need to alter existing code, especially since extensions are supposed to be well isolated AFACT), it would be rather great if I could simply drop the JS package + the TS typings into my project and go from there.

Are there any existing builds\packages like that? Will this be something you'll consider for the 1.0 beta?

Thanks in advance!

**Comment by akosyakov** [comment]
There is a Docker image which is published nightly: https://github.com/theia-ide/theia-apps#theia-docker. All extension packages are published nightly as well. You can compose application package with extensions and use [Theia CLI](https://github.com/theia-ide/theia/blob/master/dev-packages/cli/README.md) to build and start the app:
https://github.com/theia-ide/theia-apps/blob/master/theia-docker/next.package.json

**Comment by vince-fugnitto** [comment]
@feamsr00 closing the issue as it is quite old and there was no subsequent response (either it's been addressed or it is no longer being looked at from your end). Please re-open or create new issues if you ever require additional assistance :)
