### ISSUE TITLE
City Lights Icon package extension partially works 

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8901]
### Bug Description:
The option to apply colors option as file icon theme.
The black & white option works.
The colors option works in vscode.

### Steps to Reproduce:

1. Install City Lights Icon package extension (yummygum.city-lights-icon-vsc) from Open VSX Registry
2. Click on Settings icon -> File Icon Theme -> City Lights Icon Theme - colors

The Theia icons disappear and no colored icons appear.

https://user-images.githubusercontent.com/49866055/103092167-0f43a300-45ff-11eb-8232-6c4b12f3a7e7.mp4

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: master

**Comment by vince-fugnitto** [comment]
@rayakoren I believe it is an error with `open-vsx` itself, when I build and packaged the extension itself it works correctly:

![image](https://user-images.githubusercontent.com/40359487/103576386-0d040300-4ea1-11eb-8e56-4d8fead521f0.png)

![image](https://user-images.githubusercontent.com/40359487/103576412-155c3e00-4ea1-11eb-9b17-2c895394331d.png)

To reproduce, I did the following:

- `git clone git@github.com:Yummygum/city-lights-icons-vsc.git`
- `cd city-lights-icons`
- `npm run build`
- `vsce package`
- copy the `.vsix` into the plugins folder, and start the example application

**Comment by danarad05** [comment]
@rayakoren 
Downloaded extension from https://marketplace.visualstudio.com/items?itemName=Yummygum.city-lights-icon-vsc and it works ok. could you try it out?

**Comment by rayakoren** [comment]
Hi @danarad05 , if the extension was removed from open vsx registry it is no longer relevant. 
Closing this issue, thanks for your help.
