### ISSUE TITLE
Open workspace doesn't work when folder name contain "%20"

### ISSUE THREAD

**Issue by i501378** [eclipse-theia/theia#8903]
### Bug Description:
When trying to open workspace of folder that its name contain "%20" no workspace will be opened.
I try to do the same scenario on vscode and the workspace was opened.

### Steps to Reproduce:

1. Create new folder "my%20test"
2. Select "File" ->"Open workspace..."  and choose folder "my%20test"
3. The workspaces doesn't open and we get the following screen: 
![image](https://user-images.githubusercontent.com/46641136/103093450-09e85780-4603-11eb-8c6c-8f5ea00ef441.png)

### Additional Information

- Operating System: gitpot
- Theia Version: latest

**Comment by msujew** [comment]
This has been resolved by https://github.com/eclipse-theia/theia/pull/9850,
