### ISSUE TITLE
Git History extension doesn't work

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8904]
### Bug Description:
The command is not available in the menu, therefore can't work with the extension.
Works in vscode.

### Steps to Reproduce:

1. Install "Git History" extension (donjayamanne.githistory) from Open VSX Registry
2. Clone any project from git
3. Right click on any file of the project

There's no "Git view file history" command in the menu, the following error appears in the server: 

root ERROR [hosted-plugin: 23642] With stack trace: TypeError: Cannot read property 'exports' of undefined
    at h.<anonymous> (/.theia/extensions/donjayamanne.githistory-0.6.14/extension/dist/src/extension.js:16:47729)
    at Generator.next (<anonymous>)
    at s (/.theia/extensions/donjayamanne.githistory-0.6.14/extension/dist/src/extension.js:16:47160)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Additional Information

- Operating System: mac OS 11.0.1
- Theia Version: master

**Comment by vince-fugnitto** [comment]
@rayakoren before using the extension (given that you are verifying with the example apps present in this repo), perform the following:

- remove `@theia/git` as a dependency
- add the `vscode-builtin-git` plugin to your app: https://open-vsx.org/api/vscode/git/1.49.3/file/vscode.git-1.49.3.vsix
- add the `vscode-builtin-git-ui` plugin to your app: https://open-vsx.org/api/vscode/git-ui/1.49.3/file/vscode.git-ui-1.49.3.vsix

It is likely the `git-history` plugin requires the builtin git support to be present through the plugins (similarly for `gitlens`).

**Comment by rayakoren** [comment]
@vince-fugnitto Thanks for the hints, it works with the builtin plugins.
