### ISSUE TITLE
Theia extension not support React Hook

### ISSUE THREAD

**Issue by shyshywhy** [eclipse-theia/theia#8912]
### Bug Description:

Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (:3000/19.bundle.js:24764)
    at Object.useState (:3000/0.bundle.js:1518)
    at TestButton (:3000/27.bundle.js:235)
    at renderWithHooks (bundle.js:84869)
    at mountIndeterminateComponent (bundle.js:87548)
    at beginWork (bundle.js:88662)
    at HTMLUnknownElement.callCallback (bundle.js:70254)
    at Object.invokeGuardedCallbackDev (bundle.js:70303)
    at invokeGuardedCallback (bundle.js:70358)
    at beginWork$1 (bundle.js:93269)

### Steps to Reproduce:

@injectable()
export class EmulatorWidget extends ReactWidget {

    static readonly ID = 'emulator:widget';
    static readonly LABEL = 'EmulatorWidget';

    @postConstruct()
    protected async init(): Promise < void> {
        this.id = EmulatorWidget.ID;
        this.title.label = EmulatorWidget.LABEL;
        this.title.caption = EmulatorWidget.LABEL;
        this.title.closable = true;
        this.title.iconClass = 'fa fa-window-maximize'; // example widget icon.
        this.update();
    }

    protected render(): React.ReactNode {
        return <div id='widget-container'>
            <TestButton />
        </div>
    }

    protected displayMessage(): void {
    }
}

function TestButton() {
    const [count, setCount] = useState(0);
    return (
        <div>
        <p>You clicked {count} times</p>
        <button onClick={() => setCount(count + 1)}>
        </button>
        </div>
    );
}

### Additional Information

- Operating System: macOS 10.15.6 (19G2021)
- Theia Version: @theia/core@^1.9.0

**Comment by jacqueswho** [comment]
EmulatorWidget is a class component, you cant use class components with hooks. only functions can be used with hooks

**Comment by balajiv113** [comment]
Theia already has a dependency on React. May be check if you have 2 different version of React in your setup.

ReactWidget is neither a React class or functional component. ReactWidget provides support for mounting react component with the Widget provided by phospherjs.

The below repo contains example for using React Hooks within widget. 
https://github.com/balajiv113/theia-hooks-sample

**Refer**
- theia-hello-world-extension/src/browser/theia-hello-world-component.tsx for simple hook component
- theia-hello-world-extension/src/browser/theia-hello-world-extension-widget.tsx for usage of the above component

**Comment by aztack** [comment]
try this:
edit `webpack.config.js` in `browser-app` folder, add following lines:

```js
const path = require('path');
config.resolve.alias = {
    react: path.resolve(__dirname, '..', 'node_modules', 'react')
};
```
