### ISSUE TITLE
What might cause 503 error

### ISSUE THREAD

**Issue by habibali95** [eclipse-theia/theia#8944]
I'm deploying Theia using Kubernetes, randomly I get the error 503 after the readiness probe passed with success. but after a refresh after a few seconds sometimes more than 5 the 503 disappear.
This is the current configuration 
        readinessProbe:
          tcpSocket:
            port: 3000
          successThreshold: 10
          failureThreshold: 20
          periodSeconds: 1
I tried other configs such as httpGet.
does importing the project has to do with the 503? knowing that the project size might be higher than 1GB.
Any help would be really apperciated.

**Comment by vince-fugnitto** [comment]
@habibali95 thank you for your discussion, do you mind closing the issue and reporting the question in the appropriate channel?
- https://github.com/eclipse-theia/theia/discussions or 
- https://community.theia-ide.org/

We have an issue template, and we advise users to open questions in the appropriate location (generally issues are for bugs or feature requests):

<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/104473880-706def00-558b-11eb-8adf-951d4b90d04f.png)

</div>

Note: I'd convert the issue myself to a discussion but the option is currently unavailable until `github` fixes the implementation.
