### ISSUE TITLE
Clicking through function takes you to top of file first

### ISSUE THREAD

**Issue by danieltomasku** [eclipse-theia/theia#8955]
### Bug Description:
Ctrl + clicking on a function takes you to the top of the file and then to the location of the function definition, instead of taking you directly to the location of the function definition. This causes problems when using the Go > Back functionality since it takes you to the top of the file, not your previous location. You have to do Go > Back one more time before you go to your actual previous location.

![theia-click-through-bug](https://user-images.githubusercontent.com/14880569/104759033-e8235180-5724-11eb-85c3-a18f6608e8c4.gif)

Note that jumping to a function definition within a file works as expected. This seems to only occur when jumping to a different file.

### Steps to Reproduce:

1. Ctrl + click on a function that opens up a new file
2. Use Go > Back
3. Notice that it sends you to the top of the file, not the previous location.

### Additional Information

- Operating System: RHEL7
- Theia Version: 1.9.0

**Comment by vince-fugnitto** [comment]
The unit-test for it seems to pass (we include the `range` as part of the location), so it might be that it is not respected when actually opening the editor:

https://github.com/eclipse-theia/theia/blob/31d47498d52af4bfc129df2cba16e49363e819b7/packages/editor/src/browser/navigation/navigation-location-service.spec.ts#L110-L131

**Comment by colin-grant-work** [comment]
It looks like the test is right, but the way editor add new navigation locations to the stacks is to blame. It seems that no matter how you open an editor - I've tried code navigation and the search-in-workspace widget - the top of the file is added to the navigation stack.

**Comment by colin-grant-work** [comment]
[This code](https://github.com/eclipse-theia/theia/compare/master...colin-grant-work:bugfix/nav-stack-on-open) seems to solve the problem, but it isn't very clean. The data flow is currently a bit muddled, and I haven't found one place to intervene that prevent the initial position from being registered with the service that tracks the location stack - the events handling new editors are lumped in with events handling changes of editor.
