### ISSUE TITLE
Golang debugger reports "Cannot read property 'name' of null" when inspecting map contents

### ISSUE THREAD

**Issue by yeungalan0** [eclipse-theia/theia#8960]
### Bug Description:
First off, I just started using Gitpod/Theia, and am really enjoying the experience thus far! Thanks for all the hard work and hours you all have put into these projects!

When using the default Golang Theia debugger and trying to inspect a maps memory values, I can only see the first key/value pair, and then I see the error "Cannot read property 'name' of null" and no other key/value pairs are available for the map.

I pulled in the exact same code locally on VScode, and could not reproduce this issue.

### Steps to Reproduce:

1. Start a Gitpod environment using the project [https://github.com/yeungalan0/misc/tree/golang-debugger-issue](https://github.com/yeungalan0/misc/tree/golang-debugger-issue)
2. Open `test.go`
3. Set a break point at the `fmt.Printf` line
4. Run the file using the debugger
5. Try to inspect the memory contents of the maps

### Additional Information
- Operating System: Gitpod
- Theia Version: Not sure how to figure this out in Gitpod :(

![theia_golang_debugger_bug](https://user-images.githubusercontent.com/3821187/104815084-ae5b5500-57cf-11eb-859f-c43ada1bf23b.png)

**Comment by balajiv113** [comment]
@vince-fugnitto - Theia Open VSX supports two version of Go (0.14.3 & 0.22.0). 

- 0.22.0 is not working due monaco 0.21.0 upgrade (Reference https://github.com/eclipse-theia/theia/issues/8752)
- In 0.14.3 version the Go plugin returns null for alternate map values (Relevant Go Plugin issue https://github.com/golang/vscode-go/issues/199)
  We can fix 0.14.3 by doing undefined check for variable before accessing variable.name. Note 0.14.3 is working fine in VS Code
  https://github.com/eclipse-theia/theia/blob/3b5ebfd109164807f5374e085ba5cea6933eec79/packages/debug/src/browser/console/debug-console-items.tsx#L107-L109
 I tried with manually installing 0.19.0 Go Plugin and can confirm this usecase is working fine.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto - Theia Open VSX supports two version of Go (0.14.3 & 0.22.0).
> 
> * 0.22.0 is not working due monaco 0.21.0 upgrade (Reference #8752)
> * In 0.14.3 version the Go plugin returns null for alternate map values (Relevant Go Plugin issue [golang/vscode-go#199](https://github.com/golang/vscode-go/issues/199))
>   We can fix 0.14.3 by doing undefined check for variable before accessing variable.name. Note 0.14.3 is working fine in VS Code
>   https://github.com/eclipse-theia/theia/blob/3b5ebfd109164807f5374e085ba5cea6933eec79/packages/debug/src/browser/console/debug-console-items.tsx#L107-L109
>   
>   I tried with manually installing 0.19.0 Go Plugin and can confirm this usecase is working fine.

@balajiv113 thank you for investigating the issue, I'm not sure what the best solution is at the moment. The issue as you described is a problem/bug with the `golang` debug extension itself, and I'm not sure we should change/patch our debug logic to accommodate it.

**Comment by balajiv113** [comment]
Ya correct. Thats was the same doubt i had. Only reason i could think of fixing is VSCode works fine even with 0.14.3. Which means that VSCode is able to handle null values unlike us.

**Comment by hyangah** [comment]
v0.14.3 was released before the extension's migration to golang project, and very outdated. I'd recommend [v0.20.2](https://github.com/golang/vscode-go/releases/tag/v0.20.2) if vscode.Uri.joinPath is the only issue - its use was introduced in v0.21.0.

**Comment by vince-fugnitto** [comment]
I verified the issue using the `golang.go` extension at version `v0.23.0` (latest compatible) and it works well:

![image](https://user-images.githubusercontent.com/40359487/119662759-bb342900-bdff-11eb-94d8-8e11b1ccd679.png)

Since [vscode.Uri.joinPath](https://github.com/eclipse-theia/theia/pull/9422) is now supported I believe the issue can be closed :+1: 
Please comment and we can re-open the issue if its not the case.
