### ISSUE TITLE
Generating error messages for failed commands errors out

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#8974]
### Bug Description:

If a command fails to run, and one of the arguments to the handler cannot be stringified, the console shows an error about a failure of JSON.stringify, rather than a failure of the command.

### Reproduction
1. Create a command with no handler
2. Make that command take a circular object (e.g. a `Widget`, which has a `.parent` field) as an argument.
3. Invoke the command
4. Check the console, see that you get an error about `JSON.stringify` rather than a message about the command that failed.

### Additional Information

https://github.com/eclipse-theia/theia/blob/47be972b48ac26fcd117353bf7841f9e41adb866/packages/core/src/common/command.ts#L290-L301

The problem is the invocation of `JSON.stringify` on args that can be `any`, including something not stringifiable.

- Operating System: RHEL
- Theia Version: 0.9.0 (`master`)

**Comment by kittaakos** [comment]
Related: https://github.com/eclipse-theia/theia/issues/8035#issuecomment-645400605

**Comment by colin-grant-work** [comment]
@kittaakos, thanks for linking some background. It looks like there's some debate about whether it's even worth showing the `args` at all.

I'd propose something like this:

```
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    protected getUnhandledCommandMessage(args: any[], commandId: string): string {
        let argsMessage = '';
        if (args.length) {
            try {
                argsMessage = ` (args: ${JSON.stringify(args)})`;
            } catch {
                argsMessage = ` (args: ${JSON.stringify(args.map(arg => typeof arg?.constructor?.name === 'string'
                    ? arg.constructor.name
                    : typeof arg
                ))})`;
            }
        }
        const errorMessage = `The command '${commandId}' cannot be executed. There are no active handlers available for the command.${argsMessage}`;
        return errorMessage;
    }
```
It's fair number of lines just to get the message, but it should be safe and reasonably informative.

**Comment by kittaakos** [comment]
> I'd propose something like this:

Feel free to drop `args` from the log and we are done.
