### ISSUE TITLE
Support for `.vscode/extensions.json`

### ISSUE THREAD

**Issue by Kreyren** [eclipse-theia/theia#8982]
Expecting theia on gitpod to prompt installation of these extensions on startup (like vscode does).

Example file:

```json
{
    "recommendations": [
        "ms-azuretools.vscode-docker",
        "exiasr.hadolint",
        "timonwong.shellcheck",
        "coenraads.bracket-pair-colorizer-2",
        "markwylde.vscode-filesize",
        "oderwat.indent-rainbow",
        "stephen-riley.regexworkbench",
        "medo64.render-crlf",
        "gruntfuggly.todo-tree",
        "vscodevim.vim",
        "slenderman00.vsirc",
        "genuitecllc.codetogether",
        "streetsidesoftware.code-spell-checker",
        "aaron-bond.better-comments",
        "tamasfe.even-better-toml"
    ]
}
```

**Comment by Kreyren** [comment]
ah it does that already.. my fault!

**Comment by Kreyren** [comment]
My fault again, that was vscode. Theia doesn't have this behavior.

**Comment by colin-grant-work** [comment]
@vince-fugnitto, I think I can take this one. Do you think it should be its own package - pretty light, but that would parallel `preferences`, `tasks`, `debug`/`launch` - or should it be put in one of the plugin-related packages?

**Comment by vince-fugnitto** [comment]
@colin-grant-work I have not thought too much about it yet, but perhaps `vsx-registry` would be sufficient as a location? In the end we would need to use the registry api to fetch these extensions by `id`.
