### ISSUE TITLE
Is it possible to use java  or kotlin  to develop extensions?

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [eclipse-theia/theia#8984]
Is it possible to use java  or kotlin  to develop extensions?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
The original eclipse loyal fans will definitely look forward to this feature, because most of them are javaers. It also benefits the plug-in market

**Comment by kittaakos** [comment]
No, it's not possible. Duplicate of https://github.com/eclipse-theia/theia/issues/3396
