### ISSUE TITLE
terminal: garbage characters when reloading the application

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#8990]
### Bug Description:

The following is reproducible in an remote environment with latency. 
Upon reloading the application, the terminal displays garbage characters (ex: "^[[2;2R").

_Captured from Gitpod_:
<div align='center'>

![image](https://user-images.githubusercontent.com/40359487/105878081-a3be6e00-5fce-11eb-85b5-0309ebf0eb66.png)

</div>

### Steps to Reproduce:

1. open https://gitpod.io/#github.com/eclipse-theia/theia, and start the `theia` instance
2. open a terminal
3. perform `ls -lh` in the terminal
4. start `vim` in the terminal (`vi` command)
5. quit `vim` (<kbd>esc</kbd>, input `:q`, and press <kbd>enter</kbd>)
6. reload the application, and notice the garbage output

### Additional Information

- Theia Version: 4204297
- There are many issues online with the `^[[2;2R` string from vim, but I do not want to pollute their issues with a reference to `eclipse-theia`.

**Comment by dhuebner** [comment]
I see the same using gitpod. Even the Title is corrupted:
![Bildschirmfoto 2021-03-26 um 13 57 16](https://user-images.githubusercontent.com/454322/112634793-511cf900-8e3b-11eb-8dae-dfb71f005ab4.png)

**Comment by vince-fugnitto** [comment]
> I see the same using gitpod. Even the Title is corrupted:

Correct, that's what the original screenshot was from.

**Comment by dhuebner** [comment]
@vince-fugnitto 
This seem to happen because a plain `sh` is used. If you type `/bin/bash` in the broken Terminal all looks fine.

**Comment by dhuebner** [comment]
We could set `SHELL=/bin/bash` in  `.gitpod.dockerfile` to have a better Terminal at least for theia developers

**Comment by vince-fugnitto** [comment]
> We could set `SHELL=/bin/bash` in `.gitpod.dockerfile` to have a better Terminal at least for theia developers

@dhuebner would you like to prepare a pull-request to try?

**Comment by dhuebner** [comment]
@vince-fugnitto 
Will do!

**Comment by dhuebner** [comment]
@vince-fugnitto 
Seem to work fine (tested with gitpod)

**Comment by marcdumais-work** [comment]
Thanks @dhuebner . In an internal product, I still see this problem or very similar. The `$SHELL` environment variable is set and points to `bash`. Do you have an idea of other potential causes for the symptoms?

**Comment by dhuebner** [comment]
It just guessing, but overall I assume that this is not bash vs. sh problem but the prompt configuration, if you have a plain prompt `$` you will probably get the corrupt control characters. At least using VS code in gitpod I have the same symptoms (prompt is `$`) but using VS Code under OSX where `sh` have `sh-3.2$` prompt it works fine. Might also be a better `sh` version.

However, in your internal product do `echo $PS1` to see the current settings and change it to something using `\u` or `\w` maybe it helps
