### ISSUE TITLE
'when' clause doesn't work for views

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#8992]
'when' clause for views doesn't work.
Assigning 'when' to false doesn't hide the view.
Works in vscode.

### Steps to Reproduce:

1. Create the simplest vscode extension, for example: https://code.visualstudio.com/api/get-started/your-first-extension.
2. Add the following to your package.json inside "contributes": 
```json
 "views": {
	"explorer": [
		{
	            "id": "testview",
	            "name": "MY VIEW",
	            "when": "false"
		}
	]
  },
```
3. Press Ctrl+Shift+p 
4. Hosted Plugin: Start Instance
5. Select your project

See that the view "MY VIEW" appears on the left side even though it is marked as "when": "false" and should be hidden.

### Additional Information

https://user-images.githubusercontent.com/49866055/105988702-b7d69e00-60a8-11eb-8256-cc52762736e6.mp4

- Operating System: mac os 11.0.1
- Theia Version: master

**Comment by omkar07** [comment]
@amiramw , I'm facing a similar issue with latest theia. is this issue resolved? What's the solution?
