### ISSUE TITLE
User scoped preferences are incorrectly read from postConstruct method

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#8993]
### Bug Description:

If I want to read user scoped preferences from an `init` (annotated with `@postConstruct`) method, it returns with the default value.

The problem is here: https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L59

This 👆 resolves too late, and the user scoped preferences are not found. The model is not (yet) valid 

https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L83

when reading the preferences

https://github.com/eclipse-theia/theia/blob/42042974c59f148974de5e8fd90cba7222cee82f/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L108

### Steps to Reproduce:

1. Start the app, no matter you have a user scoped settings file or not.
2. Open an editor and run `Set editor.fontSize to 20 in user preferences.` You can see the font size has changed.
3. Verify it by running the `Get the editor.fontSize from the preferences` command. It should show `20`.
4. Refresh the app, you will see `editor.fontSize` `12` from the `init` method, run `Get the editor.fontSize from the preferences` again, you will see `20`.

Here is the branch with the example: https://github.com/eclipse-theia/theia/compare/master...kittaakos:broken-user-scoped-pref-from-init?expand=1

### Additional Information

- Operating System:
- Theia Version:

**Comment by kittaakos** [comment]
Here is a workaround:
```ts
@inject(FrontendApplicationStateService)
protected readonly appStateService: FrontendApplicationStateService;

@postConstruct()
protected async init(): Promise<void> {
    await this.appStateService.reachedState('ready');
    // now you can get the preferences even with user scope
}
```

**Comment by tsmaeder** [comment]
I've proposed using models only for changes to the preferences here: https://github.com/eclipse-theia/theia/issues/7426 not sure it would help this exact case, though.

**Comment by colin-grant-work** [comment]
The `PreferenceService` has a `.ready` promise that should probably not resolve until the various providers have read their preferences and can respond correctly to queries, but at the moment it seems to be resolving too early:

![image](https://user-images.githubusercontent.com/62660806/114623415-dcd4b900-9c74-11eb-866a-0990e5baad3a.png)

Perhaps @tsmaeder's approach of speeding up startup by not relying on `monaco` in the first instance, combined with only resolving the `.ready` promises when the file has been read (or its absence has been determined) would make the `PreferenceService.ready` promise more meaningful.
