### ISSUE TITLE
vscode.workspace.workspaceFile returns undefined

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#8994]
### Bug Description:
I have a multi-root workspace with a workspace config file and my test vscode extension where I try to take the location to current workspace file.  

**Expected behavior:**
`vscode.workspace.workspaceFile` returns the location of the workspace file, like: `/some/path/someTestWorkspace.theia-workspace`

**Actual behavior:**
`vscode.workspace.workspaceFile` returns `undefined` 

### Steps to Reproduce:

1. Clone my test vs code extension: https://github.com/RomanNikitenko/vscode-test-extension.git
2. Build it and copy to `plugins` folder of the `theia`  
3. Open a multi-root workspace from a config file for testing.
4. `F1 => Test 'vscode.workspace.workspaceFile'`

The command should just display a notification with info about path to the current workspace config file.

### Additional Information

- Operating System: Fedora 31
- Theia Version: 42042974c59f148974de5e8fd90cba7222cee82f

**Comment by JonasHelming** [comment]
I tried to build your example extension, but it fails for me. Could you check whether it builds for you and maybe add the TypeScript version you use to the Readme?

../node_modules/@types/react-virtualized/dist/es/WindowScroller.d.ts:34:28 - error TS2304: Cannot find name 'window'.

34     scrollElement?: typeof window | Element;

**Comment by RomanNikitenko** [comment]
I checked the extension from scratch, so clone, build using yarn, copy to `/plugins` folder, start `theia` and test the corresponding command - it works well for me.
About typescript version - I think it should work fine with the [corresponding version](https://github.com/RomanNikitenko/vscode-test-extension/blob/ee297ff67dcd44110381fa7f0fda1efd13427b3e/package.json#L69) from the `devDependencies` section.
