### ISSUE TITLE
vscode-java-debug Error: It is not possible to provide debug adapter executable.

### ISSUE THREAD

**Issue by joho1001** [eclipse-theia/theia#9012]
### Bug Description:
 
```
root ERROR Error starting the debug session Error: It is not possible to provide debug adapter executable.
    at DebugExtImpl.<anonymous> (/home/NETZAGENTUR/josef/git/theia/packages/plugin-ext/lib/plugin/node/debug/debug.js:709:39)
    at step (/home/NETZAGENTUR/josef/git/theia/packages/plugin-ext/lib/plugin/node/debug/debug.js:33:23)
    at Object.next (/home/NETZAGENTUR/josef/git/theia/packages/plugin-ext/lib/plugin/node/debug/debug.js:14:53)
    at fulfilled (/home/NETZAGENTUR/josef/git/theia/packages/plugin-ext/lib/plugin/node/debug/debug.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

### Steps to Reproduce:

1. git clean -fxd; yarn; yarn run start:electron or yarn run start:browser
2. manually install redhat-java@0.74 and vscode-java-debug@0.30 extensions
3. configure debugging configuration
{  "version": "0.2.0", "configurations":  [ 
      { "type": "java", "name": "Debug localhost", "request": "attach", "hostName": "localhost", "port": 9999}]}

when opening a java source file, theia starts a java process, code completion aka intellisense also works perfectly.
so, redhat-java extension seems to work.
but vscode-java-debug seems not to start up correctly.

- Operating System: Ubuntu 20.04
- Theia Version: master branch, v1.0.10, v1.0.9

**Comment by danarad05** [comment]
@joho1001 - opened PR #9035 for this issue. I'm not sure it solves all issues and renders java debugging fully operational on Theia but managed to run basic debug on java project - also not sure that Theia is the most comfortable IDE for it but for starters let's see if it works for you.
Thanks

@vince-fugnitto  @amiramw

**Comment by danarad05** [comment]
As per @vince-fugnitto' request, split #9035 to 2 separate PR: #9048 #9049. closed #9035.

**Comment by amiramw** [comment]
@danarad05 can we close this issue?

**Comment by danarad05** [comment]
@amiramw  As #9048 @9049 are merged - yes.

**Comment by amiramw** [comment]
@joho1001 feel free to reopen if we miss something
