### ISSUE TITLE
Build fails when downloading built-ins

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#9014]
### Bug Description:
A build of master fails on the step where the built-ins are downloaded with these messages:

<details>

```
x vscode-builtin-configuration-editing: failed to download with: 404 Not Found
x vscode-builtin-emmet: failed to download with: 404 Not Found
x vscode-builtin-csharp: failed to download with: 404 Not Found
x vscode-builtin-go: failed to download with: 404 Not Found
x vscode-builtin-cpp: failed to download with: 404 Not Found
x vscode-builtin-handlebars: failed to download with: 404 Not Found
x vscode-builtin-grunt: failed to download with: 404 Not Found
x vscode-builtin-bat: failed to download with: 404 Not Found
x vscode-builtin-scss: failed to download with: 404 Not Found
x vscode-builtin-fsharp: failed to download with: 404 Not Found
x vscode-builtin-coffeescript: failed to download with: 404 Not Found
x vscode-builtin-pug: failed to download with: 404 Not Found
x vscode-builtin-objective-c: failed to download with: 404 Not Found
x vscode-builtin-debug-auto-launch: failed to download with: 404 Not Found
x vscode-builtin-clojure: failed to download with: 404 Not Found
x vscode-builtin-sql: failed to download with: 404 Not Found
x vscode-builtin-python: failed to download with: 404 Not Found
x vscode-builtin-shellscript: failed to download with: 404 Not Found
x vscode-builtin-ruby: failed to download with: 404 Not Found
x vscode-builtin-rust: failed to download with: 404 Not Found
x vscode-builtin-shaderlab: failed to download with: 404 Not Found
x vscode-builtin-theme-defaults: failed to download with: 404 Not Found
x vscode-builtin-theme-monokai-dimmed: failed to download with: 404 Not Found
x vscode-builtin-theme-abyss: failed to download with: 404 Not Found
x vscode-builtin-theme-tomorrow-night-blue: failed to download with: 404 Not Found
x vscode-builtin-typescript-language-features: failed to download with: 404 Not Found
x vscode-builtin-npm: failed to download with: 404 Not Found
x vscode-builtin-css: failed to download with: 404 Not Found
x vscode-builtin-theme-monokai: failed to download with: 404 Not Found
x vscode-builtin-theme-kimbie-dark: failed to download with: 404 Not Found
x vscode-builtin-theme-solarized-dark: failed to download with: 404 Not Found
x vscode-builtin-yaml: failed to download with: 404 Not Found
x vscode-builtin-theme-red: failed to download with: 404 Not Found
x vscode-builtin-typescript: failed to download with: 404 Not Found
x vscode-builtin-theme-quietlight: failed to download with: 404 Not Found
x vscode-builtin-vb: failed to download with: 404 Not Found
x vscode-builtin-xml: failed to download with: 404 Not Found
x vscode-builtin-icon-theme-seti: failed to download with: 404 Not Found
x vscode-builtin-swift: failed to download with: 404 Not Found
x vscode-builtin-docker: failed to download with: 404 Not Found
x vscode-builtin-lua: failed to download with: 404 Not Found
x vscode-builtin-r: failed to download with: 404 Not Found
x vscode-builtin-ini: failed to download with: 404 Not Found
x vscode-builtin-javascript: failed to download with: 404 Not Found
x vscode-builtin-less: failed to download with: 404 Not Found
x vscode-builtin-java: failed to download with: 404 Not Found
x vscode-builtin-make: failed to download with: 404 Not Found
x vscode-builtin-markdown: failed to download with: 404 Not Found
x vscode-builtin-merge-conflict: failed to download with: 404 Not Found
x vscode-builtin-powershell: failed to download with: 404 Not Found
x vscode-builtin-groovy: failed to download with: 404 Not Found
x vscode-builtin-hlsl: failed to download with: 404 Not Found
x vscode-builtin-log: failed to download with: 404 Not Found
x vscode-builtin-perl: failed to download with: 404 Not Found
x vscode-builtin-markdown-language-features: failed to download with: 404 Not Found
x vscode-builtin-jake: failed to download with: 404 Not Found
x vscode-builtin-gulp: failed to download with: 404 Not Found
x vscode-builtin-razor: failed to download with: 404 Not Found
```

</details>

I suspect some extension versions have been purged from open-vsx

### Steps to Reproduce:

1. git clone https://github.com/eclipse-theia/theia
2. cd theia
3. yarn
4. Observe: error at the last build step

### Additional Information
Using the browser to download a missing built-in extension (`https://open-vsx.org/api/vscode/java/1.44.2/file/vscode.java-1.44.2.vsix`) shows that the extension is indeed missing. 

- Operating System: Windows
- Theia Version: master

**Comment by RomanNikitenko** [comment]
+1 
I see the same behavior 

![theia_errors](https://user-images.githubusercontent.com/5676062/106443009-ad3f4e80-6484-11eb-9163-7ce7f8374d82.png)

**Comment by tsmaeder** [comment]
The oldest version of the built-ins I find in open-vsx is 1 .45.1.

**Comment by kittaakos** [comment]
I have noticed it as well. If I got it correctly from an internal chat, the _Eclipse Publisher Agreement_ is mandatory the extensions. All the extensions that were not signed, are not available anymore although they're still in the Azure blob.

For example, https://open-vsx.org/api/vscode/cpp/1.44.2/file/vscode.cpp-1.44.2.vsix was missing for me, but it's still under https://openvsxorg.blob.core.windows.net/resources/vscode/cpp/1.44.2/vscode.cpp-1.44.2.vsix

**Comment by spoenemann** [comment]
@marcdumais-work could it be that version `1.44.2` was published to open-vsx.org with your own GitHub account? The grace period for signing the new Publisher Agreement has expired now, and all extension versions that are not backed by a signed Publisher Agreement have been disabled (they are no longer visible). If so, they can be reactivated by signing the agreement. Alternatively, we can delete those versions and republish them.

**Comment by marcdumais-work** [comment]
> Alternatively, we can delete those versions and republish them.

Let's try that. I'll setup, make sure this version still builds and report back

**Comment by marcdumais-work** [comment]
v1.44.2 looks to still build ok. 

@spoenemann How do we proceed? I think I can use `vscode-builtin-extensions`'s CI to publish a new set of builtins of that version, if the old ones have been removed first. Do you figure `ovsx` will let this happen, with newer versions already existing?

**Comment by marcdumais-work** [comment]
`1.45.1` looks to be the earlier version what was published by the `open-vsx` bot user. A quick fix would be to update to that version, the built-ins that previously were version `1.44.2`

**Comment by marcdumais-work** [comment]
The immediate build problem for our example application was fixed by switching to a slightly newer version of the vscode-builtins. 

To restore the v1.44.2 for others who may be using it, we can still re-publish v1.44.2 and are very close. I think we just need to remove the original extensions of that version from open-vsx.org and re-trigger the publish. See: 
https://github.com/theia-ide/vscode-builtin-extensions/issues/41#issuecomment-771272719

@spoenemann WDYT?

**Comment by spoenemann** [comment]
Yes I can remove those versions (and also all older versions?)

I would do that for all extensions in the `vscode` namespace. @marcdumais-work any objections?

The extensions can be listed here:
https://open-vsx.org/api/vscode

**Comment by marcdumais-work** [comment]
@spoenemann yes, please proceed at your conveinence.

**Comment by marcdumais-work** [comment]
> and also all older versions?

Yes, I think so. I guess any that were published by me (under my GH user)

**Comment by spoenemann** [comment]
I deleted `1.44.2` and older versions of all built-in extensions.

**Comment by tsmaeder** [comment]
@spoenemann @marcdumais I would be interested to know what the policy should be going forward with respect to old version of the built-ins in open-vsx.

**Comment by spoenemann** [comment]
Generally we want to keep all old versions. We might consider deleting very old `next` versions at some point to reduce the cloud storage costs for the Eclipse Foundation.

**Comment by marcdumais-work** [comment]
> I deleted `1.44.2` and older versions of all built-in extensions.

Thanks Miro. I will attempt to republish builtins `1.44.2` and markdown-language-features `1.39.2` that many were using and is a rare known to work. 
see 
- https://github.com/eclipse-theia/vscode-builtin-extensions/issues/41
- https://github.com/eclipse-theia/vscode-builtin-extensions/issues/14#issuecomment-772627682

**Comment by marcdumais-work** [comment]
> I will attempt to republish builtins `1.44.2` and markdown-language-features `1.39.2` that many were using and is a rare one known to work.
> see
> 
> * [eclipse-theia/vscode-builtin-extensions#41](https://github.com/eclipse-theia/vscode-builtin-extensions/issues/41)
> * [eclipse-theia/vscode-builtin-extensions#14 (comment)](https://github.com/eclipse-theia/vscode-builtin-extensions/issues/14#issuecomment-772627682)

This has been done
