### ISSUE TITLE
[dev-meeting] Bluejeans meeting not working

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia#9019]
https://bluejeans.com/242345344

Worked last week but no longer. 

![image](https://user-images.githubusercontent.com/25749063/106619066-31094180-653e-11eb-9b1e-84e354052932.png)

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by marcdumais-work** [comment]
cc: @benoitf @tsmaeder

**Comment by benoitf** [comment]
you can use another ID: https://bluejeans.com/912656395 or we could switch to google meet as well as we have both solutions at Red Hat

**Comment by brianking** [comment]
Where is today's call happening?

**Comment by marcdumais-work** [comment]
There was : someone updated the agenda with a temporary meeting link. Artem has volunteered to look into this, probably provide a new meeting link.

**Comment by azatsarynnyy** [comment]
Yeah, It seems the meeting owner has deleted the meeting from their Blue Jeans account. Probably @gorkem :slightly_smiling_face: 
I'll create a new meeting from my account and update the link in all the known places: Theia wiki, Eclipse Cloud Dev Tools Community calendar, etc.

**Comment by brianking** [comment]
Thanks. You may not have rights to update the cal invite for everyone, so if not send the link over to me and I'll do it.

**Comment by azatsarynnyy** [comment]
The new link is https://bluejeans.com/719612209
I've updated the wiki page https://github.com/eclipse-theia/theia/wiki/Dev-Meetings
@brianking could you update the `Theia Weekly Dev Meeting` event in the `Eclipse Cloud Dev Tools Community` calendar?

**Comment by marcdumais-work** [comment]
@brianking for next week's meeting, Colin And Ken from Ericsson will demo an enhancement they've done to the @theia/cpp-debug extension, related to the memory view, that they are considering upstreaming. If you know of people/companies that have an interest in C/C++ debug, they might be interested in that item. 

FYI that extension is a Theia-specific version of [cdt-gdb-vscode](https://github.com/eclipse-cdt/cdt-gdb-vscode) - we re-use their Debug Adapter. It could be a consideration, in the future, to "merge" the two, e.g. us (interested parties) contributing to CDT's extension whatever we have an edge-on, and collaborating on that component, going forward.

**Comment by brianking** [comment]
@azatsarynnyy I've updated the invite. Please check next week's invite to verify it has propogated to everyone.

@marcdumais-work An Embedded SIG under the ECD Tools WG is starting up soon, I am sure the members would be very interested in this. There is no single place to contact them (yet), but I'll spread the word.
Theia Blueprint might be interested in this. cc/ @JonasHelming 
There is a probably a better place to discuss this than this issue :)

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy I've updated the invite. Please check next week's invite to verify it has propogated to everyone.

Thank you @brianking! I've checked it - everything is ok.
