### ISSUE TITLE
Support for vscod{e,ium} workspaces

### ISSUE THREAD

**Issue by Kreyren** [eclipse-theia/theia#9030]
https://code.visualstudio.com/docs/editor/multi-root-workspaces

TLDR: `workspace.code-workspace` file that opens directories in the workspace and allows global configuration of the editor and installation of extensions

**Comment by vince-fugnitto** [comment]
@Kreyren thank you for the issue, the framework already supports multi-root workspaces, and allows `{name}.code-workspace` files to be opened.

**Comment by Kreyren** [comment]
@vince-fugnitto Can you elaborate how? Theia in gitpod doesn't seem to recognize the workspace files on my end.

**Comment by vince-fugnitto** [comment]
@Kreyren you can verify on `master` by building this [repository's sources](https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#quick-start). 

The framework supports opening both `.code-workspace` and `.theia-workspace` files by executing the command `Open Workspace...` and opening the corresponding file (which denotes the root folders).


Here's an example:

<img width="1218" alt="Screen Shot 2021-02-05 at 1 20 40 PM" src="https://user-images.githubusercontent.com/40359487/107073137-f957ff00-67b4-11eb-9055-8397cb8b8f3a.png">


And the corresponding `workspace.code-workspace` file I opened:

```json
{
  "folders": [
    {
      "path": "../workspace/theia"
    },
    {
      "path": "../workspace/vscode"
    }
  ],
  "settings": {
    "typescript.tsdk": "node_modules/typescript/lib"
  }
}

```

**Comment by Kreyren** [comment]
ah you are right it works, my bad! x.x Was looking for notification and didn't know about the drop-down option
