### ISSUE TITLE
Unable to create frontend TheiaPlugin

### ISSUE THREAD

**Issue by thegecko** [eclipse-theia/theia#9046]
### Bug Description:

There seems to be support for writing a TheiaPlugin (not vscode) to run in the `frontend` context by specifying the entrypoint in `package.json`:

```json
  ...
  "theiaPlugin": {
    "frontend": "lib/frontend/module.js"
  },
  ...
```

However I'm unable to get this to work in a browser (backend modules are fine)

### Steps to Reproduce:

Build a plugin with a frontend entrypoint along these lines:

```typescript
import * as theia from '@theia/plugin';

export const start = async (_context: theia.PluginContext) => {
    try {
        console.log('frontend');
    } catch (error) {
        console.log(error);
    }
};
...
```

On theia 1.4 this threw an error specifying it is unsupported.

On Theia 1.10.0 a popup is seen which says:

```
Activating extension 'test-plugin' failed: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3000/hostedPlugin/Some_Company_test_plugin/lib/frontend' failed to load.
```

### Additional Information

- Operating System: MacOS (Chrome)
- Theia Version: 1.10.0

cc @tsmaeder

**Comment by RomanNikitenko** [comment]
maybe related to https://github.com/eclipse-theia/theia/issues/6601

**Comment by tsmaeder** [comment]
@RomanNikitenko no, I made a fix for the browser case a while back and I recently tested it. @thegecko mentioned he was using the browser example in yesterday's community call.

**Comment by tsmaeder** [comment]
@thegecko do you have a built example you could share? Just wondering if packaging has anything to do with it.

**Comment by tsmaeder** [comment]
I just tried with https://github.com/eclipse/che-theia-samples/tree/master/samples/hello-world-frontend-plugin against Theia master and it works just fine.
1. yarn
2. copy the resulting theia plugin to the `<theia>/plugins` folder
3. Run and verify that the "hello world" command works

**Comment by thegecko** [comment]
> I just tried with https://github.com/eclipse/che-theia-samples/tree/master/samples/hello-world-frontend-plugin against Theia master and it works just fine.

Perfect, an example was what I needed

**Comment by thegecko** [comment]
I can confirm the example works and if loaded in place it doesn't require packaging, either.
My issue was missing the webpack step (obvious now I think of it).

For reference, this example will work in Theia versions since 1.7.0.

Thanks @tsmaeder
