### ISSUE TITLE
preferences: context-menu does not anchor properly when zoom level is updated

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9062]
#### Bug Description:

The context-menu triggered from the `preferences` UI does not anchor properly (opens with an incorrect location) when the application's zoom level is updated.

_Default Zoom_:

![default-pref](https://user-images.githubusercontent.com/40359487/107793004-ce752a00-6d23-11eb-8771-e7e3d4453092.gif)

_Increased Zoom_:

![zoom-in](https://user-images.githubusercontent.com/40359487/107793157-fe243200-6d23-11eb-8a69-92038b21598b.gif)

#### Steps to Reproduce:

1. start the application (tested with `electron`)
2. open the preferences-ui
3. zoom in (<kbd>ctrl</kbd>+<kbd>+</kbd> or use the `zoom in` command)
4. attempt to open the context-menu as shown in the `.gifs`

### Additional Information

- Operating System: Ubuntu 16.04 - Electron

**Comment by balajiv113** [comment]
@vince-fugnitto - On analysis i found that this issue occurs for all the places (Like explorer tree context menu) and not only preference. Am able to reproduce this issue only in electron and not in browser.

I will raise a PR for fixing this by honouring zoom factor for electron context menu renderer.
