### ISSUE TITLE
Can not have multiple plugins inside the plugins folder

### ISSUE THREAD

**Issue by pchuong** [eclipse-theia/theia#9064]
### Bug Description:

Can not have more than one frontend (maybe backend too) non VS plugins inside the plugins folder. I have tested dropping multiple of these example plugins, https://github.com/eclipse/che-theia-samples/tree/master/samples, as well as my own plugin into the plugins folder and only one will be registered.

After debugging the issue, I have found the root cause. The file packages/plugin-ext/src/hosted/browser/hosted-plugin.ts, line 361, **const dynamicContributions = hostContributions.get(plugin.host) || [];** should be **const dynamicContributions = hostContributions.get(host)**.

### Steps to Reproduce:

1. Build and drop the samples plugins from the link above
2. Can't open more than one sample plugin

### Additional Information

- Operating System: Ubuntu
- Theia Version: 1.9

**Comment by vince-fugnitto** [comment]
@pchuong thank you for the issue, to clarify are you attempting to consume multiple plugins in the `plugin` folder on startup (like we do for vscode builitns), or are you trying to launch hosted-plugins? If its the later, I think that only one plugin can be launched at a time as a `hosted-plugin`.

> Can't open more than one sample plugin

The wording here is what confused me, by "open" what do you mean?

**Comment by pchuong** [comment]
@vince-fugnitto, I have multiple hosted-plugins in the plugins folder. Such as the webview-sample-plugin and my own plugin. Both of these plugin registered for commands. But if I have two both of these plugins in the plugins folder, only one of the plugin is available when I try to run the command using ctrl+shift+p. As soon as I removed either one of this plugin, than the one remaining is available in the list of command.

**Comment by vince-fugnitto** [comment]
Closing in favor of #9901 which includes additional information, and is referenced by a pull-request.
Thank you for reporting the issue!
