### ISSUE TITLE
Support multi-selection in Tree View

### ISSUE THREAD

**Issue by rayakoren** [eclipse-theia/theia#9074]
Support multi-selection of tree items in Tree View.

### Feature Description:
Feature should allow selecting more than 1 item in tree view using Ctrl + Click on the relevant items. 

Can be added as a property of **TreeViewOptions** like in vscode api: 

**canSelectMany?: boolean**  

Whether the tree supports multi-select. When the tree supports multi-select and a command is executed from the tree, the first argument to the command is the tree item that the command was executed on and the second argument is an array containing all selected tree items.

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/10102.
