### ISSUE TITLE
[Diff] Images should open in preview

### ISSUE THREAD

**Issue by ghuntley** [eclipse-theia/theia#9079]
The default open handler of binary images (gif, png, jpg, jpeg) in the diff pane should display images as a preview when double clicking them.

### Feature Description:

![image](https://user-images.githubusercontent.com/127353/108167046-358e4680-7149-11eb-9956-8db57b4d1544.png)

**Comment by vince-fugnitto** [comment]
@ghuntley thank you for reporting the issue, is this something you're interested in fixing? (we can guide you if you'd like).

**Comment by ghuntley** [comment]
I absolutely am and would love if you could introduce me to the correct parts of the codebase.

**Comment by vince-fugnitto** [comment]
> I absolutely am and would love if you could introduce me to the correct parts of the codebase.

I'll do some investigation and see if I can try and find some information for anyone interested in fixing the issue. We have some open PRs that affect the SCM which we may want to wait for before attempting to fix the problem.

**Comment by pisv** [comment]
Just a note that I'm currently working on this feature. It happened to be quite complicated, a number of things across Theia needed to be fixed to make it work, but I'm making steady progress and hope to share a PR with you soon.

Basically, the `CustomEditorOpener` will be able to open a diff-uri in a side-by-side editor, so it is going to support more than just images. Here's a preview:

<img width="1704" alt="Screenshot" src="https://github.com/eclipse-theia/theia/assets/8298491/d5a94050-e178-4ee8-8140-d2f8d0d524d3">

**Comment by pisv** [comment]
I have submitted PR #13916 that hopefully will fix this issue.
