### ISSUE TITLE
preferences: setting preference programatically does not respect schema

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9086]
#### Bug Description:

The `preference-service` does not respect the preference's schema when setting the value programatically (confirmed with a `minimum` and `maximum` [test](https://github.com/eclipse-theia/theia/compare/vf/preference-test))

Should we expect that setting the preference programatically will respect the schema and not provide us with incorrect preference values?

**_Example:_**

_Schema_:

```ts
'sample.min-max': {
  type: 'number',
  default: 1,
  description: 'Test preference verifying min-max.',
  minimum: 1,
  maximum: 3,
}
```

_Result_:

When using  the `preferenceService.set`, we end up in a state where the preference value is out of bounds based on the min-max property:

![image](https://user-images.githubusercontent.com/40359487/108384179-81d49780-71d8-11eb-8ed8-83c3eeb3b6f9.png)

#### Steps to Reproduce:

1. clone the example https://github.com/eclipse-theia/theia/compare/vf/preference-test
2. build the `api-samples` extension and example application(s)
3. use the `sample: increment` and `sample: decrement` commands to test if the preference is set passed the min-max properties

**Comment by kittaakos** [comment]
Thank you for bringing this up!

Looks like this is how VS Code handles it. I could set an invalid value via code:
```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(vscode.commands.registerCommand('config-test.helloWorld', async () => {
        /**
         * // Scale of content drawn in the minimap: 1, 2 or 3.
         * "editor.minimap.scale": 1,
         * From: https://code.visualstudio.com/docs/getstarted/settings
         */
        console.log('has', vscode.workspace.getConfiguration().has('editor.minimap.scale'));
        console.log('get', vscode.workspace.getConfiguration().get('editor.minimap.scale'));
        console.log('update', await vscode.workspace.getConfiguration().update('editor.minimap.scale', 2));
        console.log('get', vscode.workspace.getConfiguration().get('editor.minimap.scale'));
        try {
            console.log('update invalid', await vscode.workspace.getConfiguration().update('editor.minimap.scale', -1000));
        } catch (e) {
            console.log(e);
        }
        console.log('get', vscode.workspace.getConfiguration().get('editor.minimap.scale'));
    }));
}

export function deactivate() { }
```

```
has true
get 2
update undefined
get 2
update invalid undefined
get -1000
```

![Screen Shot 2021-02-23 at 10 05 42](https://user-images.githubusercontent.com/1405703/108821991-b8d2f080-75be-11eb-93c3-b979e4ace8ff.jpg)

I would have expected that `update` rejects, but that's not the case. We have to be VS Code compliment, and we are. I propose closing.

**Comment by vince-fugnitto** [comment]
> I would have expected that `update` rejects, but that's not the case. We have to be VS Code compliment, and we are. I propose closing.

Thank you for looking into it @kittaakos, I'll close.
