### ISSUE TITLE
keybindings: ctrl+k, ctrl+p does not work after rebinding 2 other shortcuts

### ISSUE THREAD

**Issue by slhultgren** [eclipse-theia/theia#9087]
### Bug Description:
If a few shortcuts are rebinded, then ctrl+k ctrl+p (show all editors) stops working

Properties on the KeyCode object are not restored properly, so comparison of equals() will fail.
This leads to the key sequence being hanged on "ctrl+K", never accepting the complete sequence. This requires a restart of Theia to get back to normal shortcut behaviour.

### Steps to Reproduce:

1. Rebind "Format document" to "shift+alt+e"
2. Rebind "editor: go to last edit location" to "ctrl+alt+left"
3. Try using "ctrl+k, ctrl+p" to show all opened editors
4. Observe that nothing happens and that the shortcut is stuck in "ctrl+k"
5. Also observe crash of missing ".equals is not a function" in the developer tools console 

### Additional Information

- Operating System: All
- Theia Version: 1.10.0

**Comment by vince-fugnitto** [comment]
Closed thanks to #9088.
