### ISSUE TITLE
Update to Electron 11

### ISSUE THREAD

**Issue by AirSeeker** [eclipse-theia/theia#9095]
### Feature Description:
In order to build Theia for Apple M1 chip electron need to be updated to version 11.
Currently, Theia can run on Apple M1 chip thanks to Rosetta.
But with native build for Apple M1 chip the performance will increase.

**Comment by vince-fugnitto** [comment]
Closing since the framework now supports Electron v15 https://github.com/eclipse-theia/theia/pull/9936.
