### ISSUE TITLE
readme: update logo for both github themes

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9114]
#### Feature Description:

The `theia` logo part of the `readme` should be updated so it is visible for both github themes (light + dark).
At the moment the logo is hardly visible when using the dark theme:

<div align='center'>

<img width="1158" alt="Screen Shot 2021-02-23 at 3 03 36 PM" src="https://user-images.githubusercontent.com/40359487/108901173-8d64fb80-75e8-11eb-817b-6ab9313fdbb7.png">

</div>

<br />

~Since our logos are `svg` we can add a copy under our repository with a different fill (perhaps the same color as the application icon - `#2962FF`):~

https://github.com/eclipse-theia/theia/blob/31b08380014bae783ccf602caf7bba15c0e64871/logo/theia-logo.svg#L21

**Update**:

In order to not confuse with `Eclipse Theia Blueprint`, we can use a different color, I propose we use gray (which looks fine both on white and black backgrounds): `#9C9C9C`

**Comment by vince-fugnitto** [comment]
@koegel should we aim for a different color in the main-repository readme as not to confuse it with _Eclipse Theia Blueprint_?

**Comment by koegel** [comment]
> @koegel should we aim for a different color in the main-repository readme as not to confuse it with _Eclipse Theia Blueprint_?

Yes, I think it would be good to use a different color, maybe grey or green?

**Comment by vince-fugnitto** [comment]
> > @koegel should we aim for a different color in the main-repository readme as not to confuse it with _Eclipse Theia Blueprint_?
> 
> Yes, I think it would be good to use a different color, maybe grey or green?

I’ll stick with grey, monochrome and neutral :)
