### ISSUE TITLE
args not working when trigger a command using custom keybinding in extensions

### ISSUE THREAD

**Issue by HaoboGu** [eclipse-theia/theia#9126]
### Bug Description:
In vscode extension, if the extension defines a command and binds a shortcut to the command, `args` can be set in `package.json` as commands parameter. But in theia `args` doesn't work. 
The related discussion can be found here:
https://github.com/eclipse-theia/theia/discussions/9108#discussioncomment-401250

### Steps to Reproduce:

1. Initialize a vscode extension following https://code.visualstudio.com/api/get-started/your-first-extension
2. Add a command and binds the command with a shortcut in extension's `package.json`:
```json
"contributes": {
		"commands": [
			{
				"command": "test.helloWorld",
				"title": "Hello World"
			}
		],
		"keybindings": [
			{
				"command": "test.helloWorld",
				"args": 1,
				"key": "shift+ctrl+1",
				"mac": "shift+ctrl+1"
			},
			{
				"command": "test.helloWorld",
				"args": 2,
				"key": "shift+ctrl+2",
				"mac": "shift+ctrl+2"
			}
		]
	},
```
3. Implement the command:
```typescript
export function activate(context: vscode.ExtensionContext) {
	// The command has been defined in the package.json file
	// Now provide the implementation of the command with registerCommand
	// The commandId parameter must match the command field in package.json
	let disposable = vscode.commands.registerCommand('test.helloWorld', (order: number) => {
		vscode.window.showInformationMessage(String(order));
	});

	context.subscriptions.push(disposable);
}
```
4. In vscode, triggering `shift+ctrl+1` or `shift+ctrl+2` would raise a message window which shows corresponding number, but in theia, both shortcuts shows 0

### Additional Information

- Operating System: MacOS 11.2
- Theia Version: 1.8.0

**Comment by xcariba** [comment]
I think that one can be closed now 🙂

**Comment by HaoboGu** [comment]
Thank you!
