### ISSUE TITLE
[siw] Typing into the files to include, exclude fields do not re-trigger the search

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#9150]
### Bug Description:

The result in the SIW is not updated when changing the include/exclude fields. I have to press enter to rerun the search. It works from VS Code.

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by AbhiSahane0** [comment]
Can I do this project Plz.

**Comment by vince-fugnitto** [comment]
> Can I do this project Plz.

@AbhiSahane0 please go ahead :+1::

https://github.com/eclipse-theia/theia/blob/b972e2b217da074d821d173a4f8517e171efbd45/packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx#L531-L554

https://github.com/eclipse-theia/theia/blob/b972e2b217da074d821d173a4f8517e171efbd45/packages/search-in-workspace/src/browser/search-in-workspace-widget.tsx#L542

**Comment by AbhiSahane0** [comment]
sir what to do with 'onKeyUp={e => {  '

**Comment by vince-fugnitto** [comment]
> sir what to do with 'onKeyUp={e => { '

@AbhiSahane0 you'll likely need to modify this handler when creating the glob fields (include and exclude) so that they search on input rather than wait for an <kbd>Enter</kbd> key to be pressed (similarly to the actual search input). The logic to split the input (on commas) should be preserved to support globs.

**Comment by kittaakos** [comment]
Thank you so much for your assistance, @AbhiSahane0. I really needed the fix, so here is the PR: https://github.com/eclipse-theia/theia/pull/9183

Please chime-in and propose any changes if you do not like my approach. Thanks!
