### ISSUE TITLE
`required` field in `taskDefinitions` contribution is mandatory

### ISSUE THREAD

**Issue by sapirpol** [eclipse-theia/theia#9165]
### Bug Description:
When installing an extension that contributes `taskDefinitions` (without the 'required' field), I get multiple errors on tasks.json.
This behavior does not produce the same results compared to vscode.

<img width="981" alt="theia-bug" src="https://user-images.githubusercontent.com/30637290/110505590-f5e2cb00-8106-11eb-82e4-a57523168765.png">

**Comment by allaVolkov** [comment]
The problem becomes critical, when we use any external extension that does not define required properties.
Process of task provider detection fails on such problematic extension and doesn't see other task providers.
Thus these tasks provided become unreachable, related tasks are marked as problematic and can't be executed.

**Comment by tsmaeder** [comment]
VS Code API doc says: "A task definition has at minimum a type property but it usually defines additional properties.". This indicates that "required" should not be mandatory.

**Comment by vince-fugnitto** [comment]
The pull-request https://github.com/eclipse-theia/theia/pull/10015 should resolve the issue.
