### ISSUE TITLE
Failed to register onCustomEditor:vscode.markdown.preview.editor

### ISSUE THREAD

**Issue by jeluard** [eclipse-theia/theia#9185]
### Bug Description:

When using latest `vscode/markdown` builtin plugin, I get the following message:

```js
root ERROR [hosted-plugin: 58828] Unsupported activation events: onCustomEditor:vscode.markdown.preview.editor, please open an issue: https://github.com/eclipse-theia/theia/issues/new
```

### Steps to Reproduce:

1. Add `"vscode-builtin-markdown": "https://open-vsx.org/api/vscode/markdown/1.54.1/file/vscode.markdown-1.54.1.vsix",` to plugins
2. Start theia

**Comment by vince-fugnitto** [comment]
@jeluard which version of the framework are you using? It should be supported thanks to #8910 (`next`) 
Can you verify using `master`?

**Comment by jeluard** [comment]
Indeed, it's fixed on master

**Comment by vince-fugnitto** [comment]
> Indeed, it's fixed on master

It should be in the next release at the end of the month ~25th (or you can use `next` tag).
