### ISSUE TITLE
'code.languages.registerLinkedEditingRangeProvider is not a function' error when using the Elmtooling.elm-ls-vscode extension

### ISSUE THREAD

**Issue by dbj** [eclipse-theia/theia#9198]
### Bug Description:

When I install the Elmtooling.elm-ls-vscode extension v2.0.3 and bring up an Elm file, I get the following 2 errors:

    Couldn't start client Elm

and

    code.languages.registerLinkedEditingRangeProvider is not a function

### Steps to Reproduce:

1. Install Elmtooling.elm-ls-vscode v2.0.3
2. Load an Elm file in the file browser

### Additional Information

I have confirmed I have elm installed properly (v1.9.1)

- Operating System: I'm running Theia on https://gitpod.io in Chrome (Brave)
- Theia Version: Not sure which version of Theia gitpod is currently loading

**Comment by vince-fugnitto** [comment]
The `registerLinkedEditingRangeProvider` API is not yet implemented by the framework:

![image](https://user-images.githubusercontent.com/40359487/111153504-6e62e500-8568-11eb-9d23-d541468e98ed.png)

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/eclipse-theia/theia/issues/10200.
