### ISSUE TITLE
Drag and drop sections between views

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#9203]
### Feature Description:

In VS Code it is possible to drag and drop sections between views. In theia it is currently possible only in the same view.

Scenario:

1. install Docker vscode extension
2. Open Docker view 
3. Try to drag images section into the explorer view - it can be done in vscode but not in theia

Example:

![view](https://user-images.githubusercontent.com/71729183/123539276-8f2eff00-d741-11eb-860b-9e8fec5bb0c5.gif)

**Comment by vince-fugnitto** [comment]
Example from #9442:

![image](https://user-images.githubusercontent.com/40359487/117294749-02527e00-ae41-11eb-91ef-615116ab4852.png)

**Comment by EstherPerelman** [comment]
> Example from #9442:
> 
> ![image](https://user-images.githubusercontent.com/40359487/117294749-02527e00-ae41-11eb-91ef-615116ab4852.png)

@vince-fugnitto The image you attached is not `gif`:
![view](https://user-images.githubusercontent.com/71729183/123539276-8f2eff00-d741-11eb-860b-9e8fec5bb0c5.gif)
