### ISSUE TITLE
window.activeTextEditor is undefined after window.showErrorMessage is called.

### ISSUE THREAD

**Issue by b-tsao** [eclipse-theia/theia#9210]
### Bug Description:
In the extension my team is creating we call window.activeTextEditor to retrieve the current active text editor in order to invoke operations on said editor, but if an error happens we call window.showErrorMessage to notify users of the error. After the error message is closed and the user invokes the operation again, window.activeTextEditor is undefined.
![image](https://user-images.githubusercontent.com/8595654/111381517-0ba24400-8663-11eb-8d07-4ecf6904c486.png)

### Steps to Reproduce:

1. Open a file
2. In the text editor right click to open context menu and select a newly defined operation from an extension
3. Invoke said operation that calls window.activeTextEditor and see that it is defined.
4. Suppose that operation calls window.showErrorMessage and close the error message
5. Repeat step (2) and see window.activeTextEditor is undefined now.

![image](https://user-images.githubusercontent.com/8595654/111381721-4efcb280-8663-11eb-92be-66de0a39ea5e.png)

### Additional Information

- Operating System: docker (theiaide/theia-https)
- Theia Version: https://github.com/theia-ide/theia-apps latest

**Comment by vince-fugnitto** [comment]
@b-tsao thank you for reporting the issue, are you interested in providing a pull-request to fix the bug?

**Comment by vince-fugnitto** [comment]
I'm unable to reproduce the issue with a test plugin.
If the issue persists for you please comment and provide an example plugin to test with :+1:
