### ISSUE TITLE
Filter Hidden files option on browser Open/Save dialog

### ISSUE THREAD

**Issue by caseyflynn-google** [eclipse-theia/theia#9215]
Hey all,

Recently we have added the option to filter hidden files in the Open/Save browser Dialogs. If you like we can upstream this feature. If not, feel free to close.

Thanks for all of the amazing work you do on Theia!

### Feature Description:

![hidden_file_filter](https://user-images.githubusercontent.com/23463108/111517307-297ab200-8712-11eb-9915-5d966c5d6d2c.png)

![hidden_file_filter_save](https://user-images.githubusercontent.com/23463108/111520272-2e8d3080-8715-11eb-965f-b50b628fd9f9.png)

**Comment by kenneth-marut-work** [comment]
Hey @caseyflynn-google, curious if you had made any progress on this ticket? We've also done a very similar override downstream and would be happy to contribute it if you've been busy, thanks! 🙂
