### ISSUE TITLE
Invalid unit "p" in bulk-edit.css

### ISSUE THREAD

**Issue by ahaWDY** [eclipse-theia/theia#9216]
### Bug Description:
 "1p" is likely to be a typo and should be "1px".

### Steps to Reproduce:
https://github.com/eclipse-theia/theia/blob/9dacd49fe0cf27811e863d75fe9b69d94b8c16cc/packages/bulk-edit/src/browser/style/bulk-edit.css#L65

### Additional Information

- Operating System: Windows
- Theia Version: 1.11.0

**Comment by kittaakos** [comment]
Thank you, @ahaWDY. We have a PR for this: https://github.com/eclipse-theia/theia/pull/9100/
