### ISSUE TITLE
Timeline panel doesn't work

### ISSUE THREAD

**Issue by vinokurig** [eclipse-theia/theia#9221]
### Bug Description:
Timeline panel doesn't show any items.

### Steps to Reproduce:
1. Remove `"@theia/git": "^1.11.0"` from `examples/browser/package.json` file.
2. Download [vscode-git-1.49.3](https://open-vsx.org/api/vscode/git/1.49.3/file/vscode.git-1.49.3.vsix) and copy it to the `plugins` folder.
3. Start Theia and  open a project cloned from GitHub e.g. https://github.com/vinokurig/test.git
4. See the Timeline panel doesn't show anything:
![screenshot-localhost_3000-2021 03 18-19_40_07](https://user-images.githubusercontent.com/7668752/111671543-b7918e00-8821-11eb-91ee-0ae50dacce12.png)
Expected: The Timeline panel should show git history of the opened file:
![screenshot-localhost_3000-2021 03 18-19_43_04](https://user-images.githubusercontent.com/7668752/111671950-21119c80-8822-11eb-9fd5-a77b1f9bd21b.png)

### Additional Information

- Operating System:
- Theia Version:

**Comment by RomanNikitenko** [comment]
Should be fixed after merging https://github.com/eclipse-theia/theia/pull/9222
