### ISSUE TITLE
vsx: add compatibility handling when installing extension packs

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9224]
#### Feature Description:

The goal is to add better support for **builtin** [extensionPack](https://code.visualstudio.com/api/references/extension-manifest#extension-packs) extensions (built from the [vscode-builtin-extensions](https://github.com/eclipse-theia/vscode-builtin-extensions) repository. Creating and using `extensionPacks` will speed up development as they will be automated, and will be all grouped together.

The currently implementation relies on compatibility handling (through the `vscode.engines` version) but this step is currently skipped for builtins. The builtin `extensionPack` is quite unique and will require some additional handling to not fetch based on supported API but rather the version specified in the extension's `package.json`. We will also need custom logic to differentiate such extensions likely through the reserved `eclipse-theia` namespace.

**Comment by vince-fugnitto** [comment]
@alvsan09 I do not believe it is necessarily a bug.
The `extensionPack` you prepared has an  `vscode.engines` version of `^1.45.1` meaning it may target newer version if they are API compatible. I think the misunderstanding was thinking that `vscode.engines` and `version` are the same thing? The way `extensionPack` are controlled is through the `engines` field.

For example, the `theme-tommorow-night-blue` targets all versions because of its API support:

https://github.com/microsoft/vscode/blob/3fd2415c9f74eaa82079c2fd1292d7d18341ac3d/extensions/theme-tomorrow-night-blue/package.json#L8-L10

**Comment by marcdumais-work** [comment]
@vince-fugnitto ok to assign you this issue?

**Comment by vince-fugnitto** [comment]
Adding a couple of findings:

The idea of having a builtin `extensionPack` (referenced in an application's `package.json`) might be problematic on initial application startup. The logic to fetch the individual extensions (referenced by `id`), and determining the api-compatible version means that the application is started in a state where no plugins are yet loaded and leads to a bare minimum application (until plugins are loaded). We likely still want to be able to support the use-case where application-developers are able to include `extensionPacks` in their application by default.

We might benefit from improving the `download:plugins` script to also support pre-fetching extensions referenced in the `package.json` (download once and startup is like today).
