### ISSUE TITLE
CustomEditorProvider Cannot Saved file through function "document.save()"

### ISSUE THREAD

**Issue by SunnyFitz** [eclipse-theia/theia#9230]
### Bug Description:
document.save() in CustomEditorProvider cannot working properly

### Steps to Reproduce:

1. Create a new file worked on CustomEditorProvider
2. make a change on editor area 
3. use Ctrl + S to save file (I used acquireTheiaApi , Created a socket to send message to call document.save on my CustomEditorProvider ), which has called save function but not success
4.  click other area （resource explorer or editor title bar ） or open file in code editor and custom editor， than use Ctrl+S to call document.save and it worked

![image](https://user-images.githubusercontent.com/37280039/111994849-386ac580-8b53-11eb-980c-9c1788799c60.png)
![image](https://user-images.githubusercontent.com/37280039/111994952-5afcde80-8b53-11eb-9719-2ef1eebe4fe8.png)

- Operating System: Linuxmint
- Theia Version: 1.12.0-next.9f13354e

**Comment by vince-fugnitto** [comment]
cc @danarad05 perhaps you can help, or understand why it may not work this way.

**Comment by SunnyFitz** [comment]
i canceled keyevent in js which run in webview . Then Ctrl + S can work   properly.

but customEditor cannot active theia.workspace.onDidChangeActiveTextEditor, so i cannot get customEditor focus changed event.
Is there hava others way to get focused status of customEditor ?

**Comment by danarad05** [comment]
@SunnyFitz 
Thanks for letting us know of issue. Could you please add your example project and a short screen shots video of scenario so I could reproduce issue.
Thanks

**Comment by amos42** [comment]
This problem does not occur in v1.13.0.
This problem has occurred since v1.14.0, and the problem persists in v1.16.0.
