### ISSUE TITLE
Establish Road Map Process

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia#9232]
#### Part 1 - Issues:

We create a milestone in GitHub for every release. Developers should assign tickets to the current milestone if they intend to work on it during this period. It is OK to move things or not to complete, but developers should reflect the latest state in the tickets. Additionally, we could create a milestone "next" for the important stuff. This way we communicate with the community what the committers plan to work on and also what we find important to do.

#### Part 2 - Wiki Page:

A wiki page to which all parties can contribute their high-level goals, e.g. per quarter. Does not have to be detailed, but just bullets. Topics can be one-time things such as "Improve embedded support via memory view", but also recurring such as "Improve stability" or "Improve VS Code API coverage". The goals should be discussed in the dev meeting once per quarter. The discussion should also collect suggestions on how to drive the project forward. Goals could be potentially mapped to issue labels, so we could add links to filtered searches.

_Update_: adding [discourse link](https://community.theia-ide.org/t/short-term-roadmap/1570).

**Comment by vince-fugnitto** [comment]
@JonasHelming is the following issue an epic you wish to remain open, is there anything left for it to be closed?

We may want to add a link to the [roadmap wiki](https://github.com/eclipse-theia/theia/wiki/Roadmap) directly in the `readme` (it may be a bit hidden for newcomers to discover the location of the roadmap currently).

**Comment by JonasHelming** [comment]
> @JonasHelming is the following issue an epic you wish to remain open, is there anything left for it to be closed?
> 
> We may want to add a link to the [roadmap wiki](https://github.com/eclipse-theia/theia/wiki/Roadmap) directly in the `readme` (it may be a bit hidden for newcomers to discover the location of the roadmap currently).

After adding the link to the readme (see PR), I would close this issue

**Comment by brianking** [comment]
fyi I updated https://community.theia-ide.org/t/theia-roadmap/1527 with information about the roadmap.

I'll also work with our social team to tweet about it @theia_ide (and other content there). 

If you have recommendations on other channels we should share this on, let me know.
