### ISSUE TITLE
Error using vscode Tasks presentationOptions reveal

### ISSUE THREAD

**Issue by brianignacio5** [eclipse-theia/theia#9239]
### Bug Description:

Trying to test a vscode extension in Theia but get some errors with vscode.Task.PresentationsOptions.reveal. As I understand, this is already covered by Theia in VSCode API coverage.

### Steps to Reproduce:

1. In visual studio code extension, use the vscode.task API to create a task.
2. Try to update myTask.presentationOptions.reveal = vscode.TaskRevealKind.Always;
3. Get an error that can't update reveal of undefined

vscode extension code

```ts
public static addTask(
    taskDefinition: vscode.TaskDefinition,
    scope: vscode.TaskScope,
    name: string,
    execution:
      | vscode.ShellExecution
      | vscode.ProcessExecution
      | vscode.CustomExecution,
    problemMatchers: string | string[],
    revealTask: vscode.TaskRevealKind
  ) {
    const newTask: vscode.Task = new vscode.Task(
      taskDefinition,
      scope,
      name,
      ESP.extensionID,
      execution,
      problemMatchers
    );
    newTask.presentationOptions.reveal = revealTask; // Error here
 }
```

I believe its an issue with the new vscode.Task() constructor not initializing it.

### Additional Information

- Operating System: macOS Catalina 10.15.7
- Theia Version: next (using a browser app)
List of extensions
@theia/bulk-edit 1.12.0-next.1a1d7afc
@theia/callhierarchy 1.12.0-next.1a1d7afc
@theia/console 1.12.0-next.1a1d7afc
@theia/core 1.12.0-next.1a1d7afc
@theia/debug 1.12.0-next.1a1d7afc
@theia/editor 1.12.0-next.1a1d7afc
@theia/file-search 1.12.0-next.1a1d7afc
@theia/filesystem 1.12.0-next.1a1d7afc
@theia/markers 1.12.0-next.1a1d7afc
@theia/messages 1.12.0-next.1a1d7afc
@theia/mini-browser 1.12.0-next.1a1d7afc
@theia/monaco 1.12.0-next.1a1d7afc
@theia/navigator 1.12.0-next.1a1d7afc
@theia/outline-view 1.12.0-next.1a1d7afc
@theia/output 1.12.0-next.1a1d7afc
@theia/plugin-dev 1.12.0-next.1a1d7afc
@theia/plugin-ext 1.12.0-next.1a1d7afc
@theia/plugin-ext-vscode 1.12.0-next.1a1d7afc
@theia/preferences 1.12.0-next.1a1d7afc
@theia/preview 1.12.0-next.1a1d7afc
@theia/process 1.12.0-next.1a1d7afc
@theia/scm 1.12.0-next.1a1d7afc
@theia/search-in-workspace 1.12.0-next.1a1d7afc
@theia/task 1.12.0-next.1a1d7afc
@theia/terminal 1.12.0-next.1a1d7afc
@theia/timeline 1.12.0-next.1a1d7afc
@theia/userstorage 1.12.0-next.1a1d7afc
@theia/variable-resolver 1.12.0-next.1a1d7afc
@theia/workspace 1.12.0-next.1a1d7afc

**Comment by alvsan09** [comment]
Hi,
I am looking into this issue, 
I will be posting a pull request shortly
