### ISSUE TITLE
Provide abstraction over MessagingProtocol

### ISSUE THREAD

**Issue by nimo23** [eclipse-theia/theia#9240]
### Feature Description:

Currently, Theia uses https://theia-ide.org/docs/json_rpc to communicate between backend and frontend. Would be nice if the `messaging` can be changed globally and/or on runtime (for example, by dependencyInjection).

For example, Theia can use https://rsocket.io/ to use RSocket for all communications:

```
@inject(RSocketMessageService)
protected readonly messageService: MessageService;
```

**Comment by msujew** [comment]
The message protocol has been refactored a few times in the meantime. Theia is now using socket.io for its main communication. I'll close this.
