### ISSUE TITLE
[electron] File dialog filters do not work

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia#9242]
### Bug Description:

I found this bug when reviewing https://github.com/eclipse-theia/theia/pull/9184. Although a filter is correctly configured:

https://github.com/eclipse-theia/theia/blob/14df86f3e4a032ef83ccb428895562b58cfdd828/packages/vsx-registry/src/browser/vsx-extensions-contribution.ts#L164-L169

It has no effect, as we always use the `*` filter. This code should be changed:

https://github.com/eclipse-theia/theia/blob/edc346b2639562797f707432191a090aad4bb7d6/packages/filesystem/src/electron-browser/file-dialog/electron-file-dialog-service.ts#L96-L99

Expected:
```diff
diff --git a/packages/filesystem/src/electron-browser/file-dialog/electron-file-dialog-service.ts b/packages/filesystem/src/electron-browser/file-dialog/electron-file-dialog-service.ts
index 10729331d5..eff76250aa 100644
--- a/packages/filesystem/src/electron-browser/file-dialog/electron-file-dialog-service.ts
+++ b/packages/filesystem/src/electron-browser/file-dialog/electron-file-dialog-service.ts
@@ -93,9 +93,11 @@ export class ElectronFileDialogService extends DefaultFileDialogService {
     protected toDialogOptions(uri: URI, props: SaveFileDialogProps | OpenFileDialogProps, dialogTitle: string): electron.FileDialogProps {
         const title = props.title || dialogTitle;
         const defaultPath = FileUri.fsPath(uri);
-        const filters: FileFilter[] = [{ name: 'All Files', extensions: ['*'] }];
+        const filters: FileFilter[] = [];
         if (props.filters) {
             filters.push(...Object.keys(props.filters).map(key => ({ name: key, extensions: props.filters![key] })));
+        } else {
+            filters.push({ name: 'All Files', extensions: ['*'] });
         }
         return { title, defaultPath, filters };
     }
```

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by scottaxcell** [comment]
@kittaakos this looks like a good first issue to get my feet wet. Can I help with this issue?
