### ISSUE TITLE
Illegible Error Logs in Debug Module

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#9244]
### Bug Description:

There are a number of logs of the form `console.error(e)` in the debug module, and those errors end up appearing in the console as `[object Object]`. They should be replaced with something like `console.error('<Method> failed:', e);`

https://github.com/eclipse-theia/theia/blob/f80c4454f4ee76bb5d711ed06608ad2426b1a147/packages/debug/src/browser/debug-session.tsx#L176

https://github.com/eclipse-theia/theia/blob/f80c4454f4ee76bb5d711ed06608ad2426b1a147/packages/debug/src/browser/debug-session.tsx#L190

They can be found using a regex search with a negative lookahead like this:
```
\.error\((?!['"`])
```

### Steps to Reproduce:

1. Throw an error in one of the affected methods.
2. Observe that the log is unhelpful.
3.

### Additional Information

- Operating System: RHEL7
- Theia Version: `master`, Electron application.

**Comment by anishbhanwala** [comment]
@colin-grant-work Can I try to solve this issue? This will be my first contribution.

I am thinking of creating a `debug/src/common/logger.ts` and calling `logger.error(message | error)` from the `debug-session.tsx` file. This will make the error logging centralized and e.g. allow easily changing error log format everywhere. I can send a pull request just for the `debug-session.tsx` file and if everything looks good do the changes in other files.

Please let me know if this sounds good or there is some other solution you have in mind.

**Comment by anishbhanwala** [comment]
Actually, never mind. I jumped to the solution. Looks like the logging is already centralized through `ILogger`. Let me spend some more time understanding the code and actually reproduce the issue.

**Comment by anishbhanwala** [comment]
I tried logging an error object using `console.error` in the `debug-session.tsx` file but couldn't reproduce it. Please check the screenshot: [screenshot-link](https://www.screencast.com/t/AN5Vio3DgW). Maybe I am missing something.

**Comment by colin-grant-work** [comment]
@anishbhanwala, thanks for your interest in this issue! The problem at the moment is that our logger expects a string as the first argument of a log call. That means that calls like this (and like the ones in your screenshot):
```typescript
console.error('This is a string', someObject);
```
Are fine, because the first argument is a string, and the second argument is then logged correctly, even if it is an object.

However, if you do this:
```typescript
console.error(someObject);
```
The object as the first argument will be stringified to `[object Object]`.

There are a number of logs in the debug that have the second form: `console.error(someError)`, and in those cases, `someError` is stringified to `[object Object]`, obscuring the actual error. The solution is to add a string as the first argument to those calls, making the error object the second argument, which the logger can handle correctly.

**Comment by anishbhanwala** [comment]
I have actually called the method `console.error` with an error object. 
```Javascript
console.error(new Error('testing error in debug console'));
```
Shouldn't it log `[object object]` in the browser console in this case.

Just wanted to make sure I can reproduce the issue to verify it's fixed.

**Comment by colin-grant-work** [comment]
Here are the permutations:

![image](https://user-images.githubusercontent.com/62660806/115406820-24979b00-a1b5-11eb-9ff0-a9967c42b12f.png)

```typescript
console.error('string', object); // OK - if a string is first, anything goes for the remaining arguments.
console.error(object); // Not OK - stringified to `[object Object]`
console.error(new Error()); // OK - actual native errors are OK 
```

The errors that occur in the debug module aren't native errors - they're often response objects from a debug adapter that indicate a failed request and so are treated as error-like by the debug code.

**Comment by anishbhanwala** [comment]
Got it. I am able to reproduce it now. I will send the pull request soon.

**Comment by anishbhanwala** [comment]
@colin-grant-work Shall I assign the pull request to you?
