### ISSUE TITLE
the function of addEventListener has a bug

### ISSUE THREAD

**Issue by gpsbird** [eclipse-theia/theia#9250]
### Bug Description:
The argument "useCapture" is used in the addEventListener function, so it should also appears in the removeEventListener function
![widget](https://user-images.githubusercontent.com/9528059/112404712-cf01d700-8d4b-11eb-9d9e-4efc2b615786.png)

### Additional Information

- Operating System:
- Theia Version: master

**Comment by vince-fugnitto** [comment]
@gpsbird thank you for reporting the issue, do you mind providing a pull-request to resolve it?
