### ISSUE TITLE
waitForHidden seems to be wrong.

### ISSUE THREAD

**Issue by kgdev** [eclipse-theia/theia#9260]
https://github.com/eclipse-theia/theia/blob/d9c0fabb4e657e7d1879a8067d119598cc00fb43/packages/core/src/browser/widgets/widget.ts#L282

Should it be `return waitForVisible(widget, false);` ?

**Comment by vince-fugnitto** [comment]
@kgdev thank you for reporting the issue, I believe you are correct. It is likely that the bug went unnoticed since there are no `waitForHidden` callers. Nevertheless, would you be interested in providing a pull-request to resolve the issue?
