### ISSUE TITLE
preferences: toggling preference results in incorrect behavior

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9268]
#### Bug Description:

I reproduced the issue when updating the `editor.enablePreview` preference. It seems that the editor steals the focus away from the preferences-view, and may be a side-effect of a bigger issue (not necessarily related to preview-editors)

https://user-images.githubusercontent.com/40359487/112654253-959d9a00-8e25-11eb-9919-1829b2a3dde3.mp4

#### Steps to Reproduce:

1. start the application (`editor.enablePreview` should be turned on - default)
2. open an editor as a preview (single-click)
3. open the preferences-view
4. update the `editor.enablePreview` preference
5. notice the editor steals focus away from the view

**Comment by colin-grant-work** [comment]
I am pretty confident it's a side effect of this code:

https://github.com/eclipse-theia/theia/blob/3420ef639e3b9240edd94d207d21d83f98a4e697/packages/editor-preview/src/browser/editor-preview-manager.ts#L63-L71

**Comment by colin-grant-work** [comment]
We later arrive at this listener:

https://github.com/eclipse-theia/theia/blob/3420ef639e3b9240edd94d207d21d83f98a4e697/packages/editor-preview/src/browser/editor-preview-manager.ts#L84-L95

@vince-fugnitto, do you believe that we should not `.activateWidget()` in this case, and instead just let it be focused if it was focused before, and not otherwise?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto, do you believe that we should not `.activateWidget()` in this case, and instead just let it be focused if it was focused before, and not otherwise?

I think so, especially if it occurs during the event and not user-triggered like double-clicking the tabbar. I do not think the editor should steal focus as it gives a bad user experience.
