### ISSUE TITLE
Information disclosure via Origin/Referer leakage

### ISSUE THREAD

**Issue by Jarthianur** [eclipse-theia/theia#9275]
### Feature Description:

Currently theia by default makes use of external services like _gravatar_, _open-vsx.org_ and _azurewebsites.net_. When sending requests to those services, theia includes its internal domain in HTTP headers. This is considered an information disclosure, as internal host/domain names are not classified as public knowledge. It is not a severe security issue, but an informational vulnerability.
Neither of those headers are required to be set "correctly" to the internal domain for the request to succeed.

Hence my request for change: Please randomize these header values, instead of sending the actual internal domain.

__Example request to gravatar.com:__
```txt
GET https://www.gravatar.com/avatar/4923629b0b928d2deab5b4a3e246b94b?d=robohash

Host: www.gravatar.com
[...]
Referer: https://theia.internal.domain/
```

__Example request to open-vsx.org:__
```txt
POST https://open-vsx.org/api/-/query

Host: open-vsx.org
[...]
Referer: https://theia.internal.domain/
Origin: https://theia.internal.domain
```

__Example request to schemastore.azurewebsites.net:__
```txt
GET https://schemastore.azurewebsites.net/api/json/catalog.json

Host: schemastore.azurewebsites.net
[...]
Referer: https://theia.internal.domain/
Origin: https://theia.internal.domain
```

As a workaround, I have excluded the vsx-registry extension, and "shadowed" both other hosts via local DNS overrides.

#### Additional Information
- [refererer header: privacy and security concerns](https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns)

**Comment by vince-fugnitto** [comment]
@Jarthianur thank you for reporting the feature request, is it something you're interested in working on?

**Comment by Jarthianur** [comment]
Finally I could do some research on this issue.
For example, the gravatar request comes from https://github.com/eclipse-theia/theia/blob/7d3b1d3b33cb565ec07965e5baf10c926006cdfd/packages/git/src/browser/history/git-commit-detail-header-widget.tsx#L90. This is just an img loaded by the browser. At this point, it is clear that this is not theias fault.
The most effective solution is to add `Referrer-Policy: no-referrer` from reverse proxy.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

But an internal domain is still sent via `Origin` header by the browser. It seems to be not possible to change this behavior, especially not server side. The only mitigation would be to use a proxy for clients, that rewrites this header.

Just for the reference, if anybody else is interested:
- add `Referrer-Policy: no-referrer` from reverse proxy
- use a proxy for outgoing requests, that rewrites the `Origin` header

Issue can be closed.
