### ISSUE TITLE
Implement the Authentication (and Secret) APIs

### ISSUE THREAD

**Issue by fbricon** [eclipse-theia/theia#9288]
### Feature Description:
We're developing a Red Hat authentication provider (https://github.com/redhat-developer/vscode-redhat-account), but Theia is currently missing a series of APIs for it to work (as per https://che-incubator.github.io/vscode-theia-comparator/status.html).

- AuthenticationProvider
- AuthenticationProvider.AuthenticationSessionsChangeEvent
- AuthenticationProviderOptions
- ExtensionContext.secrets
- SecretStorage
- SecretStorageChangeEvent
- namespace/authentication/registerAuthenticationProvider

Some of these might already have been implemented, in case https://che-incubator.github.io/vscode-theia-comparator/status.html is not up-to-date, but in any case, the authentication provider doesn't currently work.
<img width="510" alt="Screenshot 2021-03-24 at 12 21 40" src="https://user-images.githubusercontent.com/148698/113189781-de0ceb80-925b-11eb-84d3-352616125020.png">
 
cc @benoitf

**Comment by PhilippeVienne** [comment]
Hello, @fbricon @benoitf have you already started to work on it? our company is also interested in this feature and we want to spend time on it.

**Comment by azatsarynnyy** [comment]
Hello @PhilippeVienne 
it's a good idea to work on it :+1: 
I think you need to sync with @ericwill as his team also planned to look at this issue.

**Comment by ericwill** [comment]
> Hello @PhilippeVienne
> it's a good idea to work on it +1
> I think you need to sync with @ericwill as his team also planned to look at this issue.

Hi @PhilippeVienne, as mentioned in response to your email, someone from my team will start working on this issue later this week. Please feel free to investigate what API you are missing and maybe we can work on it together :+1:

**Comment by PhilippeVienne** [comment]
Hi @ericwill It seems we have a need on the exact same API `namespace/authentication/registerAuthenticationProvider` with the `AuthenticationProvider` management. We currently do not use the secret API. If possible I would like to contact the person starting the work to either do a part or help in review and testing (as we would be also able to test on our own Authentication plugin).

**Comment by vinokurig** [comment]
@PhilippeVienne There is an `authentication` API exposed in the `proposed.d.ts`: https://github.com/eclipse-theia/theia/blob/4e75591d31be9fb9cd2931f303b82fa50c4c17e0/packages/plugin/src/theia-proposed.d.ts#L117 Is that what you need?

**Comment by PhilippeVienne** [comment]
@vinokurig Yes and the possibility to `provider.onDidChangeSessions` on `AuthenticationProvider` this allow our own extension to fetch the login session to our authentication plugin

**Comment by vinokurig** [comment]
@PhilippeVienne @fbricon 
> We currently do not use the secret API

So can we close this issue since the `Authentication` API is done?

**Comment by fbricon** [comment]
I still need secrets

**Comment by PhilippeVienne** [comment]
> @PhilippeVienne @fbricon
> 
> > We currently do not use the secret API
> 
> So can we close this issue since the `Authentication` API is done?

@vinokurig I made an error it is the onDidChangeSessions but on the authentication api and not the provider itself

Also, I think RedHat also need this particular point and the Secret API

**Comment by PhilippeVienne** [comment]
@vinokurig @fbricon I think there is an underlying bug due to the Authentication API moved out from proposed API see #9345

**Comment by vinokurig** [comment]
@PhilippeVienne @fbricon

**Comment by fbricon** [comment]
@vinokurig can we just rename this one "Implement the Secret API" instead?

**Comment by vinokurig** [comment]
@fbricon I think it is better to create a new one because the description is out of date and there is quite long discussion which is not related to the API itself.
