### ISSUE TITLE
Fail to add debug configuration when an empty launch.json is opened

### ISSUE THREAD

**Issue by tom-shan** [eclipse-theia/theia#9310]
### Bug Description:
when I open an empty launch.json, then click add configuration in debug panel, it only show "{}" in the file.
and actually the launch.json is modified in the backend. Because the contents of frontend and backend are inconsistent, so when I close it, it shows "changes will be lost" dialog.

### Steps to Reproduce:

1. open an empty launch.json
![image](https://user-images.githubusercontent.com/7686800/113847818-6d6d4e00-97ca-11eb-89c6-1a6a80d715f5.png)

2. add debug configuration
![image](https://user-images.githubusercontent.com/7686800/113853392-2f732880-97d0-11eb-9fcd-46cf9a53647f.png)

3. if I click "Don't save" and open the file again, the content changed
![image](https://user-images.githubusercontent.com/7686800/113853662-7cef9580-97d0-11eb-930e-273395d199e3.png)

### Additional Information
I have investigated this issue for a while, I notice the "{}" in launch.json is set by https://github.com/eclipse-theia/theia/blob/master/packages/debug/src/browser/debug-configuration-manager.ts#L265
But I dont't understand the meaning of setting it firstly. If I comment this line, then this issue will be fixed.

- Operating System: ubuntu
- Theia Version: fd91f213e15a91abf975329aaa37c9c59149d012

**Comment by vince-fugnitto** [comment]
I noticed the following when I tried and the behavior is bad as well:

https://user-images.githubusercontent.com/40359487/113869382-a97ac180-977e-11eb-9a50-489ea727cab5.mp4

https://user-images.githubusercontent.com/40359487/113869380-a8499480-977e-11eb-85d4-b9dbea652f57.mp4

**Comment by colin-grant-work** [comment]
I think this can be solved with some improvements I made to the preference system in #8917 (and some improvements on those improvements...). I'll see what I can do.
