### ISSUE TITLE
Workspace Model Not Updated `onWorkspaceLocationChanged`

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#9329]
### Bug Description:

The `TaskConfigurationManager` proxies requests for `TaskScope.Workspace` to either folder scope or the workspace file depending on workspace status. It currently listens to `onWorkspaceChanged` to detect changes to the roots, but does not listen `onWorkspaceLocationChanged` events to detect the saving a new workspace file.

### Steps to Reproduce:

1. Get the code from [this branch](https://github.com/colin-grant-work/theia/tree/reproduction/bad-workspace-handling) to add a command to log what the configuration service lists in workspace scope. (ctrl+p, search 'Check tasks listed in workspace scope.')
2. Build.
3. Open a single-root, unsaved workspace.
4. If there are no tasks in the root, add one, e.g.
```
{
  "version": "2.0.0",
  "tasks": [
    {"label": "Folder task", "type": "shell", "command": "htop"}
  ]
}
```
5. Run the command to log tasks in workspace scope.
6. See that the tasks in the folder scope are logged (since folder scope = workspace scope)
7. Run `File > Save Workspace as ...` and save the workspace wherever you'd like.
8. Run the command to log tasks in workspace scope.
9. See that the tasks in folder scope are still logged, even though folder scope != workspace scope after saving the workspace file.

### Additional Information

- Operating System: RHEL
- Theia Version: `master`

**Comment by tsmaeder** [comment]
To be sure I understand this right: the error is that when a workspace changes from being single-root to multi-root, the workspace level tasks are becoming folder level tasks (conceptually) and should not be returned when asking for the tasks from the workspace scope, but they are.
