### ISSUE TITLE
Undo/Redo for a text based customEditor isn't working

### ISSUE THREAD

**Issue by danarad05** [eclipse-theia/theia#9344]
### Bug Description:
When opening a text based custom editor document and making changes - undo/redo is caught but doesn't work

### Steps to Reproduce:

1. Run debug hosted plugin for `custom-editor-sample` from `vscode-extension-samples`
2. open `cscratch` document and make changes to it
3. run `ctrl+z` or undo/redo from Edit menu
4. `cscratch` document isn't updated

Referring to this document for instance:
![image](https://user-images.githubusercontent.com/71069170/114570417-7c4a7980-9c7e-11eb-9ad0-07f793c5a687.png)

### Additional Information

- Operating System: windows
- Theia Version: 1.12.0

**Comment by Hanksha** [comment]
Hi, 

I think I'm having a similar issue although I'm not sure if it fits in this issue. We have custom editors (no text editor) and the undo/redo shortcuts don't trigger the right command handler for the active custom editor. It works if I add the undo/redo commands to the toolbar or trigger them by any other means than the shortcuts.

I looked into it a bit and found that when using the keybinding, the monaco command handler for undo is always enabled, even though there is no focused monaco editor, so our custom handler never get called. See https://github.com/eclipse-theia/theia/blob/master/packages/monaco/src/browser/monaco-command.ts#L170

I'd like to provide a fix for this but I'm not sure if these monaco command handlers should only be enabled for focused monaco editors. If we use active editors as well (referring to monaco-command.ts#L170) if I activate my custom editor and there's a text editor opened (but hidden), it's still using that monaco command handler even though the text editor widget is technically not active.

**Comment by Hanksha** [comment]
Hi @vince-fugnitto Do you have any feedback on that?

**Comment by vince-fugnitto** [comment]
> Hi @vince-fugnitto Do you have any feedback on that?

@Hanksha I haven't looked into the details but I believe the problematic check is `codeEditorService.getActiveCodeEditor()` which will ultimately return the focused editor if it exists, or the last focused editor. You can experiment a bit and see if it works for you without this check, but it probably makes sense not to look back in history regarding the last focused editor and only check the current one.

**Comment by Hanksha** [comment]
@vince-fugnitto Alright thanks, I'll look into it.

**Comment by Hanksha** [comment]
@vince-fugnitto I think it was done this way so it can imitate the behavior of VS Code where you can undo/redo on the last active text editor without being focus on it, from example from the explorer view.

I think what we want here is to use the monaco command handler as a default if nothing else could handle the command but I don't know if it's possible.

**Comment by vince-fugnitto** [comment]
@Hanksha I don't think we have prioritized handlers for keybindings, but you may be able to use a when-clause context (when a custom-editor is active) to register handlers for `undo/redo` which should take priority over monaco,

For reference I believe vscode does the following https://github.com/microsoft/vscode/blob/726b7f51e0063b065436be42aaee4853447143d8/src/vs/workbench/contrib/customEditor/browser/customEditors.ts#L84-L93.

**Comment by Hanksha** [comment]
@vince-fugnitto Is that CustomEditorService available for extensions? I'm not using the vscode API at all.

**Comment by Hanksha** [comment]
@vince-fugnitto I'm writing a theia extension and using widgets as editors which are not text based (not vscode editors) and it has the same issue as using `CustomEditor` VS Code API. That why I mentioned in my original comment I was not sure if it would fit this issue or not.

**Comment by vince-fugnitto** [comment]
I'm not sure how your non-text based editor looks like or is implemented so I can't really comment on what might be the issue for undo/redo, or how undo/redo should work in such a case. Our `EditorWidget` relies on `TextEditor` being the underlying resource, if you have an example that is not proprietary perhaps you can share it, else I'm not sure how much help I can provide.

**Comment by Hanksha** [comment]
Unfortunately I don't have an example that is not proprietary but here's what I use:
- I have a widget, let's call it "MyCustomWidget" that extends `BaseWidget` from `@theia/core/lib/browser`, that widget has some UI in it.
- I register it in my frontend module via
```javascript
bind(WidgetFactory).toDynamicValue(ctx => ({
      id: "myid",
      createWidget: (options: MyCustomWidgetOptions) => {
          const child = ctx.container.createChild();
          child.bind(MyCustomWidgetOptions).toConstantValue(options);
          return child.get(MyCustomWidget);
      }
}));
```
- then I register a `WidgetOpenHandler` so I can open it via the `OpenerService`
```javascript
@injectable()
export class MyCustomWidgetOpenHandler extends WidgetOpenHandler<MyCustomWidget> {
    id = "myid";
    label = "My Custom Widget";

    canHandle(uri: URI): MaybePromise<number> {
        if (some condition) return 1;

        return 0;
    }

    protected createWidgetOptions(uri: URI): object {
        return {
            uri: uri.toString()
        };
    }
}
```

- From there I can open the custom widget like an editor, in the main shell area, from one of my views etc.

Once that widget is opened, the undo/redo keybindings don't work either because the handler registered by the monaco-command is always enabled.

**Comment by Hanksha** [comment]
@vince-fugnitto Wouldn't that mean that if the user want then to edit the undo keybinding for the undo/redo he'd have to do it for all the registered commands?
See
![image](https://user-images.githubusercontent.com/6960133/235158197-a73611ca-75e5-4952-92d9-128411b86abd.png)

**Comment by vince-fugnitto** [comment]
@Hanksha do you mind opening a [discussion](https://github.com/eclipse-theia/theia/discussions) instead, I think it's adding a lot of noise to this issue which is strictly about a VS Code `CustomEditor` API bug.

**Comment by Hanksha** [comment]
@vince-fugnitto Sure.

**Comment by Hanksha** [comment]
@vince-fugnitto Done https://github.com/eclipse-theia/theia/discussions/12474
