### ISSUE TITLE
plugin-ext: Add missing CodeActionTriggerKind enum to plugin context

### ISSUE THREAD

**Issue by nihonium-cfx** [eclipse-theia/theia#9347]
### Feature Description:
`typescript-language-features` plugin is constantly spewing errors because of `CodeActionTriggerKind` enum missing in plugin context.
This does not affect it's functionality, as far as I can tell, but I'd rather not see these errors in console.

I'd love to submit complete pull request, but can't obey your pr-rules because of anonymity, so if anyone could pick this commit up -- would be great. https://github.com/nihonium-cfx/theia/commit/096adfc3e8d48ae120660eb8ed4f5d465f61acb0

**Comment by DukeNgn** [comment]
@nihonium-cfx 

Unfortunately, I cannot reproduce the issue you're reporting. I tried code actions (`Quick fix` and `Refactor` feature) on TypeScript file but observed no console errors. Can you please provide the version of the plugin you're using and more details about the steps you did to reproduce the problem? 


 However, I confirmed that we don't have `CodeActionTriggerKind` enum in Theia at the moment, and would be a good idea to add support for it.

**Comment by nihonium-cfx** [comment]
@DukeNgn versions are:

Theia - 1.12.1
[TypeScript and JavaScript Language Features](https://open-vsx.org/extension/vscode/typescript-language-features) - 1.55.0

The way we can repro this is by editing (type something) in plain js file (no jsconfig.json nor tsconfig.json). Although this can only be reproducible in our environment where we have custom theia plugin that defines tsserver plugin (what an inception) that loads our defs:

```js
const fs = require('fs');
const path = require('path');

const wellKnownPathsPath = path.join(process.env.LOCALAPPDATA, 'citizenfx/sdk-storage/well-known-paths.json');
const wellKnownPaths = JSON.parse(fs.readFileSync(wellKnownPathsPath).toString());

function init() {
  return {
    create(info) {
      info.project.addMissingFileRoot(wellKnownPaths['ts_types_path']);

      return info.languageService;
    },
  };
}

module.exports = init;
```

Anyway, given that this requested addition is just an enum and don't have any extra functionality (as far as I can tell), it would be nice to have it added.

**Comment by DukeNgn** [comment]
@nihonium-cfx 

> [TypeScript and JavaScript Language Features](https://open-vsx.org/extension/vscode/typescript-language-features) - 1.55.0

Thanks for providing more details on the issue! I'm able to reproduce the problem on Theia master with `v1.55.0` of the plugin. I also confirmed that your proposed fix works.

I've picked up the changes and put up #9368 to add the enum. Thanks for your contribution!
