### ISSUE TITLE
PluginViewWidget: converting circular structure to JSON error

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9353]
#### Bug Description:

Triggering the `Find All References` command results in the following circular structure JSON error:

```
logger-protocol.ts:112 root ERROR error stringifying response:  TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'PluginViewWidget'
    |     property '_layout' -> object with constructor 'PanelLayout'
    --- property '_parent' closes the circle
    at JSON.stringify (<anonymous>)
    at safeStringify (file:///home/evinfug/workspaces/theia/examples/electron/lib/50.bundle.js:1596:21)
    at Function.push.../../packages/plugin-ext/lib/common/rpc-protocol.js.MessageFactory.replyOK (file:///home/evinfug/workspaces/theia/examples/electron/lib/50.bundle.js:1455:98)
    at file:///home/evinfug/workspaces/theia/examples/electron/lib/50.bundle.js:1325:51
```

#### Steps to Reproduce:

1. Start the application, and open a TS/JS file.
2. Open the `devTools`.
3. Trigger the command `Find All References` on a symbol.

https://user-images.githubusercontent.com/40359487/114728183-de51c000-9d0c-11eb-8c85-8d72f43f183f.mp4

#### Additional Information

- Operating System: Ubuntu 16.04
- Theia Version: a1f5e59

**Comment by colin-grant-work** [comment]
The details here seem to be that when a plugin invokes a command to open a widget, and when we open / activate widgets, we also return them.

![image](https://user-images.githubusercontent.com/62660806/114938207-72eb1980-9e04-11eb-97e6-cb9462dab1cb.png)

On the other hand, it seems that Che is/was having the opposite problem: the references view not activating: https://github.com/eclipse/che/issues/18953.
