### ISSUE TITLE
[docker theia-full:latest] Git Clone from gitlab and gogs does not work

### ISSUE THREAD

**Issue by erdalkaraca** [eclipse-theia/theia#9356]
### Bug Description:
Git cloning from a gitlab or gogs repository does not work, i.e. I can see an empty (bare) git repo created, but the contents are not fetched - I tried with both public and private repos.
Cloning from a github repo works as expected.

### Steps to Reproduce:

Call Git Clone command and enter a repo URL from either gitlab or gogs.

### Additional Information
Using docker image theia-full:latest.

**Comment by vince-fugnitto** [comment]
@erdalkaraca thank you for the issue, can you please open the issue under https://github.com/theia-ide/theia-apps (which I believe is the proper location). It's possibly a permission issue.

**Comment by vince-fugnitto** [comment]
Closing in favor of https://github.com/theia-ide/theia-apps/issues/474.
