### ISSUE TITLE
tasks: properly type task.taskType?

### ISSUE THREAD

**Issue by paul-marechal** [eclipse-theia/theia#9357]
Follow up on https://github.com/eclipse-theia/theia/pull/9352

https://github.com/eclipse-theia/theia/pull/9189 refactored some interfaces, and something like `taskType` seems to have a use in our system, but it is left out of the new interfaces now for some reason.

It's rather confusing to use this field since we can't rely on typing to understand where it is set, if set at all...

**Comment by tsmaeder** [comment]
I think this is a duplicate of https://github.com/eclipse-theia/theia/issues/9333: what we call "taskType" is really selecting the execution engine, but everywhere else, we should use the contributed type.

**Comment by marechal-p** [comment]
Agreed! But until this field is refactored away I think I'd keep this issue opened. I'll keep an eye on https://github.com/eclipse-theia/theia/issues/9333.

**Comment by tsmaeder** [comment]
@paul-marechal `TaskDto.taskType` is now typed as ` taskType?: 'shell' | 'process' | 'customExecution'`. Does that satisfy you?

**Comment by paul-marechal** [comment]
I am satisfied.
