### ISSUE TITLE
Support "editor/title/run" toolbar commands

### ISSUE THREAD

**Issue by DanTup** [eclipse-theia/theia#9387]
VS Code added a new contribution for editor toolbar icons: "editor/title/run" and encouraged extensions to move their Run/Debug icons to them:

https://github.com/microsoft/vscode/commit/97c7d2ac84b851285649e2d0acb228867eddaab1

https://code.visualstudio.com/updates/v1_54#_limits-for-editor-title-menu-and-run-submenu:~:text=added%20the%20editor%2Ftitle%2Frun%20submenu

As a consequence, these buttons have disappeared from Theia, as it doesn't read commands from there.

Pushing them onto the front of `editor/title` commands may be an easy fix to support them, though VS Code goes a little further and collapses them into a single button with a drop-down menu:

<img width="340" alt="Screenshot 2021-04-21 at 13 57 53" src="https://user-images.githubusercontent.com/1078012/115557418-99e49800-a2a9-11eb-8335-b5eb708ec806.png">

Example definition: https://github.com/Dart-Code/Dart-Code/blob/393763bc887dce42953646e3ea7381060beefd93/package.json#L1059-L1071

**Comment by Tpuljak** [comment]
Would very much love to see this implemented. Extensions like [Code Runner](https://github.com/formulahendry/vscode-code-runner) greatly improve UX using the run menu.
