### ISSUE TITLE
Application crashes at startup with certain combinations of files open

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#9394]
### Bug Description:

Having certain files open on startup causes a fatal crash due to an 'Out of memory' error.

### Steps to Reproduce:

1. Build either browser or electron target.
2. Open the application and open the Theia repo as a workspace
3. Open these three files (or the 6 in the screenshot below, but these three seem to suffice):
![image](https://user-images.githubusercontent.com/62660806/115769368-168e7980-a371-11eb-8548-9e98a4c79e63.png)
4. Focus the `tsconfig.json`
5. Restart the application
6. When the application starts, it will(?) be unresponsive.

The Electron version logs this error:
![image](https://user-images.githubusercontent.com/62660806/115769514-3de54680-a371-11eb-823d-dbd9eb57ed4c.png)
In FireFox, the browser, gives this warning:
![image](https://user-images.githubusercontent.com/62660806/115769878-ad5b3600-a371-11eb-81f7-db281b410353.png)
and logs this error if you terminate the script:
![image](https://user-images.githubusercontent.com/62660806/115769645-63725000-a371-11eb-9dcd-468f3f760484.png)

### Additional Information

- Operating System: RHEL7
- Theia Version: reproduced with 66b3dc3ba38604fcde3498796fc58a12ffcd8589 and v. 1.12.1

**Comment by colin-grant-work** [comment]
I've been able to reproduce it consistently even after cleaning out node modules and reinstalling, restarting machine, etc., but others in same environment haven't seen the same crash. Curious if other see the same or similar behavior.

**Comment by RomanNikitenko** [comment]
Tested for the browser assembly on Fedora - I was not able to reproduce the issue.
Could you check if you have installed additional Theia plugins or VS Code extensions - maybe the problem is related to a plugin or an extension...

**Comment by colin-grant-work** [comment]
It does happen during the plugin startup process, so I think some plugin is a likely culprit, but I've just got the standard pack downloaded by the build process - no extras, at the moment.

**Comment by colin-grant-work** [comment]
I can no longer reproduce this crash.
