### ISSUE TITLE
monaco: fix peek fontFamily styling

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9458]
#### Bug Description:

The `peek` `fontFamily` should be updated:

_theia_:

![image](https://user-images.githubusercontent.com/40359487/117694173-d3177600-b18c-11eb-9caf-4391978b6c3b.png)

_vscode_:

![image](https://user-images.githubusercontent.com/40359487/117694339-08bc5f00-b18d-11eb-8824-5646ef706f55.png)

#### Steps to Reproduce:

1. start the application, and open a typescript file.
2. perform `peek` > `peek definition` on a symbol using the context-menu.
3. notice the font-family styling.

**Comment by msujew** [comment]
@vince-fugnitto This seems to be fixed by the monaco upgrade. This is how it currently looks in Theia:

![image](https://user-images.githubusercontent.com/4377073/125414141-5003d6ae-3f89-4095-96f3-a00c3d723607.png)
