### ISSUE TITLE
vscode.window.showOpenDialog - filter is not applied by default

### ISSUE THREAD

**Issue by amiramw** [eclipse-theia/theia#9468]
### Bug Description:

When calling vscode API vscode.window.showOpenDialog with filter, the file dialog is opened with "all files" format by default.
In VS Code the dialog is opened with the provided filter applied by default.

Relevant code snippet:

```
const options = {
	canSelectMany: false,
	openLabel: 'Select',
	canSelectFiles: true,
	canSelectFolders: false,
	filters: {
		'test': ['txt']
	},
	defaultUri: vscode.Uri.file('C:\\')
};
vscode.window.showOpenDialog(options)
```

### Steps to Reproduce:

1. Deploy vscode extension from this zip: 
[helloworld-0.0.12.zip](https://github.com/eclipse-theia/theia/files/6464691/helloworld-0.0.12.zip)
2. F1 -> Hello World
3. File dialog is opened with format "All Files" instead of "test". 
![image](https://user-images.githubusercontent.com/9420921/117943816-33392400-b315-11eb-887f-d9de97517460.png)

In vscode it works correctly

### Additional Information

- Operating System: Windows / debian
- Theia Version: master, 1.13.0, 1.12.0

**Comment by danarad05** [comment]
@amiramw 

> When calling vscode API vscode.window.showOpenDialog with filter, the file dialog is opened with "all files" format by default.
In VS Code the dialog is opened with the provided filter applied by default.

Just to make sure - in VS Code it displays "test(*.txt)" filter only - it doesn't display "All Files". That is what you are expecting in Theia also?

**Comment by amiramw** [comment]
I think at least we should make the filter default
