### ISSUE TITLE
Prompted to save when multiple editors open for same file 

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#9474]
### Bug Description:

Related to #9369, if a file is opened in multiple editors and is dirty, the user shouldn't be prompted to save the file when closing editor instances until the last instance remains. 

### Steps to Reproduce:

1. Open multiple editors for the same file (use keyboard shortcut `ctrl + \`
2. Make some edits to the file and don't save
3. Attempt to close one instance of the editors
4. Observe that you are prompted to save the same even though other open instances remain

### Additional Information

- Operating System: Linux
- Theia Version: Master

**Comment by vince-fugnitto** [comment]
We might be able to do it generally if we handle https://github.com/eclipse-theia/theia/issues/4849.
