### ISSUE TITLE
Race condition in Editor Preview Manager and Editor Manager

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#9485]
### Bug Description:

If two open requests come in nearly simultaneously, one asking for a preview widget and one asking for a non-preview widget, a race condition in the opening routines of the `EditorPreviewManager` and `EditorManager` can lead to an empty editor preview next to an open normal editor and a broken shell / widget tracking system.

### Steps to Reproduce:
> It's finicky
1. Install the [`vscode-clangd` plugin](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) 
2. Find an `#include` directive pointing to an unambiguous filename in your workspace.
3. `Ctrl+Click` that filename.
4. You may (or may not) get bad behavior.

#### Alternatively:
1. Add a command like this somewhere in the repo:
```
        commands.registerCommand({ id: 'bad-opener-behavior', label: 'Try to open an editor two ways.' }, {
            execute: () => {
                const uri = new URI('<path to Theia>/devfile.yaml');
                open(this.openerService, uri, { preview: true });
                open(this.openerService, uri);
            }
        });
```
2. Run that command
3. You may (or may not) see something like this:

![image](https://user-images.githubusercontent.com/62660806/118290840-7f62a080-b49c-11eb-8d3c-3f654ae059d4.png)

What appears to be happening is that the `EditorPreviewManager` checks for the existence of an editor for the file its trying to open (line 124), and if it doesn't find it, it does some other `async` work (lines 137ff) before trying to open a new editor (line 139 or 146) for that file. If, between the failed check and the actual opening of a new editor, the `EditorManager` has separately handled a request to open the same file, the two openers can come into conflict.

https://github.com/eclipse-theia/theia/blob/d734315e505ad4a7691a3f6f4a07d2209af0d9cf/packages/editor-preview/src/browser/editor-preview-manager.ts#L113-L143

I've only consistently reproduced the behavior on branches with #9369, but I don't believe that the bug is actually related to that change. 

### Additional Information

- Operating System: RHEL7
- Theia Version: 1.13.0

**Comment by kenneth-marut-work** [comment]
I actually noticed this issue rather frequently while working on #9284, which predates #9369. Although I'm not sure the specific steps to reproduce, it seemed to pop up during the development cycle of watching and restarting Theia.

**Comment by colin-grant-work** [comment]
Looks like this duplicates / is related to #8511.
