### ISSUE TITLE
Dragging Preview Editor to Side Dock Panel Breaks Editor

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#9487]
### Steps to Reproduce:

1. Open an editor in preview mode.
2. Drag it into a side panel.
3. Its content and icon will disappear.

![bad-tab-drag](https://user-images.githubusercontent.com/62660806/118302778-429da600-b4aa-11eb-805e-67a23a6bbdd5.gif)

### Additional Information

- Operating System: RHEL7 - Electron
- Theia Version: d734315e505ad4a7691a3f6f4a07d2209af0d9cf

**Comment by vince-fugnitto** [comment]
Duplicate of https://github.com/eclipse-theia/theia/issues/4719?

**Comment by colin-grant-work** [comment]
Yes, quite right!
