### ISSUE TITLE
Breakpoint expression input field does not auto resize

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#9526]
### Bug Description:
When trying to add a conditional breakpoint or logpoint to an editor, the input field does not automatically resize. This can make reading the placeholder message or the input expression quite difficult.

![bad-resizing](https://user-images.githubusercontent.com/62660714/119887903-57425b00-befa-11eb-80b9-a17581cbb1e5.gif)

### Steps to Reproduce:

1. Open a source code file (or a file in which you can set a breakpoint)
2. Make the window size fairly narrow
3. Right click in editor's the left gutter to "Add Conditional Breakpoint" or "Add Logpoint"
4. Maximize the window and observe that the input field does not resize

### Additional Information

- Operating System: Linux
- Theia Version: Master (Electron and Browser)

**Comment by vince-fugnitto** [comment]
The same occurs for the `peek widget`:

![image](https://user-images.githubusercontent.com/40359487/120221751-f1611680-c20c-11eb-9b0e-da124a751b1a.png)

![image](https://user-images.githubusercontent.com/40359487/120221771-fa51e800-c20c-11eb-8d5c-123e647601eb.png)
