### ISSUE TITLE
tree-view: enable tree search and filtering for trees contributed by plugins

### ISSUE THREAD

**Issue by idoprz** [eclipse-theia/theia#9533]
### Bug Description:

The goal is to enable searching and filtering in contributed tree-views when typing similarly to trees contributed by the framework (ex: `explorer`, `scm`, `outline`). The tree search and filtering is supported in vscode, and should be supported by tree-views contributed by plugins as well.

### Steps to Reproduce:

1. start the application
2. open the explorer, and ensure that `npm scripts` tree-view part is visible
3. attempt to search in it by typing - nothing occurs
4. attempt the same use-case in vscode - tree search and filtering is supported

### Additional Information

- Operating System: all
- Theia Version:

**Comment by vince-fugnitto** [comment]
@idoprz can you clarify which tree(s) you were expecting the filtering for?
The filtering occurs for the following trees as part of the application (corresponding [review](https://github.com/eclipse-theia/theia/pull/8540#pullrequestreview-504160776)):
- `explorer`
- `scm`
- `outline`

**Comment by idoprz** [comment]
Hi,
I mean on trees from extensions. Right now it only works for the "build in extensions" as you said explorer, scm, outline.
On VSCode the filter works for extensions trees as well.

**Comment by vince-fugnitto** [comment]
@idoprz I took the liberty of updating the title and description and use-case (npm scripts) so things are a bit clearer.

**Comment by shuyaqian** [comment]
> @idoprz I took the liberty of updating the title and description and use-case (npm scripts) so things are a bit clearer.

Is this question in the development plan for the next release? I've had the same problem with no search function when there are long lists in extension and the experience is really not good.
