### ISSUE TITLE
Program files created world writable

### ISSUE THREAD

**Issue by ghost** [eclipse-theia/theia#9564]
### Bug Description:

Some program files are created world writable. On a multiuser system this may allow an attacker to control behavior by modifying the files (eg a config file). On Linux the umask should usually prevent this but it's not guaranteed. [Secure coding standards](https://wiki.sei.cmu.edu/confluence/display/c/FIO06-C.+Create+files+with+appropriate+access+permissions) recommend always specifying a restricted mode so files are secure in any environment. MITRE calls this [CWE-732](https://cwe.mitre.org/data/definitions/732.html), one of the [top 25 most dangerous](https://cwe.mitre.org/top25/archive/2020/2020_cwe_top25.html) vulnerabilities.

Findings are listed here:
https://lgtm.com/query/8754882199744511397/

One result seems to be in a general "write file" method, possibly used in multiple places. The `trash` result is because the module uses insecure permissions on Linux, possibly exposing sensitive deleted data to other users.

This came out of research with CodeQL.

**Comment by sh7dm** [comment]
This looks like upstream bugs in libraries. See https://github.com/jprichardson/node-fs-extra/blob/master/lib/ensure/file.js#L10

**Comment by dittyroma** [comment]
FYI guys that the latest `trash` v7.2.0 tightens permissions, from this patch.

https://github.com/sindresorhus/trash/pull/115

> This looks like upstream bugs in libraries. See https://github.com/jprichardson/node-fs-extra/blob/master/lib/ensure/file.js#L10
> 
> It's the function which creates file without specifying permissions

I know it. Brought it up with the project but they didn't think it was important.

https://github.com/jprichardson/node-fs-extra/issues/907

I did publish [`secure-fs-extra`](https://www.npmjs.com/package/secure-fs-extra) which uses secure default modes everywhere, so it's a possibility.

**Comment by vince-fugnitto** [comment]
@dittyroma thank you for your investigation and highlighting potential issues with dependencies.

> FYI guys that the latest trash v7.2.0 tightens permissions, from this patch.
> sindresorhus/trash#115

Are you interested in contributing a pull-request to bump the version of `trash` the framework uses to make use of your security patch?

**Comment by dittyroma** [comment]
Yes! Will look into a patch.

**Comment by vince-fugnitto** [comment]
Closing, `trash` was updated.
