### ISSUE TITLE
Git UI plugin doesn't accept a different SSH key name than id_rsa

### ISSUE THREAD

**Issue by anavarre** [eclipse-theia/theia#9574]
### Bug Description:

We're naming SSH keys with the format `id_rsa_label_<uuid>`

When we do so, interacting with the built-in Git UI immediately fails with the following message:

> Request <fetch> failed with message: Authentication failed. You may not have permission to access the repository or the repository may have been archived

https://user-images.githubusercontent.com/293478/121483683-c45ff100-c9ce-11eb-91a8-59ba82f2f42a.mp4

When we wipe the key and create a new one called `id_rsa`, Git UI operations work fine.

https://user-images.githubusercontent.com/293478/121483712-caee6880-c9ce-11eb-9434-97abce113a55.mp4

### Steps to Reproduce:

1. Create an SSH key that is not with the format `id_rsa`.
2. Attempt performing a pull, fetch or push operation.
3. Observe you're getting a notification with the error.

### Additional Information

- Operating System: Ubuntu Xenial
- Theia Version: 1.13.0

**Comment by vince-fugnitto** [comment]
@anavarre can you confirm if you are using `@theia/git` extension or the `vscode-builtin-git` plugin to provide git support?
If vscode supports the `id_rsa_label_<uuid>` format you may think about moving towards using the `vscode-builtin-git` plugin instead for your application (which includes additional features and permits the use of other git-related extensions such as gitlens).

**Comment by anavarre** [comment]
Confirmed. We're using `@theia/git 1.13.0` indeed. Following your suggestion we'll likely explore `vscode-builtin-git`. Thank you.

I'm not sure whether you intend to fix the behavior with the built-in plugin. If not, feel free to close this out.

**Comment by anavarre** [comment]
Oh, one more thing. https://www.npmjs.com/package/@theia/vscode-builtin-git was last updated 2 years ago. Not sure what to think of that.

**Comment by vince-fugnitto** [comment]
> Oh, one more thing. https://www.npmjs.com/package/@theia/vscode-builtin-git was last updated 2 years ago. Not sure what to think of that.

@anavarre I'm referring to the actual `git` plugin hosted on the open-source marketplace `open-vsx`:
- https://open-vsx.org/extension/vscode/git

**Comment by anavarre** [comment]
Thanks for clarifying :+1: . I had not explored the OpenVSX route yet.

**Comment by anavarre** [comment]
For whatever reason we cannot yet explain, with Theia 1.26 this is no longer happening. Closing.
