### ISSUE TITLE
Git UI plugin only accepts passwordless SSH keys

### ISSUE THREAD

**Issue by anavarre** [eclipse-theia/theia#9575]
### Bug Description:

When a passphrase is added to an SSH key (confirmed by the encrypted key when reading the file), the Git UI fails to perform operations and returns the below message:

> Request failed with message: Authentication failed. You may not have permission to access the repository or the repository may have been archived

https://user-images.githubusercontent.com/293478/121486724-b19aeb80-c9d1-11eb-8308-92a330ffbf12.mp4

However, when we have a passwordless key (confirmed by the lack of encryption in the key), operations work well.

https://user-images.githubusercontent.com/293478/121486714-ae9ffb00-c9d1-11eb-932f-e3cf58dd40a7.mp4

### Steps to Reproduce:

1. Create a passphrase for your SSH key
2. Try to perform Git operations
3. Observe you get a notification message with the error

### Additional Information

- Operating System: Ubuntu Xenial
- Theia Version: 1.13.0

**Comment by vince-fugnitto** [comment]
It would be good to confirm if this issue is also resolved by using the `vscode-builtin-git` extension as discussed in https://github.com/eclipse-theia/theia/issues/9574. We can keep it open as a tracker for `@theia/git` however.

**Comment by anavarre** [comment]
Will absolutely report back. Thanks!

**Comment by anavarre** [comment]
Installed the extension

![git-openvsx](https://user-images.githubusercontent.com/293478/121661198-3fdfa200-caa4-11eb-8c44-513cb948815a.png)

Confirmed the new menu items are there

![git-openvsx-menu](https://user-images.githubusercontent.com/293478/121661195-3fdfa200-caa4-11eb-8b87-a961a258cc52.png)

...But sadly this is still happening. #9559 wouldn't be a big deal, but the passwordless SSH is more problematic because it weakens the security model.

**Comment by vince-fugnitto** [comment]
@anavarre does it work for you out-of-the-box in vscode? I see the following issue for example: https://github.com/microsoft/vscode/issues/13680.

**Comment by anavarre** [comment]
@vince-fugnitto I'm not sure I'm a good candidate for testing this because on Manjaro (KDE) I don't have `ssh-askpass` installed, which then gets VSCode running into:

```
> git fetch
ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by anavarre** [comment]
ATM we are exploring whether https://www.npmjs.com/package/dugite has any support for passphrases. It seems if an upstream contribution had to be made it'd be in this package so Theia could inherit from the fix.

**Comment by anavarre** [comment]
> @anavarre does it work for you out-of-the-box in vscode? I see the following issue for example: microsoft/vscode#13680.

I had a colleague test on a Mac and local VSCode with Git integration works with a local passphrase.

**Comment by anavarre** [comment]
We haven't yet looked in details but it might seem we would have to contribute a patch upstream in https://www.npmjs.com/package/dugite - We'll look into our options.

**Comment by anavarre** [comment]
We've been trying to understand and debug the code written for the Git plugin (https://github.com/eclipse-theia/theia/tree/master/packages/git) but didn't got any clue. So far we have identified files which are basically driving the frontend execution:

* git-frontend-module.ts
* git-scm-provider.ts
* dugite-git.ts

But no luck as to how to resolve the issue so the Git UI plugin accepts the SSH key passphrase.

Would you have any idea where to take it from here?

**Comment by SamFoster** [comment]
Has there been a fix for this issue yet?

**Comment by vince-fugnitto** [comment]
> Has there been a fix for this issue yet?

@SamFoster I do not believe so, the framework supports consuming the builtin (included in vscode itself) `git` plugins from vscode ([vscode-builtin-git](https://open-vsx.org/extension/vscode/git), [vscode-builtin-git-ui](https://open-vsx.org/extension/vscode/git-ui)), and it does not look like they support it yet https://github.com/eclipse-theia/theia/issues/9575#issuecomment-859530721.

**Comment by SamFoster** [comment]
Vincent

Thanks for the reply. I've been having a play, and forgive me if this is stuff you guys are already aware of, but I have found that if I have my remote set as https and also I have used 'gh auth status' to view my connection info is set to use https and a token - which it now has to be - then I get a working set of tools in the GUI and can push/pull etc as required.

 (also useful to know  'gh auth' to view list of useful gh auth commands such as those that run through the authentication wizard again etc)

Is there anything wrong​ with me doing this, and have I just discovered a legit way round the issue if connected to the remote via SSH?

Thanks,

Sam
________________________________

**Comment by anavarre** [comment]
Question you asked a while ago https://github.com/eclipse-theia/theia/issues/9575#issuecomment-859530721

> @anavarre does it work for you out-of-the-box in vscode? I see the following issue for example: https://github.com/microsoft/vscode/issues/13680.

Was finally able to test with a Mac and it works immediately, or at least doesn't seem to fail.

![vscode-git-ui](https://user-images.githubusercontent.com/293478/159905122-246a5118-9b66-4145-a34f-9c82e3cdbcc6.gif)

Can also confirm the issue is still occurring with Theia 1.21. Tried the `vscode-builtin-git` OpenVSX extension again and it fails there too. New error window and new way to check the associated log file though.

<img width="393" alt="Screen Shot 2022-03-24 at 13 18 12" src="https://user-images.githubusercontent.com/293478/159914654-09e820e3-d548-433c-809f-cb1390c46ca8.png">


```
Looking for git in: git
Using git 2.35.1 from git
> git rev-parse --git-dir
Open repository: /home/ide/project
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/pipelines-build-master refs/remotes/pipelines-build-master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
Warning: Failed to watch ref '/home/ide/project/.git/refs/remotes/origin/pipelines-build-master', is most likely packed.
> git config --get commit.template
> git fetch
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Still the same stubborn issue with passphrases. I don't fully comprehend whether there's any chance it ever works without getting https://github.com/microsoft/vscode/issues/13680 fixed first.

**Comment by SamFoster** [comment]
So I have found that it fails when I use an ssh remote, but if I switch to https for the remote, and I use 'gh auth login' at cmd prompt to authenticate and use a personal access token it works using the gui buttons as one would expect. It is however sometimes a bit slow, and if I push/pull via the git cmdline the gui itself doesn't update that fast and leads u to think the push/pull may not have worked - but it has and after some seconds the gui does update to reflect this.



Thanks,

Sam

Sam Foster
Bangor University
________________________________

**Comment by anavarre** [comment]
Interesting. Unfortunately we don't have the option to use `https` for Git remotes so I can't try out your workaround. Nice find though!

**Comment by anavarre** [comment]
For whatever reason we cannot yet explain, with Theia 1.26 this is no longer happening. Closing.
