### ISSUE TITLE
Workspace service contains private modifiers

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#9591]
### Bug Description:
In `workspace-service.ts`, there are several members/methods that use the `private` modifier. These modifiers make it difficult to override functionality and are likely unnecessary. This also causes issues when attempting to reference a `private` member from another method inside an override. They should likely be changed to `protected` unless there is any clear reason not to.

**Comment by jyggiz** [comment]
Hey, can I take this issue?

**Comment by kenneth-marut-work** [comment]
> Hey, can I take this issue?

@jyggiz sure, go ahead!
