### ISSUE TITLE
User defined tasks are not revealed when these are executed programmatically

### ISSUE THREAD

**Issue by sunix** [eclipse-theia/theia#9605]
### Bug Description:
User defined tasks are not revealed when these are executed programmatically.

### Steps to Reproduce:

1. clone/build and execute this VSCode extension on theia hosted mode  https://github.com/sunix/vscode-test-task-execution
2. create a user `shell` task with the `Task: Configured tasks ...` > `Configure new Task` > `Others`  command, keep the default values:
    ```
    {
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "echo",
			"type": "shell",
			"command": "echo Hello"
		}
	]
    }
    ```
3. Run the command `vscode.tasks.executeTask the task named 'echo'`, this command will execute the task named `echo` with the api method `vscode.tasks.executeTask(t);`
4. no task is reveal. But the task is executed in background.

### Additional Information
It seems that the task object generated has https://github.com/sunix/vscode-test-task-execution/blob/e03b3fe41c2ce8e9c7a034542a77ad16bc3ea464/src/extension.ts#L28
```
                  presentationOptions: {
                    reveal: 'always',
```
instead of 
```
                  presentationOptions: {
                    reveal: 1,
```
(1 is the value for vscode.TaskRevealKind.Always)

There is 2 additional commands that execute a Task object to see the diff:
- the command `vscode.tasks.executeTask with presentationOptions: { reveal: 'always' }` with `presentationOptions: {  reveal: 'always' }`. This is a copy of what we get when fetching a task created by the user.
- the command `vscode.tasks.executeTask with presentationOptions: { reveal: 1}` the other with `presentationOptions: {  reveal: 1 }` that  reveals the task as expected.

#### Environment
- Operating System: kubernetes
- Theia Version: master branch

**Comment by tsmaeder** [comment]
Hmhh...it looks to me as if in your sample code, you're using an invalid value for the `reveal` field:
``` 
 reveal: JSON.parse('"always"'), // KO the task is not revealed
```
should not even compile

**Comment by sunix** [comment]
@tsmaeder yeah it's not compiling if I use 
```
reveal: 'always'
```
but the `JSON.parse` is getting through the type check

**Comment by sunix** [comment]
this part is to recreate the same json object I got from the one I created by hand.

**Comment by tsmaeder** [comment]
@sunix sorry, but I don't see how the example code demonstrates a problem: as far as the API goes, I see "garbage in, garbage out". I think you need to elaborate a bit more.

**Comment by sunix** [comment]
@tsmaeder ok I am reworking this

**Comment by tsmaeder** [comment]
@sunix maybe it's enough if you just explain what the problem is.

**Comment by sunix** [comment]
@tsmaeder I have updated the sample and description.

**Comment by tsmaeder** [comment]
@sunix where do you see "Task: Configured tasks ... > Configure new Task > Others"? Is this a menu? Do you open the command palette? Both paths don't lead to anything for me in Theia master.

**Comment by sunix** [comment]
command palette yes theia master

**Comment by tsmaeder** [comment]
I don't see "Configure new task..." when I execute "Configure Task...", just a list of tasks.

**Comment by sunix** [comment]
@tsmaeder scroll down

**Comment by tsmaeder** [comment]
The problem really seems to be that when you do "vscode.tasks.fetchTasks()", you get back an object that has
```
reveal: 'always',
```
in its presentation, when in fact it should be an integer-value enum.

**Comment by sunix** [comment]
maybe this is all wrong: https://github.com/eclipse-theia/theia/blob/master/packages/task/src/browser/task-schema-updater.ts#L551-L608

**Comment by tsmaeder** [comment]
Methinks the conversion in TasksMainImpl#fetchTasks() is broken: it does not convert the presentation options to the correct type in the TaskDTO.
