### ISSUE TITLE
Calls: Show Call Hierarchy command doesn't work

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#9612]
### Bug Description:
I get an error `Cannot use 'in' operator to search for 'uri' in undefined` at using `Calls: Show Call Hierarchy` command.
Also the corresponding panel is empty - it doesn't display the result of command execution.   

### Steps to Reproduce:

Try to use `F1`=> `Calls: Show Call Hierarchy`  command.
Please see videos.

### Additional Information

- Operating System: Fedora
- Theia Version: 55b55eec6af8b50ae61fc21bc0cd46a6c52d3272

![call_hierarchy](https://user-images.githubusercontent.com/5676062/122606230-42805f80-d081-11eb-8fc5-81172eb2454b.png)

Actual behavior:

https://user-images.githubusercontent.com/5676062/122606341-78254880-d081-11eb-8409-702cae4a3309.mp4

Expected behavior:

https://user-images.githubusercontent.com/5676062/122606609-e8cc6500-d081-11eb-8085-a2f9ddc7a80f.mp4

**Comment by colin-grant-work** [comment]
@RomanNikitenko, I get bad behavior - no results in the tree - but different logs when I try to reproduce this:
![image](https://user-images.githubusercontent.com/62660806/123458126-4b55c180-d5aa-11eb-977c-b319eab5cb5b.png)

The error shown in your console is pretty easy to fix, but it looks like it's a red herring - fixing the `'uri' in selection[0]` check in the timeline package doesn't seem to help the call hierarchy show up in the references widget.

**Comment by colin-grant-work** [comment]
It looks like the problem traces back to this command call:
https://github.com/eclipse-theia/theia/blob/144da47ee447017345f447477efc4baf3ba9e65c/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L539-L547
I've built a local version of the plugin, and the data seems to be flowing correctly, but when it reaches this call
https://github.com/microsoft/vscode-references-view/blob/870c7f3098f10090581215fbc7fcf1af23e19b40/src/calls/model.ts#L27
the result is empty.
To be continued... :-)

**Comment by RomanNikitenko** [comment]
@colin-grant-work 
thank you for the investigation!

about
> Was it previously working?

I did `git check out v1.4.0 ` to check if it's side effect of the previous `Monaco` upgrade.
The result - the command is still not working for me.
So, I believe the current issue is not related to the previous `Monaco` upgrade and we have this problem quite long time...

**Comment by colin-grant-work** [comment]
@RomanNikitenko, it looks like there are a few unimplemented utilities related to the call hierarchy. For example these type guards:

https://github.com/eclipse-theia/theia/blob/bd12178470c124448c06d1e9bb94291f7d9547dc/packages/plugin-ext/src/plugin/type-converters.ts#L634-L656

But there's code for all of the major call hierarchy functionality, so it looks like it'll just be a matter of hooking (mostly) existing code up correctly to meet plugin expectations, so I'm happy to do some work on it.
