### ISSUE TITLE
Consider to use parceljs instead of webpack

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#966]
https://parceljs.org/

**Comment by akosyakov** [comment]
We should try webpack 4 as well: https://medium.com/webpack/webpack-4-released-today-6cdb994702d4

**Comment by svenefftinge** [comment]
Why?

**Comment by svenefftinge** [comment]
Ah, they are much faster :-)

**Comment by akosyakov** [comment]
They also do better tree shaking and improve defaults, so smaller output and less config and additional dependencies for loaders.

**Comment by JonasHelming** [comment]
Update to webpack 4 has been done: https://github.com/eclipse-theia/theia/pull/1540/

As this has been inactive for quite a while I suggest to close this, any objections?

**Comment by vince-fugnitto** [comment]
Closing, we can investigate options to switch bundler if we meet limitations, and/or want other improvements.
