### ISSUE TITLE
Rename of files and folder are case insensitive

### ISSUE THREAD

**Issue by AirSeeker** [eclipse-theia/theia#9663]
### Bug Description:
On rename files or folders the registry is not taking into count.
The rename should be case-sensitive.

### Steps to Reproduce:

1. Create a new file.
2. Change some characters of the file name to a different registry.
3. Wrong error appears about the file already exists.

![image](https://user-images.githubusercontent.com/16229329/123766239-2ffef500-d8cf-11eb-99a6-abcdd297fc03.png)

### Additional Information

- Operating System: Windows 10
- Theia Version: 1.14.0

**Comment by vince-fugnitto** [comment]
@AirSeeker I was unable to reproduce the issue (I can go from `Untitled.txt` > `untitled.txt` and back fine).

https://user-images.githubusercontent.com/40359487/123794065-72fda000-d8b0-11eb-91f7-809be4e13d2b.mp4

I am on Linux however, is it something you're interested in working on, and ensuring works correctly on Windows?

**Comment by msujew** [comment]
@vince-fugnitto Windows treats file paths completely case insensitive. Therefore, `Untitled.txt` and `untitled.txt` are exactly the same file path. I guess that's the reason behind that behavior.
