### ISSUE TITLE
Update debug API to support Parent Sessions

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#9664]
### Feature Description:
The VS Code API now supports the notion of a "parent" debug sessions. It allows to group subprocesses being debugged (for example the plugin host process when debugging Theia itself) into a convenient tree. 
In order to see this in action, use the vscode built-in js-debug to debug the Theia back end.

**Comment by msujew** [comment]
I think this will be addressed by #9613.

**Comment by tsmaeder** [comment]
Cool, closing as duplicate of https://github.com/eclipse-theia/theia/issues/8518
