### ISSUE TITLE
In VSCode extensions TreeView selection is always empty

### ISSUE THREAD

**Issue by xcariba** [eclipse-theia/theia#9672]
### Bug Description:
If you have tree view in vscode extension and want to access current selection using `treeView.selection` property - it will always be empty.

### Steps to Reproduce:

1. Implement VSCode TreeView
2. Register it using `window.createTreeView(...)`
3. Register command that uses tree view instance and add `console.log('Len: ' + treeView.selection.length);`
4. It will always be empty

### Additional Information

- Operating System: Fedora
- Theia Version: 1.14 / master

**Comment by colin-grant-work** [comment]
closed via #9673
