### ISSUE TITLE
Test failure in examples/api-tests/src/file-search.spec.js 

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#9692]
After merging of https://github.com/eclipse-theia/theia/pull/9154, we have a test failure due to a newly introduced test (see https://github.com/eclipse-theia/theia/pull/9635). 

My guess is we need to replace QuickOpenItem with QuickPickItem, but not sure.

**Comment by RomanNikitenko** [comment]
![quickOpenItem](https://user-images.githubusercontent.com/5676062/124274506-06053700-db4a-11eb-96e7-0a348f6bd5b5.png)

**Comment by RomanNikitenko** [comment]
![quick_open](https://user-images.githubusercontent.com/5676062/124274737-4b296900-db4a-11eb-9916-b2c015e93daf.gif)

**Comment by RomanNikitenko** [comment]
@tsmaeder @EstherPerelman 
unfortunately, there are also failed tests not related to `file-search` 

![tests_api](https://user-images.githubusercontent.com/5676062/124293226-17a50980-db5f-11eb-80c7-85a53d98d0aa.png)
