### ISSUE TITLE
Greyed out gitignored files

### ISSUE THREAD

**Issue by kenneth-marut-work** [eclipse-theia/theia#9706]
### Feature Description:
In VSCode, gitignored files are greyed out in the file explorer, but not in Theia. It would be nice to have this functionality so that gitignored files will be known at a glance.

![image](https://user-images.githubusercontent.com/62660714/124666261-68747500-de73-11eb-8f3a-41b3af431483.png)

**Comment by vince-fugnitto** [comment]
@kenneth-marut-work I believe it is a duplicate of https://github.com/eclipse-theia/theia/issues/1564. I’d be fine with closing either or.

**Comment by kenneth-marut-work** [comment]
Ah, good catch. I'll close this issue. Thanks for the notice
