### ISSUE TITLE
Use a translation service for Theia's own translations

### ISSUE THREAD

**Issue by msujew** [eclipse-theia/theia#9708]
### Feature Description:

With #9538 we will add general i18n support for Theia. While most user facing content can be automatically translated using the vscode language packs, text that only exists in Theia won't be translated so easily. I don't think translating each contributed user facing string into 10+ languages is feasible for Theia on each PR. Therefore, we need to think of a solution how to translate Theia's own content.

Microsoft is using [`transifex`](https://www.transifex.com/) combined with the [`vscode-nls-dev`](https://github.com/Microsoft/vscode-nls-dev) package to generate json files from vscode's source which can then be machine translated into different languages.

My proposal would be to mimic the `vscode-nls-dev` behavior in a dev-package to create json files which be translated on each release.

**Comment by tsmaeder** [comment]
So the idea is to use the service to transform 'some string' to nls.translate('someStringKey', 'someString') and to write a json file of the form
```
{
   someStringKey: someString
...
```

not to actually use the service to do translations?

**Comment by tsmaeder** [comment]
Also, to me it's not quite clear how much of the Theia code is actually internationalized right now (after your related PR).

**Comment by msujew** [comment]
No, the idea is to build a new dev-package, that reads the `nls.translate('someStringKey', 'someString')` function calls in the code and generates a json file containing `{ "someStringKey": "someString" }`. Then we throw that json file at a translation service and receive a translated json file back. That's the way the `vscode-nls-dev` package works.

I haven't gone deep into how much of Theia would be translated by vscode language packs alone, but I assume its something like 90%+ in the commands and menus department. I imagine most messages won't be translated.

**Comment by msujew** [comment]
Alternatively, we could just write into our coding guidelines, that any translatable string should be added to the `nls.json` (or something similar), which will then be machine translated into `nls.de.json`, `nls.fr.json`... without the need to parse the code and generate the initial `nls.json`. That would however still require a machine translation step and the end/on release.

**Comment by tsmaeder** [comment]
Ok, so this simplifies adding keys to the nls.*.json files once we have internationalized the code. For the first step, we's still rely on manual inspection. In Eclipse IDE, there was a warning for untranslated strings that were not marked with `//non-nls` (or something like that). Any ideas on how to tackle that problem? Writing a tool that checks our code would not be that hard, I think with the Typescript tooling.

**Comment by msujew** [comment]
> Any ideas on how to tackle that problem? Writing a tool that checks our code would not be that hard, I think with the Typescript tooling.

Sure, since we are using `eslint` either way, we could implement it as an eslint plugin? Though maybe we should try to be a bit smarter with that than simply marking every string that's not annotated with the `eslint-ignore` comment. I'm thinking about having some sort of configurable `ID` rule that excludes technical IDs, and so on by default. Except for those, everything should be translated.

**Comment by vince-fugnitto** [comment]
@msujew just wanted to point out we have the `eslint-plugin` dev-package for custom eslint rules if you ever need to go that route: https://github.com/eclipse-theia/theia/tree/master/dev-packages/eslint-plugin.

**Comment by msujew** [comment]
@tsmaeder I've looked into how transifex works and I don't think it'll do a good job for Theia. There's just too much overhead. Instead I've revised the following plan to translate Theia's content:

* Store translatable content in a `nls.json` file. That could - in a later stage - be generated automatically.
* Build a new `i18n` dev-package that uses a machine translation API (think DeepL) to translate the `nls.json` into different languages.
  - This will only translate strings that are not already translated into the target language
  - Every translation will be kept in Git, similar to [vscode-loc](https://github.com/microsoft/vscode-loc).
  - Users that propose a better translation (compared to the machine translation) can use PRs.

A DeepL integration for the dev-package shouldn't be costly, as DeepL offers 500,000 free characters per month. My current estimation is that Theia has only around 5,000 characters of translatable content, which have to be multiplied by the number of languages that we want to support.

We can discuss this in more depth at the dev-meeting.

**Comment by tsmaeder** [comment]
We need to make sure we have the right to distribute the results of the translation: sometimes "free tier" services have restrictions on use. @msujew can you check the terms?

Brian King mentioned that we need to make sure we keep the translations that we ship are updated as the code evolves: maybe start with only a few languages and add more as we find maintainers.

**Comment by msujew** [comment]
@tsmaeder I looked at the terms and conditions of the [DeepL API](https://www.deepl.com/pro-license/). To my untrained eye the free tier seems to enjoy the same freedoms (as in: you're allowed to use the translations for your (commercial) application and distribute them) as the paid tier. Though, DeepL retains the rights to shut down the free tier at any time.
