### ISSUE TITLE
Upgrade 1.14.0 is causing problem with settings.json

### ISSUE THREAD

**Issue by sumitmotghare** [eclipse-theia/theia#9712]
### Bug Description:

- Upgrade 1.14.0 is causing a problem.
- We have settings.json file stored in `/home/ide/.theia/settings.json` and it does contains IDE preferences. These settings are working in version 1.13.0 but when we try to upgrade Theia to version 1.14.0 it start causing a problem.
- When we try to open a settings.json from FILE->Settings->Open Preferences->Edit in Settings.json it does open the settings.json file and I can see the copied preferences.
- But when we try to open the same via Debug->Open launch.json it does override the `settings.json` file first. If we click once again it opens `launch.json` file.
- For a workaround I tried to add configurations in settings.json at parent node and after that it stopped overriding the settings.json file but since configurations is unknown parent property for settings.json it does create a problem in Theia problems tab.
- FYI - We don't have launch.json file by default in our IDE as we didn't needed it. I tried to add default launch.json file but still it was overriding the settings.json file.

Attached is the Video for reference.

- Broken Configurations.
- In the below video you will be able to find that debug launch.json file is overriding the settings.json file.

https://user-images.githubusercontent.com/73994076/124892610-a3071a80-dff7-11eb-95ef-b831bad87229.mov

- Workaround I tried to add configurations in settings.json on parent node. It does resolve the problem of overriding settings.json but it doesn't seems to be right solution to tackle this problem.

https://user-images.githubusercontent.com/73994076/124893166-2163bc80-dff8-11eb-97ed-b60668022986.mov

### Steps to Reproduce:

1. Create IDE using Theia version 1.14.0 and Node v12.22.1. Make sure to keep settings.json with preferences before running the IDE. Attached is the sample settings.txt file - Rename the extension and keep it under /home/ide/.theia/settings.json
[settings.txt](https://github.com/eclipse-theia/theia/files/6783162/settings.txt)

2. Keep all the preferences in settings.json.
3. Open the Debug from left panel of the IDE
4. Click on either settings icon or try to add a new configuration. Also try to refer the first video - Broken configurations

PS - This issue happen only for the first time when you open and IDE and click on Debug settings icon. Once it overrides the settings.json file and create a new launch.json file it does not repeat it.

- I feel this issue have links with the earlier bug - https://github.com/eclipse-theia/theia/issues/9310 which got fixed in version 1.14.0. We never faced this challenge in version 1.13.0.

### Additional Information

- Operating System: Mac-OS & Linux 18.04
- Theia Version: 1.14.0

**Comment by colin-grant-work** [comment]
@sumitmotghare, thanks for reporting this issues. You're correct about the PR that introduced it. I've created a PR to fix it: #9719. In the meantime, the recommended workaround would be to store your `launch` configurations in `launch.json` rather than `settings.json`. In that case, this code will never touch your `settings.json` file. Apologies for the inconvenience!

**Comment by sumitmotghare** [comment]
> @sumitmotghare, thanks for reporting this issues. You're correct about the PR that introduced it. I've created a PR to fix it: #9719. In the meantime, the recommended workaround would be to store your `launch` configurations in `launch.json` rather than `settings.json`. In that case, this code will never touch your `settings.json` file. Apologies for the inconvenience!

Appreciated for your quick response 🙂
