### ISSUE TITLE
api-test: test failure following monaco upgrade #9154

### ISSUE THREAD

**Issue by EstherPerelman** [eclipse-theia/theia#9714]
### Bug Description:

Following #9702 which resolved 2 of 3 errors.
### Steps to Reproduce:

1. Remove the `.skip` from [this test](https://github.com/eclipse-theia/theia/blob/36b9092f2a1f742c7495074fa2d899400322a8d7/examples/api-tests/src/typescript.spec.js#L687)
2. From Theia root run command: `yarn test:browser`
3. An error appears:
 ![image](https://user-images.githubusercontent.com/71729183/124501298-f6942100-ddc9-11eb-8e4d-8d9f77098d9c.png)

### Additional Information

- Operating System: Windows
- Theia Version: master

**Comment by EstherPerelman** [comment]
As I wrote in [#9702 comment](https://github.com/eclipse-theia/theia/pull/9702#issuecomment-876403609):
There is a bug with `vscode` code, I am able to fix that by calling `editor.getControl().getModel().applyEdits(..)` twice, But it's not a real solution, What should I do?

**Comment by vince-fugnitto** [comment]
@EstherPerelman given that it is for test purposes, perhaps you can perform multiple edits with a comment mentioning the behavior in vscode? If multiple edits are required for the `codelens` to appear for references I'm not sure what else we can do.

I do notice the same behavior as you, however, if the method is proper from the start it will display the codelens when restarting the app:

```ts
export function foo(): void {
    return;
}
```
