### ISSUE TITLE
debug: launch configurations not available on firefox

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9716]
#### Bug Description:

The `launch.json` debug configurations are not available on **firefox** (chrome and electron are fine).

https://user-images.githubusercontent.com/40359487/124939213-ed2bd400-dfd6-11eb-923d-58f8fd5a41c0.mp4

#### Steps to Reproduce:

1. start the browser application with `theia` as workspace folder.
2. open firefox, and navigate to the `debug-view`.
3. notice that debug `launch` configurations are not available from the dropdown.

**Comment by tsmaeder** [comment]
I can reproduce the problem with Chromium on master, as well. Luckily, I have a fix ;-)
