### ISSUE TITLE
1.15.0 breaks "Python Refactor: Sort Imports"

### ISSUE THREAD

**Issue by alancummings** [eclipse-theia/theia#9718]
### Bug Description:
When I try to run the "Python Refactor: Sort Imports" command, I get a pop-up window with the message "Please open a Python file to sort the imports."

- The "Sort Imports" command worked in 1.14.0, and works again if I revert back to 1.14.0

### Steps to Reproduce:

1. Open a python (*.py) file
2. Shift-Ctrl-p
3. Select "Python Refactor: Sort Imports"

- ms-python.python version 2020.10.332292344
- built-in plugins at version 1.56.2
- prerequisites for running "Sort Imports" are installed

### Additional Information

- Operating System: content of `/etc/os-release`:
```NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Theia Version: 1.15.0

**Comment by vince-fugnitto** [comment]
@alancummings thank you for the discussion, did you notice any errors in the dev console or backend?
I tried with api-compatible version of the builtins and `ms-python.python` and the sorting of imports works correctly.

**Comment by alancummings** [comment]
> @alancummings thank you for the discussion, did you notice any errors in the dev console or backend?
There was no output at all associated with this particular issue in either the dev console or the backend output.  

> I tried with api-compatible version of the builtins and `ms-python.python` and the sorting of imports works correctly.
What is the best way to determine the api-compatible versions of the builtins and extensions? (Note: I've switched from explicit `vscode-builtins-*` entries in `package.json`  to the single `vscode-builtin-extensions` entry in `theiaPlugins` -- this changes the versions from 1.56.2 to 1.50.0 for most of the plugins, but this issue did not change)

[package.json.txt](https://github.com/eclipse-theia/theia/files/6802831/package.json.txt)
I'm attaching my package.json.

**Comment by vince-fugnitto** [comment]
> What is the best way to determine the api-compatible versions of the builtins and extensions?

As an application developer it would be your responsibility to select extensions bundled in your application (included in the `package.json`) which are api-compatible. For `vscode-builtin-*` extensions this means a version which is compatible with the api as they are built from vscode sources, while all other extensions must be compatible based on the `engines.vscode` version ([example](https://github.com/microsoft/vscode-python/blob/53dcbc0799217077e29ceff17a29e72dd2204c15/package.json#L39-L41)).

The framework currently supports:

https://github.com/eclipse-theia/theia/blob/faae393f66c779c9640c77b0d23c60a4d0d10f62/packages/plugin-ext-vscode/src/common/plugin-vscode-types.ts#L17

---

I've tried with the extensions you referenced in your `package.json` and on master and it works correctly:


https://user-images.githubusercontent.com/40359487/125323490-d48c2880-e30c-11eb-9939-a6359b799476.mp4

You can try cleaning the application and rebuilding, making sure as well your `yarn.lock` file is properly updated, but I cannot reproduce the issue you reported.

**Comment by alancummings** [comment]
@vince-fugnitto Thanks for the effort.

Is there a similar way to determine the best versions of yarn and node? The documentation (https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites) lists yarn 1.7, which seems pretty old (but maybe that is normal for the node world)

Feel free to close the issue.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Thanks for the effort.
> 
> Is there a similar way to determine the best versions of yarn and node? The documentation (https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#prerequisites) lists yarn 1.7, which seems pretty old (but maybe that is normal for the node world)

I believe newer versions are fine (I use `1.22.4`). I do know that yarn `2.x.x` (berry) is not yet supported https://github.com/eclipse-theia/theia/issues/7062.

**Comment by vince-fugnitto** [comment]
> Feel free to close the issue.
