### ISSUE TITLE
documentation: update yarn prerequisites

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9724]
#### Feature Description:

We should update the prerequisites documentation to refer to the valid `yarn` ranges that  the framework supports.

The [following](https://github.com/eclipse-theia/theia/blame/master/doc/Developing.md#L57) should be updated from:

```md
 - [Yarn package manager](https://yarnpkg.com/en/docs/install) v1.7.0
 ```

to

```md
 - [Yarn package manager](https://yarnpkg.com/en/docs/install)  `>= 1.7.0` **AND** `< 2.x.x`.
 ```

We should also update the following:

https://github.com/eclipse-theia/theia/blob/5284996e010ddf5261d603d29ed0a1d83175a9be/package.json#L6

---

Note: once https://github.com/eclipse-theia/theia/issues/7062 is supported we can update the range.

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by vince-fugnitto** [comment]
> I would like to take this one.

@RhnSharma please go ahead :)

**Comment by RhnSharma** [comment]
@vince-cognito Do I have to wait for the #7062 to complete to make a pull request?

**Comment by vince-fugnitto** [comment]
@RhnSharma no, the version range does not include `2.x.x`. Only after #7062 would we update the prerequisite again to support it. Please also see the update to the `engines.yarn` version as referenced in the issue.
