### ISSUE TITLE
Highlighting makes parts of the problem message unreadable

### ISSUE THREAD

**Issue by licam** [eclipse-theia/theia#9741]
When using problem view to display the error message. After highlighting one of the problems, highlighted text is unfortunately no longer readable! like following:
![th3](https://user-images.githubusercontent.com/10184388/125751345-1b5cab8e-0375-46de-844f-e2dbdf9c0aef.png)
Theia version is 1.14.0
How to reproduce:
1. On terminal create a new node project with npm init
2. Use this package.json which has an error:
[package2.zip](https://github.com/eclipse-theia/theia/files/6821382/package2.zip)
3. Open Problem view.
4. Select a problem row

**Comment by vince-fugnitto** [comment]
The issue is also related to https://github.com/eclipse-theia/theia/issues/7189.
