### ISSUE TITLE
Error launching custom tasks (cannot read property 'cwd' of undefined)

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia#9743]
### Bug Description:
When launching tasks with custom executions (for example from the gradle VS Code extensions), we get errors saying 
```
TypeError: Cannot read property 'cwd' of undefined
```

I was able to trace the problem to this PR:

https://github.com/eclipse-theia/theia/pull/9695/files#diff-6268a7212c6dfa3764fd2c66d3acfd23d8920a9264a28c1ec4a72210121bf96cR199

The problem is that taskConfig.options is not mandatory. 

### Steps to Reproduce:

1. Install vscode-java 0.80.0
2. Open a Java project
3. Observe: vscode-java shows a rotating progress indicator at the right bottom corner of the window
4. Click on the progress indicator
5. A popup appears saying "Error launching task 'Java Build Status': Cannot read property 'cwd' of undefined"

### Additional Information

- Operating System: Window
- Theia Version: master

**Comment by tsmaeder** [comment]
I guess one of the reasons this problem appeared is that we don't have proper typing of the `options` field in `TaskDto`, `TaskConfiguration`, etc. The problem is that those types have a "catch-all" field like

```
TaskDto {
...
 [key: string]: any;
````  

We really should add all known fields with proper typing in any types where they apply. Generally, I would refactor those types to have a fixed set of properties like so: 

TaskDto {
   label: string,
   ...
   extraPropeties: {
       [key: string]: any;
   }
} 

This way, we would notice if we're adding a property somewhere but leave it out in related types.

**Comment by tsmaeder** [comment]
@kenneth-marut-work do you have time to fix this in the short term? You're probably most familiar with that particular code.

**Comment by kenneth-marut-work** [comment]
> @kenneth-marut-work do you have time to fix this in the short term? You're probably most familiar with that particular code.

Sure I'll try to get to it today 👍

**Comment by alvsan09** [comment]
This can also be reproduced using the vscode sample: 
[task-provider-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/task-provider-sample)

Run the task: Command Palette -> Tasks: run Task -> custombuildscript: 32 watch incremental
