### ISSUE TITLE
Opening Theia browser IDE in Electron

### ISSUE THREAD

**Issue by ccheraa** [eclipse-theia/theia#9751]
### Bug Description:
When accessing the url to a Theia browser IDE inside Electron, it fails to load.
Theia knows it's run in Electron, even though it's the Browser IDE.
We encountered this problem when trying to run tests using Cypress

### Steps to Reproduce:

1. Start the browser IDE
2. Write a cypress test that uses the browser IDE
3. Open cypress, and run that test using Electron.

### Additional Information

The problem happens in `filesystem-preferences.ts` at line `32`:

```typescript
export const MAX_FILE_SIZE_MB = environment.electron.is() ? process.arch === 'ia32' ? WIN32_MAX_FILE_SIZE_MB : GENERAL_MAX_FILE_SIZE_MB : 32;
```

The function `environment.electron.is()` returns `true` which is technically true, but since it's a browser instance in reality, `process` is not defined, and that's where the problem is.

We want this function to tell the difference between being an Electron instance, or a web instance opened in an Electron instance.

A work around that worked for me:
```typescript
export const MAX_FILE_SIZE_MB = environment.electron.is() && window.process ? process.arch === 'ia32' ? WIN32_MAX_FILE_SIZE_MB : GENERAL_MAX_FILE_SIZE_MB : 32;
```

- Operating System: ubuntu 20.04
- Theia Version: 1.15.0

**Comment by vince-fugnitto** [comment]
@ccheraa I'm not sure why you'd want to have the browser instance in an electron instance over the pure electron version.
I do not believe it is a use-case that the community thought of supporting, and there is likely other areas in the code which would not support this target. If the target is purely for tests I would think it should not be supported.

**Comment by ccheraa** [comment]
@vince-fugnitto I agree with you, the only use case I know of is running Cypress tests, and it was running just fine until Theia upgraded `webpack` which doesn't include node polyfills anymore.
So up to version `1.13.0`, that was how we tested our project, and now it's not working.
Do you have a suggestion for testing the Electron IDE in some other way?

**Comment by vince-fugnitto** [comment]
> Do you have a suggestion for testing the Electron IDE in some other way?

You can probably think of using [spectron](https://www.electronjs.org/spectron) which is maintained by electron itself with a combination of the api integration tests. I haven't used Cypress in the past but it looks like using the browser version in electron for tests is a workaround, and not really a target we want to support natively in the framework as you pointed out.

**Comment by vince-fugnitto** [comment]
@ccheraa closing since we came to the conclusion that it is not something that the framework should support given the new target is only for cypress tests. If you have additional comments, please feel free to comment on the issue, or open future discussions.

**Comment by ccheraa** [comment]
If anyone comes across the same problem, and finds that moving to something else other than Cypress is not an option, here's a better workaround I implemented in our tests.

We pass `process` into Cypress config:

`cypress/plugins/index.js`
```javascript
module.exports = (on, config) => {
  // We can't use "config.process = process" because it's passed as a JSON object
  config.process = {
    env: process.env,
    chrome: process.chrome,
    defaultApp: process.defaultApp,
    electron: process.electron,
    isMainFrame: process.isMainFrame,
    mas: process.mas,
    noAsar: process.noAsar,
    noDeprecation: process.noDeprecation,
    resourcesPath: process.resourcesPath,
    sandboxed: process.sandboxed,
    throwDeprecation: process.throwDeprecation,
    traceDeprecation: process.traceDeprecation,
    traceProcessWarnings: process.traceProcessWarnings,
    type: process.type,
    stdout: process.stdout,
    stderr: process.stderr,
    stdin: process.stdin,
    argv: process.argv,
    argv0: process.argv0,
    execArgv: process.execArgv,
    execPath: process.execPath,
    debugPort: process.debugPort,
    exitCode: process.exitCode,
    version: process.version,
    versions: process.versions,
    config: process.config,
    pid: process.pid,
    ppid: process.ppid,
    title: process.title,
    arch: process.arch,
    platform: process.platform,
    memoryUsage: process.memoryUsage,
    release: process.release,
    features: process.features,
    hrtime: process.hrtime,
    connected: process.connected,
    report: process.report,
    traceDeprecation: process.traceDeprecation,
  };
  return config;
}
```

Next, we overwrite the `visit` command to pass the `process` variable from Cypress config to `window`:

`cypress/support/commands.js`
```javascript
Cypress.Commands.overwrite('visit', (orig, url, options) => {
  // this is a fix to include the process variable when using the Electron browser
  return orig(url, Cypress.isBrowser('electron') ? {
    ...options,
    onBeforeLoad(win) {
      win.process = Cypress.config('process');
      if (options?.onBeforeLoad) {
        options.onBeforeLoad(win);
      }
    }
  } : options);
})
```

**Comment by danepowell** [comment]
Rather than fixing Theia, which I _do_ think is misbehaving here (it's just as valid to view a Theia browser application in Electron as any other browser, and that should _not_ be treated the same as running a Theia electron application directly), I found it much easier to configure Cypress to trick Theia into thinking it's running in Chrome.

All you need to do is enable the `experimentalModifyObstructiveThirdPartyCode` [experimental feature](https://docs.cypress.io/guides/references/experiments) in Cypress.
