### ISSUE TITLE
Upgrade VSCode API version

### ISSUE THREAD

**Issue by svor** [eclipse-theia/theia#9752]
Currently the version of VS Code API is 1.50.0 which is defined as [VSCODE_DEFAULT_API_VERSION](https://github.com/eclipse-theia/theia/blob/c92e822830e356c77d3186fda73b47f91da272e9/packages/plugin-ext-vscode/src/common/plugin-vscode-types.ts#L17)

Many of vscode extensions require VS Code API version > 1.50.0, here is a list of some of them:

- [vscode-go](https://github.com/golang/vscode-go/)  -> 1.52.0
- [vscode-yaml ](https://github.com/redhat-developer/vscode-yaml) -> 1.52.0
- [vscode-java](https://github.com/redhat-developer/vscode-java) -> 1.53.2

To use these extensions with Theia we need to update that value. Some of API is not implemented in Theia but after upgrading it would be a better chance to add that missed API. For example @tsmaeder has already done some investigation what is missing for vscode-java extension: https://github.com/eclipse/che/issues/20134#issuecomment-880542184

### Feature Description:
Update VSCODE_DEFAULT_API_VERSION at least to 1.52.0

**Comment by vince-fugnitto** [comment]
@svor duplicate of https://github.com/eclipse-theia/theia/issues/9193?

**Comment by svor** [comment]
@vince-fugnitto seems it is, thnaks!

**Comment by svor** [comment]
Close at it is duplicate of https://github.com/eclipse-theia/theia/issues/9193
