### ISSUE TITLE
File Menu Disable and Enable doesn't Update Immediately

### ISSUE THREAD

**Issue by maheshrajrp** [eclipse-theia/theia#9760]
### Problem Description

Disabling an option in file menu and then enabling the same doesn't update immediately. Consider, this scenario, when an option in file menu is disabled for 10seconds and then is enabled, and consider the file menu option within which the option disabled is opened. Even after 10 seconds the option is not enable back, however if we perform any other action then move over to the same file menu we can find it enabled. but, the update is not shown immediately.  

### Reproducing the Issue

```ts
if (extendedAction.execute) {
    let handler = {
        execute: extendedAction.execute,
        isEnabled: extendedAction.isEnabled,
        isToggled: extendedAction.isToggled,
        isVisible: extendedAction.isVisible
    };
    if (extendedAction.label) {
        toDispose.push(this.registerCommand(extendedAction, handler));
    } else {
        toDispose.push(this.registerHandler(extendedAction.id, handler));
    }
} else {
    if (extendedAction.label) {
        toDispose.push(this.registerCommand(extendedAction));
    }
}
```

Using this function enable and disable functionality in menu is achieved using HTTP Calls. However, the same isn't refreshed immediately. Instead action such as outside click and then going to the menu needs to be performed. 

### 
Operating System: Linux,Windows
Theia Version: 1.13.0

**Comment by vince-fugnitto** [comment]
@maheshrajrp thank you for reporting the issue, please be sure to properly fill out the issue template so the community can better understand and help. For instance, please provide _"steps to reproduce"_ the issue.

**Comment by maheshrajrp** [comment]
> @maheshrajrp thank you for reporting the issue, please be sure to properly fill out the issue template so the community can better understand and help. For instance, please provide _"steps to reproduce"_ the issue.

Hi @vince-fugnitto , Thanks for quick reply. I've updated the description based on the template.

**Comment by vince-fugnitto** [comment]
> Hi @vince-fugnitto , Thanks for quick reply. I've edited the description based on the template.

The steps are not clear either, I believe there is missing information/code to the code snippet provided.

**Comment by vince-fugnitto** [comment]
@maheshrajrp is the issue still valid? The latest comment was not addressed.

**Comment by maheshrajrp** [comment]
@vince-fugnitto Sorry, I haven't checked on that issue since that. Since, this is calling our function I thought the issue was on ours. The following is the snippet of extended action.

```
    registerExtendedAction(extendedAction: VolanteGroupAction): Disposable {
        const toDispose = new DisposableCollection();
        if (extendedAction.execute) {
            let handler = {
                execute: extendedAction.execute,
                isEnabled: extendedAction.isEnabled,
                isToggled: extendedAction.isToggled,
                isVisible: extendedAction.isVisible
            };
            if (extendedAction.label) {
                toDispose.push(this.registerCommand(extendedAction, handler));
            } else {
                toDispose.push(this.registerHandler(extendedAction.id, handler));
            }
        } else {
            if (extendedAction.label) {
                toDispose.push(this.registerCommand(extendedAction));
            }
        }
        if (extendedAction.menuPath) {
            toDispose.push(this.registerMenuAction(extendedAction.menuPath, {
                commandId: extendedAction.id,
                alt: extendedAction.alt,
                icon: extendedAction.iconClass,
                label: extendedAction.label,
                order: extendedAction.order,
                when: extendedAction.when
            }));
        }
        if (extendedAction.keybinding) {
            toDispose.push(this.registerKeybinding({
                command: extendedAction.id,
                keybinding: extendedAction.keybinding,
                context: extendedAction.context,
                when: extendedAction.when
            }));
        }
        this.menuRegistry.getMenu()
        return toDispose;
    }

```

**Comment by maheshrajrp** [comment]
Sorry, I haven't checked on that issue since that. Since, this is calling our function I thought the issue was on ours. The following is the snippet of extended action.Will check further and reply to you

```
    registerExtendedAction(extendedAction: GroupAction): Disposable {
        const toDispose = new DisposableCollection();
        if (extendedAction.execute) {
            let handler = {
                execute: extendedAction.execute,
                isEnabled: extendedAction.isEnabled,
                isToggled: extendedAction.isToggled,
                isVisible: extendedAction.isVisible
            };
            if (extendedAction.label) {
                toDispose.push(this.registerCommand(extendedAction, handler));
            } else {
                toDispose.push(this.registerHandler(extendedAction.id, handler));
            }
        } else {
            if (extendedAction.label) {
                toDispose.push(this.registerCommand(extendedAction));
            }
        }
        if (extendedAction.menuPath) {
            toDispose.push(this.registerMenuAction(extendedAction.menuPath, {
                commandId: extendedAction.id,
                alt: extendedAction.alt,
                icon: extendedAction.iconClass,
                label: extendedAction.label,
                order: extendedAction.order,
                when: extendedAction.when
            }));
        }
        if (extendedAction.keybinding) {
            toDispose.push(this.registerKeybinding({
                command: extendedAction.id,
                keybinding: extendedAction.keybinding,
                context: extendedAction.context,
                when: extendedAction.when
            }));
        }
        this.menuRegistry.getMenu()
        return toDispose;
    }
```

**Comment by maheshrajrp** [comment]
Hi @vince-fugnitto ,
I haven't checked up the issue since then. Since, that issue was on our layer I thought the issue was with ours and marked that for a later date. I will do a checkup and get back.

Thanks for the reply

**Comment by maheshrajrp** [comment]
Hi @vince-fugnitto ,
Thank you for your time.
Consider this scenario, Assume that on clicking an menu item from menu a setTimeout functions run which set the menu item's isEnabled to false. and wait for around 10 seconds to be enabled back to true. Now if we view the Menu before 10 seconds, the menu should disabled. However, if we stay on the menu without clicking elsewhere post the 10sec, though the isEnabled is changed to true. The file menu is not enabled immediately instead we have click someplace and then go back to menu to see it enabled. 
This situation is similar to the ones I'm experiencing. 

And sorry for the poor problem description earlier, back then I was just beginning to learn React, Theia and stuffs.

**Comment by vince-fugnitto** [comment]
@maheshrajrp unless the problem can be reproduced with a clear example, I would argue the issue should be closed. It seems to be an implementation problem on your end? We have many examples where menus are enabled/disabled dynamically.

**Comment by maheshrajrp** [comment]
Sure, @vince-fugnitto . In that case we can close. I too believe it as a implementation problem. 

Thanks for the help. Cheers !!
