### ISSUE TITLE
Codicon spin animation

### ISSUE THREAD

**Issue by vincejo** [eclipse-theia/theia#9768]
### Feature Description: 
When we do `vscode.ThemeIcon('loading~spin')`, we noticed that the icon does not spin. In VSCode the animation modifier works. It would be great to have in Theia as well. We are in Theia 1.14.0.

**Comment by vince-fugnitto** [comment]
@vincentjocodes thank you for the issue, is it something you’re interested in contributing?

**Comment by vince-fugnitto** [comment]
I believe this is fixed.
