### ISSUE TITLE
In the docker terminals' processes die after some time

### ISSUE THREAD

**Issue by akosyakov** [eclipse-theia/theia#979]

**Comment by hexa00** [comment]
I'm trying to reproduce this.

I've started a docker instance from the example Dockerfile and started one terminal.

I'm keeping a browser open with it.

Does this match your conditions ? or you did not have a browser attached  for example ?

Does it take hours or minutes?

**Comment by akosyakov** [comment]
I am trying to develop Theia with Theia with 3 processes: watching an extension, watching an example, running an example. After some time one of them is dying. I will try to time track it.

**Comment by hexa00** [comment]
OK so it's active even... it tought something could maybe timeout... but seems like that's not the issue.

**Comment by hexa00** [comment]
I ran a term in a docker all day > 8 hours.. so I don't think it's time dependant, must be something else

**Comment by geropl** [comment]
I had the same issue when sharing a Theia instance behind an nginx (localtunnel.me) with the others. My first impression is that the nginx drops the websocket connections when there is no traffic. When executing `watch -n5 date` the terminal stayed open over night..

Is there a reason the TerminalWidget creates websockets with `{ reconnecting: false }`?

**Comment by hexa00** [comment]
The terminal should not exit when the connection is closed. The only way to close it is to click on close or kill the back-end.

It would have to be that the TerminalWidget gets disposed without storeState being called.  I'm not sure how this can happen...

**Comment by geropl** [comment]
@svenefftinge Do you have an idea when/why that may happen?

> It would have to be that the TerminalWidget gets disposed without storeState being called. I'm not sure how this can happen...

**Comment by svenefftinge** [comment]
Is that reproduceable for you? Storing happens on unload. You can observe the storage using chrome developer tools.

**Comment by msujew** [comment]
Given the lack of activity on this issue, I don't think anyone still experiences the issue in question. It has probably been fixed in the meantime. I'll close this one.
