### ISSUE TITLE
Unexpected Identifier ffunction

### ISSUE THREAD

**Issue by Infuser** [eclipse-theia/theia#9795]
Creating this ticket in hope it will be useful for anyone else if they get this issue, we started getting this issue today when running a new theia build.

Build runs fine but when opening the browser we where getting unexpected identifier causing theia to completely fail looking at the source of the error it became likely it was an issue with packaging as we could see code in the bundle like ffunction instead of function, notice the double ff

Adding this to package.json fixed the issue:

```json
  "resolutions": {
    "webpack-sources": "2.3.1"
  },
```

**Comment by vince-fugnitto** [comment]
I confirmed it fixes the recent CI failures on [`theia-apps`](https://github.com/theia-ide/theia-apps):
- https://github.com/theia-ide/theia-apps/pull/487

We will need to try and fix it upstream (this repo) since it likely affects all packaging.
cc @paul-marechal

**Comment by Infuser** [comment]
We noticed webpack sources is coming from 2 locations compression-webpack-plugin and webpack itself and the versions dont match

**Comment by paul-marechal** [comment]
A better fix is to put a resolution as:

```json
"resolutions": {
  "**/webpack": "5.46.0"
}
```

`webpack@^5.47.0` is the one depending on `webpack-sources@^3.0.1`, so just forcing the latter to resolve to `webpack-sources@2` is not the best idea when the dependent package expects the next major version.
