### ISSUE TITLE
security: potential vulnerability

### ISSUE THREAD

**Issue by Infuser** [eclipse-theia/theia#9814]
**Bug Description**

There is `low` known vulnerability in `@theia/application-package` from a nested dependency:

```
=== npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 2.6.9 < 3.0.0 || >= 3.1.0                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @theia/application-package                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @theia/application-package > changes-stream > debug          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/534                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 low severity vulnerability in 80 scanned packages
```

**Comment by vince-fugnitto** [comment]
@Infuser please note that vulnerabilities should not be disclosed publicly, we have a pull-request in review with the proper steps to report:
- https://github.com/eclipse-theia/theia/pull/9804/files

**Comment by Infuser** [comment]
Apologies and point noted Vince, assume you will now relay the issue and get it resolved

Thanks

**Comment by vince-fugnitto** [comment]
> Apologies and point noted Vince, assume you will now relay the issue and get it resolved

Sure @Infuser! Do you mind emailing me the full report so we can look into providing a fix? 
You can contact me at vincent.fugnitto@ericsson.com :+1:

**Comment by vince-fugnitto** [comment]
@Infuser my apologies about deleting the initial comment, for known vulnerabilities it is fine, but for newly disclosed vulnerabilities we should follow the proper procedure. Any reason as to why this `low` vulnerability was of interest to you? We try our best to resolve such vulnerabilities but we prioritize those that are of `moderate` or higher severity.

**Comment by Infuser** [comment]
Hi Vince 

Its just our company policy to resolve them, not too worry its not a major problem for us but would be good to see it resolved in the next 6 months

**Comment by vince-fugnitto** [comment]
> Its just our company policy to resolve them, not too worry its not a major problem for us but would be good to see it resolved in the next 6 months

@Infuser please don't hesitate in contributing updates to this dependency and others if you're interested :+1:

**Comment by vince-fugnitto** [comment]
The vulnerability was fixed thanks to https://github.com/eclipse-theia/theia/pull/10764.
