### ISSUE TITLE
electron: Setting Icon disappear if not editor opened.

### ISSUE THREAD

**Issue by linhanyu** [eclipse-theia/theia#9826]
### Bug Description:
![image](https://user-images.githubusercontent.com/17355591/127991314-978e6da2-0783-4210-a632-466447a6817a.png)

Out product whitch use theia face a problem when update from 1.11.0 to 1.16.0. the Setting Icon disappear if not editor opened. If we opened any editor like keybinding editor, that icon appeared.
That's because the setting icon is codicon-settings-gear. **Codicon** were depend on the "monaco-colors" dom element.  It's be loaded by **IStandaloneThemeService**, when first editor created.
So, In theia-blueprint, that's is a "output" widget be created when startup. But some product (like ours) remove output widget in some way (such as remove widget), it made Codicon load fail, and shadow the problem

### Steps to Reproduce:

1. remove output widget, compile theia
2. start up electron
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by linhanyu** [comment]
![image](https://user-images.githubusercontent.com/17355591/127992324-6608b636-11a3-46d5-a6e5-8ec50566422f.png)
To resolved this problem, I had create a MonacoWidget and discard it. But it's not a long-term solution，right?

**Comment by msujew** [comment]
I can reproduce this issue in the browser environment as well. Note the missing gear in the bottom left corner:

![image](https://user-images.githubusercontent.com/4377073/127998353-41970225-508c-4380-841b-54610bd196c6.png)

I removed every dependency related to `monaco` from the browser example for this:

```
"dependencies": {
    "@theia/bulk-edit": "1.16.0",
    "@theia/callhierarchy": "1.16.0",
    "@theia/core": "1.16.0",
    "@theia/file-search": "1.16.0",
    "@theia/filesystem": "1.16.0",
    "@theia/git": "1.16.0",
    "@theia/keymaps": "1.16.0",
    "@theia/messages": "1.16.0",
    "@theia/metrics": "1.16.0",
    "@theia/mini-browser": "1.16.0",
    "@theia/navigator": "1.16.0",
    "@theia/preferences": "1.16.0",
    "@theia/scm": "1.16.0",
    "@theia/scm-extra": "1.16.0",
    "@theia/workspace": "1.16.0"
},
```
