### ISSUE TITLE
Use Docker Image build theia-app , failed to resolve module：filenamify

### ISSUE THREAD

**Issue by marol1210** [eclipse-theia/theia#9839]
thanks advance

### Bug Description:

yarn run v1.22.4
$ /project/node_modules/.bin/theia build
Failed to resolve module: filenamify

### Steps to Reproduce:

1. docker pull electronuserland/builder:12-11.19
2. run container from `1` image
3. apt install npm  & yarn
4. use theia offical's package.json  to build
5. yarn
6. yarn theia build
7. Failed to resolve module: filenamify

### Additional Information

- Operating System:   Ubuntu
- Theia Version: 1.17.0-next.cff1edad

**Comment by msujew** [comment]
As far as I know, this is a [known issue](https://community.theia-ide.org/t/failed-to-resolve-module-filenamify/1153). Does this impact your build in any way, aside from the warning?

**Comment by marol1210** [comment]
> As far as I know, this is a [known issue](https://community.theia-ide.org/t/failed-to-resolve-module-filenamify/1153). Does this impact your build in any way, aside from the warning?

@msujew 
yes, it is.

the build is failed , I can't start theia : `yarn theia start /my-workspace --hostname 0.0.0.0 --port 5000`

**Comment by marol1210** [comment]
<img width="342" alt="微信截图_20210804171337" src="https://user-images.githubusercontent.com/7519301/128155448-e33d789c-37fc-4b57-8ed4-ce208dea2b33.png">

**Comment by msujew** [comment]
I think this: `Error: ENOSPC: no space left on device, write` might be your issue. The whole workspace is quite large due to a lot of dev-dependencies. Does your drive have enough free space? Because I am pretty sure, that the `filenamify` issue should not crash your build.

**Comment by marol1210** [comment]
great, it is.  

I change the path of workspace for large space.  it work if just run  `yarn theia start /my-workspace --hostname 0.0.0.0 --port 5000`, 

but something else wrong.

<img width="941" alt="aaa" src="https://user-images.githubusercontent.com/7519301/128159140-467159c4-6242-4301-80d8-db82b4029418.png">

**Comment by marol1210** [comment]
and ,  i  can't  understand that  build is failed when run yarn theia build , why this can work , `yarn theia start /my-workspace --hostname 0.0.0.0 --port 5000`

**Comment by marol1210** [comment]
and ,  i  can't  understand that  build is failed when run yarn theia build , why this can work , `yarn theia start /my-workspace --hostname 0.0.0.0 --port 5000`

**Comment by msujew** [comment]
Did you rebuild the application after resolving the drive space issue? Or is your build still failing?

**Comment by marol1210** [comment]
yes ,  i did.
exciting , getting closer to the truth ， thanks a lot.
the space of my project dist is large , i build app from it;  but failed , the same result above.  

![image](https://user-images.githubusercontent.com/7519301/128160606-0dc4f101-f670-4467-8620-ab6543dda084.png)

**Comment by marol1210** [comment]
@msujew 
deep thanks for your help
how amazing it is , once i rebuild, despite that build output  with something wrong ,  but it work.

![image](https://user-images.githubusercontent.com/7519301/128164823-a2722a7a-fcf8-4e84-8ab8-8eb2b8510ed2.png)

**Comment by marol1210** [comment]
`
theia build --mode development
Failed to resolve module: filenamify
(node:2319) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

assets by status 333 KiB [cached] 3 assets
assets by path *.gz 8.05 MiB 205 assets
assets by path *.js 19.3 MiB
  assets by chunk 12.6 MiB (id hint: vendors) 76 assets
  24 assets
assets by path vs/ 25.2 MiB
  assets by path vs/editor/ 23.3 MiB 26 assets
  assets by path vs/base/ 1.79 MiB 6 assets
  asset vs/loader.js 86.5 KiB [emitted] [from: node_modules/@theia/monaco-editor-core/dev/vs/loader.js] [copied]
  asset vs/loader.js.gz 15.3 KiB [emitted]
assets by info 1.59 MiB [immutable]
  assets by chunk 1.13 MiB (auxiliary name: main) 10 assets
  assets by chunk 478 KiB (auxiliary id hint: vendors)
    asset 6e3d5ec6699a8d147d29.wasm 457 KiB [emitted] [immutable] [from: node_modules/onigasm/lib/onigasm.wasm] (auxiliary id hint: vendors)
    asset 57695d7e34f6d23addde.svg 21 KiB [emitted] [immutable] [from: node_modules/@theia/monaco/src/browser/style/symbol-sprite.svg] (auxiliary id hint: vendors)
runtime modules 13 KiB 23 modules
javascript modules 16.3 MiB 1836 modules
asset modules 123 KiB (javascript) 1.82 MiB (asset)
  modules by path ./node_modules/@theia/ 122 KiB (javascript) 64.1 KiB (asset) 93 modules
  modules by path ./node_modules/font-awesome/ 252 bytes (javascript) 1.06 MiB (asset)
    modules by path ./node_modules/font-awesome/fonts/*.eot 84 bytes (javascript) 324 KiB (asset) 2 modules
  modules by path ./node_modules/file-icons-js/ 210 bytes (javascript) 256 KiB (asset) 5 modules
  ./node_modules/onigasm/lib/onigasm.wasm 42 bytes (javascript) 457 KiB (asset)[built] [code generated]
  ./node_modules/octicons/build/svg/git-commit.svg 489 bytes [built] [code generated]
json modules 300 KiB
  modules by path ./node_modules/@theia/core/ 241 KiB 55 modules
  modules by path ./node_modules/@theia/monaco/ 25.3 KiB 11 modules
  modules by path ./node_modules/ajv/lib/ 3.12 KiB 2 modules
  ./node_modules/entities/maps/entities.json 28.4 KiB [built] [code generated]
  ./node_modules/@theia/plugin-ext/package.json 2.29 KiB [built] [code generated]


WARNING in ./node_modules/inversify/lib/annotation/decorator_utils.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/decorator_utils.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/decorator_utils.ts'
 @ ./node_modules/inversify/lib/inversify.js 38:24-63
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/annotation/inject.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/inject.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/inject.ts'
 @ ./node_modules/inversify/lib/inversify.js 21:15-45
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/annotation/injectable.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/injectable.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/injectable.ts'
 @ ./node_modules/inversify/lib/inversify.js 15:19-53
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/annotation/multi_inject.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/multi_inject.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/multi_inject.ts'
 @ ./node_modules/inversify/lib/inversify.js 28:21-57
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/annotation/named.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/named.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/named.ts'
 @ ./node_modules/inversify/lib/inversify.js 19:14-43
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/annotation/optional.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/optional.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/optional.ts'
 @ ./node_modules/inversify/lib/inversify.js 24:17-49
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/annotation/post_construct.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/post_construct.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/post_construct.ts'
 @ ./node_modules/inversify/lib/inversify.js 32:23-61
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/annotation/tagged.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/tagged.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/tagged.ts'
 @ ./node_modules/inversify/lib/inversify.js 17:15-45
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/annotation/target_name.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/target_name.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/target_name.ts'
 @ ./node_modules/inversify/lib/inversify.js 30:20-55
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/annotation/unmanaged.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/annotation/unmanaged.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/annotation/unmanaged.ts'
 @ ./node_modules/inversify/lib/inversify.js 26:18-51
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/bindings/binding.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/bindings/binding.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/bindings/binding.ts'
 @ ./node_modules/inversify/lib/container/container.js 45:16-46
 @ ./node_modules/inversify/lib/inversify.js 6:18-50
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/bindings/binding_count.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/bindings/binding_count.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/bindings/binding_count.ts'
 @ ./node_modules/inversify/lib/planning/planner.js 4:22-58
 @ ./node_modules/inversify/lib/container/container.js 50:16-46
 @ ./node_modules/inversify/lib/inversify.js 6:18-50
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/constants/error_msgs.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/constants/error_msgs.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/constants/error_msgs.ts'
 @ ./node_modules/inversify/lib/container/container.js 46:17-51
 @ ./node_modules/inversify/lib/inversify.js 6:18-50
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/constants/literal_types.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/constants/literal_types.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/constants/literal_types.ts'
 @ ./node_modules/inversify/lib/inversify.js 8:22-58
 @ ./src-gen/frontend/index.js 5:22-42

WARNING in ./node_modules/inversify/lib/constants/metadata_keys.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/project/node_modules/inversify/src/constants/metadata_keys.ts' file: Error: ENOENT: no such file or directory, open '/project/node_modules/inversify/src/constants/metadata_keys.ts'
 @ ./node_modules/inversify/lib/inversify.js 4:11-47
 @ ./src-gen/frontend/index.js 5:22-42
`

**Comment by msujew** [comment]
Glad everything was able to build and work out in the end. Yes, I know, Theia shows quite a lot of warnings during build, but that's the life of a JS application with a large amount of dependencies. And like I said, the `Failed to resolve module: filenamify` issue message is only a warning, as far as I know, and shouldn't negatively impact your build.

If you see this issue as resolved, would you mind closing it?
