### ISSUE TITLE
workspace: add command mapping to plugin-system

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9840]
#### Feature Description:

The command `workspace:openConfigFile` requires a mapping in the plugin system to be able to be executable by vscode plugins. We should therefore add an appropriate mapping for `workbench.action.openWorkspaceConfigFile` (vscode command id) to the plugin system like so:

```ts
commands.registerCommand({ id: 'workbench.action.openWorkspaceConfigFile'}, {
    execute: () => commands.executeCommand(WorkspaceCommands.OPEN_WORKSPACE_FILE.id)
});
```

at:

https://github.com/eclipse-theia/theia/blob/cff1edad1c0fd3d9436e4119d18836a418e39cac/packages/plugin-ext-vscode/src/browser/plugin-vscode-commands-contribution.ts#L240-L242

**Comment by dineshUmasankar** [comment]
Is there a way to test this command's functionality?
I have taken the liberty of adding this command mapping into the plugin system through the provided code, but curious on where / how to write up a test for this command mapping's functionality.

**Comment by vince-fugnitto** [comment]
> Is there a way to test this command's functionality?
> I have taken the liberty of adding this command mapping into the plugin system through the provided code, but curious on where / how to write up a test for this command mapping's functionality.

@dineshUmasankar generally you would [create a vscode plugin](https://code.visualstudio.com/api/get-started/your-first-extension) that uses this functionality, package it and include it in the framework for test purposes. You can then execute these commands and confirm the behavior is correct.

**Comment by dineshUmasankar** [comment]
I would like to be assigned to this task if possible, but I would require some help clarifying `workspace:openConfigFile`. 

I have made a vscode plugin following the extension tutorial but I am having trouble going through the VS Code API finding this mapping equivalent method. As such, I cannot figure out how to call upon this specific functionality within a vscode plugin for the purposes of testing the functionality of the code provided.

My attempts so far lead me to [https://code.visualstudio.com/api/references/vscode-api#workspace](url), specifically the method: `workspace.getConfiguration().update()`, which I believe would technically open the workspace config file and write to it.
 
However, I could not specifically find a openWorkspaceConfigFile. If anyone could point in the right direction, within the VS Code API, regarding the details upon how to call upon this functionality and its parameters. I would really appreciate it and apologize in advance for the beginner question, as I'm taking my time to carefully learn the ins-outs of Theia and Typescript.

**Comment by vince-fugnitto** [comment]
@dineshUmasankar to test it is quite simple, I created a plugin to test which you can use since you were having difficulty:

- https://github.com/vince-fugnitto/vscode-open-config-file/releases/download/v0.0.1/vscode-open-config-file-0.0.1.vsix

The plugin simply [executes the command](https://github.com/vince-fugnitto/vscode-open-config-file/blob/fe083b5a8abf0084dea014a338ac6bc0023a5d88/src/extension.ts#L5):

```ts
export function activate(context: vscode.ExtensionContext) {
    let disposable = vscode.commands.registerCommand('vscode-open-config-file.test', () => {
        vscode.commands.executeCommand('workbench.action.openWorkspaceConfigFile');
    });

    context.subscriptions.push(disposable);
}
```

The command `workbench.action.openWorkspaceConfigFile` is available when we start the application, and we have a multi-root workspace opened (a workspace with more than one root folder, and described as a workspace file). In vscode this plugin will successfully work, but in the theia framework we need to make sure to add the proper mapping so that it is available by the plugin.

**Comment by dineshUmasankar** [comment]
@vince-fugnitto Thank you so much for the guidance and your time. I managed to get the test working successfully after fixing a couple build issues on my own hardware, and with your documentation. I apologize for the hassle and appreciate the opportunity to contribute significantly.

![testing-openWorkspaceConfigFile](https://user-images.githubusercontent.com/55666676/131610508-5913e153-f063-4633-8ce0-f325ef90b29a.gif)
