### ISSUE TITLE
vscode.tasks.taskExecutions API doesn't return executions after refreshing a page

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-theia/theia#9844]
### Bug Description:
`vscode.tasks.taskExecutions` API doesn't return executions after refreshing a page

### Steps to Reproduce:

1. Run a long running task/tasks
2. Use `vscode.tasks.taskExecutions ` API to get executions for the running tasks
3. It works well
4. Refresh a page
5. Use `vscode.tasks.taskExecutions ` API to get executions for the running tasks
6. It returns an empty array, at the same time `Terminal => Show Running Tasks` displays the list of tasks - the tasks are still running 

You can use my [simple vscode extension](https://github.com/RomanNikitenko/vscode-test-extension#vscodetaskstaskexecutions) for testing.

### Additional Information

- Operating System: macOS
- Theia Version: 2470421f97dfe030824c52c0df023a8c29dd8d69

**Comment by tsmaeder** [comment]
Hmh...this sounds a lot like the task executions are connection scopes, while "running tasks" is not. Since we're considering a new front and to be a fully new IDE, I think killing all tasks would be the right behaviour when we lose a front end.

**Comment by tsmaeder** [comment]
There is an older bug describing the same problem: https://github.com/eclipse-theia/theia/issues/9697 closing as duplicate.
