### ISSUE TITLE
Crash on Mac M1-Device

### ISSUE THREAD

**Issue by linhanyu** [eclipse-theia/theia#9846]
### Bug Description:
![image](https://user-images.githubusercontent.com/17355591/128307390-54b56c1c-cc8e-4cab-b64f-2c142959dd67.png)

### Steps to Reproduce:

Mac M1 devices use Rosetta2 to adapt some x86_64 application. It's known issue that old version chromium would cause crash when switch screen in M1 device.

### Additional Information

- Operating System:
- Theia Version:

**Comment by vince-fugnitto** [comment]
I believe it can be closed thanks to https://github.com/eclipse-theia/theia/pull/9936.
