### ISSUE TITLE
Incompatible with vsCode plugins later than 1.50.0

### ISSUE THREAD

**Issue by 15068821183** [eclipse-theia/theia#9848]
### Bug Description:
Some VSCode plug-ins require a version greater than 1.50.0. The current VERSION of VSCode for Theia is 1.50.0

### Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/14749519/128326589-1a9d75fe-d13b-4d97-b9ca-f04031cc0095.png)

2.
install error：
![image](https://user-images.githubusercontent.com/14749519/128326866-fe91b065-39d9-4792-ad09-f5c365b0d01a.png)

The corresponding vscode version needs to be updated：
![image](https://user-images.githubusercontent.com/14749519/128327170-c8a8f649-f88a-49bb-bb31-2ae181c3fe85.png)

### Additional Information

- Operating System:windows 10
- Theia Version:1.16.0

**Comment by msujew** [comment]
Hi @15068821183. Please see #9193 for more discussion on this topic and an explanation why the version is currently fixed to `1.50.0`. The other issue also presents a workaround for this problem.

As this is a duplicate issue, would you mind closing it?

**Comment by 15068821183** [comment]
@msujew thanks
