### ISSUE TITLE
Undo keyboard shortcut calls  command id as `undo`

### ISSUE THREAD

**Issue by cenkce** [eclipse-theia/theia#9849]
### Bug Description:
Undo keyboard shortcut calls  command id `undo` but if click edit>undo then it calls command 'core.undo' so my handler doesn't run

### Steps to Reproduce:

1. Register command handler using CommonCommands.UNDO.id and @theia/core/CommandRegistry
2. Down ctrl+z
3. Click edit > undo

### Additional Information

- Operating System: mac, win, linux
- Theia Version:  1.16.0

**Comment by vince-fugnitto** [comment]
@cenkce I'm not sure I follow, can you clarify in which case you expect your custom handler to execute?

We have the command:

https://github.com/eclipse-theia/theia/blob/f776392b6b616af48d222fbeb035e08c2c1f2865/packages/core/src/browser/common-frontend-contribution.ts#L116-L119

https://github.com/eclipse-theia/theia/blob/f776392b6b616af48d222fbeb035e08c2c1f2865/packages/core/src/browser/common-frontend-contribution.ts#L604-L606

and it is added to the `edit` main-menu item:

https://github.com/eclipse-theia/theia/blob/f776392b6b616af48d222fbeb035e08c2c1f2865/packages/core/src/browser/common-frontend-contribution.ts#L462-L465

and it's kebinding:

https://github.com/eclipse-theia/theia/blob/f776392b6b616af48d222fbeb035e08c2c1f2865/packages/core/src/browser/common-frontend-contribution.ts#L863-L866

**Comment by paul-marechal** [comment]
Note that `document.execCommand('undo')` calls into the DOM's APIs, not Theia's.

**Comment by cenkce** [comment]
I register a handler for the CommonCommands.UNDO command and when I press the keys ctrlcmd+z then Theia calls CommandRegistry.getActiveHandler to get available handlers but calls only passing `undo` command not `core.undo`, is that correct behavior?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I register a handler for the CommonCommands.UNDO command and when I press the keys ctrlcmd+z then Theia calls CommandRegistry.getActiveHandler to get available handlers but calls only passing `undo` command not `core.undo`, is that correct behavior?

@cenkce do you have a snippet of your handler? 
Also, what is the passing `undo` command you're referring to? Were you able to identify it in the source-code, does it come from a plugin?

**Comment by cenkce** [comment]
When I register only CommonCommands.UNDO it isn't catched when keyboard event happen
```
this.toCommandDisposable.push(
      this.commandRegistry.registerHandler(CommonCommands.UNDO.id, {
        execute: () => {
          this._engineApp.undo();
        },
        isEnabled: isEnabledCommand
      })
    );
```

But register a second handler for `undo` command it works

```
this.toCommandDisposable.push(
      this.commandRegistry.registerHandler('undo', {
        execute: () => {
          this._engineApp.undo();
        },
        isEnabled: isEnabledCommand
      })
    );
```

**Comment by vince-fugnitto** [comment]
@cenkce I believe you are not able to register a handler for the same command `id` multiple times without a proper `when` context to differentiate when the two should be called. At the moment the framework registers a handler for `CommonCommands.UNDO.id` and so does your snippet. The second snippet would work since `undo` is not an already registered command `id`.

**Comment by cenkce** [comment]
Hmm so I can't register more handlers to system Commands?

**Comment by vince-fugnitto** [comment]
> Hmm so I can't register more handlers for system Commands?

You can, but cannot re-use the same command id when registering.

**Comment by cenkce** [comment]
What is proper way to handle undo and redo events? listen to keyboard event? or handle undo and redo commands?

**Comment by vince-fugnitto** [comment]
> What is the proper way to handle undo and redo events? listen keyboard event? or handle undo and redo commands?

It's up to you, you can for instance listen to when a command is executed, and perform some special logic:

- https://eclipse-theia.github.io/theia/docs/next/classes/core.commandregistry-1.html#ondidexecutecommand

**Comment by cenkce** [comment]
Ok thanks
