### ISSUE TITLE
Theia Settings Menu Modification

### ISSUE THREAD

**Issue by maheshrajrp** [eclipse-theia/theia#9853]
Hi All,
I wish to edit the settings menu available in theia. I wish add a new menu item within that upon clicking that it should display a dialog-widget. I'm new to theia. Any help would be appreciated. Thanks in advance. 

![image](https://user-images.githubusercontent.com/80001447/128443214-8ca3ab5c-66b1-44fe-9a4b-0d568a46cc7b.png)

**Comment by msujew** [comment]
Hi @maheshrajrp,

You can add new menu items by using the `CommonMenus.SETTINGS_OPEN` menu path like this in your `MenuContribution`:

```ts
menuRegistry.registerMenuAction(CommonMenus.SETTINGS_OPEN, {
    commandId: DIALOG_COMMAND.id
});
```

Independently of that, you need to register a command that corresponds to the menu item in your `CommandContribution`:

```ts
const DIALOG_COMMAND = {
    id: 'open-custom-dialog-widget',
    label: 'Open dialog'
}
...ts
commandRegistry.registerCommand(DIALOG_COMMAND , {
    execute: () => openDialogWidget()
});
```

The simplest implementation of some `openDialogWidget()` method would look like this:
```ts
openDialogWidget(): void {
    new ConfirmDialog({
        title: 'Open dialog',
        msg: 'Hi, this is a simple confirm dialog'
    }).open();
}
```

Of course, you can create any kind of widget in there that you like.

@vince-fugnitto Would you mind converting this to a Q&A discussion?
