### ISSUE TITLE
The plugin debugging directory will be deleted when the same plugin is installed.

### ISSUE THREAD

**Issue by shuyaqian** [eclipse-theia/theia#9855]
### Steps to Reproduce:

1. Debugging the Plug-in on Port 3030
2. Install the same plug-in

I've developed an extension to the plug-in market myself. 
When a new plug-in is installed, if the plug-in already deployed, the extension will undeploy the old plug-in and then deploy the new plug-in. 
However, in the development host instance, the current directory is directly deleted during undeploy, so I think if the deletion action needs to be more rigorously judged.
![image](https://user-images.githubusercontent.com/6367259/128467847-1d1a9dcb-6f8c-4af5-ab4e-f40ff22e04ba.png)

### Additional Information

- Operating System: linux
- Theia Version:1.13.0

**Comment by vince-fugnitto** [comment]
Closing due to https://github.com/eclipse-theia/theia/pull/9866#issuecomment-912301877.
Please comment if it is still an issue.
