### ISSUE TITLE
Handling of yarn aliases in the application package generator

### ISSUE THREAD

**Issue by federicobozzini** [eclipse-theia/theia#9856]
### Feature Description:
[`yarn` offers the possibility of adding a package with an alias](https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-alias). When this is used a dependency entry in `package.json` is create with the following format:

```json
    "<alias>": "npm:<original_name>@<version>",
```

If this feature is used, the source generator in `@theia/application_package` breaks because `<original_name>` is used in place of `<alias` in the generated files. This happens because the information inside each package's `package.json` is used and the alias is ignored. This breaks every place where an import or a require like `import * from <alias>` is used.

Are you interested in a PR to fix this issue? I can work on it myself.

**Comment by vince-fugnitto** [comment]
@federicobozzini does it break for all packages or only `@theia/` ones? If it's only `@theia/` dependencies (extensions) then I'm not sure there is much value in supporting the use-case as aliasing is generally used to install multiple versions of the same package, something not possible with extensions.

**Comment by federicobozzini** [comment]
@vince-fugnitto Great question. it breaks only for `@theia` packages. 

In our case we often maintain a fork of most theia packages in order to add some flexibility to the development.These forks were historically included in the codebase by using git submodules but now we are exploring the possibility of replacing the git submodules with private npm packages. This would mean a package ane would change from `@theia/pkg` to something like `@org/theia-pkg`.

This change by itself would not be a problem, but it would require us to change most of our codebase to change how theia packages are used (EG: use `import * from '@org/theia-pkg/...'`) which might not really be ideal. 

Supporting yarn aliases in the source generation process would allow us to have something like `"@theia/pkg": "npm:@org/theia-pkg"` for the npm dependencies in `package.json` which would make this change more transparent and would not require any code change.

In theory [the same issue could be address by yarn resolutions](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md#mapping-version-specifications-as-well-as-packages-name), but this feature is not implemented yet.

**Comment by vince-fugnitto** [comment]
@federicobozzini alternatively, you can also reference your custom forked extensions by `path` or `url` if required:

- https://docs.npmjs.com/cli/v7/configuring-npm/package-json#local-paths
- https://docs.npmjs.com/cli/v7/configuring-npm/package-json#github-urls

However, if the aliasing support is important for your use-case, I would be fine to support it given that it does not introduce other changes such as `import * from '@org/theia-pkg/...'`.
