### ISSUE TITLE
Unable to copy/paste file/folder

### ISSUE THREAD

**Issue by DevTester425** [eclipse-theia/theia#9861]
### Bug Description:
Unable to copy file
Unable to paste file
Unable to copy folder
Unable to paste folder
It is impossible to perform these actions through the context menu or by key combinations Ctrl+c and Ctrl+v

https://user-images.githubusercontent.com/88549983/128540758-ee70fa1b-f656-4e86-b730-cf951b1dfd8f.mp4

### Steps to Reproduce:

1. Launch Theia 1.16.0
2. Create some kind of file 
3. Copy the file via the keyboard shortcut Ctrl+c
4. Paste the file via the keyboard shortcut Ctrl+v
5. Do the same using the context menu
6. Do the same for the folder

### Additional Information

- Operating System: Microsoft Windows 10, 64 bit
- Theia Version: 1.16.0

**Comment by vince-fugnitto** [comment]
@DevTester425 I verified the behavior using `master` and it works correctly for me. Is there any additional information to reproduce the problem, do you happen to have custom extensions or plugins included?

**Comment by DevTester425** [comment]
The problem was resolved after updating the dependencies of my application.
Thanks.
