### ISSUE TITLE
Removing certain commands results in "Error: Failed to start the frontend application"

### ISSUE THREAD

**Issue by nmaaiken** [eclipse-theia/theia#9870]
### Bug Description:
We are trying to implement a read-only version of Theia to display a code catalogue in the browser with added language features. For this, we remove commands from the application, to ensure that users cannot execute any write actions such as save, new, open, etc. that are out of scope of just viewing.
Removing commands from "workspace:xyz" this works fine. However, removing commands originating in "core.xyz", "file.xyz" and "textEditor.xyz" result in "Error: failed to start the frontend application". This is because those commands are later referenced in "frontend-application.ts" in method "startContributions()". 
Is there a way around this?

### Steps to Reproduce:

1. Execute the following code as an extension:

```ts
import { CommandRegistry, CommandContribution } from '@theia/core/lib/common';
import { injectable } from 'inversify';

@injectable()
// Add contribution interface to be implemented, e.g. "TheiaReadonlyMenuExtensionContribution implements CommandContribution"
export class TheiaReadonlyMenuExtensionCommandContribution implements CommandContribution {
    
    registerCommands(commands: CommandRegistry): void {
        commands.unregisterCommand("workspace:open");
        commands.unregisterCommand("workspace:openFile");
        commands.unregisterCommand("workspace:openFolder");
        commands.unregisterCommand("workspace:openRecent");
        commands.unregisterCommand("workspace:openWorkspace");
        commands.unregisterCommand("workspace:openConfigFile");
        commands.unregisterCommand("workspace:saveAs");
        commands.unregisterCommand("workspace:close");
        commands.unregisterCommand("core.save");
        commands.unregisterCommand("core.saveAll");
        commands.unregisterCommand("textEditor.commands.autosave");
        commands.unregisterCommand("file.newFile");
        commands.unregisterCommand("file.newFolder");
        commands.unregisterCommand("file.saveAs");
    }

}
```
2. Start the extension in the browser

### Additional Information

Logs:

```
yarn run v1.22.5
$ yarn rebuild:browser && yarn --cwd browser-app start
$ theia rebuild:browser
native node modules are already rebuilt for browser
$ theia start
root INFO Theia app listening on http://localhost:3000.
root INFO Configuration directory URI: 'file:///home/nic/.theia'
root WARN Frontend CommonFrontendContribution.configure is slow, took: 335.8 ms
root INFO Detected keyboard layout from browser API: German (PC)
root ERROR Failed to start the frontend application.
root ERROR Error: A command with id 'core.saveAll' does not exist.
    at ActionMenuNode.get (http://localhost:3000/bundle.js:68368:23)
    at ActionMenuNode.get (http://localhost:3000/bundle.js:68388:46)
    at http://localhost:3000/bundle.js:68281:20
    at Array.sort (<anonymous>)
    at CompositeMenuNode.__webpack_modules__.../node_modules/@theia/core/lib/common/menu.js.CompositeMenuNode.addNode (http://localhost:3000/bundle.js:68273:24)
    at MenuModelRegistry.__webpack_modules__.../node_modules/@theia/core/lib/common/menu.js.MenuModelRegistry.registerMenuNode (http://localhost:3000/bundle.js:68119:23)
    at MenuModelRegistry.__webpack_modules__.../node_modules/@theia/core/lib/common/menu.js.MenuModelRegistry.registerMenuAction (http://localhost:3000/bundle.js:68110:21)
    at CommonFrontendContribution.__webpack_modules__.../node_modules/@theia/core/lib/browser/common-frontend-contribution.js.CommonFrontendContribution.registerMenus (http://localhost:3000/bundle.js:34760:18)
    at MenuModelRegistry.__webpack_modules__.../node_modules/@theia/core/lib/common/menu.js.MenuModelRegistry.onStart (http://localhost:3000/bundle.js:68092:25)
    at http://localhost:3000/bundle.js:39463:109
```

- Operating System: Ubuntu 20.04 on WSL2
- Theia Version: 1.16.0

**Comment by vince-fugnitto** [comment]
@nmaaiken thank you for the discussion, I believe it is related to the following issue and namely that these commands are referenced when creating menus in the framework which will result in the fail:
- https://github.com/eclipse-theia/theia/issues/8175#issuecomment-658705906

We should aim to make the registration of menus more tolerant, to not fail the application if a given command it references is not available. I believe the issue itself might highlight some workarounds, or additional bindings to resolve the issue.

**Comment by nmaaiken** [comment]
@vince-fugnitto thanks you for the reference! I will use this workaround for now but I'd like to fix the underlying issue to get a more stable solution. Should i make a PR for this when I'm finished?

**Comment by vince-fugnitto** [comment]
> Should i make a PR for this when I'm finished?

@nmaaiken of course! If you're interested in resolving the issue please don't hesitate in contributing a pull-request :+1:
