### ISSUE TITLE
Add install LSP action and LSP installation status in the extension readme ?

### ISSUE THREAD

**Issue by hexa00** [eclipse-theia/theia#988]
For example for Java, I think we could externalize the gulp file so that the user runs it independently of the build for the extension.

The readme could provide a button that says like Install LSP. and this would trigger the gulp file ?

We should also have some kind of green/red status that shows the installation state of the LSP in there.

**Comment by svenefftinge** [comment]
Could you explain a bit more? The language server should be packaged with the extension. 
Whether an extension is using a language server or some other library is an implementation detail and should not be generally exposed to the user.

**Comment by hexa00** [comment]
@svenefftinge 

I don't think we can package the extension with the LSP direclty.

Take the example of clangd:

  - Using apt-get it depends on around 100MB of stuff (mostly llvm) but it's not a single binary
  - Installation of it vastly differs from OSX to linux and Windows
  - Installation also differs from one linux distro to another

I agree that the user should not have to worry about it as much as possible however so that's why I would recommend we package an installation script and make it actionable for the user to install this if the script matches his environnement.

**Comment by hexa00** [comment]
Note this is also the case for Java were the user needs to install java before being able to use the jar.

And installing java is very os specific. At the moment we don't check if that is installed or anything. 

So even if we were to package the java lsp we could have a status indicator that says that things are missing...

**Comment by hexa00** [comment]
For reference from an offline discussion suggested by @svenefftinge is to do this through the messaging like the go extension does.

I think it's a good idea.

**Comment by vince-fugnitto** [comment]
Closing as `@theia/java` is deprecated and removed.
