### ISSUE TITLE
Incorrect completion icon for snippets that come from LSP server

### ISSUE THREAD

**Issue by AirSeeker** [eclipse-theia/theia#9882]
### Bug Description:
After the update of Monaco in Theia 1.16.0, the icon for snippets that come from the LSP server is incorrect.
The icon for snippets that come from JSON configurations of plugins is correct.

Incorrect
![image](https://user-images.githubusercontent.com/585251/128985073-0fa5b9dc-99bc-48d4-a022-e9ef9f2a3723.png)

Correct icon
![image](https://user-images.githubusercontent.com/16229329/128985859-5c3808bc-3e7f-4093-b07c-4b7e5d1e0b6d.png)
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_builtin-snippets

Looks like in file packages/plugin-ext/src/common/plugin-api-rpc-model.ts:144 there missing two types
![image](https://user-images.githubusercontent.com/585251/128985649-35cd621a-6cd9-45bd-814f-0e31cf4717ea.png)
node_modules\@theia\monaco-editor-core\monaco.d.ts:5601
![image](https://user-images.githubusercontent.com/16229329/128986972-15a5d9bb-a163-466a-accb-2cb293559e78.png)

### Steps to Reproduce:

1. Remove all plugins except vscode-builtin-html and vscode-builtin-html-language-features
2. Run Theia and create an HTML file.
3. Hit CTRL + Space to trigger completion from the LSP server.

### Additional Information

- Operating System: Windows
- Theia Version: 1.16.0

**Comment by vince-fugnitto** [comment]
@AirSeeker thank you for reporting the issue, are you interested in contributing a pull-request to fix the icon?

**Comment by AirSeeker** [comment]
@vince-fugnitto Add PR #9908
