### ISSUE TITLE
[Plugins] Hosted mode status bar menu options not working

### ISSUE THREAD

**Issue by StanZGenchev** [eclipse-theia/theia#9891]
### Bug Description:

When I start "Hosted mode" in Theia, a small menu shows up in the status bar with a title such as "Hosted Plugin: Watching". When I click on this menu, two options are be presented:

- Restart Instance
- Stop Instance

Selecting either results in nothing happening in the UI but in the developer console I get the following error:

```javascript
Uncaught (in promise) TypeError: timers_1.setTimeout is not a function
    execute hosted-plugin-controller.ts:308
    node_modules bundle.js:7556
    node_modules bundle.js:19996
    node_modules bundle.js:20332
    node_modules bundle.js:20142
    node_modules bundle.js:20167
    node_modules bundle.js:27192
    invokeHandler index.js:436
    sendMessage index.js:172
    attach widget.js:915
    openRootMenu menu.js:1148
    node_modules bundle.js:20122
    showMenu hosted-plugin-controller.ts:298
    onclick hosted-plugin-controller.ts:166
    onClick status-bar.tsx:166
```

However, if I use the command palette to select "Hosted Plugin: Restart Instance" and "Hosted Plugin: Stop Instance", everything works as expected.
I have tested this in Theia 1.15 but I assume the issue is present in 1.16 as well but I cannot confirm because of issue #9871 

### Steps to Reproduce:

1. Start "hosted mode"
2. Go back to the regular instance on port 3000 and open the developer console
3. Click on "Hosted Plugin: Watching", in the left corner of the status bar
4. Select any option
5. See error

### Additional Information

- Operating System: macOS 11.5 / Fedora Linux 34
- Theia Version: 1.15.0
- Browser: Google Chrome 92 and Firefox 90

**Comment by vince-fugnitto** [comment]
@StanZGenchev it should be fixed on `1.16.0` and `master` thanks to https://github.com/eclipse-theia/theia/pull/9780.

**Comment by vince-fugnitto** [comment]
As for #9871, there is a pull-request under review to fix it if you'd like to review: https://github.com/eclipse-theia/theia/pull/9874.

**Comment by vince-fugnitto** [comment]
@StanZGenchev can you please retry with `master`? It should work correctly thanks to #9780.

**Comment by StanZGenchev** [comment]
I tested with the latest code from master and can confirm that the status bar menu now works as expected.
The issue can be closed.
