### ISSUE TITLE
Many `input` elements have spellcheck active.

### ISSUE THREAD

**Issue by colin-grant-work** [eclipse-theia/theia#9906]
### Bug Description:

A number of our input elements (search in workspace, preference search, preference string inputs, etc.) have spellcheck active. That leads to an annoying visible squiggle where none should appear.

### Steps to Reproduce:

1. Type some gibberish (or a camel-cased variable name :-) ) into one of the inputs named above.
2. Observe that you get a squiggle for bad spelling.

### Additional Information

- Operating System: RHEL 7
- Theia Version: `master`

**Comment by vince-fugnitto** [comment]
@colin-grant-work I believe it is a duplicate of https://github.com/eclipse-theia/theia/issues/6439.

**Comment by colin-grant-work** [comment]
Touche. Let's stick with the OP.
