### ISSUE TITLE
readme: update 'vscode-builtin-extensions' build badge

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9910]
#### Bug Description:

The goal is to update the **vscode-builtin-extensions** build badge in the `readme.md` to accurately report the status of the github actions workflow. The workflows are currently passing but the badge still reports failures:

- https://github.com/eclipse-theia/theia/blame/master/README.md#L14

It should be updated to:

```markdown
[![Publish VS Code Built-in Extensions](https://github.com/eclipse-theia/vscode-builtin-extensions/actions/workflows/publish-vsx-latest.yml/badge.svg?branch=master)](https://github.com/eclipse-theia/vscode-builtin-extensions/actions/workflows/publish-vsx-latest.yml)
```

**Comment by jim4067** [comment]
created a pull for this #9913
