### ISSUE TITLE
Option+Drag in Explorer does not copy file but moves it

### ISSUE THREAD

**Issue by cdamus** [eclipse-theia/theia#9922]
### Bug Description:

Drag-and-drop with the Option key on macOS should copy an object into the drop destination, not move it. But in the Explorer view of the Theia Blueprint, files are only moved, never copied.

### Steps to Reproduce:

1. In a workspace with multiple folders containing files, select some file in some folder.
2. Press and hold the Option key, then drag the selected file into another folder and drop it.
3. Release the Option key.

Expected result:

1. A copy of the dragged file is created in the destination folder.

Actual result:

1. The file is moved to the destination folder.
2. If it is some source file of a language that Theia understands, then a prompt may be shown to update imports etc. (this happens with TS/JS files).

### Additional Information

- Operating System: macOS Catalina 10.15.7 (19H15)
- Theia Version: Theia Blueprint Version 1.14.0 (1.14.0.17)

**Comment by marcdumais-work** [comment]
I have confirmed this issue and that same works in my native file explorer (Nautilus on Ubuntu), using Ctrl instead of Mac-speficic Cmd key.
