### ISSUE TITLE
Copy/paste not working within folder in Explorer

### ISSUE THREAD

**Issue by cdamus** [eclipse-theia/theia#9923]
### Bug Description:

Copying and pasting files within a single folder does not work in the Explorer. Neither Cmd+C and Cmd+V, nor Opt+Drag of the mouse will create a copy of a file in the same folder.

### Steps to Reproduce:

1. Select a file in some folder (call it `src`) in the Explorer view.
2. Copy the file with Cmd+C.
3. Attempt to paste into the same folder `src` with Cmd+V.

Expected result:

1. A new copy of the file is created with a distinct name. The usual pattern in macOS is that Xyz.ext is pasted as "Xyz copy.ext" or "Xyz copy 1.ext" if "Xyz copy.ext" already exists, etc.

Actual result:

1. A sequence of messages are shown in the status bar, too fleeting to read, and no new file is created.

The same occurs when trying to drag and drop the file using the mouse pointer with Option key modifier.

Note that pasting a copied file into a different folder than the original works (at least, it does if the destination folder doesn't already have a file with that name).

### Additional Information

- Operating System: macOS Catalina 10.15.7 (19H15)
- Theia Version: Theia Blueprint Version 1.14.0 (1.14.0.17)

**Comment by vince-fugnitto** [comment]
@cdamus can you confirm if the issue has been resolved for you when using `master`?

**Comment by cdamus** [comment]
Hi @vince-fugnitto Nope, neither the Cmd+C/Cmd+V nor the Opt+Drag scenario is resolved on the latest master branch (commit bca6eda5a46d485a98f9eec96a5ce7c45d9262c1). Tested in both the browser and Electron examples.

If I copy a file `foo.md` in a folder `stuff/` and paste it into some other folder, then I get a copy of the file pasted. And then if I paste again into that other folder, I get a file named `foo_copy.md` (it should be `foo copy.md` on Mac).

However, pasting into the folder `stuff/` that contains the original, nothing happens. I get neither `foo copy.md` nor `foo_copy.md`.

**Comment by vince-fugnitto** [comment]
@cdamus 

> I get a file named `foo_copy.md` (it should be `foo copy.md` on Mac).

I understand that vscode would produce `foo copy.md` for mac, but besides that and for my own understanding why is `foo_copy.md` incorrect?

> However, pasting into the folder `stuff/` that contains the original copied file, nothing happens. I get neither `foo copy.md` nor `foo_copy.md`.

I was unable to reproduce this problem, can you share detailed reproduction steps, and/or possibly a video?

**Comment by cdamus** [comment]
@vince-fugnitto 

> > I get a file named `foo_copy.md` (it should be `foo copy.md` on Mac).
> 
> I understand that vscode would produce `foo copy.md` for mac, but besides that and for my own understanding why is `foo_copy.md` incorrect?

Because Mac applications do not use underscores in this way, so Mac users don't expect to see them. In particular, the finder pastes `foo.md` into the folder containing the original `foo.md` as `foo 2.md`. Related operations in Finder and other applications sometimes produce `foo copy.md`.

> > However, pasting into the folder `stuff/` that contains the original copied file, nothing happens. I get neither `foo copy.md` nor `foo_copy.md`.
> 
> I was unable to reproduce this problem, can you share detailed reproduction steps, and/or possibly a video?

Perhaps it only happens on Mac? I build and run today's `master` branch with

```console
$ yarn
$ yarn electron build
$ yarn electron start
```

then I see that I cannot paste a copied file into the folder containing that file to duplicate it, but I can paste it into other folders. Also, the Mac standard Option-drag gesture with the mouse pointer doesn't create a copy, either. Worse (which is not shown in the recording below) is that Option-dragging a file into a different folder _moves_ the file rather than copying it, despite that the mouse cursor shows the correct copy action.

https://user-images.githubusercontent.com/1615558/139955908-d6668569-bf81-48d1-ac92-0c89c533f527.mp4

**Comment by AlexandraBuzila** [comment]
@vince-fugnitto Currently, the naming scheme in Theia for file duplicates is that `_copy` or `_copy_number` is appended to the name of the file, regardless of OS. Taking Christian's remarks about the naming scheme that Mac users expect into account, do we want to change the names of the files on macOS only, or would you agree to generally change the naming scheme that Theia uses for duplicates by replacing the `_` character with a space?

For reference, vscode always uses spaces. The file managers on Windows and Ubuntu (with Gnome) also use spaces.
