### ISSUE TITLE
Open editor in new window in Electron

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia#9926]
In VS Code there is no proper support for multiple screens like #526, but there is a simple workaround that seems useful to me. You  can by different means open an editor in another instance of VS Code, e.g. see [here](https://stackoverflow.com/questions/43362133/visual-studio-code-open-tab-in-new-window/43362800#43362800). The downside is that it will just open another (independent) instance of VS Code for opening the editor with the usual drawbacks (no real frontend state sync, double resource usage,...). But still this is much better than not having any support for multiple screens.
This issue is about implementing the following features:

- Allow DND of an editor from one window to another window: Will open the same file in the other window. Strongly related to #9543.
- Add command to open editor in new window: Will launch another instance and open the file of the editor.

This would make Theia as powerful as VS Code in terms of managing multiple screens.

**Comment by koegel** [comment]
@AlexandraBuzila intends to work on this issue. Also see #9543

**Comment by marcdumais-work** [comment]
> Add command to open editor in new window: Will launch another instance and open the file of the editor.

Momentarily, the file will stay open in the original window (until e.g. the user decides to close it). Until that happens, if the file is modified in one window,  changes will only be reflected in the other one(s) when saved to disk. This could hinder such use-cases as modifying a Markdown file in one window while rendering the same file in another window. This should work more seamlessly if `auto-save` is enabled. 

Would it make sense to have a "move editor in new window" flavor of this too, that would, in addition, close the original editor/file, after opening it in the new window? For the underlying DnD, it could work like a file navigator, that by default moves a dragged file but instead will copy it if `cmd`/`Ctrl` is pressed.

**Comment by koegel** [comment]
> > Add command to open editor in new window: Will launch another instance and open the file of the editor.
> 
> Momentarily, the file will stay open in the original window (until e.g. the user decides to close it). Until that happens, if the file is modified in one window, changes will only be reflected in the other one(s) when saved to disk. This could hinder such use-cases as modifying a Markdown file in one window while rendering the same file in another window. This should work more seamlessly if `auto-save` is enabled.
> 
> Would it make sense to have a "move editor in new window" flavor of this too, that would, in addition, close the original editor/file, after opening it in the new window? For the underlying DnD, it could work like a file navigator, that by default moves a dragged file but instead will copy it if `cmd`/`Ctrl` is pressed.
Good points, probably the default should be a move via DND unless a modifier is pressed. Maybe we could also prompt the user for enabling auto-save if it is a "copy".

**Comment by marcdumais-work** [comment]
> probably the default should be a move via DND unless a modifier is pressed. Maybe we could also prompt the user for enabling auto-save if it is a "copy".

+1
