### ISSUE TITLE
good-first-issue: update misc typos

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia#9939]
#### Bug Description:

The following typos should be fixed across the framework:

`rearraged` > `rearranged`

https://github.com/eclipse-theia/theia/blob/8492480b861ea6c40ca24077772fe7f2642b99fd/packages/navigator/src/browser/open-editors-widget/navigator-open-editors-tree-model.ts#L115

`ligth` > `light` 

https://github.com/eclipse-theia/theia/blob/8492480b861ea6c40ca24077772fe7f2642b99fd/examples/api-tests/src/monaco-api.spec.js#L137

`formating` > `formatting`

https://github.com/eclipse-theia/theia/blob/8492480b861ea6c40ca24077772fe7f2642b99fd/examples/api-tests/src/typescript.spec.js#L260

**Comment by RhnSharma** [comment]
I would like to take this one.
